### ISSUE TITLE
Empty error message on installation

### ISSUE THREAD

**Issue by ghost** [enso-org/enso#1000]
### General Summary

Empty error message shown in luna installer when I press "install"

### Steps to Reproduce

1. Download the latest release of the installer: http://packages.luna-lang.org/linux/lunaInstaller.zip
1. Unzip archive
1. Run installer `./lunaInstaller`
1. Leave email address field empty and press "continue"
1. Press "install"

### Expected Result

luna-studio is installed

### Actual Result

Empty error message occured:

![image](https://user-images.githubusercontent.com/50361928/87654897-d3570880-c757-11ea-856f-ea270cc59f1a.png)

### Enso Version

1.9

System info:

> Linux 4.19.0-9-amd64 #1 SMP Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

**Comment by ghost** [comment]
+ Changing the version of the `luna-studio` (1.9 on the screen) doesn't help.
+ I tried to set up `userInfoEmail` in `user_info.json` but it doesn't help as well.

**Comment by ghost** [comment]
```
{"userInfoUUID":"...","userInfoEmail":"","userInfoOsType":"Linux","userInfoOsDist":"Debian GNU/Linux","userInfoOsVer":"10 (buster)","userInfoArch":"X64"}
```

**Comment by joenash** [comment]
Hey @gram-eiq, 
Thanks for trying out Luna! We're not currently taking bug reports for Luna 1.9, as our next release is a complete rewrite on a fresh codebase. You can learn more about that in this edition of our devblog: https://medium.com/@enso_org/enso-dev-blog-19th-june-2020-335e528d50b


<blockquote><img src="https://miro.medium.com/freeze/max/1000/1*35kALPUkwLyNIEtAwwbRYA.gif" width="48" align="right"><div><img src="https://cdn-static-1.medium.com/_/fp/icons/favicon-rebrand-medium.3Y6xpZ-0FSdWDnPM3hSBIA.ico" height="14"> Medium</div><div><strong><a href="https://medium.com/@enso_org/enso-dev-blog-19th-june-2020-335e528d50b">Enso Dev Blog — 19th June 2020</a></strong></div><div>Welcome to the inaugural Enso devblog. In this series, we will share the latest updates from the development of Enso (formerly Luna), a…</div></blockquote>

**Comment by ghost** [comment]
But enso.org redirects to luna-lang.org! Where to download enso release?

**Comment by ghost** [comment]
The article points to https://dev.enso.org/docs/getting-enso.html#getting-enso which returns 404

<blockquote><img src="/gitbook/images/favicon.ico" width="48" align="right"><div><strong><a href="https://dev.enso.org/docs/getting-enso.html#getting-enso">Enso Developer Documentation</a></strong></div><div>The developer documentation for the Enso compiler, runtime, and IDE..
</div></blockquote>

**Comment by joenash** [comment]
@gram-eiq sorry, that link is broken because of a restructure we had of the devdocs, thanks for that catch, I'll get it fixed in the blog post. The correct link is https://dev.enso.org/docs/enso/getting-enso.html#getting-enso. Please note the warning in the blog post that Enso is currently pre-release, we're working hard to get a ready-to-use release out as soon as possible, but currently it's not at feature parity with Luna 1.9.

**Comment by ghost** [comment]
> The correct link is 

Great! Thank you :)

> Please note the warning in the blog post that Enso is currently pre-release

Sure, I know. I'm passively keeping track of the project since the first Luna releases, it never was really stable TBH (last time even examples in Luna didn't work) but still, it is cool. I'm happy that Luna finally moved from Atom. Atom is amazing but Luna over it was eating too much RAM.

**Comment by joenash** [comment]
Totally! That’s a big incentive for the rewrite. Thanks for sticking with us, interested in hearing what you think of the new direction.

**Comment by ghost** [comment]
How to install rust `1.40.0-nightly`? There is no `1.40.0-nightly` anymore, and it doesn't work with the latest release, latest nightly, 1.40.0, nor 1.41.0.

**Comment by ghost** [comment]
This is about IDE. For example, the error for 1.41.0:

![image](https://user-images.githubusercontent.com/50361928/87786844-fc03fe80-c83a-11ea-9bc9-088a56e201c3.png)

**Comment by iamrecursion** [comment]
`rustup toolchain install nightly-2019-11-04`. It's described in the IDE contributing docs.

**Comment by joenash** [comment]
@gram-eiq for reference https://dev.enso.org/docs/ide/CONTRIBUTING.html 

<blockquote><img src="/gitbook/images/favicon.ico" width="48" align="right"><div><strong><a href="https://dev.enso.org/docs/ide/CONTRIBUTING.html">Development & Contributing Guide · Enso Developer Documentation</a></strong></div><div>The developer documentation for the Enso compiler, runtime, and IDE..
</div></blockquote>
