### ISSUE TITLE
Compile Documentation Parser to ScalaJS

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/enso#1001]
### Summary
As currently doc parser is able to parse and generate code, we need to be able to use it in IDE, so it needs to be compiled to scalaJS, like the Enso Parser.

### Value
Doc Parser is useable

### Specification
Doc parser provides a function which parse a documentation string and returns a HTML-formatted string. The function should be exposed by scala-parser.js artifact.

### Acceptance Criteria & Test Cases
Doc Parser works as expected - it is integrated with IDE and there are tests in IDE showing that the integration works.

**Comment by farmaazon** [comment]
To close, please check how it integrates with IDE
