### ISSUE TITLE
Adding an unclosed literal breaks execution in the IDE

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10014]
Add a node with an unclosed literal, there will be an error displayed. After this you cannot recover.

![image](https://github.com/enso-org/enso/assets/4699705/72f5008e-cccb-47f6-ae42-13320ae0291b)

e.g. add `.blah "duff`

**Comment by hubertp** [comment]
Regression introduced in https://github.com/enso-org/enso/pull/8190

**Comment by hubertp** [comment]
I was partially wrong. #8190 prevents edits to the already broken source. But it really regressed in #9864 .
