### ISSUE TITLE
In some sessions, no suggestion database entries are provided for local methods

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#10021]
To reproduce:
1. Create a project with at least one local method, e.g. by grouping some components.
2. Open the component browser by pressing Enter.
3. Type `collapse` to narrow the suggestions to only methods created by grouping components.
4. Repeat steps 2-3: Sometimes the local methods are suggested, and sometimes they are not.

**Comment by kazcw** [comment]
Note: I have only tested this with a project-manager build from 2 May (142e11d).

**Comment by farmaazon** [comment]
Please test it on newest nightly. Probably it's a duplicate of https://github.com/enso-org/enso/issues/9962

**Comment by kazcw** [comment]
Seems to be fixed
