### ISSUE TITLE
Don't use `System.out.print` in `Standard.Test` - use `IO`!

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#10028]
To invoke `print` we have to include `java.io.PrintStream` in the list of classes needed for _reflective access_ - see https://github.com/enso-org/enso/pull/9997#discussion_r1606033800

If `print` (instead of `println`) is needed, we should expose it from `IO`. For example:
```
println text:Text nl='\n' = ...
```
which one could invoke as `IO.println nl="" "some text"`.

_Originally posted by @JaroslavTulach in https://github.com/enso-org/enso/pull/9997#discussion_r1606052292_

**Comment by GregoryTravis** [comment]
This will require a new builtin. @JaroslavTulach
