### ISSUE TITLE
Create a Stub AST

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1003]
### Summary
As the new Rust parser has to work from Scala and Rust, we need a way of constructing a Scala AST from inside the Rust code. This task deals with creating a small stub AST on which to base these experiments.

### Value
We have a small AST in Rust on which to base the experiments with the generation of Scala code via JNI. 

### Specification

- [x] Make the crate `lib/rust/ast`.
- [x] Examine the current structure of the [rust AST](https://github.com/enso-org/ide/tree/main/src/rust/ide/lib/ast).
- [x] Based on the core ideas of this AST, create a small stub AST. This should:
  - Ignore the deriving stuff for now.
  - Have some sensible nodes that are basic (like the current ones), but also some more complex (higher-level) nodes such as `MethodDefinition` and `OperatorDefintion`.
  - The specifics of these nodes don't matter, but try and make it realistic.

### Acceptance Criteria & Test Cases

- We have a small stub AST for use in experiments.

**Comment by farmaazon** [comment]
In IDE we already have implementation of Scala AST in rust, have you looked at it? https://github.com/enso-org/ide/blob/main/src/rust/ide/lib/ast/impl/src/lib.rs

**Comment by iamrecursion** [comment]
This isn't about that. This is for the new parser, so we need to stub it out to work on the codegen process. The existing AST is far too complex for now.
