### ISSUE TITLE
Vector benchmarks regression

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10046]
![Screenshot from 2024-05-23 11-34-13](https://github.com/enso-org/enso/assets/292128/9577d9b7-0ed2-4848-bb26-21c01a9e2f07)
![Screenshot from 2024-05-23 11-32-32](https://github.com/enso-org/enso/assets/292128/ba5c11e6-1a7d-4b06-85de-129717583522)

**Comment by hubertp** [comment]
Libs/compiler commits are
- 5c06535c46d2a20d9eef70af415575c34ddb3f78
- 4d49b003752e8771e95d5ae379ce953c85ef020c
- 3b29de313d1cac415b77802b80d012f7097b1ded

But I would bet my money on the 2nd one, @GregoryTravis

**Comment by Akirathan** [comment]
Looking into the #9922 I have a suspicion that the modification that cause the regression is in [VectorBenchmarks.java](https://github.com/enso-org/enso/commit/4d49b003752e8771e95d5ae379ce953c85ef020c#diff-c5490c0404827dc7f4488732bc1f117caa7867fae56d910e6c65325647ef406c), over there, @GregoryTravis changed `Vector.new_builder` to `Builder.new`.

Hint: Run one of the regressed benchmarks with:
```
sbt:runtime-benchmarks> run org.enso.interpreter.bench.benchmarks.semantic.VectorBenchmarks.averageOverSlice
```

**Comment by GregoryTravis** [comment]
Indeed, this regression is called by the new builder -- specifically, by the fact that we are collecting all warnings attached to values added to the builder.

Previously, warnings were sometimes propagated, if the caller remembered to use the `self` returned by `append` each time, often in a `fold` pattern. Always propagating all warnings, and not requiring the `fold` pattern, is clearly better, if the speed cost is acceptable. But is it?

Alternately, we could add a `collect_warnings=False` parameter to the builder, and disable it in cases where we don't want to pay the price.
