### ISSUE TITLE
Add new component button location incorrect

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10089]
When I press the + button to add a connected component. The component should be located at the location of the + button.

This should be true is the Viz is open or closed.

Actual:

![image](https://github.com/enso-org/enso/assets/1720119/95d7c4a5-1952-4390-9812-3f561871771d)

![image](https://github.com/enso-org/enso/assets/1720119/068e9767-c417-439d-9532-bc31f199b6d1)

**Comment by farmaazon** [comment]
We decided to allow node being pushed down a bit when source node's visualization is open; the gap there look nice, but having the same gap between vis and button would look bad. And to implement different gap when visualization is opened is tricky anyway; requires significant refactoring and makes problems in other areas, like dragging snapping.
