### ISSUE TITLE
Documentation panel removes all text when opened for the second time

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#10099]
Steps to reproduce:
- Create a new project
- Open documentation panel
- Type anything in the doc panel
- Close the doc panel
- Open the doc panel for the second time.
- **The doc panel is empty** but it should load the text that is already in the source.

[Screencast from 2024-05-27 18-01-58.webm](https://github.com/enso-org/enso/assets/14013887/cd182056-8bd3-4105-973b-79ffa660b772)

**Comment by Akirathan** [comment]
Cannot reproduce on [RC1](https://github.com/enso-org/enso/releases/tag/2024.1.1-nightly.2024.5.28).

**Comment by farmaazon** [comment]
Probably fixed by #10096
