### ISSUE TITLE
Lack of .env file leads to inconsistent authentication state

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10098]
I logged in once with email/password. Despite not having a cloud capability on my test account I was able to use it on local projects, as expected.
However, profile appears to be in a state suggesting that I'm not logged in:
![Screenshot from 2024-05-27 16-41-34](https://github.com/enso-org/enso/assets/292128/dfe9f9ab-7134-488f-903b-f4d025e0513e)

Additionally, clicking `Log in` reloads the page and does **nothing** other than some errors in the console:
![Screenshot from 2024-05-27 16-39-08](https://github.com/enso-org/enso/assets/292128/868c28d5-a85f-4e4d-b7e5-753a823415e6)

Finally, I can't log out because I'm not being considered as logged in.

**Comment by hubertp** [comment]
OK, I lacked `.env` file. Ideally that would be a bit more explicit. Maybe shouldn't even allow authenticating?

**Comment by somebody1234** [comment]
yeah. the original intention was to disallow authenticating without the `.env` file. it's possible that it was a regression - or else it was overlooked when implementing the original `.env` file PR

**Comment by MrFlashAccount** [comment]
I think we should throw an error if a developer didn't provide a `.env`. This should happen only during dev build.

**Comment by somebody1234** [comment]
i assume we still want dev *builds* to work without `.env`, just not `npm run dev`?

not sure what's the current decision on letting users build their own app without cloud support

**Comment by MrFlashAccount** [comment]
> not sure what's the current decision on letting users build their own app without cloud support

After we removed the ability to pass login by clicking "Continue without creating an account",  is it still an option?

**Comment by PabloBuchu** [comment]
It won't get you pass the login screen now. I am closing it now but @jdunkerley maybe we should discuss on `not sure what's the current decision on letting users build their own app without cloud support`
