### ISSUE TITLE
`ExpressionValueUpdate.methodCall` with argument names.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#1009]
### General Summary
Currently methodCall field in ExpressionValueUpdate contains only function name and on what type it's defined. I suspect it is also filled only for functions from the currently opened projects, because only these have the file path.

The requested change is to add the information about argument names and their types, and provide them also for functions imported from external libraries.

Perhaps the ExpressionValueUpdate could just return a SuggestionDatabaseEntry(Id).

### Motivation
In IDE we need to display argument names on nodes. The requested change will make our work much simpler.

In the current state we can only look through SuggestionDatabase and try to pick the functions with matched name, but this is tricky for same-named functions defined on different types, and we won't support cases where function is not a single-id expression. On the other hand I suspect Language Server has those information handy when executing code.

**Comment by 4e6** [comment]
I just realized that I completely misunderstood the issue and the current API is completely unusable for the IDE https://dev.enso.org/docs/enso/language-server/protocol-language-server.html#expressionvalueupdate

I'll revert the API to the previous state, changing the `methodPointer` field to contain the `SuggestionId`:

```typescript
type SuggestionId = number;

interface ExpressionValueUpdate {
  /** The id of updated expression */
  expressionId: ExpressionId;

  /** The updated type of the expression */
  type?: String;

  /** The updated pointer to the method call */
  methodPointer?: SuggestionId;
}
```

Also I would like to chanage the `MethodPointer` so it's not dependent on the file path path https://dev.enso.org/docs/enso/language-server/protocol-language-server.html#methodpointer


```typescript
interface MethodPointer {
  file: Path;
  definedOnType: String;
  name: String;
}
```

And replace the `file` path to the `module` fully qualified module name.

```typescript
interface MethodPointer {
  /** The fully qualified module name. */
  module: String;
  
  /** The type on which the method is defined. */
  definedOnType: String;
  
  /** The method name. */
  name: String;
}
```

<blockquote><img src="/gitbook/images/favicon.ico" width="48" align="right"><div><strong><a href="https://dev.enso.org/docs/enso/language-server/protocol-language-server.html#expressionvalueupdate">Enso Protocol Language Server Message Specification · Enso Developer Documentation</a></strong></div><div>The developer documentation for the Enso compiler, runtime, and IDE..
</div></blockquote>
<blockquote><img src="/gitbook/images/favicon.ico" width="48" align="right"><div><strong><a href="https://dev.enso.org/docs/enso/language-server/protocol-language-server.html#methodpointer">Enso Protocol Language Server Message Specification · Enso Developer Documentation</a></strong></div><div>The developer documentation for the Enso compiler, runtime, and IDE..
</div></blockquote>

**Comment by farmaazon** [comment]
Those changes looks good to us.
