### ISSUE TITLE
Drop down widgets shouldn't wrap text

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10091]
![image](https://github.com/enso-org/enso/assets/1720119/03fd16fd-51b0-46af-a01a-8d1a0214b5a1)

![image](https://github.com/enso-org/enso/assets/1720119/b0e896d4-c08b-475c-9bda-d99831c1969b)

**Comment by farmaazon** [comment]
We may both:
* Extend the drop-down to fit all values in a single line (what with lazy loading, however?)
* and add ellipsis if the label sent by libraries is absurdly long.
