### ISSUE TITLE
Can't authenticate with Google account

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10100]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Downloaded latest nightly and tried to authenticate with a Google account. Blank screen and errors in the console.

### Expected behaviour

Google authentication should work, if it is allowed.

### Screenshots or screencasts

![Screenshot from 2024-05-27 18-08-46](https://github.com/enso-org/enso/assets/292128/418ec578-4f40-4744-9903-78a72009e5a7)

Console logs (redacted sensitive data):
```
[INFO] [2024-05-27T18:03:01.679] [org.enso.projectmanager.boot.ProjectManager$] Started server at 127.0.0.1:30535, press enter to kill server
Done in 1716.2 ms.

(node:2108272) electron: Failed to load URL: http://localhost:8080/?code=xxx&state=xxx with error: ERR_EMPTY_RESPONSE
(Use `enso --trace-warnings ...` to show where the warning was created)
[2108272:0527/180343.287717:ERROR:CONSOLE(1)] "Request Network.loadNetworkResource failed. {"code":-32602,"message":"Unsupported URL scheme"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
(node:2108272) electron: Failed to load URL: http://localhost:8080/?code=xxx with error: ERR_EMPTY_RESPONSE
[2108272:0527/180407.428234:ERROR:CONSOLE(1)] "Request Network.loadNetworkResource failed. {"code":-32602,"message":"Unsupported URL scheme"}", source: devtools://devtools/bundled/core/protocol_client/protocol_client.js (1)
```

### Enso Version

2024.5.27 nightly AppImage

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by MrFlashAccount** [comment]
@hubertp could you please try once again? We did a bunch of fixes around Login/Sign up/Logout flow and hope that these problems are fixed for now.

Also please check that you don't have a `ENSO_CLOUD_REDIRECT` env variable (If you have one, please remove)
