### ISSUE TITLE
Provide engine-runner & language-server as a separate JPMS modules

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#10157]
## Current suboptimal module architecture
`runner.jar` is currently a fat plain jar (no a JPMS module) located in `built-distribution/component/runner/runner.jar`. System module-path is set to `built-distribution/component`. `runner.jar` contains all the classes from language-server and their dependencies. It does not contain classes that are on module-path. The original motivation, implemented in https://github.com/enso-org/enso/pull/7991, was to make the transition to JPMS as quick and as simple as possible. The idea is roughly as follows:
- Entry point is in `org.enso.runtime` module in `EngineRunnerBootLoader` class.
- This class creates an `IsolatedClassLoader` that either loads classes from `runner.jar`, or delegates to system class loader.
  - Delegation to system class loader is decided based on [ClassLoaderConstants.CLASS_DELEGATION_PATTERNS](https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/java/org/enso/ClassLoaderConstants.java#L15)
- system class loader loads classes from module-path. `IsolatedClassLoader` loads classes from `runner.jar`, that is not on the module-path.

This design, however, lead to many ugly hacks:
- A custom [IsolatedClassLoader](https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/java/org/enso/EngineRunnerBootLoader.java#L60)
- Defining unnecessary dependencies in [runtime's module-info](https://github.com/enso-org/enso/blob/develop/engine/runtime-fat-jar/src/main/java/module-info.java)
  - Some of these dependencies are, in fact, needed only by `runner.jar`, like all the helidon modules. But we need to put them inside runtime's module-info so that the system class loader can lookup classes from these modules.

## Better module architecture
- `runner.jar` should be a modular jar that is on the system's module-path.
- There should be no need for `IsolatedClassLoader`.
```[tasklist]
### Tasks
- [ ] language-server is separate JPMS module
```

**Comment by JaroslavTulach** [comment]
Related:
- #10010
- #7082

> `runner.jar` should be a modular jar that is on the system's module-path.

Rather than that `runner.jar` (or rather just the _language server JAR_) should be a module JAR in `Standard/Visualization/polyglot/java` module, loaded by its own `ModuleLayer` which automatically delegates to (mostly empty `ModuleLayer` representing the JDK - e.g. `java.base` but no Truffle APIs or language implementations, etc.).

**Comment by JaroslavTulach** [comment]
> * add `requires scala.library` to the module descriptor.

Adding a dependency on Scala core library sounds like the correct fix.
