### ISSUE TITLE
Opening a ensoproject file bug

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10169]
- Double clicking on an ensoproject file should open in the current session if it exists.
- Errors on mac currently.

**Comment by kazcw** [comment]
When I open a .enso-project file on Mac I'm getting an error whether or not there's a current session--the new project shows up in the dashboard along with a toast saying that it (as a UUID) couldn't be opened. There may be a problem with my installation. @AdRiley This is different from the error you're seeing, right?

**Comment by AdRiley** [comment]
Someone else reported the mac issue. But just tested it on my mac and I am getting the same as you. If enso is closed it opens enso, but has a toast with an error. If enso is open then I get a second instance of enso which strangely isn't logged in.

**Comment by kazcw** [comment]
Ok. I opened a separate issue for failing to open the imported project (#10282), which is either a dashboard or project manager bug.
