### ISSUE TITLE
Add hand to drag cursor (part 2)

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10166]
Red zone: 
- Hover: Open hand
- Mouse down: Closed hand

Blue zone:
- Hover: Click hand (as today, but zone is bigger)

Green zone:
- Hover: Text edit cursor

Unshaded:
- Keep existing behaviour

![image](https://github.com/enso-org/enso/assets/1720119/a96d58e2-7606-4009-91ab-815def37090f)

![image](https://github.com/enso-org/enso/assets/1720119/60907e98-3bd5-4d86-a1e9-1fb05543b6c8)

![image](https://github.com/enso-org/enso/assets/1720119/958275af-4a06-4c99-b6b7-bfa48038e125)

**Comment by farmaazon** [comment]
Refinement notes:
* The extending of blue zone is already implemented as part of #9830 
* To avoid cursor blinking, let's keep hand only over the halo and icon.
