### ISSUE TITLE
Parsing import with no target leads to internal parser error

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#1016]
### General Summary
As in title.

### Steps to Reproduce
Parse the following program:
```
import
```

### Expected Result
A single line with Macro Match node matching the `import` macro.

### Actual Result
parsing fails altogether with `java.lang.Error: Internal error: template pattern segment was unmatched` error being reported

### Enso Version
2801f58ba9bc70b7b82e5a57f4e8b1796b509477

**Comment by mwu-tow** [comment]
most likely regression from https://github.com/enso-org/enso/commit/2f404b7f08faf9f46afc0cfde8ae8967598ea0aa

**Comment by iamrecursion** [comment]
This is a known bug that will not be present in the new parser.
