### ISSUE TITLE
Cloud Integrated File Browser Widget

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10167]
Data.read has a open from cloud drive option - which gives a similar experience to the cloud drive view allowing you to pick a cloud file and insert it.

![image](https://github.com/enso-org/enso/assets/1720119/82b127f6-13ef-45ce-a026-aa0df61df9cb)

**Comment by farmaazon** [comment]
REfinement notes:
* Should be designed and refined with cloud team.

**Comment by PabloBuchu** [comment]
Oh wow.. its much more rich than I thought we want to build. Its basically a mini cloud dashboard preview.. Questions:
1. I assume drag n drop functionalities (like assigning labels, moving assets) should be disabled? I see "create new label" is this necessary?  
2. Do we need all columns? like share with or the buttons that toggle other types?
3. Do we need trash/recent/drafts/bookmarks?
4. Do we need upload /download / create datalink?
5. Whats read a local file?

If the main reason for file browser is to allow user for searching through the files then maybe its too much?

**Comment by AdRiley** [comment]
Yes sorry. That is a bad screenshot, but was all I had.

You are right it should be very simple file browser/picker.

**Comment by PabloBuchu** [comment]
Thanks! I just wanted make sure :)

**Comment by farmaazon** [comment]
Refinement notes
* Let's start with having this as Vue component
* Cloud uses TanStack query https://tanstack.com/query/latest/docs/framework/react/typescript#typing-query-options for cloud API; we could use the same library (it has the Vue API), but make sure we're using the same cache (talk with @MrFlashAccount)
    * It seems they're in the process of refactoring - work closely with dashboard team.
* The projects may be hidden or treated as directories, depending on what's easier to implement.
* The missing dashboard icons shall be ported to figma design.

<blockquote><img src="https://github.com/tanstack/query/raw/main/media/repo-header.png" width="48" align="right"><div><strong><a href="https://tanstack.com/query/latest/docs/framework/react/typescript#typing-query-options">TypeScript | TanStack Query React Docs</a></strong></div><div>
React Query is now written in TypeScript to make sure the library and your projects are type-safe!

Things to keep in mind:</div></blockquote>

**Comment by farmaazon** [comment]
Split off the first part about shared library to #10400
