### ISSUE TITLE
The project name is always accepted, regardless which button I click.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#10184]
### Discord username

farmaazon

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I start changing project's name and click (x), the name seems to be accepted.

### Expected behaviour

I expect (x) icon to be something for discarding current edit.

### Screenshots or screencasts

[Screencast from 2024-06-05 13-24-12.webm](https://github.com/enso-org/enso/assets/3919101/3fd063e4-6187-4d89-ac66-827494167679)

### Enso Version

Version 2024.1.1-rc.2 Build c0612dbd858e7491faebc59c4b1747062692de64 Electron 25.7.0 Chrome 114.0.5735.289 User Agent Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.1.1-rc.2 Chrome/114.0.5735.289 Electron/25.7.0 Safari/537.36

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standaolne

### Operating System

Linux

### Operating System Version

Garuda

**Comment by MrFlashAccount** [comment]
@somebody1234 I guess it's due to optimistic updates, right?

**Comment by somebody1234** [comment]
@MrFlashAccount no, because optimistic updates only happen when sending a request to the backend - and when canceling, of course no backend request is sent.

it may be a race condition or focus issue causing the "submit" action to be triggered instead of the "cancel" action (note that clicking away from the asset counts as accepting the rename)
