### ISSUE TITLE
Stopping a (local) project results in a crash

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10189]
Clicked stop button to close a project which resulted in an unexpected crash.
Stacktrace included in the screenshot.
![Screenshot from 2024-06-05 17-55-51](https://github.com/enso-org/enso/assets/292128/85b92b97-0949-472b-84e0-9c22a861a085)

**Comment by hubertp** [comment]
![Screenshot from 2024-06-05 17-58-12](https://github.com/enso-org/enso/assets/292128/9dfb7ff7-ee2f-400f-a6bc-614d2b1fb732)
Maybe useful as well.

**Comment by somebody1234** [comment]
@hubertp is this still an issue? (or perhaps it's inconsistently reproucible?)
