### ISSUE TITLE
Filter component's drop down bugs

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#10185]
First, one could see two arrows at once:
![Screenshot from 2024-06-05 13-31-57](https://github.com/enso-org/enso/assets/3919101/cd3f460e-cb9c-4c61-aabf-17f5a7e49fa0)

Then, once a number value is picked, it cannot be changed to anything else using drop down; the code does not change.

![Screenshot from 2024-06-05 13-35-50](https://github.com/enso-org/enso/assets/3919101/45adc9b7-4f83-4d80-b6b1-829538e9c1ac)

**Comment by farmaazon** [comment]
Another example of double arrow:

![image](https://github.com/enso-org/enso/assets/1720119/a39f01d7-f656-45b9-bd76-8d683e40ad72)

**Comment by hubertp** [comment]
Another one
![Screenshot from 2024-06-11 16-08-06](https://github.com/enso-org/enso/assets/292128/f605b8e0-f0bd-4aca-95a5-1a6c9e5f2c27)

**Comment by hubertp** [comment]
Another case with file browser
![Screenshot from 2024-06-11 16-08-06](https://github.com/enso-org/enso/assets/292128/cb2d6a26-47a8-4cc2-b678-121de03847d3)
