### ISSUE TITLE
Output port interaction hint

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10195]
When the mouse is close to the output port (less or equal to 16 px), a visual indicator is shown that clicking will create a new connection. The indicator should “grow” out of the output port (there should be an animation of it growing to the mouse and shrinking when mouse is too far). Please note that this indicator’s color is dull and it becomes vivid after user clicks:

![image](https://github.com/enso-org/enso/assets/1720119/6faa219a-1642-4ebf-ba6a-283f79f8bf82)

![image](https://github.com/enso-org/enso/assets/1720119/2b35da83-e462-4887-9c10-ea14040b0e3c)

**Comment by farmaazon** [comment]
Refinement notes:
* This should be a third type of "artificial" edge, next to actually dragged edge and edge to CB.
* For animation, we could use the existing "split edge" we have for existing edge highlighting.
