### ISSUE TITLE
Update background colors to match latest Figma

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10232]
- Update the graph editor background color to match the latest Figma design
- Update the workflow level doc panel background to match Figma (I think it is plain white and not transparent)

https://www.figma.com/design/2gwEXyEz9ybDkGn1NboFQo/ide2-v124?node-id=15504-63814&t=BKiwSmIQbYISEGqH-1

**Comment by kazcw** [comment]
> * Update the graph editor background color to match the latest Figma design

I identified the change necessary for this, but it's in the dashboard and I don't know their styling system, so I wrote it up as a dashboard ticket: #10393

**Comment by somebody1234** [comment]
note that when the dashboard right panel was implemented, it was brought up that the white might be *too* bright compared to everything else. perhaps `rgb(255 255 255 / 70%)` is a reasonable compromise?
