### ISSUE TITLE
Only Allow Node Adding Gets For JS_Objects in the JSON viz

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10246]
Alter the JSON Viz, so that we say whether `get` click through should be enabled in the Libs code.

And then only add the click through support if supported (JS_Object)

**Comment by farmaazon** [comment]
See also discussion at https://github.com/enso-org/enso/issues/9606 - there is a more general solution discussed, where objects may specify how to get an element (by default it could be `.to_json.get` but JS_Object may specify only `.get`, and then we may add more specific cases like exact getters of datetime fields etc).

**Comment by farmaazon** [comment]
I chatted with @jdunkerley, and he wants to avoid `to_json` conversion. But still it's worth leaving an option to allow more cases than JS_Object (like mentioned DateTime, or array of JS_Objects).
