### ISSUE TITLE
Change the default location for Enso project on Mac and Windows

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10240]
Should be `My Documents/enso-projects` (or `Documents/enso-projects` on Mac.

However, if the user already has the current structure we should move it to the new location.

If starting enso on a complete pristine machine (i.e. no folder) it should be created and not crash!

**Comment by hubertp** [comment]
One minor thing: please verify the correct permissions on folders. Should be `u+rw`

**Comment by 4e6** [comment]
After some consideration, I think we don't need to manipulate permissions because the root user catalog already has it correct
```
$ ls -l /home
total 20
drwx------ 60 dbushev dbushev 20480 Jun 19 11:00 dbushev/
```
Not sure about Windows though, but I would be surprised if it is different.
