### ISSUE TITLE
Hidden files shown on MacOS in Local Drive

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10261]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

.DS_Store files are visible in Local Drive

### Expected behaviour

They should not be visible

### Screenshots or screencasts

![image](https://github.com/enso-org/enso/assets/1720119/3e830a45-e64a-4179-af25-4373176bf2b6)

### Enso Version

Version 2024.1.1 Build 323d540676f1735d1f3147d506b7fec204e97052 Electron 25.7.0 Chrome 114.0.5735.289 User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.1.1 Chrome/114.0.5735.289 Electron/25.7.0 Safari/537.36

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by PabloBuchu** [comment]
Closing as it seems fixed
