### ISSUE TITLE
Cannot use local projects if no Cloud plan is enabled

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#10279]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I log in into an account that does not have an enabled Cloud plan, I get the following screen:
![image](https://github.com/enso-org/enso/assets/1436948/9ff76ebc-ebda-470b-82dd-4ec880874b0d)

There is no way to switch to the Local mode - so I cannot use Enso at all.

### Expected behaviour

I should be able to use the Free tier of Enso locally.

### How we can reproduce it?

I've got this issue on this CI build: https://github.com/enso-org/enso/actions/runs/9487658469

### Enso Version

d6d3709 / 2024.2.1-nightly.2024.6.13

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by somebody1234** [comment]
woops, the above standup was for the 13th
