### ISSUE TITLE
Initial Cloud drive integration

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10277]
In the Data.Read component file drop down. For cloud projects we should also list files that are in the same folder as the current project.

![Image](https://github.com/enso-org/enso/assets/1720119/9b809d71-49f9-4ef5-a2ee-9fcc89942d48)

![Image](https://github.com/enso-org/enso/assets/1720119/7b2edc3c-ebd3-495a-ad49-ca83c3a6d073)

**Comment by farmaazon** [comment]
Refinement notes:
* How could we access this file? Both in the GUI code and Enso code? 
  * If Enso code can access files, we could just receive it as dynamic widget configuration. In that case, it's more libraries' task.

**Comment by farmaazon** [comment]
I think we may close it in favor of #10167
