### ISSUE TITLE
 Ability to copy and paste data from the grid (and other spreadsheet tools)

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10275]

**Comment by farmaazon** [comment]
Refinement notes:
* Copying from external tools to graph: (Excel, google sheet) - some implementation is there, make sure it works for all tools. We may ask James for samples of clipboard contents using https://evercoder.github.io/clipboard-inspector/ and put them in unit tests.
* Copying from AgGrid to external tools: Works (for Google sheets at least).
* Copying from AgGrid to Graph editor should also work.

<blockquote><div><strong><a href="https://evercoder.github.io/clipboard-inspector/">Clipboard Inspector</a></strong></div><div>Explore the content of your clipboard</div></blockquote>

**Comment by kazcw** [comment]
Clipboard sampling procedure:
- Copy a 2x2 range of a spreadsheet in the source application
- In Chrome/Chromium, go to `https://evercoder.github.io/clipboard-inspector/`
- Paste into the page with the keyboard (not the button on the page)
- In the resulting type/getData(type) table, click "Copy as plain text" in the `text/html` row.
