### ISSUE TITLE
Documentation Site link from the CB's Doc Panel

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10276]
- Inside the CB help panel there should be a link to the corresponding website help page in an external; browser e.g.  https://help.enso.org/docs/api/Standard.Table/Table/join

- If a single component is selected on the Graph editor pressing F1 should open the corresponding help page in an external; browser

**Comment by farmaazon** [comment]
Refinement notes:
* Let circular menu has an icon opening docs like pressing F1 (displayed only if we can show the docs)
* It should only work for Standard namespace.
* The paths in URL are "physical" paths. The first segment is full project name (with namespace and dot).
