### ISSUE TITLE
Vue console warning when visualizing simple text length

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10289]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Seeing a rather obscure warning when visualizing `.length` of some `Text`:
![Screenshot from 2024-06-14 16-01-41](https://github.com/enso-org/enso/assets/292128/a391b3dc-ed76-4fbd-a82b-3de627e4e33b)

### Expected behaviour

No warning/stacktrace

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

 125.0.6422.112

### Operating System

Linux

**Comment by farmaazon** [comment]
Looks like bug in Table visualization, which expects quite specific format.

**Comment by kazcw** [comment]
I think we have a concurrency bug when changing visualizations--we should ensure that the visualization data from the previous preprocessor isn't delivered to the new visualization.

**Comment by farmaazon** [comment]
Seems to be fixed now. Probably by #11494
