### ISSUE TITLE
Table Input Component

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10293]
Add the ability to create and add a table literal.
Should be editable within an ag-grid editor.
Ability to copy/paste data into the editor.

The value type should auto typed in the same way as we read CSV (i.e. ISO date/time formats and numbers in conventional form).
```[tasklist]
### Tasks
- [ ] #10484
- [ ] Create AGGrid there with editing.
```

**Comment by farmaazon** [comment]
* The widget should match only the very specific `Table.new` calls (containing only proper lists with constants)
* For now, let's hardcode call to Standard's `Table.new`. The designing a general way of defining such widgets spawning over entire call is a future task.
* Let's see if AGGrid supports copypasting by default; if not, move it to a separate task.
* The cells and columns should know their link with specific AST nodes, so any edit will make minimal change in the AST.
