### ISSUE TITLE
Ydoc server is missing healthcheck endpoints

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10299]
ydoc is started as part of backend but it is (currently) not supervised.
There is currently no way to decided the status of it.

**Comment by JaroslavTulach** [comment]
Helidon project provides easy to turn on [support for health checks](https://helidon.io/docs/v2/se/health/01_health).

**Comment by hubertp** [comment]
NodeJS-based Ydoc has `/_health` endpoint responding with `OK`: https://github.com/enso-org/enso/blob/develop/app/ydoc-server-nodejs/src/main.ts#L19

<blockquote><img src="https://opengraph.githubassets.com/3135ef4447b0b296f30e30090d72e73111399fe6bc818d7f381efeb18efac6d3/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/blob/develop/app/ydoc-server-nodejs/src/main.ts">enso/app/ydoc-server-nodejs/src/main.ts at develop · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
