### ISSUE TITLE
Include `ENSO_CLOUD_PROJECT_SESSION_ID` in DB audit logs

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#10301]
Once Cloud deploys the added `ENSO_CLOUD_PROJECT_SESSION_ID` environment variable, it is suggested that we include it in the audit logs.

**Comment by radeusgd** [comment]
On hold until the change is deployed in Cloud.

**Comment by PabloBuchu** [comment]
Deployed. You can improve on your side

**Comment by radeusgd** [comment]
Done in #10303
