### ISSUE TITLE
"search/getSuggestionsDatabase" times out

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#1032]
## General Summary

On behalf of @farmaazon Who Don't Have Access to Github Again:

Sometimes, the getSuggestionDatabase request times out.

This causes https://github.com/enso-org/ide/issues/688 to happen in the IDE.

## Steps To Reproduce

* run project-manager, 
* open project
* initializes json connection
* obtains the Suggestion Database

## Actual Result 

Sometimes the last request times out, usually the first time after you run project manager (after closing and reopening project couple of times without stopping PM it starts to work smoothly).

Websocket log:
```
{"jsonrpc":"2.0","id":0,"method":"session/initProtocolConnection","params":{"clientId":"04100916-8515-41a2-ab80-f98feb4f81f2"}} | 127 | 14:51:58.502
{"jsonrpc":"2.0","id":0,"result":{"contentRoots":["6a9df029-c3e2-4526-a374-de4224cd875a"]}} | 91 | 14:51:58.504
{"jsonrpc":"2.0","id":1,"method":"search/getSuggestionsDatabase","params":{}} | 77 | 14:51:58.536
{"jsonrpc":"2.0","id":1,"error":{"code":1,"message":"Service error"}} | 69 | 14:52:08.556
```

Engine log (tail):
```
14:51:58.426 INFO  [pool-1-thread-12] o.e.l.boot.LanguageServerComponent   Starting Language Server...
14:51:58.426 INFO  [pool-1-thread-10] o.e.p.i.l.LanguageServerBootLoader   Found sockets for the language server [json:127.0.0.1:57145, binary:127.0.0.1:50942]
14:51:58.431 INFO  [pool-1-thread-16] akka.event.slf4j.Slf4jLogger         Slf4jLogger started
14:51:58.436 INFO  [pool-1-thread-12] com.zaxxer.hikari.HikariDataSource   searcher.db - Starting...
14:51:58.436 INFO  [pool-1-thread-12] com.zaxxer.hikari.HikariDataSource   searcher.db - Start completed.
14:51:58.438 INFO  [pool-1-thread-1] o.e.l.runtime.RuntimeConnector       Engine connection established.
14:51:58.452 DEBUG [pool-1-thread-6] o.e.l.boot.LanguageServerComponent   Main module initialized
14:51:58.458 DEBUG [pool-1-thread-2] o.e.l.boot.LanguageServerComponent   Json RPC server initialized
14:51:58.459 DEBUG [pool-1-thread-5] o.e.l.boot.LanguageServerComponent   Binary server initialized
14:51:58.460 INFO  [pool-1-thread-5] o.e.l.boot.LanguageServerComponent   Started server at json:127.0.0.1:57145, binary:127.0.0.1:50942
14:51:58.460 INFO  [pool-1-thread-13] o.e.p.i.l.LanguageServerBootLoader   Language server booted [LanguageServerConfig(127.0.0.1,57145,50942,6a9df029-c3e2-4526-a374-de4224cd875a,C:\Users\mwu\enso\projects\Unnamed,language-server-402ffc9d-a7be-436e-bbc2-d21a37da5326,Dispatcher[akka.actor.default-dispatcher])].
14:51:58.503 INFO  [pool-1-thread-10] o.e.l.p.j.JsonConnectionController   RPC session initialized for client: 04100916-8515-41a2-ab80-f98feb4f81f2
14:51:58.521 INFO  [pool-1-thread-14] o.e.l.p.b.BinaryConnectionController Data session initialized for client: 04100916-8515-41a2-ab80-f98feb4f81f2 [127.0.0.1:50955]
14:52:08.556 ERROR [pool-1-thread-10] o.e.l.r.s.GetSuggestionsDatabaseHandler Request Number(1) timed out
```

## Expected Result

The request finishes each time.

## Enso Version

Spotted on commit 61b285f182f33459439135928ea0acc3958b2c10
Seems to be introduced by 45d75536aae2d549d1a83e7a2ee13c22512d1f72

**Comment by mwu-tow** [comment]
This is not fixed, still hapenning to me as of latest `main` (60d0c2ae45f313d33689ce429c2df71130bd6e0b).
This reproduces quite reliably when I start IDE after deleting the `Unnamed` project. ~~Then IDE creates a new project and~~ this seems to trigger the issue.

**Comment by mwu-tow** [comment]
Nah, this actually might be the same as #1110.
Deleting project is not really observed by the project manager, so it ends up opening (not creating) the deleted project. Language Server then fails to provide the suggestion database.
Anyway, LS should somehow more gracefully handle being spawn for a project that does not exist anymore.

**Comment by iamrecursion** [comment]
@mwu-tow Does this still occur?

**Comment by mwu-tow** [comment]
@iamrecursion I don't remember seeing this recently.

**Comment by iamrecursion** [comment]
Please re-open this if the issue is seen again.
