### ISSUE TITLE
Delimiter dropdown broken on data.read

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10341]
Got broken between the Version 2024.2.1-nightly.2024.6.18
and  Version 2024.2.1-nightly.2024.6.19 builds

Expected:

![image](https://github.com/enso-org/enso/assets/1720119/622e7475-9179-44b7-b2ea-eff45f3e7313)

Actual:
No dropdown

![image](https://github.com/enso-org/enso/assets/1720119/1bffec0d-75a2-43cc-ade9-c4276da357d3)

**Comment by JaroslavTulach** [comment]
git log 2024.2.1-nightly.2024.6.18...2024.2.1-nightly.2024.6.19
 
> commit 7eeea8e1c8feb1b8e2acff0dc81e59d549daa771 (tag: 2024.2.1-nightly.2024.6.19)
> Author: Adam Obuchowicz <adam.obuchowicz@enso.org>
> Date:   Tue Jun 18 16:35:10 2024 +0200
> 
> Fix autoscoped constructor dynamic widget config (#10297)
> Fixes #10238
> 
> commit a8358512ad058323e4fda68f5bbaaf79fbaf65d2
> Author: Radosław Waśko <radoslaw.wasko@enso.org>
> Small fixes to Cloud Integration
>     
> commit 0fc3755d1b8d95b90dd84fc0e1018fdae05e9d11
> Author: marthasharkey <martha_king@hotmail.co.uk>
> Date:   Tue Jun 18 09:27:20 2024 +0100
> 
> Disable clickThrough for get nodes for anything thats datatype is not JS_Object
