### ISSUE TITLE
Fail to open the project when pressing New Empty Project button

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#10354]
## Issue

When pressing the `New Empty Project` button on the dashboard, the error is displayed and the project is not opened:

https://github.com/enso-org/enso/assets/357683/41e4fd75-3469-493b-a73b-53cd08adeadb

I tracked the issue to the #10256 commit. It is the first comit that shows this behavior.

**Comment by somebody1234** [comment]
- Does #10351 fix it?

**Comment by jdunkerley** [comment]
Seems to be fixed on mine on today's build so think the above PR fixed it.
