### ISSUE TITLE
On startup stuck on empty screen

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10361]
![image](https://github.com/enso-org/enso/assets/1720119/5b16590f-9037-43b1-91fe-98aed1da2bdd)

Clicking on data catalog fixes things. And then not reproducible.

**Comment by somebody1234** [comment]
@AdRiley seems like the image failed to upload

**Comment by somebody1234** [comment]
dunno if this one is reproducible unfortunately.
it *may* be caused by an invalid project being stored... i guess i'll try to manually set an invalid project to try and repro

**Comment by sylwiabr** [comment]
please reopen if this happen again
