### ISSUE TITLE
The "local" page in dashboard is stuck on loading when there's no `enso-projects` in my home dir.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#10387]
### Discord username

farmaazon

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The "local" page in dashboard is stuck on loading when there's no `enso-projects` in my home dir. Also, I cannot create any new projects.

### Expected behaviour

The needed directories are (re) created.

### How we can reproduce it?

remove `enso-projects` and run application.

### Screenshots or screencasts

![image](https://github.com/enso-org/enso/assets/3919101/23a524cb-c98d-4954-b266-d4c1f26bd57b)

![image](https://github.com/enso-org/enso/assets/3919101/9cca28b8-229d-487e-8a9a-7b679fc01216)

### Enso Version

 Version	2024.2.1-dev Build	88eeacf78bc5461ac9d0440f21f0c531c48756cb Electron	25.7.0 Chrome	114.0.5735.289 User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.2.1-dev Chrome/114.0.5735.289 Electron/25.7.0 Safari/537.36

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

Garuda

**Comment by somebody1234** [comment]
i guess this is a task for @4e6? not quite sure might be going wrong with the migration from the old folder to the new one

**Comment by somebody1234** [comment]
@farmaazon can you confirm whether this is fixed by the PR linked above?

**Comment by farmaazon** [comment]
Seems to be fixed.
