### ISSUE TITLE
Record/Record Once button updates

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10388]
Old

<img width="99" alt="image" src="https://github.com/enso-org/enso/assets/1720119/aa52a09f-05e9-4446-9b8e-c3909c5e099b">

New

![image](https://github.com/enso-org/enso/assets/1720119/c3b5c71f-66cb-48e5-b5a1-d4c0eed5e2f8)

Icons: refresh and workflow_play

Notes
- Record button is removed
- Replaced with a refresh inputs button which does a refresh of all input components data
- Record once is renamed to Run Workflow

Additional request : Can we move the control to the right of the navigation control please?

**Comment by farmaazon** [comment]
Refinement notes:
* On this occasion, let's remove initial `setExecutionContext(dev)`, because it's ~~probably~~ not necessary ~~(confirm with @hubertp)~~ confirmed.

**Comment by AdRiley** [comment]
Additional request : Can we move the control to the right of the navigation control please?
