### ISSUE TITLE
No `executionContext/expressionValuesComputed` notification emitted for patterns

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#1038]
### General Summary
The `executionContext/expressionValuesComputed` is not emitted for node patterns.

### Steps to Reproduce
Open the following in the IDE:
```
Main.mulAdd = 5

main =
    result = Main.mulAdd
    6


#### METADATA ####
[[{"index":{"value":0},"size":{"value":4}},"8f6eec81-a516-4dde-be43-07de625a6653"],[{"index":{"value":4},"size":{"value":1}},"b95addc1-dffd-4622-ba63-4468d083908c"],[{"index":{"value":5},"size":{"value":6}},"429638bf-fa87-4071-8114-ca700b46fe81"],[{"index":{"value":0},"size":{"value":11}},"1e0db7d9-0de1-450d-b137-4fa0e2049a35"],[{"index":{"value":12},"size":{"value":1}},"68d4054d-00d3-49fa-83bd-0807947e28f0"],[{"index":{"value":14},"size":{"value":1}},"2c980296-5cb9-42ac-adea-095409fa7c3a"],[{"index":{"value":0},"size":{"value":15}},"f8e67f93-4366-42f9-aa3e-d1d210002b38"],[{"index":{"value":17},"size":{"value":4}},"b3dbe0d8-4323-4ca2-aacc-14e3b0473740"],[{"index":{"value":22},"size":{"value":1}},"186f956b-f402-4648-98ce-8b11bea71a53"],[{"index":{"value":28},"size":{"value":6}},"743ce364-07f6-465f-8640-11fc0cbf306e"],[{"index":{"value":35},"size":{"value":1}},"612de1cf-9e9e-464b-be5e-7d6ffaa7c694"],[{"index":{"value":37},"size":{"value":4}},"fecdad1c-9451-4d2b-a7fd-4aad5550de40"],[{"index":{"value":41},"size":{"value":1}},"27938428-f93b-429e-9094-2fad6d363c83"],[{"index":{"value":42},"size":{"value":6}},"edf2376f-4edf-4c43-9111-461dc29cef3d"],[{"index":{"value":37},"size":{"value":11}},"2d6c6cae-414b-4174-8450-afabd042ae93"],[{"index":{"value":28},"size":{"value":20}},"7ba77f90-2cf9-4402-a3ab-d6f1e6585d51"],[{"index":{"value":53},"size":{"value":1}},"20f2ff1b-8932-48e5-ba25-b59d15bf7d58"],[{"index":{"value":23},"size":{"value":31}},"abd6952c-ab14-4574-8b8d-a089142c37cf"],[{"index":{"value":17},"size":{"value":37}},"0df7d0e1-a95a-47f3-9ea5-b9e54919db2b"]]
{"ide":{"node":{"20f2ff1b-8932-48e5-ba25-b59d15bf7d58":{"position":{"vector":[-495.9664,199.92416]}},"2d6c6cae-414b-4174-8450-afabd042ae93":{"position":{"vector":[-652.0,87.0]}},"7ba77f90-2cf9-4402-a3ab-d6f1e6585d51":{"position":{"vector":[-584.0,115.0]}},"32dd808a-0633-4648-994c-691653c6e758":{"position":{"vector":[-506.0,116.0]}}}}}
```

### Expected Result
As the `main` is executed, IDE gets a computed notification for `result` (left-hand side of the node assignment).

### Actual Result
No such update is emitted.
See the following ws log excerpt:
```
{"jsonrpc":"2.0","id":6,"method":"executionContext/push","params":{"contextId":"66443a03-cc8e-4b04-8376-972d8ce4e431","stackItem":{"methodPointer":{"definedOnType":"Main","file":{"rootId":"b120858a-8d4e-4a76-9d4c-85efa4cbfb24","segments":["src","Main.enso"]},"name":"main"},"positionalArgumentsExpressions":[],"thisArgumentExpression":null,"type":"ExplicitCall"}}} | 364 | 01:51:39.246 |  
{"jsonrpc":"2.0","id":6,"result":null} | 38 | 01:51:39.248 |  
{"jsonrpc":"2.0","id":7,"method":"file/exists","params":{"path":{"rootId":"b120858a-8d4e-4a76-9d4c-85efa4cbfb24","segments":["visualization"]}}} | 144 | 01:51:43.607 |  
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"66443a03-cc8e-4b04-8376-972d8ce4e431","updates":[{"id":"edf2376f-4edf-4c43-9111-461dc29cef3d","type":null,"shortValue":"UnresolvedSymbol<mulAdd>","methodCall":null}]}} | 260 | 01:51:43.910 | 
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"66443a03-cc8e-4b04-8376-972d8ce4e431","updates":[{"id":"fecdad1c-9451-4d2b-a7fd-4aad5550de40","type":"Main","shortValue":"Main","methodCall":null}]}} | 242 | 01:51:43.912 |  
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"66443a03-cc8e-4b04-8376-972d8ce4e431","updates":[{"id":"2d6c6cae-414b-4174-8450-afabd042ae93","type":"Number","shortValue":"5","methodCall":{"file":{"rootId":"b120858a-8d4e-4a76-9d4c-85efa4cbfb24","segments":["src","Main.enso"]},"definedOnType":"Main","name":"mulAdd"}}]}} | 365 | 01:51:43.912 |  
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"66443a03-cc8e-4b04-8376-972d8ce4e431","updates":[{"id":"7ba77f90-2cf9-4402-a3ab-d6f1e6585d51","type":"Unit","shortValue":"Unit","methodCall":null}]}} | 242 | 01:51:43.912 |  
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"66443a03-cc8e-4b04-8376-972d8ce4e431","updates":[{"id":"20f2ff1b-8932-48e5-ba25-b59d15bf7d58","type":"Number","shortValue":"6","methodCall":null}]}} | 241 | 01:51:43.913 |  
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"66443a03-cc8e-4b04-8376-972d8ce4e431","updates":[{"id":"abd6952c-ab14-4574-8b8d-a089142c37cf","type":"Number","shortValue":"6","methodCall":null}]}} | 241 | 01:51:43.913 |  
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"66443a03-cc8e-4b04-8376-972d8ce4e431","updates":[{"id":"7ba77f90-2cf9-4402-a3ab-d6f1e6585d51","type":"Unit","shortValue":"Unit","methodCall":null}]}} | 242 | 01:51:43.913 |  
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"66443a03-cc8e-4b04-8376-972d8ce4e431","updates":[{"id":"20f2ff1b-8932-48e5-ba25-b59d15bf7d58","type":"Number","shortValue":"6","methodCall":null}]}} | 241 | 01:51:43.913 |  
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"66443a03-cc8e-4b04-8376-972d8ce4e431","updates":[{"id":"abd6952c-ab14-4574-8b8d-a089142c37cf","type":"Number","shortValue":"6","methodCall":null}]}} | 241 | 01:51:43.913 |  
{"jsonrpc":"2.0","id":7,"result":{"exists":false}} | 50 | 01:51:43.914
```

There's no update for AST with ID `743ce364-07f6-465f-8640-11fc0cbf306e`, i.e. for the `result` variable.

### Enso Version
61b285f182f33459439135928ea0acc3958b2c10

**Comment by kustosz** [comment]
I don't understand what value would you expect there? The interpreter works on a tree, so the left hand side of assignment evaluates to "position 1 in current execution frame" (more specifically, doesn't get evaluated at all because it get's constant-folded during static analysis), the right hand side to the assigned value and the assignment is a side-effecting computation of "put the result of RHS into position 1 in current execution frame". There is no "value" the LHS of an assignment could return.

**Comment by farmaazon** [comment]
But in case we have pattern like `Pos x y = here.compute_position` we need to know what is a type of x and y, even if the variables are not used anywhere, to make the proper output port coloring.

**Comment by kustosz** [comment]
Hmmmm. OK, I see the problem. This requires some careful thought, I think we'll just have to equip the interpreter with the ability to report assignment events. Question is, how blocking is it, given that the language does not currently support this syntax?

**Comment by mwu-tow** [comment]
>  how blocking is it

Very blocking for the output port coloring and some more tricky features in the searcher (like using pattern sub-part for "this" argument). As for how these features are important — @farmaazon  ?

> given that the language does not currently support this syntax?

Is there any place I can check what language currently supports — and what I can confidently use, test and develop against, reporting all things as a bugs?
Or at least some central set of working code examples?

**Comment by kustosz** [comment]
> Very blocking for the output port coloring and some more tricky features in the searcher

Without the pattern match problem, you can just use the value of the RHS.

> Is there any place I can check what language currently supports

Not really, we should get better at pointing out the parts of the spec that are not implemented.

> Or at least some central set of working code examples

There's quite a large corpus of short & sweet samples in our tests https://github.com/enso-org/enso/tree/main/engine/runtime/src/test/scala/org/enso/interpreter/test/semantic

Also the standard library is growing currently, so you can look at https://github.com/enso-org/enso/tree/main/distribution/std-lib/Base and https://github.com/enso-org/enso/tree/main/test/Test

<blockquote><img src="https://avatars0.githubusercontent.com/u/17415943?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/17415943?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
<blockquote><img src="https://avatars0.githubusercontent.com/u/17415943?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by farmaazon** [comment]
So, if the syntax of `Position x y = ` is not supported anyway, we also cannot support multiple output ports anyway. So I think this task is not really blocker for us.
