### ISSUE TITLE
Update dashboard bg color to match Figma

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#10393]
In Figma there's a semi-transparent color (#F4F6F799) overlayed on top of the background image (see: app > window > 2nd "window"); this layer seems to be the difference between the application bg color seen in Figma and our current color.

**Comment by somebody1234** [comment]
![bg](https://github.com/enso-org/enso/assets/4046547/fd9ed751-f0e4-4fe3-be0b-5bb72adbd27c)

i'm not too sure about that - figma seems to indicate that the white background color is correct.
however, it *is* true that our opacity is wrong for some reason...
will open a PR soon.

**Comment by somebody1234** [comment]
change of plans on the dashboard side (for now) - the asset panel background has been reverted to `white / 40% opacity`, and instead a shadow + clip path has been used to display a shadow on the left side

**Comment by somebody1234** [comment]
nvm
