### ISSUE TITLE
Cannot match ExpressionValueUpdate with ExpressionId

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#1042]
### General Summary

The new shape of ExpressionValueUpdate does not provide information what expression was updated.

### Steps to Reproduce

Look at https://dev.enso.org/docs/enso/language-server/protocol-language-server.html#expressionvalueupdate

### Expected Result

I see a structure which informs me what expression is updated.

### Actual Result

I see a structure which wraps suggestionId only.

### Enso Version

93c44532994d8580809a61c465277f818ee4647d

**Comment by farmaazon** [comment]
Additionally, the field `shortValue` was removed; soon IDE is about to support them, so we still need this field.

**Comment by 4e6** [comment]
Then what about #442 that requests removing the `shortValue`?

**Comment by farmaazon** [comment]
Ok, you're right, so it seems there is inconsistency in our plans. So please forget about shortValue then

**Comment by mwu-tow** [comment]
I personally likked short values as debug help but the decision was to remove them, so the updates don't need to be resend if the value changes but type and method stays the same.
