### ISSUE TITLE
Zoom to the mouse position instead of the center of the canvas

### ISSUE THREAD

**Issue by MrFlashAccount** [enso-org/enso#10420]
As is:

https://github.com/enso-org/enso/assets/61194245/84c3924d-6b61-4a53-8750-81e7751b1774

Expected:

https://github.com/enso-org/enso/assets/61194245/4b87bd38-4c14-47ca-82a7-e8671cbd380b

**Comment by Frizi** [comment]
Removed by accident here: https://github.com/enso-org/enso/commit/614a5a610b4351b387b666f811a263d42c45e442#diff-cb6f41c72bf4bf02ee0758deebe8b578c18b814d5d7ac8d4065685c07002af95L232

**Comment by kazcw** [comment]
> Removed by accident here: [614a5a6#diff-cb6f41c72bf4bf02ee0758deebe8b578c18b814d5d7ac8d4065685c07002af95L232](https://github.com/enso-org/enso/commit/614a5a610b4351b387b666f811a263d42c45e442#diff-cb6f41c72bf4bf02ee0758deebe8b578c18b814d5d7ac8d4065685c07002af95L232)

The requested feature would require zooming to be implemented with a combination of scaling and panning. That PR changes only the scaling; panning was already absent from the zoom logic. If we had this feature in the past, we lost it prior to the linked commit.
