### ISSUE TITLE
Improve output component inside collapsed components

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10459]
Today:

![image](https://github.com/enso-org/enso/assets/1720119/3c3e291d-bebb-452a-98fa-d366b9b23af0)

In future output component should be:
- Marked as output
- Always the last component in the code
- Not deletable

**Comment by farmaazon** [comment]
Backlog refinement:
* The second point is already implemented.
* For now, let's treat it as "normal" node, just undeletable, and with some special icon and color.
* And do not display variable name: just an icon to connect to.
* Also, do not display output port in output node (you cannot drag edges from it anyway).
