### ISSUE TITLE
Unable to download from subfolders

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#10453]
- The original functionality was implemented in #7291.

However, it seems that it does not support specifying the parent directory, which seems to break download functionality in nested folders on `develop`.

**Comment by somebody1234** [comment]
pinging @4e6 as the author of the original PR

**Comment by somebody1234** [comment]
oh, apparently it's been assigned to hubert

**Comment by hubertp** [comment]
As per discussion in the standup, this is currently defined in https://github.com/enso-org/enso/blob/develop/lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/http/ProjectsEndpoint.scala#L41

<blockquote><img src="https://opengraph.githubassets.com/fe40383e4e0233b006480eeda878d40ae1c037c670a2c03b0596fb80ef7e5d28/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/blob/develop/lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/http/ProjectsEndpoint.scala">enso/lib/scala/project-manager/src/main/scala/org/enso/projectmanager/infrastructure/http/ProjectsEndpoint.scala at develop · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by hubertp** [comment]
@somebody1234 Can you check if the additional parameter unblocks you?

**Comment by somebody1234** [comment]
@hubertp funny thing is, i was testing exactly this today and i can't get it to work on the latest nightly.
code is here: <https://github.com/enso-org/enso/tree/wip/sb/dashboard-fixes> - to test, download from subfolder on electron. you should be able to run `npm run watch:linux` (or macos/windows) in `app/ide-desktop/lib/client` to test electron without having to build the entire app

<blockquote><img src="https://opengraph.githubassets.com/e71e41260a19b3c630f95e79e4339bc6052afa51410a705f62fc12c4fd6b9406/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">GitHub - enso-org/enso at wip/sb/dashboard-fixes</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by somebody1234** [comment]
but yeah *theoretically* the additional parameter is enough

**Comment by hubertp** [comment]
Confirmed that this now works. I was working on an outdated branch where GUI wasn't passing the full url (the `projectsDirectory` parameter was missing).
