### ISSUE TITLE
Warning makes it impossible to open full screen viz with icon

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10450]
![Image](https://github.com/enso-org/enso/assets/12892578/82d0d881-dac9-4645-ab55-10249ac7c0b5)

When the viz is open the warning/error should move down underneath it.

![image](https://github.com/enso-org/enso/assets/1720119/9874aeb8-2870-4132-8204-605fc3155fab)

**Comment by somebody1234** [comment]
minor nit: it seems like the plus button is overlapping the output bar... perhaps the button should move down when that bar is visible?

**Comment by farmaazon** [comment]
> minor nit: it seems like the plus button is overlapping the output bar... perhaps the button should move down when that bar is visible?

It's already fixed in #10443
