### ISSUE TITLE
Avoid name duplication of the `enso` universal launcher

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#10476]
There are two executables named `enso` among the daily bits we produce. That's **confusing** and _we shall fix it_.

One of them is called **Enso launcher**. To learn about it, please visit our download page: https://github.com/enso-org/enso/releases/tag/2024.1.1 - the download is in section called **Enso Engine** on that page, but in fact, it is **not the engine**, it is **the launcher**!

![Enso Engine](https://github.com/enso-org/enso/assets/26887752/f82e45d8-47d5-4c83-a96d-2f01ee304cdb)

To learn more abou tthe **enso launcher** visit this [documentation page](https://github.com/enso-org/enso/blob/d95ebd483684f270cb1ee04ae126d3be3560b086/docs/distribution/distribution.md) - it contains nice description of the whole **universtal launcher/updater** picture...

However to benefit from the work done by 
- #10374 
- and to fulfill the vision as discussed in #10121

we need to find a _better location_ for exposing _native image_ built launcher. The idea is to **rename the launcher** to `ensoup`:

![ensoup illustration](https://github.com/enso-org/enso/assets/26887752/b1f46e88-45d5-4a63-b776-80d2860dbe12)

It is a nice, _illustrative_ name derived from the `rustup` example that nicely describes one of the purposes of `ensoup` - download the distributions of Enso automatically. Once the `enso` in the bundle is renamed to `ensoup`, we can proceed with placing a _native image built_ binary next to it under the name `enso` - but that's for a different PR.

**Comment by JaroslavTulach** [comment]
I've just downloaded the [latest nightly](https://github.com/enso-org/enso/releases/download/2024.3.1-nightly.2024.7.17/enso-bundle-2024.3.1-nightly.2024.7.17-linux-amd64.tar.gz) and it contains the `ensoup` executable:
```
tar ftvz enso-bundle-2024.3.1-nightly.2024.7.17-linux-amd64.tar.gz  | grep enso/bin
drwxr-xr-x ci/ci             0 2024-07-17 04:29 enso/bin/
-rwxr--r-- ci/ci      58969568 2024-07-17 04:29 enso/bin/ensoup
```
the executable seems to work to some extend. I can `ensoup new path_to_a_project` and it runs. I haven't tested the other functionality (CCing @radeusgd), but in general things seem to work.

**Comment by radeusgd** [comment]
> I haven't tested the other functionality (CCing @radeusgd), but in general things seem to work.

I have downloaded the Windows bundle.

Seems to work OK to me. I've checked most of the functionality, incl. the installation feature and all seem to work as expected. I have only not checked the self-upgrade.

I will be starting using `ensoup` from now on :) 🥣
