### ISSUE TITLE
Compiler Internal Error: Impossible here, static method get should be caught when translating application

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10473]
![Image](https://github.com/enso-org/enso/assets/48301778/419617e7-b44d-4769-b982-4023d4b78fe4)

Add a unconnected component 

> node3 = get 1

And you get the above internal error and things don't work right

**Comment by JaroslavTulach** [comment]
It would be interesting to know the whole source code. Without the source code, I can only guess what could be the problem. Trying to parse:
```
node3 = get 1
```
yields: 
```
e.enso:1:9: error: The name `get` could not be found.
    1 | node3 = get 1
      |         ^~~
```
that's correct.

**Comment by JaroslavTulach** [comment]
This is the failing test:
```diff
diff --git engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecCompilerTest.java engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecCompilerTest.java
index d83891b7b5..b2ebe5bc4f 100644
--- engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecCompilerTest.java
+++ engine/runtime-integration-tests/src/test/java/org/enso/compiler/ExecCompilerTest.java
@@ -90,6 +90,25 @@ public class ExecCompilerTest {
     }
   }
 
+  @Test
+  public void testDoubleAssignmentError() throws Exception {
+    var module =
+        ctx.eval(
+            LanguageInfo.ID,
+            """
+    from Standard.Base import all
+
+    main =
+        node1 = node3 = get 3
+    """);
+    try {
+      var run = module.invokeMember("eval_expression", "main");
+      fail("Unexpected result: " + run);
+    } catch (PolyglotException ex) {
+      assertEquals("", ex.getMessage());
+    }
+  }
+
   @Test
   public void testDesugarOperatorsLeftRight() throws Exception {
     var module = ctx.eval(LanguageInfo.ID, """
```
it was actually pretty tricky to find the test case, as the same program yields normal compilation errors when executed from CLI. One really has to run in IDE's _"non-strict errors"_ mode.

**Comment by JaroslavTulach** [comment]
@kaz, the `node3 = get 3` in `node1 = node3 = get 3` is represented as _application_ of function/operator named `=`. Is that desirable? Shouldn't `=` be a reserved keyword and not an operator?

The question is who should reject that syntax? parser? `TreeToIr`? Or some later phase in the compiler?

The [error is yielded from here](https://github.com/enso-org/enso/blob/b189ceae4717f58e14e29023c570bd9d4143946a/engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala#L888) and I can generate better syntax error, but possibly we should not even get to [this place](https://github.com/enso-org/enso/blob/b189ceae4717f58e14e29023c570bd9d4143946a/engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala#L888).

**Comment by kazcw** [comment]
That would be a syntax error. Only the parser should create syntax errors.
