### ISSUE TITLE
Lost focus when both doc panel and source code panels are open

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10471]
If I edit source code while doc panel is open, every keystroke in the doc panel causes focus to revert to the doc panel, and new keystrokes are placed at the bottom of the doc panel.

https://drive.google.com/file/d/19RturKl8gykJitfPnkQnD0Rcp8iR5KRc/view?usp=drive_link

**Comment by jdunkerley** [comment]
Add a doc comment.
Then editing in the code editor does not appear to make doc comment get updated.

**Comment by kazcw** [comment]
This is a regression so we should be sure to add an e2e test for this case.
