### ISSUE TITLE
Component menu Record button updates

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10486]
New button on component drop menu
- Has workflow_play icon
- Has text Write
- Is a single click action which causes the current component to refresh it's inputs/write its outputs
- Is positioned below Add Comment in the menu

```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/issues/10719
- [ ] Wheel menu Record button updates
```

**Comment by farmaazon** [comment]
* Currently, the Record button is always visible when on, but having it NW would make it a bit odd.
* The rerunning a single node is not yet supported by engine probably.

**Comment by farmaazon** [comment]
Refinement notes:
* Use the new design for node menu.
* Remove "Record" button - leave only "run once". ~~Remove also the handlers for that for the code (like, hiding some special prefixes from the user).~~ (see below)
* The "play" button should be disabled until half a second passes or execution completes, whatever comes later.
* Add/extend the current integration tests (with engine) covering this: check if the file is not created before (in design mode), then run once the node, and see if the file appears (the `write` node could be in "append" mode, so we also check that we've written to file only once).

**Comment by farmaazon** [comment]
Breaking news:
* We actally _want_ to re-introduce record button in the near future, **so don't remove the logic implementation yet**.
