### ISSUE TITLE
Cannot pass extra parameters to Enso.exe

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10482]
`.\Enso.exe --help` yields an exception that the "single argument '--help' does not denote a readable file". So parsing parameters is rather broken on Windows executable.

**Comment by hubertp** [comment]
Surprise, surprise. One has to wrap arguments in quotes.
- `Enso.exe -debug.verbose` doesn't work
- `Enso.exe "-debug.verbose"` works

**Comment by JaroslavTulach** [comment]
Looks like it works.
