### ISSUE TITLE
Incorrect handling of multiple `session/initProtocolConnection` messages

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10495]
The problem is best illustrated with the exchange between GUI and LS:
![Screenshot from 2024-07-09 15-57-23](https://github.com/enso-org/enso/assets/292128/4020c5a6-80ce-42c3-843e-586b0ae26f97)
1. LS is slow to respond to connection initialization requests
2. GUI makes a few attempts to get the connection
3. Eventually, session is initialized and GUI receives a (late) reply
4. Further requests receive the already initialized error response, as per protocol specification

It seems that GUI's handling is incorrect. It should respect the already initialized connection response and either continue or close the connection first. Retrying the same request is not going to change the response.

This is blocking #9789.

Note that the repercussions of the current logic are that the project is unusable:
```
Cannot load initial suggestion database. Continuing with empty suggestion database: Language Server request 'session/initProtocolConnection' failed: Session already initialised
```

**Comment by farmaazon** [comment]
Closing in favor of #9347 (which is same bug and estimated)
