### ISSUE TITLE
Decide If `Main.enso` File Is Required in a Project

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#1050]
### Summary
Following the discussion from https://github.com/enso-org/ide/issues/510

@wdanilo  wrote:
> @kustosz hmm, shouldnt libraries contain `Main.enso` as well? Connected question, let's imagine you create a library "Kustosz". What will happen if I write `import Kustosz : Marcin` ? Where the struct `Marcin` will be defined in the library? I mean, should the `Main.enso` not be the "root" interface of library potentially re-exporting the most useful things?

There are some diverging opinions whether the project is required to contain `Main.enso` file.
Currently IDE treats it as required (as suggested by @wdanilo ) and will fail to open the project if it is missing. To prevent users from getting stuck with projects missing `Main.enso` it has been requested for IDE to recreate `Main.enso` if it is missing.

But in the longer term I believe this should be done on the backend side. 

### Value
Having clear idea what the project looks like and dealing with discrepancies in an appropriate manner.

### Specification
The language design stakeholders should discuss and agree whether all projects are required to have `Main.enso` file.

If the answer is that it is required, then a new issue should be created for the backend to recreate the file (or not list the project as available, if it is not a correct project) and then to remove the workaround on the IDE side. 
Otherwise, issue should be created against IDE with description how to handle projects without `Main.enso`.

### Acceptance Criteria & Test Cases
The high involved parties have achieved an agreement.

**Comment by iamrecursion** [comment]
@kustosz Has a decision been made on this?

**Comment by kustosz** [comment]
Not to my knowledge. We have a use case for the `Main` module, but I don't think there was any conclusion on whether it is required.

**Comment by iamrecursion** [comment]
I think we _should_ require it. It's either the top-level point for the library (akin to `lib.rs`) or the application main. I can't think of a reasonable use case for a project without one.

Thoughts @kustosz @mwu-tow @wdanilo?

**Comment by kustosz** [comment]
I still don't think we should require something if everything works fine without it. Why is anything better because it is required?

**Comment by iamrecursion** [comment]
Fair enough. I think a decision just needs to be made here.

**Comment by iamrecursion** [comment]
@sylwiabr

**Comment by wdanilo** [comment]
We should treat `Main.enso` as the main entry point to both exec and libs. This is a very beautiful, concise, and clean to users design.
