### ISSUE TITLE
Investigate slow opening of a project having large CSV file

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10503]
When a project has a large data file (> 50MB) it will execute relatively slow in non-interactive mode and when loading a project in GUI.

**Comment by JaroslavTulach** [comment]
I have 16MB large `.csv` file:
- with `2024.3.1-nightly.2024.7.10` it takes me **14s** to `Data.read` it
- with `2024.2.1-nightly.2024.6.14` it takes just **2s** to `Data.read` it

After bisecting, the first bad commit is fe2cf4956862aa5fe71ce304567ff530c4a5d5dc coming from
- #10296
- the **first bad commit**: https://github.com/enso-org/enso/pull/10296/commits/377bd2a28d204dbd9ecadf8df6790990a06a2fbf

**Comment by hubertp** [comment]
Yes, I confirm. fe2cf4956 takes 8.5s to parse 8MB file, while b5641aa3b just before it it takes 0.8s.

**Comment by JaroslavTulach** [comment]
> I have 16MB large `.csv` file:
> 
>     * with `2024.3.1-nightly.2024.7.10` it takes me **14s** to `Data.read` it
>     * with `2024.2.1-nightly.2024.6.14` it takes just **2s** to `Data.read` it
> 

With https://github.com/enso-org/enso/pull/10515/commits/0accf833abd86bf6be59f14f099c2e973c1e15b8 it takes `2200ms` to read the 16MB large `.csv` file.
