### ISSUE TITLE
Can’t reopen project after reloading the page in local dev build

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#10510]
I open a local project, then reload the page (or trigger hot-reloading), and I can no longer reopen this project.

```
530d10d9bda6d5c4c21881b22025b379b2436e72

Enso Project Manager
Version:    2024.3.1-nightly.2024.7.10
Built with: scala-2.13.11 for GraalVM 21.0.2
Built from: develop @ 8da06309e99f24d7062df5638f49e000fb292eff
Built on:   Mac OS X (aarch64)
```

https://github.com/enso-org/enso/assets/6566674/179596ff-94d1-4f4a-9a08-73731438d85d

**Comment by vitvakatu** [comment]
After a fix in #10511, the error message is now displayed when reloading the page:

<img width="968" alt="Screenshot 2024-07-10 at 9 24 12 PM" src="https://github.com/enso-org/enso/assets/6566674/f21378e7-1a48-489e-83ec-5bbfbb451a70">

There are no errors in dev tools console/project manager stdout.

**Comment by vitvakatu** [comment]
Bisecting engine versions, I found that this regression is caused by [2024.3.1-nightly.2024.7.6](https://github.com/enso-org/enso/releases/tag/2024.3.1-nightly.2024.7.6). It is easily reproducible, while previous released engine version (2024.3.1-nightly.2024.7.5) works flawlessly on the latest develop. Transferring to engine team @JaroslavTulach

**Comment by JaroslavTulach** [comment]
Probably fixed, need to verify.

**Comment by hubertp** [comment]
Cannot reproduce anymore. Considering that fixed.
