### ISSUE TITLE
Improve the speed of preorder operation on IR

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10537]
The [initial build of UUID map](https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/java/org/enso/interpreter/runtime/Module.java#L409) is a major bottleneck during an update to visualizations. 

[Initial experiments](https://github.com/enso-org/enso/pull/9915) in optimizing [preorder and children](https://github.com/enso-org/enso/blob/develop/engine/runtime-parser/src/main/java/org/enso/compiler/core/IR.java#L79) operations on IR failed after experiment on projects with a large number of nodes.
Using mutable collections, instead of constructing plain list during IR travels also failed to confirm significant gains in performance.

**Comment by JaroslavTulach** [comment]
I would change the preorder method signature to `default java.util.Iterable<IR> preorder() {` and had a lazily build iterator that never materializes more than one level of `children()`.

**Update** on Sep 4, 2024: It might be even better to have a simple callback `void preorder(Consumer<IR> consume)` - that way we remove all abstractions and just traverse&callback. 

![Usages of preorder()](https://github.com/user-attachments/assets/fd400e75-ccd2-4511-b195-e9439c620111)

Btw. looking at current usages of `preorder()` I find **only two** in production code! The rest seems to be in tests...

- see #10981 for further thoughts on the need of _generic IR traversal_

**Comment by 4e6** [comment]
> Btw. looking at current usages of preorder() I find only two in production code!

Unfortunately, it's a bit more

```
$ find . -not -path '*test*' -type f -name '*.scala' -or -name '*.java' | xargs grep '.preorder' | wc -l
41
```

**Comment by 4e6** [comment]
@JaroslavTulach In the end, I find the approach of having two methods: `children` and `preorder` to work better

```java
  void children(Consumer<IR> cb);

  default void preorder(Consumer<IR> cb) {
    cb.accept(this);
    children(ir -> ir.preorder(cb));
  }
```

Having the default `preorder` method eliminates the repetition of calling the `preorder` on each child node in the implementation class.

**Comment by JaroslavTulach** [comment]
I had to look what `preorder` is supposed to mean:

> Pre-order, NLR
>
>    Visit the current node (in the figure: position red).
>    Recursively traverse the current node's left subtree.
>    Recursively traverse the current node's right subtree.

OK, this is `preorder` then:

> ```java
>   default void preorder(Consumer<IR> cb) {
>     cb.accept(this);
>     children(ir -> ir.preorder(cb));
>   }
> ```

Do you really want to go (the more complicated way) and change two methods? Wouldn't be easier just call `children().foreach(ir -> ir.preorder(ch))` to begin with?

**Comment by JaroslavTulach** [comment]
The `ir -> ir.preorder(ch)` is an **allocation** of new object. It looks like lambda, but it needs to create a closure. As such it needs to allocate new instance implementing the `Consumer<IR>` interface with a field pointing to `cb`. We should avoid such an allocation. Let's:
```java
static void preorder(IR ir, Consumer<IR> cb) {
  class CB implements Consumer<IR> preorderCb {
    public void accept(IR e) {
      cb.accept(e);
      e.children(this);
  }
  ir.children(new CB());
}
``` 
the same code will work with current `List<IR> children()`:
```java
static void preorder(IR ir, Consumer<IR> cb) {
  class CB implements Consumer<IR> preorderCb {
    public void accept(IR e) {
      cb.accept(e);
      e.children().foreach(this);
  }
  ir.children().foreach(new CB());
}
```
e.g. no need to change the signature (and all the implementations) of `children` method.
