### ISSUE TITLE
Expression Work

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10531]
A number of functions for expressions return errors.
The following return an error of Method `rename` of type Text (or Integer)could not be found.

- [x] at
- [x] get
- [ ] first
- [x] last
- [x] name
- [x] length
- [x] count
- [x] count_nothing 

The following return an error of Expression.Syntax_Error: extraneous input 'between' expecting {'(', '#', '-', NULL, NOTHING, TRUE, FALSE, IF, UNARY_NOT, IDENTIFIER, EXCEL_STRING, PYTHON_STRING, NUMBER, COLUMN_NAME} (line 1, column 0).

- between([OrderCount],1,3)
- like([TERRITORY],'N%')

And one returns a warning that it has been deprecated

- Warning: Deprecated: `auto_value_type` has been replaced by `auto_cast`.

Incorrect output on one function (I believe)

- duplicate_count - I have only 10 rows of data, but it returns a duplicate_count of 12 on a column.

Workflow attached here:
https://drive.google.com/file/d/1ObpAAqury2BJv8JSid2IFhQVLxHPR00y/view?usp=drive_link

To Add:
- now (timestamp)
- today (date)

**Comment by steve-enso** [comment]
I am not certain that auto_cast does anything. I would have expected this to cast the char numbers to a float.



![Image](https://github.com/user-attachments/assets/4bc3aa6a-a141-4f79-99af-9debe81c5e07)

**Comment by jdunkerley** [comment]
Scalar functions all working now.

In Expressions:
 - between has to be written `<a> BETWEEN <B> AND <C>`
![Image](https://github.com/user-attachments/assets/da76e944-e441-42e9-a389-2c248162cd15)


 - like has to be written `<a> LIKE <expr>`
![Image](https://github.com/user-attachments/assets/9913bdee-4c91-4ac1-851a-3a21e5c25a1b)

- duplicate_count working fine (had incorrect expression in component)
![Image](https://github.com/user-attachments/assets/dd8971fa-eb54-4236-8a2e-2df54272f6ab)
