### ISSUE TITLE
Table Viz font changes when in full screen mode

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10551]
Normal mode:

![image](https://github.com/user-attachments/assets/358f2598-89b7-433c-af72-678f0d22febb)

Full Screen mode:

![image](https://github.com/user-attachments/assets/0e2ad62d-9cd8-441f-8158-364f7fa82673)

Screenshots from Windows version

**Comment by farmaazon** [comment]
Refinement:
* font of `796` is different, so CSS should be fixed.
* Let's try to make all visualization spawned in a shadow root, so they won't inherit CSS (the widget developer may be not aware of them, and they may change from one version to another). But do not spend too much time on it (no more than 3 days).
