### ISSUE TITLE
Lack of `namespace` field in project's `package.yaml` makes PM classify it as a plain directory

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10564]
If `package.yaml` has no
```
namespace: "local"
```
entry:
![Screenshot from 2024-07-16 12-43-01](https://github.com/user-attachments/assets/09d60b8b-3339-43ef-856b-3c1f893a01e0)

Once added, it magically changes to
![Screenshot from 2024-07-16 12-43-25](https://github.com/user-attachments/assets/579f4033-1438-415a-a87f-cd83c632a6ce)

I think the regression was introduced when serializing default values of YAML files, as part of https://github.com/enso-org/enso/commit/c54c3b7e9da42a3c6fc0578c5f2c7437deba890d.

**Comment by vitvakatu** [comment]
Related: #10510
