### ISSUE TITLE
Add context sensitive help to right side panel

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10582]
Add a new tab to the right side panel to show context sensitive help:

![image](https://github.com/user-attachments/assets/7f8ec3cd-cd0b-43d1-af82-4197556f3afa)

![image](https://github.com/user-attachments/assets/42a6e75d-df25-410c-894a-22c73ffa9aff)

Displays the help that we currently see in the component browser for the currently selected component.

![image](https://github.com/user-attachments/assets/91577e86-1b3b-4cd9-8a51-75f876ced577)

For multiple selections/no selection it shows the select a single component message.
For chained components show whichever help is easiest (first/last in the chain)

**Comment by Frizi** [comment]
- Keep the opened tab in localstorage per graph (same as we do for docs panel state now)
