### ISSUE TITLE
Local Project Manager is not showing any existing projects

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10588]
Regression introduced in https://github.com/enso-org/enso/commit/ebf4cd5c1f5ac67701a7e84fb38af92a94b7bf9a
leads to
![Screenshot from 2024-07-17 12-27-17](https://github.com/user-attachments/assets/ee4c7ad8-d361-43a6-b540-1d50a159332f)

**Comment by farmaazon** [comment]
Worth noting that this is an issue only on dev server. The electron app seems fine.

**Comment by somebody1234** [comment]
what is the response of `root-directory` in the network tab in devtools? (is it perhaps returning an incorrect directory path?)

**Comment by farmaazon** [comment]
The answer is: `/home/adam-praca/enso-projects` what is indeed a directory with projects:
```
    ~/dev/enso    wip/farmaazon/fix-table-drag    ls ~/enso-projects/*                                                                                                                                                                                              ✔ 
/home/adam-praca/enso-projects/NewProject1:
package.yaml  src

/home/adam-praca/enso-projects/NewProject1_1:
package.yaml  src

/home/adam-praca/enso-projects/NewProject1_2:
package.yaml  src

/home/adam-praca/enso-projects/NewProject1_3:
package.yaml  src

/home/adam-praca/enso-projects/NewProject1_4:
package.yaml  src

/home/adam-praca/enso-projects/NewProject1_5:
data  package.yaml  src

/home/adam-praca/enso-projects/NewProject1_6:
package.yaml  src

/home/adam-praca/enso-projects/NewProject1_7:
package.yaml  src
```

**Comment by somebody1234** [comment]
i guess in that case, it might be helpful to log the `const entryNames = await fs.readdir(directoryPath)` below and `entryPath` below that
