### ISSUE TITLE
'Additional Options (how to get to zoom, etc) has stopped working.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10581]

**Comment by hubertp** [comment]
![Screenshot from 2024-07-25 11-59-37](https://github.com/user-attachments/assets/14b9565c-1878-418a-b985-a18e94c0a2e0)
![Screenshot from 2024-07-25 11-59-59](https://github.com/user-attachments/assets/a1c6a956-bd63-4ecc-85b7-38dcf444af9b)
Probably related - clicking on the three dots only displays the "Additional Options" tooltip. One has to click on the outer ring to open the menu.  This is not particularly desired from the UX point of view.

**Comment by farmaazon** [comment]
> Probably related - clicking on the three dots only displays the "Additional Options" tooltip. One has to click on the outer ring to open the menu. This is not particularly desired from the UX point of view.

Not only related, but actually the only issue with "additional options" I see. Once you get the menu, the options are working fine.
