### ISSUE TITLE
When Reopening a Project, no dynamic widgets available.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10595]
The GUI attaches the correct visualizations but no response from the backend of the evaluated json.

<img width="306" alt="Snag_17f6fc27" src="https://github.com/user-attachments/assets/3e28675d-081a-4b02-a12f-0b5075902d72">

The simple workflow above works when being built but fails when reopened.

**Comment by hubertp** [comment]
It looks like GUI is not sending `executionContext/executeExpression` request  on startup for the visualization in question. It is also not sending it afterwards. So this is a regression in GUI I think.

**Comment by farmaazon** [comment]
We do not send `executionContext/executeExpression` because we send `attachVisualization` instead.

**Comment by hubertp** [comment]
@farmaazon My bad, sorry about that. We will continue looking into it.
