### ISSUE TITLE
Docker Image to run Enso as a script

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10625]
For running the project asynchronously want a docker image which runs the Enso executable.

Any warnings and errors produced in main should be logged to the console.

**Comment by hubertp** [comment]
Re warnings - first we need to get them outside of docker https://github.com/enso-org/enso/issues/9749

**Comment by hubertp** [comment]
This works out of the box:
```
docker run -v <host-project-path>:/volumes/workspace/project_root -t <build-tag> --execution-environment live --run /volumes/workspace/project_root
```

**Comment by hubertp** [comment]
@PabloBuchu This worked for you?

**Comment by hubertp** [comment]
This has been done and worked.
