### ISSUE TITLE
Can't move newly created project to a subfolder

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10633]
![Screenshot from 2024-07-22 23-24-34](https://github.com/user-attachments/assets/34011d53-3644-4dd6-97dc-92586cd87622)

Potentially related to #10453

**Comment by 4e6** [comment]
There are two issues:
- the project-manager `--filesystem*` commands can print error logs to stdout together with the json reply. I'll fix that
- @somebody1234 Another issue is related to GUI. When I drag the project to the subdirectory it generates the following command prompt:
  ```
  ["--filesystem-move-from","/home/dbushev/Documents/enso-projects","--filesystem-move-to","/home/dbushev/Documents/enso-projects/tmp/enso-projects"]
  ```
  i.e. the `from` and `to` parameters are incorrect, it should be like that:
  ```
  ["--filesystem-move-from","/home/dbushev/Documents/enso-projects/New_Project_1","--filesystem-move-to","/home/dbushev/Documents/enso-projects/tmp/enso-projects/my-subdir/New_Project_1"]
  ```

**Comment by PabloBuchu** [comment]
Fixed
