### ISSUE TITLE
Switch to Graal-based Ydoc fails 

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10632]
Starting GUI with Graal-based Ydoc:
```
> POLYGLOT_YDOC_SERVER=true npm --workspace enso-gui2 run dev
```
and backend as well (see #10627):
```
> POLYGLOT_YDOC_SERVER=true java -jar -Dtruffle.class.path.append="runtime.jar" project-manager.jar -vv
```

Leads to failed websocket connections being reported:
![Screenshot from 2024-07-22 21-53-12](https://github.com/user-attachments/assets/abce0c07-4577-4870-9eb7-6158632a0312)
and project obviously not loading.

**Comment by 4e6** [comment]
The integration can be checked by providing the custom Ydoc URL to the GUI:
```
$ ENSO_POLYGLOT_YDOC_SERVER='ws://localhost:1234' npm run dev:GUI
 ```

and then enabling the bundled Ydoc when starting the language server:
```
$ POLYGLOT_YDOC_SERVER=true java -jar project-manager.jar --no-log-masking -vv
```

**Comment by 4e6** [comment]
Fixing the issue with arbitrary failures in the service discovery can be postponed due to the upcoming changes in the module path organization. Right now it is not a blocker as the bundled Ydoc is not planned to be used in the near future.
