### ISSUE TITLE
Download with Cache

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10640]
Improve support for web requests with an in built cache.

- Should read the caching headers from response.
- Only cached for the session with temporary file cleaned up on exit.
- Only cached for GET requests.

Discuss engine-side caching with @JaroslavTulach 

Should be able to be disabled by the end user (at a request or higher level).
- i.e. Data.fetch and equivalent have options to control the caching.

Look to use Channels or another modern Java fetch techniques.

**Comment by JaroslavTulach** [comment]
- Where should the cached files be stored? In projects data directory?

> Look to use Channels or another modern Java fetch techniques.

- Should we download multiple resources in parallel? Then _virtual threads_ would be our choice.
