### ISSUE TITLE
Jobs appear to be stuck on Base_Tests

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10643]
https://github.com/enso-org/enso/actions/runs/10055728974/job/27793016991

Test temporarily disabled in https://github.com/enso-org/enso/pull/10642.

**Comment by JaroslavTulach** [comment]
The [failed test run](https://github.com/enso-org/enso/actions/runs/10055728974/job/27793016991) seems to repeat:
```
 INFO ide_ci::program::command: bash ℹ️ Still 61800 resources to clean up...
 INFO ide_ci::program::command: bash ℹ️ Still 61800 resources to clean up...
 INFO ide_ci::program::command: bash ℹ️ Still 61800 resources to clean up...
 INFO ide_ci::program::command: bash ℹ️ Still 61800 resources to clean up...
 INFO ide_ci::program::command: bash ℹ️ Still 61800 resources to clean up...
 INFO ide_ci::program::command: bash ℹ️ Still 61800 resources to clean up...
```
that's really a failure in `GC_Example` test and should be "influenced" by #10665
