### ISSUE TITLE
Unify scripts for dashboard and GUI.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#10668]
Now we have two vite configurations and thus two ways of building dev server (and everything else). This task is to unify the configuration (both vite.config and package.json) and stay with a single dev server, run in browser.

In this task also the relation between dashboard and GUI should be simplified: the dashboard should just have GUI as a dependency, and GUI part should not maintain any entry point invoking dashboard.

To consider: having both dashboard and current GUI in a single `app` subdir (`ide-desktop` being purely electron).

**Comment by somebody1234** [comment]
> having both dashboard and current GUI in a single `app` subdir

not sure whether this makes sense - the codebases are still significantly different (different frameworks, different architecture an the like) - and idk if there's any *advantage* in having a more nested structure in this case (two directories in `app/` vs one directory isn't a huge ifference IMO)

**Comment by somebody1234** [comment]
other things to note:
- GUI's vite script is more comprehensive, the dashboard one doesn't include the GUI
  - nor does it include HMR for vue, whereas GUI's vite script includes React HMR
- we still want *two ways to run the code* - one for simulating the Electron app with local backend support, another for simulating cloud.enso.org with no local backend support

**Comment by farmaazon** [comment]
> not sure whether this makes sense - the codebases are still significantly different (different frameworks, different architecture an the like) - and idk if there's any _advantage_ in having a more nested structure in this case (two directories in `app/` vs one directory isn't a huge ifference IMO)

The advantage is that it's more intuitively reflects the relation between different components. Also, we said about "having a single vite config" and for me it's more natural that vite config handler all things in its subdir.

**Comment by farmaazon** [comment]
Refinement notes:
* on this occasion, consider renaming `app` to `packages` - we want to put there also everything from `lib`

**Comment by farmaazon** [comment]
Refinement notes:
* lib/js/runner - to be removed.
* eslint config also is to be unified: apply dashboard rules to GUI's code and see what rules are violated.
* Renames:
  * gui2 -> project-view.
  * the main entry point: gui
