### ISSUE TITLE
Debugger doesn't show atom fields when there are multiple constructors

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#10675]
From the `InteropLibrary` perspective, an `Atom` lists all field for all constructors as *members*. But it should list just fields for the constructor that was used to construct that atom.

The `Atom` members are, e.g., displayed as fields in the chrome inspector debugger. For the following atom:
```
type My_Type
  Cons_1 f1 f2
  Cons_2 g1 g2

main =
  My_Type.Cons_1 1 2
```
we would like to see only `f1` and `f2` fields, not any other.

An example of wrongly listed fields in the debugger:
![image](https://github.com/user-attachments/assets/ba5145e1-c443-4d0f-806c-3ffb58a96b23)

All field accessors for all constructors are registered in [AtomConstuctor.collectFieldAccessors](https://github.com/enso-org/enso/blob/db4f7ab3b5976fef33a4b0c9c57d3ad243540ca4/engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/AtomConstructor.java#L317).

```[tasklist]
### Tasks
- [ ] Enable tests in [AtomInteropTest.java](https://github.com/enso-org/enso/blob/196506c114e95445daad19ad9b1db92abd80110c/engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/AtomInteropTest.java)
- [ ] Enable test in [DebugEnsoTest.java](https://github.com/enso-org/enso/blob/e54d47d8fb510250d43a2ef4c955ac2d2016c608/engine/runtime-integration-tests/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java#L484)
```

Related to:
- #10144

**Comment by JaroslavTulach** [comment]
It is annoying to see the fields of sibling Atoms in the debugger. The simplest fix is to not list them in `InteropLibrary.getMembers` as you suggest. How would the fix be related to 
- #6303
- How comes the `Atom.getMembers` messages only lists functions?
- How comes the functions aren't visible in the debugger? Does the debugger avoids displaying members that return `true` from `isMemberInvocable`?

**Comment by Akirathan** [comment]
> How comes the functions aren't visible in the debugger? Does the debugger avoids displaying members that return true from isMemberInvocable?

@JaroslavTulach Because [Atom.isMemberReadable](https://github.com/enso-org/enso/blob/f849634db379bc0826ba34d3c9001902c7c64d9b/engine/runtime/src/main/java/org/enso/interpreter/runtime/data/atom/Atom.java#L198) only returns true for constructor fields. Debugger does not avoid members that are *invocable* - it normally displays them as functions.

> How comes the Atom.getMembers messages only lists functions?

That seems like a historical inheritance. I have no idea. We should rethink the interop protocol for Atom. Let's consider the following snippet:
```
type My_Type
  Cons_1 f
  Cons_2 g
  instance_method self = 1
  static_method = 42
My_Type.extension_method self = 42

obj1 = My_Type.Cons_1 1
obj2 = My_Type.Cons_2 2
```
My proposition is:
- Members of `obj1` should be just `f` - that is, only fields of the corresponding constructor.
- In similar way, only member of `obj2` should be `g`.
- Members of `My_Type` shall be [Cons_1, Cons_2, instance_method, static_method, extension_method], that is, all methods and all constructors for the type.

For convenience, we can introduce a special *internal* member of atom called, say, `_type_` that refers to its type and one could expand it in the debugger and see all the methods on the type, similarly to how, e.g., JavaScript does that via its `[[prototype]]` internal member.

**Comment by JaroslavTulach** [comment]
With `2024.3.1-nightly.2024.7.27` version I see in Chrome Dev Tools:

![broken fields in chrome dev tools](https://github.com/user-attachments/assets/f8f6d213-d7ca-4f7f-82dd-14f2df32210a)

E.g. neither `f` or `g` field is displayed.

**Comment by JaroslavTulach** [comment]
- please also look at #6303

**Comment by JaroslavTulach** [comment]
I can confirm that the debugging experience in VSCode and `runEngineDistribution --debug` is great and doesn't need any urgent improvements!

![debug](https://github.com/user-attachments/assets/bd4a5005-5cda-4db5-8ed2-c70215fcce37)
