### ISSUE TITLE
Scroll bars on the graph editor background should be visible when they have somewhere to scroll

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10681]
Scroll bars on the graph editor background should be visible when they have somewhere to scroll (In the same way as the doc panel and code editor scroll bars appear when there is something to scroll.)

They should still be invisible when there is nothing to scroll, but still appear when moused over as they do today

**Comment by farmaazon** [comment]
Refinement notes:
* Let's keep the old behavior under some scrollbar component's flag.
