### ISSUE TITLE
Full Screen Mode Changes

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10686]
This story makes a  number of changes to full screen mode for Vizs and adds full screen mode for the doc panel and code editor panel.

1. Full screening the Visualisation should only full screen inside the project view (without tabs).

![image](https://github.com/user-attachments/assets/56f38abb-1a7b-4d2c-a8d7-dd376945bdac)

The full screen mode should not be saved when the project is closed.

2. Add a full screen button to the doc panel

![image](https://github.com/user-attachments/assets/d5446ae2-4f22-4192-beb5-214797576883)

![image](https://github.com/user-attachments/assets/6746f7d7-13fe-43b0-b266-f3a1dad938cd)

3. Add a full screen button to the code edit panel

![image](https://github.com/user-attachments/assets/5d4b5435-f72c-4d5e-ad03-bc4f2a1e1265)

**Comment by farmaazon** [comment]
Refinement notes:
* We may use teleport for docs and code: exactly the same way visualizations are done now. This is probably the easiest.
