### ISSUE TITLE
Add inputs to grouped components

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10696]
In the same way that we have an output component inside a grouped component we should also have inputs

![image](https://github.com/user-attachments/assets/305c0c81-ceb9-42ef-a156-313a9710b05c)

![image](https://github.com/user-attachments/assets/29b2b9f7-4815-43b2-936a-e3aaaf914cef)

These inputs cannot be deleted or edited.
They are autogenerated from the collapsed function's signature.

**Comment by farmaazon** [comment]
Refinement note:
* The connections from inputs are already returned by alias analyzer, but are filtered in graph db at some lever. It needs to be restored, and properly interpreted. Also, the graph needs to be constructed from the entire function definition, not only body.
* The placement algorithm should store input nodes in a single row, left to right
* Make sure the metadata of input nodes (their position) is stored in the file.
