### ISSUE TITLE
No suggestions for Snowflake

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10716]
<img width="1373" alt="image" src="https://github.com/user-attachments/assets/229ebea6-b894-43aa-bcbb-883f610362ef">

connection does work if I manually add components by typing them

<img width="1367" alt="image" src="https://github.com/user-attachments/assets/71c0f5fb-63eb-4f41-97a0-ed4f0c274603">

**Comment by radeusgd** [comment]
I'm also having the same problem and it feels like this may be helpful in investigation:
![image](https://github.com/user-attachments/assets/4775364d-c83f-40eb-a0a7-caace878bbba)

**Comment by GregoryTravis** [comment]
Probably needs a `to_js_object` on the Snowflake connection.
