### ISSUE TITLE
Record button appears to execute the node twice

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10730]
Notice a simple program 
![Screenshot from 2024-08-01 12-06-45](https://github.com/user-attachments/assets/48320452-e687-411a-b48a-06f99ff8a771)

File `test.txt` didn't exist before clicking on the record button.
Once enabled this is the contents of the file:
```
testtest
```
suggesting that the node was executed twice.

**Comment by hubertp** [comment]
The scenario is as follows:
1. triggering the record button kicks of a full compilation and then execution
2. GUI sends the `attachVisualization` request for `.write` **when** record button is selected

Re 1: that's all as expected
Re 2: Attaching a visualization also may trigger an execution. So that's also kind of expected.

**Comment by farmaazon** [comment]
@hubertp does GUI attach visualization even if there is no visualization shown under the node (like in the screenshot)?

**Comment by hubertp** [comment]
> @hubertp does GUI attach visualization even if there is no visualization shown under the node (like in the screenshot)?

Yes.

**Comment by hubertp** [comment]
@4e6 suggested that this could be an opportunity to provide _a proper_ support for record button rather than via this `Standard.Base.Runtime.with_enabled_context Standard.Base.Runtime.Context.Output` prefix hack. 
Therefore rather than triggering it via a text edit (and later attaching a visualization), GUI would send a request to execute a particular node with a specific execution environment. This would also fix https://github.com/enso-org/enso/issues/10719

**Comment by farmaazon** [comment]
> > @hubertp does GUI attach visualization even if there is no visualization shown under the node (like in the screenshot)?
> 
> Yes.

Then I think there is some GUI issue too. We should not attach viz on the entire `write` node - only on it's `this` argument, to get widget dynamic configs (maybe we try to get default viz? But I think we should do that only when it's visible anyway).

**Comment by farmaazon** [comment]
Ok, I know what happens on GUI side: when record button is pressed and code changed, we invalidate information about method call. Without method call, we actually don't know how to ask about widgets, so we set our visualization config to `null` what is then interpreted as request to detach the visualization.

I'm not sure if there is an easy and still sound way to fix that... Maybe we could update visualization. Or just wait for new recording API (without code changes), so there will be no code change and thus no visualization reattachment.

**Comment by hubertp** [comment]
> Or just wait for new recording API (without code changes), so there will be no code change and thus no visualization reattachment.

@farmaazon After a length discussion we decided against that.

**Comment by farmaazon** [comment]
And visualization update also does not fix the problem. But I assumed #10785 fixes the original issue of double-writes?

**Comment by JaroslavTulach** [comment]
It seems to work according to @jdunkerley
