### ISSUE TITLE
Create a native-image from (GraalVM) ydoc implementation

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10757]
Since we are planning on dockering Ydoc (https://github.com/enso-org/enso/issues/10751) it seems beneficial to have an easy way to switch between NodeJS and GraalVM implementations. The latter is clearly at an disadvantage when interpreter therefore it makes sense to create a native-image for it and speedup the startup.

**Comment by 4e6** [comment]
The native image does not support virtual threads together with the Truffle languages. The #10783 reproduces the issue, and [4e6/helidon-quickstart-se](https://github.com/4e6/helidon-quickstart-se) provides a minified example. The support should be [added](https://github.com/oracle/graal/issues/7520#issuecomment-2158154839) in Truffle 24.1.
