### ISSUE TITLE
Improve `to_display_text` for errors

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#10770]
Issues like https://github.com/enso-org/enso/issues/10750 are horrible to debug with a plain error atom name, e.g. `No_Such_Method`.

**Comment by jdunkerley** [comment]
Reviewed the `No_Such_Method` type. It has the `to_display_text` properly set up.
I'm guessing it is an issue in `engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java` as to why the Java Exception is not showing the display text.

It looks like `computeMessage` will attempt to call the `to_display_text` via the `InteropLibrary` and fall back to the type name if it doesn't exist.

**Comment by JaroslavTulach** [comment]
How exactly do we plan to tackle this issue? 

> it is an issue in engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicException.java as to why the Java Exception is not showing the display text.
> computeMessage will attempt to call the to_display_text via the InteropLibrary and fall back to the type name if it doesn't exist.

Are we supposed to dump more info when such a situation happens?
