### ISSUE TITLE
Add dropdown indicator arrows to the table Viz menu buttons

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10809]
These two buttons should have always visible dropdown arrows to indicate they are menus not just buttons

<img width="67" alt="image" src="https://github.com/user-attachments/assets/586a52cc-a7f1-4ddf-87e4-2325fc40ece0">

**Comment by farmaazon** [comment]
Refinement notes:
* we have the drop-down component which displays the button: add arrow there and use it.
