### ISSUE TITLE
Speedup `EnsoRootNode.buildFrameDescriptor`

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#10843]
Follow-up of https://github.com/enso-org/enso/pull/10837 and #10729, part of #10833.

https://github.com/enso-org/enso/blob/396d70ddc0184473d42146a440b23226221f1f3e/engine/runtime/src/main/java/org/enso/interpreter/node/EnsoRootNode.java#L65-L74

still uses `LocalScope.scope().allDefinitions()` that forces deserialization of alias analysis metadata for every `EnsoRootNode` created, that is created for at least every Enso method. Let's remove the dependency on alias metadata from `EnsoRootNode`. Optimally, we should use only [FramePointer metadata](https://github.com/enso-org/enso/blob/53e99809e2452be46d59c1e313a8d82fbd81f656/engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/FramePointerAnalysis.scala#L387) for that.

Further notes in https://github.com/enso-org/enso/pull/10837#issuecomment-2293766695

**Comment by JaroslavTulach** [comment]
Looks like `FramePointer` will not be enough. I need to associate result of `allDefinitions()` with every IR that contains `AliasMetadata.RootScope` I think now.
