### ISSUE TITLE
Single Figma project with designs

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#10866]
Instead of multitude projects with different numbers, it's better to have a single project with proper version control: research what is possible in figma.

**Comment by AdRiley** [comment]
![Image](https://github.com/user-attachments/assets/83e3cd5e-4b6b-46dc-ae4e-a97d25982fdc)

Figma has a version history feature that we can use. It has auto-saves. But more usefully for us it has named versions that we can use as checkpoints. As shown in the screenshot above.
