### ISSUE TITLE
Intermittent deletion failures

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#10888]
Sometimes when deleting multiple components, some components are only partially deleted, and remain in the graph in a non-functional state.

I think this is probably related to the `Changed the client-id because another client seems to be using it.` that appears in the logs when multiple components are deleted.

(Reported by @jdunkerley; I have been able to reproduce it once, but not since)

**Comment by vitvakatu** [comment]
#10889 did not fix the issue when removing multiple connected nodes:


https://github.com/user-attachments/assets/f3beffb0-22e6-461d-b8ee-a701a269ae19
