### ISSUE TITLE
Dragging a file on to Graph Editor background in Cloud mode is not uploading file

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10948]
If you drag a file on to Graph Editor background in Cloud mode it is not uploading file, but instead freezes.

At best we should upload the file.
At minimum we should do nothing/error/warn.

**Comment by Frizi** [comment]
I did reproduce the issue only once, where the upload started but didn't progress at all. I'm not able to trigger it again, seemingly all cloud uploads work just fine for me since then. Are there any reliable reproduction steps?
