### ISSUE TITLE
Switching Data.read to Delimited and then to Auto Detect leaves extra arguments in the component

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10962]

**Comment by vitvakatu** [comment]
Can’t reproduce as of `2819b42fd543892b9eae584ebc8881d72a2a0138`.

**Comment by jdunkerley** [comment]
![image](https://github.com/user-attachments/assets/1c5efd02-2853-493f-bf41-72ccaa0b2cb6)

Open new project
Click on format and choose Delimited
Click out
Then go back and switch to Auto_Detect
and argument gets left behind

On nightlyt 6th Sept

**Comment by vitvakatu** [comment]
Reproducible in Electron build only.

**Comment by vitvakatu** [comment]
Not reproducible on the current nightly, so it was fixed by one of the changes to the engine.
