### ISSUE TITLE
Can't add New Projects to empty favorite folder

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#10998]
Reproduction steps

- Create an empty folder outside of enso
- Add it to local using the Add Folder button
<img width="156" alt="image" src="https://github.com/user-attachments/assets/59353137-450e-4c5c-95bf-9c2196ddd5a0">

- Click on EmptyFolder in Enso
- Click on New Empty Project

Expected behaviour:
A new project gets created in EmptyFolder

Actual behaviour:
A new project gets created in my default local folder

Version 2024.4.1-nightly.2024.9.6
Build 6c80f8f05eac7ebe5dfd8479e81458f5ba2f1185
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.4.1-nightly.2024.9.6 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

**Comment by AdRiley** [comment]
The new folder button also has the same behaviour

**Comment by PabloBuchu** [comment]
Closing as it seems fixed.
