### ISSUE TITLE
When entering edit mode on a component the `+` button appears on the node

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#11011]
![Image](https://github.com/user-attachments/assets/80740a48-b6dc-4459-8118-5cef311b6206)

**Comment by farmaazon** [comment]
What exactly is the problem? The plus button is there as designed (it accepts the input in this mode).

Or the problem is that the input should be extended to fit the entire expression?

**Comment by sylwiabr** [comment]
It looks like it is here by mistake - doesn't look like a button. Also accepting with a `+` pretty often results with an error 
<img width="502" alt="image" src="https://github.com/user-attachments/assets/71cde1f9-bc2a-4e8b-af0e-471cca80e379">

**Comment by farmaazon** [comment]
The impression may come from lack of clear gap between cut input and the buttons. Also, the icon should be different, but there is still no design how. We may also make the CB input auto-resizible.

I don't reproduce the error in simple cases: it must be some specific nodes. The `+` logic should be exactly the same as pressing enter.
