### ISSUE TITLE
Discrepancies in LS responses between dev and Electron mode

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11028]
As reported internally:

> We currently observe distinct behavior between IDE dev mode and the built Electron version; different messages (order and content) come from the language server.
More specifically, in Electron, we’re getting seemingly incorrect messages, as in the screenshot. Take a look at methodCall and type fields – they contradict each other, so this expression update is incorrect.

> However, we see different behavior when running the engine manually as part of the dev mode – this invalid message still comes, but then it is fixed by the next expression update (second and third screenshots)
Engine version are of course the same, only difference is Electron/not Electron.

<img width="628" alt="image" src="https://github.com/user-attachments/assets/863d6159-be9d-4a83-8ebe-6e56844d2d08">
<img width="811" alt="image2" src="https://github.com/user-attachments/assets/9e4ae2b6-dd63-4635-b11f-88592aa9ae74">
<img width="611" alt="image3" src="https://github.com/user-attachments/assets/e03af8e6-e426-4271-94f6-ae87f7b14152">

**Comment by vitvakatu** [comment]
Related: #10962

**Comment by vitvakatu** [comment]
Steps to reproduce: 
- Create an empty project
- Switch `format` to `Delimited`
- Switch `format` to `Auto Detect`
- In communication with the engine, observe invalid expression update (a bunch of ids will be updated, but the one we’re interested in usually comes first in a batch, and it has `Auto_Detect` type info.


https://github.com/user-attachments/assets/da50ebd8-ccbd-4936-82f1-55448e561d10

**Comment by hubertp** [comment]
I can reproduce on Electron
