### ISSUE TITLE
Some dynamic widgets are still not loading on startup

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11051]
Occasionally GUI will not send `attachVisualization` request for some expressions resulting in no widgets for the node.

![Screenshot from 2024-09-11 11-47-35](https://github.com/user-attachments/assets/18f47d12-f6a0-4e16-a560-4e6968ea73cd)
![Screenshot from 2024-09-11 11-11-04](https://github.com/user-attachments/assets/ce56f9dd-a465-4fdb-9317-7f27973c701e)

The expression updates appear to be random.
Potentially related to #11028.

**Comment by JaroslavTulach** [comment]
Fixed.
