### ISSUE TITLE
Parse dropdown too narrow to see examples

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11106]
<img width="718" alt="image" src="https://github.com/user-attachments/assets/df0d5864-3c6e-4cbd-ab88-58ae948c7b12">

Can we just make the dropdown as wide as the longest option?

**Comment by Frizi** [comment]
Let's make the max width a bit larger to fit common date formats. The list elements are supposed to have scrolling text on hover, so this functionality is currently broken for unknown reason.

**Comment by vitvakatu** [comment]
Closed in https://github.com/enso-org/enso/pull/11608
