### ISSUE TITLE
No headers detection for a simple .csv file

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11129]
`Data.read` a [simple file](https://github.com/user-attachments/files/17057652/short_summary.csv).
![Screenshot from 2024-09-19 12-36-22](https://github.com/user-attachments/assets/4426066b-fde3-4cd4-946e-f05047b7665a)

I would expect `AutoDetect` to be smart enough to detect headers?

**Comment by GregoryTravis** [comment]
What we already have is as smart as we expect to be.
