### ISSUE TITLE
Grouped Components - Add open button on the component drop menu

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11179]
There should be a button on the component drop menu to open collapsed components.

It should be present for collapsed functions only.

The text should be Open Grouped Components

It should be in position 2 (below the Viz menu option)

Clicking the new button is equivalent to the double click functionality we have today.

Use icon open

![Image](https://github.com/user-attachments/assets/e85f14d4-8ea8-4f2d-9973-ea71d020de41)

**Comment by farmaazon** [comment]
Refinement notes:
* replace edit button instead of record button, as it is simpler to replace (record button sometimes stays visible) + the functionality is more useful on collapsed nodes.
