### ISSUE TITLE
Ability to rename grouped components inputs

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11180]
![image](https://github.com/user-attachments/assets/34049916-55ff-4cdb-ae5d-2f7e8563bdf5)

Clicking on the inputs name should allow editing it and propagation of rename through the graph

**Comment by farmaazon** [comment]
Refinement notes:
* We should do it ourselves, instead of using LS feature for refactoring - it's simple while being also synchronous.
* We skip changing name at the call site (like `Main.collapsed1 integer1=integer1`)  - this is rare situation.

**Comment by farmaazon** [comment]
From product meeting: we use "edit" button for it.

**Comment by farmaazon** [comment]
Closing in favor of the new design in https://github.com/enso-org/enso/issues/11181
