### ISSUE TITLE
Grouped Components - Undoing node collapsing inside collapsed functions breaks graph editor

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#11211]
To reproduce:
1. Create a collapsed function.
2. Enter it
3. Press Undo (`⌘+Z`)
4. Observe broken graph editor and errors in console.

We discussed that we want to manage undos better (let's consider separate undo stacks for different graphs), but we also need to make sure the graph shows something reasonable when the function gets deleted.

https://github.com/user-attachments/assets/af5715d3-f56b-436c-8263-4ad572c5748b

**Comment by farmaazon** [comment]
Refinement notes:
* If the definition does not exist anymore, hide the graph and display the information. User should be able to click breadcrumbs to recover.
* We could also display the information (about graph existence) in the crumbs.
* The information from point 1 should be a new component, not a toast.
