### ISSUE TITLE
Add Undo/Redo buttons

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11222]
Add Undo/Redo buttons to the graph editor

![image](https://github.com/user-attachments/assets/e821667c-0c66-42f5-9146-c6b2d7b77e6b)

They should go on the top bar to the right of Refresh/Play.

As part of this story can we re-size refresh/play width so the curve of the inner circle matches the edge?

![image](https://github.com/user-attachments/assets/03b183cc-8724-46c8-8fa6-2c264e17dae1)

**Comment by farmaazon** [comment]
Refinement notes:
* Disable button if there is nothing on undo/redo stack.
