### ISSUE TITLE
New Component Menu Design

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11244]
Update the component menu as per design here https://docs.google.com/document/d/1hvDEBDTVKiG-mcCeFPGajyxsVVjRkLytp2PrQpo80CI/edit?usp=sharing

![image](https://github.com/user-attachments/assets/8ba82778-3453-46fd-bd84-5a25d9847459)

![image](https://github.com/user-attachments/assets/b766f003-1671-4b2b-9ff0-643c4c49cfb6)

**Comment by farmaazon** [comment]
Refinement notes:
* Ask @AdRiley for exact options and their order.
* Leave the old color picker - it will be updated (and re-designed) in a seperate issue,
* For menu, use same icon as the button in top-right corner.
