### ISSUE TITLE
OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#11260]
I'm consistently getting a OOM error in the Project Manager process shortly after opening the *Selecting and Joining Data* example project (various stack traces; the allocation that fails is not consistent at all). The crash occurs with a used heap size of 2GB (25% of the physical memory on the M1 Mac I'm testing on).

**Comment by JaroslavTulach** [comment]
Hello Kaz, are you sure the `OOM` error comes from `project-manager` process? Then I remove the _compiler label_. It would be good to provide some additional information about the crash. The best would be to get heap dump when the OOM error happens.

Are you (can you) build the `project-manager` executable yourself? In such case we:
- either need to specify some flags to _native image_ when building the executable
- or we can run the JVM version just specify runtime options

Let's try the JVM variant first:

### Running `project-manager` as a JVM Process

Running `sbt` command:
```
sbt:enso> project-manager/assembly
```
generates `project-manager.jar`. Running that JAR as:
```
java -XX:+HeapDumpOnOutOfMemoryError -jar project-manager.jar
```
and reproducing the `OutOfMemoryError` should generate an `.hprof` file, print its location on console and only then crash. Having such `.hprof` file would allow us to evaluate its content and guess what is actually going wrong in there.

**Comment by JaroslavTulach** [comment]
Hello Kaz, unless you can provide more information, this cannot be reproduced neither evaluated.
