### ISSUE TITLE
enso --jvm fails with InvalidModuleDescriptorException

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#11274]
Enso built with `engine-runner/buildNativeImage` fails when given `--jvm` cmd line opt with:
```
$ enso --jvm --run tmp.enso
Error occurred during initialization of boot layer
java.lang.module.FindException: Error reading module: /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/component/helidon-webclient-websocket-4.0.8.jar
Caused by: java.lang.module.InvalidModuleDescriptorException: Unsupported major.minor version 65.0
```

Broken with #10823.

```[tasklist]
### Tasks
- [x] Fix the `--jvm` cmd line opt for native image
- [ ] Add test that this works on a simple script
```

**Comment by Akirathan** [comment]
Works locally on @JaroslavTulach's machine, but not on mine. Probably `--jvm` does not pick the correct Java version.

**Comment by JaroslavTulach** [comment]
> Works locally on @JaroslavTulach's machine, but not on mine. Probably `--jvm` does not pick the correct Java version.

According to [the launcher code](https://github.com/enso-org/enso/blob/develop/engine/runner/src/main/java/org/enso/runner/Main.java#L1329) the `--jvm` option takes a parameter. Please verify you still see the problems when providing path to the right GraalVM.

**Comment by JaroslavTulach** [comment]
If the `--jvm` option is used without a path, then the code uses [distribution manager runtimes](https://github.com/enso-org/enso/blob/develop/engine/runner/src/main/java/org/enso/runner/Main.java#L1344) to search for a JDK. I cannot say this logic is fully correct. Can we make it better? How? Record JDK version when building _native image_ executable and search/prefer JDK with the same _implementation version_, then with the same (or newer) _specification version_, etc.? This is slightly in flux, given the whole NI support isn't yet in production, but having some vision/plan wouldn't hurt.

**Comment by JaroslavTulach** [comment]
As a last resort, the system [falls back to system `java` executable](https://github.com/enso-org/enso/blob/develop/engine/runner/src/main/java/org/enso/runner/Main.java#L1354). That's probably not a good idea at all. We should:
- report a warning (at least) that such a situation happens
- verify JVM version (by running `java -version`) and [check the version](https://github.com/enso-org/enso/issues/11274#issuecomment-2418580311) to be at least basically compatible - e.g. reject anything lower than JDK21.
- detect the failure and provide instructions how to use `--jvm with_path` to fix the problem

Pavel, please add the warning and check on your system what's happening. Is it _too old system Java_?

**Comment by JaroslavTulach** [comment]
Quote from #11500:

> the distribution manager's runtime (on my system located in ~/.local/share/enso/runtime) and it used the first runtime found. But the first runtime on my system is JDK 17.

Please accompany the layout of your `~/.local/share/enso/runtime` directory with this bug report. Only with such information this bug report is reproducible.
