### ISSUE TITLE
Rename symbol handler does not rename symbol usages

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11281]
Applying an edit in GUI appears to only change the function's definition name but not its usages:
[Kazam_screencast_00014.webm](https://github.com/user-attachments/assets/53764c68-0702-4a58-8417-2448dfde5ec8)

Tracked it down to [RefactoringRenameJob](https://github.com/enso-org/enso/blob/develop/engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/RefactoringRenameJob.scala#L110) which only infers edits for the function name.

**Comment by 4e6** [comment]
Works for me on the current develop 

https://github.com/user-attachments/assets/46344ff4-ed5f-40c3-8b1b-91b7fc77d3a4

**Comment by hubertp** [comment]
@hubertp needs to verify the current state

**Comment by hubertp** [comment]
You tested if function is referenced via the full name, including the modules' name. This might not necessarily be the case:
-  https://github.com/user-attachments/assets/e4537960-17b1-4f2e-90a4-8b92d812caba
- https://github.com/user-attachments/assets/11d89364-a78b-4254-a000-bf80fe4e64ac

**Comment by hubertp** [comment]
Maybe in that sense, it's not a regression as that particular case never worked 🤔

**Comment by 4e6** [comment]
The reason that unqualified `collapsed` method calls were not supported is that in this case, the method resolution happens in runtime, and there is not enough information to ensure that the `collapsed` symbol refers to the `Main.collapsed` method call. 

Consider the following example:
```py
collapsed = ""

main =
    operator1 = Main.collapsed
    operator2 = collapsed
    operator3 = operator2.collapsed
```

Only in the first case the static analysis can reliably infer the method call. The second case is tricky but we can rely on the fact that it is a method call with a synthetic first argument that should probably resolve to this module. In the third case, we can see that it is not the call of a static method, so we should ignore it.

In the end, I think I can make it work, but it will rely on assumptions at the call site
