### ISSUE TITLE
Populate the Suggestions Database with Imported Modules

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#1130]
### Summary

The Suggestions database is populated on module compilation and only contains entries from the compiled module itself. Suggestion entries from the imported modules should be also a part of the suggestions database.

### Value

The user has a complete list of suggestions available in the current scope.

### Specification

- [ ] When analyzing the module, use the `ImportResolver` to get the list of imported modules and run the `SuggestionBuilder` on them.

### Acceptance Criteria & Test Cases

- Suggestions Database contains entries from the imported modules.

**Comment by mwu-tow** [comment]
It should not include just the imported modules, it should include all modules that could be imported.
The primary use-case for node searcher in the IDE assumes that called function might require adding a new import to the module.

**Comment by iamrecursion** [comment]
Just to be clear, the suggestions database needs to contain the module where a symbol is defined, and it should be populated with all available symbols (all registered dependencies) of the current project.

**Comment by farmaazon** [comment]
> It should not include just the imported modules, it should include all modules that could be imported.
The primary use-case for node searcher in the IDE assumes that called function might require adding a new import to the module.

> Just to be clear, the suggestions database needs to contain the module where a symbol is defined, and it should be populated with all available symbols (all registered dependencies) of the current project.

The issue is closed, however the PR and commit description suggest, that the above comments were not addressed? @4e6 @iamrecursion ?
