### ISSUE TITLE
Populate `Data.list` name filter from `File_Format.name_patterns`

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#11310]
Values for `name_filter` come from `File_Format.name_patterns`

```
Data.list
    directory:File
    name_filter:(Text | Vector Text) = []
    -> Vector File
```

`File_Format.name_patterns` is a list of extensions and extension groups to each `File_Format`. 

The patterns will include single extensions or groups of extensions, along with a GUI-friendly description.

```
File_Format.name_patterns
    -> Vector Text
```

Example:

```
file_format.name_patterns =>
[[[“csv”], “CSV Files”], [[“tab”], “Tab Delimited”], [[“csv”, “tab”], “Delimited Flat Files”]
```

**Comment by radeusgd** [comment]
1. Make sure `name_filter` works (tests)
2. Add `name_patterns`
3. Add widget for `name_filter` based on `name_patterns`
	i. 'All known patterns' that accepts all patterns known by loaded file formats
    ii. 'All files' - `*.*`
