### ISSUE TITLE
Unexpected Type_Error/Method unknown on project startup

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#11325]
Encountering regularly in a project a missing method Panic such as:
![Screenshot from 2024-10-15 09-56-59](https://github.com/user-attachments/assets/e00edb63-3ec4-49f7-a4ce-070c190714a7)

Surprisingly, when we refresh the project, it disappears. Similarly, if (IR) caches for the project are there, the project will also continue to load without hiccups.

**Comment by hubertp** [comment]
Turns out that `In_Any` is first type checked with expected `Columns_To_Keep` type and next with `Match_Colums`. The later is obviously wrong and leads to failures.

**Comment by hubertp** [comment]
Update: looks like the last argument in `.union node2 ..In_Any ..By_Name` application is actually treated as cached and unresolved constructor `..By_Name` is not even resolved. Instead, instrumentation identifies that node as already cached and returns `In_Any` for `..By_Name`, which is clearly wrong.

The reason why instrumented appears to re-use the result is, at it seems, that we index by the context's instrumented node which seems to be the actual application.

**Comment by hubertp** [comment]
One more info:
In an application of `any1.union node2 ..In_Any ..By_Name` we have to resolve `UnresolvedConstructor` for both arguments using the type information. Arguments/closures of `..In_Any` and `..By_Name` will both construct an application on the fly https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java#L173.
The problem is that such applications will get **the same** UUID, as per [search logic](https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java#L178). So when `..In_Any` is resolved and cached, the next argument re-uses that value from the cache i.e. `..By_Name` resolution is skipped and instrumentation immediately returns a (wrong) cached value, `Columns_To_Keep.In_Any`.

Pinging @JaroslavTulach, as he wrote that logic initially.

Not yet sure, why on refresh it somehow manages to **not** report type failures.

<blockquote><img src="https://opengraph.githubassets.com/0f7437b04babedcdec9e791ca2f0822ab296caa6109c5d55667d9475ee8ce4df/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java">enso/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java at develop · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by JaroslavTulach** [comment]
Thanks a lot for the detailed investigation. Yes, we have to improve the [search logic](https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/UnresolvedConstructor.java#L178).

That means the issue goes towards me (unless you want to have some Truffle fun).

**Comment by hubertp** [comment]
> That means the issue goes towards me (unless you want to have some Truffle fun).

Don't take all the fun to yourself. I can tackle it.

**Comment by hubertp** [comment]
The reason why initially we get the type error and later it disappears is because of... ID maps. Initially, `..In_Any` or `..By_Name` have no UUID. With empty location it uses the search path to discover the first parent application and then ID/caching conflicts happen, as described above.
Later, ID map will arrive from GUI and type error disappears. Unfortunately it looks like the resulting Panic persists causing method not found problems.

I would claim that even the first type error should not be happen/be displayed to the user as it causes confusion.

**Comment by JaroslavTulach** [comment]
> even the first type error should not be happen(ing)

No, the error shall not be happening regardless of UUIDs.

Does the error happen in CLI?
Can it happen in CLI with `runtime-execution-instrument` enabled?

> it uses the search path to discover the first parent application

What is the stacktrace when the path is being discovered? By whom? Who needs it?

**Comment by hubertp** [comment]
> Does the error happen in CLI? Can it happen in CLI with `runtime-execution-instrument` enabled?

No, because there are no UUIDs.

> > it uses the search path to discover the first parent application
> 
> What is the stacktrace when the path is being discovered? By whom? Who needs it?

That's something I was hoping you will have the answer since you added that search-via-parent path. I'm guessing you wanted to cache the results? No UUID no caching.

**Comment by JaroslavTulach** [comment]
> > Does the error happen in CLI? Can it happen in CLI with `runtime-execution-instrument` enabled?
> 
> No, because there are no UUIDs.

You can add UUID and used them even from CLI. Demo is in [Instrumentor_Spec.enso](https://github.com/enso-org/enso/blob/fb8c4922eb7dc27f30d3f6a94e594b11b679e0f1/test/Base_Tests/src/Semantic/Instrumentor_Spec.enso#L4).

> 
> > > it uses the search path to discover the first parent application
> > 
> > 
> > What is the stacktrace when the path is being discovered? By whom? Who needs it?
> 
> That's something I was hoping you will have the answer since you added that search-via-parent path. 

I can take over and debug the problem. Then I am sure I will see the stacktrace. Or you just paste it here to remind me where is the code we are talking about!
