### ISSUE TITLE
Deadlock on Execution Interruption

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1135]
### General Summary
When testing for the ability to interrupt execution the runtime sometimes deadlocks. This occurs much more frequently on macOS than other platforms, but I've also observed it happen on Windows.

### Steps to Reproduce

1. Execute the `engine` tests in a loop until it deadlocks.
2. It is, of course, a heisenbug, but if you can trigger it with a debugger active it's possible to observe the nature of the hang.

### Expected Result
Code execution should be interrupted successfully no matter what.

### Actual Result
The RTS deadlocks while trying to interrupt execution of Enso code.

### Enso Version

```
033ccd5aecf004dc69a37e36e3d32e17de29cb43
```

**Comment by radeusgd** [comment]
I think I have observed it happen on Linux too - I haven't been able to investigate if this is exactly the described issue, but from time to time when running `runtime/test` it would take ages to complete (and I would terminate it manually), so it's likely it was encountering this deadlock.

**Comment by iamrecursion** [comment]
Closed in #1166.
