### ISSUE TITLE
Table Editor Widget - Pasting tabular data should paste as Table.input

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11350]
When we paste tabular data (e.g. from table viz) we should paste as a Table.input not .to Table

**Comment by farmaazon** [comment]
Refinement notes:
* If data is copied from AgGrid with "with headers" option, the pasted data in enso should recognize it and use these headers as column names. So the copy handler should consider it when putting enso code to the clipboard.
* Remember about cases of newlines, tables (and quotes) in copied data - check how they are handled in other tools.

**Comment by farmaazon** [comment]
After recent changes, it should be Table.input.
