### ISSUE TITLE
Clicking out of code edit mode on a component should commit the change not discard it

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11360]
When editing a component in code edit mode, clicking out of that component should commit the change.
Pressing escape should discard the change

**Comment by farmaazon** [comment]
I assume the behavior of click-out when _adding_ a new node should stay the same, i.e. we discard the input and don't create a node?

**Comment by AdRiley** [comment]
Yes. That's correct.

**Comment by farmaazon** [comment]
Refinement notes:
* When creating a new node, we should actually see what is the CB mode: when browsing components, clicking off should hide CB and not create any node, when editing code, clicking-off should accept the current content (except when empty)
