### ISSUE TITLE
Implement Indexing Shorthand for Vectors

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1136]
### Summary
On the design issue for vectors (#496), we decided that we should provide a `!` indexing operator for vectors. This should be done once unblocked by the implementation of #1127.

### Value
Code that makes heavy use of numeric vectors will have a clean shorthand for indexing into them.

### Specification

- Define the `!` operator as an alias for the vector `at` method.
- Test it.

### Acceptance Criteria & Test Cases

- We have the `!` operator for indexing into vectors.

**Comment by kustosz** [comment]
`!` is reserved for error types, alternatives are ugly, life is suffering.
