### ISSUE TITLE
Resuming from hibernation crashes the application (Windows)

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#11389]
On a laptop waking back up, the application reports the following error:
![image](https://github.com/user-attachments/assets/16a7d7e1-b4f8-42bd-a44f-24c321fde2f6)

This was the JSON port of the language server:
`[org.enso.languageserver.boot.LanguageServerComponent] Started server at json:127.0.0.1:60829,`

**Comment by hubertp** [comment]
I will test it as well on some old WIndows machine

**Comment by hubertp** [comment]
I can confirm. From the logs it looks like something requests a shutdown. Will investigate. For the moment unassigning GUI unless I confirm otherwise.

**Comment by hubertp** [comment]
This has been fixed a while ago, at least the backend part, in
- #7470
- #7729

So it appears to be a regression. On the other hand, it does not seem to trigger the delayed shutdown logic and it only happens on Windows, so could be a new bug.

**Comment by hubertp** [comment]
> Tested polyglot version of NodeJS 

That obviously meant polyglot version of Ydoc

**Comment by hubertp** [comment]
Fun fact. Even project manager doesn't work after suspend.

**Comment by hubertp** [comment]
Closed via #11712 **and** #11739
