### ISSUE TITLE
Improve selection visibility when editing text widgets

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11397]
Today text selection looks like this

<img width="1625" alt="image" src="https://github.com/user-attachments/assets/2f47a763-d096-4228-8492-e43d0fcf04a8">

It is difficult to see the text is selected as we also highlight the currently selected/edited widget.

Propose that instead of highlighting the selected widget, we lowlight it.

<img width="924" alt="image" src="https://github.com/user-attachments/assets/4cbbc8d2-8f38-4f41-9718-962f06ca7392">

This increases contrast between the selection and its background.

We should also ensure that the text edit caret/cursor is 100% opaque and 100% white. User's are struggling to find it.

Happy to sit with whoever implements this and choose the actual levels for the lowlight/highlights together.

**Comment by farmaazon** [comment]
Merging with #11432
