### ISSUE TITLE
Distinguish between Selected/Hovered Components Spike

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11432]
This story is to book a live coding session with @AdRiley and @wdanilo to investigate how to distinguish between hovered and selected 
components.

From @wdanilo  "I want to test it live in the app. A very nice approach is to make "hovered" slightly less intensive then selected. So if selected has vivid colors,hovered might be the same but with dull ones. Lets try it out and see how it feels. "

**Comment by farmaazon** [comment]
on hold until all design meetings end.

**Comment by farmaazon** [comment]
The design of new selection (and more) is now inside #11510
