### ISSUE TITLE
Random GUI Check CI failures.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#11458]
**Note to anyone adding entries here**: Please remember to download the report and upload it here before re-running your failed action, because re-running erases old artifacts.

```[tasklist]
### Dashboard
- [ ] #11449 [Report](https://github.com/enso-org/enso/actions/runs/11608023936/artifacts/2127048992) **4 times on develop**
- [ ] [`assetsTableFeatures.spec.ts › can drop onto root directory dropzone`](https://github.com/enso-org/enso/actions/runs/11608191792/job/32322965278#step:7:579) [Report](https://github.com/user-attachments/files/17585629/gui-playwright-report.zip)
- [ ] [`delete.spec.ts:28:6 › delete and restore (keyboard) › Expect trash placeholder row`](https://github.com/enso-org/enso/actions/runs/11592078353/job/32273187796#step:7:601) [Report](https://github.com/enso-org/enso/actions/runs/11592078353/artifacts/2122571007)
- [ ] [`assetsTableFeatures.spec.ts:40:6 › extra columns should stick to top of scroll container`](https://github.com/enso-org/enso/actions/runs/11590473334/job/32268119577#step:7:645) [Report](https://github.com/enso-org/enso/actions/runs/11590473334/artifacts/2122108247)
- [ ] [`[Dashboard] › e2e/dashboard/assetSearchBar.spec.ts:24:6 › tags (negative) › Login › Accept Terms and Conditions`](https://github.com/enso-org/enso/actions/runs/11835474433/job/32980802524?pr=11551#step:7:885) No report
```

```[tasklist]
### Project View
- [ ] [Browser crash and many tests fail on start](https://github.com/enso-org/enso/actions/runs/11681103703/job/32534992167#step:7:1102) [Report](https://github.com/user-attachments/files/17634848/gui-playwright-report.zip)
```

```[tasklist]
### Deeply Magical ✨
- [x] [`typecheck: esbuildConfig.ts(52,15): error TS2322: Type 'import("/runner/_work/enso/enso/node_modules/.pnpm/esbuild@0.23.0/node_modules/esbuild/lib/main").Plugin' is not assignable to type 'import("/runner/_work/enso/enso/node_modules/.pnpm/esbuild@0.19.12/node_modules/esbuild/lib/main").Plugin'.`](https://github.com/enso-org/enso/actions/runs/11576387008/job/32225209090#step:7:254)
```

**Comment by radeusgd** [comment]
Not sure on which list to put it, but I've been getting some failures during Packaging: https://github.com/enso-org/enso/actions/runs/11611460774/job/32336224968?pr=11455#step:8:166
```
  1) electronTest.ts:13:3 › Create new project ─────────────────────────────────────────────────────

    Error: Timed out 5000ms waiting for expect(locator).toHaveText(expected)

    Locator: locator('.node-type')
    Expected string: "Table"
    Received string: "Unknown"
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for locator('.node-type')
      -   locator resolved to <div title="Unknown" data-v-99eb8ab8="" class="after-toolbars node-type">Unknown</div>
      -   unexpected value "Unknown"
```
It did not contain a playwright test report

<blockquote><img src="https://opengraph.githubassets.com/072d18043354c925d7687589d3bfcd91c1f6fd13b5dd40f6fef06493672e86df/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Add widget for `name_filter` · enso-org/enso@2d723c1</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by GregoryTravis** [comment]
https://github.com/enso-org/enso/actions/runs/11598732906/job/32296813889?pr=11417

```
1) electronTest.ts:13:3 › Create new project ─────────────────────────────────────────────────────

    Error: Timed out 5000ms waiting for expect(locator).toHaveText(expected)

    Locator: locator('.node-type')
    Expected string: "Table"
    Received string: "Unknown"
    Call log:
      - expect.toHaveText with timeout 5000ms
      - waiting for locator('.node-type')
```

<blockquote><img src="https://opengraph.githubassets.com/a910dcf0acae570ac83915828f662693bbeb9a078098d41bc0f994cc38b29a1b/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Add Warnings whenever a floating-point value is used as a Dictionary key · enso-org/enso@2277fa5</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by farmaazon** [comment]
The two comments above are the same issue, which I don't want to be part of this task, because this is an integration test: so it may be as well an engine issue :)

This time we don't receive update for a type in time (there's 5 second timeout I think). I may bump the timeout, the question is what do we call an "acceptable" waiting time for the user :)

**Comment by somebody1234** [comment]
`collapsingAndEntering` failure: <https://github.com/enso-org/enso/actions/runs/11681103703/job/32534992167#step:7:1015>
[gui-playwright-report.zip](https://github.com/user-attachments/files/17634848/gui-playwright-report.zip)

not sure if this one is just caused by insufficient timeouts.

<blockquote><img src="https://opengraph.githubassets.com/cc41c17162fcb0b3508149537046bccc3eb08ec4ea91808f6fb249c24cc32644/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Add transitions support for zustand 'useStore' · enso-org/enso@3b59e7f</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Add transitions support for zustand 'useStore' · enso-org/enso@3b59e7f</div></blockquote>

**Comment by farmaazon** [comment]
> `collapsingAndEntering` failure: https://github.com/enso-org/enso/actions/runs/11681103703/job/32534992167#step:7:1015 [gui-playwright-report.zip](https://github.com/user-attachments/files/17634848/gui-playwright-report.zip)
> 
> not sure if this one is just caused by insufficient timeouts.

timeouts would not avail us, it looks like some driver crash: https://github.com/enso-org/enso/actions/runs/11681103703/job/32534992167#step:7:1102

<blockquote><img src="https://opengraph.githubassets.com/a9f5d347d4ae8223e644905e29543663b81ff7a3d593765478d45a9c923ff55d/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Add transitions support for zustand 'useStore' · enso-org/enso@3b59e7f</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Add transitions support for zustand 'useStore' · enso-org/enso@3b59e7f</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/a9f5d347d4ae8223e644905e29543663b81ff7a3d593765478d45a9c923ff55d/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Add transitions support for zustand 'useStore' · enso-org/enso@3b59e7f</a></strong></div><div>Enso Analytics is a self-service data prep and analysis platform designed for data teams. - Add transitions support for zustand 'useStore' · enso-org/enso@3b59e7f</div></blockquote>

**Comment by farmaazon** [comment]
After merging #11522 and some follow-up fixes it seems the issues from this task were addressed.
