### ISSUE TITLE
Refresh button should clear HTTP cache

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#11485]
We need to connect refresh to the std-bits `EnsoHTTPResponseCache.clear()` in some way.
Options:
- Create a dependency between the language server and std-bits
- Register the cache (or the clear method) on library load (preferred)

**Comment by hubertp** [comment]
Plan is to 
- [ ] extend libraries' `package.yaml` with an additional "hooks" section:
```
hooks:
  refresh:
    - <FQN of method to call>
    - Standard.Base.HTTP.Caches.refresh
```

- [ ] ability for LS to parse the new config
- [ ] ability for LS to call arbitrary expression 
- [ ] call a list of refresh hooks on `RecomputeContextRequest`
- [ ] expose Java method in (private) Enso API so that it can be expressed via FQN

**Comment by 4e6** [comment]
Maybe we can call the main section `scripts` instead of `hooks`. Because this feature looks similar to scripting support in other programs, where users can implement their own code snippets that will be executed at certain conditions.

**Comment by hubertp** [comment]
`scripts` it is then. Config part is done. Over to you @4e6

**Comment by GregoryTravis** [comment]
This is https://github.com/enso-org/enso/pull/11555

**Comment by JaroslavTulach** [comment]
As an outsider to the face to face discussions I can only imagine what are the actual use-cases. The only one I see is:

> We need to connect refresh to the std-bits `EnsoHTTPResponseCache.clear()` in some way.

and then I see a plan:

> Plan is to
>     * [ ]  extend libraries' `package.yaml` with an additional "hooks" section:

I don't see why the plan would be the best way to implement the above use-case? In my opinion, the following API would be sufficient, smaller, less cross-cutting change and possibly even more general way of _controlled caching_ also satisfying the above use-case:

```diff
diff --git distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Ref.enso distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Ref.enso
index 8e8edcde12..9265fb9fb0 100644
--- distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Ref.enso
+++ distribution/lib/Standard/Base/0.0.0-dev/src/Runtime/Ref.enso
@@ -8,16 +8,29 @@ type Ref
     ## PRIVATE
        ADVANCED
        Creates a new reference containing the provided value.
+       If `can_disappear` is set to `True` than the management
+       of the reference is controlled by the runtime which
+       may _set the reference to `Nothing` any time_. The
+       definition of _"any time"_ is intentionally vague, but
+       the known implementations reset the value when running
+       out of memory or when a user asks for _"clean re-execution"_
+       of a project.
 
        Arguments:
        - value: The value to be contained in the ref.
+       - can_disappear: Is the value eligible for being cleared by the system at any time?
 
        > Example
          Creating a new reference containing the value 7.
 
              Ref.new 7
+
+       > Example
+         Cache a value, but allow the system to reclaim it.
+
+             Ref.new huge_data_downloaded_from_internet True
     new : Any -> Ref
-    new value = @Builtin_Method "Ref.new"
+    new value can_disappear=False = @Builtin_Method "Ref.new"
 
     ## GROUP Metadata
        ICON metadata
```
Of course, being an outsider, I cannot really know what _other use-cases_ were discussed that lead to the selection of the current plan. Maybe my proposal doesn't address one of such discussed use-cases. However I cannot know unless the use-cases are summarized and written down.
