### ISSUE TITLE
Update Project Manager Protocol

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#1149]
### Summary

The project manager will need to handle engine version management using the same logic that the launcher uses. This additional functionality requires an update of its [protocol](https://github.com/enso-org/enso/blob/main/docs/language-server/protocol-project-manager.md).

### Value

- Both PM and IDE know what new messages need to be handled.
- We take the first step to being able to manage engine versions from PM.

### Specification

- Requirements for the protocol:
  - It should augment opening projects so that missing engine/runtime versions will be installed.
  - When a project is being opened, it should determine what version is necessary to open it.
    - If that version is not installed, it should send a message to the IDE and wait for a reply (`install-missing-components` / `cancel`).
  - If a new project is being created, the same logic for downloading the missing version (with a question if the components should be installed or current action cancelled) should be used.
  - When the components are being installed, installation/download progress should be reported to the IDE with some progress update messages.
    - We probably want a triple: `task/started`, `task/progress-update`, `task/finished`.
    - The progress update should include not only the percentage but also a message.
    - This message or a separate message type for warnings can be used to indicate warnings regarded to locking (if another process is currently installing the same version in parallel, a warning should be displayed and the progressbar set to 'indeterminate' mode (as we do not know when the other installation finishes). It should also handle the message that other Enso versions should be closed which could be displayed when uninstalling.
  - If a version requires a newer project-manager version, a failure message should be sent `project-manager-upgrade-required` (and that message should contain the minimum version that is required).
    - This error may happen in any message that uses the engine, currently `project/open` and `project/create`.
  - Allow the IDE to query logging service setup (information needed to establish a connection to the service from the IDE).
  - Allow the IDE to query (`global-config/get`) and update (`global-config/set`, `global-config/delete`) the global configuration, so that the IDE can allow to modify properties like `author.name` and `author.email` which are used when creating new projects.
  - It should allow to list currently installed engine releases and uninstall them.
- [x] Prepare a draft of the updated protocol specification.
- [x] Discuss the draft with IDE.
  - [x] Update any requested changes.
- [x] Add a stub implementation of the protocol in the project-manager (for now the messages should return an error indicating 'not-implemented').
  - Either the old protocol should still be supported, be backwards compatible or the IDE should update to support the new protocol.
    - This will depend on how many breaking changes are there, possibly the only breaking change may be the question asked if an engine version should be installed.

### Acceptance Criteria & Test Cases

- [ ] The protocol design has been discussed with the IDE team and has been accepted.

**Comment by farmaazon** [comment]
> If that version is not installed, it should send a message to the IDE and wait for a reply (`install-missing-components` / `cancel`).

I wonder if it would be much simpler, if the project/open would have an option "don't install missing components / install missing components(version)", and return an error without any "waiting for IDE reply" state. We can just call this method twice if we need to.

Additionally, I think there should be option in project/create to specify version of Enso the project is using (usually use the newest version supported by IDE).

**Comment by radeusgd** [comment]
> > If that version is not installed, it should send a message to the IDE and wait for a reply (`install-missing-components` / `cancel`).
> 
> I wonder if it would be much simpler, if the project/open would have an option "don't install missing components / install missing components(version)", and return an error without any "waiting for IDE reply" state. We can just call this method twice if we need to.

That would indeed be simpler.

> Additionally, I think there should be option in project/create to specify version of Enso the project is using (usually use the newest version supported by IDE).

Yes that endpoint should get which version to use (which potentially may be either a semver-string or `latest-installed` to get the latest currently installed version, falling back to the latest release available online).
Moreover, it should also have this "(don't) install missing components" option as open has.

**Comment by iamrecursion** [comment]
In addition to listing installed and uninstalling it should allow for installing a specified version, same as the launcher. This is useful for people who may be without internet for some time, and want to preinstall versions they may need.
