### ISSUE TITLE
Explore How the Project Manager Can Be Started by IDE

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#1150]
### Summary

The IDE will want to package the current project manager version with its distribution so that the users do not have to download additional packages.

### Value

- The IDE can be started by downloading a single package.
- It is much easier to setup the IDE.

### Specification

- [x] Experiment with building the Project Manager into a Native Image.
  - Set-up a Native Image build in sbt.
  - Test the built image to make sure all the functionality is working.
  - [x] Try using a PM built this way with the IDE.
  - [x] Document how to cleanup the reflection config.
  - [x] Update the CI to build the native image for PM.
    - [x] Create a separate `project-manager` distribution and remove PM from `engine` distribution.
    - [x] Update documentation regarding using PM to reflect the changes.
    - [x] Update license review, migrating relevant parts from `engine` to the new `project-manager` distribution.
    - [x] Update the release CI similarly.

- ~If there are too many issues with the Native Image, discuss other options.~
  - For now requiring the user to have *some* Java runtime and using the default `java` to run the Project Manager.
   - In the future, a Graal distribution may be bundled with the IDE and then that could be used (although using it is non-trivial, since the bundled distribution should be moved by the project manager into the installed distribution directory and we may not want to just copy it so that there are two of them just to run the Project Manager).
   - We could bundle the Launcher and use it to download the required runtime for the Project Manager.
   - Other possibilites may be explored.

### Acceptance Criteria & Test Cases

- The specification above has been completed.
- [x] The native PM has been tested on all platforms.
- [ ] The updated release workflow has been ran on staging.

**Comment by iamrecursion** [comment]
Potentially useful: [Akka HTTP + Native Image](https://github.com/vmencik/akka-graal-native)
