### ISSUE TITLE
Unexpected `(42 : Text & Integer)` signature at the end of a function

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#11574]
## Issue

The following program:

```py
from Standard.Base import all

main =
    (42 : Text & Integer)
```

results in a compilation error:

```
~/Documents/enso-projects/Issue_11481/src/Main.enso:4:6: error: Unexpected type signature.
    4 |     (42 : Text & Integer)
      |      ^~~~~~~~~~~~~~~~~~~
Aborting due to 1 errors and 0 warnings.
```

## Expected

I would expect the program to compile successfully

**Comment by JaroslavTulach** [comment]
- sounds similar to #7841
- there was a change in [SignatureTest](https://github.com/enso-org/enso/pull/11289/files#diff-0445cc9446734d3472c2cdf26e8e615499f6a8496c5c424bbb2aaa146acf7ed3R978) - let's add one more
