### ISSUE TITLE
Error trying to create a new local  workflow

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11649]
Not reproducible. But that is a unfortunate error message that I would like to never show to users

![image](https://github.com/user-attachments/assets/6607aac3-f566-4bbe-88b4-159b3403f3c2)

Version 2024.5.1-nightly.2024.11.25
Build e5a65a26cb521a124b047a7fd32f7abd01c0ab7c
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.5.1-nightly.2024.11.25 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

**Comment by PabloBuchu** [comment]
Closing as can not reproduce
