### ISSUE TITLE
Icon is wrong for Graph Editor

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11644]
Left hand icon on graph editor tab should look like an Enso graph

Actual: 

![image](https://github.com/user-attachments/assets/848eec27-1aa6-41a0-9f0d-7feff3e5b8d2)

Expected;

![image](https://github.com/user-attachments/assets/7f063a2e-d017-4ca9-97a2-42ab768983bf)

Version 2024.5.1-nightly.2024.11.25
Build e5a65a26cb521a124b047a7fd32f7abd01c0ab7c
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.5.1-nightly.2024.11.25 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

**Comment by PabloBuchu** [comment]
Fixed
