### ISSUE TITLE
Wrong data appears in table Viz

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11650]
https://github.com/user-attachments/assets/d0139d6d-14a9-41a4-8fe1-6ee585595c7d

[Workflow.zip](https://github.com/user-attachments/files/17902074/Workflow.zip)

Version 2024.5.1-nightly.2024.11.25
Build e5a65a26cb521a124b047a7fd32f7abd01c0ab7c
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.5.1-nightly.2024.11.25 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

**Comment by hubertp** [comment]
That actually looks like a GUI bug. No new data is being sent from LS. It's also reproducible with this project very easily.

**Comment by sylwiabr** [comment]
I can reliably reproduce it as well with a new project.


https://github.com/user-attachments/assets/8d224820-5503-4c39-8492-b15d73221928

**Comment by farmaazon** [comment]
I found the issue: AGGrid has a bug. After bumping version the issue is gone.
