### ISSUE TITLE
Pasting content to the doc panel loses all formatting & image links

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#11699]
Previously, when pasting Preppin Data or other external content, the headings and image links pasted in. 

![Image](https://github.com/user-attachments/assets/839a3f89-cea6-41df-8ca1-51559bc26aad)

![Image](https://github.com/user-attachments/assets/07ed8ac7-20be-4904-baa2-919509659bd3)

**Comment by farmaazon** [comment]
Looks like a bit of task: we would need to "parse" text/html type and translate it to Markdown. Didn't know lexical editor had it (and that we want this feature).

**Comment by farmaazon** [comment]
Refinement notes:
* Use external library for translating HTML from clipboard to Markdown. Images links should be fine.
