### ISSUE TITLE
 Fully qualified names pasted to documentation editor are interpreted as URLs.

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#11697]
The URL detector in markdown editor paste handler is activating on a common enso pattern (module path), causing it to be incorrectly converted to a link. We should likely have a special-case to detect camel-case dot separated strings to not flag them as URLs.

Example string: `GROUP Standard.Base.Math`

<img width="206" alt="image" src="https://github.com/user-attachments/assets/efd2a765-b7eb-4569-8b7f-0f482307d3f1">

**Comment by farmaazon** [comment]
Refinement notes:
* Let's auto-convert text to a link only if it's prefixed with http(s)://
