### ISSUE TITLE
Clicking links in documentation panel not working

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#11692]
![image](https://github.com/user-attachments/assets/ccb63e78-953f-4637-a2e5-9fdfd04362b5)

clicking the link results in it editing as markdown now.

**Comment by farmaazon** [comment]
The tooltip should inform, that the link should be ctrl+clicked to follow it.

**Comment by farmaazon** [comment]
Refinement:
- there's a better way: to display a pop-up when the link is edited, which allow following the link (like in google docs) - user will have immediate feedback what to do to follow the link. The visuals may be taken from [10353](https://github.com/enso-org/enso/pull/10353)

![Image](https://github.com/user-attachments/assets/4904b0b2-5f7d-4c33-aee4-e4497d4c109e)

(this is for old editor; in our case the markdown will be still visible).
