### ISSUE TITLE
Improve the Syntax and Semantics of Exports

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#1172]
### Summary
The current syntax for exports assumes both that the exported module is imported and also requires providing the full qualified name of the export. That seems silly, the solution should instead be to allow re-exporting a module by the name in which it is in scope.

### Value
The export system is more intuitive and easier to use.

### Specification

- [ ] Change the module resolution algorithm to allow re-export of a module under its in-scope name.
- [ ] Ensure that there are no performance or functional regressions as a result.

### Acceptance Criteria & Test Cases
The functionality is well tested.

**Comment by 4e6** [comment]
The current implementation of `export` by the qualified name makes sense to me if we make `import` and `export` unrelated _header_ directives, i.e. there's no requirement to import module before exporting.

- `import A.B` imports the module `B` in scope, making it available in the _body_ of the program
- `export A.B` is a directive to include everything defined in `A.B` when this module is imported

**Comment by 4e6** [comment]
There may be also a name clash when the module polyglot imports the type and re-exports it from another module. Consider the example project:

```
.
├── Duration
│   └── Extensions.enso
├── Duration.enso
└── Main.enso
```

**Main.enso** 
`import Test.Duration` brings two `java.time.Duration` in scope and crashes the compiler.
```python
from Base import all
import Test.Duration

main = 1.second
```

**Duration.enso**
Module polyglot imports `java.time.Duration`, and at the same time re-exports `java.time.Duration` from the `Test.Duration.Extensions`.
To fix the issue we need to hide the extra duration `from Test.Duration.Extensions export all hiding Duration`.
```python
from Base import all
import Test.Duration.Extensions

from Test.Duration.Extensions export all

polyglot java import java.time.Duration
```

**Extensions.enso**
```python
from Base import all

polyglot java import java.time.Duration

Integer.second = Duration.ofSeconds [this]
```

## Issues
There are a couple of issues:

- ambiguity is not handled in compiler
- should we export polyglot imports at all?
