### ISSUE TITLE
New connection style and component comments don't play well together

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11728]
![image](https://github.com/user-attachments/assets/879c813c-d057-4a63-be46-13b0a35b677a)

Version 2024.5.1-rc2
Build e82ce1085b9f3c06b4870b839cf4dd8c9ce88579
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.5.1-rc2 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

**Comment by jdunkerley** [comment]
Lets do the following at least for now:
![image](https://github.com/user-attachments/assets/08867259-53c3-4fc3-bf6a-ac3f55dace60)

- Make the gap from arrow to node 1px (`arrowTopOffset` = `)
- Make comments slightly opaque (80% opacity)
- Move comment one pixel further away (--node-vertical-gap 5px;)
