### ISSUE TITLE
table viz column width bug

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#11731]
In a wide table, columns that are to the right, outside of the initial view, are wider than the initial columns.

https://github.com/user-attachments/assets/1fc89cd1-07ce-4fcd-b848-9d8a939d59cc

**Comment by jdunkerley** [comment]
[Big Table Test.zip](https://github.com/user-attachments/files/17978243/Big.Table.Test.zip)
Sample project to test on

**Comment by marthasharkey** [comment]
With Column virtualization on, the column auto sizing does not work for the columns not rendered. 

<img width="667" alt="image" src="https://github.com/user-attachments/assets/1706282e-eac0-4acf-955b-91829fbcd2d3">

https://www.ag-grid.com/javascript-data-grid/column-sizing/

<blockquote><img src="/images/ag-grid-social.png" width="48" align="right"><div><strong><a href="https://www.ag-grid.com/javascript-data-grid/column-sizing/">JavaScript Grid: Column Sizing | AG Grid</a></strong></div><div>Column Sizing controls the way Columns are sized within the JavaScript Datagrid. Use auto-sizing or column-flex to control Column Size programmatically. Download AG Grid v32.3.0 today: The best JavaScript Table & JavaScript Data Grid in the world.</div></blockquote>

**Comment by jdunkerley** [comment]
Not possible at present. Inevitably to revisit in future.
