### ISSUE TITLE
Old value still used after reconnecting nodes

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#11734]
I have encountered an issue where if I switch node inputs, the old value is still used until I force it to recompute (either by completely disconnecting the node or pressing the "Refresh" button).

https://github.com/user-attachments/assets/fda26d0c-8997-4770-a987-b28269f085bf

The repro that seems to work for me rather reliably is:
1. Get a table, e.g. create it with `Table.input`
2. Add an `at` node and select a column, open its visualization.
3. Now insert a `rename_columns` node (and rename e.g. to `C1` and `C2` - names not present in old column).
4. Reconnect the `at` node to now take the renamed table.

### Expected behaviour

The node should be recomputed immediately after reconnecting and after it finishes recomputing it should display `No_Such_Column` error as the old column name is no longer valid.

### Actual behaviour

The node is still showing the old values with old column name which is wrong.

**Comment by radeusgd** [comment]
It seems to be happening quite consistently in a scenario like the one described above.


https://github.com/user-attachments/assets/ab60158a-0755-4256-b822-95f8c68b5852


Interestingly, if I add a downstream node, the old values are propagated there as well:
![image](https://github.com/user-attachments/assets/149de0e1-c6ab-4df1-b052-0146aa83fec9)

So it is likely not only a visualization-update issue, but caching issue - the value for the `at` node is not recomputed and if I add any nodes that depend on it, they also are using the old value.

**Comment by hubertp** [comment]
Yes, I had that just a moment ago with AoC.

**Comment by hubertp** [comment]
That seems to happen only while adding new nodes. No update appears to be sent by LS. If I reopen the project and reconnect them in the way described above, it correctly refreshes the right nodes.

In fact, in the same project one can create exactly the same node and it will exhibit this problem, while the old nodes work correctly.

**Comment by hubertp** [comment]
For a project:
```
main =
    vector2 = ["C1", [1,2,3]]
    vector3 = ["C2", [4,5,6]]
    table1 = Table.new [vector2, vector3]
    any2 = table1.rename_columns [(Pair.Value 'C2' 'C5')]
    any3 = table1.rename_columns [(Pair.Value 'C2' 'C10')]
    any1 = any3.at 'C2'
```

when `any3` is added, it seems to compute the value of `any3.at` but for `any3.at 'C2'` it appears to use a cached value. Looks like some cache invalidation is broken.

**Comment by hubertp** [comment]
This has regressed between 10/29 and 10/30 nightly. I highly suspect https://github.com/enso-org/enso/pull/11428, @4e6

**Comment by 4e6** [comment]
Works for me on today's nightly. What am I doing wrong?

https://github.com/user-attachments/assets/c934b705-9f0b-4552-b561-dd8b019e48b2

**Comment by hubertp** [comment]
[Kazam_screencast_00019.webm](https://github.com/user-attachments/assets/f537c198-5d0a-4de3-9874-d350514f4783)

**Comment by radeusgd** [comment]
I've been using the latest release to align some tables of personal data I'm keeping and I think I ran into this issue again at least once. Is it surely resolved?

I will post a repro if I can find one

**Comment by radeusgd** [comment]
I've tried once more but could no longer reproduce it. It seems more random then before (maybe it was a one-off...). I will post if I encounter it again.
