### ISSUE TITLE
Double Menu on Table Viz

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11745]
![image](https://github.com/user-attachments/assets/a96fb368-2ac4-41e5-a1d5-31ac6109d6ea)

We shouldn't show the component menu if we are showing the AG Grid menu

Version 2024.5.1-rc2
Build e82ce1085b9f3c06b4870b839cf4dd8c9ce88579
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.5.1-rc2 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

**Comment by farmaazon** [comment]
I think the _node_ context menu should be blocked on visualizations in general.
