### ISSUE TITLE
Provide Informative Messages for Enso Exceptions and Diagnostics

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#1181]
### Summary
Currently when a panic is thrown, its message is set to the default `toString` implementation, which is usually not very user-friendly. We should populate the message with the result of calling Enso's `to_text` method and provide useful and informative implementations of said method for existing exception classes (`No_Such_Method_Error`, `Compile_Error` etc.).

### Value
It's easier for the user to understand what went wrong in their code.

### Specification
Take inspiration from Rust.

- [ ] Work out how to provide informative and helpful diagnostic messages to the user. These should
  - [ ] Clearly point to where the diagnostic occurred in the source.
  - [ ] Clearly explain the _cause_ of the diagnostic.
  - [ ] Suggest possible fixes.
- [ ] The errors should be represented as data (JSON) such that they can easily be sent to the IDE from the language server, or displayed prettily in the CLI.
- [ ] Implement nice display of diagnostics in the CLI (with colours) and so on.

### Acceptance Criteria & Test Cases

- [ ] The functionality is well tested.

**Comment by iamrecursion** [comment]
Doing this properly depends on #1174 and #1175.
