### ISSUE TITLE
AGGrid buttons spaced strangely when there is only one column

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#11814]
![image](https://github.com/user-attachments/assets/b8d96087-259a-4e91-9cc0-7bbfea40105a)

![image](https://github.com/user-attachments/assets/1e50da92-ffc2-4f04-85c3-4979b6adb73f)

Would expect them all right justified like when there are multiple columns

Version 2024.5.1-rc4
Build d56e8f758228a7dfb78478f983f13c1d578dde11
Electron 31.2.0
Chrome 126.0.6478.127
User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) enso/2024.5.1-rc4 Chrome/126.0.6478.127 Electron/31.2.0 Safari/537.36

**Comment by vitvakatu** [comment]
Cannot reproduce on the current develop (9cf7833de085f66c8a840e73e68a22af15937b2d)

<img width="519" alt="Image" src="https://github.com/user-attachments/assets/396ba6ab-08f4-4b74-a50a-c25cc71b69f0" />

**Comment by vitvakatu** [comment]
Update: it is reproducible, you need to manually resize the column.
