### ISSUE TITLE
Reordering File Output for the Logger

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#1185]
### Summary

As the logs are gathered from multiple components and sent over a network connection, they can be received by the logging service in a different order than in which they were sent (especially messages from different component can have different order).

Having the messages in the order that they were really reported would be helpful, especially when debugging interaction between components.

A `ReorderingFileOutputPrinter` should be implemented which extends the behaviour `FileOutputPrinter`. It should buffer the last few messages and try to reorder them according to the timestamps on a best-effort basis (of course if a message comes with a very different timestamp, for example 10s late, it could be infeasible to reorder it).

### Value

- The order of logs in the file is as close as possible to the real order in which they were reported.
- It is easier to debug interaction between components.

### Specification

- Implement a `ReorderingFileOutputPrinter` that implements the `Printer` interface.
- [ ] It should write messages to a file, like the `FileOutputPrinter`.
- [ ] But it should not write them immediately, but instead keep them inside of some buffer and only write messages that are 'old enough' to guarantee that they are unlikely to be reordered.
  - This could be achieved by maintaining a separate message queue which commits messages whose timestamp is at least `T` old (for example `T = 10s`). When a message is being committed, any other messages in the queue should be inspected and if they are even older than it, they should be accordingly reordered.
- [ ] It should flush all pending messages immediately when `shutdown` is called.

### Acceptance Criteria & Test Cases

- The above specification has been satisfied.
- [ ] The reordering mechanism is tested to some extent.
  - The messages could be sent to it out of order and the resulting file can be inspected.

**Comment by farmaazon** [comment]
Above standups meant for #11185
