### ISSUE TITLE
Automate License Discovery for Rust Dependencies

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#1187]
### Summary

The license discovery done in #1183 handles `sbt` dependencies. Since the parser is being rewritten in Rust, in the future, the distribution will include Rust-based components. We need a similar mechanism for gathering the dependency licensing infomration to comply with licenses of our Rust dependencies.

The mechanism should (if possible) re-use the existing backend (so it should be provided as part of the sbt task), so that the Rust licensing information is aggregated together with other licenses. It should just provide a separate frontend that discovers Rust dependencies and gives the backend means to find copyright information within them.

https://github.com/onur/cargo-license may be potentially useful.

### Value

- We can distribute the Rust components in compliance with licenses of their dependencies.

### Specification

- [ ] Extend the sbt tasks with a mechanism that can discover Rust dependencies.
  - It should be possible to define which distributed components rely on which Rust sub projects and their dependencies should be selected based on that.
  - [ ] It should detect what license each dependency has.
  - [ ] It should provide access for the backend to the dependencies' source files (possibly by using the cargo cache) and possibly any other relevant metadata (like project link).

### Acceptance Criteria & Test Cases

- The above specification is completed.
- [ ] The mechanism has been tested manually and its results are as expected.

**Comment by xvcgreg** [comment]
@radeusgd please taka a look at #5914 
"We are missing attribution for Rust dependencies."

**Comment by radeusgd** [comment]
> @radeusgd please taka a look at #5914 "We are missing attribution for Rust dependencies."

@xvcgreg Yes, no such mechanism is currently implemented. We could extend the SBT tool, or build something in Rust since we are not keen of keeping too much Scala. However, the advantage of using SBT for this would be that we can re-use parts of the infrastructure built for the JVM dependencies.

**Comment by radeusgd** [comment]
We may be able to re-use some [existing solutions](https://www.github.com/Nemo157/cargo-lichking/issues/3).
