### ISSUE TITLE
Latest enso w/ free trial on Mac does not work at all

### ISSUE THREAD

**Issue by mtaran** [enso-org/enso#11912]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I try opening a project in Enso it complains about a bad property and nothing works.

### Expected behaviour

I expected to be able to do something in the app.

### How we can reproduce it?

1. Download the latest mac (apple silicon) release
2. Sign up for a new account, with github auth
3. Use the free plan
4. Try to create + open a project

### Screenshots or screencasts

<img width="826" alt="image" src="https://github.com/user-attachments/assets/2906b44a-5303-4db1-8dac-7baa7d6bac78" />

### Logs

`$HOME/Library/Application Support/org.enso` only has a couple of empty lock files, no logs

### Enso Version

Version 2024.5.1 (2024.5.1)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Sonoma 14.5 (23F79)

**Comment by mtaran** [comment]
FYI, I tried with the prev release (rc7) and that seems to work!

**Comment by jdunkerley** [comment]
Thank you for reporting this. There was a problem with our sign-up flow.

We are working on a hotfix, but now you are signed up, the release version should also work.

**Comment by jdunkerley** [comment]
Resolved in 2024.5.2
