### ISSUE TITLE
The `json_serialize` Method Returns `null` For Values Like Float or Vector

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#1232]
### General Summary
When serializing to JSON values like `1.0` or `[1,2,3]` IDE gets `null` rather than expected value.

Interestingly `1` serializes correctly, so the problem seems specific to some types, like floating point numbers or vectors.

This causes IDE issue reported here https://github.com/enso-org/ide/issues/836

### Steps to Reproduce
Evaluate `1.0.json_serialize` or  `[1,2,3].json_serialize`.

### Expected Result
Respectively: `1.0` and `[1,2,3]` (or similar)

### Actual Result
`null` in both cases

### Enso Version
```
Enso Compiler and Runtime
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: main* @ 989aa4b7d7eebc43fae61c5135f2e385b0520bec
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Windows 10 10.0 (amd64)
```

**Comment by sylwiabr** [comment]
Floats are working but vector is giving null

Enso Project Manager
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: main* @ 36694e249655d2bba183867b1bdef7519242ac0d
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Mac OS X 10.15.7 (x86_64)

**Comment by iamrecursion** [comment]
This is because the IDE needs to update to the proper JSON API now that it exists.

**Comment by iamrecursion** [comment]
The fact that `json_serialize` is working at all at this point is very odd.

**Comment by iamrecursion** [comment]
As Marcin mentioned when PRing the new JSON, the IDE needs to change its visualisations to call [`Any.to_json`](https://github.com/enso-org/enso/blob/main/distribution/std-lib/Base/src/Data/Json.enso#L103).

**Comment by sylwiabr** [comment]
I believe they did @farmaazon can you confirm?

**Comment by farmaazon** [comment]
Yes, on the newest main we call `x.to_json.to_text`

**Comment by iamrecursion** [comment]
This is then for @kustosz to look into.

**Comment by iamrecursion** [comment]
It looks like we might be missing `to_json` for the primitive arrays that back vector.

**Comment by iamrecursion** [comment]
I can't reproduce this at all from a language standpoint. It works fine in the repl, so potentially it's an interaction with the project manager?

**Comment by farmaazon** [comment]
[Unnamed.zip](https://github.com/enso-org/enso/files/5482245/Unnamed.zip)

I tried to investigate it on the IDE side. I attach the project, where in IDE I attached visualization with:
```
{"jsonrpc":"2.0","id":9,"method":"executionContext/attachVisualisation","params":{"expressionId":"c866fda1-8139-430a-8922-09d6fd3900fa","visualisationConfig":{"executionContextId":"9e1509bb-f149-4796-a7fa-2e8939f94a94","expression":"x -> x.to_json.to_text","visualisationModule":"Unnamed.Main"},"visualisationId":"8433f0f7-8a2f-4135-be74-26174c4ca312"}}
```
The ast generated by our parser assigns the id c866fda1-8139-430a-8922-09d6fd3900fa to the Match making the list, so it seems like legit request.

**Comment by kustosz** [comment]
@farmaazon @iamrecursion sudden realization: this has the same root cause as #1313
