### ISSUE TITLE
Unboxed Atoms

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#1238]
### Summary
Currently all Atom fields are boxed and `Object[]` wrapped. This has bad consequences for performance, as it requires multiple memory jumps to get an unboxed value out of an Atom. This should be fixed.

### Value
Design and implement a layout system, allowing atoms to store unboxed values.
This should come with layout transitions, converging to a (small) set of most-frequently-used specializations.

### Specification
Design and implement the described layouting system. Measure the performance impacts.

### Acceptance Criteria & Test Cases
No tests regressions. Measure performance impact of the changes in different circumstances.

**Comment by iamrecursion** [comment]
Something like `DynamicObject` with different backing storage classes. Atoms should carry a schema. Primitive fields should be stored as `long` (e.g. `Double.toRawLongBits`). Each storage class needs to carry a schema. You want "all unboxed" and "generic object" cases.

It is very important to think of the state machine here, as you don't want to continually over-specialize. You likely want a heuristic for how many times to specialize, but we can probably start with some static limit. The schema would have to contain a transition graph of cached schemas and a count of transitions.

You want to cache the schemas for lookup. You also need to be able to initialize atoms into these unboxed states quickly.
