### ISSUE TITLE
Implement a System for Representing Builtin Objects

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#1239]
### Summary
The way we currently represent builtin (primitive) objects is very limited. Each new kind of object requires implementing a lot of boilerplate and, in particular, extending the method resolver node, making it slower for every other object.
We need a more plug-and-play system for this.

### Value
Better representation of primitive values.

### Specification
Implement a common subclass of `TruffleObject`, able to expose methods through the use of some (possibly Enso-specific) Library. Migrate existing objects, such as files, streams, arrays, references and texts to this system.

### Acceptance Criteria & Test Cases
There are no test & benchmark regressions.

**Comment by iamrecursion** [comment]
Should be done after #1538 and #1175.

A DSL:

- Where we can create `MethodNode`s in the body of the objects.
- Which abstracts away the `GetFunctionalDispatch` boilerplate.
- We want to automate the wrapper generation for the builtins which registers the methods.

There is a standard way to do this. Look at `BuiltinTestObject.java` in the Truffle sources. We want a `BuiltinObject` class. This needs to interact nicely with shadow definitions.

**Comment by iamrecursion** [comment]
The `File` builtin type is going to be a great test for whether this works well or not. We shouldn't be using `asGuestValue` in `GetFileNode.java` or anywhere else.
