### ISSUE TITLE
Clean up the Benchmarking and Testing Libraries

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1242]
### Summary
Currently we have rudimentary benchmarking and testing libraries as part of `Base`. As part of #1231, however, they are moved to their own library, `Test`. In order to be able to release them with the standard library we need to ensure that we are happy with their APIs and their documentation.

### Value
We will be able to release the benchmarking and testing libraries.

### Specification

- [x] Move them to the correct package, as described in #1231.
- [ ] Talk to @kustosz about the API, and make any requested changes.
- [ ] Add a summary printout at the end of the test suite, showing the specs executed, and summarising any failures. It should be similar to scalatest.
- [ ] Add a summary printout at the end of the benchmark suite, showing the benchmarks executed and a summary of their results.
- [ ] Add functionality for nesting `describe` blocks in the testing library.
- [ ] Add functionality for running a subset of tests or benchmarks.
- [ ] Add a regression framework to the benchmarking library, to catch performance regressions. This should use the same definition of a regression as the framework we have in Scala.
- [ ] Ensure that the API is well documented, including comprehensive examples in the documentation.

### Acceptance Criteria & Test Cases

- [ ] The basic benchmarking and testing libraries are ready for release.

**Comment by kustosz** [comment]
Things I'd like:
1. Spec autodiscovery (see `Tests.Main` for an explanation of why that's needed...) – this will require the meta-stuff to be able to dynamically import modules, so probably also requires wiring the incremental compiler back into Enso.
2. Running benchmarks in forked JVMs. Without it the benchmarks are order dependent and generally unreliable. Needs careful design.
