### ISSUE TITLE
Conflicting Extension Methods Make Resolution Nondeterministic

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#1243]
> See [comment below](https://github.com/enso-org/enso/issues/1243#issuecomment-1959026431) for updated repro.

### General Summary

When multiple modules define extension methods with the same name and for the same type and both modules are imported, resolution of that method is not deterministic.

### Steps to Reproduce

1. Create new project (here called `Multitest`) with the following files:

- `File1.enso`:
```
from Base import all
Number.foo = 42
```

- `File2.enso`:
```
from Base import all
Number.foo = "answer"
```

- `Main.enso`:
```
from Base import all
import Multitest.File1 
import Multitest.File2

main =
  a = 23.foo
  IO.println a
```

Or download the project from here: [multitest.zip](https://github.com/enso-org/enso/files/5428888/multitest.zip)

2. Run it several times

### Expected Result

The above code should result in an ambiguity error.

Ideally, the error should be detected when importing the module that brings the ambiguous resolution. If that's not possible, executing that method in runtime should yield a runtime error indicating the ambiguity.

### Actual Result

The program sometimes prints `answer` and sometimes `42`, behaving nondeterministically.

### Enso Version

```
Enso Launcher
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: wip/rw/launcher-locking* @ 0bd1686264e50e55a07b73df27b9efb0cac0e37f
Built on:   Linux (amd64)
Current default Enso engine: 
Enso Compiler and Runtime
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: wip/rw/separate-component-manager* @ 746521f8b20de95f4300fb950207c12c8ee687c0
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Linux 4.15.0-122-generic (amd64)
```

**Comment by iamrecursion** [comment]
Check for ambiguity in `ModuleScope` and then raise a runtime error in `UnresolvedSymbol`.

**Comment by radeusgd** [comment]
This issue still persist to this day.

Updated repro: create a project with following 4 files:

`Mod.enso`:
```
type My_Typ
    Value x
```

`F1.enso`:
```
import project.Mod.My_Typ

My_Typ.foo self = self.x+3
```

`F2.enso`:
```
import project.Mod.My_Typ

My_Typ.foo self = self.x+4
```

`Main.enso`:
```
from Standard.Base import all

import project.Mod.My_Typ

import project.F2
import project.F1

main =
    o = My_Typ.Value 1000
    IO.println (o.foo)
```

(or download [project456.zip](https://github.com/enso-org/enso/files/14371759/project456.zip))

and run it.

It sometimes prints `1004` and sometimes `1003`. If the nondeterministic behaviour does not show up immediately, you may try reordering the `F1` and `F2` imports and running a few more times.

**Comment by radeusgd** [comment]
Related problem - it is possible to define an extension method on a type that already has a method with that name. In such case, the extension method simply seems to be ignored during resolution.

I think we should indicate an error when trying to define an extension method on a type which already has such a method - as this extension method will never be able to be called.

Repro:
`Mod.enso`:
```
from Standard.Base import all

type My_Typ
    Value x
    foo self = self.x+1
```

`Main.enso`:
```
from Standard.Base import all

import project.Mod.My_Typ

My_Typ.foo self = self.x+2

main =
    o = My_Typ.Value 1000
    IO.println (o.foo)
```

Running it seems to always yield `1001`, so the extension method defined in `Main.enso` is always ignored.

I think this could be solved as part of this issue as both problems are essentially about ambiguity of extension methods (there's just 2 cases: ambiguity between 2 extension methods from different modules AND ambiguity between an extension method and a 'normal' one).

**Comment by radeusgd** [comment]
Interestingly, if 2 extension methods are defined _in a single module_, we _do get_ an error:

```
from Standard.Base import all

import project.Mod.My_Typ

My_Typ.foo self = self.x+2
My_Typ.foo self = self.x+22

main =
    o = My_Typ.Value 1000
    IO.println (o.foo)
```
```
C:\NBO\repr\project123\src\Main.enso:6:1: error: Method overloads are not supported: My_Typ.foo is defined multiple times in this module.
    6 | My_Typ.foo self = self.x+22
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~
Aborting due to 1 errors and 0 warnings.
Execution finished with an error: Compilation aborted due to errors.
```
