### ISSUE TITLE
Check if the Suggestion is in Scope

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#1261]
### Summary

When adding the function from `search/completion` response, IDE always adds the import statement because it doesn't have information about whether this function is in the scope or not.

To fix that, `search/completion` method should return the information about whether or not the suggested symbol is in the scope.

### Value

IDE doesn't import modules that are already re-exported from the `Base`.

**Comment by kustosz** [comment]
Note that it should also return "the best" way of importing the item. So, e.g. when we have a function or type defined in an internal module and re-exported from a non-internal module, the non-internal should be chosen. Seems like the best way to go about it would be to choose "the least-nested module exporting the name".

**Comment by iamrecursion** [comment]
The "least nested" is a good idea, but we need to be careful about project files. I feel like we should probably prefer an export in the current project over importing an external library.
