### ISSUE TITLE
Improve Interactive-Mode Error Handling

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#1272]
### General Summary

Currently, when project is opened and executed using Language Server, the execution stops when it reaches some error (at least some types of it, like non-existing function), and no update is sent for further expressions, so IDE does not know about values and types of them. Instead, Language Server should send updates for all nodes unaffected by any error discovered.

Additionally, because IDE can't deduce what nodes are affected by what kind of error, I propose to add to the executionContext/expressionValuesComputed information about erroneous nodes with their error messages. 

### Motivation

The User Experience in visual programming is much better when it can manage unaffected parts of graph in presence of errors on some other parts.

### Specification

- [ ] Determine how to deal with errors that aren't expression scoped (e.g. top-level syntax errors) without stopping the world in the interpreter.
- [ ] When running in interactive mode, capture all of these errors.
- [ ] Pass the error information to the IDE while still executing the code as much as is possible.
- [ ] This error information must contain expression IDs where possible, and some method for identifying top-level constructs where not possible.

### Acceptance Criteria

- [ ] Do the thing.

**Comment by kustosz** [comment]
Some technical perspective. While it is very desirable that we fail-fast in the text code, IDE should indeed continue execution even if a Panic is thrown. That means we have to change program semantics in the instrumentation. Now, this should be quite easy to achieve – in the instrumenter, when `onReturnExceptional` is triggered, unwind the node and return a `RuntimeError` value containing the original `Panic`'s payload – similar to how we handle caching.

**Comment by farmaazon** [comment]
Additional note: currently, when we call a function in main which contains an error, we cannot enter the node and fix it, because we don't receive executionContext/expressionValuesComputed and don't know what method call it was.

This is another argument for notifying errors in executionContext/expressionValuesComputed: IDE could receive the methodCall along with an error message.
