### ISSUE TITLE
Add `Number.random` function

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#1276]
### Summary
We want users to trivially be able to generate random numbers based on a numerical seed. This should be added as the `Number.random gen=DeterministicSeeded` method.

### Value
We will have an extensible system for the generation of random numbers, starting with purely a deterministic seeded rng.

### Specification

- [x] Create the `Generator` abstraction in `Random`.
- [x] Add the `.random` method as above as an extension to number in the `Random` package.
- [x] Test that the same seed gives the same results deterministically.

### Acceptance Criteria & Test Cases

- [ ] We have an extensible system for the generation of pseudo-random numbers.
- [ ] It need not be cryptographically secure.

**Comment by iamrecursion** [comment]
`Number.noise`:

- Clamp arguments.
- Parametrised on generator.
- Output type depends on generator.
