### ISSUE TITLE
Add `Vector.sort` function

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#1277]
### Summary
We want to be able to sort vectors and lists in the standard library, and hence the `sort` function should be added to both.

### Value
We will be able to sort our basic collection types.

### Specification

- [x] Determine the most performant sort to use.
- [x] The sort must be stable.
- [x] The `.sort` function must take a comparator argument, which should default to being defined in terms of `>` and `==`.
- [x] Implement the sort.

### Acceptance Criteria & Test Cases

- [ ] The basic Enso collections have support for sorting.

**Comment by iamrecursion** [comment]
I think that the likely-to-be-optimal sort for Enso is [timsort](https://en.wikipedia.org/wiki/Timsort). This is the sort used by default in Python, Swift, Rust, and V8, as it takes advantage of properties seen in real-world data, and has excellent performance characteristics.

- It is a _stable_ sort, where quicksort isn't, and isn't easily made to be.
- It has the same worst-case space complexity as mergesort.
- It performs particularly well on real-world data.

A comprehensive description of timsort can be found [here](https://github.com/python/cpython/blob/master/Objects/listsort.txt). Care must be taken to avoid running into a longstanding [pitfall](http://envisage-project.eu/wp-content/uploads/2015/02/sorting.pdf) of naive implementations.

**Comment by iamrecursion** [comment]
We want to support both the [`sortBy`](https://hackage.haskell.org/package/base-4.14.0.0/docs/Data-List.html#v:sortBy) and [`sortOn`](https://hackage.haskell.org/package/base-4.14.0.0/docs/Data-List.html#v:sortOn) use cases.

**Comment by iamrecursion** [comment]
While Timsort improves on Mergesort's performance for both semi-sorted and random data, the "galloping" optimisation used by timsort has a significant complexity penalty. Removing this optimisation yields a sort that has improved performance on the same kinds of data, but trades some performance on semi-sorted data for much better performance on random data. This is what Rust does.

**Comment by iamrecursion** [comment]
With #1311 adding support for bit maths on Enso's `Integer`, the pieces are now in place to actually implement the hybrid sort.
