### ISSUE TITLE
`File.open` method

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1279]
### Summary
While our `File` library provides users with good levels of control, it is somewhat lacking in terms of ease of use. We want to add a `File.open -> Text -> Text` that opens and reads the file in one shot.

### Value
Files can be opened and read in one shot.

### Specification

- [x] Add a `File.open` method that opens and reads the file in one go.

### Acceptance Criteria & Test Cases

- [x] Files can be opened and read in one function call.

**Comment by radeusgd** [comment]
Isn't it conventional that `open` usually indicates opening the file for further operations which suggests having to close it etc.? Wouldn't something like `File.read` be more familiar for an operation that reads file contents?

**Comment by iamrecursion** [comment]
@sylwiabr ?

**Comment by sylwiabr** [comment]
We can go with `File.read` just it will clash with current `read` method which requires creating a file object before reading (`File.new`)

**Comment by radeusgd** [comment]
Maybe something like `File.readContents` then?

I understand that we cannot differentiate 'static' methods from methods on `File` instances, right? @iamrecursion

**Comment by sylwiabr** [comment]
Then we should go with `read` as a default method without creating an object and `readContent` or something like this for existing `read`

**Comment by kustosz** [comment]
Why change the original? There's no conflict there. Both can be named `read` no problem.
