### ISSUE TITLE
Geo library

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1286]
### General Summary

To be able to visualize points on geomaps we need few datatypes and methods:
```
type Geo_Map  
    latitude     = Nothing
    longitude  = Nothing
    zoom        = 15 
    controller  = True 
    layers       = []
type Scatterplot_Layer data=[]
type Geo_Point latitude longitude label=Nothing color=[0,0,0] radius=100 
```
and methods to set `label` for `Geo_Point`, `add_point`, `add_layer`, `set_data` for `Geo_Map` type
### Motivation

Easy to use maps

**Comment by sylwiabr** [comment]
Check how this is working with geomap visualization in IDE and if default `radius`value is ok or should be changed.

**Comment by iamrecursion** [comment]
Closed for now.
