### ISSUE TITLE
Project Manager has big delays in sending updates after running for couple hours

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1304]
### Summary

Right now if Project Manager is running in the background with time it has bigger and bigger delays. I.e. after opening new project it takes up to 5 min to start coloring connections. After working longer with project like:
```
import Base.Data.Json
import Base.Data.Map
import Base.Data.Vector
from Base import all

main = 
    operator1 = File.read "vehicles.json"
    operator2 = Json.parse operator1
    operator3 = operator2.fields
    operator4 = operator3.get "vehicles"
    operator5 = operator4.items
    operator6 = operator5.filter (x -> x.fields.get "longitude" . is_nothing)
```
[vehicles.json.zip](https://github.com/enso-org/enso/files/5571876/vehicles.json.zip)

(building it from scratch, playing around, going away and going back) after adding node `12` I was waiting for around 30 s for types information and another 10 for visualization. Project Manager was running in the background for about 2-3 h

**Comment by iamrecursion** [comment]
First port of call for this is for us to check whether the delay still happens when connecting directly to the language server, if that's possible from the IDE. @farmaazon do we have a way to debug connect to the language server without using the project manager?

**Comment by farmaazon** [comment]
> @farmaazon do we have a way to debug connect to the language server without using the project manager?

No, we don't support such scenario. It would require some thought and blocking some features like project rename.

**Comment by farmaazon** [comment]
However we (I) can copy the calls sequence during IDE initialization, thus making some automatic way to test the Language Server only.

**Comment by iamrecursion** [comment]
It would be good to have a way to check where the slowness comes from.

**Comment by farmaazon** [comment]
Here is an initial conversation between IDE and LS: > means "from IDE to LS", < means "from LS to IDE"

[LSconversation.txt](https://github.com/enso-org/enso/files/5573070/LSconversation.txt)

I recored it during opening the freshly created project. After last message from IDE to LS I needed to wait c.a. 20 seconds to get executionContext/expressionValuesComputed notification

**Comment by iamrecursion** [comment]
This is super helpful, thanks. Something for @4e6 to look at when he's back.

**Comment by 4e6** [comment]
Update. It seems that `File.read` method introduces the performance regression. After executing it, the invocation of consequent operations becomes slower
