### ISSUE TITLE
Language Server: One visualization does not receive data.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#1308]
### General Summary
IDE do not receive visualization data nor error information in a specific program.

[The program will require a vehicles.json file attached here.](https://app.zenhub.com/files/76672223/bfce05cf-e07a-4ddb-9dcd-dae8b7434768/download)

### Steps to Reproduce

* Run Project Manager
* Run IDE with `--dev` option. Open "network" tab in Debug Tools Window. Click on the third 127.0.0.1 connection to track binary messages.
* Click in application area, click ctrl/cmd + ` to bring code editor.
* Ctrl+A to select all and paste the following snippet:
```
import Base.Data.Json
import Base.System.File
from Base import all

main = 
    IO.println "Hello, World!"
    operator1 = File.read "/home/adam-praca/Downloads/vehicles.json"
    operator2 = Json.parse operator1
    operator3 = operator2.fields.get "vehicles"
    operator4 = operator3.items
    operator5 = operator4.filter (x -> x.fields.get "latitude" . is_nothing . not)
    operator6 = operator5.last
    operator6.fields.get "longitude" . value
``` 
change the path accordingly.
* Close Code editor with ctrl/cmd + `
* select the last node and press space to show visualization

### Expected Result

Eventually we receive a binary message with visualization data. It should be seen as a new entry in debug panel.

### Actual Result

Nothing happens

### Enso Version

Enso Project Manager
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: main* @ e62f6796fe39453a88a139a966a396f40ead6eba
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Linux 5.4.77-1-MANJARO (amd64)

Tested on IDE build 351fb2bf

**Comment by sylwiabr** [comment]
I will not see the value of a node unless I will add next node (`x / 3600000`) and connect last line as an `x`
