### ISSUE TITLE
PM is caching values of one function execution and reuse them in the other

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1312]
### General Summary

PM is caching values of one function execution and reuse them in the other
### Steps to Reproduce

needed file:
[vehicles.json.zip](https://github.com/enso-org/enso/files/5589650/vehicles.json.zip)

Start with the code:
```
import Base.Data.Json
from Base import all
import Base.Network.Http


type Geo_Point latitude longitude

main = 
    http1 = Http.new.get "http://www.ttss.krakow.pl/internetservice/geoserviceDispatcher/services/vehicleinfo/vehicles?positionType=CORRECTED"
    json1 = http1.body.to_json.fields.get "vehicles" 
    operator1 = File.read "path_to_file/vehicles.json"
    operator2 = Json.parse operator1
    operator3 = operator2.fields.get "vehicles"
    operator4 = operator3.items
    operator5 = operator4.filter (x -> x.fields.get "latitude" . is_nothing . not)
    operator6 = operator5.first
    operator7 = operator6.fields.get "latitude" . value
    quotient1 = operator7 / 3600000
    operator8 = operator6.fields.get "longitude" . value
    quotient2 = operator8 / 3600000
    Geo_Point quotient1 quotient2
```
collapse nodes: operator7, operator8, quotient1,  quotient2,Geo_Point
select node operator5
press <tab> and add `map here.func1`
open visualisation on node `here.func1 operator6`and show map
close the visualization
open visualisation on node `map here.func1`
### Expected Result

visualisation with multiple different points

![](https://cdn.discordapp.com/attachments/682811508136476675/780728759674077204/Screenshot_2020-11-24_at_10.37.15.png)

### Actual Result

![](https://cdn.discordapp.com/attachments/682811508136476675/780726467176038412/Screenshot_2020-11-24_at_10.28.09.png)

### Enso Version

Enso Project Manager
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: main* @ d608e21b39969b97ba478c40c23592fe432cccf5
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Mac OS X 10.15.7 (x86_64)

**Comment by iamrecursion** [comment]
@sylwiabr Please check if this is still present.

**Comment by sylwiabr** [comment]
I don't reproduce it with newest package but will keep an eye on it
