### ISSUE TITLE
LanguageServer: `[1,2,3...]` expression has type Array, but variable having it assigned has type Vector.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#1313]
### General Summary

In project which consists of main with just two lines:
```
var = [1,2,3,4,5]
var
```
the first node has type Array, and the second Vector.

### Steps to Reproduce

* Extract the attached project to ~/enso/projects:
* Launch IDE with --dev option
* Go to network tab and select second 127.0.0.1
* wait for first executionContext/expressionValueComputed

### Expected Result

Both nodes 6dee8030 and dfe52aef have the same type.

### Actual Result

One has type Array, and the second has type Vector
![image.png](https://images.zenhubusercontent.com/5dc012d07b4f63000158fc1e/29f5cbac-58bf-44a9-9be7-24828b95d33a)

(You can open the Main.enso in plain text editor and check spans assigned to those UUIDs).

### Enso Version

Enso Project Manager
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: main* @ d608e21b39969b97ba478c40c23592fe432cccf5
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Linux 5.4.78-1-MANJARO (amd64)

Tested with IDE 100aac09

**Comment by kustosz** [comment]
This really baffled me when I first heard about, but I know what's wrong! It's a bug in the `VectorLiterals` resolution pass. We do not transfer the code position from the original literal node to the newly created node. So the code position is still associated with the original node (which indeed creates an Array) and not the wrapper (which creates a vector).
