### ISSUE TITLE
Adding argument to some specific method does not update nodes calling it.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#1314]
### General Summary

Usually if I have a method `foo = ...` in my Main module and edit code in IDE so I add new input `foo a = ...` the nodes calling foo `here.foo` are properly updated. However in our test case this does not happen.

### Steps to Reproduce

* Open [the attached project](https://app.zenhub.com/files/76672223/7e259ad8-4864-4ba9-89ab-cbc8d80c3cf4/download) in IDE with --dev option.
* In dev console go to "network" tab and choose second 127.0.0.1 (connection with Language Server). Wait until all initial messages from engine arrives (value updates and suggestion database updates).
* Clear the network log.
* Open Code Editor (Ctrl+`) and add input `a` to the method `func1`

### Expected Result

The existing suggestion is modified or IDE receives expressionValueUpdate about new suggestion entry id.

### Actual Result

The suggestion is removed and added as a new one, but we receive no expressionValueUpdate with new suggestion entry id.

### Enso Version

Enso Project Manager
Version:    0.1.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: main* @ d608e21b39969b97ba478c40c23592fe432cccf5
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Linux 5.4.78-1-MANJARO (amd64)

Tested on IDE 100aac09

**Comment by 4e6** [comment]
> The suggestion is removed and added as a new one

This behavior was fixed in #1162, now you receive a proper update that adds an argument to the existing method.


```
{
   "jsonrpc":"2.0",
   "method":"search/suggestionsDatabaseUpdates",
   "params":{
      "updates":[
         {
            "type":"Modify",
            "id":486,
            "arguments":[
               {
                  "type":"Add",
                  "index":1,
                  "argument":{
                     "name":"a",
                     "reprType":"Any",
                     "isSuspended":false,
                     "hasDefault":false,
                     "defaultValue":null
                  }
               }
            ]
         }
      ],
      "currentVersion":509
   }
}
```
