### ISSUE TITLE
project-manager fails to start Enso Engine 1.2.4-rc.4

### ISSUE THREAD

**Issue by divanorama** [enso-org/enso#1325]
### General Summary

Project manager starts, but as soon as IDE is launched it logs errors about not finding installed engine versions, IDE doesn't load projects.

https://github.com/enso-org/enso/actions/runs/391879432 at a40989e7c657717dcbd015b4c7d0175089bf3028 **works**
https://github.com/enso-org/enso/actions/runs/396440686 at 9e1b49d245c60045d57b6cbd432002e3a86ed035 **fails** (comes from https://github.com/enso-org/enso/pull/1305 and is the first commit to introduce the issue)
also the **latest** version fails
https://github.com/enso-org/enso/actions/runs/399967504 at d80089ab6916f86d0b8ce479438520f24a2ae345

### Steps to Reproduce

1. Download and unpack enso-engine-0.1.0-linux-amd64.zip from https://github.com/enso-org/enso/actions/runs/399967504
2. Start project-manager -vv
3. Start IDE (for example AppImage from https://github.com/enso-org/ide/actions/runs/400104235)
4. Look into project-manager output

### Expected results
IDE fully starts

### Actual results
IDE fails to open a project, project-manager prints things like
> [debug] [2020-12-04T20:04:45.666Z] [org.enso.runtimeversionmanager.http.HTTPDownload] Fetching https://api.github.com/repos/enso-org/enso-staging/releases?page=1&per_page=100
> [info] [2020-12-04T20:04:45.683Z] [akka.event.slf4j.Slf4jLogger] Slf4jLogger started
> [warn] [2020-12-04T20:04:46.556Z] [org.enso.runtimeversionmanager.config.GlobalConfigurationManager] No Enso versions installed, defaulting to the latest available release: 0.1.2-rc.4.
> [error] [2020-12-04T20:04:46.62Z] [org.enso.projectmanager.requesthandler.ProjectOpenHandler] Request Number(1) failed due to MissingComponentFailure(No engine 0.1.2-rc.4. Cannot continue.)

### Extra info
Blindly tried so far following things in project-manager
- setting val ensoVersion   = "0.1.2-rc.4" in build.sbt
- setting JAVA_OPTS=-Denso.version.override=0.1.0 
- setting JAVA_OPTS=-Denso.version.override=0.1.2-rc.4
- extracting enso-engine-0.1.0-linux-amd64.zip to ~/.local/share/enso/dist/1.2.4-rc.

None of which seem to fix the issue. Extracting engine to dist seems to make project-manager try that version, but either is doesn't load or its version doesn't match.

Enso interpreter and repl works though.

### Enso Version

>Enso Compiler and Runtime
>Version:    0.1.0
>Built with: scala-2.13.3 for GraalVM 20.2.0
>Built from: main* @ d80089ab6916f86d0b8ce479438520f24a2ae345
>Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
>           Linux 4.19.146-gentoo (amd64)

**Comment by farmaazon** [comment]
The newest Engine's version requires an update in IDE. I will deliver it today.

**Comment by farmaazon** [comment]
This is the PR with IDE update: https://github.com/enso-org/ide/pull/1032

**Comment by iamrecursion** [comment]
@radeusgd Is there anything on our side we need to fix for this?

**Comment by radeusgd** [comment]
@iamrecursion The protocol is implemented as documented, so once IDE supports the new functionality it should work.

Unless there is some unexpected bug (which I hope is unlikely because we have tests covering this API), it should work correctly without further action.

**Comment by divanorama** [comment]
Just verified with latest IDE build https://github.com/enso-org/ide/actions/runs/405535000 :+1: 
It does the trick, though still some rough edges
- download obviously takes a bit of time (populates ~/.local/share/enso/dist with what looks very similar to already downloaded enso engine, and ~/.local/share/enso/runtime/graalvm-ce-java11-20.2.0 which is different from host graalvm)
- after download is complete it seems that restart is needed, logs from first run don't show any errors but IDE is blank
> [warn] [2020-12-07T22:22:47.434Z] [org.enso.runtimeversionmanager.config.GlobalConfigurationManager] No Enso versions installed, defaulting to the latest available release: 0.1.2-rc.4.
> [info] [2020-12-07T22:27:05.774Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Booting a language server
> [LanguageServerDescriptor(language-server-9ff8d023-9cc9-4ce1-9388-175766fd22e3,9966994b-af6e-4217-b2b9-a388c593eabc,/home/divan/enso/projects/Unnamed,NetworkConfig(127.0.0.1,49152,65535),org.enso.projectmanager.versionmanagement.DefaultDistributionConfiguration$@2b76bd40,0.1.2-rc.4,JVMSettings(None,List()),false)]
> [info] [2020-12-07T22:27:05.776Z] 
> [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Found sockets for the language server [json:127.0.0.1:59629, binary:127.0.0.1:49552]
Starting Language Server...
> [info] [2020-12-07T22:27:06.524Z] [org.enso.languageserver.boot.LanguageServerComponent] Starting Language Server...
> [info] [2020-12-07T22:27:07.165Z] [akka.event.slf4j.Slf4jLogger] Slf4jLogger started
> [info] [2020-12-07T22:27:07.917Z] [org.enso.languageserver.runtime.RuntimeConnector] Engine connection established.
> [info] [2020-12-07T22:27:10.9Z] [org.enso.languageserver.boot.LanguageServerComponent] Started server at json:127.0.0.1:59629, binary:127.0.0.1:49552
> [info] [2020-12-07T22:27:11.241Z] 
> [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Language server booted 
> [LanguageServerConnectionInfo(127.0.0.1,59629,49552)].

<blockquote><img src="https://avatars0.githubusercontent.com/u/17415943?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/ide">enso-org/ide</a></strong></div><div>Enso – a visual and textual functional programming language. - enso-org/ide</div></blockquote>

**Comment by farmaazon** [comment]
This is again a bug in IDE - I forget to bump the timeouts. Should be fixed with https://github.com/enso-org/ide/pull/1037
