### ISSUE TITLE
Free variables in scope as soon as they're guaranteed unreachable

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1334]
### Summary
Currently a function execution retains all the bindings in its frame until the point of return. This may prove problematic when working with larger data in a linear fashion – in such a case we are able to detect and free the memory before return, effectively making the sum of all allocated variables larger than the available heap space.

### Value
Better memory performance when working with large data.

### Specification
- [ ] Implement a static pass that performs liveness analysis for local variables
- [ ] Based on the output of the implemented pass, insert "unassign" nodes at the correct places in code gen.
- [ ] The unassign node should check the slot kind and set the value to null if the kind is object.

### Acceptance Criteria & Test Cases
- [ ] The functionality is well tested and documented
- [ ] The functionality does not introduce any performance penalties on existing benchmarks
- [ ] The functionality enables programs allocating and assigning large arrays to variables, such that the total memory allocated in a function is larger than the available heap space

**Comment by iamrecursion** [comment]
GraalVM 21.1.0 has [`Frame.clear(FrameSlot)`](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/frame/Frame.html#clear-com.oracle.truffle.api.frame.FrameSlot-) that allows the graal compiler to reason about liveness of variables. It has some notes on expected usage and will be better for performance than just nulling the frame slot. It also works for non-object-type frame slots, making it much simpler to use at runtime (no branching necessary).
