### ISSUE TITLE
Dataframes Benchmarks

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1337]
### Summary
We need benchmarks that compare Enso's dataframes library to those of competitors.

### Specification

- [ ] Implement a set of comparative benchmarks based on the use cases described [here](https://h2oai.github.io/db-benchmark/).
- [ ] Write a script that can execute these benchmarks and display the comparative results (in some form).
- [ ] It should compare Pandas in Python, Data Table from R, and the Enso library.

### Acceptance Criteria & Test Cases

- [ ] We can run a suite of comparative dataframes benchmarks.

**Comment by iamrecursion** [comment]
I disagree that they should be run on CI. CI is _incredibly_ unstable in terms of execution time, so any results we get would be unreliable. If we want to do this properly we should set up a dedicated machine with the GH actions local runner so we can ensure that it isn't suffering from resource contention.
