### ISSUE TITLE
Configure Logging Per Package

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#1348]
### General Summary

When the debug log level is enabled in the project manager, it produces a lot of redundant logs from the slick library. We should be able to configure the log level per package. Below is an example of how it's done in logback, but we can re-use the existing applicaton.conf

[Example: Setting the level of multiple loggers](http://logback.qos.ch/manual/configuration.html)

```xml
<configuration>

  <logger name="chapters.configuration" level="INFO" />
  <logger name="chapters.configuration.Foo" level="DEBUG" />

  <root level="DEBUG">
    <appender-ref ref="STDOUT" />
  </root>

</configuration>
```

### Motivation

Logs are more fine-grained.

**Comment by radeusgd** [comment]
I recently noticed that `enso repl` and `enso run` print at init:
```
[info] [2020-12-15T10:59:56.934Z] [akka.event.slf4j.Slf4jLogger] Slf4jLogger started
```

Of course it is undesirable as it just adds clutter when running the REPL.

I'm not immediately sure how to suppress this message, but any solution setting Akka log level to something like `warn` may also make some important `debug` level messages disappear when we run in debug mode.

So it seems it will be best to use the filtering method as described above to suppress these messages.

**Comment by 4e6** [comment]
After implementing the log masking feature #1720, the fact that the Slick library prints its debug statements becomes an issue because it reveals some PII, like paths inside a user project, and can potentially expose user code (documentation and expressions of defaulted function arguments)
