### ISSUE TITLE
Collection of Visual Runtime Information

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1353]
### Summary
The IDE wants to provide users with _visual_ profiling information, colouring the graph to report the comparative runtime performance of its segments. To do this, it needs to obtain runtime performance information from the engine about actively executing expressions. This task deals with the engine gathering this information, and communicating it to the IDE.

### Value
The engine will be able to communicate temporal profiling information to the IDE.

### Specification

- [x] Determine how to collect profiling information in the runtime with minimal performance impact.
- [x] Ensure that this design has negligible performance impact when not enabled explicitly for an expression.
- [x] Determine the granularity at which this profiling information is useful. This may involve keeping a moving average as expressions are run again and again, but the interaction between this and caching is subtle and needs care.
- [x] Determine, in discussion with IDE, how best to send the profiling information. The current thought is to do this inside the `ExpressionValueUpdate` message, but this may change. The value update should contain an array of `ProfilingInfo  = Time`, but this union type may be expanded in the future with other kinds of information.
- [ ] Update the protocol to allow the IDE to request profiling information for an expression ID.
- [x] For each enabled expression, collect profiling information and send it to the IDE.

### Acceptance Criteria & Test Cases

- The protocol messages contain real-world information on the execution time of specified expressions.

**Comment by farmaazon** [comment]
I propose to add profiling info to the [ExpressionValueUpdate](https://dev.enso.org/docs/enso/language-server/protocol-language-server.html#expressionvalueupdate)
