### ISSUE TITLE
List functions from Standard Library and Table 

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1391]
### Summary
Currently we do not have the ability to document builtin functionality (pending #1175), so we need to provide basic documentation for these functions as if they were defined in Enso.

### Value
We will have documentation for all of the functionality available in the language, not just the standard libraries.

### Specification

- [x] Create a new document that provides stdlib-style documentation for each of the builtins, including a description of functionality, type signature, examples, import path, and so on.
- [x] Describe the intended usage mode of the standard library.
- [x] Describe how to find the above information in the already extant standard library docs.
- [x] Describe which sections of the library are considered to be heavily WIP.
- [ ] Update the standard library docs to add the below information where relevant.

### Acceptance Criteria & Test Cases

- This task should produce a markdown document that contains the following for the builtins:
  - A list of available builtin functions.
  - A description of their arguments.
  - One-line examples

**Comment by iamrecursion** [comment]
An alternative approach:

- Create a `Builtins.enso` file that contains stub definitions for each of the builtin types.
- Create `@Builtin_Type` and `@Builtin_Method ident` annotations used as follows:

```
@Builtin_Type
type Number

Number.+ : Number -> Number
Number.+ that = @Builtin_Method "Number.+"
```

- Create a pass that handles these annotations, ensuring that they are basically ignored for now.
- Use this `Builtins.enso` module to provide the stub IR for the real builtins module by running the compiler pipeline on it. This will allow it to produce searcher information (docs, signatures, etc).

This will allow us to provide searcher information for builtin types and functions without having to go through the entire shadow detinitions architecture.
