### ISSUE TITLE
LanguageServer does not send types of numeric constants with decimal point.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#1393]
### General Summary

The numeric constants with decimal point does not receive types in expressionValueUpdate

### Steps to Reproduce

1. Open IDE with `--dev` option.
2. Insert node `21.0`
3. Look at messages from Language Server in Network tab.

### Expected Result

An update with type of the new node arrives.

### Actual Result

The update does not contain type of the node, for example
```
{"jsonrpc":"2.0","method":"executionContext/expressionValuesComputed","params":{"contextId":"917e4773-6ac7-4b3f-b4af-0c43bc03a2a9","updates":[{"expressionId":"19cad12f-b2cc-4d4d-8295-87d216b3424b","type":null,"methodPointer":null}]}}
```

### Enso Version
Enso Project Manager
Version:    0.2.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: enso-0.2.0* @ d2df28bc43fcfee614fb31780cd46a59ebb16127
Built on:   Linux (amd64)

**Comment by iamrecursion** [comment]
This is already fixed in #1376 and will be part of the next release. For now please check using a nightly build.
