### ISSUE TITLE
Dataflow Analysis Does Not Detect Method Usages

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#1400]
### General Summary

```
main = here.bar 1 2

bar x1 x2 = here.baz x1 x2

baz y1 y2 = y1 + y2
```

For the given program, `DataflowAnalysis` pass does not return all dependencies of the `y1 + y2` expression. It returns only the `baz` definition and body, and not the `baz` usages.

### Steps to Reproduce

``` scala
val expr = ??? // y1 + y2 expression
val meta = module.getIr.unsafeGetMetadata(
  DataflowAnalysis,
  "Empty dataflow analysis metadata."
)
meta.get(expr) // return ids of baz `Method.Explicit` definition and body
```

### Expected Result

For `y1 + y2` expression, dataflow analysis returns `bar` and `main` body expressions as well.

### Actual Result

For `y1 + y2` expression, dataflow analysis returns only the `baz` definition.

### Enso Version

main @ 197190ceeb6647d517d3d0eef983fb17d7af39dc

**Comment by iamrecursion** [comment]
Dataflow analysis does no inspection through methods. Now we don't have UFCS it could be extended to do basic inspection through methods, at least for those defined as statics in the current module. With more work it could also do analysis for statics in other modules, but that would require deeper changes to the compiler.
