### ISSUE TITLE
Improve Support for Dataflow Errors to Work with the IDE

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1409]
### Summary
In order to allow APIs to be better designed around broken value semantics, we need to make some deep changes to the interpreter to support these in a more effective way. At the same time, we need to add a way of propagating panic information through nodes while continuing to execute in the IDE.

### Value
Errors will be handled in a fashion that is amenable to both dataflow-oriented and normal programming.

### Specification

- [x] Add support for traces to broken values. This trace should contain the trace of where the value has been created, with each element being a trace.
- [x] Increase the number of type checks to handle broken values properly in more places. This will slow the compiler down but must include:
  - [x] Atom construction, which should produce a broken value.
  - [x] Method resolution, which should be identity on a broken value.
  - [x] Polyglot arguments evaluation, where the polyglot function should never be called.
  - [x] Function calls should leave things alone except for if the function itself is an error.
- [x] Extend the builtins DSL to handle broken values by performing typechecks in code. These should be profiled. Will need to infer to avoid these typechecks when an argument is a runtime error.
- [x] Properly create broken values in more places (e.g. division by zero).
- [x] Add stdlib tests for these cases.
- [x] Create a `Sentry` value type that contains the panic and the stack trace. This should be an `Exception`.
- [x] Add typechecks to the same places as for broken values that look for the sentry value and re-throw the sentry from the new location.

### Acceptance Criteria & Test Cases

- We handle all of this properly.

**Comment by wdanilo** [comment]
I would add benchmarking as criteria with comparison to the previous version n set of benchmarks - these benchmarks (comparisons) should be part of the PR + demo day.
