### ISSUE TITLE
Noise returns almost the same values.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#1423]
### General Summary

Currently, the noise function does not really work well (please note, that the "empty" on the screenshot below means "100". It was a display bug):

![image](https://user-images.githubusercontent.com/1623053/105491953-78c6d800-5cb7-11eb-830a-799392185124.png)

![image](https://user-images.githubusercontent.com/1623053/105491992-841a0380-5cb7-11eb-8363-be163c279e48.png)

### Steps to Reproduce
Use the code posted above.

### Expected Result
For different seeds, the noise should output non-similar values.

### Actual Result
The values are very similar

**Comment by iamrecursion** [comment]
See [here](https://blogs.unity3d.com/2015/01/07/a-primer-on-repeatable-random-numbers/) for more information on what is expected.
