### ISSUE TITLE
Builtin Array Is Exposing Nulls to Surface Language

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#1424]
### General Summary

It is possible to encounter pure `null` values in the surface language if `Array` elements are accessed when they are not initialized.

### Steps to Reproduce

1. Launch `enso repl`.
2. Do the following steps and observe the output:
```
> a = Array.new 1
>>> Nothing
> b = a.at 0
>>> Nothing
> IO.println b
null
Evaluation failed with: java.lang.NullPointerException
java.lang.Exception: java.lang.NullPointerException
    at org.enso.interpreter.runtime.callable.atom.Atom.lambda$toString$0(Atom.java:80)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    (...)
```
### Expected Result

`null`s should not leak to the user. Printing missing values should not result in a crash.

`Array` API should be designed in such a way to never expose pure `null`s to the user.

### Actual Result

An exception is thrown.

### Enso Version

```
Enso Launcher
Version:    0.2.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: enso-0.2.0 @ d2df28bc43fcfee614fb31780cd46a59ebb16127
Built on:   Linux (amd64)
Current default Enso engine: 
Enso Compiler and Runtime
Version:    0.2.2-SNAPSHOT
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: wip/rw/database-library* @ 7e9d7e0ef10a609ead816375386b86f473219bcd
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Linux 4.15.0-132-generic (amd64)
```

**Comment by kustosz** [comment]
1. Decide between returning `Nothing` or a dataflow error. Error is probably more sensical.
2. Decide whether the array should get populated with the value at the beginning or if it should be null-checked on read.

**Comment by iamrecursion** [comment]
As follows:

- Create `unsafe_uninit_new` to create uninitialized arrays.
- Create `unsafe_nothing_new` to create arrays filled with `Nothing` values.
- Have `new` fill by calling a constructor function (like `Vector.new`). 
- Reads should not check.

**Comment by radeusgd** [comment]
Moved to https://www.pivotaltracker.com/story/show/181935648

<blockquote><div><strong><a href="https://www.pivotaltracker.com/story/show/181935648">Builtin Array Is Exposing Nulls to Surface Language - Pivotal Tracker</a></strong></div></blockquote>
