### ISSUE TITLE
Return a user-facing error instead of an internal error at `ProgramExecutionSupport.scala:413`

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/enso#1456]
### Summary

Trying to serialize an Enso JSON structure in a visualization preprocessor fails with
```
Received unknown message: VisualisationEvaluationFailed(f62cccad-82dd-45f1-8b88-76e515ba41ef,Cannot encode class org.enso.interpreter.runtime.callable.atom.Atom to byte array)
```
This is an internal error, Instead, a nicer user-facing error should be generated. 

### Value

Better error feedback makes everything better.

**Comment by iamrecursion** [comment]
Subsumed by #1557.
