### ISSUE TITLE
Some Documentation is Outdated After Changing Error Handling to Dataflow

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#1460]
### Summary

Many methods have obsolete documentation, for example in `Vector.enso` we have:
```
    ## Get the first element from the vector.

       > Example
         The following code returns 1.
             [1, 2, 3, 4].head
       > Example
         Empty vectors return `Nothing`.
             [].head == Nothing
    head : Any ! Nothing
    head = if this.length >= 1 then this.at 0 else Error.throw Nothing
```

The second example is incorrect, because the new semantics is not returning a `Nothing` value but throwing a dataflow error, so that equation will not hold. The example should probably should be rewritten in some way to show how to catch the errors.

Another similar example is the documentation for `Map.get` which currently states:

```
Gets the value associated with `key` in this map, or returns a `Nothing`, if `key` is not present.
```

which is also not true, because the `Nothing` is not returned anymore; it is thrown instead.

### Value

- The documentation is up-to-date again.
- The examples are not misleading.

### Specification

- [ ] Go through the methods modified in https://github.com/enso-org/enso/pull/1446 and make sure that documentation is correct.

### Acceptance Criteria & Test Cases

- The documentation has been updated and is consistent with the updated implementations.

**Comment by sylwiabr** [comment]
<img width="436" alt="Screenshot 2021-03-25 at 17 33 44" src="https://user-images.githubusercontent.com/12892578/112509923-3b52f980-8d91-11eb-9b53-15f262f0cbef.png">
`File.read` docs
