### ISSUE TITLE
Enso microbenchmarks comparison with other languages

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1479]
### Summary

In Enso we have a set of microbenchmarks implemented to measure the performance of the language. To use those informations for marketing purposes we need to compare them with languages like:
- Python
- C++
- Java
- JavaScript

As a result of this task we should get a table containing: 
- description of microbenchmark
- time in enso
- time in each of languages mentioned above
### Specification

- [ ] Implement the following set of benchmarks in the languages above:
  - [ ] Summing numbers 1 to N, using a loop or recursion, depending on what is more natural in each language.
  - [ ] Creating an N-element (pre-allocated) Vector and filling it with natural numbers.
  - [ ] Summing elements of the vector.
  - [ ] Creating an N-element Cons-list / linked-list.
  - [ ] Summing the Cons-list.
  - [ ] Creating a full binary tree of depth D.
  - [ ] Summing elements on the binary tree.
- [ ] Create a script that can run the set of benchmarks and generate a report.
  - The report should be a CSV file with columns: `benchmark_name`, `language` and `time_i` for each run.
  - [ ] Document any dependencies that are required and how to install them to replicate the results.

### Acceptance Criteria & Test Cases

- [ ] The above set of benchmarks has been implemented and can be replicated locally.

**Comment by radeusgd** [comment]
First we need to specify which exactly benchmarks we want to implement, based on what we currently have I can see the following:
- various methods of summing numbers which demonstrates efficiency of recursion, although for comparison I think we'd want at most 1-2 variants.
- concatenating long pieces of text.
- sorting vectors.
- folding/mapping a linked-list and a vector.
- building an ordered map.

**Comment by mwu-tow** [comment]
Perhaps something from 
https://benchmarksgame-team.pages.debian.net/benchmarksgame/index.html 

This would give us comparison with qiute a number of languages.

<blockquote><img src="./darkfavicon.ico" width="48" align="right"><div><strong><a href="https://benchmarksgame-team.pages.debian.net/benchmarksgame/index.html">Which programming language is fastest? | Computer Language Benchmarks Game</a></strong></div><div>Which programs written in different programming languages are fastest?</div></blockquote>

**Comment by radeusgd** [comment]
The results and repro description are up in the dedicated repository: https://github.com/enso-org/benchmarks/

<blockquote><img src="https://avatars.githubusercontent.com/u/17415943?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/benchmarks">enso-org/benchmarks</a></strong></div><div>Contribute to enso-org/benchmarks development by creating an account on GitHub.</div></blockquote>
