### ISSUE TITLE
Errors And Panics Don't Accumulate Stack Trace

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#1485]
### General Summary

Consider the following example:

```py
from Builtins import all

type MyError

main =
    x = Error.throw MyError
    y = x + 1
    IO.println y


#### METADATA ####
[[{"index": {"value": 93}, "size": {"value": 12}}, "3bbec6c7-a815-412c-b69b-5734a91b3fbf"],[{"index": {"value": 83}, "size": {"value": 5}}, "bbf3930d-6e4b-4bb8-90b7-da391fae9eea"],[{"index": {"value": 55}, "size": {"value": 19}}, "0da4a898-4ee5-4d07-a960-ae548d0c694a"]]
[]
```

When inspecting the above program in the interpreter, both expressions `Error.throw MyError` and `x + 1` have the same stack trace, containing a single element, the `Error.throw` call. In case of panics (if we change `Error.throw` to `Panic.throw`) the stack trace for all affected expressions also contains a single element (the `Panic.throw` call).

### Steps to Reproduce

Run the example in the interpreter. Both internal representations of errors, the `org.enso.interpreter.runtime.error.DataflowError` and `org.enso.interpreter.runtime.error.PanicSentinel` implements `TruffleException`. You can get stack trace of exceptions by calling `com.truffle.api.TruffleStackTrace.getStackTrace(throwable)` (see `ErrorResolver` for examples)

### Expected Result

The stack trace for errors and panics is accumulated and contains previously executed nodes.

### Actual Result

The stack trace for all expressions contains a single element, the origin of an error.

### Enso Version

main @ ef539b6ddfb449ad63da63c55ec83bd4d1256032

**Comment by iamrecursion** [comment]
While filling in the catch/rethrow dance trace would be confusing, it would be good to eagerly fill the stack trace for panics and dataflow errors to the root of the stack, if possible. This provides useful location information.

**Comment by iamrecursion** [comment]
Performance means we can't do better than this.
