### ISSUE TITLE
Spacing needed in weird place

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/enso#1486]
### General Summary
There may be an issue in parser when there's no space between variables and operator.

### Steps to Reproduce

Run this enso code:
```
    time1 = Time
    operator7 = time1.now
    operator8 = operator7.hour
    product2 = operator8*2
```

### Expected Result

current hour (integer) multiplied by 2

### Actual Result

It didn't evaluate `product2`, didn't give any error too. just nothing.
changing `operator8*2` to `operator8 * 2` fixed the issue.

**Comment by radeusgd** [comment]
Out of curiosity I've tried running this code using `enso run` and it seems to work, I just needed to add imports:
```
from Base.Data.Time.Time import all
from Base import all
main =
    time1 = Time
    operator7 = time1.now
    operator8 = operator7.hour
    product2 = operator8*2
    IO.println product2
```

However I noticed a weird thing - `Time` is not exported by default by `Base.Main`, is that expected?
