### ISSUE TITLE
Errors are not descriptive

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#1503]
When trying to add `Number` to `String` I got an error "Type Error" which is not descriptive at all. User facing errors should be much more descriptive:

![image](https://user-images.githubusercontent.com/1623053/108991904-f441ed80-7698-11eb-9197-2cd763577860.png)

**Comment by kustosz** [comment]
@wdanilo a silly mistake in our error reporting. Becomes ```Type error: expected `that` to be Number, but got Text.``` after #1504
