### ISSUE TITLE
Polyglot types do not advertise any type to the IDE and are thus ugly

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#1520]
### General Summary
Polyglot objects are gray in the IDE

### Steps to Reproduce
![image](https://user-images.githubusercontent.com/1214109/109183113-e7eb8c80-778d-11eb-8876-671cce2f5442.png)

### Expected Result
Colors
### Actual Result
No colors

**Comment by farmaazon** [comment]
Gray usually means, that we didn't received any ExpressionUpdate with `type` field for given expression. In this case it is `operator5` in the last node.

**Comment by kustosz** [comment]
@farmaazon yeah I know, that's why this is opened in the engine repo :) I'm sure this is a bug on our side

**Comment by farmaazon** [comment]
Ah, I thought I wrote something new in my comment, but now I see that the info is actually in the title.

**Comment by iamrecursion** [comment]
For types that we can talk about in concrete terms over the `InteropLibrary` protocol we need to advertise their type as the corresponding Enso type. A number returned from JS should have the same colour as an Enso number, and should be treated (in the searcher, for methods, etc) as an Enso number.

**Comment by kustosz** [comment]
The solution to this should include changing the protocol, such that `type` in `ExpressionValueUpdate` is a rich structure, including the language from which the value origins. This will allow the IDE to branch on the language in the interpretation of the type name. Otherwise, it may get confused on non-Enso types.
