### ISSUE TITLE
Disallow Proj.Main

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1534]
### Summary
In a project `Proj` we currently allow `import Proj` as syntactic sugar for `import Proj.Main as Proj`. We no longer want to allow users to import `Main` directly, only allowing the `import Proj` syntax.

### Value
Only one way to do things.

### Specification

- [ ] Disallow all usages of `Proj.Main` in code.
- [ ] Internally treat `import Proj` as `import Proj.Main as Proj`, but don't expose this to users.
- [ ] Disallow modules called `Main` within a project other than the root one.

### Acceptance Criteria & Test Cases

- [ ] Users can no longer import `Proj.Main` directly.

**Comment by mwu-tow** [comment]
Shouldn't this be also disallowed in expressions other than imports? I'd find it strange, if I could use `Proj.Main` in code but not in imports.

**Comment by iamrecursion** [comment]
Call it an issue of me under-specifying. Referring to `Proj.Main` at all should be disallowed.
