### ISSUE TITLE
1.9 beta installer download blocked by chrome 89.0.4389.82

### ISSUE THREAD

**Issue by MURPHYENGINEERING** [enso-org/enso#1552]
Pretty simple one here. Not sure if widespread, but it prevented me from downloading until I noticed.

```
Mixed Content: The site at 'https://luna-lang.org/' was loaded over a secure connection, 
but the file at 'http://packages.luna-lang.org/windows/lunaInstaller.zip' was redirected through an insecure connection. 
This file should be served over HTTPS. This download has been blocked. 
See https://blog.chromium.org/2020/02/protecting-users-from-insecure.html for more details.
```

**Comment by joenash** [comment]
Hi @MURPHYENGINEERING,
1.x (1.9 and below) is no longer supported, as 2.0 is on a completely fresh codebase. You can learn more about that [here](https://medium.com/@enso_org/enso-dev-blog-19th-june-2020-335e528d50b).
A pre-release of 2.0 is now available, if you'd like to try it out: https://github.com/enso-org/ide/releases


<blockquote><img src="https://avatars.githubusercontent.com/u/17415943?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/enso-org/ide/releases">Releases · enso-org/ide</a></strong></div><div>Enso – a visual and textual functional programming language. - enso-org/ide</div></blockquote>
