### ISSUE TITLE
Stacktrace Line Numbers Are Off On Windows

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#1561]
### General Summary

Line numbers in stacktraces are (sometimes) off by a few lines on Windows. It does not happen everywhere, only in some specific circumstances, but I don't know what is the exact reason.

The following repro is a bit *weird* but I could not immediately find a smaller one (for example a few lines program with a Panic displays correct lines).

The issue may be limited just to the stacktraces returned as text from our `get_stack_trace_text` method or it may also affect the stacktraces printed on interpreter failure, I could not determine this for sure.

### Steps to Reproduce

Modify the file `test/Table_Tests/src/Table_Spec.enso` by placing the following code at line 484:
```
            Panic.throw "484"
```
It should be added just below the line 483 which is as of writing this - commit f298fbd:
```
            r = t_1.concat t_2
```
So you should get:
```
483            r = t_1.concat t_2
484            Panic.throw "484"
```

Then, run the code by `enso run test/Table_Tests` or `/path/to/built/engine/bin/enso.bat --run test/Table_Tests` (or on Linux `bin/enso --run test/Table_Tests`).

### Expected Result

The expected result is to get correct line numbers, as is the case on Linux:
```
    - [FAILED] should missing-pad unmatched columns
        Reason: An unexpected panic was thrown: '484'
        at <enso> Panic.throw(Internal)
        at <enso> argument<1>(/home/radeusgd/NBO/enso/test/Table_Tests/src/Table_Spec.enso:484:13-29)
        at <enso> argument<1>(/home/radeusgd/NBO/enso/built-distribution/enso-engine-0.2.7-SNAPSHOT-linux-amd64/enso-0.2.7-SNAPSHOT/std-lib/Test/src/Test.enso:172:18-25)
        at <enso> Panic.recover(Internal)
```

Note how the second line in the stacktrace refers to `Table_Spec.enso:484`.

### Actual Result

On Windows however, I get line 472:

```
    - [FAILED] should missing-pad unmatched columns
        Reason: An unexpected panic was thrown: '484'
        at <enso> Panic.throw(Internal)
        at <enso> argument<1>(G:\NBO\enso\test\Table_Tests\src\Table_Spec.enso:472:19-35)
        at <enso> argument<1>(G:\NBO\enso\built-distribution\enso-engine-0.2.7-SNAPSHOT-windows-amd64\enso-0.2.7-SNAPSHOT\std-lib\Test\src\Test.enso:166:13-69)
        at <enso> Panic.recover(Internal)
```

Note the part `Table_Spec.enso:472`.

### Enso Version

```
>.\built-distribution\enso-engine-0.2.7-SNAPSHOT-windows-amd64\enso-0.2.7-SNAPSHOT\bin\enso.bat --version
Enso Compiler and Runtime
Version:    0.2.7-SNAPSHOT
Built with: scala-2.13.5 for GraalVM 21.0.0.2
Built from: main* @ f298fbd3cfc9f788cfbf1e5e118b790884ff1688
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.10+8-jvmci-21.0-b06
            Windows 10 10.0 (amd64)
```

**Comment by radeusgd** [comment]
The error may be easily reproduced with the newly added test:
```
    - [FAILED] should allow to get the source location of a frame
        Reason: 'Meta_Spec.enso:76:13-38' did not equal 'Meta_Spec.enso:77:15-40' (at D:\a\enso\enso\test\Tests\src\Semantic\Meta_Spec.enso:77-78).
```

**Comment by iamrecursion** [comment]
Blocked by the parser due to the fact that it doesn't handle `\r\n` properly, instead replacing it with `\n`.
