### ISSUE TITLE
Block Expression in Binding Evaluates to a Thunk

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#1567]
### General Summary

Consider the following snippet:

```py
from Builtins import all
                       
main =                 
    x =                
        f a = a + 1    
        f 42           
    x                  
```

In the interpreter (runtime server), variable `x` evaluates to a `Thunk`

- Only reproduces in the interpreter (IDE) mode. Does not happen in CLI (text) mode

### Steps to Reproduce

Run the provided example in the interpreter.

### Expected Result

`x` evaluates to an `Integer`

### Actual Result

`x` evaluates to a `Thunk`

### Enso Version

main @ 8b023e2549faa927794dcd8a419e23d4e331fc50

**Comment by kustosz** [comment]
I think this is a problem of how the compiler attaches source locations in demand analysis – it attaches the location to the variable read, but in case of force nodes, the location should be moved to the force.
