### ISSUE TITLE
Unqualified Imports Should Prefer Types Not Modules

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#1580]
### Steps to Reproduce

Consider the following:
```
from Standard.Base import all

from Standard.Table.Data.Column import Column
import Standard.Table.Io.Csv

Column.print_name = IO.println this.name

main = 
    column = Column.from_vector "Col" [1,2,3]
    column.print_name
```

### Expected Result
The extension method `print_names` is invoked and prints `Col`.

### Actual Result
```
C:\Users\mwurb\enso\projects\Repro>%localappdata%\enso\dist\0.2.7\bin\enso --run .
Execution finished with an error: Method `print_name` of Column could not be found.
        at <enso> Main.main(C:\Users\mwurb\enso\projects\Repro\src\Main.enso:10:5-21)
```

The issue can worked around by defining method on `Column.Column`.

### Enso Version
0.2.7

**Comment by iamrecursion** [comment]
This is actually an issue with selected imports, where, when a module contains an atom with the same name as the module, `from Mod import Mod` imports the module atom, and not the contained atom. We shoul decide what the sensible behaviour is here and fix it.

**Comment by iamrecursion** [comment]
@mwu-tow Does the IDE generate the problematic style of import?

**Comment by mwu-tow** [comment]
@iamrecursion Currently IDE supports only the qualified style of imports, i.e. `import A.B.C`.
