### ISSUE TITLE
When using Enso through the IDE, the file system is accessed very frequently

### ISSUE THREAD

**Issue by s9ferech** [enso-org/enso#1590]
### General Summary
While the IDE is running, a Java process in the background (likely part of the engine) accesses the file system many times per second, even when there is no user interaction. This is not ideal for multiple reasons:
1. It slows down every other file system access. (especially on hard drives)
2. It increases the energy consumption. (especially on hard drives)
3. Hard drives can be damaged more easily while they are running. This is most relevant on laptops.

### Steps to Reproduce
Start the IDE and wait until startup is finished. A tool like `fatrace` will show that the file system is accessed many times per second.

### Expected Result
The disk should only be used infrequently and only for tasks where it is necessary, like backups.

### Actual Result
The disk is accessed many times per second. The following is a representative excerpt of the output produced by `fatrace`:

```
$ sudo fatrace
...
java(161558): W /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-shm
java(161558): R /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db
java(161558): R /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db
java(161558): W /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-wal
java(161558): O /home/s9ferech/enso/projects/Unnamed/.enso
java(161558): C /home/s9ferech/enso/projects/Unnamed/.enso
java(161558): W /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-wal
java(161558): R /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-wal
java(161558): W /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db
java(161558): R /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-wal
java(161558): D /home/s9ferech/enso/projects/Unnamed/.enso
java(161558): CW (deleted)
java(161558): CW (deleted)
java(161558): D /home/s9ferech/enso/projects/Unnamed/.enso
java(161558): CW /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db
java(161558): O /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db
java(161558): R /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db
java(161558): R /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db
java(161558): + /home/s9ferech/enso/projects/Unnamed/.enso
java(161558): O /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-wal
java(161558): + /home/s9ferech/enso/projects/Unnamed/.enso
java(161558): WO /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-shm
java(161558): W /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-shm
java(161558): W /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-shm
java(161558): R /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db
java(161558): R /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db
java(161558): W /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-wal
java(161558): CO /home/s9ferech/enso/projects/Unnamed/.enso
java(161558): W /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-wal
java(161558): R /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-wal
java(161558): W /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db
java(161558): R /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db-wal
java(161558): D /home/s9ferech/enso/projects/Unnamed/.enso
java(161558): CW (deleted)
java(161558): CW (deleted)
java(161558): D /home/s9ferech/enso/projects/Unnamed/.enso
java(161558): CW /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db
java(161558): O /home/s9ferech/enso/projects/Unnamed/.enso/suggestions.db
...
```

### Enso Version

```
$ ./dist/client/enso-linux-0.0.0.AppImage --version
Frontend:
    Version:  1.0.0
    Build:    ba0856e
    Electron: 11.1.1
    Chrome:   87.0.4280.88

Backend:
    Enso Project Manager
    Version:    0.2.6
    Built with: scala-2.13.5 for GraalVM 21.0.0.2
    Built from: enso-0.2.6 @ aec61292c467c3c52e2259ac9e8cd03670c77f15
    Built on:   Linux (amd64)
```

**Comment by 4e6** [comment]
I can see that the backend accesses the `suggestions.db` frequently during the startup. It's a part of the compilation, and it's expected. But when the compilation is complete, there's no FS activity for me (I run `fatrace -tc -C java`)

1. Can you run the `fatrace` with timestamps to see how long and how frequent the file events
2. Can you check that it behaves the same with the latest release https://github.com/enso-org/ide/releases/tag/v2.0.0-alpha.2

<blockquote><img src="https://avatars.githubusercontent.com/u/17415943?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/enso-org/ide/releases/tag/v2.0.0-alpha.2">Release Enso 2.0.0-alpha.2 · enso-org/ide</a></strong></div><div>This is a release focused on bug-fixing, stability, and performance. It improves the performance of workflows and visualizations, and improves the look and feel of the graphical interface. In addit...</div></blockquote>

**Comment by s9ferech** [comment]
Okay, this seems to be a heisenbug. I just ran the exact same executable from earlier but couldn't observe the behaviour anymore. I will let you know when I manage to reproduce it again. It seemed to be very reliable until I created this issue :smile:

**Comment by s9ferech** [comment]
I could reproduce this on Windows 10 and Ubuntu 20.10. And I found out that it stops after writing 344 MiB, which happens within a few seconds on an SSD.

**Comment by 4e6** [comment]
> And I found out that it stops after writing 344 MiB

You mean, `suggestions.db` occupies 344 MiB in the end? Where is all this data written to?

**Comment by s9ferech** [comment]
The file stays small. The process just seems to overwrite it many times

**Comment by 4e6** [comment]
Yesterday I was tackling this issue a bit. Described performance issue comes from the fact that SQLite creates a new journal file per transaction, and the file creation operation can be expensive on some file systems. 

The task specification (when the issue is scheduled):

Improve performance:
- Change the journaling mode to MEMORY. It will significantly speed up all transactions and provide sufficient safety in our use case. Journaling mode is set when the database is created. So, changing the journaling in the existing database requires migration.
- When indexing modules, add batch insert mode with fallback to per-row inserts

Improve error handling:
- Recreate the corrupted database file. Run a simple check `select 1 from suggestions` and recreate the `db` file on errors.
- Add workaround for sick/1999 issue when initializing the database using the `MTable` metadata (see the comment on the init method)
