### ISSUE TITLE
Wrong diagnostics about type mismatch

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#1606]
### Steps to Reproduce
Consider the following
```
main =
    True && 4
```

### Expected Result
Error that right operand of `Boolean.&&` is an `Integer` instead of `Bool`.

### Actual Result
Error that `arg1` of `Boolean.&&` is an `Integer` instead of `Integer`.
```
Execution finished with an error: Type error: expected `arg1` to be Integer, but got 4 (Integer).
        at <enso> Boolean.&&(Internal)
        at <enso> Moje2.main(Moje2.enso:9-10)   
```

### Enso Version
8c9c293f567e4dd4f848cfa686f118c692db4dd3

**Comment by iamrecursion** [comment]
Already reported as #1539.
