### ISSUE TITLE
to_table on geojson

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1625]
### Summary

the goejson: https://opendata.arcgis.com/datasets/0f77c86999a440178f2be3650d00f7f6_2.geojson
if the json has fields `"type": "Feature", "geometry", "properties"` or: `"type": "FeatureCollection", "features"` it should be recognised and the `to_table` method should return `table`

**Comment by 4e6** [comment]
I want to clarify the conversion of geojson format to `Table`.

My questions are:

0. The JSON attached to the issue has the following (simplified) structure.
  ```json
  {
    "type": "FeatureCollection",
    "features": [
      { "type": "Feature", "properties": { "Prop1": 1, "Prop2": "value2", "Prop3": 3 }, "geometry": { "type": "Point", "coordinates": [ -118.58, 34.19 ] } }
    ]
  }
  ```
  From my understanding, the `geojson.to_table ['Prop1', 'Prop2']` expression  should produce a table with columns: "Prop1", "Prop2", "longitude", "latitude". Is my understanding correct?
1. in a `Point` geometry, according to geojson definition of a Position https://tools.ietf.org/html/rfc7946#section-3.1.1, 
  > A position is an array of numbers.  There MUST be two or more
  >    elements.  The first two elements are longitude and latitude, or
  >    easting and northing, precisely in that order and using decimal
  >    numbers.  Altitude or elevation MAY be included as an optional third
  >    element.

  field `coordinates` can contain more coordinates than longitude, latitude, and elevation. Should we support them (how do we name them)? 
2. the geojson format supports different geometry objects https://tools.ietf.org/html/rfc7946#page-5. Do we need to support anything other than `Point`?
3. We already have an extension method `Json.Array.to_table : Vector -> Table` on a JSON array. Should it also understand a JSON array of geojson objects (or should I define the method with a different name)?
4. `properties` can contain nested JSON objects:
  ```json
  {
  "properties": {
    "prop0": "value",
    "prop1": {
      "this": "that"
    }
  }
  ```
  Should we support them? If yes, how do we refer to the nested names when constructing the table? I can suggest merging the names with the underscore `_`, like "prop1_this"

**Comment by sylwiabr** [comment]
0. `to_table` should extract all the properties without taking the list
1. no, we will not support them
2. no, we are supporting just point RN
3. it should understand ISON array go geojson objects
4. merging with underscores or `.` is ok

All of this should be extended while working on https://app.zenhub.com/workspaces/enso-engine-5b57093c92e09f0d21193695/issues/enso-org/enso/1263

<blockquote><img src="No image" width="48" align="right"><div><img src="/dist/favicon/favicon-16x16.png" height="14"> ZenHub</div><div><strong><a href="https://zenhub.com">ZenHub</a></strong></div><div>Project Management and Software Development with GitHub | ZenHub</div></blockquote>

**Comment by sylwiabr** [comment]
> 1. `to_table` should extract all the properties without taking the list

The `to_table` requires a list of fields now - it should not @4e6 @iamrecursion

**Comment by sylwiabr** [comment]
Also please make sure thet trams example published in our repository is working properly

**Comment by 4e6** [comment]
I did not change the interface. The library provides two `to_table` extension methods. One on the JSON array and one on the JSON object.

- `to_table` on JSON array was updated to support GeoJSON features. The function already had this interface with the required `fields` parameter.
- I added `to_table` method on the JSON object. It has an optional `fields` parameter

**Comment by sylwiabr** [comment]
yep, my bad you are right

**Comment by 4e6** [comment]
> Also please make sure thet trams example published in our repository is working properly

I updated the tutorial to support enso-0.2.9 :+1:
