### ISSUE TITLE
Project Manager Should Prioritize Bundled Runtime

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#1645]
### General Summary

The project manager bundle uses local JVM runtime located at `~/.local/share/enso/runtime` even if the bundled one is available:

```
.
├── bin
│   └── project-manager
├── dist
│   └── 0.5.19
├── runtime
│   └── graalvm-ce-java11-21.0.0.2
└── THIRD-PARTY
```

### Steps to Reproduce

1. Download the project-manager bundle (tested with a 0.5.19 [staging release](https://github.com/enso-org/enso-staging/releases/tag/untagged-4f463de63d24169fa87a) 
2. Extract and start the project manager
3. Run the IDE with `--no-backend` flag
    ```
    ./enso-linux-2.0.0-alpha.2.AppImage --dev --no-backend
    ```
4. `ps` shows that the language server is using the local JVM runtime
    ```
    $ ps -ef | grep java
    dbushev   298050  297863 65 17:29 pts/8    00:02:00 /home/dbushev/.local/share/enso/runtime/graalvm-ce-java11-21.0.0.2/bin/java -Dpolyglot.engine.IterativePartialEscape=true -Dtruffle.class.path.append=/home/dbushev/Downloads/enso-project-manager-0.5.19-linux-amd64/enso/dist/0.5.19/component/runtime.jar -jar /home/dbushev/Downloads/enso-project-manager-0.5.19-linux-amd64/enso/dist/0.5.19/component/runner.jar --logger-connect ws://localhost:39415/ --server --root-id 45be41b5-9c64-42e9-bac3-a359fc6661b9 --path /home/dbushev/enso/projects/Test_R --interface 127.0.0.1 --rpc-port 59015 --data-port 61124 --log-level info
    ```

5. If you remove the local runtime, the project manager starts using the bundled one.

### Expected Result

The project manager uses the bundled JVM runtime even if the local one is available.

### Actual Result

The project manager always uses local JVM runtime if available.

### Enso Version

main @ 117ca51921c3475a39e7874d74a8185b9341af26

**Comment by iamrecursion** [comment]
The project manager is doing what is globally correct. The issue is that we don't enable the launcher to download python and graal into the runtimes it downloads, but we should.
