### ISSUE TITLE
Change `Codes.read` to `Image.read`

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#1654]
Currently, to read image wee need to write `Codecs.read`. If I were regular user, I would never ever think of it. It should be named `Image.read` instead.

![image](https://user-images.githubusercontent.com/1623053/113834798-89053400-978b-11eb-9987-899444b4cec0.png)

**Comment by 4e6** [comment]
Read and write `Codecs` functions are re-exported in the `Standard.Image` module

```py
from Standard.Base import all

import Standard.Image

main =
    pic = Image.read "/tmp/cat_1.jpeg"
    pic.histogram 0
```

**Comment by 4e6** [comment]
Related #1670

**Comment by iamrecursion** [comment]
Closing in favour of #1670.
