### ISSUE TITLE
Dev Mode stuck on compiling std libs (Mac 10.15.7 ) (Enso  2.0.0-alpha.2)

### ISSUE THREAD

**Issue by isConic** [enso-org/enso#1657]
### General Summary

Enso dev mode doesn't finish compiling standard library on Mac
![image](https://user-images.githubusercontent.com/48657113/114056585-d226b800-985f-11eb-9254-d0ed30926500.png)
   

## Output in shell:  
![image](https://user-images.githubusercontent.com/48657113/114056488-bcb18e00-985f-11eb-92ef-eef4c215103a.png)
  
## Console in Inspector: 
![image](https://user-images.githubusercontent.com/48657113/114056648-e23e9780-985f-11eb-9c06-5606c06c6eaf.png)

### Steps to Reproduce

``` /Applications/Enso.app/Contents/MacOS/Enso --dev```

### Expected Result

Enso works as expected auto-completed tabs work.  
Inspector shows things

### Enso Version

I ran `/Applications/Enso.app/Contents/MacOS/Enso --version` to get

```
Frontend:
    Version:  1.0.0
    Build:    4c2182f
    Electron: 11.1.1
    Chrome:   87.0.4280.88

Backend:
    Enso Project Manager
    Version:    0.2.6
    Built with: scala-2.13.5 for GraalVM 21.0.0.2
    Built from: enso-0.2.6 @ aec61292c467c3c52e2259ac9e8cd03670c77f15
    Built on:   Mac OS X (amd64)
```

**Comment by wdanilo** [comment]
The warnings you see are unrelated and we know about them. In the console, there is a line telling that logs are hidden and you need to write `showLogs()` to reveal them. Could you do it please and check if there are any errors reported?

**Comment by isConic** [comment]
Odd. I re-opened and it suddenly started working.

**Comment by iamrecursion** [comment]
I'm going to close this for now. Please let us know if you see the same issue happen again!
