### ISSUE TITLE
Project Manager Fails to Initialize on Mac

### ISSUE THREAD

**Issue by grzegorz-bielski** [enso-org/enso#1669]
### What did you do?

Started the enso ide  2.0.0-alpha.3 on the mac os 10.15.7.

### What did you expect to see?

I expected to start an IDE and be able to write a "hello world"

### What did you see instead?

"Failed to intialize application" error:

![Screenshot 2021-04-13 at 21 40 14](https://user-images.githubusercontent.com/22674545/114611291-29ce8480-9ca1-11eb-83df-f409f1ccfa42.png)

### Enso Version

2.0.0-alpha.3 
### Additional notes
I already had the 2.0.0-alpha.1, which worked fine in the past.

Whenever the app starts:
- it first shows a spinner (btw, UX-wise it'd be nice to know what is currently happening during the spinner phase by including some additional messages under loading indicator)
- then it displays a network permission popup - even though it's added in the firewall pane as an app that could accept network connection 🤔 
- and crashes - regardless of which option in the popup, if any is chosen.

**Comment by 4e6** [comment]
@grzegorz-bielski as a quick workaround, you can try to remove the `~/enso` directory with existing projects and see if that fixes the issue.

**Comment by grzegorz-bielski** [comment]
Sorry for the late response 😅 The workaround works fine - thx!

**Comment by 4e6** [comment]
Seems like the problem was not with the firewall, but with the language server initialization. The initialization issue was fixed in #1703
