### ISSUE TITLE
Add Re-exported Methods to the Suggestions Database

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#1670]
### Summary

SuggestionsBuilder should handle the `export` module directive.

### Value

IDE completion provides more accurate suggestions.

### Specification

- [ ] When a module re-exports symbols, they should be added to the suggestions database with an appropriate self-type/module.
- [ ] Search method should filters duplicate re-exported symbols and show only the top re-exported symbol (one with the shortest module name)

### Acceptance Criteria & Test Cases

- [ ] Suggestions database contains re-exported symbols
- [ ] Re-exported methods are preferred and showed in a search response

**Comment by iamrecursion** [comment]
It shouldn't _only_ show the one with the shortest path. It's just that the shortest path should appear first in the searcher.
