### ISSUE TITLE
OpenCV Video Library

### ISSUE THREAD

**Issue by BinarySoftware** [enso-org/enso#1688]
### General Summary

After talking with discord member 'Barckley' we've noticed potetnial of video manipulation using Enso. We already have Image library based on OpenCV, so it shouldn't be too hard to extend it with ability to manipulate videos.

**Comment by barckley75** [comment]
Hi,
thank you Maciej Mikoλajek for opening this issue.
I would like to understand how I can I import openCV in Enso and if it is possible open .edl files.
