### ISSUE TITLE
Inconsistent naming in language keywords.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#1705]
### General Summary

When we are importing things from the foreign language we are using the `polyglot` keyword like 
```
polyglot java import java.lang.Math
```
, while when defining a foreign function we are using the `foreign` keyword like 

```
foreign js calculate_volume area (height = 10) = """
    return area * height;
```

This is confusing. we should have one keyword for dealing with polyglot stuff (my vote goes for making it `foreign java import ...`.

I reported this as a bug as I consider this a big inconsistency in the basic language keywords design, which IMO should be counted as a bug.

**Comment by iamrecursion** [comment]
This is due to a parser limitation. Both were originally intended to be `polyglot`, but the marcin couldn't get the macro system to recognise both.
