### ISSUE TITLE
Extremely slow loading of big files

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#1724]
### Steps to Reproduce
I've created a 1GB file filled with random ASCII printable characters. 
I've benchmarked the time needed to read it:

```
from Standard.Base import all
import Standard.Table

time_it label ~operation =
    start = System.nano_time
    result = operation
    end = System.nano_time
    time = end-start / 10^9
    IO.print_err (label + ": " + time.format "%.3fs")
    result

main =
    here.time_it "read" <|
        (Enso_Project.root / "tfile1G") . read

```

### Expected Result
File loaded in, let's say, less than one second.
For comparison:
* Rust program reads it in ~350ms
* Python program reads it in ~850ms

### Actual Result
File takes 140-160 seconds to read.

Similar results were observed with `read_bytes`, binary file and WSL environment.

### Enso Version

```
Enso Compiler and Runtime
Version:    0.2.11
Built with: scala-2.13.5 for GraalVM 21.0.0.2
Built from: enso-0.2.11 @ 4ba8503575af07e4babe7cdcfd0430040180abb7
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.10+8-jvmci-21.0-b06
            Windows 10 10.0 (amd64)
```

**Comment by iamrecursion** [comment]
I assume you created the file with just effectively `cat /dev/urandom > tfile1G`?

**Comment by mwu-tow** [comment]
This file was limited to printable ASCII characters. But file with fully
random bytes gives similar issue.

śr., 5 maj 2021, 09:40 użytkownik Ara Adkins ***@***.***>
napisał:
