### ISSUE TITLE
Cannot connect to Project Manager outside from localhost

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#1730]
### General Summary
I've wanted to test IDE connecting to the Project Manager being runned on a different machine.

However, Project Manager does not listen for any external connections, as it listens to 127.0.0.1 interface only.

We should have a way to tell Project Manager what interface it should listen on.
The same interface should be later used by the spawned Language Server.

### Enso Version
0.2.11

**Comment by 4e6** [comment]
You can override the interface with the [`NETWORK_INTERFACE`](https://github.com/enso-org/enso/blob/main/lib/scala/project-manager/src/main/resources/application.conf#L4-L5) environment variable. By default, it listens to the localhost.
