### ISSUE TITLE
Documentation in the Suggestions Database

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1735]
### Summary
A placeholder issue for the results of #1698.

### Value

TBC

### Specification

TBC - Discuss with @iamrecursion @4e6 

### Acceptance Criteria & Test Cases

TBC

**Comment by 4e6** [comment]
We decided that the implementation of #1698 design can be split into two parts:

1. This issue implements filling the new `documentation_html` field in the suggestion database.
2. Issue #1794 implements suggestions ordering.
