### ISSUE TITLE
Streaming File Upload

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#1739]
### Summary
While the language server currently provides support for one-shot file access, we want to allow users to work with very large data. This requires streaming file transfers.

### Value

Users will be able to upload large files from the IDE to the backend as necessary.

### Specification

- [x] Design the protocol additions.
- [ ] Implement the specified protocol additions.
- [ ] Files should be written to disk in a _streaming_ manner. We do not want to keep any large amount of the file resident in memory at once.
- [x] Add a method to the `Visualization` library that is `.file_being_uploaded : Any ! File_Being_Uploaded`. This should throw a dataflow error type `File_Being_Uploaded file_path`. This will allow the IDE to display loading spinners along the propagation path for that file's data.

### Acceptance Criteria & Test Cases

- [ ] The language server has comprehensive support for streaming file uploads and downloads.

**Comment by farmaazon** [comment]
> * [x]  In addition to the above, the protocol should support _upload resumes_. If the initial message contains a byte offset that is not 0, the receiving end should check if the file exists and is up-to-date for that byte offset. If not, an error should be returned. If the files do not match, the receiving end must respond with the byte offset it _does_ have, and the sender can resume from there. `overwrite` must _not_ be set, and offset must be > 0 for a resume to occur.

One comment here: perhaps we should validate checksums of already uploaded file part (not only the number of bytes).

**Comment by iamrecursion** [comment]
Yeah. Good thought! I've added it to the task description.

**Comment by iamrecursion** [comment]
Things to consider:

- [x] Do we want a separate capability for this?
- [x] How should it interact with the existing file protocol?
- [x] How should we support bidirectionality?
- [x] What checksumming form should we use?

**Comment by iamrecursion** [comment]
Please note that the main functional requirements have been met with a significantly more simple protocol that is stateless.
