### ISSUE TITLE
Installing Project Dependencies

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#1770]
### Summary

While the IDE will handle downloading libraries that are added to the project, CLI users also need a way to install any dependencies, for example when they download a project shared by someone. Even if the dynamic loading logic were able to download libraries lazily/on-demand (see #1768), we still definitely want a way to 'preload' before running the program.

We need a way to scan all files in the project to analyse what dependencies it has. This needs to use the parser, to know the imports.

The logic for scanning the imports may also be re-used in the upload command if we decide that a manifest listing the dependencies should be included for more efficient downloads ([see the discussion](https://github.com/enso-org/enso/issues/1750#issuecomment-850871688)).

### Value

- CLI users can preinstall any required dependencies.

### Specification

- [x] Re-use the component that can parse all project files and extract a list of imported packages without running the project.
- [x] Use the downloader (#1772) to install the dependencies that were found.
- ~~Implement the `enso install library <name> --edition=<edition>` command.~~
- [x] Implement the `enso install dependencies` command which if run inside of a project installs all of its dependencies and the engine that it should use.

### Acceptance Criteria & Test Cases

- The above specification has been completed.
- [ ] Tests were added which test the dependency discovery mechanism.
- [ ] If reasonably possible, some tests for the installation mechanism were also added.

**Comment by iamrecursion** [comment]
How does this interact with the proposal for manifests on upload?
