### ISSUE TITLE
Add a method returning the file content in most convenient type according to the file extension.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#1801]
### General Summary

There should be a function in Enso Stdlib for reading File, which returns a value with type depending on the file's extension:
* `Text` for `*.md`, `*.txt`
* `Image` for `*.jpg`, `*.png`
* `Table` for `*.csv`
For other files, the returned value should beof  a new special `Binary` type. The `to_default_visualization_data` method of `Binary` should return its content as a json text.

### Motivation

This gives our users the best experience, especially in terms of drag'n'dropping files in IDE: they do not need to specify how to get the proper type from the `File`: the most usable type is just given to them.

**Comment by iamrecursion** [comment]
Additionally:

- `.json`
- `.geo-json`
- `.png`

Needs more design clarification.
