### ISSUE TITLE
Nonvideo Tutorial

### ISSUE THREAD

**Issue by jhgorse** [enso-org/enso#1823]
### General Summary

A tutorial in static text and images.

### Motivation

YouTube is a great technology for conveying some kinds of information. Some people struggle to learn from videos. I am one of those people, particularly when it comes to software. I learn software in a non-linear fashion. I start with a straightforward goal, then scan the tutorials or reference examples for the tools necessary to achieve the goal. I copy and modify existing working things, observe state, and explore the boundaries.

Where can I find a concise list of useful things, like parsing a csv, grouping data, and plotting?

**Comment by iamrecursion** [comment]
Sorry for such a belated response! Yes, this is definitely on our radar! We're hard at work on some stuff for YCombinator at the moment, but we hope to be getting to this soon! 

For now you might have some luck with the [Enso syntax reference](https://enso.org/docs/syntax) which shows code alongside the reference with links.

I hope that helps!
