### ISSUE TITLE
Functions should have a default visualization

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#1828]
### Summary

Currently a function returns `null` as its default visualization:

```
f = x -> x + 2
f.to_default_visualization_data
```

It seems that due to that, the IDE shows an empty box as the function's visualization which can be confusing to users (for example suggesting that there may be an error).

The function should instead return some kind of string description, minimally that says that this is a function, or also if possible, it could include some more information.

### Value

- Opening visualizations on a function will be less confusing.

### Specification

- [ ] Implement a specialized version of `to_default_visualization_data` for the function type that provides some basic information about the function.
- [ ] Make sure that this is enough for the visualization to show up in the IDE.
  - If not, some additional changes may be necessary or possibly a task on IDE's side should be created if needed.

### Acceptance Criteria & Test Cases

- [ ] There are tests which run `to_default_visualization_data` on a function and check the result.
- [ ] A function shows a reasonable visualization inside the IDE, suggesting that this is a function.

**Comment by iamrecursion** [comment]
An ideal solution would allow runtime inspection of the function to provide actually useful information like "how many unapplied arguments" it has and "which arguments are defaulted", and so on. It may be worth doing this as part of #1673, as we want this to work for all "callable" entities, which are currently a bit of a mess.
