### ISSUE TITLE
A Vector full of dataflow errors can be created (and breaks visualizations)

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#1830]
### General Summary
1. Errors can be stored in Vectors (they probably should propagate through vector writes? Same as they propagate through Atom instantiation, @wdanilo @iamrecursion please say what you think about this).
2. A vector containing errors will break the visualization system (which, depending on the answer to 1. is, or isn't a problem :))

### Steps to Reproduce
Create a node like this: 
![image](https://user-images.githubusercontent.com/1214109/124511837-547b3580-ddd7-11eb-8541-855fa75f26b4.png)

### Expected Result
An error. Or a visualization containing an error inside.

### Actual Result
The node will never visualize

### Enso Version
alpha.6

**Comment by wdanilo** [comment]
`[_]` should be treated like atom OR as a function which creates some kind of atom inside, so the error should be propagated, right.

**Comment by iamrecursion** [comment]
I would agree that it should propagate, but this probably ties to the work on admitting NPEs in array writes as well (#1424).
