### ISSUE TITLE
Properly Handle Default Edition

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#1864]
### Summary

Currently, the configuration allows to set the default Enso engine version (for example using `enso default` launcher command). However since the introduction of the edition system, it is the edition, not engine version, that is important for setting up the project - as there could be multiple editions tied to a single engine version.

We need to replace this system with the new one - `enso default` should set the default edition and this default edition should be respected when creating new projects or opening projects with no edition specified.

Currently, a temporary default edition is the default edition tied to the current engine version, but the goal is to make it configurable and default to the latest installed engine version instead.

### Value

- Project configuration is consistent.

### Specification

- [ ] Modify the global configuration to specify a default edition instead of engine version.
- [ ] Modify the `enso default` command.
- [ ] Modify the `Runner` to properly handle the default edition.
- [ ] Modify the `ProjectCreationService` and `ProjectService` to properly handle the default edition.

### Acceptance Criteria & Test Cases

- The above specification has been completed.
- [ ] The changes have been sufficiently tested.

**Comment by iamrecursion** [comment]
#1930 is possibly related.
