### ISSUE TITLE
Project created with alpha7 is not working with alpha8

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#1865]
### General Summary

I have a project created with alpha7 package and it is not working with alpha8:
[Main.enso.zip](https://github.com/enso-org/enso/files/6821506/Main.enso.zip)

First issue:
After running it as it is I am getting error in the console:
```
Execution of function main failed. Compiler Internal Error: Attempted to import the unresolved module Standard.Base.Data.Time.Time during code generation. Defined at Mixpanel_Daily.Main[7:1-7:35].
```
Second issue:
fixing imports manually leads to:
<img width="339" alt="Screenshot_2021-07-13_at_21 06 51" src="https://user-images.githubusercontent.com/12892578/125755489-73451e71-38f7-4f65-ad70-7bd741907569.png">

### Expected Result

fully working workspace
### Enso Version

alpha 8 release

**Comment by iamrecursion** [comment]
Project now works.
