### ISSUE TITLE
Use system's default browser for sign-in

### ISSUE THREAD

**Issue by Gregoor** [enso-org/enso#2006]
Heya,

I feel it's a bit of an anti-pattern to open the sign-in in an app-controlled browser window. Both my Google and GitHub account are too important for me to want to share credentials to them with apps other than my browser.
Would it be possible to open those in the system's default browser with a callback back into the app?

Thanks for the cool product!

**Comment by wdanilo** [comment]
Hi @Gregoor! I'm sorry for the little slow reply. Yes, let's do it. We will still keep the login screen integrated with the app (for convenient usage for people that know it's safe), but we will also add a button "login via browser" – would it work for you this way?
