### ISSUE TITLE
Graph API - Node remove and edit.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#2146]
### Summary
Implement node operations in graph API designed to being used by Graph Editor view.

### Specification
The operations to implement are:
- Node remove (without checking for variable usage so far - it will be handled by disconnecting node first).
- Change node expression
- Moving nodes (update metadata).

### Acceptance Criteria & Test Cases
Operations works in Graph Editor.

**Comment by somebody1234** [comment]
my bad -_- these reports should be on the cloud issue instead
- https://github.com/enso-org/cloud-v2/issues/2146
