### ISSUE TITLE
IDE Performance Issues

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#2571]
## Issues
I have extensively tested the performance of IDE and I have found several critical issues listed below. Please feel free to partition them into separate issues if needed, but I believe we can just fix them and untick them here instead to keep a single performance thread for an easy overall picture.

1. - [x] IDE logs so many things to console that it gets unresponsive sometimes. Logging to console should be enabled by a developer for debugging purposes, but never in the final product on the `main` branch. The console should be empty and should contain warnings and errors ONLY until the logs will not be enabled during runtime on purpose. This needs to be fixed ASAP.

2. - [ ] Writing a SINGLE LETTER in searcher costs 30ms parser time (this will be fixed with new parser) + 90ms of updating the "list view", which is caused by regeneration of MSDF things on every keystroke (!). This means that updating the view on each key-press in searcher makes the GUI run at MAX 10 FPS.

3. - [ ] After moving each node, all nodes get event `set_expression` which causes them to be re-drawn from scratch. This is a huge bottleneck for scenes containing many nodes.

4. - [ ] After opening an empty scene, a node is created, and its expression is set to `"Hello world"` 6 times (!!!), and then it gets probably deleted cause it's not visible on the stage. Moreover, the expression `"Hello world"` is set on it every time a node is moved.

5. - [ ] After starting the new project and putting node `12` on the stage, you have to wait 6-8 seconds to get it colored. The next nodes are getting colored fast, but the first is really, really slow.

6. - [ ] I have nodes `12` and `_.asin` on the stage. I'm connecting `12` to `_`. As the result: the expression `"Hello world"` was set 4 times, the expression `12` was set 4 times, and the expression `number1.asin` was set 4 times.

7. - [ ] Create node `12`. You will get 15 notifications that its type is `None` and then 4 notifications that its type is `Number`.

8. - [ ] Create node `12`. On each move, you will get 2 events about its type (should be 0).

9. - [ ] Create node `12`. Press tab, select `asin`, press enter. We will get several interesting events. First, we got event about new expression `number1.asin` with INCORRECT `SpanTree` containing only `Root` node covering the whole expression. The correct `SpanTree` will be emitted later.

10. - [ ] ![image](https://user-images.githubusercontent.com/1623053/112777397-73cd2e80-9042-11eb-8b06-812e9efd0121.png)
    Guess how many times our theme manager is queried for colors for a given type after I remove the second node and keep on the scene only the first one?  <details><summary>Click me to learn the answer.</summary><p>The answer is: 1600</p></details>

**Comment by Erudition** [comment]
+1 for Tauri, this makes perfect sense for Enso and can easily replace Electron

**Comment by braebo** [comment]
I use them together a lot.  Rust on the backend with Tauri is a huge performance boost.

The performance of Svelte blows React away - especially when paired with `nanostores`, and dev speed with it is much faster too.  SolidJS would also be a killer alternative if you can't give up JSX.

**Comment by Erudition** [comment]
Svelte is nice, but I don't expect them to rewrite the UI - switching to Tauri however can be like running in a different browser (webview) which means very little of the codebase needs to change (just the packaging). I don't see anything wrong with whatever they're using for the UI but the performance bottleneck of electron is too important to ignore and now easy to replace (one can also use NeutralinoJS for example)
