### ISSUE TITLE
The `mouse_down` event is not delivered to shapes if not under project view

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#2899]
### What did you do?
I have created a shape and attached it to the scene root (as the only object in the debug scene).

### What did you expect to see?
All mouse events working correctly.

### What did you see instead?
`mouse_down` event was never emitted, while `mouse_out` and `mouse_over` were emitted correctly.

### Enso Version
0867867ca2264557915d2ca8e9e90f7d22773996

**Comment by wdanilo** [comment]
Fixed in https://github.com/enso-org/enso/pull/3351
