### ISSUE TITLE
MacOS binary is not signed/notarised

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#3016]
There is an issue with signing the macOS package. This happened after upgrading the GraalVM to version 21.

Relevant PR enso-org/ide#1640 addressing the GraalVM version change.

<img width="255" alt="Screenshot_2021-06-28_at_14 59 49" src="https://user-images.githubusercontent.com/357683/123671029-7fe5a980-d846-11eb-9a62-24dc33f8cc8b.png">

### What did you do?

Open the Enso IDE.

### What did you expect to see?

An Enso IDE opens without an error message.

### What did you see instead?

An error message.

### Enso Version

[Enso 2.0.0-alpha.6](https://github.com/enso-org/ide/releases/tag/v2.0.0-alpha.6)
Last working build (with GraalVM 20) https://github.com/enso-org/ide/actions/runs/967308683

**Comment by kneczaj-p44** [comment]
How can I workaround this to run the app? Is it possible?

**Comment by vitvakatu** [comment]
@kneczaj-p44 I think you can. Try opening your `Applications` folder in Finder, right-click `Enso` and choose `Open`. It should override MacOS' security restrictions.
