### ISSUE TITLE
Text editor has a huge lag when editing code

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#3021]
### What did you do?
Played around with the text editor in a moderately large (130 lines) file.

### What did you expect to see?
My edits being applied instantly

### What did you see instead?
https://drive.google.com/file/d/1VkxxM0HDt6GXxBIVSeiIroJMKuKRxKGh/view?usp=sharing

### Enso Version
```
Frontend:
    Version:  1.0.0
    Build:    470a2684
    Electron: 11.1.1
    Chrome:   87.0.4280.88

Backend:
    Enso Project Manager
    Version:    0.2.11
    Built with: scala-2.13.5 for GraalVM 21.0.0.2
    Built from: enso-0.2.11 @ 4ba8503575af07e4babe7cdcfd0430040180abb7
    Built on:   Mac OS X (amd64)
```

**Comment by jur-bsw** [comment]
Still just known this problem? At my pc is laggy ....
