### ISSUE TITLE
Progress Bar Integration

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#3029]
### Summary

For a long time, the engine has been providing progress notifications regarding installation of a missing engine/runtime. Soon the same notifications will also be used to report progress of library downloads.

The IDE should handle these notifications to display progress bars to the user.

For now the engine does not have a concept of grouping multiple progress-tasks into a single one, so each sub-task is handled with a separate progress bar (subtasks are for example: downloading and installing the engine, separately downloading every dependency). In the future we will probably want to introduce some kind of grouping to better show which sub-tasks are related and estimate the overall progress, but given other priorities, this is a lower priority for now. For now, it would be good to be able to display the progress at all.

My proposition is to do it in similar fashion as IDEs like IntelliJ do it - just display the progress bar in the lower right (or some other) part of the screen indicating that an action is in progress. The progress bars will for now show up separately for download and installation etc. but at least the user will get the feedback.

In case of the libraries we can also track overall that the library is being installed, as it starts when the 'preinstall' request is sent and when it is done, a reply to that request will be sent, so all the time between that the IDE can show some indeterminate progress indicator that the library is being installed and in the meantime show the more granular progress bars for each component, as described above.

### Value

- The user gets more visible feedback that some long running process (like a download) is progressing.

### Specification

- [ ] Implement a graphical component for the progress bar.
- [ ] Handle the `task/*` progress notifications and display progress bars accordingly.

### Acceptance Criteria & Test Cases

- The progress bars correctly display in the IDE, for example when an engine is being downloaded.

**Comment by iamrecursion** [comment]
I think this has become more important with the editions system fully integrated. I just got very confused as to why a project of mine "wasn't opening" as it had been made with an older edition and was downloading the associated engine version.

**Comment by radeusgd** [comment]
> I think this has become more important with the editions system fully integrated. I just got very confused as to why a project of mine "wasn't opening" as it had been made with an older edition and was downloading the associated engine version.

If I understand correctly, the behaviour would be exactly the same prior to editions - before editions were integrated, if you had another project with some older engine version, that engine would be downloaded too, at least that was the idea.

But yeah, I think at least some very basic implementation, like displaying the messages from the `task/progress-update` in the corner and clearing them on corresponding `task/finished` (so without any actual progress bars) should be simple and would already give the user useful feedback that 'something is happening in the background'.
