### ISSUE TITLE
Searcher does not accept the text entered

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#3084]
### What did you do?

https://user-images.githubusercontent.com/12892578/128323950-102a6d64-dd26-4e37-a796-134c8a01acea.mov

### What did you expect to see?

node `operator4.at "ADVERTISER" == "Jerry Gooze"`
### What did you see instead?

`operator4.java_table`
### Enso Version

Frontend:
    Version:  1.0.0
    Build:    13b57af5
    Electron: 11.1.1
    Chrome:   87.0.4280.88

Backend:
    Enso Project Manager
    Version:    0.2.19
    Built with: scala-2.13.6 for GraalVM 21.1.0
    Built from: enso-0.2.19* @ e56a33b3dcd2b157b52b2c01b44403f1c511fa22
    Built on:   Mac OS X (amd64)

**Comment by farmaazon** [comment]
You had the first entry selected when pressing enter: in that case we prefer the selected suggestion over the typed text (which is likely to be a pattern). Of course, we should probably fix the UX there, when going back in searcher input.
