### ISSUE TITLE
Weirdly high CPU & GPU usage while idling (IDE)

### ISSUE THREAD

**Issue by fwip** [enso-org/enso#3124]
### What did you do?

Opened up the ENSO IDE, and created a new project. I waited a while, to allow it to finish compiling dependencies and get to a steady state.

### What did you expect to see?

CPU and GPU usage should be relatively low when Enso is idle.

### What did you see instead?

Enso Helper (GPU) using >80% of GPU, and WindowSever and Enso Helper (Renderer) using high CPU levels.  Screenshot attached - the initial spike is during Enso project initialization, and then settles to a slightly calmer steady-state.
[Screenshot](https://i.imgur.com/H809aPI.png)

### Enso Version

2.0.0-alpha.18 - I previously observed similar performance on 2.0.0-alpha.16.

### Additional notes
Testing done on a 2019 16" Macbook Pro. (2.6Ghz 6-core i7, 16GB RAM).
Moving the mouse is noticeably just a little slow - not impossible to use, just doesn't "feel snappy."

Resource utilization goes back to normal when Enso is quit, minimized, or on a non-visible virtual desktop.

**Comment by bdevel** [comment]
I have seen this behavior as well for 2.0.0-alpha.14. Seemed about the same usage for the large Restaurants example as for a simple example.

I don't know much about the internals of the IDE, but I suspect the issue is the draw loop is continuously re-drawing the interface even if there are no updates.

```
# Macbook, 2.8 GHz Quad-Core Intel Core i7 Intel Iris Plus Graphics 655 1536 MB
Process                   CPU %   GPU %
Enso Helper (GPU)	  54.7    55.1 (seen as high as 80% when idle)
Enso Helper (Renderer)    32.9     0.0	
Enso                       1.9     0.0	
Enso Helper                0.0     0.0
```

The renderings look great though! Good job.
