### ISSUE TITLE
Detailed tool installation instructions

### ISSUE THREAD

**Issue by ekmett** [enso-org/enso#3136]
I'm starting to install enso on a fresh Mac laptop and figured it would be useful to start to capture the additional install steps glossed over in the README.

### General Summary

I'd like us to offer a more complete onboarding instructions.

### Motivation

It'd make it easier to onboard developers.

**Comment by ekmett** [comment]
### Steps Taken

Starting after all the `git` setup users have on a fresh laptop on a Mac, my steps taken so far:

Installing `rustup`:

```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
$ . "$HOME/.cargo/env"
```

Installing LTS node through the installation link provided.

Installing NVM:

```
$ curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
```

From here it gets messier as we need to install GraalVM.

**Comment by ekmett** [comment]
Let's install sdkman as a way to manage java installations:

```
$ curl -s "https://get.sdkman.io" | bash
$ source "$HOME/.sdkman/bin/sdkman-init.sh"
```

You'll want to add `source "$HOME/.sdkman/bin/sdkman-init.sh"` to the end of your `.profile` here as well.

We can validate it is working, by installing `sbt` with `sdk`.

```
$ sdk install sbt
$ sbt --version
```

We need the version of GraalVM that is based on JDK 11.

and our build explicitly wants Graal-21.1.0, not the current version 21.3.0 nor the community edition.

If you are not on an M1 mac you can simply use

```
$ sdk install java 21.1.0.r11-grl
```

and skip down to **Resume Here**

If you _are_ on an M1 Mac, you'll need to help this process along, and go to

https://www.oracle.com/downloads/graalvm-downloads.html

and change the GraalVM version selection to `21.1.0` and java version `11` to download the current version for your platform. This will require you to quickly register an Oracle account if you don't already have one.

Once you download the tarball from there you need to extract it.

```
cd ~/Downloads
tar xzf graalvm-ee-java11-darwin-amd64-21.1.0.tar.gz 
```

Install it:

```
sudo mv  graalvm-ee-java11-21.1.0 /Library/Java/JavaVirtualMachines
```

Get your Mac to unquarantine it if you are on Catalina or later:

```
sudo xattr -r -d com.apple.quarantine /Library/Java/JavaVirtualMachines/ graalvm-ee-java11-21.1.0 
```

Now we have a version of graal installed. 

We can tell sdkman about how to find it:

```
$ sdk install java 21.1.0.r11-grl /Library/Java/JavaVirtualMachines/graalvm-ee-java11-21.1.0/Contents/Home
```

and use it by default

**Resume Here**

In either case, we can set this up to be used by default.

```
$ sdk default java 21.1.0.r11-grl
```

Back in the `enso` folder:

```
$ sdk use java 21.1.0.r11-grl
$ sdk env init
```

**Comment by vitvakatu** [comment]
There is actually a easier way to install required GraalVM via sdkman:

```
sdk install java 21.1.0.r11-grl
```

`r11` here means `JDK 11`, there are also `r8`, `r17` and so on. 

`sdkman` is also a recommended tool for `sbt` installation (at least on Linux, where you don't have `brew`), so we could mention it in instructions as well:

1. Install sdkman
2. `sdk install sbt`
3. `sdk install java 21.1.0.r11-grl`

**Comment by ekmett** [comment]
```
sdk install java 21.1.0.r11-grl
```

doesn't work for me.

I'm thinking its because this happens to be an M1 mac?

**Comment by ekmett** [comment]
I should adopt the standard name though, so that is handy information nonetheless!

**Comment by ekmett** [comment]
Switching the instructions above to use the `sdk` version of `sbt` might be better as well.

**Comment by ekmett** [comment]
Updated to include the easy path for normal users.

**Comment by ekmett** [comment]
Next up you'll need to install `flatbuffers`. 

We currently require 1.12, not the current 2.0 release, so `brew install flatbuffers` won't just work.

Grab the tarball from https://github.com/google/flatbuffers/releases/tag/v1.12.0

Open it up, inside that directory you can `cmake . && make` then copy `flatc` out to somewhere in your `PATH`. 

<blockquote><img src="https://opengraph.githubassets.com/e0cd96f8fad94f1b3c229be7ca6aebe65a8a24f4326777e6a4320f6d726279ef/google/flatbuffers/releases/tag/v1.12.0" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/google/flatbuffers/releases/tag/v1.12.0">Release FlatBuffers release 1.12.0 · google/flatbuffers</a></strong></div><div>A summary of what is in this release since 1.11.0:

An official Swift port! (including gRPC support).
A Kotlin port!
Object API and native JSON support for C#.
Object API and gRPC support for Pytho...</div></blockquote>

**Comment by vitvakatu** [comment]
> then copy flatc out to somewhere in your PATH.

`[sudo] make install` is probably the easier way.

**Comment by ekmett** [comment]
Tried that first. 

`make install` fails before I get there because of the test failures.

So we either need to patch out the `-Werror` thing or leave the user these Rube-Goldberg-esque instructions.

**Comment by ekmett** [comment]
I'd also usually tell `cmake` to build in an Xcode on a mac, and build in a side-directory like a good open source citizen, but the former was being cranky about my installed XCode version.

**Comment by wdanilo** [comment]
@ekmett what is the status of this issue? Would you be able to integrate it with our installation docs, please? Did the status of our toolchain improved and is everything still valid here? I'm wondering if @mwu-tow work would not invalidate some of the required steps here – what do you think @ekmett and @mwu-tow ?
