### ISSUE TITLE
Unexpected compiler error when following Tutorial 101

### ISSUE THREAD

**Issue by elrnv** [enso-org/enso#3156]
### General Summary

Following [ tutorial 101](https://www.youtube.com/watch?v=3f6FE1dgMNw&ab_channel=Enso) I get an unexpected compiler error indicating that a variable I have provided is not defined.

(Also wanted to add that I think this project is really awesome, and I'm excited to see it flourish! I've been following on and off for the past few years now :))

Edit: Deleting the `Table.new` node and creating it anew removes the compiler error.

### Steps to Reproduce

Following the steps in the tutorial until the state in the screenshot:
![Screenshot from 2021-11-10 12-11-18](https://user-images.githubusercontent.com/1807432/141187389-01ef287f-eae3-44ff-9198-5d3100c08846.png)

### Expected Result

A correctly created table.

### Actual Result

The table node erroring with "Compile error: Variable `var1` is not defined."

### Enso Version

enso-linux-2.0.0-alpha.18.AppImage

Frontend:
    Version:  1.0.0
    Build:    cb893fde
    Electron: 11.1.1
    Chrome:   87.0.4280.88

Backend:
    Enso Project Manager
    Version:    0.2.31
    Built with: scala-2.13.6 for GraalVM 21.1.0
    Built from: enso-0.2.31* @ a0b558d0b0e59410a17d2b0b62c599a29aa60f06
    Built on:   Linux (amd64)

**Comment by wdanilo** [comment]
Hi! thanks for reporting it. Would you be so nice and show us a screenshot of the generated code, please? To open the code press ```ctrl + <the key under escape, in most cases it is "`">```

**Comment by elrnv** [comment]
I tried it again with a windows enso 2.0.0-alpha.17 and tried your shortcut, but it seems the code is a bit cut off. I couldn't select multiple lines unfortunately to copy paste the code. Here is what I see:
![image](https://user-images.githubusercontent.com/1807432/141863504-bc3fb11d-4842-482a-97e2-ddd76e456b9b.png)

Edit: It seems that the text selection just didn't show multiple lines, but was actually selecting, so here is the full code I think
```
from Standard.Base import all
import Standard.Base.Data.Noise
import Standard.Base.Data.Number.Extensions
import Standard.Table.Data.Table
import Standard.Visualization

func1 number1 number2 =
    operator2 = number1.up_to number2
    operator3 = operator2.to_vector
    operator31 = operator3.map .noise
    operator4 = operator31.map (x -> x + 20)
    operator5 = operator4.sort
    operator6 = operator5.take_end 5
    operator6

main =
    number1 = 0
    number2 = 100
    operator6 = here.func1 number1 number2
    number3 = 200
    number4 = 300
    operator2 = here.func1 number3 number4
    operator3 = Table.new [var1, var2]
    var1 = ["latitude", operator6]
    var2 = ["longitude", operator2]
```

**Comment by jdunkerley** [comment]
We have changed a couple of the APIs since we produced this tutorial. There should be a new version of this tutorial available now.  (@xvcgreg can you link please?).

Instead of `take_end 5`, you need to use `take (Last 5)`.
Additionally, the default imports have been updated to: 

```
from Standard.Base import all
from Standard.Table import all
import Standard.Visualization
```

And finally if you reconnect the output of the two func1 calls to the `Table.new` the IDE should reorder the code so `var1` and `var2` are defined before use.

**Comment by xvcgreg** [comment]
> We have changed a couple of the APIs since we produced this tutorial. There should be a new version of this tutorial available now. (@xvcgreg can you link please?).

Sure, here it is: https://youtu.be/_Twh45PI_vU

<blockquote><img src="https://i.ytimg.com/vi/_Twh45PI_vU/maxresdefault.jpg" width="48" align="right"><div><img src="https://www.youtube.com/s/desktop/faa006c1/img/favicon_144x144.png" height="14"> YouTube</div><div><strong><a href="https://www.youtube.com/watch?v=_Twh45PI_vU">Enso 101</a></strong></div><div>Welcome to Enso!In this introduction video, we will demonstrate basic interactions with Enso GUI as well as simple data creation, manipulation, and visualiza...</div></blockquote>
