### ISSUE TITLE
broken link from old (archived) repo

### ISSUE THREAD

**Issue by techieshark** [enso-org/enso#3209]
### General Summary

Anyone trying to get here via the old repo hits dead end.

### Steps to Reproduce

1. Go here: https://github.com/enso-org/ide/blob/develop/README.md 
2. click here 
![image](https://user-images.githubusercontent.com/1072292/147558695-55b547ec-a350-45a7-aab8-923b65210aca.png)

3. observe:
![image](https://user-images.githubusercontent.com/1072292/147558662-58c34d9e-1359-4b6a-82bc-a73865f44614.png)

### Fix

https://github.com/enso-org/enso/tree/develop/gui should be https://github.com/enso-org/enso/tree/develop/app/gui (note the "app/")

**Comment by vitvakatu** [comment]
Thank you for creating an issue! `enso-org/ide` repository is now archived, so making changes to it is a bit complicated, but we will try to fix it.

**Comment by wdanilo** [comment]
@techieshark thanks so much for noticing it! Fixed! :)
