### ISSUE TITLE
clarify which file to download

### ISSUE THREAD

**Issue by techieshark** [enso-org/enso#3213]
### General Summary

For new users, it is unclear what file in the releases to download. Not sure what the differences are between the `bundle`, `engine`, `launcer` or `project manager`. 

I think the README needs updating now that you've moved to a monorepo? Note the first link goes to an archived repo.

![image](https://user-images.githubusercontent.com/1072292/147717879-6f2c48ba-4d78-42b5-89b7-abf4ed23bdea.png)

### Motivation

![image](https://user-images.githubusercontent.com/1072292/147717802-c6db0640-4e22-4101-a720-451c1ddffc0c.png)

**Comment by Igorgro** [comment]
Also, none of these files contains IDE and the link in the Readme leads to archived repository. Where it can be downloaded?

**Comment by Sintrastes** [comment]
The website also seems to link to the old (archived) repo: https://github.com/enso-org/ide/

<blockquote><img src="https://opengraph.githubassets.com/f1ececfd4b0a6a28429743d3609f5764ff340cb2debe05cfa3f2d55e99eeb83c/enso-org/ide" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/ide">GitHub - enso-org/ide: Enso – a visual and textual functional programming language.</a></strong></div><div>Enso – a visual and textual functional programming language. - GitHub - enso-org/ide: Enso – a visual and textual functional programming language.</div></blockquote>

**Comment by IsaacTell** [comment]
I think this is now resolved. https://github.com/enso-org/enso/blob/develop/README.md now points to https://github.com/enso-org/enso/releases which has clear instructions of what to download.

**Comment by jdunkerley** [comment]
Closing as instructions improved and download link also from ensoanalytics.com.
