### ISSUE TITLE
Incorrect typecheck case

### ISSUE THREAD

**Issue by ljkania** [enso-org/enso#33]
I've run into this wrong typecheck:
![screen shot 2017-09-05 at 13 04 37 2](https://user-images.githubusercontent.com/7061422/30058343-dcb8a3d4-923a-11e7-9414-da2d9c8056a1.png)
Expected type: `[Int]`
Actual type: `*`

What is more, in function `powers` type is correct:
![screen shot 2017-09-05 at 13 04 53 2](https://user-images.githubusercontent.com/7061422/30058356-e3ac9d26-923a-11e7-80c7-bdfa2e4a1830.png)

Code:
```
def main:
    powers 1 . take 100
def powers s:
    Prepend s (powers ((-2)*s))
```

**Comment by mikusp** [comment]
I believe that since compile errors are surfaced in Luna Studio, this will not occur anymore. If I am wrong, please move back to backlog.
