### ISSUE TITLE
Need a web based API/SDK search

### ISSUE THREAD

**Issue by raould** [enso-org/enso#3436]
Thanks for making enso, truly mind boggling. Please add a way to free text search for API/SDK documentation so e.g. if I see a tutorial that talks about "to_json" I can type that in and find the docs for that specific function. Should of course be able to click on types and follow along to expand out learning from there. etc.

If such a thing already exists I certainly didn't find it so I'd suggest making it more available.

**Comment by wdanilo** [comment]
@raould we are right now working exactly on that. In the future release of Enso you will have a rich component browser with nicely integrated documentation that will be searchable, will have examples and hyperlinks to other parts of it. We might generate an HTML view out of it as well, but I'm not sure if this is what we want, as an integrated documentation in the product might give you much nicer experience. What do you think about it?

You can also find some scratch of generated docs on our website, but TBH, that was a very initial approach and I don't find the result even close to being readable: https://enso.org/docs/reference

<blockquote><img src="http://enso.org/img/meta/og-image.jpg" width="48" align="right"><div><strong><a href="https://enso.org">Enso | Get insights you can rely on. In real time.</a></strong></div><div>Enso is an award-winning interactive programming language with dual visual and textual representations. It is a tool that spans the entire stack, going from high-level visualisation and communication to the nitty-gritty of backend services, all in a single language.</div></blockquote>

**Comment by raould** [comment]
mvp-- might just be a text input at the top of all current doc pages that runs google search with site restriction.

**Comment by wdanilo** [comment]
@raould This is how the new searcher and the new doc view will look like in a few months. Let's start with that (the doc will be searchable). I'd love to hear your thoughts after testing it. Would it work for you?

<img width="825" alt="image" src="https://user-images.githubusercontent.com/1623053/168730307-9e21d2e0-d1bc-4961-8030-02c09a1523a9.png">

**Comment by jdunkerley** [comment]
We now have the initial versions of documentation at help.enso.org.
