### ISSUE TITLE
electron + nvidia: "GPU process isn't usable. Goodbye."

### ISSUE THREAD

**Issue by lidorcg** [enso-org/enso#3801]
### General Summary
When executing [enso](https://github.com/enso-org/ide/releases/tag/v2.0.0-alpha.18) AppImage.
Encountering the following crash on startup:
```
FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye.
```

It is a known issue of electron + nvidia which can be bypassed by passing `--no-sandbox` to electron, however enso wraps electron and doesn't seem to support passing args to it so I'm not able to bypass this issue.

### Steps to Reproduce
This issues occur on startup on some computers with nvidia gpus

### Expected Result
Enso should load normally 

### Actual Result
Enso crashes at startup

### Enso Version
v2.0.0-alpha.18

**Comment by wdanilo** [comment]
Interesting, I'd add an option to pass custom flags to electron this week and I'll let you know. I'd be very thankful if you test then if that helps. If so, we will catch this error and pass this flag automatically then. Thanks for the help!

**Comment by lidorcg** [comment]
:+1: np, waiting for the update :smile:

**Comment by wdanilo** [comment]
Hi @lidorcg, sorry for offset. I'm working on it, but I have some problem with new electron version on macOS. Next week it should be done.

**Comment by wdanilo** [comment]
@lidorcg ok, implemented: https://github.com/enso-org/enso/pull/3869

Unfortunately, there is a problem with merging it now (described in the PR). If we would not be able to fix it, I'd prepare a simpler version for now.

**Comment by MCSH** [comment]
Hi, any updates on this issue?

**Comment by wdanilo** [comment]
@lidorcg finally fixed! https://github.com/enso-org/enso/commit/663ed1e07efc081436989eab4e3b89e9e5fb80aa 

Would you be so nice and try it out + confirming if it works on your end, please?
