### ISSUE TITLE
Discussion Links in New Issue Tab Are Broken

### ISSUE THREAD

**Issue by zicklag** [enso-org/enso#3891]
### General Summary

These links on [this page](https://github.com/enso-org/enso/issues/new/choose) are broken:

![image](https://user-images.githubusercontent.com/25393315/202739445-4f709a25-8778-49df-817b-bb192ff591e0.png)

I was checking to see if GitHub the right place to post ideas.

**Comment by xvcgreg** [comment]
Issue for that has been created on our board, thank you.

**Comment by xvcgreg** [comment]
updated
