### ISSUE TITLE
Substituting "x.json_serialize" with "json_serialize" (currying) doesn't work on visualization expression

### ISSUE THREAD

**Issue by notdanilo** [enso-org/enso#426]
### General Summary
Using `json_serialize` instead of `x.json_serialize` in visualization expression doesn't work.

### Steps to Reproduce
Use `json_serialize` instead of `x.json_serialize` in visualization expression.

### Expected Result
`x.json_serialize` and `json_serialize` should be equivalents.

### Actual Result
Using `json_serialize` doesn't work.

### Enso Version
- Please include the output of `enso --version`.

For example:
```
Enso Compiler and Runtime
Version:    0.0.1
Built with: scala-2.13.2 for GraalVM 20.1.0
Built from: main* @ 07265e616419dabca8d1ee22a1d13c36086ede0a
Running on: OpenJDK 64-Bit Server VM GraalVM CE 20.1.0, JDK 1.8.0_252-b09
            Linux 5.4.0-33-generic (amd64)
```

**Comment by kustosz** [comment]
Happens because of unimplemented interop library for `UnresolvedSymbol`.

**Comment by notdanilo** [comment]
@iamrecursion I haven't made any change. I just downloaded the artifacts generated by this action https://github.com/enso-org/enso/actions/runs/144628274

<blockquote><img src="https://avatars0.githubusercontent.com/u/17415943?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by iamrecursion** [comment]
> @iamrecursion I haven't made any change. I just downloaded the artifacts generated by this action https://github.com/enso-org/enso/actions/runs/144628274

Huh, strange that it's saying dirty worktree then. 



<blockquote><img src="https://avatars0.githubusercontent.com/u/17415943?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by kustosz** [comment]
The `dirty` issue may be because our CI flow possibly generates something that's not .gitignored?
