### ISSUE TITLE
Integrate the Searcher Database with Runtime and API

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#438]
### Summary

The task to wire up all the Searcher components.

### Value

IDE can start using the Searcher API.

### Specification

- [x] Extend Runtime API to be able to talk to the database.
- [x] On IR changes update the database and send the updates to users.
- [x] On IR execution complete the database with type information.
- [x] Connect Runtime API with Language Server API.
- [x] Load package metadata when starting the Language Server
- [x] Convert an absolute location used in the `IR` to the `Position` relative to a line used in the JSON API
- [x] Add information about external ids to the database. 
  They will be used when completing the database with runtime type info.
- [x] Index module on file open command
- [x] Clean index on file remove command
- [x] Create a database file in a project directory

### Acceptance Criteria & Test Cases

- The database is updated on source changes.
- Language Server API is wired to the runtime and ready to use.

**Comment by 4e6** [comment]
Turned out that `search/completion` request requires converting the file path to the module name. To do that, the Language Server needs to load the package info. It should also update it on the `refactoring/renameProject` request.

I added an extra task in the Specification section of the description above ^

**Comment by iamrecursion** [comment]
Good to know.

**Comment by 4e6** [comment]
More unplanned things that have been done (issue description updated)

- Load package metadata when starting the Language Server
- Convert an absolute location used in the `IR` to the `Position` relative to a line used in the JSON API
- Add information about external ids to the database. They will be used when completing the database with runtime type info.
