### ISSUE TITLE
Rust parser doesn't link/run on Mac M1

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4664]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183635511).
<hr />

Marcin [has discovered](https://discord.com/channels/401396655599124480/1034429857431556107) that the `libenso_parser.dylib` cannot be loaded into the Enso engine on his Mac M1. Very likely the library isn't created for the right architecture.

GraalVM doesn't support M1 processor (tracked as #182269744) and runs in rosetta emulator. Rust builds for ARM by default, so if Graal runs on Rosetta it's not going to work. We need to fix the build script to x-compile.

## Comments:
I have found [following advice](https://stackoverflow.com/questions/68139162/how-can-i-cross-compile-rust-code-into-intel-assembly-on-an-arm-m1-apple-silicon) on stackoverflow. (jaroslavtulach - Oct 26, 2022)
<hr />
It works with the following changes (though this diff would break any other platform, so some love is needed):

```diff
diff --git a/build.sbt b/build.sbt
index 3430e0c82..49d2fdc40 100644
--- a/build.sbt
+++ b/build.sbt
@@ -678,7 +678,7 @@ val generateRustParserLib =
     allLibs.isEmpty ||
     (`syntax-rust-definition` / generateRustParserLib).inputFileChanges.hasChanges
   ) {
-    Seq("cargo", "build", "-p", "enso-parser-jni") !
+    Seq("cargo", "build", "-p", "enso-parser-jni", "--target", "x86_64-apple-darwin" ) !
   }
   FileTreeView.default.list(Seq(libGlob)).map(_._1.toFile)
 }

diff --git a/lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java b/lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
index cd4b3be7e..c0b3731a6 100644
--- a/lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
+++ b/lib/rust/parser/generate-java/java/org/enso/syntax2/Parser.java
@@ -13,7 +13,7 @@ public final class Parser implements AutoCloseable {
     for (; ; ) {
       File parser;
       if (os.startsWith("Mac")) {
-        parser = new File(dir, "target/rust/debug/libenso_parser.dylib");
+        parser = new File(dir, "target/rust/x86_64-apple-darwin/debug/libenso_parser.dylib");
       } else if (os.startsWith("Windows")) {
         parser = new File(dir, "target/rust/debug/enso_parser.dll");
       } else {
```

The fix is _delivered_.

Marcin got everything working on his Mac M1. I integrated the changes as part of [PR-3842](https://github.com/enso-org/enso/pull/3842). However later @murbanczyk found we have problems on regular Macs. As such I had to integrate also [PR-3850](https://github.com/enso-org/enso/pull/3850). That might again break Mac M1, alas.

Marking _delivered_. Giving Marcin (as the only known owner of Mac M1) a chance to _accept_/_reject_. (jaroslavtulach - Nov 4, 2022)
<hr />

**Comment by JPMoresmau** [comment]
I have a MacBook with Apple silicon, and I ran into the same issues on current `develop` branch. I had to make the suggested changes to `build.sbt` and `Parser.java` and also change the architecture pretty name in the Rust code to harcode `amd64` and then I could get the IDE to build and run.

**Comment by wdanilo** [comment]
@JPMoresmau thanks for the report. Hmm, it seems that it was not properly fixed or the bug re-appeared. I think that no one from our Engine team works on M1/M2 macs, so this platform is not heavily tested, unfortunately. In GUI, we are building the IDE with pre-built engine binaries, to save time: `./run ide watch --skip-version-check --skip-wasm-opt --backend-source release --backend-release latest`.

@JaroslavTulach, @hubertp, could you look at it please? Can we incorporate these changes to SBT so it will build on M1/M2 seamlessly as on other platforms?

**Comment by JaroslavTulach** [comment]
I am afraid that neither me nor Hubert have access to M1 hardware. We can indeed review changes, but we cannot verify they work.

> Marking delivered. Giving Marcin (as the only known owner of Mac M1) a chance to accept/reject. (jaroslavtulach - Nov 4, 2022)

Moreover comment says the fix has been integrated on Nov 4, 2022. Is there a new problem? Does any other owner of M1 hardware sees a problem?

**Comment by wdanilo** [comment]
@JaroslavTulach I believe that no one in our team compiles engine on M1/M2. @JPMoresmau would you be able to create a small PR with the changes you needed to run it correctly on your machine? Do not care about cross-platform compatibility, we will take care of it.

**Comment by JPMoresmau** [comment]
OK, submitted https://github.com/enso-org/enso/pull/6862

**Comment by jdunkerley** [comment]
Need engine team (or libs team) to have access to a M1/M2 Mac.

Get access to a Virtual Machine - the #6862 needs the build.sbt to add the new argument conditionally.

**Comment by jdunkerley** [comment]
We now support AArch64 builds for nightly releases.
