### ISSUE TITLE
Macros and Operators Don't Get Resolved in Interpolated String Expressions

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#477]
### General Summary

Expression segments inside interpolated segments do not get macro-resolved. The expressions inside are in the app-prefix-list form.

### Steps to Reproduce

Try parsing 
```
main = '`2+2`'
```

The expression inside backticks returned by parser is:
```
Node(
  None,
  None,
  Prefix(
    Node(
      None,
      None,
      Prefix(
        Node(
          None,
          None,
          Number(None,2)
        ),
        0,
        Node(
          None,
          None,
          Opr(+)
        )
      )
    ),
    0,
    Node(
      None,
      None,
      Number(None,2)
    )
  )
)
```

The same happens with other macros, such as `if ... then ... else ...` etc.

### Expected Result
The expression inside is resolved to an infix application.

### Actual Result
The expression is not macro resolved.

### Enso Version
e2d901fb68845c979a49bf31756308971d3ec6c9

**Comment by iamrecursion** [comment]
Will be fixed by the new parser.
