### ISSUE TITLE
Implement better option parsing for Enso CLI

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#480]
### Summary
Currently, the Enso CLI uses quite a confusing and messy options scheme, which is the result of using just the basic Apache Commons CLI parsers. This should be improved, to provide a more consistent and overall better user experience.

### Value
Better experience for the CLI users.

### Specification
The current version of CLI is the main function defined here: https://github.com/enso-org/enso/blob/master/engine/runner/src/main/scala/org/enso/runner/Main.scala

The new CLI should provide the following options format:
```
enso command [--option-name=option-value...]
```
Where `command` is one of:
1. `repl`, with no additional options.
2. `run`, with one mandatory option `--path`, taking a path to a file or package directory.
3. `new`, with one mandatory `--path` option, taking a path to the root of the newly created package.
4. `server`, with the following options:
  a. `--port` - an integer defaulted to `8080`.
  b. `--interface` - a string defaulted to `localhost`.
  c. `--root-id` - a mandatory UUID option.
  d. `--root-path` - a mandatory path option.
5. `jupyter-kernel`, with no additional options.
6. `version`, with no additional options.

The semantics of each of these commands should be retained based on the existing implementation.
Whenever `enso command` where `command` is not a valid command is run, a help message listing all the available commands should be displayed.
If `command` is a valid command, but the provided options are invalid, a command-specific usage message should be displayed.

As an exception, `enso --version` should work the same as `enso version`.

The implemented solution should be easily extensible with new commands or options for existing commands.

### Acceptance Criteria & Test Cases
- There exist automated tests for the implemented functionality.
- The implemented interface conforms to the specification above.
- The implementation conforms to the code standards described in this repository.

**Comment by iamrecursion** [comment]
As an update, this should now use our own [cli](https://github.com/enso-org/enso/tree/main/lib/scala/cli/) library instead of decline and the like.
