### ISSUE TITLE
Parsing "Int.+" Yields InvalidSuffix

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#482]
### General Summary
When trying to parse extension operator methods, I get InvalidSuffix nodes from parser.

An attempt to fix this issue by @wdanilo (with me acting as proxy) is here: https://github.com/enso-org/enso/tree/wip/mwu/parser-extension-operator-fix
When fixing this issue, please let us know, what was wrong.

### Steps to Reproduce
Run the parser on the following input:
```Int.+```

### Expected Result
`Infix` with operand Cons(Int), operator Opr(.) and operand Opr(+).

### Actual Result
Prefix with function Cons(Int) and argument InvalidSuffix{elem: Opr(.), suffix: "+"}.

### Luna Version
latest master 56287522710f44b006a24c408e843c9d119ffcfd

**Comment by iamrecursion** [comment]
Will be fixed with the new parser.
