### ISSUE TITLE
Design for Date/Time support

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4961]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182655461).
<hr />

- Review the current LocalDate support provided across the polyglot boundary
- Review the functions provided in other data tools and ensure sufficient support in Enso types
- Agree scope for Time and DateTime support across polyglot boundaries

## Blockers:
[#182973664](https://www.pivotaltracker.com/story/show/#182973664) resolved
[#182987210](https://www.pivotaltracker.com/story/show/#182987210) resolved
[#182987539](https://www.pivotaltracker.com/story/show/#182987539) resolved
[#183080911](https://www.pivotaltracker.com/story/show/#183080911) resolved
[#181755990](https://www.pivotaltracker.com/story/show/#181755990) resolved
[#183081112](https://www.pivotaltracker.com/story/show/#183081112) resolved
[#183033133](https://www.pivotaltracker.com/story/show/#183033133) resolved
[#183081152](https://www.pivotaltracker.com/story/show/#183081152) resolved
[#182987539](https://www.pivotaltracker.com/story/show/#182987539) resolved
[#183082087](https://www.pivotaltracker.com/story/show/#183082087) resolved
[#183102448](https://www.pivotaltracker.com/story/show/#183102448) resolved
[#183336003](https://www.pivotaltracker.com/story/show/#183336003) resolved
[#183102477](https://www.pivotaltracker.com/story/show/#183102477) resolved
[#183794849](https://www.pivotaltracker.com/story/show/#183794849) blocked

**Comment by jdunkerley** [comment]
Related:
- [ ] #5267

**Comment by jdunkerley** [comment]
Closing as design completed.
