### ISSUE TITLE
Component Browser should not include PRIVATE entries

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4962]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184215360).
<hr />

Component browser shows methods that have the PRIVATE tag. These should be excluded.

## Comments:
 (Hubert Plociniczak - Jan 12, 2023)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2023-01-25):

**Progress:** I've implemented filtering out the components with a "PRIVATE" tag from the component browser. The code just needs to be cleaned up a bit and should be ready for review. It should be finished by 2023-01-26.

**Next Day:** Next day I will be working on the [#183604295 task](https://www.pivotaltracker.com/story/show/183604295). The latest VCS restore issues on the server end have been fixed. I'll go through my code one last time, test everything and with some luck submit the PR for review. (Enso Bot - Jan 25, 2023)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2023-01-26):

**Progress:** I've restructured the code to skip "PRIVATE" components right at the start when the list builder is populated, added a test for removing components with a "PRIVATE" tag, and opened the PR for review. Then I had a fight with git and started the book club challenge to not leave it until the last minute. It should be finished by 2023-01-26.

**Next Day:** Next day I will be working on the [#183604295 task](https://www.pivotaltracker.com/story/show/183604295). When the "reload module sources" fix is merged I'll test the VCS restore functionality, go through my code one last time, and prepare the PR for review. (Enso Bot - Jan 26, 2023)
<hr />
**Galin Bajlekov** reports a new **🔴 DELAY** for today (2023-01-30):

**Summary:** There is **5 days** delay in implementation of the [Component Browser should not include PRIVATE entries (#184215360) task](https://www.pivotaltracker.com/story/show/184215360).
It **will cause 5 days delay** for the delivery of this weekly plan.

**Delay Cause:** Delay due to addressing comments that were brought up during code review. (Enso Bot - Jan 30, 2023)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2023-01-30):

**Progress:** I've been cleaning up the code for this PR and addressing comments that were brought up during code review. It should be finished by 2023-01-31.

**Next Day:** Next day I will be working on the [#183604295 task](https://www.pivotaltracker.com/story/show/183604295). I'll go through my code one last time, and prepare the PR for review. (Enso Bot - Jan 30, 2023)
<hr />
**Galin Bajlekov** reports a new **STANDUP** for today (2023-01-31):

**Progress:** I've been addressing code review comments, and started implementing a toggle for switching on/off the inclusion of private entries in the component browser as requested. It should be finished by 2023-01-31.

**Next Day:** Next day I will be working on the [#183604295 task](https://www.pivotaltracker.com/story/show/183604295). I'll go through my code one last time, and prepare the PR for review. (Enso Bot - Jan 31, 2023)
<hr />

**Comment by farmaazon** [comment]
Starting QA
