### ISSUE TITLE
Component Browser Focus

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4966]
```[tasklist]
### Tasks
* [ ] #5326 
* [ ] #5335 
* [ ] #5336 
* [ ] #5337
``` 

This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/180872763).
<hr />

### Why

**As Enso IDE user**
**I want ** to be able to navigate between Component Browser Panels
**So that ** I don't need to switch to mouse when working with the Component Browser.

### Scope

[This design section](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#focus)

### Acceptance Criteria

```gherkin
Scenario: 
Given an open Component Browser
When I hold Panel Focus Selection Directional Modifier and press the arrow keys on the keyboard
Then the focus switches in a visible way between CB Focus Areas as described in the design doc, in a non-cyclic way

When I press the arrow keys on the keyboard
Then I am able to navigate between the Focus Areas of the Component Browser as described in the design doc, in  a non-cyclic way

When I press the Left or Right mouse button while the mouse pointer is over one of the entries of the Component List Panel
Then the Component Browser List becomes the Active Focus Area 
And the clicked entry becomes the Active Focus Item
```

**Notes:**

## Blockers:
[#183618034](https://www.pivotaltracker.com/story/show/#183618034) blocked
[#183618069](https://www.pivotaltracker.com/story/show/#183618069) blocked
[#183618091](https://www.pivotaltracker.com/story/show/#183618091) blocked
[#183618110](https://www.pivotaltracker.com/story/show/#183618110) blocked
[#183747460](https://www.pivotaltracker.com/story/show/#183747460) resolved

## Comments:
Based on discussion with @farmaazon,  adding support for Inactive Focus Item highlighting to the Component Group view is in the scope of this task. (Mateusz Czapliński - Apr 15, 2022)
<hr />
**Design Review** review set to **pass** (Adam Obuchowicz - Oct 25, 2022)
<hr />
Nice to have for the release but not crucial (James Dunkerley - Feb 2, 2023)
<hr />

**Comment by farmaazon** [comment]
This should be redesigned for the new design. @wdanilo [The document](https://github.com/enso-org/design/blob/main/epics/component-browser/design2.md) does not mention how the focus should work.

**Comment by wdanilo** [comment]
We will implement that after the release. So for now let's leave this open and I will describe that when I'll be back :)

**Comment by farmaazon** [comment]
Closing as the focus design changed in new CB.
