### ISSUE TITLE
Visualization pre-view under the searcher input.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4968]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/180872321).
<hr />

### Why

**As Enso IDE user**
**I want ** to see the visualization of currently highlighted suggestion under the node
**So that ** I can see how the suggested method can work with my data.

### Scope

"Visualization Preview Panel" point in [this section](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#panels) and [related global shortcuts](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#visualization-preview-panel)

* The visualization preview should be shown and working. It should show the evaluation result of 
  * the current expression input if there is no component selected in Component Panel,
  * the expression resulting from applying the currently selected component in Component Panel.
* The preview should look like our current visualizations under the nodes (the design shows how they will look like once Graph Editor will be remastered - but that is a part of another epic).
* The standard libraries' methods' arguments shall have sensible defaults. 
* Navigating focus is **not** in the scope.

### Acceptance Criteria

```gherkin
Scenario: 
Given I have newly created project opened in Enso IDE
When I open searcher to add new node
Then I see visualization preview under the node
When I select various components
Then the visualization displays the output of the node with applied component
When I press enter
Then node is added to the stage and visualization works
When I start editing this node and select some component and abort editing
Then node is reverted to previous expression, and visualization shows the same data as before.
```

**Notes:**

## Tasks:
- [ ] #182633483
- [ ] #182633515
- [ ] #182633544
- [ ] #182633582
- [ ] #182633967
- [ ] #182634050
- [ ] #182634001
- [ ] #182634059
- [ ] #182634086
- [ ] #182720308
- [ ] #182926584

## Comments:
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-07-02):

**Progress:** Proposed a fix for the memory leak in the integration of the Searcher Panel integration. Integrated Review Feedback for previous PR, which is now ready to merge. Slight delays here due to build system issues (as described in the thread). I will also open a PR with a proposed fix to avoid this in the future.  . It should be finished by 2022-08-12.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180872321). Further reading up on the code for the Searcher Controller / Presenter to be able to create the task list for #180872321. Note that the proposed end date for this task here is unsure, and might well be earlier. Better estimate once I have the task list talked through with Adam (Enso Bot - Jul 3, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for the provided date (2022-07-02):

**Progress:** Worked on the planning for the Features of this user story. Research on the existing functionality, discussion with Adam about how to break down the tasks. Note this was meant to be for 2022-07-03, but cannot be posted due to Enso Bot bug It should be finished by 2022-08-12.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180872321). Get feedback on task breakdown, refine, get started on the first task. (Enso Bot - Jul 4, 2022)
<hr />
**Design Review** review set to **pass**

Add some minor comments about missing AC cases. (Adam Obuchowicz - Jul 8, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for the provided date (2022-07-04):

**Progress:** Worked on planning for the "Visualization pre-view under the searcher input.". Creating the tasks in pivotal and refining with Adam. It should be finished by 2022-08-12.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180872321). Implement Acceptance Review feedback for #180872321 and get started on #182633483 (Enso Bot - Jul 13, 2022)
<hr />

**Comment by farmaazon** [comment]
Implemented.
