### ISSUE TITLE
Icons of entries in Component Browser List taken from documentation

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4969]
```[tasklist]
### Tasks
- [ ] #5324 
```

This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/181061048).
<hr />

### Why

**As Enso IDE user**
**I want ** to see icons in Component Browser suggestion entries matching the icons specified by the libraries' authors
**So that ** The list look nicer, and I can look for a specific icon when looking at the list.

### Scope

[This section](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#icons)
The icons for Submodules section are provided in "documentation section". 

### Acceptance Criteria

```gherkin
Scenario: 
Given library entries of Module, Atom, Method kind with documentation assigning an `Icon:` name from a list of supported icon names
When I open Component Browser and navigate to modules containing those entries
Then I can see that the entries are rendered with non-default icons matching the names assigned in their documentation.

Given library entries of Module, Atom, Method kind with no `Icon:` assigned in documentation, or an `Icon:` with a name not from a list of supported icon names, or given library entries of Local or Function kind
When I open Component Browser and navigate to modules containing those entries
Then I can see that the entries are rendered with default icons matching the kind of those entries, different for each kind.
```

**Notes:**

## Tasks:
- [X] #182584322
- [X] #182584326
- [ ] #182584311
- [X] #182584336

## Comments:
**Mateusz Czapliński** reports a new **STANDUP** for yesterday (2022-06-28):

**Progress:** Discussed questions and hints related to User Story design on a planned call with AO+WD. Wrote a draft of a Tasks list; had the draft reviewed and approved; moved the Tasks from the list to Pivotal; added Task descriptions + ACs; added US ACs. It should be finished by 2022-06-28. (Enso Bot - Jun 29, 2022)
<hr />
**Design Review** review set to **pass** (Adam Obuchowicz - Jul 7, 2022)
<hr />

**Comment by farmaazon** [comment]
Done in GUI2
