### ISSUE TITLE
Improved scrolling

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4970]
```[tasklist]
### Tasks
- [ ] #5374 
- [ ] #5375 
```

This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/182713594).
<hr />

### Why

**As Enso IDE user**
**I want ** to have scrolling working as in the [design doc](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#scrolling) (with exceptions listed below in Notes)
**So that ** I will have good experience with scrolling.

### Acceptance Criteria

```gherkin
Scenario 1: 
Given the scroll_area debug scene
When the user scrolls the Scroll Area contents in various ways using the mouse
Then the scrollbars behave as described in the design doc (with exceptions listed below in Notes).

Scenario 2: 
Given the IDE with the Component Browser open
When the user scrolls the Component Browser contents in various ways using the mouse and the keyboard
Then the scrollbars in the Component Browser behave as described in the design doc (with exceptions listed below in Notes).
```

**Notes:**
 - A change from the design doc was introduced: The fragment: *"The desired view is defined in such a way, that the click point should define the target for the center of the scrollbar."* - now applies only when holding a modifier key on the keyboard (any one of: Shift, Command, Alt, Option).

## Blockers:
[#183390576](https://www.pivotaltracker.com/story/show/#183390576) blocked
[#183390649](https://www.pivotaltracker.com/story/show/#183390649) blocked
[#183390702](https://www.pivotaltracker.com/story/show/#183390702) resolved
[#183390749](https://www.pivotaltracker.com/story/show/#183390749) resolved

## Comments:
**Mateusz Czapliński** reports a new **STANDUP** for yesterday (2022-09-26):

**Progress:** Checked the source code to verify that seemingly missing features are not actually implemented. Wrote a list of draft tasks. It should be finished by 2022-09-27.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/182713594). Discuss the task drafts with AO. After approved, create Tasks in Pivotal. (Enso Bot - Sep 27, 2022)
<hr />
**Mateusz Czapliński** reports a new **STANDUP** for yesterday (2022-09-27):

**Progress:** Discussed task drafts with AO, GO and WD. Did some changes to the drafts afterwards to incorporate the results of the discussion. Promoted the drafts into Tasks in Pivotal. It should be finished by 2022-09-27.

**Next Day:** Next day I will be working on the [##183389761 task](https://www.pivotaltracker.com/story/show/183389761). First, write 360 feedback. If time permits, start working on #183389761 afterwards. (Enso Bot - Sep 28, 2022)
<hr />

**Comment by farmaazon** [comment]
In GUI2 we use browser scrolling.
