### ISSUE TITLE
New look of the components' documentation.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4973]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/180872953).
<hr />

### Why

**As Enso IDE user**
**I want ** to see new look of documentation
**So that ** browsing the modules or atoms I see the content.

### Scope

The documentation is designed in [this section](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#documentation-panel). Inserting examples and extracting panel to window is **not** in the scope.

* Having cursor visible is _in_ scope of this US. It should be handled simply: when the cursor is over the documentation panel, we allow displaying the system pointer. We should also, if possible, scroll documentation panel when it's mouse-hovered, without need to click the panel first.
* "Working with links" section should be a separate US. Therefore, the "Method" section's synopsis (and other) should not encourage clicking at method names.
* Icons shall be exported as SVG from Figma.
* The HTML should be constructed in GUI, basing on the documentation sections sent by Engine. The HTML should use [tailwind CSS](https://tailwindcss.com).
* Ask Dmitry how exactly sub-types work now, how they are reported to GUI in suggestion database, how their fully-qualified names work.
* There should be also a task for displaying ["Hovered item preview. Press RMB to lock it"](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#mouse-navigation) when hovering entries in mouse

### Acceptance Criteria

```gherkin
Scenario: 
Given
When
Then
```

**Notes:**

## Blockers:
[#183970872](https://www.pivotaltracker.com/story/show/#183970872) resolved
[#183970838](https://www.pivotaltracker.com/story/show/#183970838) resolved
[#183970810](https://www.pivotaltracker.com/story/show/#183970810) resolved
[#183970777](https://www.pivotaltracker.com/story/show/#183970777) resolved
[#183970215](https://www.pivotaltracker.com/story/show/#183970215) resolved
[#183992227](https://www.pivotaltracker.com/story/show/#183992227) blocked
[#183992207](https://www.pivotaltracker.com/story/show/#183992207) resolved
[#183992025](https://www.pivotaltracker.com/story/show/#183992025) resolved
[#184012363](https://www.pivotaltracker.com/story/show/#184012363) resolved
[#184012397](https://www.pivotaltracker.com/story/show/#184012397) resolved
[#184012434](https://www.pivotaltracker.com/story/show/#184012434) resolved
[#184012517](https://www.pivotaltracker.com/story/show/#184012517) resolved
[#184012727](https://www.pivotaltracker.com/story/show/#184012727) blocked
[#184024198](https://www.pivotaltracker.com/story/show/#184024198) blocked
[#184024179](https://www.pivotaltracker.com/story/show/#184024179) blocked
[#184024167](https://www.pivotaltracker.com/story/show/#184024167) blocked
[#184024148](https://www.pivotaltracker.com/story/show/#184024148) resolved
[#184024127](https://www.pivotaltracker.com/story/show/#184024127) resolved
[#184042175](https://www.pivotaltracker.com/story/show/#184042175) resolved

## Comments:
**Ilya Bogdanov** reports a new **STANDUP** for the last Friday (2022-12-02):

**Progress:** Starting designing new User Story. Read the design, reviewed the documentaiton of the language server and the source code. It should be finished by 2022-12-06.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/180872953). splitting user story into tasks, defining acceptance criteria (Enso Bot - Dec 5, 2022)
<hr />
**Ilya Bogdanov** reports a new **🔴 DELAY** for yesterday (2022-12-05):

**Summary:** There is **1 day** delay in implementation of the [New look of the components' documentation. (#180872953) task](https://www.pivotaltracker.com/story/show/180872953).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** additional discussions needed, though minor tasks can be already implemented, so delay is not that important (Enso Bot - Dec 6, 2022)
<hr />
**Ilya Bogdanov** reports a new **STANDUP** for yesterday (2022-12-05):

**Progress:** Attended weekly demo, splitting the user story into tasks, preparing the document and a list of questions. It should be finished by 2022-12-07.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/180872953). continue discussions and planning (Enso Bot - Dec 6, 2022)
<hr />
**Ilya Bogdanov** reports a new **STANDUP** for today (2022-12-06):

**Progress:** filled in pivotal issues for a few minor subtasks, discussed Tailwind CSS usage with Michal It should be finished by 2022-12-07. (Enso Bot - Dec 6, 2022)
<hr />
**Ilya Bogdanov** reports a new **STANDUP** for yesterday (2022-12-07):

**Progress:** Discussed Tailwind integration with Michal, tasks splitting with Adam. It should be finished by 2022-12-07. (Enso Bot - Dec 8, 2022)
<hr />
Did a review. A few comments:
#184012397 - tests for updating index after db update would be nice (except we do it in a straightforward way, without any maps needing update - but then write it in the task description).
#184012434 - I would recommend to use references everywhere inside this representation to avoid copying chunks of strings (they are not big, but on the other hand the path can be crucial if we want to fit also other tasks after selecting entry in one frame). Or, at least, let them be Cows.

Overall looks good, I haven't checked estimates yet, however. (Adam Obuchowicz - Dec 12, 2022)
<hr />
**Design Review** review set to **pass** (Adam Obuchowicz - Feb 3, 2023)
<hr />

**Comment by farmaazon** [comment]
Closing in favor of #7356
