### ISSUE TITLE
Component Browser Design

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4974]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/180293096).
<hr />

Reviewer: AO

## Comments:
**Wojciech Daniło** reports a new **STANDUP** for yesterday (2021-12-06):

**Today:** Mainly writing idea doc and hiring. I will finish the first draft of the idea doc today. It should be finished by 2021-12-06.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/180293096). Finishing the first draft of the idea doc and hiring! (Enso Bot - Dec 7, 2021)
<hr />
**Adam Review** review set to **pass**

whatever (Adam Obuchowicz - Jan 18, 2022)
<hr />
**Adam Obuchowicz** reports a new **🔴 DELAY** for yesterday (2022-01-18):

**Summary:** There is **45 days** delay in implementation of the [Design (#180293096) task](https://www.pivotaltracker.com/story/show/180293096).
It **will cause 0 day delay** for the delivery of this sprint.

**Delay Cause:** I've reviewed the epic design doc, so I wanted to fill my standup for that issue. It seems that Wojciech declared this task to be finished a month ago, but then he didn't assign issue to his standups.

**Possible solutions:** rework the standup-and-delay format we have currently. (Enso Bot - Jan 19, 2022)
<hr />
**Adam Obuchowicz** reports a new **STANDUP** for yesterday (2022-01-18):

**Today:** Reading the new Design doc carefully and left many comments. It should be finished by 2022-01-20.

**Next Day:** Next day I will be working on the [##180293096 task](https://www.pivotaltracker.com/story/show/180293096). Work with Wojciech to finish the Epic Design Doc as fast as possible. Then rearranging User Stories to reflect changes. (Enso Bot - Jan 19, 2022)
<hr />
**Adam Obuchowicz** reports a new **STANDUP** for yesterday (2022-01-19):

**Today:** Wrote a new set of comments in Epic Design Doc. Also the doc review call. It should be finished by 2022-01-20.

**Next Day:** Next day I will be working on the [##180293096 task](https://www.pivotaltracker.com/story/show/180293096). Finish the doc and adjust user stories (Enso Bot - Jan 20, 2022)
<hr />
**Adam Obuchowicz** reports a new **🔴 DELAY** for yesterday (2022-01-24):

**Summary:** There is **5 days** delay in implementation of the [Design (#180293096) task](https://www.pivotaltracker.com/story/show/180293096).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** The reworked Epic task took more reviews than I expected. I also report creating User Stories to the Design task, so I need more days that just merging the PR in design repository

**Possible solutions:** I think the Enso Bot behavior must be redesigned. The last couple of delays I reported did not feel like delays to me. (Enso Bot - Jan 25, 2022)
<hr />
**Adam Obuchowicz** reports a new **STANDUP** for yesterday (2022-01-24):

**Today:** Did last round of reading Epic Design Doc. Added some comments and discussed them with @wdanilo. Also did the Q/A of @fumlead task: dropping connections to create new nodes. Also started the user stories updating. It should be finished by 2022-01-25.

**Next Day:** Next day I will be working on the [##180293096 task](https://www.pivotaltracker.com/story/show/180293096). Finish updating the stories. (Enso Bot - Jan 25, 2022)
<hr />
**Adam Obuchowicz** reports a new **🔴 DELAY** for today (2022-01-27):

**Summary:** There is **2 days** delay in implementation of the [Design (#180293096) task](https://www.pivotaltracker.com/story/show/180293096).
It **will cause 0 days delay** for the delivery of this sprint.

**Delay Cause:** I've taken one day off, and one day was just required to finish the task: the epic design was quite big (Enso Bot - Jan 27, 2022)
<hr />
**Adam Obuchowicz** reports a new **STANDUP** for today (2022-01-27):

**Today:** Finished creating user stories. I think their scope covers the whole design doc. It should be finished by 2022-01-27.

**Next Day:** Next day I will be working on the [##180978888 task](https://www.pivotaltracker.com/story/show/180978888). I start with the technical design for one more task, then I decide what US design take first (Enso Bot - Jan 27, 2022)
<hr />

**Comment by farmaazon** [comment]
The designs are ready in design repo.
