### ISSUE TITLE
Design for Distinct, Limit, Sample

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4975]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182199082).
<hr />

**Distinct**
- Specify 1 or more columns
  - Case sensitivity support
- Nice to have duplicate records
- Respect order of input

**Limit**
- Allows filtering a subset of records.
- Optionally adding a group by allows pulling a subset of each group.
- Operations:
  - TOP N:
  - LAST N: (a little tricky in SQL, but doable)
  - Optional: OFFSET - ignore the 1st (or last) N records before returning TOP or LAST N

**Random sample**
- Seeded
- Permutation so get requested number of rows (or percentage)

## Blockers:
[#182306743](https://www.pivotaltracker.com/story/show/#182306743) resolved
[#181123986](https://www.pivotaltracker.com/story/show/#181123986) resolved
[#182307026](https://www.pivotaltracker.com/story/show/#182307026) resolved
[#182307048](https://www.pivotaltracker.com/story/show/#182307048) resolved
[#182307132](https://www.pivotaltracker.com/story/show/#182307132) resolved
[#182307143](https://www.pivotaltracker.com/story/show/#182307143) resolved
[#182307281](https://www.pivotaltracker.com/story/show/#182307281) resolved
[#182307347](https://www.pivotaltracker.com/story/show/#182307347) resolved
[#182307382](https://www.pivotaltracker.com/story/show/#182307382) blocked

## Comments:
**James Dunkerley** reports a new **STANDUP** for today (2022-05-23):

**Progress:** Completed the initial design document for Distinct, Sample and Limit. PR being raised. It should be finished by 2022-05-24.

**Next Day:** Next day I will be working on the [##182199082 task](https://www.pivotaltracker.com/story/show/182199082). Statistics work... (Enso Bot - May 23, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-05-24):

**Progress:** PRs for Radek's work on Delimited. Merged PR design work for Write Data and Distinct/Sample/Limit. Prepared questions for users (and some reading around on user research). Implemented Rank functionality for stats It should be finished by 2022-05-24.

**Next Day:** Next day I will be working on the [##182059993 task](https://www.pivotaltracker.com/story/show/182059993). Completing and testing Rank. Adding support for Statistic for correlation, covariance and r_squared. Implementing Spearman Rank. (Enso Bot - May 24, 2022)
<hr />

**Comment by jdunkerley** [comment]
Related:
- [ ] #5131

**Comment by jdunkerley** [comment]
Closing as design complete.
