### ISSUE TITLE
Design for parameter metadata APIs

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4976]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183003567).
<hr />

In order to allow us to progress on dynamic widget, writing up and expanding on the ideas from Gdansk into an initial design document.

## Comments:
**James Dunkerley** reports a new **STANDUP** for today (2022-08-16):

**Progress:** Merged the `order_by` shorthand PR. Worked on the Windows installer issue - isolated to a single line change within electron-builder (reported to them) and suggested workaround to Michal. Meeting on next steps for Array/Vector. Discussed various IdAM solutions with Sylwia and my experience with them (cognito, keycloak, auth0 and okta). Started work on design for dynamic widgets. It should be finished by 2022-08-21.

**Next Day:** Next day I will be working on the [##183003567 task](https://www.pivotaltracker.com/story/show/183003567). Cloud meeting with Ned and Sylwia. Discussion on autosave approach (I feel VS Code is the correct approach). Design for dynamic widgets and looking over `[Column]` PR. (Enso Bot - Aug 16, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-08-17):

**Progress:** Cloud design meeting with Sylwia and Ned. Working on the dynamic widget data idea. Updated my Figma with templates for the new UI look and feel. It should be finished by 2022-08-21.

**Next Day:** Next day I will be working on the [##183003567 task](https://www.pivotaltracker.com/story/show/183003567). Continuing design work for dynamic widgets. (Enso Bot - Aug 17, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-08-18):

**Progress:** Completed the [Column] PR - cleaned up some more issues and merged. Work on the design for the widgets API. Review with Ned and Sylwia. Gone back to do some import tidying to finish that work off. It should be finished by 2022-08-21.

**Next Day:** Next day I will be working on the [##183003567 task](https://www.pivotaltracker.com/story/show/183003567). Continuing design work for dynamic widgets. (Enso Bot - Aug 18, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-08-19):

**Progress:** Mainly working on the design for the dynamic widgets. Picked back up tidying the imports as well. Sorted Standard.Table and Table_Tests. It should be finished by 2022-08-21.

**Next Day:** Next day I will be working on the [##183003567 task](https://www.pivotaltracker.com/story/show/183003567). Finishing draft of the design work for dynamic widgets. (Enso Bot - Aug 19, 2022)
<hr />
**James Dunkerley** reports a new **🔴 DELAY** for today (2022-08-22):

**Summary:** There is **1 day** delay in implementation of the [Design for parameter metadata APIs (#183003567) task](https://www.pivotaltracker.com/story/show/183003567).
It **will cause 0 days delay** for the delivery of this weekly plan.

Wrong end date on ticket (put Sunday not Monday).

**Delay Cause:** Look at calendar better (Enso Bot - Aug 22, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-08-22):

**Progress:** Published the first draft of the dynamic widgets design. With Ned/Sylwia/Wojciech for review. Reviewed a few PRs and sorted issues with the Standard.Table PR. It should be finished by 2022-08-22.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Pick up any comments on the dynamic widgets. Test the code for it and expand the examples. Then back to the Database read work. (Enso Bot - Aug 22, 2022)
<hr />
**James Dunkerley** reports a new **🔴 DELAY** for today (2022-08-30):

**Summary:** There is **9 days** delay in implementation of the [Design for parameter metadata APIs (#183003567) task](https://www.pivotaltracker.com/story/show/183003567).
It **will cause 0 days delay** for the delivery of this weekly plan.

Picking back up the design following PR comments.

**Delay Cause:** Waiting on review comments, holiday, and working other tasks (Enso Bot - Aug 30, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-08-30):

**Progress:** Most of the day reviewing Marcin's PR and thinking on the implications for the API design. Updated a lot of the design document for the dynamic metadata widgets. It should be finished by 2022-08-31.

**Next Day:** Next day I will be working on the [##183003567 task](https://www.pivotaltracker.com/story/show/183003567). Continuing design work for dynamic widgets. (Enso Bot - Aug 30, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-08-31):

**Progress:** Morning on recruitment (CV screening, interview prep and interview). PR review for Radek. Rebasing the database connection work onto Marcin's changes. Design for dynamic widgets. It should be finished by 2022-08-31.

**Next Day:** Next day I will be working on the [##183003567 task](https://www.pivotaltracker.com/story/show/183003567). Holiday until Monday. Then back to Database types work and thinking over implications of types and static changes. (Enso Bot - Aug 31, 2022)
<hr />

**Comment by jdunkerley** [comment]
Closing out - we have an approach an will add new tickets as needed to support the widget development.
