### ISSUE TITLE
Design for Read Database

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4977]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182652055).
<hr />

- Ability to get list of tables / views
- Fetch whole table or view
- Ability to run custom SQL query

Includes reviewing the Dialect design to ensure full support for samples, aggregation, joining and filters.

## Blockers:
[#183390662](https://www.pivotaltracker.com/story/show/183390662) blocked
[#183390699](https://www.pivotaltracker.com/story/show/183390699) blocked
[#183377997](https://www.pivotaltracker.com/story/show/183377997) blocked
[#183390797](https://www.pivotaltracker.com/story/show/183390797) blocked
[#183578491](https://www.pivotaltracker.com/story/show/183578491) blocked

## Comments:
**James Dunkerley** reports a new **STANDUP** for today (2022-07-14):

**Progress:** Started on the Database.read design work. Experimenting with ideas at the moment. It should be finished by 2022-07-18.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Continuing design. (Enso Bot - Jul 14, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-07-15):

**Progress:** Working over `Column_Type` and `Column` type design for Database.read. It should be finished by 2022-07-18.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Continuing design - hoping to get a first draft done for Monday. (Enso Bot - Jul 15, 2022)
<hr />
**James Dunkerley** reports a new **🔴 DELAY** for today (2022-07-18):

**Summary:** There is **4 days** delay in implementation of the [Design for Read Database (#182652055) task](https://www.pivotaltracker.com/story/show/182652055).
It **will cause 1 day delay** for the delivery of this weekly plan.

Expanded the scope to cover column types.

**Delay Cause:** Too hot so working on another task on laptop. (Enso Bot - Jul 18, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-07-18):

**Progress:** PR review on Date work. 1:1s with Sylwia and Wojciech. Some more design work. Started on Linear Regression as too hot. Type name alignment. It should be finished by 2022-07-22.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Continuing linear regression work. (Enso Bot - Jul 18, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-07-19):

**Progress:** Completed type name revision. Discussed `Database.Read` and column types with Ned and Sylwia. Exceptions meeting with engine team. Working on regression functions and statistics. It should be finished by 2022-07-22.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Continuing linear regression work and design work. (Enso Bot - Jul 19, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-07-20):

**Progress:** Linear regression functions working. Did some work on improving what is included in Standard.Base and Standard.Table. Working over Radek's PRs to get them merged. It should be finished by 2022-07-22.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Continuing linear regression work and design work. (Enso Bot - Jul 20, 2022)
<hr />
**James Dunkerley** reports a new **🔴 DELAY** for today (2022-07-26):

**Summary:** There is **7 days** delay in implementation of the [Design for Read Database (#182652055) task](https://www.pivotaltracker.com/story/show/182652055).
It **will cause 0 days delay** for the delivery of this weekly plan.

Returned to working on this ticket and the column types one after having been working on other tickets,

**Delay Cause:** Other work needing completed. (Enso Bot - Jul 26, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-07-26):

**Progress:** Adjusted the design for Database/Schema and table list querying. Working on Column Types and Query design. It should be finished by 2022-07-29.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Aiming to get a decent version to review with Ned and Sylwia tomorrow. (Enso Bot - Jul 26, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-07-27):

**Progress:** Completed prototype for Databases and Schemas. Worked through Tables design. Reviewed with Ned and Sylwia. It should be finished by 2022-07-29.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Adding renaming to metadata columns. Adding reading table structure from metadata and query design. Then onto types. (Enso Bot - Jul 27, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-07-28):

**Progress:** Worked over issues in the Postgres and SQLite prototypes following review with Ned and Sylwia yesterday. Set up the `tables` function and `columns_metadata_table` function. Still working on `Column_Type` type design. It should be finished by 2022-07-29.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Continuing on columns work and hopefully getting to query work. (Enso Bot - Jul 28, 2022)
<hr />
**James Dunkerley** reports a new **🔴 DELAY** for today (2022-07-29):

**Summary:** There is **6 days** delay in implementation of the [Design for Read Database (#182652055) task](https://www.pivotaltracker.com/story/show/182652055).
It **will cause 0 days delay** for the delivery of this weekly plan.

Found difficulties with mapping type from Postgres metadata. With Gdansk trip will be a few more days.

**Delay Cause:** Other work needing completed. (Enso Bot - Jul 29, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-07-29):

**Progress:** Working over types in Postgres and how they map through JDBC into Enso data types. It should be finished by 2022-08-04.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Travelling to GDansk and some more types work (Enso Bot - Jul 29, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-08-03):

**Progress:** PR reviews for Radek. Some admin sorting out post the trip. Then working on restructuring the Database Connection type allowing for reuse of as much as possible as design moves to specific ones for each database. It should be finished by 2022-08-04.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Continuing the Database read work. (Enso Bot - Aug 3, 2022)
<hr />
**James Dunkerley** reports a new **🔴 DELAY** for today (2022-08-04):

**Summary:** There is **15 days** delay in implementation of the [Design for Read Database (#182652055) task](https://www.pivotaltracker.com/story/show/182652055).
It **will cause 0 days delay** for the delivery of this weekly plan.

Refactoring work after finding data type issues for Postgres.

**Delay Cause:** Adding the work of column types made this a larger task. Should mean completing both read and column types sooner. Additional delay caused by holidays. (Enso Bot - Aug 4, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-08-04):

**Progress:** Refactored the Connection type. Allows for much easier specific implementations. As no inheritance still has a lot of boiler plate. Prototype all working. It should be finished by 2022-08-19.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Holiday until 15th then will pick this back up. (Enso Bot - Aug 4, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-08-15):

**Progress:** Catching up after week off. Repaired examples. Reviewing PRs. Replying to Discord. Meeting on Arrays and dynamic widgets. It should be finished by 2022-08-19.

**Next Day:** Next day I will be working on the [##182652055 task](https://www.pivotaltracker.com/story/show/182652055). Investigating Windows installer issue. Work on dynamic widgets design then back to database design. (Enso Bot - Aug 15, 2022)
<hr />
**James Dunkerley** reports a new **🔴 DELAY** for today (2022-09-22):

**Summary:** There is **38 days** delay in implementation of the [Design for Read Database (#182652055) task](https://www.pivotaltracker.com/story/show/182652055).
It **will cause 0 days delay** for the delivery of this weekly plan.

Picking back up to finish off design.

**Delay Cause:** Not working on it... (Enso Bot - Sep 22, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-09-22):

**Progress:** Work on the ArraySlice code. Finished off query and read prototype and design. It should be finished by 2022-09-26.

**Next Day:** Next day I will be working on the [##183208844 task](https://www.pivotaltracker.com/story/show/183208844). Prototype up the filter design. (Enso Bot - Sep 22, 2022)
<hr />

**Comment by jdunkerley** [comment]
Related:
- [ ] #5262 
- [ ] #5269 
- [ ] #5263 
- [ ] #5264

**Comment by jdunkerley** [comment]
Closing as design complete.
