### ISSUE TITLE
Design changes following types and statics

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4978]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183208844).
<hr />

Following the introduction of types and statics what should the standard libraries look like.

- Error classes
- Fundamental types
- High level API design

## Blockers:
[#183314869](https://www.pivotaltracker.com/story/show/#183314869) resolved
[#183314956](https://www.pivotaltracker.com/story/show/#183314956) resolved
[#183315144](https://www.pivotaltracker.com/story/show/#183315144) resolved
[#183315764](https://www.pivotaltracker.com/story/show/#183315764) resolved
[#183324312](https://www.pivotaltracker.com/story/show/#183324312) resolved
[#183452411](https://www.pivotaltracker.com/story/show/#183452411) resolved
[#182138887](https://www.pivotaltracker.com/story/show/#182138887) resolved
[#183403598](https://www.pivotaltracker.com/story/show/#183403598) resolved
[#182720308](https://www.pivotaltracker.com/story/show/182720308) blocked
[#182138887](https://www.pivotaltracker.com/story/show/#182138887) resolved
[#183040850](https://www.pivotaltracker.com/story/show/#183040850) resolved
[#182584311](https://www.pivotaltracker.com/story/show/182584311) blocked
[#183686741](https://www.pivotaltracker.com/story/show/183686741) blocked
[#183617179](https://www.pivotaltracker.com/story/show/183617179) blocked

## Comments:
**James Dunkerley** reports a new **STANDUP** for today (2022-09-07):

**Progress:** Reviewing the impact of the changes on the existing codebase. Thinking over the changes to the core data types and error types. Discussing the changes with Ned and Sylwia and thinking what the appropriate design for Database.connect and File.read are following the changes. It should be finished by 2022-09-14.

**Next Day:** Next day I will be working on the [##183208844 task](https://www.pivotaltracker.com/story/show/183208844). Writing up and reviewing what was discussed. (Enso Bot - Sep 7, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-09-08):

**Progress:** Tidied up various things in the standard library (aligned type signatures, some spacing in signatures, moved extension methods into types where possible, removed some dead code). Scanned the standard libraries to make list of types, constructors, functions. Reviewed all the `_Data` constructors within `Standard.Base` planned changes for the types in their. Working over the implications for File.read and Database.connect. It should be finished by 2022-09-14.

**Next Day:** Next day I will be working on the [##183208844 task](https://www.pivotaltracker.com/story/show/183208844). Continuing with File.read and Database.connect. Interview and catch up with Ned/Sylwia on changes. (Enso Bot - Sep 8, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-09-09):

**Progress:** Interview with Sylwia. Worked over the Database.connect and File.read - agreed a plan with Ned and Sylwia. It should be finished by 2022-09-14.

**Next Day:** Next day I will be working on the [##183208844 task](https://www.pivotaltracker.com/story/show/183208844). Write up the design from meeting. Implement a prototype ahead of review on Tuesday. (Enso Bot - Sep 9, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-09-12):

**Progress:** Prototyping the `File.read` approach. 1:1 with Greg. It should be finished by 2022-09-14.

**Next Day:** Next day I will be working on the [##183208844 task](https://www.pivotaltracker.com/story/show/183208844). Finish prototype and write up design. (Enso Bot - Sep 12, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-09-13):

**Progress:** Restructuring the File.read stuff within Base and Table. Tried an approach with an extension method to register types - didn't work. Discussed approach with Ned and Sylwia. It should be finished by 2022-09-14.

**Next Day:** Next day I will be working on the [##183208844 task](https://www.pivotaltracker.com/story/show/183208844). Finish File.read and put PR up. Finish design write up and send out for review. (Enso Bot - Sep 13, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-09-14):

**Progress:** Finished the PR restructuring File.read. Meeting with Hubert and Radek on possible path forward. Reviewed types in Standard.Table. Working through Standard.Database. It should be finished by 2022-09-14.

**Next Day:** Next day I will be working on the [##183208844 task](https://www.pivotaltracker.com/story/show/183208844). Work over the changes for Data.connect and build "Excel_Connection". Try out to do rows on a table with new Vector stuff. Finish write up and send to Wojciech/Sylwia/Ned. (Enso Bot - Sep 14, 2022)
<hr />
**James Dunkerley** reports a new **🔴 DELAY** for today (2022-09-15):

**Summary:** There is **5 days** delay in implementation of the [Design changes following types and statics (#183208844) task](https://www.pivotaltracker.com/story/show/183208844).
It **will cause 0 days delay** for the delivery of this weekly plan.

Completed the type renames but working over the changes to the key API functions.

**Delay Cause:** Covering the scope of the ideas from discussions with Ned and Sylwia. (Enso Bot - Sep 15, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-09-15):

**Progress:** Completed the list of type name changes. Finished the work to restructure File.read in current codebase. It should be finished by 2022-09-19.

**Next Day:** Next day I will be working on the [##183208844 task](https://www.pivotaltracker.com/story/show/183208844). Working through Database.connect to Data.connect and adding Excel_Connection prototype. (Enso Bot - Sep 15, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-09-16):

**Progress:** Applied a lot of tidying up to Database. Working on Connection.query and read design. It should be finished by 2022-09-19.

**Next Day:** Next day I will be working on the [##183208844 task](https://www.pivotaltracker.com/story/show/183208844). Working through Database.connect to Data.connect and adding Excel_Connection prototype. (Enso Bot - Sep 16, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-09-19):

**Progress:** Finished the design for Data.connect. Merged the Database rename work. It should be finished by 2022-09-19.

**Next Day:** Next day I will be working on the [##183208844 task](https://www.pivotaltracker.com/story/show/183208844). Database read/query and types. Interview. (Enso Bot - Sep 19, 2022)
<hr />

**Comment by jdunkerley** [comment]
Related:
- [ ] #5323 
- [ ] #5324 
- [ ] #5228 
- [ ] #5154

**Comment by jdunkerley** [comment]
Closing as design in place and have established links.
