### ISSUE TITLE
Design and Engine implementation for Atom dropdown UI

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4979]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/181742783).
<hr />

Initial function for consideration:

```
type Location
    type Start
    type End
    type Both

Text.trim
      from : Start | End | Both = Both
      trim_characters : Text | Nothing
    -> Text
```

This task is to review how to flow the type information for both sum types (`Start|End|Both`) and the parent type (`Location`) to the UI.

The intention is that the UI will render this as a simple drop down allowing the user to choose.

https://docs.google.com/document/d/1rQWle7XfzqzIxGk0pG7KyavwDrwtIu-gfVMwtXq9SMw/edit#heading=h.27btnzrpmhqg

## Comments:
**Edward Kmett** reports a new **STANDUP** for today (2022-04-04):

**Progress:** Outermost type constructors don't exist to hang the map off. Getting back in the swing of updating EnsoBot. Placing a wide error bar on this initial End Date estimate because of the unknown scope of work. It should be finished by 2022-04-21.

**Next Day:** Next day I will be working on the [##181742783 task](https://www.pivotaltracker.com/story/show/181742783). Regrouping with Marcin tomorrow to come up with a better plan, since this now looks like it'll force a fairly large standard library rewrite for the objects we need to be real enough to hang something on. (Enso Bot - Apr 4, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for yesterday (2022-04-05):

**Progress:** Discussion about priorities for the upcoming month. Talked with Jaroslav about various Javabeans style alternatives to annotations. It should be finished by 2022-04-21.

**Next Day:** Next day I will be working on the [##181742783 task](https://www.pivotaltracker.com/story/show/181742783). Syncing with Jaroslav and Marcin about the status of the type side of enso. (Enso Bot - Apr 6, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (2022-04-06):

**Progress:** More conversations with Jaroslav about the state of the type system, what is missing, what is changing and what we need to do to be able to support a sort of Enso Bean story to support the IDE. It should be finished by 2022-04-21.

**Next Day:** Next day I will be working on the [##181742783 task](https://www.pivotaltracker.com/story/show/181742783). Adding Marcin into the mix. (Forgot he was out til Thursday) (Enso Bot - Apr 7, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for yesterday (2022-04-08):

**Progress:** Conversations with James, Marcin, Dmitry, Jaroslav and Hubert about the nature of the language server protocol we use, and how we might patch it to allow for mroe control over what the UI looks like. Continued Info-dumping on Jaroslav well into the weekend. It should be finished by 2022-04-21.

**Next Day:** Next day I will be working on the [##181742783 task](https://www.pivotaltracker.com/story/show/181742783). Reviewing a straw-proposal by Dmitry about how we might tweak the messaging between the IDE and engine. (Enso Bot - Apr 9, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for yesterday (2022-04-11):

**Progress:** Conversations trying to pin down the "bean" story further. It should be finished by 2022-04-21.

**Next Day:** Next day I will be working on the [##181742783 task](https://www.pivotaltracker.com/story/show/181742783). Reviewing this narrative with the rest of the team, wdanilo, ned and sylwia. (Enso Bot - Apr 13, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (2022-04-12):

**Progress:** Reviewed the bean story with team, wdanilo, ned and sylwia. Much blood was shed. Short dive into the language server protocol we do have to understand how we might better back that story up, cut short due to external meeting forcing a short day, plan to make up the hour thursday. It should be finished by 2022-04-21.

**Next Day:** Next day I will be working on the [##181742783 task](https://www.pivotaltracker.com/story/show/181742783). More language server investigations, will hopefully have something from the front end side to try to marry it to. (Enso Bot - Apr 13, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for yesterday (2022-04-13):

**Progress:** Waded through the existing language server protocol documentation, looking for future latency improvements, if we're going to be carving open this part of the IDE/engine. Sketched tasks on the engine side for tomorrow's sync with Jaroslav. It should be finished by 2022-04-21.

**Next Day:** Next day I will be working on the [##181742783 task](https://www.pivotaltracker.com/story/show/181742783). Meeting Jaroslav and Marcin. (Enso Bot - Apr 15, 2022)
<hr />
**Edward Kmett** reports a new **STANDUP** for today (2022-04-14):

**Progress:** Met with Jaroslav and Marcin and broke out a set of tasks (even if unsized) to get through the static dropdowns for the IDE, backed by just enough data to dispatch from conversions for sums, even if we won't have full proper types yet. Spent the rest of the time trying to figure out a way to insulate the type constructor-producing subtask from the fact that it both breaks the entire test suite AND the standard library, which is somewhat complicated by Hubert's recent work on removing large swatches of builtins and replacing them with code directly in the stdlib making it so I can't just stub out the standard library any more! It should be finished by 2022-04-21.

**Next Day:** Next day I will be working on the [##181742783 task](https://www.pivotaltracker.com/story/show/181742783). Meeting Radek and wdanilo to figure out what parts of the type system is amenable to peeling off to fit Radek's academic work @ 1 day in 5. (Enso Bot - Apr 15, 2022)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for yesterday (2022-04-14):

**Progress:** Started working out the example when a user creates a function with one of the arguments has a sum type e.g. `Location.Start | Location.End | Location.Both`. Mapped the scenarion into the messages that LS produces when such method is created. Still need to specify how the suggestions system and compilation pipeline need to be updated in order to handle complex types. It should be finished by 2022-04-21.

**Next Day:** Next day I will be working on the [##181742783 task](https://www.pivotaltracker.com/story/show/181742783). Finish specifying the example with a type sum. (Enso Bot - Apr 15, 2022)
<hr />

**Comment by jdunkerley** [comment]
Closed as this is already in place.
