### ISSUE TITLE
Design for simple derived columns

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4981]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182653851).
<hr />

- Add a constant column
- Add an index column (grouped or not, step, start control)
- Duplicate a column
- Simple operators on a column
- Agree core set of functions

Should work for both in-memory and database.

## Blockers:
[#183631044](https://www.pivotaltracker.com/story/show/#183631044) resolved
[#183679097](https://www.pivotaltracker.com/story/show/#183679097) resolved
[#183679097](https://www.pivotaltracker.com/story/show/#183679097) resolved
[#183686167](https://www.pivotaltracker.com/story/show/#183686167) resolved
[#183679123](https://www.pivotaltracker.com/story/show/183679123) blocked
[#183692164](https://www.pivotaltracker.com/story/show/183692164) blocked
[#183692199](https://www.pivotaltracker.com/story/show/#183692199) resolved
[#183692217](https://www.pivotaltracker.com/story/show/183692217) blocked
[#183692234](https://www.pivotaltracker.com/story/show/183692234) blocked

## Comments:
**James Dunkerley** reports a new **STANDUP** for today (2022-10-10):

**Progress:** Started on tidying up Examples, Geo, Google, Test and Image libraries. Aiming to complete their tidying tomorrow. Started writing up the design for the derived columns. It should be finished by 2022-10-17.

**Next Day:** Next day I will be working on the [#182653851 task](https://www.pivotaltracker.com/story/show/182653851). Continue working on design. (Enso Bot - Oct 10, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-10-11):

**Progress:** Working over the performance of the Vector.Builder PR. Some design work on the expressions code. It should be finished by 2022-10-17.

**Next Day:** Next day I will be working on the [#182653851 task](https://www.pivotaltracker.com/story/show/182653851). Continue working on design. (Enso Bot - Oct 11, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-10-12):

**Progress:** Looking further at tuning Vector performance. Working on derived columns design. Review with Ned. It should be finished by 2022-10-17.

**Next Day:** Next day I will be working on the [#182653851 task](https://www.pivotaltracker.com/story/show/182653851). Continue working on design. (Enso Bot - Oct 12, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-10-13):

**Progress:** Completing the design document and tidying up all the mistakes. It should be finished by 2022-10-17.

**Next Day:** Next day I will be working on the [#182653851 task](https://www.pivotaltracker.com/story/show/182653851). Finish the design and put out for PR. (Enso Bot - Oct 13, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-10-14):

**Progress:** Small amount of work on design. PR for Radek. Finished tidying Image and Test libraries (PR raised). Improved Vector tuning - just Filter left to improve. It should be finished by 2022-10-17.

**Next Day:** Next day I will be working on the [#182653851 task](https://www.pivotaltracker.com/story/show/182653851). Finish the design and put out for PR. (Enso Bot - Oct 14, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-10-17):

**Progress:** Finished the tidying PR. PR raised on the design. Addresses a lot of Ned and Radek's comments. It should be finished by 2022-10-17.

**Next Day:** Next day I will be working on the [#182653851 task](https://www.pivotaltracker.com/story/show/182653851). Something else... (Enso Bot - Oct 17, 2022)
<hr />

**Comment by jdunkerley** [comment]
Related:
- [ ] #5265 
- [ ] #5333 
- [ ] #5227 
- [ ] #5261

**Comment by jdunkerley** [comment]
Closing as have the design.
