### ISSUE TITLE
Design for CrossTab and Pivot functions

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4983]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182673319).
<hr />

- Pivot: Ability to convert a column based table to a row based table
- CrossTab: Ability to convert a row based table to a column based table
  - Is doable as a multistage query within database
  - Aggregation operation to work out the values

## Blockers:
[#183909406](https://www.pivotaltracker.com/story/show/183909406) blocked
[#184072769](https://www.pivotaltracker.com/story/show/184072769) blocked
[#184072789](https://www.pivotaltracker.com/story/show/184072789) blocked
[#184072846](https://www.pivotaltracker.com/story/show/184072846) blocked

## Comments:
**James Dunkerley** reports a new **STANDUP** for today (2022-09-30):

**Progress:** PR review on data types woth Ned and Sylwia. Working on design for pivot and crosstab. It should be finished by 2022-10-08.

**Next Day:** Next day I will be working on the [##182673319 task](https://www.pivotaltracker.com/story/show/182673319). Continue working on pivot and crosstab design and finish `rename_columns`. (Enso Bot - Sep 30, 2022)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2022-10-03):

**Progress:** Work on simpler Table APIs. PR on `filter` design changes. Work on crosstab and unpivot. It should be finished by 2022-10-08.

**Next Day:** Next day I will be working on the [##182673319 task](https://www.pivotaltracker.com/story/show/182673319). Continue working on pivot and crosstab design. (Enso Bot - Oct 3, 2022)
<hr />

**Comment by jdunkerley** [comment]
Related: 
- [ ] #5150 
- [ ] #5151 
- [ ] #5229 
- [ ] #5230

**Comment by jdunkerley** [comment]
Closing as have the design.
