### ISSUE TITLE
Design for overhauled Problem Behavior

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4985]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184073122).
<hr />

## Problem Handler

Currently a simple Atom enumeration.

Could become much more like an Error catch

```
type Problem_Hander
    Ignore = Problem_Handler.Callback (_ value -> value)

    Report_Warning = Problem_Handler.Callback (problem value -> value.attach_warning problem)

    Report_Error = Problem_Handler.Callback (problem _ -> Error.throw problem)

    Callback callback:(Problem->Value->Value) =
        callback problem value = 
            if problem.is_a Encoding_Error then Error.throw problem else
                value.attach_warning problem

    ignore_on : Type -> Problem_Handler
    ignore_on self type =
        callback problem value =
            if problem.is_a type then value else
                self.callback problem value
        Problem_Handler.Callback callback

    warning_on : Type -> Problem_Handler
    warning_on self type =
        callback problem value =
            if problem.is_a type then value.attach_warning problem else
                self.callback problem value
        Problem_Handler.Callback callback

    error_on : Type -> Problem_Handler
    error_on self type =
        callback problem value =
            if problem.is_a type then Error.throw problem else
                self.callback problem value
        Problem_Handler.Callback callback

on_problems=(Report_Warning.ignore_on Encoding_Error)
```

### Table.select_columns

Table: ["A","B","C"]

a.select_columns []
- Error No_Output_Columns

a.select_columns "Hello"
- Empty table, with a No_Output_Columns and a Missing_Input_Columns warning

a.select_columns ["C", "D"]
- Table: "C"
- A Missing_Input_Columns warning

```
select_columns : Vector Text | Column_Selector -> Boolean -> Problem_Behavior -> Table
select_columns self (columns = Column_Selector.By_Index [0]) (reorder = False) (on_problems = Report_Warning) =
```

- By default a problem is treated as a warning and system attempts to continue to return a table.
- If a column in columns is not in the input table, a `Missing_Input_Columns`.
- If a column index is out of range, a `Column_Indexes_Out_Of_Range`.
- If duplicate columns, names or indices are provided, a `Duplicate_Column_Selectors`.
- If two distinct indices refer to the same column, an `Input_Indices_Already_Matched`, with the column included the first time it is matched.
- If there are no columns in the output table, a `No_Output_Columns`.

Missing Column:
- `allow_missing_columns=False`
- By default, a column selector which fails to match results in an Error.
- Otherwise, results in an attached warning.
- For both by name and by index.

Empty table:
- A `No_Output_Columns` error is raised.
- Table functions will assume a column exists to operate on, so many errors might occur (e.g. row_count will crash).
- A 0 row table is a valid object, 0 column table is an error.

`Duplicate_Column_Selectors` and `Input_Indices_Already_Matched` isn't an issue.
- Return a single column, no need to attach warning.

### Table.remove_columns

```
remove_columns : Vector Text | Column_Selector -> Problem_Behavior -> Table
remove_columns self (columns = Column_Selector.By_Index [0]) (on_problems = Report_Warning) =
```

- If a column in columns is not in the input table, a `Missing_Input_Columns`.
- If duplicate columns, names or indices are provided, a `Duplicate_Column_Selectors`.
- If a column index is out of range, a `Column_Indexes_Out_Of_Range`.
- If two distinct indices refer to the same column, an `Input_Indices_Already_Matched`, with the column included the first time it is matched.
- If there are no columns in the output table, a `No_Output_Columns`.

As with select_columns:

Empty table:
- A `No_Output_Columns` error is raised.
- Table functions will assume a column exists to operate on, so many errors might occur (e.g. row_count will crash).

`Duplicate_Column_Selectors` and `Input_Indices_Already_Matched` isn't an issue.
- Remove a single column, no need to attach warning.

Missing Column:
- `allow_unmatched_columns=True`
- By default, a column selector which fails to match is ignored.
- If specified, follow the `Problem_Behavior` rules.
- For both by name and by index.

### Table.reorder_columns

```
reorder_columns : Vector Text | Column_Selector -> Position -> Problem_Behavior -> Table
reorder_columns self (columns = Column_Selector.By_Index [0]) (position = Position.Before_Other_Columns) (on_problems = Report_Warning) =
```

Missing Column:
- By default, a column selector which fails to match is raised as a problem following `Problem_Behavior`.
- For both by name and by index.

`Duplicate_Column_Selectors` and `Input_Indices_Already_Matched` isn't an issue.
- Remove a single column, no need to attach warning.

### Table.transpose

```
transpose : Text | Vector Text | Column_Selector -> Text -> Text -> Problem_Behavior -> Table
transpose self (id_fields = Column_Selector.By_Name []) (name_field="Name") (value_field="Value") (on_problems = Report_Warning) =
```

id_fields follow same as `select_columns` (but allowed to be empty array).

if name_field or value_field name is in use in the id_fields then warn about auto rename.
Follow the `Problem_Behavior` rules, and the name and value field are renamed as needed.

### Table.rename_columns

```
rename_columns : Map | Vector Text | Column_Name_Mapping -> Problem_Behavior -> Table
rename_columns self (column_map=(Column_Name_Mapping.By_Position ["Column"])) (on_problems=Report_Warning) = case column_map of
```

- If a column in columns is not in the input table, a `Missing_Input_Columns`.
- If a column index is out of range, a `Column_Indexes_Out_Of_Range`.
- If duplicate columns, names or indices are provided, a `Duplicate_Column_Selectors`.
- If two distinct indices refer to the same column, an `Input_Indices_Already_Matched`.
- If in `By_Position` mode and more names than columns are provided, a `Too_Many_Column_Names_Provided`.
- If any of the new names are invalid, an `Invalid_Output_Column_Names`.
- If any of the new names clash either with existing names or each other, a `Duplicate_Output_Column_Names`.

Missing Column:
- `allow_missing_columns=False`
- By default, a column selector which fails to match results in an Error.
- Otherwise, results in an attached warning.
- For both by name and by index.

Too many names for position based:
- a `Too_Many_Column_Names_Provided` follow Problem_Behavior.

Duplicate renames:
- If 2 mappings would result in a different new name then should report an error.
- `Ambiguous_Column_Rename` error.
- Otherwise ignore.

Duplicate output names:
- Rename according to strategy.
- Attach a `Duplicate_Output_Column_Names` follwing the Problem_Behavior.

Invalid output names (basically empty string and null):
- Rename according to strategy.
- Attach a `Invalid_Output_Column_Names` follwing the Problem_Behavior.

### Table.use_first_row_as_names

```
use_first_row_as_names : Problem_Behavior -> Table
use_first_row_as_names self (on_problems=Report_Warning) =
```

Duplicate output names:
- Rename according to strategy.
- Attach a `Duplicate_Output_Column_Names` follwing the Problem_Behavior.

Invalid output names (basically empty string and null):
- Rename according to strategy.
- Attach a `Invalid_Output_Column_Names` follwing the Problem_Behavior.
- Should indicate column index or name that was there before.

### Table.aggregate

```
aggregate : Vector Aggregate_Column -> Problem_Behavior -> Table
aggregate self columns (on_problems=Report_Warning) =
```

- If a column name is not in the input table, a `Missing_Input_Columns`.
- If a column index is out of range, a `Column_Indexes_Out_Of_Range`.
- If there are no valid columns in the output table, a `No_Output_Columns`.
- If there are invalid column names in the output table, a `Invalid_Output_Column_Names`.
- If there are duplicate column names in the output table, a `Duplicate_Output_Column_Names`.

- If an aggregation fails, an `Invalid_Aggregation`.
- If grouping on or computing the `Mode` on a floating point number, a `Floating_Point_Grouping`.
- If when concatenating values there is an quoted delimited, an `Unquoted_Delimiter`
- If there are more than 10 issues with a single column, an `Additional_Warnings`.

Empty table (no aggregate_columns):
- A `No_Output_Columns` error is raised.
- Table functions will assume a column exists to operate on, so many errors might occur (e.g. row_count will crash).

Missing columns
- If a Group By then a hard error.
- If an aggregation is invalid for the column, then hard error.
- If a computed aggregation, then follow Problem_Behavior and drop the column.
  - Can result in a hard error if all columns dropped (warnings promoted to error in this case).

Duplicate output names:
- Rename according to strategy.
- Attach a `Duplicate_Output_Column_Names` follwing the Problem_Behavior.

Invalid output names (basically empty string and null):
- Rename according to strategy.
- Attach a `Invalid_Output_Column_Names` follwing the Problem_Behavior.
- Should indicate column index or name that was there before.

Follow Problem_Behavior for:
- Floating point aggregation
- Unquoted delimiters (rename to "Delimiter_In_Value")

### Table.order_by

```
order_by : Text | Sort_Column | Vector (Text | Sort_Column) | Sort_Column_Selector -> Text_Ordering -> Problem_Behavior -> Table ! Incomparable_Values
order_by self (columns = (Sort_Column_Selector.By_Name [(Sort_Column.Name (self.columns.at 0 . name))])) text_ordering=Text_Ordering.Default on_problems=Report_Warning =
```

- If a column in `columns` is not present in the input table, a `Missing_Input_Columns`.
- If a column index is out of range, a `Column_Indexes_Out_Of_Range`.
- If duplicate columns, names or indices are provided, a `Duplicate_Column_Selectors`.
- If two distinct indices refer to the same column, an `Input_Indices_Already_Matched`.
- If two name matchers match the same column, a `Column_Matched_By_Multiple_Selectors`.
- If no valid columns are selected, a `No_Input_Columns_Selected`.
- If values do not implement an ordering, an `Incomparable_Values`.

Missing Column:
- By default, a column selector which fails to match results in an Error.
- For both by name and by index.

Duplicates are ignored (first one wins).

If no valid columns are selected, follow the Problem_Behavior for `No_Input_Columns_Selected`.

If values do not implement an ordering, an `Incomparable_Values` error.

### Text.bytes and Text.utf_8

```
Text.bytes : Encoding -> Problem_Behavior -> Vector Byte
Text.bytes self encoding on_problems=Problem_Behavior.Report_Warning =

Text.utf_8 : Problem_Behavior -> Vector Byte
Text.utf_8 self on_problems=Problem_Behavior.Report_Warning =
```

- Encoding_Error reported following `Problem_Behavior` rules.
- Default Problem_Behavior is a warning: `Report_Warning`.
- Bad character replaced with `0xFFFD` (replacement character or `?`) bytes.

### Text.from_bytes and Text.from_utf_8

```
Text.from_bytes : Vector Byte -> Encoding -> Text
Text.from_bytes bytes encoding on_problems=Problem_Behavior.Report_Warning =

Text.from_utf_8 : Vector Byte -> Problem_Behavior -> Text
Text.from_utf_8 bytes on_problems=Problem_Behavior.Report_Warning =
```

- Encoding_Error reported following `Problem_Behavior` rules.
- Default Problem_Behavior is a failure: `Report_Error`.
- Bad character replaced with `0xFFFD` (replacement character or `?`) character.

### File.read (and Data.read_file)

```
read : File_Format -> Problem_Behavior -> Any ! File_Error
read self format=Auto_Detect (on_problems=Problem_Behavior.Report_Warning)=
```

- All file access or IO errors, reported as File_Error hard errors.
- If Auto_Detect and file is not a supported format, then a File_Error hard error.
- Otherwise will follow error handling of the format.
  - `Plain_Text` can report Encoding_Error follow Text.from_bytes rules.
  - `Excel` will generally be hard errors (if invalid file). Missing Sheet or Invalid Range.
  - `Delimited` file:
    - Encoding error as above.
    - Mismatched quote (opened a quote and never closed it) - an error if allowing multiline, otherwise a warning.
      **Multiline control flag for delimited files**
    - Invalid row (too many or too few columns) - a warning (ideally separate too few and too many).
- Warning and follow strategy for Duplicate Names or Invalid Names.
  **Single place to control whether a name is valid.**

### File.read_text (and Data.read_text_file)

```
read_text : Encoding -> Problem_Behavior -> Text ! File_Error
read_text self (encoding=Encoding.utf_8) (on_problems=Problem_Behavior.Report_Warning) =
```

- All file access or IO errors, reported as File_Error hard errors.
- Encoding_Error reported follows Text.from_bytes rules.

### Text.write

```
Text.write : (File|Text) -> Encoding -> Existing_File_Behavior -> Problem_Behavior -> Nothing ! Encoding_Error | Illegal_Argument | File_Error
Text.write self path encoding=Encoding.utf_8 on_existing_file=Existing_File_Behavior.Backup on_problems=Problem_Behavior.Report_Warning =
```

- If input value has a warning attached, warning become a hard error.
  `Warning.remove_all value`
  `Warning.remove Encoding_Error value`
  **To be assessed once real world usage.**
- All file access or IO errors, reported as File_Error hard errors.
  **Possible retry logic for file access errors.**
- Encoding_Error follow the Text.bytes rules.

### Table.filter

```
filter : (Column | Text | Integer) -> (Filter_Condition|(Any->Boolean)) -> Problem_Behavior -> Table
filter self column filter=Filter_Condition.Is_True on_problems=Report_Warning = case column of
```

Missing column
- If unable to find column then a hard error.
- If expression is invalid or can't find column then a hard error.
- Likewise if column used within Filter_Condition.

- If equality on a floating point number, a `Floating_Point_Equality` problem attached following Problem_Behavior.
- Divide by 0, Square root of a negative number, etc. - an `Arithmetic_Error`.
- Comparison with Nothing - should this be a warning?

### Table.write

```
```

## Comments:
**James Dunkerley** reports a new **STANDUP** for today (2023-01-11):

**Progress:** Addressing PR comments. Started looking at backlog and adding tasks for warnings work. Found issues with Table visualisation failing if table had a warning attached - worked around by stripping warnings. Experimental warning visualisation. It should be finished by 2023-01-16.

**Next Day:** Next day I will be working on the [#184073122 task](https://www.pivotaltracker.com/story/show/184073122). Sort the backlog and task the warnings work and then get started. (Enso Bot - Jan 11, 2023)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2023-01-12):

**Progress:** Finally got the Vector PR in. Some work on Warnings visualisation and on dropping a file onto Enso. Tidying up the backlog and starting to work through tickets. It should be finished by 2023-01-16.

**Next Day:** Next day I will be working on the [#184073122 task](https://www.pivotaltracker.com/story/show/184073122). Sort the backlog... (Enso Bot - Jan 12, 2023)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2023-01-13):

**Progress:** Sorted out the backlog into the Excel sheet. Went through the planning with Ned and Sylwia. Started adding the tasks for the problem behaviour. It should be finished by 2023-01-16.

**Next Day:** Next day I will be working on the [#184073122 task](https://www.pivotaltracker.com/story/show/184073122). A few follow up things from week 1 book club. Continued task break down and get started on implementation. (Enso Bot - Jan 13, 2023)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2023-01-16):

**Progress:** Completed tasking up the Problem Behavior work. Improved the task list enso flow and spreadsheet to help keep it ordered in a way that works for me. Did a PreppinData task to see how Enso coped (pretty well :)). Meeting on warning viz with Dmitry, Adam, Greg and Wojciech - next steps seem aligned. Prep for weekly meeting. It should be finished by 2023-01-16.

**Next Day:** Next day I will be working on the [#184073122 task](https://www.pivotaltracker.com/story/show/184073122). Design for Regex and tasking... (Enso Bot - Jan 16, 2023)
<hr />

**Comment by jdunkerley** [comment]
Related: 
- [ ] #5009 
- [ ] #5010 
- [ ] #5108 
- [ ] #5109 
- [ ] #5110 
- [ ] #5111 
- [ ] #5112 
- [ ] #5113 
- [ ] #5114 
- [ ] #5115 
- [ ] #5116
- [ ] #5117

**Comment by jdunkerley** [comment]
Closing as have the design in place
