### ISSUE TITLE
Design for Regex support

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4986]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/181524498).
<hr />

- Should simplify to a single dialect
- Need to support:
  - split/tokenise
  - find / replace
  - contains
  - parse to a table

--
We need to review the Regex API and make sure it fits our designs.

We should also figure out best ways to address some issues:
- issues with Unicode canonical forms / normalization - `s\u{301}` will match `s` but `ś` will not, even though both represent the same grapheme (ideally, both should not match `s` since `ś` is a different character);
  - we had a workaround that normalized all strings, but it was imperfect:
    - it made both cases _match_ and we would prefer both to _not match_, if achievable;
    - it shifted the code unit indices, so the positions of the matches (done in normalized version) would be misaligned versus the original code units - this was the reason that made it necessary to disable this feature for now. If we want to keep using normalization, we need to translate all indices to the original space.
- for now the returned `Match` objects work in UTF-16 code unit space; this is documented but may be confusing as all of our other text operations work in Extended-Grapheme-Cluster space;
- matching empty patterns does not work as expected, it should be revisited.

## Blockers:
[#181348590](https://www.pivotaltracker.com/story/show/181348590) blocked
[#184295366](https://www.pivotaltracker.com/story/show/184295366) blocked
[#184295378](https://www.pivotaltracker.com/story/show/#184295378) resolved
[#184295448](https://www.pivotaltracker.com/story/show/184295448) blocked
[#184295476](https://www.pivotaltracker.com/story/show/184295476) blocked
[#184295502](https://www.pivotaltracker.com/story/show/184295502) blocked
[#184295524](https://www.pivotaltracker.com/story/show/184295524) blocked
[#184295561](https://www.pivotaltracker.com/story/show/184295561) blocked
[#184295570](https://www.pivotaltracker.com/story/show/184295570) blocked
[#184295718](https://www.pivotaltracker.com/story/show/184295718) blocked
[#184295734](https://www.pivotaltracker.com/story/show/184295734) blocked
[#184295751](https://www.pivotaltracker.com/story/show/184295751) blocked
[#184295808](https://www.pivotaltracker.com/story/show/184295808) blocked

## Comments:
**James Dunkerley** reports a new **STANDUP** for today (2023-01-17):

**Progress:** Started on the design for the new Regex API. Minor fixes from Week 1 book club (fighting with it to get the issues fixed). Meeting on the AoC blog post - started getting post together. Cloud discussion on execution API and permissions. It should be finished by 2023-01-19.

**Next Day:** Next day I will be working on the [#184073122 task](https://www.pivotaltracker.com/story/show/184073122). Finish Regex design and task. Then onto expressions and null in columns. (Enso Bot - Jan 17, 2023)
<hr />
**James Dunkerley** reports a new **STANDUP** for yesterday (2023-01-18):

**Progress:** Working on the Regex design. It should be finished by 2023-01-19.

**Next Day:** Next day I will be working on the [#184073122 task](https://www.pivotaltracker.com/story/show/184073122). Finish Regex design and task. Then onto expressions and null in columns. (Enso Bot - Jan 19, 2023)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2023-01-19):

**Progress:** Got the AoC Blog Post ready to go. Worked on the Regex API. Reviewed API with Ned and Sylwia. It should be finished by 2023-01-19.

**Next Day:** Next day I will be working on the [#184073122 task](https://www.pivotaltracker.com/story/show/184073122). Finish Regex design and task. Then onto expressions and null in columns. (Enso Bot - Jan 19, 2023)
<hr />
**James Dunkerley** reports a new **🔴 DELAY** for today (2023-01-20):

**Summary:** There is **4 days** delay in implementation of the [Design for Regex support (#181524498) task](https://www.pivotaltracker.com/story/show/181524498).
It **will cause 0 days delay** for the delivery of this weekly plan.

Design nearly complete following session with Ned and Sylwia. Will complete on Monday and task up.

**Delay Cause:** Time on other things is high at moment (AoC Blog, Demos, Interviews). (Enso Bot - Jan 20, 2023)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2023-01-20):

**Progress:** Completed the skeleton of the design with Ned and Sylwia. Built up and posted the AoC blog. Issue with the IDE - took out some time this morning following issue in Demo. 2 Demos. Design session with Ned and Sylwia. It should be finished by 2023-01-23.

**Next Day:** Next day I will be working on the [#181524498 task](https://www.pivotaltracker.com/story/show/181524498). Finish the design write up and task up. (Enso Bot - Jan 20, 2023)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2023-01-23):

**Progress:** Completed the write up of the design added tasks to pivotal. It should be finished by 2023-01-23.

**Next Day:** Next day I will be working on the [#181524498 task](https://www.pivotaltracker.com/story/show/181524498). Something else... (Enso Bot - Jan 23, 2023)
<hr />

**Comment by jdunkerley** [comment]
Related:
- [ ] #5118 
- [ ] #5119 
- [ ] #5124 
- [ ] #5120 
- [ ] #5121 
- [ ] #5122 
- [ ] #5123 
- [ ] #5125 
- [ ] #5126 
- [ ] #5127 
- [ ] #5128

**Comment by jdunkerley** [comment]
Closing as have design and tasks linked.
