### ISSUE TITLE
Autosave

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4990]
```[tasklist]
### Tasks
- [ ] #5001 
- [ ] #5338
```

This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/183494296).
<hr />

- As a user, I want to have easy access to the visual indicator “*” next to the file name to see if it is saved or not.
- As a user, when I close Enso or a project the autosave file is updated for the project.
- As a user, when I choose to save the file the autosave is removed and the file updated.
- As a user, I can revert to the previously saved file if there are changes (or an auto save was restored) using a button within the UI.

The idea is roughly the same as Visual Studio Code. Autosaving just happens but the user chooses to overwrite when they wish.

Reopening a project restores from autosave if it exists.

## Tasks:
- [X] User Stories
- [ ] UI
- [ ] Pivotal Issues creation

## Blockers:
[#183509062](https://www.pivotaltracker.com/story/show/#183509062) resolved
[#183509263](https://www.pivotaltracker.com/story/show/#183509263) resolved
[#183509294](https://www.pivotaltracker.com/story/show/#183509294) resolved
[#183509394](https://www.pivotaltracker.com/story/show/#183509394) resolved
[#183509602](https://www.pivotaltracker.com/story/show/#183509602) resolved
[#183558159](https://www.pivotaltracker.com/story/show/#183558159) resolved
[https://www.pivotaltracker.com/story/show/183604295](https://www.pivotaltracker.com/story/show/https://www.pivotaltracker.com/story/show/183604295) blocked
[https://www.pivotaltracker.com/story/show/183604351](https://www.pivotaltracker.com/story/show/https://www.pivotaltracker.com/story/show/183604351) blocked
[#183661786](https://www.pivotaltracker.com/story/show/#183661786) resolved

**Comment by farmaazon** [comment]
Instead of autosave, we decided to use VCS in the old GUI. It still needs to be restored in new one, but let's make a new task with proper description when time comes.
