### ISSUE TITLE
IO execution environments

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4993]
This task is automatically imported from the old Task Issue Board and it was originally created by Marcin Kostrzewa.
Original issue is [here](https://www.pivotaltracker.com/story/show/182781696).
<hr />

In order to facilitate granular control over IO actions execution, the language needs to expose certain additional facilities.

1. Two `in` Contexts should be introduced: `Input` and `Output`, for functions performing IO.
2. For any `in Input` or `in Output` method, a permission check should be inserted (more on its nature later).
3. Point `2.` also holds for inferred signatures in the future.
4. There exist different "environments", identified by a string name, that configure IO permissions. These may or may not be configurable in the future, but there are 2 defaults: `production` and `development`. The first allows all IO, the second disallows it.
5. A program is always run in _some_ environment (including in text).
6. Methods for locally overriding these exist. I.e. It is possible to write `allow_output env="development" <| some_action`, which results in `some_action` having elevated permissions in the development env. This can be used to implement the `auto-run-IO` toggle in the IDE – such a toggle will modify the code. This ensures that running a program in the IDE and in the console will have the same result.
7. The instrumentation framework also has a way to override this setting for a single node, for a single run – this enables the `play` button of the IDE.
8. All the previous requirements point towards a `Reader` monad solution – we have a config that can be read by the permission check and we have the override which is akin to the `local` function of `Reader`.
9. Such a reader should be simulated by Enso's state monad. It's probably best to change the `Stateful` type to hold a specific `State` type instead of an `Object`. The `State` could hold the IO configs next to the object that it currently is.
10. The permission check throws an exception if IO is disallowed.

**Comment by jdunkerley** [comment]
Need to understand state of this ticket and how we can move forward with it.
@sylwiabr and @jdunkerley to discuss.

**Comment by jdunkerley** [comment]
Following #5713 will replace with new tickets.
