### ISSUE TITLE
Implementation of a simple drop-down and integration with the node view. Pt.2

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4997]
This task is automatically imported from the old Task Issue Board and it was originally created by Paweł Grabarz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183970089).
<hr />

## Step 1: implementation of a simple drop-down and integration with the node view.

**Delivery requirements:**  
- A first drop-down implementation should be created. It should be just a list of entries, allowing a single entry selection, scrolling, and nothing more (no filtering, no displaying of old values that are not on the hint list anymore, etc.). From a technical point of view, this should be a simple wrapper over the Grid View component. 
- The drop-down widget should be integrated with nodes. When the node input ports are re-drawn, we first get an AST description from the GUI backend (produced by the engine). This description contains type information and other data. It should contain hints regarding what widget to use for a particular input field. If this info is missing, adding this info is part of this task (in collaboration with the engine team). In order to make the implementation on the engine side easier, in Step 1, we should support only "static drop-downs" (where the drop-down hints do not depend on the runtime data, for example when hinting variants of a struct).
- When we get information that a particular node's input port is a drop-down widget, the GUI backend should be queried for all possible entries for the drop-down. The GUI backend should then use engine API to get this data and send it to the widget view. In order to simplify the implementation on the engine side, in Step 1, we should obtain all the data (in the next steps we will refine it to a lazy query).
- After clicking an item from the drop-down widget, the AST/code should be modified accordingly.
- The widget should be integrated both with the main IDE entry point as well with the interface debug scene.

**Technical comments:**  
Please, be very careful when changing the logic of the input ports implementation. It's not big, but it's fairly complex. It was designed in a particular way for a few reasons. The input ports are part of the node expression, while the expression can be hierarchical, like `foo [1, 2, bar x]`. It should be possible to connect the input port to any of  `foo [1, 2, bar x]`, `foo`, `[1, 2, bar x]`, `1`, `2`, `bar x`, and `x` (this is currently implemented). In the future (this is not part of this task), we also want to support connecting inputs between list items with automatic comma insertion. In order to support this use case in a general way, our parser was designed in such a way, that most of the syntax elements (like array literals) are macros, whose structure is described by regexp-like expression, that we can analyze after parsing. For example, we can analyze it to understand that after inserting an element after `2`, a comma should be inserted.

## Blockers:
[https://www.pivotaltracker.com/story/show/184023380](https://www.pivotaltracker.com/story/show/https://www.pivotaltracker.com/story/show/184023380) resolved
[https://www.pivotaltracker.com/story/show/184023445](https://www.pivotaltracker.com/story/show/https://www.pivotaltracker.com/story/show/184023445) resolved

## Comments:
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2022-12-06):

**Progress:** Cleaned up the standalone dropdown component FRP API to match new requirements, started simplifying the model towards simple static list support. It should be finished by 2022-12-12. (Enso Bot - Dec 7, 2022)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for today (2022-12-07):

**Progress:** Implemented static list support for dropdown and simplified entry cache to support just that usecase. It should be finished by 2022-12-12. (Enso Bot - Dec 7, 2022)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2022-12-08):

**Progress:** Created more test scenarios on dropdown demo scene and matched visuals to design. Added tag_values support to argument suggestions. It should be finished by 2022-12-12. (Enso Bot - Dec 9, 2022)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2022-12-12):

**Progress:** Added opening/closing animation to dropdown. Used tag_values as data source in the node widget. Fixed some issues with dropdown entry updates after state change. It should be finished by 2022-12-12.

**Next Day:** Next day I will be working on the [#184023380 task](https://www.pivotaltracker.com/story/show/184023380). Will isolate standalone dropdown without node-related changes and prepare it for PR submission, then continue working on basic node widget integration. (Enso Bot - Dec 13, 2022)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for the provided date (2022-12-09):

**Progress:** Reworekd dropdown value abstraction to avoid wrapping entries that already hold their label. Simplified dropdown entry cache further based on that. It should be finished by 2022-12-12. (Enso Bot - Jan 5, 2023)
<hr />

**Comment by sylwiabr** [comment]
already implemented
