### ISSUE TITLE
Drop-down widget

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#4999]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/183930734).
<hr />

## Team
Technical Designer: Wojciech Danilo
Implementer: Pawel Grabarz
Acceptance/QA: Adam Obuchowicz

## Why
The drop-down widget is the most important widget that we want to display on nodes. The idea is that the user of Enso does not have to type expressions, not learn by heart the names (like the column names), and is able to choose them from a list.

## Acceptance Criteria
The drop-down widget appears on nodes in every place where the libraries are providing us with metadata that a drop-down should be displayed.

## Design
This description is a refinement of a design created by our engine team. Please read these documents first in order to know the context of how widgets will work on the engine side: https://github.com/enso-org/design/tree/main/epics/widgets/drop-downs

See the attachments with mockup images.

---------------

# Implementation Plan
This is a bigger feature that needs to be split into several stories. This section contains a proposal for such a split. The plan should be discussed between teams (GUI and Engine), and the planning management (Sylwia and Greg). Then, adjustments to this plan should be made and the plan should be split into tasks.

Please remember that in many cases an additional API might be required on the Engine side. If delivering of this API would take so long that it will block the work on the GUI side, a mock API should be delivered first (we did it multiple times, and it works well).

## Step 1: implementation of a simple drop-down and integration with the node view.

Status: DONE (only simple dropdown part - complete widget integration tracked separately in #5134)

**Delivery requirements:**  
- A first drop-down implementation should be created. It should be just a list of entries, allowing a single entry selection, scrolling, and nothing more (no filtering, no displaying of old values that are not on the hint list anymore, etc.). From a technical point of view, this should be a simple wrapper over the Grid View component. 
- The drop-down widget should be integrated with nodes. When the node input ports are re-drawn, we first get an AST description from the GUI backend (produced by the engine). This description contains type information and other data. It should contain hints regarding what widget to use for a particular input field. If this info is missing, adding this info is part of this task (in collaboration with the engine team). In order to make the implementation on the engine side easier, in Step 1, we should support only "static drop-downs" (where the drop-down hints do not depend on the runtime data, for example when hinting variants of a struct).
- When we get information that a particular node's input port is a drop-down widget, the GUI backend should be queried for all possible entries for the drop-down. The GUI backend should then use engine API to get this data and send it to the widget view. In order to simplify the implementation on the engine side, in Step 1, we should obtain all the data (in the next steps we will refine it to a lazy query).
- After clicking an item from the drop-down widget, the AST/code should be modified accordingly.
- The widget should be integrated both with the main IDE entry point as well with the interface debug scene.

**Technical comments:**  
Please, be very careful when changing the logic of the input ports implementation. It's not big, but it's fairly complex. It was designed in a particular way for a few reasons. The input ports are part of the node expression, while the expression can be hierarchical, like `foo [1, 2, bar x]`. It should be possible to connect the input port to any of  `foo [1, 2, bar x]`, `foo`, `[1, 2, bar x]`, `1`, `2`, `bar x`, and `x` (this is currently implemented). In the future (this is not part of this task), we also want to support connecting inputs between list items with automatic comma insertion. In order to support this use case in a general way, our parser was designed in such a way, that most of the syntax elements (like array literals) are macros, whose structure is described by regexp-like expression, that we can analyze after parsing. For example, we can analyze it to understand that after inserting an element after `2`, a comma should be inserted. 

## Step 2: Support for dynamic data (important to be done ASAP for demo purposes)

Status: DONE

**Delivery requirements:**  
- The implementation should be refined to work with dynamic data. For example, the `remove_column` node should display a drop-down with a list of all column names. 

## Step 3: Support for multi-selection

Status: ??? (probably replaced by Vector Editor)

**Delivery requirements:**  
- The implementation should be refined to allow a multi-selection of entries. The information if the widget should allow multi-selection should be delivered from the engine together with the information that a particular input should be displayed as a drop-down widget. See the widget metadata design to learn more: https://github.com/enso-org/design/blob/main/epics/widgets/drop-downs/dynamic-widgets.md

## Step 4: Sorting and lazy loading the data.

Status: TO DO

**Delivery requirements:**  
- The drop-down widget should display a sorting icon (with 3 states: off, sorting in ascending order, and sorting in descending order. See the attached mockup image.). 
- In this step, the data provided to the widget should be provided in a lazy fashion. The engine should expose an API allowing for Enso expression evaluation from the widget. The API should be very similar to the lazy visualization API with one difference - in the case of lazy visualization, the input data is produced by the previous node. In the case of lazy widgets, the input data is produced by evaluating the expression placed in code metadata (see the metadata design to learn more: https://github.com/enso-org/design/blob/main/epics/widgets/drop-downs/dynamic-widgets.md).
- The Enso expression produced by the widget should use the caching mechanism. In particular, when scrolling a sorted list of entries, the sorting should be done as the first expression part, it should be cached, and should not be recomputed when the list is being scrolled. While scrolling the list, another expression part should be modified (something along the lines of "give me the entries 500-520"). 
- Please be sure that the cached data on the GUI side (e.g. after loading some data to the drop-down view) is correctly invalidated when nodes are recomputed (this information should come from the engine and is probably already there, as other GUI elements depend on this behavior).

## Step 5: Filtering the data.

Status: TO DO

**Delivery requirements:**  
- When the drop-down is clicked, the list of entries is displayed. In this state, when the user starts typing, the typed text should be displayed instead of the current value (on the node). The entries should be filtered in "real-time" on the engine side. This should be done in the same way as scrolling and sorting (just by creating another expression which should be computed on the engine side before the widget gets the final data). 
- The filtering should allow for regexp input. The text typed by the user should be just fed into our regexp library on the engine side.
- The matched letters should have different color and should be displayed in bold (in the same way as letters in the component browser search).
- After pressing "enter", the best match should be used. After pressing "ctrl + enter", the typed text should be used as-is. This behavior should be the same as in the case of the component browser.

## Step 6: Showing the obsolete data.

Status: TO DO

**Delivery requirements:**  
- In this step, the drop-down should be refined to display on the list of entries obsolete data, data that was chosen but is no longer available to be chosen. For example, the user could have chosen a table column name, but the table changed and it does not have this column anymore. The chosen entry should be displayed just as an ordinary entry but should have a different color (to be designed closer to the implementation of this step).
- Drop-down widgets should allow deselecting an obsolete entry, selecting an existing one, and then selecting the obsolete entry again. Basically, the obsolete entries should not disappear from the drop-down until the node is recomputed, or until the user changes the view to another part of the graph (e.g. by entering a node).

## Blockers:
[https://www.pivotaltracker.com/n/projects/2539304/stories/183855312](https://www.pivotaltracker.com/story/show/https://www.pivotaltracker.com/n/projects/2539304/stories/183855312) resolved
[#183970089](https://www.pivotaltracker.com/story/show/#183970089) blocked
[#184012743](https://www.pivotaltracker.com/story/show/#184012743) blocked
[#184012753](https://www.pivotaltracker.com/story/show/#184012753) blocked
[#184012776](https://www.pivotaltracker.com/story/show/#184012776) blocked
[#184012788](https://www.pivotaltracker.com/story/show/#184012788) blocked
[#184012807](https://www.pivotaltracker.com/story/show/#184012807) blocked

## Comments:
 (Wojciech Daniło - Dec 1, 2022)
<hr />

**Comment by sylwiabr** [comment]
@Frizi @wdanilo is it done? can we close it? this is an umbrella task for the drop-down AFAIK

**Comment by Frizi** [comment]
Step 4, 5 and 6 are not done yet. Given our current priorities, we won't work on it any time soon as well.

**Comment by xvcgreg** [comment]
> Step 4, 5 and 6 are not done yet. Given our current priorities, we won't work on it any time soon as well.

Some time ago we were also discussing a scope change of those tasks as well.

**Comment by wdanilo** [comment]
> Step 4, 5 and 6 are not done yet. Given our current priorities, we won't work on it any time soon as well.

Could you please edit the main description off the task and add there checkboxes or anything like DONE / TO BE DONE to indicate the current progress of it, please?

**Comment by xvcgreg** [comment]
@Frizi please see the above. When can you do that?

**Comment by Frizi** [comment]
Status added.
