### ISSUE TITLE
Prepare and run build script usage survey

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5000]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/183940788).
<hr />

No description provided.

**Comment by sylwiabr** [comment]
@mwu-tow what is the status?

**Comment by mwu-tow** [comment]
Was done [here](https://discord.com/channels/401396655599124480/1049895870704926910/1049895870704926910).
