### ISSUE TITLE
Implement a new `GridView` based multi-column Text Visualization (Table Visualization)

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5002]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/183453490).
<hr />

## Why

**As** Enso developer
**I want** to have a visualization that can efficiently render large tables
**So that** I can integrate it in the IDE for efficient rendering of node outputs with large tables

## Acceptance Criteria

```gherkin
Scenario: 
Given I open the Grid View Text visualisaiton demo scene
Then I see a table visualization that contains a huge table that is cropped to a smaller visualization windows and that can be scrolled vertically and horizontally. 
```

## Notes
This should extend the visualization implemented in #183453449

## Comments:
**Michael Mauderer** reports a new **STANDUP** for today (2022-11-03):

**Progress:** Backported the changes to make the previous PR re-review ready. Need to fix one more small thing. It should be finished by 2022-11-10.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Get properly started on the current task, starting with extending the single column grid to be able to show a nice grid of multiple rows and columns with dividers. (Enso Bot - Nov 3, 2022)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for yesterday (2022-11-14):

**Summary:** There is **8 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Sick 4 days + 2 days weekend + delays due to slow progress on working with the engine integration. Debugging and testing Enso code that integrates with the IDE is slow. Was discussed with Sylwia and Greg.

**Possible solutions:** Kill all viruses. Better debugging story for IDE/Enso integrations. (Enso Bot - Nov 15, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-11-14):

**Progress:** Catching up. Updating PRs and resolving issues around changed layer orderings. It should be finished by 2022-11-18.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Create demo videos and test behaviour, mentioned by Wojciech during demo. Resume work on lazy table visualisation. (Enso Bot - Nov 15, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-11-15):

**Progress:** Fixed the remaining issues around layer ordering. Started more extensive testing of the lazy vis according to Wojciech requests and found some issues that needed fixing (and are fixed) and some that require more discussion. It should be finished by 2022-11-18.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Start discussions about lazy vis behaviour for files. Record the scrolling behaviour when the known length/width of the text changes (to show there is no jumping). Continue work on table visualisation. (Enso Bot - Nov 16, 2022)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for yesterday (2022-11-16):

**Summary:** There is **7 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Technical issues with underlying infrastructure appeared (GridView) and some open question that need to be addressed. (Enso Bot - Nov 17, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-11-17):

**Progress:** [for 2022-11-17] Adam found some issues with the GridView when used with many entries, that affects the ability of the lazy vis to show huge texts. I need to investigate and fix this. Also, there appears an issue with the garbage collector panicking sometimes with the current implementation of the lazy text vis, which needs to be fixed before I can continue recording videos and testing. It should be finished by 2022-11-25.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Fix the above-mentioned issues. Discuss the other outstanding issues that need external input. (Enso Bot - Nov 18, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-11-17):

**Progress:** Did some additional research into scrolling and file data content visualization issue. Fixed issue of visualization panicking the garbage collector. Started discussions about outstanding issues of the lazy text visualization. It should be finished by 2022-11-25.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Finish discussions, fix the issues according to discussion outcome. (Enso Bot - Nov 18, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-11-20):

**Progress:** Started PR code cleanup, ran into an issue after rebasing to the newest develop. Engine std lib stopped building correctly.  Investigating and requesting help from the engine team. It should be finished by 2022-11-25.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Fix stb lib issue and finalize PR. (Enso Bot - Nov 21, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-11-21):

**Progress:** With help of engine team, resolved the issue and can now work with the std lib again. Continued on cleanup of the PR. Some lint issues and testing remain. It should be finished by 2022-11-25.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Finish testing and finalize PR.  Resume work on Lazy Table Vis (Enso Bot - Nov 21, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-11-22):

**Progress:** PR code looks good at testing, but found some last bugs. Iterating is somewhat slow when re-building the std-lib, but I used the time to also start work on the rustc bump. No major issues, there it seems, just a number of easy warnings/lints to fix. It should be finished by 2022-11-25.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Finalize PR. Open PR for rustc bump.  Continue work on Lazy Table Vis. (Enso Bot - Nov 23, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-11-23):

**Progress:** Final clean-up and opened PRs for rustc bump and Lazy Text Visualization. Continued work on visuals of the GridView, adding new layout options to and haves to render a grid around columns and rows of text, It should be finished by 2022-11-25.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Continue work on Grid View visuals and start backend integration. Integrate review feedback, if available. (Enso Bot - Nov 24, 2022)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for yesterday (2022-11-26):

**Summary:** There is **4 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** 2 days weekend. Plus 2 days more work needed than expected to finish upgrading single column text view to working multi-column view. Partially due to realizing that the original plan to just use Enso shapes to render the grid, would lead to use needing clipping for both Enso AND HTML component, which it seems sensible to avoid in favor of only using HTML entities and not taking the performance hit of adding the Enso clipping area after all. (Enso Bot - Nov 27, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-11-26):

**Progress:** (actually for 2022-11-24) Continued work on Table Grid View. Continued work on layouting logic. Updating row/column sizes on the fly based on data provided through the backend. It should be finished by 2022-11-29.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Implement an “infinite data” table provider for debugging and the test scene, to be able to iterate quickly without backend. Work on updating the std lib code, providing lazy data from tables. (Enso Bot - Nov 27, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-11-27):

**Progress:** More work on the lay outing side of things was needed to fix some bugs that appeared on further testing. (Also related to FRP initialization.) It should be finished by 2022-11-29.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Finish GUI code. Update the std lib code, providing lazy data from tables. (Enso Bot - Nov 27, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-11-28):

**Progress:** Worked in finalizing GUI code. Basic logic for the visuals are done, but code needs some clean-up and the design needs to be finalized. This will happen as part of the rebase once the lazy text is merged, which is up next. It should be finished by 2022-11-29.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Merge rustc bump. Update the lazy text PR. Rebase Lazy Tables to integrate feedback from Lazy Text. (Enso Bot - Nov 29, 2022)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for yesterday (2022-11-29):

**Summary:** There is **3 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Implementing review feedback took longer than expected. Doing work on the std lib takes me a fair amount of time, due to unfamiliarity with Enso code and tooling (slow iteration process, error message not always as good as they could be). (Enso Bot - Nov 30, 2022)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for today (2022-11-30):

**Summary:** There is **3 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Implementing review feedback took longer than expected. Doing work on the std lib takes me a fair amount of time, due to unfamiliarity with Enso code and tooling (slow iteration process, error message not always as good as they could be). (Enso Bot - Nov 30, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-11-29):

**Progress:** Rustc bump was merged. Started working on integrating feedback. Applied changes from James and Radoslaw, added some more test, and started with the Feedback from Wojciech. I think something went wrong with the last delay report, it got submitted twice. The correct end date is 2022-12-02, but cannot be set on this standup, die to a bot error. It should be finished by 2022-12-05.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Finish updating the lazy text PR. Rebase Lazy Tables to integrate feedback from Lazy Text. (Enso Bot - Nov 30, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-11-30):

**Progress:** Almost managed to finish updating the lazy text PR, but fixing some issues around the serialization/deserialization took a bit longer to fix than hoped, as the workflow is quite slow. It should be finished by 2022-12-05.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Finish fixing the JSON messaged, then rebase Lazy Tables and continue work there. (Enso Bot - Dec 1, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-12-01):

**Progress:** Finished updating the lazy text vis PR and requested re-review. Started updating the lazy tables and fixing some layout issues that were still unresolved. It should be finished by 2022-12-05.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Update the communication protocol for tables on the stdlib side and test integration. (Enso Bot - Dec 1, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-12-04):

**Progress:** Worked on updating the backend/IDE protocol and found some issues with the design that require updating: some mismatch in table cell access vs text line/chunk access, that makes the previous design unsuitable for working with tables and requires some tweaking now. Working on generalizing this in a nice way to work equally nice for both sue cases, It should be finished by 2022-12-05.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Finish updating the communication protocol. Test integration. Clean up code. (Enso Bot - Dec 4, 2022)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for today (2022-12-07):

**Summary:** There is **4 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Regression on develop is blocking work on Lazy Vis and needs to be resolved first. (Enso Bot - Dec 7, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-12-06):

**Progress:** After upgrading the Lazy Text Vis pr to the latest develop and resolving some resulting issues, I noticed that the Lazy Vis no longer works, even worse, not even the Text Grid debug scene already on develop works anymore. Need to investigate what is going on, why this is broken and when this was broken. It should be finished by 2022-12-09.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Continue investigating the cause for Text Grid no longer working. (Enso Bot - Dec 7, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-12-07):

**Progress:** Bisected to find that commit d60e38 (Display object refactoring (#3877)) broke the debug scene. Investigating why this is happening. It should be finished by 2022-12-09.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Find root cause and fix the Lazy Text. (Enso Bot - Dec 7, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-12-08):

**Progress:** Further looked into this and found that the PR changed the default value for DomSymbols to be invisible. Turns out that I am using DomSymbols that are not parented via the display object hierarchy, so they no longer show up. Started discussion around this and how to be solved this. It should be finished by 2022-12-09.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Continue discussion, resolve issue. (Enso Bot - Dec 9, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-12-09):

**Progress:** Updated PR and fixed some merge conflicts. Update the discussion with a minimal example that illustrates the issue that currently exists with mixing HTML element parenting and display object parenting. It should be finished by 2022-12-09.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Finish discussion, implement results in PR. (Enso Bot - Dec 9, 2022)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for today (2022-12-15):

**Summary:** There is **7 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** 2 days weekend, 2 days sick 2 days delay due to extra work required on previous task and one day delay due to needing some extra time after fixing things after updating to develop on both stdlib and GUI code. (Enso Bot - Dec 15, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-12-14):

**Progress:** Finished discussion about mixing HTML element parenting and display object parenting and implemented the changes to PR. I got back to working on the Lazy Table PR, implemented the communication between engine and GUI. Mostly the GUI part so far. It should be finished by 2022-12-16.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Finish the integration of GUI and stlib code for the Lazy Table. (Enso Bot - Dec 15, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-12-15):

**Progress:** Finished frontend/backend integration of Lazy Table. Added some more tests and started code cleanup. It should be finished by 2022-12-16.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Clean up the code, final round of testing and open PR. (Enso Bot - Dec 15, 2022)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for today (2022-12-18):

**Summary:** There is **5 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** 2 days weekend. Additional time needed for testing and code clean-up.

**Possible solutions:** Chatting with Wojciech today. (Enso Bot - Dec 18, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-12-18):

**Progress:** Working on the cleanup. Spent today on adding tests and cleaning the Enso stlib part. Tried to update to develop and ran into a build issue. It should be finished by 2022-12-21.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Clean up the code, more testing. (Enso Bot - Dec 18, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-12-20):

**Progress:** Worked on updating the Lazy Table Vis PR. Resolving some issues caused by updating to newest develop. After some more testing, found some issues with the layouting and started fixing those. It should be finished by 2022-12-21.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Update the Lazy Text PR and release for QA. Finish work on Lazy Tables and start on planning for tasks for Adding Examples from Documentation. (Enso Bot - Dec 21, 2022)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for today (2022-12-21):

**Summary:** There is **1 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Addiiotnal time needed to resolve issues caused by merging develop. (Enso Bot - Dec 21, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-12-21):

**Progress:** Updated the Lazy Text PR again for develop to be ready for QA. API changes to the DOM elements caused text to disappear and required fixing (related to # Fixing set_size regression. #3995). It also broke some parts of the serialization on, which took some time to fix. But the PR is now working again and ready for QA. Worked further on updating the Lazy Table to open PR. Spent time during compiles on planning for Adding Example from Docs task. It should be finished by 2022-12-22.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Discuss Adding Example Task splitting and create tasks. Finish work on Lazy Table. (Enso Bot - Dec 21, 2022)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for today (2022-12-23):

**Summary:** There is **6 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

3 days of Christmas.

**Delay Cause:** Additional time needs for Lazy Text Visualization to investigate issues that appeared during QA. (Machine dependent JS behavior and some performance considerations). (Enso Bot - Dec 23, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-12-22):

**Progress:** Discussed task splitting for Adding Examples From Docs and prepared follow-on discussion and notes for creating pivotal tasks. Continued work on Lazy Table PR. Fixed the serialization/deserialistion issue that occured after updating develop. Continued testing and fixing smaller issues. I also received feedback from Galin about the Text Pr, where he found some issues. It should be finished by 2022-12-28.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Create Pivotal tasks for Adding Examples From Docs. Investigate Galins Feedback. Create an initial draft PR for the Lazy Table Stlib API as a first step to delivering (Enso Bot - Dec 23, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2022-12-23):

**Progress:** Investigated Galin's feedback and found a performance issue with the engine communication on less powerful machines as well as a timeout that aborts lazy text evaluation for very, very large texts. There is also an issue about measuring text, which seems to have platform-specific issues and needs to be further investigated. I also created the pivotal tasks for the Examples From Docs task.  I also created a draft PR for the Lazy Table PR stlib part as a first step to delivering the entire task. It should be finished by 2022-12-28.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Continue investigations and fixes for the issues on Lazy Text. (Enso Bot - Dec 23, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-12-27):

**Progress:** Made some performance related improvements based on Galins feedback and spoted an issue where the first update to the lazy visualisation would be too big. Started further investigating the Layouting issue. Started discussions about non-technical issues around Galins feedback. It should be finished by 2022-12-28.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Find solution for layouting issue and implement it. (Enso Bot - Dec 28, 2022)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for today (2022-12-29):

**Summary:** There is **2 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Investigating an issue with the JS text measurement functionality is taking extra time. (Enso Bot - Dec 29, 2022)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2022-12-28):

**Progress:** Investigating the layouting issues and why we are getting values that do not correspond to the size of elements we are seeing. It should be finished by 2022-12-30.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Continue investigation of layouting issues. (Enso Bot - Dec 29, 2022)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for today (2023-01-10):

**Summary:** There is **11 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Illness + investigating + fixing text layout issue (Enso Bot - Jan 10, 2023)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2023-01-09):

**Progress:** Catching up after illness. Continued investigating the text layout issue and found a solution. Discussed the issue with Wojciech. Also discussed the implementation requirements for the text selection. It should be finished by 2023-01-10.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Implement proper fix for lay outing issue and layout initialization. (Enso Bot - Jan 10, 2023)
<hr />
**Michael Mauderer** reports a new **STANDUP** for today (2023-01-10):

**Progress:** Implemented the fix for the layout issue and initialization. It should be finished by 2023-01-10.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Request QA and reviews and get started on the next task. (Enso Bot - Jan 10, 2023)
<hr />
**Michael Mauderer** reports a new **🔴 DELAY** for yesterday (2023-01-11):

**Summary:** There is **1 days** delay in implementation of the [Implement a new `GridView` based multi-column Text Visualization (Table Visualization) (#183453490) task](https://www.pivotaltracker.com/story/show/183453490).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** After updating, PR found a regression that needed fixing. (Enso Bot - Jan 12, 2023)
<hr />
**Michael Mauderer** reports a new **STANDUP** for yesterday (2023-01-11):

**Progress:** When updating the PR I found what looked like a performance regression that needed addressing. Resolved the issue, which was caused by infinite recursion between two different methods that got moved around in an unexpected way.  Continued cleanup. It should be finished by 2023-01-11.

**Next Day:** Next day I will be working on the [#183453490 task](https://www.pivotaltracker.com/story/show/183453490). Request QA and reviews and get started on the Rust bump. (Enso Bot - Jan 12, 2023)
<hr />
	@michael_mauderer @gregociepka what is the status here? (Sylwia Brodacka - Feb 1, 2023)
<hr />
There are 2 PRs that need to be merged (in order) for this to be finished. First PR is currently under review.  (Michael Mauderer - Feb 3, 2023)
<hr />

**Comment by farmaazon** [comment]
No longer valid for GUI2 - we don't have any "GridView" component.
