### ISSUE TITLE
Dropdown dynamic data support

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5003]
This task is automatically imported from the old Task Issue Board and it was originally created by Paweł Grabarz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184012743).
<hr />

Step 2: Support for dynamic data

important to be done ASAP for demo purposes

Continuation of https://www.pivotaltracker.com/n/projects/2539304/stories/183970089

Delivery requirements:

The implementation should be refined to work with dynamic data. For example, the remove_column node should display a drop-down with a list of all column names.

Design doc: https://github.com/enso-org/design/blob/main/epics/widgets/drop-downs/dynamic-widgets.md

## Blockers:
[#182801491](https://www.pivotaltracker.com/story/show/#182801491) resolved
[#184204435](https://www.pivotaltracker.com/story/show/#184204435) resolved

## Comments:
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2023-01-02):

**Progress:** Applied Meta.get_annotation mock, built local engine version and ran IDE on it. I have manually tested that mock on some tables and I was able to get table headers correctly. It should be finished by 2023-01-11. (Enso Bot - Jan 3, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for today (2023-01-03):

**Progress:** Started planning implementation of dynamic data provider for widgets. Reading through Visualization and ExecutedGraph implementation to better understand how to query arbitrary expression results. It should be finished by 2023-01-11. (Enso Bot - Jan 3, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2023-01-04):

**Progress:** Started working on widgets controller implementation, which will be necessary for querying widget metadata. Not sure yet how to query that data using existing engine APIs, plan to discuss that soon. It should be finished by 2023-01-11. (Enso Bot - Jan 5, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for today (2023-01-05):

**Progress:** Discussed details of `Meta.get_annotation` function and how it might be queried for widgets using Visualization API. Still unsure about how exactly it can be used, as I see a potential issues with available expression Ids not being granular enough. I plan to explore that as part of widget controller. Further discussion about this is also planed. It should be finished by 2023-01-11. (Enso Bot - Jan 5, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for today (2023-01-09):

**Progress:** Discussed and decided on the general approach of how to use visualisation APIs to query for widget metadata. I started querying for it and ran into some issues when registering visualisations for non-node expressions. I will report those as bugs once I rule out that I'm using it wrong. It should be finished by 2023-01-11. (Enso Bot - Jan 9, 2023)
<hr />
**Paweł Grabarz** reports a new **🔴 DELAY** for yesterday (2023-01-11):

**Summary:** There is **5 days** delay in implementation of the [Dropdown dynamic data support (#184012743) task](https://www.pivotaltracker.com/story/show/184012743).
It **will cause 0 days delay** for the delivery of this weekly plan.

**Delay Cause:** Figuring out how to correctly query widget data took longer than expected and bugs were found. (Enso Bot - Jan 12, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2023-01-11):

**Progress:** Found a language server bug with visualizations that are registered for non-root expression, worked out when responses are missing. Continuing work on integrating visualisation based widget query into nodes. It should be finished by 2023-01-16. (Enso Bot - Jan 12, 2023)
<hr />
**Paweł Grabarz** reports a new **🔴 DELAY** for today (2023-01-17):

**Summary:** There is **3 days** delay in implementation of the [Dropdown dynamic data support (#184012743) task](https://www.pivotaltracker.com/story/show/184012743).
It **will cause 3 days delay** for the delivery of this weekly plan.

**Delay Cause:** I was interrupted by additional post-QA work and performance regression related to simple dropdown, which needed to be addressed immediately. (Enso Bot - Jan 17, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2023-01-16):

**Progress:** Added proper widget query controller, requesting queries from nodes as function calls are discovered. Started querying widget metadata using fixed visualizations hooked to call target subexpressions. Still have some issues detecting both prefix and infix function calls and threading that data to the right widgets. I'm hitting some race conditions with suggestion database updates, which also causes the expressions to not be annotated properly. This looks to be an old bug. It should be finished by 2023-01-19. (Enso Bot - Jan 17, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2023-01-17):

**Progress:** I was inspecting input span trees, searching for a reliable way to index widgets based on calls they correspond to and route data updates to them. I have discovered many situations where method calls are tricky to pattern match. I have built a better visualisation tool for span trees to aid the process. Also finished shader cache work after PR review. It should be finished by 2023-01-19. (Enso Bot - Jan 18, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for today (2023-01-18):

**Progress:** Extended span tree building process to preserve information about related function calls and their targets for each discovered argument node. Used that to index created widgets and route data updates. I'm finally getting the whole trip from discovering calls, querying widget metadata and feeding it to widgets in the right places. That indexing also allowed the widget views to be retained across expression edits, greatly improving edit performance. I still need to clean up that logic a bit and fix bugs with node widgets not being cleaned up properly after some edits. It should be finished by 2023-01-19. (Enso Bot - Jan 18, 2023)
<hr />
**Paweł Grabarz** reports a new **🔴 DELAY** for yesterday (2023-01-19):

**Summary:** There is **5 days** delay in implementation of the [Dropdown dynamic data support (#184012743) task](https://www.pivotaltracker.com/story/show/184012743).
It **will cause 3 days delay** for the delivery of this weekly plan.

**Delay Cause:** Underestimated the complexity of matching for the method calls to place widgets and propagating the queried widget data to the correct views. The initial implementation resulted in a lot of bugs. (Enso Bot - Jan 20, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2023-01-19):

**Progress:** Found and fixed an Rc cycle memory leak that caused the dropdowns to not disappear on node changes. Now widgets tend to disappear for a moment during expression updates, and the metadata is lost. Added saving of previously queried widget data in the widget controller, but it still needs to be properly propagated to view. It should be finished by 2023-01-24. (Enso Bot - Jan 20, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for today (2023-01-20):

**Progress:** Extended spantree even further to preserve call expression ID. Used that to issue widget query based on created widgets or during suggestion db updates. Now queried data is always propagated after widget creation, making widgets resilient to transient expression updates. It should be finished by 2023-01-24. (Enso Bot - Jan 20, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2023-01-24):

**Progress:** Cleaned up widget code in preparation for PR review. Also measured the performance of opening a dropdown and found a few easy improvements. It should be finished by 2023-01-24. (Enso Bot - Jan 24, 2023)
<hr />
**Paweł Grabarz** reports a new **🔴 DELAY** for yesterday (2023-01-24):

**Summary:** There is **2 days** delay in implementation of the [Dropdown dynamic data support (#184012743) task](https://www.pivotaltracker.com/story/show/184012743).
It **will cause 2 days delay** for the delivery of this weekly plan.

**Delay Cause:** More non-trivial widget bugs were uncovered when cleaning up the PR and testing it. Making it stable requires more work. (Enso Bot - Jan 25, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2023-01-24):

**Progress:** Continuing the remaining cleanup and doing more testing. I have noticed another bug with widgets not being properly disposed or updated. Most likely another Rc cycle that needs to be tracked down. It should be finished by 2023-01-26. (Enso Bot - Jan 25, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for today (2023-01-25):

**Progress:** Found the cause of inconsistent widget updates and cause of memory leak, both caused by incorrect passing of frp endpoints to the lazily initialized dropdown. Implemented hiding widgets when node is in edit mode. Rebased the branch and I'm now able to test the whole feature using actual engine provided annotations. It should be finished by 2023-01-26. (Enso Bot - Jan 25, 2023)
<hr />
**Paweł Grabarz** reports a new **🔴 DELAY** for today (2023-01-31):

**Summary:** There is **6 days** delay in implementation of the [Dropdown dynamic data support (#184012743) task](https://www.pivotaltracker.com/story/show/184012743).
It **will cause 2 days delay** for the delivery of this weekly plan.

**Delay Cause:** Received a lot of requested changes during PR review, which requires some non-trivial refactoring to address properly. (Enso Bot - Jan 31, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2023-01-30):

**Progress:** Refactored widget registration to get rid of not strictly necessary target_id, which caused a lot of confusion on code review feedback. That simplified code quite a bit in preparation for widget controller refactor. It should be finished by 2023-02-01. (Enso Bot - Jan 31, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for today (2023-01-31):

**Progress:** Completed refactor of widget controller, addressed a lot of other remaining feedback from PR. Almost done going through all of it, no more big changes should be necessary. It should be finished by 2023-02-01. (Enso Bot - Jan 31, 2023)
<hr />
**Acceptance/QA** review set to **pass** (Ilya Bogdanov - Feb 2, 2023)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for yesterday (2023-02-01):

**Progress:** Finished remaining changes and submitted PR for final review. A bug on page refresh was noticed during QA, which I have investigated and found that it only happens on older engine versions. I'm preparing a detailed bug report for it. It should be finished by 2023-02-01. (Enso Bot - Feb 2, 2023)
<hr />

**Comment by sylwiabr** [comment]
@Frizi I think this one was delivered, am I right?
