### ISSUE TITLE
Runtime doesn't reload module's sources after LS reloaded the buffer

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5013]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184324365).
<hr />

This is causing unexpected failures in positions e.g.,
```

org.enso.interpreter.service.error.FailedToApplyEditsException: Some(Failed to apply edits for local.Unnamed_35.Main, edits=***, failure=InvalidPosition(Position(13,369)), source='***')
```
or 
```
org.enso.syntax.text.Parser.ParserError: Some(Internal error in parser Could not not deserialize metadata (found 2 metadata sections))
```

## Comments:
**Hubert Plociniczak** reports a new **STANDUP** for yesterday (2023-01-25):

**Progress:** Investigation revealed that we modules sources weren't being reloaded from FS in runtime. That is why all buffers in LS were OK and why applying edits was crushing only in runtime. Draft PR ready and seems to do the job. It should be finished by 2023-01-26.

**Next Day:** Next day I will be working on the [#184324365 task](https://www.pivotaltracker.com/story/show/184324365). Figure out the proper test for the bug. Address PR reviews. (Enso Bot - Jan 26, 2023)
<hr />
**Hubert Plociniczak** reports a new **STANDUP** for today (2023-01-26):

**Progress:** Finished PR along with a decent test for it. Also spent a while trying to address reviews in various PRs. It should be finished by 2023-01-26.

**Next Day:** Next day I will be working on the [#184208157 task](https://www.pivotaltracker.com/story/show/184208157). Looks like there are some issues with initializing git on windows. (Enso Bot - Jan 26, 2023)
<hr />

**Comment by jdunkerley** [comment]
Closed by #4083.
