### ISSUE TITLE
Implement SpanTree for new AST types

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5014]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182988419).
<hr />

No description provided.

## Blockers:
[#182970096](https://www.pivotaltracker.com/story/show/#182970096) blocked

**Comment by kazcw** [comment]
Transition completed in #4113
