### ISSUE TITLE
Implement Crumbs API for new AST

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5015]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182970096).
<hr />

Implement the same "Crumb" API as the old parser, for the new parser's types.

# Notes

This will require use of Rc instead of Box in `Tree` to support structure-sharing.
This can be implemented with a derive macro, or using `reflect`.

**Comment by kazcw** [comment]
Transition completed in #4113
