### ISSUE TITLE
Engine version mismatch in YAML file causes project to fail on open

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5018]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184303109).
<hr />

On the mismatch of installed engine version with one specified in YAML file:
- we should try to open the project 
- with information logged and displayed to the user

``[error] [2023-01-24T07:35:33.718Z] [org.enso.languageserver.protocol.json.JsonConnectionController] Failed to initialize the resources. org.enso.editions.EditionResolutionError$CannotLoadEdition: Cannot load edition [2022.7.1]: The edition was not found.``

Discussions:
https://discord.com/channels/401396655599124480/1064989125314347098

https://discord.com/channels/401396655599124480/1067350451718201375

## Comments:
**Dmitry Bushev** reports a new **STANDUP** for today (2023-01-30):

**Progress:** Started working on the task. Was able to reproduce the issue. It happens because the edition in question can be found by the project-manager but cannot be loaded during the language server startup. Started to debug the logic that loads the revisions. It should be finished by 2023-02-01.

**Next Day:** Next day I will be working on the [#184303109 task](https://www.pivotaltracker.com/story/show/184303109). Continue working on the task (Enso Bot - Jan 30, 2023)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for yesterday (2023-01-31):

**Progress:** Continue working on the task. Tried to look into the issue of loading the revision but it looks like that such revision does not exist indeed. Started investigating the revision manager to see how to load the fallback. It should be finished by 2023-02-01.

**Next Day:** Next day I will be working on the [#184303109 task](https://www.pivotaltracker.com/story/show/184303109). Continue working on the task (Enso Bot - Feb 1, 2023)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2023-02-01):

**Progress:** Continue working on the task. Found that the fallback logic exists in the project manager but does not work for some reason. So far it looks like the issue is with the engine release provider. It should be finished by 2023-02-01.

**Next Day:** Next day I will be working on the [#184303109 task](https://www.pivotaltracker.com/story/show/184303109). Continue working on the task (Enso Bot - Feb 1, 2023)
<hr />
**Dmitry Bushev** reports a new **🔴 DELAY** for today (2023-02-02):

**Summary:** There is **1 day** delay in implementation of the [Engine version mismatch in YAML file causes project to fail on open (#184303109) task](https://www.pivotaltracker.com/story/show/184303109).
It **will cause 1 day delay** for the delivery of this weekly plan.

**Delay Cause:** Investigation of the issue took longer than I expected. (Enso Bot - Feb 2, 2023)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2023-02-02):

**Progress:** Continue working on the task. Added the edition override to the language server paramters that will be used to configure the execution context of the language server. Did manual testing in the Enso app. Created the PR It should be finished by 2023-02-02.

**Next Day:** Next day I will be working on the [#184303109 task](https://www.pivotaltracker.com/story/show/184303109). Continue working on the task (Enso Bot - Feb 2, 2023)
<hr />

**Comment by sylwiabr** [comment]
@4e6 @JaroslavTulach what is the status of this? I can see open PR but it looks like it is stuck. Shouldn't it be also assigned to this iteration?

**Comment by JaroslavTulach** [comment]
Yes, the PR is stuck waiting for a code approval. What is the UX we are aiming to get?

> On the mismatch of installed engine version with one specified in YAML file:
>
>   we should try to open the project
>   with information logged and displayed to the user

I believe the PR now opens the project. I don't see any code that would notify user a (potentially dangerous) switch of the engine has happened.

**Comment by sylwiabr** [comment]
We want the project to be opened and the message in the IDE (the top banner can be used) that it was opened with different version of the engine.
