### ISSUE TITLE
Fix global installation of enso-build-cli

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5021]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/184355731).
<hr />

See discussion here https://discord.com/channels/401396655599124480/1068485164621103184/1068485164621103184

## Comments:
**Michał Urbańczyk** reports a new **STANDUP** for today (2023-01-30):

**Progress:** Weekly updates. Implemented fixes for regressions caused by recent build script updates that broke global installation scenario. Made ensogl-pack not hardcode the built-time path to cargo.
Fixing issues with M1 macOS builds.
Design discussions with Wojciech. It should be finished by 2023-01-31.

**Next Day:** Next day I will be working on the [#184350589 task](https://www.pivotaltracker.com/story/show/184350589). Start refactoring build script as discussed with Wojciech: merging wasm & gui targets; consuming ensogl-app through constant path. (Enso Bot - Jan 31, 2023)
<hr />

**Comment by sylwiabr** [comment]
@mwu-tow what is the status?
