### ISSUE TITLE
Open Project dialog is empty

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5022]
This task is automatically imported from the old Task Issue Board, and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184250625).
<hr />

https://discord.com/channels/401396655599124480/1063051397655973938

Open Project dialog implementation was accidentally removed during refactoring, so we need to reimplement it from scratch. The controller's code must be recreated, while the View side should be refactored to use `grid-view` instead of the older `list-view`.

As opening a project takes considerable time, we need to show some progress indicator for the user. We also need to improve error handling and show possible errors in the status bar instead of the developer console.

## Comments:
**Ilya Bogdanov** reports a new **STANDUP** for yesterday (2023-01-31):

**Progress:** Investigated the issue, it appears the code for Open Dialog was accidentally removed a long time ago. Started implementation, and refactoring to replace list view with a new grid view component. It should be finished by 2023-02-03. (Enso Bot - Feb 1, 2023)
<hr />

**Comment by MichaelMauderer** [comment]
QA: @MichaelMauderer
