### ISSUE TITLE
Special CachedShape parameter in shape! macro

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5023]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184212663).
<hr />

## Why
**As** Enso IDE developer
**I want** to be able to add CachedShape parameter to my shape created with `shape!` macro,
**So that** I can parametrize my shape by other cached_shape.

The `CachedShape` creates a generic setter taking a marker type for a specific cached shape. The parameter of `CachedShape` type may be then returned as the shape to display <or added to another - should be simple, but is not necessary yet>. In the GLSL, the input is a vec4 describing a rectangle the shape is occupying in the global texture, and the shader just reads that fragment as SDF.

The code could look as follows:
```rust
mod icon1 {
    use super::*;
    ensogl_core::cached_shape! { 32x32
        (style: Style) {
            let shape = Circle(10.px());
            shape.into()
        }
    }
}

mod icon2 {
    use super::*;
    ensogl_core::cached_shape! { 32x32
        (style: Style) {
            let shape = Rectangle(10.px());
            shape.into()
        }
    }
}

mod icon {
    use super::*;
    ensogl_core::shape!
        (
            style: Style, 
            shape: CachedShape,
            color: Vector4
        ) {
            shape.into()
        }
    }
}
```

## Acceptance Criteria
```gherkin
Scenario: 
GIVEN I have a debug scene with two cached shapes and one shape displaying CachedShape taken as parameter, and two instances of the latter parameterized by the former.
WHEN I open it
THEN I see two cached shapes displayed.
```

## Blockers:
[#184212594](https://www.pivotaltracker.com/story/show/#184212594) blocked

## Comments:
**Adam Obuchowicz** reports a new **STANDUP** for yesterday (2023-01-31):

**Progress:** Developed a special registry for cached shapes data, so everyone would know where on the texture is given shape. It should be finished by 2023-02-08.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/184212663). Continue developing, refactor the code a bit to fill the results of shape arrangement in the registry. (Enso Bot - Feb 1, 2023)
<hr />
**Adam Obuchowicz** reports a new **STANDUP** for today (2023-02-01):

**Progress:** Little progress, as I played with pivotal and discuss other topics. Started refactoring of the registry and shape arrangement algorithm. It should be finished by 2023-02-08.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/184212663). Finish refactoring, so I could move to making parameter and its glsl code. (Enso Bot - Feb 1, 2023)
<hr />
**Adam Obuchowicz** reports a new **STANDUP** for yesterday (2023-02-02):

**Progress:** Dived into the shapes/shaders code. I think I understood how the things work. Implemented the "prototype" API for parametrizing shapes by cached shapes. It should be finished by 2023-02-08.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/184212663). Try to display cached shapes in the debug scene. (Enso Bot - Feb 3, 2023)
<hr />
**Adam Obuchowicz** reports a new **STANDUP** for today (2023-02-03):

**Progress:** Display the cached shapes in the debug scene. Spent some time in fixing shader compiler errors. The shapes are displayed, but have artifacts. It should be finished by 2023-02-08.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/184212663). Fix all issues (Enso Bot - Feb 3, 2023)
<hr />

**Comment by galin-enso** [comment]
QA: @galin-enso
