### ISSUE TITLE
UnsatisfiedLinkError: libenso_parser.so: /lib64/libc.so.6: version `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5025]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184350069).
<hr />

Final exception in the log is:
```
Jan 30 11:36:08 i enso_runtime[3853]: [warn] [2023-01-30T11:36:08.708Z] [enso] Execution of function main failed (Module local.Main.Main not found.).
Jan 30 11:36:08 i enso_runtime[3853]: org.enso.interpreter.service.error.ModuleNotFoundException: Some(Module local.Main.Main not found.)
Jan 30 11:36:08 i enso_runtime[3853]:   at org.enso.interpreter.service.ExecutionService.lambda$execute$2(ExecutionService.java:214)
Jan 30 11:36:08 i enso_runtime[3853]:   at java.base/java.util.Optional.orElseThrow(Optional.java:408)
Jan 30 11:36:08 i enso_runtime[3853]:   at org.enso.interpreter.service.ExecutionService.execute(ExecutionService.java:214)
Jan 30 11:36:08 i enso_runtime[3853]:   at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.executeProgram(ProgramExecutionSupport.scala:133)
Jan 30 11:36:08 i enso_runtime[3853]:   at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$3(ProgramExecutionSupport.scala:243)
Jan 30 11:36:08 i enso_runtime[3853]:   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
Jan 30 11:36:08 i enso_runtime[3853]:   at cats.syntax.EitherObjectOps$.catchNonFatal$extension(either.scala:391)
Jan 30 11:36:08 i enso_runtime[3853]:   at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.$anonfun$runProgram$2(ProgramExecutionSupport.scala:243)
Jan 30 11:36:08 i enso_runtime[3853]:   at scala.util.Either.flatMap(Either.scala:352)
Jan 30 11:36:08 i enso_runtime[3853]:   at org.enso.interpreter.instrument.job.ProgramExecutionSupport$.runProgram(ProgramExecutionSupport.scala:237)
Jan 30 11:36:12 i enso_runtime[3853]: [info] [2023-01-30T11:36:12.794Z] [org.enso.languageserver.protocol.binary.BinaryConnectionController] Connection closed [...].
```
but the real problem is likely caused by a `LinkageError` which leads to disabling the new parser and enabling the (incapable) old one:
```
Caused by: java.lang.UnsatisfiedLinkError: /opt/enso/component/libenso_parser.so: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/enso/component/libenso_parser.so)
```
something must have changed in the Rust/LibC execution environment. Either Rust requires newer version of LibC now which the docker image doesn't provide. Or there was an upgrade in LibC version and Rust isn't happy with it.

## Comments:
We (me and @PawelBuchowski) got [debugging of Enso engine](https://discord.com/channels/401396655599124480/1069837261568495688) in the cloud working. (jaroslavtulach - Jan 31, 2023)
<hr />
While debugging I noticed following error:
```
Caused by: java.lang.UnsatisfiedLinkError: /opt/enso/component/libenso_parser.so: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by /opt/enso/component/libenso_parser.so)
```
as a result of out inability to load Rust based parser, the old Scala based one is used. Probably it is no longer good enough parser. We have to make sure the Rust based parser gets loaded.
 (jaroslavtulach - Jan 31, 2023)
<hr />
	**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2023-01-31):

**Progress:** - helping cloud
- got debugging working to the Enso in cloud
- able to debug lib/scala projects: https://github.com/enso-org/enso/pull/4098/commits/b897bfca658610e8cd9d1bd54420ef37217ce368
- it was a linkage error: https://www.pivotaltracker.com/story/show/184350069/comments/235309699
- investigating jgit: https://www.pivotaltracker.com/story/show/184350020/comments/235310985
- review LocalDate.now vs. Date.now with Pavel: https://www.pivotaltracker.com/n/projects/2539304/stories/184336928
- Fixing context closing: https://www.pivotaltracker.com/story/show/184347367
- Talking to GraalVM guys about Espresso: https://graalvm.slack.com/archives/CPSD12R71/p1675171823673009?thread_ts=1675171736.618429&cid=CPSD12R71
- Meeting James It should be finished by 2023-01-31.

**Next Day:** Fixing context closing (Enso Bot - Feb 1, 2023)
<hr />
**Michał Urbańczyk** reports a new **🔴 DELAY** for today (2023-02-01):

**Summary:** There is **1 day** delay in implementation of the [UnsatisfiedLinkError: libenso_parser.so: /lib64/libc.so.6: version `GLIBC_2.25' not found (#184350069) task](https://www.pivotaltracker.com/story/show/184350069).
It **will cause 1 day delay** for the delivery of this weekly plan.

**Delay Cause:** No reason. (Enso Bot - Feb 1, 2023)
<hr />
**Michał Urbańczyk** reports a new **STANDUP** for yesterday (2023-01-31):

**Progress:** * debugging macOS build failures (developer id renewal)
* investigating parser's glibc issue;
* discussing with Pawel how to fix cloud releases. It should be finished by 2023-02-01.

**Next Day:** Next day I will be working on the [#184350069 task](https://www.pivotaltracker.com/story/show/184350069). Follow up with cloud frontend upload updates. Make trial release and confirm that it is working. (Enso Bot - Feb 1, 2023)
<hr />
**Michał Urbańczyk** reports a new **STANDUP** for yesterday (2023-02-01):

**Progress:** Fixed the issues with cloud backend image. Updated GUI release file structure. Made a new test release to confirm that it is working as expected. It should be finished by 2023-02-01.

**Next Day:** Next day I will be working on the [#184381521 task](https://www.pivotaltracker.com/story/show/184381521). ... (Enso Bot - Feb 3, 2023)
<hr />

**Comment by sylwiabr** [comment]
@mwu-tow what is the status?

**Comment by mwu-tow** [comment]
@sylwiabr It is done.
