### ISSUE TITLE
Investigate startup performance of LS+engine

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5027]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/184369994).
<hr />

[The engine startup is extremely slow](https://discord.com/channels/401396655599124480/1070181785226453022).

We need to investigate it:
```
project-manager --profiling-events-log-path=start.log --profiling-path=start.npss --profiling-time=20
```
try some experiments, remeasure and schedule a plan of further actions.

## Blockers:
[#184370589](https://www.pivotaltracker.com/story/show/#184370589) blocked

## Comments:
These two files contain one recorded startup of the engine. They were generated using the [PR-4110](https://github.com/enso-org/enso/pull/4110) logging support. To analyze what is happening during the start, download both files, put them next to each other and open the `.npss` file in VisualVM. (jaroslavtulach - Feb 1, 2023)
<hr />
1164ms of 17s wasted in `org.enso.languageserver.search.SuggestionsHandler.org$enso$languageserver$search$SuggestionsHandler$$generateDocumentation` (jaroslavtulach - Feb 1, 2023)
<hr />
`org.enso.compiler.Compiler.runImportsAndExportsResolution`  takes 3s - also because of slow `SerializationManager.deserialize`. (jaroslavtulach - Feb 1, 2023)
<hr />
1.5s initializing the language context including 600ms in initialization of `PackageManager`:

 (jaroslavtulach - Feb 1, 2023)
<hr />
	**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2023-02-02):

**Progress:** - measuring suggestions
- proposing benchmark: https://discord.com/channels/401396655599124480/1070399718649237514/1070708726757064714
- measuring: `generateDocumentation`: https://www.pivotaltracker.com/story/show/184117587/comments/235359646
- book club - issues with API incompatibilities, `filter` vs. `filter_by_expression`, https://discord.com/channels/401396655599124480/1068485595984318504/1070667696502476810
- review of type-node: https://github.com/enso-org/enso/pull/- catching up with discord It should be finished by 2023-02-06.

**Next Day:** Analyzing performance (Enso Bot - Feb 3, 2023)
<hr />
	**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2023-02-03):

**Progress:** - caching suggestions
- raw impl for review: https://github.com/enso-org/enso/commit/8fd217d203d28d68ac8eca137204afc1f8913987
- caching Suggestions per set of modules, doesn't work: https://github.com/enso-org/enso/commit/28064eec7a71949a09c27676a5d8e874d7daab26
- review and idea: https://github.com/enso-org/enso/pull/4116 It should be finished by 2023-02-06.

**Next Day:** Analyzing performance (Enso Bot - Feb 4, 2023)
<hr />
	**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2023-02-04):

**Progress:** - Pre-compute suggestion db prototype & plan: https://www.pivotaltracker.com/n/projects/2539304/stories/184350816
- fixing XML startup logging: https://github.com/enso-org/enso/pull/4110
- documentation: https://github.com/enso-org/enso/blob/27fcd06c600898f356c1ac555051f735dc91453c/docs/profiler/engine-startup.md
- reviews It should be finished by 2023-02-06.

**Next Day:** Prepare presentation about analyzing performance (Enso Bot - Feb 5, 2023)
<hr />

**Comment by JaroslavTulach** [comment]
The [Startup investigation by Feb 6](https://docs.google.com/document/d/1-jG7HQoPY7KASG8NZ1PUDzqqd5ZL7wMzVSSMCcNFWMI/) has been finished. Time to report individual issues:
- #5068 
- #5567
- #5568

Low priority tasks:
- #5569
- #5570

**Comment by JaroslavTulach** [comment]
Results of [startup improvements as of Mar 9](https://docs.google.com/document/d/1-jG7HQoPY7KASG8NZ1PUDzqqd5ZL7wMzVSSMCcNFWMI) are promising. After integration of #5068 as well as #5568 and #5791 we managed to speed startup (according to our methodology - #5569) from **11s** to **8s**. Great work!
