### ISSUE TITLE
With Nightly 2023.1.1-nightly.2023.2.1 the Restaurant example is not working

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5028]
This task is automatically imported from the old Task Issue Board and it was originally created by Sylwia Brodacka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184369225).
<hr />

There is a warning about EOF and no results shows

## Comments:
 (Sylwia Brodacka - Feb 1, 2023)
<hr />
Caused by new API changes. (James Dunkerley - Feb 1, 2023)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2023-02-01):

**Progress:** Repaired all examples except NASDAQReturns (will examine issue in the morning). Attempting to get video recording for PreppinData blog post. Backlog sorting. It should be finished by 2023-02-02.

**Next Day:** Next day I will be working on the [#184369225 task](https://www.pivotaltracker.com/story/show/184369225). Resolve issue with NASDAQReturns. Demo. More Backlog and then onto DB/InMemory differences. (Enso Bot - Feb 1, 2023)
<hr />
**James Dunkerley** reports a new **STANDUP** for today (2023-02-02):

**Progress:** Fixed the NASDAQReturns. Design session and planning on the dropdowns with Pawel - agreed plan on what to do next. More work on the tickets on Pivotal. It should be finished by 2023-02-02.

**Next Day:** Next day I will be working on the [#184369225 task](https://www.pivotaltracker.com/story/show/184369225). Blog post, interview,  finish the pivotal ticket tidy. (Enso Bot - Feb 2, 2023)
<hr />

**Comment by jdunkerley** [comment]
Commits:
- https://github.com/enso-org/project-templates/commit/16b49c44a5053e426630513a7d9181c3ae6affe3
- https://github.com/enso-org/project-templates/commit/3cfcbe18ef77395e368477dd4f102a58d0e73424
