### ISSUE TITLE
Implement alias analysis for new AST

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5029]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182973659).
<hr />

Implement the alias-analysis API found in `double-representation` for the new AST types.

## Comments:
(Logic needs to be reevaluated) (Keziah Wesley - Aug 12, 2022)
<hr />

**Comment by kazcw** [comment]
Transition completed in #4113
