### ISSUE TITLE
Implement Node API for new AST

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5030]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182974161).
<hr />

Implement the `double_representation` Node API for the new types.

# Notes

The `NodeLocation` types and logic will be affected by the UTF-16 work in the parser.

## Blockers:
[#182807114](https://www.pivotaltracker.com/story/show/#182807114) blocked

**Comment by kazcw** [comment]
Transition completed in #4113
