### ISSUE TITLE
Table Vis is not the default visualization for Tables

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5033]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/184267396).
<hr />

### Steps to reproduce
1. Newly create a node that has type “Table” or "Vector"
2. Open the visualization.

### Expected
The visualization opened should be a table visualization. 

### Actual
The visualization shown is a text visualization.

**Comment by xvcgreg** [comment]
https://user-images.githubusercontent.com/108271897/216966922-b2ed14e4-e34b-49aa-863f-9fab551d0628.mp4

**Comment by MichaelMauderer** [comment]
https://github.com/enso-org/enso/pull/4120
