### ISSUE TITLE
Unify wasm and gui build script targets

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5035]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/184381521).
<hr />

With shader precompilation they are now too closely intertwined.

## Comments:
**Michał Urbańczyk** reports a new **STANDUP** for today (2023-02-02):

**Progress:** Landed pending PRs. Wasted quite a while because of GitHub's breakage and the way it corrupted the CI runners.
Started refactoring the build script to have new, unified gui target. Thinking about supporting electron reloads and ide-watch. It should be finished by 2023-02-06.

**Next Day:** Next day I will be working on the [#184381521 task](https://www.pivotaltracker.com/story/show/184381521). Continue. (Enso Bot - Feb 3, 2023)
<hr />

**Comment by mwu-tow** [comment]
No longer relevant, as the `wasm` target was removed.
