### ISSUE TITLE
Speed start up by deferring post-startup ls/engine actions 

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5040]
#### Overview

Services that are being currently initialized can be divided into two categories:
- **required startup** to bring the necessary services up and running
- **post-startup** actions that could be started with low-level priority and **warm up** our engine

#### Motivation

- https://github.com/enso-org/enso/pull/4116#pullrequestreview-1282336101 - **100ms** JGit initialization can wait until first user edit
- #5068 - **1s** - delivering suggestion DB isn't necessary for computing visualizations

#### Goal

Investigate how and if we can divide some of our existing services to provide a good compromise between accessibility of services and their performance. Mitigate at least **1s** spend in `SqlSuggestionRepo` initialization:

![1074ms in SqlSuggestionRepo](https://user-images.githubusercontent.com/26887752/224230756-58d7db08-685c-4c7a-be23-7c42108d5998.png)
 

#### Design

Let's introduce new Akka internal message - `WarmUp`. All actors that are interested in performing _post-startup_ actions shall register for that message in Akka bus and start their initialization when it is delivered. Their initialization may be triggered in response to other events - the `WarmUp` message is there to let everyone know: _Hey, all the important work is done, you have time to pre-initialize!_

The language-server detects (possibly in cooperation with the IDE) when the _essential part of startup_ is done and emits the `WarmUp` message then.

#### References

- Original issue was [reported by Hubert](https://www.pivotaltracker.com/story/show/184388932).
- NetBeans offered following set of [annotations to accommodate different initialization](https://github.com/enso-org/enso/pull/4116#pullrequestreview-1282336101) needs:
    - `@OnStart` - https://bits.netbeans.org/16/javadoc/org-openide-modules/org/openide/modules/OnStart.html
    - `@OnShowing` - https://bits.netbeans.org/16/javadoc/org-openide-windows/org/openide/windows/OnShowing.html
    - `@OnStop` - https://bits.netbeans.org/16/javadoc/org-openide-modules/org/openide/modules/OnStop.html

**Comment by 4e6** [comment]
The work for delaying post-startup actions was done in #5970 #5990 and #5997
