### ISSUE TITLE
Replace JGit with plain git calls

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5041]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184387703).
<hr />

**Motivation**
After the initial implementation of `vcs` operations in language-server it became apparent that the performance of JGit is suboptimal. A number of improvements have been added bringing git repo setup to 300-400 ms. 
Regular operations (such as `commit` or `setup`) are withing the acceptable range (<10ms).
Performance of JGit appears to be suboptimal due to the upfront cost of JGIt setup which does a lot of FS calls and config reads, which is not necessary for our use-cases. Attempts to replace parts of JGit with our own implementation failed due to rather inflexible architecture.

A quick and dirty replacement of jgit with `git` calls for vcs setup in our implementation was measured around ~30ms, a result unreachable with JGit.

**Acceptance criteria**
1-to-1 straightforward replacement of the existing JGit calls with plain `git <cmd>` calls and parsing of the results.
Special care has to be given to Windows paths, which JGit handled for us transparently.

## Blockers:
[#184387653](https://www.pivotaltracker.com/story/show/#184387653) blocked

**Comment by hubertp** [comment]
No longer relevant. We had no issues after a few initial hiccupts
