### ISSUE TITLE
Design for typechecker prototype

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5044]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/181986955).
<hr />

Before we start implementing a typechecker prototype it makes sense to write some high-level design of what we expect of the first iteration of the prototype.

This task consists of preparing and discussing such a design.

## Comments:
**Radosław Waśko** reports a new **STANDUP** for the provided date (2022-04-22):

**Progress:** Read through the Extended Static Checking paper, skimmed through other related papers, thought how to relate these to our needs, formulated some questions to clarify together what is our vision for the prototype. (The end date is a bit random - depends on how many iterations we'll need to converge on a design) It should be finished by 2022-05-13.

**Next Day:** Next day I will be working on the [##181266184 task](https://www.pivotaltracker.com/story/show/181266184). Fix problematic edge cases, get the PR reviewed; prepare some screenshots for the demo and start a next task. (Enso Bot - Apr 25, 2022)
<hr />
**Radosław Waśko** reports a new **STANDUP** for today (2022-04-29):

**Progress:** Reading through the OutsideIn and NBE Tutorial, some thoughts on how to best start the prototype that are independent of the pending decisions (in particular, looking at the new Java 17 features and how they can help use it instead of Scala for the prototype, as asked). Some fixes to get the Delimited parser merged. It should be finished by 2022-05-13.

**Next Day:** Next day I will be working on the [##181998375 task](https://www.pivotaltracker.com/story/show/181998375). Implement custom encodings for Delimited file reading. (Enso Bot - Apr 29, 2022)
<hr />

**Comment by jdunkerley** [comment]
Well out of date.
