### ISSUE TITLE
"Internal" methods are displayed in the Component Browser

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5048]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/184380173).
<hr />

Currently, methods like `to_default_visualization_data` or `to_lazy_visualization_data` or `default_visualization` are displayed in the component browser.

These are mostly "internal" methods used to support our visualization logic. I don't think they should be displayed in the Component Browser, as they are not really meant to be used by the users and they can mostly just cause unnecessary noise/confusion.

I'm not sure if they should be marked as PRIVATE as this label is usually used to mark internal implementation details. It could fit these methods, but it may be better to create another flag like HIDDEN which would hide these methods from CB but have a different meaning from PRIVATE.

## Comments:
To agree a new set of tags and review what is using each tag. Post release. (James Dunkerley - Feb 2, 2023)
<hr />
Keeping this as libs-only issue for now. Once the new set of tags is agreed, will need follow up tickets on LS and GUI.  (Hubert Plociniczak - Feb 3, 2023)
<hr />

**Comment by jdunkerley** [comment]
This has been cleaned up a lot already so closing.
