### ISSUE TITLE
Add support for polyglot values in conversion methods

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5049]
This task is automatically imported from the old Task Issue Board and it was originally created by Pavel Marek.
Original issue is [here](https://www.pivotaltracker.com/story/show/184380208).
<hr />

For standard method dispatch, we treat some polyglot interop objects as their Enso equivalents. We should do the same for conversion methods. More specifically:
```
polyglot java import java.time.LocalDate as Java_Date

type Comparable
type Date_Comparator

Comparable.from (_:Date) = Date_Comparator

main =
    date = Java_Date.now
    comp = Comparable.from date
    comp == Date_Comparator
```
Should return `True`, since `date.is_a Date == True`.

## Tasks:
- [x] Remove the workaround from `Any.assert_ordered_comparators` introduced in https://github.com/enso-org/enso/pull/4067

## Comments:
This blocks #184380208, because without fixing this story first, `date1 == date2`, where both `date1` and `date2` are polyglot dates, won't work. I have found no other reasonable workaround. (Pavel Marek - Feb 2, 2023)
<hr />

**Comment by Akirathan** [comment]
Closed by #4067. Added some functionality in #5623
