### ISSUE TITLE
File Upload progress indicator shows a Compile Error and never changes the node from 'in-progress' to 'complete' for large files

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5051]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/184380082).
<hr />

I was testing drag and drop and it seems to sometimes work and sometimes not.

The biggest issue is - when I drop a file onto the stage, there is no immediate feedback that it has been accepted. So if nothing is happening for a while, i do not know if it is uploading and I should just wait or if something just failed.

I tried dragging and dropping multiple files. Small ones (<15KB) work most of the time. With bigger ones, it was a bit random. Usually the first try did nothing at all. After some retries, they do upload fine. But sometimes there are weird artifacts (see screeenshot) where there appears a `File_Uploading` node that is an unresolved reference. 

The biggest issue is lack of progress indicator so I'm not sure if the upload is taking place or if it was discarded for unknown reasons.

## Comments:
 (Radosław Waśko - Feb 2, 2023)
<hr />

**Comment by farmaazon** [comment]
The progress will be a separate feature task. This issue will be about failing upload only.

**Comment by vitvakatu** [comment]
Estimated as 1 for initial investigation

**Comment by farmaazon** [comment]
I cannot reproduce the failure. @radeusgd do you reproduce it still on the newest develop or today's nightly?

**Comment by radeusgd** [comment]
So the `File_Uploading` now appears consistently. That's good.

But there are still issues:
<img width="530" alt="image" src="https://github.com/enso-org/enso/assets/1436948/c2b31425-0f35-491a-96ca-9f9288a3032c">

If I upload a bigger file, such that the wait time is more significant, I can see that the temporary node that is created yields a compile error. That is not what is supposed to happen. Apparently, the module is now `File_Upload` but IDE inserts `File_Uploading` - we should fix the path.

Files around 20MB took some time but worked fine.

For large files (I tried an Ubuntu ISO, 4.8GB), the upload took a very long time (uploading 2 copies took more than 7 minutes on my laptop, whereas copying them in Explorer took me about 7 **seconds**). So the upload speed, even on a local connection is very slow - I think we should improve it at some point.

But regardless of that, there is a bigger issue. It seems like the upload is "timing out"?

When I uploaded the Ubuntu ISO, it took these ~7 minutes. I could track the file upload by looking at the size of the destination file in Explorer - I knew the upload has finished when it has stopped growing. So even when the file stopped growing, the node `File_Uploading.file_uploading ...` has stayed like it is in the IDE. Normally, for smaller files, once upload finishes, the node is transformed into `enso_project.data "..." . read`. But here, if the upload took more time (not sure what the cutoff is, 4+GB worked for my case), the node stays  in the 'in progress' state forever.
I can still upload small files afterwards and they will show up fine, but the large one that took so long to upload, just never updates. I assume something somewhere times out??

**Comment by radeusgd** [comment]
I updated the issue name to reflect the state of the latest repro.

**Comment by farmaazon** [comment]
> For large files (I tried an Ubuntu ISO, 4.8GB), the upload took a very long time (uploading 2 copies took more than 7 minutes on my laptop, whereas copying them in Explorer took me about 7 seconds). So the upload speed, even on a local connection is very slow - I think we should improve it at some point.

I'm afraid the web API could be a bottleneck. But there was a request of putting a file instead of uploading on local environment: #6263 

> When I uploaded the Ubuntu ISO, it took these ~7 minutes. I could track the file upload by looking at the size of the destination file in Explorer - I knew the upload has finished when it has stopped growing. So even when the file stopped growing, the node File_Uploading.file_uploading ... has stayed like it is in the IDE. Normally, for smaller files, once upload finishes, the node is transformed into enso_project.data "..." . read. But here, if the upload took more time (not sure what the cutoff is, 4+GB worked for my case), the node stays in the 'in progress' state forever.
I can still upload small files afterwards and they will show up fine, but the large one that took so long to upload, just never updates. I assume something somewhere times out??

I reproduced it by uploading the Enso AppImage (~1.4 GB). The problem is that the final check of checksum fails with:

```
{"jsonrpc":"2.0","id":701,"error":{"code":1,"message":"Service error"}}
```

In the console log (from Language Server):
```
 INFO ide_ci::program::command: npm⚠️ [error] [2023-05-15T08:31:17.59Z] [org.enso.languageserver.requesthandler.file.ChecksumFileHandler] Failure during [ChecksumFile] operation: ***
```
I admit it's a bit enigmatic.

So I will create the PR fixing the node expression, but I'll create an issue for the Language Server with above information.

**Comment by farmaazon** [comment]
Created PR: #6689 and issue for the Engine: https://github.com/enso-org/enso/issues/6691
