### ISSUE TITLE
Documentation panel does not preserve layout from textual docs

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5053]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/184379993).
<hr />

In the text docs we have multiple 'levels' of nesting, for example we have a _list_ of arguments in the `Arguments:` section, and one of these arguments may also present another list.

The docpanel displays all methods of a type as a list, so overall we can have up to 3 levels of nesting, but all of these are displayed 'flat' in the panel, so that it is hard to distinguish between consecutive points on a list of method's arguments vs list of methods themselves. The methods are highlighted as blue, but still because the list is not indented it is very hard to see when one ends and another begins.

See screenshot.

## Comments:
The relevant doc code is:
```
    ## Joins two tables according to the specified join conditions.

       Arguments:
       - right: The table to join with.
       - join_kind: The `Join_Kind` for the joining the two tables.
       - on: A single condition or a common column name, or a list thereof, on
         which to correlate rows from the two tables. If multiple conditions
         are supplied, rows are correlated only if all are true.
         If common column names are provided, these columns should be present
         in both tables and an equality condition is added for each of them.
       - right_prefix: The prefix added to right table column names in case of
         name conflict.
       - on_problems: Specifies how to handle problems if they occur, reporting
         them as warnings by default.

         - If a column name cannot be found, a `No_Such_Column` is reported
           and an empty result is reported.
         - If a column index is invalid, an `Index_Out_Of_Bounds` is
           reported and an empty result is reported.
         - If there are column names that are clashing between the two tables, a
           `Duplicate_Output_Column_Names` is reported and the columns from the
           table are renamed as described below.
         - If a join condition correlates columns whose types are not compatible
           (for example comparing numeric types with text), an
           `Invalid_Value_Type` is reported.
         - If decimal columns are joined on equality, a
           `Floating_Point_Grouping` is reported.
```

There we can see that the list of problems is a sublist of the `on_problems` argument. In the doc panel in GUI it is not apparent at all. (Radosław Waśko - Feb 2, 2023)
<hr />

**Comment by farmaazon** [comment]
Fixed in GUI2
