### ISSUE TITLE
Doc panel not showing _some_ examples

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5054]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/184379971).
<hr />

Create a Table and open component browser on it, type `take` and open the doc panel for this method (see screenshots in the comments).

The code for this method has 2 examples.

The first one is displayed correctly.

For the second one, only the caption is visible, but the code is not.

## Comments:
```
    ## Creates a new Table with the specified range of rows from the input
       Table.

       Arguments:
       - range: The selection of rows from the table to return.

       For the purposes of the `Index_Sub_Range.While` predicate a single
       "element" of the table is represented by the `Row` type.

       > Example
         Take first 10 rows of the table.

             table.take (First 10)

       > Example
         Take rows from the top of the table as long as their values sum to 10.

             table.take (While row-> row.to_vector.compute Statistic.Sum == 10)
    take : (Index_Sub_Range | Range | Integer) -> Table
``` (Radosław Waśko - Feb 2, 2023)
<hr />

**Comment by sylwiabr** [comment]
Can not reproduce it with the package from 20.04.2023
