### ISSUE TITLE
Dropdown for Table.join right is wrong

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5055]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/184379354).
<hr />

Discovered during [book clubing](https://discord.com/channels/401396655599124480/1065951201860001792/1068417429891469363).

There is a drop down for `Table.join` `right` argument! And it offers `Table.Value`. `Table.Value` is just a function which needs a parameter of `java_table`, so it makes no sense to offer it as `tag_value`.

## Comments:
 (jaroslavtulach - Feb 2, 2023)
<hr />

**Comment by jdunkerley** [comment]
Please let us know how to determine what ends up in `tagValues` and the logic we need to control this.

**Comment by JaroslavTulach** [comment]
To determine what ends up in `tagValues` one needs to put breakpoint to [buildResolvedUnionTypeName](https://github.com/enso-org/enso/blob/bf9508603ff3926c3ba0d13475338fd2e1c4e8c0/engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala#L387). Or better have three breakpoints:
```diff
enso$ git diff engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
diff --git a/engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala b/engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
index b2161b2d3..23d9789da 100644
--- a/engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
+++ b/engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala
@@ -106,6 +106,9 @@ final class SuggestionBuilder[A: IndexedSource](
                   _
                 ) if !m.isStaticWrapperForInstanceMethod =>
             val typeSignature = ir.getMetadata(TypeSignatures)
+            if (methodName.toString().contains("join")) {
+                System.out.println("Found method " + methodName)
+            }
             val (selfTypeOpt, isStatic) = typePtr match {
               case Some(typePtr) =>
                 val selfType = typePtr
@@ -200,6 +203,9 @@ final class SuggestionBuilder[A: IndexedSource](
     }
 
     val builder: TreeBuilder = Vector.newBuilder
+    if (module.toString().endsWith("Table")) {
+      System.err.println("Processing " + module)
+    }
     builder += Tree.Node(
       buildModule(
         module,
```
and stop when one is processing `Standard.Table.Data.Table` module and `join` method. Then stop in the [buildResolvedUnionTypeName](https://github.com/enso-org/enso/blob/bf9508603ff3926c3ba0d13475338fd2e1c4e8c0/engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala#L387).

Doing that one finds out there is [Value java_table](https://github.com/enso-org/enso/blob/1bc27501e6c8a6018e4c17e68ef4cb4068db15f9/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso#L118) which is seen as:
```js
BindingsMap$Type
  name = "Table" 
  members = [ BindingsMap$Cons name="Value" arity = 1 allFieldsDefaulted=false ]
```
e.g. offering `Table.Value` is as good as offering [Filter_Condition.Equal](https://github.com/enso-org/enso/blob/ccdfaca584a77f6c9bb0fd79c75654049b9913ec/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso#L27) which is what #5656 [wants to offer](https://user-images.githubusercontent.com/919491/218737379-b53ff125-3910-48f3-bb9f-a0e7b1684ab9.png). Alas they aren't really distinguishable from the perspective of the `SuggestionBuilder`.

Ideas @jdunkerley, @Frizi & co.?

**Comment by hubertp** [comment]
@jdunkerley Here are is a clue from Dmitry that I once got on debugging suggestions:


If you want to observe the database, the easiest way is to create a file-based one instead of in-memory https://github.com/enso-org/enso/blob/c4c35c92b7e2b53f5e4571af0e89a56eac8e7120/engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala#L117 with
`val sqlDatabase = SqlDatabase(languageServerConfig.directories.suggestionsDatabaseFile)`
and then use CLI 
`$ sqlite3 /path/to/suggestions.db`

**Comment by JaroslavTulach** [comment]
> offering `Table.Value` is as good as offering [Filter_Condition.Equal](https://github.com/enso-org/enso/blob/ccdfaca584a77f6c9bb0fd79c75654049b9913ec/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Filter_Condition.enso#L27) which is what #5656 [wants to offer](https://user-images.githubusercontent.com/919491/218737379-b53ff125-3910-48f3-bb9f-a0e7b1684ab9.png). Alas they aren't really distinguishable from the perspective of the `SuggestionBuilder`.

@jdunkerley proposes to ignore `tagValues` with a single entry in `SuggestionBuilder`. Let's do it!
