### ISSUE TITLE
Adding easy way to share projects with a single file

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5057]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184370467).
<hr />

As a user I want to be able to open Enso projects from a single file that I can easily share with others.

After double-click on the received file it should unpack to the Enso projects folder and open in Enso.

The suggestion is an `ensa` file type. This would just be a zip file containing the `src`, `data` and `project.yaml`. 

There is no requirement on this ticket for IDE to write these (just consume), this is to allow us to post blogs and demos with sample projects.

**Comment by sylwiabr** [comment]
1. After double-clicking on .enso file project should open in the application
2. Option to zip the project (whole folder) to file .enso-project
3. After double-clicking on .enso-project it should be unzipped to the right folder and be run in the application

**Comment by wdanilo** [comment]
`Root prilileges are required to install;` This is so stupid :(

**Comment by sylwiabr** [comment]
@mwu-tow ping me when you will have packages ready to be tested on MacOS - happy to do it

**Comment by mwu-tow** [comment]
@sylwiabr You can give this a try: https://github.com/enso-org/enso/actions/runs/4521196938?pr=6077

See the PR description for details.

<blockquote><img src="https://opengraph.githubassets.com/17ac6cd93f98824002284db9dbaa588440ee48bd3e33861411439ef300bacfff/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Project Sharing · enso-org/enso@b85c949</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
