### ISSUE TITLE
Edits to metadata section trigger a full compilation

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5059]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184369622).
<hr />

## Why

**As** language server
**I want** to trigger compilations only on when the source code actually changes, rather than on every modification of the graph layout
**So that** I have better performance

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN enso program in GUI
WHEN modify the graph layout
THEN language server should not trigger a compilation in engine but the modification to metadata section should still be recorded.
```

## Notes
This is an IDE ticket because API of `text/applyEdit` provides an optional parameter `execute` to indicate if the compilation should be triggered. `execute : false` should be set on every **metadata** edit. Currently it appears that IDE does not set that field at all, meaning that we always trigger a compilation.

## Comments:
Issue already describes that this should go to someone from GUI who know the controller part. For now, this should go to @farmaazon for further assignment.  (Michael Mauderer - Feb 1, 2023)
<hr />

**Comment by farmaazon** [comment]
Seems to be fixed.
