### ISSUE TITLE
Cannot scroll down below value 1.0 in scatter plot visualization

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5060]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184369088).
<hr />

https://discord.com/channels/401396655599124480/1067010192849522688

**Comment by sylwiabr** [comment]
Our visualizations needs revisiting. Closing for now as on the video it was a histogram and I can't repro the issue anymore
