### ISSUE TITLE
Visualization for Map shows nothing.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5061]
This task is automatically imported from the old Task Issue Board and it was originally created by Pavel Marek.
Original issue is [here](https://www.pivotaltracker.com/story/show/184280631).
<hr />

Implement visualization for `Standard.Base.Data.Map`. It does not show anything - see https://discord.com/channels/401396655599124480/1066025620393435216/1066025620393435216 . The default visualization should probably be JSON. After https://github.com/enso-org/enso/pull/3878 was merged, `Map` is a builtin type

## Blockers:
[#184061302](https://www.pivotaltracker.com/story/show/#184061302) blocked

## Comments:
	will be solved with PR for this issue: https://www.pivotaltracker.com/story/show/184061302
@pmarek  (Greg Ociepka - Jan 25, 2023)
<hr />
Update: Previous task is just touching the same location in code that needs to be fixed for the map viz. Propper fix will land with this PR: https://github.com/enso-org/enso/pull/4067
 (Greg Ociepka - Jan 27, 2023)
<hr />

**Comment by Akirathan** [comment]
I have tried the following diff in one of my branches, and the visualization of maps seems to work:
```diff
diff --git a/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso b/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
index a6ada90b6..4238dbaaa 100644
--- a/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
+++ b/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Map.enso
@@ -1,3 +1,4 @@
+import project.Data.Json.Json
 import project.Data.Numbers.Integer
 import project.Data.Vector.Vector
 import project.Data.Pair.Pair
@@ -354,6 +355,9 @@ type Map key value
     to_text : Text
     to_text self = @Builtin_Method "Map.to_text"
 
+    to_json : Json
+    to_json self = Json.from_pairs self.to_vector
+
     ## PRIVATE
     get_builtin : Any -> Any -> Any
     get_builtin self key ~if_missing = @Builtin_Method "Map.get_builtin"
```

This should be enough. Also, performance should be OK, since `to_vector` method on a `Map` caches its result.

**Comment by jdunkerley** [comment]
Thanks @Akirathan - exactly what I was going to use. Will do a slight additional step of setting up so default viz is a table.
