### ISSUE TITLE
Screenshots on Mac can break application input

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5063]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/184369591).
<hr />

When doing screenshots with Cmd+Shift+4 (default Mac tool) you can see the standard system mouse cursor appearing. Moreover, keyboard input stops working after that – any key presses do not result in anything. Restarting the application helps.

## Comments:
Probably an Electron issue or something else related to input processing. Definitely GUI side. (Michael Mauderer - Feb 1, 2023)
<hr />

**Comment by sylwiabr** [comment]
Not longer an issue on Mac with new GUI
