### ISSUE TITLE
Enabling zooming in should be a different shortcut than debug mode.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5064]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184369484).
<hr />

## Why

**As** someone doing the demos for clients
**I want** to show zooming in nodes without displaying a lot of debug stuff in graph editor.
**So that** I can demonstrate zooming in

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN I have any project opened
WHEN I try to zoom in more than 1.0
THEN I cannot 
WHEN I press a special shortcut
THEN a message "Zooming in enabled" appears
AND I can zoom in more than 1.0
AND Nothing more is displayed in graph editor
WHEN I press a special shortcut again
THEN a message "Zooming in disabled" appears
AND I cannot zoom in more than 1.0 anymore
```

**Comment by farmaazon** [comment]
We have different rules for zooming in GUI2
