### ISSUE TITLE
It's impossible to edit named arguments within an Atom nested inside of a Node

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5069]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/184350466).
<hr />

If I try to create the following node:

```
table.aggregate [Aggregate_Column.Group_By "y", Aggregate_Column.First "z" order_by=operator5]
```

Weird stuff is happening. I try to type `order_by=operator5` but in the node, only `order_by=` shows up, which of course leads to the node erroring as the expression is invalid.

Screenshots showing how to repro this are linked in the comments.

Interestingly. if I do the same construct but not inside of `[...]` but as a standalone node - it works fine. Another workaround is to provide all arguments positionally (but that is a pain as I not always want to change all).

## Comments:
The repro is: create a new table with columns x,y,z and then try doing the aggregation:

First I prepare the scene by adding `First` without the `order_by` parameter.

In the next screenshot, I typed `order_by=operator5` but after clicking Ctrl+Enter to submit the changes, I get just `order_by=` and an error. (Radosław Waśko - Jan 30, 2023)
<hr />
However, doing the same named argument in a separate node, or using positional arguments works there just fine:

But of course named arguments should work ok even in nested expressions (Radosław Waśko - Jan 30, 2023)
<hr />
I don't think this feels like engine so leaving it to you @michael_mauderer  (Hubert Plociniczak - Feb 1, 2023)
<hr />
This seems to be related to the node port creation, which I reckon is for @wdanilo to look at. So assigning to him.   (Michael Mauderer - Feb 1, 2023)
<hr />

**Comment by farmaazon** [comment]
Not reproducible in GUI2
