### ISSUE TITLE
Disabling skip/freeze icons next to nodes

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5073]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184347909).
<hr />

Disabling skip/freeze icons next to nodes, add launching it with flag

**Comment by vitvakatu** [comment]
Done in https://github.com/enso-org/enso/pull/4109
