### ISSUE TITLE
adding a new import might invalidate/fix any of the existing nodes

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5074]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184347357).
<hr />

The file does not seem to insert Standard.Table it seems.
That's my header with imports:
``from Standard.Base import all``
``from Standard.Table.Data.Table import Table``
``import Standard.Visualization``

And I have
``operator8 = [ Aggregate_Column.Group_By "gender", Aggregate_Column.Count Nothing ]``

resulting in Aggregate_Column is unknown error

Discussed in the Week 1 BC challange: https://discord.com/channels/401396655599124480/1060875693199728720/1065594261824864326
Further discussion: https://discord.com/channels/401396655599124480/1071077992090050622

## Comments:
	@farmaazon please discuss this issue with @ilyabogdanov on how to start (Greg Ociepka - Feb 1, 2023)
<hr />

**Comment by xvcgreg** [comment]
closing:
https://discord.com/channels/401396655599124480/1071077992090050622/1072284282170658896

<blockquote><img src="undefined//discord.com/assets/652f40427e1f5186ad54836074898279.png" width="48" align="right"><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/channels/401396655599124480/1071077992090050622/1072284282170658896">Discord - A New Way to Chat with Friends & Communities</a></strong></div><div>Discord is the easiest way to communicate over voice, video, and text.  Chat, hang out, and stay close with your friends and communities.</div></blockquote>

**Comment by jdunkerley** [comment]
As per the discussion on discord, the specific import of Aggregate_Column is done but we need to check the `reexport` field and assess how the IDE decides.

**Comment by 4e6** [comment]
Reexports were fixed in #6613
