### ISSUE TITLE
Reorder flag not visible for Table.select_columns

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5080]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/184340526).
<hr />

https://discord.com/channels/401396655599124480/1065951201860001792/1068422295451865160

I realized that `Table.select_columns [ "gender", "pupil first name", "pupil last name", "Date of Birth" ]` doesn't keep my order, but the order in which the columns appeared in the original table. 

There is a `reorder` flag which reorders to the specified order (this was based on discussion with Ned - original cut did reorder). 

The IDE doesn't seem to show that flag, however. It should be drop down, right?

yes **it should have been visible** as a `True`/`False`

**Comment by jdunkerley** [comment]
Already fixed by something else.
