### ISSUE TITLE
Explore Github Projects as a replacement for Pivotal for PM

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5082]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184335131).
<hr />

This chord tracks investigation into the state of Github Projects (vs e.g. Jira ) and how it would fit our needs when replacing Pivotal.

Some things to consider:
- do we need to integrate with specialized plugins on top of GH (e.g. Zenhub)
- how easy it is to define sprints
- how can we manage backlog
- how can we triage unlabeled/unknown tickets efficiently
- how does the prioritization of tickets works these days in GH Projects

**Comment by hubertp** [comment]
No longer valid.
