### ISSUE TITLE
Add support of Named arguments to Span Tree Generator

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5083]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184335109).
<hr />

Add support for `on_problems=value` syntax in node arguments on IDE side. Currently the arguments are always treated as positional, ignoring the name part. This likely depends on new parser being integrated to IDE.

Node that the engine respects the named arguments, so the expressions are evaluated correctly. The issue is purely about how IDE interprets the code present on the node. The visible consequence is invalid argument placeholder and widget assignment.

## Comments:
 (Paweł Grabarz - Jan 27, 2023)
<hr />

**Comment by sylwiabr** [comment]
@Frizi @xvcgreg is this task a bloker for the drop downs implementation? Can you fill the description?

**Comment by Frizi** [comment]
It's not a blocker for dropdowns in general. The task is specifically about supporting named argument syntax in IDE. Without it, the nodes with named arguments behave incorrectly, resulting in bad argument placeholder and widget assignment.

A screenshot of fail state when named argument is present but not supported:
![image](https://user-images.githubusercontent.com/919491/217486154-41d88f15-b88c-457f-bf8e-ddcfca26e984.png)
