### ISSUE TITLE
Scroll bar is visible over visualizations list

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5089]
This task is automatically imported from the old Task Issue Board and it was originally created by Sylwia Brodacka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184335215).
<hr />

The screenshot available in the comment

## Comments:
 (Sylwia Brodacka - Jan 27, 2023)
<hr />

**Comment by MichaelMauderer** [comment]
This seems to be fixed on develop @farmaazon 

https://user-images.githubusercontent.com/1428930/218738866-9837d3d9-e5f2-4b35-afff-1c7366438502.mp4

**Comment by vitvakatu** [comment]
Can it be a non-deterministic (or rather, build-dependent) layers ordering issue? When did we fix it?

**Comment by MichaelMauderer** [comment]
I have not bisected it yet, but @sylwiabr reported that this issue was gone. It might be worth finding out which commit changed the behaviour.

**Comment by sylwiabr** [comment]
It is fixed - not happening to me anymore co I am closing it @MichaelMauderer

**Comment by farmaazon** [comment]
Reported by @jdunkerley that the issue appeard again.
