### ISSUE TITLE
Scrollbar in the project selection section

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5092]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184258141).
<hr />

in both Open project dialogue window and homescreen

https://discord.com/channels/401396655599124480/1063051397655973938

## Tasks:
- [ ] Scrollbar for Home screen
- [ ] Scrollbar for Open project dialog

**Comment by farmaazon** [comment]
Fixed in open project dialogue #5607 , and the homescreen will have a new version.
