### ISSUE TITLE
Link between nodes separates

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5095]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184250659).
<hr />

When dragging a node around noticed that the link separates from the parent. Vertical separation is small between the two
https://discord.com/channels/401396655599124480/1063108713340215368

and
Connection shape fragments sometimes are not properly removed
https://discord.com/channels/401396655599124480/1065600305301049375

**Comment by hubertp** [comment]
Just saw it today on one of the demos:

![Screenshot from 2023-02-13 17-18-51-2](https://user-images.githubusercontent.com/292128/218519642-ce846bd3-fd1a-4c36-8960-58ab0c44ba9a.png)

**Comment by Frizi** [comment]
Video from the discord discussion:

https://user-images.githubusercontent.com/919491/218528724-0daf5514-b4d2-4f8a-8b7f-3fd159ab4200.mp4

**Comment by wdanilo** [comment]
> Just saw it today on one of the demos:
> 
> ![Screenshot from 2023-02-13 17-18-51-2](https://user-images.githubusercontent.com/292128/218519642-ce846bd3-fd1a-4c36-8960-58ab0c44ba9a.png)

If I remember correctly, this small thing on the left should be there, but should be behind node. So probably there is something wrong with the edge placement, but this small thing is not an issue. I might be wrong though, its a long time since I was touching it

**Comment by vitvakatu** [comment]
@hubertp reported that the issue became worse recently. I can't confirm it. I checked a few commits and reproduced the issue even on commit `f53696eda4c6514d9fdc77e8899694c09cfa3ca1`, which is more than one month old. It is quite easy to reproduce, indeed.


https://user-images.githubusercontent.com/6566674/226448613-c2758658-c776-4473-b3f2-ecdc3dd3a2d4.mp4

**Comment by wdanilo** [comment]
@vitvakatu FYI, we will be working on improving draw calls now, including edges. So this MIGHT get fixed along of @kazcw work sooner than later.

**Comment by Frizi** [comment]
Fixed in #6155
