### ISSUE TITLE
UX improvement on Warnings [design]

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5096]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184237659).
<hr />

For now we will display warning with orange stripes background and errors with red stripes background. Warnings will be displayed after hovering the node (just as dataflow errors are). There is a question if we want to show warnings nicer in the future. This task is about designing improved way of displaying warnings in the future.

## Blockers:
[#184237388](https://www.pivotaltracker.com/story/show/#184237388) resolved
[#184237276](https://www.pivotaltracker.com/story/show/#184237276) resolved

**Comment by farmaazon** [comment]
New design of warnings was implemented in GUI2
