### ISSUE TITLE
Integration tests sometimes all fail

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5097]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182278293).
<hr />

Sometimes all the integration tests fail, with errors indicating that JS properties such as `window.console` are missing (`undefined`).

Example of failure:
https://github.com/enso-org/enso/runs/6567669981?check_suite_focus=true

Sometimes they succeed:
https://github.com/enso-org/enso/runs/6548123826?check_suite_focus=true

However, when I[KW] test on my machine the git commit that succeeded in CI above, it consistently produces the same errors as in the failure example.

(Note that this failure presents differently from the timeout issue.)

**Comment by mwu-tow** [comment]
The integration tests ended up being remove before being fixed. The issue is no longer relevant.
