### ISSUE TITLE
High-cpu usage when IDE is idle

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5100]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184204292).
<hr />

It is sufficient to have a browser open with a tab for Enso and CPU usage is 100%

As per discussion with Wojciech
```
We fixed it some time ago, but the fix was not correct (e.g. the mouse cursor stopped blinking). We need to re-enable the fix of not doing any computations when idle. In fact, what you are observing are just redrawing of the frames and the reported CPU usage is stupid. If you record performance of the tab, we are not doing much every frame. 
```

## Comments:
 (Hubert Plociniczak - Jan 11, 2023)
<hr />

**Comment by jdunkerley** [comment]
Assumed to be an Enso GL problem so making lowest, if reoccurs once TS Vue implementation done should be further investigated.

**Comment by sylwiabr** [comment]
Not happening with the new GUI
