### ISSUE TITLE
Initial view should focus on present nodes

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5101]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184194127).
<hr />

If nodes for the existing project were created outside of the usual "center" and there are no nodes in the center, the initial loading of the project may be confusing to users as they may get a blank screen.

## Comments:
 (Hubert Plociniczak - Jan 10, 2023)
<hr />

**Comment by jdunkerley** [comment]
This has been resolved.
