### ISSUE TITLE
Improve entries searching

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5102]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184238020).
<hr />

## Why

**As** Enso IDE user
**I want** to be able to find "read" suggestion by typing "Data.re", or table static methods by writing "Table."
**So that** I can easily find entries when I know the Enso code.

The current searching/filtering tries to match the patter with the entry visible name. It should also try to match the results of code_to_insert, and take the better score as the match score of the entry.

Also, on this occasion, please change the way of displaying methods: they should be `<method name> (<type name>) ` instead of `<type name> <method name>`.

## Acceptance Criteria
```gherkin
Scenario: 
GIVEN I just opened the Component Browser
WHEN I type "Table." in the input
THEN I see all static methods of "Table" in the filtering results
WHEN I type "Data.read" in the input
THEN the "read" suggestion should be displayed and selected.
```

**Comment by MichaelMauderer** [comment]
QA: @MichaelMauderer
