### ISSUE TITLE
New `Data.post` for sending a payload to a Web API

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5105]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184073150).
<hr />

TBD

**Comment by jdunkerley** [comment]
Review the current HTTP APIs (lower level ones).
Look at what JS fetch API is like.

First step should be a markdown/google doc what we think the API will be and then build a prototype and try it out.
Can look at using something like the GH APIs as a target API to work against.

Needs to support posting Text and JSON trivially.
