### ISSUE TITLE
Appending to an Excel sheet where sheet does not start in cell A1

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5106]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182655313).
<hr />

Currently the append to sheet assumes the data starts at cell A1.

Ideally this would use the same system as the ExcelReader to find the existing range.

This ticket is to add this support.

**Comment by jdunkerley** [comment]
Will do when asked for by a user.
