### ISSUE TITLE
Review Table.join warnings

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5110]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184236813).
<hr />

- [x] Any missing column should be an error.
- [x] Joining on a Floating Point should follow the problem behavior.
- [x] Renames should be attached following the problem behavior.

**Comment by jdunkerley** [comment]
Think already mostly already completed.

**Comment by radeusgd** [comment]
Reviewed that all requirements listed above are already implemented.

I want to add one more small test for Join renames to make the coverage better, but that is just a few lines and I will pack it together with a PR for #5109, as there's no point in such a micro PR and the two are relatively related anyway.
