### ISSUE TITLE
Text.write and Table.write problem behavior.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5114]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184238365).
<hr />

Any file access issues (e.g. _parent directory_ not existing or no permission) is an error.
If the file format is not supported should be an error.

If the document doesn't fit in the target or will overwrite data unexpectedly should be an error (mostly for Excel write).

If a character cannot be written then a warning should follow the on_problems behaviour.

**Comment by radeusgd** [comment]
TODO:

- [x] Tests for writing with nonexistent parent directory.
- [x] Table.write test with read-only file (like ones that already exist for Text.write)
- [x] Change `Illegal_Argument` to new error - `Unsupported_Output_Format: The file format XYZ does not support writing ABC.` and add ~~Text/~~ Table tests for that.
- ✅ There are tests for Excel range/overwrite cases.
- [x] Add tests for writing characters invalid in a given encoding - ensure a warning is attached.
   - [x] Text.write
      - [x]  fix it
   - [x] Table.write Delimited
   - [x] check if doable for Table.write Excel - maybe do a write+read combination of some emojis and see what comes out
     - _Added a test that saves unicode Emojis and then loads them back to see that they survived the round-trip. Cannot test other encodings as encoding is not customizable with this format._
     - Testing for non-Unicode encodable characters would require manually creating such an invalid string first, I think this would be an overkill to handle. But hypothetically we could test this.
