### ISSUE TITLE
All types used as an Error or Warning should have a nice `to_display_text` function

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5116]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184225948).
<hr />

All warning types attached by the APIs will be rendered to the user via the `to_display_text`. 

This ticket is to review the display format and ensure they have helpful messages for each error.

Additionally, we should add tests to ensure regressions do not occur on this.

**Comment by radeusgd** [comment]
We should probably ensure our unit tests run `to_display_text` of each error type, to ensure that the error visualizations work correctly.

This will allow to avoid regressions like `to_display_text` breaking due to changed field names.
