### ISSUE TITLE
Functions writing to a file should only write if no warnings attached

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5117]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184225897).
<hr />

When writing data to a file we should error if there are still warnings attached.

The function should have an explicit `ignore_warnings=False` argument allowing by passing of this behaviour.

**Comment by jdunkerley** [comment]
Closing for now - we can revisit later if product decides.
