### ISSUE TITLE
`Regex.compile` shall compile just once. Create new Regex types and use for match, find and find_all.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5120]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184295502).
<hr />

Approximately.

The current `Standard.Base.Text.Regex.compile` method will be replaced with:

```haskell
compile : Text -> Case_Sensitivity -> Pattern ! Compile_Error
compile expression case_sensitivity=Case_Sensitivity=Case_Sensitivity.Sensitive =
    ...
```

The `Pattern` type would be converted to being the actual implementation (removing the interface and `Default` implementation). In general, it is expected that users will use the extension methods defined on `Text` and not the `Pattern` methods directly. 

- `pattern`: The original pattern text.
- `group_count`: The number of capture groups present.
- `named_group_map`: Mapping between grouping name and group id.
- `matches input:Text -> Boolean`: Does the whole `input` match the pattern.
- `find input:Text -> Match`: Execute the pattern against the `input` get the first match.
- `find_all input:Text -> Vector Match`: Execute the pattern against the `input` get the all the matches.
- `replace input:Text replacement:Text -> Text`: Execute the pattern against the `input`, replace the first match following the rules.
- `replace_all input:Text replacement:Text -> Text`: Execute the pattern against the `input`, replace all matches following the rules.

The old `Matching_Mode.Last` ability is removed from the RegEx support. This needed to be a slow implementation where it would match each value and move forward until no more matches were possible.

The `Match` type would represent what comes back from the pattern `exec` method.

```haskell
type Match
    Value parent:Text pattern:Pattern java_match:...

    ## Gets the index of the codepoint within the Text
    start_codepoint : Integer
    start_codepoint self = ...
    
    ## Gets the index of the codepoint within the Text
    end_codepoint : Integer
    end_codepoint self = ...

    ## Gets the index within the Text where the match starts
       If the match starts part way through a graphene cluster, will be the
       including that cluster.
    start : Integer
    start self = ...

    ## Gets the index within the Text where the match end
       If the match ends part way through a graphene cluster, will be the
       including that cluster.
    end : Integer
    start end = ...

    ## Gets a marked group from the match.
       If the group does not exist returns `Nothing`.
       Group `0` represents the whole match.
       If `selector` is `Text`, will find a named group.
    get Integer | Text -> Text | Nothing
    get self selector = ...
```

**Comment by jdunkerley** [comment]
Ring buffer was an assumed solution. We want:

```
vector = [...]
replaced = vector.map (_.replace "[A-Z]{3}" "...")
```

to be fast and not be compiling the regex for every record.

**Comment by JaroslavTulach** [comment]
The previous [exploratory work on regex](https://www.pivotaltracker.com/n/projects/2539304/stories/181348590/comments/235101212) shall be expanded with a cache to ensure only one compilation happens for each call site. With [this change](https://github.com/JaroslavTulach/enso/commit/e7ee357ceb503bea828bc42949e265d4752722f2) I can run following program:
```haskell
from Standard.Base import all

main =
    v = Range.new 1 10000
    v2 = v.map i->
        t = i.to_text
        m = Regex.compile ".*[135]$"
        if m.matches t then i else Nothing
    v2.filter x->
        case x of
            _:Number -> True
            _ -> False
```
and only one compilation of the `Regex` happens during the whole execution - in spite the `Regex.compile` call being used in a loop. The system *caches the previous computation at the callsite* and if the pattern is the same, it returns existing regex. The cache size is set to three for each location invoking `Regex.compile`.

**Comment by JaroslavTulach** [comment]
After rewrite of [Text.replace](https://github.com/JaroslavTulach/enso/commit/7c089c22ec07652cbd29b6a13a96f81c265409b3) to use the new `Regex.compile` method, I am able to execute:
```haskell
from Standard.Base import all

main =
    v = Range.new 1 10000
    v2 = v.map i->
        t = i.to_text
        r = t.replace "[135]$" "0" matcher=Regex_Matcher.Value
        m = Regex.compile ".*[0135]$"
        if m.matches r then i else Nothing
    v2.filter x->
        case x of
            _:Number -> True
            _ -> False
```
and there are just two `RegexCompileNode.compile` invocations. E.g. the caching seems to work even for `Text.replace`. Of course, the real behavior shall be stressed by a benchmark to be really sure.

The [whole TRegex branch](https://github.com/enso-org/enso/compare/develop...JaroslavTulach:wip/jtulach/TRegex_181348590) demonstrates the **TRegex** approach is viable.
