### ISSUE TITLE
Add simple parts of `Table.take` and `Table.drop` functions to Database table

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5131]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182307382).
<hr />

### Take

```python
    take : (Index_Sub_Range | Range) -> Table
    take range = ...
```

#### Generic Description

Creates a new Table with the specified range of rows from the input Table.

#### Parameters

- **range**  
  The selection of rows from the table to return.  
  If a `Index_Sub_Range`, then the selection is interpreted following the rules of that type.  
  If a `Range`, the selection is specified by two indices, from and to.

#### Returns

A new table with the same columns but with just the specified rows.

### Drop

```python
    drop : (Index_Sub_Range | Range) -> Table
    drop range = ...
```

#### Generic Description

Creates a new Table from the input with the specified range of rows removed.

#### Parameters

- **range**  
  The selection of rows from the table to remove.  
  If a `Index_Sub_Range`, then the selection is interpreted following the rules of that type.  
  If a `Range`, the selection is specified by two indices, from and to.

#### Returns

A new table with the same columns but without the specified rows.

### Notes

- With the exception FIRST will probably only work on tables with a defined ORDER BY clause
- This ticket will need exploration of the capabilities of the specific DB engine

## Comments:
Break this up into a `Limit` and `Skip`  (James Dunkerley - Dec 20, 2022)
<hr />
Anything that is logically too hard then report a Unsupported Database Operation (James Dunkerley - Dec 20, 2022)
<hr />

**Comment by jdunkerley** [comment]
This should be possible to be based on top of the row number and can do more options.

**Comment by radeusgd** [comment]
Just to not forget: we need to ensure that stuff like `table.drop 3 . drop 4` works correctly and removes total of 7 rows from the result
