### ISSUE TITLE
Pan camera to show entire component browser after opening

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5132]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184369766).
<hr />

## Why

**As** Enso IDE user
**I want** To see the entire component browser after creating a node near the top of the scene
**So that** I don't have to pan view myself to see its content

## Notes

Panning view to newly created node is already implemented, so it should be relatively easy to extend this behavior to Component Browser panels.

**Comment by farmaazon** [comment]
Fixed in #9273
