### ISSUE TITLE
Dropdown data filtering

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5136]
This task is automatically imported from the old Task Issue Board and it was originally created by Paweł Grabarz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184012788).
<hr />

## Step 5: Filtering the data.

Part of https://www.pivotaltracker.com/n/projects/2539304/stories/183930734

**Delivery requirements:**  
- When the drop-down is clicked, the list of entries is displayed. In this state, when the user starts typing, the typed text should be displayed instead of the current value (on the node). The entries should be filtered in "real-time" on the engine side. This should be done in the same way as scrolling and sorting (just by creating another expression which should be computed on the engine side before the widget gets the final data). 
- The filtering should allow for regexp input. The text typed by the user should be just fed into our regexp library on the engine side.
- The matched letters should have different color and should be displayed in bold (in the same way as letters in the component browser search).
- After pressing "enter", the best match should be used. After pressing "ctrl + enter", the typed text should be used as-is. This behavior should be the same as in the case of the component browser.

**Comment by farmaazon** [comment]
Superseded by #9058
