### ISSUE TITLE
Missing `Compiling Standard Library` message

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5139]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184009041).
<hr />

IDE stopped showing Compiling Standard Library on all operating systems while opening the project - after spinner is gone there are no nodes just gray window and it looks like the product is dead. After a longer moment nodes shows up and starts coloring cc

## Comments:
 (Greg Ociepka - Dec 11, 2022)
<hr />
Only displays a single error message and so the version check message masks. No way to dismiss that message and hence no way to see the compiling message. (James Dunkerley - Feb 1, 2023)
<hr />

**Comment by farmaazon** [comment]
Fixed by hiding mismatched engine version

**Comment by xvcgreg** [comment]
removed ``--regression`` label - it wasn't missing it was just obstructed
