### ISSUE TITLE
#[derive(Iterator)] Should Support More Enum Variants

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#514]
### Summary
Currently `derive(Iterator)` can be only applied to enum types with all variants being of form `Con(Foo)`, where `Foo` implements `iter()`.

This should be generalized to support variants being structures, tuples or single-elem tuples storing directly the iterated value.

### Value
Consistency and completeness. 

### Specification
Same rules (and partially code) should be used as when iterating structs (and its tuples fields, respectively).

### Acceptance Criteria & Test Cases
Test to be developed along with this task.

**Comment by iamrecursion** [comment]
Obsolete.
