### ISSUE TITLE
UX improvement while scrolling with a scrollbar

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5143]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184009034).
<hr />

Can't scroll because top bar keeps on interfering - it is rather annoying since one cannot get to the scrollbar as it keeps interfering with the top bar that unfolds (as per video).

## Comments:
 (Greg Ociepka - Dec 11, 2022)
<hr />

**Comment by farmaazon** [comment]
No video, and I guess in GUI2 scrollbars work good (as we use browser's ones).
