### ISSUE TITLE
UX improvement on changing visualization

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5144]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184009031).
<hr />

Most users while trying to change the type of visualization are starting to drag a connection or have hard time clicking in the right place to see the drop down.

**Comment by farmaazon** [comment]
I think it's not a problem in new visualization design (implemented in GUI2).
