### ISSUE TITLE
Load visualizations after opening project

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5149]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183981006).
<hr />

### Steps to reproduce
1.Run IDE and open a project with custom visualization in its `visualization` directory
2. Create node with output compatible with custom visualization
3. Open visualization and display visualization list

### Expected

The custom visualization is there

### Actual

It isn't. It shows only on reload visualization shortcut

### Notes

There is a function in presenter/graph/visualization.rs which is called on shortcut - it should be called also after project load.

**Comment by farmaazon** [comment]
Not reproducible in GUI2
