### ISSUE TITLE
Improve error paths and testing for transpose and cross_tab

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5150]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183909406).
<hr />

Current crosstab and transpose do not have all the error checking and support they should have.

Review the doc comment for the public API methods and improve.

Additionally, review the `all_same_column` logic and the doc string attached. Should also have tests written for this.

**Comment by jdunkerley** [comment]
We have a decent test suite now and have the habit of adding tests whenever a bug is discovered so closing this.
