### ISSUE TITLE
Use Unique Name Strategy for Cross Tab

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5151]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184072769).
<hr />

Currently the names generated in the crosstab are just the `toString` value.
This should use the normal naming convention to resolve empty and null names.

**Comment by jdunkerley** [comment]
Brought into scope as currently can get non-unique names out.
@radeusgd please post your example.

**Comment by radeusgd** [comment]
> Brought into scope as currently can get non-unique names out. @radeusgd please post your example.

Added a pending test case in my current PR: https://github.com/enso-org/enso/pull/5579/files#diff-1d77bd6fe79579d5cd6ff45a36388683a3c2bb5923da4750849cca7f9b8245b9R136-R141

<blockquote><img src="https://avatars.githubusercontent.com/u/1436948?s=400&v=4" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/pull/5579">Rework Invalid Aggregations by radeusgd · Pull Request #5579 · enso-org/enso</a></strong></div><div>Pull Request Description
Closes #5108
Important Notes

Checklist
Please include the following checklist in your PR:

 The documentation has been updated if necessary.
 All code conforms to the
Scal...</div></blockquote>
