### ISSUE TITLE
More tests for Data.fetch, Table.from_objects and JSON APIs

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5152]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184073145).
<hr />

Following the update of the JSON API.

Need to add some more tests for the Table.from_objects (very basic at present).
Add some actual tests for Data.fetch.

Review any gaps in JSON testing.

**Comment by jdunkerley** [comment]
Lots of work done on top of this now so closing as very out of date.
