### ISSUE TITLE
Fix expressions in Database

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5155]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/183933832).
<hr />

Expression tests were only being run for the in-memory backend.

Turns out many of them fail on the Database backend. They have been marked as pending for now, but the issues should be fixed so that the expressions work properly on either backend.

Review all the Column operations and consistency between InMemory and InDB operation
- Pay attention to NULL in equality (both should allow for a == Null).
- Division in SQL appears to be integer based if both columns are integer.

## Comments:
**James Dunkerley** reports a new **STANDUP** for today (2022-12-06):

**Progress:** Covering the PR tidying up. Build an experimental flow downloading the Nasdaq price history and processing. Adding Data.fetch API prototype. Started looking at the issues with Database expressions. It should be finished by 2022-12-12.

**Next Day:** Next day I will be working on the [#183933832 task](https://www.pivotaltracker.com/story/show/183933832). Finish Data.fetch prototype. Continue the expression debugging. (Enso Bot - Dec 6, 2022)
<hr />
Missing loads of testing of the column operations - this will determine follow on tickets. (James Dunkerley - Dec 20, 2022)
<hr />

**Comment by jdunkerley** [comment]
This ticket is to assess what is broken and to write the new ticket set needed to fix (which will then be prioritized).
