### ISSUE TITLE
Add Value_Type to In-Memory Column

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5158]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183854180).
<hr />

- Update prototype Value type to [current specification](https://github.com/enso-org/design/blob/main/epics/basic-libraries/database-read/design.md#column-metadata-and-value-types).
- Adjust storage classes:
  - Hold the minimum and maximum values in the dataset (just the size needed)
  - ~~Hold the nullability flag~~ _will be done separately in #5872_
  - Allow computation	 of the type from the values in the dataset
  - Allow setting of a type restriction on the column
- Add set_value_type and value_type to the Column
- Alter Table.info to return the value type of the column
- Ensure builders create value typed if possible.
	Type is possible use Mixed in not.

`From_Vector` take a new optional argument with a fixed type.

**Comment by radeusgd** [comment]
1. Core
	- [x] Create a proper mapping from SQL Types into `Value_Type`.
	- [x] Create a `Dialect`-specific `SQL_Type_Mapping` mapping from `Value_Type` to SQL type.
    	- [x] Add unit tests checking that the mapping is aligned with the table in the design doc.
		- [x] Ensure if we can make `SQL_Type_Mapping.value_type_to_sql` injective.
			- ~~Will not work in full with SQLite?~~
			- It is not injective as we are approximating some types on purpose. We report warnings in such cases when the approximation is inexact. That should be good enough for now.
			- _Other issue is the reverse scenario - types like `CLOB` and `TEXT` that we both map into `Value_Type.Char` and so they cannot be distinguished - thus the mapping is not injective. We ignore this for now as it may not be a problem currently._
			- [x] In particular, extend SQL_Type to allow additional parameters, to allow distinguishing types like fixed length text - e.g. `CHAR(16)`.
		- ~~Add `SQL_Type_Mapping.to_code` which will generate the Dialect specific type name, for example `INTEGER`.~~ - _currently probably not needed, may be needed for `upload_table` - TODO we will see_
	- ~~Add `fits_in` (bits) to numeric in-memory storage.~~
	  - Aggregate min and max? This may be costly in some operations like masking.
	  - _Not sure if needed. Will be revised in next PR when working on constraining types of in-memory columns._
	- [x] ~~Decouple in-memory `value_type` from `storage_type`~~ - add a `value_type` property on the column.
		- ~~When creating a new column with a storage, check that the storage and `value_type` are compatible (i.e. the `value_type` must be of the same kind and have the same or greater size; or be `Mixed`).~~
		- Cannot be tested well without `from_vector` or `set_value_type`/`cast`.
		- After all, not sure if this is the best idea. It may be better to keep a storage<->value_type mapping and let storage keep information on the type data. This will make operations, like ensuring limited integer size, easier.
			- But needed to some extent - we want to be able to re-cast a type to Mixed in O(1) (ideally without changing the storage).
				- Still can be done by adding more metadata to storages.
		- Finally implemented this by adding more info to Storages and mapping Storage into a corresponding Value_Type. Mixed is handling by a special storage wrapper facade that changes its reported type from the actually stored type to the "Any" type. Still WIP until we get `set_type`...

2. Tidying up
	- [x] Ensure `Table.info` returns the `Value_Type`
		- [x] and that it displays nicely in the GUI.
	- [ ] Add `value_type` parameter to `Column.from_vector` (`Nothing` by default which means that the type will be automatically inferred like now).
	  - _`From_Vector` take a new optional argument with a fixed type._
	  - By default, infer the type.
	  - If given values do not match the expected type, throw type mismatch error / does not fit the type error.
	    - [ ] Figure out what the error type should be here.
	    - [ ] Implement a `Value_Type.is_valid_for` function that checks if an Enso value can be stored in the given type.
     	    - Possibly relying on just `InferredBuilder` and checking its result type could be slightly more efficient, but it should not make a big difference, and this approach will allow us to raise an error containing an exact value that did not match the type, instead of just saying that _some_ values were invalid. We can revisit this in the future if needed.
	- [ ] Rename `Table.parse_values` into `parse`?
	  - This is suggested by designs. Are we doing it?
    - ~~Make SQL_Type depend on the dialect.~~
       - Kind of done by removing the constants from `SQL_Type` and just relying on the mappings.

3. Operations
	- [ ] Add checks on operations that check if the operand has right type (arithmetic require a numeric type, text need text).
	- [ ] Consolidate the return type based on operands (usually choose the larger type).
      - _On DB side this is now done by asking the Database what is the effective type of a given SQL expression corrresponding to each operation; for in-memory will be handled in next PRs_.
	  - Partially handled by #5159 but that is just part of the story, I'd prefer to do a single PR with all type logic.
	- [ ] in-memory `map` and `zip`
		- [ ] Add `expected_type` parameter.
	    	- Acts exactly like `Column.from_vector`, i.e. infer by default, otherwise check and error if does not fit.
	- [ ] Arithmetic and text etc. operations will use the type consolidation for their type (numeric, text, generic for `iif`)
    	- [ ] Consolidation will need to be partially context-specific - like `Text + Text` should not select the maximum length but instead _add_ the lengths!
    	- Probably worth having some module `Value_Type_Unifier` with various algorithms for numeric, text types, depending on context etc.
		- [ ] Add tests for overflows - new value and warnings.
		- [ ] If the operand type does not fit an operation (adding Text to Integer etc.), report `Invalid_Value_Type` error - but with `expected` not necessarily being a specific `Value_Type` but a description like `"a numeric type"`.
	- [x] ~~Add a suite of tests that verify that the type merging algorithm is consistent with what SQL generates.~~
	  - ~~We could create tables with the given SQL types, perform each operation and check the metadata of the resulting type.~~
	  - ~~SQLite will be problematic.~~
	  - No longer applicable - we are using the types that the Database reports to us - so this is aligned by definition. With the exception of SQLite Booleans which are not aligned on purpose to provide better UX.

4. Conversions
	- [ ] Add `cast` to the in-memory column.
		- _Allow setting of a type restriction on the column_
		- This was called `set_value_type` in the designs.
		- [ ] Widening scenario - if types match and the goal is wider - just change it.
		- [ ] Converting scenario - stuff like `.to_text` or integer<->float
		- [ ] Introduce `Lossy_Conversion` error.
		- [ ] Truncating scenario - tests
			- [ ] Ensure that if the new type does not fit all numbers because the bit-size is too small, a `Lossy_Conversion` warning is reported.
			- [ ] Ensure if new Text type is too small and some values are truncated, `Lossy_Conversion` is reported.
	- [ ] Add `cast` to Database column.
		- This will mostly rely on the `Value_Type <-> SQL_Type` mapping and use the `CAST` operator.
		- [ ] Add tests for DB casting.
		- [ ] See if we can keep `value_type` and `sql_type` coupled.
  			- The idea would be to resort on the mapping `sql_type -> Value_Type`. Cast will convert the desired `Value_Type` into a corresponding SQL Type and add a CAST expression.
  			- Still, we want `column.cast vt . value_type == vt`, so this will rely on the property of Value_Type <-> SQL_Type such that `forall vt, vt.to_sql_type.to_value_type == vt` (i.e. `to_sql_type` will need to be injective). 
	- [ ] Implement `auto_value_types`.
	   - Will only work in-memory as too complicated for DB. Standard 'please materialize' error in DB.
	   - [ ] Tests for `use_smallest = True | False` logic.

**Comment by radeusgd** [comment]
TODO list before the first PR:
- [x] Finish Postgres mapping to pass all tests.
- [x] Add overrides for Boolean operation types for SQLite.
	- [x] Ensure we can override types for some operations.
	- [x] How to wire this nicely so that the overrides only happen in SQLite?
    	- Adding `infer_return_type` to the type mapping.
	- [x] Clean-up column operations from obsolete `new_type` internal arguments.
- [x] Change all `col.sql_type.is_definitely_TYPE` into `col.value_type.is_TYPE`.
	- [x] Remove the `is_definitely_***` from `SQL_Type`.
	- [x] Remove the constants for types from `SQL_Type` - we should rely on the backend-specific mappings instead.
	- [x] Move Builders in Result_Set to depend on the Type_Mapping - add a place to later plug-in custom Postgres date handling logic.
- [x] Ensure tests are passing.

**Comment by radeusgd** [comment]
The major PR #6073 is ready, save for fixing conflicts and adding one more small functionality.

I think the remaining types work (parts noted here above, parts tracked by separate tasks), is something along these lines:

1. Add Day, Month, Year operations on Columns - both in DB and in-mem.
   #6115
   #6153 
2. Implement Union for DB 
   #5235
3. Implement Full Join workaround for SQLite 
   #5254
4. Implement `cast` (in memory and DB) 
   #6112
5. Add missing type checks to column operations (inmem and DB, mostly inmem I think) 
   #6106
6. Add expected type checks to map, zip and Column.from_vector (in-memory) 
   #6111
7. Improve variety of in-memory storage types (add 16/32-bit ints, fixed length strings) and adapt any functions to support these. 
   #5159 
	- To keep in mind that currently we are still storing smaller ints in 64-bits and just 'faking' the limits, and that we cannot store 32-bit floats, I created a separate issue to actually implement the smaller storages #6109. It will take a significant amount of work as we cannot do it generically very easily. So it probably should not be completed before the Beta Release, we may schedule it for sometime later when there is time.
8. Implement `auto_value_types` and update `Table.parse_values` to use Value_Type.
   #6113 
   #5660
9. Extend the `Value_Type` system with the concept of nullability. 
   #5872
	- This may be a bigger chunk and possibly split into multiple PRs too.
