### ISSUE TITLE
Implement `replace` on the Database Column

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5160]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183499562).
<hr />

```python
    replace : Text | Column -> Text | Column -> Case_Sensitivity -> Boolean -> Boolean -> Column
    replace self term="" new_text="" case_sensitivity=Case_Sensitivity.Sensitive only_first=False use_regex=False =
```

- Surfaces the same options as `Text.replace`.
- Should follow the same API as the in-memory version.
- Case Insensitive in non-default locale should be an error.
- What modes are available will depend on what is supported by the dialect.

This should be done by mapping the modes to specific dialect operators:

| case_sensitive | use_regex | only_first | operation |
|---|---|---|---|
| True | False | True | Replace_First |
| True | False | All | Replace_All |
| False | False | True | IReplace_First |
| False | False | All | IReplace_All |

etc.

**Comment by GregoryTravis** [comment]
Looking through the Postgres and SQLite docs, it looks like

| case_sensitive | use_regex | only_first | postgres | sqlite |
|---|---|---|---|---|
| True | False | False | supported | supported |
| True | False | True | via regex(2) | via instr(3) |
| False | False | False | via regex(1) | unsupported |
| False | False | True | via regex(1,2) | via instr(3) |

(1) Postgres regex supports case insensitivity; this would require escaping the search string so it would not act as a regex.
(2) Postgres regex supports only_first starting with version 13; this would require escaping the search string so it would not act as a regex.
(3) Use INSTR() to find the lowercased string, then replace it via concatenation
