### ISSUE TITLE
Design for Write Database

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5161]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182652184).
<hr />

Similar to Table.write for in-memory.

- Create a new table
  - Specified table name
  - Overwrite with warning or error
- Append data
  - Map columns by Name or Position
- Update data
  - Using primary key to join on
  - Option to remove unmatched rows
- Delete data
  - Using primary key to join on

Additionally transaction support.

**Comment by jdunkerley** [comment]
Tasks to complete:
- #6326 
- #6327 
- #6437
- #6498 
- #6887 
- #7035 
- #7238
