### ISSUE TITLE
Cannot load Advent5 project in the IDE

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5162]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183957970).
<hr />

I was [implementing task for day 5](https://discord.com/channels/401396655599124480/1049202965141004298) of Advent of Code.

I had to code (parts of the code) manually, but then the IDE refused to load my project.

## Comments:
 (jaroslavtulach - Dec 5, 2022)
<hr />
This is my project. (jaroslavtulach - Dec 5, 2022)
<hr />

**Comment by jdunkerley** [comment]
Closing as havent seen similar in BC era.
