### ISSUE TITLE
Types with bang (!) syntax are not resolved

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5164]
This task is automatically imported from the old Task Issue Board and it was originally created by Dmitry Bushev.
Original issue is [here](https://www.pivotaltracker.com/story/show/183882946).
<hr />

### Steps to reproduce
Given a type signature
```
creation_time : Date_Time ! File_Error
```

### Expected
The type is `Date_Time`

### Actual
The type is `Any`

**Comment by jdunkerley** [comment]
This is an error now. Thanks @hubertp.
