### ISSUE TITLE
Don't use winapi in 0.2.8 version

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5167]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/183533636).
<hr />

This is a transitive dependency. Warning message is: warning: the following packages contain code that will be rejected by a future version of Rust: winapi v0.2.8

**Comment by mwu-tow** [comment]
Already fixed.
