### ISSUE TITLE
Update electron-builder, pt.2

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5169]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/183085541).
<hr />

As soon as https://github.com/electron-userland/electron-builder/issues/6865 is addressed.

## Blockers:
[https://github.com/electron-userland/electron-builder/issues/6865](https://www.pivotaltracker.com/story/show/https://github.com/electron-userland/electron-builder/issues/6865) blocked

**Comment by farmaazon** [comment]
Done in #9884
