### ISSUE TITLE
Clean vulnerabilities in the runtime docker image

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5170]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/183453034).
<hr />

No description provided.

**Comment by mwu-tow** [comment]
Un-assigning, as the Dockerfile is owned by the Backend team.
It received some updates (like https://github.com/enso-org/enso/pull/8349) but likely it should be audited and kept clean continuously.
