### ISSUE TITLE
Update `Flatbuffers` toolchain

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5171]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/180303547).
<hr />

## Description
The Old Flatbufferes version has several problems and is hard to be installed on some systems.

## Resources
Flatbuffers has released [2.0.0](https://github.com/google/flatbuffers/releases/tag/v2.0.0) which overhauls rust support and fixes numerous bugs.

## Tasks:
- [ ] Upgrade both the engine and IDE to be compatible with the new `flatc` version.
- [ ] Split up the flatbuffers schemas into multiple organised files.

**Comment by hubertp** [comment]
Whatever version is picked please let's avoid using another package manager (like `congo`?) and simply fetch binaries directly from GH for the specific platform.

**Comment by mwu-tow** [comment]
> Whatever version is picked please let's avoid using another package manager (like congo?) and simply fetch binaries directly from GH for the specific platform.

Yes, absolutely. `conda` was used only because for older releases flatbuffers was only providing Windows binary.
