### ISSUE TITLE
Properly handle error codes when downloading the run artifact

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5172]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/184350556).
<hr />

Fix on our side or in the octocrab.
The issue is that error code is not checked, just html streamed as zip.

**Comment by mwu-tow** [comment]
This is handled by our fork of octocrab, was also fixed upstream.
