### ISSUE TITLE
Building enso sometimes fails with message "Multiple exports with the same name "ccall"

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5174]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183313529).
<hr />

As in description.

The issue shows quite regularly, but has no 100% reproduction scenario yet.

It is caused by build script of "ensogl-text-msdf" crate. In the script we patch the downloaded js file adding some exports, but sometimes they are added twice (despite the check which is already present there).

Probably we should not patch the file at all, but instead add the js code in the published package on [msdfgen-wasm repository](https://github.com/enso-org/msdfgen-wasm)

**Comment by mwu-tow** [comment]
No longer relevant with the old gui gone.
