### ISSUE TITLE
Equality with polyglot numbers is broken

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5177]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/183764270).
<hr />

```
int = Polyglot.new Integer [42]
int . should_equal 42
```
is currently false.
So is
```
42 . should_equal int
```
The main issue is that when the equality check sees that we compare a polyglot and a non-polyglot value it assumes that can't be ever true and bails.
We need to special case numbers.

**Comment by JaroslavTulach** [comment]
The problem will be in missing `CoercionNode` - after a call to polyglot, we need to convert to supported Enso values. So `java.lang.Integer` becomes `long`, etc.

**Comment by GregoryTravis** [comment]
I'm getting this as well -- using the Truffle regex library, translating a pattern group name to a pattern group number, I'm getting a polyglot integer that can't be used as a regular integer.
