### ISSUE TITLE
Play button support

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5179]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/182816602).
<hr />

Blocks:  https://www.pivotaltracker.com/story/show/182746085
The _play button_ will be part of _IO control system_ - e.g. #182781696

This may heavily involve the controller in GUI. On the top of the GUI there will be a button allowing switching the mode (production <-> development <-> maybe other modes). Given a mode, every IO node is assigned with info if it should auto-refresh. In the production mode all IO nodes are refreshed by default. In development mode, all IO nodes are not refreshed by default and the user needs to press play button next to the nodes. Unfortunately, this is important and we constantly hear about it from people. E.g. you open your dataflow network and you want to change it, but you dont want to override your database when playing with values. So you switch to dev mode and nothing evaluates until you want to. Also, the nodes should not evaluate their IO actions even if visualizations are opened. Anyway, this requires a bigger talk with the engine team, because support for it seems non-trivial. In particular, if the IO operations are nested, e.g. after collapsing a node, we still want to have the "play button" visible on the collapsed node and we want the inner IO nodes to not autorefresh in the given mode. This can't be done by GUI, as after the definition of the collapsed node changes, things should be updated and work. Let's have a talk about how much of that can be done and when.

## Blockers:
[#182781696](https://www.pivotaltracker.com/story/show/182781696) blocked

**Comment by jdunkerley** [comment]
@sylwiabr and @jdunkerley to discuss what parts of this need moving forward.

**Comment by jdunkerley** [comment]
Following #5713 will replace with new tickets.

**Comment by wdanilo** [comment]
@jdunkerley Ive just noticed that the design doc does NOT mention the play button. Basically, in "development" mode we should have play button which pressed should just override the context to "production" for a second, run all nodes, and switch back to development. This allows for "one-shot" execution of the graph. I think this is an important thing, and pretty easily implementable probably. It's also already designed in Figma (see below). Do you agree? 

<img width="1530" alt="image" src="https://user-images.githubusercontent.com/1623053/225178344-9888051f-2ac3-4f9f-be53-63d55b891452.png">

**Comment by wdanilo** [comment]
Reopening because of the question above ^^^

**Comment by jdunkerley** [comment]
Good point - I'll add a section to the document covering this.
