### ISSUE TITLE
Simplify EpbLanguage by using TruffleLanguage.ParserRequest.getArgumentNames + support Ruby & co.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5184]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/182435117).
<hr />

`EpbLanguage` has special _envelope_ code for interop with JavaScript, Python and R. There is however a standard Truffle API: https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/TruffleLanguage.ParsingRequest.html#getArgumentNames-- that allows to achieve (almost) the same and work across languages. Let's investigate whether we can simplify `EpbLanguage` implementation.

Initial discussion with Marcin lead to a fundamental question: Can we support JavaScript `this`? Pictures as well as description is below. The following two files `parseself` program seem to indicate providing `self` is possible. E.g. simplification of Python is possible right now. Dropping special _envelope_ support for `R` shall work as well, as `R` doesn't have any 1st class object oriented features anyway. 

Moreover, by basing our support on `getArgumentNames`, we open up to other, unknown languages that support it. Btw. [GraalVM Insight](https://github.com/oracle/graal/tree/master/docs/tools/insight) is using `getArgumentNames` - e.g. we'd be using exactly the same mechanism. Any language ready for **Insight** would also work for Enso.

Compiling and executing these two classes as `/graalvm-ce-java11-21.3.0/bin/java -cp . -Dtruffle.class.path.append=. org.apidesign.netbeans.parseself.Main` provides some insight into the behavior of `parse` with argument names.

```
package org.apidesign.netbeans.parseself;

import com.oracle.truffle.api.CallTarget;
import com.oracle.truffle.api.TruffleContext;
import com.oracle.truffle.api.instrumentation.ContextsListener;
import com.oracle.truffle.api.instrumentation.TruffleInstrument;
import com.oracle.truffle.api.nodes.LanguageInfo;
import com.oracle.truffle.api.source.Source;
import java.io.IOException;
import java.util.function.BiConsumer;

@TruffleInstrument.Registration(id = "parseself", name = "Parse Self", services = BiConsumer.class)
public class Parseself extends TruffleInstrument {
    final void defineSelf(TruffleInstrument.Env env, String lang, String text) {
        String selfName = "nic";
        switch (lang) {
            case "js": selfName = "this"; break;
            case "python": selfName = "self"; break;
        }
        try {
            Source src = Source.newBuilder(lang, text, "sample.py").build();
            CallTarget target = env.parse(src, selfName);
            target.call("hello");
        } catch (IOException ex) {
            throw new IllegalStateException(ex);
        }
    }

    private TruffleContext ctx;

    @Override
    protected void onCreate(Env env) {
        BiConsumer<String, String> c = (lang, text) -> {
            Object p = ctx.enter();
            defineSelf(env, lang, text);
            ctx.leave(p);
        };
        env.registerService(c);
        env.getInstrumenter().attachContextsListener(new ContextsListener() {
            @Override
            public void onContextCreated(TruffleContext context) {
            }

            @Override
            public void onLanguageContextCreated(TruffleContext context, LanguageInfo language) {
                ctx = context;
            }

            @Override
            public void onLanguageContextInitialized(TruffleContext context, LanguageInfo language) {
            }

            @Override
            public void onLanguageContextFinalized(TruffleContext context, LanguageInfo language) {
            }

            @Override
            public void onLanguageContextDisposed(TruffleContext context, LanguageInfo language) {
            }

            @Override
            public void onContextClosed(TruffleContext context) {
            }
        }, true);
    }
    
}
```

and `Main.java`: 

```
package org.apidesign.netbeans.parseself;

import java.util.function.BiConsumer;
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.Engine;

public class Main {
    public static void main(String[] args) {
        Context ctx = Context.create();
        Engine engine = ctx.getEngine();
        ctx.eval("js", "print('regular JavaScript initialized');");
        
        BiConsumer c = engine.getInstruments().get("parseself").lookup(BiConsumer.class);
        c.accept("python", "print(self);");
        c.accept("js", "print(this);");
        
        ctx.eval("js", "print('regular JavaScript finished');");
    }
}
```

## Comments:
The current functionality supports JavaScript `this` as well as Python's `self`. The `parseself` program (in the description of this issue) seems to indicate replacing `self` with `getArgumentNames()` shall be doable. Replacing JavaScript's `this` doesn't seem to be possible with `getArgumentNames()` functionality. However (as Enso is planning to replace `this` with `self`) we want to use `self` in JavaScript as well and that shall be no problem. (jaroslavtulach - Jun 10, 2022)
<hr />
Re: move from `this` to `self` – I think we should still stick to what the original language does – so `self` in py and `this` in js. This is how it works now anyway. (Marcin Kostrzewa - Jun 10, 2022)
<hr />
I've just installed `gu install ruby` into my GraalVM and then tried to use:
```
foreign ruby hello = """
    'Hello '
```
and got
```
now.enso[20:1-21:12]: Invalid foreign definition. Language ruby is not a supported polyglot language.
```
by using the `getArgumentNames()` approach, all the GraalVM languages would be supported. (jaroslavtulach - Jul 15, 2022)
<hr />

**Comment by JaroslavTulach** [comment]
Needed by #7755 to use `foreign arrow fn_name = """` syntax.
