### ISSUE TITLE
Crash on context loss

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5187]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/181899769).
<hr />

I have encountered a crash caused by context loss several times while trying to take a screenshot. (Side note: ImageMagick's `import` screenshot tool seems to be an effective way to cause a real context loss for testing.)

The crash occurs here: https://github.com/enso-org/enso/blob/998d078b9a1670ef7b5f5bcf1796244b2983c3ff/lib/rust/ensogl/core/src/system/gpu/data/texture/class.rs#L315

`unwrap()` is used because the `Texture` object cannot be constructed if the context has been lost.

**Comment by farmaazon** [comment]
We don't use WebGL anymore.
