### ISSUE TITLE
Filling CachedShape with a color.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5188]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184212741).
<hr />

## Why
**As** Enso IDE developer
**I want** to be able to replace color in cached texture
**So that** I can use cached textures to display Component Browser icons for differently colored Component Groups.

## Acceptance Criteria
```gherkin
Scenario: 
GIVEN I have a debug scene with cached shapes from the previous task #184212663
WHEN I open it
THEN I see additional shape instances filled with different color than the original.
```

## Blockers:
[#184212663](https://www.pivotaltracker.com/story/show/#184212663) blocked

**Comment by galin-enso** [comment]
QA: @galin-enso
