### ISSUE TITLE
Agree on specification for initial benchmarking machine

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5190]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/181109028).
<hr />

Following initial discussions agree on a specification for a benchmarking machine.

- Test the expanded Engine benchmarks on a range of different machines
- Assess the requirements of various existing data blending tools (Alteryx, Tableau Prep, Knime and others)
- Discuss with Ned
- Check the Hetzner server specification: https://www.hetzner.com/dedicated-rootserver

Arrange follow up meeting with Michal, Michael, James and Wojciech to agree on acquiring and setting up benchmarking machine

Notes from first meeting
https://docs.google.com/document/d/1NdYX1TyZjGvgTrWW1gT9cGj-Ww7L5UtEt7peuiSQ40I/edit?usp=sharing

**Comment by jdunkerley** [comment]
Closing as we have a benchmarking machine.
