### ISSUE TITLE
Runtime shapes ordering is not working for component browser icons.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5193]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183814171).
<hr />

Some of the icons are displayed in a wrong order when `layer.add_global_shapes_order_dependency` API is used. 

Details in discussion on Discord: https://discord.com/channels/401396655599124480/1041664588334235741

## Comments:
**Ilya Bogdanov** reports a new **STANDUP** for yesterday (2022-11-15):

**Progress:** debugging issue with runtime shapes ordering, found some clues and suspicious places in the code, but didn't find the ultimate solution. It should be finished by 2022-11-16.

**Next Day:** Next day I will be working on the [#183313944 task](https://www.pivotaltracker.com/story/show/183313944). open a final PR for the component browser design update, make sure everything matches Figma (Enso Bot - Nov 16, 2022)
<hr />

**Comment by farmaazon** [comment]
EnsoGL was replaced with Vue framework.
