### ISSUE TITLE
Default visualizations should be chosen based on a value's `to_default_visualization_data`.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5195]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/184390437).
<hr />

### Why

Better experience when exploring the output of nodes, as information will be presented in a more appropriate way.

**As User**
**I want ** the best possible visualization appear for every node
**So that ** I can make sense of the node's output

### Acceptance Criteria

```gherkin
Scenario: 
Given I have a project that contains a node with some data, e.g., of type `Table` or `Image`
When I open the visualisation
Then I see the best possible visualisaiton for the data (i.e., Table Visualisation or Image Visualisation)
```

**Notes:**
See old issues related to this here: https://github.com/enso-org/enso/issues/2951

Note that this is related, but not completely duplicate to https://www.pivotaltracker.com/story/show/184245839
However, both need a lot of similar preliminary work on the IDE controller side to be implemented (one-shot expressions, and using those to determining valid visualizations)

**Comment by jdunkerley** [comment]
Please note the method `default_visualization` provides the name for the standard visualization for a value. This could be merged into `to_default_visualization_data`.

**Comment by farmaazon** [comment]
Implemented in GUI2
