### ISSUE TITLE
Ability to navigate back to the home screen

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5200]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184382499).
<hr />

Currently, once you are in a project it is possible to open a new project or open a project from the file list.

We need a way to return to the home screen and select a new project or template.

**Comment by sylwiabr** [comment]
Already implemented
