### ISSUE TITLE
JS Objects show up as 'Error in to_text' in the --inspect Chrome Devtools debugger

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5204]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/184370169).
<hr />

As shown on the screenshot below.

Run the following program with the `--inspect` option:
```
from Standard.Base import all

main =
    x = Json.parse "[1,2,3]"
    y = Json.parse "42"
    z = Json.parse '{"x": 23}'
    IO.println [x,y,z]
```
and put a breakpoint on the last line and examine the scope in the debugger panel.

You can see that the `z` will show up as:
```
JS_Object Error in method `to_text` of [Value org.enso.interpreter.epb.runtime.PolyglotProxy@c6bf8d9]: Expected Text but got {"x":23}
```

Interestingly, `to_text` itself works, because once we continue execution, we can see that `[[1, 2, 3], 42, {"x":23}]` is printed as expected.

It may be some issue around the polyglot / debugger capabilities.

## Comments:
 (Radosław Waśko - Feb 1, 2023)
<hr />

**Comment by jdunkerley** [comment]
Works now.
