### ISSUE TITLE
Initial opening of the CB takes a long time

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5205]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184369947).
<hr />

The first time we open the component browser it takes a long time to get the values.

Looking at the logs on the network of the IDE it appears it takes 13-15s to get the suggestion database loaded.

## Comments:
 (James Dunkerley - Feb 1, 2023)
<hr />
Performance issue for @wdanilo.  (Michael Mauderer - Feb 1, 2023)
<hr />
It looked like it was taking the time in the language server getting the initial suggestionDB sent over so possibly one for @dmitry_bushev  (James Dunkerley - Feb 1, 2023)
<hr />
The initial processing of suggestions takes significant time of the LS startup, and can be definitely improved as discussed here https://discord.com/channels/401396655599124480/1055451457576509501/1055477146367295488  (Dmitry Bushev - Feb 1, 2023)
<hr />

**Comment by 4e6** [comment]
Sheduled #5068 and #5570 should speedup the delivery of initial suggestions. This issue should be re-evaluated after the linked optimizations are implemented.

**Comment by jdunkerley** [comment]
Lets review the state post completion of #5068 and see what is still needed.

**Comment by jdunkerley** [comment]
Closing this ticket as the performance has now been significantly improved.
