### ISSUE TITLE
Shortcut to jump to default view (see the whole workflow)

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5207]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184369908).
<hr />

## Why

**As** Enso IDE user
**I want** to be able to show my entire graph on the screen
**So that** I can see it quickly, zoom to another part etc.

## Acceptance Criteria
```gherkin
Scenario: 
GIVEN I have opened project with a big graph
WHEN I press a predefined shortcut
THEN The camera gradually moves this way it shows the entire graph + some margin.
```

**Comment by farmaazon** [comment]
Merging to #6206 as it has more details.
