### ISSUE TITLE
Improve shader recompilation and optimisations.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5210]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/184356911).
<hr />

To be done here:
- Glyphs do not support shader recompilation pipeline.
- Shaders are precompiled when shapes are moved between layers.
- Shaders are compiled on app run and this causes things to appear randomly on the screen. They should be compiled when the loader is visible.
- To be investigated if WASM compilation can be done on different thread (Web workers).

**Comment by jdunkerley** [comment]
@wdanilo - is there anything left to be done on this? is there any other connections to tickets on board.

Can you estimate the remaining work please.

**Comment by wdanilo** [comment]
I believe everything is done here. Thanks @jdunkerley! Closing.
