### ISSUE TITLE
Use EnsoGL spinner for the documentation panel

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5214]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/184315201).
<hr />

The currently used HTML-based spinner should be replaced with a unified Enso spinner. See `load_waiting_screen` method of the documentation panel.

**Comment by farmaazon** [comment]
No need for spinner, as the documentation is loaded instantly.
