### ISSUE TITLE
Error propagates through if_then_else expression

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5215]
This task is automatically imported from the old Task Issue Board and it was originally created by Dmitry Bushev.
Original issue is [here](https://www.pivotaltracker.com/story/show/184313342).
<hr />

### Steps to reproduce
Consider a program
```
from Standard.Base import all

main =
    err = Error.throw 42
    if True then 0 else err
```

### Expected
program returns `0`

### Actual
program returns `(Error: 42)`

## Comments:
	@radeusgd [wrote](https://discord.com/channels/401396655599124480/1067449951245844481/1067856871144300635) few examples:
```
if (Error.throw "A") then X else Y --> Error: A
if True then X else Error.throw Y --> X
if False then X else Error.throw Y --> Error: Y
if True then Error.throw X else Y --> Error: X
if False then Error.throw X else Y --> Y
```
that shall be part of the test suite. (jaroslavtulach - Jan 27, 2023)
<hr />

**Comment by jdunkerley** [comment]
Works now.
