### ISSUE TITLE
Add an indicator that the Virtual CG headers are unclickable

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5216]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/184313030).
<hr />

https://discord.com/channels/401396655599124480/1065293020322332783/1065293020322332783

There should be a clear indicator that the user can't press enter with the virtual component group header being selected.

Design the exact implementation with WD

**Comment by farmaazon** [comment]
No Component Group headers in new CB
