### ISSUE TITLE
Revise `Vector.zip` error handling

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5218]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/184306776).
<hr />

Our `Table.zip` implementation has a nice `keep_unmatched : Boolean | Report_Unmatched` functionality that allows to specify what to do if zipped tables have differing row counts.

`Vector.zip` blindly truncates to the shorter of the two vectors.

It may be good to align its API with the Table one. We usually do not do warnings in the most primitive types like Vector, but we could probably Report_Unmatched as a dataflow error. If `keep_unmatched=True` we can do the longer vector and pad with `Nothing`s.

We need to revise if we should keep the current behaviour as default or change it. I think it may be safer to default to throwing a dataflow error if the lengths do not match (usually when zipping we _do_ expect length to match) and only allow the user explicitly tell that they expect the lengths may differ and explicitly say what should happen in that case (by setting True/False the users specifies if we keep the longer vector and pad or truncate to the shorter one).

**Comment by jdunkerley** [comment]
Will replace with a new issue
