### ISSUE TITLE
Make text Selectable in Visualization

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5221]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184181426).
<hr />

## Why
**As** Enso IDE user 
**I want** to be able to select text in text visualization
**So that** I can copy it and paste elsewhere

## Acceptance Criteria
```gherkin
Scenario: 
GIVEN I opened the project and show some text/json visualization
WHEN I drag cursor over text
THEN the text is selected, and I can copy it and paste elsewhere using shortcut
```

**Comment by sylwiabr** [comment]
duplicate of https://github.com/enso-org/enso/issues/5217
