### ISSUE TITLE
Test and optimize performance of Text Visualization

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5222]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/184278986).
<hr />

### Why

The new lazy text visualization should be optimized for performance to be able to handle reasonable large data. 

**As a Enso User**
**I want ** to be able to scroll through large data
**So that ** I can explore large datasets

### Acceptance Criteria

```gherkin
Scenario: 
Given a project with a text node that is very large(tm)
When I scroll through the text visualisaiton
Then there should be no delays from processing and sending the text data from the backend
```

**Notes:**

This requires profiling/optimizing the Enso code that generates the response in the std lib. 
Part of this task should be to determine a reasonable size of data that should be usable on a reference machine, and maybe adding of benchmarks to spot performance regressions.

## Comments:
Michael: "It might be more efficient for someone from the stlib or engine team to look as this, as this is pure Enso code" 
FYI @jdunkerley 
 (Greg Ociepka - Feb 1, 2023)
<hr />

**Comment by jdunkerley** [comment]
Closing until new Text visualization as part of the new IDE code.
