### ISSUE TITLE
Opening visualization with space does not always work.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5223]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184266469).
<hr />

https://discord.com/channels/401396655599124480/1064967872012615872

There is no reliable reproduction scenario, but here are some clues:
* Sylwia reported, that she usually spots the issue when recording screens
* I (Adam) reproduced the issue in browser when build with `ide watch --skip-wasm-opt`.

**Comment by sylwiabr** [comment]
This is much worse with newest (today) nightly - it happens almost every time @MichaelMauderer

**Comment by vitvakatu** [comment]
QA: @vitvakatu

**Comment by hubertp** [comment]
I noticed that first `AttachVisualization` operation always timeouts after startup. So I'm not sure this will fix all problems with visualization.

**Comment by MichaelMauderer** [comment]
Do we know why they time out? Timeouts do sound like an issue on the engine side, though. Unless the IDE is making weird requests. In either case, we might want to file an issue and investigate.

**Comment by hubertp** [comment]
@MichaelMauderer Good point. If I can reproduce this consistently I will investigate (seems like it is happening less often).

**Comment by farmaazon** [comment]
@hubertp see also #5745 I put there my reproduction scenario and a bit of investigation.
