### ISSUE TITLE
Wrong behavior of Vector.new_builder in the IDE

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5231]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/183979125).
<hr />

It was found during [Advent of Code](https://discord.com/channels/401396655599124480/1047834987141025794/1048173011854950460) that using `Vector.new_builder` in the IDE isn't easy/possible. In spite of the pipeline adding just a single element into the builder, the result somehow accumulates! Try editing the value 20 and see the visualization.

## Comments:
 (jaroslavtulach - Dec 7, 2022)
<hr />
I think it is a general issue with stateful computations in an interactive environment.

That's why we should probably keep such imperative constructs for internal usage in our implementations, but they shouldn't really be exposed to the users in the GUI. (Radosław Waśko - Dec 7, 2022)
<hr />
It's OK, if we somehow disallow an IDE node to return `Vector.Builder` type. Or treat such nodes as non-cachable? Or at least have a way to re-run the node? Anything is fine, but not the current state where I just type `Vector.new_builder` and the IDE starts to misbehave. (jaroslavtulach - Dec 7, 2022)
<hr />
	@jtulach Fair! Shall we start a discussion on Discord about it? Seems like possibly better place to get more people involved. Later we can summarize the conclusions in the ticket here. (Radosław Waśko - Dec 7, 2022)
<hr />

**Comment by jdunkerley** [comment]
`Vector.new_builder` has been replaced with a more "functional" interface.
