### ISSUE TITLE
Displaying and understanding "self" in Component Browser

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5232]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183523327).
<hr />

## Why

**As** Enso IDE user
**I want** Component Browser to recognize "self" argument and suggest only methods applicable to its type
**So that** I can focus on my data type operations.

## Details

The searcher controller should already know if the cursor position is currently in the last segment of `.` Infix chain. If there is only one segment before, the suggestion database should be looked up for the Local entries matching the name and being in the searcher scope. If found, the Engine shall be asked for suggestions for the type of this local variable. Also, in that case, the suggestions shall not be filtered by context.

Additionally, adding the "this" argument to expression input when opening the Component Browser with known source type is also in scope of this task.

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN I have a newly created project
WHEN I open Component Browser and type any of the expression listed below
THEN I get suggestions for Vector type only
WHEN I add a node `operator1.length` and start editing it again placing cursor at the end of the `length` word
THEN I see `length` suggestion for Vector type.
```
```
operator1.
2 + operator1.
2 + (operator1.
```

**Comment by farmaazon** [comment]
Implemented in GUI2
