### ISSUE TITLE
initialization time of grid-view is very slow

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5234]
This task is automatically imported from the old Task Issue Board and it was originally created by Paweł Grabarz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184223891).
<hr />

Currently grid-view initialization time is prohibitively expensive, and we are deferring it in the widgets until necessary. Otherwise the IDE startup can take multiple minutes on non-trivial projects.

In node Widgets module, we should be able to replace `LazyDropdown` with ordinary `Dropdown` view and not see any performance degradation.

**Comment by farmaazon** [comment]
@kazcw isn't it already done by you?

**Comment by kazcw** [comment]
> @kazcw isn't it already done by you?

I haven't worked on grid view, but it is slow because text rendering is slow. I will be looking in to that this week: #5669. Closing this as a duplicate.
