### ISSUE TITLE
Remove UFCS assumptions from the connection discovery algorithm.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5240]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184130005).
<hr />

https://discord.com/channels/401396655599124480/1055186227160170556/1055238189226401824

The method calls should not be discovered as used aliases in double representation alias analysis.

**Comment by farmaazon** [comment]
Done in GUI2
