### ISSUE TITLE
Add parsed documentation to suggestion database entries

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5242]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/184100456).
<hr />

Needs to be planned by Engine Team. 
See discussion: https://discord.com/channels/401396655599124480/1055451457576509501

**Polemic: ** To improve the initial UX we need to make suggestion _database entries lighter_, not to _add anything_ to them. Tracked as #184117587

## Blockers:
[#182497187](https://www.pivotaltracker.com/story/show/#182497187) blocked

**Comment by farmaazon** [comment]
Already done.
