### ISSUE TITLE
Correctly place newly created example nodes.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5244]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/184100448).
<hr />

**As** a user of the component browser (CB)
**I want** to find new example nodes in a good position
**So that** they do not overlap other nodes, otherwise disturb the open project, or are hard to find.

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN a project with an open CB with some documentation with examples
WHEN I click an example item
THEN the example is added as a new node to the project in a location that a new node would be created. 
```

**Comment by farmaazon** [comment]
Merging with https://github.com/enso-org/enso/issues/5245
