### ISSUE TITLE
Add an on-click hook to the example cards that prints the example data to the console

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5246]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/184100434).
<hr />

**As** developer of the component browser (CB)
**I want** to have an easy hook to react to on-click events
**So that** I can add functionality that reacts to a click on the example item

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN a demo scene with a documentaiton panel that shows documentation with examples
WHEN I click an example item
THEN the example items data is printed to the console.
```

**Comment by farmaazon** [comment]
Merging with https://github.com/enso-org/enso/issues/5245
