### ISSUE TITLE
Cannot access field of custom type defined in project

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5249]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/184096097).
<hr />

Thread: https://discord.com/channels/401396655599124480/1050713360511016970

As shown on the screenshots - if I define a custom type (editing the Main.enso in a text editor before launching the GUI), then create an instance of it -I can visualize it nicely to JSON.

See that I have fields foo and bar.
I select the node containing the instance, press Tab and write foo to access that field. After pressing enter, as seen on 2nd screenshot - I get an error that method foo could not be found.

Interestingly, if I close the IDE and run that exact file in the CLI it all works. Also, once I restart the IDE it also works - correctly fetches the field.

So it seems that fetching the field does not work when the node is created.

## Comments:
 (Greg Ociepka - Dec 23, 2022)
<hr />
After I restarted, the original accessor that was present there now works, but then when I add another one - it is broken again:
 (Greg Ociepka - Dec 23, 2022)
<hr />
Low priority - will be a while before users define types. (James Dunkerley - Feb 3, 2023)
<hr />

**Comment by jdunkerley** [comment]
As now a newer ticket with clearer description closing this.
