### ISSUE TITLE
Stop silently ignoring name resolution errors in type signatures

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5256]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/184080961).
<hr />

While debugging some other ticket, I noticed that we seem to silently ignore errors when resolving names in type signatures. 
These appear to be on purpose as defined by the code in
https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/scala/org/enso/compiler/pass/resolve/TypeNames.scala#L81

Rather than ignoring them, we should always report the error so that missing imports are added.

This may cause issues with dropdowns, and the information sent by language-server in general.

**Comment by jdunkerley** [comment]
@hubertp - I believe this is done can you verify if it is done please?

**Comment by jdunkerley** [comment]
Verified this works - now get an error at compile time.
