### ISSUE TITLE
Expand tests for `query` and `read`.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5262]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183390662).
<hr />

The current tests for `Database.query` do not test `Raw_SQL` and `Text` inputs for the query.

Additionally, tests for `read` should be expanded as well.

**Comment by jdunkerley** [comment]
Lots more tests than used to be.
