### ISSUE TITLE
Implement Excel_Files and Excel_Connection

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5263]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183377997).
<hr />

Allow connection to a collection of Excel files:

```python
Excel_Options.Excel_Files path:(File|Text) recursive:Boolean=False patterns:(Vector Text)=[”*.xlsx”, ”*.xlsm”, ”*.xls”]
```

- Ability to connect to a single workbook or a folder of workbooks.
- Users can provide either a file or folder path.
- The user can choose to scan subfolders using the `recursive` option.
- By default, it will look at standard Excel extensions but user can set patterns as they wish.

The Connection API would be mapped as follows:
- Database ==> Excel filename.
- Schema ==> Not used - Nothing.
- Table ==> Worksheet name or range name
- The `query` function will return an `Unsupported_Operation` error.
- The `read` method will not support SQL but will allow:
  - Table names.
  - Range names.
  - Range address.
  - Otherwise an `Illegal_Argument` error should be returned.

## Blockers:
[#183578491](https://www.pivotaltracker.com/story/show/#183578491) blocked

**Comment by jdunkerley** [comment]
Separating off the directory connection work from this. But a new Excel_Workbook covers the other behvaiors.
