### ISSUE TITLE
Implement Delimited_Files and Delimited_Connection

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5264]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183390797).
<hr />

Allow connection to a collection of delimited files:

```python
Delimited_Options.Delimited_Files path:(File|Text) recursive:Boolean=False patterns:(Vector Text)=[”*.csv”, ”*.tsv”]
```

- Ability to connect to a single file or a collection of files.
- Users can provide either a file or folder path.
- The user can choose to scan subfolders using the `recursive` option.
- By default, it will look at standard extensions but user can set patterns as they wish.

The Connection API would be mapped as follows:
- Database ==> Filename.
- Schema ==> Not used - Nothing.
- Table ==> Not used - Nothing.
- The `query` function will return an `Unsupported_Operation` error.
- The `read` method will have a slightly different API:
  - **Needs to be thought out.**

## Blockers:
[#183578491](https://www.pivotaltracker.com/story/show/#183578491) blocked

**Comment by jdunkerley** [comment]
The new `read_many` api supersedes this.
