### ISSUE TITLE
Adjust starts_with and ends_with to avoid computing grapheme length

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5266]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183794867).
<hr />

Current implementation means that the length is recomputed rather than using the property.

The length can be passed in from Enso and then the caching will help.

**Comment by jdunkerley** [comment]
If we need to improve performance we can dig into such optimisations when needed.
