### ISSUE TITLE
Add custom Postgres `tables` function.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5269]
This task is automatically imported from the old Task Issue Board and it was originally created by James Dunkerley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183390699).
<hr />

The JDBC query for tables does not support listing tables for another database.

This task is to implement a custom function returning the list of tables with across all databases and schemas.

Standard JDBC implementation is https://github.com/pgjdbc/pgjdbc/blob/0b097fd4a8e9990a9b86173d58633cd88d263b0b/pgjdbc/src/main/java/org/postgresql/jdbc/PgDatabaseMetaData.java#L1268

## Comments:
**Radosław Waśko** reports a new **STANDUP** for today (2022-11-18):

**Progress:** Fixed issues with the Text.match PR, making it ready to merge. Reviewed next round of James' Base refactors. Some bookkeeping. Started work on Postgres.tables - created a basic test script and looking into what is possible. Clarifying the requirements. It should be finished by 2022-11-22.

**Next Day:** Next day I will be working on the [same task](https://www.pivotaltracker.com/story/show/183390699). Clarify the specification and continue working on the implementation. Add some proper tests. (Enso Bot - Nov 18, 2022)
<hr />
https://github.com/enso-org/design/blob/main/epics/basic-libraries/database-read/design.md#tables-and-views (James Dunkerley - Nov 18, 2022)
<hr />

**Comment by jdunkerley** [comment]
Current solution works as you need to make a new connection to switch DB anyway.
