### ISSUE TITLE
Display objects that have both a child/parent relationship in EnsoGL and in the DOM, should be positioned correctly. 

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5272]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/184051310).
<hr />

## Why
**As** Developer 
**I want** to be able to parent `DomElement`s with each other while also use the EnsoGL API to set their position.
**So that** I can create visuals based on DOM elements with ease. 

## Acceptance Criteria
```gherkin
Scenario: 
GIVEN the demo scene pasted here: https://pastebin.com/G7Hc5qe6 with line 56 uncommented
WHEN looking at the demo scene
THEN the two square should move in sync. 
```

## Notes
How this should be fixed should be planned in more detail. See the discussions below for the current state of the discussion. 

## Resources
Discord thread with discussion about this issue: https://discord.com/channels/401396655599124480/1050037851376586812

**Comment by farmaazon** [comment]
EnsoGL is removed from repository.
