### ISSUE TITLE
Component browser changes selection when dragging out of the documentation panel

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5274]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/184042722).
<hr />

## Steps to reproduce:
1. Open a component browser
2. Hover the documentation panel, hold the left mouse button and select some text inside the documentation panel
3. Drag the mouse over to the component list panel while holding the button
Alternatively:
2. Hover the documentation panel, start scrolling by holding the middle mouse button

## Expected:

The component list panel does not react on mouse events that start over the documentation panel.

## Actual

The selected entry changes and the documentation panel's content is updated.

## Notes

From [discord thread](https://discord.com/channels/401396655599124480/1051826510513836153/1051826510513836153)
> On windows, a way to scroll through a page is to press the middle mouse button and drag the mouse away from the place where the button was pressed. The mouse cursor then can exit the documentation panel while still interacting with it. When during such an event the mouse cursor moves over the component browser, it highlights the component above which the mouse is hovered, while interacting with the documentation panel still.
Similarly, when selecting text from the documentation panel, if during text selection the mouse exits the documentation panel and hovers over the component browser the documentation panel changes to a different component while the selection is still active.

**Comment by farmaazon** [comment]
ATM in GUI2 documentation panel selection does not work at all (reported as #9175). But clicking inside documentation panel and moving the cursor over the component list does not select a component.
