### ISSUE TITLE
Displayed table visualization disappears on node recomputation

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5276]
This task is automatically imported from the old Task Issue Board and it was originally created by Dmitry Bushev.
Original issue is [here](https://www.pivotaltracker.com/story/show/184034775).
<hr />

Sometimes when I refresh some computation (for example change the input and the whole flow is recomputed), the Table vis 'disappears' - i.e. it becomes a full white square with no contents.

Then when I click space to hide it and show it again, the nice contents of Table vis show up for a split-second and disappear again. I need to hide-and-show it a few times to get it to 'stick' and stay displayed.

Notes
https://discord.com/channels/401396655599124480/1049924754582274088/1050022662795182100

## Comments:
**Dmitry Bushev** reports a new **STANDUP** for today (2022-12-21):

**Progress:** Started wornking on the issue. Trying to reproduce the issue. It is not particularly easy to do. Also discovered that the logic that shows the vis window is not connected to one that updates the contents. This makes me think that it could be the issue somewhere in the frp logic of IDE. It should be finished by 2022-12-22.

**Next Day:** Next day I will be working on the [#184034775 task](https://www.pivotaltracker.com/story/show/184034775). Continue working on the task (Enso Bot - Dec 21, 2022)
<hr />
**Dmitry Bushev** reports a new **STANDUP** for today (2022-12-22):

**Progress:** Continue wornking on the issue. Added even more logging, Tried different cases, tried adding delays, but was not able to come up with a repro. At least in chrome. Now thinking, maybe it is an Electron related issue. It should be finished by 2022-12-22.

**Next Day:** Next day I will be working on the [#184034775 task](https://www.pivotaltracker.com/story/show/184034775). Continue working on the task (Enso Bot - Dec 22, 2022)
<hr />
The issue occurs quite randomly, and happens very rarely. This makes it very hard to reproduce. I wasn't able to do it in fact. Leaving for now. (Dmitry Bushev - Feb 1, 2023)
<hr />
	Changed the title of this task not to be confused with other issue we have with spacebar press
We need more reliable data on reproduction steps for that
@michael_mauderer @dmitry_bushev do you have any idea on how we can detect the repro steps other than trying it over and over again? (Greg Ociepka - Feb 1, 2023)
<hr />
Not sure this is occurring any more - we have overhauled a lot of the JSON/Viz flow so possible it has been cured.
We are removing `release` from it unless we get it to re-occur. (James Dunkerley - Feb 1, 2023)
<hr />

**Comment by 4e6** [comment]
I didn't see this issue happening for a long time. The original one was created in December. Closing for now
