### ISSUE TITLE
Support for custom target-dir when building wasm

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5277]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/184028498).
<hr />

See https://github.com/rustwasm/wasm-pack/pull/1082

**Comment by mwu-tow** [comment]
The `wasm` target no longer exists. The issue is not relevant anymore.
