### ISSUE TITLE
Generate HTML for Examples section

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5279]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/184024198).
<hr />

## Why
**As** Enso User
**I want** to see a examples in the documentation
**So that** I can quickly learn how to use the API

Applying necessary Tailwind CSS styles is in the scope of this task.

## Acceptance Criteria

```gherkin
Scenario: Module
GIVEN the documentation panel debug scene
WHEN I see the documentation of the mock module entry
THEN I can see a list of examples defined for the current module in the "Examples" section of the documentation
AND The list of examples is styled as in design doc

Scenario: Type
GIVEN the documentation panel debug scene
WHEN I see the documentation of the mock type entry
THEN I can see a list of examples defined for the current type, its methods or constructors in the "Examples" section of the documentation
AND The list of examples is styled as in design doc
```

## Notes

Refer to design doc for the layout of the sections, also see [this document](https://docs.google.com/document/d/1HIzgRAqJ44Ua8qlggPq7FxqD41wFSMtTtUqVM17TpXw/edit?usp=sharing)

**Comment by vitvakatu** [comment]
Implemented
