### ISSUE TITLE
Generate HTML for Types section

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5280]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/184024179).
<hr />

## Why
**As** Enso User
**I want** to see a list of all Types in the documentation
**So that** I can find the needed one

Applying necessary Tailwind CSS styles is in the scope of this task.

## Acceptance Criteria

```gherkin
Scenario:
GIVEN the documentation panel debug scene
WHEN I see the documentation of the mock module entry
THEN I can see a bullet list of all module's types in the "Types" section with their descriptions
AND The bullet list is styled as in the design doc
```

## Notes

Refer to design doc for the layout of the sections, also see [this document](https://docs.google.com/document/d/1HIzgRAqJ44Ua8qlggPq7FxqD41wFSMtTtUqVM17TpXw/edit?usp=sharing)

**Comment by vitvakatu** [comment]
Implemented
