### ISSUE TITLE
chromeinspector fails when displaying EnsoBigInteger

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5285]
This task is automatically imported from the old Task Issue Board and it was originally created by Pavel Marek.
Original issue is [here](https://www.pivotaltracker.com/story/show/184017959).
<hr />

Running enso with chromeinspector, it fails when trying to display a big integer. Stack trace as first comment.

Inspiration from graal-js `BigInt`: https://github.com/oracle/graaljs/blob/master/graal-js/src/com.oracle.truffle.js/src/com/oracle/truffle/js/runtime/BigInt.java

Related:
- https://www.pivotaltracker.com/story/show/183798184
- https://www.pivotaltracker.com/story/show/183855919

## Comments:
stack trace (Pavel Marek - Dec 12, 2022)
<hr />

**Comment by jdunkerley** [comment]
Works now.
