### ISSUE TITLE
Restore the dead backend/connection

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5288]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/184000475).
<hr />

### Why

**As Enso IDE user**
**I want ** to use IDE which is quite resistant to connection breakage or language server deaths
**So that ** I can work smoothly even when some rare backend crash appear.

**As Enso Engine developer**
**I want ** to not be forced to restart IDE when backend dies.
**So that ** I can just kill the stuck backend when I'm testing something.

### Acceptance Criteria

```gherkin
Scenario: 
Given
When
Then
```

**Notes:**

**Comment by jdunkerley** [comment]
Need to consider how to detect failures of the backend better.

**Comment by farmaazon** [comment]
What exactly is in the scope of this task? We have already one for making IDE reconnecting with the backend #5202 (it's quite a task: we need to restore the engine state after reconnecting). Is #5288 (this) just a duplicate, or it covers some engine stuff to add?

**Comment by jdunkerley** [comment]
ok guess this one is a duplicate then - so we can close.
