### ISSUE TITLE
Check if we can use sqlite in wasm

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5292]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183992227).
<hr />

We want to check if we can use SQLite compiled to WASM to store our suggestion database on the IDE side.

Things to consider:
- Is it possible to build SQLite to wasm?
- How hard is it from build process standpoint?
- How should we modify our build pipeline to make it working?

Alternatives to SQLite may be considered if time allows.

## Comments:
I don't like this issue TBH, it assumes we want to use SQLite, while we did not have conversation about what we might want to use. Maybe other in-memory databases written in pure Rust? SQLite may not be the best choice and I feel it is not a good choice here. Instead of this task we should start with investigation what are the options. Also, based on Adam's reply, we should NOT do it before the first release, so this task should rather not be planned now. (Wojciech Daniło - Dec 12, 2022)
<hr />
This task should go to the backlog until better times. I just wonder how I can keep the connection with this user story. @gregociepka could you help me? (Ilya Bogdanov - Dec 12, 2022)
<hr />
	@ilyabogdanov Simplest way is to push it further down the timeline (I have moved to March) - this way we will still have it in the midst of interest but will be able to reschedule it later on. (Greg Ociepka - Dec 20, 2022)
<hr />

**Comment by farmaazon** [comment]
We decided to use reactive maps in GUI2, and they serve well.
