### ISSUE TITLE
Truncation ellipsis of text labels doesn't change color

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5294]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183960509).
<hr />

The color of the ellipsis (`...`) of the truncated text is not updated when the color of the text is changed.

It can be reproduced on component_list_panel debug scene.

![](https://user-images.githubusercontent.com/6566674/205297344-d8d46e68-8c46-4e5a-b7f5-5e23014df23f.png)

(note the colors of the ellipsis glyphs in the dimmed component groups)

**Comment by farmaazon** [comment]
No ellipsis nor dimming in new CB.
