### ISSUE TITLE
Stop and restart functionality on button action.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5295]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/183862015).
<hr />

When a user makes a mistake and i.e. start processing too big data, he should be able to stop the calculation without leaving Enso. 

After stopping the evaluation and fixing the issue he should be able to restart the evaluation without reloading the IDE.

## Blockers:
[#183862007](https://www.pivotaltracker.com/story/show/#183862007) resolved

**Comment by farmaazon** [comment]
Marked as User Story as I doubt we will handle it as a single GUI task.

**Comment by farmaazon** [comment]
Actually, I missed the fact we already have shortcuts for it. So, it's not a user story, but just the task of implementing buttons.

We need design for buttons first, so it's blocked by https://github.com/enso-org/design/issues/52

**Comment by farmaazon** [comment]
We don't expect making it in the new design.

From @jdunkerley:
>  we need instead the libs guys to make sure all is abortable (which we are trying to do!)
we probably do want a restart backend and refresh button but lets spec that up and add later
