### ISSUE TITLE
GraalVM Bump 23.0 to resolve BigInteger issues

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5300]
Official `BigInteger` support has been integrated into forthcoming GraalVM 23.0: https://github.com/oracle/graal/pull/5490/files#diff-b9f3acd7cf907a1ea1fa5dd88bcb3c544622d1665cea25cdf1ffe54f4928738cR991. Use it and remove the hacks currently in place.

Discord discussion: https://discord.com/channels/401396655599124480/1045300007995179048

Related:
- https://www.pivotaltracker.com/story/show/184322520
- A "warning support" had to be added to Truffle DSL because of `fitsBigInteger` - https://github.com/oracle/graal/pull/5490/files#diff-f8f6123284e302854d17f6ac7d4a5e2c488c4c7ed6c894a128246180ab647e68R270 - otherwise every existing Node that has exported `isNumber` would no longer compile. With 23.0 it compiles, but a warning will be issued to also implement `fitsBigInteger` and `asBigInteger` messages.

## Tasks:
- [x] https://github.com/oracle/graal/pull/5490/

Original issue is [here](https://www.pivotaltracker.com/story/show/183934416).

## Follow-up issues
- #7213
- #7214

**Comment by jdunkerley** [comment]
Currently not released and this isn't yet resolved in GraalVM.

**Comment by JaroslavTulach** [comment]
As of [yesterday](https://graalvm.slack.com/archives/CNBFR78F9/p1682345977331569):

> next feature release will go live on June 13.

e.g. GraalVM 23.x will not appear sooner than on June 13.

**Comment by JaroslavTulach** [comment]
GraalVM 23.0 is out and it comes with [fitsInBigInteger](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/interop/InteropLibrary.html#fitsInBigInteger-java.lang.Object-) support.

**Comment by jdunkerley** [comment]
As is now released can we investigate the complexity involved in this ticket and then we can assess if we want to do pre the sales release.
