### ISSUE TITLE
Implement a sort optimization for Between Join_Condition

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5303]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/183913337).
<hr />

TODO: figure out more details how it should work

In short, currently we rely on a full scan for Between but should be able to get better results by sorting one table by the key.

This needs to co-operate with the index-based join - sorting the hashmap buckets.
It also needs to support multiple between levels - probably by relying on lexicographically ordering between the levels

**Comment by radeusgd** [comment]
Indirectly related #7767
