### ISSUE TITLE
Enable Enso debugging directly in vscode via debug adapter protocol

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5305]
This task is automatically imported from the old Task Issue Board and it was originally created by Pavel Marek.
Original issue is [here](https://www.pivotaltracker.com/story/show/183900090).
<hr />

There should be *Debug adapter protocol* (DAP) tool in truffle tools, which is a native debugging protocol in vscode. We should incorporate this tool, same as we do with `chromeinspector` (`--inspect` option), and verify that it works.

Related issues:
- https://www.pivotaltracker.com/story/show/183855919
- https://www.pivotaltracker.com/story/show/183892554

## Blockers:
[#184126398](https://www.pivotaltracker.com/story/show/#184126398) resolved

**Comment by jdunkerley** [comment]
We have a decent VS Code debugger set up now.
