### ISSUE TITLE
Improve parser error message when `...` is method's body

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5307]
This task is automatically imported from the old Task Issue Board and it was originally created by Pavel Marek.
Original issue is [here](https://www.pivotaltracker.com/story/show/183881839).
<hr />

When trying to run a file that contains just `func = ...`, parsing fails with:
```
Execution finished with an error: org.enso.compiler.exception.UnhandledEntity: Fatal: Unhandled entity in translateExpression = AutoScope[" ", "...", AutoScope["", "...", ]]
```
which seems confusing. Instead, I would expect something like:
```
Compiler encountered errors:
tmp.enso[1:8-1:11]: Unexpected expression
```

**Comment by jdunkerley** [comment]
Returns a syntax error.
