### ISSUE TITLE
Lack of space between a field, colon and type leads to a cryptic error

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5308]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/183865129).
<hr />

Looks like a problem still in new parser. With the old parser it was crashing as well but earlier. I believe I was told this was fixed (at least on the Rust side).

```
type A
    Foo (x: Integer)
```
leads to
```
Execution finished with an error: org.enso.compiler.exception.UnhandledEntity: Fatal: Unhandled entity in translateArgumentDefinition = App["", "x: Integer", Invalid["", "x:", `:` operator must be applied to two operands., OprApp["", "x:", Ident["", "x", Ident["", "x", false, 0, false, false]], Either{right=Operator["", ":", ]}, null]], Ident[" ", "Integer", Ident["", "Integer", false, 0, true, false]]]
```

## Comments:
The parser is emitting an `Invalid` for this case, but `translateArgumentDefinition` currently doesn't expect error nodes. (Keziah Wesley - Nov 23, 2022)
<hr />

**Comment by jdunkerley** [comment]
Fixed we will get a Syntax Error.
