### ISSUE TITLE
Move component browser icons to a separate crate

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5313]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183814161).
<hr />

We want to define all the icons used in the component browser in a single crate for future performance optimizations. `ide_view_component_list_panel_icons` crate is a perfect place for them.

This task has a serious blocker.

## Blockers:
[#183814161](https://www.pivotaltracker.com/story/show/#183814161) blocked

**Comment by farmaazon** [comment]
In GUI2, we keep all icons in SVG file.
