### ISSUE TITLE
The selection unnecessarily jumps to local scope when switching breadcrumbs

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5314]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183813820).
<hr />

TBD

This needs further investigation. Originally reported here: https://github.com/enso-org/enso/pull/3832#issuecomment-1309267768

**Comment by farmaazon** [comment]
No longer valid in new CB
