### ISSUE TITLE
Local scope section filling algorithm

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5315]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183813810).
<hr />

## Why

**As** Enso User
**I want** to see local scope entries centered by default
**So that** their position matches the positions of first entries in other sections

## Acceptance Criteria

Currently, the local scope section is filled left-to-right. We need to change that and fill the columns in order center-left-right.

```gherkin
Scenario: 
GIVEN The component browser with local scope section opened
WHEN There is a single element in the local scope section
THEN It is positioned in the middle column
WHEN There are two elements in the local scope section
THEN They fill the center and left columns, the first entry is moved to the left column
WHEN There are three and more entries in the local scope section
THEN They are evenly distributed between all three columns in alphabetical order left-to-right, bottom-to-top
```

**Comment by farmaazon** [comment]
No longer valid in new CB.
