### ISSUE TITLE
Improved component groups dimming

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5316]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183813766).
<hr />

## Why

**As** Enso User
**I want** to see the currently hovered/selected section highlighted
**So that** I can clearly see the section I'm working with

## Acceptance Criteria

Basically, we want to highlight the section with the most recently moved selection/hover and dim every other section.

```gherkin
Scenario: 
GIVEN the opened component browser with more than one section filled
WHEN I select an entry from any section
THEN every component group in other sections is dimmed
AND WHEN I hover the entry from the dimmed section with the mouse
THEN The hovered section becomes highlighted, and the currently selected one becomes dimmed
WHEN I move the selection using the keyboard
THEN The section with the currently selected entry becomes highlighted, and every other section is dimmed
```

## Notes
Do we need to display the currently highlighted section in the section navigator when hovering? Should the breadcrumbs update as well? Consult with WD

**Comment by farmaazon** [comment]
No longer needed in new CB.
