### ISSUE TITLE
Typing `.` in searcher adds space before it

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5325]
This task is automatically imported from the old Task Issue Board and it was originally created by Greg Ociepka.
Original issue is [here](https://www.pivotaltracker.com/story/show/183782923).
<hr />

https://discord.com/channels/401396655599124480/1040667547520995378

## Comments:
Should be fixed in #183523327  (Adam Obuchowicz - Nov 14, 2022)
<hr />

**Comment by sylwiabr** [comment]
@xvcgreg please confirm that it is fixed

**Comment by farmaazon** [comment]
The new task is #5232
