### ISSUE TITLE
Support for Panel Focus Selection Directional Modifier.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5326]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/183618034).
<hr />

## Why

**As** Enso Developer
**I want** the Panel Focus Selection Directional Modifier key handled in Component Browser
**So that** I can implement rendering a blue border around the Panel with Active Focus.

## Acceptance Criteria

```gherkin
Scenario:
GIVEN an open Component Browser
WHEN I hold the Panel Focus Selection Directional Modifier and press one of the arrow keys on the keyboard
THEN a debug message is printed in Developer Console informing which Focus Area is selected as Active Focus Area
WHEN I hold the Panel Focus Selection Directional Modifier and press Backtick key or 0 key on the keyboard
THEN a debug message is printed in Developer Console informing that the Expression Input Panel Area is selected as Active Focus Area.
```

## Notes
- Focus Areas that need to be supported:
    - the Component List area of the Component Browser List Panel,
    - the Section Navigator area of the Component Browser List Panel,
    - the Expression Input Panel,
    - the Documentation Panel,
    - the Visualization Panel.
- The Panel Focus Selection Directional Modifier is defined differently on Mac vs. on Windows and Linux. This difference can be encapsulated in a new macro to be used when defining key combinations in `default_shortcuts` functions.

## Comments:
**Paweł Grabarz** reports a new **STANDUP** for today (2022-11-07):

**Progress:** Discussed the arch approach for central focus system, task got estimated. Now implementing focus manager for component browser specifically. It should be finished by 2022-11-14. (Enso Bot - Nov 7, 2022)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for the provided date (2022-11-02):

**Progress:** Meeting with Adam on planned focus changes. Investigating application loading times. It should be finished by 2022-11-14. (Enso Bot - Dec 12, 2022)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for the provided date (2022-11-03):

**Progress:** Started implementing application-wide focus manager, for now scoped to component browser. It should be finished by 2022-11-14. (Enso Bot - Dec 12, 2022)
<hr />
**Paweł Grabarz** reports a new **STANDUP** for the provided date (2022-11-04):

**Progress:** Another meeting with Adam on focus planning. Scrapping focus manager implementation and switching to compile time optimizations task. It should be finished by 2022-11-14. (Enso Bot - Dec 12, 2022)
<hr />

**Comment by farmaazon** [comment]
CB focus design changed.
