### ISSUE TITLE
Move `deprecated_focus*` events to the new events api

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5328]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/183776234).
<hr />

The event endpoints generated by `ensogl::define_endpoints/2` macros were recently prefixed with the `deprecated_` prefix. They should be replaced by the new mechanism built into display objects.

**Comment by farmaazon** [comment]
EnsoGL is removed.
