### ISSUE TITLE
Bump msdfgen version used in msdfgen_wasm library.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5330]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183747513).
<hr />

## Description
The newer version of msdfgen_was has more useful features and fixed bugs. As a result, the displaying of mplus1 font should not require any magic numbers (see todo annotations referring to this task).

**Comment by farmaazon** [comment]
msdgen_wasm library is removed from repository.
