### ISSUE TITLE
Release-mode parser builds

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5331]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/183740720).
<hr />

When building a release-mode IDE or engine distribution, we should also build `libenso_parser` in release mode. This is accomplished by adding the `--release` flag to the `cargo build` command for `enso-parser-jni`, and obtaining the resulting library from the `release` subdirectory of the rust targets path, instead of the `debug` directory.

**Comment by mwu-tow** [comment]
This probably applies to the `sbt` building the native binary of the Rust parser. 
@JaroslavTulach Is this issue still relevant?
