### ISSUE TITLE
Switching visualizations in the Visualization Preview does not work.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5339]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183602469).
<hr />

### Steps to reproduce
1. Open any project
2. Open Component Browser without any node selected
3. select "number input"
4. Try to switch the visualization by opening visualizations menu

### Expected

The visualization menu is shown

### Actual

It is not.

**Comment by farmaazon** [comment]
Fixed in GUI2
