### ISSUE TITLE
Component Browser: Searching by Alias

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5340]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183602398).
<hr />

## Why

**As** Enso IDE user
**I want** to filter in entries whose alias matched to my searching pattern
**So that** I can find entries of which I don't remember what wording is used in their name.

## Acceptance Criteria
```gherkin
Scenario: 
GIVEN I opened  a project whose Main modle has a method with defined aliases and opened Component Browser 
WHEN I start typing the original method name 
THEN the method is matched
WHEN I start typing one of the method's aliases
THEN the method is still matched and the matched alias is displayed below name
WHEN I start typing string not matching name nor aliases 
THEN the method is filtered out.
```

**Comment by galin-enso** [comment]
@farmaazon The task description mentions the matched alias should be displayed when it matches the searcher input:
```
THEN the method is still matched and the matched alias is displayed below name
```

 I'm not clear on how this should look, where should the alias be displayed?

I'd imagine the alias could replace the entry's label in the component browser grid, but this does not match the description. Displaying the alias below the label, as described, would not fit in the current component browser layout.

**Comment by wdanilo** [comment]
@galin-enso good point. Let's replace the current searcher value with it and put the original name in parentheses after the match, ok?

**Comment by farmaazon** [comment]
> @farmaazon The task description mentions the matched alias should be displayed when it matches the searcher input:
> 
> ```
> THEN the method is still matched and the matched alias is displayed below name
> ```
> 
> I'm not clear on how this should look, where should the alias be displayed?

@galin-enso Oh, I just forgot about it. The exact design is here: https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#component-aliases as you see, when matching by alias we push the main name up and add labels below.

HOWEVER, as this definitely exceeds the estimate (1 - I just forget about visual part when I was estimating it), let's do it in a way @wdanilo described (if it's simple, I'm not sure how it would be on your branch), and make a separate task for doing it better.

<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 100 million people use GitHub to discover, fork, and contribute to over 330 million projects.</div></blockquote>

**Comment by wdanilo** [comment]
Im not sure if this is not the final solution actually. Maybe it is. Let's implement it and let's see in real life if we need to improve it. Then lets create improvement task :)

**Comment by MichaelMauderer** [comment]
QA: @MichaelMauderer
