### ISSUE TITLE
Replace Database operation names with an enum (ADT)

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5343]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/183581371).
<hr />

Currently we use `Text` for database operation names, as this seemed better for extensibility.

However, the set of operations is known because it is just internal names for the backend implementation of known column ops, while some may not be defined for a particular backend, we know all operations defined in the library.

So we can replace the names with an ADT.

```
type Database_Operation
    Is_Null
    Add
    ...
```

**Comment by jdunkerley** [comment]
We are working on a design of SQL AST and Dialects so that shall take precedence.
