### ISSUE TITLE
Animate label_color in node::input::area

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5344]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183567665).
<hr />

```
`label_color` should be animated, when when we can set text colors more efficiently.
```

graph-editor/src/component/node/input/area.rs

See https://github.com/enso-org/ide/issues/1031

**Comment by farmaazon** [comment]
Code removed along with EnsoGL.
