### ISSUE TITLE
Style watch is unsuitable in node::input::area

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5345]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183567648).
<hr />

```
// StyleWatch is unsuitable here, as it was designed as an internal tool for shape system
```
`graph-editor/src/component/node/input/area.rs`

**Comment by 4e6** [comment]
Relevant code:

https://github.com/enso-org/enso/blob/75fda33837214a774b7c8bbbbe64aeb72db069bd/app/gui/view/graph-editor/src/component/node/input/area.rs#L445-L451

**Comment by wdanilo** [comment]
Do we need to fix it now? I mean, does it cause any bad visual artifacts?

**Comment by vitvakatu** [comment]
It works fine. This comment has been in the codebase longer than I am.

**Comment by wdanilo** [comment]
> It works fine. This comment has been in the codebase longer than I am.

hahahaha, 😂, this comment made my day :D

**Comment by farmaazon** [comment]
Removed code along with EnsoGL
