### ISSUE TITLE
Area label is using a separate layer for depth sorting in node::input::area

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5346]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183567632).
<hr />

```
// Depth sorting of labels to in front of the mouse pointer. Temporary solution.
        //   It needs to be more flexible once we have proper depth management.
```

graph-editor/src/component/node/input/area.rs

**Comment by 4e6** [comment]
Relevant code

https://github.com/enso-org/enso/blob/75fda33837214a774b7c8bbbbe64aeb72db069bd/app/gui/view/graph-editor/src/component/node/input/area.rs#L257-L262

**Comment by wdanilo** [comment]
We have now good depth sorting of things. This code might be touched soon by @kazcw who is working on lowering the amount of draw calls and is investigating layers usage. So CCying him.

**Comment by farmaazon** [comment]
EnsoGL is removed from repository.
