### ISSUE TITLE
Hardcoded glyph width in node::input::area

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5347]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183567623).
<hr />

The `GLYPH_WIDTH` constant has hardcoded value. We should calculate the width of the text dynamically instead.

graph-editor/src/component/node/input/area.rs

**Comment by Frizi** [comment]
This will be resolved as part of #5921.
