### ISSUE TITLE
Remove unwraps in node::input::area.rs

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5348]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183567590).
<hr />

There are two unwraps in the `graph-editor/src/component/node/input/area.rs` module. They need to be removed.

**Comment by farmaazon** [comment]
The related code is being removed from repository.
