### ISSUE TITLE
Item hover highlight is sometimes not cleared on quick mouse leave

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5349]
This task is automatically imported from the old Task Issue Board and it was originally created by Paweł Grabarz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183557392).
<hr />

### Steps to reproduce
1. Open component browser
2. Hover over any item
3. Move mouse cursor quickly away from component browser

Might require repeating a few times.

### Expected

The highlighted item should lose highlight.

### Actual

One of the items in mouse path keeps being highlighted until the component browser is hovered again.

The side effect of this is that the documentation panel keeps referring to the highlighted item, completely disregarding keyboard navigation.

The image shows a state where mouse cursor is outside of the component browser, yet the highlight is still active. Notice the documentation panel showing information about highlighted element, not the active one

![broken highlighting](https://cdn.discordapp.com/attachments/1031537526374150184/1031542421307281408/unknown.png)

**Comment by farmaazon** [comment]
No hover highlight in new CB.
