### ISSUE TITLE
Remove UFCS assumption from Span Tree proposed arguments

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5350]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183555146).
<hr />

## Why

**As** Enso IDE user
**I want** to not see "this" argument when calling imported module methods
**So that** the non-filled argument list on nodes will be actual.

## Acceptance Criteria
```gherkin
Scenario: 
GIVEN I have a project with the following Main module:
from Standard.Base import all

foo a = a + 2

main = 
    Main.foo
    foo

WHEN I open this project, and it loads fully
THEN I see both nodes having just one gray argument name `a`
```

**Comment by farmaazon** [comment]
Fixes in new GUI
