### ISSUE TITLE
Component Browser: Replace "." with " " when adding an operator +-*/

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5351]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183554179).
<hr />

## Why

**As** Enso IDE user
**I want** the dot at the end of expression input to be removed if I started typing operator
**So that** I do not need to press backspace to have `operator1 + 2` instead of `operator1.+ 2`

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN I have opened newly created project and have one of initial nodes selected
WHEN I open Component browser and type `+`, `-`, `*`, or `\`
THEN the dot after "this" variable is removed.
```

**Comment by jdunkerley** [comment]
Already works correctly now.
