### ISSUE TITLE
Synchronize Component Browser breadcrumbs with qualified name left to the text cursor.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5354]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183544056).
<hr />

## Why

**As** Enso IDE user
**I want** to have synchronized the part of qualified name I've written so far with the breadcrumbs
**So that** the suggestion list reflects the context I'm currently focusing on.

Only the names starting with the full project name have to be recognized, and such shall be inserted when entering module in CB panel.

## Acceptance Criteria

```gherkin
Scenario: .
GIVEN I have opened a project containing module "Foo" with method "bar"
WHEN press tab and enter some module in CB
THEN the project and module name appears in input with dot
WHEN I cancel editing, press tab and type `local.<projectName>.`
THEN I see the new '<projectName>' breadcrumb in breadcrumbs, and the projects Main module content is displayed
WHEN I press backspace
THEN I'm back in the All breadcrumb.
WHEN I enter the "Main.Foo" module from there
THEN I see "local.Main.Foo." in input and CB display the Foo module's content.
WHEN I move the text cursor to "Foo" segment
THEN I CB switch to `Main` project crumb.
WHEN I delete the input's content and type `(2 + ` and enter `Foo` module
THEN the input should be `(2 + local.Main.Foo.` and the CB display the Foo module's content.
```

**Comment by farmaazon** [comment]
The design has changed and this task is no longer valid.
