### ISSUE TITLE
Recognize already written qualified names when applying Component Browser suggestions.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5356]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183522615).
<hr />

## Why
**As** Enso IDE user
**I want** suggestion applying to take the already written qualified name into consideration
**So that** editing existing nodes with qualified names produces working code (otherwise, editing `read` in `File.read` could result in `File.File.new`).

## Details

The searcher controller knowing the text cursor position should realize if the currently edited AST node is a direct, last part of qualified name, i.e. the Infix chain with `.` operator and containing names only. In such a case, after accepting a suggestion:
* if the existing qualified name is a substring of the suggestion's qualified name, the remaining segments from the latter are added to the right side of the existing qualified name. 
* otherwise, the existing qualified name is just removed, and then the suggestion should be put as before
In any case, the appropriate import for the first segment of the eventual qualified name should be added if needed.

## Acceptance Criteria

```gherkin
Scenario : 
GIVEN I have opened a project which Main module is identical to newly created project's, and has an additional module "Foo" having a submodule "Bar" which in turn contains some module method and a type "Baz" with some methods,
WHEN I open the Component Browser, type "Foo.Bar." and accept one ofthe "Baz" methods
THEN the input become "Foo.Bar.Buz.<method name>" and "Foo" module became imported.
WHEN I open another Component Browser, type "Bar." and accept one of the "Baz" methods
THEN the input become "Bar.Buz.<method name>" and "Bar" module became imported.
WHEN I open another Component Browser, type "Bar." and accept one of the "Bar" methods
THEN the input become "Bar.<method name>" and no additional import is added.
WHEN I open another Component Browser, type "Foo.Gee." and accept one of the "Bar" methods
THEN the input become "Bar.<method name>" and no additional import is added.
```

**Comment by farmaazon** [comment]
**QA**: @farmaazon
