### ISSUE TITLE
Visualization window is zoomed out when editing a node.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5357]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/183521784).
<hr />

### Steps to reproduce
1. Create a new project.
2. Zoom out.
3. Press `TAB` key to create a new node.

### Expected
A visualization preview is visible. The preview window is not zoomed out (see Component Browser Design Doc, section ["Editing zoomed-out nodes"](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#editing-zoomed-out-nodes).

### Actual
The visualization preview window is zoomed out. This makes it difficult to see the contents of the visualization. Also, this view is inconsistent with the non-zoomed-out view of the node being edited.

![](https://user-images.githubusercontent.com/273837/195307859-fd0594ac-c099-46d4-a704-98e1f4192c79.png)

**Comment by farmaazon** [comment]
Fixed in GUI2
