### ISSUE TITLE
Support custom profiles in wasm-pack

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5359]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/182443428).
<hr />

## Description
https://github.com/enso-org/enso/pull/3498 introduced slightly faster release builds at price of worse optimization. 
We should introduce the `production` profile, however it is not possible now because wasm-pack does not support custom profiles.

**Comment by mwu-tow** [comment]
Not in scope anymore.
