### ISSUE TITLE
Proper selection behavior when moving to column without entries in the current row.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5361]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183487880).
<hr />

### Steps to reproduce
Open Component Browser and select the highest entry possible
Move left or right

### Expected
Behavior as described in  ["Underflow Navigation Patterns"](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#underflow-navigation-patterns) section of the design doc.

### Actual

The selection goes to non-existing entry.

**Comment by farmaazon** [comment]
No longer valid for new CB design.
