### ISSUE TITLE
Grid View selection sometimes is not updated after selecting new entry.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5362]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183487730).
<hr />

### Steps to reproduce
1. Open "component list panel" debug scene
2. after the component is loaded, move the selection down with the arrow key.

### Expected

The selection is over the entry.

### Actual

The selection is sometimes a bit moved up.

### Notes

The behavior is caused by the fact that local scope entries declares contour and highlight offsets, which cannot be read upon selecting, because we select them when they were not yet visible (scrolling animation just started).

**Comment by farmaazon** [comment]
EnsoGL is removed.
