### ISSUE TITLE
Support displaying 0-2 characters instead of an icon in Component Browser entries.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5366]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/183440276).
<hr />

## Why

**As** Enso Developer
**I want** to be able to display shortcut characters instead of icons in Component Browser entries
**So that** I can implement the Suggestion Shortcut Mode feature.

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN the component browser debug scene
WHEN I open it
THEN I can see some example entries with 0-2 characters in place of the icons.
```

## Notes
- When displaying 1-2 characters, they should be horizontally centered.
- See the Suggestion Shortcut Mode image in the design doc.

**Comment by farmaazon** [comment]
Tasks of #4971 will be redesigned for GUI2
