### ISSUE TITLE
Display shortcuts instead of icons while Suggestion Shortcut Modifier Key is held in Component Browser.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5367]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/183440749).
<hr />

## Why

**As** Enso User
**I want** to see the keyboards shortcuts of the visible entries in Component Browser when I press and hold a Suggestion Shortcut Modifier Key
**So that** I can learn the shortcuts which I can use in the Suggestion Shortcut Mode.

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN a project with Component Browser open
WHEN I press and hold a Suggestion Shortcut Modifier Key
THEN I can see 0-2 character shortcuts for each visible entry in Component Browser
AND the shortcuts are displayed instead of entry icons
WHEN I release the Suggestion Shortcut Modifier Key
THEN I can see icons again and the shortcuts disappear.

GIVEN a project with Component Browser open
WHEN I press and hold a Suggestion Shortcut Modifier Key
THEN shortcuts are displayed either immediately or after a delay, depending on which modifier key was pressed.
```

## Notes
 - in scope: ensuring that the shortcuts are stored in the Component Browser’s internal structs.
 - in scope: hardcoded/configured delay before showing the shortcuts for some of the Suggestion Shortcut Modifier Keys (see design doc).
 - in scope: when first loading the data, print a warning in Dev Console when a shortcut is too long and gets trimmed to 2 characters.
 - in scope: define sample shortcuts for a few components in the standard library, in the `component-groups` section of the `project.yaml` file (showcase 1-letter-long and 2-letter long shortcuts).

**Comment by farmaazon** [comment]
Tasks of #4971 will be redesigned for GUI2
