### ISSUE TITLE
Move Active Focus to the Entry with a shortcut that best matches the characters typed while in Suggestion Shortcut Mode.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5368]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/183442463).
<hr />

## Why

**As** Enso User
**I want** the Active Focus highlight in Component Browser to move to the entry best matching the characters I typed while in Suggestion Shortcut Mode
**So that** I can use the keyboard to quickly select an entry from the Component Browser.

## Acceptance Criteria

```gherkin
Scenario:
GIVEN an open Component Browser in Suggestion Shortcut Mode
WHEN there is a single entry having a one-letter shortcut 'a' in the Component Browser
AND I type the character 'a'
THEN the Active Focus moves to the entry having the one-letter shortcut 'a'.

OR WHEN there are two entries having a one-letter shortcut 'b' in the Component Browser, one from the standard library and the other from outside the standard library
AND I type the character 'b'
THEN the Active Focus moves to the entry from the standard library having a matching shortcut.

OR WHEN there are no entries having a shortcut starting with letter 'c'
AND I type the character 'c'
THEN the Active Focus disappears.

OR WHEN there are no entries having a one-letter shortcut 'd'
AND there are two entries having a shortcut starting with letter 'd' (specifically, 'dd' and 'de')
AND I type the character 'd'
THEN the Active Focus moves to the entry from the standard library
AND WHEN I type the character 'e'
THEN the Active Focus moves to the entry having the shortcut 'df'.
AND WHEN I type the character 'd'
THEN the Active Focus disappears.
```

## Notes
 - in scope: handling the 2nd pressed character
 - in scope: “conflict resolution”: (1) perfect match wins; (2) standard library match wins; (3) the same item should be selected given exactly the same Entries.
 - NOT IN SCOPE: keyboard arrows navigation
 - if a third character is typed while still holding a Suggestion Shortcut Modifier Key, the Active Focus should disappear (no item should be highlighted).

**Comment by farmaazon** [comment]
Tasks of #4971 will be redesigned for GUI2
