### ISSUE TITLE
Hide Entries without a matching shortcut when a character is typed while in Suggestion Shortcut Mode.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5369]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/183442621).
<hr />

## Why

**As** Enso User
**I want** to only see the Component Browser entries having shortcuts that match the characters I typed while in Suggestion Shortcut Mode
**So that** irrelevant entries don't distract me and waste my time while in Suggestion Shortcut Mode.

## Acceptance Criteria

```gherkin
Scenario:
GIVEN an open Component Browser in Suggestion Shortcut Mode
WHEN there are entries having shortcuts starting with letter 'a'
AND there are entries having shortcuts starting with letter 'b'
AND I type the character 'a'
THEN I can only see entries having shortcuts starting with letter 'a'.

OR WHEN there are multiple entries having shortcuts starting with letter 'a'
AND there is an entry having a shortcut 'ab'
AND I type the character 'a' and then a character 'b'
THEN I can only see the entry having shortcut 'ab'.
```

## Notes
 - in scope: handling the 2nd pressed character

**Comment by farmaazon** [comment]
Tasks of #4971 will be redesigned for GUI2
