### ISSUE TITLE
Update Expression when leaving Suggestion Shortcut Mode.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5370]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/183444710).
<hr />

Insert the suggestion corresponding to the Entry with Active Focus when a Suggestion Shortcut Modifier Key is released. If the Suggestion Shortcut Modifier Key held was the Option key or the Expression Acceptance Key, then also accept the Expression and close the Component Browser.

## Why

**As** Enso User
**I want** to use the chosen suggestion from the Suggestion Shortcut Mode to become part of the edited expression after I exit the Suggestion Shortcut Mode
**So that** I can use the output of the Suggestion Shortcut Mode when editing expressions.

## Acceptance Criteria

```gherkin
Scenario 1:
GIVEN an open Component Browser in Suggestion Shortcut Mode with an entry having an Active Focus
WHEN I release the Suggestion Shortcut Modifier Keys
THEN code of the entry having Active Focus is inserted into the node's expression.

Scenario 2:
GIVEN an open Component Browser in Suggestion Shortcut Mode with no Active Focus on any entry
WHEN I release the Suggestion Shortcut Modifier Keys
THEN no new code is inserted into the node's expression.
```

## Notes
 - If no entry matched the characters typed by the user, then nothing should be inserted when the Suggestion Shortcut Modifer Key is released.
 - Pressing the Escape key before releasing the Suggestion Shortcut Modifier Key should make the Active Focus disappear, so that no code is inserted into the edited node after the SSMK is released.

**Comment by farmaazon** [comment]
Tasks of #4971 will be redesigned for GUI2
