### ISSUE TITLE
Handle arrow keys during Suggestion Shortcut Mode.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5371]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/183444756).
<hr />

## Why
**As** Enso User
**I want** to be able to navigate the Component Browser using arrow keys while in Suggestion Shortcut Mode
**So that** I can more easily insert the suggestion that I want into the edited node.

## Acceptance Criteria
```gherkin
Scenario:
GIVEN an open Component Browser in Suggestion Shortcut Mode with an entry having an Active Focus
WHEN I press an arrow key
THEN the Active Focus moves to another entry in a similar way as when not in the Suggestion Shortcut Mode.
```

## Notes
Navigation keys (arrows) should work while pressing any key enabling Suggestion Shortcut Mode. To achieve that, all navigation shortcuts should have duplicated entries for every key, like that:
```
(PressAndRepeat, "up", "move_selection_up"),
(PressAndRepeat, "alt up", "move_selection_up"),
(PressAndRepeat, "tab up", "move_selection_up"),
// ..etc
```

**Comment by farmaazon** [comment]
Tasks of #4971 will be redesigned for GUI2
