### ISSUE TITLE
Add an invisible wide click area to the scrollbar.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5374]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/183390576).
<hr />

Scrollbar should have three areas with hardcoded widths:

1. An area where hovering the mouse pointer makes the scrollbar appear.
2. An area where clicking the mouse is interpreted as clicking on the scrollbar.
3. An area where the scrollbar is rendered.

By default, the hover area should be wider than the click area, which should be wider than the render area.
This should make it easier for the user to click the scrollbar.

## Why

**As** Enso User
**I want** the clickable area of the scrollbar to be wide
**So that** it is easy for me to use the scrollbar.

## Acceptance Criteria

```gherkin
Scenario 1
GIVEN the scroll area debug scene
WHEN the mouse is hovered near a vertical scrollbar
THEN the scrollbar becomes visible
WHEN the mouse is clicked, or clicked and dragged, while near the visible scrollbar area
THEN the scrollbar behavior is the same as if mouse pointer was clicked, or clicked and dragged, at equal vertical coordinate inside the scrollbar area.

Scenario 2
GIVEN an opened Component Browser
WHEN (same as in Scenario 1)
THEN (same as in Scenario 1).
```

**Comment by farmaazon** [comment]
In GUI2, we should use browser's scroll bars for simplicity.
