### ISSUE TITLE
Clicking the scrollbar's background while holding a modifier key should move the scroller’s center to the mouse position.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5375]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/183390649).
<hr />

## Why

**As** Enso User
**I want** a scroller on a scrollbar to move to the clicked location when clicking a scrollbar while holding a modifier key
**So that** I can quickly navigate to a specific position in the scrolled data.

## Acceptance Criteria

```gherkin
Scenario 1
GIVEN the scroll area debug scene with the vertical scrollbar visible
WHEN the mouse is clicked on the scrollbar background while holding a Command, Option, Ctrl, Alt, or Shift key
THEN the scroller should jump such that its center is vertically aligned with the mouse pointer.

Scenario 2
GIVEN an opened Component Browser
WHEN (same as in Scenario 1)
THEN (same as in Scenario 1).
```

## Notes
- TODO: should the jump of the scroller be smoothly animated or instant?

**Comment by farmaazon** [comment]
in GUI2 shift works.
