### ISSUE TITLE
Ability to request Enso benchmark runs on our standarized runner through GH

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5376]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/183363770).
<hr />

We have a suite of benchmarks written in Enso, the `test/Benchmarks/` project.

We run them from time to time to check performance of various mechanisms from the library. In the future they will probably need to be restructured a bit, but for now it would be useful if we can schedule a run on our standarized runner of a specific suite. To do so we need Enso to be built and we need to run the runner with the proper project path and path to a particular file, for example:

```
sbt bootstrap
sbt buildEngineDistribution
./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --in-project test/Benchmarks/ --run test/Benchmarks/src/Vector/Vector.enso
```

The `test/Benchmarks/src/Vector/Vector.enso` should be customizable so that we can select which suite we run. This probably should be parameter to provide during manual workflow dispatch on GitHub.

**Comment by mwu-tow** [comment]
Was done.
