### ISSUE TITLE
Out of the box support for IDE development: run ide watch

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5379]
This task is automatically imported from the old Task Issue Board and it was originally created by jaroslavtulach.
Original issue is [here](https://www.pivotaltracker.com/story/show/182998577).
<hr />

While starting the IDE development, it has [come to my attention](https://discord.com/channels/401396655599124480/1008991402971123732/1009016703256117299) that `run ide watch` isn't really optimized for development. For example it performs maximal `-O3` wasm optimization. 

When in watch mode - shouldn't the `--skip-wasm-opt` or `-O0` be there by default? Then the out of the box experience of those who try `run ide watch` would be better.

**Comment by farmaazon** [comment]
No longer relevant in new GUI
