### ISSUE TITLE
Text Area 2.0 and basic widgets (slider, check box)

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5381]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/183406714).
<hr />

- Creating abstraction for a "widget" type.
- Supporting glyphs and widgets within text field with good text cursor management.
- Creating slider and check box widgets. [Sliders API](https://github.com/enso-org/enso/blob/f61849ce04960c1c347768a5d7666e29daf90f99/docs/language-server/protocol-language-server.md#textapplyexpressionvalue)

GUI-only task.

**Comment by farmaazon** [comment]
Implemented in GUI2
