### ISSUE TITLE
Adjusting look and feel of nodes, connections, and the application.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5382]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/182746079).
<hr />

Making nodes look like in the design file – with coloured backgrounds, arguments separated. with vertical lines, no self argument, nicer arrows, nicer selection. Adjusting the background color and theme. Probably would include improvements to the theme manager, to allow reloading themes faster and more dynamically.

Needed from engine:
- Information about node type (to get icon and color). In particular, we need the information to which component-browser group the function belongs to (if any), and the information about where the function was defined (full path with lib info). 
- Information about node status (computed, to be computed, in progress + info about progress). It is impossible to create a generic mechanism providing us with information about function evaluation progress (like, "40% of computations are done"), but we should create an [Progress API](https://www.pivotaltracker.com/n/projects/2539304/stories/182781062) in the language allowing the lib team to report the progress of function evaluation. In case such progress will be reported, we will show a spinner in GUI that will change its length. In case no progress is reported, we will only show a spinner without changing its length. We need to get the information on whether a function reports progress as soon as we got information that the node starts being evaluated because the look of the spinner will be different for functions reporting progress and those that don't.
- Information about argument names and types (including nested arguments, e.g. function accepting a structure Foo - we need names of fields of that structure. If the structure has a field of type Bar, we also need to be able to query for the names and types of the fields of the Bar type, etc. These queries should be done on demand and we should be able to perform them from GUI ad-hoc).
- Information whether a node is in the Input, Output, or IO context. This requires introducing the distinction of Input and Output contexts in the backend (this might not be a lot of work, as we don't really have a type inferencer yet). We need to display "play button" next to output nodes and the refresh button next to input nodes.

## Blockers:
[#182781062](https://www.pivotaltracker.com/story/show/#182781062) blocked
[#182818735](https://www.pivotaltracker.com/story/show/#182818735) resolved

**Comment by farmaazon** [comment]
Implemented in GUI2
