### ISSUE TITLE
Display Warnings associated with nodes

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5383]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/183274296).
<hr />

We have got a warning system that allows to associate warnings with values in the language.

This warning system was designed so that users can be notified of non-critical errors or other potential issues when executing various operations.

In many cases the warnings are already attached in the libraries, but currently there is no way for a GUI user to see these warnings.

We need a way to get the attached warnings from the engine and display them in the GUI next to the relevant node.

## Blockers:
[#181935852](https://www.pivotaltracker.com/story/show/#181935852) resolved

## Design

* A new icon (looking like :warning: ) should be shown next to the node's eye icon (and in the same style as the eye icon) if the node has warnings.
* Clicking on this icon should switch visualization to Warnings (which displays the full warning message).
* The `Warnings` visualization should not be visible in the visualization chooser, or it should be visible only when node has warnings.

**Comment by jdunkerley** [comment]
We now color the nodes but need to show the warning message as appropriate.

**Comment by farmaazon** [comment]
@wdanilo Do you have any idea how to display warnings?

I think about something like an additional icon next to "eye" icon, visible only when there are warnings, and clicking on it would display warnings in place of the visualization.

**Comment by wdanilo** [comment]
@farmaazon the problem with an icon is that its not visible when the graph is zoomed out. I'd rather show both the icon and also yeloow/orange background of a node (just like we have red bg for errors). And yes, clicking icon shows warning.

**Comment by farmaazon** [comment]
Ok, the yellow stripes on the background are already there. Let's add the icon, then.

**Comment by farmaazon** [comment]
The ⚠ icon will be done in a separate task, thus reduced estimate to 5.
