### ISSUE TITLE
GridView is glitchy when `set_column_width` is used with masked highlight layers

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5385]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/183247118).
<hr />

### Steps to reproduce
 1. In the code of the `grid_view` debug scene, use the `set_column_width` FRP to change column widths for a GridView instance which has a masked layer enabled both for highlights and for selection. For example, change the following line: https://github.com/enso-org/enso/blob/f233ea66b37969b84a224e462014853f00db285e/lib/rust/ensogl/example/grid-view/src/lib.rs#L127 to `    let view = &grid_views[2];`.
 2. Compile the changed code and open the `grid_view` debug scene.
 3. Hover the mouse over the entries of the GridView mentioned in point (1) above.
 4. Click the mouse over some entries of the GridView mentioned in point (1) above.

### Expected
- The entry hovered by mouse should be highlighted.
- When clicking the mouse over an entry, this entry should become selected.
- The text of hovered and clicked entries should be correctly positioned horizontally.

### Actual
- When hovering the mouse over the entries, the hover highlight jumps between the hovered entry and some other entries.
- When clicking the mouse over an entry, a different entry is sometimes selected instead.
- The text of the hovered and clicked entries is not correctly positioned along the horizontal axis.

See the video linked below for a demonstration of the behaviors mentioned above (note: in the video, the change from point (1) above was applied to the GridView in top-left corner of the debug scene).

https://drive.google.com/file/d/1N1zOtlhzik7laiRrSV8vzwdEg2l8_ueD/view?usp=sharing

**Comment by farmaazon** [comment]
EnsoGL is removed.
