### ISSUE TITLE
Update design of the Component Browser to the latest design doc version

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5386]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183186828).
<hr />

The latest design doc is available here: https://github.com/enso-org/design/blob/main/epics/component-browser/design.md

The design was updated, so these changes must be reflected in the implementation of the Component browser.

**Comment by farmaazon** [comment]
Superseded by #7125
