### ISSUE TITLE
More effective handling of the column widths in the GridView

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5389]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/183046885).
<hr />

## Why
The current implementation as per https://github.com/enso-org/enso/pull/3651 uses not the most performant solution for simplicity. We can implement (or find) a data structure that would be more performant

**As** Enso developer
**I want** an effective implementation of the resizing columns in the grid view 
**So that** I'm not afraid of using large grid views while implementing features

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN [necessary context and predictions for the story, e.g. "I select a flight"]
WHEN [action, e.g. "I scan the wheelchair"]
THEN [reaction, e.g. "I am presented with a popup where I can select the type of the wheelchair: Electric, Manual, Other"]

<SECTIONS BELOW ARE OPTIONAL AND YOU CAN ADD MORE OF THEM>
AND THEN [additional reaction, e.g. "if I hit 'ENTER' the wheelchair is scanned onto the flight and I am presented with the confirmation pop up"]
OR THEN [alternative reaction, e.g. "If I hit 'Cancel' then I am sent back to the flight that I just came from"]
```

**Comment by farmaazon** [comment]
We removed EnsoGL and its components.
