### ISSUE TITLE
Documentation sections of `Standard.Database.Data.Table.Table.join` are not parsed correctly

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5394]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/182781673).
<hr />

### Steps to reproduce
1. Start `./run ide watch`.
2. Open the built IDE in Chrome.
3. Open the Chrome Developer Console, go to the "Network" tab.
4. Create a new project in the IDE.
5. In the "Name" panel of the Dev. Console, find the 2nd (of 3) entry named "127.0.0.1" and click it.
6. In the right panel of the Dev. Console, click "Messages".
7. In the "Enter regex (...)" input, enter the following expression: `Standard.Database.Data.Table.Table.*Efficiently joins`. This should filter out just a single `search/suggestionsDatabaseUpdates` response in the "Data" panel.
8. Right-click the `search/suggestionsDatabaseUpdates` response, select "Copy message".
9. Paste the copied JSON message body into a text file.
10. In the JSON, search for `documentationSections` of the `join` method.

### Expected
There should be a separate `"type":"keyed"` section with `"key":"Arguments"`.

### Actual
The contents of the "Arguments" section in the documentation is contained in HTML format in `"type":"paragraph"` entry in `documentationSections`:

```
        "documentationSections":[{
          "type":"tag",
          "name":"UNSTABLE",
          "body":""
        },
        {
          "type":"paragraph",
          "body":" <pre><code>Efficiently joins two tables based on either the index or a key column.</code><br /><code>Arguments:</code><br /><code>- other: the table being the right operand of this join operation.</code><br /><code>- on: the column(s) or expression(s) of `self` that should be used as</code><br /><code>  the join key. If this argument is not provided,
           the index of `self`</code><br /><code>  will be used.</code><br /><code>- drop_unmatched: whether the rows of `self` without corresponding</code><br /><code>  matches in `other` should be dropped from the result.</code><br /><code>- left_suffix: a suffix that should be added to the columns of `self`</code><br /><code>  when there's a name conflict with a column of `other`.</code><br /><code>- right_suffix: a suffix that should be added to the columns of `other`</code><br /><code>  when there's a name conflict with a column of `self`.</code><br /><code>The resulting table contains rows of `self` extended with rows of</code><br /><code>`other` with matching indexes. If the index in `other` is not unique,
          </code><br /><code>the corresponding rows of `self` will be duplicated in the result.</code><br /></pre>"
        }]
```

## Additional Notes

 - The documentation source: https://github.com/enso-org/enso/blob/7e2998bd27964b888c4f9dd03c7d99fe9694edfd/distribution/lib/Standard/Database/0.0.0-dev/src/Data/Table.enso#L522-L542
 - Note: this issue was found while working on #182584311 and trying to add an `Icon: join` section in the docs of the `join` method. This "Icon" section got also incorrectly merged into the `"paragraph"` section.
 - A similar block in `distribution/lib/Standard/Table/0.0.0-dev/src/Data/Column.enso`, which does not have an `UNSTABLE` tag, seems parsed properly into sections.

## Blockers:
[#183417662](https://www.pivotaltracker.com/story/show/#183417662) resolved

## Comments:
Update

The parser parses the docstring with an extra indent
```
"documentation":" UNSTABLE\n\n     Efficiently joins two...
```
`Unstable` line is parsed correctly (one space), but the next lines contain an extra indent (more than one space)

Then docparser treats that extra indent as a code block (Dmitry Bushev - Aug 1, 2022)
<hr />
The new parser should be ready in a month form now. We can postpone fixing an old one, and just wait for the new implementation. (Dmitry Bushev - Aug 1, 2022)
<hr />

**Comment by sylwiabr** [comment]
We will not fix the old parser
