### ISSUE TITLE
When Expression Input area is selected, its selection overlaps Component Browser.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5395]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/182749100).
<hr />

### Steps to reproduce
1. Open the Component Browser.
2. Type `asdf` into the Expression Input panel.
3. Click the edited node's outline, while keeping the Component Browser open, so that the node becomes selected.

### Expected

The parts of the blue selection outline of the node that overlap with the Component List Panel View should be hidden behind it.

### Actual

The blue outline of the node is fully visible, as seen in the image below.

![](https://user-images.githubusercontent.com/273837/178254975-835bb5da-405a-461a-adf4-d394b9ea11d8.png)

**Comment by farmaazon** [comment]
New GUI has different design.
