### ISSUE TITLE
Selection can show over empty space in Local Scope section of Component Browser.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5396]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/182748789).
<hr />

### Steps to reproduce
To reproduce:
 1. Hover the mouse over an item in the left column of the Local Scope section.
 2. Type letters "ab" on the keyboard.

### Expected

The selection should show highlight some existing entry in the Component Browser.

### Actual

The selection shows over a space that does not contain any entry of the Component Browser.

![](https://user-images.githubusercontent.com/273837/178253245-39a22cc2-fe2a-4307-8115-bb06ed8128d4.png)

**Comment by sylwiabr** [comment]
Check if it is still valid

**Comment by 4e6** [comment]
Closing because the updated design of the Component Browser does not have the _Local Scope_ section anymore
