### ISSUE TITLE
Expanded nodes view

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5398]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/182746297).
<hr />

GUI-only task.

To be discussed (also with engine): handling of problems on nodes - should that be an argument or a more generic functionality. Not a blocker.

**Comment by farmaazon** [comment]
Superseded by https://github.com/enso-org/enso/issues/9208
