### ISSUE TITLE
Circular menu for nodes

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5399]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/182746085).
<hr />

Circular menu allowing displaying 3 icons and more icons. In 3 shapes - curved 3 icons, semi curved 3 icons, and full circle. 

Needed from Engine:
- Support for IO running modes (production vs development + setting it per node) - this may heavily involve the controller in GUI. On the top of the GUI there will be a button allowing switching the mode (production <-> development <-> maybe other modes). Given a mode, every IO node is assigned with info if it should auto-refresh. In the production mode all IO nodes are refreshed by default. In development mode, all IO nodes are not refreshed by default and the user needs to press play button next to the nodes. Unfortunately, this is important and we constantly hear about it from people. E.g. you open your dataflow network and you want to change it, but you dont want to override your database when playing with values. So you switch to dev mode and nothing evaluates until you want to. Also, the nodes should not evaluate their IO actions even if visualizations are opened. Anyway, this requires a bigger talk with the engine team, because support for it seems non-trivial. In particular, if the IO operations are nested, e.g. after collapsing a node, we still want to have the "play button" visible on the collapsed node and we want the inner IO nodes to not autorefresh in the given mode. This can't be done by GUI, as after the definition of the collapsed node changes, things should be updated and work. Let's have a talk about how much of that can be done and when.
- Support for "play button" (playing IO node in dev mode) (described above).
- Support for "stop button" - stoping computation of nodes (described above). Ability to "stop node execution" on demand.

## Blockers:
[https://www.pivotaltracker.com/story/show/182781696](https://www.pivotaltracker.com/story/show/https://www.pivotaltracker.com/story/show/182781696) blocked
[https://www.pivotaltracker.com/story/show/182781743](https://www.pivotaltracker.com/story/show/https://www.pivotaltracker.com/story/show/182781743) blocked
[#182816602](https://www.pivotaltracker.com/story/show/#182816602) blocked

**Comment by farmaazon** [comment]
Implemented updated design in GUI2
