### ISSUE TITLE
Drop-down menu widget

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5401]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/182746285).
<hr />

Looking as in the design file

Engine:
- dynamic widgets (probably already done)

## Blockers:
[https://www.pivotaltracker.com/story/show/182801515](https://www.pivotaltracker.com/story/show/https://www.pivotaltracker.com/story/show/182801515) resolved
[https://www.pivotaltracker.com/story/show/182801491](https://www.pivotaltracker.com/story/show/https://www.pivotaltracker.com/story/show/182801491) resolved

**Comment by jdunkerley** [comment]
Already done.
