### ISSUE TITLE
Names of Modules and Atoms displayed in Component Browser start with a small letter.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5409]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/182745386).
<hr />

### Steps to reproduce
1. Create new project in IDE.
2. Close the IDE (including Project Manager).
3. Edit the new project's `package.yaml` file, adding the following section:
```
component-groups:
  new:
    - Test Group 1:
        exports:
          - Standard.Base.Data.Time
          - Standard.Table.Data.Table.Table
```
4. Open the IDE with Component Browser enabled.
5. Open the project in the IDE.
6. Make sure none of the nodes are selected, and press the `TAB` key to open the Component Browser.
7. Scroll the Component Browser to see the contents of the `Test Group 1` group.

### Expected
- The `time` entry starts with a small letter.
- The `table` entry starts with a small letter.

### Actual
- There's a `Time` entry starting with a big letter instead of the `time` entry. (The `Time` entry represents a module.)
- There's a `Table` entry starting with a big letter instead of the `table` entry. (The `Table` entry represents an atom.)

### Additional Notes

See also the following video demonstrating the issue in a slightly different setup. Notice the type and names of the entries displayed in the Documentation Panel when the mouse hovers over the `time` and `table` entries in the `Mcdbg Group 1` group.

https://user-images.githubusercontent.com/273837/179016109-c3ebab5a-0205-4b44-85b8-df3129edd75d.mov

**Comment by farmaazon** [comment]
Fixed in GUI2
