### ISSUE TITLE
Bad UX when components have really long name

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5410]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/182713407).
<hr />

## Description

The names get clipped in the Component Browser Panel. The Documentation panel sometimes shows the name (but not the path) for a component with long name, but sometimes does not show the name - see the screenshots below (looks like name is only shown if the component does not have documentation available).

![](https://user-images.githubusercontent.com/273837/178250671-b2a13af2-77b8-4c3c-b010-d50c5a8968b4.png)

![](https://user-images.githubusercontent.com/273837/178250092-667bc513-7099-46df-b493-82c37d99166a.png)

Most of the group headers look much better, as the workaround skipping "Standard" part was already applied. However, some of them are still clipped - see e.g.: "Visualization.G..." in the screenshot below. 

![](https://user-images.githubusercontent.com/273837/178485283-a80046f0-3a89-4fb5-861c-b0e71c39a123.png)

As a workaround, we should show full names on the documentation top, both when selecting components and headers (the components has it partially implemented: they do not show the full name when the documentation is missing).

## Comments:
**Adam Obuchowicz** reports a new **STANDUP** for today (2022-07-15):

**Progress:** Implemented changes, but still fighting with some issues. It should be finished by 2022-07-19.

**Next Day:** Next day I will be working on the [#same task](https://www.pivotaltracker.com/story/show/182713407). Not sure if will have time for this task, as there are many meetings on Monday + I have some pivotal work to do. (Enso Bot - Jul 15, 2022)
<hr />
**Adam Obuchowicz** reports a new **STANDUP** for yesterday (2022-07-18):

**Progress:** Decided to prepare a PR with current work, as fixing the headers docs will require Component Browser API update, which will be reworked anyway when doing Efficient Component Browser It should be finished by 2022-07-19.

**Next Day:** Next day I will be working on the [##182585668 task](https://www.pivotaltracker.com/story/show/182585668). Start working on the selection task. (Enso Bot - Jul 19, 2022)
<hr />

**Comment by farmaazon** [comment]
Partially fixed by #5102

**Comment by jdunkerley** [comment]
Closing as new CB design improves this - we should ensure the new version copes with longer names and reopen a similar ticket to this if not.
