### ISSUE TITLE
Visibility icon in the component browser top bar

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5411]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/182729825).
<hr />

## Why

**As** Enso user
**I want** to have a working Visibility icon in the top bar
**So that** I can toggle the visibility of the documentation panel with the mouse

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN the component browser is opened
THEN I can see a Visibility icon in the top bar of the browser
WHEN I click it
THEN the documentation panel disappears
WHEN I click it again
THEN the documentation panel appears

Scenario:
GIVEN I disabled the visibility of the documentation panel
WHEN I save the project, close it and open it again
THEN the documentation panel is still disabled
```

## Notes

The visibility of the documentation panel must be saved in the project configuration, so that it preserves between IDE reloads.

**Comment by farmaazon** [comment]
Already implemented in #7350
