### ISSUE TITLE
Option icon in component browser top bar

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5412]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/182729802).
<hr />

## Why

**As** Enso user
**I want** to see if the Selection Directional Modifier key is pressed or the Suggestion Shortcut Mode is active and be able to toggle it with the mouse
**So that** I have a visual feedback and can use mouse instead of the keyboard

Design section: https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#the-option-icon

## Acceptance Criteria

```gherkin
Scenario: highlight
GIVEN The component browser is opened
THEN I can see an option icon as per design
WHEN I hold the Suggestion Shortcut Mode Key
OR I hold the Selection Directional Modifier key
THEN the Option icon is highlighted in the Application Accent Color

Scenario: hovering
GIVEN The component browser is opened
WHEN I hover the Option icon with the mouse
THEN The popup is displayed with the short information about Selection Directional Modifier key and The Suggestion Shortcut Mode
WHEN I move the mouse out
THEN The popup disappears after a short delay

Scenario: clicking
GIVEN The component browser is opened
WHEN I click the Option icon with the mouse
THEN The Suggestion Shortcut Mode is activated
WHEN I click the Option icon again
THEN The Suggestion Shortcut Mode is deactivated
```

## Notes

We do not have a prepared icon for this button

The Suggestion Shortcut Mode activation/deactivation can be demonstrated by console logs, the mode itself is out of scope.

**Comment by farmaazon** [comment]
The new design does not contain option icon: https://github.com/enso-org/design/blob/main/epics/component-browser/design2.md

<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 100 million people use GitHub to discover, fork, and contribute to over 330 million projects.</div></blockquote>
