### ISSUE TITLE
Pressing `tab` quickly followed by `enter` leaves a floating "No Entries." text in the IDE.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5414]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/182713432).
<hr />

### Steps to reproduce

As in the title, see also video below. Note that this happens in a newly loaded IDE; if the Component Browser was already opened before, the behavior may differ.

### Expected

After closing the Browser, the captions inside disappears.

### Actual

https://user-images.githubusercontent.com/273837/178478212-98f7b139-9878-4f4c-9b0c-480ac44c92eb.mov

**Comment by jdunkerley** [comment]
Doesn't happen as no place holder any more.
Does make fun pressing return to see what random function it chooses.
