### ISSUE TITLE
Scrolling while the mouse hovers the right-most column of Component Browser results in whole graph panning.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5415]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/182713670).
<hr />

### Steps to reproduce
1. Create a new project.
 2. Select the bottom node.
 3. Press <kbd>tab</kbd> to open the Component Browser.
 4. Using the mouse (or touch bar), position the cursor  over the right-most column of the Component Browser.
 5. Scroll using the "two-finger gesture" on a Mac touch bar (possibly reproduce using the mouse scroll wheel as well):

### Expected
Only the contents of the Component Browser should scroll; the Graph Editor should not pan.

### Actual
The whole Graph Editor is panned in addition to the Component Browser contents scrolling. See the video below.

https://user-images.githubusercontent.com/273837/178541977-70f3ab6a-724a-4c84-babd-24ea17d880b4.mov

**Comment by farmaazon** [comment]
No longer reproducible.
