### ISSUE TITLE
Obtain strong macOS server.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5416]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/182682362).
<hr />

## Description
The GH-hosted macOS runners are too weak to reliably run our CI.

**Comment by mwu-tow** [comment]
Whether the machine is strong is arguable (mac mini) but it has been obtained.
