### ISSUE TITLE
Setting up self-hosted macOS runner

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5417]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/180302889).
<hr />

## Description
The GitHub-hosted macOS runners are very slow. Because of that we had to disable some tests on this platform.

## Resources
Hetzner recently added macOS dedicated server to their offerings: https://www.hetzner.com/dedicated-rootserver/matrix-apple

## Blockers:
[The macOS machines are temporarily unavailable to order on Hetzner.](https://www.pivotaltracker.com/story/show/The macOS machines are temporarily unavailable to order on Hetzner.) blocked

## Comments:
**Michał Urbańczyk** reports a new **STANDUP** for yesterday (2021-12-21):

**Today:** Adjusting the deploy scripts to work on macOS. So far the results are promising, the direct setup deployment seems relatively straightforward. It should be finished by 2021-12-27.

**Next Day:** Next day I will be working on the [##180302889 task](https://www.pivotaltracker.com/story/show/180302889). Test metarunner on macOS. Refactor script to work both with mac and non-mac deployments. (Enso Bot - Dec 22, 2021)
<hr />
**Michał Urbańczyk** reports a new **STANDUP** for today (2021-12-22):

**Today:** Got metarunner to work on macOS. Encountered some strange permission issues when runner is deployed as a service (agent) and located in the separate disk. It should be finished by 2021-12-27.

**Next Day:** Next day I will be working on the [##180302889 task](https://www.pivotaltracker.com/story/show/180302889). Debug and attempt to fix deployment issue. If done, deploy and test things. (Enso Bot - Dec 23, 2021)
<hr />
**Michał Urbańczyk** reports a new **STANDUP** for the last Friday (2021-12-24):

**Today:** Succeeded in deploying runners manually on macOS. However, doing the same from runner service context behaves different. Likewise, using a different account creates even more confusion. It should be finished by 2021-12-27.

**Next Day:** Next day I will be working on the [##180302889 task](https://www.pivotaltracker.com/story/show/180302889). Attempt to resolve remaining macOS issues. (Enso Bot - Dec 27, 2021)
<hr />

**Comment by mwu-tow** [comment]
Was mostly done.
