### ISSUE TITLE
Eliminate all panic branches from parser

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5445]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182811073).
<hr />

The parser should not have any `panic` / `unwrap` / `except` calls, even in code that is not expected to be reachable; if an internal error occurs, the parser should produce an `Invalid` node for the subtree that was not able to be parsed.

**Comment by kazcw** [comment]
The existing panics have not been a problem. Let's just continue to be sure to handle any case that isn't *definitely* unreachable.
