### ISSUE TITLE
Compute full (UTF16) span info in parser

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5449]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/184004555).
<hr />

Refactor source references.

# In Rust

In Rust a source code reference is currently a `Cow<str>`, so when serializing we don't know anything about a tree or token's corresponding code except its length (and contents). To be able to serialize/deserialize with only that information, the AST must reference every part of the input exactly once, in input order, so that when deserializing we can construct source document offsets by maintaining a running total of lengths. This restriction causes some difficulties:
- It is incompatible with macro expansion in the parser.
- Although the AST always *should* correspond exactly to the input, currently if we lose any character, the rest of the AST is corrupted, escalating what should be a minor bug: https://discord.com/channels/401396655599124480/1020366298661793802/threads/1031901019229126719

# In Java

In Java, source references are already document-relative indexes; however, to best support reporting source locations in macro output, each source reference should also identify its source document or macro-expansion.

**Comment by kazcw** [comment]
The new parser relies on UTF-16 document locations in the `Span` and `Code` objects. I have mostly implemented this now, but have a few cases remaining.
