### ISSUE TITLE
Intersection of shapes doesn't work with shadows

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5454]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/182593513).
<hr />

Copied from discord thread https://discord.com/channels/401396655599124480/991392411739758682/991392413555888168

I faced these issues while working on the component browser, but we can reproduce it on a much simpler example. I used the custom-shape-system demo scene: https://github.com/enso-org/enso/compare/wip/vitvakatu/reproduce-shadow-issues

1. Let's add a simple rectangular background with a shadow, and add a rectangular shadow on top of it [pic1]
The code is straightforward [code-pic1]
2. Our goal is to clip the shadow in such a way that it fits inside the background shape (no part of it sticks out). That should be simple, we have an intersection method on shapes! (The * operator does the same afaik) [code-pic2]
But the result doesn't look like we make an intersection, it rather messes up the order of shapes [pic2]
3. Even worse, if we make some code modifications like moving one line to another place [code-pic3] we see that the rendering is completely broken [pic3]. I must say this is not the only way to get a similar result, but I'm not sure I've found some pattern here.

Probably related (**easier way to reproduce**): https://github.com/enso-org/enso/pull/3686#discussion_r969989035

## Comments:
 (Ilya Bogdanov - Jun 29, 2022)
<hr />

**Comment by farmaazon** [comment]
Issue related to EnsoGL which is no longer used.
