### ISSUE TITLE
Java formatter doesn't work on files that use latest syntax

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5461]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/182515732).
<hr />

It appears that Java formatting tool silently(!) fails to run on Java sources that use latest syntax (as allowed by Frgaal). This, as it turns out, is a feature of Google Format tool because it [detects JDK version](https://github.com/google/google-java-format/blob/e0132d0fb62624d6616426e8c9e450a814f2db02/core/src/main/java/com/google/googlejavaformat/java/Formatter.java#L154) while running and enhances constructs it can use. It also relies on JDK's parser so it's not like it is possible to magically configure that in their tool/sbt plugin.

There a couple of solutions to this problem, none of which are perfect:
1. We do nothing, it's a pity but it is not the end of the world. We might run/check it occasionally.
2. We provide a way for people to run the formatting tool via some bash script (requires JDK 17 on devs machine). Additionally CI would have to be updated to ensure that the check job runs the appropriate JDK
3. We adapt SBT to allow to run formatting only with JDK17-based Graal. The disadvantage is that one has to still restart SBT with a different JDK. Additionally we would have to ping maintainers of [sbt-java-formatter](https://github.com/sbt/sbt-java-formatter) to bump the version of google format tool they use because it is pretty outdated and has a number of bugfixes for latest Java stuff (or fork it/publish under our own org).

Is this really a problem? 
I tweaked the setup a bit and run the formatter on our current develop branch and here are some rough stats for the expected change
```
 96 files changed, 1363 insertions(+), 834 deletions(-)
```

## Comments:
There is a [GitHub Actions job](https://github.com/enso-org/enso/blob/develop/.github/workflows/formatting.yml#L13) which checks the formatting. The simplest solution is to change it to run on the latest JDK (either JDK19 or GraalVM 22.2 java17). It is just a CI fix, but it'd would allow us to close this story. (jaroslavtulach - Aug 24, 2022)
<hr />

**Comment by hubertp** [comment]
Despite the upgrade to JDK21, the formatter is still not capable of handling the new format.
This is because `sbt-java-formatter` plugin has a (very) outdated version of google format dependency.
Changes of getting upgrade are rather slim, I would say. We might need to fork and release ourselves.

**Comment by Akirathan** [comment]
Was fixed by https://github.com/enso-org/enso/pull/8543
