### ISSUE TITLE
Make the interpreter assumption of `Standard.Base` parametrizable

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5465]
This task is automatically imported from the old Task Issue Board and it was originally created by Marcin Kostrzewa.
Original issue is [here](https://www.pivotaltracker.com/story/show/182487649).
<hr />

Currently the interpreter assumes certain types (Date, Vector...) are located in certain modules in `Standard.Base`. It would sometimes be useful to use an alternative stdlib, mostly for testing. For such a use case it should be possible to re-parametrize the intepreter to use the provided alternative stdlib.

**Comment by jdunkerley** [comment]
We have the micro-distribution now.
