### ISSUE TITLE
Separate annotation processor from compilation in SBT

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5468]
This task is automatically imported from the old Task Issue Board and it was originally created by Hubert Plociniczak.
Original issue is [here](https://www.pivotaltracker.com/story/show/182463758).
<hr />

SBT has a problem with sources produced during javac annotation processing.
In order to reduce the number of recompilations we should investigate separating javac compilation into two:
1. Run javac with `-proc:only`
2. Run javac with `-proc:none`

## Comments:
Obsolete after splitting `runtime` into more projects each with a single instrument/language, I guess. Let's close this one? (jaroslavtulach - Jun 16, 2022)
<hr />
Nope, still the case. Just run `sbt compile` twice and on the second attempt it will still try to re-compile unnecessary Java files. (Hubert Plociniczak - Jun 16, 2022)
<hr />

**Comment by hubertp** [comment]
Still a problem but unlikely to have resources to address it. Workarounds are available.

**Comment by hubertp** [comment]
We can live without it for now. Potentially could be better adressed in bazel.
