### ISSUE TITLE
Development documentation webpage is automatically updated with GUI docs.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5469]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/180302885).
<hr />

## Why
**As** developer
**I want** to have GUI dev documentation page automatically updated from the repository
**So that** I can publish update to documentation through usual PR process

## Acceptance Criteria
```gherkin
Scenario: 
GIVEN I am working on a documentation update
WHEN I am merging my changes
THEN webpage with dev docs is automatically updated.
```

**Comment by farmaazon** [comment]
We don't maintain developer docs from a while, let's make a new "bring back dev docs" if anyone feel it needed.
