### ISSUE TITLE
List View reports non-existing entry as selected

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5470]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/182358403).
<hr />

### Steps to reproduce
Unfortunately, there is no clear way to reproduce this issue. It depends on the viewport size of the Enso window. One of the possible sizes of window (`window.screen.avail{Width,Height}`) is `(1512, 944)`.

1. Open `list-view` demo scene in a browser window of a specific size.
2. Move the cursor below the last element of the list

### Expected
The list view won't report an element with `Id = len(list_view)` .

### Actual
The list view reports `selected_entry` FRP events with `Id` of N, where N is a count of entries in the list view. (Ids start from 0).

See attached video in the first comment.
The video uses modified list view code:

```diff
diff --git a/lib/rust/ensogl/example/list-view/src/lib.rs b/lib/rust/ensogl/example/list-view/src/lib.rs
index efba495dd..c55aa7db2 100644
--- a/lib/rust/ensogl/example/list-view/src/lib.rs
+++ b/lib/rust/ensogl/example/list-view/src/lib.rs
@@ -93,8 +93,8 @@ fn init(app: &Application) {
     theme::builtin::light::enable(&app);

     let list_view = app.new_view::<list_view::ListView<list_view::entry::GlyphHighlightedLabel>>();
-    let provider = list_view::entry::AnyModelProvider::new(MockEntries::new(1000));
-    list_view.frp.resize(Vector2(100.0, 160.0));
+    let provider = list_view::entry::AnyModelProvider::new(MockEntries::new(15));
+    list_view.frp.resize(Vector2(100.0, 427.0));
     list_view.frp.set_entries(provider);
     list_view.focus();
     app.display.add_child(&list_view);
```
The size and amount of entries were chosen based on the first encounter of this bug in the component-group demo scene.

```diff
diff --git a/lib/rust/ensogl/component/list-view/src/lib.rs b/lib/rust/ensogl/component/list-view/src/lib.rs
index 221913bb1..6b18e3142 100644
--- a/lib/rust/ensogl/component/list-view/src/lib.rs
+++ b/lib/rust/ensogl/component/list-view/src/lib.rs
@@ -476,6 +476,8 @@ where E::Model: Default
             mouse_pointed_entry <- mouse_y_in_scroll.map(f!([model](y)
                 entry::List::<E>::entry_at_y_position(*y,model.entries.entry_count()).entry()
             ));
+            debug <- mouse_pointed_entry.filter_map(|e| *e);
+            trace debug;


             // === Selected Entry ===
```

## Comments:
 (Ilya Bogdanov - Jun 2, 2022)
<hr />

**Comment by sylwiabr** [comment]
@wdanilo @farmaazon do we want to fix it or we are removing list view?

**Comment by farmaazon** [comment]
List View was removed along with entire EnsoGL
