### ISSUE TITLE
Slider doesn't follow mouse cursor

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5473]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/182323104).
<hr />

### Steps to reproduce
1. Open a `slider` demo scene
2. Using a Mac touchpad (other input methods are to be checked), click-and-drag the slider
3. Observe that the cursor is not following the slider border at exact same distance as at the start of the movement. 

### Expected
The slider border must follow the mouse cursor precisely, otherwise, it's harder to make small adjustments to the value.

### Actual
The cursor changes its relative position to the slider's border.

See attached video in the first comment.

## Comments:
 (Ilya Bogdanov - May 30, 2022)
<hr />

**Comment by vitvakatu** [comment]
Seems to be fixed
