### ISSUE TITLE
Table visualization incorrectly renders custom Enso objects

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5480]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/182263745).
<hr />

See Discord thread https://discord.com/channels/401396655599124480/978315597400145920/978316216408092763

### Steps to reproduce
1. Make sure that `import Standard.Table` is included at the beginning.
2. Create a node `Table.new [["foo", [Ordering.Less, Ordering.Equal]]]`.
3. Show the visualization and switch it to `Table`.

### Expected

The visualization cells should display `Less` and `Equal`.

### Actual

They display `[object Object]` instead.

### Comment

For comparison, if we add a node `. at "foo" . to_vector` and show the `Table` visualization on the Vector type, it is displayed correctly. So the logic for vectors seems to be correct and the logic for tables seems to lack something, but it should be fairly easy to just adapt the logic from vectors.

## Comments:
Screenshots of the described repro. (Radosław Waśko - May 23, 2022)
<hr />

**Comment by vitvakatu** [comment]
It seems the issue is in the logic of table visualization (see `toTableCell` function).

**Comment by jdunkerley** [comment]
JSON serialization of an Object should include the `to_display_text` within the Table viz.
This can then be used within table.js to render the value. This can also remove the Date, Time_Of_Day and Date_Time workaround.

**Comment by jdunkerley** [comment]
Table.js now has support for `_DISPLAY_TEXT_`.
This ticket is to update the enso serialization to add that and simplify the table.js

While here steal ownership!

**Comment by jdunkerley** [comment]
Include rendering of JS_Object.
