### ISSUE TITLE
Nodes are not reordered if a reference is introduced in text-edit mode

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5481]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/182225245).
<hr />

See https://github.com/enso-org/enso/issues/3156 for reference.

A quick repro is following: 
1. Create a `Table.new` node, do not apply any args to it yet.
2. Create two nodes `["a", [1,2]]` and `["b", [3,4]]`.
3. Now, Ctrl+LMB the `Table.new` node, and in the 'edit node contents as text' (I don't know the official name) mode, fill in the arguments, for example `[var3, var4]` (the names will depend on the variable names associated with the two nodes from step (2)). Click enter to confirm the edit.
4. You will see a compile error saying that a variable name is not defined.
5. Inspect the created code in the code editor, it will be like:
   ```
   ...
   operator5 = Table.new [var3, var4]
   var3 = ["a", [1,2]]
   var4 = ["b", [3,4]]
   ```

For comparison, you can follow the same steps 1 and 2, but instead of step 3 do: Ctrl+LMB to edit, but type `[_, _]` creating two 'placeholder holes'. Now connect the two nodes to these placeholders. In that case the table will be correctly created and you will see in the code editor that the nodes have been reordered correctly so that the `Table.new` is now _below_ the other two.

Similarly, if you create the connections in the code editor, they will also appear, but the computation will not be updated correctly either (it displays `null` as its visualization). This may be a broader issue with the code editor itself though.

## Summary

The nodes are added to the code in the order in which they are created (I'm skipping the situation where there are dependencies at creation time, assuming nodes that do not depend on any others). If then dependencies are created by using the drag-and-drop connection creation, they are correctly reordered. However, it seems that the reordering algorithm does not fire if the dependency/connection is created using text-editing.

Interestingly though, the connections are correctly detected and displayed using the 'arrows' in the graph. So the dependency is detected, but the reordering seems not to kick-in if it was created in text-mode.

## Comments:
A screenshot showing the repro:  (Radosław Waśko - May 18, 2022)
<hr />

**Comment by farmaazon** [comment]
Superseded by [#6915](https://github.com/enso-org/enso/issues/6915)
