### ISSUE TITLE
Deleting multiple nodes does not always work correctly

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5482]
This task is automatically imported from the old Task Issue Board and it was originally created by Keziah Wesley.
Original issue is [here](https://www.pivotaltracker.com/story/show/182213475).
<hr />

When I do this:

1. Use the "Create a new project" button on the Welcome Screen to open a new project with two nodes.
2. Select both nodes.
3. Press the delete key.

The result I get is: Usually (not always), only one of the selected nodes is deleted.

Expected result: Both nodes should be deleted.

Example video in attachments.

## Comments:
 (Keziah Wesley - May 17, 2022)
<hr />

**Comment by sylwiabr** [comment]
is this still valid?

**Comment by vitvakatu** [comment]
It was probably fixed in #4084, not reproducible on a current develop. @kazcw, as the original reporter, please create a new issue if it is still the case.
