### ISSUE TITLE
IDE User should experience minimal delay when collapsing nodes.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5483]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/182196203).
<hr />

### Why

**As** IDE user
**I want ** to be able to collapse groups of nodes with minimal delay
**So that ** I have a smooth experience of working with the IDE

### Acceptance Criteria

```gherkin
Scenario: 
Given I have an open project in the IDE
When I select some nosed and press ctrl+g
Then the new node should be created and the visualisation should be visible instantly. 
```

**Notes:**

This user story is written aspirational, and delays should be as minimal as possible, but might not be instant in the end. The actual threshold for acceptance will need to be decided while investigating possible improvements.

## Tasks:
- [X] Analyze what happens in the engine when collapsing node

## Comments:
	Attached is VisualVM profiling snapshot file that shows what happens when nodes in the default project get collapsed. Collapsing took `457ms` on my Mac. 
- `304ms` is compilation from which `285ms` is parsing
- `80ms` to analyzeModule & sendModuleUpdate
- `70ms` taken by the actual execution of the Enso program

One attached image shows the time dominated by compilation. The other one shows the `deserializing` section. (jaroslavtulach - May 16, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-05-16):

**Progress:** Collapsing nodes slowness is on the engine side dominated by parsing - evidence uploaded. Fun with benchmarks for https://github.com/enso-org/enso/pull/3440 - learning to debug them. At the end confirming `AtomBenchmarks` are unstable - evidence uploaded to https://www.pivotaltracker.com/n/projects/2539304/stories/182199750 It should be finished by 2022-07-31.

**Next Day:** Focus on summarizing dynamic drop-downs thoughts. Continue performance work. (Enso Bot - May 17, 2022)
<hr />
	@dmitry_bushev pointed out that subsequent invocations of something in the JVM are more representative than the first one. How could I forget! As such I decided to repeat my experiment three times. Collapse nodes, undo, collapse nodes, undo, collapse nodes. This `.nps` file is from the 3rd collapsing. Results:
- It takes just `155ms` - e.g. everything gets faster compared to the first invocation
- `133ms` is related to compiling 
   - `122ms` of that clearly belongs to the parser
   - `org.enso.compiler.Compiler.runImportsAndExportsResolution` compiler phase takes `11ms`
- the JSON serialization is not even visible - compared to the previous experiment - looks like the first invocation initialises some data structures and that takes time
- `10ms` took by `org.enso.compiler.PackageRepository$Default.getLoadedModules`
- actual execution of the program took `12ms`: `org.enso.interpreter.instrument.job.ProgramExecutionSupport$.runProgram()` (jaroslavtulach - May 17, 2022)
<hr />
Following approach is being used to obtain the data:
```
ENSO_JVM_OPTS=-Dcom.sun.management.jmxremote.authenticate=false\ -Dcom.sun.management.jmxremote.ssl=false\ -Dcom.sun.management.jmxremote.port=9090  /Applications/Enso.app/Contents/MacOS/Enso
```
and then, from another terminal invoke following command to start collecting the data:
```
/Applications/Enso.app/Contents/Resources/enso/runtime/graalvm-ce-java11-21.1.0/Contents/Home/bin/java -jar /Applications/Enso.app/Contents/Resources/enso/runtime/graalvm-ce-java11-21.1.0/Contents/Home/lib/visualvm/platform/modules/org-netbeans-modules-sampler.jar 9090 output_sample.npss
```
when an experiment is done, press enter to obtain `output_sample.npss`. Analyze the file in `/Applications/Enso.app/Contents/Resources/enso/runtime/graalvm-ce-java11-21.1.0/Contents/Home/bin/jvisualvm`. (jaroslavtulach - May 17, 2022)
<hr />
**Jaroslav Tulach** reports a new **STANDUP** for yesterday (2022-05-17):

**Progress:** Benchmarking to find a regression, talking about interop (Time, Date & Array) It should be finished by 2022-07-31.

**Next Day:** Write down dynamic drop-downs thoughts. Continue performance work. (Enso Bot - May 18, 2022)
<hr />

**Comment by jdunkerley** [comment]
Closing as will raise as more detailed tickets as needed.
