### ISSUE TITLE
Scroll area content rendering bug

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5484]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/182193824).
<hr />

Adding a Component Group View to the scroll area content does not make it visible, though adding an arbitrary shape (like a transparent circle) fixes the issue.

To reproduce: 
1. open the `component-group` demo-scene in the https://github.com/enso-org/enso/commit/4ebf637fd489b120d446cb30e9d7d0228ae673bf 
2. Remove the `scroll_area.content().add_child(&transparent_circle)` line
3. Observe that component groups are no longer visible.

The bug is probably related to masking the sublayers. (the component group is not in the `masked_layer` of the ScrollArea, but rather in one of its sublayers)

**Comment by farmaazon** [comment]
No longer relevant in GUI2
