### ISSUE TITLE
IDE User should experience minimal delay when viewing a new visualization.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5489]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/182060084).
<hr />

### Why

**As** IDE user
**I want ** to be able to view data from new nodes with minimal delay
**So that ** I have a smooth experience of working with the IDE

### Acceptance Criteria

```gherkin
Scenario: 
Given I have an open project in the IDE
When I press tab to create a new node
Then The new node should be created and the visualisation should be visible. 
```

**Notes:**

This user story is written aspirational, and delays should be as minimal as possible, but might not be instant in the end. The actual threshold for acceptance will need to be decided while investigating possible improvements.

**Comment by jdunkerley** [comment]
Closing as do more detailed tasks anyway.
