### ISSUE TITLE
IDE User should experience minimal delay when opening a new project.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5490]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/182036435).
<hr />

### Why

**As** IDE user
**I want ** to be able to open a new project with minimal delay
**So that ** I have a smooth experience of working with the IDE

### Acceptance Criteria

```gherkin
Scenario: 
Given I have the IDE opened at the welcome screen
When I select a project to open
Then the new project should be visible, ready to interact and fully populated with type information, and visualisations immediatly. 
```

**Notes:**

This user story is written aspirational, and delays should be as minimal as possible, but might not be instant in the end. The actual threshold for acceptance will need to be decided while investigating possible improvements.

## Blockers:
[#182024911](https://www.pivotaltracker.com/story/show/#182024911) resolved

**Comment by jdunkerley** [comment]
Removing as now have a performance epic.
