### ISSUE TITLE
No indication of errors in user's imports in the GUI

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5493]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/181935722).
<hr />

### General Summary

If modules imported by the user (from the same project) fail to compile, an indication for this error should be shown in the GUI so that the user can resolve the error.

Currently the compile is only visible in the project-manager logs which are not visible by default.

The GUI is stuck showing `Compiling standard library...` (I have verified that after waiting a while that message still stays, even though the language server stopped logging any compilation progress with one of the last logs being an indication of dependency compilation error), confusing the user that something is still in progress.

### Motivation

The user should know that the project fails to load due to an error in imported modules to be able to resolve the errors.

Migrated from: https://github.com/enso-org/enso/issues/2809

## Comments:
Migrated comment from original GH issue by @farmaazon :

> I'm not sure if we receive any message from the engine, when compiling module fails? (Radosław Waśko - Apr 19, 2022)
<hr />

## Notes

This should be fixed by displaying information we receive from `executionContext/status`. We'll use the new notification list for that #5201.

**Comment by jdunkerley** [comment]
This can lead to a scenario where the UI changes do nothing so we will keep in the release for examining.

**Comment by 4e6** [comment]
Compilation errors and warnings are reported as [`executionContext/executionStatus`](https://github.com/enso-org/enso/blob/53d5487f475980566fbc1e54bb7a457aeee21b4b/docs/language-server/protocol-language-server.md#executioncontextexecutionstatus) notifications.

For example, for the program
```py
from Standard.Foo import all
import Standard.Visualization

main =
    operator1 = 0.up_to 100 . to_vector . map .noise
    operator2 = operator1.sort
```
It returns
```json
{"jsonrpc":"2.0","method":"executionContext/executionStatus","params":{"contextId":"c55916b1-a06c-44b0-b8d0-45cff28a3df0","diagnostics":[{"kind":"Error","message":"Package containing the module Standard.Foo.Main could not be loaded: The package could not be resolved: The library `Standard.Foo` is not defined within the edition.","path":{"rootId":"7c246d5d-c478-4b2a-9c01-89579e02c343","segments":["src","Main.enso"]},"location":{"start":{"line":0,"character":0},"end":{"line":0,"character":28}},"expressionId":"82903ccc-de94-4b35-abad-e2dfc9d1db81","stack":[]},{"kind":"Warning","message":"Unused variable operator2.","path":{"rootId":"7c246d5d-c478-4b2a-9c01-89579e02c343","segments":["src","Main.enso"]},"location":{"start":{"line":5,"character":4},"end":{"line":5,"character":13}},"expressionId":"f546dc8e-f5c0-47ba-9723-2ed71865282a","stack":[]}]}}
```

**Comment by 4e6** [comment]
I guess the question is how to show this information because it is not associated with any node on the screen.

**Comment by jdunkerley** [comment]
I think it should be shown as a message like we do for the engine mismatch version.

**Comment by vitvakatu** [comment]
It is probably blocked by #5201, because the current messages infrastructure sucks

**Comment by farmaazon** [comment]
Estimated for 2 days, but assuming that #5201 will be done before

**Comment by hubertp** [comment]
Please note this only concerns failure when finding the library.
Invalid imports are generally not reported in CLI either.

**Comment by farmaazon** [comment]
The message is no longer stuck; but indeed GUI does not display errors returned from `executionContext/executionStatus` like this one below:

```{
  "jsonrpc": "2.0",
  "method": "executionContext/executionStatus",
  "params": {
    "contextId": "20fe43bd-f1fc-4bb0-b8e0-3517b80d974a",
    "diagnostics": [
      {
        "kind": "Error",
        "message": "Package containing the module Standard.Foo.Main could not be loaded: The package could not be resolved: The library `Standard.Foo` is not defined within the edition.",
        "path": {
          "rootId": "09f71dab-b70f-47fe-80d1-3089570ab5c3",
          "segments": [
            "src",
            "Main.enso"
          ]
        },
        "location": {
          "start": {
            "line": 0,
            "character": 0
          },
          "end": {
            "line": 0,
            "character": 28
          }
        },
        "expressionId": "314a758c-c019-4a31-89ca-0f3c189f7817",
        "stack": []
      },
      {
        "kind": "Warning",
        "message": "Unused variable operator2.",
        "path": {
          "rootId": "09f71dab-b70f-47fe-80d1-3089570ab5c3",
          "segments": [
            "src",
            "Main.enso"
          ]
        },
        "location": {
          "start": {
            "line": 5,
            "character": 4
          },
          "end": {
            "line": 5,
            "character": 13
          }
        },
        "expressionId": "471d12db-e74c-42e5-8751-091896c575f9",
        "stack": []
      }
    ]
  }
}```

We could add those at least to Code Editor diagnostics.

**Comment by jdunkerley** [comment]
Shown in code editor.
