### ISSUE TITLE
Builtin Array Is Exposing Nulls to Surface Language

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5494]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/181935648).
<hr />

### General Summary

It is possible to encounter pure `null` values in the surface language if `Array` elements are accessed when they are not initialized.

### Steps to Reproduce

1. Launch `enso repl`.
2. Do the following steps and observe the output:
```
> a = Array.new 1
>>> Nothing
> b = a.at 0
>>> Nothing
> IO.println b
null
Evaluation failed with: java.lang.NullPointerException
java.lang.Exception: java.lang.NullPointerException
    at org.enso.interpreter.runtime.callable.atom.Atom.lambda$toString$0(Atom.java:80)
    at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    (...)
```
### Expected Result

`null`s should not leak to the user. Printing missing values should not result in a crash.

`Array` API should be designed in such a way to never expose pure `null`s to the user.

### Actual Result

An exception is thrown.

### Enso Version

```
Enso Launcher
Version:    0.2.0
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: enso-0.2.0 @ d2df28bc43fcfee614fb31780cd46a59ebb16127
Built on:   Linux (amd64)
Current default Enso engine: 
Enso Compiler and Runtime
Version:    0.2.2-SNAPSHOT
Built with: scala-2.13.3 for GraalVM 20.2.0
Built from: wip/rw/database-library* @ 7e9d7e0ef10a609ead816375386b86f473219bcd
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.8+10-jvmci-20.2-b03
            Linux 4.15.0-132-generic (amd64)
```

Migrated from https://github.com/enso-org/enso/issues/1424

**Comment by JaroslavTulach** [comment]
With 4dcf802831bea716c26b7870f056b43d19744a12 I am getting the exception even sooner:
```
enso$ ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --repl
a = Array> a = Array.new 1
>>> Nothing
> b = a.at 0
Evaluation failed with: Null receiver values are not supported by libraries.
java.lang.Exception: Null receiver values are not supported by libraries.
        at com.oracle.truffle.api.library.LibraryFactory.dispatch(LibraryFactory.java:528)
        at com.oracle.truffle.api.library.LibraryFactory.create(LibraryFactory.java:295)
        at org.enso.interpreter.runtime.error.WarningsLibraryGen$CachedDispatch.specialize(WarningsLibraryGen.java:542)
        at org.enso.interpreter.runtime.error.WarningsLibraryGen$CachedDispatch.hasWarnings(WarningsLibraryGen.java:492)
        at org.enso.interpreter.runtime.data.Array.hasWarningElements(Array.java:160)
        at org.enso.interpreter.runtime.data.Array.hasWarnings(Array.java:170)
```

**Comment by JaroslavTulach** [comment]
I have a fix:
- #5736 

but there is a question puzzling in my mind: _What's the point of having `Array.new size` now, when there is no `set` method and `Array` is immutable!?_ CCing @jdunkerley and @radeusgd

**Comment by jdunkerley** [comment]
> but there is a question puzzling in my mind: _What's the point of having `Array.new size` now, when there is no `set` method and `Array` is immutable!?_ CCing @jdunkerley and @radeusgd

A fair question - we still have Array in a couple of places, but we should probably reduce this. There are 2 places we use `Array.copy` to fill it.
