### ISSUE TITLE
Panics in IDE built with `./run watch`

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5497]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/181867429).
<hr />

### Steps to reproduce
1. On Mac, start the development IDE and wait until it compiles: `./run watch`
2. Open Chrome (`Version 98.0.4758.102 (Official Build) (x86_64)`)
3. Navigate Chrome to: http://localhost:8080/?project=Unnamed
4. Open Developer Console in Chrome

### Expected
IDE should display the contents of the Project.

### Actual
A "spinner" circle shows. After a while, the Chrome window flashes; after the flash, the website area's content shows as empty in Chrome, and the Developer Console shows some panics. The panics seem to vary in messages and their order on repeated attempts at reproducing the issue. Refreshing Chrome or quitting it and then starting again also varies the messages in the console. The attachments contain some representative samples of the messages observed (screenshots + console log dumps).

Note: clean rebuild (after `rm -rf dist/ ; ./run clean`) does not appear to resolve the issue.

### Additional notes

 - possibly related: #181296145

## Comments:
Probably an Electron or a EnsoGL issue. Needs to be investigated from the GUI side.  (Michael Mauderer - Feb 1, 2023)
<hr />

**Comment by farmaazon** [comment]
@wdanilo is this still relevant?

**Comment by wdanilo** [comment]
It's fixed!
