### ISSUE TITLE
Code highlighting disappears when editing the node

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5502]
This task is automatically imported from the old Task Issue Board and it was originally created by Dmitry Bushev.
Original issue is [here](https://www.pivotaltracker.com/story/show/181590920).
<hr />

When you start editing the node, the code loses its syntax highlighting, see attached video.

## Comments:
Attached video (Ilya Bogdanov - Mar 16, 2022)
<hr />

**Comment by 4e6** [comment]
The node is correctly re-colored after the editing is done.
