### ISSUE TITLE
User should be able to undo/redo the opening of visualizations after deselecting them.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5503]
This task is automatically imported from the old Task Issue Board and it was originally created by Michael Mauderer.
Original issue is [here](https://www.pivotaltracker.com/story/show/181585473).
<hr />

### Steps to reproduce
1. Open a visualization on a node.
2. Click on the background of the project.
3. Press cmd-z

### Expected
Visualization should close.

### Actual
Nothing happens.

**Comment by 4e6** [comment]
Can reproduce on the current develop 75fda33837214a774b7c8bbbbe64aeb72db069bd

**Comment by farmaazon** [comment]
Works in GUI2
