### ISSUE TITLE
Duplicated `stop_editing` event in GraphEditor

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5506]
This task is automatically imported from the old Task Issue Board and it was originally created by Ilya Bogdanov.
Original issue is [here](https://www.pivotaltracker.com/story/show/181578044).
<hr />

For some reason, GraphEditor emits `stop_editing` event twice when accepting new node creation/editing with `Enter` key.

To reproduce:
1. Open a default project. You should add `trace frp.stop_editing` somewhere in GraphEditor FRP code.
2. Start editing a node.
3. Press Enter. You will see two `stop_editing` events in the console.

OR:
1. Open a default project
2. Create a new node with the `.sort` node selected (either by using TAB key or by dropping a connection)
3. Type `.length` expression and press Enter. Any other valid expression will work as well.
4. You will see two `stop_editing` events in the console.

**Comment by farmaazon** [comment]
Related to old GUI
