### ISSUE TITLE
Attempting to drop a connection just below a node does not create a new node.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5508]
This task is automatically imported from the old Task Issue Board and it was originally created by Mateusz Czapliński.
Original issue is [here](https://www.pivotaltracker.com/story/show/181369980).
<hr />

### Steps to reproduce
1. Open the default project in the IDE.
2. Click the output port (bottom edge) of a node, to start dragging a connection from the node.
3. Hover the mouse just below the bottom edge of the node - observe a name of an Enso type showing (for example, `Vector`)
4. Click the mouse just below the bottom edge of the node, on the type name that is showing.

### Expected
A new node should be created.

### Actual
No node is created. See the attached [screencast][].

[screencast]: https://www.pivotaltracker.com/file_attachments/114817650/download?inline=true

## Comments:
 (Mateusz Czapliński - Feb 24, 2022)
<hr />

**Comment by farmaazon** [comment]
Fixed in GUI2
