### ISSUE TITLE
Auto-import does not work for Atom constructors

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5514]
This task is automatically imported from the old Task Issue Board and it was originally created by Radosław Waśko.
Original issue is [here](https://www.pivotaltracker.com/story/show/181309938).
<hr />

### Steps to reproduce
1. Open the IDE
2. Type `By_Index` in the searcher
3. Use tab and proceed to create a node `By_Index [0]`

### Expected
I would expect the created node to create an instance of the ADT. I would expect that the IDE would add an import to bring the requested constructor into scope, as it does for methods (like `Table.from_vector`).

### Actual
The node gets created but returns a compile error saying that the constructor could not be found.

## Comments:
 (Radosław Waśko - Feb 18, 2022)
<hr />

**Comment by farmaazon** [comment]
In GUI2, we add the typename (`Index_Sub_Range.By_Index [0]`) with proper import.
