### ISSUE TITLE
Disable icon in section Component Browser's section navigator if there is no entry in that section.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5517]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183523727).
<hr />

## Why

**As** Enso IDE user
**I want** to see grayed out icons in section navigator if related section have no entries displayed
**So that** I'll clearly see that the button does not work

## Acceptance Criteria

```gherkin
Scenario: 
GIVEN I have Component Browser opened
WHEN I enter any module
THEN the "Popular tools" section icon is grayed out, and hovering/clicking it does nothing.
WHEN I enter any module without submodules
THEN the "Submodules" section icon is similarly disabled.
```

**Comment by farmaazon** [comment]
No longer valid in the new design
