### ISSUE TITLE
Recognize "as" keyword when creating import::Info from AST.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5518]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/183590537).
<hr />

## Description
Our double-representation structure for imports does not recognize "as" keyword for aliases, as the old parser also seems to not handling those properly. Once new parser will land, the AST for import with aliases shall be checked and added to the import::Info structure

**Comment by farmaazon** [comment]
In GUI2 we have dedicated AST representation of imports, including aliases.
