### ISSUE TITLE
Add missing ways of closing Component Browser

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5519]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/182713510).
<hr />

### Why

**As Enso IDE user**
**I want ** to have various ways of opening/closing searcher
**So that ** I can use what meet my needs.

### Scope

 - Section about [closing](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#closing-the-component-browser).
 - Section about [accepting suggestions and expressions](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#accepting-suggestions-and-expressions).

### Acceptance Criteria

```gherkin
Scenario: 
Given
When
Then
```

**Notes:**

**Comment by farmaazon** [comment]
The old design is more-or-less covered (for things which weren't later changed).
