### ISSUE TITLE
Accepting method suggestion without this port specified

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5536]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/181061824).
<hr />

### Why

**As Enso IDE user**
**I want ** to see "this" port ready to connect, if I picked a method and have no source input specified
**So that ** I can connect proper connection to "this" later.

### Scope

[This section](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#using-methods-with-this-port-not-connected)

### Acceptance Criteria

```gherkin
Scenario: 
Given
When
Then
```

**Notes:**

**Comment by farmaazon** [comment]
In the new design version we don't display methods without source node.
