### ISSUE TITLE
Undo-Redo

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5537]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/181061289).
<hr />

### Why

**As Enso IDE User**
**I want ** to have Undo-Redo shortcuts working properly in Expression Input
**So that ** I can treat Expression Input as a civilized text input.

### Scope

[This short section](https://github.com/enso-org/design/blob/main/epics/component-browser/design.md#undo-redo)

### Acceptance Criteria

```gherkin
Scenario: 
Given
When
Then
```

**Notes:**

**Comment by farmaazon** [comment]
in GUI2 we have browser support for undo-redo, but it does not handle applied suggestions (the UR stack is seemingly cleared on programmatic changes).

**Comment by farmaazon** [comment]
UR is implemented and mostly working. Any issue should be reported separately.
