### ISSUE TITLE
Enso developers should have access to predefined checkbox-like components.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5540]
This task is automatically imported from the old Task Issue Board and it was originally created by Wojciech Daniło.
Original issue is [here](https://www.pivotaltracker.com/story/show/180890619).
<hr />

## Why
Checkboxes are a very common UI element. They will be often used on the nodes if the type of the parameter is a 2-variant ADT containing one of the Boolean atoms. For example, an argument `use_regexp : False | Regexp` should be displayed as a check box in the GUI which when turned on, should display additional parameters of the `Regexp` atom.

## Implementation Notes
This task is about implementing the set of components allowing displaying checkboxes in GUI. In particular:

1. A `Checkbox` component – combination of a ToggleButton component (already existing) with a label.
2. A `CheckboxGroup` component – a set of checkboxes where one or many can be clicked.

An example implementation of other components can be found [here](https://github.com/enso-org/enso/tree/develop/lib/rust/ensogl/component). In particular, please see the [ToggleButton component](https://github.com/enso-org/enso/blob/develop/lib/rust/ensogl/component/toggle-button/src/lib.rs).

Please note, that in order to keep the development efficient, you should create a new debug scene and test it when developing this task (it will not require to compile all GUI dependencies, allowing you to wait 2-5 seconds for compilation of the results): https://github.com/enso-org/enso/tree/develop/lib/rust/ensogl/example

The build instructions can be found [here](https://github.com/enso-org/enso/tree/develop/app/gui).

It is possible, that the ToggleButton component would need to be modified during this task implementation.

**Comment by farmaazon** [comment]
Related to no longer maintained EnsoGL.
