### ISSUE TITLE
Unify JSON-RPC and binary RPC

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5549]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/180399347).
<hr />

## Description
Currently we have two RCP handlers: one in the `json-rpc` crate and the second one in the `enso-protocol`. The latter should be used also for JSON-RPC and replace the former completely.

Getting rid of duplicated logic will allow better code reuse. Also, features developed for binary handler (`mockall` based mocks, better logging, etc) will bring benefit to users of JSON-RPC.

**Comment by mwu-tow** [comment]
No longer relevant, the code is gone.
