### ISSUE TITLE
Developer can use tokio-based transports with JSON-RPC crate

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5550]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/180399744).
<hr />

## Why
Who wants the functionality, why, and to what end? This is incorporated so that everyone on the team understands why the feature is being added. If you cannot think of a reason, then it’s worth reassessing if the feature should be included. The business case also allows others on the team to think if there is a better user experience than the one provided. Use the following template:

**As** a developer
**I want** to use our json-rpc crate with TCP and named-pipe tokio-provided implementations
**So that** I can reuse code from the crate when developing build scripts.

## Acceptance Criteria
```gherkin
Scenario: 
GIVEN I have tokio-based `AsyncRead` and `AsyncWrite`
WHEN I want to create a new JSON-RPC-based protocol handler
THEN I can trivially used these as a transport.
```

## Blockers:
[#180303561](https://www.pivotaltracker.com/story/show/#180303561) resolved
[#180399347](https://www.pivotaltracker.com/story/show/#180399347) blocked

**Comment by farmaazon** [comment]
Closing as related to old GUI
