### ISSUE TITLE
CI developer can interact with SBT server programmatically.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5551]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/180403774).
<hr />

## Why
Who wants the functionality, why, and to what end? This is incorporated so that everyone on the team understands why the feature is being added. If you cannot think of a reason, then it’s worth reassessing if the feature should be included. The business case also allows others on the team to think if there is a better user experience than the one provided. Use the following template:

**As** a CI developer
**I want** I want to interact with SBT server progrmaatically
**So that** my build script can work faster and smarter, rather than just rely on spawning SBT process for each command.

## Acceptance Criteria
```gherkin
Scenario: 
GIVEN I am working on a CI script
WHEN I want to talk to SBT server
THEN there is an available library code that facilitates this.
```

## Resources
See the docs
https://www.scala-sbt.org/1.x/docs/sbt-server.html

## Blockers:
[#180399744](https://www.pivotaltracker.com/story/show/#180399744) blocked

**Comment by mwu-tow** [comment]
No longer relevant.
