### ISSUE TITLE
Rust code compiles more than once

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5552]
This task is automatically imported from the old Task Issue Board and it was originally created by Michał Urbańczyk.
Original issue is [here](https://www.pivotaltracker.com/story/show/183689179).
<hr />

No description provided.

## Comments:
Wojciech reported that he observes that Rust code compiles more than once even hen no change is made to the code while using the watch command.

Exact scenarios and resolution shall be discussed at a later date (after the release). (Michał Urbańczyk - Nov 1, 2022)
<hr />

**Comment by mwu-tow** [comment]
There is no watch for the Rust code anymore, so the issue is no longer relevant.
