### ISSUE TITLE
User editing code should be able to freely use letters from all languages.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5554]
This task is automatically imported from the old Task Issue Board and it was originally created by Adam Obuchowicz.
Original issue is [here](https://www.pivotaltracker.com/story/show/180392693).
<hr />

### Why

**As a user editing code/nodes** 
**I want to** see characters represented in UTF-8 as several code points in a single grapheme cluster as a single proper glyph, and the text cursor should move by 
**So that** I can comfortably write in all languages.

### Acceptance Criteria

```gherkin
Scenario: 
Given: node is edited, keyboard layout switched to "Hindi (Bolnagri)"
When: pressing sequence: KeyK, KeyE:
Then: the single के is displayed;
When: pressing ArrowLeft 
Then: cursor moved before के.
```

**Notes:**
* See description of https://www.pivotaltracker.com/n/projects/2540121/epics/4864521, where useful links are attached explaining all UTF-8 quirks (as well as explanation of the terminology)
* Currently, our text rendering engine is able to render only a single Unicode code points. It should be enhanced, so it will handle grapheme clusters. If it turns out to be too complicated, the simpler solution should be applied first: just display the first code point of grapheme cluster and discard the rest.
* Check if the rope structure can be extended, so it allows converting byte offsets to grapheme cluster offsets effectively (O(log n) is doable). Having such structure will help the implementation greatly.

## Comments:
Posting the unicode character into the IDE currently makes it crash - के (James Dunkerley - Feb 3, 2023)
<hr />

**Comment by farmaazon** [comment]
Closing, as in GUI2 we use the browser's input
