### ISSUE TITLE
Component Browser search does not like underscores

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#5562]
I was looking for the `to_text` method and once I typed `to_text` I did not get any results in the CB. This was confusing.

Apparently, I had to type `to text` (with _space_ instead of underscore), and only then did the documentation show up.

I think the CB should support both `_` and ` `. Moreover, if I typed the _exact_ method name - it should definitely be displayed instead of empty results.

**Comment by farmaazon** [comment]
duplicate of #5102
