### ISSUE TITLE
Process only Requested Modules when Resolving Imports

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#5568]
### Summary

The analysis of LS+engine startup (#5027) revealed a long time spend when resolving imports. `org.enso.compiler.Compiler.runImportsAndExportsResolution` takes **3s** - also because of slow `SerializationManager.deserialize` (tracked independently as #5567) - let’s speed this up by pre-computing all exports for each library - e.g. `Standard.Base`, `Standard.Visualization`, `Standard.Table`, etc. These exports are known at the manifest build time and will never change. 

![VisualVM](https://user-images.githubusercontent.com/26887752/217163881-4586ef91-2fae-44c2-b9c7-507f226c8dc2.png)

### Value

No need to load whole serialized IR to compute the exports. More effective structure, indexed by names and symbol hierarchy is needed. This step is needed to avoid loading all library IRs - with precise knowledge of the exported symbols, we’ll be able to load only the files that really export the imported symbol.

Proper implementation of this issue may render #5567 unnecessary/less needed.

### Specification

Change the `sbt` build process to generate a **map of exported symbols** and store it next to the library manifest. Read this **map of exported symbols** in the `runImportsAndExportsResolution` compiler pass.

Have a map of exported symbols for a library, so it is clear that `Standard.Base.Any.Any` is provided by `Any.enso` file and no other file needs to be processed. The amount of Enso files needed from a library shall then be restricted to minimum by such *export map* and not proportional to the size of the library.

### Acceptance Criteria & Test Cases

Measure the startup according to our [methodology](https://discord.com/channels/401396655599124480/1070399718649237514/1070708726757064714) and confirm an improvement. Write a (unit) test showing the resolution avoids parsing/deserializing files that aren't providing the requested symbols.

**Comment by jdunkerley** [comment]
Closed by #5700

**Comment by hubertp** [comment]
Will open follow up tickets, if necessary, if further improvements are necessary.
