### ISSUE TITLE
Port IDE support for `SKIP` and `FREEZE` to new AST

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#5572]
### General Summary

The logic for adding/removing/detecting `SKIP` and `FREEZE` applications in the gui needs to be rewritten for their new representations.

### Motivation

This is necessary for `SKIP` and `FREEZE` to work.

**Comment by jdunkerley** [comment]
SKIP and FREEZE are not expected in the beta release version, so removing from the backlog for now.

**Comment by kazcw** [comment]
I'm going to close this; when we plan a new implementation of SKIP/FREEZE, we will create the necessary issues.
