### ISSUE TITLE
[Windows] Ctrl+click on edited node doesn't move the cursor

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#5581]
### General Summary

The issue is spotted during the QA acceptance of task #4963. It is platform specific, it is not reproducible on Mac ~~It was not checked on Linux.~~ nor Linux.

### Steps to Reproduce

1. Start editing the node with `ctrl-click` (or `cmd-click`, depending on your OS)
2. While holding `ctrl`, click anywhere inside the node.

### Expected Result

The cursor is moved to the clicked location.

### Actual Result

No visible effect.

### Enso Version

Latest as for #4119

**Comment by 4e6** [comment]
Works as expected on Linux

**Comment by jdunkerley** [comment]
Tested on newest IDE build within Windows 11 and appears to be working fine so closing.

**Comment by farmaazon** [comment]
@galin-enso You have spotted it first time, could you confirm?

**Comment by galin-enso** [comment]
> @galin-enso You have spotted it first time, could you confirm?

I can still reproduce the issue on both my local and latest nightly builds. The only interaction I can get while holding down `ctrl` is a selection from the current cursor position to the mouse position when clicking and dragging. Tested on Windows 11.

https://user-images.githubusercontent.com/117099775/218419078-b12bee63-1fc8-4fe5-942e-62feda8ca85f.mp4

**Comment by jdunkerley** [comment]
Have reopened - as able to reproduce on my Windows box as well.
No idea why it worked last week!

**Comment by farmaazon** [comment]
Fixed in GUI2
