### ISSUE TITLE
Review expression generated column names

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#5583]
Currently, we remove all non alpha numeric characters and replace with `_`.

Need to check that DB escaping is safe and disable this behavior.

**Comment by jdunkerley** [comment]
Rules for SQL92 identifiers
Ordinary identifiers are identifiers not surrounded by double quotation marks. 
Delimited identifiers are identifiers surrounded by double quotation marks.

A delimited identifier can contain any characters within the double quotation marks. The enclosing double quotation marks are not part of the identifier; they serve only to mark its beginning and end. Spaces at the end of a delimited identifier are insignificant (truncated). Derby translates two consecutive double quotation marks within a delimited identifier as one double quotation mark-that is, the "translated" double quotation mark becomes a character in the delimited identifier.

Postgres:
Quoted identifiers can contain any character, except the character with code zero. (To include a double quote, write two double quotes.) 

SQLite:
"keyword"		A keyword in double-quotes is an identifier.

**Comment by jdunkerley** [comment]
We should reject names which are empty, Nothing or contain `\0`

**Comment by radeusgd** [comment]
TODO:
- [ ] Change `"Result"` new name in column operations to an expression of that operation (where possible, where not, an approximation)
- [ ] Add tests verifying that generated column names stemming from operation are consistent between in-memory and Database.
- [ ] Add tests for irregular column names in databases (Unicode, weird quotes etc.)
- [ ] Check behaviour of Unicode across DBs.
	- [ ] Decide how to handle it.

**Comment by radeusgd** [comment]
Summary of my findings of weird character support:

**Postgres** and **SQLite** are fine with all weird stuff that I threw at it. I added tests to our suite and they are passing. I will add a few more, but it seems that for our current backends we can safely use any characters as column names :)
<img width="930" alt="Zrzut ekranu 2023-03-06 150316" src="https://user-images.githubusercontent.com/1436948/223141952-cb1c960b-a8e7-46d8-94b4-82d50bae04e9.png">

Even slightly older versions of Postgres seem to do just fine:
<img width="806" alt="Zrzut ekranu 2023-03-06 150920" src="https://user-images.githubusercontent.com/1436948/223142091-bfa5155d-7d94-4763-8d6d-6d0eb57a5c63.png">

I also checked a few other backends that we may want to potentially support in the future.

1. **SQLServer** seems to be doing just fine:
<img width="750" alt="Zrzut ekranu 2023-03-06 150939" src="https://user-images.githubusercontent.com/1436948/223142405-a630cbf2-882d-4fb0-8149-90561ab34c38.png">

2. There are some problems with **MySQL** it does allow basic Unicode like characters with accents, but does not support emojis:

<img width="936" alt="Zrzut ekranu 2023-03-06 150835" src="https://user-images.githubusercontent.com/1436948/223146816-3b9b0509-4ba2-4c29-98c6-f620441c4ac3.png">
<img width="660" alt="Zrzut ekranu 2023-03-06 150845" src="https://user-images.githubusercontent.com/1436948/223146944-b3cdb133-91ab-47da-af44-5d1842e06550.png">

3. Apparently **Oracle ** database is weird as it allows Unicode and Emojis but does not allow quotes.

<img width="658" alt="Zrzut ekranu 2023-03-06 151059" src="https://user-images.githubusercontent.com/1436948/223147144-50ddeaa2-3f33-482c-ba42-a52fc267a268.png">
<img width="376" alt="Zrzut ekranu 2023-03-06 151032" src="https://user-images.githubusercontent.com/1436948/223147176-7ab5d2a7-d6c4-41a0-8f3f-da7241bb0b06.png">
<img width="663" alt="Zrzut ekranu 2023-03-06 150956" src="https://user-images.githubusercontent.com/1436948/223147197-14cf1e89-c620-4b02-82de-f551643f19ff.png">

**Comment by radeusgd** [comment]
So for now the rules will be:
1. empty or Nothing names will raise `Illegal_Argument`
2. names containing `\0` will raise `Illegal_Argument`
3. all other names will be accepted.

We may need to revise this once we start supporting more backends which do not support some of the weirder names.

**Comment by radeusgd** [comment]
Note:
Newer MySQL seems to accept emojis, but it replaces them with `?`:
<img width="533" alt="image" src="https://user-images.githubusercontent.com/1436948/223149059-17dd3be7-c885-417b-a899-9f12c5d3fefb.png">
<img width="361" alt="image" src="https://user-images.githubusercontent.com/1436948/223149134-424488dd-71a5-4800-aacc-3b13edabc3b3.png">
