### ISSUE TITLE
document dependency on rustfmt

### ISSUE THREAD

**Issue by milahu** [enso-org/enso#5589]
### How important is this feature to you?

0 – Not too important

### Describe the idea you'd like to see implemented.

https://github.com/enso-org/enso/blob/53d5487f475980566fbc1e54bb7a457aeee21b4b/docs/CONTRIBUTING.md?plain=1#L126

the program `rustfmt` must be in `$PATH`

### Would you be willing to help us implement this feature?

No

**Comment by 4e6** [comment]
Hi, can you please clarify when the `rustfmt` binary is required. Is it a build-time dependency?

**Comment by Frizi** [comment]
Our rust-toolchain file already specifies a dependency on both clippy and rustfmt.
```
channel = "nightly-2023-01-12"
components = ["clippy", "rustfmt"]
```

The documentation already states that you should use `rustup` to manage your rust toolchain, which will respect that file and install required components for you.

Is this by any chance not working as expected for you?

**Comment by milahu** [comment]
aah, im not using rustup
im using `rustPlatform.buildRustPackage` in nixpkgs, which does not parse rust-toolchain.toml

sorry, my bad, closing
