### ISSUE TITLE
Unsupported Engine version warning after opening a project

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#5594]
### Discord username

mwu#2888

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

After opening the project, the top banner complains about not supported engine version.

### Expected behaviour

No complaint.

GUI should compare not against a specific hardcoded version number, but against version range that is compatible with its own version.

### How we can reproduce it?

Open a new project.

### Screenshots or screencasts

![obraz](https://user-images.githubusercontent.com/1548407/217532472-ed2c6ccd-db9d-43b7-b8cb-fcb675605f97.png)

### Enso Version

what output?

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by Frizi** [comment]
Currently this check is performed using semver range check on IDE side, with the minimum version being configured with `engineVersionSupported` to specific nightly from 2022. It looks like the intention was to only check for lower bound, but the actual implementation also checks for upper bound limited by semver major, as it uses the `^` pattern. The year is being used as a major version, so it implies a semver breaking change once a year. 

The version range definition is here:
https://github.com/enso-org/enso/blob/a2a1aefc14363685bd72710239ad125c8769ebc5/app/gui/config/src/lib.rs#L30-L32

**Comment by farmaazon** [comment]
The easy fix should be just bumping the required version (I don't think we even now are compatible with the version printed as desired). For the long term, I think some process of keeping track of breaking changes should be developed.

**Comment by jdunkerley** [comment]
We should realign the IDE and new project versions so this does not show (currently I get a new project with a different version each time). Why has it become hard coded rather than read from the entry shown in `--version` for the IDE or backend?

It would be **very helpful** to have a dismiss button on this as we regularly are demoing from dev versions and needing to get rid of it.

Longer term, we should move to a semantic version number on this with the library and engine team determining when an incompatible change is made. Then ideally if the `Major.Minor` are the same don't complain as long as the third part is higher than the files.

**Comment by farmaazon** [comment]
> Why has it become hard coded rather than read from the entry shown in `--version` for the IDE or backend?

Not always newer version of IDE should make the old engine versions unsupported. If there is a backward compatibility in the LS API, then we should be mostly fine. The message could be then just "New version of the engine available".

> It would be **very helpful** to have a dismiss button on this as we regularly are demoing from dev versions and needing to get rid of it.

Part of #5201 

> Longer term, we should move to a semantic version number on this with the library and engine team determining when an incompatible change is made. Then ideally if the `Major.Minor` are the same don't complain as long as the third part is higher than the files.

:heavy_plus_sign:

**Comment by sylwiabr** [comment]
>Not always newer version of IDE should make the old engine versions unsupported. If there is a backward compatibility in the LS API, then we should be mostly fine. The message could be then just "New version of the engine available".

Still, if the version of the Engine is identical to the IDE version (as it is in the nightly/release package) the error should not appear.
