### ISSUE TITLE
Comparison operators should not require importing Standard.Base.Any module

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#5610]
After https://github.com/enso-org/enso/pull/4067 was merged, we now have to `import Standard.Base.Any.Any` for a simple operation like equality check or comparison with operators like <,>,<=,>=. The problem is that `Any.==` is no longer a builtin method, as it requires some more complex logic with comparators from `Ordering` module. Even the other comparison operators are not builtin methods.

One of the proposed solutions is to implement `Any.==` and co. as builtin methods. But in order to do that, we need to investigate where to put the current code of `Any.==`and how to resolve all the required module imports.

Related discussion on Discord: https://discord.com/channels/401396655599124480/1072936017235030027

Related comment on PR: https://github.com/enso-org/enso/pull/4067#pullrequestreview-1291161153

```[tasklist]
### Tasks
- [ ] Revert https://github.com/enso-org/enso/pull/4067/commits/2bf52564904d427f937af4f895641270d2d3e38d
```

**Comment by JaroslavTulach** [comment]
Is everything that' needed in here to rewrite the following code in 
- #6280 
```
== self that = Comparable.equals_builtin self that
```
to _not_ delegate to `Comparable`? In such case, let's handle this as part of #6280!
