### ISSUE TITLE
Collapsing nodes does not understand named parameters.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#5614]
Having the following nodes:
```
date = Date.new 2019 month=number1
operator3 = date.year
operator4 = date.month
```
select operator3 and operator4 and collapse them.

We expect a collapsed node with a single input parameter.

Instead, the collapsed node has an additional argument with wrong connection.

**Comment by Frizi** [comment]
Might be connected with https://github.com/enso-org/enso/issues/5083

**Comment by farmaazon** [comment]
The issue reported in this task is not reproducible: we get just two arguments for single connection, what was reported in #9159
