### ISSUE TITLE
Fullscreen visualization is partially covered by IDE buttons

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#5618]
## Steps to reproduce

1. Open desktop IDE
2. Create a node with a simple visualization, like a number input.
3. Open a fullscreen vis for this node.
4. Observe that part of the visualization is covered by window buttons.

<img width="663" alt="Screenshot 2023-02-10 at 14 47 17" src="https://user-images.githubusercontent.com/6566674/218091482-f9d096f4-a5ff-4f9e-a406-5308572d6ee2.png">

## Affected version

[Recent develop](https://github.com/enso-org/enso/commit/1f8511dab2d3cf6c49c959f71b180f9c4bd40995)

**Comment by farmaazon** [comment]
The visualization is under canvas, so those icons and messages shall be hidden, as Graph Editor is.

**Comment by farmaazon** [comment]
No longer an issue, as the macOS windows are decorated.
