### ISSUE TITLE
Error in logs when double clicking the background

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#5619]
## Steps to reproduce

1. Open any project in the IDE
2. Double-click the empty space
3. Observe the following error in the dev tools console

```
2. [ERROR] app/gui/src/presenter/graph/call_stack.rs:78 Exiting node failed: Tried to pop an entry point.
```

## Affected version

[Recent develop](https://github.com/enso-org/enso/commit/1f8511dab2d3cf6c49c959f71b180f9c4bd40995)

**Comment by 4e6** [comment]
What behavior is expected in this case?

**Comment by farmaazon** [comment]
First, this should not be an error, as it's a normal routine. Second, perhaps we should give some feedback to user that he's already in top stacktrace level, but I don't know what would be best.

**Comment by 4e6** [comment]
If the user also needs a feedback, I'll link #5201 here.

**Comment by farmaazon** [comment]
No longer an issue in GUI2
