### ISSUE TITLE
Visualization Disappears When Grouping Nodes

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#5622]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When you group a set of nodes the visualizations (and the graph below) are getting recalculated causing the already present visualization to blink,

### Expected behaviour

No need to recalculate viz should stay stable.

### How we can reproduce it?

- Bring in Book Club Sample
- Parse Date Column
- Show viz on set back into table
- Group 2 nodes parsing the date
- Viz will blink

### Screenshots or screencasts

https://user-images.githubusercontent.com/4699705/218096351-82a24a20-5ada-43aa-9811-a9eed553729d.mov

### Enso Version

Develop as of 10/2

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone and cloud

### Operating System

Other (provide the OS name in the next field, please)

### Operating System Version

Windows and Linux (dont have a mac...)

### Hardware you are using

Some slow EC2 machine and a AMD one

**Comment by sylwiabr** [comment]
@jdunkerley can you still reproduce it? It is working now for me on MacOS

**Comment by sylwiabr** [comment]
Can not reproduce it. Possibly fixed with other issues.
