### ISSUE TITLE
Pressing `enter` in text editor is opening component browser

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#5625]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I am trying to add a new line in Text editor (i.e. add a new line and an import) Component Browser is appearing after pressing `enter`

### Expected behaviour

Just a new line

### Enso Version

 2023.1.1-nightly.2023.2.9

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
No longer an issue in GUI2.
