### ISSUE TITLE
Add support for `Vector_Editor` widget to graph editor

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#5631]
```[tasklist]
* [ ] #5946
* [ ] #6037 
* [ ] #5947
* [ ] #6038 
* [ ] #5948
* [ ] #6039 
* [ ] #5949
* [ ] #5950
* [ ] #5923 
```

Support node widget that operates on lists of values. It needs to allow:
- adding new entry to the list (a + button)
- removing existing entries from the list (e.g. by dragging them out of the node)
- reordering existing entries in the list (e.g. by dragging them around)
- editing existing entries using specified item widget

The engine provided widget type will specify the default value to insert on add action (`idem_default`), and a widget to use for existing items (`item_editor`).
```py
Vector_Editor
  item_editor: Widget
  item_default: Text
  label: (Nothing | Text) = Nothing
  display: Display = Display.When_Modified
```

Reference design:
<img width="368" alt="image" src="https://user-images.githubusercontent.com/919491/218160117-6d5b2695-0aab-4997-88d0-d8312e1018ac.png">

The vector editor needs to be rendered as part of the node. This will likely require refactoring node input ports rendering to allow inserting interactive UI elements in between fragments of code text.

### Acceptance criteria:
A node with `Table.select_columns` method should receive a vector widget on `columns` parameter that allows editing a list of selected columns. All of adding, removing, reordering and modifying already present names should be supported.

**Comment by Frizi** [comment]
Depends on #5134

**Comment by wdanilo** [comment]
@Frizi you made my day with this design :D

**Comment by Frizi** [comment]
This is the one from https://www.figma.com/file/Gouv03sV4Oi2btc8qula1h/API-Design?node-id=0%3A1 which we used as a reference when discussing it for the first time with @jdunkerley. I guess this one is more adequate now:

![union node](https://user-images.githubusercontent.com/919491/220371433-a2825203-f704-4984-b6c4-2f72bcd27683.png)

Though a simpler example of e.g. a list of strings or numbers would be even more helpful.
