### ISSUE TITLE
Component browser documentation panel should not show PRIVATE entries

### ISSUE THREAD

**Issue by galin-enso** [enso-org/enso#5635]
## Why
**As** Enso User
**I want** to have the documentation of component browser entries with a `PRIVATE` tag hidden.
**So that** I can read through the relevant documentation more easily

## Acceptance Criteria

```gherkin
Scenario:
GIVEN I opened  a new project and I open the component browser
WHEN I view the documentation of a group that has PRIVATE entries 
THEN The documentation for the PRIVATE entries is not shown in the documentation panel
```

**Comment by farmaazon** [comment]
Already done https://github.com/enso-org/enso/pull/5582

**Comment by vitvakatu** [comment]
@farmaazon are you sure? I don't see anything related in the code or description.

**Comment by galin-enso** [comment]
This task was created as a follow-up to https://github.com/enso-org/enso/pull/4085#issuecomment-1425557399 . It's about hiding private methods in the _documentation panel_ of the component browser and is as far as I'm aware not yet done.

**Comment by farmaazon** [comment]
You are right, I confused this with just hiding private entries. Reopening.

**Comment by jdunkerley** [comment]
As documentation no longer shown at a type level this is fixed.
