### ISSUE TITLE
Investigate multiple `ApplyEdit` requests from IDE on startup

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#5637]
On a startup for a simple project (take the `0.up to 100` example project) IDE makes a total of 4(!) `ApplyEdit` requests.
The first request includes a text edit for the whole file.
Successive requests differ by `"visualization":{"name":{"content":{"content":"JSON"}},"project":"Builtin"}` vs `"visualization":null` for individual IDE node entries in the metadata section.

We need to investigate if such requests are actually necessary, especially on startup.

**Comment by farmaazon** [comment]
Fixed in GUI2: there we send only one update on new projects to set idmap and metadata.
