### ISSUE TITLE
Expression updates for static calls sometimes receive invalid `methodPointer.definedOnType` value

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#5644]
Test expression: `Table.new`

Received expression update:

```json
{
  "expressionId": "83fba596-73b7-4bbb-be0d-e36b083b75d8",
  "type": "Standard.Base.Function.Function",
  "methodPointer": {
    "module": "Standard.Table.Data.Table",
    "definedOnType": "Standard.Table.Data.Table.Table.type",
    "name": "new"
  },
  "profilingInfo": [
    {
      "ExecutionTime": {
        "nanoTime": 450200
      }
    }
  ],
  "fromCache": false,
  "payload": {
    "type": "Value",
    "warnings": null
  }
}
```

While in the suggestion database, the entry was added like that:
```
{
  "type": "Add",
  "id": 1273,
  "suggestion": {
    "type": "method",
    "module": "Standard.Table.Data.Table",
    "name": "new",
    "selfType": "Standard.Table.Data.Table.Table",
    "returnType": "Standard.Table.Data.Table.Table",
    "isStatic": true,
    ...
}
```

Notice the ` .type` suffix in expression method pointer's `definedOnType` field.

The `selfType` of suggestion entry doesn't match `definedOnType` in the expression method pointer, so it cannot be resolved correctly on IDE side.

**Comment by Frizi** [comment]
Actually the information whether or not `.type` is present does signal to the IDE how the `self` argument of a method is used. We could either keep this as expected behavior (and complicate the resolution on IDE side as a result), or modify the methodPointer to match correctly, but add an extra field that says if the call was made on a type. That would mean the IDE could properly locate `self` argument in both `Text.trim` and `text1.trim` expressions.

**Comment by Frizi** [comment]
I'm inclined to leave this as an expected behaviour and mark the issue as invalid. I've made use of trailing `.type` to decide where to place `self` argument.

<img width="334" alt="image" src="https://user-images.githubusercontent.com/919491/218492178-fcbf9597-88e1-4ceb-8378-34b57b5452ea.png">

**Comment by JaroslavTulach** [comment]
> Actually the information whether or not `.type` is present does signal to the IDE how the `self` argument of a method is used. 

Yes, that is correct. Instance methods (with `self`) are defined on the `Type` itself. **Static methods** are defined on _"eigentype"_ of the `Type` - e.g. `Type.type`. This is how Enso engine works.

> We could either keep this as expected behavior (and complicate the resolution on IDE side as a result), 

It is the expected behavior. But it can be changed, if there is a reason for that.

> I'm inclined to leave this as an expected behaviour and mark the issue as invalid. I've made use of trailing .type to decide where to place self argument.

Good. CCing @kustosz & @4e6, but closing as won't fix.
