### ISSUE TITLE
Dropdown display value shortening

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#5650]
Shorten the display names in dropdowns.

<img width="293" alt="image" src="https://user-images.githubusercontent.com/919491/218530502-4053fe83-f6ca-415d-90e7-335538721cb4.png">

The dropdown values should be shortened by parsing proposed expressions and mapping resulting Ast to a more user-friendly form.

### static dropdowns (entries provided via suggestion database's `tag_values`)
Shorten all access chains to the minimal unique set by stripping away leftmost parts of the chain. When a constructor with arguments is detected, add parentheses around it in the entry value, but not in the label.

Dynamic dropdowns covered in #5689

**Comment by sylwiabr** [comment]
@Frizi was this merged?
