### ISSUE TITLE
Table and error visualization seem to be randomly not working

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#5651]
### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When trying to preview nodes, sometimes the visualization shows up empty white box.

<img width="700" alt="image" src="https://user-images.githubusercontent.com/1436948/218532631-b53aa58a-8c72-4999-b317-25e8ecc12666.png">
<img width="746" alt="image" src="https://user-images.githubusercontent.com/1436948/218533853-1e0a82d8-7440-4f0a-a9ce-c7b097f38632.png">

It seems like warnings attached to the value may have a play in this, but it is inconsistent, so it is hard to say.

### Expected behaviour

The visualization should show up.

### How we can reproduce it?

Add nodes as shown on the screenshots.

### Screenshots or screencasts

<img width="700" alt="image" src="https://user-images.githubusercontent.com/1436948/218532631-b53aa58a-8c72-4999-b317-25e8ecc12666.png">
<img width="746" alt="image" src="https://user-images.githubusercontent.com/1436948/218533853-1e0a82d8-7440-4f0a-a9ce-c7b097f38632.png">

### Enso Version

https://github.com/enso-org/enso/pull/5605

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Windows 11

### Hardware you are using

Thinkpad X1 Carbon G10, i7-1280P, 32GB RAM

**Comment by jdunkerley** [comment]
Error issue was identified by @radeusgd as a bug in `to_display_text`.

Will investigate issue with warnings on the table and isolate issue,

**Comment by jdunkerley** [comment]
Payload sent from visualization does not have `data` so errors on parsing.
