### ISSUE TITLE
Adjust `Table.parse_values` and `Column.parse` to use the `Value_Type` type

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#5660]
Currently the type selection is based on the Enso type. 

This argument should be replaced with a Value_Type argument.

It should also cause validation of limits for integer type for example.

**Comment by radeusgd** [comment]
Shall we rename `Table.parse_values` to `Table.parse`? The design seems to use `parse` for the name, but the current implementation is `parse_values`. @jdunkerley any opinions on this?
