### ISSUE TITLE
Remove the old searcher from the codebase

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#5661]
### How important is this feature to you?

3 – Lack of it makes using Enso slightly harder

### Describe the idea you'd like to see implemented.

Since we have the new Component Browser fully functional, we should get rid of the old searcher. Remember to remove feature flag.

### Would you be willing to help us implement this feature?

No

**Comment by wdanilo** [comment]
Please remember that his should also remove the feature preview flag / new component browser from the app config :)

**Comment by farmaazon** [comment]
No old searcher nor feature flag in new GUI.
