### ISSUE TITLE
Improve error handling while opening projects

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#5663]
Currently, we always print the message `Failed to open project: unsupported engine version.`, even if the actual issue is different. `UnsupportedEngineVersion` struct ignores the `root_cause` field in `Display` implementation and is also used in places where it shouldn't.

The invalid error message makes the investigation of other issues much harder, and it should be prioritized.

**Comment by farmaazon** [comment]
Not relevant to GUI2.
