### ISSUE TITLE
Cannot snap input data to placeholders in a lambda function

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#5668]
I am unable to pin an input data into placeholders that are inside a lambda function (see the screencast). The edge is snapped instead of the whole lambda instead. A workaround is to move the lambda into a separate node.

[Screencast from 10.2.2023 21_13_16.webm](https://user-images.githubusercontent.com/14013887/219117387-a960d207-66d9-44d3-8ac2-665698b51227.webm)

**Comment by Akirathan** [comment]
Not sure whether this is a _feature_ or a _bug_ though.

**Comment by farmaazon** [comment]
Reassigned labels, because I think this is about generating span-tree (the span tree does not decompose most macros), and span tree is officially a controller part.

**Comment by wdanilo** [comment]
> Not sure whether this is a _feature_ or a _bug_ though.

A bug. Or a missing feature, we never implemented it, but it should be supported.

**Comment by farmaazon** [comment]
Fixed in the new GUI
