### ISSUE TITLE
Generate HTML docs from Rust documentation AST

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#5670]
Depends on: #5448

The frontend is currently spending about a quarter of its CPU time running the Scala documentation parser. The Rust parser can be 100x faster. Also, this is the last thing blocking us from eliminating the Scala parser entirely.

**Comment by wdanilo** [comment]
Out of curiosity - what is your approx estimate for it Kaz?

**Comment by vitvakatu** [comment]
Wait, we don't want to generate the actual HTML, do we? It would be ideal to generate *better* DocSections, but without much HTML code, as I described here: https://discord.com/channels/401396655599124480/1063461140794986636/1063461140794986636

<blockquote><img src="undefined//discord.com/assets/652f40427e1f5186ad54836074898279.png" width="48" align="right"><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/channels/401396655599124480/1063461140794986636/1063461140794986636">Discord - A New Way to Chat with Friends & Communities</a></strong></div><div>Discord is the easiest way to communicate over voice, video, and text.  Chat, hang out, and stay close with your friends and communities.</div></blockquote>

**Comment by kazcw** [comment]
We no longer need HTML docs in the frontend.
