### ISSUE TITLE
Warnings are discarded if a `Nothing` value crosses the polyglot boundary

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#5672]
Create a new Enso project and add a file `polyglot/java/foo/foo/Foo.java` with contents:
```java
package foo;

import java.util.function.Function;
import org.graalvm.polyglot.Value;

public class Foo {
    public static Value bar(Function<Integer, Value> f) {
        Value result = f.apply(42);
        System.out.println(result);
        System.out.println(result.getClass().getCanonicalName());
        return result;
    }
}
```
then run `javac Foo.java` in that directory.

Modify `src/Main.enso` to contain:
```
from Standard.Base import all

polyglot java import foo.Foo

main =
    f x =
        IO.println "f (x = "+x.to_text+")"
        Warning.attach "warn:f:1" x+10
    g x =
        IO.println "g (x = "+x.to_text+")"
        Warning.attach "warn:g:1" Nothing
    
    r1 = Foo.bar f
    IO.println "r1 = "+r1.to_text
    IO.println <| "r1 warnings = " + Warning.get_all r1 . map .value . to_text
    IO.println ""

    r2 = Foo.bar g
    IO.println "r2 = "+r2.to_text
    IO.println <| "r2 warnings = " + Warning.get_all r2 . map .value . to_text
    IO.println ""
```
and run the project (I use `enso run` in the launcher, but other means like the runner should work the same).

The results that I'm getting are:
```
f (x = 42)
52
org.graalvm.polyglot.Value
r1 = 52
r1 warnings = [warn:f:1]

g (x = 42)
Nothing
org.graalvm.polyglot.Value
r2 = Nothing
r2 warnings = []
```

Of course there is no reason for the second value to not contain the warning that is attached in the same way as in the first one. The expected result is that both returned values do contain a warning.

**Comment by radeusgd** [comment]
The error is most likely due to the fact that our library checks in some places for `isNull` and in such a case returns a singleton `Nothing` instance.

For example here:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/1436948/219344828-90b322b4-22f9-457e-b539-fa63ffdd5e5e.png">

But this is wrong - if the carried value is `WithWarnings`, it will also respond with `isNull() == true` because it proxies that query to the inner `Nothing` value. But if we then return the singleton `Nothing` value instead of the input object, we have stripped the result off of any warnings.

**Comment by JaroslavTulach** [comment]
> The error is most likely due to the fact that our library checks in some places for `isNull` and in such a case returns a singleton `Nothing` instance.

True. In general we don't want primitive values from other languages like `byte`, `int`, `float` to enter the Enso interpreter. We want to convert that _"on the boundary"_ of Enso.

However the situation is different with `TruffleObject` instances (just like `Nothing` or Java `null` or JavaScript `undefined`) - we can let them in:
- e.g. we could remove the whole `doNull` conversion and let the `WithWarnings(Nothing)` just continue thru

That however yields another question. Somehow we've been **assuming, there is just a single instance** of `Nothing` in the system. This example shows, that's not the case. There can be *many instances* of `Nothing` (wrapped with warnings). Every check of `x == EnsoContext.get(node).getBuitins().nothing()` is now suspicious - luckily I found only few such occurrences in `Type` and there it might be OK.

CCing @kustosz, @Akirathan, @hubertp

**Comment by Akirathan** [comment]
Having multiple instances of `Nothing` that potentially has warnings attached, or some kind of `None` from Python with other warnings attached sounds good. There will have to be some locations fixed, as @JaroslavTulach mentioned.

**Comment by radeusgd** [comment]
> That however yields another question. Somehow we've been **assuming, there is just a single instance** of `Nothing` in the system. This example shows, that's not the case. There can be _many instances_ of `Nothing` (wrapped with warnings). Every check of `x == EnsoContext.get(node).getBuitins().nothing()` is now suspicious - luckily I found only few such occurrences in `Type` and there it might be OK.

I have checked and it seems that we have two such places where we compare `== nothingSingleton` and they both seem safe. They both are in `Type.java` and essentially check the condition `this == nothingSingleton`. This seems safe, because `this` has type `Type` so it cannot be a `WithWarning` instance, and we do keep only one singleton `Type` instance of Enso `Nothing`. So it looks OK.

But we have to indeed be careful outside of `Type.java` to not use `==` but instead use the `InteropLibrary#isNull` check. Which I think we currently do correctly, so that's good. Let's keep it in mind for the future.
