### ISSUE TITLE
First start of the Mac application fails

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#5673]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

As for current develop (`f316ba01367dd7bf25b63f0bd4f774fb105e3d13`) I started to face IDE crash when running a locally built package. IDE starts, but the connection to the project manager is not established, and the application is unresponsive.

In the console there is a following message.

```
objc[11130]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x2246a32e0) and /Users/ilyabogdanov/projects/enso/dist/ide/mac-arm64/Enso.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Libraries/libGLESv2.dylib (0x106dd6978). One of the two will be used. Which one is undefined.
```

Restarting the IDE always helps, and the issue is not present after the first restart.

### Expected behaviour

IDE starts normally.

### Enso Version

f316ba01367dd7bf25b63f0bd4f774fb105e3d13

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

MacOS Ventura 13.0.1

**Comment by farmaazon** [comment]
Not reproducible in GUI2
