### ISSUE TITLE
`enso-types` is sometimes rebuilt superfluously

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#5686]
### Discussed in https://github.com/orgs/enso-org/discussions/5681

<div type='discussions-op-text'>

<sup>Originally posted by **farmaazon** February 17, 2023</sup>
Sometimes when I switch between building in console and "clipping" in the IDE, I see that `enso-types` crate is rebuilt many times.

And that is caused by `build.rs` script which regenerates file _in src directory_. When I switch to another configuration (or another target dir, as in IntelliJ configs), then that another configuration thinks that something has changed in our source code.

So the question is: why `enso-types` does not generate source code in $OUT dir (according to the recommendations)? The dim_macros module could just have proper include inside.

Calling @wdanilo - the author of the script

(BTW, we also put this generated file to git repository)</div>

**Comment by mwu-tow** [comment]
The crate is gone.
