### ISSUE TITLE
Improve diagnostics of EnsoGL

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#5697]
### Describe the idea you'd like to see implemented.

Currently, we have a diagnostic view, but it is not providing a lot of information. It should allow us to easily debug what shape systems are being rendered and why, what shaders or buffers are in use, etc. This is needed to understand if we are not leaking memory nor if we are not using too many resources by accident.

**Comment by sylwiabr** [comment]
@wdanilo is this done? there is no progress for past weeks and no PR linked

**Comment by wdanilo** [comment]
It seems I messed up with bot and I was not reporting it to a proper number. Sorry @sylwiabr :(

**Comment by sylwiabr** [comment]
can we close it @wdanilo ?

**Comment by wdanilo** [comment]
Yes, sorry for not doing it.
