### ISSUE TITLE
Duplicated entries in visualisations list

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#5708]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The regression that was previously fixed is back - we have `Table` visualization listed twice on visualizations list. Switching between them causes visualization blanc.

### Expected behaviour

Just one Table visualization available on the list

### Screenshots or screencasts

![image](https://user-images.githubusercontent.com/12892578/220137104-7f25005c-d961-46e7-9b0b-8e640d7de10f.png)

### Enso Version

2023.1.1-nightly.2023.2.18

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
Reproduced on develop (58c7ca54011bba1208de298d7b2e6877570d5b47). Also, it seems that it's not a conflict issue: I don't see two tables on the visualization list.

**Comment by sylwiabr** [comment]
@MichaelMauderer any progress here?

**Comment by farmaazon** [comment]
**QA**: @farmaazon
