### ISSUE TITLE
I cannot drag the scroll bar in the Component Browser documentation panel

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#5726]
### Discord username

farmaazon

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The mouse click events on the Component Browser documentation's scrollbar seem to be ignored.

### Expected behaviour

I should be able to scroll by mouse click on the scroll bar, as in every application.

### How we can reproduce it?

Open any project, open the component browser, and try to scroll documentation panel by mouse click.

### Enso Version

build on commit 58c7ca54011bba1208de298d7b2e6877570d5b47

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by jdunkerley** [comment]
Tested on current develop and appears to be working now.
