### ISSUE TITLE
Bell Icon (with "unread" state).

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#5727]
There should be a shape defined being a bell icon, which will be used to showing/hiding notification panel. The shape should have "read/unread" state (in the latter we should display a red dot, in similar place as the blue dot in screenshot below). 

The icon should be similar to the one from GH: 
![image](https://user-images.githubusercontent.com/3919101/220591234-e389864c-bfcd-47e8-9ebf-221eda340e09.png)

**Comment by jdunkerley** [comment]
Assume this is for notifications not documentation.

**Comment by farmaazon** [comment]
> Assume this is for notifications not documentation.

Indeed, fixed description

**Comment by farmaazon** [comment]
The tasks for https://github.com/enso-org/enso/issues/5201 should be redesigned for new GUI
