### ISSUE TITLE
[Dashboard] Create project and create project using templates

### ISSUE THREAD

**Issue by PabloBuchu** [enso-org/enso#5735]
https://www.figma.com/file/XOo3EIPbDaapKO9K3DbLFK/cloud3-31?node-id=0%3A1&t=RjJX2SUjPkZgXIVd-0

User should be able to create new blank project or create project using templates
Templates list and names can be found here https://github.com/enso-org/project-templates/

Hitting the create project button should send POST request to /projects API endpoint (createProject method). `projectName` is mandatory and template name can be send under `projectTemplateName` attribute. 

No reloads when adding new project to project list and table

**Comment by somebody1234** [comment]
merged in as #6071
