### ISSUE TITLE
Dynamic Dispatch - Phase 2

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#574]
### Summary
The current implementation of dynamic dispatch for the Enso interpreter is capable only of dispatching based on the `self` argument. This, however, is not the full set of dynamic dispatch semantics that we want for Enso, meaning that there is still work to do.

The remaining portions of the dynamic dispatch semantics involve dispatching based on the types of the remaining arguments passed to the function in addition to the self argument.

### Value
Implementing the second portion of dynamic dispatch ensures that the language semantics for Enso are nearly complete, removing one of the largest obstacles to cutting the 2.0 alpha release. 

### Specification

- [ ] Determine a design for implementing multiple-dispatch in the context of curried function application and function definition-site argument suspension (laziness). If resolution is ambiguous, the design should accommodate this by throwing an error.
- [ ] Establish how this design integrates with the existing work on the interpreter. 
- [ ] Implement the design into the existing interpreter while ensuring that it causes no performance regressions.
- [ ] Implement a comprehensive set of tests for the functionality in order to catch any semantic regressions caused by further work on the interpreter. 

### Acceptance Criteria & Test Cases

- The full set of dynamic dispatch semantics has been implemented.
- It is accompanied by comprehensive tests.
- It has acceptable performance, and has caused no regressions when it comes to performance of existing cases.

**Comment by CameronBieganek** [comment]
Hello! I'm a data scientist who programs in Julia, among other languages. I just want to voice my support for multiple dispatch in Enso. I've found multiple dispatch in Julia to be highly useful, and I miss it when programming in languages that don't support it.

Of course there can be some tension between multiple dispatch and currying. For reference, see the discussion on this un-merged PR that adds currying to Julia:

https://github.com/JuliaLang/julia/pull/24990
