### ISSUE TITLE
Cache Comparator for every Type

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#5740]
Every Type should have exactly one Comparator, that should not be changed. Comparator API was implemented in #4067.

This should improve the performance of `Any.==`, or any type of ordering.

Follow-up of #5712

**Comment by JaroslavTulach** [comment]
I believe the [cache has been implemented](https://github.com/enso-org/enso/pull/6280/files#diff-cde95eff5a2e7c62157b3a96c667bbc6201980c963c3dc00b9f47a371a131821R89) as part of #6280
