### ISSUE TITLE
Close and Fullscreen buttons are in the center of the scene

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#5743]
### Discord username

farmaazon

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I open a project in browser, the close and fullscreen icons are in the middle of the scene:

![Screenshot from 2023-02-22 15-20-26](https://user-images.githubusercontent.com/3919101/220671912-85ba6843-092d-42f1-b214-3896563198ab.png)

They move to their proper place after resizing scene.

### Expected behaviour

Those icons should be in their right place right away.

### Enso Version

build on commit 58c7ca54011bba1208de298d7b2e6877570d5b47

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

Google Chrome 110.0.5481.100

### Operating System

Linux

**Comment by farmaazon** [comment]
@sylwiabr Is it still required for the Design Partners?

**Comment by jdunkerley** [comment]
This is fixed.
