### ISSUE TITLE
Cant rename project

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#5746]
https://user-images.githubusercontent.com/108271897/220845031-8842aa21-80a3-4125-b801-3410586f5c57.mp4
[2302230829_Cant rename project.txt](https://github.com/enso-org/enso/files/10811187/2302230829_Cant.rename.project.txt)

**Comment by farmaazon** [comment]
Confirmed on Linux, deducing from the system mouse cursor something catches mouse events near top edge.

**Comment by farmaazon** [comment]
The main offender seems to be `-webkit-app-region: drag;` on `.titlebar`. It's strange, as the code was not touched for 2 years. Perhaps electron version update triggered this issue.

**Comment by farmaazon** [comment]
Confirmed that 663ed1e07efc081436989eab4e3b89e9e5fb80aa introduced the regression.
