### ISSUE TITLE
Text copy-paste inside of nodes is no longer working

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#5750]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Copying and pasting the text to nodes while editing is not working

### Expected behaviour

I can copy and paste code from one node to another

### Enso Version

663ed1e07efc081436989eab4e3b89e9e5fb80aa

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by sylwiabr** [comment]
I downloaded packages from GitHub actions to check which commit possibly broke the functionality

**Comment by jdunkerley** [comment]
Fixed by #5958
