### ISSUE TITLE
Flag `--version` is returning too much irrelevant informations

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#5751]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![image](https://user-images.githubusercontent.com/12892578/220898475-301fbfa2-f74f-4fa1-80f9-b79e32899211.png)

### Expected behaviour

Just version information

### Enso Version

663ed1e07efc081436989eab4e3b89e9e5fb80aa

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
The commit introducing it will be reverted.
