### ISSUE TITLE
Heisenbug in EqualsNode Specializations

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#5758]
When working on my PR I noticed a weird bug that hides from being debugged.

The bug is following:

In `parse_values` in `Table.enso`, I create a new Vector by mapping and introducing a dataflow dependency on a variable `selected_column_names` which may be a `Map` or may contain a specific dataflow error: `No_Input_Columns_Selected`.

In a situation where I expect the `No_Input_Columns_Selected` dataflow error to be propagated, instead I get some unexpected error:

```
    - [FAILED] should error if no input columns selected, unless error_on_missing_columns=False [282ms]
        Reason: An unexpected dataflow error ((Illegal_Argument.Error 'All columns must have the same row count.' Nothing)) has been matched (at C:\NBO\enso\test\Table_Tests\src\Formatting\Parse_Values_Spec.enso:380:13-32).
        at <enso> Error.throw(Internal)
        at <enso> Table.type.new<arg-1>(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Table\0.0.0-dev\src\Data\Table.enso:83:72-151)
...
```

What is weird is that I get this _only_ when running the whole `Table_Tests` project.

If I just run one file (`test\Table_Tests\src\Formatting\Parse_Values_Spec.enso`), the tests _do pass_.

Moreover, I tried debugging it (running whole project) with `--inspect` which crashed the Chrome Dev tools with nullpointer exception when trying to step through the problematic procedure.

When I tried running it on `--inspect`+JVM debugger together - the bug went undercover and again disappeared.

Then I tried good old print debugging
```diff
+            IO.println new_columns
+            IO.println (new_columns.map .length)
             result = Table.new new_columns
             parse_problem_builder.attach_problems_after on_problems result
```
at the end of the `parse_values`

Then, the tests succeed again. _The bug disappears if I try to take a look at it!_

I'm not sure what I'm encountering here, but this kind of nondeterministic behaviour seems concerning so I think it could be worth investigating what is going on, since it may possibly manifest itself in other situations.

I've put a snapshot of my code where the bug is reproducible on this branch: https://github.com/enso-org/enso/tree/wip/radeusgd/investigate-weird-dataflow-bug

**Comment by radeusgd** [comment]
@JaroslavTulach @hubertp Do you have some ideas how we could debug such a weird thing?

I'm not sure what is it's priority - it's not blocking anything as a workaround is rather simple (and I already shipped that in my PR to not stop myself). But the kind of nondeterminism that can be seen here is worrying.

Possibly also cc @Akirathan as this shows how to break devtools - if I put a breakpoint on `Parse_Values_Spec.enso:375` and then click `Step` a few times, I get a nullpointer exception. May be interesting.

**Comment by Akirathan** [comment]
@radeusgd I am afraid this is a bug in specializations of `EqualsNode`. Just the other day @hubertp spent a good portion of his day figuring some similar bug. Fortunately, I now have a pretty straightforward idea how to debug this. I will take a look at your branch and try to figure something out.

**Comment by jdunkerley** [comment]
@Akirathan - please do a triage on this if it is EqualsNode related, if no obvious cause we will put on the back burner.
It only seems to appear in very limited scenarios (I saw something similar in the Table tests last week).

**Comment by hubertp** [comment]
Yes, that looks similar to what I experienced.

**Comment by jdunkerley** [comment]
We have completely rewritten the `EqualsNode` so closing for now as not fixing.
