### ISSUE TITLE
`getMetaObject` for a primitive `Value` returns `null` unexpectedly

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#5759]
For a `org.graalvm.polyglot.Value value` that wraps some primitive, e.g., `Integer`, calling `value.getMetaObject()` returns `null` (`com.oracle.truffle.api.interop.DefaultIntegerExports.getMetaObject` is transitivelly called), even though it should return `org.enso.interpreter.node.expression.builtin.number.Integer` in our case.

The following patch makes `MetaObjectTest` fail:
```diff
diff --git a/engine/runtime/src/test/java/org/enso/interpreter/test/ValuesGenerator.java b/engine/runtime/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
index b8493361e..ce14b0092 100644
--- a/engine/runtime/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
+++ b/engine/runtime/src/test/java/org/enso/interpreter/test/ValuesGenerator.java
@@ -271,14 +271,6 @@ class ValuesGenerator {
     if (languages.contains(Language.ENSO)) {
       collect.add(v(null, "", "42").type());
       collect.add(v(null, "", "6.7").type());
-      collect.add(v(null, "", "40321 * 43202").type());
-      collect.add(v(null, """
-      fac s n = if n <= 1 then s else
-          @Tail_Call fac n*s n-1
-      """, "fac 1 100").type());
-      collect.add(v(null, "", "123 * 10^40").type());
-      collect.add(v(null, "", "123 * 10^40 + 0.0").type());
-      collect.add(v(null, "", "123 * 10^40 + 1.0").type());
     }
 
     if (languages.contains(Language.JAVA)) {
```
(i.e., we remove all `Big_Integer` from `ValuesGenerator`)

We should ensure that even for primitive values wrapped in `org.graavm.polyglot.Value`, `hasMetaObject()` return `true` and, therefore, `getMetaObject()` returns non-null value.

We should probably implement some kind of our own `Default*Export`, the same way as we do it, e.g., in https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/java/org/enso/interpreter/runtime/library/dispatch/DefaultLongExports.java

**Comment by JaroslavTulach** [comment]
>  ... returns null unexpectedly ...

I don't consider returning `null` for `getMetaObject()` an unexpected behavior (but I know well how it all works in Truffle). All interop types that aren't inheriting from `TruffleObject` will return `null`. That's `org.graalvm.polyglot` behavior.

The only way around it is to represent all Enso objects as subclasses of `TruffleObject`. However doing that all the time would be inefficient. We could convert `long` to `TruffleObject` on the interop boundary - but I am not convinced it gives us any benefits.

> We should probably implement some kind of our own Default*Export, the same way as we do it, e.g., in https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/java/org/enso/interpreter/runtime/library/dispatch/DefaultLongExports.java

Default export is fine for our own library, but defining default export for a standard Truffle library and standard Java value might lead to clashes. What would happen if JavaScript defined it as well?

I don't think we'll try to address this problem. Closing.

<blockquote><img src="https://opengraph.githubassets.com/b353d53039524cc7156f23b5a436ad632026bbea0d9f70cd0bbf07196dd29dcc/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">enso/DefaultLongExports.java at develop · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by JaroslavTulach** [comment]
One more note: it'd be an error if `TypesLibrary` returned no type for `6.7` or `42` - but that is working correctly as far as I know.

**Comment by Akirathan** [comment]
> One more note: it'd be an error if `TypesLibrary` returned no type for `6.7` or `42` - but that is working correctly as far as I know.

Yes, `TypesLibrary` is working correctly. I was only concerned about the behavior of `hasMetaObject`/`getMetaObject` methods on `InteropLibrary`.
