### ISSUE TITLE
Warning Icon

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#5761]
The icon will be next to the "show visualization" (eye) icon, and should have the same style (i.e. be black when on/hovered).

Should look like ⚠

**Comment by farmaazon** [comment]
Merging with [#9125](https://github.com/enso-org/enso/issues/9125)

**Comment by somebody1234** [comment]
@farmaazon is this issue obsolete?
- circular menu icons currently don't go black when hovered
- the new warnings icon is currently to the left of the menu, not the right

**Comment by farmaazon** [comment]
I assume we followed new design.
