### ISSUE TITLE
`if` behaves inconsistently with attached warnings/errors if an argument is passed by value

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#5762]
If I have `if x then y else z` vs `if x then y + 10 else z + 10`, I would expect the properties of dataflow error/warning propagation from `y` and `z` depending on value of `x` to be the same in both examples.

Currently they are _not_.

See the example:
```
from Standard.Base import all
import Standard.Base.Error.Illegal_State.Illegal_State

foo x y =
    if x then y else 42

bar x y =
    if x then y + 100 else 42

summarize str res =
    IO.println ""
    IO.println "-----------------------"
    case res.is_error of
        True ->
            IO.println str
            IO.println "is error: "+res.catch.to_text
        False ->
            IO.println str
            IO.println "is value: "+res.to_text
            IO.println "warnings: "+(Warning.get_all res . map .value).to_text

main =
    x1 = 33
    x2 = Warning.attach "WARN" 44
    x3 = Error.throw (Illegal_State.Error "ERR")

    summarize "foo False x1" <| foo False x1
    summarize "bar False x1" <| bar False x1
    
    summarize "foo False x2" <| foo False x2
    summarize "bar False x2" <| bar False x2

    summarize "foo False x3" <| foo False x3
    summarize "bar False x3" <| bar False x3
```

Indeed, given that I always set the first argument to `foo`/`bar` to `False`, I'd expect _all_ of these to return `42` without any warnings.

However the output on current versions is as follows:

```
-----------------------
foo False x1
is value: 42
warnings: []

-----------------------
bar False x1
is value: 42
warnings: []

-----------------------
foo False x2
is value: 42
warnings: [WARN]

-----------------------
bar False x2
is value: 42
warnings: []

-----------------------
foo False x3
is error: (Illegal_State.Error 'ERR' Nothing)

-----------------------
bar False x3
is value: 42
warnings: []
```

So we can see that in the case where a value containing errors/warnings is passed to the if branch directly 'by name', these errors/warnings are inherited, _even if that branch is **not** taken_. However, obviously the not taken branches are not computed, so if there is _any_ computation - these are _not_ inherited anymore.

I think these should be consistent.

**Comment by Akirathan** [comment]
The issue seems to be in how we generate `IfThenElseMethodGen`. `IfThenElseNode.execute` specifies both arguments with `@Suspended` annotation, which impacts how a `Function` object is created for the builtin method (with `ExecutionMode.PASS_THUNK`), but still all the warnings of these arguments are gathered, and appended to the result.

In other words, the following line should be rewritten in `IfThenElseMethodGen` (more specifically, in `BuiltinMethodProcessor`):
![image](https://user-images.githubusercontent.com/14013887/229744257-dc4d7181-5698-48c7-8c7f-55c5bb91f57b.png)

**Comment by Akirathan** [comment]
#6070 is related
