### ISSUE TITLE
Access a type's method list through the `Meta` library

### ISSUE THREAD

**Issue by kustosz** [enso-org/enso#5765]
### How important is this feature to you?

3 – Lack of it makes using Enso slightly harder

### Describe the idea you'd like to see implemented.

It should be possible to get a list of available methods for a given type. The result should also include information on whether the method is static or not, its argument names and types, and certain additional metadata, including annotations and documentation.

### Is your feature request related to a problem?

It will allow us to better generate AI prompts from Stdlib

### Would you be willing to help us implement this feature?

No

**Comment by JaroslavTulach** [comment]
@kustosz, there is a bunch of issues newlly reported like #5767, #5766, etc. Is there some document that describes the whole vision or do we have just these individual, hard to grasp issues?

**Comment by wdanilo** [comment]
> @kustosz, there is a bunch of issues newlly reported like #5767, #5766, etc. Is there some document that describes the whole vision or do we have just these individual, hard to grasp issues?

These issues are needed for @kustosz to finish the AI integration in Enso. As soon as we finish these issues, Marcin will be able to properly integrate it with the product.

**Comment by sylwiabr** [comment]
@kustosz please provide a design doc so there will be a high level explanation of the idea and the connection with created issues.
