### ISSUE TITLE
Implement an API for Parser Textual-Diff Communication

### ISSUE THREAD

**Issue by Josef-Vonasek** [enso-org/enso#577]
### Summary

The Enso parser can take any handle or string as an input. This is sufficient for one-run tasks, but not very efficient for interactive editing of the source code, where parser needs to be run after each modification.
The Text API will be a communication channel between text editors and our language interpreter / parser, providing simple and efficient way to trigger small modification of our AST.

### Value

Since Enso studio also operates over textual representation, good text API is a requirement.

### Specification

1. Define the API
2. Implement it

### Acceptance Criteria & Test Cases

Working API for text manipulation.

**Comment by iamrecursion** [comment]
Obsolete.
