### ISSUE TITLE
Add support for partial ordering to Comparators

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#5771]
After recent discussion with @JaroslavTulach and @radeusgd (the conclusion is here https://github.com/enso-org/enso/issues/5742#issuecomment-1444995335) we have decided that we will roll back the behavior of comparators to allow specification of _partial ordering_.  The new API shall look like so:
```
type Ordered_Comparator
  is_ordered = True
  compare : Any -> Any -> (Ordering|Nothing)
  hash -> Any -> Integer

type Unordered_Comparator
  is_ordered = False
  equals : Any -> Any -> (Boolean|Nothing)
  hash : Any -> Integer
```
for `compare x y`, the return value of `Nothing` specifies that `x` and `y` are incomparable. (for example, this will be the case when `x` or `y` is `NaN`).

```[tasklist]
### Tasks
- [x] Reject #5744.
- [x] Make sure that there are no regressions in related benchmarks.
- [ ] Consider using just `compare` method without dedicated `equals` method
```

**Comment by JaroslavTulach** [comment]
Why don't we have just a single:
```
type Comparator
  compare : Any -> Any -> (Ordering|Nothing)
  hash -> Any -> (Integer|Nothing)
```
Such an API is simpler and achieves the same. Everyone who would want to support just `equals` can implement `compare: Any -> Any -> (Ordering.Equal | Nothing)` at the same cost and speed.

**Comment by Akirathan** [comment]
Now that we support partial ordering, and we can have situations like:
```
type My_Comparator
  equals x y = x.data == y.data
  hash x = Nothing
```
i.e. `hash` just returns `Nothing`, or `equals` can return `Nothing` for almost all instances except for few ones, etc. I am thinking it is, indeed, not necessary anymore to differentiate between an _ordered_ comparators and _unordered_ ones. 

These all changes of course mean that we will have to deal with more weird comparator behavior at runtime, but since we all agreed that our users are as [clueless](http://wiki.apidesign.org/wiki/Cluelessness) as possible, then I think these changes are just fine.

The author of the proposal to differentiate between _ordered_ and _unordered_ comparators is @radeusgd, so if he does not have any strong opinions against merging _ordered_ and _unordered_ comparators into single comparators, then let's do it.

**Comment by JaroslavTulach** [comment]
Have I made an oversight in the [previous comment](https://github.com/enso-org/enso/issues/5771#issuecomment-1447566286)? I am surprised `hash` could return `Nothing` - why? I believe the requested behavior should be:
```
type Comparator
  compare : Any -> Any -> (Ordering|Nothing)
  hash -> Any -> Integer
```
Don't we want all Enso objects to participate in (hash) `Map`? If so, we want them to have `hash` computed. They cannot say no. Of course they can return `hash _ = 0` or any other constant - which has similar meaning.... so my comment is more about _expectations_... but still: returning `Nothing` shall not be encouraged.

**Comment by Akirathan** [comment]
You are right. We can, and probably _should_, enforce users to specify `hash` for all the values, even the incomparable ones. That should not break the _hash contract_. So far, I have just updated the docs, and method signatures, so let me revert it such that `hash` method cannot return `Nothing`.

By the way, let's deal with the merging of _unordered_  and _ordered_ comparators into a single one in a separate issue.

**Comment by radeusgd** [comment]
> The author of the proposal to differentiate between _ordered_ and _unordered_ comparators is @radeusgd, so if he does not have any strong opinions against merging _ordered_ and _unordered_ comparators into single comparators, then let's do it.

I think with the new approach merging these two seems fine.

My only concern is that is may be relatively common for users to want to define such unordered types and having to define a `compare` method which returns `Equals` or `Nothing` _instead_ of being able to define an `equals` method which simply returns `True` or `False` feels like adding a bit of unnecessary confusion.

BUT I don't think this is an issue, because we should be able to, at the library level, provide a helper `make_comparator_for_unordered_type` (name ofc to be revised) which could take an object with `equals : a -> a -> Boolean` and `hash` methods and _'convert'_ it into this `comparator` based form.

So I think at implementation level it is all good, and at the user-facing API level we may want to revise it later on, probably ideally once we use custom comparators a bit more and see what patterns will work best.
