### ISSUE TITLE
NullPointerException in CLI execution

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#5780]
### Discord username

mito

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

On branch https://github.com/enso-org/enso/tree/wip/gmt/npe

I'm getting:

$ built-distribution/enso-engine-0.0.0-dev-macos-amd64/enso-0.0.0-dev/bin/enso --run regs.enso
Execution finished with an error: java.lang.NullPointerException

I'm pretty sure the problem is the commented-out code on line 37, leaving an empty block after a case ->.

### Expected behaviour

Expect an Enso syntax error.

### How we can reproduce it?

Reproduce:
$ built-distribution/enso-engine-0.0.0-dev-macos-amd64/enso-0.0.0-dev/bin/enso --run regs.enso

Version:
$ built-distribution/enso-engine-0.0.0-dev-macos-amd64/enso-0.0.0-dev/bin/enso --version
Enso Compiler and Runtime
Version:    0.0.0-dev
Built with: scala-2.13.8 for GraalVM 22.3.1
Built from: wip/gmt/compile-regexp* @ 49633f7c558dbb0706104f94489d034717a83ee0
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.18+10-jvmci-22.3-b13
            Mac OS X 12.6.3 (x86_64)

### Enso Version

0.0.0-dev (not sure how to get the real version)

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone (not sure)

### Operating System

MacOS

### Operating System Version

12.5.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by 4e6** [comment]
Posting the contents of `regs.enso` for context
```py
from Standard.Base import all

import Standard.Base.Data.Text.Regex_2
import Standard.Base.Data.Text.Regex.Pattern_2.Pattern_2

#main = Test_Suite.run_main spec
main =
  p = Regex_2.compile_2 "ab"
  IO.println p
  case p of Pattern_2.Value internal -> IO.println internal
  mt = p.matches "ab"
  IO.println mt

  p.match_all "heyabyeahab yo abc no cab ab abab ye "

  ##

          #m = p.match "cabbie" Matching_Mode.First
          #IO.println m.groups
          #IO.println (m.span 0)
          #m
          "hi"
```

**Comment by 4e6** [comment]
Can't reproduce on the current develop 941512e0ba1aea7a46db904a7d87860b8b42b35f

```
$ ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run ./regs.enso
In module regs:
Compiler encountered errors:
regs.enso[3:1-3:38]: The module Standard.Base.Data.Text.Regex_2 does not exist.
regs.enso[4:1-4:56]: The module Standard.Base.Data.Text.Regex.Pattern_2.Pattern_2 does not exist.
regs.enso[8:7-8:13]: The name `Regex_2` could not be found.
regs.enso: The name `Pattern_2.Value` could not be found.
Aborting due to 4 errors and 0 warnings.
Execution finished with an error: Compilation aborted due to errors.
```

@GregoryTravis can you check if it works for you on the `develop` branch?

**Comment by GregoryTravis** [comment]
I also cannot reproduce this on the current develop.
