### ISSUE TITLE
Uncaught expression when opening entry point

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#5786]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Clicking on the link on the page with entry points leads to an error popup.

The chosen entry point is opened afterward without issues.

### Expected behaviour

No error visible

### How we can reproduce it?

1. Open entry points list: `Enso -startup.entry=_`
2. Click on any link in the list

### Screenshots or screencasts

<img width="1378" alt="Screenshot 2023-03-01 at 16 19 44" src="https://user-images.githubusercontent.com/6566674/222139116-5ba622e2-f688-4866-af92-5f2ec4405ca2.png">

### Enso Version

0abeb354e29a8490242690ee0b344dae3616edb8

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

MacOS Ventura 13.0.1

### Hardware you are using

M1 Mac

**Comment by somebody1234** [comment]
Closing as it should have been fixed by #6507.
