### ISSUE TITLE
Parameter formatting is broken with TruffleLoggers

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#5801]
Logs coming out of TruffleLogger don't use the provided arguments leading to incomplete messages:
```
[debug] [...] [epb.org.enso.interpreter.epb.EpbContext] Initializing languages {0}
[trace] [...] [epb.org.enso.interpreter.epb.EpbContext] Starting initialization thread
[trace] [...] [epb.org.enso.interpreter.epb.EpbContext] Entering initialization thread
[trace] [...] [epb.org.enso.interpreter.epb.EpbContext] Initializing language {0}
[trace] [...] [epb.org.enso.interpreter.epb.EpbContext] Initializing on background
[debug] [...] [enso] Executing commands in a separate command pool
[debug] [...] [epb.org.enso.interpreter.epb.EpbContext] Done initializing language {0} with {1} in {2} ms
```
Notice the `{0}` for parameter position which should have been replaced with the correct argument.

As per logs in https://github.com/enso-org/enso/blob/develop/engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java#L66 or https://github.com/enso-org/enso/blob/develop/engine/runtime-language-epb/src/main/java/org/enso/interpreter/epb/EpbContext.java#L80.

Those logs were introduced in https://github.com/enso-org/enso/pull/5680 but I can see plenty of places where we could use parameter formatting except we can't so logs are full of String concatenation (also affecting performance).

**Comment by JaroslavTulach** [comment]
There is a [Builder.logHandler(...)](https://www.graalvm.org/truffle/javadoc/org/graalvm/polyglot/Engine.Builder.html#logHandler-java.util.logging.Handler-) method. If we use it, we [get `LogRecord`](https://docs.oracle.com/en/java/javase/17/docs/api/java.logging/java/util/logging/Handler.html#publish(java.util.logging.LogRecord)) and we can format it using [SimpleFomatter](https://docs.oracle.com/en/java/javase/17/docs/api/java.logging/java/util/logging/SimpleFormatter.html) or our own formatter.

The implementation must be somewhere in [PolyglotLoggers](https://github.com/oracle/graal/blob/c1cffd4b4605aa7667c1161b9bd28bbd14aa4fba/truffle/src/com.oracle.truffle.polyglot/src/com/oracle/truffle/polyglot/PolyglotLoggers.java#L277).

**Comment by JaroslavTulach** [comment]
Running `./project-manager -vv --no-log-masking 2>&1 |grep "\{0"` shows messages like:
```
[debug] [2023-03-09T09:22:58.525Z] [epb.org.enso.interpreter.epb.EpbContext] Initializing languages {0}
[trace] [2023-03-09T09:22:58.53Z] [epb.org.enso.interpreter.epb.EpbContext] Initializing language {0}
[debug] [2023-03-09T09:22:59.139Z] [epb.org.enso.interpreter.epb.EpbContext] Done initializing language {0} with {1} in {2} ms
[debug] [2023-03-09T09:51:17.29Z] [epb.org.enso.interpreter.epb.EpbContext] Initializing languages {0}
[trace] [2023-03-09T09:51:17.297Z] [epb.org.enso.interpreter.epb.EpbContext] Initializing language {0}
[debug] [2023-03-09T09:51:17.913Z] [epb.org.enso.interpreter.epb.EpbContext] Done initializing language {0} with {1} in {2} ms
```
they deserve to be properly formatted.
