### ISSUE TITLE
Icons in component browser when screen scaling is not an integer.

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#5807]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![image](https://user-images.githubusercontent.com/12892578/222756183-b424d23c-a64b-41ad-a2ad-3d024fb576ef.png)

### Expected behaviour

<img width="75" alt="Zrzut ekranu 2023-03-3 o 16 12 37" src="https://user-images.githubusercontent.com/12892578/222756266-0fa49f28-fc90-4e24-bd49-a46c185fb2f0.png">

### Enso Version

Nightly 3.03.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by farmaazon** [comment]
I didn't reproduce it on Windows. Perhaps some hardware also plays a role in this issue.

**Comment by farmaazon** [comment]
The cached_shape debug scene shows, that the texture is rendered more-or-less correctly. It's reading from it what is broken.

![image](https://user-images.githubusercontent.com/3919101/222773321-16c650d3-bca3-4446-8a62-798f984ddc45.png)

![image](https://user-images.githubusercontent.com/3919101/222773212-38cef460-3f33-4990-9925-d3c0e3e5debb.png)

**Comment by farmaazon** [comment]
Reproduced and found the cause: the cache rendering behave wrong if pixel ratio is not an integer.

Workaround: change the screen scaling on your system to 1 or 2.
