### ISSUE TITLE
Initial position of visualization covers new node

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#5814]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When creating a new node, the node's visualization initially covers it:

![image](https://user-images.githubusercontent.com/1047859/222920586-a5743433-742b-4c69-be84-6decf5fe3dc8.png)

Once I start typing, the visualization moves and I can see the node.

### Expected behaviour

The visualization should start out below the node, in the position it currently moves to when I start typing.

### Enso Version

f64edd806d4de7e71e6b1fea41a13ac189ebfadd

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by farmaazon** [comment]
Duplicate of #5183

**Comment by kazcw** [comment]
Closing as duplicate.
