### ISSUE TITLE
Table viz displays `Day_Of_Week` values as `[object Object]`

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#5815]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![image](https://user-images.githubusercontent.com/1047859/222923214-dfbf5651-91c8-4040-9f75-8666de0e2f55.png)

### Expected behaviour

It should stringify to the constructor name, like `Monday`.

### Enso Version

develop / current engine

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by vitvakatu** [comment]
@jdunkerley seems like a duplicate of #5480

**Comment by jdunkerley** [comment]
> @jdunkerley seems like a duplicate of #5480

True - a quick fix needed but yes is same issue.

**Comment by jdunkerley** [comment]
Closing as a duplicate.
