### ISSUE TITLE
Viz incorrectly renders text, issue with scrolling

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#5822]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

No, I can use Enso despite of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Lines seems rendered with bold font - it changes to the normal font when scrolled to the far right and back
(also Scroll wheels do not work)

please see video in the comment

### Expected behavior

text rendered in normal face font

### Enso Version

Build: Nightly Release #842

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11 pro

### Hardware you are using

xps laptop. 12gen intel + discrete gpu

**Comment by xvcgreg** [comment]
https://user-images.githubusercontent.com/108271897/223106417-afb5e1bb-b244-4286-9378-0b861b3cbfe6.mp4

**Comment by farmaazon** [comment]
Issues with scrolling are being fixed in #6196

**Comment by jdunkerley** [comment]
Closing as fixed other than focus issue (scroll wheel doesnt work on them).
