### ISSUE TITLE
Negative numbers are not supported by the parser

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#5826]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [x] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

During the demo we spotted that input `-2` is considered a unary application of the `-` operator, not the negative number, as it should be.

`-2` produces:
```
Ast: Ast { wrapped: WithID { wrapped: WithLength { wrapped: Module(Module { lines: [BlockLine { elem: Some(Ast { wrapped: WithID { wrapped: WithLength { wrapped: SectionRight(SectionRight { opr: Ast { wrapped: WithID { wrapped: WithLength { wrapped: Opr(Opr { name: "-", right_assoc: false }), length: 1 }, id: Some(4169b315-60db-42f9-9a35-1078b3b0776d) } }, off: 0, arg: Ast { wrapped: WithID { wrapped: WithLength { wrapped: Number(Number { base: None, int: "2" }), length: 1 }, id: Some(6e2f3c62-b71f-4f7b-baf0-0af31214237e) } } }), length: 2 }, id: Some(854895b7-8836-4268-91eb-40e701b04b8b) } }), off: 0 }] }), length: 2 }, id: None } }
```

`- 2` produces similar AST:
```
Ast: Ast { wrapped: WithID { wrapped: WithLength { wrapped: Module(Module { lines: [BlockLine { elem: Some(Ast { wrapped: WithID { wrapped: WithLength { wrapped: SectionRight(SectionRight { opr: Ast { wrapped: WithID { wrapped: WithLength { wrapped: Opr(Opr { name: "-", right_assoc: false }), length: 1 }, id: Some(a2144ab8-d4f7-46ba-8c46-a42753800527) } }, off: 1, arg: Ast { wrapped: WithID { wrapped: WithLength { wrapped: Number(Number { base: None, int: "2" }), length: 1 }, id: Some(547c287d-f1cf-436d-9daa-ea8af4f6c664) } } }), length: 3 }, id: Some(e1fe25f3-5887-47e7-a9f2-091456c5cc68) } }), off: 0 }] }), length: 3 }, id: None } }
```

### Expected behaviour

`-2` is a negative number, not a function.

### How we can reproduce it?

```rust
#[test]
fn negative_number() {
    let parser = Parser::new();
    let input = "-2";
    let ast = parser.parse(input, default());
    eprintln!("Ast: {ast:?}");
    panic!()
}
```

### Enso Version

current develop (2d29456)

### Browser or standalone distribution

Other (provide the browser name in the next field, please)

### Browser Version or standalone distribution

none

### Operating System

MacOS

**Comment by kazcw** [comment]
Oh, I see what's happening. The parser itself is per spec (and covered by tests), this is a bug in lowering to the frontend `Ast` representation. I'll fix it today.
