### ISSUE TITLE
Failure to load a precompiled-shader / dynamic asset should not be fatal

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#5829]
In the absence of any bug, all dynamic assets will load successfully. However, dynamic-assets are an optimization; if any fails to load, we *should* continue application startup, and log an error about lost performance.

Currently we are using `Promise.all` in `lib/rust/ensogl/pack/js/src/runner/index.ts`. We can use `promise.allSettled` to handle any failures. (Any work on this should wait until #5811 merges, as it refactors this code.)

**Comment by wdanilo** [comment]
Good point. Yup, let's use `allSettled` instead.

**Comment by farmaazon** [comment]
Not relevant to GUI2
