### ISSUE TITLE
NaN cannot be used as a key in Map

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#5833]
The primary motivation for`Map` existance is implementation of `Vector.distinct`. To make such implementation easy/fast/possible we **don't want errors** from `Map.insert`. On contrary, we want **every object** to provide **hash code** - so it can be used as a key for the `Map`. Constraints:

1. it is desirable for Map to always satisfy: `m.insert k v . contains_key k == True`
2. For `Number` we are going to use JavaScript's [Equality comparisons and sameness](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#same-value-zero_equality) to ensure `NaN` works as a key
3. Custom types - shall have a **forced reflexivity** - e.g. `Meta.is_same_object` implies that they are `Any.==` which in turn satisfies the first point

Following code shows the expected behavior for custom types that violate reflexivity:
```haskell
type My_Nan
    Value comment:Text

...comparator such that it always returns Nothing

k = My_Nan.Value "foo"
k2 = My_Nan.Value "foo"
(k==k).should_be_true
(k==k2).should_be_false
m = Map.empty.insert k 10
m.contains_key k . should_be_true
m.get k . should_equal 10
m.contains_key k2 . should_be_false

m2 = m.insert k2 20
m2.get k . should_equal 10
m2.get k2 . should_equal 20
m2.size . should_equal 2

m3 = m2.insert k 30
m3.size . should_equal 2
m3.get k . should_equal 30
```

e.g. , we will do a best effort solution. Thanks to `Any.==` relying on `Meta.is_same_object`, even if `compare` implementation is **always incomparable**, `x==x` will be `True`. Multiple separate instances of incomparable atoms will however not be. 

Follow up of 
- #5771 
- #5818

```[tasklist]
### Tasks
- [ ] Make sure `NaN` can be a key in `Map` using the JavaScript's [Equality comparisons and sameness](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Equality_comparisons_and_sameness#same-value-zero_equality)
- [x] Make sure `x == x` via `Meta.is_same_object` (tracked in #6065)
- [ ] Update tests
- [ ] Update documentation
```

**Comment by radeusgd** [comment]
Probably also worth adding a test for `Vector.distinct`:

```
[Number.nan, 1, Number.nan, 2, 1].distinct.to_text . should_equal "[NaN, 1, 2]"
```
(using `to_text` as regular equality may actually yield `False` due to the NaNs...)

**Comment by radeusgd** [comment]
Let's be sure to test the custom types properly, i.e. have tests for a custom type like `My_Nan` above.

As @Akirathan mentioned, this may be blocked by #5709
