### ISSUE TITLE
`./run ide watch --ide-option --debug.dev-tools` Returns repeatedly "Unexpected arguments found" error.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#5838]
Running the command from the title starts compilation (as expected), then run electron process (as expected) but the process returns immediately with error:
```
 INFO ide_ci::program::command: npmℹ️ Waiting for Electron process to finish.
 INFO ide_ci::program::command: npmℹ️ Unexpected arguments found: '--debug.dev-tools'.
```
And the help message is printed. Then the process is restarted infinitely with the same results. 

Full log from one of my runs:
[log.txt](https://github.com/enso-org/enso/files/10908907/log.txt)

As the new electron version does not allow opening dev console by shortcut (`ctrl+alt+shift+I`) I cannot use dev console in watch command, making this issue quite pressing.

**Comment by vitvakatu** [comment]
The flag is called `-debug.dev-tools` (with a single dash). Does it work this way?

**Comment by farmaazon** [comment]
No, it is not.

**Comment by wdanilo** [comment]
@vitvakatu we accept both `--` and `-`. It's written in help. Just FYI.

**Comment by wdanilo** [comment]
Also, this error is reported by `npm`, so it looks like build script issue. CC @mwu-tow
