### ISSUE TITLE
The Number Type

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#584]
### Summary
Currently, Enso's concept of numbers is morbidly simple: `long`. This is far from an ideal state of affairs, and should be improved. However, the combination of usability and performance that we want to strike in Enso means that a little bit of design work is necessary. 

In an ideal world, non-power-users shouldn't have to even think about the _kind_ of number that they are using. All they want is that the number type _works_. While power users should be able to specify specific numeric types like `Int64`, `Float64`, `BigInteger`, and so on, Enso should have a default `Number` type that behaves sensibly in all situations.

### Specification

- [x] Take a look at how SimpleLanguage does numbers.
- [x] Design a state machine that transitions between number types (`long`, `double`, `BigInteger`, and `BigDecimal`) internally with a focus on using the most _performant_ type for the value contained. This should:
  - Represent all integer numbers as `long` until the point of overflow. At the point of overflow, it should be converted to a `BigInteger`. Make sure to use `Math.addExact(...)` and co.
  - At the point of transition, the number object should perform a specialization rewrite.
  - Any division operator (or fractional number) should be represented as a `double`.
  - All integer literals should be represented as the smallest type that they fit into.
  - All non-integer literals should be represented as `BigDecimals`, and be transitioned to the appropriate type when an operation is performed.
  - The transitions are effectively `long -> double`, `long -> BigInteger`, `BigDecimal -> double`, but depending on the operands to the various operations, these transitions will occur in different places.
- [x] Implement this as `Number`, and integrate it with the interpreter.
- [x] It must support `+`, `-`, `/`, `%`, `*`, `<`, `<=`, `>`, `>=`, `!=`, `==`, `^` as operators. It is very important that, when in comparing non-integer numbers, the comparison is done with relation to some [epsilon](https://doc.rust-lang.org/src/core/num/f64.rs.html#337).
- [x] Additionally, implement basic mathematical functions (trig, hyperbolic trig, log, exp, etc).
- [x] Implement interop with this number type (will need to export messages), and test this.
- [x] Performance wise, it should ensure that it uses the machine-word types wherever possible, as the JVM has a much better chance of optimising these.
- [x] Benchmark this number type comprehensively.

### Acceptance Criteria & Test Cases

- The above functionality has been designed and implemented.
- It has been tested in the test suite with both functional and performance tests.

**Comment by kustosz** [comment]
Technical hints:
1. Read how SL implements numbers, this will give you a good idea of how to do state transitions in the DSL.
2. In our case, the specializations should only specialize on the second argument of operators. The specialization on the first argument should be realized through method dispatch. I.e. have separate paths in `MethodResolverNode` for dispatch on different numeric types and register multiple different functions per `this` type. For example, there should be a method definition for `Long.add` that internally, through DSL specializes on the second argument (i.e. do a different thing for `Long + double` vs `Long + Long` vs `Long + BigInt`). Meanwhile, `BigInt + Long` should be implemented as a specialization of the method `BigInt.+`. 
3. In the method resolver node, make use of the type hierarchy chains, to allow best extensibility from the Enso side. For example when resolving a method on a `long`, look for methods defined on Enso-side `Long`, then `Integer`, then `Number`, then `Any`. This will allow the user to define a method only for integers etc. The dispatch chains should be as follows:
`long`: `Prim_Int_64 -> Integer -> Number -> Any`
`BigInteger`: `Prim_Big_Integer -> Integer -> Number -> Any`
`double`: `Prim_Float_64 -> Number -> Any`
`BigDecimal`: `Prim_Big_Decimal -> Number -> Any`
The `Prim_*` types will probably be private outside of `Base` (when that becomes possible), but we should have them implemented for the future – it will allow us to implement different kinds of number semantics (e.g. a pure `BigDecimal` subset) later without changing the underlying representations. The advice from point 2. now becomes "implement the number operations as methods of `Prim_*` types".
4. Don't panic when you get a (small, probably in the 10-30% range) slowdown in existing benchmarks. They should remain in the `long` range, but every arithmetic operation will now incur an additional `jo` instruction when compiled. However, no matter the slowdown, please use IGV to ensure that `jo` is the _only_ overhead in existing benchmarks after compilation.

**Comment by kustosz** [comment]
5. Remember to put `BigInteger` / `BigDecimal` operations behind a `@TruffleBoundary`.
6. Try to cache the results of `BigDecimal -> double` conversion. It's a slow operation (`@TruffleBoundary`) which will only occur for literals. Therefore, specializations accepting a `BigDecimal` should speculate on the operand being a constant and cache a few different cast results. You should see a significant speed-up after doing this.

**Comment by kustosz** [comment]
7. Implement 6. in a separate node that should be a `@Cached` child of the big-decimal-related specializations. This will significantly reduce the amount of copy-pasting you have to do.

**Comment by kustosz** [comment]
8. Make sure to use `@ReportPolymorphism` for your nodes (ones that actually have multiple specializations), so that splitting can do its job.
