### ISSUE TITLE
Investigate high memory usage of WASM

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#5844]
During my work on BookClub_6, roughly taking 40 minutes, I noticed high WASM memory usage - 1.15 GB. The memory usage was still raising throughout my work and never dropped. Looking at the particular `opera` process on my system, the process had 1.9 GB allocated.

![Screenshot from 2023-03-07 13-16-02](https://user-images.githubusercontent.com/14013887/223499378-d6843435-455a-4f27-8af4-c29d8e5cb21c.png)

We should investigate whether we don't keep references to some objects that should already be garbage collected.

This might be an issue only on my machine - I have 64 GB memory and tried latest Enso in `opera` browser.

**Comment by wdanilo** [comment]
Good point. We should investigate it after performance work is done. CC @sylwiabr

**Comment by farmaazon** [comment]
Not relevant to GUI2
