### ISSUE TITLE
Avoid unnecessary spaces when modifying node expression in CB

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#5848]
When editing the node with CB and accepting a suggestion, we should avoid adding unnecessary spaces after the changed fragment. See #5770

## AC

Cursor position is represented by `|` character.

1. Replacing `foo` with `bar` in `foo` adds additional space at the end: `bar |`
2. Replacing `foo` with `bar` in `foo + baz` only moves the cursor one place: `bar |+ baz`
3. Replacing `foo` with `bar` in `(1 + foo)` doesn't add space and doesn't move the cursor: `(1 + bar|)`
4. Replacing `foo` with `bar` in `[1, foo]` doesn't add space and doesn't move the cursor: `[1, bar|]`

**Comment by farmaazon** [comment]
Most points are applied in GUI2. We move the cursor _after_ closing bracket, but it was on purpose by me (otherwise we still see the filtered entries). If we change our minds, let's reopen this or file another issue.
