### ISSUE TITLE
Investigate Why Using `whenReady()` Freezes the Application

### ISSUE THREAD

**Issue by indiv0** [enso-org/enso#5851]
### What type of issue is this?

Transient – Occuring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

PR https://github.com/enso-org/enso/pull/5793 introduced [a change](https://github.com/enso-org/enso/pull/5793/files/0042018e7a40a703cda72bbf73e0e5549aa1341e#diff-b95360e2d8b887bb7979194b5085fd434a0512895b389e74f7a207713fdb4f6bL53-R54):
```diff
- electron.app.whenReady().then(() => this.main(windowSize))
+ electron.app.on('ready', () => this.main(windowSize))
```

In this change, the `whenReady()` listener was replaced. It was removed because the application freezes during the loading of the spinner, after the https://github.com/enso-org/enso/pull/5793/files/0042018e7a40a703cda72bbf73e0e5549aa1341e#diff-b95360e2d8b887bb7979194b5085fd434a0512895b389e74f7a207713fdb4f6bR106 `authentication.initModule` method was added to the startup process for the client.

The same freeze does not occur if the `on('ready', ...)` listener is used. It is unclear why.

### Expected behaviour

The `whenReady()` listener should be usable in place of the `on('ready', ...)` listener, without causing a freeze of the application. The cause of the freeze must be investigated before this issue can be fixed.

### How we can reproduce it?

The steps defined in this [comment](https://github.com/enso-org/enso/pull/5793#discussion_r1129142459) outline an approach to diagnosing the issue.

### Enso Version

https://github.com/enso-org/enso/pull/5793

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

MacOS Ventura

### Hardware you are using

M2 MacBook Air 24 GB

**Comment by wdanilo** [comment]
It's worth noting here that `whenReady` is better solution than what we use now, as it is a promise that could be already resolved. The current solution might not work if the event was emitted before the handle was registered. That's why we want to fix it.

**Comment by wdanilo** [comment]
@hubertp I'm not sure I should be assigned to it. CC @sylwiabr
