### ISSUE TITLE
Running GUI via `./run watch gui` will occasionally fail to serve the generated WASM file

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#5860]
### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Initially reported in the [discussion](https://github.com/orgs/enso-org/discussions/5788).

Running via `./run gui watch --skip-wasm-opt` will start the server but occasionally fail to serve the generated WASM file 
hanging the loading of the page.
In the console we would get 
```
Uncaught (in promise) CompileError: WebAssembly.instantiateStreaming(): section (code 10, "Code") extends past end of the module (length 29962350, remaining bytes 27208289) @+185753
```
 
The only workaround is to restart the command.

### Expected behaviour

Should always serve generated WASM files.

### Screenshots or screencasts

![image](https://user-images.githubusercontent.com/292128/223784731-c79df88e-5964-412f-9dd4-b41d30c61dae.png)

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by JaroslavTulach** [comment]
Obsoleted with GUI rewrite.
