### ISSUE TITLE
Focus feature in Component Browser occasionally loses focus on mouse hover over not focused components

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#5862]
### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When using component browser when I select some component to have documentation on it pinned in the doc panel it occasionally switches to a different component that wasn't clicked with RMB but cursor of the mouse touched it.

It can be observed here (0:20sec, 0:33sec)

https://user-images.githubusercontent.com/108271897/223801263-006e91dc-1544-40d5-9893-2fc549f71008.mp4

and here (0:46sec, 0:53sec, 1:04sec, 2:13sec):

https://user-images.githubusercontent.com/108271897/223802956-cf1fd13f-c79e-458d-8e2e-bf3318c66e94.mp4

Subjective observation: w/o screen recording it happens a lot more often (when CB works much more fluidly).

### Expected behaviour

Documentation on selected with RMB component stays in doc panel once mouse leaves any other component.

### How we can reproduce it?

Tab to open CB
RMB on any component
Move mouse around over different components 
Move randomly mouse cursor over the doc panel

### Screenshots or screencasts

attached in the desctiption

### Enso Version

Build: Nightly Release #842

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

Standalone

### Operating System

Windows

### Operating System Version

11pro

### Hardware you are using

i9 12th gen / discrete gpu

**Comment by vitvakatu** [comment]
It looks like we don't call `unhover` when leaving the CB list. Though documentation hover event is definitely handled, as you can see a system mouse cursor. So the main issue is that our mechanism for "lost focus" of CB is not robust enough.

**Comment by wdanilo** [comment]
Good finding @xvcgreg! Could I ask you though to make the title of the issue more clear please? Based on the title alone I would never know what this issue is about.

**Comment by farmaazon** [comment]
Not reproducible in new GUI/new CB
