### ISSUE TITLE
Implement `nullable` Value_Types

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#5872]
Currently our Value_Types do not care about nullability.

Add a `is_nullable` flag to all types and adjust behavior accordingly:

- Ensure that most specific type logic will not mark columns without missing values as nullable.
- If a column containing nulls is set to non-nullable - raise error.
- See what other places need adjustment.

**Comment by radeusgd** [comment]
On the edge between estimating this as 5 or 8. Keeping the larger to be safe, there is quite a lot here - possibly once I start working on it I may consider splitting into smaller pieces - but that is to be defined once I go deeper into what exactly needs to be done.

**Comment by jdunkerley** [comment]
Currently we are allowing columns to be null - not sure if we need to limit this.

**Comment by jdunkerley** [comment]
Closing as not doing.
Our value types will allow NULLs.
