### ISSUE TITLE
`from_rows` and `new` suggestions in CB while opening with the `Table` selected

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#5874]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I open a CB with `Table` selected I am getting `from_rows` and `Table.new` as the best suggestions - they are invalid and choosing those would create always a node with an error.
<img width="978" alt="image" src="https://user-images.githubusercontent.com/12892578/224025537-77962258-eb45-408d-9004-44f0147cb833.png">

### Expected behaviour

We should not suggest both of those when working with already created table.

### Enso Version

Nightly 9.03.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
@4e6 is it hard to make `searcher/component` skipping static methods if called with `this` parameter? I know we want to resign from it, but we are still far on the IDE side.

**Comment by 4e6** [comment]
Yes, I think it is possible. I'll take a look
