### ISSUE TITLE
Visualisation evaluation failed: Type error: expected a function, but got 100000 (Integer) resulting in Error

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#5877]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While recreating 101 Enso script I have encountered wierd behaviour when changed the original range of 0 to 100 to some greater numbers (1000, 10000, 100000).

Multiple warnings:
```[warn] [2023-03-09T17:19:31.685Z] [enso] Visualisation evaluation failed: Type error: expected a function, but got 100000 (Integer)..```

resulting in error:
```[error] [2023-03-09T17:19:37.349Z] [org.enso.languageserver.requesthandler.visualisation.ModifyVisualisationHandler] Request [Number(120)] timed out.```

Starts at 2:05 mark in the vid:

https://user-images.githubusercontent.com/108271897/224111623-ef024b13-a5d6-4f0d-8c62-64ae1ff642b6.mp4

log: [2303091824_shareX.txt](https://github.com/enso-org/enso/files/10934516/2303091824_shareX.txt)

### Expected behaviour

User should be able to enter almost any reasonable range w/o errors.

### How we can reproduce it?

See the video

### Screenshots or screencasts

attached in the description of the issue

### Enso Version

Build: Nightly Release #842

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro

### Hardware you are using

i9 12th gen / discrete gpu

**Comment by hubertp** [comment]
@xvcgreg This is also a glitch, right? Probably warrants a separate ticket
![Screenshot from 2023-03-09 19-48-25](https://user-images.githubusercontent.com/292128/224125491-295a8b89-bf5a-4a49-b5f7-9b034e70d7dc.png)

**Comment by xvcgreg** [comment]
> @xvcgreg This is also a glitch, right? Probably warrants a separate ticket 

I believe we have a ticket for broken node links already filed. But found just this #5405 mysterious one.

**Comment by sylwiabr** [comment]
@xvcgreg are you sure you linked the correct ticket? This one is a placeholder for the future feature we will need to add...

**Comment by xvcgreg** [comment]
> @xvcgreg are you sure you linked the correct ticket? This one is a placeholder for the future feature we will need to add...

@sylwiabr I'm not sure - as I wrote that's the only one I found treating on IO of nodes
@farmaazon Can you recall such ticket?

**Comment by sylwiabr** [comment]
@xvcgreg https://github.com/enso-org/enso/issues/5095 here it is - you were even an author of it

**Comment by xvcgreg** [comment]
> @xvcgreg #5095 here it is - you were even an author of it

thanks!

**Comment by jdunkerley** [comment]
We need to isolate where this exception is coming from and then adjust the viz code in Standard.Visualization.

**Comment by hubertp** [comment]
@jdunkerley I'm looking into this

**Comment by jdunkerley** [comment]
k thanks @hubertp

**Comment by hubertp** [comment]
I'm fairly sure those failures in visualization are triggered by eager request for visualization coming from CB similar to  https://github.com/enso-org/enso/issues/5888. 
And just to illustrate why I think this is the case:
![Screenshot from 2023-03-10 16-28-56](https://user-images.githubusercontent.com/292128/224356516-6ba5048f-1d1e-42b2-911e-1a3db641b7f4.png)

**Comment by hubertp** [comment]
@farmaazon Feel free to re-assign back to me if you don't think this is not a duplicate.

**Comment by farmaazon** [comment]
It seems fixed on newest nightly (which features "literal" suggestions - merged in #5770 ).
