### ISSUE TITLE
Colors of edges is inconsistent and changes when connecting other inputs.

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#5886]
Noticed on recent develop while testing one of the PRs.

https://user-images.githubusercontent.com/6566674/224274046-8a684ce4-e847-4a01-b75c-4e97bbec1259.mp4

**Comment by farmaazon** [comment]
Check if it still does not work after @Frizi changes (a00efb28f3cca317464a71c1aa0bad63f2e2724a)

**Comment by jdunkerley** [comment]
Closing as new colouring is based on target node.
