### ISSUE TITLE
Mapping value to elements of vector renders errror despite transforming data correctly

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#5888]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![image](https://user-images.githubusercontent.com/108271897/224278338-6651e79c-e084-43e2-93b5-be3e31f295ec.png)

### Expected behaviour

Visualization of vector with increased values of its elements

### Enso Version

Build: Nightly Release #842

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro

### Hardware you are using

i9 12th gen / discrete gpu

**Comment by farmaazon** [comment]
@xvcgreg Is this bug about _Visualization Preview_ of the edited node only? 

If yes: the visualization preview shows the result of the last selected entry, not input. See https://github.com/enso-org/enso/discussions/5856

The UX should be improved somehow once we merge #5770 as writing literal should show special "literal" entry.

<blockquote><img src="https://opengraph.githubassets.com/54ffb7524feae62ddc4b421bfb3dd15a245165cf9fac8173957f7f788589edad/orgs/enso-org/discussions/5856" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/orgs/enso-org/discussions/5856">How to improve Visualization Previews · enso-org/enso · Discussion #5856</a></strong></div><div>So, the Component Browser&#39;s Visualization Preview was implemented some time ago, and roughly works as described in the design. But once the CB was used by various people, a few UX issues emerge...</div></blockquote>

**Comment by wdanilo** [comment]
@farmaazon wait, but why the selected entry is not `map` in the @xvcgreg example?

**Comment by farmaazon** [comment]
> @farmaazon wait, but why the selected entry is not `map` in the @xvcgreg example?

Because we assume user finished typing function name (put the space after `map`) and now fills the first argument.

So we display what happens when user picks the currently selected argument. Somehow, before the CB was cleared up, the last selected argument was "connect" method, which we tried to apply as first argument (and thus the error)

**Comment by xvcgreg** [comment]
I have always confirmed creating a node with ctrl+enter,

https://user-images.githubusercontent.com/108271897/224308890-cf74f681-bf9a-465b-83a4-932377e1f90a.mp4

in the second movie i have spaced with tab so no component is selected:

https://user-images.githubusercontent.com/108271897/224308979-9c1677d5-aef3-4fb8-8fc2-c6fbe5fae827.mp4

**Comment by wdanilo** [comment]
> > @farmaazon wait, but why the selected entry is not `map` in the @xvcgreg example?
> 
> Because we assume user finished typing function name (put the space after `map`) and now fills the first argument.
> 
> So we display what happens when user picks the currently selected argument. Somehow, before the CB was cleared up, the last selected argument was "connect" method, which we tried to apply as first argument (and thus the error)

Gotcha, but I understand that the `connect` hint is invalid when typing `+20`, right? We should consider this a searcher bug/improvement, is that correct?

**Comment by xvcgreg** [comment]
@farmaazon In the second example I have used the suggestion acceptance key ``Tab`` which should allow me to further edit the expression when I was done with +20 I have hit ``Ctrl + Enter`` to create this function. That has not changed the viz panel content.

**Comment by farmaazon** [comment]
> Gotcha, but I understand that the `connect` hint is invalid when typing `+20`, right? We should consider this a searcher bug/improvement, is that correct?

Well, if there is no item in CB we have none selected (and that's why Tab does not work), but still keep the old preview. We can change that, of course. But I will judge the importance of this issue when #5770 will be merged.

**Comment by farmaazon** [comment]
I think it was fixed by #6812. Now, if no entry is visible, we display the input.
