### ISSUE TITLE
Spurious visualization request timeouts caused by cancelling all jobs after file edits

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#5889]
This investigation into this issue was partially triggered by https://github.com/enso-org/enso/issues/5877 investigation where I noticed `Request timeout` in `DetachVisualisationHandler` being triggered rather frequently:
```
[error] [2023-03-10T11:25:09.319Z] [org.enso.languageserver.requesthandler.visualisation.DetachVisualisationHandler] Request [Number(16)] timed out.
[error] [2023-03-10T11:25:09.319Z] [org.enso.languageserver.requesthandler.visualisation.DetachVisualisationHandler] Request [Number(18)] timed out.
```

### To reproduce
Steps to reproduce are not always working due to an inherent race-condition between the actions submitted by IDE.
A simple project suffices
![Screenshot from 2023-03-10 15-07-28](https://user-images.githubusercontent.com/292128/224337879-b68de3b2-a45b-4a18-8cb2-f364165cce74.png)
Now select all the nodes and simply delete them.
This will trigger 2 kinds of actions:
- `executionContext/detachVisualisation`
- `text/applyEdit`

Note that the order of execution of actions is very much environment dependent and therefore not always reproducible. We can either get a smaller number of request timeouts or none at all.

## Problem 1.
For such 2 nodes deletion we seem to get 4(!) `executionContext/detachVisualisation` requests. Those are issued separately  from the apply edit request corresponding to deletion of nodes.

## Problem 2
`DetachVisualisation`  and `ApplyEdit` commands are typically submitted in close succession. If any of the detach jobs is **submitted** but not **executed** before `ApplyEdit` is executed, it will likely lead to spurious `Request timeouts`. 
This is because the latter [cancels](https://github.com/enso-org/enso/blob/develop/engine/runtime/src/main/scala/org/enso/interpreter/instrument/command/EditFileCmd.scala#L30) pending jobs, and handlers for `DetachVisualisation` will simply timeout waiting for the results of submitted jobs that will never execute.
Should there be a more fine-grained or graceful cancellation of jobs that doesn't lead to timeouts?

**Comment by 4e6** [comment]
Yes, that makes sense. I checked and turned out that `DetachVisualizationJob` is cancellable. It should not be like that

**Comment by 4e6** [comment]
After further poking around I realized that `DetachVisualizationJob` should not only be not-cancellable but extend `UniqueJob` because it does not make sense to have multiple `DetachVisualizationJobs` queued for a single expression.

**Comment by hubertp** [comment]
> After further poking around I realized that `DetachVisualizationJob` should not only be not-cancellable but extend `UniqueJob` because it does not make sense to have multiple `DetachVisualizationJobs` queued for a single expression.

I think they were unique (by coincidence?) but I will double-check

**Comment by hubertp** [comment]
@4e6 same with `ModifyVisualisation`? That one appears to be unique at least

**Comment by 4e6** [comment]
ModifyVisualization  works correctly and triggers the `UpsertVisualizationJob` which is already marked as unique. We just need to mark `DetachVisualizationJob` as unique too:

```diff
--- a/engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/DetachVisualisationJob.scala
+++ b/engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/DetachVisualisationJob.scala
@@ -23,7 +23,7 @@ class DetachVisualisationJob(
   expressionId: ExpressionId,
   contextId: ContextId,
   response: ApiResponse
-) extends Job[Unit](List(contextId), true, false) {
+) extends UniqueJob[Unit](expressionId, List(contextId), false) {

   /** @inheritdoc */
   override def run(implicit ctx: RuntimeContext): Unit = {
   ```
