### ISSUE TITLE
Scrolling a visualisation window to the right hangs the browser tab

### ISSUE THREAD

**Issue by PabloBuchu** [enso-org/enso#5891]
### Discord username

pbuchu

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Opening the visualisation window and scrolling to the right makes the browser tab unresponsive. After couple of second "Page Unresponsive" alerts pop up. Reload does not help, I need to copy the location url and open it in another tab.

### Expected behaviour

I should be able to scroll my visualisation back and forth without a problems

### How we can reproduce it?

1. Use cloud.eno.org to create and open project
2. Upload any bookclub entry file
3. Open visualisation window
4. Scroll to the right (sometimes you need to scroll back) but it will hang eventually

### Screenshots or screencasts

<img width="1792" alt="Screenshot 2023-03-10 at 15 40 27" src="https://user-images.githubusercontent.com/2855109/224350016-2729c6ba-1b34-421b-92e8-0ad9f6ab4646.png">

### Enso Version

2023.1.1-nightly.2023.3.8.1

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

Version 110.0.5481.177 (Official Build) (x86_64)

### Operating System

MacOS

### Operating System Version

Monterey 12.5.1

**Comment by MichaelMauderer** [comment]
@PabloBuchu Does this happen for every visualization or only specific ones? Specifically, does it happen for the Text/JSON Visualization or the Table Visualization?

**Comment by wdanilo** [comment]
@PabloBuchu I think you had an update here, right? I think you told me you will write new observations here.

**Comment by PabloBuchu** [comment]
Closing as the bug no longer occurs with new visualisation layout
