### ISSUE TITLE
Dynamic widget visualization throws an error

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#5893]
On latest engine versions, the visualization that is responsible for widget data throws an error. In effect, the dynamic widgets never how up. The error is reported in the console as a visualization execution error.

<details>
<summary>Reported visualization error: <code>Method `map` of Function could not be found.</code></summary>

```json
{
  "jsonrpc": "2.0",
  "method": "executionContext/visualisationEvaluationFailed",
  "params": {
    "contextId": "6d8fccce-38b3-495a-87ed-4af06a67ddb5",
    "visualisationId": "41fec3bf-eebc-44d7-a185-bca5753a33f0",
    "expressionId": "c85c515e-cc9e-4022-a826-f4faeb6db66d",
    "message": "Method `map` of Function could not be found.",
    "diagnostic": {
      "kind": "Error",
      "message": "Method `map` of Function could not be found.",
      "path": {
        "rootId": "19e3e980-e2f7-4b4c-bf20-5753a2e4aaf7",
        "segments": [
          "src",
          "Main.enso"
        ]
      },
      "location": {
        "start": {
          "line": 17,
          "character": 16
        },
        "end": {
          "line": 17,
          "character": 56
        }
      },
      "expressionId": "8148e959-14dc-4530-b0d8-58e6b832b0e2",
      "stack": [
        {
          "functionName": "Main.main",
          "path": {
            "rootId": "19e3e980-e2f7-4b4c-bf20-5753a2e4aaf7",
            "segments": [
              "src",
              "Main.enso"
            ]
          },
          "location": {
            "start": {
              "line": 17,
              "character": 16
            },
            "end": {
              "line": 17,
              "character": 56
            }
          },
          "expressionId": "8148e959-14dc-4530-b0d8-58e6b832b0e2"
        }
      ]
    }
  }
}
```
</details>

Affected engine release: `2023.1.1-nightly.2023.3.9`
Known good engine release: `2023.1.1-nightly.2023.3.4`

|Missing widget on `2023.1.1-nightly.2023.3.9`|Widget on `2023.1.1-nightly.2023.3.4`|
|-|-|
|![No drop down for Table.at](https://user-images.githubusercontent.com/26887752/224062675-68ca5c81-3809-4147-b863-fe8ec4323534.png)|![Dropdown with column names for Table.at](https://user-images.githubusercontent.com/919491/224307315-b8f80262-f6d5-400e-85ce-06ea48fb8b3d.png)|

Issue orginally reported in https://github.com/enso-org/enso/pull/5852#issuecomment-1462199693

**Comment by jdunkerley** [comment]
Resolved some issues with warnings in the Widgets library and the engine. 

However the argument isn't added for values with warnings for some reason.


![Image](https://user-images.githubusercontent.com/4699705/225947778-d7b01ed5-df06-4aba-921b-2d6e405890bb.png)

**Comment by jdunkerley** [comment]
Following some debugging with Dmitry, the `callInfo` and `cachedCallInfo` in the `ExpressionValue` are not set.

Looking into `IdExecutionInstrument::onReturnValue` the `onFunctionReturn` is not tiggered for a `WithWarnings` value.

**Comment by jdunkerley** [comment]
Value with no warning causes:
- FunctionCallInstrumentationNode
- ExpressionNode
to occur.

If there is a warning attached to the "self" then, no FunctionCallInstrumentationNode
(Inside IdExecutionInstrument)

**Comment by jdunkerley** [comment]
![Image](https://user-images.githubusercontent.com/4699705/226338693-a7c9ce34-f17c-4b7b-aca7-02a0683c1278.png)

The above workflow is enough to reproduce the issue. Change the input to the warning version and it will not do parameters in the IDE.
