### ISSUE TITLE
Overhaul the random number and item generation code

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#5897]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Random function is useless - needs revisit
![image](https://user-images.githubusercontent.com/108271897/224574189-de814cec-3310-4c98-830b-9289d98cfecc.png)

### Expected behaviour

each time new set of random data, preferably with possibility of defining seed as an argument

### Enso Version

Build: Nightly Release #842

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by wdanilo** [comment]
@xvcgreg What the title means? The sentence ".noise function needs revisit for its seed is the input " is not a correct English sentence.

**Comment by jdunkerley** [comment]
@xvcgreg had spoken over this one with me over the weekend. We need to review the random data APIs we have and make them more obvious to end users.

**Comment by jdunkerley** [comment]
This should include trivial random statics with a single seed object.
The `.noise` should be removed as not useful.

Should promote the `Faker` library from `Test` to `Base` (as generally useful).
Should include a `Lorem Ipsum` implementation as useful.

**Comment by jdunkerley** [comment]
[Main.txt](https://github.com/enso-org/enso/files/11260635/Main.txt)

Lorem Ipsum implementation.
