### ISSUE TITLE
Any.== slowed down by Panic.catch 2x times

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#5898]
I have just been verifying the effect of #5845 on performance of [sieve.enso](https://github.com/jtulach/sieve/blob/5ff0f8881aed3d0b772c532e22665361ad8f0854/enso/sieve.enso) and via _VisualVM Polyglot Sampler_ I can see that an enormous time is being spent on [line 31 comparing == 0](https://github.com/jtulach/sieve/blob/5ff0f8881aed3d0b772c532e22665361ad8f0854/enso/sieve.enso#L31) and subsequently catching panics. Single round of the benchmark takes:
```
Hundred thousand prime numbers in 895 ms. Last one is 1299709
```
By changing the Enso standard library to:
```diff
diff --git distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
index 565b64adcb..7181423508 100644
--- distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
+++ distribution/lib/Standard/Base/0.0.0-dev/src/Any.enso
@@ -108,8 +108,8 @@ type Any
     == self that =
         # If there is No_Such_Conversion, then `self` and `that` are probably
         # host or polyglot values, so we just compare them with the default comparator.
-        eq_self = Panic.catch No_Such_Conversion (Comparable.from self) _-> Default_Comparator
-        eq_that = Panic.catch No_Such_Conversion (Comparable.from that) _-> Default_Comparator
+        eq_self = Comparable.from self
+        eq_that = Comparable.from that
         similar_type = Meta.is_same_object eq_self eq_that
         case similar_type of
             False -> False
```
I am able to get to better numbers. Single round of the benchmark goes down to:
```
Hundred thousand prime numbers in 403 ms. Last one is 1299709
```
e.g. the benchmark gets twice as fast by eliminating `Panic.catch` call.

**Comment by hubertp** [comment]
Isn't this related to the whole `if/then/else` slowdown. Seems like `thunk` execution is really the root of all evil.

**Comment by JaroslavTulach** [comment]
> Isn't this related to the whole `if/then/else` slowdown. Seems like `thunk` execution is really the root of all evil.

Yes, the `if/then/else` handling may be the cause. I did some investigation https://github.com/enso-org/enso/issues/5709#issuecomment-1494620793 and yes, there is a spurious `OptimizedCallTarget.callBoundary` - it shouldn't be there. However I am not sure how to get rid of it.

Anyway the current `Any.==` logic is complex and simplifying it for simple cases is also desirable.
