### ISSUE TITLE
Tag values use incorrect fully qualified names.

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#5901]
The `tag_values` field provided within suggestion database should always contain fully qualified names, so they can be resolved on IDE side and used as suggestions in dropdowns.

Currently for some types, the provided names within `tag_values` are either not fully qualified (but work with the right import), or just completely incorrect.

### Example with non-FQN values
`Text.trim` method, `where` argument.
<img width="183" alt="image" src="https://user-images.githubusercontent.com/919491/224712980-cd7e37c5-1c7a-460e-907d-cf99b2604267.png">
Provided argument data in suggestion database:
```json
{
  "name": "where",
  "reprType": "Location.Start | Location.End | Location.Both",
  "isSuspended": false,
  "hasDefault": true,
  "defaultValue": null,
  "tagValues": [
    "Location.Start",
    "Location.End",
    "Location.Both"
  ]
}
```
Provided values are short. This happen to work in IDE, since the right import is usually already present. Unfortunately it means we cannot add that import in case it is necessary.

Expected tagValues:
```json
  "tagValues": [
    "Standard.Base.Data.Text.Location.Start",
    "Standard.Base.Data.Text.Location.End",
    "Standard.Base.Data.Text.Location.Both"
  ]
```

### Example with invalid value
`File.read` method, `on_problems` argument.
<img width="425" alt="image" src="https://user-images.githubusercontent.com/919491/224714966-1569304d-5557-416a-8158-44f49d9121d4.png">
Provided argument data in suggestion database:
```json
{
  "name": "on_problems",
  "reprType": "Standard.Base.Error.Problem_Behavior.Problem_Behavior",
  "isSuspended": false,
  "hasDefault": true,
  "defaultValue": null,
  "tagValues": [
    "Standard.Base.Error.Problem_Behavior.Ignore",
    "Standard.Base.Error.Problem_Behavior.Report_Warning",
    "Standard.Base.Error.Problem_Behavior.Report_Error"
  ]
}
```

The provided tag values contain invalid FQNs. The module and type names has been incorrectly deduplicated. The correct values would be:
```json
  "tagValues": [
    "Standard.Base.Error.Problem_Behavior.Problem_Behavior.Ignore",
    "Standard.Base.Error.Problem_Behavior.Problem_Behavior.Report_Warning",
    "Standard.Base.Error.Problem_Behavior.Problem_Behavior.Report_Error"
  ]
```

**Comment by jdunkerley** [comment]
The issue with `trim` is in the type definition line. Will investigate the Problem_Behavior.

**Comment by jdunkerley** [comment]
`trim` is fixed. The other issue is related to work @hubertp is doing on import / export so will hand that part to him.

**Comment by jdunkerley** [comment]
Suggestion database appears to have the correct type information for the `on_problems`. 


![Image](https://user-images.githubusercontent.com/4699705/225653394-6ba24aeb-2575-4f9e-956a-ad75f52ad485.png)
