### ISSUE TITLE
Bringing up the Viz selection menu causes the text on nodes to vanish

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#5912]
### Discord username

jdunkerley

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When you bring up the viz chooser for a node all nodes on other text disappears.

### Expected behaviour

Not losing the text!

### How we can reproduce it?

Open a viz on a node, change from default to something else, text vanishes.

### Screenshots or screencasts

https://user-images.githubusercontent.com/4699705/224777443-0c03ff5b-79ad-44c7-8c56-0e91f83ec7a5.mp4

### Enso Version

Develop as of 13/3

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Microsoft Windows [Version 10.0.22621.1105] Version 22H21

### Hardware you are using

AMD 6800HS 32GB RTX3050

**Comment by 4e6** [comment]
The issue is triggered when you press the down arrow button. There are no interactions with the engine happening at that moment. I'm pretty sure it's something wrong with the rendering.
