### ISSUE TITLE
Docs are outdated Re: engine distribution and licensing of Rust dependencies

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#5914]
This is in the docs:

https://github.com/enso-org/enso/blob/888307f03ff661d78bd1c5b652cca11428055333/docs/distribution/licenses.md?plain=1#L58-L68

We *do* now distribute Rust-based artifacts, ~and it looks like we also already handle their licensing  (#1187, implemented in #1183). So probably, this file just needs to be updated.~

**Comment by wdanilo** [comment]
Good points. CC @xvcgreg could you handle it, please?

**Comment by kazcw** [comment]
@wdanilo @xvcgreg I had another look at #1187--I don't think it's been done. It was closed when we closed all our GH issues. We are missing attribution for Rust dependencies.

**Comment by kazcw** [comment]
This is now covered by the other issue.
