### ISSUE TITLE
simplify node edit mode to not interfere with widgets

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#5919]
Current node edit mode is tightly coupled with existing ports displaying logic. In anticipation of node input refactor with widget trees, the edit mode must be separated into its own logic and use dedicated text label for its needs.

- Handle edit mode with a single long editable text. Existing ports and widgets should be hidden when edit mode is active.
- When edit mode is entered, all interactions other than manually editing text are not available.
- If node is externally updated during edit, the edit mode itself ignores that change. When edit is later canceled (using esc key), all external updates that happened during edit must be applied to ports and widgets.

**Comment by sylwiabr** [comment]
@Frizi was that finished?there is no update since last Wednesday

**Comment by farmaazon** [comment]
**QA:** @farmaazon
