### ISSUE TITLE
Add minimal hierarchical widget definition

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#5920]
Add an new widget enum variant for a hierarchical widget, with no actual implementation. That way it can be used during development of vector editor before widget tree implementation is done.

**Comment by wdanilo** [comment]
@Frizi please add at least short description.

**Comment by Frizi** [comment]
Since the vector editor needs to be usable on its own, it won't be using that temporary hierarchical widget. Instead, it will hardcode its own "code editor" widget for all entries until the widget hierarchy is done. This task is no longer needed.
