### ISSUE TITLE
Modifying code to add/remove context switch expressions.

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#5926]
We need an API on the controller side to recognize, add, remove, and modify *context switch expressions* inside a single node. 

Context switch expression looks like the following:

```
Standard.Base.Runtime.enable_context "Output" in="mode" <| rest_of_the_expression
Standard.Base.Runtime.disable_context "Output" in="mode" <| rest_of_the_expression
```

We support two execution modes (`in` argument): `development` and `production`.

Two switch expressions can be nested one into the other:

```
Standard.Base.Runtime.enable_context "Output" in="mode" <| Standard.Base.Runtime.enable_context "Output" in="mode2" <| rest_of_the_expression
```

We do not support more than two chained expressions, nor do we support these patterns inside subexpressions.

The modification includes switching from `enable_context` to `disable_context`, and also changing the `mode` in the `in` argument.

We only recognize fully qualified names `Standard.Base.Runtime.enable_context` and `Standard.Base.Runtime.enable_context`.

### QA Acceptance Criteria

See test cases in the [table](https://docs.google.com/spreadsheets/d/1Ks_qOlFdAdLgVEhF-V0RU5BhmpwDKDSUAEXDnbHfFkM/edit?usp=sharing) – everything should be supported.

**Comment by farmaazon** [comment]
Shouldn't the `enable_context` take also a context name as argument (always "output")? Or is "output" the default one?

**Comment by vitvakatu** [comment]
> Shouldn't the enable_context take also a context name as argument (always "output")? Or is "output" the default one?

You're right, fixed.
