### ISSUE TITLE
Importing a nonexistent module/type using `from` syntax does not yield any errors

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#5936]
## Repro

Run the following code:
```
from Standard.Base import Something_That_Does_Not_Exist

main = 423
```

## Expected Behaviour

Import resolution should fail and tell me that `Something_That_Does_Not_Exist` does not exist.

## Actual Behaviour

Instead the code runs OK and prints `423` on output.

**Comment by radeusgd** [comment]
It's even more suspicious if you run the following code:

```
from Standard.Base import Something_That_Does_Not_Exist

main =
    Something_That_Does_Not_Exist.do_a_thing_for_me 42
```

It yields:
```
In module nonexist:
Compiler encountered errors:
nonexist.enso[4:5-4:33]: The name `Something_That_Does_Not_Exist` could not be found.
Aborting due to 1 errors and 0 warnings.
Execution finished with an error: Compilation aborted due to errors.
```

So yeah, it _does_ report that the module was not found at usage site. But I can see I have an import that **did not fail**. Now I'm confused - I successfully imported this module, it should be here. If the module name does not have a weird name, I have no clue that it actually didn't exist instead.

Note that if I'd run the import without the `from` form:
```
import Standard.Base.Something_That_Does_Not_Exist

main =
    Something_That_Does_Not_Exist.do_a_thing_for_me 42
```

Then I get:

```
In module nonexist:
Compiler encountered errors:
nonexist.enso[1:1-1:50]: The module Standard.Base.Something_That_Does_Not_Exist does not exist.
nonexist.enso[4:5-4:33]: The name `Something_That_Does_Not_Exist` could not be found.
Aborting due to 2 errors and 0 warnings.
Execution finished with an error: Compilation aborted due to errors.
```

So it correctly points out that it was unable to **import** the module and now I know why it is later not found.

With `from` I do not know why it is not found, assuming that as I did not get any import resolution errors, the import must have succeeded.

cc: @hubertp you may be interested in this, as you know the imports resolution well

**Comment by JaroslavTulach** [comment]
> cc: @hubertp you may be interested in this, as you know the imports resolution well

Yup. I think @hubertp will need to take a look when not occupied with other pressing stuff.

**Comment by hubertp** [comment]
Yes, it's been like that forever.

**Comment by JaroslavTulach** [comment]
Shouldn't

```
from Standard.Base import Something_That_Does_Not_Exist

main = 412
```

yield a _warning_? Something `Something_That_Does_Not_Exist isn't used`? That would be way simpler check than trying to resolve symbols from other modules...

**Comment by wdanilo** [comment]
If the imported module does not exist, there should be a warning about it (explicitly telling that it does not exist). Warning is better than error, as it is less error-prone - more projects will work. If this happens and the graph still works, for the user it give a way more "stable" feeling than crashing with an error. I know this is not how IDEs work, but Enso is not an IDE and we should be as error-prone as possible.
