### ISSUE TITLE
Test performance of reduced pixel-read-pass frequency on slow-GPU hardware

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#5940]
Compare FPS after increasing `pixel_read_pass` threshold.

**Comment by sylwiabr** [comment]
was it done? is it finished? @wdanilo @kazcw what was the result of the benchmarks?

**Comment by wdanilo** [comment]
> was it done? is it finished? @wdanilo @kazcw what was the result of the benchmarks?

Sylwia, but you know that Kaz did not receive the hardware yet, right? So the test is not done yet.

**Comment by kazcw** [comment]
I've added a debug option (in #6019) to make benchmarking this easy, and I've measured it on my development machine (negligable impact here). When I have the Intel Xe hardware, I'll run the same test on it and compare results.

**Comment by sylwiabr** [comment]
@wdanilo @kazcw what is the status of the test? can we close the issue? If not, please add the progress summary and the next steps.

**Comment by wdanilo** [comment]
@kazcw did you run the tests on Ned's machine just to check if they have any impact?

**Comment by farmaazon** [comment]
@kazcw Bump

**Comment by wdanilo** [comment]
We did the tests. It looks that it does not have big effect. Also, a flag was added to the IDE to test it out easily. Closing.
