### ISSUE TITLE
./run ide watch does not work on recent develop

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#5969]
Today I faced that `./run ide watch` stopped working on my machine.

```
TypeError: process.on is not a function
 INFO ide_ci::program::command: npm⚠️     at file:///Users/ilyabogdanov/projects/enso/app/ide-desktop/lib/client/watch.ts:79:9
 INFO ide_ci::program::command: npm⚠️ npm ERR! Lifecycle script `watch` failed with error:
 INFO ide_ci::program::command: npm⚠️ npm ERR! Error: command failed
 INFO ide_ci::program::command: npm⚠️ npm ERR!   in workspace: enso@0.0.0-dev
 INFO ide_ci::program::command: npm⚠️ npm ERR!   at location: /Users/ilyabogdanov/projects/enso/app/ide-desktop/lib/client
TRACE ide_ci::program::command: npmℹ️ <ENDUT>
```

Command I'm running: `./run ide watch --backend-source=release --backend-release="2023.1.1-nightly.2023.3.4" --cargo-watch-option -w --cargo-watch-option ../rebuild_me --wasm-size-limit=0 --skip-wasm-opt`

Last part of the log: https://gist.github.com/vitvakatu/252b3d230221a0bedefe248fc8c047c6

Version: `a6487e51055d88de53ba4aedac6416c85f155d6e`

**Comment by mwu-tow** [comment]
Reproed, looks like a regression from https://github.com/enso-org/enso/pull/5717

Not sure if my watcher code is wrong or linter.

**Comment by mwu-tow** [comment]
Oh, I see @somebody1234 already has fix! 👍

**Comment by somebody1234** [comment]
opened #5972 which should fix it, but currently running a `run ide build` (slow on my pc) so i can't test whether it works
