### ISSUE TITLE
./run ide watch displays white screen

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#5975]
Run the `./run ide watch` on a clean repository. A blank window appears.

This seems to be caused by hardcoding path to tailwind.css in https://github.com/enso-org/enso/commit/6f29262f90027995efbe8d5eee6d831496e97ad7#diff-57b07427fa0b3aa82b74d34fad7c62a14fb874dba1ca7a0e45cb86c67a021938R20

![obraz](https://user-images.githubusercontent.com/1548407/225628789-fab31591-9c7a-4baa-bcb3-02790e8bd1f8.png)

See https://github.com/enso-org/enso/pull/5972#issuecomment-1471916821

**Comment by mwu-tow** [comment]
@somebody1234 
> the way to go here is probably to edit the bundle.ts and watch.ts to build tailwind. it doesn't seem to have a programmatic api though so there might be a better way

Both are just wrappers for `app/ide-desktop/lib/content/esbuild-config.ts` — it should do the thing and use `output_path` rather than `../../../../../../dist/gui/assets`.
Perhaps there's a plugin for esbuild that can do that for us? (e.g. https://www.npmjs.com/package/esbuild-plugin-tailwindcss )

<blockquote><img src="https://static.npmjs.com/338e4905a2684ca96e08c7780fc68412.png" width="48" align="right"><div><img src="https://static.npmjs.com/da3ab40fb0861d15c83854c29f5f2962.png" height="14"> npm</div><div><strong><a href="https://www.npmjs.com/package/esbuild-plugin-tailwindcss">esbuild-plugin-tailwindcss</a></strong></div><div>Esbuild plugin for TailwindCSS. Latest version: 1.1.0, last published: a month ago. Start using esbuild-plugin-tailwindcss in your project by running `npm i esbuild-plugin-tailwindcss`. There are no other projects in the npm registry using esbuild-plugin-tailwindcss.</div></blockquote>

**Comment by PabloBuchu** [comment]
For anyone affected / blocked please remove `<link rel="stylesheet" href="/tailwind.css" />` from `app/ide-desktop/lib/content/src/index.html` which the `authentication` option is disabled

you will be able to work normally with IDE watch while we are preparing the fix

**Comment by somebody1234** [comment]
potential fix just committed. no idea if it works because it's still building...
