### ISSUE TITLE
Debug scenes not working

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#5980]
If I open any alternate entry point, e.g.:
`./dist/ide/linux-unpacked/enso -startup.entry=text_area`

I just get a window that says "Unauthenticated".

It worked in 7394a1a4ec543c033e95604322d220648c741031; is now broken in 7394a1a4ec543c033e95604322d220648c741031. Maybe related to #5798? (@PabloBuchu)

**Comment by PabloBuchu** [comment]
Yes we will disable authentication (set default to false) since it is partially merged.

**Comment by PabloBuchu** [comment]
@kazcw this PR fixes issue https://github.com/enso-org/enso/pull/5982 until its merged you can use `authentication=False` flag to run debug scene
