### ISSUE TITLE
Visualization chooser let's me choose Table vis (default one) which causes the vis going blank

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#5992]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://user-images.githubusercontent.com/12892578/225929654-08fb3d4c-3aaa-4976-a20a-02a5ad2b7c60.mov

### Expected behaviour

I can't choose table visualization when it is a default one

### Enso Version

126a4668720141e235aaa54c6dad41a10a82ac60

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by 4e6** [comment]
I was able to reproduce it on the current develop c696bf1d87ebb3524880e58219e04302021d9560

When the issue happens (pressing the down arrow and selecting the table) there are no interactions with the engine, so I'm transferring the issue to the IDE team.
