### ISSUE TITLE
Optimizing WebGL

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#6001]
# Introduction
Presently, the performance optimization of the WebGL scene display is inadequate, as is evident when executing Enso on legacy hardware, particularly those lacking a dedicated GPU. Numerous factors contribute to this predicament. Although the fundamental rendering architecture is extensible and modular, time constraints have limited the optimization of all aspects. As we near a stable release, it is imperative to identify and address the most critical areas of concern systematically.

## Related articles
- https://docs.google.com/presentation/u/1/d/12AGAUmElB0oOBgbEEBfhABkIMCL3CUX7kdAPLuwZ964/htmlpresent
- https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices
- http://nical.github.io/onGameStart2013/

<br/>

# Draw calls count
The optimization of the number of draw calls is a critical technique for ensuring optimal performance in WebGL applications. At present, we are facing two key issues in this regard. Firstly, there is a high number of draw calls. Secondly, even after removing certain scene elements such as the Component Browser, the number of draw calls per frame remains constant. Please find below a summary of my findings.

### Scene without nodes loaded – 18 draw calls

```
- *cursor (2?)*
  - lib/rust/ensogl/core/src/gui/cursor.rs:139:5
  - lib/rust/ensogl/core/src/gui/cursor.rs:139:5

- *buttons/icons (3)*
  - app/gui/view/graph-editor/src/component/add_node_button.rs:21:5
  - app/gui/view/src/window_control_buttons/close.rs:22:5
  - app/gui/view/src/window_control_buttons/fullscreen.rs:22:5
  - (unused icon, to be removed) app/gui/view/graph-editor/src/component/profiling.rs:31:5

- *rectangles (6)*
  - app/gui/view/src/window_control_buttons.rs:30:5
  - 2x lib/rust/ensogl/component/label/src/lib.rs:41:5
  - app/gui/view/graph-editor/src/component/breadcrumbs.rs:78:5
  - app/gui/view/graph-editor/src/component/breadcrumbs/project_name.rs:46:5
  - app/gui/view/src/status_bar.rs:95:5

- *text (1)*
  - lib/rust/ensogl/component/text/src/font/glyph.rs:100:5

- *screen (6!)*
  - screen
```

There are a few concerning issues here:
- The cursor is rendered twice.
- The `screen` draw call is evaluated 6 times per frame.
- There are many shapes that are basically "rectangles" and could be drawn using a single call instead of a call per-shape.

### Scene with nodes (+16 draw calls, total of 34 draw calls)

```
- *edge (7)*
  - app/gui/view/graph-editor/src/component/edge.rs:750:5
  - app/gui/view/graph-editor/src/component/edge.rs:749:5
  - app/gui/view/graph-editor/src/component/edge.rs:742:5
  - app/gui/view/graph-editor/src/component/edge.rs:741:5
  - app/gui/view/graph-editor/src/component/edge.rs:289:5
  - app/gui/view/graph-editor/src/component/edge.rs:751:5
  - app/gui/view/graph-editor/src/component/edge.rs:743:5

- *rectangles(6)*
  - (node shadow and selection) app/gui/view/graph-editor/src/component/node.rs:129:5
  - (node bg) app/gui/view/graph-editor/src/component/node.rs:110:5
  - (drag area) app/gui/view/graph-editor/src/component/node.rs:190:5
  - (input port hover) app/gui/view/graph-editor/src/component/node/input/port.rs:34:5
  - (input port visible part) app/gui/view/graph-editor/src/component/node/input/port.rs:60:5
  - (hover) app/gui/view/graph-editor/src/component/node/action_bar.rs:40:5

- *output port (1)*
  - (output port shape) app/gui/view/graph-editor/src/component/node/output/port.rs:175:5

- *icons (1)*
  - (eye icon) app/gui/view/graph-editor/src/component/node/action_bar/icon.rs:15:5

- *text (1)*
  - lib/rust/ensogl/component/text/src/font/glyph.rs:100:5
```

As previously, there are many shapes that can be unified and drawn in the batch way. 

### Scene with nodes and Component Browser (+64 draw calls, total of 98 draw calls)

I did not dig deep enough to understand it, but it is really bad. 64 draw calls just to display the searcher indicate something really broken under the hood.

## Lowering the draw call count, idea 1
The initial proposal involves optimizing the arrangement of shapes in the layers and implementing a specific "box" shape that can be utilized in various instances where rectangular-like shapes are defined, such as node shapes, backgrounds, and even rounded connections, as they comprise a portion of an empty rectangle with a border. I created a breakdown of how this solution might work. 

**To sum it up, using these optimizations, we can get to:**
- **17 - 19 draw calls, no searcher, no notifications**
- **34 - 38 draw calls with searcher**

Which means, we could shave off 60 draw calls from the current state. That means almost 3x improvement. In this solution, we could use the following layers layout and shapes batching:

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/1623053/226239164-a100d3ae-6dd3-4a7c-bf68-e3e96ea2e718.png">

## Lowering the draw call count, idea 2
However, a significantly superior method for optimizing the quantity of draw calls exists. At present, element sorting is only possible by layers (with each layer being a distinct set of draw calls) and by symbol ordering within a layer. However, instance ordering per single symbol can also be implemented, albeit at a slightly higher cost (requiring the reordering of elements in a vector on both CPU and GPU sides). Nevertheless, as the reordering would only be executed when adding or removing elements, the number of draw calls per frame during regular usage could be substantially reduced. For example, the "box" component could be employed to draw edges and nodes in a single draw call instead of three, as previously illustrated. As previously, I created a breakdown of how this solution might work. 

**To sum it up, using these optimizations, we can get to:**
- **8 - 11 draw calls, no searcher, no notifications**
- **14 - 17 draw calls with searcher**

Which is 2x as good as the previous solution. It means, we could shave off 81 draw calls out of 98 of the current solution. That means almost 6x improvement. In this solution, we could use the following layers layout and shapes batching:

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/1623053/226239801-1f681e0d-404d-48e7-a320-c552ece9baa2.png">

## Lowering the draw call count, idea 3
This represents a significant departure from our current rendering approach, and its potential benefits are uncertain. However, it is worth discussing. Presently, we utilize SDF-based shapes to achieve anti-aliasing, which produces optimal quality. However, this technique precludes the use of depth-pass, as it does not support anti-aliasing in the same way that we do. It is conceivable to output non-anti-aliased pixels from our SDF-shaders (this will not enhance the speed of our shaders), and then employ WebGL antialiasing instead. This would enable us to render all texts, icons, boxes, etc., with just 4-5 draw calls, even when boxes are positioned above or below certain texts. As previously, I created a breakdown of how this solution might work. 

**To sum it up, using these optimizations, we can get to:**
- **4 - 5 draw calls (triangles, boxes, texts, icons) WITH searcher, but with a WAY lower quality (see description below).**

Which is 4x as good as the previous solution. There are though several issues with this solution:
- Antialias in WebGL is a request, not a flag, which means that it can be disabled even if we request it.
- The final image quality will be lower, which will be especially visible with small glyphs.
- The default MSAA is set to 4x4, but it seems there [on some devices Chrome uses 8x8 now](https://bugs.chromium.org/p/chromium/issues/detail?id=730303). 

It means that although we can drastically lower the amount of draw calls, we will end up at [worse image quality](https://www.shadertoy.com/view/4dGXW1) (especially with text). In order to increase the quality we could use "true supersampling" (rendering higher resolution and down-sampling it later), but it would require A LOT more shader calls. Instead, we could theoretically rely on MSAA (supersampling depth buffer only), but it would not work with SDF-based shapes, as they would need to write to `gl_FragDepth`, which basically transforms MSAA to "true, slow supersampling", as it needs to evaluate fragment shader on every pixel. In this scenario, the text would need to be handled differently as well, for example by switching to rendering fonts using HTML canvas, and uploading glyphs to the WebGL texture. This will give us several benefits, including true ClearType rendering and support for emoji. To learn more about supersampling and MSAA, see [here](https://www.google.com/search?client=safari&rls=en&q=learnopnegl+antialiasing&ie=UTF-8&oe=UTF-8) and [this](https://mynameismjp.wordpress.com/2012/10/24/msaa-overview/).

Here is a demo scene in JSFiddle that does not work yet (the SDF shape is not anti-aliased, but I'm not sure why), but it is a good starting point to investigate this technique. The code can be found [here](https://jsfiddle.net/q47ch2ng/5/). Please note that if you are not running it on high-DPI, you should change the line `<canvas id="canvas" width="400" height="400" style="border: none; width: 200px; height: 200px"></canvas>` to `<canvas id="canvas" width="200" height="200" style="border: none; width: 200px; height: 200px"></canvas>`.

<img width="1045" alt="image" src="https://user-images.githubusercontent.com/1623053/226248916-d07c89d8-f2c4-499b-aeec-8e7904f40f29.png">

To sum this up, we have 2 options here:
1. Using non-SDF based shapes (polygon shapes), approx 4 draw calls, textured fonts, and MSAA. This should give us way lower quality of rounded shapes, but should be really fast.
2. Using SDF-based shapes, with true supersampling (by using `gl_FragDepth` in frag shaders), but this will just eval frag shaders 4x4 or 8x8 per pixel, which even with 4 draw calls will equal to 16x4 = 64 or 64x4 = 256 draw calls, so solution 2 will be faster here.

<br/>

# Removing "GPU memory leaks"

As written earlier, we can currently observe that after hiding the component browser, the amount of draw calls per frame remains high. This means, that we are calling draw calls unnecessarily. It is very important for us to be able to add and remove draw calls as results of some events (e.g. adding blinking cursor when node is being edited), but the draw calls should be removed as soon as the object disappears from the scene.

<br/>

# Optimizing VAO usage
I am not sure how it works right now, but we should check if we are not sending too much data on every frame to the GPU. We are using Vertex Array Objects (VAOs) under the hood, and we should not need to update the bound attributes until they change. I'm sure we are not updating uniforms, but I'm not sure whether we update attributes. This needs to be checked, as indicated in [this article](https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices#avoid_changing_vao_attachments_vertexattribpointer_disableenablevertexattribarray).

<br/>

# Other optimizations
We should check in detail articles about optimizing WebGL in order to be sure we are not missing something obvious.

**Comment by farmaazon** [comment]
The summary of number of draw calls seems too optimistic for me. I listed missing items for Idea 1, but most of them propagate to Idea 2 as well.

* You cannot draw Component Browser breadcrumbs and entries elements (label/icon etc.) with a single draw call, as they are in separate layers. They are in separate layers because they have different masks. That adds additional 3 draw calls
* I don't see a draw calls for "special mask-selection". I see "Selected text (masked)" but we actually render the grid view a second time to display all re-colored things (backgrounds headers also could be selected, etc.). Definitely more than 1 draw call, rather 5 (bg + icons + text + header bg + header text). 
* Masks for CB entry list and breadcrumbs also needs to be rendered: additional 2 draw calls.
* The "invisible rectangles" set up for catching mouse events (known as "io_rects") are missing entirely. CB make them for entries, headers (both x2 to include also "selected" version), and for breadcrumbs. This is 5 draw calls, as each mentioned element is in a separate layer.
* Draw calls for scroll bars are missing. Additional 3 draw calls (background, track and io_rect). Again they are in a separate layer, as they are masked but above "selected grid".

There is also another idea:

## Idea 1.5: Masking system not requiring making separate layers

We could cut off the separate draw calls for CB breadcrumbs by doing masking in the shape shaders; we could allow for a single rounded-corner-rect mask for every shape, and the mask position and parameters could be propagated through the display object hierarchy (as it is currently with bboxes and positions).

Still, the "selected component list" require a separate layer, so it still would not have a tremendous effect.

**Comment by wdanilo** [comment]
@farmaazon I believe that some of your points are indeed missing from solution 1, but should be already covered in solution 2. We should have a chat about it and fix the description I prepared.

Regarding scroll-bars, I did not list them, the same was as I did not list e.g. blinking cursor, as these draw calls should be there ONLY when needed. And sure, we will have additional draw calls in GUI, but I'm trying to describe here a "static state" of GUI.

Regarding Idea 1.5, this is a good point (and it is applicable to idea 2 as well).

**Comment by farmaazon** [comment]
See also Greg's comment in a duplicated task (https://github.com/enso-org/enso/issues/6623#issuecomment-1541518518 ):
> yes, it happens many times. In some scenarios, it's a desired behavior - but mostly it renders the preview useless. How can we fix that? So the user will know that adding what he/she has (not) selected in the CB is the new output of the node computation result. Making the selection of component a conscious decision (requiring user action (mouse movement, arrow key press)) to reevaluate the previously correct code into an error state with new results served to the preview window.

So the options are: 
1. A special entry (as in my comment above)
2. Not selecting any entry when user closes bracket (as in Greg's comment).

**Comment by farmaazon** [comment]
The app performance was agreed to be sufficient for now, so I lower the priority.

**Comment by somebody1234** [comment]
@wdanilo I think this is mostly no longer relevant, as GUI2 is no longer using WebGL. However, the issue has been raised that large `backdrop-filter: blur` (which are present both in GUI2 and the dashboard) are expensive, especially without a GPU (as they more or less require sampling a circle of the specified radius, for each pixel)

On second thought though, it's possible that browsers only sample a few points - this would explain the subtle flickering behavior when you move a colorful node around, under an element with `backdrop-filter: blur` - so it may be better to make sure that this *is* indeed an issue on legacy hardware

**Comment by wdanilo** [comment]
We can disable some nice styling if we discover performance drop. Also, I believe that browsers are not doing real blur and are sampling only a few pixels, especially with big blur radius. I've checked that on website. When an element is being scrolled below blurred background it is flickering as it is not sampling all pixels. If the samples pixel actually hits text (black) a big area is being displayed as blurred. So this might not be a performance concern.

**Comment by farmaazon** [comment]
Closing as not relevant to GUI2
