### ISSUE TITLE
Allow Node.js to be used through Node version managers

### ISSUE THREAD

**Issue by Procrat** [enso-org/enso#6008]
### Discord username

Stijn#6455

### How important is this feature to you?

0 – Not too important

### Describe the idea you'd like to see implemented.

If we put a `.node-version` in the root of the repo, Node.js version managers like [fnm](https://github.com/Schniz/fnm), [nvm](https://github.com/nvm-sh/nvm), [nvs](https://github.com/jasongin/nvs), [n](https://github.com/tj/n), [nave](https://github.com/isaacs/nave), [nodeenv](https://github.com/ekalinin/nodeenv), [nodist](https://github.com/nullivex/nodist), ... automatically select the right Node version. At the moment, it either needs to be set manually or the system-installed version is used.

I can make a PR with it, but the version number would be duplicated in `build-config.yaml`, unless the build script were to look for the version number.

### Is your feature request related to a problem?

The system-installed Node version is rarely the exact one pinned by Enso. This results in one more hurdle to cross for new people to build Enso for the first time.

### Would you be willing to help us implement this feature?

Yes

**Comment by wdanilo** [comment]
I like it. Didn't know that you can use this file to hint these tools with the version. Please create PR with it. Also, take a look at the build script, if you'd be able to fix it in 15-30 mins, include it in your PR. If not, add a note there that it needs to be fixed :)

**Comment by mwu-tow** [comment]
It's no problem for build script to take the version from the file. We do a similar for retrieving the GraalVM version from build.sbt. 
If anyone needs some help with this, please ping me.

@Procrat By the way if there are node version managers that:
* work across Windows, Linux, and macOS;
* do not not require root privileges.

Then it might be worth updating documentation and guiding users to it — the fewer platform-specific setup instructions and more out-of-the-box just working, the better.
