### ISSUE TITLE
`-debug` option and `debug.enable-spector` are incompatible

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#6022]
The option to run Enso with SpectorJS is now usable after #5941:
`./dist/ide/linux-unpacked/enso -debug.enable-spector`

However, option-parsing seems to fail when the option is used together with `-debug`:
`./dist/ide/linux-unpacked/enso -debug -debug.enable-spector`

![image](https://user-images.githubusercontent.com/1047859/226531075-f7459a4e-dcaf-4bdf-8ba1-c62af80f77d1.png)

It's not immediately obvious why this would happen. `-debug` works in combination with other options in the `debug` group, e.g. `-debug.verbose`.

**Comment by wdanilo** [comment]
Hmmm, it seems that the argument passed to the URL is `enableSpector` instead of `debug.enableSpector`, as the error is shown in the option parser in content, not in the cmd yards version.

**Comment by vitvakatu** [comment]
@kazcw please assign anybody to this issue or add a `triage` label.

**Comment by kazcw** [comment]
> Hmmm, it seems that the argument passed to the URL is `enableSpector` instead of `debug.enableSpector`, as the error is shown in the option parser in content, not in the cmd yards version.

The strange thing is that the `-debug.enable-spector` option works when the `-debug` option is not also passed, so I think it must have to do with the option group logic

**Comment by farmaazon** [comment]
No longer reproducible. In fact, I think we don't even read these options in GUI2.
