### ISSUE TITLE
WebGL errors logged when using SpectorJS

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#6023]
The application now appears to work correctly with SpectorJS (#5941), however when the application is run with SpectorJS WebGL errors appear in the console:
![image](https://user-images.githubusercontent.com/1047859/226531491-86c41320-7228-486a-bdfe-ceae42b543db.png)

This likely affects analysis performed with SpectorJS.

**Comment by wdanilo** [comment]
Should we report them in the Spector Github Issue tracker? It looks like we don't have these errors without Spector, right?

**Comment by kazcw** [comment]
I think the bug must be in Spector. I'll have a quick look at whether I can narrow it down to something easily reproducible, and then report it over there.

**Comment by wdanilo** [comment]
Probably you don't need to narrow it down. Spector authors know it has issues, especially on systems that do not base on Babylon.js. They are really fast and handy with discovering / understanding the errors if they have live version of the environment to test things out. So, don't spend time on narrowing it down :) Instead, talk with @PabloBuchu so he could expose the newest version of Enso on a link that we could post in the issue on Spector's Issue Board (as I did here: https://github.com/BabylonJS/Spector.js/issues/252).

**Comment by sebavan** [comment]
Yup would be great to have a repro but I guess this one might already been fixed :-)

Could you try the latest version from a local install ?

I ll see to deploy if it is all good.

**Comment by kazcw** [comment]
> Yup would be great to have a repro but I guess this one might already been fixed :-)
> 
> Could you try the latest version from a local install ?
> 
> I ll see to deploy if it is all good.

That was fast :smile:. Yeah, the `PredefinedColorSpace` error is fixed in current `master`.

The `GL_INVALID_OPERATION` error is still occurring, though. We'll set up a page that reproduces it.

**Comment by wdanilo** [comment]
@sebavan thanks so much for helping us here so fast!

**Comment by PabloBuchu** [comment]
Hi! In case you would still need a playground here is the newest one (2023.1.1-nightly.2023.3.23):

http://ensocdn-playground.s3-website-eu-west-1.amazonaws.com/

<blockquote></blockquote>

**Comment by wdanilo** [comment]
@sebavan would you be able to take a look at the link provided above? Do you prefer me to report it on Spector.js Github instead? :)

**Comment by sebavan** [comment]
The invalid format is not an issue, just means we have an unreadable texture so I can not capture the data. It should not break the rest of the experience.

I can not really try cause: 

![image](https://user-images.githubusercontent.com/16655165/228068887-c900149c-346a-4350-acb6-72403270f06b.png)

**Comment by wdanilo** [comment]
@sebavan oh, sorry about that. It seems the backend is not responding there. You can run the interface without backend with the following link: http://ensocdn-playground.s3-website-eu-west-1.amazonaws.com/?startup.entry=interface

Regarding the unreadable texture - do you know why it could happen? We are not using any special texture types there, so all of them should be capturable I think. 

<blockquote></blockquote>

**Comment by farmaazon** [comment]
Closing, as we don't use WebGL in GUI2.
