### ISSUE TITLE
No error and no visualization when using `Standard.Base.Data.Json.parse`

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#6024]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I'm trying to create such a graph. There is no error nor visualization:

<img width="399" alt="image" src="https://user-images.githubusercontent.com/1623053/226548030-8234c142-fc57-448e-aa6a-6e9f656e57c0.png">

### Expected behaviour

Either error or visualization. dead sd and asks fast and asd

### How we can reproduce it?

Create the graph from screenshot.

### Enso Version

newest 

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by jdunkerley** [comment]
`json_parse` function is an internal one not marked by `PRIVATE` (will fix).
The JSON format is incorrect and does error. Once fixed and using `Json.parse` works as expected.


![Image](https://user-images.githubusercontent.com/4699705/226587131-e4490854-44d6-49af-a255-323256017632.png)

Will tag the private functions.

**Comment by wdanilo** [comment]
Great, however, I still don't understand the behavior I got there. How a function could be evaluated not producing visualization nor error? I understand it was internal function, but still, something should be visible, right?

**Comment by jdunkerley** [comment]
This is a JavaScript function. 

As the JSON text was invalid the function will have thrown an error. 

I'm guessing the engine/language server swallowed it - which shouldn't be the case. I will check and see if there is a panic being lost and raise with the engine team if so.

**Comment by jdunkerley** [comment]
Having resolved the import issue so we don't get the module and type clash it is now returning the error cleanly.
![image](https://user-images.githubusercontent.com/4699705/226885910-ac66880f-5222-4141-832c-716d96481574.png)

Once the code has been merged this should be resolved.
