### ISSUE TITLE
Component browser suggests things that throw error and the error does not make much sense ()

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#6025]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The component browser hints things that do not work.

### Expected behaviour

Component browser should hint things that do work. It's OK if parameters are missing, but here we got scoping error.

### How we can reproduce it?

1. Open Component Browser.
2. Type "json"
3. Choose "json parse"

### Screenshots or screencasts

<img width="399" alt="image" src="https://user-images.githubusercontent.com/1623053/226548908-b4815227-e454-406e-a04a-491e5438b39d.png">

<img width="399" alt="image" src="https://user-images.githubusercontent.com/1623053/226548954-4c2e06fd-d0d2-42fd-b5eb-57812334b7dd.png">

### Enso Version

newest

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
For me, the error is clear: we imported two `Json` names - one for type, one for module.

Perhaps one of them is mass-imported in default imports, the second is added by us (which you should see in the code editor).

There are two ways of fixing this:
1. Implementing https://github.com/enso-org/enso/issues/5353 - this task is not planned yet, and it gives results which may be considered undesirable, e.g. in the example CB will create `Standard.Base.Data.Json.json_parse`.
2. Import only type name into the scope, and convert all `Json` module method to static method of `Json` type. This way we won't encourage CB to put imports with name clashes. @jdunkerley is it possible and acceptable?

**Comment by jdunkerley** [comment]
We don't export the module into scope by default. There were a few functions that are missing PRIVATE (will be fixed within the hour).

**Comment by wdanilo** [comment]
Yeah, importing with name clashes is really bad :( I understand that we don't have time to fix it now though. Thanks @farmaazon for info. Thanks @jdunkerley for the fixes!

**Comment by farmaazon** [comment]
I guess https://github.com/enso-org/enso/pull/6032 will fix this particular reproduction scenario.

**Comment by jdunkerley** [comment]
Yes - there is one issue left to investigate that the JS thrown error vanished somewhere in the stack.

**Comment by vitvakatu** [comment]
Fixed on the current develop
