### ISSUE TITLE
`Vector_Editor` component allowing element adding.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#6037]
What exactly may be added and where should be configured by widget's FRP.

If a user moves the mouse cursor in the area side to any element, a pin-shaped (+) icon appears. Also, there should be an option of having always visible circle icon after the last element instead of mentioned pin-shaped (+).

Clicking on circle or the area between elements should put an empty `_` element to the vector at the right place.

**Comment by sylwiabr** [comment]
@wdanilo I think it was started? Can you update the status?

**Comment by wdanilo** [comment]
It was not started yet. I started with element re-ordering. I will add element adding very soon.
