### ISSUE TITLE
Second version of enable/disable output icon

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#6042]
We need a second version for the already implemented (#5928) icon, see https://github.com/orgs/enso-org/discussions/5964#discussioncomment-5386969

It should look like the already existing one, but without the stroke that crosses it:

![](https://user-images.githubusercontent.com/1623053/226760408-b15370c7-f15d-4414-ad96-43c765ca8b56.png)

### QA Acceptance Criteria

The icon above is visible on the `icons` demo scene.

**Comment by Procrat** [comment]
@wdanilo: Is the cut-out in the bottom left intentional? Just double-checking because we weren't sure and I couldn't find it in the Figma design.

**Comment by wdanilo** [comment]
> @wdanilo: Is the cut-out in the bottom left intentional? Just double-checking because we weren't sure and I couldn't find it in the Figma design.

good question. It is accidental, should be removed. Thanks so much for catching it!
(I mean, in Figma I have the icon with this cutout there, but you are right, from the visual standpoint, there should be no cutout).

**Comment by Procrat** [comment]
Great, good to know. I'll get rid of it in the PR.

**Comment by wdanilo** [comment]
Thanks again for catching it!
