### ISSUE TITLE
Suggestions for `Text`, `Integer`, `Decimal` are hard to discover

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6046]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I am opening searcher with the node containing text or numbers selected, I am not getting the suggestions for the appropriate type, but as a part of `Base.Data`

### Expected behaviour

User should see them as the most optimal suggestions.

### Screenshots or screencasts

<img width="619" alt="image" src="https://user-images.githubusercontent.com/12892578/226929966-97b10f05-879c-47cc-aafb-3dc59913af4a.png">
<img width="675" alt="image" src="https://user-images.githubusercontent.com/12892578/226930193-2d7687b4-c0d0-4677-9410-4617a921289c.png">

### Enso Version

Nightly 22.03.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
This definitely is not a bug. Such an issue was never requested.

Also, it requires discussion: I don't know on what basis CB should deduce what group should be suggested first. This time it's just `Base.Data`, but what is a general rule? What if the type's methods are spread across many modules? What if some suggestions in favorites matches?

@wdanilo @jdunkerley and others?

**Comment by wdanilo** [comment]
@farmaazon you are right, this needs discussions and ideas. But Sylwia request is valid as well. Currently, component browser does not show hints that are most useful. We've discovered it after using it for a while. I think we should have a brainstorming call, maybe on Monday?

**Comment by farmaazon** [comment]
Next steps to improve CB were discussed, and will be implemented in several tasks of another epic.
