### ISSUE TITLE
Component Browser is suggesting Visualization Helpers for many types (i.e. `Text`)

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6047]
<img width="1035" alt="image" src="https://user-images.githubusercontent.com/12892578/226931365-54779c87-04e1-423b-bde0-488ce064779b.png">

**Comment by farmaazon** [comment]
I assume this is a problem? Because, well, they are indeed defined in Stdlib and indeed can be called on any type.

Shall they be PRIVATE?

**Comment by sylwiabr** [comment]
The end user probably would never need to use them so they are just polluting the CB

**Comment by vitvakatu** [comment]
I assume this is a matter of PRIVATE tags, so assigning the Libs team.
