### ISSUE TITLE
Visualization preview should not be visible when it's causing an error

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6049]
### How important is this feature to you?

3 – Lack of it makes using Enso slightly harder

### Describe the idea you'd like to see implemented.

Right now we have a lot of errors when we are selecting functions in the Component Browser (during edition). It is caused by evaluation of the function to show visualization preview - if the selected function is lacking i.e. default parameters it throws an error. We should not show visualization preview in such cases.

### Would you be willing to help us implement this feature?

No

**Comment by vitvakatu** [comment]
@sylwiabr I don't quite understand. When the previewed entry causes an error, we don't display a visualization preview, but rather display the error. In the code, it is called `error preview`. Does it mean we should not show errors while the Component Browser is opened?

**Comment by sylwiabr** [comment]
@vitvakatu yes, we don't want to show errors when the CB is opened

**Comment by farmaazon** [comment]
There is a broader problem with the erroneous preview: even if we hide the errors on the edited node, the error will still propagate through graph. See https://github.com/orgs/enso-org/discussions/5856

<blockquote><img src="https://opengraph.githubassets.com/54ffb7524feae62ddc4b421bfb3dd15a245165cf9fac8173957f7f788589edad/orgs/enso-org/discussions/5856" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/orgs/enso-org/discussions/5856">How to improve Visualization Previews · enso-org · Discussion #5856</a></strong></div><div>So, the Component Browser's Visualization Preview was implemented some time ago, and roughly works as described in the design. But once the CB was used by various people, a few UX issues emerged: A...</div></blockquote>

**Comment by GregoryTravis** [comment]
In my case (https://github.com/enso-org/enso/issues/6114), it shows an error even after I have corrected the error.

**Comment by farmaazon** [comment]
> In my case (#6114), it shows an error even after I have corrected the error.

I guess it's because the last selected suggestion (before the Component turns blank) would make the error I get.

**Comment by farmaazon** [comment]
No longer needed in new GUI, where previews are handled better.
