### ISSUE TITLE
Drop down values for `take` on `Text` should be shortened 

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6052]
### How important is this feature to you?

2 – Somewhat important, but I can live without it

### Describe the idea you'd like to see implemented.

We a shortening drop down values for `take` on a `Vector` but for `Text` we are displaying FQN. It's hard to read (specially because longer names are cut).
<img width="504" alt="image" src="https://user-images.githubusercontent.com/12892578/226979470-be42ed6b-cb00-489f-8619-de08b43f33a9.png">

### Would you be willing to help us implement this feature?

No

**Comment by vitvakatu** [comment]
@Frizi am I correct that it is a bug? If I understand the idea correctly, every access chain should be shortened, so on the screenshot, even the `Index_Sub_Range` values should be much shorter.

**Comment by farmaazon** [comment]
@Frizi bump
