### ISSUE TITLE
Rendering artifacts in IDE

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6061]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Recently I noticed when doing QA/demo with @jdunkerley he has rendering artifacts in IDE (weird extra underscores when rendering `t` letter). The same I saw today on @JaroslavTulach screenshots. I can see Jaroslav was working in Chrome, James was working with Electron app. In James case I know it was Windows.

### Expected behaviour

Nicely rendered text

### Screenshots or screencasts

screen from @JaroslavTulach 
![image](https://user-images.githubusercontent.com/12892578/227228830-d6736528-4042-41dd-bc0f-d61237d9f3eb.png)
screen from @jdunkerley 
<img width="232" alt="image" src="https://user-images.githubusercontent.com/12892578/227229388-595fffbd-8a6e-470f-8c1c-072d7869196d.png">

### Enso Version

Nightly 20.03

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

Standalone

### Operating System

Windows

**Comment by wdanilo** [comment]
We know about it. It is cause by glyph shaders and we need to investigate why. Probably @farmaazon would be the best person to take a look there as he was writing the shaders for glyphs.

**Comment by jdunkerley** [comment]
This has been significantly improved and we don't see anymore.
