### ISSUE TITLE
Fix treatment of `WithWarnings` in builtin method annotation processor

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6070]
`org.enso.interpreter.dsl.MethodProcessor` generates code for every builtin method in such a way that it removes all the warnings from all the arguments, except for `self`, and then reattaches these gathered warnings to the result. It does that by checking `if (arg instanceof WithWarnings)` which is incorrect, it should be replaced by `WarningsLibrary.hasWarnings(arg)`. Moreover, the lack of warnings removal from the `self` argument is suspicious, since you have to take care of the warnings in the builtin method manually.

This might cause problems especially for vectors, for which, if one of the elements has a warning attached, it is propagated to the whole vector and sometimes duplicated across other elements.

```[tasklist]
### Tasks
- [ ] Replace `instanceof WithWarnings` checks by `WarningsLibrary.hasWarnings(arg)`.
- [x] Investigate warning removal from `self` argument.
```

Related:
- #3248
- #3938

**Comment by hubertp** [comment]
Regarding warnings on self. I think that part will have to stay in order to be able to do dispatch on Warning correctly. This was for example needed for https://github.com/enso-org/enso/pull/6176.

**Comment by Akirathan** [comment]
Closing this as not an issue:

Stripping of warnings from the `self` argument is controlled by [AcceptsWarning](https://github.com/enso-org/enso/blob/4653bfeeabe5daee28b51caa2919de4c4adc01a0/lib/scala/interpreter-dsl/src/main/java/org/enso/interpreter/dsl/AcceptsWarning.java) annotation.

Checking for warnings via `instanceof` is just fine. Passing messages via `WarningsLibrary` has unnecessary overhead.
