### ISSUE TITLE
`Boolean.False == False` is false

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6076]
![image](https://user-images.githubusercontent.com/4699705/227727792-52dc7d85-0273-4a5c-b85e-958fa3ed9319.png)

The dropdown puts in `Boolean.True` and `Boolean.False`. There is a problem that `Boolean.False` != `False`.

**Comment by jdunkerley** [comment]
Possibly related:
```
[warn] [2023-03-25T15:55:24.566Z] [enso] Execution of function main failed (class org.enso.interpreter.runtime.callable.atom.BoxingAtom cannot be cast to class java.lang.Boolean (org.enso.interpreter.runtime.callable.atom.BoxingAtom is in unnamed module of loader com.oracle.graalvm.locator.GraalVMLocator$GuestLangToolsLoader @7ac9af2a; java.lang.Boolean is in module java.base of loader 'bootstrap')).
java.lang.ClassCastException: Some(class org.enso.interpreter.runtime.callable.atom.BoxingAtom cannot be cast to class java.lang.Boolean (org.enso.interpreter.runtime.callable.atom.BoxingAtom is in unnamed module of loader com.oracle.graalvm.locator.GraalVMLocator$GuestLangToolsLoader @7ac9af2a; java.lang.Boolean is in module java.base of loader 'bootstrap'))
```

**Comment by JaroslavTulach** [comment]
Thanks @Akirathan for taking a look.

**Comment by Akirathan** [comment]
> Possibly related:

I guess you mean exactly this:
```
> False.not
>>> true
> Boolean.False.not
Evaluation failed with: class org.enso.interpreter.runtime.callable.atom.BoxingAtom cannot be cast to class java.lang.Boolean (org.enso.interpreter.runtime.callable.atom.BoxingAtom is in unnamed module of loader com.oracle.graalvm.locator.GraalVMLocator$GuestLangToolsLoader @27912e3; java.lang.Boolean is in module java.base of loader 'bootstrap')
```

Does not seem related at first sight, because that is failing due to the casting done through invocation. Moreover, I tried running that snippet on engine from 12/2022, and it was still failing, so this issue is an old one.

```
> Boolean.False == False
>>> false
```
I will fix that, should be pretty much straightforward. The problem is that `Boolean.False` is an atom, whereas `False` is a literal value.

**Comment by JaroslavTulach** [comment]
> The problem is that Boolean.False is an atom, whereas False is a literal value.

The best fix is to make sure `Boolean.False` also resolves to a literal value, if possible.
