### ISSUE TITLE
Rendering of default font returns incorrect height or baseline

### ISSUE THREAD

**Issue by Procrat** [enso-org/enso#6086]
### Discord username

Stijn#6455

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When the default font (M PLUS P1) is rendered with a `Text` component, the height or baseline seems off, as you can see here:

![text](https://user-images.githubusercontent.com/607786/227939762-5fc5675d-6ba8-44cb-96ec-a7bb7ef7a4e3.png)

The green backdrop is taking over the width and height that the text components reports. Note that the baseline is rather low, compared the reported height. This has weird consequences such as text in tooltips being placed a bit lower than expected. In other places where text is used in the interface, either a different font is used (like in nodes or the status bar) or an offset is used instead.

For the person looking into this:
- As far as I can tell, this only happens with the M PLUS P1 font; not with the others.
- Two FRP events occur reporting the height. The first one returns a height of 3.84px, based on a baseline of 0.0. The second one returns a height of 16.84px, based on a baseline of -13.0. In both cases these font metrics are used:
  - ascender: 12.9
  - descender: -3.84
  - gap: 1.0799999
- Since font rendering doesn't seem core to the mission of Enso and issues like these distract us from working on features that help us work towards product-market fit, it might be worth investigating whether there are existing font rendering engine we can leverage. 

### Expected behaviour

I expect the text to be a bit more vertically centered, relative to the reported height.

### How we can reproduce it?

Here's the minimal example that produced the screenshot above:
```rust
use ensogl_core::display::shape::*;
use ensogl_core::prelude::*;

use ensogl_core::application::Application;
use ensogl_core::display::navigation::navigator::Navigator;
use ensogl_core::display::object::layout::Size;
use ensogl_text::Text;
use ensogl_text_msdf::run_once_initialized;


ensogl_core::define_endpoints! {}

mod backdrop {
    use super::*;

    ensogl_core::shape! {
        (style: Style, bg_color: Vector4) {
            let width      = Var::<Pixels>::from("input_size.x");
            let height     = Var::<Pixels>::from("input_size.y");
            let radius     = &height / 2.0;
            let base_shape = Rect((&width, &height));
            let shape      = base_shape.fill(Var::<color::Rgba>::from(bg_color.clone()));
            shape.into()
        }
    }
}


#[entry_point]
pub fn main() {
    run_once_initialized(|| {
        init(Application::new("root"));
    });
}

fn init(app: Application) {
    let scene = &app.display.default_scene;
    let navigator = Navigator::new(scene, &scene.camera());

    let text = app.new_view::<Text>();
    text.set_font(ensogl_text::font::DEFAULT_FONT);
    scene.add_child(&text);

    let backdrop = backdrop::View::new();
    backdrop.bg_color.set(Vector4(0.0, 255.0, 0.0, 0.1));
    scene.add_child(&backdrop);

    let model = Model { backdrop };

    let frp = Frp::new();
    let network = &frp.network;
    frp::extend! { network
        eval text.frp.output.width ((width) {
            model.set_width(*width);
        });
        eval text.height ((height) {
            model.set_height(*height);
        });
    }

    text.set_content("abcdefghijkl");

    mem::forget(model);
    mem::forget(frp);
    mem::forget(text);
    mem::forget(navigator);
    mem::forget(app);
}

#[derive(Debug, Clone, CloneRef)]
struct Model {
    backdrop: backdrop::View,
}

impl Model {
    fn set_width(&self, width: f32) {
        error!("Width = {}", width);
        self.backdrop.set_x(width / 2.0);
        self.backdrop.set_size_x(Size::from(width));
    }

    fn set_height(&self, height: f32) {
        error!("Height = {}", height);
        self.backdrop.set_y(-height / 2.0);
        self.backdrop.set_size_y(Size::from(height));
    }
}
```

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by wdanilo** [comment]
1. I don't see anything bad with the screenshot provided. The free space above letters is the same as below baseline, so what's wrong there? 
2. We are not using other fonts in other places in the GUI.
3. `it might be worth investigating whether there are existing font rendering engine we can leverage.` - we are using `rustybuzz` for font shaping, this is a well working library. Also, I do not know about any webgl-text library in Rust that produces as good results as we have right now.

**Comment by farmaazon** [comment]
Ad 2. We do use deja-vu-mono in many places still.

**Comment by wdanilo** [comment]
> Ad 2. We do use deja-vu-mono in many places still.

OH! Didn't know about it.

**Comment by farmaazon** [comment]
> I don't see anything bad with the screenshot provided. The free space above letters is the same as below baseline, so what's wrong there?

@Procrat please answer the first point, otherwise I will close the issue.

**Comment by Procrat** [comment]
> > I don't see anything bad with the screenshot provided. The free space above letters is the same as below baseline, so what's wrong there?
> 
> @Procrat please answer the first point, otherwise I will close the issue.

It's probably true that the free space above the letters is the same as below the baseline. Like I said, it looks a bit weird to me that the x-height is not centred relative to the height of `Text` element. What I think I forgot to mention initially, is that I was looking at this from the context of single-line UI component (specifically tooltips), as opposed to multi-line text. A line gap makes sense for multi-line text.

We saw this recently as well with those grid view entries that had their line height set to the default of 1.2. When text is off-center like this for single-line elements, the usual way to fix it in CSS is with either `vertical-align: center` or `line-height: 1`. Not sure what the best approach is here.

In any case, if I'm the only one who thinks it's off, feel free to close it. I'm not bothered by it; I merely identified the underlying issues when someone else mentioned that the text in tooltips was not centred.

**Comment by wdanilo** [comment]
Ok, @Procrat is right, there is some offset there. If we compare what we see for example on MacOS in Safari tabs:

<img width="348" alt="image" src="https://user-images.githubusercontent.com/1623053/235951909-34b05741-514d-4dc3-ac58-3c373ec64012.png">

With @Procrat's screenshot:

<img width="1196" alt="image" src="https://user-images.githubusercontent.com/1623053/235952355-825b456c-a3e5-4fc0-8566-a90db2dfb12b.png">

It's clear we have a small, unintended vertical offset there.
