### ISSUE TITLE
Creating a new node sometimes places it at a random location

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6088]
### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Most of the time creating a new node, by creating a new tab, places it at a location where the current mouse pointer is. Except... when it doesn't. See screenshot.
It's not clear what governs the rules for that and forces the user to move around the new node.

### Expected behaviour

Should always create the new node under the mouse pointer.

### Screenshots or screencasts

Position 1. Where the mouse pointer was.
Position 2. Where the node was created and the mouse pointer was moved.
![Screenshot from 2023-03-27 15-01-02](https://user-images.githubusercontent.com/292128/227974030-380bc50b-c624-43db-9a14-fa86e5381a94.png)

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by wdanilo** [comment]
This is known issue, but I can't find it. Our border weights in auto-placing algorithmm are too big, or the auto-placing has bugs.

**Comment by farmaazon** [comment]
@hubertp could you post your project, or screenshot without Component Browser?

**Comment by hubertp** [comment]
HTH
[BookClub_3.zip](https://github.com/enso-org/enso/files/11088190/BookClub_3.zip)

**Comment by farmaazon** [comment]
The project seem to be changed since the screenshot was taken, and I cannot reproduce it the same way.

**Comment by jdunkerley** [comment]
As we no longer auto move nodes, think all fixed.
