### ISSUE TITLE
Random build failure: `✘ [ERROR] Could not resolve "env"`

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#6091]
Sometimes builds (both locally and on CI) randomly fail while bundling JS snippets for WASM with the output like:
```
	cd "/runner/_work/enso/enso/target/ensogl-pack/wasm-pack" && "/usr/local/bin/npx" "--yes" "esbuild" "/runner/_work/enso/enso/target/ensogl-pack/wasm-pack/index.ts" "--format=cjs" "--bundle" "--sourcemap" "--platform=node" "--outfile=/runner/_work/enso/enso/target/ensogl-pack/dist/pkg.js"
	with working directory: /runner/_work/enso/enso/target/ensogl-pack/wasm-pack}: ide_ci::program::command: Spawning.
TRACE ide_ci::program::command: npxℹ️ <START>
TRACE ide_ci::program::command: npx⚠️ <START>
Warning: O ide_ci::program::command: npx⚠️ ▲ [WARNING] "import.meta" is not available with the "cjs" output format and will be empty [empty-import-meta]
 INFO ide_ci::program::command: npx⚠️ 
 INFO ide_ci::program::command: npx⚠️     pkg.js:4146:39:
 INFO ide_ci::program::command: npx⚠️       4146 │         input = new URL('pkg_bg.wasm', import.meta.url);
 INFO ide_ci::program::command: npx⚠️            ╵                                        ~~~~~~~~~~~
 INFO ide_ci::program::command: npx⚠️ 
 INFO ide_ci::program::command: npx⚠️   You need to set the output format to "esm" for "import.meta" to work correctly.
 INFO ide_ci::program::command: npx⚠️ 
Error: NFO ide_ci::program::command: npx⚠️ ✘ [ERROR] Could not resolve "env"
 INFO ide_ci::program::command: npx⚠️ 
 INFO ide_ci::program::command: npx⚠️     pkg.js:16:29:
 INFO ide_ci::program::command: npx⚠️       16 │ import * as __wbg_star3 from 'env';
 INFO ide_ci::program::command: npx⚠️          ╵                              ~~~~~
 INFO ide_ci::program::command: npx⚠️ 
 INFO ide_ci::program::command: npx⚠️   You can mark the path "env" as external to exclude it from the bundle, which will remove this error.
 INFO ide_ci::program::command: npx⚠️ 
```

Full log in the attachment.
[env-log.zip](https://github.com/enso-org/enso/files/11081090/env-log.zip)

**Comment by wdanilo** [comment]
I've seen it multiple times on my end.

**Comment by MichaelMauderer** [comment]
I'm also seeing this on my end. Multiple times today. Solved by doing a `cargo clean`, but quite annoying.

**Comment by MichaelMauderer** [comment]
Note that I am running into this a lot and this is causing a lot of lost time.

**Comment by wdanilo** [comment]
I'm seeing it rarely. Like once a week. @MichaelMauderer @mwu-tow @sylwiabr what should we do with it? It might happen often on some systems, like @MichaelMauderer's one. @MichaelMauderer have you investigated it a little?

**Comment by MichaelMauderer** [comment]
I have not investigated it yet. It does happen daily, but not so often that I stopped to have a more in-depth look.

**Comment by wdanilo** [comment]
When this error happens, please copy the content of `pkg.js` and its location, and paste it here, please. It's runtime generated file and it looks like that this line should not be there. It is not there on my end. It means that sometimes this file might be generated wrongly by warm pack and produce error. I need to see the wrongly generated file though, so ping me when you'll have it. Also, after it happens and you will change code and it works again, please attach the same file from working state here as well, so I could compare them.

**Comment by MichaelMauderer** [comment]
@wdanilo Just happened again. The file is located at `dist/wasm/pkg.js` and this is the [content of the failing file.](https://gist.github.com/MichaelMauderer/065f298f4904492b2c81597abfe3c9aa).
After deleting `dist` the error persists. 
After `cargo clean` and rebuilding, the build works. [This is the working file then](https://gist.github.com/MichaelMauderer/93387a8ac813908977380d36d950c25f).

**Comment by sylwiabr** [comment]
Do we know how we can fix it? Any leads? Estimates? @mwu-tow?

**Comment by somebody1234** [comment]
:/ very odd... both files have the exact same content

**Comment by somebody1234** [comment]
took an embarrassingly long time to find this:

https://github.com/enso-org/enso/blob/66631254107fe9ff1d8e05c09b8b684e4b3fbf10/lib/rust/ensogl/pack/src/lib.rs#L419-L427

but given the esbuild scripts (the ones written in TS) manually silence some errors, maybe the best solution would be to do the same here. either by doing:
- `--log-limit=silent`
- `--log-override:empty-import-meta=silent` (the second diagnostic is an error though, which doesn't have an identifier, so maybe this is the wrong approach)

**Comment by somebody1234** [comment]
i think when the build fails, maybe the file doesn't get output at all, which would explain why both files are identical (since both would be from successful builds)

**Comment by somebody1234** [comment]
in the correct build output, the first line becomes `input = new URL("pkg_bg.wasm", import_meta.url);`. the second disappears as that is ESM syntax, which is not valid when the build works properly (outputs as CJS)

however it should *always* be cjs, because of this flag:
https://github.com/enso-org/enso/blob/66631254107fe9ff1d8e05c09b8b684e4b3fbf10/lib/rust/ensogl/pack/src/lib.rs#L427

and it's not like the directory name could possibly be causing problems with esbuild's parsing of the commandline arguments... especially since the paths (and the entire command in general) should be the same every time

**Comment by mwu-tow** [comment]
@sylwiabr @somebody1234 
This is a very, very old issue. It was here before esbuild and likely even before the build script. I have no idea what this is about.
This might be relevant to a degree: https://github.com/rustwasm/wasm-bindgen/issues/2570 https://github.com/rustwasm/wasm-bindgen/issues/2160

I wonder why this is non-deterministic, though. Likely some race condition.

**Comment by somebody1234** [comment]
this comment seems relevant: <https://github.com/rustwasm/wasm-pack/issues/743#issuecomment-798881356>:
> Amanieu/parking_lot # 269 was the root cause. The workaround for me was to manually pin:
> ```
> parking_lot_core = "=0.8.0"
> ```
it seems like we depend on `parking_lot_core` via `tokio-reactor` but i don't think it's avoidable

one thing the thread *does* say though is this: <https://github.com/rustwasm/wasm-pack/issues/743#issuecomment-1003207803>

> For those using parking_lot you should update to the latest version `0.11.2`. The timer issue, which in some cases caused the missing `env`, has been addressed.

`Cargo.lock` says we're using `0.9.0`, so this might be an option

**Comment by mwu-tow** [comment]
@somebody1234 
Interesting find. We should be able to avoid the `tokio-reactor` dependency; it is outdated and deprecated. From what I see, we pull it in only through the `websocket` dependency. IIRC, we only used it for the parser service client, which should not be needed anymore since we moved to the Rust parser. Please, check if we can get rid of this dependency.

We should remove this dependency by removing the code or switching to a different websocket implementation.

**Comment by mwu-tow** [comment]
Though still, even if the `parking_lot_core` was the source of the problem, I have no idea why it is so random. Still, getting rid of outdated dependencies is always good.

**Comment by wdanilo** [comment]
@MichaelMauderer I can't find in these files the line `import * as __wbg_star3 from 'env';` - are there correct files?

**Comment by MichaelMauderer** [comment]
> @MichaelMauderer I can't find in these files the line `import * as __wbg_star3 from 'env';` - are there correct files?

These are the files that I found last time this happened. But I will double-check whether there are other locations where these appear with different content.

**Comment by Procrat** [comment]
I had this error today. [This](https://github.com/enso-org/enso/files/11230844/target-ensogl-pack.zip) is a zip of the whole `target/ensogl-pack` directory at the time it happened. You can find the `import * as __wbg_star3 from 'env';` line in `wasm-pack/pkg.js` on line 16.

Deleting `target/ensogl-pack` didn't resolve it, but `cargo clean` did, as mentioned before.

The new, working version of `target/ensogl-pack` is too large to upload here apparently, but [here](https://github.com/enso-org/enso/files/11230908/pkg.js.txt) is the new version of `target/ensogl-pack/wasm-pack/pkg.js` (renamed to bypass GitHub filters).

**Comment by Procrat** [comment]
I can't find any usage of the `websocket` dependency, so I think it's safe to remove it. We seem to only be using `web_sys::WebSocket`s.

**Comment by wdanilo** [comment]
> I can't find any usage of the `websocket` dependency, so I think it's safe to remove it. We seem to only be using `web_sys::WebSocket`s.

How is this related to the problem? Removing this dependency resolves it?

**Comment by mwu-tow** [comment]
> How is this related to the problem? Removing this dependency resolves it?

We don't know, but there is a chance that it is related. And even if this doesn't help, eliminating outdated, unused dependencies is a win.

**Comment by Procrat** [comment]
> I have not investigated it yet. It does happen daily, but not so often that I stopped to have a more in-depth look.

I also want to mention that I'm running into this 5+ times a day. Having to do a clean build every time consumes a lot of time.

If we could somehow know which package is to blame, then, even if it's not immediately fixed upstream, we'd at least only have to rebuild a single package (and it's dependents). (`cargo clean -p parking_lot -p parking_lot_core -p websockets` didn't do anything btw.)

**Comment by MichaelMauderer** [comment]
I actually haven't run into it again, so that is why I have no new diagnostics/insights on this.

**Comment by Procrat** [comment]
After getting slowed down a bunch more times by this bug, I decided to write a small script to see if we can get away with only deleting compilation artifacts for a single package (with the hope that only a single package is to blame).

```sh
target='wasm32-unknown-unknown'
packages=$(cargo tree --target "$target" --workspace --edges all --prefix none \
    | grep -v '\(\*\)$' \
    | grep -v '^$' \
    | sed 's/^\(\S\+\) .*/\1/' \
    | sort \
    | uniq)
n_packages=$(echo $packages | wc -w)
i=0
while IFS= read -r package || [[ -n $package ]]; do
    ((i+=1))
    echo "Testing package $i/$n_packages"
    echo "Running cargo clean $package"
    cargo clean --target "$target" -p "$package"
    if ./run ide build --skip-wasm-opt; then
        echo "It worked! Package $package was the culprit!"
        break
    fi
done <<< "$packages"
```

Unfortunately, it seems to have indeterministic results. Sometimes cleaning `mio` was enough. Another time, it was `matrixmultiply`. The last time I ran it, it ran until the end without a solution.

**Comment by wdanilo** [comment]
I did not run into this issue for months, so It's hard for me to debug it. It's worrying though that @Procrat is facing it. What ideas do you guys have to investigate/resolve it?

**Comment by Procrat** [comment]
I also can't find much more than what @mwu-tow and @somebody1234 already found. I've create a PR (#6535) for removing our dependency on `websocket`, which then also removes the transitive dependency on that old version of `parking_lot`.

**Comment by wdanilo** [comment]
@Procrat does removing this dependency fixes this issue?

**Comment by Procrat** [comment]
> @Procrat does removing this dependency fixes this issue?

I can't reliably reproduce it, so it's hard to tell. It's just the only lead we have, I think. But I usually get it 5 to 15 times a day, so if I go a couple of days without hitting it at all, I think it's safe to say that fixed it, so I'll report back after a while.

**Comment by wdanilo** [comment]
This is so strange. Good to know it's "fixed" by this. I can't understand though how on earth this change can influence this error. If it ever happens again, please re-open this issue :)

**Comment by mwu-tow** [comment]
This still happens, e.g. in https://github.com/enso-org/enso/actions/runs/4947955531/jobs/8848037185?pr=6605

<blockquote><img src="https://opengraph.githubassets.com/a2026a986c89b5167d46e3e57518885506ef572010d616bafa62c191c5ad7106/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Fix redirect paths and enable authentication and new dashboard by default · enso-org/enso@97d120f</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by Procrat** [comment]
I've noticed it as well. This time, I've decompiled `target/ensogl-pack/wasm-pack/pkg_bg.wasm` with `wasm2wat` to try and figure why it's trying to import from this `env` package. These are the imports I found:
```wat
  (import "env" "_ZN16ensogl_grid_view10selectable9highlight25Data$LT$InnerGrid$C$E$GT$18connect_with_shape17h304c73ed6f309421E.llvm.9607723420403503891" (func $ensogl_grid_view::selectable::highlight::Data<InnerGrid_E>::connect_with_shape::h304c73ed6f309421 (type 21)))
  (import "env" "_ZN8nalgebra4base3ops168_$LT$impl$u20$core..ops..arith..Add$LT$nalgebra..base..matrix..Matrix$LT$T$C$R2$C$C2$C$SB$GT$$GT$$u20$for$u20$nalgebra..base..matrix..Matrix$LT$T$C$R1$C$C1$C$SA$GT$$GT$3add17ha1ddb8a757bbb102E.llvm.9607723420403503891" (func $nalgebra::base::ops::<impl_core::ops::arith::Add<nalgebra::base::matrix::Matrix<T_R2_C2_SB>>_for_nalgebra::base::matrix::Matrix<T_R1_C1_SA>>::add::ha1ddb8a757bbb102 (type 97)))
  (import "env" "_ZN11ensogl_core9animation5loops13LOOP_REGISTRY7__getit17h8f6678a17766ac9eE.llvm.9607723420403503891" (func $ensogl_core::animation::loops::LOOP_REGISTRY::__getit::h8f6678a17766ac9e (type 5)))
 ```

Does anyone see a connection between those? It looks pretty random to me.

**Comment by Procrat** [comment]
After researching this a bit more, I read that somewhere someone mentioned this only happened spuriously when they cancelled the wasm generation process. Based on that, I decided to test the hypothesis that the `watch` commands stop the process at an inopportune time. This week I haven't used the `watch` commands at all and I also didn't encounter this bug.

**Comment by kazcw** [comment]
I encounter this without using `watch` or otherwise interrupting any builds.

**Comment by JanBeelte** [comment]
Sometimes still happening on my end, see the discord discussion [here](https://discord.com/channels/401396655599124480/403573875901726720/1133335877762949190)

**Comment by PabloBuchu** [comment]
Also randomly encounter such error while building small PR: https://github.com/enso-org/enso/actions/runs/5831890147/job/15816211594?pr=7564

<blockquote><img src="https://opengraph.githubassets.com/744131f2bebd9da74aab00acc4cd8402430c385bed9184280f2502873ed0cbfb/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Fix IDE bug on cloud backend · enso-org/enso@b016eec</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by mwu-tow** [comment]
The issue is gone with the GUI, as far as I know.
