### ISSUE TITLE
Mouse point does not move together with the scrollbar

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6095]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Minor inconsistency when scrolling through large tables:

https://user-images.githubusercontent.com/292128/228074512-df644644-18d6-49d0-b336-9b8df598d1d9.mp4

This is likely a regression with the new JS visualization of tables.

### Expected behaviour

I was expecting the mouse circle to move together with the scrollbar.

### How we can reproduce it?

Take any large table and scroll around.

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by wdanilo** [comment]
@hubertp your video does not work on my end (Safari, Mac)

**Comment by hubertp** [comment]
@wdanilo it's a problem with safari not supporting properly mp4. try o proper browser ;)

**Comment by hubertp** [comment]
https://user-images.githubusercontent.com/292128/228177071-1d4d083f-1001-4d76-b285-aab77f9a8252.mp4

(converted to avi)

**Comment by farmaazon** [comment]
I think the HTML scrolling blocks any mouse events, so we do not receive mouse position updates. Don't know how to fix it, except usual "display system cursor instead of ours".

**Comment by wdanilo** [comment]
@hubertp doesn't work either:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/1623053/228494407-158a9cda-bc82-4c84-b22b-984f5d9dfccf.png">

Your videos in some other threads are working fine if I remember correctly.

**Comment by wdanilo** [comment]
Anyway, I've seen it in chrome. I think @farmaazon is right - we are just not receiving `mousemove` event and probably we can't do anything with it until we implement custom scroll-bar component and use it in all visualizations. Such a custom scrollbar in HTML is super simple, so probably this is the solution we are looking for.

**Comment by farmaazon** [comment]
Not relevant to GUI2 where we don't use our own mouse pointer.
