### ISSUE TITLE
Add `value_type` support to `from_vector`, `map` and `zip` in in-memory `Column`.

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6111]
With the value types implemented, we need to update these three functions.

All three of them should take an optional `value_type` parameter. It will default to `Auto`.

- [x] In the `Auto` mode, the current behaviour will be retained - the `InferredBuilder` will be used under the hood, figuring out the type that fits the provided data.
- [x] If a specific value type is provided, a builder for the requested type will be used instead.
	- Similar but stricter rules like with `cast` should be used:
		- if a value does not match the requested type (text-integer mismatch) or fit its size (text-length restriction / integer bit size), always a type mismatch is raised.
- [x] Add tests for all 3 methods handling the Auto case, the specific types and checking for lossy conversion reports.
	- [x] If implemented after #5159, ensure that tests also account for scenarios of non-64-bit ints and fixed-length strings etc.

**Comment by radeusgd** [comment]
@jdunkerley what do you think, if we get a type mismatch, do we throw an `Invalid_Value_Type` error, or report it as a warning and replace the value with `Nothing`?

I would throw an error in this case, as one can always use `Auto` and then do the `cast`. So if they are using the specific return type override, they probably want more correctness assurance. But I'm not strongly attached to this idea, so I'd appreciate your opinion on this.

**Comment by jdunkerley** [comment]
yes lets throw and error and make the user choose explicitly
