### ISSUE TITLE
Implement `Table.auto_value_types`

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6113]
The method should allow to try to find a more specific value type in a given column, as [described in the design](https://github.com/enso-org/design/blob/main/epics/basic-libraries/database-read/design.md#auto_value_types).

This needs to be done after #5159 to be able to provide its full functionality.

- [x] Implement logic for setting a more precise value type for Mixed columns, as described.
- [x] Implement the `use_smallest` feature to find more precise types.
	- By default, all integers will fall back to 64-bit ints, but with `use_smallest`, a 32-bit size will be used if all integers are sufficiently small.
	- Similarly for text - a `max_size` will be selected, and if all texts have equal length, it will be set to be fixed-length.
- This will only work on in-memory tables. We want the API to be present on Database table for consistency, but always throw `Unsupported_Database_Operation`.

**Comment by radeusgd** [comment]
@jdunkerley I'd like to clarify 2 things.

> It will never use Bits_16 or Byte.

1. Why are we not allowing smaller sizes?

2. I assume the logic mostly applies for Mixed columns. Parsing Text columns into more specific types is handled by the separate `parse` method, right? (to be updated in #5660)

**Comment by jdunkerley** [comment]
1. When we discussed in Gdansk it was agreed it would be the default for integer types. Users can specify them if they wish.
2. Yes this is to work out the types as needed when we don't know them. It should shrink number types as well.

**Comment by radeusgd** [comment]
> 1. When we discussed in Gdansk it was agreed it would be the default for integer types. Users can specify them if they wish.

64-bit is the default, right? Then if we use `use_smallest`, we allow it to go down to 32-bit. IMHO it is a bit un-intuitive that `use_smallest` still won't use the smallest value, just a slightly smaller one. 

I'm fine with keeping it that way though (as, as you said - we can always specify the 16 bits explicitly if needed), but I feel like this may cause confusion. We definitely need to explain this well in the doc comment to be clear that `use_smallest` will still _not_ use 16-bit ints.

**Comment by radeusgd** [comment]
> 2. Yes this is to work out the types as needed when we don't know them. It should shrink number types as well.

Ok.

As for shrinking number types - with the current spec I assume the **only** shrinking that can happen is shrinking 64-bit ints to 32-bit ints, and that's all, right? Because 16-bit is ruled out; and 32-bit floats are not supported currently (it will need #6109).

(But we also have the shrinking of text values though)

**Comment by jdunkerley** [comment]
> > 1. When we discussed in Gdansk it was agreed it would be the default for integer types. Users can specify them if they wish.
> 
> 64-bit is the default, right? Then if we use `use_smallest`, we allow it to go down to 32-bit. IMHO it is a bit un-intuitive that `use_smallest` still won't use the smallest value, just a slightly smaller one.
> 
> I'm fine with keeping it that way though (as, as you said - we can always specify the 16 bits explicitly if needed), but I feel like this may cause confusion. We definitely need to explain this well in the doc comment to be clear that `use_smallest` will still _not_ use 16-bit ints.

I think should be 16-bit smallest. It was 8-bit unsigned byte that we want to avoid, but if you are aiming to make least memory per row `short` is probably the right target.
