### ISSUE TITLE
Language Server Protocol changes to support Execution Contexts

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#6133]
According to PR-55 there are two new messages that need to be supported in the language server protocol:

> 
> When an execution environment is chosen, this will be sent to the Language Server causing it to re-evaluate the whole workflow. There will need to be a new language server protocol added to support this.

The IDE always starts in `design` mode, but by selecting another mode from the 

<img width="595" alt="image" src="https://user-images.githubusercontent.com/1623053/227451944-25b6c680-2a94-4442-8935-5046eec029a4.png">

drop down, it can instruct the engine via the LS protocol to switch to `live` mode and back. In addition to such a _permanent_ (for the rest of IDE session) switch there has to be support for _"Workflow Level Play Button"_. The IDE shall be able to emit a message that instructs the language server to:

> - _Delete all cached_ values.
> - Execute the project with _all contexts enabled_.
> - _Re-evaluate all_ nodes (including inputs) 
> - store the _results in the cache_

The switch of the _execution mode_ to enable all contexts is just a temporary in this case. After the re-evaluation is over, the previous execution mode (together with its contexts) is turned on again.

**Comment by 4e6** [comment]
As for the API, I imagine it can be something like that:

## executionContext/setMode

```ts
type ExecutionMode = Design | Live;

{
  contextId: ContextId;
  mode: ExecutionMode;
}
```

### Example

```json
{"jsonrpc":"2.0","id":0,"method":"executionContext/setMode","params":{"contextId":"d8e948fd-6418-43c8-9f02-54827f09e10a","mode":"Live"}}
```

**Comment by vitvakatu** [comment]
Your example shows only a _permanent_ change of the execution environment (design doc uses the term `environment` instead of `mode`).
We also need an API for a temporary switch by pressing the Play button.
Besides, we need some indication that the re-evaluation has finished, because the IDE would be locked for the user until this operation completes.

**Comment by 4e6** [comment]
> design doc uses the term environment instead of mode

Let's use the `environment` term then.

As for the temporary change, I suggest adding an optional `environment` parameter to the `executionContext/recompute` message. 

```typescript
type ExecutionEnvironment = Design | Live;

{
  contextId: ContextId;
  invalidatedExpressions?: "all" | [ExpressionId];
  environment?: ExecutionEnvironment;
}
```

If the `environment` parameter is present, the program will be re-executed in the provided environment. All the subsequent executions will not be affected.

**Comment by vitvakatu** [comment]
I have no objections. cc @MichaelMauderer
