### ISSUE TITLE
Cannot drag files into electron window on Windows

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/enso#6146]
### Discord username

MichaelMauderer#5076

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When trying to drag a file (i.e., "Text.txt") into the electron window on Windows, instead of being able to drop the file, the mouse cursor turns into an "🛇" and dropping has no effect. 

### Expected behaviour

I should be able to drop the file into the scene to create a new node.

### How we can reproduce it?

* Run `./run.cmd ide watch --backend-source=release --backend-release=latest --skip-wasm-opt` on Windows.
* Wait until the electron window opens.
* Drag a file from the Explorer into the electron window. 

### Screenshots or screencasts

https://user-images.githubusercontent.com/1428930/228836621-be45b972-b4c6-429e-9bb7-2eb8c2a64924.mp4

### Enso Version

Latest develop 90612cfa3595d2fcfad7b3e3c004a9fac953e76f

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by farmaazon** [comment]
Is this only on election window shown by `watch` script, or on built packages as well?

**Comment by sylwiabr** [comment]
We didn't have this issue yesterday when testing Enso with @jdunkerley on Win 11

**Comment by wdanilo** [comment]
> Is this only on election window shown by `watch` script, or on built packages as well?

Ohhhh,  this is a good catch @farmaazon ! I don't know if this is the case, but I feel it might be!

Btw, @MichaelMauderer, I adore the color of you wallpaper!

**Comment by farmaazon** [comment]
Checked watch on linux - it works.

**Comment by MichaelMauderer** [comment]
Good point! This was actually observed with the watch script.
