### ISSUE TITLE
Support type-annotated expressions at the top level of a block

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#6152]
Currently, any use of the `:` operator at the top level of a line is parsed as a `TypeSignature`. I think any time the LHS is not an Ident (or operator-ident), we should parse it as a `TypeAnnotated` expression--in particular, this enables declaring the type of the value returned from a block.

There is one tricky case: The user may try to return a variable from a block while declaring its type. Syntactically, this would look like a block ending in a `TypeSignature`. I think that's the right parse; we can achieve consistent semantics by, in translation, treating a type signature as evaluating to the value of the annotated ident (its value will only be used when it occurs at the end of a block).

**Comment by jdunkerley** [comment]
@kazcw could you add an example to this to clarify and check still an issue?
