### ISSUE TITLE
Node positions are reset after reopening the project

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#6161]
### Discord username

farmaazon@1240

### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I have a big project where the node positions are lost and default layout is applied every time I re-open it.

### Expected behaviour

The nodes positions are kept when re-opening.

### How we can reproduce it?

Open the attached project, move any node, close and open again.

[Unnamed_10.zip](https://github.com/enso-org/enso/files/11122369/Unnamed_10.zip)

### Enso Version

build d89de84988156c12ab82d1afb40cf77d41d80786

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

Garuda

**Comment by farmaazon** [comment]
Let's check if this occurs on other projects. For now it's not the top priority, because other projects seem to work well.

**Comment by wdanilo** [comment]
It's so strange. Maybe there is limit to how big metadata engine can send to us? ;)

**Comment by farmaazon** [comment]
Closing as not reproducible. If will appear anytime I will reopen this.
