### ISSUE TITLE
Remove `\` from `IR.Type.Set` but support `&`

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#6165]
There are some `SugaredTypeFunctionsTest` that deal with support for sets(!?) and produce `IR.Type.Set`. Some of the operations seem to be working (like `T & P` or `T | P`) but some of them aren't. Particularly the `T \ P` syntax seems to contradict with the _"new syntax for lambdas"_.

Please take a look at `SugaredTypeFunctionsTest` three failing tests:
- should resolve context ascription
- should resolve equality
- should resolve subtraction

and decide whether such tests are supposed to be fixed or deleted. Thanks for your help.

**Comment by wdanilo** [comment]
You are right. The syntax `T \ P` is not working anymore, as it's needed for lambdas. However, I am not sure we will support full boolean algebra on contexts. In particular, I'm not sure if we can support the `\` operator in a general sense. Maybe we could, but until we are sure about it and it is correctly designed, I'd propose to just remove the `\` boolean operator and use this syntax for lambdas only.

**Comment by JaroslavTulach** [comment]
>  just remove the `\` boolean operator and use this syntax for lambdas only.

OK. Let's remove `\` operator support. Shall we keep all the others `&`, `|`, etc. or attempt to remove this whole `IR.Type.Set` support?

**Comment by wdanilo** [comment]
Yes, we should keep them. `String | Nothing` and similar types are super useful and are foundation for many things we are designing with James.
