### ISSUE TITLE
Suggestion in Table.join does not insert required import resulting in error

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6173]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When creating a node that `join`s two tables, the suggested join kind results in an error from missing `Join_Kind` type.

See the workaround in the comment but still, for a first-time user that would be surprising.

### Expected behaviour

Should figure out the missing import during insertion of the selected suggestion.

### How we can reproduce it?

See video.

### Screenshots or screencasts

https://user-images.githubusercontent.com/292128/229380949-430bd6b3-a99b-4bc8-b1d9-a0958d063104.mp4

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by hubertp** [comment]
Workaround - create a node with `Join_Kind.Inner` and magically imports get added.

**Comment by Frizi** [comment]
This is an example of a dynamic dropdown, for which IDE doesn't attempt to insert imports or shorten the expressions yet. That would be part of #5689. Those expressions are right now treated as arbitrary code and are inserted as-is. We could attempt to parse them as fully qualified names, but existing dynamic dropdowns don't provide FQNs as values, so it would have no immediate effect. The values are already pre-shortened.

In this case though, the dropdown should simply be left as static, as there is no actual dynamic data generated. The default `tag_values`-based dropdown would work fine, including import support.

Custom widget annotations on `join` method:
https://github.com/enso-org/enso/blob/0d7682b6ec3cdea65e8ef713476af926f9fff1fc/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso#L1266-L1268

Dynamic dropdown values definition:
https://github.com/enso-org/enso/blob/0d7682b6ec3cdea65e8ef713476af926f9fff1fc/distribution/lib/Standard/Table/0.0.0-dev/src/Internal/Widget_Helpers.enso#L25-L29

**Comment by wdanilo** [comment]
@hubertp the video is not working on Safari again. Would you be able to record them somehow different, so Safari users would be able to see them, please? :)

**Comment by farmaazon** [comment]
If I understand correctly @Frizi comment, this should be done on the stdlib side (switch dynamic dropdown to static) or wait for https://github.com/enso-org/enso/issues/5689 to be merged. Thence I reassign the issue to libs.

**Comment by jdunkerley** [comment]
This has been done.
