### ISSUE TITLE
Any.== slowed down by gigantic EqualsNode specializations

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#6191]
#5898 investigation brought down the [sieve benchmark](https://github.com/enso-org/enso/pull/6184) to 518ms on my computer. While continuing investigations I found a way to get down to 333ms. It is just necessary to [productize my prototype](https://github.com/enso-org/enso/compare/wip/jtulach/ConversionFromAnyFallback_5898...wip/jtulach/MoreEqualsNodes_6191)...

- [EqualsNode](https://github.com/enso-org/enso/blob/5f7a4a5a39d57210651656d732b40e945e2d4bef/engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java#L80) contains gigantic amount of `@Specialization` which leads to (possibly) too huge `execute` method in `EqualsNodeGen`. Such a huge method may overload the compiler thresholds and disable some optimization. @steve-s suggested to split the node into few smaller ones
- We should optimize for most common cases - e.g. first of all check for primitive type comparisons and only then move to other builtins and/or to custom comparators
- Current [Any.== implementation](https://github.com/enso-org/enso/commit/5f7a4a5a39d57210651656d732b40e945e2d4bef#diff-de36bd4bcd83668fcc27dc4154277d083ed2184aa72ba248c22d8b25eb1f99eeR111) checks comparators first - given most of our common cases don't have special comparator this is a waste of CPU

Remove the Enso `Any.==` code. Split the logic into multiple nodes. Revert the checks to optimize for most common situations. CCing @Akirathan

**Comment by Akirathan** [comment]
I agree. Reducing `Any.==` to just a builtin method, without the overhead of some Enso code wrapper seems like a good idea, and will be easily implemented once we have #5740. Moreover, optimizing for primitive value comparison is indeed a good idea.

**Comment by Akirathan** [comment]
> [EqualsNode](https://github.com/enso-org/enso/blob/5f7a4a5a39d57210651656d732b40e945e2d4bef/engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/meta/EqualsNode.java#L80) contains gigantic amount of @Specialization which leads to (possibly) too huge execute method in EqualsNodeGen. Such a huge method may overload the compiler thresholds and disable some optimization.

Right. Once there are many specializations instantiated, the compilation might get tricky. Also, it is a problem for the interpreter.
