### ISSUE TITLE
JSON visualization does not show the last row

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6196]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

It seems that the default visualization cuts slightly the visualization of the last row.
I would expect scrolling to show the missing bits but that doesn't work either.

### Expected behaviour

Should be able to see all data.

### Screenshots or screencasts

![Screenshot from 2023-04-04 16-55-39](https://user-images.githubusercontent.com/292128/229836099-e38ee6d1-e659-416c-81d0-18a50fcafd71.png)

See the cut `1` and missing brackets.

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by 4e6** [comment]
Reproduced in 2e08f734d7953d2c0f67b7d6f733287072299a2e
