### ISSUE TITLE
`Fit all` and `pan to selected` functionality

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6206]
### How important is this feature to you?

4 – Lack of it makes using Enso a lot harder

### Describe the idea you'd like to see implemented.

Right now there is no way to automatically move the scene to see your nodes when they got lost. Due to the bug with panning the canvas while scrolling the full screen visualizations it happens pretty often that users loose their nodes and trying to find them can be really hard. 

We should implement the way to do it. 

1. There should be a shortcut and a pop-up when user does not have any nodes on scene with an information about the shortcut.
2. If user have a node selected, pressing the shortcut should move the scene to show the selected nodes.
3. If user doesn't have any nodes selected, pressing the shortcut should fit all nodes on the scene.

### Would you be willing to help us implement this feature?

No

**Comment by 4e6** [comment]
An alternative approach would be to detect if the scene is empty (the case when the user scrolled away), and then move the screen to the nearest (or last created) node.

**Comment by wdanilo** [comment]
> An alternative approach would be to detect if the scene is empty (the case when the user scrolled away), and then move the screen to the nearest (or last created) node.

This would probably cause strange effect when panning screen in such a way that nodes are not visible. Sometimes you want to do it in order to have clean screen and create a new graph there. I think that what Sylwia proposed is more generic and I like it a lot. Does it make sense to you @4e6 ?

**Comment by somebody1234** [comment]
@wdanilo @sylwiabr I think this should be simple enough to do in GUI2 now - there is one major issue though:
There are already shortcuts for this for visualizations, and I think these shortcuts should have the same keybinds, at least by default.

*However*, in the visualizations "fit all" uses <kbd>Cmd</kbd>+<kbd>A</kbd> which conflicts with the shortcut for "select all nodes", and "zoom to selected" (which I'd assume is equivalent to "pan to selected" in the graph) uses <kbd>Cmd</kbd>+<kbd>Z</kbd>, which conflicts with the shortcut for "undo".

Does anyone have any preferences on the appropriate keybinds for all mentioned actions?

**Comment by somebody1234** [comment]
One option is to have completely different keybinds from the current system - e.g. <kbd>Cmd</kbd>+<kbd>0</kbd> for both actions - which one is triggered depends on whether any selection is active.

(Note of course, that <kbd>Cmd</kbd>+<kbd>0</kbd> usually resets zoom instead, so we may want to use a different shortcut for that)

**Comment by wdanilo** [comment]
First of all, cmd + z is a terrible choice for a shortcut to fit visualization data on screen ;) 

Secondly, when visualization is active, it should handle some shortcuts differently than when visualization is not focused. For example, cmd + a should select all nodes or all visualization points (depending if viz is selected or not). 

Regarding exact shortcuts, let's create a list of actions for shortcuts and then we can brainstorm on what are the best options. How does it sound? :)

**Comment by somebody1234** [comment]
Sounds good! Although, GUI2 isn't quite feature complete with respect to shortcuts yet, so I think the authoritative source would still be [shortcuts.md](https://github.com/enso-org/enso/blob/b9ec6d4ec307cc5e3c5949688588b08f3b9f978a/app/gui/docs/product/shortcuts.md).

Unless you mean an updated list of shortcut actions that:
- are already implemented, or
- may be needed in the future, and
- potentially excluding actions that are no longer relevant - for example, I think the `Debug` actions could be combined to a single shortcut that toggles a modal containing buttons to trigger each debug action.
