### ISSUE TITLE
Selecting text on the node to copy enables selection in documentation panel and visualization preview when adding next nodes

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6224]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://user-images.githubusercontent.com/12892578/230599177-4ebce15d-f348-4f83-b299-2e614ba86188.mp4

### Expected behaviour

The text in documentation panel and visualization should not be selected

### Enso Version

2023.1.1-nightly.2023.4.5

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by Frizi** [comment]
This is likely related to #6290, looks like another instance of keyboard events not having "preventDefault" called.

**Comment by farmaazon** [comment]
Not reproducible in GUI2
