### ISSUE TITLE
Fullscreen visualization icon

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6225]
### How important is this feature to you?

4 – Lack of it makes using Enso a lot harder

### Describe the idea you'd like to see implemented.

Right now to discover how to open a visualization full screen user has to know the shortcut. Magical shortcuts are not easy to discover. There should be an icon to open visualization full screen.

### Would you be willing to help us implement this feature?

No

**Comment by farmaazon** [comment]
Fixed in GUI2
