### ISSUE TITLE
Styles being set on `body` instead of `#root` will affect dashboard styles

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#6229]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

`cursor: none` is being set on `body`. This will hide the cursor for the dashboard as well, which is not good because the dashboard doesn't have a replacement cursor, unlike the editor which has the translucent circle.
https://github.com/enso-org/enso/blob/7ad09f4e406dfad999ec47c772157eadf3761279/lib/rust/ensogl/core/src/application.rs#L81

### Expected behaviour

`cursor: none` should be set on `#root` instead; this way the cursor will always be visible on the dashboard and top bar.

### Enso Version

latest

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by vitvakatu** [comment]
@somebody1234 is this issue blocking some work on dashboard?

**Comment by somebody1234** [comment]
not really, since you can manually remove the `cursor: none` every time you reload

**Comment by somebody1234** [comment]
note: i cannot consistently reproduce the underlying issue, *usually* (but not always) it sets cursor back to auto when out of view. (regardless, this will not be an issue anyway, if this change is made)

**Comment by somebody1234** [comment]
hasn't been an issue lately, so closing this
