### ISSUE TITLE
Opening dev tools with a shortcut does not work anymore

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6249]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

After changes to Electron the shortcut to open dev tools in IDE stopped working. Theoretically it is enabled in our code:
https://github.com/enso-org/enso/blob/e7668ebc3ae39a489149bf0d0a51e45b7ef7b427/app/ide-desktop/lib/client/src/index.ts#L353

### Expected behaviour

The default shortcut to opening dev tools should work in IDE.

### Enso Version

2023.1.1-nightly.2023.4.12

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by vitvakatu** [comment]
Can we confirm this is a bug and not a deliberate decision to disable dev-tools by default? @sylwiabr @wdanilo 

The reason is this line: https://github.com/enso-org/enso/blob/e7668ebc3ae39a489149bf0d0a51e45b7ef7b427/app/ide-desktop/lib/client/src/index.ts#L209

Removing it will fix the issue.

**Comment by sylwiabr** [comment]
I confirmed it with @wdanilo on Tuesday :)
