### ISSUE TITLE
After saving and reopening project the camera settings are not preserved

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6250]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

1. Open an existing project.
2. Pan/zoom the scene.
3. Close and reopen the project.

Project after reopening has a default zoom and focus, not the last saved one. If the nodes were added - they are there, so the file is updated.

### Expected behaviour

Camera settings should be saved with project metadata.

### Enso Version

2023.1.1-nightly.2023.4.12

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
It should be done _after_ a shortcut for panning back to the graph. Otherwise, the situations where the view jumped far could be hard to manage.

**Comment by farmaazon** [comment]
* The camera should be stored on client side, not in the project, in something like local storage.
