### ISSUE TITLE
Project folder not renamed after project name change inside Enso

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6254]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

After renaming project inside our GUI, the folder where project is contained is not being renamed.

### Expected behaviour

Folder name consistent with the project name.

### How we can reproduce it?

Under Windows OS (havent tested it on other systems)
1. open Enso
2. create a new project
3. rename it to acceptable name (in my case "Enso_101")
4. close Enso
5. check the folder name

### Screenshots or screencasts

![image](https://user-images.githubusercontent.com/108271897/231504304-4b0f43e9-6040-4804-8672-553565a10d2d.png)

### Enso Version

ctrl + ? doesn't work. version: 2023.3.21

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by vitvakatu** [comment]
If this is a regression, it's an old one, I can reproduce it on a commit more than one month ago. I find further bisecting unreasonable. I can reproduce it on Mac OS.

**Comment by Akirathan** [comment]
I am attaching a log from the engine for creating a new project, for which the name is resolved to `Unnamed_2`, to `Enso_101` indeed does not rename the directory. The only thing that seems to change is the name property in `package.yaml`.
[20230413-092052-659-enso-project-manager.log](https://github.com/enso-org/enso/files/11220553/20230413-092052-659-enso-project-manager.log)

**Comment by farmaazon** [comment]
This is a bug, not a regression, as it is with us since the renaming is implemented.

@4e6 did some research, and it turned out to be very difficult to address. Dmitry, could you share it here if you remember?  I cannot find the original issue here or in Pivotal.

**Comment by wdanilo** [comment]
What was the reason the regression flag was set? What was the version that was working properly @xvcgreg ?

**Comment by xvcgreg** [comment]
@wdanilo Reason for it was that I noticed some project folders with names corresponding to the upper left corner name in GUI and others without this correspondence. As @farmaazon mentioned it's not a regression, it's a bug or rather a missing feature in my opinion. I don't know if in prior versions of Enso (~1,5y ago) it worked as intended.

**Comment by 4e6** [comment]
I was looking into this issue yesterday and I think there might be a race in the shutdown logic of the project manager. Starting working on it today.

**Comment by xvcgreg** [comment]
@4e6  Renaming works on Windows. I have noticed warn after renaming is done (renamed from "Book_Club_01_test" to "Book_Club_01":

```[info] [2023-04-21T07:56:57.969Z] [org.enso.projectmanager.infrastructure.languageserver.ProjectRenameAction] Requesting a Language Server to rename project [Book_Club_01_test].
[info] [2023-04-21T07:56:57.993Z] [enso] Project renamed to local.Book_Club_01
[info] [2023-04-21T07:56:57.994Z] [org.enso.projectmanager.infrastructure.languageserver.ProjectRenameAction] Project renamed by the Language Server.
[info] [2023-04-21T07:56:57.994Z] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Project renamed [cf8f4e49-f6dd-4858-8b91-f490b600bd22].
[warn] [2023-04-21T07:56:58.002Z] [enso.org.enso.compiler.PackageRepository$Default] Resolution failed with [NotResolved(org.enso.librarymanager.LibraryResolutionError: The library `local.Book_Club_01_test` is not defined within the edition.)].```
