### ISSUE TITLE
On desktop, drag and drop file on the scene should read it directly from its location.

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6263]
### How important is this feature to you?

2 – Somewhat important, but I can live without it

### Describe the idea you'd like to see implemented.

Currently, while dragging and dropping the file on the scene the file is automatically copied to the `data` folder inside a project folder. 

Instead of this on desktop we should:
1. link the file by default and read it,
2. when dragging and dropping with `ctrl` the file should be copied to a `data` folder in a project.

### Would you be willing to help us implement this feature?

No

**Comment by farmaazon** [comment]
Renamed a bit to avoid a confusion I had with the file links.

**Comment by vitvakatu** [comment]
This is a task for the GUI team, but we probably need to split it further.

**Comment by somebody1234** [comment]
I'm assuming "On desktop" means on Electron when using the local backend. In that case, the dashboard already does something like this for adding projects, so it may be a useful reference:

https://github.com/enso-org/enso/blob/cd84ac16ce4c98f22d0eda8e65a5ddb27b5eb1d5/app/ide-desktop/lib/dashboard/src/authentication/src/dashboard/components/projectNameColumn.tsx#L155-L167

**Comment by Frizi** [comment]
Added an issue for implementing the existing file drag and drop behavior in new gui https://github.com/enso-org/enso/issues/8158

Special handling of local paths in electron client is kept out of scope from that task, so this feature report still stands.

**Comment by farmaazon** [comment]
Refinement note: 
* To have "local" uploads, we must check both if we're electron (as other browser may not share the full path with us) _and_ running the local project.
