### ISSUE TITLE
Upgrade to GraalVM based on JDK17

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#6274]
GraalVM 22.3.x was the last GraalVM that was based on JDK11. Future version of GraalVM - e.g. 23.x are going to be based on JDK17 and/or newer JDKs. 

Currently Enso uses **GraalVM 22.3.1 based on JDK11**. This complicates testing of new features and bugfixes done in `master` branch of http://github.com/oracle/graal repository as that requires switching between JDK11 & JDK17 and total recompilation of the code. Moreover certain features like JMH aren't ready for JDK17 - we have to update some libraries.

Let's switch to **GraalVM 22.3.x based on JDK17** as soon as "design partners" release is done.

Latest GraalVM update PR: https://github.com/enso-org/enso/pull/3663

**Comment by Akirathan** [comment]
The latest version is now 22.3.2 with the latest CPU release on April 25th 2023. Let's then use **22.3.2 JDK17**.

See https://www.graalvm.org/release-notes/release-calendar/

<blockquote><img src="/resources/img/graalvm.png" width="48" align="right"><div><strong><a href="https://www.graalvm.org/release-notes/release-calendar/">GraalVM Community Release Calendar</a></strong></div><div>GraalVM is a high-performance JDK designed to accelerate Java application performance while consuming fewer resources. It provides the Graal compiler, which ...</div></blockquote>
