### ISSUE TITLE
`UnresolvedSymbol` is not a `Function`, but it should be

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6277]
I'm pretty sure I reported it already, but I cannot find it now anywhere - that does not bode well for fixing of the issue, so I'm posting it (possibly again). If the duplicate is found we can mark the old one as a duplicate.

This is related to #6276, but it's a more general issue. Although fixing this may likely make #6276 work too.

See the following REPL interaction:
```
> (x-> x.is_nothing) . is_a Function
>>> true
> (.is_nothing) . is_a Function
>>> false
```

We can see that `.is_nothing` is not treated as a function, because it is an `Unresolved_Symbol` which is treated as its own separate type. This is problematic, because the two forms should be essentially equivalent ways of the expressing the same thing and they should be interchangeable for all intents and purposes.

Well, possibly the `.is_nothing` may give us a bit more information, because we can query what symbol it is representing, whereas `(x-> x.is_nothing)` is a lambda that we cannot inspect that well.

Still, `.is_nothing` should be albe to be placed anywhere `(x-> x.is_nothing)` may be and it should _just work_. I remember chatting with @kustosz that the two should be interchangeable for most intents, definitely from perspective of both being a `Function` that can be called.

So I propose to make sure that `(.is_nothing) . is_a Function` will be `true`. We can probably achieve this just by making `Unresolved_Symbol` a subtype of `Function`.

**Comment by radeusgd** [comment]
This has practical implications.

For example, `Vector.filter` tries to distinguish if it was given a `Filter_Condition` or a regular `Function`.

It is doing a pattern match like:
```
case filter of
    _ : Filter_Condition -> ...
    _ : Function -> ...
```

This is making it fail:
```
> [1,2,3,Nothing].filter x-> x.is_nothing
>>> [Nothing]
> [1,2,3,Nothing].filter .is_nothing
Evaluation failed with: Inexhaustive pattern match: no branch matches is_nothing (Unresolved_Symbol).
java.lang.Exception: Inexhaustive pattern match: no branch matches is_nothing (Unresolved_Symbol).
        at <enso>.Standard.Base.Data.Vector::Standard.Base.Data.Vector.Vector::filter(Vector.enso:409)
        at <enso>.<eval>(Unknown Source)
        at <enso>.Debug.breakpoint(Unknown Source)
        at <enso>.Internal_Repl_Module___::Internal_Repl_Module___::internal_repl_entry_point___(Internal_Repl_Module___:4)
        at <unknown>.org.graalvm.polyglot.Value<Function>.execute(Unknown Source)
```

Of course, we could change the second branch to `_ -> ...` without any checks. But I don't think that's the right direction. We _should_ have a reliable way of checking if an object is a _function_ and `.foo` should be a function with this notion.

**Comment by Akirathan** [comment]
Related to #6276

**Comment by Akirathan** [comment]
Just out of curiosity, where does `_.foo` stand? Should that syntax also be equivalent to `.foo`, and thus `x -> x.foo`? Currently, `_.foo . is_a Function` returns True. By the way, I find the `_.foo` syntax to be more readable than `.foo`.

**Comment by radeusgd** [comment]
> As a user I want to **be able to match functions in my code**, and I don't want to care _how_ these functions were constructed: `(+)`, `.foo`, `_.foo`, `x-> x.foo`; and `foo` when declared as `foo x = ...` should _all_ match `Function`.

**Comment by radeusgd** [comment]
As for `.foo` vs `_.foo` - that's another thing, I'm fine with removing one of the syntaxes (although I guess @wdanilo may have something to say about this). 

But for each of these syntaxes that we support, I want to be able to tell if an object is a _Function_ and I want this to work regardless of how this function has been constructed.

**Comment by Akirathan** [comment]
I believe I have found a bug in our codegen phase, see [this comment in a discussion](https://github.com/orgs/enso-org/discussions/6278#discussioncomment-5614522). Basically, the IR for `.foo` is `IR.Name.Literal(name="foo", isMethod=true)`, which is fine, but the `isMethod` field is later ignored in our codegen phase. I believe we should create some kind of `Function` for these symbols, rather than `UnresolvedSymbol`. That should fix this issue.
