### ISSUE TITLE
`Vector.sort` should attach limited number of warnings

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6283]
We will be adding a warning for each pair of incomparable values when sorting.

If I sort a vector of 1M of values, each of them being incomparable, how many of these warnings will I get?

I'm thinking that we may want to report only the first 3-10 of these and then report just a counter _'and N more values that were incomparable.'_

See for example `Additional_Warnings` in the Table library which is a similar concept. When doing Table aggregations we report the first 10 issues and then just report the count of additional problems. We don't want 1000+ of the same problem just with different values in it attached, it will not add much more information.

More importantly, sorting 1M elements that are comparable vs incomparable shouldn't have vastly different performance characteristics.

I'm not pushing to necessarily do it _now_, but ideally we should at least create a ticket to ensure that large incomparable vectors are handled well by this. Ideally with adding a test that sorts a vector of at least 10k+ values and measures the amount of warnings, possibly also a benchmark.

_Originally posted by @radeusgd in https://github.com/enso-org/enso/pull/5998#discussion_r1166724905_

## Related
- https://github.com/enso-org/enso/pull/5998#discussion_r1167437550
- #6372 
- #5233

**Comment by jdunkerley** [comment]
Closing as related to #6257 and we need a general solution.

**Comment by Akirathan** [comment]
Probably blocked by #5233.
