### ISSUE TITLE
Undo is broken in many places but occurs randomly

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6286]
### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Undo behaves unstable, it occurs by:
- not working while inside collapsed functions
- undoing just last step over and over (i.e.: I have created a node than undone it and after second press of ctrl + z node reappeared back)

### Expected behaviour

Undo working as it should - undoing actions till the project open state without any actions done.

### How we can reproduce it?

There's no reliable way of reproducing this issue. It occurs most often while working with collapsed nodes.

### Enso Version

2023.04.13

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by xvcgreg** [comment]
Another issue found in the build: https://github.com/enso-org/enso/actions/runs/4734034483 

After deleting a node I have to press Ctrl + z three times to revert the node deletion. 
The first press issues a warning but no visible change in the GUI, then the second press shows me the node, third press reverts the connection. You can observe it here:

https://user-images.githubusercontent.com/108271897/233005349-8eed737d-7cad-4945-8c25-321daaa66694.mp4


Also: Each time Ctrl is pressed I'm issued a warning in console.

<blockquote><img src="https://opengraph.githubassets.com/6af21b35f1d88030cef9356d6dcf0808ed6a24374e453330ab09cb5f5d1c6bde/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Disable buffer compaction (#6339) · enso-org/enso@9125568</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by sylwiabr** [comment]
Looks like the fix from @vitvakatu (https://github.com/enso-org/enso/commit/68119ad6bbd1435ba34a947b20861fc18d6a13d5) fixed most of the Undo issues as well. I can't reproduce most of the issues. @xvcgreg reopen if you will observe the behavior again. For specific and reproducible cases please, create separate issues.
