### ISSUE TITLE
Bredcrumbs ordering issue (multiple of the same func displayed)

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6287]
### What type of issue is this?

Intermittent – Ocurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Bredcrumbs behavior is sometimes unpredictable resulting in such path:
Project name -> Func1 -> Func2 -> Func1

can be observed here in 0:43:

https://user-images.githubusercontent.com/108271897/232108863-c3825d74-c1d0-4d72-bbd4-bd6b18b50e2c.mp4

### Expected behaviour

Not having 2 Func1 breadcrumbs placed in the path but rather going back and forth with navigation

### How we can reproduce it?

See attached video file.

### Enso Version

2023.04.13

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by MichaelMauderer** [comment]
I can reproduce this quite reliably when stepping up from a nested node via background double clicks and then choosing the lowest node to descend again. When doing this repeatedly, at some point the node order in the breadcrumbs will reverse. 

https://user-images.githubusercontent.com/1428930/234867978-1549bf40-4dea-4a68-8a24-d3cc6228b833.mp4

**Comment by vitvakatu** [comment]
QA passed 🟢
