### ISSUE TITLE
After pressing TAB node is not selected and is not accepting key inputs

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6290]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Cant type node name while creating it without clicking it with a mouse first.

### Expected behaviour

after pressing TAB I should be able to start typing desired node name, not having to click the empty node text area first (one below component browser)

### How we can reproduce it?

press TAB
start typing

watch no character appear in the node name field

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/232113358-ffd8462f-ae98-4502-a9ac-ddb7f36c2796.mp4

### Enso Version

2023.04.13

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

Version 111.0.5563.149 (Official Build) (64-bit)

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by sylwiabr** [comment]
Can not reproduce it on MacOS (build 467d3df4c2c33352cd9a6e8e8e0eff1d2d436f9b)

**Comment by Frizi** [comment]
In browsers, this looks to be caused by the "tab" press event default behaviour not being prevented. That way, the browser moves the focus to the next browser UI element (e.g. "new tab" button). None of the events looks to be prevented now, as other default browser actions are also allowed to happen (e.g. ctrl+shift+d enables debug mode, but also adds the page to bookmarks).

So this is likely caused by a global event handling code change.

**Comment by xvcgreg** [comment]
@farmaazon, @JaroslavTulach - can you confirm it's caused by https://github.com/enso-org/enso/pull/6078 ?

**Comment by Akirathan** [comment]
Can reproduce on Linux (build e5a96b97828f865ec9f9a3325a1e407adcf04451) in Chrome.

**Comment by hubertp** [comment]
Similar "hijacking" of focus I noticed with `ctrl+s` when saving the project. It does save the project in Enso but it also triggers "save the page to a file" dialog in the browser.

**Comment by wdanilo** [comment]
CC @Frizi, as you are working on it I think (or plan to work on it).

**Comment by xvcgreg** [comment]
``tab``, ``ctrl+s``, ``ctrl+shift+d`` fixed on Windows and no longer triggers browser events
