### ISSUE TITLE
Output of collapsed function changes from original state before collapsing or entering the function

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6291]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

After collapsing nodes collapsed function has the proper output, but after entering the newly created function it changes to the wrong one (outputs a different node).

Please see the attached video for more details.

### Expected behaviour

Collapsed nodes output doesn't change.

### How we can reproduce it?

See attached video

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/232114628-2631bfd9-7f1a-4c5e-8df6-d26c27c06d2b.mp4

### Enso Version

2023.04.13

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by 4e6** [comment]
I'll check if the engine sends the correct updates.

**Comment by farmaazon** [comment]
I don't understand this bug. Everything seems working to me here.
1. You collapse nodes without clear output connection. We just assume one of the nodes being an output node. We pick the one on the right - we have no clue you prefer the left pipeline to produce an output.
2. Immediately after collapsing the collapsed node output's type is `Decimal`, not `Vector/Table` So there is no second where collapsed node returns "proper" value. I don't see a moment where collapsed node output does change.

**Comment by xvcgreg** [comment]
@farmaazon you are right about the output. When I created one more additional node after the group I was collapsing it was connected properly.
