### ISSUE TITLE
Add `forceInline` parameter to `@Builtin.Method` annotation

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6293]
#6255 got merged a bit prematurely. There are some leftovers that should be addressed. As `MethodProcessor`'s functionality is getting more and more complicated, we should strive to keep its functionality readable and understandable. This issue lists the tasks, along with links to appropriate comments, that were not merged with the PR.

```[tasklist]
### Tasks
- [ ] Rename `handleExecute` to `executeInline` - https://github.com/enso-org/enso/pull/6255#discussion_r1166507590
- [x] Replace the, rather cryptic, functionality of `MethodProcessor` that checks for a `VirtualFrame` parameter in builtin method's `execute` method, and if it is there, does not force inlining by a proper, documented, `forceInline` parameter to `@Builtin.Method` annotation - https://github.com/enso-org/enso/pull/6255/files#r1165949715
```

**Comment by JaroslavTulach** [comment]
`executeInline` isn't better name than `handleExecute` as [this comment explains](https://github.com/enso-org/enso/pull/6255/files#r1167411315). In fact I find it way more misleading.

**Comment by JaroslavTulach** [comment]
Re. _"Add forceInline parameter to @Builtin.Method annotation "_ - I have [tried to explain](https://github.com/enso-org/enso/pull/6255#discussion_r1167410563) that adding `allowInline` attribute isn't justified right now. I haven't planned any refactoring unless there is a performance benefit in doing so.

**Comment by JaroslavTulach** [comment]
Might it be enough to [document & test current behavior](https://github.com/enso-org/enso/pull/6304/commits/9246ce196d64a29046585f90b239cacd85839607)?

**Comment by Akirathan** [comment]
> Might it be enough to [document & test current behavior](https://github.com/enso-org/enso/pull/6304/commits/9246ce196d64a29046585f90b239cacd85839607)?

Definitely. Seems great. Thanks!
