### ISSUE TITLE
Type.to_text shall invoke instance method

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#6300]
To turn the #6216 discussion into some practical resolution I propose following [improvement](https://github.com/orgs/enso-org/discussions/6216#discussioncomment-5592834):

If a method `x` is defined on `Any`, then the only "static call" syntax is `Any.x`. Every other form is an **instance invocation**. E.g. `My_Type.x` invokes the instance method with `self=My_Type` (that's actually the current behavior). The same way `With_X.x` should be the instance invocation (that has to change for types that override `x`).

The only [identified drawback](https://github.com/orgs/enso-org/discussions/6216#discussioncomment-5593041) is that we don't have a way to invoke `With_X.x` statically. Let's ignore that, fix the above problem (which is really painful) and see whether we need to fix the _identified drawback_ as well (so far we aren't aware of any such need).

**Comment by somebody1234** [comment]
should the title say "instance method", not "static method", or am i just reading it wrong?

**Comment by wdanilo** [comment]
The discussion is not finished and we are chatting about this design with Radek actively. The change proposed by Radek is incompatible with how types are intended to work and this topic needs a lot more work/thinking before making such radical changes. We should revisit this topic in approx 1 week.

**Comment by JaroslavTulach** [comment]
> The change proposed by Radek is incompatible ... radical ... needs more thinking ...

@wdanilo please note that this issue isn't implementing Radek's proposal. **No incompatible** changes, **no syntax** changes, **no radical** changes.

This issue proposes **minimal** change and only affects how **methods defined on `Any`** behave. There is _just a few_ methods on `Any` - e.g. the impact of this change is very limited.

> We should revisit this topic .... (later)

We already have at least three duplicates and counting. The current behavior of `Any`-methods on `Type` object is contra-intuitive and we need a fix. The proposed fix isn't affecting non-`Any` methods - e.g. the main topic of the #6216 discussion isn't affected by the change proposed in this issue. Please let us move on, let us prepare a PR for review. Continue thinking, discussing #6216 in parallel.

**Comment by JaroslavTulach** [comment]
I've just chatted with @wdanilo and Wojciech is fine with us implementing this issue, as long as it only affects dispatch of methods defined on `Any`.
