### ISSUE TITLE
Letter "t" is underlined

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#6311]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Every instance of the lowercase letter "t", no matter which UI element it is in, is underlined

### Expected behaviour

No underline

### How we can reproduce it?

1. Open IDE
2. Open any project

### Screenshots or screencasts

![image](https://user-images.githubusercontent.com/4046547/232487164-75180aa1-4018-40d9-b95d-cdeda00d6a2c.png)

### Enso Version

recent build from develop

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

Linux 6.2.9-zen1

**Comment by somebody1234** [comment]
i think it's been like this the entire time for me, not sure if it's just flown under everyone's radar or maybe it was so low priority that nobody thought to report it?

unless it's a problem with my specific setup

**Comment by vitvakatu** [comment]
Duplicate of #6061

**Comment by somebody1234** [comment]
ah, of course, thanks

**Comment by somebody1234** [comment]
(not planned because it's a duplicate)
