### ISSUE TITLE
Invalid WASM modules, apparently size-related

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#6315]
We have started encountering invalid WASM modules in the `./run wasm test` build. They seem to be triggered by quantity of debug info, rather than anything specific in the application.

When built in this mode (with debuginfo=2), our main WASM module is over 5GB. AFAICT the module should not violate anything in the WASM binary format specification; while most numeric types in the file format are constrained to 32-bit values, I don't believe the specification calls for any absolute offsets into the file, and our individual sections are within the 2^32-byte limit. Therefore I think this may represent a bug somewhere in the toolchain in the handling of large WASM modules.

**Comment by jdunkerley** [comment]
Closing as GUI1
