### ISSUE TITLE
Join throws many "GL errors"

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6320]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Whenever I'm placing Join method I'm getting bunch of GL errors:

```[26212:0417/215009.751:ERROR:gl_utils.cc(398)] [.WebGL-00003AFC06691B00] GL_INVALID_OPERATION: Error: 0x00000502, in ..\..\third_party\angle\src\libANGLE\renderer\d3d\VertexDataManager.cpp, reserveSpaceForAttrib:520. Internal error: 0x00000502: Vertex buffer is not big enough for the draw call.
[26212:0417/215009.751:ERROR:gl_utils.cc(398)] [.WebGL-00003AFC06691B00] GL_INVALID_OPERATION: Error: 0x00000502, in ..\..\third_party\angle\src\libANGLE\renderer\d3d\VertexDataManager.cpp, reserveSpaceForAttrib:520. Internal error: 0x00000502: Vertex buffer is not big enough for the draw call.
[26212:0417/215009.766:ERROR:logger.cc(46)] Too many GL errors, not reporting any more for this context. use --disable-gl-error-limit to see all errors.
```

eventually (usually 3rd or 4th join) engine crashes i get this partial line:

```
[29508:0417/215657.798:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is
```

and no further working with Enso is possible.

### Expected behaviour

Join working

### How we can reproduce it?

read some large CSV file like one from BC10
and try to inner join it 

### Enso Version

2023.04.15

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

11pro 22H2

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop

**Comment by xvcgreg** [comment]
At this point it's also triggered by changing project name:



https://user-images.githubusercontent.com/108271897/232599264-85f29ebd-fcf4-42d3-9681-4dcd419bb58a.mp4

**Comment by xvcgreg** [comment]
@kazcw What caused this regression? Please update this information.

**Comment by xvcgreg** [comment]
Log from todays build 
[log for 6320 regression build 2023.04.18.txt](https://github.com/enso-org/enso/files/11259448/log.for.6320.regression.build.2023.04.18.txt)

**Comment by kazcw** [comment]
It was caused by #6202. I tested it on Linux, possibly no one tested in on Windows.
