### ISSUE TITLE
Investigate Behaviour of Collapsed Functions in IDE

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6323]
Create a set of 4 nested functions.
@jdunkerley has a Lorem Ipsum example of exactly this.

- [x] Want to be able to explore through each layer.
- [x] Need to be able to move up and down smoothly.
- [x] Need to be able to easily test the grouped nodes.
- [x] Make sure if low level changes propagates correctly.
- [x] Ensure supports for project rename.

**Comment by 4e6** [comment]
The interrupted exception can be caught with the `Standard.Visualization.Helpers.recover_errors`
```
[trace] [2023-04-24T14:36:03.676Z] [enso] Visualisation computed c559c625-ce4e-4c38-bda6-bd1154f58659 ===start visualization
Success({"error":"org.enso.interpreter.runtime.control.ThreadInterruptedException"})
===end visualization.
```
The engine thinks that the visualization was successful and sends the result to the IDE as a successful response
