### ISSUE TITLE
Dropdown not shown on a node on opening a simple project, appears when clicked into.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6324]
https://user-images.githubusercontent.com/4699705/232742627-270bb14e-48e5-4b9c-aa07-e233eae368f6.mp4

The `Table.get` should show a dropdown of the column names.
If edited the dropdown appears.

On Windows 11 Pro with newest develop as of 18th April.

**Comment by farmaazon** [comment]
Tried similar cases, but always got the drop down. I will try to replicate the exact graph from the clip.

**Comment by farmaazon** [comment]
I was unable to reproduce it on the 6d3151f32da9367790e8635036ccb1f31b4b254d even on the original project (with stripped metadata, but could it influence the drop downs?). @jdunkerley do you still reproduce it on 04-20 nightly?

**Comment by sylwiabr** [comment]
I can reproduce it with today nightly (20.04) on MacOS for a Restaurants template. Here is the video.

https://user-images.githubusercontent.com/12892578/233347065-8d8397f7-4cb1-488d-9f92-c3e8a5cb8476.mov

**Comment by jdunkerley** [comment]
Still there for me on the newest build
![image](https://user-images.githubusercontent.com/4699705/233348848-459a27af-9c6f-45c5-8493-a4cb49bb155c.png)

**Comment by farmaazon** [comment]
Indeed, Restaurants example shows me the bug.

**Comment by farmaazon** [comment]
I checked the message exchange, and seemingly we attach visualization properly, but don't get the response with column list. I attach the binary messages we get.

[binary_messages_on_vis_problem.txt](https://github.com/enso-org/enso/files/11287875/binary_messages_on_vis_problem.txt)

The visualization is attached at expression "11a08ea5-df1b-414d-8cd5-bab19edc18a9"

Handling to the engine.
