### ISSUE TITLE
If you add a node from the CB with just a existing operator when editing it gets deleted.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6325]
https://user-images.githubusercontent.com/4699705/232743125-0423da9f-8476-453d-a889-bc8896cc73be.mp4

To reproduce:
- Click the +
- Scroll down and pick an existing node
- The node will link (and may or may not render the text)
- Enter the node in edit mode and then Ctrl-Enter
- The node is deleted.

Windows 11 Pro, newest develop build as of 18th April.

**Comment by farmaazon** [comment]
Reproduced, get error from Searcher Controller "Expected a single line, parsed none".

**Comment by kazcw** [comment]
#6347 seems to fix this (by rewriting the file that had the bug)

**Comment by vitvakatu** [comment]
@kazcw what file do you mean?

**Comment by kazcw** [comment]
> @kazcw what file do you mean?

The bug does not seem to occur after that PR. That PR replaces (among other things) much of the node input area code, which seems like the likely location of the bug.

**Comment by farmaazon** [comment]
Indeed, is not reproducible anymore.
