### ISSUE TITLE
Add `create_database_table` to Database Table

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6327]
This should allow for direct creation of a DB table based on a constructed DB query.

It should have the same API as #6326.

**Comment by radeusgd** [comment]
Clarifying the spec:

I assume the idea here is to avoid materializing the data and use an INSERT+SELECT query here.

If the target connection is different from the source, it will still fail and require explicit materialization of data (as inter-database transfer is not possible).

**Comment by jdunkerley** [comment]
Yes this should be on the same backend for this ticket. If a mixed backend we should error and require the user to be explicit.

A `SELECT ... INTO <New_Table>` should work.
