### ISSUE TITLE
IDE crash when opening a CB

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6328]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://user-images.githubusercontent.com/12892578/232745507-48976150-38a4-4784-a07e-8c5b21b36b78.mov

### Expected behaviour

CB should be opened

### Enso Version

2023.1.1-nightly.2023.4.18

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by xvcgreg** [comment]
Confirmed on Windows. Opening CB through tab, + sign and by dragging connection crashes. With the same error as in https://github.com/enso-org/enso/issues/6320

**Comment by wdanilo** [comment]
Wait, the real error is here: 
<img width="297" alt="image" src="https://user-images.githubusercontent.com/1623053/232753375-1904c1c7-93bc-4abc-8b51-35922121c796.png">

We are not handling lost contexts good yet. Context is lost when the operating system takes it from our application. This is not a new bug, it happens sometimes, rarely. It's interesting that both of you encountered it the same day. 

@sylwiabr you've clicked "Permanent – Ocurring repeatably" - are you able to reproduce it constantly? Can you reproduce it after restarting your computer?

@xvcgreg the error you mentioned is different than what Sylwia mentioned. So what error you are getting ?

**Comment by sylwiabr** [comment]
After restarting the computer it is still happening. Here are the videos with logs and performance monitor:

https://user-images.githubusercontent.com/12892578/232762064-7fe3e380-1d0f-43a0-b30c-d73506b60504.mov


https://user-images.githubusercontent.com/12892578/232762144-56426d09-4306-44a5-aeba-396fabc45840.mov

**Comment by xvcgreg** [comment]
before restart: 

enso v2023.04.18

https://user-images.githubusercontent.com/108271897/232768432-fc6b296d-4fea-473e-b0cb-312fa8d0978f.mp4

**Comment by sylwiabr** [comment]
The first nightly package where I am observing this issue is from 15th of April.
I looks like it is one of the commits: 
![image](https://user-images.githubusercontent.com/12892578/232770011-658e0b1d-dc4a-49e2-ae69-9ad67662b2bd.png)

**Comment by xvcgreg** [comment]
Error:
![image](https://user-images.githubusercontent.com/108271897/232776649-24d08e65-b4fd-41e1-99f8-30a3dce2ccb4.png)

Full video:

https://user-images.githubusercontent.com/108271897/232776702-f521eb63-f903-43a8-882f-35e37d081a9d.mp4

Log:
[2304181349_log.txt](https://github.com/enso-org/enso/files/11261702/2304181349_log.txt)

**Comment by xvcgreg** [comment]
I have also screengrab with process explorer if needed I can share it

**Comment by xvcgreg** [comment]
I have tried to reproduce the error that Sylwia is getting on her Mac on my Windows machine. Doing the same actions Sylwia did I get different results. The different errors can be seen in the post above. 

On top of that, I got no errors when restarted the computer and launched Enso for the first time after the restart:
Here's a video of Enso behavior before the restart:

https://user-images.githubusercontent.com/108271897/232794993-e3fd5ad2-b1b7-4153-b3cd-3fcbf3351be9.mp4

And here is a video of Enso behavior after the restart:

https://user-images.githubusercontent.com/108271897/232795102-56ae5bc1-f2b6-4d28-99c3-0c9196bcf777.mp4

No errors whatsoever.
I have shut Enso down and launched it again. Now I could observe errors once again:

https://user-images.githubusercontent.com/108271897/232795676-cc04c59d-8333-4f17-bc74-2e56bf29a4be.mp4

I have repeated this process 2 more times (restarting the machine and launching Enso consecutively several times). This time with no Errors to observe. I have 3 more videos but those do not contain any errors - I can share those if needed.

Enso 2023.04.18
Win 11pro (updated to most recent version)
XPS i9 12th gen laptop with RTX 3060

**Comment by kazcw** [comment]
I think this likely is the Mac version of #6320, however I can't test on Mac.

**Comment by wdanilo** [comment]
@kazcw @xvcgreg is using Windows FYI

**Comment by sylwiabr** [comment]
The issue was solved with 912556853f17325f37287f791f418831eb53c479
