### ISSUE TITLE
Deselection of dropdown on an argument does leaves some edges misaligned

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6333]
### What type of issue is this?

Permanent – Ocurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![Screenshot from 2023-04-18 10-55-17](https://user-images.githubusercontent.com/292128/232765392-405f5898-d606-4eb5-9e7f-0f6aeeeb21b8.png)

Apparently we are missing some trigger that recalculates sizes.

### Expected behaviour

Should adapt to the node change.

### How we can reproduce it?

1. Pick some node with default arguments or suggestions for the dropdowns. 
2. Connect it to some other node close by.
3. Select one choice.
4. Deselect the choice.

### Screenshots or screencasts
[Kazam_screencast_00000.webm](https://user-images.githubusercontent.com/292128/232779643-fd061770-5f0b-45a5-9740-f24d81bd47fe.webm)

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by hubertp** [comment]
This is apparently known and will be potentially fixed by recent work by @Frizi.
Filed the ticket so that it is not forgotten.

**Comment by wdanilo** [comment]
I can confirm that @Frizi work seems to resolve it!

**Comment by farmaazon** [comment]
Indeed, I cannot reproduce it anymore.
