### ISSUE TITLE
When editing/adding a node with just a number, placeholders for invalid arguments appears

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6349]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![image](https://user-images.githubusercontent.com/12892578/233000229-93a54c26-2c28-4756-9357-4557dee7cf76.png)

The grayed out args are appearing quite often when the node is created. When it is changed with `cmd+click` the fields remains.

### Expected behaviour

just a number

### Enso Version

fa995dd765f55fd6a30295b8c44654df1f249f67

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
I haven't reproduced it completely. I see sometimes the grayed-out ports, but they always disappear after short time. @sylwiabr this is likely timing-dependent, if you reproduce it reliably, please create a screencast.

The cause seems to be the Visualization Preview: we put the preview code to the node, receiving information about ports. Then, if we quickly write a number and press enter, we should see still the ports until the engine updates the node again. 

I have no idea how to fix that in our current architecture.

**Comment by sylwiabr** [comment]
https://user-images.githubusercontent.com/12892578/233326928-733ec3a3-6dfd-43fa-bb76-7495fdde707b.mov

@farmaazon it's not happening every time but quite often.

**Comment by wdanilo** [comment]
As agreed via call with @farmaazon, we should probably in GUI understand what was the change. If the change was affecting the method or the self argument, all port info should be cleared before we get update from engine. Is this the current plan @farmaazon ?

**Comment by farmaazon** [comment]
Yes, probably clearing "method_call" field in "computed_value_info_registry" on changes mentioned above will help.

**Comment by farmaazon** [comment]
@radeusgd discovered a reproduction scenario of _stuck_ gray ports: https://discord.com/channels/401396655599124480/1120654472222347304/1121401780241174598

<blockquote><img src="undefined//discord.com/assets/652f40427e1f5186ad54836074898279.png" width="48" align="right"><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/channels/401396655599124480/1120654472222347304/1121401780241174598">Discord - A New Way to Chat with Friends & Communities</a></strong></div><div>Discord is the easiest way to communicate over voice, video, and text.  Chat, hang out, and stay close with your friends and communities.</div></blockquote>

**Comment by farmaazon** [comment]
Should not happen anymore in GUI2 - there we use different mechanism for displaying previews, so no node should get "intermediate" method calls.
