### ISSUE TITLE
Can't open performance monitor when dev console is opened

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6351]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I am running application with dev tools opened (`-debug.dev-tools `) I can not open our internal performance monitor through the shortcut. There is no problem without the dev console.

### Expected behaviour

Shortcuts should work as expected

### Enso Version

fa995dd765f55fd6a30295b8c44654df1f249f67

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by wdanilo** [comment]
@sylwiabr just to double check it - are you sure the focus is in GUI and not in the dev console when you try this shortcut?

**Comment by sylwiabr** [comment]
@wdanilo you are right. When I am opening enso with dev console it has focus on the console, not the GUI. Thanks.
