### ISSUE TITLE
Hiding Windows console during Enso launch 

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6360]
### How important is this feature to you?

2 – Somewhat important, but I can live without it

### Describe the idea you'd like to see implemented.

During the launch of Enso on Windows, Windows Console pops out alongside Enso. We need to disable it so it's not visible to the user. 

Side note: closing this console renders IDE loosing the connection to the engine.

### Screenshots, screencasts, mockups.

https://user-images.githubusercontent.com/108271897/233199356-26d30cd5-41f5-442f-8efd-6884e4520d4c.mp4

### Would you be willing to help us implement this feature?

No

**Comment by farmaazon** [comment]
@mwu-tow can you estimate how hard it is to implement?

**Comment by mwu-tow** [comment]
@farmaazon 
> @mwu-tow can you estimate how hard it is to implement?

Should be simple.

**Comment by wdanilo** [comment]
I believe that this ticket in its current description form is invalid and we should not implement it. I don't like the idea of "hiding Windows console during Enso launch". Instead, the console should never be opened when double clicking on the launcher. Both visible console, as well as hidden console (that is visible for a moment or visible in the task bar) are bad designs.
