### ISSUE TITLE
Nodes disappear during renaming of the project

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6373]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

During renaming of the project the last edited node will disappear. 

### Expected behaviour

Nodes must not be modified during renaming.

### Screenshots or screencasts

[Kazam_screencast_00002.webm](https://user-images.githubusercontent.com/292128/233422372-6472a91a-b27c-4658-b28e-6d3cdc19957d.webm)

Apologies for the fragment of the screen only; something is weird with my resolution when recording. But you can see see the node disappearing. 

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by vitvakatu** [comment]
It's funny, it disappears because you had it selected and pressed `Backspace`, which is a shortcut for node deletion. The easy fix would be to unselect nodes when starting editing the project name (I believe we already unselect everything when the node is edited)

**Comment by hubertp** [comment]
> It's funny, it disappears because you had it selected and pressed `Backspace`, which is a shortcut for node deletion. The easy fix would be to unselect nodes when starting editing the project name (I believe we already unselect everything when the node is edited)

:)

I would expect the focus to switch to the thing that I'm editing i.e. name of the project.

**Comment by wdanilo** [comment]
@hubertp that's right, that's a bug on our end, but at least we know the cause of it now :)
