### ISSUE TITLE
Unusual GPU behavior while circling mouse over CB

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6376]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While circling mouse over CB the performance of application (measured in FPS here) drastically drops - same drop can be observed with GPU utilisation. It seems that GPU is not being served data fast enough to be utilized to its full potential.

Observe this GPU as it's the one handling Enso:
![Screenshot 2023-04-21 080115](https://user-images.githubusercontent.com/108271897/233552733-c8b7110b-dfc0-4e6b-99b0-20f96989abb2.png)

### Expected behaviour

With fast selector switching over components GPU should be utilized more not less due to more data to be processed and displayed.

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/233552440-a2026890-aa73-437b-b585-b2a7c446156c.mp4

### Enso Version

2023.04.20

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by sylwiabr** [comment]
Performance drop was also observed by us yesterday on @jdunkerley computer during the demo.

**Comment by sylwiabr** [comment]
Actually I can observe the same behavior on my Mac with the package from 21.04.2023

**Comment by jdunkerley** [comment]
Opening the component browser feels a lot more sluggish than it did a few weeks ago.

Appears to take a while to render even on second opening now.

**Comment by wdanilo** [comment]
@jdunkerley as we agreed, would you be able to locate which PR introduced it? Or anyone else assigned by you of course. We need to investigate what happened there.

**Comment by xvcgreg** [comment]
@wdanilo @jdunkerley 

I'm already checking the versions as I'm recording the 101 vid. But it's tricky. Here are my findings so far:
Nightly 2023.4.22.1 - CB selector animation laggy, DocPanel snappy (slower CB start)
Nightly 2023.4.21 - CB selector animation laggy, DocPanel snappy (slower CB start)
Nightly 2023.4.20 - CB selector animation laggy, DocPanel snappy (slower CB start)
Dev 2023.4.19 dev build Kaz fix 6339 - CB selector animation laggy, DocPanel snappy (fast CB start)
Nightly 2023.4.19 - CB selector animation laggy, DocPanel snappy (slower CB start)
Nightly 2023.4.18 - CB selector animation laggy, DocPanel snappy (fast CB start)
Nightly 2023.4.15 - CB selector animation laggy, DocPanel snappy (fast CB start)
Nightly 2023.4.14 - CB selector animation laggy, DocPanel snappy (fast CB start)
Nightly 2023.4.13 - CB selector animation laggy, DocPanel snappy (fast CB start)
Nightly 2023.4.12 - CB selector animation laggy, DocPanel snappy (fast CB start)
Nightly 2023.4.8 - CB selector animation laggy, DocPanel snappy (fast CB start)
Nightly 2023.4.7 - CB selector animation laggy, DocPanel snappy (fast CB start)
Nightly 2023.3.30 - CB selector animation laggy, DocPanel snappy (fast CB start)
Nightly 2023.3.29 - CB selector animation laggy, DocPanel snappy (fast CB start)
Nightly 2023.3.28 - CB selector animation laggy, DocPanel snappy (fast CB start)
Nightly 2023.3.25 - CB selector animation laggy, DocPanel snappy (okish CB start)
Nightly 2023.3.24 - CB selector animation laggy, DocPanel snappy (okish CB start)
Nightly 2023.3.23 - CB selector animation laggy, DocPanel snappy (okish CB start)
Nightly 2023.3.22 - CB selector animation laggy, DocPanel snappy (okish CB start)

//updated the list with proper namings and findings - I'll write more below

**Comment by wdanilo** [comment]
@xvcgreg interesting. If you'd be able to find exact date when faster/slower CB was shipped, this would help us debug it a lot. Between your dates there were probably different releases, so we just need info - "this exact release made it slower", "this exact release made is faster"

**Comment by xvcgreg** [comment]
@wdanilo sorry for not writing the full name of the build - those are recent Nightly builds - I use 0 after the first dot to have the proper ordering of directories when storing them on my drive.

**Comment by wdanilo** [comment]
I was not talking about exact build name. You've written "release from 2023.03.28 was fast, but release from 2023.03.25 was slow` - were there any releases in-between? If so, they need to be checked. If not, there should be information about it that these are consecutive releases.

**Comment by xvcgreg** [comment]
@wdanilo, there were no Nightly releases in between those two

**Comment by xvcgreg** [comment]
What I have found out is that the sluggish behavior of the Component Browser can be addressed to the selector changing its position in the CB over several methods. It can be observed here, and happens on all nightly builds (and one dev build) from last month (haven't tested further):

https://user-images.githubusercontent.com/108271897/234067686-1249ed57-a0d5-446f-b862-a53bb9157b8b.mp4

Please observe how GPU behaves on me fast-moving mouse over methods in one column. When I'm over greyed out components it has no impact on the GPU - when I switch to the cultured ones it seems to drop its performance on several functions quite regularly. 

_Builds tested can be seen on the list in the comment above._

**Comment by farmaazon** [comment]
This task is in "Design" state. @wdanilo are you working on it? Is it still reproducible after last performance improvements?

**Comment by xvcgreg** [comment]
> This task is in "Design" state. @wdanilo are you working on it? Is it still reproducible after last performance improvements?

@farmaazon Performance of CB got significantly better on fast mouse movement over components (even with the debugger turned on)


https://github.com/enso-org/enso/assets/108271897/8d525c91-c662-445c-9512-0567956deeed


recorded with Nightly 2023.6.28

**Comment by farmaazon** [comment]
Then I will close it as fixed. Probably Ilya's work on documentation helped here, maybe other performance work as well.
