### ISSUE TITLE
`Ctrl+r` is resetting the project to the default project template

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6377]
Pressing `Ctrl+r` in IDE is removing the project content and leaving just the default node.

package from 21.04.2023 on MacOS and Windows

**Comment by jdunkerley** [comment]
As we have no way to revert to previous versions this caused a loss of a workflow.

**Comment by jdunkerley** [comment]
This appears to be a "revert to saved state". This **must** ask the user to confirm before performing the action.

**Comment by vitvakatu** [comment]
This is not a regression, the shortcut has been there for a very long time. 
@sylwiabr do you have a vision of how we can fix it? Implementing confirmation would take a lot of time.

**Comment by sylwiabr** [comment]
Somehow before the `ctrl+r` was refreshing IDE and getting us to the Welcome Screen in a previous versions (see the nightly package from 20.4.2023). I would suggest changing shortcut to something less popular than ctrl+r so user will not accidentally perform the action and loose the work. What do you think @wdanilo?

**Comment by jdunkerley** [comment]
I think the typescript based shortcuts were covering it up so `Ctrl-R` was causing an electron refresh (now on Ctrl-Alt-Shit-R).

**Comment by wdanilo** [comment]
If `ctrl-shift-r` is refreshing electron now, what does `ctrl-r` do now? There has to be some logic there if we observe this behavior. I fully agree with Sylwia that any shortcut that makes the user lose the workflow is bad and we need to fix it.

**Comment by jdunkerley** [comment]
`Ctrl-R` resets the project back to the last checkpoint (which I think `Ctrl-S` stores).

**Comment by wdanilo** [comment]
Ok, then I believe we have the following things to do here:
1. refreshing electron should be `ctrl-alt-r` (as with all our debug shortcuts, it should start with `ctrl-alt`, as it is a developer-shortcut, not user-one).
2. We should create a popup asking if you want to get back to last saved snapshot. Until this is done, we can change the shortcut to `ctrl-shift-r` or something like that so it's not so easy to trigger. Of course, longer term, this should be done this way that when you switch to last saved checkpoint, a new checkpoint should be created before the switch which would allow you to switch back, but this would also require a view of list of checkpoints and managing a tree of checkpoints (not a flat list of them).

**Comment by farmaazon** [comment]
Let's put only the shortcut changes to scope of this issue, and make new issues for other ideas (asking user, and then full change-tree view).

**Comment by Procrat** [comment]
I've changed the shortcut in #6620 and created two issues for the other ideas:
- #6624 
- #6625
