### ISSUE TITLE
Ctrl Clicking into default node and then exiting causes the node to vanish

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6378]
https://user-images.githubusercontent.com/4699705/233607702-5f2c4179-d023-49a5-a2d4-64ec01044b7f.mp4

When I ctrl click into the node the node enters edit. When I click out it vanishes.

Windows 11 Pro, newest develop as of 21/4.
On MacOS the node blinks but doesn't disappear.

![image](https://user-images.githubusercontent.com/4699705/233608128-3ace3a63-912a-4f93-b3d8-bf18c08679aa.png)

**Comment by vitvakatu** [comment]
Seems like a duplicate of https://github.com/enso-org/enso/issues/6325

**Comment by MichaelMauderer** [comment]
Closing as duplicate of https://github.com/enso-org/enso/issues/6325, but we should check the condition after that issue is fixed.
