### ISSUE TITLE
Quick Viz Preview Shows Box But No Viz for Text viz

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6379]
If pressing Ctrl/Cmd we should see a nodes viz preview.
This not appearing with any content.

https://user-images.githubusercontent.com/4699705/233608701-e0f3c67e-0c48-4cd8-88ac-d473c0868444.mp4

It kind of flickers and is sometimes visible.

This doesn't happen for the Table viz.

Both on Windows and MacOS.

**Comment by hubertp** [comment]
I'm not really able to reproduce this. Is this standalone? What version? Can you share the project? Any errors in the logs?

**Comment by hubertp** [comment]
(from @jdunkerley)
Steps to reproduce:
- new project
- hold control down
- move over the bottom of default node
- open viz, change type to table
- close viz
- quick show now stable

**Comment by MichaelMauderer** [comment]
I can reproduce this on develop. Depending on the position of the cursor, the preview is either empty or flickering. 

https://user-images.githubusercontent.com/1428930/234838520-325b8b5b-e860-48a2-b7ea-22888837fb35.mp4

**Comment by MichaelMauderer** [comment]
I've tried to track down the offending commit, but it is older than b74debb151fdf8b1ce446e1dace12c0e0825583a so I won’t go back further.

**Comment by farmaazon** [comment]
I cannot reproduce _empty_ preview anymore, only the flickering (which seem to occur on both text and table visualizaitons).
