### ISSUE TITLE
Scrolling in the Documentation Panel is not working

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6385]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

After opening the Component Browser I cannot scroll the documentation panel (both mouse wheel and by holding scroll bar).

### Expected behaviour

Scrolling of the Documentation Panel working.

### How we can reproduce it?

Open CB with Tab key
Try to scroll the Documentation Panel

### Enso Version

2023.04.22.1

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

Version 112.0.5615.138 (Official Build) (64-bit)

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by vitvakatu** [comment]
Probably #6364 is at fault, I will check it.

**Comment by xvcgreg** [comment]
Present also in 2023.04.21
Not occurring in 2023.04.20

**Comment by wdanilo** [comment]
99% sure this is caused by prevent default. It seems we should call prevent default only on some selected events, like `tab` key, but not e.g. arrow keys (to scroll docs). Also, @vitvakatu please checkin scrolling works in the performance monitor details view (after selecting draw calls there is a long list of draw calls that should be scrollable). Probably it is also affected by this change.

**Comment by wdanilo** [comment]
Btw, how Q/A did not catch it? Scrolling docs is a natural thing to check when changing events behavior I think.

**Comment by farmaazon** [comment]
> Btw, how Q/A did not catch it? Scrolling docs is a natural thing to check when changing events behavior I think.

I think the answer is here: https://github.com/enso-org/enso/pull/6364#issuecomment-1516381143

**Comment by wdanilo** [comment]
> > Btw, how Q/A did not catch it? Scrolling docs is a natural thing to check when changing events behavior I think.
> 
> I think the answer is here: [#6364 (comment)](https://github.com/enso-org/enso/pull/6364#issuecomment-1516381143)

Ha! Good catch!

**Comment by vitvakatu** [comment]
Yep, my change is the problem, we don't need to prevent default for mouse events. 
> Also, @vitvakatu please checkin scrolling works in the performance monitor details view (after selecting draw calls there is a long list of draw calls that should be scrollable). Probably it is also affected by this change.

I was specifically checking that, it works either way (if we prevent default and if we don't). The documentation panel slipped through, though.

**Comment by wdanilo** [comment]
@vitvakatu the perf monitor is affected as well, right? Anyway, let's fix that and don't prevent mouse events. Also, what with arrow keys (my question above).

**Comment by vitvakatu** [comment]
> the perf monitor is affected as well, right?

No, it does not seem to be affected. It scrolls on develop, while the documentation panel doesn't.

> Also, what with arrow keys (my question above).

We never supported scrolling with arrow keys, did we?

**Comment by wdanilo** [comment]
Interesting that it works. OK then. Regarding arrow keys - why not just preventing default if the key is not arrow? This will allow for scrolling with arrows right?

**Comment by vitvakatu** [comment]
> Regarding arrow keys - why not just preventing default if the key is not arrow? This will allow for scrolling with arrows right?

No, because it conflicts with component browser hotkeys, arrow keys are used to navigate in the component list. We don't have focus management in the CB, so currently it is not possible.

**Comment by farmaazon** [comment]
**QA:**: @farmaazon
