### ISSUE TITLE
Unexpected behavior on the first launch of the Component Browser 

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6386]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When Component Browser is opened for the first time just before project is fully initialized it's: 
- not loading components
- mouse freezes 
- cursor takes very narrow shape (like it's squashed)

### Expected behaviour

Component Browser - even when opened before it's ready state should display "loading" spinner and load all of it's components once it's ready. Also mouse should not be frozen.

### How we can reproduce it?

Open CB just before project name becomes initialized.

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/233976476-02a35487-eb47-493e-b4bb-f4eaa0f69005.mp4

### Enso Version

2023.04.22.1

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

Version 112.0.5615.138 (Official Build) (64-bit)

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by wdanilo** [comment]
Oh, that's right. I thought we had issue for that. This is serious. I encountered it multiple times always thinking that something is broken. Clients will think the same.

**Comment by farmaazon** [comment]
It should be not possible to reproduce once the loading spinner lands.

**Comment by sylwiabr** [comment]
@xvcgreg can you still reproduce it?

**Comment by xvcgreg** [comment]
@sylwiabr, no I cannot reproduce it anymore (tried on monday build and on todays). Closing this issue.
