### ISSUE TITLE
Different zoom steps for ctrl + mouse wheel up/down

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6389]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When zooming out with ctrl + mouse wheel user gets different behaviors on zoom out and zoom in. It seems that zoom in skips one step of zoom level.

### Expected behaviour

Zoom in and out are stepping the same way, not skipping any steps.

### How we can reproduce it?

- press ctrl and zoom out with mouse wheel twice (two levels)
- press ctrl again and zoom in once (nodes will be same size as at the start of this repro steps)

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/233984412-dc3b9f8e-7baa-47a6-abc1-e796494e0dc2.mp4

### Enso Version

2023.04.20

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

Version 112.0.5615.138 (Official Build) (64-bit)

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by wdanilo** [comment]
@xvcgreg Open this in your chrome please: https://jsfiddle.net/L21kd3vs/

Open "console" on the right bottom of the right bottom window. In the white area, use your mouse wheel up, and then down. Then copy the output here, please.

<blockquote><div><strong><a href="https://jsfiddle.net/L21kd3vs/">Mouse Event - JSFiddle - Code Playground</a></strong></div><div>Test your JavaScript, CSS, HTML or CoffeeScript online with JSFiddle code editor.</div></blockquote>

**Comment by xvcgreg** [comment]
wheel up (forward):
```  &lt;/body&gt;&lt;/html&gt;,
  type: "wheel",
  view: [circular object Window],
  wheelDelta: 150,
  wheelDeltaX: 0,
  wheelDeltaY: 150,
  which: 0,
  x: 410,
  y: 178
```

wheel down (backward):
```
  &lt;/body&gt;&lt;/html&gt;,
  type: "wheel",
  view: [circular object Window],
  wheelDelta: -150,
  wheelDeltaX: 0,
  wheelDeltaY: -150,
  which: 0,
  x: 473,
  y: 215
```

**Comment by wdanilo** [comment]
Interesting. OK, indeed, this is a bug then.

**Comment by hubertp** [comment]
@farmaazon Can you re-assign to the appropriate person in the team, please?

**Comment by xvcgreg** [comment]
it's still reproducible in Nightly 2023.7.4

**Comment by wdanilo** [comment]
Low priority for now, let's keep it open.

**Comment by farmaazon** [comment]
In GUI2 the steps seem to be the same... The only problem I see is that they're huge and skip 100% - Reported as #9177
