### ISSUE TITLE
Component Browser creates node not visible in the graph editor until Enso restart

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6395]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I open project that I have worked previously on it opens with one additional node in the scene. It seems that the Component Browser on close with esc key leaves something behind that's not shown in the graph editor. I have managed to reproduce it when I have opened project created on earlier version of Enso (2023.3.25) with a newer one (this time it was 2023.4.18). Also I have noticed it on several other occasions but always assumed I have closed the CB wrongly, please watch attached video when I restart Enso several times and the node appears back.

### Expected behaviour

When I delete a node it stays that way - deleted.

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/234004034-f8643df9-b6f4-46f2-ab52-e00a17697a09.mp4

### Enso Version

2023.4.18

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by wdanilo** [comment]
@xvcgreg please record logs as well.

**Comment by farmaazon** [comment]
We have function `restore_temporary_changes` in module model. I don't know why just don't call it on project open - it should fix this issue.

**Comment by wdanilo** [comment]
@farmaazon but the issue is that when creating the node in component browser it disappears immediately (see the Gregs video).

**Comment by vitvakatu** [comment]
It looks to me that the project is not saved between restarts, and we always see the same node on the video.

**Comment by farmaazon** [comment]
> @farmaazon but the issue is that when creating the node in component browser it disappears immediately (see the Gregs video).

No, the task description is completely different:

> When I open project that I have worked previously on it opens with one additional node in the scene. It seems that the Component Browser on close with esc key leaves something behind that's not shown in the graph editor. I have managed to reproduce it when I have opened project created on earlier version of Enso (2023.3.25) with a newer one (this time it was 2023.4.18). Also I have noticed it on several other occasions but always assumed I have closed the CB wrongly, please watch attached video when I restart Enso several times and the node appears back.

As I understand, the node disappears in the video, because Greg is pressing Esc. The problem is that the node reappears.

@xvcgreg could you confirm?

**Comment by xvcgreg** [comment]
A mix of those two worlds actually. I spotted this issue the first time when I have been recording 101 vid and mistakenly typed the wrong function in the node. I pressed the ESC key to abort node creation, closed the project, and saw the node that creation I have previously aborted present on the next open of the project.

In the video above I'm deleting this node, and somehow the project isn't saving this change between sessions.

**Comment by hubertp** [comment]
In general, all pending file saves are forced on project close. So if the project was closed correctly you shouldn't see any difference. It would probably be good to verify it with the logs and the contents of the project after it is closed but before it is re-opened.

**Comment by xvcgreg** [comment]
I have launched today's Enso build and was greeted with this issue (a node that was not there when I left that project 2 days ago). I tried to reproduce it today with recording and logging on but failed to do so in 30mins of tries. As soon as I will catch it on camera with logs I'll post it here.

**Comment by hubertp** [comment]
Tried to reproduce but no avail. Will dig into implementation to see if this is really possible on the `language-server` side.

**Comment by hubertp** [comment]
@xvcgreg @sylwiabr If you notice this again, please reopen.
