### ISSUE TITLE
Enso workspace - go to project dashboard button

### ISSUE THREAD

**Issue by PabloBuchu** [enso-org/enso#6399]
According to the figma https://www.figma.com/file/3Vu3tEXwASy8hY8Hb86U54/ide2-v42.2-(Copy)?node-id=0-1&t=F8CR4ErlVSaHHFQA-0 in the top left corner we should have a `hamburger button` which will take user back to the dashboard view

To have that working we need the IDE to emit an event after user hit that button that could be captured by dashboard in js layer and just do some hide/display logic in the DOM.

@somebody1234 is there anything specific related you want to add?

**Comment by somebody1234** [comment]
not really - but i should mention that there's currently a sliding hamburger animation (that's hidden by the loader anyway, so *very* low priority to get working), but not sure whether the IDE team is planning on adding an identical slider, or whether the implemention should maybe be changed on the dashboard side

**Comment by somebody1234** [comment]
an ideal solution would probably be to let the IDE always render the top bar, but i don't think that's *actually* an option, especially since the IDE will potentially have to load different versions when opening different projects

**Comment by somebody1234** [comment]
(off-topic, but it looks like this new mockup has *massively* improved UX, which is really cool)

**Comment by wdanilo** [comment]
This button should be coded in Rust and emit JS signal for you guys. We are talking about this button:
<img width="25" alt="image" src="https://user-images.githubusercontent.com/1623053/234267957-5d38aaf5-1d7a-4292-a2e9-fa8436c9b43b.png">

**Comment by vitvakatu** [comment]
@PabloBuchu @somebody1234, do you have ideas on how we need to implement such an event so you guys can capture it? A short JS snippet would be ideal.

**Comment by somebody1234** [comment]
not sure if there's a more *correct* way, but:
```js
// to verify that it works:
// document.addEventListener('ide-close', console.log)
document.dispatchEvent(new Event('ide-close'))
```
it can be on any element though - but it does make things easier if it bubbles from whatever element it belongs on:
```js
theButton.dispatchEvent(new Event('ide-close', { bubbles: true }))
```
To test:
```js
document.addEventListener('ide-close', console.log)
// dispatched on a different element
document.body.dispatchEvent(new Event('ide-close', { bubbles: true }))
```
i guess ensogl doesn't actually have DOM elements for specific things so it doesn't really matter where it's dispatched - `document`, `document.body`, `window`, or a `new EventTarget()` on the wasm API (if that's possible) would all be fine
