### ISSUE TITLE
Notify user when downloading new engine version

### ISSUE THREAD

**Issue by Procrat** [enso-org/enso#6402]
### Discord username

Stijn#6455

### How important is this feature to you?

0 – Not too important

### Describe the idea you'd like to see implemented.

Recently, we started showing a spinner when opening or creating a project. We could continue to improve on the user experience there by displaying a message whenever we download a new version of the engine since this would incur some extra loading time.

### Would you be willing to help us implement this feature?

Yes

**Comment by farmaazon** [comment]
No longer valid: currently, we don't download engine.
