### ISSUE TITLE
Renaming of project folder under Windows fails to rename Unnamed to desired name

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6406]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When changing the name from default to "Enso_101" (previously worked) the project folder remains unnamed.

See the log:
[rename log.txt](https://github.com/enso-org/enso/files/11314393/rename.log.txt)

### Expected behaviour

Folder containing project should be renamed along the project on given change.

### Enso Version

2023.4.22.1

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by hubertp** [comment]
This is as expected. Once you close Enso, the finalizer of language server will do the actual move of the folder. It's not possible to move the folder while it is still up and running.
