### ISSUE TITLE
Review the Widget set up for Public APIs and Improve Stuff (May)

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6410]
Task list of little things:
- [x] `SQLite_Format.For_File` should fail early if the file is not a SQLite DB. Include checking an empty file. [@radeusgd]
- [x] `Data.read` should error if the file does not exist (for all file types). [@radeusgd]
- [x] Update defaults on `Table.join` (Inner->Left_Outer, join by first column name instead of index) [@radeusgd]
- [x] Remove the `_` from the join `right_prefix` and also from `NameDeduplicator` [@radeusgd]
- [x] `Date_Range` type and support for `up_to` / `down_to` on `Date`. #6543 
- [x] `tokenize_to_columns` or `parse_to_columns` results in a single column we shouldn't add the ` 1`. [@GregoryTravis]
- [x] Add tests for `Date.until`, `Date.next` and `Date.previous`. [@GregoryTravis]
- [x] Row count status line on Table viz is really annoying [@jdunkerley]
- [x] Table visualization of a function should be `<Function>` not `{Error object}`. [@jdunkerley]
- [x] Render null in Table viz as light grey `null`. [@jdunkerley]
- [x] Rendering of the Vector of weekday versus Table of weekday in Table viz [@jdunkerley]
- [x] Row .get doesn't have a drop down or Table vis. [@jdunkerley]
- [x] Experiment with delimiter drop down. [@jdunkerley]
- [x] Add delimiter dropdown to `split` functions. [@jdunkerley]
- [x] `rename_columns` to allow a Vector of Pairs (should error if mixed) and have a widget to design [@jdunkerley]
- [x] Refresh the dropdown set up on Table. [@jdunkerley]
- [x] Custom dropdown for take and drop on Text. [@radeusgd]
- [x] take/drop defaults for Sample and Every. Additionally should report error more gracefully for constructor of valid type. [@radeusgd]
- [x] Add drop down for Locale like `Encoding`. [@GregoryTravis]
- [x] Look at `set` vs `add_column` / `update_column`. Add ALIASes. [@jdunkerley]
- [x] `.tables` on a connection does not accept a single value for Sqlite (e.g. 'TABLE') - dropdown supplies single values! [@jdunkerley]
- [x] Add decode methods to HTTP Response and Body allowing easier parsing. [@jdunkerley]
- [x] Remove the custom filter drop down as not needed any more. [@jdunkerley]

** Others moved to June. **

**Comment by jdunkerley** [comment]
On auto Date Parsing from @radeusgd:

I think one thing I'd really like to see here is to ensure we don't confuse dd-mm-yyyy with mm-dd-yyyy - so if from the data it cannot be conclusively inferred*, we should at least produce a warning about it or maybe even error? because it's quite a possible data corruption

*we can infer it if we have entries like 12-30-2022 because the 30 cannot ever be a month

**Comment by radeusgd** [comment]
The https://github.com/tsegall/fta library may be worth looking at for Date parsing - it provides pretty neat date format detection.

<blockquote><img src="https://opengraph.githubassets.com/da24fd83036fb457c56a013b7de58e455ca3b1fe5e060623795fb5030d794ee3/tsegall/fta" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/tsegall/fta">GitHub - tsegall/fta: Metadata/data identification Java library. Identifies Semantic Type information (e.g. Gender, Age, Color, Country,...). Extensive country/language support. Extensible via user-defined plugins. Comprehensive Profiling support.</a></strong></div><div>Metadata/data identification Java library. Identifies Semantic Type information (e.g. Gender, Age, Color, Country,...). Extensive country/language support. Extensible via user-defined plugins. Comp...</div></blockquote>

**Comment by radeusgd** [comment]
As [noted on Discord](https://discord.com/channels/401396655599124480/1109054956612370442/1111357796710109305), `Vector.new_builder` is currently not hidden in the GUI. But such stateful computations are unusable in the GUI mode. Shall we hide it by adding `PRIVATE ADVANCED`?

**Comment by radeusgd** [comment]
re: inexhaustive pattern match better errors

We should be able to just adapt the solution take/drop uses:
![image](https://github.com/enso-org/enso/assets/1436948/a1373bd4-86f4-44cf-94a8-fba7cfbddb34)

The method is already rather re-usable, just need to replace `range` in the error message with sth generated from expected types.
