### ISSUE TITLE
Pressing `ctrl+click` to start edit a node and then clicking in the background is replacing the content with the content from previously edited node

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6411]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [x] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://user-images.githubusercontent.com/12892578/234248457-5d646a37-b70f-44e2-aa91-944efceb7d20.mov

### Expected behaviour

Content of the node should not change.

### How we can reproduce it?

1. open new project
2. add a node
3. start editing the added node and click on the background
4. start editing the default node and click on the background without any changes to the node content

### Enso Version

Nightly 25.04.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by sylwiabr** [comment]
In the package from 22.04 the node was disappearing if I clicked to edit and then clicked in the background but the content was not replaced. the issue with vanishing node is described here: https://github.com/enso-org/enso/issues/6378

**Comment by vitvakatu** [comment]
We need to check it on branch #6347. If it is not fixed there, the issue is somewhere in CB, and the fix can be complicated. I was facing similar issues while working on cursor-aware CB, but at that time, everything was fixed.

**Comment by hubertp** [comment]
Maybe slightly related:
- select a method from CB (e.g. `aggregate`)
- ctrl+click to edit the newly added node
- click outside

![Screenshot from 2023-04-25 14-42-33](https://user-images.githubusercontent.com/292128/234280093-d99f3366-246d-47b9-9c75-3c164e900335.png)

I would expect that we revert to the old node since clicking outside (I think) meant the cancellation of the edit action.
Instead it picks a random fragment from the node's name and disconnects the edge.

**Comment by vitvakatu** [comment]
It is reproducible on #6347

**Comment by sylwiabr** [comment]
@vitvakatu what is the status here?

**Comment by vitvakatu** [comment]
@sylwiabr the fix is ready, the PR will be here today.
