### ISSUE TITLE
Execution environment dropdown is shifted to the right

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#6414]
See the screenshot:

<img width="163" alt="Screenshot 2023-04-24 at 16 45 28" src="https://user-images.githubusercontent.com/6566674/234282744-9fa32e78-0815-4328-9636-409ca38316b4.png">

Instead, the dropdown should be aligned with the left side of the green box. The text must also be aligned.

**Comment by wdanilo** [comment]
Oh, your issue was earlier, but mine contains more info ;) https://github.com/enso-org/enso/issues/6445

**Comment by farmaazon** [comment]
merging to #6445
