### ISSUE TITLE
Previewed suggestion must not be executed with Output context enabled.

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#6417]
## The problem

Previewing suggestions with CB currently involves modification of the actual AST and execution of the workflow. It is a problem for nodes working in the Output context, as it can produce unintended evaluations (writes to files or transactions to the database). 

Therefore, the suggestion preview must be executed in the environment with the Output context disabled.

## Ideas on implementation

Summary of initial discussion with @farmaazon:

One of the ideas is to modify the expression of suggestion preview in the following way:

```
var = Standard.Runtime.with_disabled_context Standard.Runtime.Context.Output current_env <| actual_expression
```

But it won't affect the execution of the nodes further in the workflow, and they can use output context while re-evaluating.

Another solution is to make all edits in a temporary node that won't be connected to any other node. After accepting the edit, the original node is updated, and the temporary one is removed. This way, we also don't propagate errors down the graph. (which is another known issue with preview)
The problem here is view synchronization because we currently display nodes as in the code. We need an additional "fake" view with the same connections in this case.

Another idea is to switch the environment globally when we open CB.

**Comment by farmaazon** [comment]
> Another solution is to make all edits in a temporary node that won't be connected to any other node. After accepting the edit, the original node is updated, and the temporary one is removed. This way, we also don't propagate errors down the graph. (which is another known issue with preview)
The problem here is view synchronization because we currently display nodes as in the code. We need an additional "fake" view with the same connections in this case.

I think this is solution we shoudl try first.
