### ISSUE TITLE
Ambiguous aliased imports not reported

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6431]
See the following code:
```
from Standard.Base import all

import Standard.Table
from Standard.Table import Table

main =
    IO.println Table.new
```

We can see that the identifier `Table` is actually imported twice and so the imports are ambiguous - it could refer to the `Table` _module_ from `import Standard.Table` or the _type_ from `from Standard.Table import Table`.

Apparently, `import Standard.Table` takes precedence here and so the program outputs:
```
Execution finished with an error: Method `new` of Main could not be found.
        at <enso> colliding-import.main<arg-1>(colliding-import.enso:7:16-24)
        at <enso> colliding-import.main(colliding-import.enso:7:5-24)
```

But there are no errors or even warnings about the aliasing.

I think this should result in an error saying that the imports are ambiguous, or at least a warning.

I'm also surprised that it's not the _last_ import that takes precedence (I guess that would be the behaviour that I'd expect).

**Comment by Akirathan** [comment]
Running the following code snippet does not produce any compiler errors and normally evaluates:
```
from Standard.Base.Data.Boolean import True
from Standard.Base.Data.Boolean import True

main =
    42
```

That was just a simple example that should generate a compiler error explaining that `True` symbol is ambiguous. Although, strictly speaking, in this case it is not ambiguous, just duplicated. But for simplicity, it is IMHO better to report errors as early as possible, and even for duplicated symbol imports, not only for ambiguous imports. It seems that we have many ambiguous symbol imports in std lib code base.

**Comment by JaroslavTulach** [comment]
> simple example that should generate a compiler error explaining that `True` symbol is ambiguous

It is not ambiguous. It is just imported twice. In Java this yields a _warning: Unnecessary import_ on the second import line.
