### ISSUE TITLE
Investigate Undo-Redo in the IDE

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6435]
As we were progressing fast recently we need to make sure the Undo-Redo works properly. The testing should cover:
- [ ] adding/removing nodes
- [ ] reconnecting nodes
- [ ] collapsing nodes
- [ ] modifying nodes by editing the text on the node
- [ ] modifying nodes with drop-downs/widgets
- [ ] modifying collapsed nodes
- [ ] changing the view 
- [ ] project renaming

**Comment by vitvakatu** [comment]
We also need to cover project renaming - it also recorded as undo action.

**Comment by sylwiabr** [comment]
Thank you @vitvakatu, description updated!
