### ISSUE TITLE
Execution context menu shows in a wrong place and looks ugly

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#6445]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

@MichaelMauderer, I remember I was pointing out that the borders are not nicely aligned during code review. I opened the project on develop and I've seen this. Also, the drop-down is shifted to the right:

<img width="259" alt="image" src="https://user-images.githubusercontent.com/1623053/234728082-82a6e4e2-3b31-435a-9900-73e32e5a764c.png">

Is this a regression or was it never coded correctly? Can we fix it?

### Expected behaviour

It should have borders of the same size and should be aligned.

### Enso Version

Newest develop

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
The menu is replaced with two "record" buttons.
