### ISSUE TITLE
Erroring with `No_Such_Method.Error` without any details

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#6451]
I have just been investigating #6211 and when I create `e.enso` with:
```haskell
$ cat > e.enso 
main =
    a = 5
    if a == 3 then a = 10 else a = 15
```
and execute it with version `2023.1.1-nightly.2023.4.27` I get useless error:
```bash
enso$ ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run e.enso 
Execution finished with an error: No_Such_Method.Error
        at <enso> e.main<arg-2>(e.enso:3:32-37)
        at <enso> e.main(e.enso:3:5-37)
```
while displaying `No_Such_Method.Error` is correct, it is not providing any details. The #6211 bug description claims there used to be time when better message was displayed:
```
Execution finished with an error: Method `=` of 5 (Integer) could not be found.
```
Something must have regressed. 

PS: We don't need to display the same text as before, but mentioning `=` and possibly the type of the `a` variable (e.g. `Integer`) was very valuable.

**Comment by hubertp** [comment]
This is as expected and consequences of https://github.com/enso-org/enso/pull/6275 have been described and discussed there.

**Comment by hubertp** [comment]
Removed the regression since it is an intentional change.

**Comment by JaroslavTulach** [comment]
> expected ... consequences of #6275 ... discussed there.

It took me a while to realize what you mean!

> Take for example `No_Such_Method.Error`. If we do not import `Errors.Common` module ... does not have `to_display_text` in scope

OK, so if I modify the code to
```haskell
from Standard.Base import all

main =
    a = 5
    if a == 3 then a = 10 else a = 15
```
then I get the correct error again:
```
bin/enso --run e.enso
Execution finished with an error: Method `=` of 5 (Integer) could not be found.
        at <enso> e.main<arg-2>(e.enso:5:32-37)
        at <enso> e.main(e.enso:5:5-37)
```

I think this is OK behavior then. Sorry for causing confusion!
