### ISSUE TITLE
Visual glitches appearing in CB right after opening

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6452]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://user-images.githubusercontent.com/12892578/234830661-04c95a8d-502d-4926-af6a-9c537b4722db.mov

### Expected behaviour

The CB content should not blink. The regression appeared around this commit: https://github.com/enso-org/enso/commit/fa995dd765f55fd6a30295b8c44654df1f249f67 but I was waiting for https://github.com/enso-org/enso/commit/a00efb28f3cca317464a71c1aa0bad63f2e2724a to check if it will not be fixed together with connections animations issues.

### Enso Version

develop @ ae94a9f40d3e98b9068da716b8b6416bba517a19

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
Reproduced it on Restaurants example. It happens quite often, but not every time.

**Comment by sylwiabr** [comment]
can't reproduce it on the newest version
