### ISSUE TITLE
Missing warning message for `parse` in the IDE

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6454]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I can see I have a warning on a node but unfortunately I can't see the warning message.

https://user-images.githubusercontent.com/12892578/234865717-ed4350f9-1fa6-43ff-b5e8-a3cff152396d.mov

![image](https://user-images.githubusercontent.com/12892578/234865841-ea99e373-dc38-4177-bd41-251672570eb0.png)
 Project file: 
[Unnamed_28.zip](https://github.com/enso-org/enso/files/11343606/Unnamed_28.zip)

### Expected behaviour

Warning should be visible for the user.

### Enso Version

2023.1.1-nightly.2023.4.27

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by hubertp** [comment]
@sylwiabr can you include the full screenshot of the project, please? It helps with reproduction.

**Comment by sylwiabr** [comment]
@hubertp you have a source code of the project in a zip file - it is easier to just run it probably than to rewrite it from the screenshot :)

**Comment by hubertp** [comment]
> @hubertp you have a source code of the project in a zip file - it is easier to just run it probably than to rewrite it from the screenshot :)

Thanks, missed it in the questionnaire template

**Comment by hubertp** [comment]
IDE is certainly getting the failure, indeed:
```
{
    "jsonrpc": "2.0",
    "method": "executionContext/visualisationEvaluationFailed",
    "params": {
        "contextId": "2d59378e-c495-4a7b-a203-2269b0ad1c0e",
        "visualisationId": "cf91be49-9191-4eb7-8c00-d77e4c9e5d1b",
        "expressionId": "eb7e56f0-1fc6-446b-8add-d1c09bd8db15",
        "message": "Type error: expected `that` to be Number, but got Text.",
        "diagnostic": {
            "kind": "Error",
            "message": "Type error: expected `that` to be Number, but got Text.",
            "path": null,
            "location": {
                "start": {
                    "line": 257,
                    "character": 8
                },
                "end": {
                    "line": 257,
                    "character": 45
                }
            },
            "expressionId": null,
            "stack": [ ... ]
        }
    }
}
```

**Comment by hubertp** [comment]
I think this is a problem on IDE side, as it does not show the error

**Comment by vitvakatu** [comment]
We were never displaying `executionContext/visualisationEvaluationFailed` to the user. It was never implemented in our code. 

Though it should be possible to handle such things, I wonder why the engine uses various methods to tell about warnings. Currently, we display warnings that come to the IDE in [`ExpressionUpdatePayload`](https://github.com/enso-org/enso/blob/develop/docs/language-server/protocol-language-server.md#expressionupdatepayload). 

And the suspicious thing here is that you can still see the yellow marks around the node – it means we received warnings info in `ExpressionUpdatePayload`, but perhaps it was empty?

**Comment by hubertp** [comment]
OK. So I think there are actually two things here:
1. An expression may contain warnings
2. Visualization fails to materialize thus not really showing those warnings

The thing is that visualization evaluation may always fail under some weird circumstances and we should probably report it somehow rather than just displaying a blank page. So that seems like an additional feature anyway?

**Comment by farmaazon** [comment]
> The thing is that visualization evaluation may always fail under some weird circumstances and we should probably report it somehow rather than just displaying a blank page. So that seems like an additional feature anyway?

Of course, the visualization should report their failure to the user (perhaps there is already an issue somewhere), but even then the warning visualization should be fixed: If we have warnings, we should always be able to show the warnings, not any error.
