### ISSUE TITLE
Options in a drop down for `cross_tab` are so long, that user doesn't see the last (most important) part

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6455]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![image](https://user-images.githubusercontent.com/12892578/234873548-8d3de507-eb46-4a2b-bc8e-3f4b225ec662.png)

### Expected behaviour

fully visible constructors names

### Enso Version

nightly 27.04.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by wdanilo** [comment]
I understand that this is part of the fixes for new widgets view, am I correct @Frizi ?

**Comment by farmaazon** [comment]
Duplicate of #6052
