### ISSUE TITLE
Edited node wiggles when panning the scene on non-default zoom level

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#6456]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://user-images.githubusercontent.com/6566674/234887288-dae20803-4309-4280-8c9b-0f3235571cd1.mp4

I have been spotting this issue for some time. It probably does not make sense to bisect it. The issue is probably in the algorithm for the searcher camera position updates.

### Expected behaviour

The edited node must be aligned to the CB.

### Enso Version

0c7c3bdeaf914c74e8d8af02c482454a1b01f8a8

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
Reproduced on 7e333000130ea539fe82d5f5942f23047c92fe3a

**Comment by kazcw** [comment]
The cameras are updated asynchronously via the FRP `batch` mechanism. It is supposed to finish before anything observes it, but it was the cause of one bug I just fixed so it'd be a direction to look in to

**Comment by farmaazon** [comment]
No longer an issue in GUI2
