### ISSUE TITLE
Entering debug mode disappears text rendered in top bar and code window

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6460]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When entering debug mode project title, breadcrumbs and code disappears instantly. Code can still be selectable, so it's there but rendered transparent?

Vid fragment demonstrating the issue:

https://user-images.githubusercontent.com/108271897/234951056-a801918c-3e6f-45f5-aada-6beeaeee948c.mp4

### Expected behaviour

After entering debug mode no text disappears.

### Screenshots or screencasts

Entire session (with logs recorded on previous than shared above attempts):

https://user-images.githubusercontent.com/108271897/234951266-70086715-1a25-4f83-8ca8-dda8de4fd429.mp4

### Enso Version

2023.4.27 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by MichaelMauderer** [comment]
Can reproduce, and it seems the following warning pops up when the texts disappear. 

Since only test on the panel layer disappears, I assume this might be related to layering or the text implementation. Bisecting now.

**Comment by MichaelMauderer** [comment]
This appears to be present for a long time, before February. Before that, I'm running into trouble with the old build, so I won't bisect this further back. The oldest commit I was able to check and confirm this happens was  50f376e365cfea9a571afff49eda89f47fcad450

**Comment by vitvakatu** [comment]
Might be related to the issue in #6366
