### ISSUE TITLE
Missing cargo-watch-plus is silently ignored

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#6464]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I noticed that changes in source files don't trigger recompilation when using the `./run ide watch` command.

It turns out `cargo-watch-plus` was accidentally uninstalled, but I still had the `USE_CARGO_WATCH_PLUS` environment variable. In the logs, the following message is present. But the build process was not stopped, and this message quickly got lost in thousands of the following log messages. I only found it by accident.

```
TRACE ide_ci::program::command: cargo⚠️ <START>
TRACE ide_ci::program::command: cargoℹ️ <START>
 INFO ide_ci::program::command: cargo⚠️ error: no such command: `watch-plus`
 INFO ide_ci::program::command: cargo⚠️
 INFO ide_ci::program::command: cargo⚠️ 	View all installed commands with `cargo --list`
TRACE ide_ci::program::command: cargoℹ️ <ENDUT>
TRACE ide_ci::program::command: cargo⚠️ <ENDUT>
```

### Expected behaviour

A clear error should be reported to the developer.

### How we can reproduce it?

1. `export USE_CARGO_WATCH_PLUS=1`
2. Uninstall cargo-watch
3. ./run ide watch
4. Change any source file and save it

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by wdanilo** [comment]
@mwu-tow as you know this part the best, could you please throw an exception if one of the things we need is missing during the build?

**Comment by mwu-tow** [comment]
Irrelevant after old GUI removal.
