### ISSUE TITLE
Visualization chooser bar is partially covering opened dropdown if hovered with a mouse.

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6469]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![Enso_YbGR4GVWgM](https://user-images.githubusercontent.com/12892578/235138533-e9fa388e-2e80-4ea1-95a4-4d659e194e61.png)

### Expected behaviour

The vis chooser should stay below the dropdown.

### Enso Version

nightly 28.04.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by wdanilo** [comment]
The drop-down should close when clicking outside of it - this should be the solution to this problem.

**Comment by sylwiabr** [comment]
@wdanilo I didn't click, just moved the cursor

**Comment by wdanilo** [comment]
Gotcha! As we've been talking via phone today, this is WONTFIX for now, as we don't want to use separate draw calls for everything. It might be fixable one day in longer future though. Closing it for now.
