### ISSUE TITLE
Meta.meta Any . methods doesn't work

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#6473]
One can list all methods of every type like `Boolean`:
```
> Meta.meta Boolean . methods
>>> ['&&', '||', 'not', 'if_then', 'if_then_else']
```
but one cannot do the same with `Any` type:
```
> Meta.meta Any . methods
Evaluation failed with: Type error: expected `type` to be Type, but got Function.
java.lang.Exception: Type error: expected `type` to be Type, but got Function.
        at <enso>.Type.methods<arg-1>(Meta.enso:42)
        at <enso>.Standard.Base.Meta::Standard.Base.Meta.Type::methods(Meta.enso:41)
```
probably related to #6300 and or #5612. Tested on 0dc9f3742cc52ac091b0338672fe02039931e097

**Comment by Akirathan** [comment]
The problem is this:
```
> Meta.is_a Any.catch Function
>>> true
> Meta.is_a Vector.catch Function
>>> function
```

In other words, `Any.catch` resolves to a reference to `Any.type.catch` method. The reason for that is roughly explained in https://github.com/enso-org/enso/issues/5612#issuecomment-1520362618.
