### ISSUE TITLE
Ensogl loader default options are outdated

### ISSUE THREAD

**Issue by PabloBuchu** [enso-org/enso#6475]
The defaults in ensogl config options in loader groups are set to:
```
"wasmUrl": {
          "value": "pkg.wasm",
          "description": "The URL of the WASM pkg file generated by ensogl-pack.",
          "primary": false
        },
        "jsUrl": {
          "value": "pkg.js",
          "description": "The URL of the JS pkg file generated by ensogl-pack.",
          "primary": false
        },
        "assetsUrl": {
          "value": "assets",
          "description": "The URL of the dynamic assets directory.",
          "primary": false
        },
```
This is no longer true as `assetsUrl` should have `dynamic-assets`. We need to check and fix values of  `wasmUrl` (either `pkg.wasm` or `pkg-opt.wasm`).

**Comment by wdanilo** [comment]
@mwu-tow did you change `assetsUrl` to `dynamic-assets`? I think you've been chasing that, right? If so, the EnsoGL pack should be fixed as well.

**Comment by mwu-tow** [comment]
@wdanilo I don't think I touched it, pinging @kazcw?

**Comment by wdanilo** [comment]
Oh maybe it was Kaz then!
