### ISSUE TITLE
Component Browser fails to load on erroneous node

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6481]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When opening CB on an erroneous node it goes to, what appears to be, an infinite loop.
See the recording.

### Expected behaviour

Should probably open and show anything?

### How we can reproduce it?

1. Createa node with some non-existing method
2. Create an edge from that node which will open CB

### Screenshots or screencasts

[Kazam_screencast_00004.webm](https://user-images.githubusercontent.com/292128/235438141-95dca5ef-205c-417c-b055-d9e73a01f97e.webm)

### Enso Version

efe904cd9f0c44c112a254229d94522802c246e5

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by farmaazon** [comment]
I reproduced it. It does not show anything because we don't get any suggestion in `completion` response. I remember some times ago there were methods of Panic suggested (e.g. catch).

The example request we send to the engine is:
```
{"jsonrpc":"2.0","id":142,"method":"search/completion","params":{"file":{"rootId":"5a1d2ae3-6569-4e4a-858e-03941a2d7443","segments":["src","Main.enso"]},"isStatic":false,"position":{"character":20,"line":12},"returnType":null,"selfType":"Standard.Base.Panic.Panic","tags":null}}
```

**Comment by 4e6** [comment]
What happens is, IDE indeed asks for non-static methods on the `Panic` type
```json
{
    "file":{
      "rootId":"9ef839a5-01ea-4c72-9dd6-b7158f8fe041",
      "segments":[
        "src",
        "Main.enso"
      ]
    },
    "isStatic":false,
    "position":{
      "character":14,
      "line":9
    },
    "returnType":null,
    "selfType":"Standard.Base.Panic.Panic",
    "tags":null
  }
```

But the methods on `Panic` are all static https://github.com/enso-org/enso/blob/bb8f910be9272fbf513f05a05f24110ed6d5d7e4/distribution/lib/Standard/Base/0.0.0-dev/src/Panic.enso, and the engine returns an empty response.

<blockquote><img src="https://opengraph.githubassets.com/62017eeb492552a76d970a27f87aef85e8a20ec9a832222a446550d03c0438be/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">enso/Panic.enso at bb8f910be9272fbf513f05a05f24110ed6d5d7e4 · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
