### ISSUE TITLE
Error: "expected function but got 1" when trying to add 2 literals

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6484]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While exploratory testing Enso got weird bug:

![image](https://user-images.githubusercontent.com/108271897/235446297-8a2feb3b-e705-4c48-9ec5-324bede24bc9.png)

While "1+2" returns proper result, the above renders error.

### Expected behaviour

preview displaying result of the addition

### How we can reproduce it?

create two integers
select one 
create new node
type "+number2"
confirm creation of that node
watch error

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/235446623-e64a2fdc-41a6-4d37-be21-3b33d167d938.mp4

### Enso Version

2023.5.1 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by farmaazon** [comment]
It looks like this is `number1 +number2` instead of `number1 + number2`. Such cases should be fixed once finished New Component Browser #4967

**Comment by 4e6** [comment]
`number1 +number` is interpreted as a function application, i.e. function `number1` is called with the argument `+number2`.

**Comment by 4e6** [comment]
Related #6485

**Comment by 4e6** [comment]
We cannot interpret `1 +2` as an addition operation because Enso uses whitespace-precedence, meaning that 
```
> 2 * 3+4
>>> 14
```
And not `10`. Because `3+4` is bound more tightly, resulting in `2 * (3 + 4)`. This allows us to chain expressions without using brackets
```rb
1..100 . each random . take 10 . sort
```

**Comment by farmaazon** [comment]
Yes, I think when we finish the Epic with the component browser it should be visible for the user (as the input port will be visible, so it will be visible instantly that the spaces does not match). Or we could make a quick fix by just checking how many spaces we should add to have them equal in number.

**Comment by xvcgreg** [comment]
@wdanilo please choose the solution from what @farmaazon is suggesting

**Comment by wdanilo** [comment]
@xvcgreg the description of this issue is confusing. You know the the case is `n +n` instead of `n + n`, as we were chatting about it on PW on Discord. This confusing description made @4e6 lose time to explain something we know. Sorry @4e6 for that.

Regarding the issue, when creating node `+2` this way, the additional spacing should be automatically inserted. And I am OK with any solution that @farmaazon proposes here.

**Comment by wdanilo** [comment]
Also, I think I missed that in my previous reply - making it visible does not solve the issue. If we create a node while having other node selected `+2` or `.foo`, the space should be automatically inserted even if it is visible that it will not match. So, if I have node `2` selected and I type `+2` I end up with `node1 + 2`. 

This solution has of course a downside. If the selected node output is a function and we want to provide to it a lambda (like `+2`), then it would be harder to do so. Then user would need to write `(+2)` or insert it with ctrl+enter. But I'm very OK with it as this use case is so rare, that we should optimize for more common cases.

**Comment by farmaazon** [comment]
Ok, let's clarify something:

**Scenario 1**

The user has some node selected and presses enter. The node appears with code 

`var1.|` where `|` is a caret.

They type `+`. I guess at this moment we remove `.` (as it is in the design) and insert `+`, so we get

`var1 + |` 

Or do we? Maybe doing it without space is better? (we just replace `.` without jumping too much).

`var1+|`

**Scenario 2**

The user has an existing node on their scene:

`(some.very complex x->expression)+`

I guess starting editing at the end and typing `2` should not add any space anywhere?

**Comment by wdanilo** [comment]
### Scenario 1
This is more tricky. If the user writes `+2` the code has to be either `var1 + 2` or `var1+2`, because `var1 +2` would not work. So we need to be careful about spacing from both sides of the operator. I'd always prefer a code with spaces, as it's easier to read. I'm not sure though if this answer provides you with the full answer to your question.

### Scenario 2
No, we co NOT add any spacing here. We are talking only about more intelligent spacing when creatingg a new node after pressing tab when having a node selected prior to pressing tab.

**Comment by farmaazon** [comment]
Ad 1. I also think spaces looks nicer. So the result of typing `+` would be transition `var1.|` to `var1 + |`. However, there is:

**Scenario 1A** We have input `var1.|` and user wants to use operator `>=`. They type `>`: now, shall we put `var1 > |`? That would make adding = harder.
