### ISSUE TITLE
Blank input port on node creation

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6485]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When creating node the input port is blank (layering issue?)

![image](https://user-images.githubusercontent.com/108271897/235449804-46d04703-751e-4071-bdca-b61aa63fc4ac.png)

### Expected behaviour

port should be filled in and visible

### How we can reproduce it?

see video below

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/235449880-13e8f3ff-515e-48f1-8426-7209740116d4.mp4

### Enso Version

2023.5.1 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by sylwiabr** [comment]
This is happening when there is a missing space between an operator (like `+`) and next input port/number i.e. `number1 +3`

**Comment by 4e6** [comment]
`1 +2` expression is parsed as a function application, i.e. the function `1` is called with an argument `+2`

**Comment by 4e6** [comment]
`number1 2` has the same effect

![2023-05-01-213424_564x392_scrot](https://user-images.githubusercontent.com/357683/235507661-820eff27-44c5-4d79-a096-b9bdcefc2447.png)
