### ISSUE TITLE
CB is adding `Column.from_vector` when creating a vector 

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6486]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When typing a vector the CB is always adding `Column.from_vector` after closing `]` when pressing `enter`

### Expected behaviour

Vector should be treated like a number or literal - as a special input type

### Enso Version

develop @ 6b0c682b08b7745368cec3474cc774c51a5b48f5

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by hubertp** [comment]
I've seen this before and I don't think this is Vector-related. It happens when you type anything that doesn't match what CB is proposing.

**Comment by 4e6** [comment]
It seems that CB simply inserts the currently selected item on the `enter` key keypress. Nothing to do with Vector

[cb.webm](https://user-images.githubusercontent.com/357683/235501136-9096ce03-5819-453c-a067-a1a6d80cb97c.webm)

**Comment by 4e6** [comment]
To make it less confusing to the user, we can change the behavior of the `enter` key so that it doesn't insert the selected item unless the node is empty (there was no user input).

**Comment by farmaazon** [comment]
Or, we could do something similar to literals: if the cursor is after a closing bracket, it shows special suggestion for the array which is selected by default.

We should also do that for any "closing" token: `)`, `]` or whatever is supported in enso.

**Comment by farmaazon** [comment]
See also Greg's comment in a duplicated task (https://github.com/enso-org/enso/issues/6623#issuecomment-1541518518 ):
> yes, it happens many times. In some scenarios, it's a desired behavior - but mostly it renders the preview useless. How can we fix that? So the user will know that adding what he/she has (not) selected in the CB is the new output of the node computation result. Making the selection of component a conscious decision (requiring user action (mouse movement, arrow key press)) to reevaluate the previously correct code into an error state with new results served to the preview window.

So the options are: 
1. A special entry (as in my comment above)
2. Not selecting any entry when user closes bracket (as in Greg's comment).
