### ISSUE TITLE
Visualization after reconnecting nodes is visible for a second and then it disappear until it will be manually refreshed 

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6489]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://user-images.githubusercontent.com/12892578/235452736-3ff4d017-aa94-4299-9437-b76039ef8aca.mov

### Expected behaviour

Visualization should appear without forcing a refresh (changing vis type or hiding and showing it again)

### Enso Version

develop @ 6b0c682b08b7745368cec3474cc774c51a5b48f5

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by vitvakatu** [comment]
I can't reproduce on the latest develop (bb8f910be9272fbf513f05a05f24110ed6d5d7e4) and the latest engine `2023.1.1-nightly.2023.5.3`. @sylwiabr if it is still reproducible for you, please attach the project.

**Comment by sylwiabr** [comment]
Looks like it is working on today's nightly
