### ISSUE TITLE
Replace package.yml `component-groups` with in Enso source information

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#6497]
There are [component-groups](https://github.com/enso-org/enso/blob/c4c35c92b7e2b53f5e4571af0e89a56eac8e7120/distribution/lib/Standard/Base/0.0.0-dev/package.yaml#L11) definitions spread around the `package.yaml` files. Having these definitions at a distinct location than the method definition makes them fragile and easy to get out of sync.

Design a way (an annotation) to keep these _"component group"_ information next to the definition of the function.

**Comment by JaroslavTulach** [comment]
A proposal to add `GROUP` into documentation is being discussed at 
- #7120

**Comment by jdunkerley** [comment]
Closing as doc tag is sufficiently good.
