### ISSUE TITLE
Horizontal scaling gets squished when you resize Enso application jsut after the start with debug.dev-tools flag

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6500]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Enso horizontal resolution gets squished when you resize Enso screen horizontally (ie.: to have more space to work with). Also there's a navigation gap between the squished to the left side area and dev console (mouse teleports through the "gap" when you move it from left to right and vice versa). 

https://user-images.githubusercontent.com/108271897/235632950-94f7ff15-c3d1-46eb-aed2-74ebdeba5847.mp4

### Expected behaviour

No squashing of the resolution of GUI, expanding the application accordingly to the  window size.

### How we can reproduce it?

launch Enso with debug.dev-tools flag and stretch the window it as soon as it appears.
first: observe the shashed cursor
then, after a project opens: entire GUI gets squished horizontally

### Screenshots or screencasts

longer movie:

https://user-images.githubusercontent.com/108271897/235633631-667e0524-5ac1-43f5-a841-ff0b667230c6.mp4

### Enso Version

2023.5.2 Nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by xvcgreg** [comment]
Also what I have noticed on the next Enso launch is that the mouse position in the home screen was incorrectly displayed. I have clicked "new project" but instead I got several projects from the templates clicked instead of several new "unnamed" projects created.

**Comment by farmaazon** [comment]
This is a regression. I'm sure resizing worked before.

**Comment by vitvakatu** [comment]
#6461 (commit `cd92d90f9ff70320096bb514194c50796dcfcba0`) is at fault.

An easier way to reproduce on the smaller screen (that doesn't allow extending the window):
1. Open the IDE with `-debug.dev-tools`
2. Make the window really narrow
3. Reload it (I use Electron menu `View -> Reload`)
4. Quickly enlarge the window

**Comment by wdanilo** [comment]
> #6461 (commit `cd92d90f9ff70320096bb514194c50796dcfcba0`) is at fault.
> 
> An easier way to reproduce on the smaller screen (that doesn't allow extending the window):
> 
> 1. Open the IDE with `-debug.dev-tools`
> 2. Make the window really narrow
> 3. Reload it (I use Electron menu `View -> Reload`)
> 4. Quickly enlarge the window

Are you 100% sure this commit caused it? It was not touching any code but code related to a widget, so I don't see why it could theoretically change anything like that.

**Comment by wdanilo** [comment]
> This is a regression. I'm sure resizing worked before.

Are you sure this is regression? It's not about scaling. It's about calling fast before our graph editor loads.

**Comment by vitvakatu** [comment]
> Are you 100% sure this commit caused it? It was not touching any code but code related to a widget, so I don't see why it could theoretically change anything like that.

I checked one more time. I can reproduce it on this commit, and I can't do that on the previous one.

**Comment by wdanilo** [comment]
This is almost impossible as that code was not changing anything ... Anyway, I'd take a look at it.

**Comment by kazcw** [comment]
I think it has to have been the previous one (a839545)--I changed the resize logic in #6458. I haven't been able to reproduce this, can someone check whether, once the bug is observed, further changing the screen size corrects it?

**Comment by wdanilo** [comment]
@vitvakatu as you are reproducing it (I can't, it somehow works on my end), could you check the above question from Kaz, please?

**Comment by kazcw** [comment]
I have reproduced it. It's very timing-sensitive. Fixing it now.

**Comment by kazcw** [comment]
@vitvakatu When you get a chance, could you verify that this is fixed for you also?
