### ISSUE TITLE
Selecting text from documentation panel and pressing Ctrl+c - selects and copies node text instead of selected documentation

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6504]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Selecting text from documentation panel and pressing Ctrl+c - selects and copies node text instead of selected documentation fragment.

https://user-images.githubusercontent.com/108271897/235653901-4eccad6e-ffdf-431f-acae-e0a278857594.mp4

After I press Ctrl+c text on the node selects in pinkish color and is copied into the clipboard instead of selected documentation fragment.

### Expected behaviour

Selected documentation fragment gets copied into the clipboard.

### How we can reproduce it?

as on the movie provided

### Enso Version

2023.5.2 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by vitvakatu** [comment]
We're preventing default for all keyboard events, so `cmd+c` is captured by the Text's FRP.

**Comment by wdanilo** [comment]
A good question is if not preventing default for ctlr+c would fix it. It might. We need to check if then copying node selection would still work though.

**Comment by farmaazon** [comment]
We no longer prevent default on all keyboard events, but this issue still occurs.

**Comment by farmaazon** [comment]
Superseded by #9175
