### ISSUE TITLE
Visualization between two nodes (one table one text viz) mixed together.

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6516]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

<img width="480" alt="image" src="https://user-images.githubusercontent.com/12892578/235867674-484671ad-cc4f-4a26-9a60-3254328275b7.png">

### Expected behaviour

Proper Z ordering for different types of visualizations.

### Enso Version

Nightly 02.05

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by vitvakatu** [comment]
That isn't very pleasant to fix, as it requires a separate layer per visualization type. With a recently introduced API for shape ordering, it can be simpler, though. @MichaelMauderer @kazcw, you might have some helpful advice here.

**Comment by wdanilo** [comment]
Layer per visualization is a bad idea, it will kill the performance. New layers are also not a solution here. If both visualizations are in HTML/JS this is fixable. If one of the visualizations (or its text) is in WebGL, I think this is wontfix. I don't like it, but either we have this or way worse performance :(

**Comment by MichaelMauderer** [comment]
In this specific case, it might be easier, as both of them are JS visualization using HTML elements. As are most of our visualizations, and the backgrounds. So this might be easy to "hotfix". But the general case for EnsoGL visualizations might be tricker, as we'd want the background of each instance to occlude the whole other visualization.

**Comment by wdanilo** [comment]
If both visualizations are in HTML and their backgrounds are in HTML as well, then yes, this should be fixable. But I think this is low-priority now, taking into consideration other bugs we have.

**Comment by farmaazon** [comment]
Not relevant to GUI2.
