### ISSUE TITLE
"+" icon in List Editor should be finished, as it is easy now to confuse it with a mouse cursor.

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6517]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Add a new node, try to move it - the cursor pointer will be rendered on the node and never disappear
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/12892578/235870730-0d30775e-071f-4aba-8ae7-2321a7d8c61c.png">

### Expected behaviour

I should have just one cursor

### Enso Version

Nightly 03.05

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

Standalone

### Operating System

MacOS

**Comment by sylwiabr** [comment]
This is happening also on Windows

**Comment by vitvakatu** [comment]
It's quite easy to reproduce - add a `.split` node for text literal input. It seems the cursor (or a shape that is similar to the cursor) is displayed in place of the array literal. Clicking on it creates a new `[_]` placeholder. So it has to be connected with the vector editor implementation.

**Comment by vitvakatu** [comment]
I don't think it makes sense to bisect it, it is rather clear that it came together with vector editor, and we don't want to rollback any of the related PRs anyway. So I'm removing regression label.

**Comment by wdanilo** [comment]
This is not a cursor duplication. The circle you see on the node is something we did not finish - it would be a "+" icon telling you that you can add new items there, it is not a cursor. It is displayed on empty vector editor. We need to finish it and display `+` icon there instead.

**Comment by farmaazon** [comment]
As #6540 removes the icon for some time (until it will be restored [when implementing the design](#6552)), I think the task is no longer valid. For future reference, the shape definition is something along:
```rust
mod add_element_icon {
    use super::*;

    ensogl_core::shape! {
        (style: Style, color_rgba: Vector4) {
            let size = Var::canvas_size();
            let radius = Min::min(size.x(),size.y()) / 2.0;
            let circle = Circle(&radius);
            let bg = circle.fill(INVISIBLE_HOVER_COLOR);

            let angle= Radians::from(90.0.degrees());
            let bar_length= &radius * 5.0 / 4.0;
            let bar_width= &bar_length / 5.0;
            #[allow(clippy::disallowed_names)] // The `bar` name here is totally legit.
            let bar= Rect((bar_length, &bar_width));
            let plus = bar.rotate(angle) + bar;
            let shape= circle - plus;
            shape.fill(color_rgba);
            (shape + bg).into()
        }
    }
}
```
May be further improved by taking plus size and color from styles.
