### ISSUE TITLE
Renaming the project is breaking the use of collapsed function

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6521]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://user-images.githubusercontent.com/12892578/235883040-8a21812e-d56f-4947-979c-7e7a8fc61467.mov

### Expected behaviour

Renaming the project should not break the user workflow.

### Enso Version

Nightly 03.05

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by wdanilo** [comment]
Created functions should be referenced as `Main.` not `ProjectName.`. We don't have automatic refactoring and I'm not sure if automatic refactoring would be ever possible, so we should generate nodes in such a way, that they are never referring to project's name.

**Comment by vitvakatu** [comment]
It should be relatively easy to improve CB to generate the code with `Main` instead of the project name.

**Comment by farmaazon** [comment]
I remember I inquired @jdunkerley about use of `Main` name in code, and - as I remember - we settled, that `Main` should not be used in the code. James, could you confirm? 

Or I will find the discord thread, but it's buried quite deep, I'm afraid.

**Comment by jdunkerley** [comment]
If I did say that I was mistaken. 

I don't believe we need either in front of the function name but I guess Main. makes the most sense.

**Comment by farmaazon** [comment]
> Created functions should be referenced as Main. not ProjectName.. We don't have automatic refactoring and I'm not sure if automatic refactoring would be ever possible, so we should generate nodes in such a way, that they are never referring to project's name.

@wdanilo The last is not possible, actually, because we want to sometimes call method functions from other modules of our projects. We can import them, of course, but hey: the import _will_ have a node name.

So we won't avoid automatic refactoring, I'm afraid, unless we introduce some keyword for the current project.

**Comment by wdanilo** [comment]
@farmaazon some keyword like `crate::`?

**Comment by farmaazon** [comment]
Yes.
