### ISSUE TITLE
Shift + End selecting the project name not always work

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6524]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I want to Shift + End select the project name to rename it sometimes skips the shift and moves the cursor to the end instead of selecting it.

https://user-images.githubusercontent.com/108271897/235890843-0e324804-f1ec-4b27-89da-e037203e84c2.mp4

### Expected behaviour

Shift + End always selects entire text after the cursor

### How we can reproduce it?

repeat the sequence of:
Home -> Shift + End
several times

### Enso Version

2023.5.2 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by vitvakatu** [comment]
I can't reproduce it myself on MacOS, might be hardware- or OS-related issue

**Comment by jdunkerley** [comment]
No longer supports editing so deprecated issue.
