### ISSUE TITLE
Comma within vector is not visible

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6528]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![image](https://user-images.githubusercontent.com/12892578/235901652-b572b74a-d6a7-4681-afaf-c8e00772d6fc.png)

### Expected behaviour

Just like for text `"` is visible the `,` for vector should be visible as well or we should have a clear visual indicator those are elements of a vector.

### Enso Version

nightly 03.05

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by wdanilo** [comment]
In the new design, we do not have commas (nor `[` and `]`): 
<img width="467" alt="image" src="https://user-images.githubusercontent.com/1623053/235931463-e248fc3d-fc49-4c2c-b6b9-40f6e63b5423.png">

Instead, we have the vertical lines (visible on the screenshot above). @Frizi is working on improving widgets now, I think the vertical lines should be added instead and we should progress towards the new design ASAP.

**Comment by 4e6** [comment]
@farmaazon I assume you have a link to an appropriate issue in support of the new design and/or can close this one.

**Comment by wdanilo** [comment]
I was chatting with @Frizi about this and he will soon implement these vertical lines. So @Frizi if you have these issues written down somewhere, please link them here and close this one.

**Comment by farmaazon** [comment]
@Frizi bump.

**Comment by farmaazon** [comment]
Closing anyway, as the new design does not expect commas.
