### ISSUE TITLE
Automatic type based dropdown does not include singleton in a union type

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6532]
`Auto | Value_Type` is used in a few places.

The automatically generated drop down doesn't show `Auto`.

![image](https://user-images.githubusercontent.com/4699705/235920551-a21a27e9-6938-44f5-b69e-c975b7322cc6.png)

**Comment by 4e6** [comment]
@Frizi How do the dropdowns work? I.e. we have a function
```
type Foo
    Bar
    Baz

foo : Foo | Boolean -> Any
foo a = a
```
How does IDE show the dropdown?

**Comment by wdanilo** [comment]
It should display all possible values, including `False`, `True`, `Bar`, and `Baz`. In the future, we could also display headers in the dropdown indicating to what type these values belong, but this is not planned now (but we would like to receive this info from backend).
