### ISSUE TITLE
`Range.Between` not working with Dates

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#6543]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I tried to use `Range.Between` to produce a sequence of `Date` values, but got an error. See bottom left:
![image](https://user-images.githubusercontent.com/1047859/236123297-02f42b63-a812-4260-af07-c45cf7db8f67.png)

Both inputs are `Date` objects; I don't know where the `0` mentioned in the error is coming from.

### Expected behaviour

`Range.Between` should produce a range of dates.

### Enso Version

current `develop` (bb8f910)

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by jdunkerley** [comment]
Libs will have a look into how best to expand the Date support to allow this.
