### ISSUE TITLE
Vector Add Pointer appears when selecting a project from the open project list

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6549]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![image](https://user-images.githubusercontent.com/4699705/236177281-a2aee26e-432f-4444-a304-a8b9ecd3abff.png)

When selecting a project from the Open List if a Vector is behind you get a + pointer.

### Expected behaviour

Normal pointer.

### How we can reproduce it?

Put a vector under where the open file list appears

### Enso Version

Current Develop as of 4th May

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Microsoft Windows [Version 10.0.22624.1680] Version 22H22

### Hardware you are using

AMD 6800HS 32GB RTX3050

**Comment by 4e6** [comment]
That's probably an artifact of adding a (+) button #6470

**Comment by wdanilo** [comment]
We know about this issue and I was chatting with @Frizi yesterday about fix for it (discovering mouse cursor change based on display object hierarchy - this looks like the only way to do it reliably). So @Frizi has it on its TODO list. @Frizi could you link your task from our yesterdays call to this issue, please?

**Comment by Frizi** [comment]
Yes, this is the issue. https://github.com/enso-org/enso/pull/6540
Turns out there are still some plus-related issues reported during QA, so I'm working on fixing that.
