### ISSUE TITLE
Change node colors and add icons to match the design

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#6552]
- Add icons on the left side of the node. The icons must match ones from component browser. The user should always be able to drag the node by holding by the icon.
- Change node color to match the function coloring from component browser. The node's outgoing edges must also match its color.
- Move node action bar (skip, freeze etc.) to the left.
- Remove node names. On connected ports, show the argument name instead. When connection generates a named argument, do not show it twice.
- Use dedicated style for placeholder values (`_`).
- Change style of incoming edge connections to the `self` argumnet.
- Separate widgets of each method argument with a pipe.
- Render all argument names and non-literal expressions as lowercase and do not show any underscores separating words.
- Remove type-based text coloring. Instead, apply different transparency and font weight styles depending on context.
  - argument names are semitransparent and thin
  - default values are semitransparent and bold
  - non-default values are white and bold

<img width="518" alt="image" src="https://user-images.githubusercontent.com/919491/236200485-fff5073c-bb56-471c-a322-4b8ae916c84f.png">

<img width="487" alt="image" src="https://user-images.githubusercontent.com/919491/236199931-8ebee68f-f7b0-4ba7-b455-ba3889d4b1b9.png">

**Comment by farmaazon** [comment]
This task is started, but it has no estimate. I also believe I would take more than a week, so it should be made an epic and split into smaller task.

**Comment by farmaazon** [comment]
@Frizi We should put this task on hold in favor of #6792

**Comment by wdanilo** [comment]
Btw, @Frizi what's the progress here? How much is left to be closer to our final design? :)

**Comment by Frizi** [comment]
@wdanilo not much since I shown it last time. I was able to do some progress on implementing widgets for displaying method calls with icons, but I still have a bug that prevents them from being displayed that I have to figure out. To do this properly, I will need to truly focus on this task only, but so far a lot of higher priority bugs related to widgets kept showing up.
