### ISSUE TITLE
stdlib benchmarks should produce reports in a unified format

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6554]
Currently [engine benchmarks](https://github.com/enso-org/enso/tree/develop/engine/runtime/src/bench) and [stdlib benchmarks](https://github.com/enso-org/enso/tree/develop/test/Benchmarks) produce different and incompatible outputs.
The former is currently nicely plotted  in https://enso-org.github.io/engine-benchmark-results/. 

The task is for the stdlib benchmarks to produce output that is acceptable for the plotted benchmarks and can be tracked continuously. 

Came as part of the discussion on https://github.com/enso-org/enso/pull/6534

**Comment by JaroslavTulach** [comment]
There is currently no support for parsing XML in our standard library. However we can do `polyglot import java javax.xml.*` and use the needed classes directly. It shouldn't be that hard to mimic the behavior of `BenchmarkRunner` and its [Report](https://github.com/enso-org/enso/blob/develop/engine/runtime/src/bench/java/org/enso/interpreter/bench/Report.java) or even call into that class directly.

**Comment by jdunkerley** [comment]
The work that @Akirathan has done to run libs benchmarks within the JMH supersedes this ticket.

**Comment by JaroslavTulach** [comment]
- #7101
