### ISSUE TITLE
Dropdown entries using long names

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6555]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![image](https://user-images.githubusercontent.com/108271897/236214323-64639316-cac9-4f85-8428-f313f49effaf.png)

### Expected behaviour

Short and elegant dropdown entries names.

### Screenshots or screencasts

just create ``drop`` on any text and expand the dropdown for range

### Enso Version

2023.5.3 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by 4e6** [comment]
Duplicate #6455
