### ISSUE TITLE
Mouse cursor not updated correctly when selecting nodes by dragging on zoomed out node graph

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6556]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When trying to select nodes while having zoomed out graph for better view, cursor position was not calculated properly with the scale. All mouse movements were proportionally scaled up but the cursor position was in a wrong place - like it was scaled down.

https://user-images.githubusercontent.com/108271897/236217189-fcb151ad-a735-4857-ae7d-3fc01ad6d4c2.mp4

(errors you see to the right are from different bug - were there before this behavior occurred)

### Expected behaviour

When zoomed out mouse cursor follows the real mouse position.

### How we can reproduce it?

zoom out
select nodes by dragging

### Enso Version

2023.5.3 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by wdanilo** [comment]
This is the same issue as this one: https://github.com/enso-org/enso/issues/6549

**Comment by farmaazon** [comment]
@wdanilo remember to add proper label in such cases

**Comment by wdanilo** [comment]
@farmaazon right, thanks!

@xvcgreg I confused this issue with another one, sorry. Reopening. 

@MichaelMauderer When you were recently working on selections, did you test them with camera movement? https://github.com/enso-org/enso/pull/6487

**Comment by MichaelMauderer** [comment]
> @MichaelMauderer When you were recently working on selections, did you test them with camera movement? #6487

I think I panned, but don't quite remember about zooming out. The issue was specified about the bounding box (as is the fix, which only changes the bbox computation), so that seemed less relevant.

**Comment by farmaazon** [comment]
I cannot reproduce it on develop. @xvcgreg Can you reproduce it on the newest nightly?

**Comment by xvcgreg** [comment]
@farmaazon newest nightly is unfortunately unusable for me on this project anymore. I reproduced it several times on Monday with the freshest Nightly from the weekend.

**Comment by farmaazon** [comment]
@xvcgreg Tried it, still without luck. I will check if it reproduces on Windows. In the meantime, could you post here the project where you reproduce the issue?

**Comment by xvcgreg** [comment]
@farmaazon sure, here it is: 
[Unnamed_5.zip](https://github.com/enso-org/enso/files/11442142/Unnamed_5.zip)

but last week it was on much earlier stage. You can probably remove the first 2 sections of that setup.

**Comment by farmaazon** [comment]
Checked Windows, 2023.2.1-nightly.2023.5.6 package, and the uploaded project, and still could not reproduce it.

Perhaps the cause is somewhat related to the fact, that on video we constantly see (+) icon.

**Comment by farmaazon** [comment]
Reading the code, I have the following observations:
The main issue might be not the zoom or some cursor offset, but the fact, that the cursor has wrong style.
While selecting, the cursor style should be a box of appropriate size. But in the video, I see the cursor stuck with + sign style. As the cursor position is in the _middle_ of the selection box, thence the impression of the offset.

However, I still cannot reproduce the styling-cursor problem.

**Comment by sylwiabr** [comment]
styling cursor is the issue that appears randomly pretty often (multiple times per day) when testing the product

**Comment by farmaazon** [comment]
I did the yesterday bookclub without spotting the issue with cursor. I suspect #6540 could fix that. @sylwiabr have you seen the issue recently?

**Comment by sylwiabr** [comment]
Didin't observe it today/yesterday
