### ISSUE TITLE
Warning regarding missing precompiled shader when creating a new project in IDE

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#6557]
Open IDE, create a new project. The following warning appears in the console:
```
lib\rust\ensogl\core\src\display\shape\primitive\system.rs:502 No precompiled shader found for 'lib\rust\ensogl\component\text\src\font\glyph.rs:100:5'. This will affect performance.
```

Ther should be no warnings.

**Comment by wdanilo** [comment]
We know about it. I don't think we should issue for that though, so leaving it here for now. This is not fixable right now, but should be one day. It's low-priority on our end - glyphs do not have optimized shapes now.

**Comment by farmaazon** [comment]
Closing as EnsoGL related, and we no longer use EnsoGL.
