### ISSUE TITLE
Warning: Failed to Parse ID Map When Creating a New Project in IDE

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#6558]
Open IDE, and create a new project. The following warning appears in the console:
```
app\gui\language\parser\src\lib.rs:89 parse_with_metadata: Failed to parse ID map.
```

There should be no warning.

**Comment by 4e6** [comment]
I assume that's because the new project does not have any metadata

**Comment by wdanilo** [comment]
Even if there is no metadata, warning should not appear. Warnings mean that something was wrong, while project with no metadata is totally fine.

**Comment by farmaazon** [comment]
No reproducible in GUI2
