### ISSUE TITLE
Project created with a new nightly package is requesting an outdated engine

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6560]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

IDE is reporting unsupported Engine version for a project just created with newest nightly.

### Expected behaviour

No warning - I have newer version then the one required

### Screenshots or screencasts

<img width="1325" alt="image" src="https://user-images.githubusercontent.com/12892578/236234680-1d704f4d-67c3-4252-a483-2948cc052fa8.png">

### Enso Version

nightly 04.05

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by hubertp** [comment]
I don't believe this is a regression. It has been like that for a while if not from the inception of that version check.

**Comment by sylwiabr** [comment]
The nightly package from yesterday does not have this issue so it is a regression. It is like that for dev builds where you have dev engine version but for nightlies it was fixed.
