### ISSUE TITLE
Enso froze while working on project

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6563]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While working on project when I opened the CB and moved my mouse over ``join (Table)`` several errors appeared and enso became unresponsive.

![image](https://user-images.githubusercontent.com/108271897/236262891-233b3996-bd43-4dd9-9790-5f0b41d62350.png)

[Enso_201 v2023.5.3 console.txt](https://github.com/enso-org/enso/files/11399354/Enso_201.v2023.5.3.console.txt)

[Enso_201 v2023.5.3 localhost-1683215146793 part1.log](https://github.com/enso-org/enso/files/11399368/Enso_201.v2023.5.3.localhost-1683215146793.part1.log)

[Enso_201 v2023.5.3 localhost-1683215146793 part2.log](https://github.com/enso-org/enso/files/11399369/Enso_201.v2023.5.3.localhost-1683215146793.part2.log)

[2023-05-04T10-36-22.604Z-ide-2023.1.1-nightly.2023.5.3.log](https://github.com/enso-org/enso/files/11399372/2023-05-04T10-36-22.604Z-ide-2023.1.1-nightly.2023.5.3.log)

[20230504-103622-747-enso-project-manager.log](https://github.com/enso-org/enso/files/11399373/20230504-103622-747-enso-project-manager.log)

### Expected behaviour

Enso working

### Enso Version

2023.5.3 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by kazcw** [comment]
This is a repeat of #5813 and it's very concerning

**Comment by xvcgreg** [comment]
@kazcw so now we have some reproduction on another SysOp and full set of data :)

**Comment by kazcw** [comment]
Yeah. Closing this as a duplicate, since we already have some discussion in the other issue.

**Comment by kazcw** [comment]
Yeah. Closing this as a duplicate, since we already have some discussion in the other issue.

**Comment by farmaazon** [comment]
> Yeah. Closing this as a duplicate, since we already have some discussion in the other issue.

@kazcw please remember to add a proper label when closing task without implementation.
