### ISSUE TITLE
Navigating from a function (grouped nodes) adds an element to vector editor

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6565]
Steps I did:
- Clicked in a `Main.func1`
- Navigated back to the project
- Vector element was prepended to one of the nodes.

[Screencast from 2023-05-04 18-36-43.webm](https://user-images.githubusercontent.com/14013887/236269059-bfdf3959-6c62-4f3b-9e81-7e94153105eb.webm)

**Comment by wdanilo** [comment]
Oh wow, I'm so intrigued what is causing it!

**Comment by farmaazon** [comment]
To be checked if still reproducible after #6540

**Comment by Akirathan** [comment]
I am attaching one more screencast from today's book club that demonstrates that once you get outside the grouped nodes, *all* the vector editors prepend a default value
[Screencast from 2023-05-12 20-58-14.webm](https://github.com/enso-org/enso/assets/14013887/132ec175-6c80-4958-9622-4c30694c2b5d)

**Comment by farmaazon** [comment]
I don't reproduce it on the newest develop (08e6d21885497215cbef6bd358122c1eeec6ef3b). @Akirathan you can also check and reopen if you still do.

Closing as fixed by #6540

**Comment by Akirathan** [comment]
> I don't reproduce it on the newest develop (https://github.com/enso-org/enso/commit/08e6d21885497215cbef6bd358122c1eeec6ef3b). @Akirathan you can also check and reopen if you still do.

Seems working on the latest develop. I was also not able to reproduce it anymore. Thx for the fix.
