### ISSUE TITLE
Escape doesn't cancel node connection cut action

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6576]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I click on node connection and want to cancel this action pressing esc doesn't cancel it - I have to undo to reinstate the connection.

### Expected behaviour

Esc key cancels the connection breakage and reconnects the node as they were

### Screenshots or screencasts

https://user-images.githubusercontent.com/108271897/236439948-c1adc964-4bb5-4e3a-9df6-7e7dd624a633.mp4

### Enso Version

2023.5.5 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by vitvakatu** [comment]
I couldn't reproduce it locally on MacOS.

**Comment by wdanilo** [comment]
This is an important issue. I believe it wasn't ever implemented properly (escape should behave as Greg commented). @vitvakatu are you sure? I believe that what Greg sees is what we implemented long time ago.

**Comment by vitvakatu** [comment]
Ah, sorry, I misunderstand it. I thought it was about the inability to drop the edge with `Esc`, but it's actually the opposite. This is not a bug, then, but rather a new feature request. @sylwiabr could you assign priorities here?

**Comment by farmaazon** [comment]
Working fine in GUI2
