### ISSUE TITLE
Warning when opening the searcher (multi-line location not supported)

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#6586]
Open IDE, and create a new project. Press <kbd>Tab</kbd> to open the sercher.

The following warning appears in the DevTools console:
```
[WARN] lib\rust\ensogl\component\text\src\component\text.rs:129 Trying to compute coordinates for multi-line location. This is not supported yet.
```

There should be no warning.

**Comment by farmaazon** [comment]
Not reproducible in GUI2
