### ISSUE TITLE
Errors when closing searcher with no input.

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#6588]
Open IDE, and create a new project. Press <kbd>Tab</kbd> to open the searcher. Click outside to close the searcher. 

The following errors appear in the DevTools console:
```
router.ts:62 [ERROR] app\gui\src\presenter\searcher.rs:235 Error while committing node expression: Expected a single line, parsed none..
router.ts:62 [ERROR] app\gui\src\presenter\graph.rs:336 Failed to remove node in AST: Node with ID e0c80a7c-a3a3-4ab6-9c9c-c818ca49f0e4 was not found.
```

There should be no errors.

**Comment by vitvakatu** [comment]
I don't remember how it worked before, but failing when committing the empty node is technically the exactly needed thing. We just don't want to log such an error message, as this is not a regular failure. Perhaps a simple check in the `Searcher::commit_node` and changing the return type to `FalliblyResult<Option<ast::Id>>` will suffice.

**Comment by farmaazon** [comment]
I think the empty node should be a special case. Any other string should be actually parsed to a valid AST, so having an error there is not expected (and deserves an error log).

**Comment by farmaazon** [comment]
No errors in GUI2
