### ISSUE TITLE
Issue with undo and showing/hiding visualizations.

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#6589]
Open IDE, and create a new project. Wait until it initializes fully. Click on the node to select it. Press (don't hold) space to open visualization. The visualization appears. Press space again to hide the visualization.

Now repeatedly press Ctrl+Z to undo, After two presses (undoing hiding and undoing showing in the first place) they should do nothing more. However, it seems to work indefinitely, not exhausting the undo-redo stack.

See the video:
https://user-images.githubusercontent.com/1548407/236522265-db2aacf7-34ac-44be-a750-70227d8b74f6.mp4

**Comment by MichaelMauderer** [comment]
This might be alleviated by #6831, which fixes some cycles in the show/hide logic.
