### ISSUE TITLE
Undo not working properly for node created by drag&drop

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#6591]
Open IDE, and create a new project. Drag a file from another Window (e,g. the csv file from the first weekly book club). A new node that loads the file appears.

Press <kbd>Ctrl</kbd>+<kbd>Z</kbd> to undo. The node does not disappear, It takes several undo actions to undo a single action of dragging the file.

It should be a single, atomic action.

See the video:

https://user-images.githubusercontent.com/1548407/236549323-fe9e9249-a219-4bd3-b907-9b7b0eb2825f.mp4

**Comment by farmaazon** [comment]
Fixed in GUI2.
