### ISSUE TITLE
Searcher misbehaves when moving selection 

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#6598]
Do the following:
1. Start a new project.
2. Click on the initial node.
3. Press <kbd>Tab</kbd>.
4. Give it a moment. When everything is ready press <kbd>→</kbd> (right arrow key).

The error appears in the console and the selection immediately jumps back.

https://user-images.githubusercontent.com/1548407/236808166-6d4f5285-db39-434a-9189-3d0452602c88.mp4

**Comment by vitvakatu** [comment]
Duplicate of #6124
