### ISSUE TITLE
Problems when comitting string literal edit with the enter key.

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#6601]
Do the following:
1. Start a new project.
2. Ctrl+Click on the initial node to edit the literal.
3. Place the edit caret after the space character. 

Now, either:
4. Press the Backspace key to erase the space. 
5. Press the Return key to commit the change.

The node reverts to the original literal text (space comes back).

Alternatively:
4. Press the Space key to insert one more (second) space character.
5. Press the Return key to commit the change.

Now the text literal ends up with 3 space characters in that place. 

https://user-images.githubusercontent.com/1548407/236852729-bc5081e8-aecc-452c-b105-f3c12e0478b5.mp4

**Comment by farmaazon** [comment]
From my observations, we just always add a space _inside_ the literal when pressing enter.
