### ISSUE TITLE
Enso Chat

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#6610]
## General idea

The Enso Chat is a built-in the app chat for the clients. In case a client does not know how to perform a task, they can click it and instantly chat with someone from our team.

<br/>

## Accessing the chat

You can access it by pressing the chat icon at the top-right corner:

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/1623053/237008487-5a606ffe-f713-43ca-82ef-fea662712bb5.png">

After the icon is pressed, a chat window should open. It should be placed on the right side of the component browser and the dashboard, so the user would be able to modify the graph and use the dashboard while keeping the chat opened. However, as WebGL scene resizing is slow, technically, it should float over the EnsoGL scene and we should expose an API from GUI allowing for "virtual clipping of the scene". Such a virtual clipping would allow for passing information to EnsoGL about the visible scene size, which would, for example, prevent showing component browser off-screen (under the chat). However, such an API should not be part of the first implementation task.

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/1623053/237008750-07dc5d3e-c4e0-407b-b5c3-cda27ebdbed2.png">

<br/>

## Components of the chat window

<img width="370" alt="image" src="https://user-images.githubusercontent.com/1623053/237008880-bbba03a2-9501-4f04-b717-bd58ed15985e.png">

The chat window should display the following properties (top to bottom):
- The name of the current thread. In case no thread was created earlier, the name should be "New chat thread". After clicking the thread name, list of threads is displayed. In case in any of the threads there are new messages, an indicator (red bubble) should be shown next to the thread drop-down.
- Conversation divided into chat bubbles. Each chat bubble contains avatar of the person who has written the message, time formatted in the user-local format, and the message. For the Enso team, the avatar should be taken from Enso Discord server, and the real, full name should be used (first and last name). This makes the client feel that they are really speaking with a real person.
- Under the last message of Enso Team member, a reaction panel should be displayed, allowing the user to react with an emoji with a single mouse click. This also encourages the user to react to messages, as it is so easily accessible.
- After moving the mouse over any of Enso Team member messages, a reaction panel hovering over the bottom part of the message should be displayed as well. If there is at least one reaction given, the reaction panel should stay visible in the chat history under the message.
- An input panel allowing typing new messages. If the user typed at least one letter, the buttons under the input field start to be active (less transparent). The "reply" button simply posts the message, while the "New question? Click to start a new thread!" button posts this question in a new thread and switches to that thread.
- In case the user is not a paid user, a notification should be shown, as presented on the above image.

<br/>

## How the chat should work under the hood?
Under the hood, the chat should speak with a Enso Customer Chat Discord Bot (which should be created as part of this task), which should be a bridge between this chat and our Discord server. An example user session should look like follows:
- As soon as the user logs in to Enso, the information about user login should be send to Enso Customer Chat Discord Bot and the chat history is fetched. In case new messages were posted since user checked them last time, an indicator (red bubble) should be displayed next to the chat icon.
- After the user clicks the chat icon, the chat window opens with the last selected thread. In case the user did not use the chat yet, a new thread is created with the default name. 
- As soon as a thread in the Enso Chat is created, a thread in the "Customer Chat" Discord channel (of type "Forum") is created. The title of the Discord thread should be `name of the channel [customer_id]`.
- Every message posted by the user should be replicated and posted by the bot in the appropriate Discord thread. As soon as any of Enso team members replies in the thread, the message should be sent by bot to the application, if it is opened. The application should not waste any CPU cycles waiting for the message, so instead of polling, we should use web-sockets with direct communication between the chat bot and the Enso app. 
- The communication with Discord should be done via [discord.js library](https://discord.js.org), as it is the most popular of all Discord bindings.
- The emojis should use the open-source Twitter emoji images: https://twemoji.twitter.com
- The backend should run on Heroku-like thing. Simple git-push should be able to update the bot and its development/deployement should be as straightforward as possible. Please compare available options and chose one that is popular, robust, and provides fast, git-based development speed.

<br/>

## Possible future extensions

This chat and bot can (and probably will) become the basis for our customer support. For example, if a logged customer (via app our our website) asks a question about their billing, someone from our team should be able to write in the Discord thread `!billing history` and get a billing history printed in this discord thread (visible only for Enso members). This way, our customer support could really fast query the bot for information about specific user and reply to them from within the same chat window. This could also allow for creating template replies. For example, someone from our customer support team could write `!send pricing info` and a nicely formatted message about pricing info will be send to the user.

**Comment by farmaazon** [comment]
Added to `Epics` board, as I feel this is longer than one-week task.

**Comment by somebody1234** [comment]
re: communication with discord: while discord.js *is* the most popular, it may be worth considering other options, e.g.:
- discordeno + node.js (functional style)
- using the current aws lambdas as backend - webhooks (user -> discord) are simple HTTP requests, websockets (user <-> backend) can be done through AWS API gateway + lambdas, so the only issue would be sending messages back (discord -> user)
  - however, discord -> user can be done with a very minimal discord bot that just listens for messages and sends them to a lambda on the backend

assuming we do still want paas (so not using aws lambdas as the backend), here are the options:
- heroku:
  - :heavy_check_mark: supports node (out of the box)
  - :heavy_check_mark: github deploy on push (integration?)
  - :heavy_check_mark: rollbacks
  - :question: cost effective (uses AWS internally, but still on the lower side as (afaict) each dyno doesn't get a dedicated CPU)
- digitalocean: 
  - :heavy_check_mark: supports node (buildpack/docker image)
  - :heavy_check_mark: github deploy on push (out of the box)
  - :heavy_check_mark: rollbacks - to any previous deployment ([more info](https://docs.digitalocean.com/products/app-platform/how-to/manage-deployments/#roll-back-to-a-previous-deployment-using-the-control-panel))
  - :heavy_check_mark: cost effective
- aws elastic beanstalk:
  - :heavy_check_mark: supports node (process unknown: [official docs provide example "source bundles"](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/nodejs-getstarted.html))
  - :heavy_check_mark: github deploy on push (out of the box) - [guide](https://faun.pub/how-to-create-cicd-using-github-as-source-and-elastic-beanstalk-244319a2a350)
  - :question: rollbacks - "manual rollback" ([more info](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features.deploy-existing-version.html))
  - :x: cost effective (uses AWS EC2, which are a lot more costly than a simple VPS like AWS Lightsail)
  - :heavy_check_mark: integrates with services we are already using, like dynamodb
  - :heavy_check_mark: integrates with cloudformation ([more info](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/AWS_ElasticBeanstalk.html)) - however we probably don't need to dynamically provision instances anytime soon, so not necessarily a reason to use Elastic Beanstalk
- google app engine:
  - :heavy_check_mark: supports node (out of the box)
  - :heavy_check_mark: github deploy on push ([gh action](https://github.com/google-github-actions/deploy-appengine))
  - :heavy_check_mark: rollbacks - to any previous deployment ([more info](https://cloud.google.com/run/docs/rollouts-rollbacks-traffic-migration))
  - :x: cost effective - like ec2, dedicated CPUs are pretty pricey
  - :heavy_check_mark: generous free tier
- azure app service:
  - :heavy_check_mark: supports node (out of the box; deploy via vs code extension)
  - :heavy_check_mark: github deploy on push (out of the box via [github actions](https://learn.microsoft.com/en-us/azure/app-service/deploy-github-actions?tabs=applevel))
  - :question: rollbacks - between a fixed set of "deployment slots" ([more info](https://learn.microsoft.com/en-us/azure/app-service/deploy-staging-slots))
  - :x: cost effective - dedicated cpus as well

there are other PaaS options but these are the most popular/well known cloud providers

overall, i think the strongest contenders are:
- DigitalOcean for cost savings (and ease of use)
- AWS for tighter integration with existing services already being used (may be convenient in the future if we want to access backend info like billing history), or just to have one less piece in the tech stack. the others

**Comment by sylwiabr** [comment]
@somebody1234 @PabloBuchu can you split this to smaller issues (probably in the cloud repository for easier tracking) that will be max 3-5 points and we can then plan it?

**Comment by somebody1234** [comment]
re: twemoji, we may want to consider adding the icons to `ide-assets`.
on one hand, it's technically unnecessary - and most, if not all, of the other dependencies are being loaded from the internet
on the other hand, because the icons maybe be visible from the moment chat is opened, it might be noticeable if the images load in in a random order

**Comment by wdanilo** [comment]
@somebody1234 thank you so much for the detailed writeup above!

Regarding tech stack, I believe that using `discord.js` is the best bet here, because:
1. It's most popular, so there is a lot of docs, and a lot of people that can help us.
2. It's updated often - e.g. Discord introduced forum channels and the same week the API was updated.
3. Writing things as a simple TypeScript code that is run somewhere on the server will be easy to debug and maintain. I don't see benefits of doing that via AWS API gateway + lambdas, but if there are any strong benefits, I'd be thankful for some deeper information about it - then we'd need to discuss it.

Regarding Heroku vs other things – it seems like you did a pretty deep comparison between them, that is an amazing job, thank you! In such a case, it seems like DigitalOcean is our best bet, is that correct? :)

**Comment by somebody1234** [comment]
i think they're all more or less equal feature wise, so i *think* digitalocean should be more than fine until we find that it's lacking something, yeah. and i think most if not all of them require no special setup, so vendor lock-in shouldn't be a problem

**Comment by wdanilo** [comment]
@somebody1234 as you are working over 1 week on this task, would you be able to split it into several PRs, please? Otherwise, if we will have one huge PR to review, there is big possibility the review will be very long and painful.

**Comment by somebody1234** [comment]
the majority of it is on the Discord bot - the frontend part is currently ~450 lines in total

speaking of the Discord bot - where should it be pushed to? a new private (or public) repo?

(i think it'll have to be its own repo either way because we are planning to use github deploy on push, right?)

**Comment by wdanilo** [comment]
Yeah, we should probably keep it in a separate repo. I've created one for you here: https://github.com/enso-org/enso-bot :) D o you think it would be possible to split it into several PRs, or would it be hard and time consuming?

<blockquote><img src="https://opengraph.githubassets.com/edca8715eb4b5a0b4f832e252096cdd8eac19df2f1d965fd05641932735a5b0a/enso-org/enso-bot" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso-bot">GitHub - enso-org/enso-bot</a></strong></div><div>Contribute to enso-org/enso-bot development by creating an account on GitHub.</div></blockquote>
