### ISSUE TITLE
SuggestionBuilder needs to send `ascribedType` of constructor parameters

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6611]
When building the meta data for a constructor (`buildAtomConstructor` in `SuggestionBuilder`), the ascribed type of the parameters is not used and only `Any` is passed.

In order for the dropdowns to work this must contain the type information.

**Comment by JaroslavTulach** [comment]
Slightly related to #6584 which is supposed to verify that `ascribedTypes` are correct.
