### ISSUE TITLE
Understand the decision logic to add a specific type import and update the method to know current set.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6613]
Currently when we add things via the component browser the import list gets duplicated (as a lot is exported in Standard.* anyway).

We want to understand how we determine whether or not to add to this list and improve logic.

```
from Standard.Base import all
from Standard.Base.Data.Boolean import Boolean
from Standard.Base.Data.Index_Sub_Range import Index_Sub_Range
from Standard.Base.Data.Ordering.Sort_Direction import Sort_Direction
import Standard.Base.Data.Text.Extensions
from Standard.Base.Data.Text.Text_Ordering import Text_Ordering
from Standard.Base.Errors.Problem_Behavior import Problem_Behavior
from Standard.Base.Network.HTTP.HTTP_Method import HTTP_Method
from Standard.Base.System.File.Existing_File_Behavior import Existing_File_Behavior
import Standard.Base.System.File.Write_Extensions
from Standard.Database.Data.Table import as Table
from Standard.Table import all
from Standard.Database import all
from Standard.Table.Data.Column import Column
from Standard.Table.Data.Column_Selector import Column_Selector
from Standard.Table.Data.Match_Columns import Match_Columns
from Standard.Table.Data.Table import Table
from Standard.Table.Data.Type.Value_Type import Value_Type
import Standard.Visualization
```

**Comment by 4e6** [comment]
The `Suggestion` object has a `reexport` field that contains the shortest module (module with the shortest path) re-exporting this suggestion. 

Initially, the suggestion is created with an empty `reexport` field. The field gets populated in the SuggestionsHandler https://github.com/enso-org/enso/blob/4ba8409defb01a698e606f4de0f9a76231b54419/engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala#L487 when the database update is applied and then sent to IDE as an update message.

After implementing the library suggestions cache, SuggestionsHandler no longer sets re-exports for loaded library suggestions https://github.com/enso-org/enso/blob/4ba8409defb01a698e606f4de0f9a76231b54419/engine/language-server/src/main/scala/org/enso/languageserver/search/SuggestionsHandler.scala#L460-L471

The fix would be to set the suggestion `reexport` field when building the suggestions cache https://github.com/enso-org/enso/blob/4ba8409defb01a698e606f4de0f9a76231b54419/engine/runtime/src/main/scala/org/enso/compiler/SerializationManager.scala#L255-L257
