### ISSUE TITLE
A simple vector with warnings does not highlight the node

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6616]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![Screenshot from 2023-05-09 14-15-32](https://github.com/enso-org/enso/assets/292128/1efc6368-26f5-4e86-8b23-b601d5326c68)

The above screenshot visualizes warnings, not data. So they clearly are there.

### Expected behaviour

Should be wrapped in orange, similar to our regular warnings.

![Screenshot from 2023-05-09 14-55-22](https://github.com/enso-org/enso/assets/292128/85f3312d-d554-4e60-9e35-328e331a303c)

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by hubertp** [comment]
More surprisingly, when using the value it will display orange warning when CB is open (it will disappear afterwards. 
![Screenshot from 2023-05-11 13-18-16](https://github.com/enso-org/enso/assets/292128/ef00cd16-62fd-480e-a3d0-7684cac062bb)

**Comment by Akirathan** [comment]
In CLI, it works as expected. The following snippet produces "[bla]":
```
from Standard.Base import all

main =
    vec = [Warning.attach "bla" 1]
    IO.println <| Warning.get_all vec . map (_.value)
```

**Comment by Akirathan** [comment]
**Update**

Seems most likely related to language-server and that language-server in its `expressionUpdates` message does not fill in the `payload.warnings` parameter correctly for, e.g., `[Warning.attach "foo" 1]`.

**Comment by Frizi** [comment]
![image](https://github.com/enso-org/enso/assets/919491/e2a48634-cb94-4530-9763-67cf73abd679)

It looks like the warnings are not properly attached to the whole vector for cases where errors come from vector entries. The language server doesn't provide the warnings to the IDE in those cases. It works correctly if you attach the warning to the whole vector expression yourself.

Response for `Warning.attach "bla" [1]`:
```json
      {
        "expressionId": "11760322-d298-439e-978e-dc4d2f5ae573",
        "type": "Standard.Base.Data.Vector.Vector",
        "methodPointer": {
          "module": "Standard.Base.Warning",
          "definedOnType": "Standard.Base.Warning.Warning.type",
          "name": "attach"
        },
        "profilingInfo": [{ "ExecutionTime": { "nanoTime": 9861800 } }],
        "fromCache": false,
        "payload": {
          "type": "Value",
          "warnings": { "count": 1, "value": "'bla'" }
        }
      },
```

Response for [Warning.attach "bla" 1]:
```json
      {
        "expressionId": "994a1f47-d7af-4ec0-83d9-ba69e03d50cf",
        "type": "Standard.Base.Data.Vector.Vector",
        "methodPointer": null,
        "profilingInfo": [{ "ExecutionTime": { "nanoTime": 157567500 } }],
        "fromCache": false,
        "payload": { "type": "Value", "warnings": null }
      },
```

**Comment by JaroslavTulach** [comment]
I think the problem is in [ProgramExecutionSupport:354](https://github.com/enso-org/enso/blob/0055973f628782c747f0e918627621fe51a6976e/engine/runtime/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala#L354) - it checks for `WithWarnings`, but `Vector` isn't being wrapped by that class, it has `withWarnings` field. We should be using `WarningsLibrary` instead.
