### ISSUE TITLE
Editing widgets

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#6622]
## Overview

Widgets allow users to change node parameters simply by clicking or dragging values. However, sometimes more fine-grained control is required. This issue summarizes all the ways a widget can be edited.

<br/>

## Editing widget by clicking / dragging the values

Widgets can react to mouse down, mouse up, and vertical mouse drag events. They should never react to vertical mouse drag events, as vertical drag is reserved for widget ordering initialization, for example, if they are placed within the list editor widget. There is one exception to this rule, though. In case a widget wants to provide a secondary control to the user, this control can use vertical drag. A good example is the slider widget. You can drag it left and right to change the value, and you can move your mouse up and down during the drag to change the slider precision. This works well with the list editor because of two reasons:

1. The vertical drag happens normally after the horizontal drag to adjust the precision during the drag.
2. The list editor has a timer, which will pass the vertical drag events to the widgets if the user clicks the widget and does not move their pointer for approximately 0.5 seconds. In this case, if someone wants to adjust the precision of the slider without moving it, they can click the slider and wait a little before moving the mouse up or down.

Editing widgets by clicking or dragging the values should be considered the most common and most important way of interacting with widgets.

<br/>

## Editing widgets by providing their values from keyboard

All widgets should implement this mode. After double-clicking a widget, the value on the widget should switch to an editable mode. For example, after double-clicking the slider, the slider should still be visible, but its value should be highlighted, allowing the user to type their own value. After the user presses the `enter` key, the value should be accepted if it was correct. In case an incorrect value was typed (for example, test in a numeric slider), there should be a popup error about it, and the widget should remain in edit mode.

<br/>

## Editing widgets as a code

After `ctrl + LMB` click on a widget, it should enter "code-edit mode". In this mode, the user is able to write any code expression, by default in the Enso language, but we should support other languages in the future as well. For example, given this node:

<img width="295" alt="image" src="https://github.com/enso-org/enso/assets/1623053/1b97106e-8e67-4f2f-afe9-9d6b0b01805b">

After `ctrl + LMB` on the `delimited` value, the code-edit mode should look as follows (please, do not look at other parts of the node - they come from a different mockup):

<img width="295" alt="image" src="https://github.com/enso-org/enso/assets/1623053/de1e598e-00d9-49b6-bb5f-57d8ba7d8edf">

After the expression is accepted, the widget should be displayed as follows (the value visible next to the language icon is the value of the evaluated expression, not the code):

<img width="314" alt="image" src="https://github.com/enso-org/enso/assets/1623053/e2c1eb73-1c9c-4147-aa61-4069824a554e">

In the future, the user should be able to click on the language icon and choose another supported language from the drop-down menu.

The `ctrl + LMB` click on the node icon should turn the whole node into code-edit mode, allowing the user to write an arbitrary expression by hand. After finishing editing, the node should become visible again based on the written expression, unless the chosen language is different from Enso. In the case of a different language, the node icon should remain the same as during the node editing (e.g., showing the Python language logo).

**Comment by farmaazon** [comment]
>  They should never react to horizontal mouse drag events, as horizontal drag is reserved for widget ordering, for example, if they are placed within the list editor widget.

@wdanilo Is this actually the current state? I thought actually the _vertical_ drags are reserved for removing/moving elements in List Editor.

Also regarding "Editing widgets as code", should we automatically add parenthesis if the edited code would change the context of code in other widgets (e.g. write `->` which turns them into lambda).

**Comment by wdanilo** [comment]
@farmaazon yes, thanks for catching it. Vertical drags are reserved for element reordering! I feed the original description!

Regarding parenthesis – we should add in the code parentheses that are required, yes. But it would be good if these were not visible to the user if they (users) are editing code of a single widget.

**Comment by farmaazon** [comment]
Closing, as
1. The design here is dated
2. New one is implemented as part of #8750
