### ISSUE TITLE
Restoring to last saved snapshot should ask for confirmation

### ISSUE THREAD

**Issue by Procrat** [enso-org/enso#6624]
### Discord username

Stijn#6455

### How important is this feature to you?

0 – Not too important

### Describe the idea you'd like to see implemented.

Following up from #6377, we'd like to have a confirmation pop-up before restoring a saved snapshot, especially since this can be relatively easily triggered by a shortcut. (The shortcut will change from `ctrl-r` to `ctrl-shift-r` in #6620 though.)

### Would you be willing to help us implement this feature?

No

**Comment by farmaazon** [comment]
Closing for now, as in new GUI we don't have snapshot yet.
