### ISSUE TITLE
Weird scaling behavior on Enso project start when the window was rescaled

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6626]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Enso goes through weird scaling steps to addjust to the new window size. Also during that process the part of the Graph Editor background is rendered in different color than the rest (part that was revealed during the resize).

### Expected behaviour

No node/node graph rescaling on window changing shape/size
Consistent BG color
(faster performance - mouse was unresponsive over Enso but worked over the console - it took ~3mins to launch the project (previously it was ~1min + 0-20sec)

### How we can reproduce it?

Resize Enso window while some larger project is starting

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/108271897/ab316238-5f2d-4bf8-bae8-783d5ea083f0

### Enso Version

2023.5.10 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by farmaazon** [comment]
The rescaling steps may be unavoidable (this is just how the browser is handling things AFAIK), but it seemingly does not render anything for a very long time here. 

@xvcgreg does the project start 3 minutes only when you're rescaling on load, or every time?

**Comment by xvcgreg** [comment]
@farmaazon Every time now - there's some rather nasty performance regression since yesterday.

2023.5.10 Nightly:

https://github.com/enso-org/enso/assets/108271897/74173984-72b6-4c8c-a6d1-0cbb1b303281


2023.5.9 Nightly:

https://github.com/enso-org/enso/assets/108271897/ac752de7-2c15-41ce-81b7-c67ef7de60dc

**Comment by xvcgreg** [comment]
2023.04.28 Nightly:
startup time 2:43

https://github.com/enso-org/enso/assets/108271897/585a7631-07a8-4d7d-999c-7989d5ceb01c

**Comment by Akirathan** [comment]
The recent performance regression is tracked in #6630, which also includes the screencasts of loading the project.

**Comment by Frizi** [comment]
I believe that the apparent resize glitch is just a consequence of main thread being blocked for a while. The screen will appear unresponsive during that time no matter what we do really. The only real option to fix that is to improve startup performance.

**Comment by Akirathan** [comment]
Closing this as a non-issue.
