### ISSUE TITLE
Constructors should not be shown in the component browser when connected to an instance.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6627]
We don't see the static methods any more but do still see constructors for links from an instance.

![image](https://github.com/enso-org/enso/assets/4699705/5f792794-2310-424c-ad36-507b254b9de1)

To reproduce:
- Add 1.up_to 10
- Drag out and filter to between
- Should not show between.

**Comment by Frizi** [comment]
We do want to have the constructors present in suggestion database, since it is also used for expression method resolution, which widgets depend on. The fix should then be GUI-side, the component browser should filter the entries.

**Comment by farmaazon** [comment]
So far, filtering is done on the Engine side (we just display result of `searcher/completion` call), so the fix is rather on the Engine side, I'm afraid.

It should not send constructors then `self type` is present. It already do it with static methods.
