### ISSUE TITLE
Opening a project (attached) is freezing GUI after coloring the nodes and making cursor disappear

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6632]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Opening a project attached to the issue is having few problems:
1. nodes are appearing after a very long time
2. when nodes are colored after a few seconds GUI gets irresponsive:
- mouse cursor is disappearing
- there are huge lags on panning/zooming
- it is not possible to edit the nodes

### Expected behaviour

This project is rather small - it should work without problems

### How we can reproduce it?

Open the project:
[Unnamed_5_1.enso-project.zip](https://github.com/enso-org/enso/files/11441335/Unnamed_5_1.enso-project.zip).
 
Try to interact with it. Alert: there is a lot of performance issues while working with this project - when we were trying to clean up the project with James GUI was freezing pretty often ad getting desynchronized with engine. Separate issues will come.

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/12892578/e02ddfcd-1500-43ac-98a8-479c42f76df1

### Enso Version

nightly 10.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
May have something to do with #6630

**Comment by xvcgreg** [comment]
Yes, described behavior is the same as I'm experiencing (#6630).

**Comment by kazcw** [comment]
I have reproduced this with a build older than the #6630 fixes, and found that in a current build performance is fine. I think it's safe to say this was another instance of the same problem, which has drastic improvements merged on both backend and frontend.
