### ISSUE TITLE
Debug logs left in the console

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6636]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When working with the workflow the console is polluted with:
<img width="472" alt="image" src="https://github.com/enso-org/enso/assets/12892578/9168189e-b85c-4494-b0c7-9f054fbcbc81">

### Expected behaviour

Meaningful informations displayed in the console

### Enso Version

nightly 10.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by vitvakatu** [comment]
Addressed in https://github.com/enso-org/enso/pull/6595
