### ISSUE TITLE
Adding a node to existing workflow is freezing IDE for a second

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6637]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Adding a new node to the bigger workflow is making the IDE unresponsive - the project is attached below

### Expected behaviour

Adding a node should not freeze the cursor and IDE

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/12892578/802a0e24-fd69-41ef-9181-adea03410e7b

[Unnamed_7.enso-project.zip](https://github.com/enso-org/enso/files/11442678/Unnamed_7.enso-project.zip)

### Enso Version

nightly 10.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by Akirathan** [comment]
Tried reproducing it on Fedora 38, with NVIDIA RTX A2000 GPU, Nouveau drivers, Wayland, on Chromium. I experience similar lag as you, although not after adding the node, but just after dragging the connection and clicking -right before CB is shown. The FPS is stable 60 but before CB was shown, dropped to 5 for a second or so. I didn't want to screen record it as that might affect the observations.

Assigning this to the GUI team

**Comment by farmaazon** [comment]
@sylwiabr Once you'll be back, please check if this issue is not fixed by https://github.com/enso-org/enso/pull/6954

**Comment by sylwiabr** [comment]
can't repro on package from 05.07
