### ISSUE TITLE
When changing an input such that whole workflow breaks the IDE loses the connection while errors being evaluated.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6639]
https://github.com/enso-org/enso/assets/4699705/a0f5a8d3-ac6e-4b2c-abf6-8cab299089d4

With an older version of the IDE (2nd May Nightly and newest backend) while very slow (~50s to complete) it didn't die.
Newest IDE (10th May develop) the connection gets lost and the workflow needs reloaded.
[Enso_201.enso-project.tar.gz](https://github.com/enso-org/enso/files/11443966/Enso_201.enso-project.tar.gz)

The sample workflow is attached.

To reproduce change the top file format to JSON.

**Comment by Akirathan** [comment]
I tried it on my machine, but I cannot reproduce it. I don't lose the connection to the backend, probably because my CPU is more powerful. Could you try it one more time and also attach very verbose logs pls? So that we can find out what happened on the Language Server side.

**Comment by sylwiabr** [comment]
It doesn't appear on https://github.com/enso-org/enso/pull/6540 branch so I assume it is GUI side - we should check it after merging it

**Comment by hubertp** [comment]
Tried with the provided project, I can confirm that it breaks with the standalone version.

**Comment by hubertp** [comment]
Can't reproduce this reliably. I think my machine was under heavy load which might have triggered the slowdown. On successive attempts I couldn't reproduce the connection failure again. 

I could see that when making small changes, we can trigger a massive recompilation which can take on its own a lot of time:
```
[debug] [enso] Job org.enso.interpreter.instrument.job.ExecuteJob@3f110b59 finished in 2066 ms
```
But that should still not trigger connection failures.

**Comment by hubertp** [comment]
Was no longer able to reproduce this. And even if possible, IDE workarounds for synchronization problems should prevent this from happening.
