### ISSUE TITLE
Map visualization is not working anymore

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6645]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The map visualization is blank. It was working correctly on the package yesterday. I am assuming one of the commits from @somebody1234 broke loading the visualizations. Please confirm and fix it.

### Expected behaviour

Map visualization visible

### How we can reproduce it?

Open Restaurants example and see if the map is visible there.

### Enso Version

nighty 11.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by PabloBuchu** [comment]
apparently this js file is not being loaded properly

<img width="962" alt="map_vis" src="https://github.com/enso-org/enso/assets/2855109/3ab6c1ab-f5d1-462f-9a45-bd923c44b064">
