### ISSUE TITLE
Scrolling drop-down is panning the scene

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6649]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

If I have a drop-down with many entries and I have to scroll it the scene is also panned.

### Expected behaviour

Scrolling drop-down should not cause panning of the scene.

### Enso Version

nightly 11.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by Frizi** [comment]
We should migrate all scrolling to new event system, that way it will be possible to use `stop_propagation` to prevent the scroll from being handled twice.

**Comment by wdanilo** [comment]
@Frizi even better would be to use display-object based focus there, and send scroll events only to the focused element. Stop propagation is tricky and if we will start using it everywhere , the code will be hard to maintain in the future.

**Comment by farmaazon** [comment]
No longer a problem in GUI2.
