### ISSUE TITLE
Removing a node from a canvas is removing first the node and then the input port selection

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6650]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/4a6ae5df-1f6d-4a59-969f-f71525442ea0

### Expected behaviour

there should be no delay

### Enso Version

nightly 11.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by Akirathan** [comment]
I can reproduce this with `enso-linux-2023.2.1-nightly.2023.5.10.AppImage`. Although on my machine, it's faster, but I can see that the input port selection disappears after the node has already disappeared.

**Comment by Akirathan** [comment]
It can also be reproduced on the latest `develop`

**Comment by Frizi** [comment]
I reproduced it and it is linked with new widget tree implementation. The node port shapes for yet unknown reason are destroyed a frame later than everything else.

**Comment by farmaazon** [comment]
Maybe because of garbage collector https://github.com/enso-org/enso/blob/236bb9b988ba096dafff6f6d29c2e30b47f78bc8/lib/rust/ensogl/core/src/display/garbage.rs#L48 ?

**Comment by farmaazon** [comment]
Not reproducible in GUI2
