### ISSUE TITLE
When longer using the app sometimes pop-up is sticiking to the mouse coursor 

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6651]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/fb10dbbc-9bed-4248-a4a7-8e4386f3b8d1

### Expected behaviour

pop-up should disappear

### Enso Version

nightly 11.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by Akirathan** [comment]
Can reproduce with:
- Create a new node, e.g., a "bla" literal
- Hover over the marketplace icon in the CB
- Once the "Marketplace will be available soon" popup appears, accept the node with `Enter`.
- The "Marketplace will be available soon" popup now is displayed all the time next to the mouse cursor and cannot be discarded.
[Screencast from 2023-05-15 13-21-18.webm](https://github.com/enso-org/enso/assets/14013887/74414965-5d31-4477-a1e0-e1b944039f73)

**Comment by Frizi** [comment]
The component browser left-bar icons are implemented using `Grid` view, which doesn't properly handle hovering/unhovering in some rare cases (when the mouse is moving fast) or when it is destroyed (the last "mouse out" will not be registered after if it destroyed). While the grid mouse handling could be improved, I believe that the left bar should instead simply be changed to use a column autolayout. That would also have positive performance consequences.

**Comment by farmaazon** [comment]
This is why the "garbage collector" was designed in EnsoGL: https://github.com/enso-org/enso/blob/236bb9b988ba096dafff6f6d29c2e30b47f78bc8/lib/rust/ensogl/core/src/display/garbage.rs

<blockquote><img src="https://opengraph.githubassets.com/43e22fc746d43dc98d916cc6dd33bbd042068be8634ee0691825b5a20d0889c8/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">enso/garbage.rs at 236bb9b988ba096dafff6f6d29c2e30b47f78bc8 · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by farmaazon** [comment]
I think this should be no longer reproducible after merging #7177. @sylwiabr if you still notice this, please reopen.
