### ISSUE TITLE
State is lost inside of `Vector.map`

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6656]
Run the following repro:
```
from Standard.Base import all
import Standard.Base.Runtime.State

main =
    State.run Number 0 <|
        IO.println (State.get Number)
        ["A", "B"].each x->
            IO.println "Vector.each: "+x+": "+(State.get Number).to_text
        ["X", "Y"].map x->
            IO.println "Vector.map: "+x+": "+(State.get Number).to_text
```

## Actual result

```
0
Vector.each: A: 0
Vector.each: B: 0
Execution finished with an error: State is not initialized for type Number.
        at <enso> <anonymous><arg-0>(state_is_lost.enso:10:47-62)
        at <enso> <anonymous><arg-1>(state_is_lost.enso:10:46-71)
        at <enso> <anonymous><arg-1>(state_is_lost.enso:10:24-71)
        at <enso> <anonymous>(state_is_lost.enso:10:13-71)
        at <enso> <anonymous>(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\Data\Vector.enso:519:36-55)
        at <enso> Vector.map(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\Data\Vector.enso:519:9-55)
        at <enso> state_is_lost.main<arg-1>(state_is_lost.enso:9-10)
        at <enso> state_is_lost.main(state_is_lost.enso:5-10)
```

## Expected result

```
0
Vector.each: A: 0
Vector.each: B: 0
Vector.map: X: 0
Vector.map: Y: 0
```

**Comment by radeusgd** [comment]
I suspect it may have something to do with the function being invoked from within `Vector.new` - apparently the `State` data is not forwarded there.

**Comment by radeusgd** [comment]
I can also reproduce this with `Array_Proxy`:

```
from Standard.Base import all
import Standard.Base.Runtime.State
from Standard.Base.Data.Array_Proxy import Array_Proxy

main =
    State.run Number 0 <|
        IO.println (State.get Number)
        
        arr = Array_Proxy.new 10 x->
            sn = State.get Number
            IO.println "Array_Proxy.new: "+x.to_text+": "+sn.to_text
            x+sn
        IO.println arr

```
yielding
```
0
Execution finished with an error: State is not initialized for type Number.
        at <enso> <anonymous>(state_is_lost.enso:10:18-33)
        at <enso> <anonymous><arg-0>(C:\NBO\enso\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\lib\Standard\Base\0.0.0-dev\src\Data\Vector.enso:519:46-54)
...
```


**BUT** tbh with `Array_Proxy` I think this may be the right thing to do. The proxy element is computed at access time, which can indeed be long after the original `State.run` has completed. Also, changing the state could influence the results given from the `Array_Proxy` making it 'too mutable'.

So I think that while with `Vector` this is definitely a bug - `map` is a casual function and should support state, with `Array_Proxy` that bug is a **feature** :)

So I think when solving this, ideally we should additionally:
- not fix this for `Array_Proxy`, only for Vector,
- add a note in the `Array_Proxy` documentation that state is inaccessible from within the `Array_Proxy` as that is too much of a risk for immutability - we can always capture the current state before computing the proxy, i.e.:
  instead of
  ```
  arr = Array_Proxy.new 10 x->
    x + State.get Number
  ```
  one should do
  ```
  current_state = State.get Number
  arr = Array_Proxy.new 10 x->
    x + current_state
  ```
  essentially 'freezing' the state in closure. I'd appreciate the documentation containing this example as part of the explanation.
- add a test ensuring that _indeed_ `State` is inaccessible within `Array_Proxy` - to guarantee that our documentation does not lie (i.e. if by accident we 'fix' it in the future).

**Comment by JaroslavTulach** [comment]
As [noted here](https://github.com/enso-org/enso/issues/6955#issuecomment-1598257945): The state is lost in Vector.newFromFunction which is using InteropLibrary to invoke a Function and [Function.java:190](https://github.com/enso-org/enso/blob/1859ccbab5dc69bb14ef44b4afe59b280d52dee5/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/function/Function.java#L190) is using emptyState() instead of provided state in @ExportMessage and Execute message handler.

**Comment by JaroslavTulach** [comment]
According to @kustosz the following code should fail:
```haskell
main =
    arr = State.run Number 0 <|
        IO.println (State.get Number)
        
        Array_Proxy.new 10 x->
            sn = State.get Number
            IO.println "Array_Proxy.new: "+x.to_text+": "+sn.to_text
            x+sn
    IO.println arr
```
assuming `Array_Proxy` is lazy.

**Comment by radeusgd** [comment]
> According to @kustosz the following code should fail:
> 
> ```haskell
> main =
>     arr = State.run Number 0 <|
>         IO.println (State.get Number)
>         
>         Array_Proxy.new 10 x->
>             sn = State.get Number
>             IO.println "Array_Proxy.new: "+x.to_text+": "+sn.to_text
>             x+sn
>     IO.println arr
> ```
> 
> assuming `Array_Proxy` is lazy.

Interesting. Shouldn't the lambda (taking `x`) actually capture the current state in its closure and thus make it work? 

It seems really weird to me that laziness of some computation influences the 'scope' (including state) at which it is computed.
