### ISSUE TITLE
Widgets fail to parse in the IDE if their label or code contains a double quote "

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6657]
Repro:
- modify some custom widget to contain a `"`
- open the IDE with the widget displayed

I modified `Text_Sub_Range.default_widget` (currently on my PR #6641, should be merged soon, it can also be tested on any other widget):
```diff
diff --git a/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso b/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso
--- a/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso	(revision 607a45525f30fdece328a8a58a308f345bc02b7c)
+++ b/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Text/Text_Sub_Range.enso	(date 1683889513913)
@@ -58,7 +58,7 @@
     ## PRIVATE
     default_options : Vector Option
     default_options =
-        o1 = Option "Before" "(Text_Sub_Range.Before ' ')"
+        o1 = Option 'has a " quote' "(Text_Sub_Range.Before ' ')"
         o2 = Option "Before_Last" "(Text_Sub_Range.Before_Last ' ')"
         o3 = Option "After" "(Text_Sub_Range.After ' ')"
         o4 = Option "After_Last" "(Text_Sub_Range.After_Last ' ')"
```

Then I open a project that has a `Text.take` node in it:
<img width="290" alt="image" src="https://github.com/enso-org/enso/assets/1436948/db62bc3b-9b84-4dcf-a915-b713eba622fa">

I can see the issue in the logs:
<img width="174" alt="image" src="https://github.com/enso-org/enso/assets/1436948/785d9cd5-0760-4f8b-bcc8-e892d5a73827">

And when I open the widget, I can see it fell back to default instead of my custom one, due to this issue:
<img width="650" alt="image" src="https://github.com/enso-org/enso/assets/1436948/bef19cf0-b629-4630-a2bf-4021296167fc">

**Comment by Frizi** [comment]
This will be addressed in https://github.com/enso-org/enso/pull/6540
