### ISSUE TITLE
New Dashboard: Cannot reset my password

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#6659]
### Discord username

farmaazon

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I cannot reset password on my "official" Enso account in Enso application. The account was only authenticated with Google so far.

Once I click the button, an error appears in the console:

![image](https://github.com/enso-org/enso/assets/3919101/903d9019-114c-4f58-b79b-b04367b41929)

### Expected behaviour

I can reset password and be able to log in with password instead of Google.

### Enso Version

9e71fea844920ecedcc93ca774e33ad40d4576a8

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

Garuda Linux 6.3.1-zen1-1-zen

**Comment by PabloBuchu** [comment]
This was due a bug in our AWS Cognito configuration. Basically we were creating users with "not verified" email addresses. The problem has been fixed and I will manually verify your account (and any other who signed up before the fix)
