### ISSUE TITLE
`--startup.project` option does not work with the new dashboard.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#6666]
When providing `--startup.project` option, the IDE went directly to the project view, now it displays Dashboard instead. We should fix this or remove the option from the list.

The latter is less preferable, as it's convenient to me to run something like `enso-build-cli ide watch --skip-wasm-opt --ide-option --debug.dev-tools --ide-option --startup.project --ide-option Unnamed_7` so I don't have to pick the project on every electron restart.

**Comment by farmaazon** [comment]
Moreover, this option breaks the project: No matter what project do I open in the dashboard, the appointed one is opened, but the node are not colored.

**Comment by somebody1234** [comment]
should it be able to go back to the dashboard? (it's a lot easier to not allow it to go back to the dashboard, just wondering what is the more correct thing to do here)

**Comment by somebody1234** [comment]
on second thought, i think the dashboard should be completely disabled, since manipulating the URL query string to remove `-startup.project` to allow opening a different project is A Bad Idea

**Comment by somebody1234** [comment]
for posterity: it will be changed to open the dashboard soon, since we want to avoid introducing different modes where e.g. something is disabled. see this comment for more info:
<https://github.com/enso-org/enso/pull/6671#issuecomment-1549472236>
