### ISSUE TITLE
IDE died while editing a node 

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6672]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

It happened few times during last two days: IDE died without any message to the user while working normally (editing the node). The error in the console was: `Peer has replied with an error:  File not found `. Full session had just around 4 min so attaching the link to the video: https://drive.google.com/file/d/1ajtJTaEkFsGMe0bg8YnO5SAt9aGGtf7x/view?usp=share_link

### Expected behaviour

IDE should never die.

### Enso Version

develop 12.05 

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by sylwiabr** [comment]
@farmaazon @4e6 have a look here. IDE should never die - it was a short session, nothing controversial. During last days we encountered exactly this error 2-3 times and we had to restart IDE multiple time because it was unusable. Also we lost our work few times due to this and other problems (like problems with synchronization between IDE and engine).

**Comment by jdunkerley** [comment]
I think making the engine sluggish by running in trace mode will help reproduce.

Project: https://drive.google.com/file/d/11jOQvmkEhplUfPDlvGPnESkiV5EXnmoO/view?usp=share_link

**Comment by JaroslavTulach** [comment]
The video shows following log at 3:42:

![obrazek](https://github.com/enso-org/enso/assets/26887752/1851740e-8346-4b3b-9e61-e1155d513c5a)

At 22:06 the `HeartbeatSession] stopped`. At 22:15 the `HeartbeatSession] started` - what does that mean? Is the IDE trying to reconnect? Btw. at 22:21 the heartbeat stops again.

Is there any other explanation of the heartbeat stopping/starting than an attempt to reconnect? The IDE logs (shown at 4:02 of the video) do not contain any message about reconnecting, however.

**Comment by farmaazon** [comment]
The Heartbeat is an internal Engine thing, IDE do not use it.

**Comment by hubertp** [comment]
@JaroslavTulach Heartbeat session is a shortlived action that starts and dies regularly. sending/receiving the regular ping/pong. This is as expected.

**Comment by JaroslavTulach** [comment]
> sending/receiving the regular ping/pong. This is as expected

That means the connection between the IDE and engine is OK, right? Alas, if it is OK, then I have no other idea what can be wrong...

**Comment by sylwiabr** [comment]
@JaroslavTulach the issues we are observing recently like this one, https://github.com/enso-org/enso/issues/6727 or https://github.com/enso-org/enso/issues/6634 are not caused by IDE/LS loosing the connection. Probably this is why IDE is not reporting issues. They all have common part: evaluation of newly added nodes is not happening but the connection is there.

**Comment by JaroslavTulach** [comment]
We need to find out what is happening in the Enso engine/LS process - let's download [VisualVM](https://www.graalvm.org/22.3/tools/visualvm/) and then:
- open the `org.enso.runner.Main` process
- take a thread dump (Threads tab/Thread Dump button / copy and paste)
- sample what the application does (Sampler tab / CPU button / Snapshot / save into a file)
- take a heap dump (right click on the process node)

![obrazek](https://github.com/enso-org/enso/assets/26887752/4395db3a-0238-402c-a3c2-c5a98adb9918)

With such information we should have a better insight of what is happening in the engine/LS process:
- thread dump would show us if the engine is *blocked* somewhere
- profiling sample allows us to record few seconds and deduce what the **engine is doing** at that time
- heap dump allows us to **inspect internal** objects like actors, etc.

**Comment by JaroslavTulach** [comment]
Alas, we have just done both (thread dump and profiling) with James and the LS/engine process does **nothing**! The next step is to find out whether there are some messages sent to the process at all.

**Comment by hubertp** [comment]
Sounds vaguely similar to https://github.com/enso-org/enso/issues/6763

**Comment by JaroslavTulach** [comment]
I guess we should invest into an infrastructure that would allow us to capture/record the state of the engine easily:
- #6775

**Comment by jdunkerley** [comment]
Closing as we believe is related to #6763.
