### ISSUE TITLE
Text edit lag

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6675]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When editing existing nodes specially the lag in text edit is really big. It feels like we have a regression recently in this area.

### Expected behaviour

When I am typing I should not have to pause for a second between edits.

### Enso Version

nightly 12.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by Akirathan** [comment]
Probably related to https://github.com/enso-org/enso/issues/6637

**Comment by sylwiabr** [comment]
Actually we have been checking it with @wdanilo - the issue has two roots:
1. updating documentation and generating HTML after each letter
2. updating CB entries.
If you type something random (so it has no matches in the CB) there is no delay.

**Comment by farmaazon** [comment]
@sylwiabr Some performance fixed were merged. Is it still an issue for you?

**Comment by sylwiabr** [comment]
The lag is significantly smaller
