### ISSUE TITLE
Ctrl+click is placing cursor in a random place on a node

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6702]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When starting editing an existing node, `ctrl+click` is placing a cursor in a random place.

### Expected behaviour

Cursor should be placed exactly where user clicks.

### Enso Version

nightly 12.05.2023

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by wdanilo** [comment]
This is a regression. Was working for sure in the past.

**Comment by vitvakatu** [comment]
The widgets on nodes introduced it.

**Comment by wdanilo** [comment]
Thanks @vitvakatu! CC @Frizi

**Comment by Akirathan** [comment]
Observation: Once you are trying to edit the same node for the second time, with `Ctrl + click`, the cursor is put on the correct location.

**Comment by Frizi** [comment]
I can reproduce it when editing a node for a first time in given session. The second time it's edited, it works as expected.

The code that handles the cursor position on edit mode switch is as follows:
```rs
            self.edit_mode_label.set_content(expression.code.clone());
            self.display_object.remove_child(&self.widget_tree);
            self.display_object.add_child(&self.edit_mode_label);
            self.edit_mode_label.set_cursor_at_mouse_position();
```

My suspicion is that the `set_cursor_at_mouse_position` input of `Text` component doesn't work correctly directly after calling `set_content` with new content, or if it wasn't part of the widget hierarchy yet.
