### ISSUE TITLE
New shape instance render latency

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#6717]
### Discussed in https://github.com/orgs/enso-org/discussions/6716

<div type='discussions-op-text'>

<sup>Originally posted by **kazcw** May 16, 2023</sup>
When I create a new instance of a shape, I'm observing a 1-frame delay before it starts drawing. This is not caused by GPU buffer upload; other GPU parameter changes are visible without the delay. I suspect it is related to asynchronous processing of changes in the display object hierarchy. Is this expected behavior? It is causing a flicker in the new edge implementation when I need to change shaders in response to hover position changes (#6707), and working around it by delaying hiding the previous shader would add significant complexity.</div>

**Comment by kazcw** [comment]
The problem is that `ShapeView`'s `add_to_scene_layer` was not designed for `microtask` deferred events:
- Handlers for display objects' `batch`ed events, such as `on_layer_change`, are run at a time after display object `update` completes.
- If these handlers alter any display objects, the changes will not take effect until the next frame's display object `update` phase.
- `ShapeView`'s `on_layer_change` handler uses `ShapeInstance::swap`, which alters display objects.

**Comment by wdanilo** [comment]
Ok, good that we know the source of this problem! Do you see a way to fix it / do you want to have a design call about it? :)

**Comment by sylwiabr** [comment]
@wdanilo @kazcw what is the status here?

**Comment by kazcw** [comment]
Implemented in #6744, waiting for review
