### ISSUE TITLE
No exit logs in the console after Enso close

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6721]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When working on a cloud project when I close Enso it doesn't report usual logs in the console.

https://github.com/enso-org/enso/assets/108271897/786ed4a2-4297-4e94-86c7-f9cfefc7995d

### Expected behaviour

Termination logs visible in the console (everything closed propperly)

### Enso Version

2023.5.17 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by sylwiabr** [comment]
The termination logs you have when working locally are from the LS. LS logs when working remotely are  gathered in the DB and should not be pushed to this console.
