### ISSUE TITLE
Full screen visualization hindered by "Unsupported Engine version..." message

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6722]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The `Unsupported Engine version` or in fact any kind of notification that pops up (like connectivity issues) is blocking the view of the graph and of full screen visualization.
Maybe worse is that it can't be moved or mitigated in any way, sometimes hindering the view of data.

### Expected behaviour

Semi-transparent notification would be sufficient.

### How we can reproduce it?

Start a locally built engine. 

### Screenshots or screencasts

![Screenshot from 2023-05-17 11-45-43](https://github.com/enso-org/enso/assets/292128/7b1c4bba-d398-45a4-b542-928f15291b02)

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by farmaazon** [comment]
Currently, we hide Graph Editor component when visualization is going full-screen. Seemingly, we need to hide more things.

**Comment by farmaazon** [comment]
The new dashboard button is also displayed _over_ full-screen visualization (reported in #6839). Let's fix it in this task as well.
