### ISSUE TITLE
Project list (ctrl+o) doesn't display any projects when working with a cloud project

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6723]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Project list (ctrl+o) doesn't display any projects when working with a cloud project

https://github.com/enso-org/enso/assets/108271897/9187ef23-3b0f-4061-90ac-e1c2cdd6c7df

### Expected behaviour

Project list available for fast project switching or this feature disabled in the cloud environment.

### How we can reproduce it?

open project in the cloud
press ctrl+o

### Enso Version

2023.5.17 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

Version 112.0.5615.138 (Official Build) (64-bit)

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by sylwiabr** [comment]
We will not fix it - instead we will enable switching between IDE and dashboard as it was designed.
