### ISSUE TITLE
Node preview occasionally doesn't work - closes before showing results

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6724]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While working with a cloud project, when pressing spacebar on ``column_names`` node preview takes very long to load and eventually preview window disappears without showing the results.

https://github.com/enso-org/enso/assets/108271897/5e7ab07d-adc6-41e7-8c3e-b548da3942bb

### Expected behaviour

Preview is shown promptly and stays on until turned off by a user.

### Enso Version

2023.5.17 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by sylwiabr** [comment]
Please add the information if you are using the local installation or the cloud @xvcgreg

**Comment by Akirathan** [comment]
Related discussion: #6783. Related issue: #6766.

**Comment by farmaazon** [comment]
Hmm, I've suspected we close visualization due to receiving some error on visualization/attach... But in that case, the error log should be printed.

**Comment by farmaazon** [comment]
>  But in that case, the error log should be printed.

It may be caused by not-quite-working `showLogs` in the cloud.

**Comment by MichaelMauderer** [comment]
Due to https://github.com/enso-org/enso/issues/6899 I cannot debug this properly in the cloud environment.

 I can, however, reproduce the same behaviour locally for large enough data sets (200MB as a table vis). The observed behaviour in this scenario is caused by a timeout on the engine side: `[org.enso.languageserver.requesthandler.visualisation.AttachVisualisationHandler] Request [Number(279)] timed out.`

While we can (and should) increase the timeout, but this will only alleviate but not solve the problem. Ideally, the IDE should show the correct error message to the user, to inform them what is happening (i.e., the visualization is closed due to a timeout). 

So, I propose: 
* we increase the timeout. 
* we add a user-facing error message in the IDE when a visualization is closed due to a timeout. 

Do you agree with this as a solution to this issue, or are there any other suggestions, or comments? @farmaazon @xvcgreg @sylwiabr @wdanilo

**Comment by wdanilo** [comment]
I believe that the solution proposed by you, Michael, is correct. Unless someone else has a better idea / adjustments, let's do it.

**Comment by hubertp** [comment]
> I can, however, reproduce the same behaviour locally for large enough data sets (200MB as a table vis). The observed behaviour in this scenario is caused by a timeout on the engine side: `[org.enso.languageserver.requesthandler.visualisation.AttachVisualisationHandler] Request [Number(279)] timed out.`

Try network throttling on chrome with `Slow 3G` speed. This illustrates visualizations issues I've seen reported occasionally.

**Comment by farmaazon** [comment]
> So, I propose:
> 
> * we increase the timeout.
> * we add a user-facing error message in the IDE when a visualization is closed due to a timeout.

The second point brings a bit of logic (and design) here. I believe we could do it by
1. Implementing the notification board as designed in #5201
2. Make a special mode in displayed visualization which shows error instead of data.

For now, I think 2 is nicer, as we avoid "someone just hid my visualization!" effect: the box is still there, it just has an error message.

Anyway, let's do the point 1 as a separate fix now.

I have also a third idea:
3. Let the "attach vis" in IDE controllers retry the operation several times before giving up.

**Comment by MichaelMauderer** [comment]
I was just thinking of using the current mechanism for showing an error at the top of the IDE. I assume this is the mechanism that will get extended in #5201 ? 

> I have also a third idea:
> 3. Let the "attach vis" in IDE controllers retry the operation several times before giving up.


I don't think this will solve this problem. In this case, the computation of the visualization just takes too long on the engine side and is aborted there. Every additional attempt initiated from the IDE, in the same way, will most likely take just as long.

**Comment by farmaazon** [comment]
> I don't think this will solve this problem. In this case, the computation of the visualization just takes too long on the engine side and is aborted there. Every additional attempt initiated from the IDE, in the same way, will most likely take just as long.

Yes, however, there is one important detail here.

IDE should not hide visualization if it waits long for _data_. The data arrival is in a separate message and it does not have a timeout. But we hide visualization if the _attaching_ fails.

Now, there are two reasons it could fail:
1. There is some bug and it fails instantly. In this case, we can show error and do not retry.
2. There are connectivity issues (cloud): in this case retry should help
3. It times out, but not due to connectivity issues (local). In that case, I would consider it an engine bug. "Attach visualization" should not wait for data to return, and if the thread handling this message is starved due to other heavy computation, it's also bad.

**Comment by farmaazon** [comment]
> I was just thinking of using the current mechanism for showing an error at the top of the IDE. I assume this is the mechanism that will get extended in https://github.com/enso-org/enso/issues/5201 ?

Yes, I added a point there for various failures (including visualization attaching).

**Comment by MichaelMauderer** [comment]
> IDE should not hide visualization if it waits long for data. The data arrival is in a separate message and it does not have a timeout. But we hide visualization if the attaching fails.

I don't think it does. When playing around with throttled bandwidth speed, the visualizations stayed in the loading state until I got data or bored.

The observed error clearly originates on the engine side and is actively propagated.

**Comment by hubertp** [comment]
> The observed error clearly originates on the engine side and is actively propagated.

I'm starting to get lost in this thread so excuse me if the remark sounds banal but I believe engine has no timeout when it comes computing the visualization data. It might take a while but it should not timeout. Do you have an example where it shows that it aborted the computation?

> "Attach visualization" should not wait for data to return, and if the thread handling this message is starved due to other heavy computation, it's also bad.

Response for Attach visualization request should be near instant, agreed. If it is too long and because of engine, that's a bug.
The data of the visualization can arrive any time after the request is confirmed.

**Comment by farmaazon** [comment]
> It might take a while but it should not timeout. Do you have an example where it shows that it aborted the computation?

Please look at an engine's log line posted in https://github.com/enso-org/enso/issues/6724#issuecomment-1570239589

Here we see there is some timeout inside the engine (as this is an engine log), and it's related to attaching process (so perhaps it's not timeout for waiting for _data_, only for _attaching result_).

@MichaelMauderer do you have a full engine log for that case?

**Comment by hubertp** [comment]
@farmaazon Thanks. The problem with those warnings is that they may be spurious and caused by successive file editions https://github.com/enso-org/enso/issues/5985 is one example.
I'm pretty sure it is this problem as there isn't much that can go wrong when attaching visualizations. Full log would help, obviously.

**Comment by MichaelMauderer** [comment]
@hubertp Let me know if there is anything else I can provide. 

<details><summary>Full Console output</summary>
<p>

``` INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:24:30.739Z] [org.enso.projectmanager.boot.ProjectManager$] Starting Project Manager...
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:24:30.76Z] [org.enso.projectmanager.boot.ProjectManager$] Started server at 127.0.0.1:30535, press enter to kill server
 INFO ide_ci::program::command: npm⚠️ libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:24:31.625Z] [org.enso.projectmanager.protocol.ClientController] Client connected to Project Manager [1b4a9044-885e-4e0f-b5ce-8a06dec648e5]
 INFO ide_ci::program::command: npm⚠️ [warn] [2023-06-02T11:24:31.819Z] [org.enso.projectmanager.service.ProjectService] Could not resolve engine version for Edition(Some(2023.1.1-nightly.2023.4.17),None,Map(),Map()). Falling back to Edition(Some(2023.2.1-nightly.2023.6.2),None,Map(),Map())
 INFO ide_ci::program::command: npmℹ️ Build ended: 8538ms
 INFO ide_ci::program::command: npmℹ️ Content bundle updated.
 INFO ide_ci::program::command: npmℹ️ Resource '/favicon.ico' not found.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:24:42.055Z] [org.enso.projectmanager.protocol.ClientController] Client connected to Project Manager [9e773b92-96c7-4f39-b68f-8d16d57e22bb]
 INFO ide_ci::program::command: npm⚠️ [warn] [2023-06-02T11:24:42.11Z] [org.enso.projectmanager.service.ProjectService] Could not resolve engine version for Edition(Some(2023.1.1-nightly.2023.4.17),None,Map(),Map()). Falling back to Edition(Some(2023.2.1-nightly.2023.6.2),None,Map(),Map())
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:24:45.417Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine [2023.1.1] not found.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:24:45.417Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Installing the engine [2023.1.1].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:26.327Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Found GraalVM runtime [GraalVM 22.3.1-java11].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:26.328Z] [org.enso.projectmanager.service.versionmanagement.ControllerInterface] Installed Enso Engine 2023.1.1.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:26.405Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Found GraalVM runtime [GraalVM 22.3.1-java11].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:26.406Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Booting a language server [LanguageServerDescriptor(language-server-44825d6a-4af7-4a54-9d42-cbc65190ccc7,f7f80edf-644d-4b4d-b90d-0e80ea802d72,/home/michael/enso/projects/Colorado_COVID_1,NetworkConfig(127.0.0.1,49152,65535),org.enso.projectmanager.versionmanagement.DefaultDistributionConfiguration$@7f537db0,2023.1.1,JVMSettings(None,List()),false,None,None,None,Future(Success(Some(ws://localhost:34277/))),false)].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:26.406Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Found sockets for the language server [json:127.0.0.1:57761, binary:127.0.0.1:64405].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:26.407Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine [2023.1.1] found.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:26.43Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Found GraalVM runtime [GraalVM 22.3.1-java11].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:27.391Z] [org.enso.languageserver.boot.LanguageServerComponent] Starting Language Server...
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:27.401Z] [org.enso.languageserver.boot.MainModule] Initializing main module of the Language Server from [2023.1.1, LanguageServerConfig(127.0.0.1,57761,64405,f7f80edf-644d-4b4d-b90d-0e80ea802d72,/home/michael/enso/projects/Colorado_COVID_1,ProfilingConfig(None,None,None),StartupConfig(false),language-server,scala.concurrent.impl.ExecutionContextImpl$$anon$3@1afdd473[Running, parallelism = 32, size = 2, active = 1, running = 1, steals = 0, tasks = 0, submissions = 0]), info]
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:28.14Z] [org.enso.languageserver.runtime.RuntimeConnector] Starting the runtime connector.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:28.14Z] [org.enso.languageserver.runtime.RuntimeConnector] Runtime connector established connection with the message endpoint [com.oracle.truffle.api.instrumentation.TruffleInstrument$Env$MessageTransportProxy$MessageEndpointProxy@f6caa63].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:28.315Z] [org.enso.languageserver.search.SuggestionsHandler] Starting suggestions handler from [Config(projectContentRoot=ContentRootWithFile(contentRoot=Project(f7f80edf-644d-4b4d-b90d-0e80ea802d72),file=***/Colorado_COVID_1), fileManager=FileManagerConfig(3 seconds,32), vcsManager=VcsManagerConfig(5 seconds,3 seconds,true), pathWatcher=PathWatcherConfig(5 seconds,5 seconds,10), executionContext=ExecutionContextConfig(5 seconds), directories=DirectoriesConfig(***/Colorado_COVID_1)), org.enso.searcher.sql.SqlSuggestionsRepo@607ef1cd].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:28.395Z] [org.enso.languageserver.boot.MainModule] Main module of the Language Server initialized with config [Config(projectContentRoot=ContentRootWithFile(contentRoot=Project(f7f80edf-644d-4b4d-b90d-0e80ea802d72),file=***/Colorado_COVID_1), fileManager=FileManagerConfig(3 seconds,32), vcsManager=VcsManagerConfig(5 seconds,3 seconds,true), pathWatcher=PathWatcherConfig(5 seconds,5 seconds,10), executionContext=ExecutionContextConfig(5 seconds), directories=DirectoriesConfig(***/Colorado_COVID_1))].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:28.476Z] [org.enso.languageserver.boot.LanguageServerComponent] Started server at json:127.0.0.1:57761, binary:127.0.0.1:64405
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:29.181Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Language server booted [LanguageServerConnectionInfo(127.0.0.1,57761,64405)].
 INFO ide_ci::program::command: npm⚠️ [warn] [2023-06-02T11:25:29.219Z] [org.enso.projectmanager.service.ProjectService] Could not resolve engine version for Edition(Some(2023.1.1-nightly.2023.4.17),None,Map(),Map()). Falling back to Edition(Some(2023.2.1-nightly.2023.6.2),None,Map(),Map())
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:25:36.464Z] [akka.actor.LocalActorRef] Message [akka.actor.ReceiveTimeout$] to Actor[akka://project-manager/system/IO-TCP/selectors/$a/3#-1887581406] was not delivered. [1] dead letters encountered, no more dead letters will be logged in next [5.000 min]. If this is not an expected behavior then Actor[akka://project-manager/system/IO-TCP/selectors/$a/3#-1887581406] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:15.198Z] [org.enso.projectmanager.protocol.ClientController] Client connected to Project Manager [6ef42b11-a9cf-48e4-ad9f-23661442e764]
 INFO ide_ci::program::command: npm⚠️ [warn] [2023-06-02T11:26:15.669Z] [org.enso.projectmanager.service.ProjectService] Could not resolve engine version for Edition(Some(2023.1.1-nightly.2023.4.17),None,Map(),Map()). Falling back to Edition(Some(2023.2.1-nightly.2023.6.2),None,Map(),Map())
 INFO ide_ci::program::command: npm⚠️ [warn] [2023-06-02T11:26:15.671Z] [org.enso.projectmanager.service.ProjectService] Could not resolve engine version for Edition(Some(2023.1.1-nightly.2023.4.17),None,Map(),Map()). Falling back to Edition(Some(2023.2.1-nightly.2023.6.2),None,Map(),Map())
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:15.836Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine [2023.1.1] found.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:15.854Z] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Found GraalVM runtime [GraalVM 22.3.1-java11].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:15.985Z] [org.enso.languageserver.protocol.json.JsonConnectionController] Initializing resources.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:15.988Z] [org.enso.languageserver.boot.resource.DirectoriesInitialization] Initializing directories...
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:15.989Z] [org.enso.languageserver.boot.resource.DirectoriesInitialization] Initialized directories.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:15.996Z] [org.enso.languageserver.boot.resource.JsonRpcInitializationComponent] Initializing JSON-RPC protocol.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:15.996Z] [org.enso.languageserver.boot.resource.JsonRpcInitializationComponent] JSON-RPC protocol initialized.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:15.997Z] [org.enso.languageserver.boot.resource.ZioRuntimeInitialization] Initializing ZIO runtime...
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:16.289Z] [org.enso.languageserver.boot.resource.ZioRuntimeInitialization] ZIO runtime initialized [org.enso.languageserver.effect.ExecutionContextRuntime@da4ebbe].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:16.29Z] [org.enso.languageserver.boot.resource.RepoInitialization] Initializing sql database [org.enso.searcher.sql.SqlDatabase@1554698e]...
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:16.393Z] [org.enso.languageserver.boot.resource.RepoInitialization] Initialized sql database [org.enso.searcher.sql.SqlDatabase@1554698e].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:16.394Z] [org.enso.languageserver.boot.resource.TruffleContextInitialization] Initializing Runtime context...
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:18.32Z] [org.enso.languageserver.boot.resource.TruffleContextInitialization] Initialized Runtime context.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:18.321Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: Truffle context initialized.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:18.321Z] [org.enso.languageserver.boot.resource.RepoInitialization] Initializing suggestions repo [***/suggestions.db]...
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:18.41Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: project name is updated to [Colorado_COVID_1].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:18.629Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: got type graph response.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:18.723Z] [org.enso.languageserver.boot.resource.RepoInitialization] Initialized Suggestions repo [***/suggestions.db].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:18.724Z] [org.enso.languageserver.search.SuggestionsHandler] Initializing: suggestions repo initialized.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:18.724Z] [org.enso.languageserver.protocol.json.JsonConnectionController] RPC session initialized for client [19d3f238-e7f3-4207-ac8b-a6eecdd0753a].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:18.756Z] [org.enso.languageserver.protocol.binary.BinaryConnectionController] Data session initialized for client: 19d3f238-e7f3-4207-ac8b-a6eecdd0753a [127.0.0.1:36340].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:19.057Z] [org.enso.languageserver.text.CollaborativeBuffer] Buffer opened for [path:Path(f7f80edf-644d-4b4d-b90d-0e80ea802d72,Vector(src, Main.enso)), client:19d3f238-e7f3-4207-ac8b-a6eecdd0753a].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:19.579Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Base @ 2023.1.1 at [***/2023.1.1].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:19.661Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Table @ 2023.1.1 at [***/2023.1.1].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:19.688Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Database @ 2023.1.1 at [***/2023.1.1].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:19.708Z] [enso.org.enso.compiler.PackageRepository$Default] Found library Standard.Visualization @ 2023.1.1 at [***/2023.1.1].
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:26:55.35Z] [enso] Background jobs started.
 INFO ide_ci::program::command: npm⚠️ [error] [2023-06-02T11:27:00.412Z] [org.enso.languageserver.requesthandler.visualisation.AttachVisualisationHandler] Request [Number(19)] timed out.
 INFO ide_ci::program::command: npm⚠️ [error] [2023-06-02T11:27:01.482Z] [org.enso.languageserver.requesthandler.visualisation.AttachVisualisationHandler] Request [Number(23)] timed out.
 INFO ide_ci::program::command: npm⚠️ [error] [2023-06-02T11:27:01.482Z] [org.enso.languageserver.requesthandler.visualisation.AttachVisualisationHandler] Request [Number(25)] timed out.
 INFO ide_ci::program::command: npm⚠️ [error] [2023-06-02T11:27:01.482Z] [org.enso.languageserver.requesthandler.visualisation.AttachVisualisationHandler] Request [Number(24)] timed out.
 INFO ide_ci::program::command: npm⚠️ [info] [2023-06-02T11:27:05.427Z] [akka.actor.LocalActorRef] Message [org.enso.languageserver.requesthandler.RequestTimeout$] from Actor[akka://language-server/user/json-connection-controller-37d7ea14-b8d1-4cd0-8d08-a3a40574e427/request-handler-AttachVisualisation-5dfb6517-d842-44f8-be7e-31fa6357c79a#1223408393] to Actor[akka://language-server/user/json-connection-controller-37d7ea14-b8d1-4cd0-8d08-a3a40574e427/request-handler-AttachVisualisation-5dfb6517-d842-44f8-be7e-31fa6357c79a#1223408393] was not delivered. [1] dead letters encountered, no more dead letters will be logged in next [5.000 min]. If this is not an expected behavior then Actor[akka://language-server/user/json-connection-controller-37d7ea14-b8d1-4cd0-8d08-a3a40574e427/request-handler-AttachVisualisation-5dfb6517-d842-44f8-be7e-31fa6357c79a#1223408393] may have terminated unexpectedly. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
`
</p>
</details>

**Comment by MichaelMauderer** [comment]
@hubertp Could you point me to the correct timeout that needs to be adjusted for this? I was unable to identify the right place for certain. I think this might be it, but it looks like this might affect much more code than intended: https://github.com/enso-org/enso/blob/cfb2f2916eb1d81f521c5af238e42c2b227f65d3/engine/language-server/src/main/scala/org/enso/languageserver/boot/TimingsConfig.scala#L42

**Comment by hubertp** [comment]
> @hubertp Could you point me to the correct timeout that needs to be adjusted for this? I was unable to identify the right place for certain. I think this might be it, but it looks like this might affect much more code than intended:
> 
> https://github.com/enso-org/enso/blob/cfb2f2916eb1d81f521c5af238e42c2b227f65d3/engine/language-server/src/main/scala/org/enso/languageserver/boot/TimingsConfig.scala#L42

Yes, that's the default.

**Comment by hubertp** [comment]
@farmaazon @MichaelMauderer Should this ticket still be open? I've added some significant improvements on the LS side which should have remedied the problem.

**Comment by MichaelMauderer** [comment]
This should be already closed. #6937 was the solution on the IDE  and #7005 is the follow-up issue on the engine side.
