### ISSUE TITLE
The loading dots on the visualization stayed visible on the full screen grid view

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6732]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

On freshly reopened project the full screen vis was opened. The loading dots stand visible together with the data.

https://github.com/enso-org/enso/assets/12892578/743da53c-d235-473e-961c-65aa85afd4f1

### Expected behaviour

User should see either the dots or the data 

### Enso Version

develop 17.05

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by jdunkerley** [comment]
Seems to be resolved - will close and reopen if occurs again.
