### ISSUE TITLE
CB inserts `Column.from_vector` during a simple node edit

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6734]
### What type of issue is this?

Permanent.

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

During a simple edit of a node having an `Integer` value, CB appears to insert `Column.from_vector` leading to visualization preview failures.

In the example project, CB inserts `Column.from_vector` which leads to roughly this error
```
Panic(no applicable overload found (overloads: [Method[public static native void java.lang.Thread.sleep(long) throws java.lang.InterruptedException], Method[public static void java.lang.Thread.sleep(long,int) throws java.lang.InterruptedException]], arguments: [Column.type.from_vector[Column.enso:47-1895] (Function)])
``` 

### Expected behaviour

CB should not force this `Column.from_vector` selection during visualization preview as it may and will confuse users.

### How we can reproduce it?

Attached a simple project. Try to edit the top `800` value and wait for the errors to appear.
[Timed.zip](https://github.com/enso-org/enso/files/11498472/Timed.zip)

### Screenshots or screencasts

The fun starts at 0:30:
[Kazam_screencast_00005.webm](https://github.com/enso-org/enso/assets/292128/e15ba89c-4fdf-4587-a365-46b699941676)

Logs from the engine:
[20230517-125502-825-enso-project-manager.log](https://github.com/enso-org/enso/files/11498519/20230517-125502-825-enso-project-manager.log)

### Enso Version

7bf9d3614ce9262af00185485af0553846abf0c5

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by farmaazon** [comment]
Closing in favor of https://github.com/enso-org/enso/issues/6486 as it's the same thing and has longer discussion
