### ISSUE TITLE
Item list in the node is rendered wrong - no dropdowns to select item name

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6735]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

What I have while constructing list:
![image](https://github.com/enso-org/enso/assets/108271897/23e339f4-d026-4c07-a07b-b0d513155706)

there are no dropdowns to chose from. 

The one before the list is:
![image](https://github.com/enso-org/enso/assets/108271897/a1e650a7-1b27-48fb-b355-092a710a0667)

### Expected behaviour

What I'd like to have:
![image](https://github.com/enso-org/enso/assets/108271897/1056c051-23f7-4d08-b323-6eba0298aeea)

### Enso Version

2023.5.17 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by xvcgreg** [comment]
2023.5.18 Nightly - same bug with 1st dropdown:
![image](https://github.com/enso-org/enso/assets/108271897/47b62349-4ec5-4cb4-9c6d-d652ab1369c9)

It should show the column names. When I select ``by name`` it gives me this error:
![image](https://github.com/enso-org/enso/assets/108271897/a518c133-d4df-4341-b24d-d49c1b58f8d6)

**Comment by xvcgreg** [comment]
Workaround:

https://github.com/enso-org/enso/assets/108271897/6a3919db-82ee-4d82-8979-c2ca26010668

**Comment by Akirathan** [comment]
This seems the same as what happened to me on latest develop today - #6785. It seems like an issue with the vector editor. cc @Frizi

**Comment by jdunkerley** [comment]
Being fixed by #6768
