### ISSUE TITLE
Confusing preview output of vector method

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6736]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While learning Enso I get confused by the preview of method I'm exploring being what I'd expect as a result of the method to later find out that it's not working.

https://github.com/enso-org/enso/assets/108271897/60506f6b-2b71-4a85-b722-c36cac416d02

I wanted to create vector from a table / colum and got a decent result in a preview...

### Expected behaviour

If the method isn't correct I'd like to be informed about it with possible solution suggested.

### Enso Version

2023.5.17 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by Akirathan** [comment]
This seems like a problem with how the GUI search suggestion database regarding the actual cursor position?

**Comment by xvcgreg** [comment]
I have not moved the cursor - look at the video. After typing fully ``vector`` CB was empty on suggestions.

**Comment by farmaazon** [comment]
What I see here is:
1. In most cases, just no suggestion is displayed, and in that case we stick to the old preview. This should be fixed: we should display preview of the current input instead.
2. Once you have a text cursor in the middle of the word. In that case we may select something different (as we take only left part as a pattern). Perhaps this should be changed, as indeed this may be confusing.
