### ISSUE TITLE
``to_text`` outputs square brackets surrounding the expected value

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6737]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When using ``to_text`` method on a vector I'm getting ``["value"]`` - when expecting just ``"value"``.
Even when I'd have multi item vector I'd still expect ``"value1, value2, ..., valuen"`` without square brackets.

![image](https://github.com/enso-org/enso/assets/108271897/b8442f73-910b-4d1c-8a85-8330c4625c0c)

### Expected behaviour

just as ``.at`` works

### Enso Version

2023.5.17 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by jdunkerley** [comment]
`.take 1` is producing a new Vector with a single element. That is what the `to_text` is rendering that it is a single element vector with a value.

To get the first element as a single value, you can either use `first`, `at 0` or `get 0` on the Vector.

**Comment by xvcgreg** [comment]
Thank you @jdunkerley - it was surprising.
