### ISSUE TITLE
Date vs Date_Time not intuitive

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6738]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When dealing with this format: ``dd/MM/yyyy hh:mm:ss`` I'd expect to use ``Date_Time`` value type
![image](https://github.com/enso-org/enso/assets/108271897/f5b8ffff-d256-4c14-a062-b13139215b72)
but it's wrong.

Instead when I want to use ``dd/MM/yyyy hh:mm:ss`` I have to use ``Date`` value type:
![image](https://github.com/enso-org/enso/assets/108271897/6e744c13-9104-4040-9a93-7b571752cea8)

where I'd expect ``dd/MM/yyyy`` from that value type.

### Expected behaviour

as described above

``date_time`` value type = date and time
``date`` value type = date

### Enso Version

2023.5.17 nightly

### Browser or standalone distribution

Standalone distribution

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by jdunkerley** [comment]
To parse as a datetime we are requiring the format to have Hours and Minutes. The ` 00:00:00` tells it to ignore it.
If you used `yyyy-MM-dd HH:mm:ss` as the format for a Date_Time this should have worked.

**Comment by xvcgreg** [comment]
@jdunkerley that information is not presented to the user in the documentation panel - it could help users to understand it better.

**Comment by jdunkerley** [comment]
No question we need to improve the docs and format specifiers (the Java set up is too complex).
