### ISSUE TITLE
New node is spawned above an existing one

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6742]
A new node is created outside existing ones, but if the method in the node is long, it will be shown above other nodes, effectively hiding them.

[new_node_spawned_above_existing.webm](https://github.com/enso-org/enso/assets/14013887/61fdec80-654e-41c0-afe9-adaeb44201c2)

**Comment by wdanilo** [comment]
The fact that we are crating new nodes on the left side of existing ones is a bad design. If the node was placed on the right side, then during editing, when its size changes, it will not overlap other nodes. So we should create nodes on the right side, rather than on the left.

**Comment by Akirathan** [comment]
Should this be a bug or a feature request?

**Comment by wdanilo** [comment]
I think its a bug

**Comment by farmaazon** [comment]
In GUI2 we create nodes on the right.
