### ISSUE TITLE
Pressing `Backspace` when full screen vis is open is deleting the node 

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6757]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

AS described in the title, pressing backspace when full vis is open is deleting the node and the screen is getting blank. Moreover, it is impossible to undo those operations.

### Expected behaviour

1. The undo stack should allow user to get back to previous state.
2. Node should not be deleted. 

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/12892578/35766712-901a-4b2a-9c7c-f357eb02838f

### Enso Version

nightly 18.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
The UR path should be covered by #6635 

The rest is merged to https://github.com/enso-org/enso/issues/6754
