### ISSUE TITLE
First drag over the input port is not working

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6759]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [x] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/a2ec1347-f03f-4710-97fa-3fd3876d3e65

### Expected behaviour

Connection should be made with first attempt

### How we can reproduce it?

This is reproducible for `filter` node and does't dependent on the OS

### Enso Version

nightly 18.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by Akirathan** [comment]
Seems easy to reproduce on anew project.

**Comment by farmaazon** [comment]
@kazcw I see you've taken this task.

We believe it might be related to other problems with ports, described in comments of #6850, so I propose doing this task after that one.

**Comment by farmaazon** [comment]
@sylwiabr Do you still reproduce this task, after all recent changes?

**Comment by sylwiabr** [comment]
Can't repro on newest develop
