### ISSUE TITLE
Full screen visualisation doesn't work on double pressed spacebar

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6761]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When pressing space bar twice fast visualisation doesn't enter full screen mode:

https://github.com/enso-org/enso/assets/108271897/b7edebb7-b55e-47a1-a748-58e8f7a1d5f1

### Expected behaviour

full screen visualisation working on double pressed space bar key

### Enso Version

2023.5.18 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by sylwiabr** [comment]
Shortcut was changed to `shift+space` as requested here: https://github.com/enso-org/enso/issues/6260
