### ISSUE TITLE
Need an indicator for adding the first item to a List Editor

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6764]
https://github.com/enso-org/enso/assets/4699705/6fcd7106-e1e4-41bb-99e2-3636248844cf

There is no obvious way to add the first item in the new Vector editor unless you know where to go.
An always-shown icon would be useful to give the user a hint.

**Comment by farmaazon** [comment]
The new design expects having such indicator. 

@Frizi will it be fixed as part of #6552? Or maybe you want to keep this issue as a remainder?
