### ISSUE TITLE
Warnings getting lost when returning a result of a call in tail position

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6765]
Consider the following program:

```
from Standard.Base import all

do_select x =
    Warning.attach "WARN" [x+1, 2, 3]

do_fold_1 x =
    v = do_select x
    v.fold 0 (+)

do_fold_2 x =
    v = do_select x
    res = v.fold 0 (+)
    res

main =
    r1 = do_fold_1 100
    IO.println r1
    IO.println (Warning.get_all r1 . map .value)

    r2 = do_fold_2 100
    IO.println r2
    IO.println (Warning.get_all r2 . map .value)
```

### Expected Result

```
106
[WARN]
106
[WARN]
```

### Actual Result

```
106
[]
106
[WARN]
```

The methods `do_fold_1` and `do_fold_2` are basically the same. They do the same logic, just one of them uses a temporary variable. They should behave exactly the same. Yet, `do_fold_1` is losing warnings.

**Comment by hubertp** [comment]
It appears that `TailCallException` ruins propagation of warnings :facepalm:

**Comment by radeusgd** [comment]
I'm adding some workarounds for this bug as part of #6731.

They are all marked with a comment containing the issue name `#6765`. Please ensure that when this bug is fixed, the (then hopefully obsolete) workarounds are removed.
