### ISSUE TITLE
Some visualisations do not load on project start

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6766]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Some of the visualisations that were left visible on project close do not show and are stuck on loading animation. Not all of them have this problem and it seems random. Also it doesn't depend on visualisation type (had missing visualizations for JSON, Map, Table)

![image](https://github.com/enso-org/enso/assets/108271897/6673f41b-393c-4e6b-8900-cf3633ab1af7)

Turning the visualisation off and on loads it w/o a problem.

### Expected behaviour

Visualisations left visible on project exit remain visible on project open (or at least load promptly).

### Enso Version

2023.5.18 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by hubertp** [comment]
When this happens, can we have the logs/project please?

**Comment by hubertp** [comment]
Never mind, just got it on my pet project. Will try to find the faulty party but, due to lack of errors on the engine-side, I believe it could be IDE not making the necessary request.

**Comment by Akirathan** [comment]
Related discussion: https://github.com/orgs/enso-org/discussions/6783

<blockquote><img src="https://opengraph.githubassets.com/43243f337aeb58108947672b4eb7d40054bbb99f98dbff1cb6f8b5c19133940b/orgs/enso-org/discussions/6783" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/orgs/enso-org/discussions/6783">When does visualization decide to display things and when does it give up? · enso-org · Discussion #6783</a></strong></div><div>As part of the investigation into #6766, I started to notice something weird with visualizations on startup. Assume a simple project with a few nodes like: If I start the project again but with som...</div></blockquote>

**Comment by MichaelMauderer** [comment]
After some tricky investigation (as this occurs quite randomly and nothing obvious goes wrong at first glance)  I found the issue: sometimes the visualization gets the data before the node receives type information. This is due to event processing on the IDE side. In that case, currently, the visualization is reset, and no new data ever arrives, as the visualization was attached, and data was sent. This should be fixed with #6831, which improves the handling of events arriving in different orders.

**Comment by xvcgreg** [comment]
fixed, closing
