### ISSUE TITLE
Renaming the project twice (or more) in the same project session leads to inconsistencies

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6767]
### What type of issue is this?

Permanent.

### Is this issue blocking you from using Enso?

- [x] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The order in which directory move happens on LS shutdown is unpredictable.
I had a project, say `X`, renamed to `New_Project_1` and then changed my mind and renamed it to `New_Project_2`.

Ended up with a project being in directory `New_Project_1` but the name of the project in `package.yaml` being `New_Project_2`.

Logs confirm out of order renaming of directories:
```
[info] [org.enso.projectmanager.infrastructure.languageserver.ShutdownHookRunner] Firing shutdown hooks for project [21260df1-f569-43d3-b2b2-d70944d8db8b].
[debug] org.enso.projectmanager.infrastructure.log.Slf4jLogging] Moving project [21260df1-f569-43d3-b2b2-d70944d8db8b] to [New_Project_2].
[info] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Project [21260df1-f569-43d3-b2b2-d70944d8db8b] moved to [<...>/enso/projects/New_Project_2].
[debug]  [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Moving project [21260df1-f569-43d3-b2b2-d70944d8db8b] to [New_Project_1].
[info] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Project [21260df1-f569-43d3-b2b2-d70944d8db8b] moved to [<...>/enso/projects/New_Project_1].
```

### Expected behaviour

Should rename the project to the directory based on the last change, not the first one.

### Enso Version

2bc7d346a8add19e422788db7792ee3c8de3f7fe

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by hubertp** [comment]
As discussed:
Renaming action should remove previous renaming shutdown hooks.

**Comment by wdanilo** [comment]
Question – we have SO MANY problems with directory renaming when renaming the projects. Do we really want to rename the directories when renaming projects? For example, for me it is so counter-intuitive, that directories change name when I'm closing Enso. This is super confusing and it was confusing to many people so far. What if we keep the project names only in yaml files and we don't touch folder names? What do you think about it?

CC @sylwiabr @jdunkerley

**Comment by wdanilo** [comment]
@sylwiabr @jdunkerley ping on my question above

**Comment by sylwiabr** [comment]
@wdanilo I think we should rename directories - people are looking into directories and searching through them and having 20 folders with names like New_Project_* when you know you named the projects would be very confusing.

**Comment by sylwiabr** [comment]
I was thinking about what is the best solution to our problems with renaming projects and since we have the new dashboard where we are able to rename and manage projects we should disable renaming project while it's opened and allow users just to rename through the dashboard. This will solve the issue with users being confused that folders are renamed when they are closing enso not while there are renaming the project.

**Comment by wdanilo** [comment]
We've been chatting with Sylwia about it and the above proposal of Sylwia is the best solution. It will work on all platforms and will not be confusing to users.

**Comment by hubertp** [comment]
I proceeded with fixing the issue a while ago, once this was approved on the backlog sync last week.
While it fixes the renaming problem, it also fixes any duplicate shutdown hook that we could have in the future. That is why I think this was still useful to fix, despite the decision mentioned above @wdanilo @sylwiabr.
