### ISSUE TITLE
IDE does not signal progress update from "Downloading new runtime"

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6769]
I tried running `project-manager` with an upgraded GraalVM version, and so, I got tons of these messages in project-manager's log: (Downloading GraalVM runtime with progress parameter)
![image](https://github.com/enso-org/enso/assets/14013887/a391834c-6ae9-4b0a-8e24-7f3fe71519a4)

But the IDE does not signal anything to me - it is just blank. I would expect a message similar to "Compiling standard library, this could take a while ... "

**Comment by farmaazon** [comment]
Duplicate of #6402 

@Akirathan or @sylwiabr feel free to bump priority of that task (and/or put it in the milestone) if you think it's important.
