### ISSUE TITLE
Malfunctioning edge after detaching source end

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#6772]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Under some (common) conditions, an edge that has been detached from its source node cannot be attached to anything, and is stuck in a broken state.

### Expected behaviour

After detaching an edge from a source, it should be possible to attach the source end to an output port.

### How we can reproduce it?

1. Choose an edge that would cause errors in the graph if detached, e.g. a node a method is invoked on.
2. Click on the edge near the target side, to disconnect it from its source.
3. Wait for the graph to show errors.
4. (Once the errors show, you can see the edge slightly disconnect from the target node; this indicates the broken state has been reached.)
5. Click on some output port to attempt to reattach the edge: Nothing happens.

### Screenshots or screencasts

[vokoscreenNG-2023-05-18_16-19-54.webm](https://github.com/enso-org/enso/assets/1047859/395c94e6-c6d5-46ce-8a3f-4e8f25e86f95)

### Enso Version

develop (a32a2eafba)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by kazcw** [comment]
I encountered this while debugging #6707. It is not a problem with the edge view; I think after reevaluation, the port the edge is supposed to be attached to no longer exists. However, in #6707 I'll improve how the graph editor displays this case: If an edge is found to be invalid, it would be less confusing for it to disappear than to stick around in a zombie state.

Also, I think this is not a (recent) regression. I remember encountering it during a Book Clubs some time ago, but didn't find how to reproduce it at the time.

**Comment by kazcw** [comment]
It is repeatable most of the time but occasionally works as expected.

**Comment by Akirathan** [comment]
I can't reproduce this in a simple case. Would you attach the project where you have spotted this, I could also try it there on the same node as you.

**Comment by kazcw** [comment]
> I can't reproduce this in a simple case. Would you attach the project where you have spotted this, I could also try it there on the same node as you.

It happens for me in a fresh Orders.

**Comment by kazcw** [comment]
I'll take this, as I've already done some debugging

**Comment by farmaazon** [comment]
During a call, we came up with a solution: the edges should be represented by AST IDs (+ additional info if they are half-detached connections to some placeholders), not by span-tree crumbs. In the long term, we remove span tree altogether - see #6834
