### ISSUE TITLE
Suggestions in the Component Browser are missing

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6781]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Most of the suggestions seems to went away. I have a vector and I want to make a column out of it:

https://github.com/enso-org/enso/assets/108271897/5036429f-5cfa-4fe4-9db7-2f7bbdbdc337

### Expected behaviour

Suggestions working

### Enso Version

2023.5.19 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by farmaazon** [comment]
Does Stdlib actually have `column` method of Vector? I thought only `Column::from_vector` is there.

**Comment by xvcgreg** [comment]
It's possible to create Column.from_vector so for seamless work (not deselecting a node) it would be good to have.

**Comment by Akirathan** [comment]
`Vector` does not, indeed, have `to_column` method. Assigning this ticket to @jdunkerley as a feature request.

**Comment by jdunkerley** [comment]
`Vector` now has `to_column` and `set` can take `Range`,`Date_Range` or `Vector`.
