### ISSUE TITLE
Confusing error message

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6782]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Confusing error message - completely unrelated to the node I'm creating - also there were no if/then/else expression used before to carry it down the node stream:

![image](https://github.com/enso-org/enso/assets/108271897/d9a64c23-e17e-42aa-b78b-bfd828945ccb)

### Expected behaviour

I'd expect error to explain why my node is not working.

### Enso Version

2023.5.18 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by Akirathan** [comment]
Will be fixed with #5142
