### ISSUE TITLE
Argument to `Table.transpose` disappears from the node once chosen from the dropdown

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6785]
Once I chose an argument for `Table.transpose` from the dropdown widget, the argument disappeared from the node. I have to ctrl+click to see it again.

[transpose-arg-dissapear.webm](https://github.com/enso-org/enso/assets/14013887/7099a3a3-456b-461d-ac05-9f1497ef12ec)
[20230519-161155-414-enso-project-manager.log.zip](https://github.com/enso-org/enso/files/11518678/20230519-161155-414-enso-project-manager.log.zip)

**Comment by jdunkerley** [comment]
The dropdown for this will be changed by my PR #6768.
The bug with the Vector editor making it disappear is being fixed by @Frizi.

**Comment by farmaazon** [comment]
@Frizi Check if I linked the proper PR which the fix.
