### ISSUE TITLE
Fallback to opened date when ordering projects

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#6787]
This makes newly created projects appear first in the project list, instead of below all other projects.
This is required to fix [cloud-v2/#432](https://github.com/enso-org/cloud-v2/issues/432)

https://github.com/enso-org/enso/blob/9ec7415ded9a96b01ec8c9300ac018084b87e53e/lib/scala/project-manager/src/main/scala/org/enso/projectmanager/service/RecentlyUsedProjectsOrdering.scala#L19-L25

should be changed to:

```scala
  override def compare(x: Project, y: Project): Int = {
    val xOpenedOrCreated = x.lastOpened.getOrElse(x.created)
    val yOpenedOrCreated = y.lastOpened.getOrElse(y.created)
    compareDates(xOpenedOrCreated, xOpenedOrCreated)
  }
```

**Comment by JaroslavTulach** [comment]
Wouldn't this better be reported as a PR? If all checks passed, it'd be a matter of pressing the green button.

**Comment by somebody1234** [comment]
maybe, not familiar with scala development so not sure whether it might need new tests
