### ISSUE TITLE
Selecting the edge replaces the node operator with `_` after cancellation

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6788]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Clicking the edge replaces the connected node with `_`. Attempts to go back to the previous state with `ESC` or ctrl+z fail. See screencast for details.

### Expected behaviour

It should be possible to cancel the action and go back to the original state.

### How we can reproduce it?

See screencast.

### Screenshots or screencasts

[Kazam_screencast_00007.webm](https://github.com/enso-org/enso/assets/292128/44bb64d4-7992-4dcb-9316-1abe745a78b7)

### Enso Version

c44d0f4ff2afd817a02ba38c982c5cfd7f8462a0

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by hubertp** [comment]
Maybe a duplicate of https://github.com/enso-org/enso/issues/6772 ?

**Comment by farmaazon** [comment]
No, it's different.

Actually, it's a kind of expected, as when you reconnect, you _disconnect_ the node first (that's why operator5 is replaced with `_`). The fact escape does not revert it is a part of #6576, and not-working undo-redo should be a part of  #6435
