### ISSUE TITLE
Faster FRP engine implementation.

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#6795]
Currently, we are spending a lot of time during FRP nodes initialization, removal, and evaluation (based on Chrome runtime profiles). Our FRP implementation was never optimized and we need to investigate ways to improve it and make it better.

**Comment by farmaazon** [comment]
@wdanilo what is the status? Can it be closed? (as the remaining work is tracked by #7043)

**Comment by wdanilo** [comment]
Good catch! Closing.
