### ISSUE TITLE
Make consistent types reported by the runtime with the types in the Suggestions Database

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#6800]
related #6715

Runtime type representation report static types with the `.type` suffix. In contrast, the suggestions database has the `is_static` flag instead. This creates inconsistencies in the language server API.

## TODO

- Return "function schema" together with the method pointer. It should contain a list of function arguments.

**Comment by farmaazon** [comment]
Given https://github.com/orgs/enso-org/discussions/6762#discussioncomment-5992601 is this task still valid?

<blockquote><img src="https://opengraph.githubassets.com/45da8563af2bd6530e9bf83a454b46e3b88477843a75cbbd35792a076554ce40/orgs/enso-org/discussions/6762" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/orgs/enso-org/discussions/6762">Language Server API · enso-org · Discussion #6762</a></strong></div><div>When I was discussion with @Frizi the issue #6715, we discovered several points about Language Server API to be discussed broader @4e6 @hubertp : What widgets needs to know The widgets need to know...</div></blockquote>

**Comment by 4e6** [comment]
I updated the description.

**Comment by farmaazon** [comment]
TODO section still mentions adding `.type` to the Suggestion Database.

**Comment by 4e6** [comment]
After the discussion with @Frizi, we decided that besides the method pointer, the IDE needs to know the list of arguments expected by the function.

I updated the task description

**Comment by 4e6** [comment]
The #6903 should fix expression updates for partially applied constructors.
