### ISSUE TITLE
Remove old "Open Project" view.

### ISSUE THREAD

**Issue by Procrat** [enso-org/enso#6804]
### Discord username

Stijn#6455

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

With the new dashboard, when I open the project list to switch to a different project, it shows up empty:
![bug](https://github.com/enso-org/enso/assets/607786/1297af77-803b-4a09-8ff7-1c48ea062d80)

### Expected behaviour

I expect the project list to be populated with my projects.

### How we can reproduce it?

1. Run Enso with `-feature-preview.new-dashboard`.
2. Open a project.
3. Press `ctrl-o` to open the project switcher.
4. Notice that it's empty.

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by farmaazon** [comment]
Related to #6756. Actually, with the new dashboard, we should remove the old "Open Project" window. @sylwiabr correct me if I'm wrong.

**Comment by wdanilo** [comment]
@farmaazon you are correct.
