### ISSUE TITLE
`Could not resolve engine version for Edition(Some(NaN)` warnings

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6806]
### What issue are you facing?

When I switch from default cloud context to local one I get spammed with ``projectmanager`` warnings:

(see log section - it's too long to paste here)

### Expected behaviour

No unnecessary warnings

### Logs

[new 17.txt](https://github.com/enso-org/enso/files/11543474/new.17.txt)

### Enso Version

2023.5.23 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by JaroslavTulach** [comment]
I see:
```
[org.enso.projectmanager.service.ProjectService] Could not resolve engine version for 
Edition(Some(NaN),None,Map(),Map()).
Falling back to Edition(Some(2023.2.1-nightly.2023.5.23),None,Map(),Map())
```
not sure what it is caused by, but certainly we can report the error just once.

**Comment by xvcgreg** [comment]
It might be connected to the fact that all of my projects except today's one was created with an older version or have the version erased from the YAML file?

**Comment by hubertp** [comment]
This has nothing to do with switching to local context (I saw that message just by randomly using IDE):
```
[debug] [org.enso.projectmanager.requesthandler.ProjectListHandler] started (org.enso.projectmanager.requesthandler.ProjectListHandler@5437483a)
[warn] [org.enso.projectmanager.service.ProjectService] Could not resolve engine version for Edition(Some(NaN),None,Map(),Map()). Falling back to Edition(Some(0.0.0-dev),None,Map(),Map())
[debug] [org.enso.projectmanager.requesthandler.ProjectListHandler] stopped
```

**Comment by hubertp** [comment]
> or have the version erased from the YAML file?

@xvcgreg yes, although the `Some(NaN)` is wrong and misleading.

**Comment by hubertp** [comment]
Reduced to a simple test-case (now fails):
```
    "correctly de-serialize missing edition" in {
      val config =
        """name: FooBar
          |edition:
          |""".stripMargin
      val parsed = Config.fromYaml(config).get

      parsed.edition.get.parent shouldBe None
    }
```

**Comment by hubertp** [comment]
#6086 fixed the warning so that it now properly complains about a missing edition (and defaults to some hardcoded version). No warning like the above in the logs.
