### ISSUE TITLE
Connecting a node inside vector editor is adding a new element and connecting it to the newly created port

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6822]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/77f7a1e1-6374-4418-aef4-5687514fcff7

### Expected behaviour

The connection should be done for selected port

### Enso Version

Nightly 24.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
I found a way to reproduce it. You need to have the mouse cursor very close to the left edge of the port, so after connecting, the cursor changes to (+) icon.

Or you can click, then move the cursor between elements (so it becomes (+)) and then release.

In normal vector (like `[1, 2, 3, 4]`) it just adds a new element (`_`) but in some cases the old element is restored (maybe when there is a drop-down widget inside? Anyway, the `rename_column` method always restored old value).

**Comment by farmaazon** [comment]
No longer relevant in GUI2 (no insert-between areas).
