### ISSUE TITLE
Trying to drag scroll bar in a drop down inside a vector editor made the whole item move (with drop down and all).

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6823]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/c8ce7134-54c6-4f93-87b3-59c967a3d48d

### Expected behaviour

Dragging scroll should not move element of a vector.

### Enso Version

nightly 24.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by wdanilo** [comment]
I'm confused. The title tells about scrolling drop down, and the description tells about dragging the scroll bar. So which one is correct? It's hard to understand what you really did by looking at the video.

**Comment by sylwiabr** [comment]
@wdanilo dragging scroll bar - I updated the title. For scrolling drop-down bug we have another issue.

**Comment by farmaazon** [comment]
No longer reproducible in GUI2
