### ISSUE TITLE
Add polyglot tests for equals and hashcode

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6826]
Add polyglot tests to `runtime-with-polyglot` project. Currently, `EqualsTests` and `HashCodeTests` run with a `ValueGenerator` that generates only Enso and Java values. We should add `EqualsPolyglotTests` that use a `ValueGenerator` with all the other languages.

Mentioned in https://github.com/enso-org/enso/pull/6820#discussion_r1203820389

For the inspiration, see https://github.com/enso-org/enso/pull/6820

**Comment by JaroslavTulach** [comment]
We are living without them for a long time. Let's add them when bugs are found.
