### ISSUE TITLE
Dynamic dropdown is not displayed if the argument is annotated with the `Widget_Helpers.make_column_name_vector_selector`

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#6836]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

There is no dropdown for the `columns` argument of the `Table.parse` method

https://github.com/enso-org/enso/blob/4cbd5f45a172177171dadea688fda81ee056f6bc/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso#L848-L851

The method uses `Widget_Helpers.make_column_name_vector_selector` for the `columns` dropdown which returns the following structure when evaluated:
```json
[["self",null],["columns",{"type":"Widget","constructor":"Vector_Editor","item_editor":{"type":"Widget","constructor":"Single_Choice","values":[{"type":"Choice","constructor":"Option","label":"Number","value":"'Number'","parameters":[],"icon":""}],"label":null,"display":{"type":"Display","constructor":"Always"},"allow_custom":true},"item_default":"'Number'","label":null,"display":{"type":"Display","constructor":"Always"}}],["type",{"type":"Widget","constructor":"Single_Choice","values":[{"type":"Choice","constructor":"Option","label":"Auto","value":"Auto","parameters":[],"icon":""},{"type":"Choice","constructor":"Option","label":"Integer","value":"Value_Type.Integer","parameters":[],"icon":""},{"type":"Choice","constructor":"Option","label":"Float","value":"Value_Type.Float","parameters":[],"icon":""},{"type":"Choice","constructor":"Option","label":"Date","value":"Value_Type.Date","parameters":[],"icon":""},{"type":"Choice","constructor":"Option","label":"Date_Time","value":"Value_Type.Date_Time","parameters":[],"icon":""},{"type":"Choice","constructor":"Option","label":"Time","value":"Value_Type.Time","parameters":[],"icon":""},{"type":"Choice","constructor":"Option","label":"Boolean","value":"Value_Type.Boolean","parameters":[],"icon":""}],"label":null,"display":{"type":"Display","constructor":"Always"},"allow_custom":true}],["format",null],["error_on_missing_columns",null],["on_problems",null]]
```

In contrast, the dropdown for `Table.at` method is displayed correctly

https://github.com/enso-org/enso/blob/4cbd5f45a172177171dadea688fda81ee056f6bc/distribution/lib/Standard/Table/0.0.0-dev/src/Data/Table.enso#L210-L212

But it uses a different `Widget_Helpers.make_column_name_selector` method that returns
```json
[["self",null],["selector",{"type":"Widget","constructor":"Single_Choice","values":[{"type":"Choice","constructor":"Option","label":"Number","value":"'Number'","parameters":[],"icon":""}],"label":null,"display":{"type":"Display","constructor":"Always"},"allow_custom":true}]]
```

I also noticed that there is the same issue with other methods (i.e. `Table.cast`, `Table.distinct`) that use the `Widget_Helpers.make_column_name_vector_selector` method to define a widget.

### Expected behaviour

IDE displays a dropdown for the `columns` argument of the `Table.parse` method.

### How we can reproduce it?

Select a `parse` method of a table (see the screenshot)

### Screenshots or screencasts

![2023-05-24-192658_1099x497_scrot](https://github.com/enso-org/enso/assets/357683/784424c3-f303-4a35-922d-b3715932184a)

### Enso Version

cbc3568cf

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

113.0.5672.126

### Operating System

Linux

**Comment by JaroslavTulach** [comment]
Looks like a problem in `Widget_Helpers.make_column_name_vector_selector` can you glance at it James? If it is not clear where the problem is, pass back I can investigate more.  CCing @jdunkerley, @Frizi.

**Comment by 4e6** [comment]
It is either the IDE does not understand the `{"type":"Widget","constructor":"Vector_Editor",` Vector_Editor constructor, or there is some other issue in the widget reply.

**Comment by jdunkerley** [comment]
The columns widget is a Vector editor. If you move to the right of the word you should get an add circle pointer

Clicking that will add the first item in the Vector which has a drop-down of columns. 

There will be an indicator added soon I believe. 

Definitely was working for me today but will check on develop tomorrow.

**Comment by 4e6** [comment]
> If you move to the right of the word you should get an add circle pointer

Ok, that worked, but this behavior is very hard to discover. There should be a better clue

![2023-05-25-003741_1207x460_scrot](https://github.com/enso-org/enso/assets/357683/ba88edc9-c8fb-4fc7-9798-1bcdea8791f8)

**Comment by Frizi** [comment]
The new design changes the looks of vectors in the node. There will always be an indicator to add an element to the end. It is simply not added yet.
![image](https://github.com/enso-org/enso/assets/919491/79287430-336d-4571-9215-6c5984074883)

**Comment by JaroslavTulach** [comment]
> > If you move to the right of the word you should get an add circle pointer
> 
> Ok, that worked

Can I resolve this with **not a bug** resolution given there are improvements planned?

**Comment by 4e6** [comment]
Closing as not an issue
