### ISSUE TITLE
Dashboard button is visible over full screen visualization

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6839]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![image](https://github.com/enso-org/enso/assets/12892578/92ffc068-fe25-422a-ab3e-2cbfe46a3b24)

### Expected behaviour

Dashboard button should be hide when opening full screen vis just like other buttons.

### Enso Version

nightly 25.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
Merging with #6722
