### ISSUE TITLE
Editing node by `ctrl`+`click` on the drop-down triangle is putting the first entry from the drop-down instead of typed value

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6845]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/567e6056-ec0d-439c-b90c-b59f29278cf1

### Expected behaviour

Value written by user should be accepted

### How we can reproduce it?

1. add a `set` node
2. connect column you want to add to the table
3. ctrl+click on the node to enter edit mode **over the drop-down triangle of `column_name` port**.
4. write new desired column name
6. press enter to accept the written text

### Enso Version

nightly 25.05

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
Reproduced, but it has nothing to do with ctrl key. It happens when the ctrl+click (to start editing node) was done over the drop-down's triangle.

**Comment by farmaazon** [comment]
Updated description.

**Comment by sylwiabr** [comment]
Can not reproduce it after recent changes
