### ISSUE TITLE
Column `==` operator does not compare values with Nothing

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#6846]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

`column == Nothing` always returns a column filled with `Nothing`s (see the screenshot)

### Expected behaviour

Vectorized column `==` operator compare values with `Nothing`

### How we can reproduce it?

Consider the following program (see the screenshot)

```py
operator1 = Column.from_vector "Number" [Date.new 2022, Nothing]
operator2 = operator1 == Nothing
```

### Screenshots or screencasts

![2023-05-25-133200_869x765_scrot](https://github.com/enso-org/enso/assets/357683/3cf8fe75-80bd-4da6-8733-e99f93b563cd)

### Enso Version

792cbc448

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

113.0.5672.126

### Operating System

Linux

**Comment by jdunkerley** [comment]
Agreed behaviour for `==` with Nothing is this.
