### ISSUE TITLE
Suggestion should contain a list of annotations

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#6847]
A method suggestion should contain a list of generic annotations of type `@name expression`. Right now it is sufficient to store just the annotation name.

It will significantly speed up the IDE because right now to get this information it needs to make one call per function to the language server.

**Comment by Frizi** [comment]
To be more specific, the potential win on the IDE side is to completely skip querying for dynamic widget data for all arguments that don't contain an annotation, which is a majority of them. That will drastically reduce the number of attached visualizations at any given moment.
