### ISSUE TITLE
`Text.find_all` can loop endlessly

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6856]
As shown in the video

https://github.com/enso-org/enso/assets/1436948/1550a1f4-c2be-43a4-9787-ec3607ad2258

Repro:
1. Create a text value
2. Press Tab on it to open CB, type `find_all` and select that entry from CB (by LMB or enter)
3. Observe

For a brief second the input ports **do show up** but they actually are _wrong_ - `find_all` on `Text` does not have a `path` argument.

**Comment by radeusgd** [comment]
These logs may be related:
```
[warn] [2023-05-25T17:09:07.294Z] [enso] Visualisation evaluation failed: Compile error: The name `find_all` could not be found..
[warn] [2023-05-25T17:09:07.436Z] [enso] Visualisation evaluation failed: Compile error: The name `find_all` could not be found..
[error] [2023-05-25T17:09:25.039Z] [org.enso.languageserver.requesthandler.visualisation.AttachVisualisationHandler] Request [Number(61)] timed out.
```

**Comment by radeusgd** [comment]
[bookclub_05_25.zip](https://github.com/enso-org/enso/files/11567559/bookclub_05_25.zip)

I attach my project files.

Weirdly, when I reopen the project in the IDE, nothing seems to compute _until I remove `find_all`_ from the stage.

![image](https://github.com/enso-org/enso/assets/1436948/bb287eb9-826a-49dd-ac57-f1da070e60fd)
![image](https://github.com/enso-org/enso/assets/1436948/281fe321-f2a0-4f15-90d3-d7eac618ffbe)


The nodes, up to `find_all` **do have** they colors, so seems like the values thesmselves did compute (apart from `find_all`), but the visualizations don't want to show up.

Later on I deleted `find_all`. This triggered **something**. In my verbose logging terminal I saw **tons** of text scrolling by and finally the visualization reappeared.

![image](https://github.com/enso-org/enso/assets/1436948/50701f3c-3749-4a5a-981f-c76f4f6d3f3e)

My logs: [20230525-171138-691-enso-project-manager.log](https://github.com/enso-org/enso/files/11567584/20230525-171138-691-enso-project-manager.log)

**Comment by radeusgd** [comment]
Now I'm getting tons of
```
[warn] [2023-05-25T17:43:43.592Z] [enso] Execution of function main failed (Compiler Internal Error: Operators should be desugared by the point of underscore to lambda conversion.).
[error] [2023-05-25T17:43:44.294Z] [enso] Error executing org.enso.interpreter.instrument.job.EnsureCompiledJob@61efe268
[warn] [2023-05-25T17:43:44.307Z] [enso] Execution of function main failed (Compiler Internal Error: Operators should be desugared by the point of underscore to lambda conversion.).
[error] [2023-05-25T17:43:44.832Z] [enso] Error executing org.enso.interpreter.instrument.job.EnsureCompiledJob@8728896
[warn] [2023-05-25T17:43:44.844Z] [enso] Execution of function main failed (Compiler Internal Error: Operators should be desugared by the point of underscore to lambda conversion.).
[error] [2023-05-25T17:43:45.957Z] [enso] Error executing org.enso.interpreter.instrument.job.EnsureCompiledJob@46d387be
[warn] [2023-05-25T17:43:45.971Z] [enso] Execution of function main failed (Compiler Internal Error: Operators should be desugared by the point of underscore to lambda conversion.).
[error] [2023-05-25T17:43:46.315Z] [enso] Error executing org.enso.interpreter.instrument.job.EnsureCompiledJob@3db6b9c
[warn] [2023-05-25T17:43:46.321Z] [enso] Execution of function main failed (Compiler Internal Error: Operators should be desugared by the point of underscore to lambda conversion.).
[error] [2023-05-25T17:43:46.481Z] [enso] Error executing org.enso.interpreter.instrument.job.EnsureCompiledJob@42ce5475
[warn] [2023-05-25T17:43:46.493Z] [enso] Execution of function main failed (Compiler Internal Error: Operators should be desugared by the point of underscore to lambda conversion.).
[warn] [2023-05-25T17:43:47.17Z] [enso] Execution of function main failed (Compiler Internal Error: Operators should be desugared by the point of underscore to lambda conversion.).
```

**Comment by jdunkerley** [comment]
It's something to do with `find_all` on `.*` pattern. I'll take a look in the morning.

![image](https://github.com/enso-org/enso/assets/4699705/0568ccbd-d470-4236-ad2b-2329390a5e60)
Works

but if you replace with `find_all` will crash.

**Comment by radeusgd** [comment]
As @Akirathan noted (possibly that should get its own issue, shall we create it?), ideally we should somehow detect the common message meaning the engine is failing - `Execution of function main failed` and display some message to the user in the IDE. We probably cannot explain much, but we can at least say that the engine is in a bad state and an undo+restart may be needed to bring it back. Currently, knowing this requires quite a bit of know-how and inspecting the logs - which we cannot expect the users to do.

> Edit: created a separate issue for this: #6859

**Comment by jdunkerley** [comment]
Agree we should have another issue for that.

**Comment by JaroslavTulach** [comment]
> ```
> [warn] [2023-05-25T17:43:43.592Z] [enso] Execution of function main failed (Compiler Internal Error: Operators should be desugared by the point of underscore to lambda conversion.).
> ```

That certainly looks like a `-compiler` error.  If I only had the source code that's causing this `Compiler Internal Error`! I am trying to install the provided [Unnamed_17 project](https://github.com/enso-org/enso/files/11567559/bookclub_05_25.zip) and see if I can obtain the same error.

**Comment by JaroslavTulach** [comment]
When I execute the `long.enso` program via `sbt:enso> runEngineDistribution --debug --run long.enso`:
```haskell
from Standard.Base import all
from Standard.Base.Data.Boolean import Boolean
from Standard.Table import all
from Standard.Database import all
from Standard.AWS import all
import Standard.Visualization

main =
    operator1 = "Press TAB key to create a new node"
    text1 = "https://www.football-data.co.uk/englandm.php"
    operator2 = Data.fetch text1 parse=Boolean.True
    operator3 = operator2.body
    operator4 = operator3.bytes
    operator5 = Text.from_utf_8 operator4
    operator6 = operator5.find_all
```
it spends **1200%** of my CPU in an endless circle. I managed to get following stacktrace from it:
```
case_branch (/Standard/Base/0.0.0-dev/src/Data/Vector.enso:1069)
Builder.append (/Standard/Base/0.0.0-dev/src/Data/Vector.enso:1066)
case_branch (/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern.enso:75)
go (/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern.enso:73)
Pattern.match_all<arg-2> (/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern.enso:78)
Pattern.match_all<arg-1> (/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern.enso:70)
case_branch (/Standard/Base/0.0.0-dev/src/Data/Text/Helpers.enso:12)
Helpers.expect_text (/Standard/Base/0.0.0-dev/src/Data/Text/Helpers.enso:11)
Pattern.match_all (/Standard/Base/0.0.0-dev/src/Data/Text/Regex/Pattern.enso:68)
Text.find_all (/Standard/Base/0.0.0-dev/src/Data/Text/Extensions.enso:275)
long.main (/home/devel/NetBeansProjects/enso/enso/long.enso:15)
Value.execute() (/home/devel/.config/Code/User/globalStorage/asf.apache-netbeans-java/userdir/var/cache/java-server/s8/org/graalvm/polyglot/Value.java:878)
Function.execute() (/home/devel/NetBeansProjects/enso/enso/engine/polyglot-api/src/main/scala/org/enso/polyglot/Function.scala:16)
Main$.runMain() (Unknown Source:836)
Main$.runSingleFile() (Unknown Source:748)
Main$.run() (Unknown Source:630)
Main$.main() (Unknown Source:1131)
Main.main() (Unknown Source:0)
```
the code never reaches `match_all` line `79` - e.g. the primary problem I see is an endless loop in regular expressions processing. Passing to @GregoryTravis

![My debugging session](https://github.com/enso-org/enso/assets/26887752/20c20b90-181d-49ea-a69f-973b1694bf59)

**Comment by jdunkerley** [comment]
Already have a fix for this on my branch. Should be merged tomorrow.
