### ISSUE TITLE
Let the user know that the engine has entered a 'bad state'

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6859]
From time to time the engine fails with a fatal error that makes it unable to perform _any_ computations, essentially freezing the GUI as any new nodes that are added are not going to get their results computed.

Sometimes it suffices to remove some offending node that caused this state, sometimes a restart of the IDE is also required. But some action is needed. Currently, in the IDE the only indicator of this is that no new values are being computed - making the user confused as to why the IDE is frozen.

The only way to discover that engine entered such a state is to inspect the logs. This is usually accompanied by a log message `Execution of function main failed`.

The user cannot be expected to browse the logs to understand that the engine is failing. Instead, we should detect this situation and display some kind of a message to the user. Such message should disappear once the engine starts working and sending updates again.

This was [originally proposed on Discord](https://discord.com/channels/401396655599124480/1111327381924347914/1111343076884091013) by @Akirathan. There, he also suggested that ideally we should detect what node is causing such a fatal failure and highlight that node in the IDE - letting the user know that they may try to remove that node which could fix the issue. If detecting the 'offending' node is indeed feasible, it may be worth implementing as well.

**Comment by JaroslavTulach** [comment]
The [log provided by Pavel](https://discord.com/channels/401396655599124480/1111327381924347914/1111343076884091013) contains:
```
[warn] [2023-05-25T17:00:43.347Z] [enso] Execution of function main failed (Unexpected values provided for RegexCompileNodeGen@297049: [Value TRegexObject{source=/HREF=".+"/usgi}, usg], [Layout_Atom_0_1,Text]).
com.oracle.truffle.api.dsl.UnsupportedSpecializationException: Some(Unexpected values provided for RegexCompileNodeGen@297049: [Value TRegexObject{source=/HREF=".+"/usgi}, usg], [Layout_Atom_0_1,Text])
  at org.enso.interpreter.node.expression.builtin.text.RegexCompileNodeGen.executeAndSpecialize(RegexCompileNodeGen.java:99)
  at org.enso.interpreter.node.expression.builtin.text.RegexCompileNodeGen.execute(RegexCompileNodeGen.java:47)
```
which is a very **serious crash in the Enso compiler**. `UnsupportedSpecializationException` means that an operation is not expecting the value it got as parameter. In CLI mode it'd mean crash - just like a C/Rust compiler crashing.

I hope that in the _language server mode_ the exception is caught and a _message is delivered to the IDE properly_, but still, it makes little sense to continue working on such project. Telling the user to _give up, save asap, and send us a bug report_ is the only recovery scenario.

Unless IDE needs a special message from the _language server_, it is purely `--gui` issue. CCing @hubertp.

**Comment by hubertp** [comment]
GUI should receive `executionContext/executionFailed` message, yes.

**Comment by farmaazon** [comment]
> GUI should receive executionContext/executionFailed message, yes.

Yes, we do. I think we even log it in our web console. We should also display it in our current status bar.
