### ISSUE TITLE
``window.size`` flag opens Enso with wrong dimensions

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6864]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Whenever I try to specify resolution to open Enso (ie. 1920x1080) it opens it in wrong size (scaled up)

![image](https://github.com/enso-org/enso/assets/108271897/18a5b2b5-7f8f-4c25-9722-dbf1fda03a16)

Image you can see is exactly 1920x1080 - Enso stacked below is larger.
CLI for the flag syntax.

The resolution of the Enso seems to be scaled by 1,25x - that'd match my monitor desktop resolution scale (125%)

### Expected behaviour

Enso opening in given resolution

### Enso Version

2023.5.26 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by somebody1234** [comment]
`scaleFactor` may be useful here: <https://www.electronjs.org/docs/latest/api/structures/display>
but:
- we might need a way to get the screen on which the window will open, before the window actually opens (or even after)? not sure how difficult this will be.
- this might need to be specialcased for macos retina?

<blockquote><div><strong><a href="https://electronjs.org/docs/latest/api/structures/display">Display Object | Electron</a></strong></div></blockquote>

**Comment by wdanilo** [comment]
I don't understand this bug report. In several places it tells about window size, in several it tells about resolution. These are 2 very different concepts here. @xvcgreg would you mind describing it more wordy and being very clear about what is happening, please?

**Comment by wdanilo** [comment]
> `scaleFactor` may be useful here: https://www.electronjs.org/docs/latest/api/structures/display but:
> 
> * we might need a way to get the screen on which the window will open, before the window actually opens (or even after)? not sure how difficult this will be.
> * this might need to be specialcased for macos retina?
> 
> > **[Display Object | Electron](https://electronjs.org/docs/latest/api/structures/display)**

I don't think we need to do anything there. At least on MacOS the window size is provided to Electron using virtual pixels and these are scaled to native pixels by the system. I hope other systems do the same. Anyway, let's wait till the bug is clarified, as I'm not sure if we are even talking about the same problem here :) 

<blockquote><div><strong><a href="https://electronjs.org/docs/latest/api/structures/display">Display Object | Electron</a></strong></div></blockquote>

**Comment by xvcgreg** [comment]
> I don't understand this bug report. In several places it tells about window size, in several it tells about resolution. These are 2 very different concepts here. @xvcgreg would you mind describing it more wordy and being very clear about what is happening, please?

@wdanilo Please look at the attached image.
I want to open Enso with a given resolution - which it currently does not. It opens it in the wrong resolution on at least one of the platforms we support. It should be fixed - it's not the top priority, but it should be fixed eventually.

We have ``-window-size`` flag - you are referring to that name being wrong? If so we should also change that.

**Comment by farmaazon** [comment]
I think resolution is a wrong word here. I understand it as "number of pixels on some area (screen)". It would make sense if Enso would go full-screen and change the resolution of the screen. Here we're setting window size in pixels - so the argument name is ok. And it's description:

```
-window.size                             Set the initial window size. Defaults  
                                         to 1380x900.
```
As you see, there is no word resolution here.

Also, there is no specification if those are _device_ pixels or not. I would expect they are not. We may look at other applications with such option (I don't know many, usually open source games which are not a perfect benchmark).

**Comment by wdanilo** [comment]
@xvcgreg your explanation make it even more confusing to me, so I believe @farmaazon is right, and you did not want to use the word "resolution". 

@farmaazon 100% agree. All apps that I tested were behaving in such a way that the size was interpreted as virtual pixels. Moreover, I remember that when I was initially implementing this option it was working correctly on Mac's retina. If it is not working now, this is a regression.

**Comment by xvcgreg** [comment]
@farmaazon @wdanilo 
Size and resolution are words that can be used interchangeably here. And their units depend on the context of the words used. For example: when we are talking about a size of a painting we usually talk in centimeters, when we talk about the resolution of a Vogue cover we usually talk about Dots Per Inch, but when we talk about the resolution of something displayed on a computer screen we talk pixels. 

Yes, I wanted to use word resolution. The resolution here is 1920 by 1080 pixels. We could debate academically here if I’d use word size – which could take into account system-specific desktop scaling. Apparently, it does but incorrectly, since default 1300/900 is actually opening as 1710/1076 on a 125% scaled screen resolution (should be 1625/1125) (side note: my screen has an aspect ratio of 21/9).

That renders the User incapable of defining the specific size/resolution of the window with Enso in it. As a user, I want to open Enso in 1920/1080 resolution without trial and error math on how to do that on my screen scale/aspect ratio.

It’s a minor issue since most users will resize the window at the start of the application. Nevertheless, this doesn’t work correctly – hence I have issued this bug.

**Comment by farmaazon** [comment]
>  Apparently, it does but incorrectly, since default 1300/900 is actually opening as 1710/1076 on a 125% scaled screen resolution (should be 1625/1125

Ok, this is something new, as it wasn't in the original report. I measured your screenshot and there the window size also does not match exactly `window.size` x 1.25 (however it's smaller in this case).

We can check how it behaves in macOS.

**Comment by xvcgreg** [comment]
> > Apparently, it does but incorrectly, since default 1300/900 is actually opening as 1710/1076 on a 125% scaled screen resolution (should be 1625/1125
> 
> Ok, this is something new, as it wasn't in the original report. I measured your screenshot and there the window size also does not match exactly `window.size` x 1.25 (however it's smaller in this case).
> 
> We can check how it behaves in macOS.

Yes @farmaazon I have noticed it too - that's why I think the aspect ratio might be relevant information here since vertical and horizontal scale are different on my screen (21/9) than in typical 16/9 or also common 16/10 aspect ratios on most widely used computer monitors.
I have access to 32/9 monitor - I can check it there if that'd help.

**Comment by xvcgreg** [comment]
Closing due to the impossibility of controlling the exact resolution operating system opens a window without taking into account the scaling factor of native pixels provided in the flag. No such flag exists that would open a window in the exact window size for recording purposes due to scaling. Will investigate a couple of suggestions made by @wdanilo and @farmaazon on how to open a window with desired x/y dimensions for future recordings.

**Comment by xvcgreg** [comment]
I'm reopening this issue due to the fact that on 1:1 scale of monitor with native pixels being equal to virtual ones Enso opens with the wrong x and y dimensions:


https://github.com/enso-org/enso/assets/108271897/3cbeae05-4ed0-4612-bc8e-e19a4e849c1a

@farmaazon 
platform the same, Enso version: 2023.6.1 Nightly

**Comment by wdanilo** [comment]
@xvcgreg what is the size of the window opened in your last video? Plus, can you please fix the title of the issue – it still tells about "resolution".

**Comment by xvcgreg** [comment]
@wdanilo exact dimmensions are 1904x1041 when opened with ``--window.size 1920x1080`` flag

counted inside the frame (w/o 1px border):
![image](https://github.com/enso-org/enso/assets/108271897/8d6a7b6e-4beb-4ac8-bded-2ccb96cfb4bd)

![image](https://github.com/enso-org/enso/assets/108271897/1a5edfbb-89a9-4413-bba4-cccef80ed9a0)

**Comment by wdanilo** [comment]
@xvcgreg could you try opening Chrome with the same size on the same monitor and checking if it works correctly, please?

`"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe" --window-size=800,600`

**Comment by xvcgreg** [comment]
@wdanilo 
![image](https://github.com/enso-org/enso/assets/108271897/b26b8560-7e01-49c3-a198-7752efa171ab)
Unfortunately, it's not.

**Comment by wdanilo** [comment]
So this is not out bug. Could you report it to Chrome and link the bug report here, please?

**Comment by xvcgreg** [comment]
> @wdanilo 

done:
https://bugs.chromium.org/p/chromium/issues/detail?id=1456169

<blockquote><div><strong><a href="https://bugs.chromium.org/p/chromium/issues/detail?id=1456169">1456169 - 
 
 
 chromium -
 
 
 An open-source project to help move the web forward. - 
 
 Monorail</a></strong></div></blockquote>
