### ISSUE TITLE
Warning and Error layer ordering on nodes went wrong

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6874]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Layers got messed up: 
![image](https://github.com/enso-org/enso/assets/108271897/2fa0d73a-4a47-4e77-b706-e0a6e326f9b2)

### Expected behaviour

node marked properly, like so:
![image](https://github.com/enso-org/enso/assets/108271897/af240160-8235-407e-8aa3-fa737cfb1711)

### Enso Version

2023.5.29 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by hubertp** [comment]
![Screenshot from 2023-05-29 18-37-01](https://github.com/enso-org/enso/assets/292128/898d47c1-c4b4-4447-b712-aead2062703f)

This appears to be a rather serious regression

**Comment by hubertp** [comment]
Regression introduced in https://github.com/enso-org/enso/pull/6595 @wdanilo

**Comment by wdanilo** [comment]
Oh wow, why I haven't seen it and why this code breaks it... it should not touch it. Anyway, I'm taking a look right now

**Comment by wdanilo** [comment]
Ok, I carefully reviewed all the code in my PR and it's not even close any shapes drawing or ordering, so why it is causing such problems is a big surprise to me. Investigation in progress ...

**Comment by wdanilo** [comment]
@hubertp @xvcgreg I can't repro it. It just works fine on my end. However, I noticed that we are not defining the ordering of layers there explicitly, which makes the order undefined. It means, that there is a possibility that on some build configurations this order will be different. This is bad and we need to fix such places. Anyway, I created a PR with the fix, @hubertp could you please confirm it works on your end? https://github.com/enso-org/enso/pull/6882

**Comment by hubertp** [comment]
That worked, yes. I got this on the nightly as well, not only on my local build.
