### ISSUE TITLE
Rename the `Decimal` type to `Float`?

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#6889]
### Discussed in https://github.com/orgs/enso-org/discussions/6858

<div type='discussions-op-text'>

<sup>Originally posted by **radeusgd** May 25, 2023</sup>
The [discussion](https://github.com/enso-org/enso/pull/6817#discussion_r1205810671) on #6817 showed that our number type names and `Value_Type` are misaligned:

> Unfortunately with `Value_Type` with have a bit of inconsistency between it and the Enso types.
> 
> <table>
> <tr>
>  <th> Value Type
>  <th> Enso Type
> <tr>
>  <td> Value_Type.Integer
>  <td> Integer
> <tr>
>  <td> Value_Type.Float
>  <td> Decimal
> <tr>
>  <td> Value_Type.Decimal
>  <td> (currently not supported) BigDecimal
> </table>
> 
> The names for value type were chosen to be close to the SQL type names. Maybe we should rename Enso `Decimal` into `Float`?? It is indeed a bit confusing to have this inconsistency. Also indeed, `Decimal` often suggests precise decimals, where we have IEEE-754 floating points.
> 

As discussed, we decided that we want to rename the `Decimal` type to `Float`.

- [ ] Rename the `Decimal` type in Enso code into `Float`.
	- [ ] Also in error messages and docs.
- [ ] Rename any references to the `Decimal` type name in the Java engine code.
- [ ] Ensure that tests are still passing.
- [ ] Rename any utilities in the Java engine, like nodes - `ToDecimalNode` should now be `ToFloatNode`, the `decimal` packages should be renamed to `float` etc.

**Comment by hubertp** [comment]
@jdunkerley to distribute?

**Comment by radeusgd** [comment]
I'm pretty sure this should have been closed by #7807
