### ISSUE TITLE
Cannot enter collapsed function that failed the execution

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#6897]
### Discord username

farmaazon

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I declared the following function:

```
func4 operator3 =
    operator4 = Data.fetch operator3 headers=[] parse=Boolean.False
    operator1 = operator4.body
    operator2 = operator1.bytes
    operator5 = Table.from
```
But the node `Main.func4` on my scene never evaluates, and I cannot enter it.

The dev console reports the following error:
```
router.ts:48 [ERROR] app/gui/src/model/project/synchronized.rs:560 Execution failed in context 5bc17fc6-5b10-4c78-be59-0689f8a2e71b. Error: Execution of function main failed (Conversion currying without `this` or `that` argument is not supported.)..
```

### Expected behaviour

I can enter node, even if it's erroneous.

### How we can reproduce it?

Try to collapse any function with `Table.from` and enter it.

### Enso Version

ab159238ddb27a3a2d1ea228b2dd23a4e19694f6 on 2022-05-26 engine

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by hubertp** [comment]
@farmaazon do you have the full project, please?

**Comment by farmaazon** [comment]
[Daily_Bookclub_25.zip](https://github.com/enso-org/enso/files/11610363/Daily_Bookclub_25.zip)

**Comment by hubertp** [comment]
I don't think this has anything to do with `Table.from`. The error itself can be easily reproduced via cli on
```
type Foo
    Value foo

type Bar
    Value bar

Foo.from (that:Bar) = Foo.Value that.bar

main =
    v = Bar.Value 42
    a = Foo.from v
    b = Foo.from
```

In fact, any non-dataflow failure will do.

**Comment by hubertp** [comment]
@farmaazon So I'm starting to wonder if this is really a bug in LS.
IDE does not send the request for `executionContext/push` or in fact, I think, do anything to enter the collapsed function.
But other than receiving `executionFailed` message from LS there is nothing really preventing it from doing the action. And the `executionFailed` is well... correct.

**Comment by farmaazon** [comment]
The IDE even does not try to enter method, because it does not know where to go. The execution failure makes our node not receive expression update, so we don't have any MethodPointer/MethodCall which would tell us what graph we ought to display. 

As a rule, if the node's output is grey, we cannot enter it.

**Comment by hubertp** [comment]
OK, talked to @4e6 about this. We can certainly change a runtime exception to a Panic which _should_ not cause execution failures.
But... this only delays the issue until someone else triggers a `RuntimeException` in some function. We will need to come up with some fallback mechanism, potentially involving some adaptation of API or IDE. :crossed_fingers: this doesn't have to be handled immediately.
