### ISSUE TITLE
Hide java_internal fields of constructors

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#6900]
Find a way to hide `java_internal` atom field suggestions in the component browser.

**Comment by JaroslavTulach** [comment]
Isn't the usual pattern the following?
```haskell
type Column
    Value java_internal
```
Then I believe that single type constructors like the `Value java_internal` are already hidden from the suggestion database.

**Comment by 4e6** [comment]
Currently, constructors with a single argument are not shown in dropdowns. But they still exist in the suggestions database.

**Comment by JaroslavTulach** [comment]
> Currently, constructors with a single argument are not shown in dropdowns. 
> But they still exist in the suggestions database.

Do they? I excluded them out in 0536eeb0bbb8847b91efd1559fb777fde425c73a. The code [still seems to be present](https://github.com/enso-org/enso/blob/578ba59f1dc9cb2d672b8d587176446cb86da0f8/engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala#L422) in (_another reincarnation_).

> constructors with a single argument are not shown in dropdowns. 

After some investigation I wonder what do you mean by _not shown_? Originally I thought you were saying that they are _"filtered out"_ by the IDE. Are you?

Probably not. The logic to filter out single constructors from `buildResolvedUnionTypeName` [still seems to be there](https://github.com/enso-org/enso/blob/578ba59f1dc9cb2d672b8d587176446cb86da0f8/engine/runtime/src/main/scala/org/enso/compiler/context/SuggestionBuilder.scala#L422).
