### ISSUE TITLE
Typing `set` in CB and accepting it quickly is putting `at` or `select_columns` in the node

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6908]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/dd05cf45-f581-40e9-a85a-fad830676309

### Expected behaviour

node should contain method that was typed

### How we can reproduce it?

1. open CB connected to a table (occurs more repeatably on bigger workflows like Colorado COVID example)
2. type `set` and press `enter` quickly

### Enso Version

nightly 31.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
Even after #6875 it still reproducible, however, I'm not able to put `at`. `select_columns` is put only if I had a node returning Table selected when opening CB.

The strange thing is, that when typing slowly, at no point `select_columns` is selected. Perhaps it some race between "rearrange entries", "accept selected entry", and "select best match".
