### ISSUE TITLE
User can connect to `.` in `_.get`

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6910]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/b2211f39-1cc9-44e5-b94c-44c653f46b07

### Expected behaviour

User should be able to connect to `_`  not to the `.`

### Enso Version

nightly 31.05

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by wdanilo** [comment]
Oh, connecting to dots is a new feature I have not heard about :P Just joking ofc :D

**Comment by kazcw** [comment]
*Should* the user be able to connect to the `get` after the dot? Replacing the identifier on the RHS of a `.` operator with the name of a variable will not normally yield a correct expression (and even if it is correct, it would not be a reference to the variable)

**Comment by kazcw** [comment]
It seems an edge can be connected to other binary operators, like `/` or `*`.

**Comment by wdanilo** [comment]
@kazcw no, the user should not be able to connect to `get` in `_.get`, as this would not give correct expression, as you noted. Possibility to connect to other binary operators is probably the same bug as reported here.

**Comment by farmaazon** [comment]
> Possibility to connect to other binary operators is probably the same bug as reported here.

Yes, it is the same bug, as in the AST (the old one, which IDE still uses) both `.` and other operators are an Infix (or Section) node.

**Comment by kazcw** [comment]
> @kazcw no, the user should not be able to connect to `get` in `_.get`, as this would not give correct expression, as you noted. 

Ok, I suppose this is similar enough that we could consider it part of the same bug.

**Comment by vitvakatu** [comment]
@Frizi is the best candidate for this task.
