### ISSUE TITLE
Picking local variable in the Component Browser sometimes makes an erroneous node 

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#6915]
The Component browser shows the local variables in "Local Scope" section, what is great, but does not work correctly when editing existing node:

1. The list contains an identifier of the node we're editing. Picking it will never work, so we should not show it in CB
2. Picking another identifier which is defined below the currently edited node also causes error (as the identifier is not yet known). They can be removed from the list, but there's a better solution of reordering nodes, so the edited node goes below the referred node. Still, there could be errors when the user is making cycles, but the errors in such case are expected.

**Comment by radeusgd** [comment]
> 2\. Still, there could be errors when the user is making cycles, but the errors in such case are expected.

We probably cannot do much about these in the engine, since from its perspective it looks just like 'not yet defined symbol'. But could we have special logic in the IDE to detect such cycles and display some more user-friendly message to the user?

**Comment by farmaazon** [comment]
Probably, but it's not an easy task, and I'd like to have it separately. We need to consider various cases, like "what if a user connected to the node making a cycle which _already_ had "unknown identifier" error" (because someone has written it in text).

As a side note: the pure functional language theoretically could use symbols defined later: is this missing feature, or it was designed to be unable to do so?

**Comment by farmaazon** [comment]
Today we don't display suggestions when editing node.
