### ISSUE TITLE
Investigate why `Text.parse_to_table` never finishes

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6917]
The following project never finishes. I tried to keep it running for 30 minutes, and still not finishing.
```
from Standard.Base import all
from Standard.Table import all
from Standard.Database import all
from Standard.AWS import all
import Standard.Visualization

main =
    operator1 = "https://raw.githubusercontent.com/enso-org/project-templates/main/Colorado_COVID/data/CDPHE_COVID19_County_Status_Metrics.csv"
    operator2 = HTTP.new
    operator3 = operator2.get operator1
    operator4 = operator1.write
    operator5 = operator3.code
    operator6 = operator3.body
    operator7 = operator6.to_text
    operator8 = operator7.characters
    operator9 = operator8.length
    operator10 = operator7.parse_to_table
    operator10
```

If we try to manually download the CSV from the URL, and load it, it works. It seems that the infinite hang is in `parse_to_table` method.

Run it via cmdline via engine.

**Comment by jdunkerley** [comment]
The default of `.` for the pattern on `parse_to_table` caused that to run for ages.
There is no way to terminate a long running task within the IDE.

Should investigate the issue with running cmdline as well.

**Comment by jdunkerley** [comment]
The default of every character being a row was the problem and the safepoint should stop it from hanging now.

**Comment by jdunkerley** [comment]
Confirmed following previous work now works.
