### ISSUE TITLE
Component Browser showing getters and empty modules when searching for static methods.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#6936]
When clicking to add a new node not connected to anything getters (fields of a constructor) should not show up.
![image](https://github.com/enso-org/enso/assets/4699705/f5ee19f4-f0eb-43eb-9de5-8ec0b31698eb)

This also includes getter of private types and constructors appearing.
![image](https://github.com/enso-org/enso/assets/4699705/0f61a57e-b916-408e-90cf-9e5627d559f8)

Additionally, we should filter modules which contain nothing public so they are not shown in the CB.
![image](https://github.com/enso-org/enso/assets/4699705/50581727-94ac-42c7-a8cf-cfec38e13dc2)

![image](https://github.com/enso-org/enso/assets/4699705/c162503c-46ce-49b0-ac45-c2981be9d224)

I would also suggest not showing modules by default and opting in to see them.

**Comment by 4e6** [comment]
The description provides `hours` as an example of a constructor filed, but in fact it's a method

https://github.com/enso-org/enso/blob/1ce3505e5b52161e1e198e914585ce443febe857/distribution/lib/Standard/Base/0.0.0-dev/src/Data/Time/Date_Time.enso#L297-L298

**Comment by 4e6** [comment]
#7007 hides getters from the completion response. Private suggestions and modules will be filtered out after we finish the work on the new exports algorithm.
