### ISSUE TITLE
Panic handling: Report and halt.

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#6953]
As discussed on the #6946 call, we should do two things differently in event of a panic:
- Ensure the application stops running, as continued execution is UB and can cause the appearance of strange bugs.
- Report the failure to the user.

Both of these things could be achieved by altering our panic hook to navigate to a new "crash" page. Note that this API should not attempt to pass information to the JS handler, as it is possible that state is so corrupted that we cannot export heap-allocated objects to JS correctly.

**Comment by wdanilo** [comment]
But I understand that the "crash page" can have info about the stack trace from Rust, right ? Ofc not displayed by default, but displayed after clicking "details" or something like that.

**Comment by farmaazon** [comment]
From the linked discussion:

> If we upgrade wasm-bindgen, we can enable [reference types](https://rustwasm.github.io/wasm-bindgen/reference/reference-types.html). That would eliminate this failure mode, and should be a little more efficient.

So, as I understand, an alternative (better IMO) could be bumping WASM version, enable reference types and then give the user crash reports but not force them to stop working?

**Comment by farmaazon** [comment]
Merging with #7376
