### ISSUE TITLE
Enso stops responding to inputs and no cursor is rendered

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6958]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Enso stops responding to inputs after CB is opened and typing method name is rewritten (typed ie. ``deli`` backpsaced it and typed ``to``) as you can see on the video here:

https://github.com/enso-org/enso/assets/108271897/4c6bcb5d-5fac-4575-8eb0-6f27181b3a91

I can repeatedly invoke this error.

### Expected behaviour

Enso working after searcher input is edited multiple times

### Logs

[20230606-073615-891-enso-project-manager.log](https://github.com/enso-org/enso/files/11661347/20230606-073615-891-enso-project-manager.log)

### Enso Version

2023.6.6 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by xvcgreg** [comment]
Nightly 2023.6.5 log with same problem:
[20230606-074935-585-enso-project-manager.log](https://github.com/enso-org/enso/files/11661435/20230606-074935-585-enso-project-manager.log)

**Comment by xvcgreg** [comment]
Nightly 2023.6.2 same as above:
[20230606-075450-254-enso-project-manager.log](https://github.com/enso-org/enso/files/11661475/20230606-075450-254-enso-project-manager.log)

**Comment by jdunkerley** [comment]
The issue is that `to_uri` is being passed a massive string (7.2Mb) and reporting an error message containing this.

The IDE is then trying to render this (assuming it makes it over the lang server protocol) and freezing while it tries to render.

I have amend `to_uri` to truncate the URI if a syntax error but IDE team should also look at where the IDE is hanging.

cc: @farmaazon

**Comment by farmaazon** [comment]
I guess we try to display a 7.2 Mb string in HTML, trusting the engine that error messages are always reasonably small.

**Comment by jdunkerley** [comment]
I am amending this error message but it completely hangs the IDE at the moment - so might be worth taking just the first 256 characters or similar.

**Comment by xvcgreg** [comment]
Nightly 2023.6.7 still freezes on ``to_uri`` suggestion displayed in CB

**Comment by farmaazon** [comment]
@jdunkerley shouldn't the message cut be performed somewhere "higher" than IDE? The messages should be reasonably short, regardless if we display them in IDE or print to console (nobody will gladly read 7.2 Mb bump).

Or have you done it already, and IDE is still freezing?

**Comment by farmaazon** [comment]
@jdunkerley bump ^

**Comment by jdunkerley** [comment]
The error message on this specific issue has been fixed, so this one won't kill the IDE.

If however, a long panic message gets to the IDE, it will still hang it. We could add something in the language server as well. Given our limited rendering capability on error messages at the moment feels like we should truncate the message.

**Comment by xvcgreg** [comment]
@4e6 @hubertp check it out what can be added there as James has mentioned

**Comment by 4e6** [comment]
>  If however, a long panic message gets to the IDE, it will still hang it. We could add something in the language server as well. Given our limited rendering capability on error messages at the moment feels like we should truncate the message.

Yes, we can add a truncation logic on the language server side before sending the error messages
