### ISSUE TITLE
Add unit tests for the correct order of various Language Server locks

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#6960]
https://github.com/enso-org/enso/pull/6920 founds some problems with deadlocks and it turned out we have no unit tests that ensure the proper order of acquiring multiple locks.

https://github.com/enso-org/enso/pull/6920#pullrequestreview-1457468324 gave some suggestions, this will need to be investigated separately.

**Comment by jdunkerley** [comment]
Have asserts now.
