### ISSUE TITLE
On first launch Enso blinks white -> black -> white screens and stays blank (white) on launch

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#6971]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

First observed with yesterday dev build #6963 (https://github.com/enso-org/enso/actions/runs/5187801275)

https://github.com/enso-org/enso/assets/108271897/1a11828c-ad5c-4c5f-b10c-1b84ae2eee27

Second launch of Enso (and each consequent) launches it normally.
After reinstalling back to 2023.6.6 Nightly all goes back to normal and Enso launches normally on a first run.

### Expected behaviour

launch normally

### Enso Version

2023.6.7 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by Akirathan** [comment]
I don't see anything like that on linux AppImage. Seems specific to this Windows installer.

**Comment by sylwiabr** [comment]
any logs in the dev console when launching @xvcgreg ?

**Comment by xvcgreg** [comment]
[20230607-055136-317-enso-project-manager.log](https://github.com/enso-org/enso/files/11674387/20230607-055136-317-enso-project-manager.log)
[20230607-054952-843-enso-project-manager.log](https://github.com/enso-org/enso/files/11674388/20230607-054952-843-enso-project-manager.log)
[20230607-054706-666-enso-project-manager.log](https://github.com/enso-org/enso/files/11674389/20230607-054706-666-enso-project-manager.log)
[20230607-055311-943-enso-project-manager.log](https://github.com/enso-org/enso/files/11674390/20230607-055311-943-enso-project-manager.log)

@sylwiabr couldn't run it with flags since it opens forcefully just after the install

**Comment by Akirathan** [comment]
Nothing indicates that this is a problem with Engine, project-manager, or LS. @xvcgreg do you still experience these blinks on the latest nightly?

**Comment by sylwiabr** [comment]
I can not reproduce it on my Windows machine

**Comment by wdanilo** [comment]
@xvcgreg "since it opens forcefully just after the install" what does it mean?

**Comment by xvcgreg** [comment]
@Akirathan I will test it on today's build (have been on a time off)
@wdanilo It means that after the installation is done Enso opens itself w/o asking the user to do so - it's not a common practice. It forces me to close it in order to launch it with debug tools or verbose logging, or just working on other things while having it installed in the background to be ready for later.

**Comment by wdanilo** [comment]
Regarding the first part of the sentence, it's interesting. @mwu-tow do you know why our windows installer does so? MacOS installer behaves in the standard way (not opening Enso after installation).

**Comment by xvcgreg** [comment]
Can't reproduce it anymore (tried on Nightlys 6.12 and 6.13) - it can be closed.

@wdanilo @mwu-tow I'm leaving it open since you have a conversation above. @mwu-tow please close this issue once the new issue is created for Enso not opening/starting after installation is done on Windows.

**Comment by xvcgreg** [comment]
closing due to above
