### ISSUE TITLE
Missing drop-downs when opening the project on weaker hardware

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#6982]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I am opening a bigger project (i.e. Colorado COVID example) on weaker machine (see the spec below) not all of the drop-downs are rendered. After adding new nodes or editing existing ones the drop-downs appear. 

### Expected behaviour

All drop-downs should be rendered when loading the project.

### Screenshots or screencasts

![Enso_0mWShynKJr](https://github.com/enso-org/enso/assets/12892578/e5667932-be92-470e-a599-a88714dc2f96)
![Enso_SHsrWVdebf](https://github.com/enso-org/enso/assets/12892578/8f428d5a-40cb-4296-8e72-9b4d23ba6310)

### Enso Version

nightly 07.06.2023

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Hardware you are using

Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz   1.20 GHz, RAM 8.00 GB,

**Comment by Akirathan** [comment]
I can't reproduce it on my side, even with CPU throttling.

**Comment by farmaazon** [comment]
It may be a similar problem to one reported in #7001: Some attach-visualization requests fail, and we cannot retrieve information about widgets.

**Comment by farmaazon** [comment]
@sylwiabr do you still face this issue?

**Comment by sylwiabr** [comment]
can't repro on the package from 05.07
