### ISSUE TITLE
Table visualization is updated when creating new node

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#6983]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

@sylwiabr reported performance issues when typing quickly in CB.

https://github.com/enso-org/enso/assets/6566674/8734ce5c-c09f-4081-8218-87658a43de5f

![image](https://github.com/enso-org/enso/assets/6566674/10e98815-da27-4491-b3f5-fbb9460de274)

The table visualization (`ag-grid`) code is at fault, but there is an issue: we don't see table visualization on the node, so it should not be updated.

I reproduced this issue with a similar stack trace in the following project:

<img width="627" alt="image" src="https://github.com/enso-org/enso/assets/6566674/554a302f-ca16-469c-8db0-df7a73b71c73">

Steps to reproduce:
1. Create a new project, read some CSV using `Data.read`
2. __Important__ Open the table visualization on this node.
3. Open CB, quickly type `get` and accept the node.
4. Observe the stack trace in performance profile that shows table visualization updates.

Step 2 is essential. If no visualization is open on a node – I don't see table vis updates in the stack trace.

cc @wdanilo 

### Expected behaviour

We should not update table vis on different nodes.

### Enso Version

0a4df4faf3c1075cced1e51aa1ac598dfcee0d8b

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by wdanilo** [comment]
This is an important issue. It means that we are updating visualizations on other nodes even if we should not. And this causes several perf problems we observed recently. Btw, updating of this ag-grid visualization is super slow. It takes on the weak hardware 200ms.

**Comment by farmaazon** [comment]
Has anyone checked if this is not an engine issue? AFAIK, we update visualizations only when engine sends us an update (and it should not when receiving unrelated edits).

**Comment by sylwiabr** [comment]
update: the same happens when reconnecting the nodes

https://github.com/enso-org/enso/assets/12892578/be64d23c-64a2-46f8-9eb2-c96aff6b4738

**Comment by farmaazon** [comment]
Seems fixed in GUI2 - I don't see any table update.
