### ISSUE TITLE
After opening any project, the types under nodes are not displayed when hovered

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6994]
After opening any project, the types under nodes are not displayed when hovered. One has to open the visualization first for the type to be displayed.

[Screencast from 2023-06-08 09-50-43.webm](https://github.com/enso-org/enso/assets/14013887/076c0452-2438-4ad9-9b29-647487bb418b)

Works on `enso-linux-2023.2.1-nightly.2023.6.5.AppImage`, does not work on `enso-linux-2023.2.1-nightly.2023.6.6.AppImage`

**To reproduce:**
- Open any project
- Try to hover over any node.
  - The color is fine, but the type is not displayed under the node.

**Comment by farmaazon** [comment]
@Akirathan have you tracked which commit caused the issue?

**Comment by hubertp** [comment]
@farmaazon Nightly from 05/06 works fine. It's broken from 06/06 nightly.
If I was to guess, I would say it's @MichaelMauderer's change (https://github.com/enso-org/enso/pull/6831) since it is the only one on IDE that day. Will verify.

**Comment by hubertp** [comment]
@MichaelMauderer @farmaazon I confirm this has regressed via https://github.com/enso-org/enso/commit/72b202b7d09753d9af1adc8815ed0872396b0d7b

**Comment by jdunkerley** [comment]
This appears to have been fixed and now works so am closin.g
