### ISSUE TITLE
Horizontal scrollbar on long warning is not moving

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6996]
On a node with a long warning, open the warning visualization and try to scroll to the right/left. The scrollbar stays in the same place and only the cursor moves. I am uncertain whether this is on purpose or not, but it feels weird.

[Screencast from 2023-06-08 18-08-08.webm](https://github.com/enso-org/enso/assets/14013887/542663c7-aacf-4d55-b413-b6610ccac3fc)

**Comment by wdanilo** [comment]
It's of course not on purpose :)

**Comment by farmaazon** [comment]
After merging #6981 it's not reproducible.
