### ISSUE TITLE
Clicking and dragging on a scrollbar of a dropdown moves the whole element

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#6997]
Clicking and dragging on a scrollbar of a dropdown inside a vector editor moves the whole element. When there are many columns, I am unable to scroll down to the last column. Scrolling with a mouse moves with the whole scene instead of the dropdown widget.

[Screencast from 2023-06-08 18-37-57.webm](https://github.com/enso-org/enso/assets/14013887/9e18afcc-4d1c-4e98-83ca-c40ea11ee7dc)

**Comment by farmaazon** [comment]
May be similar (even duplicate of) #6823

**Comment by Akirathan** [comment]
Closing as duplicate of #6823.
