### ISSUE TITLE
Hide error message when execution is fixed

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7003]
The error message introduced in https://github.com/enso-org/enso/pull/6918 needs to be hidden when the execution is no longer failing.

This is blocked by https://github.com/enso-org/enso/issues/7002

**Comment by hubertp** [comment]
@farmaazon @vitvakatu Should be unblocked. Also, the execution failure messages should be less frequent now because (normal) program execution interruptions are not reported as failures (they never should have been).
