### ISSUE TITLE
Commented code is represented as an empty node

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#7004]
IDE represents commented-out code as empty nodes. Such commented code should be completely ignored.

![image](https://github.com/enso-org/enso/assets/14013887/749a50f5-5a1b-4ba7-8fbf-62f0a4f86c23)

**Comment by wdanilo** [comment]
Oh, that's funny :D

**Comment by farmaazon** [comment]
It might be not a problem of the parser, as IDE also takes some part of interpreting nodes' comments (there was a feature requested long ago, that controllers would be able to see what node has comments above).

**Comment by jdunkerley** [comment]
We need to agree how comments should be shown within the IDE and then ensure the parser produces correct AST as needed.

**Comment by kazcw** [comment]
This issue relates to plan comments, which I think as @Akirathan says should be completely ignored. When a doc comment (`##`) is encountered, the parser attaches it to the item on the following line. I believe when it is within a block like this, it is currently ignored in `AstToIr.java`.

**Comment by farmaazon** [comment]
Fixed by new parser.
