### ISSUE TITLE
Investigate reasons for Request timeouts during `AttachVisualizationHandler`

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7005]
https://github.com/enso-org/enso/issues/6724#issuecomment-1570239589 lists that `Request timeouts` happen frequently under heavy workload. Increasing timeouts (as in https://github.com/enso-org/enso/pull/6972) is unlikely to fix the underlying problem.

A request for attaching visualization should be handled rather swiftly (compared to sending data for the visualization).

**Comment by hubertp** [comment]
One thing which stands out when I'm reading the code is why are we requesting `writeCompilation` [lock](https://github.com/enso-org/enso/blob/develop/engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualisationJob.scala#L52) for that job. This will contend with for example compilation job which can certainly take a lot of time.

**Comment by JaroslavTulach** [comment]
Having a job that, as a first operation, tries to obtain a compiler lock, is a sign of poor design. If the lock isn't available, the job shall not be scheduled at all. Jobs that require some information from compiler or need the compiler to be idle are so common, that they need _support in the infrastructure_. It shouldn't be the job that requires the lock - **the infrastructure shall** realize that compilation is over and **invoke the job** at that moment.

NetBeans editing infrastructure has an intricate system of _"phases"_. Jobs register for individual phases and get invoked when such (compiler) phase is finished. For example identifying local variables happens sooner than resolving and binding imports.

Regardless of the infrastructure we select, the more _lock free code_ of regular tasks is, the better. Locks belong to the infrastructure.

**Comment by hubertp** [comment]
I can confirm that acquisition of locks in
- [ModifyVisualisationCmd](https://github.com/enso-org/enso/blob/develop/engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/ModifyVisualisationCmd.scala#L30)
- [AttachVisualisationCmd](https://github.com/enso-org/enso/blob/develop/engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/AttachVisualisationCmd.scala#L26)
- [UpsertVisualisationJob](https://github.com/enso-org/enso/blob/develop/engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/UpsertVisualisationJob.scala#L51)

is the real reason for the delays in handling those requests, ending up eventually as timeouts.

**Comment by hubertp** [comment]
Another insight: it seems we can also easily experience thread starvation in our `JobExecutionEngine`.
E.g.
A request comes from IDE for `executionContext/attachVisualisation`. It is handled by the handlers and eventually lands in `AttachVisualisationCmd` as executed by `CommandExecutionEngine`. The latter is executed and submits `UpsertVisualisationJob`. But the job is only started 5 seconds(!) later and this is the job that produces a response for the IDE. Hence the timeout in handler.

**Comment by hubertp** [comment]
> Another insight: it seems we can also easily experience thread starvation in our JobExecutionEngine.

And just to add more info. On startup, at some point we can have 60+ threads in the command pool and have only 1 thread in job pool:
![Screenshot from 2023-06-13 17-25-24](https://github.com/enso-org/enso/assets/292128/e71eed19-f219-43b6-888b-ca03145cef61)
![Screenshot from 2023-06-13 17-25-37](https://github.com/enso-org/enso/assets/292128/a70ad798-b360-485f-8aa8-673ab463b39f)

That can certainly lead to some bottleneck.

**Comment by JaroslavTulach** [comment]
FYI: [Mutex](https://bits.netbeans.org/dev/javadoc/org-openide-util/org/openide/util/Mutex.html) - my implementation of read/write lock with _"post-when unlocked"_ methods. Probably more flexible than our current `Locking` , but still my preferred architectural solution is to hide all locks.

**Comment by JaroslavTulach** [comment]
> > Another insight: it seems we can also easily experience thread starvation in our JobExecutionEngine.
> 
> And just to add more info. On startup, at some point we can have 60+ threads in the command pool and have only 1 

Having 60 threads that exclude each other by synchronizing on a lock is a sign of a poor design.

**Comment by hubertp** [comment]
> > > Another insight: it seems we can also easily experience thread starvation in our JobExecutionEngine.
> > 
> > 
> > And just to add more info. On startup, at some point we can have 60+ threads in the command pool and have only 1
> 
> Having 60 threads that exclude each other by synchronizing on a lock is a sign of a poor design.

Command pool is (almost) unlimited while job pool apparently [defaults](https://github.com/enso-org/enso/blob/develop/engine/polyglot-api/src/main/java/org/enso/polyglot/RuntimeServerInfo.java#L13) to 1. So in the case of sudden bursts of visualization requests, we run a ton of command handlers which can submit various jobs that are then queued until resources are available. 

Won't comment on the design as I wasn't the one who did it and there might have been different requirements 3 years ago.

**Comment by hubertp** [comment]
Note that "job parallelism" is adapted [during bootstrapping](https://github.com/enso-org/enso/blob/develop/engine/language-server/src/main/scala/org/enso/languageserver/boot/MainModule.scala#L295) to read the number of available processors. That code _should just work_ except when I actually log the value that is retrieved I get 1(!). ~The `availableProcessors()` method seems to be rather sensitive to the current state of OS, so probably a poor choice.~ 

Edit: I was wrong, `Runtime.getRuntime().availableProcessors()` returns the desired value. It's the value that ends up in the context's options appears to be wrong and always 1. This is a problem somehow option descriptors.
