### ISSUE TITLE
Visualization previews are blank

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#7006]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When creating or editing a node, a visualization preview is shown. This preview currently doesn't show any data.

### Expected behaviour

The preview should show the same visualization that would be enabled by accepting the current CB suggestion, then clicking the show-visualization-button on the node.

### How we can reproduce it?

1. Start creating a node that should have some data to show.
2. No data is visualized.

### Screenshots or screencasts

![image](https://github.com/enso-org/enso/assets/1047859/38a07398-59c3-4fb6-851e-74c67e058c6d)

### Enso Version

recent develop (ff51347)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by kazcw** [comment]
[I'll check whether this is a quick fix to include in my current PR]

**Comment by kazcw** [comment]
This is not related to the visualization attach/detach logic (which I'm currently debugging due to another issue). Rather, the problem is that we are trying to preview the current (usually incomplete) expression, not the current CB selection.

```
[ERROR] app/gui/src/model/project/synchronized.rs:580 Visualisation evaluation failed in context b8f30810-2b48-41e1-b2dc-46d0ab293a8e for visualisation b0f7dcb9-0cdd-4274-ba6b-ea358d48d119 of expression 37a90011-2002-4d5f-863a-ee1f54dc470d. Error: Method `orde` of type Table could not be found.
```

**Comment by wdanilo** [comment]
In such a case, the visualization should be hidden altogether in order not to confuse users.

**Comment by xvcgreg** [comment]
@farmaazon what caused this regression?

**Comment by farmaazon** [comment]
I don't know. Needs investigation.

**Comment by xvcgreg** [comment]
> I don't know. Needs investigation.

~~ok, why wasn't the investigation done before the removal of the ``triage`` label?~~
solved
