### ISSUE TITLE
Error visualizations are not styled consistently with other visualizations

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#7008]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The error visualizations have square corners.

### Expected behaviour

The application uses rounded corners.

### Screenshots or screencasts

![image](https://github.com/enso-org/enso/assets/1047859/33104d2c-ce86-41db-8fb8-fea67a090145)

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by wdanilo** [comment]
This is part of @Frizi work scheduled soon – he is working on making the look of Enso as in the mockup. @Frizi is there a task for it that we can link this issue to?

**Comment by farmaazon** [comment]
No longer relevant in GUI2 where we use new design of displaying errors.
