### ISSUE TITLE
Recalculate only necessary nodes when a node changes

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7020]
Currently when you change the input on a node low down on a workflow a huge amount can be recalculated.

For example, in the Covid Dashboard example changing day of month should not recalculate anything other than the downstream nodes of that.

**Comment by jdunkerley** [comment]
@jdunkerley to supply the Book Club Dashboard example.

**Comment by JaroslavTulach** [comment]
> @jdunkerley to supply the Book Club Dashboard example.

The report needs to be completed before it can be scheduled for an iteration. Do I understand correctly that we are waiting for a project that will demonstrate the "unnecessary node recomputation", right?

**Comment by wdanilo** [comment]
As @sylwiabr is away, @jdunkerley, do you have example projects / examples of this behavior?

**Comment by jdunkerley** [comment]
> As @sylwiabr is away, @jdunkerley, do you have example projects / examples of this behavior?

Yes hence it being allocated to me - I will get to this today hopefully.

**Comment by jdunkerley** [comment]
[Book_Club_20230531.enso-project.tar.gz](https://github.com/enso-org/enso/files/11798050/Book_Club_20230531.enso-project.tar.gz)

Attached project.

The section on the right has 3 drop downs and changing the last should recalculate the least.

**Comment by wdanilo** [comment]
@JaroslavTulach is this project enough for you to investigate it further? :)

**Comment by JaroslavTulach** [comment]
I have enhanced the project (download as [Book_Club_Covid_Timed.tar.gz](https://github.com/enso-org/enso/files/11914161/Book_Club_Covid_Timed.tar.gz) with _"timed"_ `func3` function) and I am looking at

![Year, Month & Day Dropdowns](https://github.com/enso-org/enso/assets/26887752/df792600-3fe5-40e0-91dd-6961fc70d689)

These _year_, _month_ and _day_ dropdowns influence a lot - almost every node "below them" depends on them. When I change something, then the "nodes bellow" are recomputed - but that's expected.

> day of month should not recalculate anything other than the downstream nodes of that.

I haven't seen an excessive update yet. I've added `func3`:

```haskell
polyglot java import java.lang.Thread

func3 number1 v =
    operator49 = Thread.sleep number1
    v
```
which helps me _delay the computation_ artificially and really see what is being recomputed. When I set the `number1` delay to 3000ms this is what I can capture:



![What gets recomputed](https://github.com/enso-org/enso/assets/26887752/c44018a6-3506-4e18-9171-c0a0c32ceb30)

Assuming the notification of _pending nodes is correct_ (CCing @hubertp), then everything is working as expected. I'd say.

**Comment by JaroslavTulach** [comment]
I believe things are working fine now. The following picture shows

![Pending expressions & nodes](https://github.com/enso-org/enso/assets/26887752/ff1394df-c731-4c94-ae4d-d4a7bf52448b)

that _pending expressions are grayed out_ and _pending nodes have a gray bottom_.  Graying out only happens _"below"_ the changed node. Everything seems to work fine.
