### ISSUE TITLE
Node pending status does not show/propagate correctly when recalculating

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7021]
Using the current Orders example.

When you open the project, the nodes will load in a pending state and then propagate updates correctly.
When you change a dropdown value, the IDE appears to freeze while it recalculates
The pending status does appear on connections but the flow of updates appears to stutter.
Appears particularly bad with errors in the graph.

https://github.com/enso-org/enso/assets/4699705/60d7b547-37b7-42f8-87df-d31cdd87d0cb

Using develop build as of 14th June.

**Comment by JaroslavTulach** [comment]
> IDE appears to freeze while it recalculates

We need to find out whether freeze is on the engine or the IDE side. If it is on the engine side, we need to capture profiling data. It is a shame we don't have anything like
- #6775

and the best way to report a bug is to tape it without any additional useful information. Forcing others to _replay_ the video manually. What a waste of time.

**Comment by jdunkerley** [comment]
https://github.com/enso-org/enso/pull/7183#issuecomment-1621700729

The second video in here doesn't show the progress.

**Comment by JaroslavTulach** [comment]
I will investigate more, but please note following comment: https://github.com/enso-org/enso/issues/7020#issuecomment-1614310039 - the way IDE _"highlights"_ pending nodes is very invisible: only by gray underlined bottom.

**Comment by JaroslavTulach** [comment]
> Using the current Orders example.

I assume the project can be found at [project-templates repository](https://github.com/enso-org/project-templates/tree/main/Orders).

**Comment by JaroslavTulach** [comment]
First of all, I don't see any _hiccups_. After a change of a parameter of the `read` method, the IDE recomputes swiftly. Second...

> ... note following comment: [#7020 (comment)](https://github.com/enso-org/enso/issues/7020#issuecomment-1614310039) - the way IDE _"highlights"_ pending nodes is very invisible: only by gray underlined bottom.

when I modify the `Orders/src/Main.enso` to `delay` computation of some nodes by 5s and I change the parameter of read, then

![gray bottom](https://github.com/enso-org/enso/assets/26887752/e980ee56-3449-479f-8382-4ee19df45f6a)

then the bottom of the last node is grayed out properly. E.g. the IDE has enough information about _pending_ nodes and _underlines_ such nodes properly. Closing.

**Comment by farmaazon** [comment]
The new look of _pending_ nodes is a part [of the new design](7125), they will be wholly faded a bit:

![image](https://github.com/enso-org/enso/assets/3919101/037543be-08a4-435c-8694-53b209fa8c24)
