### ISSUE TITLE
Blank screen after unexplained WebGL failure

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7025]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

On a fresh run, out of nowhere, got a blank screen.
![Screenshot from 2023-06-13 19-44-12](https://github.com/enso-org/enso/assets/292128/0dde8652-a277-4508-9f50-e4b5fe34f7e6)

### Expected behaviour

Probably chrome went nuts. But even if, we should have some way of notifying the user and potentially suggesting a restart.

### How we can reproduce it?

One-off, not able to reproduce.

### Screenshots or screencasts

See screenshot.

### Enso Version

6de2700209a51d70b7a6aa8d5664ba6062d98f51

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by farmaazon** [comment]
> Probably chrome went nuts. But even if, we should have some way of notifying the user and potentially suggesting a restart.

And we need to do it in HTML if WebGL does not work. I will merge it with #5201

**Comment by farmaazon** [comment]
In new GUI there is no webgl
