### ISSUE TITLE
User needs to click on the node to get `+` button appear for list editor

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7027]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I add a new node that accepts a list of arguments in order to add an argument I have to click on a node (see the video)

### Expected behaviour

List editor should be available immediately.

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/12892578/83ae80ef-3041-40b6-a24d-8f28ca926cdd

### Enso Version

Nightly 14.06

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by MichaelMauderer** [comment]
I can reproduce it, but I've noticed that it does not happen when the new node is newly created by doing the following:
* select source node
* press tab
* type “order”
* press enter
Now when hovering the new node, the plus does seem to appear.

When, however, typing the node fully, then the issue appears for the newly created node.

**Comment by jdunkerley** [comment]
This has been solved.
