### ISSUE TITLE
Raise a compile error if `self` is referenced from a static method

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7040]
Currently code like
```
type Foo
    Value x
    bar = self.x*self.x
```

yields no error at compile time because every method has the 'synthetic self'.

But of ourse this is most of the time an oversight - I forgot to add `self` and created a static method instead of a member - and it's my mistake.

So if I do:
```
o = Foo.Value 42
o.bar
```
which I wanted to work, it will fail with `Unresolved_Symbol` because the method is static by accident.

To prevent this, we can report a compile time error whenever `self` is referenced in method body but the method does not declare to be taking `self`.

The only issue is if the synthetic self reference ever needs to be used by user code. I'm not aware of such situations however. @hubertp do you know any obstacles here?

If not, I think reporting an error could make it easier to catch issues as essentially a `self` reference without a `self` argument is most likely just a mistake.

[(As mentioned on Discord)](https://discord.com/channels/@me/948519891961544714/1118588355798630420)

**Comment by hubertp** [comment]
> The only issue is if the synthetic self reference ever needs to be used by user code. I'm not aware of such situations however. @hubertp do you know any obstacles here?

Can't recall any at this point. This sounds like a desired improvement.
