### ISSUE TITLE
The selected visualization should be displayed over the nodes and connections.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7045]
The visualization which is selected should be displayed over nodes. 

The HTML visualization should be put in DOM above the canvas, and the system cursor should be displayed over them (similarly to the documentation panel). It will make those being displayed over other GUI elements, but it's acceptable for the scope of this task.

**Comment by farmaazon** [comment]
When working [on a different task](#6379), I discovered a problem with displaying visualizations over the nodes in general:

ATM, the HTML visualizations could be displayed over the entire canvas or below it. I assumed is just a matter of bringing system cursor (as our will be hidden under HTML), but the visualization "top bar" (where you can pick visualization) is also rendered on canvas, and also will be hidden by HTML (in case of Table vis for example it will be covered completely).

@wdanilo, what are the plans for "visualization chooser" in the new design? I cannot find it in figma files. If it will be "outside" the visualization content, then we will have no problem here (this task will be just postponed until new design). If "inside" then we can
1. Block visualization chooser when visualization is selected (or previewed).
2. Make some solution for interleaving HTML with EnsoGL elements.

**Comment by sylwiabr** [comment]
@farmaazon Here is the look for the new visualizations chooser: 
![image](https://github.com/enso-org/enso/assets/12892578/55fb736f-346b-4d57-926a-2add0f446da9)

**Comment by farmaazon** [comment]
Oh, so those icons are actually _visualizations_ to be chosen? How do we manage the custom visualizations then?

**Comment by wdanilo** [comment]
<img width="501" alt="image" src="https://github.com/enso-org/enso/assets/1623053/5ed3e0b6-86d0-4d6c-b5e2-3612c7a002ba">

The icon on the right of the eye is the visualization chosen. In case visualization provides an icon, it should be displayed on the drop down list. In case it does not, a generic icon for visualization should be used. Does it answer your question?

**Comment by farmaazon** [comment]
Anyway, my fears were true: We cannot implement that without a way of intermixing HTML with EnsoGL shapes. Or the visualization icons have to be also displayed in HTML.

**Comment by farmaazon** [comment]
In GUI2, you can just click node to bring it front, with its visualization.
