### ISSUE TITLE
Clicking outside node area while editing it deletes the node

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7058]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [x] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While editing a node when I click outside the node area it removes edited node.

https://github.com/enso-org/enso/assets/108271897/21a59329-935c-45df-8b67-a11e47242f4d

### Expected behaviour

clicking outside the node abandons node edition

### Enso Version

2023.6.19 nightly

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by wdanilo** [comment]
@xvcgreg this is a regression, a serious one. Please mark it as a regression.

**Comment by xvcgreg** [comment]
> @xvcgreg this is a regression, a serious one. Please mark it as a regression.

i did

**Comment by wdanilo** [comment]
> > @xvcgreg this is a regression, a serious one. Please mark it as a regression.
> 
> i did

No, you did not :)

<img width="540" alt="image" src="https://github.com/enso-org/enso/assets/1623053/3861dbe9-487d-4aec-8b18-7b267f66dbd6">

**Comment by MichaelMauderer** [comment]
Can reproduce this. I noticed that this does only happen when

(1) the newly created node is selected from the component browser. Not if it is created by typing. For example, typing `0` and pressing enter, the node is fine. If selecting “Number input” (and thus creating the same node containing `0`) and when editing and clicking away, the node will disappear. 

(2) the node is not connected to another node. When, for example, selecting `split` for a text node, and the newly created node is connected the text node, the new node will not disappear when editing and clicking away. 

Bisecting now.

**Comment by MichaelMauderer** [comment]
First failing commit: 2e39d7595fc30cd4aa52359b7d9776197ae176fe @farmaazon

**Comment by xvcgreg** [comment]
> > > @xvcgreg this is a regression, a serious one. Please mark it as a regression.
> > 
> > 
> > i did
> 
> No, you did not :)
> 
> <img alt="image" width="540" src="https://user-images.githubusercontent.com/1623053/246850539-3861dbe9-487d-4aec-8b18-7b267f66dbd6.png">

I thought this one: 
![image](https://github.com/enso-org/enso/assets/108271897/c2ada30a-2bcd-424b-afcb-5da019abbfdd)
is more important as it serves some purpose?

**Comment by wdanilo** [comment]
It does not serve the same purpose. The checkbox is for error reporter, the label is set by the team after it is confirmed that this is a regression. As you are part of the team, you can check both of them, or only the checkbox, and then people who will investigate it can add label.

**Comment by farmaazon** [comment]
Cannot reproduce it anymore. I think the additional fixes in #7032 could fix this as well.
