### ISSUE TITLE
Improve execution of jobs and commands

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7059]
This is a placeholder ticket for a new design for executing jobs and commands. It comes as part of the investigation into #7005 which discovered several shortcomings in the current implementation. Namely:
1) [Locks](https://github.com/enso-org/enso/blob/develop/engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/execution/Locking.scala) are used extensively to ensure the corrected of the execution
2) Jobs and commands are two ways of serving user requests. The former often does not guarantee timely response, leading to timeouts and unnecessary confusion

In #7005 we patched the underlying problem by sending replies early and take into account jobs that may still be in-progress while other requests come around. But there is an inherent problem between long-running jobs (e.g. compilation) and requests that should be served quickly, exacerbated by the extensive locking logic.

**Comment by jdunkerley** [comment]
Closing this one for now.
