### ISSUE TITLE
The IDE chooses to override location of new node too aggressively and then doesn't end near where user chose

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7064]
Dragging a link into an empty space, the IDE chose to put node in a different location.
This should be a very rare behavior (as user will probably want it where they chose) but appears to happen even when it looked perfectly fine space-wise.
Ideally, if it must move it would also look to move in the shortest distance possible moving left, right, up or down so that it is as close to where the user wished.

Video attached:

https://github.com/enso-org/enso/assets/4699705/13b652b9-d795-44ab-90ce-d58c7d9268e7

**Comment by wdanilo** [comment]
I propose for now to remove the auto-node-placing code as it's broken. We will fix it one day, but now, let's just remove it and create nodes exactly where they were dropped.

**Comment by MichaelMauderer** [comment]
But it should still be used for nodes that are created without edge dragging, yes? If a node is selected, and the user presses tab, the node should needs to be placed in a sensible position.

**Comment by wdanilo** [comment]
That's right!
