### ISSUE TITLE
Add marks to the performance profile by a hotkey or internal API

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7065]
### How important is this feature to you?

1 – Not too important now, but possibly important in the future

### Describe the idea you'd like to see implemented.

Add an ability to automatically trigger the profiler "cut-out" by adding a "mark" by hotkey or internal Rust API.

I see one feature that can be useful when debugging async code – triggering the profile "cut-out" automatically. For example, I want to debug a specific moment in the application when the bug happens – and I want to see somehow the list of tasks running at that moment. It is impossible with the current profiler – I have to record the logs, then somehow record the time of the bug, and find that time in the logs. The logs will contain some unnecessary information about what happened after the point of time I'm interested in.

This feature will allow filtering profiling data to keep only the profilers alive at a mark. Then you could use the `run-graph` to see those tasks visually; `intervals` to get a list; or `measurements` to see the task hierarchy and the history of each async task.

This will enhance our ability to debug async tasks, similar to the API implemented in https://github.com/enso-org/enso/pull/6753

### Would you be willing to help us implement this feature?

Yes

**Comment by MichaelMauderer** [comment]
I recently was also using the profiling to track a specific interaction in the GUI, and this would have been incredibly useful to narrow down the log file to the part of interest. This could save us a lot of time sifting through log files.

**Comment by farmaazon** [comment]
No longer relevant afer removing old GUI. I guess the parser does not use too much asynchronous code.
