### ISSUE TITLE
Delete panel doesn't wrap around the close icon.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7066]
If a project name is a little too long but not long enough to trigger line wrapping it appears behind the close icon.

![image](https://github.com/enso-org/enso/assets/4699705/a2918aa5-7ab0-4861-a8eb-430346356901)

**Comment by somebody1234** [comment]
will be fixed in #6919

(also i'm not sure this counts as a gui issue)

**Comment by jdunkerley** [comment]
Maybe we need a `dashboard` tag then

**Comment by wdanilo** [comment]
@jdunkerley I added `g-dashboard` label and assigned it here!
