### ISSUE TITLE
Differences in font and rendering two error messages on top of each other in IDE.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7067]
While doing some performance testing managed to get two error message pop-ups in the IDE.

![image](https://github.com/enso-org/enso/assets/4699705/af2cc92c-e8cd-457b-9dde-2eff87057962)

They appear to have different fonts and overlap at the top.

**Comment by wdanilo** [comment]
Different fonts are surprising to me. Does anyone from IDE team knows why it could happen?

**Comment by farmaazon** [comment]
> Different fonts are surprising to me. Does anyone from IDE team knows why it could happen?

Nothing scary: text::Area takes monospaced font by default, and Status Bar creates with default font.

Perhaps the mplus1 should be the default, replaced with mono only when required?

**Comment by wdanilo** [comment]
I think this is the correct solution Adam, yes.

**Comment by farmaazon** [comment]
The old status bar and pop-up were replaced with [a new notification system](#7458), so this should no longer be an issue.
