### ISSUE TITLE
Error message with two dots at the end.

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7068]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

two dots at the end of the error message: 
![image](https://github.com/enso-org/enso/assets/108271897/8bf5a5b6-f9af-4710-8bab-3d896cddfc5c)

### Expected behaviour

Properly formulated error messages.

### Enso Version

2023.6.19 nightly

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

Version 112.0.5615.138 (Official Build) (64-bit)

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by hubertp** [comment]
Honestly, I am completely against adding dots in errors messages. Especially in messages coming from LS.
Error wrapping is bound to trigger those kind of problems again and again.

**Comment by farmaazon** [comment]
> Honestly, I am completely against adding dots in errors messages. Especially in messages coming from LS. Error wrapping is bound to trigger those kind of problems again and again.

I agree. The one who receive/display error should decide if they display it with dot or comma or inside quotes.

So, as a rule, we should display dots in messages displayed for the user and in logs.
