### ISSUE TITLE
Major performance difference between inline function and as a node within IDE

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7070]
When mapping over a large Vector of text values (...) there is a big difference between a function being passed as a node or being inline within the `map` function node.

Inline: 0.28s vs As Node: about 6 minutes (after which it appears to timeout)

This is not the same when applying a `filter` taking predicate function.

Inline: 1.26s vs As Node: 0.84s

Test workflow:
![image](https://github.com/enso-org/enso/assets/4699705/15d1706a-2985-4e28-82a6-1e52c573ea81)

In the CLI: 
2.41s Filter with predicate in node vs 2.06s Filter with predicate in function
0.46s Map with predicate in node vs 0.42s Map with predicate in function

[Wordle_Solver.enso-project.tar.gz](https://github.com/enso-org/enso/files/11788840/Wordle_Solver.enso-project.tar.gz)

**Comment by hubertp** [comment]
Oh, this is a good one. It appears that we are literally spamming IDE with expression updates.

**Comment by jdunkerley** [comment]
> Oh, this is a good one. It appears that we are literally spamming IDE with expression updates.

That was my guess!

It also seems to leave the lang server in a state sending these messages so wont exit immediately later.

**Comment by jdunkerley** [comment]
Any idea why so different on filter vs map?

**Comment by hubertp** [comment]
> Any idea why so different on filter vs map?

One uses the builder the other not. I guess some instrumentation is messed up there.

**Comment by hubertp** [comment]
This seems to be a problem with `_.to_case Case.Lower` sending constantly expression updates. Replacing it with `identity` finishes immediately.
