### ISSUE TITLE
Display a critical failure message when runtime cannot initialize

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7073]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

If runtime fails to initialize, for example by not being able to install GraalVM, the IDE will hang in a weird state with no message to the user.
This is a very unlikely event, but still possible.

### Expected behaviour

I was expecting some notification telling me that "things are really bad, restart".
Especially because IDE receives the error from Language Server.

### How we can reproduce it?

For this example:
1) remove previous installations of GraalVM (e.g. `rm -rf ~/.local/share/enso/runtime/graalvm*`)
2) select the project
3) pull the plug on your internet :D

### Screenshots or screencasts

![Screenshot from 2023-06-19 17-44-19](https://github.com/enso-org/enso/assets/292128/4429f3c2-a6c1-4574-a74d-1b5284e6b370)

### Enso Version

5f572d068075d51beb2671e0c9604ac7471664fd

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by farmaazon** [comment]
Tested after removing graalvm from backend package. Opening immediately fails - no need of turning off internet connection. The error is displayed to the user, so I assume the task is fixed.
