### ISSUE TITLE
Ambiguous import of Nothing needs to be prevented

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#7084]
Create a project with `Main.enso` and `FromNothing.enso` files. Where `Main.enso` contains:
```haskell
import Standard.Base.Nothing
import project.FromNothing

main = Nothing == FromNothing.nothing
```
and `FromNothing.enso` is
```haskell
from Standard.Base import Nothing

nothing = Nothing
```
when you run the project, it yields `False`! That's wrong:
```bash
enso --run ~/enso/projects/FromNothing/
False
```
Both imports shall refer to the some `Nothing` type.

**Comment by Akirathan** [comment]
Are you sure that it should be False? `from Standard.Base import Nothing` imports a type, whereas, `import Standard.Base.Nothing` imports a module. I think the False is right there.

**Comment by GregoryTravis** [comment]
I am getting something similar:

<img width="563" alt="Screen Shot 2023-07-27 at 12 55 11 PM" src="https://github.com/enso-org/enso/assets/24406074/cbb9d585-1a2e-4158-afca-8627ced33c84">

This is also type vs module.

```
from Standard.Base import all
from Standard.Table import all
from Standard.Database import all
from Standard.AWS import all
import Standard.Visualization

main = 
    operator1 = enso_project.data/"all.bench.txt" . read (Delimited_Format.Delimited)
    operator2 = operator1.parse_to_columns "Column 1" "(?<operation>.*)/(?<method>.*)/(?<b>.*)"
    operator3 = enso_project.data/"all.bench.txt" . read
    operator4 = operator3.lines
    operator5 = operator1.filter "Column 1" (Filter_Condition.Contains "average")
```

**Comment by JaroslavTulach** [comment]
Nobody really complains about this anymore.
