### ISSUE TITLE
Fix macOS notarization

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#7091]
Administrative action is required in our company's Apple account (updating Apple Developer Program License Agreement).

**Comment by xvcgreg** [comment]
@mwu-tow Ola has access to this account, Invoice was paid a long time ago and it should be working. Please contact Ola and solve that - she's available today till 14.oo our time. From the first glance that she did over the account it looks alright.

**Comment by mwu-tow** [comment]
Fixed in #7112.
