### ISSUE TITLE
Expression type is no longer displayed for nodes when hovered over

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7098]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![Screenshot from 2023-06-21 17-30-54](https://github.com/enso-org/enso/assets/292128/bb8012b8-d6f4-461b-a15c-3abe46f8d9e1)

Apparently enabling quick visualization with ctrl brings it back for that specific node only.

### Expected behaviour

![image](https://github.com/enso-org/enso/assets/292128/a333987f-97c2-4250-8e42-0fa3c4128851)

### How we can reproduce it?

Hover over the node.

### Enso Version

5f572d068075d51beb2671e0c9604ac7471664fd

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by kazcw** [comment]
I think there's already a bug: #6994

**Comment by hubertp** [comment]
So old? Yeah, appears so.
