### ISSUE TITLE
Implement AI-powered searcher

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/enso#7099]
In order to prototype integration of AI powered searcher completion in the IDE
we create a simple new searcher that can be used din the IDE. It will be opened
instead of the component browser searcher when the user presses a special shortcut.
The input to the AI searcher will then be sued as a prompt for the AI model and the
results will be used to create a new node (or replace the currently edited one).

### First PR
* [x] Create a new searcher that translates the input to a prompt for the AI model and
  displays the results.
* [x] Integrate the searcher side by side with the component browser searcher. (#7146)
    * [x] Allow opening AI searcher or component browser searcher, based on shortcut used. 
    * [x] Hide preview visualization for the AI searcher and show it for the CB searcher
    * [x] Correctly show an edge between the AI searcher input node and the source of the `this` argument

### Clean-up for later
- [x] Move shortcut for opening searcher from `tab` to `enter`.  Currently, there is an issue with this: the `enter` key press is processed for opening the Component Browser, but it will also be immediately processed for accepting the input. This needs to be further investigated and solved. [2 days]
- [x] Implement support for one-shot expressions in the GUI. [3 days]
- [x] Implement Enso library for generating the prompt for the AI
  model and requesting the AI completion through an external endpoint. [3 days]
- [x] Integrate the new Enso AI library with the AI searcher, replacing the current LS AI endpoint [1 day]
- [x] Replace current use of the visualization API to execute Enso code in the AI searcher with a one-shot expression [1 day]

**Comment by wdanilo** [comment]
@MichaelMauderer could you add a short description here, please? :)

**Comment by farmaazon** [comment]
@MichaelMauderer And a list of tasks, what remained to do for first version (discussed during last meeting).
