### ISSUE TITLE
Cannot drag out from a node

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7102]
Use the newest nightly (or version built on develop @ e18ffb7ca07a9be1b3b8c393f8f1ceb87bbc4393) you cannot drag out from a node.

https://github.com/enso-org/enso/assets/4699705/c0378cd3-2bf2-4a49-8cae-f52a9a037b0f

On Windows 11 Pro.

**Comment by jdunkerley** [comment]
Working fine on 20th June nightly, broken on later builds.

**Comment by xvcgreg** [comment]
Cannot reproduce it on Nightly 2023.6.22


https://github.com/enso-org/enso/assets/108271897/26943f2d-2265-4bfd-a588-96a9463d5169

I'm also on W11pro

**Comment by MichaelMauderer** [comment]
I can reproduce this on develop. Bisecting now. 

But note that this only seems to affect "mouse-down + drag", not clicking on the output port. The latter still creates a new edge from the output.

**Comment by MichaelMauderer** [comment]
First failing commit seems to be fcaa7510c5048ab7022d492bfb4dcd296e827cdd @Frizi

**Comment by Frizi** [comment]
That seems like a bad regression from my changes, i'm able to reproduce it. Indeed the drag doesn't work, while clicking does. I'm going to fix it soon.

**Comment by jdunkerley** [comment]
Tested on my machine and dragging out working as normal again.
Other behavior seems fine as well.
