### ISSUE TITLE
No placeholder inserted for binary method

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#7107]
No placeholders are inserted for binary operators like `Integer.+`, `Integer.<`, etc.

[Screencast from 2023-06-22 12-44-03.webm](https://github.com/enso-org/enso/assets/14013887/070bee34-b861-4753-8ce9-c983c6867ddc)

Tried on `enso-linux-2023.2.1-nightly.2023.6.21.AppImage`.

**Comment by kazcw** [comment]
This is currently being worked on. It's part 2 of: https://github.com/enso-org/enso/issues/6854

**Comment by farmaazon** [comment]
Let's keep this task tracking the "operator arguments" only. #6854 is also about displaying operators in CB.
