### ISSUE TITLE
DocSection improvements

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7130]
Discussion in Discord: https://discord.com/channels/401396655599124480/1063461140794986636/1063461140794986636

I couldn't implement some of the requested changes in #6978 because IDE cannot extract some information from the existing DocSection format.

1. Argument names in the list should be bold (or otherwise emphasized). The list of arguments is currently provided as an HTML code with `<ul>` and `<li>` tags. It complicates documentation panel styling and makes distinguishing a list of arguments from any other text impossible.
2. Examples formatting is suboptimal because we are provided with the HTML code. Instead, we need a specific abstraction containing the example's header, description, and code.

**Comment by farmaazon** [comment]
The task about new docparser (referred by the discord thread) is closed as completed: #5448, so I guess the engine should just start using it.

**Comment by vitvakatu** [comment]
The new docparser still uses the old DocSection format, so it has the same set of problems.

**Comment by JaroslavTulach** [comment]
> new docparser ... is ... completed: #5448, so I guess the engine should just start using it.

I am afraid that's far from possible. Looking at the [associated PR I see a lot of removals](https://github.com/enso-org/enso/pull/5917/files#diff-ba87b05069ce6d6bc2bcc063f40bf85389597c107af7f20352604b701eb7ad86), but no additions on the JVM side. If I remember correctly @kazcw removed the old parser, but hasn't given the engine access to the new one. We would need new `Tree` subclasses to represent the documentation sections and I don't see any.

Should my understanding be correct, then _engine has no means to parse documentation_ right now. Can you comment, @kazcw?

**Comment by kazcw** [comment]
The new doc parser is not run by the engine; it is only in the frontend. If we want to change the syntax tree, we can just do it.

> The new docparser still uses the old DocSection format, so it has the same set of problems.

The old format is the *output* of the new parser. However, we are not handed the `DocSection` format fully-formed anymore; [we are now generating the HTML tags](https://github.com/enso-org/enso/blob/2bac9cc8441c2160e4c4488f0fce528380d75718/lib/rust/parser/doc-parser/src/doc_sections.rs#L171). If we want to change what final output is generated from the abstract representation, we can just do it.

**Comment by farmaazon** [comment]
You are right, I thought we still get documentation split into sections from the engine. But nowadays, the engine sends us the doc string, and the IDE parses it using a new doc parser.

**Comment by wdanilo** [comment]
Ok, so what steps are required to make the changes needed by @vitvakatu?

**Comment by farmaazon** [comment]
According to @vitvakatu:
> The first point there is mostly fixed (we have dedicated Section.Arguments type), second was not addressed, but examples need future rework either way. So I guess we can close this one
