### ISSUE TITLE
`File`'s `input_stream` type signatures are inconsistent

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7133]
Current `input_stream`'s definition

```
    ## PRIVATE
       Creates a new input stream for this file. Recommended to use
       `File.with_input_stream` instead, which does resource management.

       Arguments:
       - open_options: A vector of `File_Access` objects determining how to open
         the stream. These options set the access properties of the stream.
    input_stream : Vector File_Access -> Input_Stream
    input_stream self options = @Builtin_Method "File.input_stream"
 ```

does not correspond to the reality because
```
from Standard.Base import all

main =
    f = File.new "/tmp/foo.txt"
    i_stream_1 = f.input_stream []
    bytes_1 = i_stream_1.read_all_bytes
```

will error:
1. `[]` is not accepted as the builtin only accepts `Array`
2. `input_stream` returns a Java's `InputStream` rather than Enso's `Input_Stream`, as per type signature
```[tasklist]
### Tasks
- [x] Remove `to_array` method calls from `File.enso`
```

**Comment by hubertp** [comment]
As @JaroslavTulach noted, we should change `Array` arg to to `Array`-like object to make it happen (as part of #6299).

**Comment by jdunkerley** [comment]
The File operations do not have the coerce to Array function needed. The signature should be a `Vector File_Access` and then the last `to_array`s can be removed from the libs.
