### ISSUE TITLE
Removing a node does not remove the reference to it from connected nodes

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7135]
Like shown on the video:

https://github.com/enso-org/enso/assets/1436948/dbaa3f52-21b9-4ee1-93f1-341d22d57c2d

This seems like a regression - IIRC in the past when I removed a node, the connections are disconnected and the reference in other nodes would be removed or replaced with a `_` placeholder.

This is especially problematic (as in the video) when the node was connected to an optional argument. If the argument disappeared (as I recall used to be the case in the past) - the node would come back to the previous setting. Now, instead, the node becomes erroneous because it references a name that no longer exists.

**Comment by farmaazon** [comment]
I guess it's caused by #7041 change

I think the view was before emitting events about connections being removed before the node was removed. The @Frizi's change may have altered it, and probably it should be done on the controller side (it makes more sense to me).
