### ISSUE TITLE
If an operation executed on a node with a warning fails with a dataflow error, it is displayed wrongly in the IDE

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7141]
The repro is very simple - create a value with warnings (e.g. `Warning.attach "WARNING" "value"`) and call some method on it that will return an error (e.g. `value.at 10000` which should fail with index out of bounds error).

![image](https://github.com/enso-org/enso/assets/1436948/ffbf7d57-f22e-47d0-8261-5f8aba5d7e8a)

### Actual behaviour

If the `value` had a warning attached (yellow border), then the resulting node also has a yellow border and is rendered like a 'regular' value.

https://github.com/enso-org/enso/assets/1436948/716bcad3-3bc7-47a3-912a-ac1c97a1c2d1

We can even switch the visualizations (even though it is an error) and check the attached warnings. Somehow the dataflow error gets 'promoted' to almost regular value, as if it was implicitly `.catch`ed.

![image](https://github.com/enso-org/enso/assets/1436948/370e106a-0d0c-4054-8c30-e9c6782d48d8)

It does correctly answer `true` to `is_error` though.

### Expected behaviour

The `at` node should have a red border and be displayed as an error - regardless of if the 'parent' node had any warnings or not, the dataflow error should take precedence and be an _error_.

It is not specified what should happen to warnings. IMO it is okay for an error to be just the error and at this point the 'parent' warnings do not matter much anymore and could be ignored. But I also find it okay if we want to have some mixed display - like a red-yellow border indicating _both_ an error and warnings - I think displaying both can be OK although IMO is rather unnecessary and may be more confusing than useful.

But the gist is - if the method fails - it must be clear how to distinguish a node that errored from a node that contains a regular value (possibly with some warnings).

**Comment by farmaazon** [comment]
Reproduced it. The IDE get the "Value" payload from the engine, for the node, like this:
```
            {
                "expressionId": "1e71e7a3-295e-4b86-8be6-a895634594cb",
                "type": "Standard.Base.Error.Error",
                "methodCall": {
                    "methodPointer": {
                        "module": "Standard.Base.Data.Text.Extensions",
                        "definedOnType": "Standard.Base.Data.Text.Text",
                        "name": "at"
                    },
                    "notAppliedArguments": []
                },
                "profilingInfo": [
                    {
                        "ExecutionTime": {
                            "nanoTime": 7802282771993
                        }
                    }
                ],
                "fromCache": false,
                "payload": {
                    "type": "Value",
                    "warnings": {
                        "count": 1,
                        "value": "'WARNING'",
                        "reachedMaxCount": false
                    }
                }
            },
```
The "payload" should be of the "DataflowError" type. We may consider adding "warnings" field to that variant.

**Comment by Akirathan** [comment]
> The "payload" should be of the "DataflowError" type. We may consider adding "warnings" field to that variant.

Indeed. I would expect something like:
```json
{
    "expressionId": "152fd918-227b-4106-84ef-5e6c16fb641b",
    "type": "Standard.Base.Error.Error",
    "methodCall": {
      "methodPointer": {
        "module": "Standard.Base.Data.Text.Extensions",
        "definedOnType": "Standard.Base.Data.Text.Text",
        "name": "at"
      },
      "notAppliedArguments": []
    },
    "profilingInfo": [
      {
        "ExecutionTime": {
          "nanoTime": 102534572900549
        }
      }
    ],
    "fromCache": false,
    "payload": {
      "type": "DataflowError",
      "trace": [
        "152fd918-227b-4106-84ef-5e6c16fb641b"
      ]
    }
  }
```
