### ISSUE TITLE
When installing Enso on Windows we need to check for the VC++ Runtime

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7150]
If the Visual C++ Runtime is not present the GraalVM runtime will not work and will error and the language server will fail to start as the `gu` command will fail.

Need to install https://aka.ms/vs/17/release/vc_redist.x64.exe to get it to work if not present.

**Comment by hubertp** [comment]
@mwu-tow is that something you could tackle as part of installation process?

**Comment by wdanilo** [comment]
Oh, we should not require users to install VS C++ Runtime. Can we bundle it in the package somehow? What's the standard way of doing that? CC @mwu-tow

**Comment by mwu-tow** [comment]
@wdanilo 
This is strange. From what I've seen, the GraalVM is already shipping the necessary binaries. We should not need additional packaging nor rely on user-provided runtime.

@jdunkerley How is the language server spawning the `gu`? Does it use the `cmd` script wrapper? This might be just a matter of adjusting cwd or PATH.

**Comment by wdanilo** [comment]
Ok, good to know that @mwu-tow! In such a case this needs to be investigated and fixed in such a way that it just works for users without this runtime.

**Comment by mwu-tow** [comment]
This is presumably working and covered by https://github.com/enso-org/enso/pull/4019.
If the new information is available, the binaries should be packaged where needed (as was done elsewhere) rather than expected to be provided by the user.
