### ISSUE TITLE
Default placement of a new node should be smarter

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#7156]
Is the algorithm for the placement of a new node simply "go to the left side of the current node and find some free space, and place the new node there"? I have a project where I have a plenty of nodes to the left of the current node, and there is an empty space on the right side. Pressing `Tab` places the new node to the far-left side, which feels very weird in these situations.

[Screencast from 2023-06-29 08-47-48.webm](https://github.com/enso-org/enso/assets/14013887/6b0b9cbb-468c-4ebd-a1c1-18fd2688a62c)

**Comment by Akirathan** [comment]
Feel free to close the issue if this is intentional and there are no plans to change that.

**Comment by wdanilo** [comment]
This needs to be fixed. Let's keep this ticket opened. The current behavior is definitely not the best one.

**Comment by jdunkerley** [comment]
We should place new nodes on the right side not the left side of any existing node when pressing Enter to add one.

**Comment by farmaazon** [comment]
Merging with #8069
