### ISSUE TITLE
Electron can't access cashe Error

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7162]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Each time I open Enso it asks me to log in.

https://github.com/enso-org/enso/assets/108271897/6591e7f0-b4d9-46cd-bca4-75002e1ae9e6

### Expected behaviour

Once logged in it shouldn't ask me each time for credentials.

### Logs

[trace] [2023-06-29T11:09:23.155Z] [org.enso.loggingservice.LoggingServiceSetupHelper] Logging service has been set-up and is listening at `ws://localhost:62943/`.
│ ╰ Done in 99.5 ms.
│ Loading the window address 'http://localhost:8081/?startup.platform=win32'.
╰ Done in 188.7 ms.
[55404:0629/130923.246:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[55404:0629/130923.246:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[55404:0629/130923.309:ERROR:disk_cache.cc(205)] Unable to create cache
[55404:0629/130923.309:ERROR:gpu_disk_cache.cc(673)] Gpu Cache Creation failed: -2
[55404:0629/130923.309:ERROR:disk_cache.cc(205)] Unable to create cache
[55404:0629/130923.310:ERROR:gpu_disk_cache.cc(673)] Gpu Cache Creation failed: -2
Backend exited with code 1.
[39988:0629/130925.250:ERROR:cache_util_win.cc(20)] Unable to move the cache: Access is denied. (0x5)
[39988:0629/130925.251:ERROR:disk_cache.cc(205)] Unable to create cache
[55404:0629/130926.258:ERROR:service_worker_storage.cc(1945)] Failed to delete the database: Database IO error
Opening URL in system browser: 'https://production-enso-domain.auth.eu-west-1.amazoncognito.com/oauth2/authorize?redirect_uri=enso%3A%2F%2Fauth&response_type=code&client_id=4j9bfs8e7415erf82l129v0qhe&identity_provider=Github&scope=email%20openid&state=MNlNfEwzew2mUgtGH5XWuKJhiSsiKEBM&code_challenge=yN-BlxcM_VtTaibJxeflGNuHKq7_ADdgXtRU6LC79hg&code_challenge_method=S256'.
Expecting URL callback, acquiring the lock.
Got data from 'second-instance' event: 'C:\Users\xvc\AppData\Local\Programs\Enso\enso.exe,--allow-file-access-from-files,enso://auth/?code=a6b138a7-2dd6-4e60-9969-5eae4e10ceeb&state=MNlNfEwzew2mUgtGH5XWuKJhiSsiKEBM'.
URL callback completed, releasing the lock.
Checking if 'enso://auth/?code=a6b138a7-2dd6-4e60-9969-5eae4e10ceeb&state=MNlNfEwzew2mUgtGH5XWuKJhiSsiKEBM' denotes a URL to open.
Parsed 'enso://auth/?code=a6b138a7-2dd6-4e60-9969-5eae4e10ceeb&state=MNlNfEwzew2mUgtGH5XWuKJhiSsiKEBM' as URL: enso://auth/?code=a6b138a7-2dd6-4e60-9969-5eae4e10ceeb&state=MNlNfEwzew2mUgtGH5XWuKJhiSsiKEBM. Protocol: enso:.
Got URL from 'second-instance' event: 'enso://auth/?code=a6b138a7-2dd6-4e60-9969-5eae4e10ceeb&state=MNlNfEwzew2mUgtGH5XWuKJhiSsiKEBM'.
Got URL from second instance: 'enso://auth/?code=a6b138a7-2dd6-4e60-9969-5eae4e10ceeb&state=MNlNfEwzew2mUgtGH5XWuKJhiSsiKEBM'.
Received 'open-url' event for 'enso://auth/?code=a6b138a7-2dd6-4e60-9969-5eae4e10ceeb&state=MNlNfEwzew2mUgtGH5XWuKJhiSsiKEBM'.
'enso://auth/?code=a6b138a7-2dd6-4e60-9969-5eae4e10ceeb&state=MNlNfEwzew2mUgtGH5XWuKJhiSsiKEBM' is a deep link, sending to renderer.
Resource '/new-project.svg' not found.
Resource '/project.svg' not found.

### Enso Version

2023.6.29 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by farmaazon** [comment]
Cannot reproduce on Linux. Here, even a freshly downloaded nightly build seems to know who I am.

**Comment by farmaazon** [comment]
Worse, I also cannot reproduce that on Windows. It must be some specific setup of @xvcgreg 

Unfortunately, I can't check which commit introduced the regression.

**Comment by xvcgreg** [comment]
Cannot reproduce it on Nightly 2023.7.3 - closing
