### ISSUE TITLE
IDE does not retry to open project

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7163]
Some time ago, [I've implemented](#5802) retry mechanism for IDE initialization to make it more robust in the cloud environment. However, currently it does not work if the _opening_ of the project fails: we instead print an error log and leave the IDE in the unopened state.

Instead, we should retry several times, and if the all tries fail: _show the error to the user_ and block the view from any interactions (as there is no point in adding nodes, for instance).

**Comment by hubertp** [comment]
Would it help if LS reported some intermediate messages with say "initialization at stage X out of Y" rather than having nothing in between sending the `initProtocolConnection` and the reply?

**Comment by farmaazon** [comment]
It still would need some support from the IDE side, as I think we do not have mechanism of bumping timeout after receiving such updates.

**Comment by hubertp** [comment]
Yeap, certainly. But in case someone tries to run Enso on some outdated spec (and people **will** try that) then we will have to increase those timeouts incrementally, probably multiple times.
