### ISSUE TITLE
Visualizations disappear when project loads

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7182]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

A project with some visualizations is reloaded. After reboot, some visualizations appear to be fetching data and then suddenly disappear. There is no failure from LS, it also appears that IDE gets not only the response to the request but also the underlying data. Nevertheless IDE appears to send an explicit request to detach visualizations for unknown reason.

### Expected behaviour

Visualization should load data and stay up, preserving the state on closure of the project.

~Pretty sure this has worked in the past.~ Unable to confirm if this is a regression since visualizations have been rather unstable until recently.

### How we can reproduce it?

Same project as in https://github.com/enso-org/enso/issues/7140.

### Screenshots or screencasts

[Kazam_screencast_00016.webm](https://github.com/enso-org/enso/assets/292128/9e3ee7b5-6864-4bb1-8545-d5c85b5a2e59)

### Enso Version

b78a7e74e890bbc573178e5e856c65e6e8c83052

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by vitvakatu** [comment]
Can reproduce on the latest develop, IDE sends `detachVisualization` for some reason.
<img width="847" alt="Screenshot 2023-07-17 at 13 46 18" src="https://github.com/enso-org/enso/assets/6566674/371140f7-0427-4338-b907-a6c57a60aae3">

**Comment by farmaazon** [comment]
No longer reproducible in GUI2
