### ISSUE TITLE
Triggering recomputation in live environment closes all visualizations 

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7189]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Triggering a recomputation in live execution environment (with a play button) closes visualizations for all nodes and never brings them back automatically.

### Expected behaviour

Either not close them or reopen automatically. It is impractical if the whole project suddenly closes all visualizations and user has to manually reopen them.

### How we can reproduce it?

Use the same example as for #7140, just ignore the node with dataflow error.

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/292128/82ca1c3e-b89b-4467-beaf-e4a3ea0e92fb

### Enso Version

b78a7e74e890bbc573178e5e856c65e6e8c83052

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by vitvakatu** [comment]
Not sure what happens here, most probably an IDE bug:

1. IDE initiates recompute
2. IDE receives DataflowError
3. IDE detaches visualization
4. ... and attaches it back immediately
5. Execution completes, IDE receives expression update (without errors)
6. IDE detaches visualization.

[log.har.zip](https://github.com/enso-org/enso/files/12068038/log.har.zip)

<img width="486" alt="image" src="https://github.com/enso-org/enso/assets/6566674/58661261-8f2c-4b32-aa27-44a8ac0b5da0">

Assigning to IDE team for further investigation.

**Comment by farmaazon** [comment]
No longer reproducible in GUI2
