### ISSUE TITLE
Infix operators still not displaying correctly

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7190]
Follow up on #6374. It appears that while backend support was added to and we send method pointer info for infix operators, they are still not being displayed correctly in GUI. Needs further investigation.

**Comment by kazcw** [comment]
I think this needs some (probably simple) frontend work now that the frontend has the data. There's a bug for it: https://github.com/enso-org/enso/issues/7107

**Comment by farmaazon** [comment]
So, it's not engine's issue, and GUI already has a task for it, so this one I will close.
