### ISSUE TITLE
Use new Enso font

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7197]
There is a new font crafted by @wdanilo which we ought to use everywhere in GUI. We should no longer use mplus1 nor deja-vu fonts.

The fonts are defined in https://github.com/enso-org/font repository. The script may download the newest release. 

The font should be also available in HTML elements (applied to documentation panel, for instance).

**Comment by wdanilo** [comment]
Please only be sure that build script downloads newest release, so if we release a new font version, it is automatically bumped.

**Comment by farmaazon** [comment]
> Please only be sure that build script downloads newest release, so if we release a new font version, it is automatically bumped.

I don't think this is a good idea.

To make it working, the script would need to check for newest version _every time_. If the newest version turns out to be somehow broken (file unreadable or not uploaded), we will magically break _every_ commit on _everyone's_ machine. 

As a rule, I don't like when the build outcome depends on some external changes. The commit number and local env should always produce the same application. The "lock" files are for some reason.

**Comment by farmaazon** [comment]
Make sure the font brightness matches the design after using the new one.

**Comment by jdunkerley** [comment]
![Image](https://github.com/enso-org/enso/assets/4699705/415cf114-a4f4-4ecc-b5ac-5954502984c7)

Can we ensure brightness is aligned with the design as well.
