### ISSUE TITLE
Update look of the breadcrumbs panel

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7200]
The current top bar should look like in the new design, except we should not add new icons:

![image](https://github.com/enso-org/enso/assets/3919101/dfb9e97a-1538-46ab-8d19-6b60431e8761)

The project name will no longer be considered a "main" crumb. 

Currently, various top-bar elements are spread across different components. Refactoring is not required by this task, but may be considered if it would make the task easier. In that case, using autolayouts should also be considered.

**Comment by wdanilo** [comment]
Also, changing the name should not be possible from within the GUI, only from within the dashboard. Writing that just as additional info.
