### ISSUE TITLE
Style leakage in `histogram.js` and `scatterPlot.js`

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#7210]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

`button:hover` styles are not scoped to the visualization, so it is affecting dashboard appearance.

### Expected behaviour

`button:hover` is only applies to the specific visualization

### How we can reproduce it?

1. Open a project with either the "histogram" or "scatterPlot" visualizations. The "KMeans" template is one such project.
2. Go back to Dashboard
3. Hover over any button (most interactable elements are buttons)

### Enso Version

b243a5f

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Windows 11 21H2 (OS Build 22000.1936)

**Comment by somebody1234** [comment]
after testing: i no longer observe this issue (and can still repro on develop). however, on both `develop` and here i am getting errors when trying to open the visualizations ("method not found" for `executionContext/attachVisualization`)

**Comment by farmaazon** [comment]
> after testing: i no longer observe this issue (and can still repro on develop). however, on both `develop` and here i am getting errors when trying to open the visualizations ("method not found" for `executionContext/attachVisualization`)

Method not found means the visualization wasn't successfully attached, so probably we just don't put styles there (as we get no data). Probably your engine is too old, as #7124 introduced breaking changes.

**Comment by somebody1234** [comment]
yeah, seems like clearing `enso-ci` fixed it. can repro on `develop` again, *and* vis is working now, will test on fixed branch very soon

**Comment by somebody1234** [comment]
correction: it worked exactly once :(
(edit: tested. for posterity it is because i was using `--backend-release latest` instead of `--backend-release nightly` in `./run ide watch`)
