### ISSUE TITLE
Adopt Truffle DSL Node Object Inlining

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#7214]
GraalVM 17.0.7 (23.0.0 JDK17) introduces [DSL Node Object Inlining](https://github.com/oracle/graal/blob/master/truffle/docs/DSLNodeObjectInlining.md) which introduces a new set of Truffle annotations to make nodes inlined into their parents and therefore, have substantially lower memory footprint. The inlined and non-inlined nodes can co-exist; therefore, the migration can be iterative. Moreover, the truffle DSL processor now emits many [useful warnings](https://github.com/oracle/graal/blob/master/truffle/docs/DSLWarnings.md) that suggest where the usage of such inlining could be useful.

This is a follow-up issue of #5300.

- Update Graal PR - #7176

```[tasklist]
### Tasks
- [ ] Turn on warnings - revert https://github.com/enso-org/enso/pull/7176/commits/24ea89dd875aaea86f54860893bb63207d3c4d3f
```

**Comment by jdunkerley** [comment]
@JaroslavTulach and @Akirathan to discuss how this ticket should progress

**Comment by JaroslavTulach** [comment]
I guess we do it on case by case basis.
