### ISSUE TITLE
MacOS Enso needs top foreground to run a project

### ISSUE THREAD

**Issue by PabloBuchu** [enso-org/enso#7216]
Enso doesn't continue opening project flow if I switch with `cmd+tab` to some other program (e.x. terminal or browser). Not sure for how long it works that way.

Steps to reproduce:
1. Open Enso
2. Click local project to run
3. Immediately hit `cmd` + `tab` to some other window (browser or terminal)
4. Proces pauses at 
```
[info] [2023-07-05T13:01:57.598Z] [org.enso.projectmanager.infrastructure.languageserver.LanguageServerBootLoader] Language server booted [LanguageServerConnectionInfo(127.0.0.1,54546,62744)].
```
5. Switch back after e.x 1 minute to Enso
6. Process resumes initialisation

https://github.com/enso-org/enso/assets/2855109/6983b901-c50a-4618-9812-ec0c28603e75

**Comment by PabloBuchu** [comment]
@xvcgreg tested on windows, seems fine

Uploading 2307051452_shareX.mp4…

**Comment by PabloBuchu** [comment]
@somebody1234 it looks like project manager related, but can you check whether maybe we pause communication from react with PM? I am also having an impression that when you do that with cloud project it won't switch to workspace when running in background

[edit] yeah for clouds it also won't switch to workspace in the background..

@mwu-tow would you be able to help here? maybe its hardware configuration?

[edit2] it is I guess related to js. workspace (drawing nodes and colouring) will also be paused when you switch

**Comment by mwu-tow** [comment]
@PabloBuchu I believe it is the browser throttling the JS when it is not in the view.
https://github.com/electron/electron/issues/9567 might be relevant.

**Comment by PabloBuchu** [comment]
@mwu-tow that did the trick

in `app/lib/client/src/config.ts:155` we have this option `backgroundThrottling` it set by default to `true` meaning the Enso works like above. Shouldn't we set it by false or at least for nightly builds? @wdanilo @sylwiabr @xvcgreg

**Comment by wdanilo** [comment]
@PabloBuchu we should set it to "false" by default in all builds IMO.

**Comment by PabloBuchu** [comment]
https://github.com/enso-org/enso/pull/7319
