### ISSUE TITLE
`enso-project` is not opening properly

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7218]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When trying to open `.enso-project` the project is unpacked to `~/enso` directory, appears on the project list but doesn't run automatically. Happens on MacOS and Windows.

### Expected behaviour

The project should be run automatically.

### Enso Version

nightly 05.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by hubertp** [comment]
@sylwiabr do you have a sample `.enso-project` you tried?

**Comment by vitvakatu** [comment]
@mwu-tow I don't see mentioning of opening `.enso-project`s in PR description https://github.com/enso-org/enso/pull/6077, did it even work before?

**Comment by mwu-tow** [comment]
@vitvakatu 
> @mwu-tow I don't see mentioning of opening .enso-projects in PR description https://github.com/enso-org/enso/pull/6077, did it even work before?

IIRC it should have been working.

I can investigate/fix this.
