### ISSUE TITLE
Long name of the project is causing the play button to shrink and eventually disappear

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7219]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![image](https://github.com/enso-org/enso/assets/12892578/441e473c-ab3c-483f-a031-d0d129d98648)
![image](https://github.com/enso-org/enso/assets/12892578/f98c3706-296b-4e59-a3eb-530e91cebe25)

### Expected behaviour

Play button should be always visible and should not change the size

### Enso Version

Nightly 05.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by jdunkerley** [comment]
This has been resolved.
