### ISSUE TITLE
It seems to be harder to find the + in Vector Editor

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7227]
https://github.com/enso-org/enso/assets/1436948/7d442b36-e014-483b-af7a-9803b273858b

It may be a subjective feeling, but I remember that finding the spot where I need to hover my mouse to get a + in the vector editor used to be much easier, now I really need to carefully place the mouse and the place is in a position that is not intuitive (it's not the edge of the `]` but a bit to the left, the end of the last entry).

I'm not sure if anything has changed or if is it just me, but I remember having less trouble with it in the past.

Also, there's always been the issue that for a new user - I'd have no idea that I need to hover over some specific place to get the plus icon - IMO the plus icon should be displayed always or at least appear whenever the node is focused - but not require finding a magic place that you need to know about.

**Comment by vitvakatu** [comment]
This will be probably improved with the new node design, so I'm not sure we should investigate it right now even if it is a regression. @Frizi do you agree?

**Comment by vitvakatu** [comment]
Let's revise this problem when a new design comes. Closing for now.
