### ISSUE TITLE
Table type checks now allow Mixed columns if all values satisfy a more precise type, but the Storage vectorized operations are not prepared for it

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7231]
Since adding 'precise type detection' for Mixed columns in #6973, we are able to accept a Mixed type column wherever a column with more precise type is needed (e.g. a numeric column).

Unfortunately, our internal architecture is mostly not ready for this.

```python
from Standard.Base import all
from Standard.Table import all

main =
    t0 = Table.new [["X", ["a", 1, 2]], ["Y", [4, 5, 6]], ["Z", [7, 8, 9]]]
    t = t0.drop 1 . cast "Z" Value_Type.Mixed
    x = t.at "X"
    y = t.at "Y"
    z = t.at "Z"

    IO.println ("X: " + x.value_type.to_text + " / " + x.inferred_precise_value_type.to_text)
    IO.println ("Y: " + y.value_type.to_text)
    IO.println ("Z: " + z.value_type.to_text + " / " + z.inferred_precise_value_type.to_text)

    # This miraculously works, because MixedStorageFacade delegates to the underlying LongStorage - not sure if that is correct.
    IO.println <| Panic.recover Any (z+y)

    # This fails because ObjectStorage does not have vectorized `+`.
    IO.println <| Panic.recover Any (x+y)

    # This will fail with an internal type error - LongNumericOp is only taught to handle LongStorage and DoubleStorage.
    IO.println <| Panic.recover Any (y+x)
    IO.println <| Panic.recover Any (y+z)
```
prints
```
(In-Memory Column [Z] + [Y])
(Error: java.lang.IllegalArgumentException: The operation + has no vectorized implementation for this storage type, but no fallback function was provided. This is a bug in the Table library.)
(Error: org.enso.table.error.UnexpectedTypeException: Unexpected value type. Expected a Number..)
(Error: org.enso.table.error.UnexpectedTypeException: Unexpected value type. Expected a Number..)
```
exposing internal errors to the user.

In the past, all of these operations would fail with `Invalid_Value_Type`. The new approach is more lenient - we indeed want these mixed columns to 'pretend' they have this more specific type. To do so, we need to adapt our architecture accordingly.

So the expected behaviour is that all 4 of these operations should return a new numeric column, without errors.

**Comment by radeusgd** [comment]
There are 2 ways to approach this:
1. Adapt the storages to accept a Mixed storage everywhere. It can then assume all values in Mixed storage are of correct type and safely cast them (if they were of other type, `inferred_precise_value_type` would not yield the specific type).
2. Somehow auto-cast these columns before running the operation.

The drawback of (1) is that if the LHS of an operation is a Mixed type, since an ObjectStorage cannot (and should not, for a decent design IMO) have operations on _all_ types imaginable, this will fall-back to the in-Enso fallback function which is slower.

(2) would need to be implemented carefully, as we do not complicate all operations too much - we probably would need to create some common logic in the `run_vectorized_binary_op` so that it can easily be re-used. We can there check if the precise type was inferred (by adding a special flag to the storage) and if yes, if it matches the value type - if the precise type does not match - we would cast the column to the precise type before actually requesting the vectorized operation.

IMO (2) seems like a better choice here.

**Comment by GregoryTravis** [comment]
Why do these fail?

```
    IO.println <| Panic.recover Any (y+x)
    IO.println <| Panic.recover Any (y+z)
```

After casting Z to mixed, are the X and Y columns also cast to mixed? Or are they still numeric?

**Comment by radeusgd** [comment]
> Why do these fail?
> 
> ```
>     IO.println <| Panic.recover Any (y+x)
>     IO.println <| Panic.recover Any (y+z)
> ```
> 
> After casting Z to mixed, are the X and Y columns also cast to mixed? Or are they still numeric?

1. `X` has Mixed type to begin with (as it started from being `["a", 1, 2]` - mixing Text and numbers). `drop`ping values does not automatically cause the column to 'retype' itself. That would be costly and also mostly unexpected. So `y+x` fails, as I described, because the `LongStorage` of `y` which handles the vectorized `+` is not adapted to handle a mixed storage - it only expects numeric storages.
2. `y+z` fails for the same reason as above, just the mixed storage is a `MixedStorageFacade` and not `ObjectStorage` - but it still does not satisfy a check `instanceof (LongStorage | DoubleStorage)` which is done in `LongNumericOp`s.
