### ISSUE TITLE
PanicSentinel value isn't propagated via Vector & co.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7245]
![image](https://github.com/enso-org/enso/assets/4699705/ba76438a-0f7c-4721-8dab-e5279c1a32a7)

If the user enters some invalid code within a Vector, this results in only an "Execution failed" and no way to find the error.

**Comment by JaroslavTulach** [comment]
When I have `t.enso` file with:
```ruby
from Standard.Base import all

main = [1, 2, 3, Decimal.nan ]
```
I can run it and see reasonable error:
```bash
sbt:enso> runEngineDistribution --run t.enso
Execution finished with an error: Method `nan` of type Decimal.type could not be found.
        at <enso> t.main(t.enso:3:18-28)
```
e.g. from a CLI perspective things are looking fine.

**Comment by JaroslavTulach** [comment]
The IDE converts the execution error cause by `Decimal.nan` into [PanicSentinel](https://github.com/enso-org/enso/blob/381081e9032449f88d6261e99b4326a078d0d2ff/engine/runtime/src/main/java/org/enso/interpreter/runtime/error/PanicSentinel.java#L12) according to its documentation:

> This tracing is enabled by the active intervention of the runtime instrumentation, and does
> not function in textual mode.

This tracing isn't going to happen in the CLI - only [IdExecutionInstrument does the conversion](https://github.com/enso-org/enso/blob/381081e9032449f88d6261e99b4326a078d0d2ff/engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java#L247).

However `PanicSentinel` isn't a warning - e.g. it doesn't get propagated further...

**Comment by JaroslavTulach** [comment]
What is the desired behavior? Shall we treat `PanicSentinel` as a `Warning` and propagate it like that? I can easily achieve

![treat PanicSentinel as warning](https://github.com/enso-org/enso/assets/26887752/f18b692a-d02a-413e-92a2-a896620b7cd8)

with following few lines change:
```diff
diff --git engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
index c868592d51..a710420955 100644
--- engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
+++ engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/IdExecutionInstrument.java
@@ -244,7 +248,10 @@ public class IdExecutionInstrument extends TruffleInstrument implements IdExecut
       if (exception instanceof TailCallException) {
         onTailCallReturn(exception, Function.ArgumentsHelper.getState(frame.getArguments()));
       } else if (exception instanceof PanicException panicException) {
-        onReturnValue(frame, new PanicSentinel(panicException, context.getInstrumentedNode()));
+        var ctx = EnsoContext.get(context.getInstrumentedNode());
+        var sentinel = new PanicSentinel(panicException, context.getInstrumentedNode());
+        var warning = Warning.create(ctx, panicException.getMessage(), context.getInstrumentedNode());
+        onReturnValue(frame, WithWarnings.appendTo(ctx, sentinel, warning));
       } else if (exception instanceof AbstractTruffleException) {
         onReturnValue(frame, exception);
       }
```
Would you consider that a fix, @jdunkerley? Probably not as I now can see that I changed the **red border** to **orange one**. If that is a problem (which I expect), then we need something slightly better:
- duplicate the treatment of `WithWarnings` everywhere to also deal with `PanicSentinel`
- also check the `payload` of `WithWarnings` in the _language server_ and send message that will **red border** the nodes

CCing @4e6

**Comment by JaroslavTulach** [comment]
The #7385 pull request shows a _conservative approach_ that _just_ turns `PanicSentinel` into an object that has `WarningsLibrary.hasWarnings(...)`. The more radical change is shown at [jtulach/NoPanicSentinel branch](https://github.com/JaroslavTulach/enso/commit/de92153368e4c0d65235a9ca5d9c4ee055001565) - it removes `PanicSentinel` altogether - but then we'd have to fix a lot of `Runtime*Test`s. CCing @4e6. A sample difference for example is:
```
List(Response(Some(0823c808-30ab-44bd-9e80-3c0cf7f32166), PushContextResponse(55b911ed-f384-460a-9410-da16d121085b)), Response(None, ExecutionUpdate(55b911ed-f384-460a-9410-da16d121085b, List(Diagnostic(Error, Some("The name `undefined` could not be found."), Some(/tmp/enso-test-packages2956044925097422099/src/Main.enso), Some(Range(Position(2, 8), Position(2, 17))), Some(c75803f2-3fb3-426f-bb8a-c7bbec6cae3a), Vector())))), Response(None, ExpressionUpdates(55b911ed-f384-460a-9410-da16d121085b, Set(ExpressionUpdate(c75803f2-3fb3-426f-bb8a-c7bbec6cae3a, Some("Standard.Builtins.Main.Panic"), None, Vector(ExecutionTime(0)), false, true, Panic("Compile_Error.Error", List(c75803f2-3fb3-426f-bb8a-c7bbec6cae3a)))))), Response(None, ExecutionFailed(55b911ed-f384-460a-9410-da16d121085b, Diagnostic(Error, Some("Compile_Error.Error"), Some(/tmp/enso-test-packages2956044925097422099/src/Main.enso), Some(Range(Position(2, 8), Position(2, 17))), Some(c75803f2-3fb3-426f-bb8a-c7bbec6cae3a), Vector(StackTraceElement("Main.main", Some(/tmp/enso-test-packages2956044925097422099/src/Main.enso), Some(Range(Position(2, 8), Position(2, 17))), Some(c75803f2-3fb3-426f-bb8a-c7bbec6cae3a)))))), Response(None, BackgroundJobsStartedNotification()), Response(None, BackgroundJobsStartedNotification())) 



did not contain the same elements as 


List(Response(None, BackgroundJobsStartedNotification()), Response(Some(0823c808-30ab-44bd-9e80-3c0cf7f32166), PushContextResponse(55b911ed-f384-460a-9410-da16d121085b)), Response(None, ExecutionUpdate(55b911ed-f384-460a-9410-da16d121085b, List(Diagnostic(Error, Some("The name `undefined` could not be found."), Some(/tmp/enso-test-packages2956044925097422099/src/Main.enso), Some(Range(Position(2, 8), Position(2, 17))), Some(c75803f2-3fb3-426f-bb8a-c7bbec6cae3a), Vector())))), Response(None, ExpressionUpdates(55b911ed-f384-460a-9410-da16d121085b, Set(ExpressionUpdate(c75803f2-3fb3-426f-bb8a-c7bbec6cae3a, Some("Standard.Builtins.Main.Panic"), None, Vector(ExecutionTime(0)), false, true, Panic("Compile_Error.Error", List(c75803f2-3fb3-426f-bb8a-c7bbec6cae3a)))))), Response(None, ExpressionUpdates(55b911ed-f384-460a-9410-da16d121085b, Set(ExpressionUpdate(11ba8aab-a7fd-4160-bf93-35c836273df9, Some("Standard.Builtins.Main.Panic"), None, Vector(ExecutionTime(0)), false, true, Panic("Compile_Error.Error", List(c75803f2-3fb3-426f-bb8a-c7bbec6cae3a)))))), Response(None, ExpressionUpdates(55b911ed-f384-460a-9410-da16d121085b, Set(ExpressionUpdate(115feac2-51fc-4191-8393-ea75a0f5e80b, Some("Standard.Builtins.Main.Panic"), None, Vector(ExecutionTime(0)), false, true, Panic("Compile_Error.Error", List(c75803f2-3fb3-426f-bb8a-c7bbec6cae3a)))))), Response(None, ExecutionComplete(55b911ed-f384-460a-9410-da16d121085b))) (RuntimeErrorsTest.scala:161)
```
e.g. we are not getting `ExecutionFailed`, but rather `ExpressionUpdates` because [the commit](https://github.com/JaroslavTulach/enso/commit/de92153368e4c0d65235a9ca5d9c4ee055001565) removes many places where `PanicSentinel` gets `thrown` during a method invocation.
