### ISSUE TITLE
Can't create a node from an output port when clicking too fast

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#7251]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Creating a node by clicking on the output port and then clicking on the background doesn't work if the two clicks occur too close together in time (below our double-click threshold); the second click just drops the edge.

### Expected behaviour

Clicking on the output port and then clicking on the background should create a node no matter how fast you do it.

### How we can reproduce it?

1. Clicking on an output port.
2. Click on the background within 300ms of (1).

### Enso Version

develop (72ec775d8c)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by farmaazon** [comment]
Perhaps we should not treat two clicks as DoubleClick if the mouse significantly moved between them.

**Comment by kazcw** [comment]
It seems to me that specifically if the second click is over a different target, we should not treat that as a DoubleClick.

**Comment by farmaazon** [comment]
No longer reproducible in GUI2. There we track double clicks on a single HTML element.
