### ISSUE TITLE
`Nothing` is offered as an option for `new_name` in `Aggregate_Column.Group_By`, if selected the value is an error

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#7252]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When using the `Aggregate_Column.Group_By` constructor, a dropdown for the `new_name` field shows one option: `Nothing`. Selecting this value makes the expression produce an error.

### Expected behaviour

`Nothing` should not be offered as an option for `new_name`.

### How we can reproduce it?

Create a node containing the expression `Aggregate_Column.group_by`.

### Screenshots or screencasts

![image](https://github.com/enso-org/enso/assets/1047859/fc34631e-254f-4f40-9415-26553ee06bc7)

### Enso Version

develop (72ec775d8c)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by jdunkerley** [comment]
Closed by #7243 .
