### ISSUE TITLE
Replace custom Logger with slf4j's SocketAppenders and a single logging server

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7253]
We currently have a [custom logger implementation](https://github.com/enso-org/enso/tree/develop/lib/scala/logging-service) that is being used in every backend service. The primarily reason for that was that we could collect all logs into a single file.
While the service has worked without any problems, further maintenance and adding new features will be problematic.

1. We would like that add rolling log files, so that customers/cloud do not experience the "out of disk space" problems. Since we have a custom logger implementation, we would have to use something custom as well, rather than off-the-shelf, which is an unnecessary burden.
2. Profiling the startup of Enso reveals that all those individual logging threads created for every sub-service can affect resource usage. Using off-the-shelf appenders, that have been typically optimized, could reduce the problem.
3. Less code to maintain = profit.

**Comment by Akirathan** [comment]
Another advantage of using an *off-the-shelf* logging library is that the logs have, by default, some *standard* format which is recognizable by most of the log-viewer software, like [lnav](https://lnav.org/) for example. Currently, our log files do not have such *standard* format, we always have to investigate the logs as text-only files.

**Comment by hubertp** [comment]
One thing to note:
```
14:08:53.734 [job-pool-1] DEBUG org.enso.interpreter.runtime.DefaultPackageRepository -- Resolving component groups of package [New_Project_16].
14:08:53.891 [job-pool-1] INFO org.enso.interpreter.runtime.DefaultPackageRepository -- Found library Standard.Base @ 0.0.0-dev at [***/0.0.0-dev].
```
and
```
14:08:52.289 [scala-execution-context-global-31] DEBUG org.enso.distribution.DistributionManager -- Detected paths: DistributionPaths(
  dataRoot = ***/enso,
  runtimes = ***/runtime,
  engines  = ***/dist,
  bundle   = None,
  config   = ***/enso,
  locks    = ***/lock,
  logs     = ***/log,
  tmp      = ***/tmp,
  ensoHome = ***/enso,
  customEditions = ArraySeq(***/editions),
  localLibrariesSearchpaths = ArraySeq(***/libraries)
)
14:08:52.302 [scala-execution-context-global-31] DEBUG org.enso.distribution.config.GlobalConfigurationManager -- Global config [/home/hubert/.config/enso/global-config.yaml] not found, falling back to defaults.
```
I thought I broke that with my change but those are coming from the nightly. Notice how they do not respect the format of other logs because they are clearly formatted by the default non-enso loggers. 

This is because those messages are logged **before** logs are setup correctly.

**Comment by JaroslavTulach** [comment]
> they do not respect the format .... those messages are logged before logs are setup correctly.

Usual problem of having uninitialized objects in the system - they are [pathological liars](http://wiki.apidesign.org/wiki/Singleton#Singletons_are_Pathological_Liars.5B3.5D).

[LogManager](https://docs.oracle.com/javase/8/docs/api/java/util/logging/LogManager.html) offers some properties to allow one to configure everything before first `LogRecord` is published. Just make sure `java.util.logging.config.class` points to the class that configures all the log handlers...

**Comment by hubertp** [comment]
It's not so easy in this case, I'm afraid. That class discovers the root where the log files should be placed (dependent on the distribution) so it's a catch-22.
