### ISSUE TITLE
IDE does not recreate WebGL context after waking up from hibernation

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7255]
Once #7254 lands it will reveal a problem at the IDE related to waking up from hibernation issues (#5197):
![Screenshot from 2023-07-10 12-34-45](https://github.com/enso-org/enso/assets/292128/2b70383c-7fb2-4ad4-bb2a-bc3949a7d328)

After confirming with @wdanilo it seems like that functionality is missing in the current implementation even though there are some [stubs](https://github.com/enso-org/enso/blob/develop/lib/rust/ensogl/core/src/system/gpu/context.rs#L98) present.
Restoring the context also [does not appear](https://github.com/enso-org/enso/blob/develop/lib/rust/ensogl/core/src/system/gpu/context.rs#L49) to be a trivial change but still it is necessary. Without it the project view goes blank a few seconds after waking up from hibernation.

**Comment by farmaazon** [comment]
"Lost connection" messages also seem worrying. We have an epic to track the general idea of reconnecting with the engine: #5202. Or just restart the entire project, which is far from ideal.

@hubertp Am I right that those "lost connection" messages would make Language Server process finished and project closed?

**Comment by hubertp** [comment]
@farmaazon not with https://github.com/enso-org/enso/pull/7254 PR. It actually seems to re-connect just fine then. Without this PR LS will shutdown and IDE will try (not sure how many times) to reconnect but fail and you will see plenty of errors in the logs about lost connection. 
I think this temporary "lost connection" appears to be _fine_ and a consequence of waking up from hibernation. 

Also, if LS shutsdown and then someone starts LS for the same project it will very likely open on a different port, making the re-connection useless anyway.
