### ISSUE TITLE
Visualization for dataflow error appears in wrong position and occludes the node

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7256]
![image](https://github.com/enso-org/enso/assets/1436948/a2b767cc-44f5-48e0-9ca3-ea176528a6d7)

Repro: type `Error.throw 42` and hover over the output port to see the visualization.

It does not appear below the node, but shifted up, occluding the contents of the node itself.

Even worse, it also happens when the preview is an error when editing the node:
![image](https://github.com/enso-org/enso/assets/1436948/e23b28b0-f434-4e4f-86bb-0e024936e4ac)

This way, I cannot see big part of the text that I'm editing, so I cannot fix the error that is in there because I do not know where is my cursor and what I'm typing.

**Comment by radeusgd** [comment]
![image](https://github.com/enso-org/enso/assets/1436948/1d29078b-eb24-4bde-9a76-4b740b26ddd2)
The error visualization also does not resize with the node like the 'normal' visualizations.

**Comment by vitvakatu** [comment]
Introduced by resizable visualizations, I will fix it.
