### ISSUE TITLE
Connection to the lambdas are appearing on the left side on the node

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7261]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

K-means example from the template
<img width="778" alt="image" src="https://github.com/enso-org/enso/assets/12892578/1d76eb38-a541-4ac9-b4b7-22e6a6d72a91">

### Expected behaviour

We are not going to support the connections inside lambdas at this point.

### Enso Version

nightly 11.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
I guess the @Frizi connection fixes caused it. Before, those connections were just not displayed at all.

I think that until we do not make a work of removing span tree and implementing widgets for lambdas (tracked in #6834), we should not display them. What do you think @Frizi?

**Comment by 4e6** [comment]
ping @Frizi
