### ISSUE TITLE
The output port type is not visible

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7262]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When opening existing project or creating project from template the output ports for existing nodes does not have types displayed. The types are displayed for newly created nodes.

### Expected behaviour

Output ports types should be displayed of all nodes.

### Enso Version

nightly 11.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
Isn't it a duplicate of #6994? @sylwiabr what if you open and close visualization on the node where type does not appear?

**Comment by sylwiabr** [comment]
You are right, I couldn't find the original issue so I opened the new one.
