### ISSUE TITLE
Mouse wheel scrolling does not work inside of JSON visualization (default vis for Plain Text)

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7265]
Repro:
1. Create node with a lot of text, e.g. load a HTML file
2. Open the visualization
3. Try scrolling using the mouse wheel

![image](https://github.com/enso-org/enso/assets/1436948/1770299a-67ce-4ae3-bede-1d3891306c24)

It does not work for me, at least on Windows 11.

Scrolling with the scroll bar works fine - but it is hard to be precise when the amount of text is large and it's just annoying that one cannot use the mouse wheel.

**Comment by 4e6** [comment]
Current d8d467f62be1c990ecf180da1ac20228c07916e1 behavior on Linux:
- :heavy_multiplication_x:  after opening the visualization (pressing space bar). The scroll moves both the visualization and the scene
- :heavy_check_mark:  when the visualization window is selected, the scroll moves the visualization correctly
- :heavy_check_mark: when the visualization window is deselected, the scroll moves the scene and not visualization

https://github.com/enso-org/enso/assets/357683/e5171e94-7ad7-4296-9978-5bcaa1a8eb05

**Comment by farmaazon** [comment]
The @4e6 comment is about table visualization, not JSON. I'd say it's WAD behavior, as visualizations should react to events only when selected (with blue border).

Regarding original issue: The current text visualization use EnsoGL scrollbars, and those do not support wheel by default, we have to implement it.

**Comment by somebody1234** [comment]
I think this is no longer an issue in gui2? gui2 should be using native scroll focus, which defaults to whichever container is currently being hovered over. @farmaazon can you confirm whether the problem still exists?

**Comment by farmaazon** [comment]
Yes, it works in the new GUI.
