### ISSUE TITLE
Wrong type in `Text.parse_to_table` causes whole engine to fail execution instead of just throwing an error

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7266]
## Repro

Create the following workflow:
![image](https://github.com/enso-org/enso/assets/1436948/4c2670b6-cdcd-4f0b-854e-5676bd41cf92)

Essentially - instead of providing a raw `Text` value to `parse_to_table`, I provide an already compiled regex.

## Actual behaviour

In the logs I get:
```
[warn] [2023-07-11T17:42:07.3Z] [enso] Execution of function main failed (Unexpected values provided for RegexCompileNodeGen@1e9b2bb: [Value false TRegexObject{source=/(\w+),(\w+)/usg}, usg], [Layout_Atom_0_2,Text]).
```

and the engine is 'hung' - no further computations are going to succeed, until the problematic node is modified/deleted

![image](https://github.com/enso-org/enso/assets/1436948/37a475aa-2efe-437b-a536-b180092504fe)

Another repro shows instead of passing the `Regex`, passing some other unexpected value, like an Integer:
![image](https://github.com/enso-org/enso/assets/1436948/0926aae7-16b4-463d-9f2a-53cab3c5352b)

## Expected behaviour

1. I think the `parse_to_table` should actually accept a compiled `Regex` value (so the input type should be `Text | Regex`).
2. Even if the `parse_to_table` method gets a wrong type (e.g. Integer), it should not break the whole engine, it should just report a panic/dataflow error.

**Comment by radeusgd** [comment]
We can easily fix this by adding a typecheck in the arguments of `parse_to_table`. Ideally I think we should adapt the operation to also accept `Regex`.

But this also shows a deeper issue - a type error in some of the builtins seems to be able to trip the whole engine. That seems rather drastic. It could be valuable to investigate if we can also add a more 'general' solution so that in the future such type errors only result in some kind of, possibly even internal, but a Panic not a whole engine failure.

(Regardless of the more generic fix, we should add a typecheck to `parse_to_table` just to get nice error messages for the user)

**Comment by hubertp** [comment]
> But this also shows a deeper issue - a type error in some of the builtins seems to be able to trip the whole engine. That seems rather drastic. It could be valuable to investigate if we can also add a more 'general' solution so that in the future such type errors only result in some kind of, possibly even internal, but a Panic not a whole engine failure.

The statements are executed in sequence so when you have something like
```
    op1 = exp1
    op2 = exp2
```
and `exp1` throws a `Panic` then the engine will simply not evaluate `op2`. So everything works as expected and the engine correctly does not proceed with the evaluation. So type errors would have to become dataflow errors if you want it to continue executing.

**Comment by radeusgd** [comment]
> > But this also shows a deeper issue - a type error in some of the builtins seems to be able to trip the whole engine. That seems rather drastic. It could be valuable to investigate if we can also add a more 'general' solution so that in the future such type errors only result in some kind of, possibly even internal, but a Panic not a whole engine failure.
> 
> The statements are executed in sequence so when you have something like
> 
> ```
>     op1 = exp1
>     op2 = exp2
> ```
> 
> and `exp1` throws a `Panic` then the engine will simply not evaluate `op2`. So everything works as expected and the engine correctly does not proceed with the evaluation. So type errors would have to become dataflow errors if you want it to continue executing.

No, that is not true at all in the IDE.

What you are saying is correct when executing in batch mode, or for how a non-inspected function is executed.

However, when we are actually interactively executing a function (like `main`) in the IDE view, the panics do not stop execution of other nodes.

Here you can see on the video that I've thrown some Panics and I can happily continue executing other stuff. Note how this other stuff is added _below_ the panics in the code view.

https://github.com/enso-org/enso/assets/1436948/ed08cf68-34f1-4cee-8833-2d947b69b95c

I think this is handled with the `PanicSentinel`s?

**Comment by radeusgd** [comment]
So now as we can see - regular well behaved panics work fine and do not break execution in the IDE.

But there are some kinds of errors - like the one encountered here - that do break it. I suspect it is Exceptions that are leaking from the interpreter which are not wrapped into panics anywhere. Then the `PanicSentinel` instrumentation mechanism cannot correctly interject them and thus it causes the whole engine to 'stall'. I think we need to ensure that no such compiler errors (unless fatal) leak the interpreter and instead ensure that they are always wrapped in Panics so that the IDE can handle them.

**Comment by jdunkerley** [comment]
@JaroslavTulach could you check into this please.

I'll look at the library side and ensure if passed a Regex it works correctly, but can you check the runtime panic issue Radek described.

**Comment by jdunkerley** [comment]
If you pass a built-in an invalid type it appears properly handled.
![image](https://github.com/enso-org/enso/assets/4699705/7d0c2519-ee22-46d3-ab3f-ee3f4c364af0)

It is a problem in the `Prim_Text_Helper.compile_regex`, calling that seems to be cause.
```
Execution of function main failed (Unexpected values provided for RegexCompileNodeGen@40bfd6bf: [1, i], [Long,Text]).
```

It is lacking a `@Fallback` to handle the mismatched type cases. 

We need to verify all builtins get a fallback I guess.

**Comment by jdunkerley** [comment]
@GregoryTravis can you add an `@Fallback` to fix this.

**Comment by radeusgd** [comment]
> It is lacking a `@Fallback` to handle the mismatched type cases.
> 
> We need to verify all builtins get a fallback I guess.

I assume that if a fallback is missing, we get some Truffle exception being thrown. @JaroslavTulach / @hubertp do you think catch it somewhere upwards in the interpreter so that even if some node is missing a Fallback, we would still get a panic at the surface instead of this 'internal' error?

**Comment by jdunkerley** [comment]
Two tickets to close this:
- #7287 
- parse_to_table should accept a Regex.
