### ISSUE TITLE
Unclosed text literal issues no syntax error

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7279]
```
from Standard.Base import all

main =
    x = "a
    y = "b

    IO.println x
    IO.println y
    IO.println "z
    IO.println "w
```
The code above is happily accepted by the compiler without any errors or warnings and prints
```
a
b
z
w
```

![image](https://github.com/enso-org/enso/assets/1436948/7aa1745c-5a59-44b1-bb4c-9330a3dd3eac)

I'm wondering if this is an intended behaviour? I assume it could be useful in the IDE to display a preview while the user is still typing the literal.

If that is intended, then it would be good if we could update the rules for syntax highlighting that we use, because it breaks when encountering such literals:
![image](https://github.com/enso-org/enso/assets/1436948/846986db-b799-46ae-b3ee-fd7cda72edc6)

**Comment by radeusgd** [comment]
I tried to record a video showing the preview in the IDE displaying a Text even when trailing `"` is missing, but I could not due to another issue #7280.

**Comment by JaroslavTulach** [comment]
I am getting valid `TextLiteral` from the Rust parser. Is that correct, @kazcw?

**Comment by JaroslavTulach** [comment]
My test in Java:
```diff
enso$ git diff
diff --git engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java
index d4c0fc2300..3c5e0b35c0 100644
--- engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java
+++ engine/runtime/src/test/java/org/enso/compiler/ErrorCompilerTest.java
@@ -19,6 +18,14 @@ import scala.collection.immutable.List;
 
 public class ErrorCompilerTest extends CompilerTest {
 
+  @Test
+  public void unfinishedLiteral() throws Exception {
+    var ir = parse("""
+    foo = "unfinished literal...
+    """);
+    assertSingleSyntaxError(ir, IR$Error$Syntax$UnexpectedExpression$.MODULE$, "Unexpected expression", 6, 8);
+  }
+
   @Test
   public void spaceRequired() throws Exception {
     var ir = parse("foo = if cond.x else.y");
```
fails, because there is no error in the unfinished literal.

**Comment by JaroslavTulach** [comment]
With #7340 I get following error when running [the program](https://github.com/enso-org/enso/issues/7279#issue-1802625924) that started this issue:
```bash
/tmp/t.enso:4:9: error: Unclosed text literal.
    4 |     x = "a
      |         ^~
/tmp/t.enso:5:9: error: Unclosed text literal.
    5 |     y = "b
      |         ^~
/tmp/t.enso:9:16: error: Unclosed text literal.
    9 |     IO.println "z
      |                ^~
/tmp/t.enso:10:16: error: Unclosed text literal.
   10 |     IO.println "w
      |                ^~
Aborting due to 4 errors and 0 warnings.
Execution finished with an error: Compilation aborted due to errors.
```
