### ISSUE TITLE
Union operation on shapes is not commutative

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7283]
Given the code:

```rust
pub mod local_scope(LocalScope) {
    ensogl_core::cached_shape! {
        size = (SIZE, SIZE);
        alignment = center;
        (style: Style) {
            let dull_alpha: Var<f32> = style.get_number(dull_color_alpha).into();
            let dull_color = &VIVID_COLOR * &dull_alpha;
            let dot = Circle(3.0.px());
            let dot = dot.fill(VIVID_COLOR.glsl());
            let outer = Circle(8.0.px()) - Circle(5.0.px());
            let outer = outer.fill(dull_color.glsl());
            let shape = outer + dot;
            let shape = shape.shrink(SHRINK_AMOUNT.px());
            shape.into()
        }
    }
}
```

It produces this image (middle shape):
<img width="135" alt="Screenshot 2023-07-13 at 13 53 22" src="https://github.com/enso-org/enso/assets/6566674/a8a061aa-fc1b-48f5-958e-bbb92b553207">

But swapping `outer` and `dot` on the line `let shape = outed + dot` produces a different image:

<img width="223" alt="Screenshot 2023-07-13 at 13 53 59" src="https://github.com/enso-org/enso/assets/6566674/404f13c3-64a8-4fe5-82e3-b0416ddfb6e1">

**Comment by farmaazon** [comment]
No longer relevant in GUI2
