### ISSUE TITLE
Type checks inconsistent when dealing with `a -> b` function types

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7289]
```python
from Standard.Base import all

t1 (f : Function) =
    f "x"

t2 (f : (Text -> Any)) =
    f "x"

t3 (f : (Integer | Function)) =
    f "x"

t4 (f : (Integer | (Text -> Any))) =
    f "x"

main =
    f x = "|" + x + "|"
    IO.println (t1 f)
    IO.println (t2 f)
    IO.println (t3 f)
    IO.println (t4 f)
```

Running the example above yields:
```
|x|
|x|
|x|
Execution finished with an error: Type error: expected `f` to be Integer, but got Function.
        at <enso> inconsistent-function-type.t4(inconsistent-function-type.enso:12-13)
        at <enso> inconsistent-function-type.main<arg-1>(inconsistent-function-type.enso:20:17-20)
        at <enso> inconsistent-function-type.main(inconsistent-function-type.enso:20:5-21)
```

Whereas we'd expect all 4 cases to behave the same way.

Weirdly, if the type is 'alone' - both `Function` and `Text -> Any` behave the same and accept a function input.

However, once we construct a sum type using `|`, for some weird reason the `Text -> Any` seems as if it disappears.

**Comment by JaroslavTulach** [comment]
> However, once we construct a sum type using |, for some weird reason the Text -> Any seems as if it disappears.

`Text->Any` actually disappears all the time. Just in case of `t4` the `Integer` is left in the check. While in case of `t2` there is no type check at all. Anyway #7298 fixes it all.
