### ISSUE TITLE
Undo-redo is not working properly when adding an element to the node with a list with connection

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7294]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Undoing the action of adding a new element to the vector takes 4 undo actions. Redo is not possible (never adds the new element).

### Expected behaviour

Undo should take one action and redo should be possible.

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/12892578/9a193b8e-c21d-4f41-9d31-27361f9a6f4f

### Enso Version

nightly 13.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by 4e6** [comment]
I was able to reproduce this issue on the current d8d467f62be1c990ecf180da1ac20228c07916e1 develop. 

Initial conditions. Start the project with empty `main` function.
```py
main = Nothing
```

In the video I'm pressing `ctrl + z` and the undo action does not go beyond the creation of `operator1` no matter how many times I press `ctrl + z`.

https://github.com/enso-org/enso/assets/357683/7a016059-fc09-439c-b4ef-a37fc8e3cf85

**Comment by farmaazon** [comment]
Closing, as we use different tool for undo redo in GUI2. Any issue with it should be reported as a new task.
