### ISSUE TITLE
Closing project before loading causes panic

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7301]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Initially reported by @PabloBuchu here: https://github.com/enso-org/enso/issues/7095#issuecomment-1630752082

https://github.com/enso-org/enso/assets/2855109/cac5e0aa-3f5f-4d71-a8c1-ea4f4dabfe43

### Expected behaviour

No errors in the console should happen.

### How we can reproduce it?

1. Open a project
2. Immediately switch to dashboard
3. Stop project by pressing "Stop" button near its name
4. Observe the panic in the console.

### Enso Version

e59513065da41258e642485dab023e5a5107ff98

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by PabloBuchu** [comment]
Whats the progress on this? I am asking cause after panicking in above case the project is left in corrupted state. In theory its closed but reopening is corrupted and closing throws another error:

<img width="537" alt="Screenshot 2023-07-28 at 10 59 17" src="https://github.com/enso-org/enso/assets/2855109/fc6a48ca-31c0-4bcc-9621-d1f905eda8f0">

**Comment by farmaazon** [comment]
I'm fixing it right now. But panics may always happen, and we want to have something to handle them anyway - see #7376
