### ISSUE TITLE
`.enso-project`s from the PM HTTP endpoint are missing the `.enso` directory

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#7303]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Projects downloaded via the PM HTTP endpoint are missing the `.enso` directory:
https://github.com/enso-org/enso/blob/e59513065da41258e642485dab023e5a5107ff98/lib/scala/pkg/src/main/java/org/enso/pkg/archive/TarArchiveBuildingFileVisitor.java#L85-L87

### Expected behaviour

`.enso` directory is in the final bundle

### Enso Version

866283

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by somebody1234** [comment]
the fix should be simple enough but the testcase will need to be updated too

**Comment by jdunkerley** [comment]
This is by design - we should not include the version history when we create a package for distribution.
Otherwise for example, a user might have removed a password before packaging and it could be recovered from the version history. 
Word/Excel used to have these histories and they were a nightmare.

**Comment by somebody1234** [comment]
@jdunkerley makes sense - however it's still true that the electron app is breaking, because `.enso/project.json` (which contains the uuid among other things) is missing. should that file perhaps just be regenerated from scratch instead?
