### ISSUE TITLE
Debug info left in the console

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7308]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

<img width="550" alt="image" src="https://github.com/enso-org/enso/assets/12892578/8eaa0f87-3633-4107-ad46-e8be3f003e24">

### Expected behaviour

Console without debug info

### Enso Version

nightly 17.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by 4e6** [comment]
@sylwiabr cannot reproduce on the current d8d467f62be1c990ecf180da1ac20228c07916e1 develop


https://github.com/enso-org/enso/assets/357683/680da5ac-4645-42d0-92dc-01e34b06da47

**Comment by sylwiabr** [comment]
appearing in nightly 20.07 - unfortunately nightly from 21 is not available for MacOS so will check on Monday

**Comment by hubertp** [comment]
That looks like a gui log anyway

**Comment by sylwiabr** [comment]
it doesn't appear anymore
