### ISSUE TITLE
CB opening in the middle of visualization

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7309]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

<img width="779" alt="image" src="https://github.com/enso-org/enso/assets/12892578/67162629-9318-48fa-9d07-51706f1f97b9">

### Expected behaviour

CB should be opened below the opened visualization.

### Enso Version

nightly 17.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by 4e6** [comment]
Can reproduce on the current d8d467f62be1c990ecf180da1ac20228c07916e1 develop

The new node is created on top of the visualization window.

https://github.com/enso-org/enso/assets/357683/165219f0-a423-42cb-93e7-3ed20db0d173
