### ISSUE TITLE
Unstable filtering

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7314]
The entries containing "ADVANCE" or "UNSTABLE" flag should not be displayed in CB by default, only when the "Unstable" button is toggled on (on the CB's top bar).

**Comment by kazcw** [comment]
@farmaazon Does this mean: If a Component has an `UNSTABLE` tag in its documentation, don't show it in the CB?

**Comment by farmaazon** [comment]
Sorry, I haven't realized the description is missing in this task.

Yes, it does, and a bit more, but now the description should say the full information.

**Comment by somebody1234** [comment]
I'm assuming this was implemented in GUI2 here:
- #7804
