### ISSUE TITLE
2 entries for the _same_ `Table.join` method appear in the component browser

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7318]
As can be seen on the video
https://github.com/enso-org/enso/assets/1436948/4eef89f9-6a81-4b7d-892d-af78bb87d83a

To reproduce - create a table, focus on it and press Tab, and type `join`.

![image](https://github.com/enso-org/enso/assets/1436948/bb89d0ff-d478-4702-8aaf-ee175e780647)

I see two entries for the exactly same method. Looking at breadcrumbs, one of them is placed in `Standard` whereas other in `Popular`.

**Comment by radeusgd** [comment]
The same happens for many other entries, e.g. `select_columns`:
![image](https://github.com/enso-org/enso/assets/1436948/aada814d-3dfc-4115-9b4b-5176d9623b10)

Is this intended behaviour? It does not seem right.

**Comment by farmaazon** [comment]
It looked better in the old design - we just kept entries in groups, and one entry could possibly be in two different groups. This will once my PR with new entries order land.

**Comment by jdunkerley** [comment]
Suggest we close this as it is in the planned sequence already.

**Comment by farmaazon** [comment]
I will close it once my PR land. Put it on current iteration.
