### ISSUE TITLE
Rendering issue with Text visualisation

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7332]
![image](https://github.com/enso-org/enso/assets/4699705/c5959eea-2148-40f8-83f6-f703131756a7)

Showing the default visualization of the default node has a weird gap in the text.

**Comment by 4e6** [comment]
@jdunkerley Cannot reproduce on the current d8d467f62be1c990ecf180da1ac20228c07916e1 develop

**Comment by 4e6** [comment]
@jdunkerley and @Akirathan confirmed that they have this rendering issue sometimes, and they both have some kind of display scaling in their setup. This might cause the issue

**Comment by sylwiabr** [comment]
<img width="360" alt="image" src="https://github.com/enso-org/enso/assets/12892578/130bc0c8-9d97-4891-8068-3b9b9d7f9e88">
This is screen from my Mac - nightly 20.07

**Comment by hubertp** [comment]
![Screenshot from 2023-07-31 12-42-41](https://github.com/enso-org/enso/assets/292128/b741ed36-f4c0-43e7-9aef-d92ebb729442)
Is this related to ^

**Comment by hubertp** [comment]
> Is this related to ^

Created https://github.com/enso-org/enso/issues/7455 as advised during the meeting.

**Comment by MichaelMauderer** [comment]
This is most likely related to fonts bundling. Since this is being worked on in  #7197 by @kazcw, I would like to wait until that task is closed before revisiting this.

**Comment by kazcw** [comment]
> This is most likely related to fonts bundling. Since this is being worked on in #7197 by @kazcw, I would like to wait until that task is closed before revisiting this.

#7197 actually will not affect this. The Text Grid visualization requires a monospace font; the new Enso Font has some tweaks to display code well (i.e. large space characters make indentation clear), but it is not monospace, so Text Grid will be unchanged by my PR.

**Comment by MichaelMauderer** [comment]
Okay. So we will keep Deja Vue sans Mono in the build system, then I'll keep looking into this.

For me, this issue only appears on systems that don't have the font installed. Installing the font makes the layout issue disappear. So probably our bundling is broken ins some way.

**Comment by kazcw** [comment]
I don't think in HTML we are using DejaVu acquired by the build system--until #7197 a `build.rs` downloads it, but that is only used for `ensogl_text` rendering from Rust. Some visualizations use the font by loading `https://fonts.cdnfonts.com/css/dejavu-sans-mono`, but as far as I can see the text visualization doesn't appear to be getting the font from anywhere.
