### ISSUE TITLE
Visualisations disappear on mouse hover 

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7341]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/108271897/36940c13-2e55-4d4d-b6cd-730722606cd1

### Expected behaviour

Visualization is visible all the time while hovering over it

### Enso Version

2023.7.20 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1555

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by 4e6** [comment]
I assume there was a timeout from an older visualization request that made the visualization collapse

**Comment by farmaazon** [comment]
We may add a fix where timeout from old "attachVisualization" is not closing the later successful one, but it may be hard to test.
