### ISSUE TITLE
ERROR:CONSOLE(6) while resizing visualisations or Enso window

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7342]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/108271897/95d4e92e-73f2-424f-a9b7-d27592e69a3a

please ignore ``ungaught error`` in the log - it's from previous testing
not related to this error

### Expected behaviour

more information over this error or error not happening while resizing windows/viz

### Enso Version

2023.7.20 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1848

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by jdunkerley** [comment]
Appears to be fixed.
