### ISSUE TITLE
User has to click twice to open a CB when dragging out the connection

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7351]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Pretty often when trying to drag out the connection from a node the CB is not opening after a first click and I have to click for the second time to get the CB. In the video first and third opening of the CB were the example of such case.

https://github.com/enso-org/enso/assets/12892578/6c6fb432-69ea-48b0-ab2a-663ca3c59c88

### Expected behaviour

CB should appear every time when dragging out the connection and clicking on the background.

### Enso Version

nightly 20.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
I do not reproduce it. Needs to check macOS version, maybe it's system-dependent.

**Comment by kazcw** [comment]
I think this is #7251.

**Comment by farmaazon** [comment]
Not reproducible in GUI2
