### ISSUE TITLE
Unreported loss of precision when mixing big `long` values with floating-point values in a Column

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7353]
```
from Standard.Base import all
from Standard.Table import all

polyglot java import java.lang.Long as Java_Long

main =
    i1 = Java_Long.MAX_VALUE - 123

    c1 = Column.from_vector "X" [i1, 1]
    IO.println c1.value_type
    IO.println (c1.to_vector.at 0 == i1)
    IO.println (c1.to_vector.at 1 == 1)

    c2 = Column.from_vector "Y" [i1, 1.0]
    IO.println c2.value_type
    IO.println (c2.to_vector.at 0 == i1) # This prints true, because `i1` is coerced to double before comparison, so it gets rounded in the same way as in input.
    IO.println (c2.to_vector.at 1 == 1.0)

    c3 = c2.cast Value_Type.Integer
    IO.println c3.value_type
    # But once we convert to integer, we see they are not really equal:
    IO.println (c3.to_vector.at 0 == i1) # False
    IO.println (c3.to_vector.at 1 == 1.0)
```

As we can see in this example, when we create a Column containing mixed integers and decimals, we coerce all values to `double`. For big enough integers (still small enough to fit in `long`), this coercion is **lossy**. We can see that once we convert back to integer, the number we 'take out' is not the same as the one that we did 'put in'.

Obviously, this is a normal behaviour for coercing into floating point values, we cannot do much about it apart from storing such mixed cases using some kind of BigDecimal - but that is rather not the direction we want to go.

However, in line with the philosophy of avoiding data corruption, I think we should warn whenever a coercion like this causes a loss of precision.

**I suggest that when building a column from mixed Integers and Floats**, whenever we encounter an Integer that cannot be exactly represented (i.e. `(long) (double) x != x`), **we issue some kind of `Lossy_Conversion` warning** (it probably should be aggregated to only report one warning for the whole column).

Silently losing precision seems wrong and can lead to getting wrong results - i.e. when the silent coercion loses precision and then I want to join on a column that was not converted this way - the equality between the values may no longer hold and the join will not find all records leading to wrong results. To prevent that, we should issue a warning so that the user is conscious that a loss of precision is ocurring and can either avoid the lossy coercion or take it into account when going forward.

**Comment by jdunkerley** [comment]
Agree worth attaching a warning.
