### ISSUE TITLE
Error pop-up covers node

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7361]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

A node's error pop-up covers most of the node, making it difficult to fix the error.

### Expected behaviour

The pop-up should be to the side, and not cover any part of the node.

### How we can reproduce it?

As seen in the video:
- create a node with an incorrect method call
- cmd-click in the node to edit it

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/24406074/ca8ef796-f047-48ba-b70f-3bf0efa8ae9a

### Enso Version

Version 2023.2.1-nightly.2023.7.11 (2023.2.1-nightly.2023.7.11)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

12.6.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by farmaazon** [comment]
Can you check newest develop? I think it is already fixed in #7267.
