### ISSUE TITLE
It is hard to drag a connection if a node is selected and the vis is opened

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7365]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Right now when the node is selected and the visualization is opened it is very hard to grab an output port to drag a connection.

https://github.com/enso-org/enso/assets/12892578/d703f30b-a0b8-4720-96a8-dce7a8727f19

### Expected behaviour

Dragging a connection should be easy and should not require being pixel perfect.

### Enso Version

nightly 20.07

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
First, let's make a gap between node and visualization wider.
