### ISSUE TITLE
Component Browser missing entries when opened too soon

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#7383]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When the Component Browser is opened immediately before data about available components has arrived, it doesn't offer any components except the built-in "text input" and "number input" options.

### Expected behaviour

When the data arrives, we should display the populated list.

### How we can reproduce it?

1. Open the IDE.
2. Press Tab right away.

### Screenshots or screencasts

![image](https://github.com/enso-org/enso/assets/1047859/de8140f7-7edb-4f8a-a822-023a35ef252f)

### Enso Version

develop (3e3b823620)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by farmaazon** [comment]
We do not display entries because we haven't received the suggestion database from the engine yet.

We could forbid opening CB until the database is loaded, but we don't know when it happens.

So the better solution could be reloading the list each time the suggestion database is modified.

**Comment by farmaazon** [comment]
> So the better solution could be reloading the list each time the suggestion database is modified.

We do that in GUI2
