### ISSUE TITLE
startup.project not working anymore

### ISSUE THREAD

**Issue by JanBeelte** [enso-org/enso#7384]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Last week I was able to use:
`http://127.0.0.1:8080/?startup.project=Kadalian_Automotive_Sample`
to launch Enso directly into my project.
After rebasing to develop I now get the following message:
![image](https://github.com/enso-org/enso/assets/114063253/e5c305d9-042f-4328-9c1a-face99e83f33)

Nothing has changed with respect to the project name on my end.

### Expected behaviour

It should start into the startup project without error

### Enso Version

1d2371f986c5a9d99db1c52ee6d5933ad42e33be

### Browser or standalone distribution

Chrome, Firefox (not supported officialy, but should work)

### Browser Version or standalone distribution

Mozilla Firefox 115.0.2

### Operating System

Linux

**Comment by somebody1234** [comment]
@JanBeelte Fix opened at #7393 - if you can, you might want to test it to confirm that it fixes your issue

**Comment by JanBeelte** [comment]
Works in my use case!
Thanks for the super quick fix :+1:

**Comment by JanBeelte** [comment]
I pulled develop from today and even though the MR that I tested (and which was working) is merged it does not seem to work on develop branch.
Unfortunately I do not even get an error pop up like the last time.
Also I do not see any error in the developer console.
The dashboard starts normally as if no startup project was provided.

**Comment by somebody1234** [comment]
seems like [this](https://github.com/enso-org/enso/commit/fe160ac287dd58331e5035a46433c2346b53bd2a#diff-70107806bcb5e28eff2d7ea02fd252200b63668ed57075e3b4806d85d5de81e0) is the culprit :/
i'll see whether it'll be easy to fix

**Comment by somebody1234** [comment]
edit: fix added to #7430. @JanBeelte feel free to test that PR

**Comment by vitvakatu** [comment]
It is still not working on the latest develop for me (`5d6f902383ac27c9e762ee1b79d99ac309ac5f77`)

**Comment by somebody1234** [comment]
not sure what happened there :/
fixed *again*, in #7500: https://github.com/enso-org/enso/pull/7500/commits/fe6718ac445eb81c53e3a8b3821bedafa788bbb0

**Comment by somebody1234** [comment]
closing, after basic testing i *think* this is no longer an issue.
