### ISSUE TITLE
Investigate Python Interop

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7387]
Want to ensure the basic polyglot interop with Python is fully working.

- Confirm we can move simple scalars back and forth (including Date, Date_Time and Time_Of_Day).
- Also review what happens with big integers as it stands.
- What happens with an Enso type.
- Confirm that Vector/Array become python list appropriately
- Confirm that Map become python dictionary appropriately
- Verify works in both directions.

Verify we can import python libraries - specifically how to `import datetime` and show it works.

**Comment by JaroslavTulach** [comment]
Python in _GraalVM CE 17.0.7+7.1_ seems to have a problem with treatment of `null`-like values (reported as https://github.com/oracle/graalpython/issues/345) and also converting `ZoneId` into `tzinfo` (being [discussed](https://graalvm.slack.com/archives/CNA7PDH2N/p1690355917039919?thread_ts=1690352094.690799&cid=CNA7PDH2N)):
```java
import java.time.ZoneId;

import org.graalvm.polyglot.Context;

class t {
  public static void main(String... args) throws Exception {
    var ctx = Context.newBuilder().allowAllAccess(true).build();
    var dt = ctx.eval("python", """
    import datetime
    datetime.datetime
    """);
    var v = dt.execute(2023, 7, 26, 5, 55, 57, 440);
    System.out.println(v);
    var n = dt.execute(2023, 7, 26, 5, 55, 57, 440, null);
    System.out.println(n);
    var z = dt.execute(2023, 7, 26, 5, 55, 57, 440, ZoneId.of("CET"));
    System.out.println(z);
  }
}
```
`v` is fine, but `n` and `z` fail with:
```
Exception in thread "main" TypeError: tzinfo argument must be None or of a tzinfo subclass
	at <python> _check_tzinfo_arg(bin/graalvm-ee-java17-21.3.0/languages/python/lib-python/3/datetime.py:443:16056-16126)
	at <python> __new__(bin/graalvm-ee-java17-21.3.0/languages/python/lib-python/3/datetime.py:1587:53507-53531)
	at org.graalvm.sdk/org.graalvm.polyglot.Value.execute(Value.java:841)
```

**Comment by JaroslavTulach** [comment]
##### Pros and Done

> Confirm we can move simple scalars back and forth (including Date and Time_Of_Day).

**Done**: `Date` and `Time_Of_Day` seem to be fine as #7396 demonstrates.

> What happens with an Enso type.

Not sure what this means?

> Confirm that Vector/Array become python list appropriately

**Done**. Tested in [Vector_Spec](https://github.com/enso-org/enso/blob/e4357f889026fbcb989398668909387f332c91be/test/Tests/src/Data/Vector_Spec.enso#L104) alrelady.

> Confirm that Map become python dictionary appropriately

**Done**. Tested in [Map_Spec](https://github.com/enso-org/enso/blob/e4357f889026fbcb989398668909387f332c91be/test/Tests/src/Data/Map_Spec.enso#L560) already.

> Verify how to import `datetime` and show it works.

**Done**: #7396 demonstrates how to import `datetime` library.

##### Cons or Pending

> Confirm we can move simple scalars back and forth (including Date, Date_Time and Time_Of_Day).

There is a problem with `Date_Time` as Python cannot consume polyglot or Enso `ZoneId`.

> Verify works in both directions.

Neither python seems to consume Enso's `Time_Of_Day` properly. 

> Also review what happens with big integers as it stands.

Pending. Tracked as #7213 

> Verify we can import python libraries 

Not sure how to import generic python files not installed as system libraries.

**Comment by JaroslavTulach** [comment]
#### Status Update

> > Confirm we can move simple scalars back and forth (including Date, Date_Time and Time_Of_Day).
>
> There is a problem with `Date_Time` as Python cannot consume polyglot or Enso `ZoneId`.
> Verify works in both directions.
> Neither python seems to consume Enso's `Time_Of_Day` properly. 

Reported as #7418

> Also review what happens with big integers as it stands.

(Almost) Done as #7213 

#### Future Work

> Verify we can import python libraries 

By writing own `truffle.FileSystem` we can control what files the Python implementation sees. According to the [finding polyglot bindings specification](https://github.com/enso-org/enso/blob/c61c74147674d1cb10cae164e255722593980c05/docs/polyglot/polyglot-bindings.md#finding-polyglot-bindings) we should be able to load Python, JavaScript files from `polyglot/python` and `polyglot/js` directories. I don't think this is implemented at all right now, but should be possible with the help of the `truffle.FileSystem` when really needed.
