### ISSUE TITLE
Investigate Load Time of CSV

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7398]
As reported by @JanBeelte, the processing time of a simple workflow is surprisingly slow.

A quick analysis suggests most of the time is in initialiaztion (#6100 should cover this).
The remaining time was mostly in the CSV load (14s).

This ticket is to look into the loading time and see what can be sped up.

**Comment by JanBeelte** [comment]
Thanks @jdunkerley for the analysis.
My expectation is that the startup time should not "appear" when we reload the file (hotkey: cmd alt y), right?
For my use cases the initial startup time is no big issue as long as  the reload works as fast as possible.
Maybe you can include a "reload" test into you benchmarks :-)

**Comment by jdunkerley** [comment]
The time is taken within the text to value parsing.
We have a very flexible parser but it is probably slower than it could be. I will do more investigation tomorrow to isolate where the time is being taken.

**Comment by jdunkerley** [comment]
> My expectation is that the startup time should not "appear" when we reload the file (hotkey: cmd alt y), right?

Yes that will skip the initial load time as that is triggering an execution context reload. The initial parse is already done and the nodes are just recalculated.

**Comment by jdunkerley** [comment]
https://cdn.discordapp.com/attachments/1213151264469295136/1268956583656689705/performance_hit_of_viz.gif?ex=66ae4f69&is=66acfde9&hm=e200b9988644a1bb5d11bb04361c6ae3c8672a3fa95648a913df2a9e2892dd41&

**Comment by jdunkerley** [comment]
Viz time for Table seems very slow if a large number of fields.

**Comment by steve-enso** [comment]
Here is a really good test case for this.

The video shows this at 5x speed. 

The first table viz has all of the columns (98 of them) and this seems to be a significant performance hit.

https://github.com/user-attachments/assets/02dd3506-b8d7-4e49-be29-fc208b4834e3
[Ubiquity - Prepare Invoice Data.enso-project.zip](https://github.com/user-attachments/files/16472524/Ubiquity.-.Prepare.Invoice.Data.enso-project.zip)

**Comment by steve-enso** [comment]
Here is a workflow with its associated data that is the source for the video James added:

https://drive.google.com/file/d/14VFpPR-ioc_CH8AdQCqlsIx1NHOaOOdT/view?usp=drive_link

There are 98 columns in the original.

<blockquote></blockquote>
