### ISSUE TITLE
Can't scroll a JSON/Text visualisation

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7405]
If you have a long JSON visualization the scroll bar doesn't
![image](https://github.com/enso-org/enso/assets/4699705/b7ef1ad2-631e-48e9-becf-e3d094fef070)

Neither the scroll wheel nor the scroll bar work.

**Comment by Akirathan** [comment]
It can be reproduced on `enso-linux-2023.2.1-nightly.2023.7.28.AppImage`. Moreover, the horizontal scrollbar does not work either. Neither does the horizontal mouse wheel.

**Comment by radeusgd** [comment]
Partially related #7265
