### ISSUE TITLE
Unable to use nightly as a backend release of a run script 

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#7408]
## Issue

When running IDE with a run script, and specifying a `--backend-release` with a latest nightly
```
./run --skip-version-check ide watch --backend-source release --backend-release 2023.2.1-nightly.2023.7.24 --skip-wasm-opt 
```

the script fails with the following error (full log attached)

```
Error: No matching asset for target Backend
...
Available assets: enso-bundle-2023.2.1-nightly.2023.7.24-linux-x64.tar.gz, enso-bundle-2023.2.1-nightly.2023.7.24-macos-x64.tar.gz, enso-bundle-2023.2.1-nightly.2023.7.24-windows-x64.zip, enso-engine-2023.2.1-nightly.2023.7.24-linux-x64.tar.gz, enso-engine-2023.2.1-nightly.2023.7.24-macos-x64.tar.gz, enso-engine-2023.2.1-nightly.2023.7.24-windows-x64.zip, enso-launcher-2023.2.1-nightly.2023.7.24-linux-x64.tar.gz, enso-launcher-2023.2.1-nightly.2023.7.24-macos-x64.tar.gz, enso-launcher-2023.2.1-nightly.2023.7.24-windows-x64.zip, enso-linux-2023.2.1-nightly.2023.7.24.AppImage, enso-linux-2023.2.1-nightly.2023.7.24.sha256, enso-mac-2023.2.1-nightly.2023.7.24.dmg, enso-mac-2023.2.1-nightly.2023.7.24.sha256, enso-project-manager-2023.2.1-nightly.2023.7.24-linux-x64.tar.gz, enso-project-manager-2023.2.1-nightly.2023.7.24-macos-x64.tar.gz, enso-project-manager-2023.2.1-nightly.2023.7.24-windows-x64.zip, enso-win-2023.2.1-nightly.2023.7.24.exe, enso-win-2023.2.1-nightly.2023.7.24.sha256, launcher-manifest.yaml, manifest.yaml, project-manager-bundle-2023.2.1-nightly.2023.7.24-linux-x64.tar.gz, project-manager-bundle-2023.2.1-nightly.2023.7.24-macos-x64.tar.gz, project-manager-bundle-2023.2.1-nightly.2023.7.24-windows-x64.zip
```

[run.log](https://github.com/enso-org/enso/files/12175484/run.log)

Despite the error message, the release seems to have all the artifacts uploaded correctly.

## Note

Just an observation. The latest working nightly is [2023.2.1-nightly.2023.7.20](https://github.com/enso-org/enso/releases/tag/2023.2.1-nightly.2023.7.20). It is the day when #7176 was merged and it may be related to the issue.

**Comment by farmaazon** [comment]
Related discussion: https://discord.com/channels/401396655599124480/1132945320884584500/1132945320884584500

<blockquote><img src="undefined//discord.com/assets/652f40427e1f5186ad54836074898279.png" width="48" align="right"><div><img src="/assets/ec2c34cadd4b5f4594415127380a85e6.ico" height="14"> Discord</div><div><strong><a href="https://discord.com/channels/401396655599124480/1132945320884584500/1132945320884584500">Discord - A New Way to Chat with Friends & Communities</a></strong></div><div>Discord is the easiest way to communicate over voice, video, and text.  Chat, hang out, and stay close with your friends and communities.</div></blockquote>

**Comment by Akirathan** [comment]
I am afraid I have accidentally broken our nightly releases. Nevertheless, nowadays, it should work just ok. More specifically, `Enso 2023.2.1-nightly.2023.7.21` is OK once more and should work as expected. If you continue having these issues, try a clean build.
