### ISSUE TITLE
New top bar in workspace view

### ISSUE THREAD

**Issue by PabloBuchu** [enso-org/enso#7411]
![image](https://github.com/enso-org/enso/assets/2855109/1db93aa0-c3a5-47c1-9b30-d3f9671404ee)

New design of a top bar which will be visible for users on workspace view. It contains (from the right):
1. Icons which allows user to go to the welcome screen, dashboard and currently open project (active on workspace)
2. Project name and node breadcrumbs
3. Help chat and user profile / settings related stuff

1 & 3 have to be implemented in react and 2nd is already done in Rust. To meet these requirements we (react team) need to render a fixed div and tell rust width of left and right box (so you can move your parts X pixels to the right).

This task assumes:
1. Remove current back to dashboard icon.
2. Allow us to inject the 1&3 boxes width during the EnsoApp constructing next to e.g loader / engine / startup configuration options. 
3. Ensure that events are being properly propagated between the rust / react layers

@somebody1234 anything you would like to add?

**Comment by somebody1234** [comment]
i can't think of anything missing right now, this should be enough

**Comment by farmaazon** [comment]
@PabloBuchu @somebody1234 I think I've done the rust part, you may continue the React part on the branch: #7488
