### ISSUE TITLE
Wrong placement of drop-downs 

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7423]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/f3de6cb6-2fae-453a-b7ef-a7e42d3828e8

### Expected behavior

Drop-downs should be rendered in correct positions:
* Drop-down for "join_kind" should appear when hovering "join_kind" name, even when any value is picked.
* When value is picked, the drop-down should be displayed under the constructor (first segment of prefix chain).

### Enso Version

nightly 28.07

### Browser or standalone distribution

Standalone distribution (local project), Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
@sylwiabr These drop-downs position are correct... from a certain point of view. In general, the arrows are always displayed in the middle of the drop-down widget. In this example:

![image](https://github.com/enso-org/enso/assets/3919101/2daf62c4-bc75-4831-a945-7b30e1eb006c)

The entire expression in brackets is a single drop-down widget, and you see here arrow in the middle.

How do you imagine displaying arrow for such case, so users won't be confused?
