### ISSUE TITLE
Opening a project in the cloud, switching to local and opening another project is crashing the IDE

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7424]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [x] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [x] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/73ac6025-edb2-46f5-8cbd-a1e845acee35

### Expected behaviour

Project should be opened without any issues.

### Enso Version

nightly 28.07

### Browser or standalone distribution

Standalone distribution (local project), Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
Reproduced it with logs, we get "MutuallyExclusiveOptions" error from the IDE, so it's an example of #7346.

@PabloBuchu handling to your team as it seems to be a dashboard issue: when running WASM, you should not pass both LS and PM endpoints under any condition (those are the "mutually exclusive options".

**Comment by PabloBuchu** [comment]
@somebody1234 could you take a look? maybe `backendType` is not being properly set so this is failing?
```
const engineConfig =
                            backend.type === backendModule.BackendType.remote
                                ? {
                                      rpcUrl: jsonAddress,
                                      dataUrl: binaryAddress,
                                  }
                                : {
                                      projectManagerUrl: GLOBAL_CONFIG.projectManagerEndpoint,
                                  }
```

**Comment by somebody1234** [comment]
yeah i'll investigate. it might also be the dependencies being wrong?
but according to the snippet you posted, it should never send both LS endpoints and PM endpoints at the same time. maybe one of the endpoints is being added to the URL, which is being loaded as well as our explicit config?

**Comment by somebody1234** [comment]
more importantly, i'm pretty we originally used to send the `rpcUrl` and `dataUrl` even for the local backend, so i think it shouldn't error even if `backend.type` is wrong

**Comment by somebody1234** [comment]
for posterity: i think i've fixed it locally, but i got this once when trying to close a cloud project.

repro steps:
- open local project
- back to dashboard
- open cloud project
- back to dashboard
- stop cloud project

`panicked at 'called `Option::unwrap()` on a `None` value', lib/rust/ensogl/core/src/display/world.rs:409:37`:

https://github.com/enso-org/enso/blob/e5a20ee15ed9b8b8c70385f4f8fce8455ded5504/lib/rust/ensogl/core/src/display/world.rs#L403-L410
