### ISSUE TITLE
"Failed to open visualization" / "method not found", unless I remove the "edition" line from the project's package.yaml

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7426]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

In my local build, I often get this error when attempting to create a node.

<img width="900" alt="Screen Shot 2023-07-28 at 3 21 59 PM" src="https://github.com/enso-org/enso/assets/24406074/0b598906-6ebc-4583-900f-d82d01451463">

The problem stops after I remove the 'edition' line from package.yaml.

Server log attached.

### Expected behaviour

- Start IDE and backend separately
- Create a new project
- Press Tab to create a node
- I can create a node

### How we can reproduce it?

- Start backend
java -jar project-manager.jar -vv --no-log-masking
- Start frontend
dist/ide/mac-arm64/Enso.app/Contents/MacOS/Enso -engine=false -debug.verbose

### Logs

[20230728-192029-444-enso-project-manager.log](https://github.com/enso-org/enso/files/12197793/20230728-192029-444-enso-project-manager.log)

### Enso Version

Built at a5d1cae14f0cbbafff29ea9f41fe8e42cf0ab4ab (20230728)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Monterey 12.6.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by hubertp** [comment]
If I'm reading the logs correctly then you are trying latest IDE with `2023.2.1-nightly.2023.5.11` engine. Yes, that's bound to fail due to some refactorings we did. This is the same issue as mentioned in https://github.com/enso-org/enso/issues/7095#issuecomment-1655690996

**Comment by Akirathan** [comment]
Related discussion about versioning of Engine+IDE is at https://github.com/orgs/enso-org/discussions/6762#discussioncomment-6090645

<blockquote><img src="https://opengraph.githubassets.com/43be3224a70bce8e00447fa0058339397a74c8a694d61fadf0b7ab4ad012b9ec/orgs/enso-org/discussions/6762" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/orgs/enso-org/discussions/6762">Language Server API · enso-org · Discussion #6762</a></strong></div><div>When I was discussion with @Frizi the issue #6715, we discovered several points about Language Server API to be discussed broader @4e6 @hubertp : What widgets needs to know The widgets need to know...</div></blockquote>

**Comment by GregoryTravis** [comment]
Is the workaround to just delete the line from package.yaml? Or is there something else? I wonder why it's 5.11 for me, and not 6.20.
