### ISSUE TITLE
Table.parse fails to parse a month in textual form.

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7427]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Table.parse fails to parse a date when given both a type parameter and a format parameter. It produces Nothing values. If I remove the type parameter, it works fine.

### Expected behaviour

- Parse a date string column with something like:
`operator5.parse columns="Month" type=Value_Type.Date format=(Data_Formatter.Value.with_format Value_Type.Date "MMMM")`
- Expect to see a data column produced

### How we can reproduce it?

- Create a table with a date formatted as a string
- Parse it with a node like `operator5.parse columns="Month" type=Value_Type.Date format=(Data_Formatter.Value.with_format Value_Type.Date "MMMM")`
- Observe that it produces a column of Nothings

### Screenshots or screencasts

With the type parameter:
<img width="1153" alt="Screen Shot 2023-07-28 at 4 34 13 PM" src="https://github.com/enso-org/enso/assets/24406074/98846fc3-678b-4180-8fed-2016e6323476">

Without type parameter:
<img width="1147" alt="Screen Shot 2023-07-28 at 4 34 41 PM" src="https://github.com/enso-org/enso/assets/24406074/addc1237-07e4-495c-8c48-d94c4b708930">

### Logs

[20230728-203206-138-enso-project-manager.log](https://github.com/enso-org/enso/files/12198083/20230728-203206-138-enso-project-manager.log)

### Enso Version

a5d1cae14f0cbbafff29ea9f41fe8e42cf0ab4ab (Fri Jul 28)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Monterey 12.6.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by farmaazon** [comment]
I think the actual issue is different.

I reproduced it for parsing column, but the "normal" date parsing works fine.

![Image](https://github.com/enso-org/enso/assets/3919101/cf22924f-1ea0-40cd-818d-f78f79ff92a9)

I think the actual issues is just parsing months in text form, regardless what parameters are passed to `Table.parse`.

**Comment by jdunkerley** [comment]
Can't parse just a month - need either a year or a day to make it parse-able.

This is consistent with Excel and other tools.
