### ISSUE TITLE
List editor widget should be easier discoverable

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7434]
List editor widget should display a circle allowing adding new element when clicked or creating a new element and connecting when clicked with connection dragged.

![image](https://github.com/enso-org/enso/assets/3919101/48bcc1b9-cfe2-4c0e-936c-8b6d28990579)

**Comment by AdRiley** [comment]
This functionality is available in the new GUI

![image](https://github.com/enso-org/enso/assets/1720119/3649b4da-5f17-47e3-84a8-750f4b1534dc)
