### ISSUE TITLE
Pending node status

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7435]
The IDE may receive the "Pending" status for nodes from the engine; it is sent in `executionContext/expressionUpdates` messages and stored in `ComputedValueInfoRegistry` inside the execution context.

In this task, this informatino should be propagated to view, and "pending" nodes should be displayed as in design (they have 50% their normal opacity): 

![Image](https://github.com/enso-org/enso/assets/3919101/838cfe84-7447-40a3-8aa1-5424de66b0b7)

**Comment by vitvakatu** [comment]
We also want to display some indication that the node is currently evaluating. I will create a separate task for that.
