### ISSUE TITLE
Vector Editor Rendering Issue

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7436]
![image](https://github.com/enso-org/enso/assets/4699705/59475362-d09e-4555-b698-3d3cbcc62706)

rendering of `[["Authorization", "Bearer " + operator2]]` is broken.

`operator2` is a text value.

**Comment by farmaazon** [comment]
Tried to reproduce it on 
```
commit c1e24629b0233e92f8a6a6323f686c256013ac8b (HEAD -> develop, tag: 2023.2.1-nightly.2023.8.1, origin/develop, origin/HEAD)
```
but failed:

![Image](https://github.com/enso-org/enso/assets/3919101/08030965-d8e0-4540-9777-45b2a0b6eece)

@jdunkerley Does it trigger consistently? Could you test it on the newest nightly? If you still reproduce, could you send here a project where it's happening?

**Comment by farmaazon** [comment]
@jdunkerley bump ^

**Comment by jdunkerley** [comment]
Not doing on my newest build of develop. So will close and create a new issue if occurs again.
