### ISSUE TITLE
Calling `toString` on an Enso object implementing a Java interface causes Panic

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7437]
Sometimes when passing Enso objects to Java, we can make them implement some interface by ensuring that the Enso object has all methods of that interface. This makes it easier to interact with Enso objects on the Java side (once can just use the interface instead of Polyglot methods).

It seems that `toString` which is expected from all Java objects is not picked up properly.

I'm not exactly sure if this is a bug in Enso or Graal itself.

### Repro

Let's create a file `Foo.java`:
```java
package foo;

public class Foo {
    public static interface Fooable {
        public long foo();
    }

    public static long callFoo(Fooable f) {
        long x = f.foo();
        System.out.println("Foo.foo() returned " + x);
        return x;
    }

    public static void showObject(Object o) {
        System.out.println("Object = " + o.toString());
    }

    public static long callFooAndShow(Fooable f) {
        long x = f.foo();
        System.out.println("{" + f.toString() + "}.foo() returned " + x);
        return x;
    }
}
```
and then put it in a polyglot project, with `src/Main.enso` being:
```
from Standard.Base import all

polyglot java import foo.Foo

type My_Fooable_Implementation
    Instance x

    foo : Integer
    foo self = 100+self.x

main =
   fooable = My_Fooable_Implementation.Instance 23
   IO.println fooable.foo
   IO.println fooable.to_text
   IO.println (Foo.callFoo fooable)
   IO.println (Foo.showObject fooable)
   IO.println (Foo.callFooAndShow fooable)
```

### Actual behaviour

The project as described above, when run yields:
```
123
(Instance 23)
Foo.foo() returned 123
123
Object = (Instance 23)
Nothing
Execution finished with an error: Method `toString` of type My_Fooable_Implementation could not be found.
        at <java> org.graalvm.truffle/com.oracle.truffle.polyglot.PolyglotObjectProxyHandler.invoke(PolyglotObjectProxyHandler.java:105)
        at <java> jdk.proxy5/jdk.proxy5.$Proxy44.toString(Unknown Source)
        at <java> foo.Foo.callFooAndShow(Foo.java:20)
        at <enso> Main.main<arg-1>(src\Main.enso:17:16-41)
        at <enso> Main.main(src\Main.enso:17:4-42)
```

### Expected behaviour

The program should execute without errors and yield:

```
123
(Instance 23)
Foo.foo() returned 123
123
Object = (Instance 23)
Nothing
{(Instance 23)}.foo() returned 123
123
```

The `toString` call on the Proxy object should delegate to the `to_text` method of the Enso object. As we can see, if we pass it as an `Object` that correctly happens. But if we pass it as this 'interface proxy' - that fails.

**Comment by JaroslavTulach** [comment]
Exposing `java.lang.Object` methods to guest languages is considered as **security problem**. I fixed that by designing [HostAccess](https://www.graalvm.org/truffle/javadoc/org/graalvm/polyglot/HostAccess.html). Enso is using `HostAccess.PUBLIC`, but even that doesn't allow access to methods like `getClass()`, `hashCode()` and `toString()`.

I understand that logging is problematic when `toString()` doesn't return anything at all. But I am not sure whether there is something to do about it.

**Comment by JaroslavTulach** [comment]
Here is a small program that demonstrates the behavior on Python object:
```java
import org.graalvm.polyglot.Context;
import org.graalvm.polyglot.HostAccess;

public class ToString {
    public interface WithX {
        int x();
    }

    public static void main(String[] args) {
        try (
            var ctx = Context.newBuilder()
                .allowHostAccess(HostAccess.ALL)
                .build()
        ) {
            var obj = ctx.eval("python", """
            class WithX:
                def __init__(self, v):
                    self.x = v

            WithX(42)
            """).as(WithX.class);

            System.out.println("obj.x: " + obj.x());
            var txt = obj.toString();
            System.out.println("obj  : " + txt);
        }
    }
}
```
when executed as `graalvm-17/bin/java ToString.java` it works and it prints:
```
obj.x: 42
obj  : <__main__.WithX object at 0x254cc548>
```
Something else must be wrong in the Enso case...

**Comment by JaroslavTulach** [comment]
Probably related to `PolyglotObjectProxyHandler` that caches `UnsupportedOperationException` and then handles `Object.toString` in a special way. But we throw different exception:
```java
    @Override
    public Object invoke(Object proxy, Method method, Object[] arguments) throws Throwable {
        CompilerAsserts.neverPartOfCompilation();
        Object[] resolvedArguments = arguments == null ? EMPTY : arguments;
        try {
            return invoke.call(languageContext, obj, method, resolvedArguments);
        } catch (UnsupportedOperationException e) {
            try {
                return PolyglotFunctionProxyHandler.invokeDefault(this, proxy, method, resolvedArguments);
            } catch (Exception innerE) {
                e.addSuppressed(innerE);
                throw e;
            }
        }
    }
```

**Comment by radeusgd** [comment]
> when executed as `graalvm-17/bin/java ToString.java` it works and it prints:

so that sounds like we should be able to fix this issue in Enso, because it's not a Graal issue, right? :) That sounds nice
