### ISSUE TITLE
The first entry in Component Browser may is scrolled too low and hidden from vie

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7445]
Probably best desribed with an image:

![image](https://github.com/enso-org/enso/assets/1436948/8c63b5e9-10d8-4fd0-b7c8-e7dd5bf89ac5)

The entry is there, but it's scrolled too low so it is not visible.

I've been able to reproduce it very consistently on the example from video (load an Excel file and try searching for `sheet_names` on it).

https://github.com/enso-org/enso/assets/1436948/0d3b317d-ba00-43bf-8afd-1e91783f555e

**Comment by farmaazon** [comment]
Reproduced, it seems to happen always when all entries fit the space. And I think I know the cause.

It was introduced in 73237b7b2552ac81b2db34d052812d41556396da
