### ISSUE TITLE
Cannot set username for GitHub/Google Signup

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7448]
When trying to sign up with Google or GitHub, the first stage works and the account is created but when trying to enter a username there is a server side error and you get stuck on that screen.

![image](https://github.com/enso-org/enso/assets/4699705/b12374eb-f3a1-4596-9492-c9dce7def3f1)

No error message is displayed to the end user.

There is no way back to the log in screen except to access the local storage and delete all the values.

The permission should be resolved, but additionally error handling should be added to this screen and process.

**Comment by PabloBuchu** [comment]
@somebody1234 could you take a look? The scopes didnt change since long time. So maybe regressions during the refactor?
