### ISSUE TITLE
When deleting a single item, pop up confirmation should show it

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7452]
![image](https://github.com/enso-org/enso/assets/4699705/c9e8acc5-7ef3-4f65-b8ee-70bb547d89ef)
would be good to see what I am deleting. 

When a single item would be better to have the name rather than "1 selected item".

**Comment by somebody1234** [comment]
Closing, I think this has been solved at some point. If it occurs again though, feel free to reopen

**Comment by somebody1234** [comment]
Closing, I think this has been solved at some point. If it occurs again though, feel free to reopen
