### ISSUE TITLE
Lots of warnings from WebGL in console

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7453]
![image](https://github.com/enso-org/enso/assets/4699705/251391a5-820d-4d7d-a075-55f78255bf1f)

Testing the new version go back and forth into the examples, lots of error messages in the console.
**Had not run showLogs().**

**Comment by farmaazon** [comment]
Do they show when closing project? If yes, then it's duplicate of https://github.com/enso-org/enso/issues/6505

**Comment by jdunkerley** [comment]
Yes when closing. Will close as a duplicate.
