### ISSUE TITLE
Rendering issues for simple text

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7455]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?
(standalone)
![Screenshot from 2023-07-31 12-42-41](https://github.com/enso-org/enso/assets/292128/b8ac40a6-0489-459a-943e-b771d3fea3d1)

(chrome)
![Screenshot from 2023-08-01 14-14-20](https://github.com/enso-org/enso/assets/292128/df717532-5a81-400f-aca9-129f3eae6e25)

A simple text node is weirdly displayed during edition. Potentially related to OS (Linux)?
Chrome version looks actually better than in the standalone one nightly.

### Expected behaviour

Should render text in a similar way that it is displayed in a node and in visualization:
![Screenshot from 2023-08-01 14-18-50](https://github.com/enso-org/enso/assets/292128/87866704-7ed6-44a2-bf21-d0bcea54bcd7)

### How we can reproduce it?

1. Create a new project
2. Start typing "foo"

### Enso Version

c1e24629b0233e92f8a6a6323f686c256013ac8b (latest develop)

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

c1e24629b0233e92f8a6a6323f686c256013ac8b (latest develop)

### Operating System

Linux

### Operating System Version

Ubuntu 22.04

**Comment by farmaazon** [comment]
I cannot reproduce that on my Garuda Linux. @hubertp do you still reproduce it? Could you send me all logs from the web console?

**Comment by hubertp** [comment]
Tried again the nightly where it occurred and today's nightly and I also can't reproduce anymore. Weird. Closing then.

**Comment by hubertp** [comment]
Got it again today. When tried again failed to reproduce. It's a pretty elusive bug.
![Screenshot from 2023-08-18 14-10-45](https://github.com/enso-org/enso/assets/292128/12da5c5a-1d85-4e10-9952-4cf51a7d4991)
Are those warnings maybe related? 
In the screenshot `parse` is already normal but a moment ago it wasn't rendered correctly. So yeah, pretty weird.

**Comment by vitvakatu** [comment]
@kazcw could you take a look at the warning about `The font is not defined`?

**Comment by kazcw** [comment]
> @kazcw could you take a look at the warning about `The font is not defined`?

That has been occurring for some time--we are specifying `ExtraBold` for the non-code font somewhere and it doesn't support it.

**Comment by vitvakatu** [comment]
Gotcha, we use it for the execution environment selector (it had extra bold font in some previous design version). That warning is not related to this issue, then.

**Comment by farmaazon** [comment]
Likely a bug in EnsoGL engine, and GUI2 doesn't use it anymore.
