### ISSUE TITLE
Colors on the nodes are chosen randomly.

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7456]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When creating the same node few times in a row user can get different colors.

### Expected behaviour

Colors should have meaning and be reliably used.

### Screenshots or screencasts

Uploading Nagranie z ekranu 2023-08-1 o 14.55.09.mov…

### Enso Version

nightly 1.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
Technically, it's not a "bug" in the sense that it was never implemented. But I'll keep this issue, as we don't have any for this specific feature.

The colors of the node should depend on the main expression group (or have a color designed for groupless nodes). If the group has no designated color, the color should be generated basing on the group's name hash. **The component browser should use the same way of assigning colors**.
