### ISSUE TITLE
Pressing `Cmd` is closing the visualization

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7457]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Hovering over visualization and pressing `Cmd` is causing visualization to hide when the cursor position change (move away from the visualization).

### Expected behaviour

`Cmd` should not hide the visualization

### Enso Version

nightly 1.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by jdunkerley** [comment]
`Ctrl` on Windows does this too.

**Comment by farmaazon** [comment]
I've reproduced it. I suspect the issue is that we switch visualization's `ViewState` to preview when it was enabled. If yes, then it was introduced by #7158
