### ISSUE TITLE
Dashboard has no limit on retries when a project creation fails

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#7459]
The Dashboard, or Project Manager (I am not sure which component is responsible here) does not have a max limit on retries when a project creation fails. In the screen recording below, in 4 seconds, the project-manager retries to create a new project for more than 100 times, resulting in GH API exceeding my rate limit.

[Screencast from 2023-08-01 19-10-33.webm](https://github.com/enso-org/enso/assets/14013887/924615c7-b6c9-4c0d-a111-1931cb0ab84d)

**To reproduce:**
- Set `ENSO_VERSION` or/and `ENSO_EDITION` to a version that does not exist, for example `export ENSO_VERSION=foo`. In my case, I had them set to `0.0.0-dev`, but my `0.0.0-dev` installation was broken at the time.
- Start Enso IDE.
- Try to create a new project from the dashboard

[appenso.log](https://github.com/enso-org/enso/files/12232327/appenso.log)

**Comment by Akirathan** [comment]
I was trying that on `enso-linux-2023.2.1-nightly.2023.8.1.AppImage`.

**Comment by jdunkerley** [comment]
Duplicate #7432
