### ISSUE TITLE
Editing the node is not changing the placeholders and widgets

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7462]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When user edit the node to non-existing function the widgets and placeholders are kept from the previous function.

### Expected behaviour

Node structure and view should be updated.

### Screenshots or screencasts

<img width="821" alt="Zrzut ekranu 2023-08-2 o 09 38 53" src="https://github.com/enso-org/enso/assets/12892578/8b39ce4f-6d60-4b5e-add1-2ca42c5f5100">

https://github.com/enso-org/enso/assets/12892578/c685e7b8-b197-42f8-ac4a-abf74e1f65bc

https://github.com/enso-org/enso/assets/12892578/6d979d92-e078-4ea5-b6cc-27899cc3594d

### Enso Version

nightly 1.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
The bug is in the engine, as we still receive update with "get" method call, even if it results in Panic:
```
           {
                "expressionId": "faf8448c-560b-4848-964b-45f8ad665ced",
                "type": "Standard.Base.Panic.Panic",
                "methodCall": {
                    "methodPointer": {
                        "module": "Standard.Base.Data.Vector",
                        "definedOnType": "Standard.Base.Data.Vector.Vector",
                        "name": "get"
                    },
                    "notAppliedArguments": [
                        2
                    ]
                },
                "profilingInfo": [
                    {
                        "ExecutionTime": {
                            "nanoTime": 620785
                        }
                    }
                ],
                "fromCache": false,
                "payload": {
                    "type": "Panic",
                    "message": "Method `ge` of type Vector could not be found.",
                    "trace": [
                        "faf8448c-560b-4848-964b-45f8ad665ced"
                    ]
                }
            }
```

Also, every time the code has any invalid identifier, we get the error
```
[ERROR] app/gui/src/model/project/synchronized.rs:585 Execution failed in context b89a6878-80ab-46d8-9fd4-efe0c1817366. Error: Execution of function main failed (Null receiver values are not supported by libraries.)..
```
Which in turn causes a message about execution failure presented to the user. This also should be fixed.
