### ISSUE TITLE
Automatic Dropdown support for single Atom types does not work

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7468]
Any dropdown being chosen which is an Atom only type (e.g. Report_Unmatched) results in an incorrect import being added.

The import causes ambiguous import errors (as then both the module and type are imported).

Can be worked around by custom dropdowns but this should be fixed.

**Comment by hubertp** [comment]
@Frizi is that you area? Maybe you can let us know if something is missing from LS support?

**Comment by Frizi** [comment]
I'm not sure what's the expected and observed result here. For me, selecting `Report Unmatched` from a dropdown doesn't result in any errors. I've checked that `union` has no override, and the default static tag value is used.

<img width="801" alt="Zrzut ekranu 2023-08-03 123520" src="https://github.com/enso-org/enso/assets/919491/5aa82431-0fac-4fbb-836c-f0e031d55e53">


The generated code looks like this:
```
from Standard.Table.Data import Report_Unmatched
...
operator6 = operator8.union [operator8] keep_unmatched_columns=Report_Unmatched.Report_Unmatched
```

Is this incorrect?

**Comment by farmaazon** [comment]
@jdunkerley ^ could you post here an exact scenario where "ambiguous import" happens?

**Comment by jdunkerley** [comment]
![image](https://github.com/enso-org/enso/assets/4699705/3da30490-0300-4537-beba-e638956876a3)

The additional import is creating a clash with `Report_Unmatched` included in `from Standard.Table import all`.

- The type `Standard.Table.Data.Report_Unmatched.Report_Unmatched` is exported by `Standard.Table`.
- The added import brings in the module `Standard.Table.Data.Report_Unmatched` causing am abiguous import.

We should just put the type in as the chosen option (i.e. just `Report_Unmatched` here not `Report_Unmatched.Report_Unmatched`) and detect that this is already imported.

The issue with `Nothing.Nothing` bug is exactly the same as this case.
