### ISSUE TITLE
It is not clear for the user which node is selected/where is the focus

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7469]
On this picture, the (2) is overlapped by mouse while (3) is selected by clicking it before. So if I press space, the visualization will be opened for (3), not (2). But looking at the node highlights it is almost impossible to tell that. After moving around and clicking I see that the border is a bit darker once the node is clicked on - but especially if the nodes are of different colors it's rather hard to tell which shade is supposed to be which. 

![image](https://github.com/enso-org/enso/assets/12892578/574e9b8e-8a0f-4272-a7aa-0a5a47594ec1)

**Comment by farmaazon** [comment]
Still an issue in GUI2. Perhaps we should make "hover selection" a bit less vivid (less alpha)?

**Comment by farmaazon** [comment]
No longer relevant in the new design
