### ISSUE TITLE
Default Visualisation for Connections

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7473]
When opening an Excel_Workbook (or Postgres_Connection/SQLite_Connection) the default visualisation should be a list of the available tables.

For Excel_Workbook:
- List of the sheet names followed by the list of range names.
- Clicking on a sheet name should add a new node of `.read "Sheet2"`

For a Postgres_Connection and SQLite_Connection:
- List of the table names
- Clicking on a table name should add a new node of `.query "MyTable"`

Table Viz feature:
- Serialize a cell in a special form ( `{ type: "NodeLink", text: "MySheet", node: ".read \"MySheet\"" }`)

**Comment by somebody1234** [comment]
I'm assuming the correct solution isn't to just `to_default_visualization_data self = self.tables.to_default_visualization_data` for all three types mentioned...

... re: links, if you have any requests for any potential new visualizations in GUI2 it might be a good idea to bring them up soonish - visualization support should be basically complete anyway, so I think we now have the freedom to add new visualizations and/or begin addressing previously open feature requests for visualizations.
