### ISSUE TITLE
Selecting node input ports is difficult due to limited-to-none mouse movement feedback

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7476]
This is very hard to show well on a video, nonetheless I try to demonstrate it:

https://github.com/enso-org/enso/assets/1436948/f52adecb-abbc-4bde-bc5d-e61e565c6ac8

The issue is that once an input port is 'focused' my whole mouse cursor essentially 'merges' with the input port and there is no distinction anymore. At this point - when I move my mouse around slightly - I get no immediate feedback on these movements at all. I only get feedback when I move far enough to select a different input port (then the selection jumps to that port).

First of all, it is hard to be precise. I do not know how much I need to move my mouse to switch to the next port, because I don't see its actual position. It is easy to move the mouse too much and it just feels a bit random which port will be selected. It seems the only good way is to move the mouse completely outside the node (e.g. upwards) so that the cursor becomes visible again and then I can try to more easily 'aim' at where I want to connect.

Moreover, it creates an unpleasant experience - because I do not know how much I need to move the mouse to move to next port and not overshoot completely outside of the node, I try to be very precise - I start moving my mouse much slower, which makes my hand more tense overall. The movement feels sluggish - because there's no feedback to it until it actually switches. But any faster movements are very easy to overshoot and exit the node completely or select another input port than the one that I was aiming at.

Is it possible to decouple the input port selection and the mouse cursor? I understand that this looks nice and I don't think we need to get rid of the nice effect, but it would be great if we still had _some_ small indicator that shows our mouse movements in-between switching selected input ports - that makes it much easier to be precise in these movements. The current behaviour is essentially hiding the mouse cursor and make the user work half-blinded to its movements.

**Comment by radeusgd** [comment]
On a side note, I'm not sure if this deserves a separate issue but I'm also always confused that the cursor is a big circle. In most cases the cursor is an arrow indicating the 'exact point of interaction' at the end of the arrow. A circular shape is all good too - but it is much harder to locate the center of that circle precisely - and in practice one can see that the center of the circle is the 'exact point of interaction' - its not the whole area of the circle, but the point at its center. So this is a 'point of interest' but it is not marked in any way - forcing the user to try to locate the center of the circle which is not easy to do precisely. Would it be possible to have some kind of dot at the center that would show us where _exactly_ the interaction happens?

**Comment by jdunkerley** [comment]
@sylwiabr and I was discussing this issue this morning. 

We also discussed the pointer on Monday and will pick that one up on Wojciech return.

**Comment by farmaazon** [comment]
No longer relevant in new GUI, where we use system pointer.
