### ISSUE TITLE
Clicking on a Dropdown should focus on the parent node.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7478]
When you open a dropdown the parent node should be automatically selected.

**Comment by farmaazon** [comment]
The issue is old and written for the old GUI. Do we still want to implement it such way?

**Comment by farmaazon** [comment]
Refinement nodes:
* The rule should be broader: any edit in nodes should make this (and only) node selected.
* There will be an event emitted from widgets that they are edited (needed for drop-down filtering) - we could just listen for it.

**Comment by kazcw** [comment]
I think this is blocked on #9058.
