### ISSUE TITLE
Renaming the project after closing it gets 'disturbed' by some finishing-up events

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7479]
Best to show a video of what happened:

https://github.com/enso-org/enso/assets/1436948/4e5a2af3-dca0-4b3b-8c78-803e8660e935

To add some textual explanation, let's trace the events:
1. I work on a project and then click the hamburger button to go to the dashboard.
2. I press the 'stop' button on the project.
3. The stop button disappears, so from my user perspective I assume all is done and project is closed (although I see in the logs on the right that some finishing up actions are still running - but that should not change anything from the user perspective).
4. I right-click and select to rename the project.
5. I start typing a new name, thinking what it should be :)
6. After a while, we can see in the console that the finish-up actions complete.
7. My project-name edit text-field loses focus (0:15s in the video), discarding any beautiful words I tried writing in there.

Essentially it seems like the project list is re-refreshed, disturbing the renaming workflow.

We should never discard user text changes like this - as it makes the user lose whatever was written in the text field and not submitted, which is really annoying.

If renaming should not happen while the project is still closing, we should not allow to even initiate the renaming and show the editable text field - instead we should show some indicator that some finish-up is still running, making the user aware of it (we cannot expect one to read the logs for this purpose, especially as in cloud they are not easily visible) and only allow the rename once it finishes.

If renaming is to be allowed already, we should ensure that any kind of 'refreshing' does not discard any input the user has written. The text field the user is currently editing should also not lose focus when any refresh happens. I should be able to continue coming up with a new name for my project, undisturbed.

**Comment by radeusgd** [comment]
Partially related to #7470

**Comment by farmaazon** [comment]
Reproduced on acce6108d9e1ba5433389c295ba66179520cefc1

**Comment by PabloBuchu** [comment]
Looks like the issue was solved somewhere with the new dashboard implementation. I can no longer reproduce the problem.

However if you switch windows you will lose focus on the rename project input yet the new project name will be preserved.

@radeusgd can you try with new dashboard?

**Comment by radeusgd** [comment]
> Looks like the issue was solved somewhere with the new dashboard implementation. I can no longer reproduce the problem.
> 
> However if you switch windows you will lose focus on the rename project input yet the new project name will be preserved.
> 
> @radeusgd can you try with new dashboard?

I can no longer reproduce too, so I guess it seems OK.
