### ISSUE TITLE
Creating a project on a new machine for the first time takes ages and eventually hangs infinitely

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7480]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I downloaded the newest nightly on a clean machine and created a new project. I took ages to download Graal and eventually hang on 
<img width="574" alt="image" src="https://github.com/enso-org/enso/assets/12892578/873a7ba4-e05c-4186-9170-da6e7fc8d9ef">

When I tried to open another project it was created quickly and run pretty smoothly. I was waiting for 30 min before doing any action.

### Expected behaviour

New project creation should not hang.

### Enso Version

Nightly 2.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Hardware you are using

MacBookAir Apple M1 8gb MacOS Ventura 13.3.1

**Comment by hubertp** [comment]
@sylwiabr you don't happen to have full logs, do you? They should be under the date when you run it (I will accept zip with logs as well!)

**Comment by sylwiabr** [comment]
[Archive.zip](https://github.com/enso-org/enso/files/12248577/Archive.zip)
@hubertp I don't remember which run was it so I am attaching zip with 2 logs

**Comment by 4e6** [comment]
It may be due to the fact that the engine tries to download all the edition files from GitHub. You should be able to reproduce it by removing the `~/.local/share/enso/editions` directory
