### ISSUE TITLE
Disconnecting the input for `join` node is not updating the node value/visualization

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7481]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/12892578/eed27b0b-09f5-46fc-9347-fc58003f2966

### Expected behaviour

After disconnecting the input the visualisation and node value should be updated

### Enso Version

nightly 2.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
I've reproduced the issue, and it depends on the chosen visualization:
1. Keeping the default one (not choosing any) usually does not show the issue.
2. Table visualization works fine
3. JSON visualization updates when disconnecting, but does not update back when connecting again
4. Scatterplot behaves as in the issue: does not refresh at all.

https://github.com/enso-org/enso/assets/3919101/975e13de-1570-4377-8feb-1f84633514a4

I assume our visualizations are just not prepared for receiving "Function" data. And we do not show any errors to the user, just keep the old data displayed. I remember an issue for doing that, but cannot find it now (maybe it was in pivotal).

I think the best fix would be catching any JS error going from JS viz and displaying some error like "Received incompatible data". Also, we could make distinction between exceptions going from JS (so we display different errors on incompatible data and different on visualization bugs). Handling errors going from Enso code set by viz would not hurt as well.

Also, @JaroslavTulach @4e6 here is another example where I get "Execution failed", perhaps similar case to #7496.

**Comment by jdunkerley** [comment]
Closing as now the issue that the chosen visualization is forgotten so we can't see this issue any more.
