### ISSUE TITLE
Scrolling through CB is causing Compiler Error

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7496]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When building a workflow, searching for a proper method (with node with Table selected) and highlighting them to get the documentation I am getting a compiler error as on snapshot. IDE needs then a restart because the execution is no longer possible.
<img width="393" alt="Zrzut ekranu 2023-08-4 o 10 41 00" src="https://github.com/enso-org/enso/assets/12892578/0ec75b77-ebd0-4a64-a1d3-1445a608799d">
[localhost-1691138464489.log](https://github.com/enso-org/enso/files/12258919/localhost-1691138464489.log)

### Expected behaviour

Execution should not break because of searching for the method in CB

### Enso Version

nightly 4.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by sylwiabr** [comment]
Engine logs: 
[20230804-080206-882-enso-project-manager.log](https://github.com/enso-org/enso/files/12259430/20230804-080206-882-enso-project-manager.log)

**Comment by farmaazon** [comment]
I annotate it as the backend issue @hubertp, because the engine should never fail this way. Then, if we discover there are also wrong things set by CB in GUI, we will create a separate issue for that.

Basically, I discovered that in any case, when I put a non-existing method in node, the engine fails with this error message.

**Comment by 4e6** [comment]
Fixed by #7482
