### ISSUE TITLE
I cannot log in to Enso account with my unorthodox password.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7498]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The password I have set when registering now is not accepted upon _login_:

![image](https://github.com/enso-org/enso/assets/3919101/e9939b01-7362-4682-b7f4-9fecd5d9dd8a)

There are two problems:
1. The offending password is `ÑéFÛÅÐåÒ.ú¿¼´N@aö¶U¹jÙÇ3`, so it theoretically meets all requirements.
2. When resetting the password, I got an email with a link leading to a form. The form happily accepted again the password from point 1. It should not.

### Expected behaviour

1. This password should work
2. The reset password form should have the same requirements as the login form.

Plus 3. I think checking the password should be done during registration, not during _login_.

### Enso Version

bc9cde65438ccfb912ed1a427f60a5a6d4a004d4

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by somebody1234** [comment]
@farmaazon you might want to test out #7499, which should fix it
