### ISSUE TITLE
Display only static methods when creating new node without self-argument

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#7503]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The CB component list for the input `Table.new` includes two different `Table.set` functions. Their labels and docs are indistinguishable. When previewing one, an ambiguous-name error is shown.

### Expected behaviour

- If two different `Table.set` functions are suggested, there should be a visible and obvious difference between them.
- If a component is listed in the CB, its preview (and the results of selecting it) should not report an ambiguous-name error.

### How we can reproduce it?

1. Open the IDE.
2. Press `Tab` to begin creating a new node.
3. Type `Table.new`.
4. Compare the two `New Column (Table.set)` options.

(Note that, until #7497 is merged, there are many additional extraneous entries.)

### Screenshots or screencasts

![image](https://github.com/enso-org/enso/assets/1047859/08b15997-f956-4c05-9fe6-4b462746cd1c)

### Enso Version

develop (6534d0a)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by farmaazon** [comment]
Regarding "ambiguous" name error, I think this is due to the fact we do not avoid imported names' conflicts (this is tracked by #5353).

Seemingly, we have both `set` method for module _and_ type.

**Comment by 4e6** [comment]
Should be fixed by #5353

**Comment by farmaazon** [comment]
> Should be fixed by #5353

Yes and no.

It will help with the message, but there will still be a problem of two "Table.set" methods in CB without clarity which should be used. I think we should have only one of those.

**Comment by vitvakatu** [comment]
I guess James is the best person to sort this out. If not, feel free to reassign.

**Comment by jdunkerley** [comment]
There should not be a clash here as we shouldn't see the `set` method in a static list only when we tab on one of the instances.

We do have `Table` and `Column` in both `Standard.Table` and `Standard.Database` and they very **deliberately** share identical APIs.

The type/static filtering of the CB should resolve this.

**Comment by jdunkerley** [comment]
Assigned back to @vitvakatu to assign to appropriate person to do static/type filtering (this might be engine team I guess).

**Comment by vitvakatu** [comment]
Gotcha, AFAIK, engine is currently responsible for filtering out items depending on self-type.

I was confused that in the design doc we have a statement that we should display non-static items:

<img width="1071" alt="Screenshot 2023-08-15 at 13 09 38" src="https://github.com/enso-org/enso/assets/6566674/31b50081-ee79-45bf-b2ee-7dfd56d8685d">

**Comment by jdunkerley** [comment]
For the moment, we shouldn't show the non-static methods. 
It can be useful but the user will find them more simply by going via an instance and we can't differentiate between methods with the same name well.
