### ISSUE TITLE
Unit tests fail on Mac OSX (x64)

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#7505]
The [Engine (macosx) build](https://github.com/enso-org/enso/actions/runs/5769482320/job/15641558873?pr=7487#step:10:13812) is failing. I've just reproduced it on my own Mac and following tests are failing:
```
sbt> runEngineDistribution --run test/Tests
    - [FAILED] should parse custom format of zoned time [11ms]
        Reason: 'UTC' did not equal 'Etc/UTC' (at /enso/test/Tests/src/Data/Time/Date_Time_Spec.enso:48:5-24).
--
    - [FAILED] should parse custom format of zoned time [5ms]
        Reason: 'UTC' did not equal 'Etc/UTC' (at /enso/test/Tests/src/Data/Time/Date_Time_Spec.enso:48:5-24).
--
    - [FAILED] should parse custom format of zoned time [2ms]
        Reason: 'UTC' did not equal 'Etc/UTC' (at /enso/test/Tests/src/Data/Time/Date_Time_Spec.enso:48:5-24).
--
    - [FAILED] should parse custom format of zoned time [4ms]
        Reason: 'UTC' did not equal 'Etc/UTC' (at /enso/test/Tests/src/Data/Time/Date_Time_Spec.enso:48:5-24).

```

The error seems to persist. Let's investigate it cause!

**Comment by JaroslavTulach** [comment]
According to `git blame` line 48 is written by me, but I just refactored the code. The failure was there before.

**Comment by radeusgd** [comment]
I assume that for some reason the JVM reports a different name for the parsed timezone on Mac vs Linux and Windows.

This is strange actually.

I'm actually confused, because the `Etc/UTC` that is returned here is different from the `Time_Zone.utc` constant that we have:
```
> Date_Time.parse "2020-05-06 04:30:20 UTC" "yyyy-MM-dd HH:mm:ss z"
>>> 2020-05-06T04:30:20Z[Etc/UTC]
> Date_Time.parse "2020-05-06 04:30:20 UTC" "yyyy-MM-dd HH:mm:ss z" . zone
>>> Etc/UTC
> Time_Zone.utc
>>> UTC
> Date_Time.parse "2020-05-06 04:30:20 UTC" "yyyy-MM-dd HH:mm:ss z" . zone == Time_Zone.utc
>>> false
```

So it seems that the Mac behaviour is actually "more correct".

Ideally, we should modify these tests to:
```diff
        Test.specify "should parse custom format of zoned time" <|
            time = parse_datetime "2020-05-06 04:30:20 UTC" "yyyy-MM-dd HH:mm:ss z"
            time . year . should_equal 2020
            time . month . should_equal 5
            time . day . should_equal 6
            time . hour . should_equal 4
            time . minute . should_equal 30
            time . second . should_equal 20
            time . millisecond . should_equal 0
            time . microsecond . should_equal 0
            time . nanosecond . should_equal 0
-           loose_zone_equal time.zone.zone_id  "Etc/UTC"
+           loose_zone_equal time.zone.zone_id "UTC"
+           loose_zone_equal time.zone Time_Zone.utc
```

But that will make them fail on Windows/Linux. I'd have to look into the parser to understand why it yields `Etc/UTC` instead of the 'plain' `UTC` there and what shall we do to change that.

**Comment by JaroslavTulach** [comment]
#7526 disabled some of the checks on the Mac OS X engine CI pipeline. @radeusgd requested to keep this issue open and perform additional investigation of what is going on?

**Comment by radeusgd** [comment]
> #7526 disabled some of the checks on the Mac OS X engine CI pipeline. @radeusgd requested to keep this issue open and perform additional investigation of what is going on?

Thank you.

I was thinking of renaming this issue to reflect the remaining problem. But to avoid making the history too messy, I instead created a new issue about making sure that this UTC behaviour is consistent: #7543 

So now we can close this issue and handle the remaining problems in the followup.
