### ISSUE TITLE
cannot run behind corp proxy

### ISSUE THREAD

**Issue by d0uub** [enso-org/enso#7506]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I tried using this tool behind a corporate proxy, but it keeps loading when I click the play button. I see it cannot access github.com, but it only displayed an error message once.

### Expected behaviour

I am able to load the project.

### Logs

Error opening project
'Restaurants': Unable to open
project 'Restaurants': Cannot
install the required engine.
akka_stream StreamTcpException
Tcp command
[Connect(api_github coml<unresol
seconds),true)] failed because of
java _ net_ Unknown HostExce ption.
api github_com

### Enso Version

2023.2.1-nightly.2023.8.2

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

**Comment by 4e6** [comment]
You should be able to set a proxy for Java applications by adding a `JAVA_OPTS` environment variable with your configuration, i.e.
```
-Dhttp.proxyHost=10.0.0.10 -Dhttp.proxyPort=8800
```

https://docs.oracle.com/javase/6/docs/technotes/guides/net/proxies.html
