### ISSUE TITLE
Clean-up problem handling in Table Java helper libraries

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7514]
[Latest design](https://github.com/orgs/enso-org/discussions/7738#discussioncomment-6916770)

TODO:
- [x] Add new `ProblemAggregator`.
- [ ] One by one remove old ways of reporting problems and replace them with the new one, ensuring no regressions.
	- Ideally, we should try to start with more isolated parts so that we do not have to do the refactor in one go but in smaller pieces.
	- Whether we should do it as a single PR or a series is an open question - probably depends on the probability of conflicts - unless we get probable conflicting changes in the Table library soon, keeping a single PR may be tidier. But if there are conflicts predicted, it may be better to avoid them by merging a WIP (that does not introduce regressions).
- [ ] Remove `translate_problems` in favour of constructing the right Enso problem instances straight-away in the Java code.
    - To achieve that, we will need #7797.
    - This may very well be done in a separate PR.
    - This will allow us to move the basic `ProblemAggregator` to the `std-base` project and the root helpers to `Standard.Base`, allowing us to use it in other libraries as well, if it would be needed. 

------

Old description:

## Introduction

While working on #7509 I've realised our system of aggregating 'problems' in the Java helper libraries has accumulated a bit of technical debt. 

It has grown in complexity to the point where we have multiple Problem Builders/Aggregators, two types called `WithProblems` and for practical reasons I have added a third one - `WithAggregatedProblems`. That is mostly because the main `WithProblems` was working with `List<Problem`, whereas a lot of our operation return an `AggregatedProblems` instance. The two can be converted between each other, but `AggregatedProblems -> List<Problem>` will loose information (more on this later).

![image](https://github.com/enso-org/enso/assets/1436948/95f54a1b-bcfd-4f62-8af7-aee3c1c391ce)

In general, I think we should try to slightly unify our handling of problems. The major issue of the 'non-unification' is that it is not that easy for more complex operations of which multiple sub-tasks can report problems have it hard to merge all these problems together. Firstly, it's complicating the code if we need to convert a `List<Problems>` into `AggregatedProblems` and as noted above the converse is not really possible without loss of information - that is because `AggregatedProblems` may be limiting the amount of problem instances retained (to conserve resources) and it will only keep an overall count of additional problems that were skipped. This count is checked back in Enso and `Additional_Warnings` is attached to account for these.

The other issue is that we have some objects that have a `getProblems` getter (e.g. `Table`, and I have added a similar concept to `Builder`). This is bad for two reasons:
1. from architecture PoV, this is a bit ugly, because the problems are not really semantically associated with the particular value, but with the act of creating that value (e.g. the warning about truncation of data is not a property of the table itself, but of the operation that created this table). This is not a practical issue, but more of a philosophical one.
2. The more practical problem is that - it is very easy to use this value for further processing and completely discard/forget about the problems that are attached to it. In fact, I'm guilty of this - we use `builder.seal` in many places and in many of them I don't do propagate the problems that are associated with the builder to the result. I did this because adding this propagation would mean modifying lots of our code and would take much more time. For now I chose where we _need_ to propagate and where for now this is not necessary. But as we add more kinds of problems to be reported, such holes may cause loss of warnings - a warning could be detected but could not 'survive' to be propagated to the user.

-----

Ideally, I wanted to handle this as part of #7509, especially as some of these 'architectural regressions' are newly added in this PR (but some of these issues are existing already). I started implementing it, but realised to properly unify the problem handling requires to 'touch' almost every place of the `std-table` library and it will simply take a lot of time. There's no hard challenge to it - it just needs some patience. I realised that the task of my current PR can be realised just 'continuing' the path of existing problem handling and doing the 'bad stuff' like adding another `WithAggregatedProblems` type next to `WithProblems` and sometimes discarding the `Builder`'s `getProblems` data. I just knew the solution I'm working on will still work well, and to do this properly requires a bigger refactor. So I decided it's better to split this into two - the PR will rely on these 'workarounds' that are not exactly cleanest code but get the job done, and we can plan to do this task as follow-up to improve the overall codebase - whenever we have time for this.

## Proposed steps

Above I have highlighted the two main issues we currently have:
1. Multiple 'ways' of storing problems - we have `WithProblems` in `std-base` and a similar but different `WithProblems` in `std-table`, and now I have added a yet another `WithAggregatedProblems`. Ideally, I think we should keep only `WithAggregatedProblems` that allows for easy aggregation of problems. We may have to slightly change its API to make it more universal, but in general it will allow us to merge problems for many sources in the easiest way.
2. Problems as properties of values/helpers that are too easy to ignore. Currently `Table.getProblems` and `Builder.getProblems` are showing this issue. We should not be returning an object like `Table` that contains its own problems. Neither `Builder.seal` should return a raw storage and allow to query for problems separately. Whenever we 'finish' some operation (like building a Table to be returned or sealing a column builder), we should return a value clearly indicating that there may be problems attached, e.g. `WithAggregatedProblems<Table>`. This way it is easier to remember that we should propagate these problems from such a return value. Many places already do this, but some yet don't.

Moreover, we should make it a bit easier to aggregate problems. We currently have `AggregateProblems.merge` and that is good, but we likely need to adapt it a bit to make it easier to merge problems from multiple sub-tasks.

With all that, the problem handling should be a bit easier to understand and manage.

### Additional considerations

As mentioned at the beginning we also have many different types of 'aggregators'. We may want to think if we can unify them, but we have to be careful - it may be good to have specialized variants as they allow us to be more efficient. We just need to ensure it is easy to then make sure that any problems reported by them can be easily propagated 'downstream'.

### Problem Context

Another issue that could be worth looking into when improving the system is providing necessary context for building the problem. For example, when I added the `LossOfIntegerPrecision` error, ideally I wanted to also add a column name to it, to make it easier to understand where the error is coming from. However, in the codepaths that lead to creating this problem instance, the column name was just not yet available. E.g. the `Storage` and its `Builder` do not know the `Column` name as that is the 'job' of the column. But they are the ones creating such problems. We should think if we can give them this contextual information, or if we should 'enrich' existing problems with additional context in more outer layers.

Either way, ideally, the `Loss_Of_Integer_Precision` reported in Enso should contain a `column_name`.

**Comment by radeusgd** [comment]
The test for `Loss_Of_Integer_Precision` column names:
```diff
diff --git a/test/Table_Tests/src/In_Memory/Lossy_Conversions_Spec.enso b/test/Table_Tests/src/In_Memory/Lossy_Conversions_Spec.enso
--- a/test/Table_Tests/src/In_Memory/Lossy_Conversions_Spec.enso	(revision 50c05b5330648d8d53942e8e3e6a5ca62c1be81d)
+++ b/test/Table_Tests/src/In_Memory/Lossy_Conversions_Spec.enso	(revision fd00ea46ba3ff9902139a31c9cca8c10444cad1d)
@@ -32,6 +32,7 @@
             w.example_value.to_text . should_equal y.to_text
             w.example_value_converted.to_text . should_equal (y+0.0).to_text
             w.affected_rows_count . should_equal 1
+            w.column_name . should_equal "X"
 
             t2 = table_builder [["X", [1, 2, 3, 100, 1000, x]]]
             c3 = t2.at "X" . cast Value_Type.Float
@@ -48,6 +49,7 @@
             w2 = Problems.expect_only_warning Loss_Of_Integer_Precision c4
             w2.to_display_text . should_contain "too large to represent exactly"
             w2.affected_rows_count . should_equal 4
+            w2.column_name . should_equal "Z"
 
         Test.specify "should be reported in Column.from_vector and Table.new" <|
             c1 = Column.from_vector "X" [1, 2, x, x+1, x+2, 100]
@@ -58,6 +60,7 @@
             w2 = Problems.expect_only_warning Loss_Of_Integer_Precision c2
             w2.affected_rows_count . should_equal 1
             w2.example_value . should_equal x+1
+            w2.column_name . should_equal "Y"
 
             t3 = Table.new [["X", [1, x, x+1, 1.5]]]
             w3 = Problems.expect_only_warning Loss_Of_Integer_Precision t3
@@ -106,6 +109,7 @@
             w = Problems.expect_only_warning Loss_Of_Integer_Precision r
             w.affected_rows_count . should_equal 1
             w.example_value.to_text . should_equal (x+1).to_text
+            w.column_name . should_equal "if [C] then [A] else [B]"
 
         Test.specify "should be reported when reading a CSV file" <|
             t = (enso_project.data / "lossy_int.csv") . read
@@ -115,7 +119,8 @@
             t.at "Y" . value_type . should_equal Value_Type.Float
             # Loss of precision here - the 3rd value is really x+1
             t.at "Y" . to_vector . should_equal [1, x, x, 1]
-            Problems.expect_only_warning Loss_Of_Integer_Precision t
+            w = Problems.expect_only_warning Loss_Of_Integer_Precision t
+            w.column_name . should_equal "Y"
 
             # No loss of precision if Mixed type is used early enough:
             t.at "Z" . value_type . should_equal Value_Type.Mixed

```

**Comment by GregoryTravis** [comment]
# Greg & Radek Discussion

## Main problems to solve
- We have many different problem builders which should be combined into a unified approach
- Each way of handling / aggregating problems is slightly different
- Using multiple kinds of problem builders in the same code path requires extra code to combine them
- Problems are (sometimes) attached to values, so some objects need their own problem builders while others don't
- The developer has to take care to propagate problems anywhere they arise, making it easy to lose problems

## Alternative solution
- Instead of combining / unifying the current builders, possibly take a different approach
- Define builders which *wrap around* a computation, so that any problem generated during the computation will be held by the builder
	- The 'wrapping' is achieved simply by passing a builder as an argument to a computation.
	- We would completely get rid of the `WithProblems`/`WithAggregatedProblems` wrappers (likely along with the `AggregatedProblems` type). Any operation that may return problems, instead of returning a decorated value, will need to _take_ the problem builder as an argument.
- Allow for *child builders* to wrap around a subcomputation, after which the problems are automatically merged with the parent's problems. 
	- Essentially a problem builder defines a 'scope' for problems. Child builders allow us to create child scopes.
- Allow builders to have custom logic for particular computations. For example, arithmetic errors when operating on a large column would generate too many problems; in this case, we want a count of them problems, and also the first few problems to show the user, but no more.
	- Instead of a generic aggregation logic that is hard to get right, each problem type can rely on its own aggregation logic by using a specialized child problem builder (which then feeds the problems back to the parent at the moment of summarization).
- Apart from specializing for more efficient handling of some problem types, the child builders can also provide additional context information for some classes of problems, e.g. name of a related column.
	- We can create sub-classes of the base problem builder indicating what kind of context information they provide. This way an operation can determine as part of its contract any additional context information it requires, simply by requiring a more specific problem builder type at its input. We can create a whole interface hierarchy showing what kind of context information is provided.
- The child/parent architecture means that we don't have to distinguish between *top level* and *lower level* computations, since a problem builder works the same way whether it is at the top level, or the child of another problem builder
- We can associate problems with *any* value, without worrying about whether the downstream consumer of the value will check for problems, since problems are never forgotten - they will be forwarded to the top-level problem builder through the chain of child dependencies, created _before_ the computation.
	- In Enso, we create a top-level builder to pass to a Java computation. We will not forget to do so, because every operation in Java that can report problems will _require_ it as an argument.
	- Then we have to query for the reported problems _after_ computation has finished. To ensure we don't forget about it we can create an idiom that does it for us:
	   ```
       with_problem_builder : Problem_Behavior -> (Java_Problem_Builder -> Any) -> Any
       with_problem_builder on_problems action =
            pb = new top-level problem builder
            result = action pb
            on_problems.attach_problems_before (pb.summarize_problems) result

       ...
       with_problem_builder Report_Warning pb-> java_table.do_something args pb
       ```

**Comment by radeusgd** [comment]
One limitation of this alternative approach is that there is no way to 'drop' some problems. If a problem is reported, it will surely get to the top. We cannot report it conditionally, based on some result.

However, I don't think it is a big issue. It is quite a natural effect of also the biggest advantage of that approach - in that it is impossible to 'forget' to forward a problem (because the structure of dependencies is created when starting the computation, not afterwards).

If we ever really need to explicitly drop some problems we can:
- create a blackhole problem builder that forgets them and is disconnected from top-level;
- create some kind of conditional problem builder that can be disconnected after computing a result and deeming that the problem should not be reported after all.

However, for now I don't think this affects us in any way and we will be able to find good solutions whenever needed. 

I think all in all the alternative solution gives us much better guarantees of not forgetting about handling some problems and likely should simplify the code too.

**Comment by GregoryTravis** [comment]
Yes, I think you're right -- there are cases when a child builder might attach a problem that we don't actually want the user to see. I think it's valid for the calling code -- perhaps within a parent builder, or perhaps not -- to inspect and modify the set of problems that were collected. For example, a child builder might return all problems found, and not summarize them, but the parent might know that that is too much information, and rewrite the set of problems to be a summary. This is a more rare case, but it still prevents losing any problems by accident.

**Comment by GregoryTravis** [comment]
Design document: https://github.com/orgs/enso-org/discussions/7738

<blockquote><img src="https://opengraph.githubassets.com/68d0ca3d7d59d220ba6e943f7aa183efcdb3e139b1b1a22005088c75f73175c7/orgs/enso-org/discussions/7738" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/orgs/enso-org/discussions/7738">Implicit Problem Aggregators · enso-org · Discussion #7738</a></strong></div><div>Implicit Problem Aggregators The Problem Problem aggregation in the Java Table implementation suffers from a number of issues: We have many different problem builders which should be combined into ...</div></blockquote>
