### ISSUE TITLE
Selecting `Nothing` in the dropdown inserts an erroneous expression

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7522]
https://github.com/enso-org/enso/assets/1436948/e74e5d95-2f8c-4298-afdc-ab239c787203

This is partially related to #7252 but it is a broader issue.

For some parameters, `Nothing` is a valid value and I think it may be displayed (although ideally we should have a better widget than what shown on the video for types like `Integer | Nothing`).

Still, whenever we select `Nothing` in a dropdown, an expression `Nothing.Nothing` is inserted - but that expression is never valid. I assume the dropdown logic adds an expression of the form `Type.Constructor` to the node. However, `Nothing` is a special value where `Nothing : Nothing` and it's kind of both a value and type at the same time. So there's no `Nothing.Nothing` and it fails.

### Expected behaviour

I think the dropdown logic should be able to insert a `Nothing` argument from the dropdown. It needs special handling to generate correct code in that special case.

**Comment by vitvakatu** [comment]
Assigning to @farmaazon for prioritisation, seems p-high, d-easy to me.

**Comment by vitvakatu** [comment]
See #7468, we need to fix it for all Atom types as well.

**Comment by vitvakatu** [comment]
Closing in favor of #7468
