### ISSUE TITLE
Inconsistent behaviour of `Column.||`/`OR` operation between in-memory and Database backends

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7523]
```
from Standard.Base import all
from Standard.Table import Table, Value_Type
from Standard.Database import Database, SQLite, In_Memory

main =
    t = Table.new [["X", [True, Nothing, Nothing, True, False]], ["Y", [False, True, False, Nothing, Nothing]]]
    ((t.at "X") || (t.at "Y")).print
    t.evaluate_expression "[X] OR [Y]" . print

    t2 = t.select_into_database_table (Database.connect (SQLite In_Memory)) "t2" primary_key=Nothing
    ((t2.at "X") || (t2.at "Y")).print
    t2.evaluate_expression "[X] OR [Y]" . print
```
yields
```
   | [X] || [Y]
---+------------
 0 | True
 1 | Nothing
 2 | Nothing
 3 | Nothing
 4 | Nothing

   | [X] OR [Y]
---+------------
 0 | True
 1 | Nothing
 2 | Nothing
 3 | Nothing
 4 | Nothing

 [X] || [Y]
------------
 True
 True
 Nothing
 True
 Nothing

 [X] OR [Y]
------------
 True
 True
 Nothing
 True
 Nothing
```

We can see that whenever one operand is a `Nothing`, the in-memory backend returns `Nothing` as result, regardless of the other one. In SQL that is different - even if one operand is `Nothing`, if the other one is `True`, then the result is `True` - because for `OR` if one element is true, the result should be true regardless of the other one (even if its NULL=Unknown).

The behaviour should be consistent and I'm sure that the SQL behaviour is correct here, so we should adapt the in-memory backend to also work this way.

We need to add tests that check this behaviour.

Additionally, likely `AND` may suffer from the same issue - `False AND Nothing` should be `False` because regardless of the other operand, if one is `False` than the result cannot ever be True. We should add tests for `AND` as well.

**Comment by radeusgd** [comment]
The fact that `x OR y` is NULL whenever _any_ operand is NULL in-memory is also making `filter_by_expression` work in a confusing way. I [discuss](https://discord.com/channels/401396655599124480/1138385090079113216/1138482588105838796) it in the latest bookclub.

Intuitively, adding an `OR` clause to an existing filter expression should make it return at least as many or more results. But because of the weird null propagation it may actually return **less** results. That is very un-intuitive and wrong.

Fixing the above issue will fix that.

**Comment by jdunkerley** [comment]
Blocked by agreeing behaviour of nulls

**Comment by jdunkerley** [comment]
Done.
