### ISSUE TITLE
Handle conflicting shortcuts in a nicer way.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7528]
Follow up of https://github.com/enso-org/enso/pull/7527

The proper fix for conflicting shortcuts' problem should be to handle them by focus; The shortcuts in project view should not be _global_ shortcuts, and the shortcuts should be handled "upwards": if the focused element does not handle a given shortcut, his parents should be checked one after another, and global shortcuts only then.

**Comment by somebody1234** [comment]
I'm assuming this is a non-issue in GUI2 due to bubbling of regular DOM events.
