### ISSUE TITLE
Top bar icons are visible over full screen visualizations

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7536]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

<img width="1298" alt="image" src="https://github.com/enso-org/enso/assets/12892578/8084a2a3-4deb-4b15-971d-d3e4c37cb58a">

User can not interact with the visualization or close it if they accidentally clicked on one of the buttons.

### Expected behaviour

Top bar icons should not be on the top of full screen visualization

### Enso Version

nightly 09.08

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by vitvakatu** [comment]
Introduced by #7488, I missed it on the QA.

**Comment by somebody1234** [comment]
unfortunately i'm not sure there's an easy fix. the React dashboard sets `z-index: 10` so the top bar draws over the IDE...

... actually i guess it can be fixed by moving the dashboard after the IDE, in `index.html`?

**Comment by somebody1234** [comment]
actually i'm not sure that would help... fullscreen visualizations probably need some kind of z-index still, otherwise it's impossible to show the top bar when fullscreen viz is not open, but hide it when fullscreen viz is open

**Comment by somebody1234** [comment]
Actually, I guess it should be fine to put the top bar in the "back" layer (`z-index: 1`)
https://github.com/enso-org/enso/blob/5d6f902383ac27c9e762ee1b79d99ac309ac5f77/lib/rust/ensogl/core/src/display/scene.rs#L560
