### ISSUE TITLE
Creating and launching new project in local context while new project is spinning up in the cloud context interrupts the spinning up of the cloud environment

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7538]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I have pressed one of examples in the cloud context to create new project, while it was spinning it's environment I have switched back to local context and created and launched new project from the example. Clicked a few nodes, went back to the dashboard and closed this project in the local context. When I have switched back to the cloud context the project I have left to spin up was not spinning up and it wasn't ready to launch.

### Expected behaviour

Getting back to the cloud context either shows me the spinning up of the cloud project or project has it's env. set up and it's ready to be opened.

### Enso Version

2023.8.9 nightly

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1848

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by somebody1234** [comment]
@xvcgreg i can't reproduce - mind providing repro steps?
what i tried:
- open cloud project
- switch to local backend
- open local project
- go back to drive view
- (optional) close the local project
- switch back to cloud backend
- project is still opening

**Comment by xvcgreg** [comment]
duplicate of https://github.com/enso-org/enso/issues/7424 - closing

**Comment by xvcgreg** [comment]
After further investigation it's not a duplicate - reopening

**Comment by vitvakatu** [comment]
I'm a bit perplexed about triaging this issue, I don't even understand whether it is a backend or frontend issue. @PabloBuchu could you help?

**Comment by xvcgreg** [comment]
https://github.com/enso-org/enso/assets/108271897/168af74e-e7a2-497c-9cfc-0207877f32f7

closing, can't reproduce on Nightly 2023.8.14
