### ISSUE TITLE
Horizontal scrolling JSON visualization sometimes makes text stop loading.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7545]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

In one of my project I have a node, and opened JSON visualization on it. When I horizontally scroll it to and fro several times, at some point I stop to see text and get many errors in web console.

![Screenshot from 2023-08-10 12-27-33](https://github.com/enso-org/enso/assets/3919101/f97694a5-5889-432a-b2aa-ef26e46bb4c2)

### Expected behaviour

I can scroll indefinitely without any errors.

### How we can reproduce it?

I haven't reproduced it on just any JSON visualization, but it always happens on this project, in `operator4`'s visualization.

[Bookclub_8_8.zip](https://github.com/enso-org/enso/files/12311887/Bookclub_8_8.zip)

### Enso Version

2023.2.1-nightly.2023.8.10

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by vitvakatu** [comment]
@4e6 could you help investigate this one? I'm assigning to the compiler team purely by logs.

**Comment by 4e6** [comment]
@vitvakatu I can reproduce the issue. Yes, it seems that the visualization function is failing, I need to investigate further.

**Comment by hubertp** [comment]
@4e6 @jdunkerley mentioned this is likely a libs issue, so once you narrow it down and confirm please re-assign

**Comment by 4e6** [comment]
The issue can be reproduced on the visualization of `Table`. IDE calls the lazy visualization preprocessor with 3 arguments `Vector Integer`, `Vector Integer` and `Integer`:
```json
{"jsonrpc":"2.0","id":21,"method":"executionContext/modifyVisualization","params":{"visualizationId":"08b7ff1d-47f7-4bcc-8d30-63491cf387d8","visualizationConfig":{"visualizationModule":"local.Bookclub_8_8.Main","executionContextId":"2611c9a3-5b43-4c42-9ed4-9401c3e1ba6a","expression":{"module":"Standard.Visualization.Preprocessor","definedOnType":"Standard.Visualization.Preprocessor","name":"lazy_preprocessor"},"positionalArgumentsExpressions":["[8,0]","[35,415]","20"]}}}
```

and the `Table.to_lazy_visualization_data` expects 4 arguments https://github.com/enso-org/enso/blob/c9d7c5cb2b4ae905fa5f6085c3d7a4d346c55325/distribution/lib/Standard/Visualization/0.0.0-dev/src/Helpers.enso#L284-L285

**Comment by jdunkerley** [comment]
On hold until we rework in GUI2

**Comment by farmaazon** [comment]
Closing for now, as there is no lazy JSON visualization in GUI2 yet. Once restored, we will test it for such issues.
