### ISSUE TITLE
Remove list of hard-coded type names from `TypeWithKind.java`

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#7552]
For now I can just extend it with `EnsoObject` interface, but we should use `processEnv.getTypes()` to check the real types and not just names.

_Originally posted by @JaroslavTulach in https://github.com/enso-org/enso/pull/7544#discussion_r1289976750_

**Comment by JaroslavTulach** [comment]
This will be addressed by d3c7538704590a907602c14a1fbfae29c49d7e08
