### ISSUE TITLE
Two selections are visible in the component list

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7554]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Two selections (one vivid, one dim) appear in the Component Browser, though it might be hard to spot in some cases.

https://github.com/enso-org/enso/assets/6566674/86c44964-4191-44cc-9e83-bf42e2ef2cf8

### Expected behaviour

Only a single selection is visible.

### How we can reproduce it?

1. Open CB
2. Hover over any entry with the mouse.
3. Close CB with Esc
4. Open CB again

### Enso Version

af0e738dec643b1129facd95c745409a204d828e

### Browser or standalone distribution

Standalone distribution (local project), Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
No hover highlight in GUI2.
