### ISSUE TITLE
Visualization contents scrolls when moving the scene

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#7560]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When opening a visualization and starting to move the scene with the scroll, the visualization contents also moves. The issue happens only after the initial opening of the visualization (pressing the space bar). After you select the visualization or deselect the node, the issue is gone.

### Expected behaviour

Visualization contents does not scroll together with the screen movement.

### How we can reproduce it?

- open a table visualization
- move the pointer on top of it
- start scrolling to move the scene up or down

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/357683/25785904-1504-4171-aceb-566b9151a385

### Enso Version

f1c224e62ebf755485e478164dab7beef8b749c2

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

Chromium 115.0.5790.110 Arch Linux

### Operating System

Linux

**Comment by farmaazon** [comment]
No longer reproducible in GUI2
