### ISSUE TITLE
Dropdowns not disappearing on selecting another node and are still in selection stage

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7562]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I click the dropdown on a widget it stays active even when I select another component, node. It only disappears when I click on the empty canvas.

https://github.com/enso-org/enso/assets/108271897/2b3e710f-d48f-4265-ac48-d5e910916472

### Expected behaviour

It should disappear on clicking whatever outside the selection of the dropdown.

### Enso Version

2023.8.11 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1848

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by farmaazon** [comment]
Still an issue in GUI2... except now even clicking canvas does not close drop-down :)
