### ISSUE TITLE
``add_row_number`` missing widgets, lack of example syntax, misleading doc

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7563]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I add the ``add_row_number`` node it lacks interaction on the widgets (for example I'd expect that control clicking on a particular widget/argument would allow me to edit it's value without having to type ie. "from="). 

Documentation section is missing example syntax, what we have in the header suggests to use for example ``from = 123`` but it results in ``Type_Error``. It's confusing for a new user as he/she gets double ``from`` argument in the rendered node (one being name and one proper ``form`` in its default state.

https://github.com/enso-org/enso/assets/108271897/838a19d8-c9cf-4255-a2a0-6c4109f77404

### Expected behaviour

1. documentation has an example syntax
2. (idea) after control clicking the node to edit it it has all the syntax in place with default values present (it'd be faster to edit for the user)

### Enso Version

2023.8.11 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1848

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by 4e6** [comment]
It seems that the language server sends the appropriate suggestion for the `Standard.Database.Data.Table.add_row_number` method
```
DefinedMethod(None,Standard.Database.Data.Table,add_row_number,List(Argument(self,Standard.Database.Data.Table.Table,false,false,None,None), Argument(name,Standard.Base.Data.Text.Text,false,true,Some(Row),None), Argument(from,Standard.Base.Data.Numbers.Integer,false,true,Some(1),None), Argument(step,Standard.Base.Data.Numbers.Integer,false,true,Some(1),None), Argument(group_by,(Standard.Base.Data.Vector.Vector Standard.Base.Data.Text.Text | Standard.Base.Data.Numbers.Integer | Standard.Base.Data.Text.Regex.Regex) | Standard.Base.Data.Text.Text | Standard.Base.Data.Numbers.Integer | Standard.Base.Data.Text.Regex.Regex,false,true,None,None), Argument(order_by,(Standard.Base.Data.Vector.Vector Standard.Base.Data.Text.Text | Standard.Table.Data.Sort_Column.Sort_Column) | Standard.Base.Data.Text.Text,false,true,None,None), Argument(on_problems,Standard.Base.Errors.Problem_Behavior.Problem_Behavior,false,true,None,Some(List(Standard.Base.Errors.Problem_Behavior.Problem_Behavior.Ignore, Standard.Base.Errors.Problem_Behavior.Problem_Behavior.Report_Warning, Standard.Base.Errors.Problem_Behavior.Problem_Behavior.Report_Error)))),Standard.Database.Data.Table.Table,Standard.Database.Data.Table.Table,false,Some( ALIAS rank, record id, add index column
```

Assigning this to the GUI for now

**Comment by jdunkerley** [comment]
The widgets for `add_row_number` are 2 vector editors on `order_by` and `group_by`, and a dropdown on `on_problems`. These are displayed but none have any obvious change at present (awaiting vector editor to have a + icon soon).

Widgets are as correct as we can make them currently.
