### ISSUE TITLE
Resizing visualization resets its position and column widths

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7567]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

1. change position of the viz
2. resize column widths
3. change size of the viz

https://github.com/enso-org/enso/assets/108271897/f946e039-cd1c-4598-9eb5-4c8b86076eb3

### Expected behaviour

resized columns stays resized, and viz doesn't resets it's origin

### Enso Version

2023.8.11 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1848

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by farmaazon** [comment]
Fixed in GUI2
