### ISSUE TITLE
State is not propagated to lazy field evaluation

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#7571]
When a lazy field of a type constructor is evaluated, it is evaluated with an empty state.

The problem is in [SuspendedFieldGetterNode#execute](https://github.com/enso-org/enso/blob/741b394b0dee21f0e0f76fd8e394484059db36a3/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/unboxing/SuspendedFieldGetterNode.java#L43) - it creates a new state via `State.create(ctx)`, instead of fetching this state from the parent's `Frame` via something like `Function.ArgumentsHelper.getState(frame.getArguments())`.

Reproducer:
```
from Standard.Base import all
import Standard.Base.Runtime.State

type Data
    Value ~lazy_field

fill_field =
    (State.get Data) + 1

main =
    State.run Data 42 <|
        data = Data.Value fill_field
        data.lazy_field
```
Running that fails with:
```
Execution finished with an error: State is not initialized for type Data.
        at <enso> tmp.fill_field<arg-0>(tmp.enso:9:6-19)
        at <enso> tmp.fill_field(tmp.enso:9:5-24)
        at <enso> tmp.main<arg-1>(tmp.enso:13:27-36)
        at <enso> Data.lazy_field(Internal)
        at <enso> tmp.main<arg-1>(tmp.enso:14:9-23)
        at <enso> tmp.main(tmp.enso:12-14)
```

Changing the `lazy_field` to a normal field, the snippet runs as expected and returns 43.

Related to #7117

**Comment by Akirathan** [comment]
We would probably need to change the messages in [StructsLibrary](https://github.com/enso-org/enso/blob/242bd529427be7a4b58a35c528b99565c147c74f/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/StructsLibrary.java#L24) to also include frames.

**Comment by JaroslavTulach** [comment]
Interesting. This has already been discussed at https://github.com/enso-org/enso/issues/6656#issuecomment-1600502936 - according to @kustosz we shouldn't be capturing state in library functions like `Array_Proxy.new 10 x`. 

Suspended arguments & lazy fields are a bit more _language connected construct_, so I am not sure what is the actually desired behavior.

> We would probably need to change the messages in [StructsLibrary](https://github.com/enso-org/enso/blob/242bd529427be7a4b58a35c528b99565c147c74f/engine/runtime/src/main/java/org/enso/interpreter/runtime/callable/atom/StructsLibrary.java#L24) to also include frames.

I am not sure how the fix would look like? Especially in the light of #7117 which suggests to put state into `EnsoContext`...

**Comment by jdunkerley** [comment]
Awaiting for discussion between @kustosz and @JaroslavTulach

**Comment by kustosz** [comment]
1. I think this issue is valid – should return 43.
2. The whole discussion seems to stem from whether we capture state at closure allocation or bind dynamically. Monadic state is akin to dynamic scoping and as such is always bound at call sites, not definition sites. Posting a few variants of @Akirathan repro with explanations of what I think is the correct behavior of monadic state:

a. Original code: evaluation of the lazy field happens with state in scope. Therefore it should work.
```haskell
from Standard.Base import all
import Standard.Base.Runtime.State

type Data
    Value ~lazy_field

fill_field =
    (State.get Data) + 1

main =
    State.run Data 42 <|
        data = Data.Value fill_field
        data.lazy_field
```
b. State was available at alloc time, but it isn't at eval time. Therefore this errors – alloc time doesn't matter. This is consistent to what I am saying in #6656 and still correct.
```hs
from Standard.Base import all
import Standard.Base.Runtime.State

type Data
    Value ~lazy_field

fill_field =
    (State.get Data) + 1

main =
    data = State.run Data 42 <| Data.Value fill_field
    data.lazy_field
```
c. The opposite extreme of `b` – state not available at alloc, available at eval. This works fine and returns 43.
```hs
from Standard.Base import all
import Standard.Base.Runtime.State

type Data
    Value ~lazy_field

fill_field =
    (State.get Data) + 1

main =
    data = Data.Value fill_field
    State.run Data 42 <| data.lazy_field
```

**Comment by Akirathan** [comment]
Bumping the priority of this issue, since I have encountered yet another instance of it, and it took me some time to figure out what is wrong.
