### ISSUE TITLE
State accepts only Type as key - explain in docs

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#7572]
The following code fails on `Uninitialized_State` panic:
```
main =
  State.run "my_state"  42 <|
    State.get "my_state"
```
This is because in both cases `"my_state"` is a different instance of `Text` and we do not have `equals` method implemented on `Text`. See the javadoc of `DynamicObjectLibrary`:
```
Property keys are compared using object identity (`==`) first and then `Object.equals(Object)`. It is
therefore recommended to use the same string/key instances for each access of the property in order
to avoid pulling in `equals`.
```

Putting types as keys works because types are singletons. So the following works:
```
type My_Type
main =
  State.run My_Type 42 <|
    State.get My_Type
```

Ideally, we should compare keys with `EqualsNode`, at least on the slow path. Or update the documentation of `State` methods.

**Comment by jdunkerley** [comment]
Can we make it so that the methods throw and error if the key is not a type object.
