### ISSUE TITLE
Visualizations close immediately on opening (Mac M1)

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7574]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I open a node's viz (with spacebar or the button), the viz window opens and immediately closes.

This happens both in my local build (5d6f902383ac27c9e762ee1b79d99ac309ac5f77) and with 2023.2.1-nightly.2023.8.11.

### Expected behaviour

I expect the viz to stay open and show a value.

### How we can reproduce it?

- Start the IDE
- Create a new project
- Create a node with just `12` in it
- Open the node's visualization.

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/24406074/affdf9ab-e15d-4b83-a881-84251113590b

### Logs

[20230811-203149-618-enso-project-manager.log](https://github.com/enso-org/enso/files/12325008/20230811-203149-618-enso-project-manager.log)

### Enso Version

2023.2.1-nightly.2023.8.11

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Monterey 12.6.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by hubertp** [comment]
Is there any chance you could also get GUI console logs as well? It does not appear that backend receives a single `AttachVisualization` request so I suspect GUI might be at fault.

**Comment by GregoryTravis** [comment]
@hubertp Here are console and server logs.
[2023-08-14T14-15-41.342Z-ide-2023.2.1-dev.log](https://github.com/enso-org/enso/files/12335759/2023-08-14T14-15-41.342Z-ide-2023.2.1-dev.log)
[localhost-1692022607106.log](https://github.com/enso-org/enso/files/12335760/localhost-1692022607106.log)

**Comment by vitvakatu** [comment]
Oh, that's weird, it looks like #7531, but on the video, I don't see a particularly small window.

**Comment by GregoryTravis** [comment]
Is there any more info I can provide? This is happening consistently, in my local build as well as in nightly standalone builds. I can't use the IDE at all.

**Comment by vitvakatu** [comment]
A potential fix is here: https://github.com/enso-org/enso/pull/7594, but the real issue may differ.

**Comment by vitvakatu** [comment]
@GregoryTravis could you check if the issue is still present on the most recent develop?

**Comment by GregoryTravis** [comment]
This is still happening for me.

[localhost-1692307744747.log](https://github.com/enso-org/enso/files/12373688/localhost-1692307744747.log)
[2023-08-17T21-27-02.489Z-ide-2023.2.1-dev.log](https://github.com/enso-org/enso/files/12373689/2023-08-17T21-27-02.489Z-ide-2023.2.1-dev.log)

**Comment by vitvakatu** [comment]
GUI logs look concerning, but it is not reproducible for me, and backtraces do not include debug information. 

@GregoryTravis  could you use `./run watch --skip-wasm-opt --wasm-profile=dev` command for your local build, and post the console logs here? This way, we will have backtrace information. `./run watch` has basically the same arguments as `./run build`, but to pass additional flags to the application, you need to use the `--ide-option` flag. E.g. `./run ide watch --backend-source=release --backend-release="2023.2.1-nightly.2023.8.8" --skip-wasm-opt --wasm-profile=dev --ide-option -debug --ide-option -debug.dev-tools`.

**Comment by GregoryTravis** [comment]
[localhost-1692360597325.log](https://github.com/enso-org/enso/files/12379082/localhost-1692360597325.log)

**Comment by vitvakatu** [comment]
For now, looks like the issue comes from the old engine being used. @GregoryTravis please check with the latest engine, creating a new project.

**Comment by GregoryTravis** [comment]
Yes, that was the problem. I'm not sure why all new projects are created with the 5.11 engine. In this case, Normally I run the backend with `built-distribution/enso-project-manager-0.0.0-dev-macos-amd64/enso/bin/project-manager -v` and the frontend with `dist/ide/mac-arm64/Enso.app/Contents/MacOS/Enso -engine=false`.
