### ISSUE TITLE
Example keeps the spinning animation after project has been launched and closed, spinner from cloud also shows in the local context

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7575]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![image](https://github.com/enso-org/enso/assets/108271897/b5a5e3ce-1eac-4ae6-9e28-eb26c7d7109f)

I have launched new project from example in the cloud context
Went to the local context and launched another project from the example

Got two spinning projects in the examples section:
![image](https://github.com/enso-org/enso/assets/108271897/8743c0ec-27a8-4294-9b74-22d9cb1b7640)

### Expected behaviour

separate spinners in both contexts, ending on project ready to be opened

### Enso Version

2023.8.14 nightly

### Browser or standalone distribution

Standalone distribution (local project), Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.1848

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by xvcgreg** [comment]
Refreshing Enso (ctrl+R) removes the spinner from the examples panel

**Comment by jdunkerley** [comment]
Seems to work fine now.
