### ISSUE TITLE
Dashboard Context Icons are incorrect for Windows

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7576]
![image](https://github.com/enso-org/enso/assets/4699705/ee8f234a-6101-4a23-8a62-0def44474769)

I assume these are `Ctrl` key shortcuts. There isn't a standard icon for Ctrl on windows so should be shown as `Ctrl+` key.

**Comment by somebody1234** [comment]
@jdunkerley oh yeah... i think when implementing, the context menus were slightly too narrow so one of the entries line wrapped... i guess the correct solution would be to just make the context menus wide enough

**Comment by somebody1234** [comment]
@jdunkerley PR opened as #7578
