### ISSUE TITLE
Java heap space error

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#7583]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

On a `join` node the error appeared:
<img width="1033" alt="Zrzut ekranu 2023-08-15 o 08 19 35" src="https://github.com/enso-org/enso/assets/12892578/b300e7d7-70e0-42e8-972c-634ac84ac06b">
[20230804-080206-882-enso-project-manager.log](https://github.com/enso-org/enso/files/12341707/20230804-080206-882-enso-project-manager.log)

### Expected behaviour

Join should be executed or user understandable error should be thrown

### Enso Version

15.08 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by hubertp** [comment]
Is this using the latest version? I still see `Null receiver values are not supported by libraries.` which was fixed more than a week ago.

**Comment by sylwiabr** [comment]
@hubertp yes: `edition: 2023.2.1-nightly.2023.8.15`

**Comment by sylwiabr** [comment]
today's nightly ( I am not building enso at all)

**Comment by jdunkerley** [comment]
The join wants to create a table with 487mm rows which causes an out of space error.
We need to capture the error and handle more gracefully.
