### ISSUE TITLE
Sometimes table visualization columns don't auto-size correctly when visualization is initially opened

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#7590]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Sometimes when I initially open a Table visualization for a node, not all of the columns auto-size to fit their content:
![image](https://github.com/enso-org/enso/assets/1047859/7cd0ae3c-4554-4a1f-9e1d-478d7d3e396f)

If I drag a corner of the visualization to resize it, the columns resize to their content as soon as I have changed the visualization size at all.

### Expected behaviour

Columns auto-sizing should not change completely when a small visualization resize occurs; I think the intended behavior is for them always to be sized to their content.

### How we can reproduce it?

1. Open a table visualization.
2. Often, but not always the bug is apparent.

I think this has been occurring for a long time (on the scale of weeks).

### Enso Version

develop (fd972f8)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by somebody1234** [comment]
This should be tested with GUI2, both with regular opening and fullscreen opening on a newly opened project (shift+space)

However, I think the shortcut for fullscreen vis might have been (unintentionally?) removed. @Frizi can you confirm? I think it might have been one of your changes, so I'm just confirming whether that was intentionally removed, or whether we should add new bindings to the shortcut registry

**Comment by somebody1234** [comment]
Upon some investigation: it seems like we do have bindings for opening a visualization, but none for opening a fullscreen visualization:
https://github.com/enso-org/enso/blob/cd84ac16ce4c98f22d0eda8e65a5ddb27b5eb1d5/app/gui2/src/bindings.ts#L24
