### ISSUE TITLE
No-filter component order inconsistent with matched-filter order

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#7591]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

The order of elements in the Component Browser when a filter is applied is not consistent with the order without a filter. Without a filter, the best match is `Data.read`. However, if I type `read`, the best match for that is `File_Access.Read`.

### Expected behaviour

Typing `read` shouldn't replace `Data.read` with a different best match. We could avoid this kind of inconsistency by using the no-filter sort key to break ties between components with the same match score.

### How we can reproduce it?

1. Press `Enter` to create a node; the suggested component is `Data.read`.
2. Type `read`; a different fuzzy match of equal match quality is suggested, such as `File_Access.read`.

### Enso Version

develop

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by vitvakatu** [comment]
Can't reproduce as described as of 6fd2295cc64f522ce1dd6b4746ebac2dfab4eb83 because, well, we never display `File_Access.read`. My CB currently displays exactly 13 entries on an empty project.

**Comment by vitvakatu** [comment]
Upd: either I was using the old engine, or my project was broken. Now I see more than 13 entries after opening the searcher. There is still no `File_Access.read`, though, but I will try to reproduce with some other entry.
