### ISSUE TITLE
When project delete confirmation popup appears focus doesn't switch to it - pressing Enter enters name change

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7600]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/108271897/672e3113-df75-4afb-b1c5-9ab19208e832

1st done with mouse - works
2nd done with keyboard - focus doesn't switch

### Expected behaviour

After popup appears pressing enter should confirm the delete action

### Enso Version

2023.8.17 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.2134

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by somebody1234** [comment]
note that the delete modal currently intentionally doesn't submit when pressing enter (this has always been the case)

*but*, the enter keypress definitely shouldn't be handled by anything else either. i think the best solution here is to handle the keypress on the delete modal and just have it do nothing - what do you think?

(alternatively we can just make enter confirm the dialog, as expected)

**Comment by somebody1234** [comment]
on second thought - maybe all keyboard events should be disabled when a modal is open? e.g. ctrl+r for renaming a project/folder?

**Comment by vitvakatu** [comment]
> on second thought - maybe all keyboard events should be disabled when a modal is open? e.g. ctrl+r for renaming a project/folder?

I believe this is correct behavior, except for maybe the shortcuts that are used in the modal. At least that's what I would expect as a user.

**Comment by somebody1234** [comment]
for now i'll just prevent propagation of all `keydown` events, except for `Escape` (which is the keybind used to close modals)

**Comment by somebody1234** [comment]
Potential fix implemented in #7602
