### ISSUE TITLE
Unable to delete project

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7601]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I have selected multiple projects and deleted them.
After a while (20-30sec) they started to pop out back on the list.
I noticed 1st one appearing just after the name change of one of the projects.
![image](https://github.com/enso-org/enso/assets/108271897/e576e882-e9a2-4163-800b-fd9c7ae9533e)

### Expected behaviour

Deleted projects stays deleted.

### Enso Version

2023.8.17 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.2134

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by xvcgreg** [comment]
When I repeated the action of deleting multiple projects 3 out of 4 were deleted successfully but one remained. I got this error: 
![image](https://github.com/enso-org/enso/assets/108271897/4ad812b0-5fae-4e58-9a7d-c443f31460c7)
but the project still exists in the projects folder:
![image](https://github.com/enso-org/enso/assets/108271897/ab7e8630-8717-4e3a-bd9a-09bbdf0bbbee)

**Comment by somebody1234** [comment]
if that is a project you created during that session, i have a hunch about what could be causing it

**Comment by xvcgreg** [comment]
no it was not - it was very old project

**Comment by hubertp** [comment]
@xvcgreg is the `package.yaml` inside that directory? If yes, can you pass it here? Also the internal logs, if still available.

**Comment by xvcgreg** [comment]
> @xvcgreg is the `package.yaml` inside that directory? If yes, can you pass it here? Also the internal logs, if still available.

unfortunately not, I have cleaned out Enso before recording vids
.yaml was present - the entire project was there

**Comment by hubertp** [comment]
@somebody1234 Is there any chance this could be on the dashboard side? Those logs are coming from there. Not sure how it would occur by first opening the project and the deleting it.

**Comment by somebody1234** [comment]
@hubertp the second error may be a dashboard one, I can maybe try to repro it later. the original error seems to be coming from the PM though, *but* it's true that the dashboard may have something to do with it - specifically, because projects cannot be deleted if they are still running (and/or still being created?), it tries to open them (if and only if the cached state indicates that they are still being opened), and then close them

**Comment by xvcgreg** [comment]
> because projects cannot be deleted if they are still running (and/or still being created?), it tries to open them (if and only if the cached state indicates that they are still being opened), and then close them

That'd be bizarre - this project was ancient and wasn't open for a long time. It might have something to do with the fact that I deleted multiple projects at once when I was cleaning in batches.
