### ISSUE TITLE
Context menu show option to delete all projects even if the list is empty

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7603]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/108271897/9106237e-f022-4e36-b9e1-d42ce39d0fb3

### Expected behaviour

option to delete all if there's nothing not showing up

### Enso Version

2023.8.16 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.2134

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by somebody1234** [comment]
Should be fixed by #7606, but I'm not 100% sure it's the same issue so you might want to try it out when CI finishes building it
