### ISSUE TITLE
Broken breadcrumbs spacing

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7605]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

For some paths, breadcrumbs have incorrect relative positions, so the icons overlap.

https://github.com/enso-org/enso/assets/6566674/d400a871-7d66-4e5a-affa-bc11b91608ee

### Expected behaviour

Breadcrumbs must be displayed correctly.

### Enso Version

d15b3db0ac8df5a3d149bd7f4c4559207129202f

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by kazcw** [comment]
This probably began with #7362, but it is not a regression since it's a new design.

**Comment by farmaazon** [comment]
Fixed in GUI2
