### ISSUE TITLE
Entering edit mode on node and confirming no changes with enter adds ``.join`` after the argument rendering error

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7641]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/108271897/497423d7-069e-4b0d-8d40-6f2e34a8414e

### Expected behaviour

When editing node and making no changes node stays as it was - nothing is added to the code

### How we can reproduce it?

Ctrl click to edit the node
Press Enter

### Logs

[20230823-092515-590-enso-project-manager.log](https://github.com/enso-org/enso/files/12417971/20230823-092515-590-enso-project-manager.log)

### Enso Version

2023.8.23 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.2134

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by xvcgreg** [comment]
On repro it added "Widgets" string to the code: 
![image](https://github.com/enso-org/enso/assets/108271897/01de9bcf-30b8-4801-9f64-4a84a044334b)

[20230823-100947-206-enso-project-manager.log](https://github.com/enso-org/enso/files/12418002/20230823-100947-206-enso-project-manager.log)

https://github.com/enso-org/enso/assets/108271897/fc9495fc-577e-4280-9528-11c50878f413

**Comment by vitvakatu** [comment]
Accepting the suggestion with enter was always adding the code to the node. To avoid that, you can use the `cmd+enter` shortcut. I see the issue that a seemingly random component is added each time, and there is no selection visible in the component list. I suspect we select a "random" item when open CB, the selection is displayed beyond the viewport, and accepting this suggestion adds an additional expression to the node.

**Comment by xvcgreg** [comment]
I'm well aware of that @vitvakatu. That's why it's weird that w/o selecting anything it adds random code to the node.

**Comment by xvcgreg** [comment]
I have tested it on some older version and it behaved correctly previously:

https://github.com/enso-org/enso/assets/108271897/73365a1e-5dda-45e6-b778-4fc9a73955bc

**Comment by farmaazon** [comment]
Reproduced it on develop. We correctly do not have any entry selected in CB, but insert an entry which was selected before. Seems like we have outdated value on some FRP node.

**Comment by farmaazon** [comment]
Tracked down to f2c46428bd502eed0e27a025bacc161e21469b5d..7441a9a62cdec26ed0bd152ed556ec9025c38054 (first commit is good, last is bad). Further bisecting was hard due to engine changes.

**Comment by farmaazon** [comment]
No longer reproducible in GUI2
