### ISSUE TITLE
Nodes that are not computed look bad

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#7642]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Currently, when nodes are not computed yet, they look like this:

![image](https://github.com/enso-org/enso/assets/1623053/3932d9f2-dd8c-43fe-9ca3-9cc0db613100)

It has several issues:

1. The node's background is 2 colors, because probably the selection shape is visible:
    ![image](https://github.com/enso-org/enso/assets/1623053/5833edce-5cf1-43d4-b7e0-bd1b241ba84c)
2. The connections start points are visible below nodes:
    <img width="60" alt="image" src="https://github.com/enso-org/enso/assets/1623053/a76f4456-e7a6-4416-a9df-aada0b3fcafb">
3. The colors are different than in the design.

In order to get to the design view, we need to also use the background image provided by the cloud team as the background for the graph editor. This should be simple, as our WebGL scene has transparent background and cloud uses the image just as background of the HTML scene, so please let's chat with the Cloud team how to utilize this image.

The design looks like this:

![image](https://github.com/enso-org/enso/assets/1623053/6dc16cef-b96e-4d72-b3ff-b7f32574a8c2)

### Expected behaviour

As shown above.

### Enso Version

newest

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by somebody1234** [comment]
basic testing suggests that removing the solid backgrounds from `.scene` and `#root` is enough to let the background show through - the CSS sets the background on `body` so it makes sense that nothing special should need to be done

**Comment by somebody1234** [comment]
This is where `.scene` seems to have its background set:
https://github.com/enso-org/enso/blob/4203a6e7781b7bb94f97318ee1b3d5a663fdd533/lib/rust/ensogl/core/src/display/scene.rs#L1039-L1045

And here for `#root`:
https://github.com/enso-org/enso/blob/4203a6e7781b7bb94f97318ee1b3d5a663fdd533/lib/rust/ensogl/pack/js/src/runner/index.ts#L262-L268

**Comment by vitvakatu** [comment]
@kazcw could you please give some comment regarding visual issues here? I remember from PR discussion there were some technical issues, e.g. for connections between nodes.

**Comment by kazcw** [comment]
1. The `INVISIBLE_HOVER_COLOR` has a small nonzero alpha, to avoid being culled. If round-to-zero rounding mode is being used on the GPU in some part of compositing, this could cause this color to be a little bit visible when blending with another color. I'll test this possibility after my current PR.
2. This is an interesting problem. We don't currently have a good way to draw shapes meeting when they are not rendered fully opaquely. I think the best solution involves some changes to our rendering API. I'll write up the situation in more detail after my current PR.

**Comment by kazcw** [comment]
1. I did not find the hypothesized rounding issue when compositing with the `INVISIBLE_HOVER_COLOR` in testing. We must be drawing something more opaque than that. I'm debugging to find which of the many `Rectangle`s drawn over the node is causing the tint.

**Comment by farmaazon** [comment]
Fixed in new GUI
