### ISSUE TITLE
Remove backgrounds from `.scene` and `#root`

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#7643]
The dashboard and IDE should have the same background. In order to do this, the solid color backgrounds currently set on `.scene` and `#root` should be removed.

**Comment by somebody1234** [comment]
This is where `.scene` seems to have its background set:
https://github.com/enso-org/enso/blob/4203a6e7781b7bb94f97318ee1b3d5a663fdd533/lib/rust/ensogl/core/src/display/scene.rs#L1039-L1045

And here for `#root`:
https://github.com/enso-org/enso/blob/4203a6e7781b7bb94f97318ee1b3d5a663fdd533/lib/rust/ensogl/pack/js/src/runner/index.ts#L262-L268

**Comment by vitvakatu** [comment]
Remember that we might rely on the `application.background` property from the stylesheet when calculating colors for other GUI elements. All these usages must be reviewed.

For a little context, the `#root` element background was set to white by me to ensure we notice when something goes wrong with `application.background` handling. So I think it can be safely removed.

**Comment by farmaazon** [comment]
No longer relevant in new GUI.
