### ISSUE TITLE
Each subsequent instance of Enso asks me to log in

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7645]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

https://github.com/enso-org/enso/assets/108271897/26eca88a-1107-47fa-a5e8-0bd9a6e8bf0a

### Expected behaviour

once logged in - Enso remembers I'm autentifficated 

### Enso Version

2023.8.23 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.2134

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 531.68

**Comment by somebody1234** [comment]
@xvcgreg i think you posted this before the video finished uploading btw.

as for this issue... i think it might be possible to have just one electron instance, and have new instances of the app just open new windows - that way Enso doesn't have to spawn more than one Project Manager. does anyone have any thoughts? is there a situation where this doesn't work, or where this is not desirable?

**Comment by xvcgreg** [comment]
@somebody1234 thanks. fixed

**Comment by somebody1234** [comment]
@xvcgreg Potential fix at #7648. It seems to work for me on Linux, *but* Linux has neither file handling nor URL handling, so I can't guarantee that those aren't currently broken in that branch (e.g. if authentication URLs open in the wrong window, or if double clicking a file does the wrong thing)

**Comment by hubertp** [comment]
Based on the discussion, I'm adding dashboard label.

**Comment by somebody1234** [comment]
It *might* be `g-electron`, depending on the cause of this issue

**Comment by jdunkerley** [comment]
We should at least for now stop multiple instances of electron running. We can revisit at a later date when we support different port numbers etc for project manager.

**Comment by somebody1234** [comment]
@jdunkerley note that we do now support different port numbers for the PM

**Comment by somebody1234** [comment]
putting on hold as i don't think this is actionable currently?

i wonder if the multi-user that's supported by GUI2 would be useful for this - although, it *would* mean that the same yjs instance needs to be integrated with both React and Vue
