### ISSUE TITLE
Visualization drag handle is not visible

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7647]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I see no arrows on the left side of the visualization's action bar

<img width="589" alt="Screenshot 2023-08-23 at 18 17 41" src="https://github.com/enso-org/enso/assets/6566674/bc794446-0e2f-4152-90d4-078fc8975e36">

### Expected behaviour

The arrows are visible and I can drag the visualization container around.

### Enso Version

7d83b3d7b4da4836555a50b4dca3f001a019b02d

### Browser or standalone distribution

Standalone distribution (local project), Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
I remember vaguely that it was removed by purpose. @sylwiabr @jdunkerley @wdanilo do you know something about it?

**Comment by vitvakatu** [comment]
It is visible on the very same branch I was testing; see video in #7620, and I also see the corresponding code in the sources.

**Comment by farmaazon** [comment]
I see the drag handle on newest develop

![Image](https://github.com/enso-org/enso/assets/3919101/7ab75500-7d62-4096-bf3d-9f572697a27a)

@vitvakatu do you still reproduce the issue? If yes, then I guess it may be another shape ordering problem.

**Comment by vitvakatu** [comment]
I just checked on b49cc25d3879ca5fbc4810a3dd83809680f5f086, and it's visible. It might be a heisenbug, though. Let's close it until somebody else discovers it.
