### ISSUE TITLE
Hard to change viz when scatter plot is focused

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#7652]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When the scatter plot is focused, it is hard to use the dropdown to change visualizations.

### Expected behaviour

Clicking anywhere on the visualizaiton-chooser dropdown label or arrow should open the dropdown.

### How we can reproduce it?

1. Enable the Scatter Plot visualization for a node.
2. Click in the center of the visualization, so that the cursor changes to a crosshair.
3. Move the mouse over the visualization chooser: The cursor shows a crosshair except when the mouse is at the very top, above most of the label's text. If the mouse is clicked while the cursor is a crosshair, the visualization will receive the click event and the dropdown will not open.

### Screenshots or screencasts

[vokoscreenNG-2023-08-23_22-34-27.webm](https://github.com/enso-org/enso/assets/1047859/1b1c9fa1-aaa3-4503-9ea2-7399cc4a9c4e)

### Enso Version

develop (7d83b3d)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by farmaazon** [comment]
For me, it's more reproducible on histogram than scatter plot. But as a rule, we do not react to clicks inside the "plot area" of visualization, even if it's below vis top bar.

@wdanilo Do you remember, when you were implementing new event system, you asked me why EnsoGL was taking events in capturing phase? Here is the answer: the d3js is still stealing events in some situations.

Introduced probably by new event system, quite a long ago.

Workaround: deselect visualization (click on the background outside), and then open visualization chooser.

**Comment by farmaazon** [comment]
in GUI2, the visualization chooser is always visible, so we no longer have this problem.
