### ISSUE TITLE
CB bounces when scrollbar dragged beyond end

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#7653]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Dragging the CB scrollbar beyond the end of the panel causes the CB to start bouncing.

### Expected behaviour

When the end of the scrollbar range is reached, the scrollbar should stop and the panel should hold still.

### How we can reproduce it?

1. Open the component browser.
2. Click the scrollbar and drag it slightly past the bottom of the panel.

### Screenshots or screencasts

[vokoscreenNG-2023-08-23_22-57-53.webm](https://github.com/enso-org/enso/assets/1047859/df036abc-e4b6-4110-aef1-41a782196965)

### Enso Version

develop (7d83b3d)

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

**Comment by vitvakatu** [comment]
The issue is caused by the scrollbar component, not the component browser itself, so slightly changing labels.

**Comment by farmaazon** [comment]
No reproducible in GUI2
