### ISSUE TITLE
Broken breadcrumbs navigation

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7665]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

colapse node twice to create 2 levels deep grouped node
navigate through breadcrumbs - going from left to right: 
press main - ok
press func 1 - goes straight to func 2 - wrong
press func 2 - goes to func 2 - ok
press func 1 - goes to func 1 - ok
repeat

https://github.com/enso-org/enso/assets/108271897/c3348c22-f4a8-4e2a-938f-dc1e14726577

### Expected behaviour

breadcrumbs leading to correct places

### Enso Version

2023.8.25 nightly

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.2134

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 537.13

**Comment by vitvakatu** [comment]
It was most likely introduced by #7619, but let's not mark it as regression, as the algorithm was heavily refactored _and_ we got a new design, and we can't ship either alone. Let's fix it in the new implementation.

**Comment by farmaazon** [comment]
No longer reproducible in GUI2
