### ISSUE TITLE
Enso doesn't display the dashboard elements after the start

### ISSUE THREAD

**Issue by xvcgreg** [enso-org/enso#7672]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Fresh install of Nightly 2023.8.28 and Enso cant load it's dashboard.

```[34340:0828/140952.150:ERROR:display_layout.cc(551)] PlacementList must be sorted by first 8 bits of display_id
[info] [2023-08-28T12:09:52.645Z] [org.enso.projectmanager.boot.ProjectManager$] Starting Enso Project Manager
Version:    2023.2.1-nightly.2023.8.28
Built with: scala-2.13.11 for GraalVM 17.0.7
Built from: develop* @ b8edf6a3582b35573dbd824ca04d21b39d4be910
Built on:   Windows 10 (amd64)

[info] [2023-08-28T12:09:52.712Z] [org.enso.projectmanager.boot.ProjectManager$] Started server at 127.0.0.1:30535, press enter to kill server
[34340:0828/140952.814:ERROR:display_layout.cc(551)] PlacementList must be sorted by first 8 bits of display_id
[34340:0828/141017.526:ERROR:display_layout.cc(551)] PlacementList must be sorted by first 8 bits of display_id
[34340:0828/141211.583:ERROR:display_layout.cc(551)] PlacementList must be sorted by first 8 bits of display_id
[34340:0828/141220.132:ERROR:display_layout.cc(551)] PlacementList must be sorted by first 8 bits of display_id
[34340:0828/141321.140:ERROR:display_layout.cc(551)] PlacementList must be sorted by first 8 bits of display_id
[info] [2023-08-28T12:13:22.705Z] [org.enso.projectmanager.boot.ProjectManager$] Stopping server...
[info] [2023-08-28T12:13:22.71Z] [akka.actor.CoordinatedShutdown] Running CoordinatedShutdown with reason [ActorSystemTerminateReason]
```

Here's what I see in Nightly 2023.8.28:
![image](https://github.com/enso-org/enso/assets/108271897/502a53d1-cbfa-4b21-813d-c320127bb887)

I have installed the Nightly 2023.8.25 which I was using on last Friday and then it worked perfectly. I still got the ``dispaly_layout`` error. But here I got further due to fact that top bar icons were visible and Enso has started opening last project I was working recently.

Nightly 2023.8.25:
https://github.com/enso-org/enso/assets/108271897/7ca27bc3-7a02-4e1d-bcb3-71ddf4e45438

I have suspicion that due to traveling and changing my monitor configuration (from none attached to two additional monitors hooked up) Enso somehow got lost in the setup. I have not restarted the machine, had put it to sleep (will restart now and continue with this bug report).

### Expected behaviour

start properly

### Enso Version

2023.8.28 nightly

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Windows

### Operating System Version

Win11pro 22H2 22621.2134

### Hardware you are using

12th Gen Intel(R) Core(TM) i9-12900HK / RTX3060 Laptop / Nvidia Drivers 537.13

**Comment by xvcgreg** [comment]
After restarting the Windows - everything works fine on both versions (28th and 25th Aug Nightlies).

**Comment by somebody1234** [comment]
yeah i *think* this was a chromium issue - `display_layout.cc` is in chromium:
https://chromium.googlesource.com/chromium/src/+/master/ui/display/display_layout.cc

<blockquote><div><strong><a href="https://chromium.googlesource.com/chromium/src/+/master/ui/display/display_layout.cc">ui/display/display_layout.cc - chromium/src - Git at Google</a></strong></div></blockquote>

**Comment by vitvakatu** [comment]
Seems to be an Electron issue, I doubt we should investigate it unless we have a very clear reproduction scenario (and even in this case, it is probably better to report upstream).

UPD: https://github.com/electron/electron/issues/37156
