### ISSUE TITLE
Segmentation fault (presumably) when parsing Main.enso file

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#7691]
Using `2023.2.1-nightly.2023.8.30` I get:
```
$ ./built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run Main.enso
Segmentation fault (core dumped)
```
Just before everything started to crash there was some external change in metadata and the IDE dropped layout of my nodes. As such my hypothesis is this is a bug in native part of the parser.

[Main.enso.gz](https://github.com/enso-org/enso/files/12472661/Main.enso.gz)

Removing the metadata section fixes the problem and my file can be executed again.

**Comment by kazcw** [comment]
1. An incomplete metadata delimiter causes metadata to be parsed as code.
    * Feature: Detect the metadata delimiter less strictly.
2. While parsing the resulting input, the macro resolver overflows the stack, causing a segfault.
    * **Bug: The macro resolver cannot handle arbitrarily large inputs because it is recursive.**
3. A segfault in the parser causes the engine to crash.
    * Feature: Sandbox the parser.

I'm implementing a solution for (2), then I'll write up (1) & (3).
