### ISSUE TITLE
Test backend startup when user is behind a proxy

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7693]
`gu install` potentially needs some additional configuration when a user is behind a (corporate) proxy.
This typically manifests itself with
```
PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
```
exception. 

Steps to verify (on Linux) when proxy is setup:
- `~/.local/share/enso/runtime/graalvm-ce-java17.0.7-23.0.0/bin/gu install js`
- `~/.local/share/enso/runtime/graalvm-ce-java17.0.7-23.0.0/bin/gu --jvm install js`
- `~/.local/share/enso/runtime/graalvm-ce-java17.0.7-23.0.0/bin/gu -vm.Dhttp.proxyHost=web.cache.oracle.com -vm.Dhttp.proxyPort=8080 install js`

Related tickets: https://github.com/oracle/graal/issues/4048 https://github.com/oracle/graal/issues/4728

**Comment by jdunkerley** [comment]
Can we localize the gu parts locally.

**Comment by jdunkerley** [comment]
putting on hold - attempting to always use packaged parts rather than downloading.

**Comment by hubertp** [comment]
Apparently still an issue when running behind the proxy:
```
IllagealArgumentException error when sending request. HTTP connect timed out (at <enso> <anonymous>) (/home/.../install/enso/sroot/resources/enso/dist/2023nightly23.10.17/lib/Standa  nightly23.10.17/lib/Netwo 137)
```

**Comment by jdunkerley** [comment]
As no longer using gu closing.
