### ISSUE TITLE
TS API for Enso Parser

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#7701]
Efficiently invoke the WASM parser from TS/JS and produce AST types.

**Comment by Frizi** [comment]
Currently the parser is integrated in the minimal form, just by compiling a relatively small crate to WASM, which exports single parsing function for the whole module's code. To finish this task, we have to implement some form of incremental updates resolved on rust side. Right now, the idea is to reparse the whole module and find a difference between old and new AST, then send that difference to JS, which can apply it on its existing structure. That way we can easily leverage fine-grained vue reactivity to update only parts of the view that were dependant on the updated AST subtree.

**Comment by kazcw** [comment]
Moved to #7884.
