### ISSUE TITLE
Runtime type check on a function is delayed until all required arguments were provided

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7713]
See the following example:
```
from Standard.Base import all

foo (x : Text) (y : Vector) (z : Integer = 42) =
    [x, y, z]

main =
    IO.println (foo "A" [1])
    IO.println (Panic.recover Any <| foo [2])
    IO.println (Panic.recover Any <| foo [3] "A")
```

### Actual behaviour

```
[A, [1], 42]
delayed-typecheck.foo[delayed-typecheck.enso:3-4] self=delayed-typecheck x=[2] y=_
(Error: (Type_Error.Error Text [3] 'x'))
```

We can see that on the second line, we have `x=[2]` which _will_ trip the runtime type check. But it didn't yet. Until I provide a value for `y`, that 'sits frozen' and waiting. This is delaying the inevitable - whatever I plug in later, will make this invocation fail **(*)**.

### Expected behaviour

I'd expect both of the last two calls to fail 'immediately':
```
[A, [1], 42]
(Error: (Type_Error.Error Text [2] 'x'))
(Error: (Type_Error.Error Text [3] 'x'))
```

### * Comment

I wanted to make sure if I'm not lying about the (*) sentence.

I was wondering if it is possible to add something to make that invocation _not fail_. Well the only idea I had was, what if I add an `x="A"` argument _afterwards_. Will it reorder the arguments to move the `[4]` onto the `y` argument? Well, I tried it to be sure and no.

```
from Standard.Base import all

foo (x : Text) (y : Vector) (z : Integer = 42) =
    [x, y, z]

main =
    IO.println (foo "A" [1])
    IO.println (Panic.recover Any <| foo [2])
    IO.println (Panic.recover Any <| foo [3] "A")
    IO.println (Panic.recover Any <| foo [4] x="A")
```
yields
```
[A, [1], 42]
delayed-typecheck.foo[delayed-typecheck.enso:3-4] self=delayed-typecheck x=[2] y=_
(Error: (Type_Error.Error Text [3] 'x'))
delayed-typecheck.foo[delayed-typecheck.enso:3-4] self=delayed-typecheck x=[4] y=_ +x='A'
```
So, the second `x="A"` shows up as an _oversaturated argument_. Meaning that the original `x=[4]` is not 'reordered'. Well, if that doesn't reorder it, I don't think anything can. So it will stay as `x=[4]`. Meaning that it **will** trip over once we reach execution. Meaning that there is no way to 'save' this call, so it seems that there is no sense to delay this error. We should report the type error as early as possible - once it is inevitable there is no point in delaying it.

**Comment by JaroslavTulach** [comment]
Intersting:
```ruby
from Standard.Base import all

foo (x : Text) (y : Vector) (z : Integer = 42) =
    [x, y, z]

computeFirst =
    IO.println "First argument computed"
    [1]

main =
    IO.println "Starting..."
    f = foo computeFirst
    IO.println "f is computed..."
    f [2]
```
fails with:
```
Starting...
First argument computed
f is computed...
Execution finished with an error: Type error: expected `x` to be Text, but got Vector.
        at <enso> z.foo(z.enso:3-4)
        at <enso> z.main(z.enso:14:5-9)
```

However I don't think it is a bug. This is behaving exactly as we wanted. The argument check is done inside of the called method, not at a callsite.

**Comment by radeusgd** [comment]
Okay, we may not call it a bug, but I think it would still be worth implementing - it is worth to report the 'inevitable' type error as soon as possible.

Moreover, it is slightly confusing to see
```
delayed-typecheck.foo[delayed-typecheck.enso:3-4] self=delayed-typecheck x=[2] y=_
```
knowing that `x : Text`

**Comment by radeusgd** [comment]
Do you think it would be a big problem to move the check from inside the method into the callsite?

**Comment by JaroslavTulach** [comment]
> Do you think it would be a big problem to move the check from inside the method into the callsite?

Yes, I believe it would negatively affect performance.

**Comment by jdunkerley** [comment]
This is not being done for now due to how are type checking is performed. Could be revisited in future.
