### ISSUE TITLE
Displaying entries from Suggestion Database with fuzzy search

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7737]
* Suggestion database is to be mocked - no listening to LS updates in the scope.
* The filtering should get the entire input as the pattern (interpreting what is the pattern in the input is another task).
* Fuzzy search can be minimal.

**Comment by Frizi** [comment]
Potential lib that could be used to get fuzzy search and efficient indexing: https://github.com/leeoniya/uFuzzy

<blockquote><img src="https://opengraph.githubassets.com/1a90872103718b5d5f341f9230107be618e0f0fedc2475a946baddc99748514b/leeoniya/uFuzzy" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/leeoniya/uFuzzy">GitHub - leeoniya/uFuzzy: A tiny, efficient fuzzy search that doesn't suck</a></strong></div><div>A tiny, efficient fuzzy search that doesn't suck. Contribute to leeoniya/uFuzzy development by creating an account on GitHub.</div></blockquote>

**Comment by jdunkerley** [comment]
We don't need fuzzy matching in this.
The filtering is just starts with, word starts with or initials.
https://github.com/enso-org/enso/issues/7046#issuecomment-1619773935 has the algorithm we want.
Also have it as react code if needed.

**Comment by Frizi** [comment]
@jdunkerley Right, we will implement those rules. What we are really shopping around for is a decent text indexer, so we don't have to do full scan text scearch through the whole suggestion database on every keypress/DB update. It looks like the library I posted doesn't really provide that after all, so we have to find something else. If the fuzzy index query is a bit less strict than our ruleset, it's fine. We can filter the reduced dataset manually afterwards.

**Comment by farmaazon** [comment]
> What we are really shopping around for is a decent text indexer, so we don't have to do full scan text scearch through the whole suggestion database on every keypress/DB update. 

Actually, I think it's not as needed. I tried the prototype written by James, which does the full scan of 3K entries (I believe covering all entities of our Stdlib), and checked with performance tab: obtaining and sorting the filtered list takes ~1 ms. I think we could handle even 5 times more entries.
