### ISSUE TITLE
"Unexpected error occured when loading the list of workspaces" in Cloud

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7757]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

After login, cloud.enso.org showed me an empty list of workspaces, with the error message “Unexpected error occured when loading the list of workspaces. Please try again later.”

### Expected behaviour

I expect to see the list of workspaces.

(I was able to create workspaces, which, when opened, produced another error, but those same workspaces could be opened using a local build of the IDE)

### How we can reproduce it?

1. cloud.enso.org
2. Log in with Google
3. See error

### Screenshots or screencasts

<img width="1268" alt="Screen Shot 2023-09-06 at 3 24 08 PM" src="https://github.com/enso-org/enso/assets/24406074/4c4e7e45-86b5-495c-ad63-5fdfe1cf20d1">

### Logs

[2023-09-06T19-27-53.858Z-ide-2023.2.1-dev.log](https://github.com/enso-org/enso/files/12542573/2023-09-06T19-27-53.858Z-ide-2023.2.1-dev.log)
[client-Wed-Sep-6-16.28.55-2023.txt](https://github.com/enso-org/enso/files/12542574/client-Wed-Sep-6-16.28.55-2023.txt)
[server-Wed-Sep-6-16.28.57-2023.txt](https://github.com/enso-org/enso/files/12542575/server-Wed-Sep-6-16.28.57-2023.txt)

### Enso Version

local build on branch wip/gmt/5105-post

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Monterey 12.6.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by Akirathan** [comment]
The same happens for me. Once a workspace is created, the error message disappears and the workspace is correctly displayed.

**Comment by PabloBuchu** [comment]
`https://cloud.enso.org/` is an old cloud and should not be used.

We do not have atm remote in browser environment. Please youse cloud mode / tab provided within the Enso Electron
