### ISSUE TITLE
Websocket error after opening a workspace on cloud.enso.org

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7758]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

After opening a new workspace on cloud.enso.org, I get the errror "Failed to initialize application: Invalid websocket specification: SyntaxError: Failed to construct 'WebSocket': The URL 'undefinedjson' is invalid.."

### Expected behaviour

I expect to be able to use Enso normally.

### How we can reproduce it?

1. cloud.enso.org
2. Log in with Google
3. Create a new workspace
4. Error appears

### Screenshots or screencasts

<img width="1672" alt="Screen Shot 2023-09-06 at 3 24 43 PM" src="https://github.com/enso-org/enso/assets/24406074/523a7012-bb2b-462a-a571-993c528c05ef">

### Logs

[2023-09-06T19-27-53.858Z-ide-2023.2.1-dev.log](https://github.com/enso-org/enso/files/12542592/2023-09-06T19-27-53.858Z-ide-2023.2.1-dev.log)
[client-Wed-Sep-6-16.28.55-2023.txt](https://github.com/enso-org/enso/files/12542593/client-Wed-Sep-6-16.28.55-2023.txt)
[server-Wed-Sep-6-16.28.57-2023.txt](https://github.com/enso-org/enso/files/12542594/server-Wed-Sep-6-16.28.57-2023.txt)

### Enso Version

local build on branch wip/gmt/5105-post

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

Google Chrome	114.0.5735.198 (Official Build) (arm64)

### Operating System

MacOS

### Operating System Version

Monterey 12.6.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by Akirathan** [comment]
The same behavior for me.

**Comment by PabloBuchu** [comment]
https://cloud.enso.org/ is an old cloud and should not be used.

We do not have atm remote in browser environment. Please youse cloud mode / tab provided within the Enso Electron

<blockquote><div><strong><a href="https://cloud.enso.org/">Enso Cloud: Loading</a></strong></div></blockquote>
