### ISSUE TITLE
Pasting code into a node also creates a new node with the pasted contents

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7759]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When I cmd-click a node to edit its code, and then cmd-v to paste code into it, it also creates a new node with the pasted contents.

### Expected behaviour

I expect it to only paste into the node I am editing.

### How we can reproduce it?

1. Run standalone IDE
2. Connect to cloud
3. Open workspace
4. Create a new node with [Enter]
5. Paste code into the node
6. See the additional node created

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/24406074/a9a16c7d-b246-4616-887f-850f7c10f4d7

### Logs

[2023-09-06T19-27-53.858Z-ide-2023.2.1-dev.log](https://github.com/enso-org/enso/files/12542621/2023-09-06T19-27-53.858Z-ide-2023.2.1-dev.log)
[client-Wed-Sep-6-16.28.55-2023.txt](https://github.com/enso-org/enso/files/12542622/client-Wed-Sep-6-16.28.55-2023.txt)
[server-Wed-Sep-6-16.28.57-2023.txt](https://github.com/enso-org/enso/files/12542623/server-Wed-Sep-6-16.28.57-2023.txt)
[2023-09-06T20-30-16.627Z-ide-2023.2.1-dev.log](https://github.com/enso-org/enso/files/12542624/2023-09-06T20-30-16.627Z-ide-2023.2.1-dev.log)
[client-Wed-Sep-6-17.07.44-2023.txt](https://github.com/enso-org/enso/files/12542625/client-Wed-Sep-6-17.07.44-2023.txt)
[server-Wed-Sep-6-17.07.47-2023.txt](https://github.com/enso-org/enso/files/12542626/server-Wed-Sep-6-17.07.47-2023.txt)

### Enso Version

local build on branch wip/gmt/5105-post

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Monterey 12.6.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by vitvakatu** [comment]
I can reproduce it. It seems like a flaw in the initial implementation.
