### ISSUE TITLE
Typo in an argument results in a Type_Error

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7761]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

A typo in `operator13.rename_columns (Maps.from_Vector [["Sum Right Matches Played in Tournament", "previous_tournament_matches"]])` (I used `Maps.from_Vector` instead of `Map.from_vector`) produced only a `Type_Error`.

### Expected behaviour

I expect it to say `Maps not found` or something like that.

### How we can reproduce it?

1. Run local IDE against cloud backend
2. Create a node with the text shown above
3. See `Type_Error`

### Enso Version

local build on branch wip/gmt/5105-post

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Monterey 12.6.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by vitvakatu** [comment]
@Akirathan seems like the engine issue, am I right?

**Comment by Akirathan** [comment]
@vitvakatu Yes, this seems like an engine issue. I am looking into it right now.

**Comment by Akirathan** [comment]
I can reproduce this with on this project:
[New_Project_19.zip](https://github.com/enso-org/enso/files/12575732/New_Project_19.zip)

The behavior of execution over CLI is different than the behavior when executed with IDE.

On CLI:
```
╭─ 4s │ ✘ 1 │ ~/dev/enso │ ☕ 17.0.7-graalce │ develop                                                                                                               ─╮
╰─ enso --run ~/enso/projects/New_Project_19                                                                                                                         ─╯
+ env 'JAVA_OPTS= ' /home/pavel/dev/enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run /home/pavel/enso/projects/New_Project_19
/home/pavel/enso/projects/New_Project_19/src/Main.enso:11:31: error: The name `Maps` could not be found.
   11 |     operator3.rename_columns (Maps.from_vector var1)
      |                               ^~~~
Aborting due to 1 errors and 0 warnings.
Execution finished with an error: Compilation aborted due to errors.
```

And in IDE, I get the aforementioned `Type_Error`.
