### ISSUE TITLE
Attaching visualizations and updating their data.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7789]

**Comment by farmaazon** [comment]
@somebody1234 Why do you need to get types of nodes? Generally we get types returned by nodes in expressionUpdates; but there is another task for extracting information from those: #7783

**Comment by somebody1234** [comment]
@farmaazon good point, relevant code has been removed. types are nice to have to be able to filter for only relevant visualizations, but i guess it's out of scope for this issue. i did try using `expressionUpdates` clientside but it only seemed to return types for two nodes (?!), so either way it's not usable so it should be removed from this PR.
