### ISSUE TITLE
Enso method to get a type/constructor by fully qualified name

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7797]
Currently within File_Format SPI code and the Expression Visitor, we get Enso objects by using the context and finding module and then type.

The idea of this ticket is to add methods to Meta to allow us to do this more correctly.

Goals:
- Get a type by FQN (giving us the ability to get methods).
- Make a new Enso object (want to expand expressions to allow us to make simple atoms).
- Eventual goal to be able to deserialize JSON better - first part would be Date/Time_Of_Day/Date_Time.

**Comment by JaroslavTulach** [comment]
FYI:

> Eventual goal to be able to deserialize JSON better - first part would be Date/Time_Of_Day/Date_Time

There [used to be an into mechanism](https://github.com/enso-org/enso/commit/ace459ed5321dd2141063990c6a42aa524b12774#diff-a202e21b60271f4c073e3f5ccf91c4c1767f8ba7a840a38ff5e10a3cced16406L88) in the `Json_Spec.enso`.

**Comment by JaroslavTulach** [comment]
So far I managed to find out how to get current `ModuleScope` of module `m.enso`:
```ruby
from Standard.Base import Meta

main =
    symbol = Meta.meta .anything
    typ = symbol.rename "Standard"
    [symbol.scope, typ]
```
returns `[ScopeModule[m], UnresolvedSymbol<Standard>]`. The next step is how to resolve a FQN in such scope.

The next step is available [in this commit](https://github.com/enso-org/enso/commit/8fbf42e5f031c4af7bd785d4de4e63d509af25df#r127466953). It tries to resolve only modules and types which are in scope by:
```java
    String name = symbol.getName();
    if (searchScope(symbol.getScope().getModule(), name) instanceof Object found) {
      return found;
    }
    for (var imp : symbol.getScope().getImports()) {
      if (searchScope(imp.getModule(), name) instanceof Object found) {
        return found;
      }
      for (var m : imp.getExports()) {
        if (searchScope(m.getModule(), name) instanceof Object found) {
          return found;
        }
      }
    }
```
but it is complicated and moreover it doesn't work properly - e.g. when one `from Standard.Base.Data import Vector` then also [boolean is found as this comment says](https://github.com/enso-org/enso/commit/8fbf42e5f031c4af7bd785d4de4e63d509af25df#r127466953).

**Comment by JaroslavTulach** [comment]
Let's go the simpler way and [search whole TopScope](https://github.com/enso-org/enso/pull/7885/files#r1335750626)...
