### ISSUE TITLE
ls/completion request returns not enough entries.

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7805]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

While investigating https://github.com/enso-org/enso/issues/7591, I noticed that my CB contains ridiculously small amount of entries.

After investigation, it turns out that the engine never returns us a single Constructor, Module, or Type. The only kind of entry in the response is Method. The statistics look the following:
(engine 9.11, default new project, creating new node without inputs and with zero input from the user)
```
Results: total=1049, modules=0, methods=1049, constructors=0, types=0, never=871, always=31, when_filtered=178, private=871
```

This means we received 1049 entries, all of which are methods. 871 are private (marked with a documentation tag), so we never show them. We show 31 entries by default and can show 178 in total when the user types something.

The issue also happens with the engine `8.16`.

### Expected behaviour

The `ls/completion` response must return modules and constructors as well (I'm not sure about types).

### How we can reproduce it?

You can use https://github.com/enso-org/enso/tree/wip/vitvakatu/debug-ls-completion branch with additional debug logging to get the similar output.

1. Create and open a new project
2. Press Enter to open CB
3. See the output in the console, also observe the list of displayed entries in the CB itself.

### Enso Version

e5425d35a05cc04cb36ea853b42ad6ce330f42a1

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by 4e6** [comment]
So far I can see that constructors are present in the response on the current develop. I'll try tomorrow with the nightly

**Comment by vitvakatu** [comment]
Just checked on `9.14`, I still see only methods.

**Comment by 4e6** [comment]
Ok, I see what the issue is. I was able to reproduce it today.
