### ISSUE TITLE
Choosing `Any.from` conversion even the required & actual types are the same

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7814]
If the marked line below is removed, the related tests (Http_Spec.enso) become non-deterministic.

```
Request_Body.from (that:Text) = Request_Body.Text that
Request_Body.from (that:File) = Request_Body.Binary that
# TODO: determine if this is needed.
Request_Body.from (that:Request_Body) = that             # <==========
Request_Body.from (that:Any) = Request_Body.Json that
```

Specifically, there are some failures resulting from a Request_Body being wrapped in another Request_Body, so that the following is passed from `Data.post` to `HTTP.post`:

`Request_Body.Json (Request_Body.json (Test_Type.Aaa "abc"))`

Some debugging revealed, of course, that it was choosing the `Any` conversion even though the required and actual types were both `Request_Body`.

When this broken test is duplicated at the top of the test file, not only does it pass, but all the tests pass. (This was true at a particular revision which I don't remember now, but it continues to happen at the latest revision in some form.)

https://github.com/enso-org/enso/pull/7700/files#diff-354bb8a4e6056d3e8f3599a64ec9125d8e8bcc36e3e4bdad6df28d5359f419b0R45

**Comment by JaroslavTulach** [comment]
There already is some support for [not doing the conversion](https://github.com/enso-org/enso/pull/7704/files#r1311550110) when the `that` and target types are the same. The code has however not been tested together with generic `Any.from` conversion.
