### ISSUE TITLE
Language Server able to run behind HTTPS and use WSS

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7839]
As discussed please add support.

Please align with Cloud on how to add certificate.
Locally should continue on http/ws and only allow 127.0.0.1 (or IP6 equivalent).

**Comment by hubertp** [comment]
Some background info on creating test certificates https://lightbend.github.io/ssl-config/CertificateGeneration.html
Sadly it is not possible to use `ssl-config` to configure server-side TLS out of the box meaning we have to go a long way and define all the keystores, key managers etc to obtain certificates, as documented in https://doc.akka.io/docs/akka-http/current/server-side/server-https-support.html

<blockquote><div><strong><a href="https://lightbend.github.io/ssl-config/CertificateGeneration.html">Generating X.509 Certificates · SSL Config</a></strong></div><div>SSL Config</div></blockquote>
<blockquote><img src="../images/favicon.ico" width="48" align="right"><div><strong><a href="https://doc.akka.io/docs/akka-http/current/server-side/server-https-support.html">Server HTTPS Support • Akka HTTP</a></strong></div><div>Akka Http: Modern, fast, asynchronous, streaming-first HTTP server and client.</div></blockquote>
