### ISSUE TITLE
Type ascriptions not accepted in tail position

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7841]
The PR #7796 gave us the ability to check / trigger conversions of types by a type ascription `(a : Xyz)`.

Apparently, this is not accepted by the parser in tail position.

```
from Standard.Base import all

f1 v = v.each x->
    y = x : Text
    y

f2 v = v.each x->
    x : Text

main =
    IO.println (f1 ["foo"])
    IO.println (f2 ["foo"])
```
yields
```
C:\NBO\repr\type-check-parse.enso:7:15: warning: Unused function argument x.
    7 | f2 v = v.each x->
      |               ^
C:\NBO\repr\type-check-parse.enso:8:5: error: Unexpected type signature.
    8 |     x : Text
      |     ^~~~~~~~
Aborting due to 1 errors and 1 warnings.
Execution finished with an error: Compilation aborted due to errors.
```

So `f1` is happily accepted but `f2` is not.

The repro itself shows how to work-around this - we just need to add an intermediate variable. Thus it's rather low priority, but still - it seems there is no reason to disallow a check in there.

**Comment by kazcw** [comment]
Currently the parser allows type signatures anywhere in a block. We could treat the last line of a block specially, since a type ascription is clearly more likely to be the intent in that case. In the meantime another option for a workaround would be `(x : Text)`, which is a type ascription because type signatures are not allowed inside expressions.

**Comment by radeusgd** [comment]
> In the meantime another option for a workaround would be `(x : Text)`, which is a type ascription because type signatures are not allowed inside expressions.

Actually, I checked `(x : Text)` and it does not work either:

```
from Standard.Base import all

f1 v = v.each x->
    y = x : Text
    y

f2 v = v.each x->
    (x : Text)

main =
    IO.println (f1 ["foo"])
    IO.println (f2 ["foo"])
```
still yields
```
C:\NBO\repr\type-check-parse.enso:7:15: warning: Unused function argument x.
    7 | f2 v = v.each x->
      |               ^
C:\NBO\repr\type-check-parse.enso:8:6: error: Unexpected type signature.
    8 |     (x : Text)
      |      ^~~~~~~~
Aborting due to 1 errors and 1 warnings.
Execution finished with an error: Compilation aborted due to errors.
```

**Comment by kazcw** [comment]
Huh. That is actually a separate bug, in `TreeToIr`; in the AST, that's a `TypeAnnotated` so it should not be treated as a type signature:
```
$ echo -n 'foo = x->    (y : Text)' | target/rust/release/enso-parser-debug
(BodyBlock #((Assignment (Ident foo) "=" (OprApp (Ident x) (Ok "->") (Group (TypeAnnotated (Ident y) ":" (Ident Text)))))))
```

**Comment by JaroslavTulach** [comment]
Investigating. Following diff seems to enable the proper behavior:
```diff
diff --git engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/FramePointerAnalysis.scala engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/FramePointerAnalysis.scala
index a524f70ebf..3270abef23 100644
--- engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/FramePointerAnalysis.scala
+++ engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/FramePointerAnalysis.scala
@@ -12,7 +12,8 @@ import org.enso.compiler.core.ir.{
   Function,
   Module,
   Name,
-  Pattern
+  Pattern,
+  Type
 }
 import org.enso.compiler.core.ir.module.scope.Definition
 import org.enso.compiler.core.ir.module.scope.definition.Method
@@ -163,6 +164,9 @@ case object FramePointerAnalysis extends IRPass {
         caseExpr.branches.foreach { branch =>
           processCaseBranch(branch)
         }
+      case asc: Type.Ascription =>
+        processExpression(asc.typed, graph)
+        processExpression(asc.signature, graph)
       case _ => ()
     }
     if (updateSymbols) {
diff --git engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
index 10f52ce9d5..fc01693c85 100644
--- engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
+++ engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/resolve/TypeSignatures.scala
@@ -315,7 +315,13 @@ case object TypeSignatures extends IRPass {
         lastSignature = None
         res
       case a => Some(resolveExpression(a))
-    } ::: lastSignature.map(errors.Unexpected.TypeSignature(_)).toList
+    } ::: lastSignature.map({
+      case asc @ Type.Ascription(_:Name, sig, comment, _, _) =>
+        asc.updateMetadata(
+          new MetadataPair(this, Signature(sig, comment))
+        )
+      case any => errors.Unexpected.TypeSignature(any)
+    }).toList
 
     block.copy(
       expressions = newExpressions.init,
diff --git engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
index c7b47140b4..5c7a306bb6 100644
--- engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
+++ engine/runtime/src/main/scala/org/enso/interpreter/runtime/IrToTruffle.scala
@@ -878,7 +878,8 @@ class IrToTruffle(
       // Type contexts aren't currently really used. But we should still check the base type.
       extractAscribedType(comment, typeInContext.typed)
     case t => {
-      t.getMetadata(TypeNames) match {
+      val res = t.getMetadata(TypeNames)
+      res match {
         case Some(
               BindingsMap
                 .Resolution(binding @ BindingsMap.ResolvedType(_, _))
@@ -1287,7 +1288,24 @@ class IrToTruffle(
         case binding: Expression.Binding => processBinding(binding)
         case caseExpr: Case =>
           processCase(caseExpr, subjectToInstrumentation)
-        case typ: Tpe => processType(typ)
+        case asc : Tpe.Ascription =>
+            val checkNode =
+              extractAscribedType(asc.comment.orNull, asc.signature)
+            if (checkNode != null) {
+              val body = run(asc.typed, binding, subjectToInstrumentation)
+              ReadArgumentCheckNode.wrap(body, checkNode)
+            } else {
+              processType(asc)
+            }
+        case typ: Tpe =>
+            val checkNode =
+              extractAscribedType("ascribed", typ)
+            if (checkNode != null) {
+              //val body = run(typ.typed(), binding, subjectToInstrumentation)
+              ReadArgumentCheckNode.wrap(null, checkNode)
+            } else {
+              processType(typ)
+            }
         case _: Empty =>
           processEmpty()
         case _: Comment =>
```

**Comment by kazcw** [comment]
In the `Tree` we have a distinction between two different `expression : Type` syntaxes:
- `TypeSignature`, which *declares* the type of `expression` and is used in statement context (e.g. in the older out-of-band-types method definition syntax)
- `TypeAnnotated`, which *evaluates to* `expression` and is used in a value context

I think this is an important syntactic distinction because it corresponds to a semantic distinction in whether the form causes `expression` to be evaluated. So I'm wondering, why not reflect this distinction in the IR representation?

**Comment by JaroslavTulach** [comment]
>     * `TypeSignature`, which _declares_ the type of `expression` and
>     * `TypeAnnotated`, which _evaluates to_ `expression` and is used in a value context
> I think this is an important syntactic distinction because it corresponds to a semantic distinction ... So I'm wondering, why not reflect this distinction in the IR representation?

I was surprised the `x: Text` is processed by `TypesSignatures`'s `lastSignature`, because it is not signature, but an expression. The diff addresses that directly in `TypesSignatures`, but I'll try to avoid this confusion in `TreeToIr`.

**Comment by kazcw** [comment]
> > ```
> > * `TypeSignature`, which _declares_ the type of `expression` and
> > * `TypeAnnotated`, which _evaluates to_ `expression` and is used in a value context
> > ```  
> >   
> > I think this is an important syntactic distinction because it corresponds to a semantic distinction ... So I'm wondering, why not reflect this distinction in the IR representation?
> 
> I was surprised the `x: Text` is processed by `TypesSignatures`'s `lastSignature`, because it is not signature, but an expression.

Yes, the problem is that IR doesn't distinguish type declaration statements (`Tree.TypeSignature`) from type-annotated expressions (`Tree.TypeAnnotated`)--in `TreeToIr` they are currently both translated to the same type `ir.Type.Ascription`.

**Comment by JaroslavTulach** [comment]
There are signatures like this [is_wanted : Node -> Boolean](https://github.com/enso-org/enso/blob/669ac97d9eb8c0f67e80959791c9fe86504b783e/distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso#L772) and then the signatures like
```ruby
                plusChecked a b =
                    x = a + b
                    x:Integer
```
so far I have problems to differentiate them. This second case is still `TypeSignature["    ", "x:Integer", [], Ident["", "x", [], Ident["", "x", 1, 1, false, 0, false, false]], TypeAnnotationOperator["", ":", 1, 1], Ident["", "Integer", [], Ident["", "Integer", 7, 7, false, 0, true, false]]]`. I cannot differentiate from the case:
```ruby
               plusChecked a b =
                    x:Integer
                    x = a + b
                    x
```
in this example, it is again `TypeSignature["    ", "x:Integer", [], Ident["", "x", [], Ident["", "x", 1, 1, false, 0, false, false]], TypeAnnotationOperator["", ":", 1, 1], Ident["", "Integer", [], Ident["", "Integer", 7, 7, false, 0, true, false]]]`.

> Those are both currently parsed as declarations, which I think we should change (in the parser):

If you want, **please do so**. I find way easier to just process the `lastSignature` as I [did in this patch](https://github.com/enso-org/enso/issues/7841#issuecomment-2397164927).

**Comment by kazcw** [comment]
Those are both currently parsed as declarations, which I think we should change (in the parser):

> Currently the parser allows type signatures anywhere in a block. We could treat the last line of a block specially, since a type ascription is clearly more likely to be the intent in that case. In the meantime another option for a workaround would be `(x : Text)`, which is a type ascription because type signatures are not allowed inside expressions.

**Comment by kazcw** [comment]
> There signatures like this [is_wanted : Node -> Boolean](https://github.com/enso-org/enso/blob/669ac97d9eb8c0f67e80959791c9fe86504b783e/distribution/lib/Standard/Base/0.0.0-dev/src/Data/XML.enso#L772) and then the signatures like
> 
> ```ruby
>                 plusChecked a b =
>                     x = a + b
>                     x:Integer
> ```
> 
> so far I have problems to differentiate them. This second case is still `TypeSignature[" ", "x:Integer", [], Ident["", "x", [], Ident["", "x", 1, 1, false, 0, false, false]], TypeAnnotationOperator["", ":", 1, 1], Ident["", "Integer", [], Ident["", "Integer", 7, 7, false, 0, true, false]]]`. I cannot differentiate from the case:
> 
> ```ruby
>                plusChecked a b =
>                     x:Integer
>                     x = a + b
>                     x
> ```
> 
> in this example, it is again `TypeSignature[" ", "x:Integer", [], Ident["", "x", [], Ident["", "x", 1, 1, false, 0, false, false]], TypeAnnotationOperator["", ":", 1, 1], Ident["", "Integer", [], Ident["", "Integer", 7, 7, false, 0, true, false]]]`.
> 
> > Those are both currently parsed as declarations, which I think we should change (in the parser):
> 
> If you want, **please do so**. I find way easier to just process the `lastSignature` as I [did in this patch](https://github.com/enso-org/enso/issues/7841#issuecomment-2397164927).

With the patch, the code runs correctly, so the patch solves the problem from a compiler perspective. From a broader tooling perspective, if the AST is wrong, and the compiler output is "right", that shows we have *two* bugs. #11289 fixes the immediate issue; I've opened separate issues for fixing the parser and then the compiler:
- #11293
- #11301
