### ISSUE TITLE
Polyglot classes ignored in the type check signature

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7858]
I have noticed that polyglot classes are ignored in typechecks - they act as if they wasn't there.

There does not seem to be a reason for this - especially as they are accepted for typechecking in `case of` statements:

```
from Standard.Base import all

polyglot java import java.time.format.DateTimeFormatter

f1 (x : DateTimeFormatter) = x.to_text
f2 (x : Text | DateTimeFormatter) = x.to_text
f3 (x : DateTimeFormatter | Text) = x.to_text
f4 (x) = case x of
    _ : DateTimeFormatter -> "DateTimeFormatter: "+x.to_text
    _ : Text -> "TEXT: "+x
    _ -> "OTHER"

main =
    d = DateTimeFormatter.ofPattern "yyyy"
    IO.println (f1 d).to_display_text
    IO.println (f2 "AAA").to_display_text

    IO.println (Panic.recover Any (f2 d)).to_display_text
    IO.println (Panic.recover Any (f3 d)).to_display_text

    IO.println (Panic.recover Any (f1 42)).to_display_text

    IO.println (Panic.recover Any (f4 d)).to_display_text
```

### Actual Behaviour

```
Value(YearOfEra,4,19,EXCEEDS_PAD)
AAA
Error: Type error: expected `x` to be Text, but got java.lang.Class.
Error: Type error: expected `x` to be Text, but got java.lang.Class.
42
DateTimeFormatter: Value(YearOfEra,4,19,EXCEEDS_PAD)
```

As we can see, the `Text | DateTimeFormatter` seems to get 'degenerated' into just `Text` and so the `d : DateTimeFormatter` fails this typecheck.

Interestingly also, in `f1` the checked `(x : DateTimeFormatter)` seems to also 'reduce' to an "unchecked" `(x)`, meaning that an integer `42` gets accepted without a type error.

### Expected behaviour

```
Value(YearOfEra,4,19,EXCEEDS_PAD)
AAA
Value(YearOfEra,4,19,EXCEEDS_PAD)
Value(YearOfEra,4,19,EXCEEDS_PAD)
Error: Type error: expected `x` to be DateTimeFormatter, but got Integer.
DateTimeFormatter: Value(YearOfEra,4,19,EXCEEDS_PAD)
```

**Comment by JaroslavTulach** [comment]
Interesting, @radeusgd - you are trying to use Java classes as Enso types. However they are not Enso types. Certainly not now. The easiest _"fix"_ is to make sure that usage of `DateTimeFormatter`  as _Enso type_ yields a compile time error. What do you think, @Akirathan? On the other hand, I understand directly using Java classes as types might be useful - see #8009.

**Update**: I got reminded that Java types do work in `catch` and `case` statements and one can use them in `Meta.type_of`. Looks like we should implement support for them in type signatures then.

**Comment by Akirathan** [comment]
> Interesting, @radeusgd - you are trying to use Java classes as Enso types. However they are not Enso types. Certainly not now. The easiest _"fix"_ is to make sure that usage of `DateTimeFormatter` as _Enso type_ yields a compile time error. What do you think, @Akirathan? On the other hand, I understand directly using Java classes as types might be useful - see #8009.

You mean to ensure that polyglot types are not used as type ascription during compile time?
