### ISSUE TITLE
Add `Text.substring` to allow for an easy short hand of `Text.take (start.up_to end)`

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7876]
Review Java, C#, Python, Alteryx and Excel should it be length or end as second argument...

Add a short hand function to get a sub-string from a Text value.

**Comment by Cassandra-Clark** [comment]
Going with length as second argument - this differentiates from text.take but is likely more intuitive and easier for complex use cases (i.e. variable substring lengths per row)

TBD if negative lengths should be accepted or should error - leaning towards error case.

**Comment by Cassandra-Clark** [comment]
Closed by accident, reopening.

Going with length as second argument. This differentiates from Text.take, but allows for more intuitive use, especially in cases like those with variable lengths per row.

TBD on if negative lengths should be accepted, but leaning towards no.
