### ISSUE TITLE
Java Values are displayed differently in the Chrome Devtools debugger

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7890]
Consider the following program:
```
from Standard.Base import all

main =
    d_enso = Date.new 2011 12 13
    d_java = Date.parse "2014-12-15"
    
    IO.println d_enso
    IO.println d_java
```
run it with `--inspect` and set the breakpoint at `IO.println d_java`.

We will see the following Scope:
![image](https://github.com/enso-org/enso/assets/1436948/4f883312-ea2e-4ef7-9d96-60678d592134)

We can see that the value coming from Java is displayed differently than the one from Enso, even though both are a `Date`. It is probably because Enso did not manage yet to perform its polyglot conversions. Shall they be performed before displaying the object?

Another issue can be seen when we interact with the REPL:
![image](https://github.com/enso-org/enso/assets/1436948/cb9c3870-6e9f-441c-98e1-aca55c527b23)

We can see that values coming from polyglot calls (e.g. `next`) behave Java-like and the ones that are 'correctly' displayed come from builtin methods (e.g. `Date_Time.date`) which ensure the Enso polyglot conversion happens.

----

I'm not sure if this is a bug - although ideally the behaviour of the Debugger should be consistent regardless of where the value is coming from.

What may be especially misleading is that the Java values display all kinds of Java methods they have:
![image](https://github.com/enso-org/enso/assets/1436948/68417e19-e2be-499d-8537-677003436b84)

But these methods won't work, because of how the Enso interop works (once we do a call, we _do_ the polyglot conversion and it's no longer a Java `LocalDate` but an `EnsoDate`):
![image](https://github.com/enso-org/enso/assets/1436948/2278169c-92de-4b72-9b55-891a17674a79)
![image](https://github.com/enso-org/enso/assets/1436948/21e79498-f0a1-4ee7-8db7-43342de018b2)

That is quite misleading, so I think ideally we should fix it and show the value for what it is to the user - an Enso date. I'm not sure how big of a priority this is though.

**Comment by JaroslavTulach** [comment]
> Enso did not manage yet to perform its polyglot conversions. 

Yes, Enso doesn't convert non-primitive values until they need to be converted.

> Shall they be performed before displaying the object?

No. The general rule is to convert values as late as possible.

> show the value for what it is to the user - an Enso date

There is a [concept of a view](https://www.graalvm.org/truffle/javadoc/com/oracle/truffle/api/TruffleLanguage.html#getLanguageView(C,java.lang.Object)) `EnsoLanguage` could probably convert those values (for example by passing them to `identity` function).

**Comment by JaroslavTulach** [comment]
> * Double primitive wrapped in `WithWarnings` answers to `hasMetaObject` with false??

- I believe this is a result of the #8685 
- the TCK (probably) asserts primitive values to not have a meta object
- at least I think I had to do a delicate dance around the _meta objects_ for Enso objects
- for example I am sure that `Nothing` - e.g. `isNull` cannot have a meta object according to the TCK

**Comment by JaroslavTulach** [comment]
> * Need to tweak some existing types, like `EnsoBigInteger` because of various (at first sight unrelated) test failures.

One of my first tasks in Enso was to handle dates, times and datetimes interop properly. That was done by converting the values to Enso before method invocation:
- #3374
- the story of `BigInteger` support is more complicated
- however I think it (also) touches TCK - the TCK requires the foreign `BigInteger` to go thru the identity function while _keeping identity_
- that may make its support special

**Comment by Akirathan** [comment]
> the TCK (probably) asserts primitive values to not have a meta object

@JaroslavTulach That does not seem right. For a primitive `int i = 5432` created in host, this is not true:
```java
  @Test // Put this test inside MetaObjectTest.java
  public void myTest() {
    var primNum = ctx.asValue((int) 5432);
    assertThat(primNum.fitsInInt(), is(true));
    assertThat(primNum.getMetaObject(), is(notNullValue()));
  }
```
This test passes. So host language clearly assigns meta objects to primitive values. Do you think guest languages should have a different contract?

**Comment by Akirathan** [comment]
Moreover, the current state of Enso primitive values is as follows (this test passes on develop):
```java
  @Test
  public void myTest() {
    var g = ValuesGenerator.create(ctx, ValuesGenerator.Language.ENSO);
    g.numbers()
        .stream()
        .filter(Value::fitsInLong)
        .forEach(num -> {
          assertThat(num + " Enso primitive long numbers don't have meta object",
              num.getMetaObject(),
              is(nullValue()));
        });
    g.numbers()
        .stream()
        .filter(num -> !num.fitsInLong() && !num.fitsInDouble() && num.fitsInBigInteger())
        .forEach(num -> {
          assertThat(num + " Enso big integer numbers have meta object",
              num.getMetaObject(),
              is(notNullValue()));
        });
    g.booleans()
        .forEach(bool -> {
          assertThat(bool + " Enso primitive booleans have meta object",
              bool.getMetaObject(),
              is(notNullValue()));
        });
  }
```
In other words. Primitive numbers (those that fit inside long) don't have a meta object, but big integers have. Moreover, primitive booleans have meta objects. This is confusing and not consistent. I assume that we should ensure that all the primitive Enso values have meta objects. Right?

**Comment by Akirathan** [comment]
Host primitive boolean also has meta object:
```java
  @Test
  public void javaBoolHasMeta() {
    var b = ctx.asValue(true);
    assertThat(b.isBoolean(), is(true));
    assertThat(b.getMetaObject(), is(notNullValue()));
  }
```

**Comment by Akirathan** [comment]
The same is true for js and python - their primitive values have meta objects: (the following test passes on develop as well)
```java
  @Test
  public void guestBoolHasMeta() {
    var jsBool = ctx.eval("js", "true");
    var pyBool = ctx.eval("python", "True");
    assertThat(jsBool.isBoolean(), is(true));
    assertThat(pyBool.isBoolean(), is(true));
    assertThat(jsBool.getMetaObject(), is(notNullValue()));
    assertThat(pyBool.getMetaObject(), is(notNullValue()));
  }

  @Test
  public void guestIntHasMeta() {
    var jsInt = ctx.eval("js", "42");
    var pyInt = ctx.eval("python", "42");
    assertThat(jsInt.isNumber(), is(true));
    assertThat(pyInt.isNumber(), is(true));
    assertThat(jsInt.getMetaObject(), is(notNullValue()));
    assertThat(pyInt.getMetaObject(), is(notNullValue()));
  }

```

**Comment by JaroslavTulach** [comment]
> So host language clearly assigns meta objects to primitive values. Do you think guest languages should have a different contract?

No, if ...

> > the TCK (probably) asserts primitive values to not have a meta object

...the TCK is OK with that, then having ...

> ...long(s)... don't have a meta object, but big integers have

... **consistency** is **important**.

**Comment by JaroslavTulach** [comment]
>     * Implement this contract in a separate PR - [Implement hasLanguage interop message for all enso objects #11538](https://github.com/enso-org/enso/pull/11538)
>       * Inspired by GraalJS and GraalPython 

I am not sure what you mean by _inspired_, but [PythonAbstractObject](https://github.com/oracle/graalpython/blob/040cfa7b72b4503fa338e3c6fab0456bb4a8a4c8/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/objects/PythonAbstractObject.java#L35) has to be `abstract` because it `extends DynamicObject`. Enso objects don't use `DynamicObject`.

**Comment by Akirathan** [comment]
> I am not sure what you mean by _inspired_, but [PythonAbstractObject](https://github.com/oracle/graalpython/blob/040cfa7b72b4503fa338e3c6fab0456bb4a8a4c8/graalpython/com.oracle.graal.python/src/com/oracle/graal/python/builtins/objects/PythonAbstractObject.java#L35) has to be `abstract` because it `extends DynamicObject`. Enso objects don't use `DynamicObject`.

Yes, but how else would you ensure that [hasLanguage](https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/InteropLibrary.java#L2416) and [getLanguage](https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/InteropLibrary.java#L2434) messages are implemented for every object? `@ExportMessage` annotation does not work on default methods on interfaces, it has to be on a method in abstract class.

**Comment by JaroslavTulach** [comment]
> how else would you ensure that [hasLanguage](https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/InteropLibrary.java#L2416) and [getLanguage](https://github.com/oracle/graal/blob/master/truffle/src/com.oracle.truffle.api.interop/src/com/oracle/truffle/api/interop/InteropLibrary.java#L2434) messages are implemented for every object? 

I would write a test that uses `ValuesGenerator` and checks that all Enso values support this message.

> `@ExportMessage` annotation does not work on default methods on interfaces, it has to be on a method in abstract class.

I see. I am checking with Christian Humer, but I guess you are right.
