### ISSUE TITLE
Spurious warning when loading inner Java classes into Enso

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#7895]
https://github.com/enso-org/enso/commit/6cbd111bad50afeeb6bac97791be667ab7f54c22 Added support for Espresso.
It also improved support for loading inner classes.

Unfortunately since then we can get spurious warnings:
```
[WARN] [2023-09-20T14:06:50+02:00] [enso.org.enso.interpreter.runtime.EnsoContext] null
com.oracle.truffle.host.HostLanguage$HostLanguageException: Access to host class com.ibm.icu.text.Normalizer2.Mode is not allowed or does not exist.
[WARN] [2023-09-20T14:06:51+02:00] [enso.org.enso.interpreter.runtime.EnsoContext] null
com.oracle.truffle.host.HostLanguage$HostLanguageException: Access to host class java.net.http.HttpRequest.BodyPublisher is not allowed or does not exist.
```

Steps to reproduce:
```
> cat hello-world.enso 
from Standard.Base import all

main =
  IO.println "Hello World!"
```
```
> built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso  --run hello-world.enso
[WARN] [2023-09-26T12:16:00+02:00] [enso.org.enso.interpreter.runtime.EnsoContext] null
com.oracle.truffle.host.HostLanguage$HostLanguageException: Access to host class com.ibm.icu.text.Normalizer2.Mode is not allowed or does not exist.
[WARN] [2023-09-26T12:16:00+02:00] [enso.org.enso.interpreter.runtime.EnsoContext] null
com.oracle.truffle.host.HostLanguage$HostLanguageException: Access to host class java.net.http.HttpRequest.BodyPublisher is not allowed or does not exist.
Hello World!
[WARN] [2023-09-26T12:16:00+02:00] [enso.org.enso.compiler.SerializationManager] Serialization manager has been shut down.
```

**Comment by radeusgd** [comment]
The `catch` within
https://github.com/enso-org/enso/blob/6cbd111bad50afeeb6bac97791be667ab7f54c22/engine/runtime/src/main/java/org/enso/interpreter/runtime/EnsoContext.java#L418-L438

is used as part of a control flow primitive and catching the exception does not necessarily mean there is a problem there - it may be part of normal control flow, so we shouldn't log there (or use trace level at most, but IMO there is not much gain from the log message).

If we want to have a log around that place it should instead be just before the `return null` - at this point we know that the resolution has failed.

**Comment by JaroslavTulach** [comment]
> part of normal control flow

Yes, it is a part of normal control flow.
