### ISSUE TITLE
Unexpected difference of behaviour if the `|>` composition operator spans multiple lines

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7900]
Run the following program:
```ruby
from Standard.Base import all

main =
    x = "x" |> (_ + "a") |> (_ + "b") |> (_ + "c")
    y = "y" |>
        (_ + "a") |>
        (_ + "b") |>
        (_ + "c")
    
    IO.println x
    IO.println y
```

### Actual behaviour

It yields:
```
xabc
yc
```

### Expected behaviour

I would expect both expressions to be equivalent, just one of them is split into multiple lines:
```
xabc
yabc
```

I don't understand why the behaviour differs. Maybe it's not a bug but a _'feature'_ and I don't understand some edge case of operator precedence that is happening here. Still, this current behaviour is rather confusing and IMO it should rather behave as described in _Expected behaviour_.

**Comment by kazcw** [comment]
https://github.com/enso-org/design/blob/wip/wd/enso-spec/epics/enso-spec-1.0/03.%20Code%20format%20and%20layout.md#body-code-blocks

<blockquote><img src="https://github.githubassets.com/images/modules/open_graph/github-logo.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 100 million people use GitHub to discover, fork, and contribute to over 330 million projects.</div></blockquote>

**Comment by radeusgd** [comment]
> [enso-org/design@`wip`/wd/enso-spec/epics/enso-spec-1.0/03.%20Code%20format%20and%20layout.md#body-code-blocks](https://github.com/enso-org/design/blob/wip/wd/enso-spec/epics/enso-spec-1.0/03.%20Code%20format%20and%20layout.md?rgh-link-date=2023-09-26T13%3A30%3A24Z#body-code-blocks)
> 
> > <img alt="" width="48" src="https://camo.githubusercontent.com/e3498776c2fc6e103c368b2e0a90aac9dbb53e742fc03c294b4c4073cc7e7bd0/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f696d616765732f6d6f64756c65732f6f70656e5f67726170682f6769746875622d6c6f676f2e706e67"><img alt="" height="14" src="https://camo.githubusercontent.com/b6a12909f1e31185a69a73d59208c507a992236d3230f9fc18e85058ae3d19e7/68747470733a2f2f6769746875622e6769746875626173736574732e636f6d2f66617669636f6e732f66617669636f6e2e737667"> GitHub**[Build software better, together](https://github.com)**GitHub is where people build software. More than 100 million people use GitHub to discover, fork, and contribute to over 330 million projects.

Oh ok, thanks for the explanation!

This is quite unintuitive in this example though 😅

**Comment by GregoryTravis** [comment]
What is the meaning of this first line (from the block version):

```
(_ + "a") |>
```

?

**Comment by radeusgd** [comment]
It can be rewritten as:
```
f x = x + "a"
f.|>
```
where `|>` is:
```
Any.|> self ~function = function self
```

So essentially the whole statement is:
```
y-> y (x-> x + "a")
```

Which doesn't make much sense.

----

My intent was that it would act like the one-line version, i.e.
```
(("x" |> (_ + "a")) |> (_ + "b")) |> (_ + "c")
```
which should reduce to
```
(_ + "c") ((_ + "b") ((_ + "a") "x"))
```
which will then reduce to
```
(("x" + "a") + "b") + "c"
```

**Comment by GregoryTravis** [comment]
Right, I know the meaning of `|>`, but I was wondering if it makes sense to interpret your block as a series of separate values when two of them are like `(_ + "a") |>`. I see that it is valid and follows the spec, but I wonder if that should be an unused value warning, since it's neither a side-effect nor a binding.

**Comment by radeusgd** [comment]
> Right, I know the meaning of `|>`, but I was wondering if it makes sense to interpret your block as a series of separate values when two of them are like `(_ + "a") |>`. I see that it is valid and follows the spec, but I wonder if that should be an unused value warning, since it's neither a side-effect nor a binding.

Ah, yes I think ideally it should be an unused value warning, but currently we have no way of telling if `x.|>` _does not have_ side effects. Ideally, we should be able to report such unused values, I even proposed it a long time ago: https://github.com/enso-org/enso/issues/5430

**Comment by kazcw** [comment]
Maybe we could warn despite potential side effects? Although consistent application of language semantics requires us to allow someone to create an operator section to invoke the side effect of partially-applying the operator, we are free to discourage it :smile:

**Comment by GregoryTravis** [comment]
Yes @kazcw I agree that the behavior is consistent with the spec and the overall approach to whitespace and blocks; in this case an 'unused value' warning would be enough to let someone know that they aren't getting what they probably expected.

**Comment by radeusgd** [comment]
> Maybe we could warn despite potential side effects? Although consistent application of language semantics requires us to allow someone to create an operator section to invoke the side effect of partially-applying the operator, we are free to discourage it 😄

You mean to add a warning for calls like `x.<op>` where `<op>` is an operator?

**Comment by radeusgd** [comment]
Ideally we'd 'just' implement https://github.com/enso-org/enso/issues/5430 and get a warning for all kinds of unused values like that.

But I guess a special case for the operators could work as well.

**Comment by kazcw** [comment]
Well if we will have a general unused value warning, that would cover it.

BTW, there is a syntax in the spec and parser for this use case. The implementation is incomplete: #7904.

**Comment by radeusgd** [comment]
> BTW, there is a syntax in the spec and parser for this use case. The implementation is incomplete: #7904.

Yes, that's exactly what I was looking for.

After all I ended up merging all of this into one ultra-long line:
```
t2 = t1 . set (t1.at "short_unbounded" . cast (Value_Type.Char size=1000)) "short_1000" . set (t1.at "short_unbounded" . cast (Value_Type.Char size=10)) "short_10" . set (t1.at "long_unbounded" . cast (Value_Type.Char size=400)) "long_400" . set (t1.at "short_unbounded" . cast Value_Type.Mixed) "short_mixed"
```
That is basically unreadable, so getting the better multiline support would be cool.

**Comment by kazcw** [comment]
I think this is covered by #7904 (which will provide a syntax addressing this use case) and #5430 (which will make the compiler's interpretation of the non-working syntax here more clear).
