### ISSUE TITLE
Restructuring XML into Table form

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7901]
Similar to the new way of processing JSON to an In-Memory table, we want a simple way to convert an `XML_Document` and `XML_Element` to a table.

Design of what makes sense.

- Name would be a column,
- Namespace should be added if present as a column.
- Attributes would become columns.
- Children becomes a column with `Vector XML_Element`
- Text becomes a column (if multiple concatenate).

Extend the `expand_vector_to_rows` function to explode a `Vector` to a set of rows repeating the other.

If an empty node then no value or children.
```xml
<Library catalog="Fiction" letter="A" />
``` 
or
```xml
<Library catalog="Fiction" letter="A"></library>
```

| Name | @catalog | @letter |
| --- | --- | --- |
| Library | Fiction | A |

If no children and only a text inside becomes.
```xml
<Library catalog="Fiction" letter="A">
    Hello
</Library>
```

| Name | @catalog | @letter | value |
| --- | --- | --- | --- |
| Library | Fiction | A | "Hello"

If children then instead of Value add Children.

```xml
<Library catalog="Fiction" letter="A">
    Hello
    <Book author="An Author">My Book<Book>
    World
    <Book author="Another Author">Your Book<Book>
    <Magazine month="August-2023" series="AutoCar">Cheap Cars For You</Magazine>
</Library>
```

| Name | @catalog | @letter | children |
| --- | --- | --- | --- |
| Library | Fiction | A | ["Hello", Book, "World", Book, Magazine] | 

if then expanded to row:

| Name | @catalog | @letter | children |
| --- | --- | --- | --- |
| Library | Fiction | A | Hello |
| Library | Fiction | A | Book "My Book" |
| Library | Fiction | A | World |
| Library | Fiction | A | Book "Another Book" |
| Library | Fiction | A | Magazine "Cheap Cars For You" |

if then expanded to columns (default prefix is `column name plus a ,`:

| Name | @catalog | @letter | children.Name | children.@author | children.Value | children.@month | children.@series |
| --- | --- | --- | --- | --- | --- | --- | --- |
| Library | Fiction | A | *Nothing* | *Nothing* | Hello | *Nothing* | *Nothing* |
| Library | Fiction | A | Book | An Author | My Book | *Nothing* | *Nothing* |
| Library | Fiction | A | *Nothing* | *Nothing* | World | *Nothing* | *Nothing* |
| Library | Fiction | A | Book | Another Author | Another Book | *Nothing* | *Nothing* |
| Library | Fiction | A | Magazine | *Nothing* | Cheap Cars For You | August-2023 | AutoCar |

**Comment by jdunkerley** [comment]
```
xml_doc = Data.read "myfile.xml"
table = xml_doc.to Table . expand_to_rows "children" . expand_column "children"
with_row_number = table.add_row_number
renamed = table.cross_tab ["Row"] children.Name (First children.Value)
output = with_row_number.drop_columns [] . join ....
```

**Comment by GregoryTravis** [comment]
Namespace support will happen in: https://github.com/enso-org/enso/issues/8082
