### ISSUE TITLE
HTTP spec should spawn its own test server

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#7903]
The HTTP spec currently relies on the build system to spawn a test server for it to connect to. This does not happen locally without taking extra steps, so it is generally only run in CI.

To make this work automatically, the test will have to allocate an unused port for each run, just as the build system does now.

**Comment by radeusgd** [comment]
Some more tests are now relying on the HTTP test server.

If possible, we should try to make sure that only one server is spawned for all tests that need it within `Base_Tests`, to avoid spawning them multiple times.

Moreover, `Table_Tests` also need a way to run it.

**Comment by radeusgd** [comment]
When was this completed? I'm not aware of it being done. Did you mean to close as not planned?

**Comment by GregoryTravis** [comment]
Yes -- re-closed as not planned.
