### ISSUE TITLE
Demo scenes in GUI2

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7916]
We, devs, would like to have a possibility to test visuals of components without connecting to the backend, like the demo scenes in the old GUI. We could use Historie framework https://histoire.dev/guide/vue3/getting-started.html to manage such scenes.

In scope of this task is to make a scene displaying our project view with some mocked nodes, where we also could see the component browser.

**Comment by somebody1234** [comment]
oh, also adding mocked suggestion db store and project store
