### ISSUE TITLE
### META-DATA ### get duplicated (on external edits) and yield Unexpected expression

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#7921]
When I compile attached file with `2023.2.1-nightly.2023.9.28` I get:
```bash
$ /enso/built-distribution/enso-engine-0.0.0-dev-linux-amd64/enso-0.0.0-dev/bin/enso --run src/Main.enso 
src/Main.enso:22:5: warning: Unused variable operator13.
   22 |     operator13 = Main.func1 operator1 operator3 text1
      |     ^~~~~~~~~~
src/Main.enso:27:5: warning: Unused variable operator6.
   27 |     operator6 = operator5.map (x -> Main.funct1 (x.at 0) operator3 (x.at 1))
      |     ^~~~~~~~~
src/Main.enso:41:5: warning: Unused pattern binding x.
   41 |     x -> "Insufficient"
      |     ^
src/Main.enso:44:1: error: Unexpected expression.
   44 | [[{"index":{"value":5},"size":{"value":8}},"1a936fb5-1fe2-493d-9bb4-2218ba91b3be"],[{"index":{.........
```
the file is **result of IDE only manipulations** - e.g. the IDE is capable to create a file which isn't executable from the command line. Shall we be more robust when parsing metadata? Shalln't metadata be _prefixed with four spaces_ to really look like comment?

[Main.enso.gz](https://github.com/enso-org/enso/files/12756261/Main.enso.gz)

Obviously deleting the metadata section fixes the problem. I suspect the parser error goes to 2023.2.1-nightly.2023.9.28@kazcw - pre-assigning. However this is not the first time I get this error - happens to me almost every more complex bookclub that requires me to switch to CLI.  Maybe IDE guys could take a look as well.

**Comment by farmaazon** [comment]
@JaroslavTulach in this specific case, have you used the IDE's code editor, or the `trend` and `status` functions have been added _before_ opening IDE?

The code which creates the entire source file leaves no doubts: it always creates three newlines before METADATA tag:
```rust
        let before_tag = "\n".repeat(NEWLINES_BEFORE_TAG);
        let before_idmap = "\n";
        // Blah, blah, blah...
        let content = format!(
            "{code}{before_tag}{METADATA_TAG}{before_idmap}{id_map}{before_metadata}{metadata}"
        );
```
Where
```rust

const NEWLINES_BEFORE_TAG: usize = 3;
const METADATA_TAG: &str = "#### METADATA ####";
```
 I really doubt any bug would remove these newlines. Moreover, this code is then used to create source for computing hashes, so the IDE hashes should always represent the code with 3 newlines before the tag. Very strange. @JaroslavTulach I guess you don't have any IDE logs now, but perhaps you still have LS logs where possibly is an information about synchronization errors?

**Comment by JaroslavTulach** [comment]
Here are [all the logs](https://github.com/enso-org/enso/files/12761877/log.txt) I have since yesterday. Meanwhile I restarted the server at least once.

> have you used the IDE's code editor, or the trend and status functions have been added before opening IDE?

I definitely went to external editor and added the `trend` and `status` function. I believe I restarted the IDE then, but it is possible the IDE received some _"external files modified"_ notifications before the restart.

> bug would remove these newlines

If you take a look at the [attached file](https://github.com/enso-org/enso/files/12756261/Main.enso.gz) , you'll notice the metadata are duplicated (I haven't noticed that at first sight).

**Comment by farmaazon** [comment]
> If you take a look at the [attached file](https://github.com/enso-org/enso/files/12756261/Main.enso.gz) , you'll notice the metadata are duplicated (I haven't noticed that at first sight).

You are right, that explains all the mystery. So I would start with checking what code editor does: perhaps after edit there we remove one critical newline somewhere, then we parse the entire file treating metadata as part of the code and then glue again with metadata we know.

**Comment by farmaazon** [comment]
In GUI2 we have a completely different mechanism of sending updates to engine. If any similar bag appears, it should be reported as a new issue.
