### ISSUE TITLE
Documentation in new Component Browser

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#7924]
This task is about porting the old HTML documentation generator to the new GUI.

**Comment by vitvakatu** [comment]
A big part of the task would be bringing the doc parser from Rust to JS.

A rough list of subtasks:

- Get intermediate representation in JS
- Prepare Vue components for displaying IR on the screen
- Implement integration between links and breadcrumbs (which are nonexistent now!)
- Add features missing in the ide1 (mostly better display representation for tags)

**Comment by farmaazon** [comment]
> Implement integration between links and breadcrumbs (which are nonexistent now!)

This could be moved to "Navigating Documentation in new Component Browser" task, which is in the #7685 list, but not converted to issue yet.
