### ISSUE TITLE
[GUI2] Create documentation for new gui project

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#7942]
- Add high-level documentation file explaining major architectural features
- Add contributing documentation explaining how to run dev environment and how to build editor distribution.

**Comment by farmaazon** [comment]
Also update the style guide for Typescript. It should contain rather a list of preferences; anything we would like to enforce should be enforced automatically.

**Comment by AdRiley** [comment]
Duplicate of #8483 or different?

**Comment by farmaazon** [comment]
It was meant to be done long before removing GUI1. As we are on the doorstep of the latter, this one may be closed.
