### ISSUE TITLE
Investigate hosting yjs server within GraalJS

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#7954]
Gui2 decided to bet on [y.js](https://github.com/yjs/yjs). In order to avoid back and forth sending of package between processes, let's investigate hosting of the [y-websocket server](https://github.com/yjs/y-websocket) in language server process itself.

Language server process is capable to execute [Graal.js](https://github.com/oracle/graaljs) - compliant EcmaScript implementation on top of JVM. All that is needed is to polyfill the WebSocket server API.

Initial polyfill is available at https://github.com/JaroslavTulach/graaljs-websocket

**Comment by JaroslavTulach** [comment]
## Loading y-websocket Server

There is a `graalvm/bin/js` command to launch [Graal.js](https://github.com/oracle/graaljs) in the [GraalVM](http://graalvm.org). If not, try `graal/bin/gu install js`. I am able to use that support with:
```bash
$ git clone https://github.com/yjs/y-websocket.git
$ cd y-websocket
$ rm -rf *; git checkout -f 05b2f894d5237005b70a3d3ab01f040111371506

$ npm install
$ npm run dist

$ cat >fill.js
function clearTimeout() {
}
function clearInterval() {
}
^D
$ /graalvm/bin/js --experimental-options --js.commonjs-require --js.commonjs-require-cwd=. fill.js ./dist/y-websocket.cjs
```
e.g. [Graal.js](https://github.com/oracle/graaljs) (**without** node.js support) can load `y-websocket.cjs` and its dependencies.

**Comment by JaroslavTulach** [comment]
Using [WebPack.js](https://webpack.js.org/guides/development/) to generate single JavaScript file to send to Graal.js - easier than trying to [convince Graal.js to understand mixture of CommonJS and ES6 modules](https://graalvm.slack.com/archives/CN9L59P61/p1700499347887409?thread_ts=1700499044.997459&cid=CN9L59P61).

See [the commit](https://github.com/JaroslavTulach/graaljs-websocket/commit/265bd0c064bcaf328d242f8bb013d494fba3b945)

I assume packing things via webpack is OK, @Frizi? A standard thing among JavaScript developers, right?

**Comment by JaroslavTulach** [comment]
A meeting discussing _Yjs synchronization with Engine_ has just finished. Here are the meeting notes. Feel free to update them to be more accurate:

- Issue: versioning of AST between engine & IDE
- @Frizi: can IDE send the code for the y.js to run on the engine side?
- is the [API going to be simpler if it is AST](https://github.com/enso-org/enso/issues/9257#issuecomment-1978474823)?
- @4e6: gradually move...
    - step no. 1: Add UUID to each AST element & use UUIDs in other protocols/places

Question: y.js server in JVM. **Good** or bad? Proceed?
- **Pros**: eliminates one element of the infrastructure
    - step no. 1: run current y.js server in JVM (almost) unchanged
- **Cons**: question of compatibility still remains
- Need **batch changes** without engine seeing "middle stages"

@4e6 prepares a PR to **move the server into the JVM**.

**Comment by JaroslavTulach** [comment]
The [strategic vision document](https://docs.google.com/document/d/1bKX2swSW-6ACLkTt623adrT45-SeANom4vv3w6XvqKc) has just been written. It describes why this _hosting of y.js server in Graal.js_ is an important enabler.

**Comment by JaroslavTulach** [comment]
Everything is ready for consumption by @PabloBuchu & co.
