### ISSUE TITLE
Accepting node edit closes visualization

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#7977]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When accepting or cancelling node edit, the currently open visualization closes.

### Expected behaviour

Visualization must preserve its state.

### How we can reproduce it?

1. Open visualization on a node.
2. Edit the node. Accept the edit.
3. Observe visualization is no longer opened.

### Enso Version

0228022809cb2f5a11b9ae7e8b2db4497e2c103b

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by farmaazon** [comment]
Fixed in GUI2
