### ISSUE TITLE
Implement `Table.lookup_and_replace` for the Database backend

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#7981]
This has been split off from #7749 as we realized there are more nuances to the Database implementation than initially anticipated, so it requires additional analysis how to do properly.

The goal of this task is to decide about the compromises related to the various approaches we can take and implement the missing feature.

-----

Highlighted requirements of `lookup_and_replace`:
1. if `allow_unmatched_rows=False`, if a row of the input table has no corresponding row in the lookup, `Unmatched_Rows_In_Lookup` should be raised;
2. if the lookup table contains duplicate entries with the same key, at least for the keys that are being matched from the source table (other keys can be ignored), a `Non_Unique_Key` error should be raised;
3. overall the operation should not change the rows from the input; no rows may be dropped and existing rows cannot get duplicated.

**Comment by radeusgd** [comment]
# Context

> Note that possibly similar trade-offs may be encountered with other operations that are more 'multi' stage than just simply composing queries, for example `cross_tab`. We may try to use some of the ideas mentioned below for it as well.

## Why the naive solution will not work?

The naive solution ports directly the logic from in-memory to the database backend.

It would perform the checks for uniqueness of lookup keys and if `allow_unmatched_rows=False` check if all input rows have a match. Then it will return the query performing a join that does the 'proper' lookup and merges the two tables.

This approach is, however, incorrect. The checks are performed at 'construction time', but the join query that is constructed is just an SQL query that may be materialized later. We have no guarantees that the Database will not be modified in the meantime. Thus the checks performed at construction time may no longer be valid when the query is materialized. Thus the result of that query may very well break the invariants that the operation assumes - this is not acceptable.

Possible bad scenarios between check and materialize:
- lookup row gets added with a duplicate key - thus a simple join will now duplicate all rows from the source table that correlate with such duplicated key. This essentially violates highlighted requirements (1) and (3);
- lookup row gets deleted - violating (2) if `allow_unmatched_rows=False` - even if the check succeeded initially, at the moment of materialization we may get an unmatched row;
- input table row gets added - violating (2) if `allow_unmatched_rows=False` - even if the check succeeded initially, at the moment of materialization we may get an unmatched row, because the new row may not have a matching key in the lookup table.

I think violating the requirement (3) is the worst problem, because the user will never expect this operation to duplicate data. (1) and (2) are not good either because the user should be able to rely on the errors and here they become unreliable - they may not be raised but the underlying problem may still occurr.

## Alternative solutions

### Materializing the query into a temporary table

We can materialize the query into a temporary table that lives as long as the returned `Table` reference. This way all the checks are done within the same transaction that creates the temporary table. The data is 'frozen' into the result table so the checks performed at creation time will not 'get invalidated' by changes to the input tables, because the output date will not change unless the whole operation is recomputed.

Pros:
- simple to implement and relatively simple to keep track for users
- for some scenarios keeping the data in a temporary table may mean we avoid re-doing the join work multiple times
Cons:
- the DB has less optimization opportunities (e.g. a FILTER after the lookup can be moved upward by the DB optimizer to make the lookup much smaller; if the sub-query is materialized, that cannot be done and the whole sub-query needs to be constructed even if many of the results are discarded in the next operation);
- the temporary table may be very large (we can be joining a HUGE source table with a relatively small lookup table), we can exhaust DB server's resources. The temporary tables are not cleared immediately - we need the Enso Table reference to be GCed first.

### Adding checks that are run upon materialization

We can extend query metadata to include checks that are run inside of a transaction when materializing a query containing subqueries with such checks.

Pros:
- we can give clear error messages, the same as with checks done at init
Cons:
- the additional checks may be costly and partially defeat any DB optimization (if the FILTER reduces the query to only look at a subset, such checks usually will look at the whole query anyway, potentially wasting effort);
- non-trivial extension of the existing codebase/infrastructure for managing queries - definitely doable but adds complexity

### Versioning

A bit of a random idea - if we can ensure that the source tables were not modified between the init checks and the materialization, we can guarantee consistency. If a modification has taken place, we can throw a special error requesting the user to rerun the original operation.

We'd need to rely on the Database providing some kind of 'modification timestamps' or implement hashing of table contents (potentially quite costly).

Cons:
- less informative error message and risk of 'false positives' (we don't even know if we reached inconsistency, we just know some values have changed, it may be harmless),
- complicates the infrastructure a bit requiring to contain and re-verify the input 'versions'; similarly like the checks above;
- not sure if we can get such info from DBs and hashing manually is relatively costly.

### Embedding the checks into the query itself

This seems like the best idea if we can pull it of.

Pros:
- the checks are executed when the query is being materialized, so we guarantee consistency;
- no additional storage required and it is doable without significant changes to current Enso DB Table infrastructure.
Cons:
- we shift the complexity from the Enso code onto the SQL query; this may make the generated queries less likely to get optimized (needs practical checking to be sure);
- we may not be able to display as informative error messages - possibly we may just know that 'some previously checked invariant has been violated'.

The major challenge of this approach, apart from constructing a more complex query that can check the invariants, is allowing an invariant violation to trigger an error that will 'break' the whole query. 
- Apparently, in SQLite we can use `'x' MATCH 'y'` to trigger an error. That is because by default the `match` operation is not implemented so it will throw an error that will propagate and 'abort' the current query. We can detect this specific SQL error in Enso and turn it into a more informative 'invariant violation error'. If we don't use `match` operation anywhere else, we can guarantee that it only comes from our own special 'traps'.
- Not yet sure how to do this in Postgres, but likely we should be able to find some analogous way to trigger a failure on arbitrary condition.
   - _UPDATE_ a simple way is we can just use `SQRT(-1)` - this fails in Postgres. A bit more elaborate is to do an unsupported cast - this allows us to control more the error message thus detecting the failures robustly without false positives (`SQRT(-1)` can happen in normal operations so we don't want to falsely convert it into the 'consistency error').
   - ```
     radeusgd=> SELECT CASE 1 WHEN 1 THEN 1 ELSE CAST(('my message'||'') AS INTEGER) END;
      case
     ------
         1
     (1 row)

     radeusgd=> SELECT CASE 2 WHEN 1 THEN 1 ELSE CAST(('my message'||'') AS INTEGER) END;
     ERROR:  invalid input syntax for type integer: "my message"
     ```
> A prototype by @jdunkerley :
```
WITH lookup as (
    select *, row_number() over (partition by B) lu_ref from lookup_table
)
         SELECT l.A,
                l.B,
                case r.lu_ref when 1 then r.AA else l.AA end AA,
                l.CI,
                case r.lu_ref when 1 then 0 else match('value not found.', '') end
           from test_table l
left outer join lookup r on l.B = r.B;
```

`r.lu_ref` will be `1` for the first row of the given group; if there are more rows in a group, it will be `2`, `3` etc. and so we will go to the `else` branch and fail the query (handling the `Non_Unique_Key` scenario); if a row in `test_table` does not match anything in lookup, `r.lu_ref` will be `NULL` also triggering the `else` branch (handling the `Unmatched_Rows_In_Lookup`) scenario.

**Comment by GregoryTravis** [comment]
I definitely like "Embedding the checks into the query itself" as well. My only concern with that is, what if SQLite implements match? Is there anything we can 100% rely on, in all (or every) engine that can trigger an error? It would be awkward if certain engines had to report "Cannot perform `lookup_with_replace` without materializing the result".

Regarding the "Adding checks that are run upon materialization" solution:

> * the additional checks may be costly and partially defeat any DB optimization (if the FILTER reduces the query to only look at a subset, such checks usually will look at the whole query anyway, potentially wasting effort);

Wouldn't these checks have to run on the full dataset in any case? Is this concern about performing `lookup_with_replace` before a filter, or after a filter? If before, then the checks would have to run against the full dataset anyway; if after, then the checks would have to run against the smaller, filtered dataset, otherwise the optimization wouldn't have been correct.

> * non-trivial extension of the existing codebase/infrastructure for managing queries - definitely doable but adds complexity

True, this is more complicated, but there will surely be more operations that have this kind of problem, so the extra cost will be justified by the benifits.

I am only thinking about these two "con" issues because of my small concern about the "embedding" approach. Overall, I prefer the embedding approach if it is sure to work.

**Comment by radeusgd** [comment]
> Is there anything we can 100% rely on, in all (or every) engine that can trigger an error?

I don't think there is a single operation we can use, unfortunately. Especially with SQLite which has rather limited set.

---

> My only concern with that is, what if SQLite implements match?

The SQLite engine that Enso uses is embedded into the Database library itself. So we have control over its version. So there is no risk of version mismatch. If a newer version changes how `match` works _and_ we'd want to upgrade we would indeed have to figure out an alternative solution. But surely we will be able to do something.

----

> Wouldn't these checks have to run on the full dataset in any case? Is this concern about performing `lookup_with_replace` before a filter, or after a filter? If before, then the checks would have to run against the full dataset anyway; if after, then the checks would have to run against the smaller, filtered dataset, otherwise the optimization wouldn't have been correct.

Indeed, we discussed this with @jdunkerley and the consensus was that it would be OK to only have the check for values that actually affect the result. We can define that in the semantics of the operation.
