### ISSUE TITLE
Cannot debug Enso / Java in VSCode

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#8017]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I followed the instructions at <https://github.com/enso-org/enso/blob/develop/tools/enso4igv/vscode.md> and <https://github.com/enso-org/enso/blob/develop/docs/debugger/mixed-debugging.md> and was able to use it to debug for a few days, but now it no longer works.

Now, I get "Configured debug type 'java+' is installed but not supported in this environment.".

I have reinstalled the enso tools via `vsix` file. Sometimes I don't get the error, but starting the debug listener doesn't actually listen on a port, and I can't debug. Usually, though, I just get the above error.

It's possible that I have enabled/disabled some other plugins since it was working, but I am not sure if I did.

### Expected behaviour

I expect vscode to listen on port 5005 and to be able to execute a test from the shell or sbt and have it connect to the debugger.

### How we can reproduce it?

- Uninstall and reinstall "VSCode Extension" from the latest actions run
- Set breakpoints
- Select `Listen to 5005`
- Click the play button in the debug pane

### Enso Version

7637c003dd457fa6c721909ae8484ca39323dcb2

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Monterey 12.6.3

### Hardware you are using

MacBook Air (M1, 2020)

**Comment by JaroslavTulach** [comment]
Meanwhile the [VSCode documentation moved](https://github.com/enso-org/enso/blob/9a9a6e65a7007c7500af7684202fb1b35376c12d/tools/enso4igv/README.md) to new location. 

The way to start from scratch is to:
```
$ code --extensions-dir /tmp/code/ext --user-data-dir /tmp/code/usr
```
Installing Enso Tools for VSCode brings in `v1.15.119` and Language Server for Java by Apache NetBeans
`v19.0.301`.

Making sure Enso is properly built:
```
enso$ git checkout -f 2023.2.1-nightly.2023.12.4
enso$ sbt --java-home /graalvm-21/ buildEngineDistribution
```
Now I can open the root of `enso` repository as folder in VSCode. Following projects are found:

![obrazek](https://github.com/enso-org/enso/assets/26887752/bdbbbd88-42e5-40f5-a3d9-c87b7cfdf133)

I can open `Vector_Spec.enso` file and put breakpoint to line 68 on the first line of `type_spec` function. Then I can press F5 and VSCode starts `Listening on 5005` as indicated in the bottom status line. Then I can:
```
enso$ sbt --java-home /graalvm-21
sbt:enso> runEngineDistribution --run test/Tests/src/Data/Vector_Spec.enso --debug
```
and the breakpoint is hit. True, I tested it only on Ubuntu, but I don't believe there is anything OS specific in this sequence:

![obrazek](https://github.com/enso-org/enso/assets/26887752/c2e7caf5-c3ff-4637-846a-3e208c4d8fdb)

Greg, please repeat my steps and let's see what's your result. If the debugging isn't still working, please reopen.

**Comment by JaroslavTulach** [comment]
CCing @ola-lis

**Comment by GregoryTravis** [comment]
It is working for me again.

**Comment by JaroslavTulach** [comment]
Time heals...
