### ISSUE TITLE
Implement enso language support for codemirror code editor

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#8041]
Implement codemirror's language mode for Enso using our existing enso parser integration. The code editor should be able to perform syntax highlighting.

Make sure that it is possible to eventually attach more metadata for convenient display in the editor. In the future, we want to be able to see AST ID of selected or hovered ranges, as well as show current state received from execution context.

**Comment by somebody1234** [comment]
wip here: <https://github.com/enso-org/enso/tree/wip/sb/codemirror-highlighting>

<blockquote><img src="https://opengraph.githubassets.com/e14f20ad4d9e03aff7fd30084e94af967c84e010054d9aca345beff45edee245/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">GitHub - enso-org/enso at wip/sb/codemirror-highlighting</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
