### ISSUE TITLE
Constant columns (in expressions and `Column_Operation`s) should have clearer names

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#8050]
Currently a constant column gets an autogenerated name based on UUID:

![image](https://github.com/enso-org/enso/assets/1436948/dfa6ec3a-9764-4ee9-94b7-935776218ec4)

This does not look good at all.

- [ ] Instead, the column name should just be based on the `.to_text` representation of the constant. 
- [ ] We should use `column_naming_helper.create_unique_name_strategy` to ensure the name doesn't clash with other columns in the target table.
  - [ ] This may still not guarantee that _two distinct columns created from constants in a single expressions_ will have different names. Ideally, we should change the logic for creating constant columns to guarantee that OR test if this causes any issues (I suspect it could cause non-trivial problems in generated SQL, but only under some circumstances).
- [ ] Add tests for the naming.

**Comment by GregoryTravis** [comment]
@radeusgd When you say "two distinct columns created from constants in a single expressions", you're talking about two distinct columns created by two different `set` calls, but using the same constant as input?

**Comment by radeusgd** [comment]
> @radeusgd When you say "two distinct columns created from constants in a single expressions", you're talking about two distinct columns created by two different `set` calls, but using the same constant as input?

I mean the two `2`s in `table.set "([X] + 2) * 2"`

**Comment by radeusgd** [comment]
Sorry, the expression above will not create columns by default IIRC.

But this one surely should: `table.set "2 + (2 / [X])"`
