### ISSUE TITLE
Collapsing nodes

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8067]
To be done after #7863 

Collapsing nodes should work exactly the same as in old GUI: https://github.com/enso-org/enso/blob/develop/app/gui/src/controller/graph.rs#L1074-L1106

**Comment by Frizi** [comment]
Alias analysis is needed to determine inputs/outputs of collapsed nodes and to insert appropriate arguments.

Only support as much as the language server currently allows (e.g. single output)
