### ISSUE TITLE
Setting evaluation context on a single node.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8072]
To be done after #7791 

[Relevant design section](https://github.com/enso-org/design/blob/main/epics/basic-libraries/write-action-control/design.md#ide-control-of-a-single-node)

**Comment by Frizi** [comment]
Add support for hiding specific macros from node GUI. Possibly needs AST edits for proper macro support. For now, it is fine to do it in a hacky way, just for the context switch macro.

**Comment by farmaazon** [comment]
I think not only macros must be supported, as the code for enabling/disabling output context is a normal `<|` operator application.
