### ISSUE TITLE
Improving performance of `Map.insert`

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#8090]
As documented, currently `Map.insert` takes linear time when the key already exists in the Map:
```
       Due to the limitation of the current implementation, inserts with a
       key that is already contained in the map, or insert on a map instance that
       is re-used in other computations, have a linear time complexity.
       For all the other cases, the time complexity of this method is constant.
```

This is a serious limitation, making the map unusable for many use-cases, e.g. the `add_row_number` case - where we migrated to Java because the Enso implementation was too slow. This case needed to update existing keys.

Honestly, I've initially implemented `add_row_number` using Enso Map and forgot about the mentioned limitation - because it is so common that a `Map` in programming languages has better performance characteristics (`~O(1)` or `O(log N)` for _update_), that I assumed it is also like that in our case, completely forgetting about this limitation.

[We've already agreed that this is just temporary solution and it needs to be addressed in followup PRs](https://github.com/enso-org/enso/pull/3878#issuecomment-1383524234) - but it has never been planned.

So this ticket is exactly that - we should make `Map.insert` faster - it should be asymptotically `O(1)` or `O(log N)`, or at least amortized to that.

**Comment by radeusgd** [comment]
_I added the `compiler` tag because `Map` is currently a builtin. It's not exactly the compiler thing - maybe we need a separate tag for `runtime`?_

**Comment by radeusgd** [comment]
In #8091 I've added benchmarks showing the issue:

| Scenario     | Incremental | Replacement |
| ------------ | ----------: | ----------: |
| Enso Map     |   14.515 ms | 9796.416 ms |
| Java HashMap |    3.964 ms |   11.616 ms |

- _Incremental_ is a scenario like `Vector.distinct`, where we only add new keys to the map but do not update existing ones.
- _Replacement_ is a scenario like what we needed for `Table.add_row_number` - we are updating each key keeping a count of visited occurrences of each key.

As we can see, in the _incremental_ scenario the performance is relatively comparable. The Enso Map is still ~3x slower than Java, but this seems rather acceptable (especially as the Enso map is supposed to be an immutable data structure, so it satisfies a more complicated contract than the Java HashMap which is very imperative and mutable).

However, in the replacement scenario we can see a 800x slowdown - which is no longer acceptable. In fact the slowdown can be arbitrarily large, the larger the test size we set. That is because the Java HashMap does updates in amortized O(1) time, meaning that the whole algorithm runs in O(N) time, whereas Enso updates cost O(N), so the whole algorithm becomes O(N^2) - too slow for this usecase.

**Comment by JaroslavTulach** [comment]
`EnsoHashMapBuilder` is using `StorageEntry`. My idea to support "replacement operation" effectively is to associate such entries with __removedIndex__ that can mark them as removed when they are replaced. The check for `isEntryInThisMap` wouldn't check only `index`, but also `removedIndex` (if set) and wouldn't include such entries _in this map_ when `removedIndex` is lower than`snapshotSize`.

This however require us to make sure we can have multiple values with the same key in the `EnsoHashMapBuilder`. Probably a reason to finally stop using `EconomicMap` and implement simple linear hashing.

**Comment by radeusgd** [comment]
> This however require us to make sure we can have multiple values with the same key in the `EnsoHashMapBuilder`. Probably a reason to finally stop using `EconomicMap` and implement simple linear hashing.

Does that mean that if I update key `k` 1000 times, I will have 1000 entries mapped to that key? This will mean that again, the get/update operations will not be `O(1)`/`O(log N)`, they will be `O(M(k))` where `M(k)` is the number of times key `k` was updated in the lineage of the specific map. That will still be too slow and not what is expected from a HashMap collection.

Or did I misunderstood something?

---

I think we should try to ensure that the asymptotics of the insert/get/remove operations are all around amortized `O(1)` or `O(log N)` - that is what people expect from this kind of collection.

I really think we should consider using a [_Hash trie_](https://en.wikipedia.org/wiki/Hash_tree_(persistent_data_structure)) which seems to be most common approach to implementing efficient pure Hashmaps in functional languages (e.g. [in Haskell](https://hackage.haskell.org/package/unordered-containers-0.2.19.1/docs/Data-HashMap-Strict.html) and [Scala](https://docs.scala-lang.org/overviews/collections-2.13/concrete-immutable-collection-classes.html#compressed-hash-array-mapped-prefix-trees)). We don't necessarily have to reinvent the wheel - we could just [reuse an existing Java library for persistent data structures](https://github.com/usethesource/capsule).

**Comment by JaroslavTulach** [comment]
> Does that mean that if I update key `k` 1000 times, I will have 1000 entries mapped to that key? 
> Or did I misunderstood something?

Adding 1000 new entries (as overriding existing key would add a new entry) will lead to rehashing. At that moment only the latest value of a key is kept and we are back to happy times.

> I think we should try to ensure that the asymptotics of the insert/get/remove operations are all around amortized `O(1)` or `O(log N)` - that is what people expect from this kind of collection.

O(1) for `Vector.distict` and at most O(log N)` in case of updates of an existing key. OK.

> I really think we should consider using a [_Hash trie_](https://en.wikipedia.org/wiki/Hash_tree_(persistent_data_structure)) ... We don't necessarily have to reinvent the wheel - we could just [reuse an existing Java library for persistent data structures](https://github.com/usethesource/capsule).

Alas, existing library isn't going to be PE friendly.

**Comment by radeusgd** [comment]
> > I really think we should consider using a [_Hash trie_](https://en.wikipedia.org/wiki/Hash_tree_(persistent_data_structure)) ... We don't necessarily have to reinvent the wheel - we could just [reuse an existing Java library for persistent data structures](https://github.com/usethesource/capsule).
> 
> Alas, existing library isn't going to be PE friendly.

Ok, I was just suggesting a simple solution. My point is that if an existing library has better asymptotics than our solution, even if not PE friendly - it will still be much faster in practice. **If** we can get a PE friendly approach with good asymptotics - OK. 

I'm just worried about re-inventing the wheel - a lot of thought is put into making such hashmap structures very efficient and I'm just not sure if we have the capacity to do the same.
