### ISSUE TITLE
Missing suggestions in CB

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#8120]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

No suggestions visible when opening CB with selected node with Text or Number

### Expected behaviour

List of suggestions available

### How we can reproduce it?

Open Enso, add a node with text, select the node and open the CB again

### Enso Version

nightly 20.10.2023

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by hubertp** [comment]
A screenshot would be nice :)

**Comment by farmaazon** [comment]
I'm checking where the problem is (is it GUI or Engine).

**Comment by sylwiabr** [comment]
<img width="917" alt="image" src="https://github.com/enso-org/enso/assets/12892578/fe6051b3-910f-48aa-8f40-c10f8b6aae3b">
<img width="1074" alt="image" src="https://github.com/enso-org/enso/assets/12892578/42448fd2-6e26-43ef-9f95-3fef9e13d3ce">

**Comment by farmaazon** [comment]
Haven't reproduced it on 675fff07de10a3e7c1743c9ae6c620c2ec951ddf with 2023.2.1-nightly.2023.10.22 backend.

**Comment by vitvakatu** [comment]
I'll check it today between the calls

**Comment by vitvakatu** [comment]
Hmm, can’t reproduce either as of 03b7613e3c51d68e04087d1a333fd9094b239797 with 2023.2.1-nightly.2023.10.22 backend.

**Comment by jdunkerley** [comment]
Hubert is looking into this as a separate ticket. After restarting seemed to be fixed.
