### ISSUE TITLE
Unable to close new GUI tab

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8124]
### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

Occasionally new GUI will become unresponsive and a user is unable to close the browser tab which is far from convenient. 
Only after turning to Chrome's `TaskManager` I was able to kill the process. On top of that, while being in such a limbo, the new GUI process would consume 99% of CPU resources. 

### Expected behaviour

The GUI shutsdown immediately when the user clicks 'X".

### How we can reproduce it?

Leave new GUI idle for a while. Occurs sporadically. 

### Screenshots or screencasts

[Kazam_screencast_00021.webm](https://github.com/enso-org/enso/assets/292128/06a69071-b2f0-421f-ab5f-d98cee4021ab)

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

110.0.5481.100

### Operating System

Linux

**Comment by farmaazon** [comment]
@hubertp I used new GUI a lot and never saw this issue. Is it still reproducible on your side?

**Comment by farmaazon** [comment]
Not reproduced, closing for now. @hubertp reopen this if you spot it again.
