### ISSUE TITLE
Inline Execution

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#8132]
## Description

The engine should allow the execution of arbitrary expressions at the given point in the program with access to local variables defined in the scope.

Currently, the language server provides two endpoints with similar functionality:
- [executionContext/executeExpression](https://github.com/enso-org/enso/blob/1114a9bcff6ad93146e92cc5135cff8dcde69055/docs/language-server/protocol-language-server.md#executioncontextexecuteexpression)
- [executionContext/attachVisualization](https://github.com/enso-org/enso/blob/1114a9bcff6ad93146e92cc5135cff8dcde69055/docs/language-server/protocol-language-server.md#executioncontextattachvisualization)

The difference is that the `executeExpression` evaluates the value once and then "detaches" from the expression, and the `attachVisualization` leaves the expression attached and re-evaluates when the program changes.

## ToDo

The limitation of the current functionality is that it does not allow to access expressions in the local scope, for example given the program,

```py
main =
    operator1 = ...
    operator2 = ...
```

the IDE should be able to request the execution of an expression in the scope of the `main` method, and the expression can contain `operator1` and `operator2` symbols.

## Notes
- When designing the new JSON-RPC protocol, how should the scope be specified? One way would be to provide the scope as an `expressionId`, and then assume that the execution happens in the same scope as `expressionId`, after the expression is defined.

**Comment by JaroslavTulach** [comment]
Where to find _inline parsing_ related functionality:
- [Compiler.scala#runInline](https://github.com/enso-org/enso/blob/08c9ecb54037396a6ea26247c37b2bccb5ac1b4f/engine/runtime/src/main/scala/org/enso/compiler/Compiler.scala#L686) handles the conversion into `IR`
- it is used by [EnsoLanguage.parse(InlineParsingRequest request)](https://github.com/enso-org/enso/blob/08c9ecb54037396a6ea26247c37b2bccb5ac1b4f/engine/runtime/src/main/java/org/enso/interpreter/EnsoLanguage.java#L217) to integrate that with other Truffle languages
- the [EvalNode](https://github.com/enso-org/enso/blob/08c9ecb54037396a6ea26247c37b2bccb5ac1b4f/engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java#L49) - it probably does exactly what the IDE needs, so possibly just use it "somehow"
- and last, but not least there is the [ReplDebuggerInstrument](ReplDebuggerInstrument) and it uses the node: `private @Child EvalNode evalNode = EvalNode.buildWithResultScopeCapture();`

The right functionality must be somewhere along these lines.
