### ISSUE TITLE
Edge rendering details

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#8139]
- [x] Fix output ports anti-aliasing: The end-caps and variable-width portions of output ports are separate objects in order to efficiently tie the variable-width portion to the node's width. They need to overlap each other and the node in order to avoid apparent gaps due inexact FP math and antialiasing.
- [x] Z-order: A disconnected edge should render above nodes (except the attached node); target-attachment segments should be rendered above nodes. As individual components of an SVG object cannot be given different Z-indexes, objects that need different stacking should be rendered by separate component instantiations. (Target attachments could be drawn by the nodes, but they'll need the coloring information computed for rendering the edges.)

**Comment by farmaazon** [comment]
Refinement notes: 
* In the connected edges, "above node" could be just a part of the port.
* In general, the path of the edge should just start where the node ends.

**Comment by kazcw** [comment]
# The issues:

### Incoming edge is not drawn above node background:
![image](https://github.com/enso-org/enso/assets/1047859/1db71cda-7f9e-4d15-ac0f-14cb3c0b7c09)

### Disconnected edge is not drawn above other nodes:
![image](https://github.com/enso-org/enso/assets/1047859/14920207-3b1b-445e-8aaf-fdbaa0ec9501)
