### ISSUE TITLE
Pricing for the website

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#8149]
Design is [here](https://www.figma.com/file/lhyMbFlsbOXCzEZjkNV2n7/website-pricing5?type=design&node-id=0%3A1&mode=design&t=GcGY2oGw9V6hdzoZ-1)

<img width="1190" alt="image" src="https://github.com/enso-org/enso/assets/1623053/d398d2bb-b1c5-4299-9f6b-6e98ef03275f">

For smallest screen, we should have it looking APPROXIMATELY like this (this design does not have good spacing, it's just a preview. In case some spacing is inconsistent, feel free to make it consistent):

<img width="350" alt="image" src="https://github.com/enso-org/enso/assets/1623053/81860037-8c96-439f-a35e-76b702c41330">

Notes:
- When hovering or clicking on an entry, a pop-up should appear with explanation. Some things might not have pop-ups.
- Before downloading any version, including free, we will require signing-in, so sign-up should be integrated with website (possibly in another ticket).

**Comment by somebody1234** [comment]
reopening to track the design for smaller screens

**Comment by somebody1234** [comment]
notes:
- responsive design implemented. spacing is more or less the same as the screenshot, but it should be easy enough to change later
- popups not yet implemented as (i believe) the longer explanations do not yet exist
- sign in not yet implemented
