### ISSUE TITLE
Application of edits continues to lead to sporadic failures

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8174]
Recently reported https://github.com/enso-org/enso/issues/7978 was closed due to the inability to reproduce the underlying problem.
More logs have been added since which now carry some additional information:
[enso-project-manager-2023-10-26.0.zip](https://github.com/enso-org/enso/files/13203650/enso-project-manager-2023-10-26.0.zip)
[enso-project-manager-2023-10-22.0.log.gz](https://github.com/enso-org/enso/files/13203652/enso-project-manager-2023-10-22.0.log.gz)

**Comment by jdunkerley** [comment]
Seems significantly on hold for now.

**Comment by hubertp** [comment]
Yes, I haven't seen any failures in a while.

**Comment by jdunkerley** [comment]
Continue to not see these issues so closing as complete.
