### ISSUE TITLE
GUI2 edges bugs

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8175]
To be done after implementing widgets (as they may alter connections as well).

```[tasklist]
### Bugs
- [x] After connecting the edge is not adjusted to updated expression (see screenshot below)
- [ ] Undoing connecting updates node but not remove edge.
```

![image](https://github.com/enso-org/enso/assets/3919101/8b9a1e21-4d56-4da0-b2a4-3d6bb4eeb604)

**Comment by somebody1234** [comment]
After widgets:
- After connecting, updates seem to work fine
- Undoing connecting... cannot be tested properly due to another known issue:
![image](https://github.com/enso-org/enso/assets/4046547/8631bd94-31ce-4878-8837-dcd8533c937b)

**Comment by farmaazon** [comment]
Merging with #8420
