### ISSUE TITLE
E2E Tests

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8179]
Add a few high-level E2E application tests. Use existing API mocking capabilities (as used in demo scenes) to avoid having to spawn an engine.

Important scenarios to tests:
- A project with few predefined nodes is opening and the nodes show up.
- Node visualization can be opened and loaded.
- A component browser can be opened, and it shows database entries.
- Submitting component browser input adds or modifies a node.

**Comment by somebody1234** [comment]
submitted for the wrong day again -_-
