### ISSUE TITLE
Avoid heavyweight (fansi, Truffle) runtime-compiler dependencies

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#8210]
The `engine/runtime-compiler` project introduced by #8197 contains the _static IR compiler_ able to produce error diagnostics useful in any advanced text editor. In order to _simplify embedding_ of this part of Enso, we want to make sure the `runtime-compiler` project isn't [heavyweight](http://wiki.apidesign.org/wiki/HeavyWeight) - e.g. it doesn't carry unnecessary dependencies. Currently it does:
- fansi - used to print colorified output on various terminals
- Truffle - reusing `Source` and `SourceSection`

The idea is to create another project `runtime-error-reports` and move the `fansi` functionality there. Or _just move it_ to `engine/runtime` (for now). The same for Truffle. Once these abstractions are made, we can continue work on:
- #7054
- #8094 

```[tasklist]
### Tasks
- [x] Abstract fansi functionality in `runtime-compiler`
- [ ] Abstract Truffle dependencies in `runtime-compiler` - #8888
```

**Comment by Akirathan** [comment]
Remove `truffle-api` from `runtime-compiler` and `runtime-parser` projects:
```diff
diff --git a/build.sbt b/build.sbt
index e219b193e..28ea45704 100644
--- a/build.sbt
+++ b/build.sbt
@@ -1517,7 +1517,6 @@ lazy val `runtime-parser` =
   (project in file("engine/runtime-parser"))
     .settings(
       frgaalJavaCompilerSetting,
-      instrumentationSettings,
       commands += WithDebugCommand.withDebug,
       fork := true,
       Test / javaOptions ++= Seq(
@@ -1540,7 +1539,6 @@ lazy val `runtime-compiler` =
   (project in file("engine/runtime-compiler"))
     .settings(
       frgaalJavaCompilerSetting,
-      instrumentationSettings,
       libraryDependencies ++= Seq(
         "junit"            % "junit"                   % junitVersion       % Test,
         "com.github.sbt"   % "junit-interface"         % junitIfVersion     % Test,
```

**Comment by Akirathan** [comment]
Remove `fansi` by introducing a method like `CompilerContext.reportDiagnostics` and implementing it in `runtime`.

**Comment by Akirathan** [comment]
I have just moved the "Abstract Truffle dependencies in runtime-compiler" part into another issue - #8888

**Comment by JaroslavTulach** [comment]
Removing `pkg` may be easy as well:
```diff
$ git diff
diff --git build.sbt build.sbt
index 5e69fbedd9..68eaa9df7a 100644
--- build.sbt
+++ build.sbt
@@ -1876,7 +1876,6 @@ lazy val `runtime-compiler` =
       )
     )
     .dependsOn(`runtime-parser`)
-    .dependsOn(pkg)
     .dependsOn(`polyglot-api`)
     .dependsOn(editions)
     .dependsOn(`persistance-dsl` % "provided")
```
seems to work find with `2024.1.1-nightly.2024.1.30`
