### ISSUE TITLE
Restructure GUI2 directory

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8228]
So far we are hastily adding new modules to our codebase, not caring much about clarity or consistency. As a result, the `util` directory became a 'catch-all' place.

Let's gather some propositions in this task. Our goal is to have such a directory tree, so anyone not familiar with our codebase would have no problem with deducing place of given logic from our project structure.

**Comment by somebody1234** [comment]
yeah. honestly when i first looked at it, it didn't look *that* bad... but now it's one screen tall for me.

my proposition is to split the folder into subfolders of `util`. it may not be ideal, but would probably be sufficient for now. for example:
- [ ] `visualization*` can go in `visualization/`
  - [x] alternatively, `visualizationDataRegistry` and `computedValueRegistry` can go in `graph/`, and `visualizationBuiltins` can stay where it is
    - [ ] `getIconName` and `iconName` and `iconList` can maybe go in `graph/` too.
- [ ] `reactivity`, `events`, `navigator`, and `selection`, and `animation` can go in `vue/`
- [ ] `docParser` and `parserSupport` can perhaps go in the existing `ast/`
- [ ] `ffi` should maybe be renamed? and then also perhaps go in `ast/`
- [x] `mutable` is unused so it can be deleted?
- [ ] `vec2`, `rect`, `result`, `opt`, and `range` can go in `data/`
  - [ ] alternatively, `vec2`, `rect` and `range` can go in `data/` or `dataType` - the others are not classes so they may not fit.

**Comment by somebody1234** [comment]
I guess this one can also be closed until (well, if) it becomes a problem in the future
