### ISSUE TITLE
Match gui2 eslint rules more closely with established TS conventions.

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#8229]
Currently gui2 uses a code style as inherited from initial vue template. While most of it has to stay the same, we need to address a few stylistic differences that makes it incosnsistent with existing typescript in the codebase, e.g. adjusting the indentation size to 4 spaces. The format changes should be applied to the whole project in a separate commit that can later be excluded from the git blame.

**Comment by farmaazon** [comment]
Refinement notes: probably we should go with 2 spaces everywhere. Discuss it with dashboard team.

**Comment by somebody1234** [comment]
I assume no further action is needed here?
