### ISSUE TITLE
Node should be always as wide as visualization.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8234]
Now, when resizing a visualization, its background may be made wider than the node, but the node width stays the same. But it should also be extended to match visualization width.

Additionally, the visualization should have minimum width, so the main toolbar will always fit inside. The additional toolbar provided by visualization itself may be cut at the boundary.

**Comment by somebody1234** [comment]
alternatively the additional toolbar could wrap to a new line (or multiple, if it's still too long).

i think one line is fine, multiple may be a concern if you want a small viz *but* the node has a *very* long toolbar
