### ISSUE TITLE
Chaos testing of language server

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8247]
### Motivation 
A number of recent have been related to the fact that some operations take longer than excepted. When combined with asynchronous nature of compilation/execution this occasionally leads to unexpected timeouts/crashes.

### Desired outcome
Introduce some kind of framework that allows us to simulate random delays/crashes and making sure that backend recovers from them in a predictable manner.
Note that since LS is planned to retire from Akka, the framework should primarily focus on testing public API.

**Comment by JaroslavTulach** [comment]
No plans to do it in any foreseeable future.
