### ISSUE TITLE
Inconsistent type reported by Meta for `[]`

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#8255]
As [raised on Discord](https://discord.com/channels/@me/948519891961544714/1171105994634436638), we can see that there is inconsistency between the types reported by various `Meta` methods for the value `[]` (and any other vector for that matter):

### Actual behaviour

```
> Meta.get_qualified_type_name []
>>> Standard.Base.Data.Vector.Vector
> Meta.get_simple_type_name []
>>> Array
> Meta.get_qualified_type_name [].to_array
>>> Standard.Base.Data.Array.Array
> Meta.get_simple_type_name [].to_array
>>> Array
```

We can see that the `Vector` type is still characterized as `Array` by the `get_simple_type_name`. It seems like both methods should be consistent - so I assume that we most likely want:

### Expected behaviour

```
> Meta.get_qualified_type_name []
>>> Standard.Base.Data.Vector.Vector
> Meta.get_simple_type_name []
>>> Vector
```

**Comment by JaroslavTulach** [comment]
The `get_simple_type_name` is (probably due to historical reasons) a completely different implementation that is not using the `TypeOf...Node` as the `get_qualified_type_name` does. Probably time to rewrite the simple version to delegate to fully qualified name and shorten it - where possible.
