### ISSUE TITLE
Remove GraalVM distribution downloading facility

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#8280]
Since #7991, all the *runtime* (GraalVM distribution) handling is deprecated. Since that comprises a lot of functionality in our code base, we should get rid of that altogether.

There will no longer be no `runtime` directories cached anywhere.

Note that after this change, the `project-manager` will no longer be able to launch projects with older engines that require runtime.

**Comment by JaroslavTulach** [comment]
I don't think it is true that we don't have concept of `runtime` anymore. With the upgrade to GraalVM for JDK21 we have just moved the boundary a bit. Previously the Truffle API and languages like JavaScript and Python were part of the _"distribution"_. Now they are part of `enso-engine...zip`. But the GraalVM JDK still remains and can be considered a distribution.
