### ISSUE TITLE
Errors on nodes

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8288]
If node panics or returns a dataflow error, the message should be displayed on a dark-red/red background as in the new design:

![image](https://github.com/enso-org/enso/assets/3919101/f9731d6b-9752-4754-8ca0-a8ddcf01ae48)

* In case of panics, the message should be read from "Panic" payload of expression update
* In case of dataflow errors, the message should be read by attaching special "error" visualization.

For details, see GUI1 implementation.

**Comment by somebody1234** [comment]
i'm going to count fixing dataflow error diagnostics in the Code Editor as in scope for this PR, since the required functionality will need to be implemented here anyway.
