### ISSUE TITLE
Fix stepping over for Enso debugging

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#8290]
When debugging Enso code via chrome inspector or DAP, the step over functionality is unintuitive. As declared in [DebuggingEnsoTest.java:testSteppingOver](https://github.com/enso-org/enso/blob/ce9e284263bdf1d5a01c929cf226e092f650bf8b/engine/runtime/src/test/java/org/enso/interpreter/test/DebuggingEnsoTest.java#L473) - The *step over* always jumps to the method declaration, and does not skip it.

Let's fix this behavior and update the test in `DebuggingEnsoTest`.

Relevant:
- f5c3d252390370a6bc76826ad130f20cf0fe2c5a

**Comment by Akirathan** [comment]
Some of the tests were reverted as part of #8467 in 3d097eec065f9266bd2b5f1d5c661ac360a7fdcb

**Comment by JaroslavTulach** [comment]
- work in #10842 might be related
- particularly this https://github.com/enso-org/enso/pull/10842/commits/40ed82306b07e3a78e661b551bec02c287e71fa8 commit
- and this https://github.com/enso-org/enso/pull/10842/commits/41b3473437deaa8c17f5841b9c1fa74f6503918f commit

**Comment by JaroslavTulach** [comment]
This has been improved recently. Is it still a problem?
