### ISSUE TITLE
Free-floating visualization responses with failures

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8299]
As per log entry

```
[org.enso.languageserver.runtime.RuntimeConnector] No sender has been found associated with request id [e715b5da-a7bc-4261-8b43-156eae6bd86c], the response [org.enso.polyglot.runtime.Runtime.Api$.VisualizationExpressionFailed] will be dropped.
```

No other indication of the failure, the request id does not appear to exist anywhere else.

**Comment by hubertp** [comment]
It kinda feels plausible because we send the reply in [(1)](https://github.com/enso-org/enso/blob/develop/engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/AttachVisualizationCmd.scala#L25) and [(2)](https://github.com/enso-org/enso/blob/develop/engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/command/ModifyVisualizationCmd.scala#L54), thus removing them from the senders' list https://github.com/enso-org/enso/blob/develop/engine/language-server/src/main/scala/org/enso/languageserver/runtime/RuntimeConnector.scala#L128. 

And when later there comes a failed visualization message, it's sender is clearly not on the list anymore.

**Comment by hubertp** [comment]
This has changed (regressed?) in https://github.com/enso-org/enso/commit/e529f7bb3b0fbc98a39c9a460cfda439d4458549

**Comment by jdunkerley** [comment]
Closing - will add a new one if we see in GUI2.
