### ISSUE TITLE
GeoMap visualization is not working in gui2

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8300]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When opening GeoMap visualization, it shows nothing and an error is displayed in the console:

![image](https://github.com/enso-org/enso/assets/3919101/3c93e00f-79e0-4797-a8c5-c1ca7ee31b6e)

![image](https://github.com/enso-org/enso/assets/3919101/985d3da0-136c-4ad1-8760-2b998be2bcaf)

### Expected behaviour

Map visualization shows.

### Enso Version

develop - 5baec46466283c02a04621dcce6323e18b66d72a

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

119.0.6045.123

### Operating System

Linux

**Comment by somebody1234** [comment]
quite weird... i don't think any code changed, so i can only assume that the code changed on the CDN.
but that's not likely as well, since the import is pinned...:
```js
'https://cdn.jsdelivr.net/npm/deck.gl@8.9.27/dist.min.js'
```

**Comment by somebody1234** [comment]
ah. the issue is that it detects `exports` on window, and so it adds itself onto `exports` instead.
