### ISSUE TITLE
Unify settings of dev and electron servers.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8304]
Recently [we had a bug](8297) which was left unnoticed for a long time, because everyone was testing on the dev server which (apparently) had no CORS policies set.

Both servers should have the same CORS policies, and perhaps other settings should be unified as well.

**Comment by farmaazon** [comment]
Refinement notes: Check all response headers: if they are the same in electron server and in vite dev and preview server.

https://vitejs.dev/config/server-options.html#server-headers

**Comment by somebody1234** [comment]
nit: *the issues are from coop/coep/corp policies
(iirc, i changed the fonts from a CDN without cors, to one with cors)

**Comment by somebody1234** [comment]
For posterity, here are the headers sent by Electron server (excluding `Content-Length`, `Date`, and `Content-Type` which differ for each asset):
```
HTTP/1.1 200 OK
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
Cross-Origin-Resource-Policy: same-origin
Connection: keep-alive
Keep-Alive: timeout=5
```

**Comment by somebody1234** [comment]
Here are the headers sent by Vite:
It also includes and `Etag` header, which is omitted here as it also varies depending on asset.
```
HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Keep-Alive: timeout=5
```

From this, I will be assuming the COEP/COOP/CORP headers are the only headers that are missing

**Comment by somebody1234** [comment]
after the PR, there will still be one difference - Vite server has `Etag`, Electron does not.
I'll be leaving it in for now as it shouldn't make a difference for anything but caching, but I *can* look into it if we want 100% parity
