### ISSUE TITLE
A node persists in erroneous state despite fixing the underlying problem

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8336]
A situation has been reported numerous times with no clear instructions or logs indicating the problem.

![Screenshot from 2023-11-20 14-31-07](https://github.com/enso-org/enso/assets/292128/56ac82cf-7076-47b6-87bb-32fd710eac47)
![Screenshot from 2023-11-20 12-51-20](https://github.com/enso-org/enso/assets/292128/91c6c7d7-554d-4b6d-ad8d-987f41b8769d)

One can fairly consistently reach the above state just by playing around and specifying the date argument to be `day` instead of `day=1`.
The exact reasons are yet unclear but we are seeing in the logs for example
`executionContext/visualizationEvaluationFailed` messages that refer to the culprit expression.

The problem has been reported on larger projects.

**Comment by hubertp** [comment]
And another example:
![Screenshot from 2023-11-20 16-02-08](https://github.com/enso-org/enso/assets/292128/e6a68704-fb8d-452a-8124-e98144985ae1)

Edit:
Looking at `expressionUpdates` it might actually be a problem on the GUI side.
In the above example, the last update from `513e95d0-adaa-4b51-97a0-912f22d1fb7f`, which is a grey'ed out node, has a non-pending value.

**Comment by hubertp** [comment]
> Edit: Looking at `expressionUpdates` it might actually be a problem on the GUI side. In the above example, the last update from `513e95d0-adaa-4b51-97a0-912f22d1fb7f`, which is a grey'ed out node, has a non-pending value.

Or a combination of both. Sometimes GUI indeed gets "pending" in the expression updates and nothing else:
[Kazam_screencast_00023.webm](https://github.com/enso-org/enso/assets/292128/392d3814-ee62-4132-922c-8b2240768415)
and the last update has 
```
    {
      "expressionId": "513e95d0-adaa-4b51-97a0-912f22d1fb7f",
      "type": null,
      "methodCall": null,
      "profilingInfo": [],
      "fromCache": true,
      "payload": {
        "type": "Pending",
        "message": null,
        "progress": null
      }
    },
```

**Comment by hubertp** [comment]
[Kazam_screencast_00024.webm](https://github.com/enso-org/enso/assets/292128/342f6fb8-995e-4b6e-8749-276da0462c7e)

So I'm fairly certain this is some weird interaction **in GUI** when it receives a visualization. Notice the exact steps - preview the visualization that leads to a panic and then go back to a regular value. I can **always** reproduce this behaviour. Moreover, the last expression update has the non-pending payload so it shouldn't get stuck in this state:
```
  {
    "expressionId": "513e95d0-adaa-4b51-97a0-912f22d1fb7f",
    "type": "Standard.Base.Data.Time.Date.Date",
    "methodCall": {
      "methodPointer": {
        "module": "Standard.Base.Data.Time.Date",
        "definedOnType": "Standard.Base.Data.Time.Date.Date",
        "name": "new"
      },
      "notAppliedArguments": []
    },
    "profilingInfo": [
      {
        "ExecutionTime": {
          "nanoTime": 377134604114663
        }
      }
    ],
    "fromCache": false,
    "payload": {
      "type": "Value",
      "warnings": null,
      "functionSchema": null
    }
  },
  ```

**Comment by hubertp** [comment]
Also, I feel like the recent @4e6's work for the new GUI could make this work irrelevant for the new GUI since this could be related to the hacky solutions we had with CB previews

**Comment by vitvakatu** [comment]
I'm going to check it out in the old gui.

**Comment by vitvakatu** [comment]
I can’t seem to reproduce it on the following version:
```
Frontend:
    Version:  2023.2.1-dev
    Build:    2ddcaad6fe38d456989063ce934213fb3c4adb3e
    Electron: 25.7.0
    Chrome:   114.0.5735.289

Backend:
2023-11-23 16:59:59.011 Enso[41517:16260515] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
    Enso Project Manager
    Version:    2023.2.1-nightly.2023.11.17
    Built with: scala-2.13.11 for GraalVM 17.0.7
    Built from: develop @ 4b181c38d09951a8891d772e3394e350db8fe746
    Built on:   Mac OS X (amd64)
```


https://github.com/enso-org/enso/assets/6566674/8a0cbc2b-a359-41ff-8c2d-2414b1d1a557

@hubertp, on your recording, I see a weird thing that should never be happening on the recent GUI. When you start editing, the node shrinks, and you can see the original node underneath it. What exact version of the GUI are you using?

**Comment by farmaazon** [comment]
@hubertp bump

**Comment by hubertp** [comment]
> I can’t seem to reproduce it on the following version:
> 
> @hubertp, on your recording, I see a weird thing that should never be happening on the recent GUI. When you start editing, the node shrinks, and you can see the original node underneath it. What exact version of the GUI are you using?

Latest develop.

**Comment by hubertp** [comment]
@vitvakatu Can't reproduce consistently anymore but still every now and then it gets into a weird state:
![Screenshot from 2023-11-27 17-13-36](https://github.com/enso-org/enso/assets/292128/c70484b2-2da9-44da-8a25-2e769d597f10)

This is with today's GUI and backend. If you try a few times to remove `=1` from `day=1`, wait, and reapply, you will get it eventually.

**Comment by hubertp** [comment]
[Kazam_screencast_00027.webm](https://github.com/enso-org/enso/assets/292128/05264d66-5848-461f-81ad-620db4f4409b)

**Comment by vitvakatu** [comment]
I was able to reproduce the case with the pending state being stuck, can’t reproduce the stuck error though. Investigating.

**Comment by hubertp** [comment]
> I was able to reproduce the case with the pending state being stuck, can’t reproduce the stuck error though. Investigating.

Yeah, it's rather random. It's a flip a coin kind of thing.

**Comment by vitvakatu** [comment]
@hubertp I think I found the issue and prepared a fix. It would be awesome if you check it in my branch: https://github.com/enso-org/enso/pull/8464.
