### ISSUE TITLE
Provide engine support for decimal & co. types

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#8346]
Motivation:
In the Database table, we can currently have a Decimal value type representing a Decimal with a scale and precision in the normal database way.

First improvement, add support for using BigDecimal within the In-Memory table but need a built-in type to work with this type in Enso native. Convert with a warning to a float on at of to_vector when coming in.

But want to have a real built in.

Requirements:
- Create via parse and conversion method.
- Basic arithmetic operations interacting with Integers and Floats
- Convert between BigDecimal and EnsoDecimal on the polyglot boundary.

In order to support mixing and matching with other numbers must be a built in as no other way to enable addition operators etc.
 `1 / (Decimal 2) ==> Decimal 0.5`

@jdunkerley - review the .Net decimal and spec up more detail.

**Comment by JaroslavTulach** [comment]
I am not really sure what would be the benefit of having Decimal Type as a built in? It doesn't have any special support in `InteropLibrary` anyway. If the following is the only reason...

> to support mixing and matching with other numbers must be a built in

... then I think we can solve the mixing of regular numbers with special numbers _via conversions_. All binary operands on `Number` would check the other operand and _convert itself into the other operand type_, if that type defines the same binary operation.  Here is an example of that [for + operation](https://github.com/JaroslavTulach/enso/commit/feb899001b0ed599e79c641f9dc49a71880c6849#diff-f7984ef7d2e2b1f57d935f19c1255df94c390bb01803ba6de6db57327050d446R12).

**Comment by jdunkerley** [comment]
Following operators should work: `+`, `-`, `/`, `*`, `%`, 
Additionally, they should support all the comparison operations in usual way.

We should be able to take an `Integer` as either the left or the right and automatically convert to a `Decimal`.
`Float` will require the use to convert first to a Decimal explicitly and should give a nice error message saying this.

**Comment by JaroslavTulach** [comment]
> Following operators should work: `+`, `-`, `/`, `*`, `%`, 
> Additionally, they should support all the comparison operations in usual way.
> We should be able to take an `Integer` as either the left or the right and automatically convert to a `Decimal`. 

Initial set of specs for `+` and `Ordering` is available at https://github.com/enso-org/enso/pull/8779/commits/7407518376f9557085db90a0114c6d94c9bbc8fd where it defines `Complex` type and checks its interoperability with `Number`.

**Comment by JaroslavTulach** [comment]
We need to solve interoperability of `BigDecimal` support with `java.math.BigDecimal`. One idea that I am exploring is to use the `java.math.BigDecimal` directly in Enso:
```ruby
from Standard.Base import all
polyglot java import java.math.BigDecimal

# adding * as extension symbol to BigDecimal
BigDecimal.* self that:BigDecimal = self.multiply that
# adding conversion from Integer to BigDecimal
BigDecimal.from (that:Integer) = BigDecimal.new that.to_text

main =
    b = BigDecimal.new "132.778"
    2 * b
```
however right now that fails as **neither extension or conversion methods** can be defined on `polyglot java` symbols. On the other hand _explicit conversions and operations_ are possible:
```ruby
from Standard.Base import all
polyglot java import java.math.BigDecimal

times a:BigDecimal b:BigDecimal = a.multiply b

to_decimal n:Integer = BigDecimal.new n.to_text

main =
    b = BigDecimal.new "132.778"
    times b (to_decimal 2)
```
e.g. one can type some parameters to be `java.math.BigDecimal` and they'll be _runtime checked_ for being of the right type. Should we allow _extension and conversion methods_ for `polyglot java` types? **Update**:

- #8821

Per [general agreement](https://discord.com/channels/@me/948519891961544714/1197472662486786090), issue #8821 has been reported to track the implementation.
