### ISSUE TITLE
Review and update the current state of our AI integration

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#8348]
Need to review the work previous done by Marcin and Jan.
Look at what works / doesn't as it stands.

Goal of this ticket is to understand where we currently are and then we can work out a plan to get the functionality back to fully capable.

**Comment by jdunkerley** [comment]
@JaroslavTulach please add references:
- #5910
- discussing [REST calls in Visualizations](https://discord.com/channels/401396655599124480/1123196512369913946/threads/1124228885467365457)

**Comment by 4e6** [comment]
## How to use
- The AI completion is enabled by providing the `OPENAI_API_KEY` environment variable. It is required for the Language server to make calls to openai.
- The AI completion prompt is toggled by `cmd`+`tab` key combination in IDE. 
  :warning: on Linux, I have to hold the `tab` key and then press the `ctrl` button to make the shortcut work. There is an open issue about that #7528
  
## Implementation

The AI completion is implemented by creating a query from the user prompt and sending it to `https://api.openai.com/v1/completions`. 

To form a query, each user prompt is wrapped in a template describing the table API https://github.com/enso-org/enso/blob/8516ed5cbb07544b540aa7cf59fd88f7671dc330/distribution/lib/Standard/Visualization/0.0.0-dev/src/AI.enso#L23-L29

and providing examples https://github.com/enso-org/enso/blob/8516ed5cbb07544b540aa7cf59fd88f7671dc330/distribution/lib/Standard/Visualization/0.0.0-dev/src/AI.enso#L13-L22

The query looks like:
```
Operations available on Table are: <example code>
Available ways to aggregate a column are: <example code>
...
goal: <user prompt>
```

Then based on the provided examples, ChatGPT tries to come up with a code sequence that would satisfy the goal.

It works better than I expected given how little information is provided to ChatGPT

https://github.com/enso-org/enso/assets/357683/814fadc6-2c8e-4e2a-92fb-0691d916725d

**Comment by 4e6** [comment]
Related PRs:
- #5910
- #7146
