### ISSUE TITLE
Follow on from the Enso Cloud API PR.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#8352]
## URI_With_Query:
- Not doing EnsoSecrets in the URI_With_Query.
- [x] tests for `Data.fetch` and `self.fetch` in Http_Spec.
- [x] tests for `Data.post` and `self.post` in Http_Spec.
- [x] ensure URI has tests for fetch and post methods as well.
- [ ] ensure failures allow a URI_With_Query in the error.
- [x] refactor the test code to avoid some repitition.
- [x] Need tests for add_query_arguments URI => URI_With_Query and extending URI_With_Query.
- [x] Test URI conversion from text.
- [ ] URI_With_Query should support same API as URI so should be run through same set.
- [x] Character set that needs encoding needs verifying (definitely missing `[]`).
  - Test adding a parameter and sending response.
  - [x] See if simple httpbin would do the test.
  - [x] Test that to_uri works as the original URI_With_Query.

## HTTP Util Merge:
- [x] Test that the basic auth and bearer headers actually work.
- [x] Should test that changing HTTP version actually works.
- Headers are an Immutable Dictionary
  - Added workaround in Java for Response
  - Read keys and pass the HTTPHeaders.
  - Ideally felt should be a Map.
  - Response.enso then builds into a Vector
  - [x] check if we can make it work as an Enso Map more directly?
- Don't think there are any tests for headers being read.
	- [x] add such tests if needed

## Missing Tests:
- [x] JSON into Map had no tests ~~and was broken.~~

- (done elsewhere) ~~Add missing Docs on `Blank_Selector`.~~

**Comment by radeusgd** [comment]
@jdunkerley I need clarification what did we mean by
> tests for `Data.fetch` and `self.fetch` in Http_Spec.
?

What was the `self`?

We have tests for `URI.fetch`.

Do we want separate tests for `Http.new.fetch`? These are currently `PRIVATE` so I assume they are rather internal and it seems enough to have `Data.fetch` (the public API) tested.

But maybe we meant something else in there, I cannot remember exactly - hence asking.

**Comment by radeusgd** [comment]
Re: tests for converting text to URI; should we also be able to convert a text to a `URI_With_Query`? I guess it may make sense to be able to do so, although I'm not sure if it's useful in practice as I don't expect the user constructing `URI_With_Query` directly - rather getting it as results from the `add_query_argument` function.

**Comment by radeusgd** [comment]
I amended slightly how headers are handled in the response, but the Enso `Response.headers` function still returns a `Vector Header` - that is because the headers may be duplicated and handling of duplicates depends on user's needs. I added an example to `headers` function showing how to construct a `Map` from it.
