### ISSUE TITLE
New nodes' positions issues

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8368]
* [x] When making a chain of nodes, they are not in vertical line
* [ ] The position does not check if collides with visualization.

![Screenshot from 2023-11-21 16-37-24](https://github.com/enso-org/enso/assets/3919101/ad7b2795-f9b4-4175-aebc-e59199fa0292)

**Comment by somebody1234** [comment]
> When making a chain of nodes, they are not in vertical line
 
Cannot repro - could you double-check and see whether it's still a problem? I may just be trying to do it in the wrong way

**Comment by farmaazon** [comment]
> > When making a chain of nodes, they are not in vertical line
> 
> Cannot repro - could you double-check and see whether it's still a problem? I may just be trying to do it in the wrong way

Yes, I don't see the issue anymore.
