### ISSUE TITLE
Issues in the Component Browser in the new IDE

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#8372]
- The `qnIsTopElement` function is filtering out all the methods that should be in the default list.
The code was changed from `(name.match(/\./g)?.length ?? 0) <= 2` to `!/[.].*?[.].*?[.]/.test(name)`.
These are not equivalent. The later only works if 3 parts in the name.
`name.split('.'),length <= 2` is probably clearer.

- We should remove modules, types and constructors from the top level list unless we have added a GROUP to them (though not even sure that works at moment).
```ts
  private mainViewFilter(entry: SuggestionEntry): MatchResult | null {
    const hasGroup = entry.groupIndex != null
    const isModule = entry.kind === SuggestionKind.Module
    const isType = entry.kind === SuggestionKind.Type
    const isConstructor = entry.kind === SuggestionKind.Constructor
    const isTopElement = qnIsTopElement(entry.definedIn)
    if (!hasGroup && (isModule || isType || isConstructor || !isTopElement)) return null
    else return { score: 0 }
  }
```

- The initial filtering should just be initials starts with not a letter by letter match.
For example, within a Table, `sc` should match `select_columns` but not `select_blank_columns`.

- Ordering is not being applied. The sort algorithm is missing in `matched`.
`const matched = Array.from(matchSuggestions()).sort(compareSuggestions)`

- We should only show the local variables if `showLocal` is `true`.

**Comment by farmaazon** [comment]
> The qnIsTopElement function is filtering out all the methods that should be in the default list.
The code was changed from (name.match(/\./g)?.length ?? 0) <= 2 to !/[.].*?[.].*?[.]/.test(name).
These are not equivalent. The later only works if 3 parts in the name.
name.split('.'),length <= 2 is probably clearer.

Well, I think qnIsTopElement does exactly what it promises, and this test confirms it:
```ts
  test.each([
    ['local.Project', true],
    ['local.Project.elem', true],
    ['local.Project.Module.elem', false],
  ])('qnIsTopElement(%s) returns %s', (name, result) => {
    const qn = unwrap(tryQualifiedName(name))
    expect(qnIsTopElement(qn)).toBe(result)
  })
}
```
and it should never filter out the entries that are in group:
```ts
  private mainViewFilter(entry: SuggestionEntry): MatchResult | null {
    const hasGroup = entry.groupIndex != null
    const isModule = entry.kind === SuggestionKind.Module
    const isTopElement = qnIsTopElement(entry.definedIn)
    if (!hasGroup && (!isModule || !isTopElement)) return null
    else return { score: 0 }
  }
```

> We should remove modules, types and constructors from the top level list unless we have added a GROUP to them (though not even sure that works at moment).

That effectively will make us display just the elements in groups, as there is no top element I know which is not a module or type. We can do that, however personally I liked the idea, that after group we allow user browsing stdlib in a "hierarchical" way - we display top modules which may be entered by the user to browse further.

> We should only show the local variables if showLocal is true.

I think it would worsen my UX. Doing some work (bookclubs) I often type `operator` to pick one of the local variables and create connection. Now I would have to click some button to have that.

**Comment by jdunkerley** [comment]
> Well, I think qnIsTopElement does exactly what it promises, and this test confirms it:

I found reverting it made it work yesterday but possible other issues then.

**Comment by jdunkerley** [comment]
> That effectively will make us display just the elements in groups, 

No, we are correctly showing static methods which are not in groups with this change.

![image](https://github.com/enso-org/enso/assets/4699705/b2ed2a65-bfcb-477f-810e-6f664ed2f415)

If we want to have a module hierarchy to explore, we shouldn't show all modules/types (there are 700 or so in the db). We should just show the immediate children of where we are.

So we would just show the Standard.Base, Standard.Database, etc in top level and allow drilling down. 

This needs a little thought but I think would be a nice set up. I am cautious about adding complexity into the CB as it is already far too hard to find things for end users.

**Comment by jdunkerley** [comment]
>  I often type operator to pick one of the local variables

OK that is fair - the issue is that in any real workflow the count is enormous. 
With the ordering correctly implemented such that they appear together post groups it can work.
The catch being that it massively increases the requirement for renaming nodes to make it clearer.

**Comment by jdunkerley** [comment]
The `qnIsTopElement` was indeed not the bug - rather that the database had not finished initialising and hence you get an empty component browser making the experience feel completely broken.

**Comment by jdunkerley** [comment]
The icons within the component browser are not aligned with what is shown now on the nodes. 

We should use the icon of the function if defined or the Enso logo if not.
The GraphNode has the code:

```ts
const icon = computed(() => {
  if (suggestionEntry.value?.iconName) {
    return mapOldIconName(suggestionEntry.value.iconName)
  }

  const methodName = expressionInfo.value?.methodCall?.methodPointer.name
  if (methodName == null && outputTypeName.value != null) {
    return typeNameToIcon(outputTypeName.value)
  } else {
    return 'enso_logo'
  }
})
```

**Comment by jdunkerley** [comment]
Worth noting, that the CB user experience will need more thought.

It is much better than the old version but we still have work to make it easy for beginner end users to interact with.

**Comment by farmaazon** [comment]
> > That effectively will make us display just the elements in groups,
> 
> No, we are correctly showing static methods which are not in groups with this change.
> 
> ![image](https://user-images.githubusercontent.com/4699705/285186678-b2ed2a65-bfcb-477f-810e-6f664ed2f415.png)

Ah, I missed one more change: we display not only _top elements_ but all entries _defined in top elements_.

I will fix CB first to make it same as in the old GUI (where we display _top modules_, not their content), and then apply any further UX suggestions.

**Comment by jdunkerley** [comment]
We really should show those static functions - they are exactly the set I expected to see there.

**Comment by farmaazon** [comment]
Ok. I just want to express that this is [design change](https://github.com/enso-org/design/blob/main/epics/component-browser/design2.md#order-of-results-when-no-nodes-are-selected-and-no-query-has-been-provided-yet). I think the idea was, that any static function, if important, should be in some group.

**Comment by jdunkerley** [comment]
That is understood - the design will need to evolve as we use it.

Not faulting the implementation just in usage it becomes clearer what we need it do.
