### ISSUE TITLE
Engine sometimes returns empty list for `runtime/getComponentGroups`

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8376]
IDE sometimes does not display groups of entries: this is because we don't receive a list of groups from the engine.

It not always happens, but to me quite often. To reproduce, just open a project in the new GUI and see network log.

An example exchange:  [IDE-engine-no-groups.txt](https://github.com/enso-org/enso/files/13449975/IDE-engine-no-groups.txt)

PM logs: [enso-project-manager-2023-11-23.0.log](https://github.com/enso-org/enso/files/13449993/enso-project-manager-2023-11-23.0.log)

**Comment by hubertp** [comment]
If I was to guess, it could be before the compilation pipeline is run, which is when component groups get initialized, as per protocol documentation https://github.com/enso-org/enso/blob/develop/docs/language-server/protocol-language-server.md#runtimegetcomponentgroups. Before that it is certainly empty.
@farmaazon the request is sent after the first `executionContext/executionComplete`, right?
/cc @4e6

**Comment by farmaazon** [comment]
Uhm, no, I overlooked that important information from docs.

So I will fix that on the IDE side and will test. If everything will be ok, I'll close it as WAD.

**Comment by farmaazon** [comment]
Fixed on the IDE side and the problem disappeared. Closing.
