### ISSUE TITLE
Default visualization

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8386]
Before the user picks a concrete visualization, the chosen vis should be "default" - the exact kind should be picked according to the node output type (consult the old GUI for details - most prominently, the `Table` type displays `Table` visualization).

**Comment by farmaazon** [comment]
To consider: making visualization type depending on the _value_ as well, for example Geo Map could be default for tables having "longitude" and "latitude" columns.

**Comment by somebody1234** [comment]
relevant code here:
https://github.com/enso-org/enso/blob/8516ed5cbb07544b540aa7cf59fd88f7671dc330/app/gui/view/graph-editor/src/component/visualization/registry.rs#L81

**Comment by somebody1234** [comment]
> for example Geo Map could be default for tables having "longitude" and "latitude" columns.

i think we can use the same system that is currently being used by widgets for this. @Frizi thoughts?

**Comment by somebody1234** [comment]
@farmaazon  re: viz depending on value - i think this is something that will need

> To consider: making visualization type depending on the _value_ as well, for example Geo Map could be default for tables having "longitude" and "latitude" columns.

i think this should be discussed with @jdunkerley?

**Comment by somebody1234** [comment]
(for posterity: i guess the consensus (?) is that `default_visualization` should produce the correct value; no logic should take place on the GUI side.)

it gets a bit complicated when considering how(/when) user-defined visualizations should be automatically selected, but that's an issue for another day.
