### ISSUE TITLE
Language Server fails to start

### ISSUE THREAD

**Issue by sylwiabr** [enso-org/enso#8396]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [X] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

when trying to create a project an error occurs: ```Error creating new project: The runner used to create the project returned exit code 1.```

### Expected behaviour

Project should be created

### How we can reproduce it?

Open Ań electron package and try to create a new project

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/12892578/f0e68731-e02d-44ed-bba1-84e161628993

### Enso Version

nightly 27.11

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

**Comment by somebody1234** [comment]
@sylwiabr I think you posted the issue before the video finished uploading

**Comment by farmaazon** [comment]
Tested on package built on today's develop; tried to open project, got an error:
![image](https://github.com/enso-org/enso/assets/3919101/2abeb77b-9baf-45d6-8d16-6ec4aca28b6f)

**Comment by farmaazon** [comment]
Those errors are returned by Project Manager.

Calling in @hubertp and @JaroslavTulach

**Comment by JaroslavTulach** [comment]
I've just tested my own build at b6fa561fa32a46071b13c2dabb12136b26bacd8e and it worked.

**Comment by farmaazon** [comment]
@JaroslavTulach what's your operating system? We've seen it on linux and macOS.

**Comment by hubertp** [comment]
Tried today's nightly. Works just fine (linux). Maybe something to do with GraalVM upgrade (I assume OP didn't update for a while)?

**Comment by sylwiabr** [comment]
[2023-11-27T09-55-28.801Z-ide-2023.2.1-nightly.2023.11.27.log](https://github.com/enso-org/enso/files/13476597/2023-11-27T09-55-28.801Z-ide-2023.2.1-nightly.2023.11.27.log)
My logs

**Comment by sylwiabr** [comment]
@hubertp I didn't have the working package since the upgrade available so it might be it.

**Comment by hubertp** [comment]
@sylwiabr Those appear to be IDE-only console's logs. Can I get the backend one as well?

**Comment by hubertp** [comment]
> @hubertp I didn't have the working package since the upgrade available so it might be it.

It might be that we should test things on a machine that has no GraalVM prior to installation.

**Comment by sylwiabr** [comment]
[enso-project-manager-2023-11-27.0.log](https://github.com/enso-org/enso/files/13476863/enso-project-manager-2023-11-27.0.log)
oh, sorry, my computer was moody today

**Comment by hubertp** [comment]
Can you start it with `-debug.verbose`, please? Current logs don't indicate what is wrong.

**Comment by somebody1234** [comment]
tested on my pc (linux) - setting system java to jdk17-graalvm results in this problem; switching to jdk21-graalvm fixes it. i currently still have both installed, so do feel free to request any tests i should be doing to help debug this

**Comment by farmaazon** [comment]
My investigation:

* I have set up "old" jdk 11 GraalVM 22.2.0
  - Built package on newest develop but with 11-17 backend - project opened
  - Built package with 11-27 backend - error as above
* Removed GraalVM jdk and switched to plain openjdk 17 in my system
  - Run package again - the opening hanged for a long.
* Installed GraalVM jdk 21
  - Run package again - project opened

All logs from today:
[enso-project-manager-2023-11-28.0.log](https://github.com/enso-org/enso/files/13485970/enso-project-manager-2023-11-28.0.log)

**Comment by hubertp** [comment]
Apparently this has been an unintended consequence of GraalVM upgrade. We will look into it.

**Comment by JaroslavTulach** [comment]
Can I reproduce the problem on my Mac? Let's download DMG https://github.com/enso-org/enso/releases/tag/2023.2.1-nightly.2023.9.21 . Let's click on the downloaded image and drag Enso to applications. Creating new project really hangs.

I can see `/Applications/Enso.app/Contents/Resources/enso/bin/project-manager` process running. I can see that the `project-manager` has started `Library/Application Support/org.enso/tmp/runtime-23.0.0-java17.0.7-261120280/graalvm-ce-java17.0.7-23.0.0/` - e.g. wrong JDK runtime. Moreover it tries to download JavaScript and Python by calling `org.graalvm.component.installer.ComponentInstaller install js python`

#### Why does the DMG contain JDK17?

I can see the DMG installed into:
```
$ cd /Applications/Enso.app/Contents/Resources/enso
/Applications/Enso.app/Contents/Resources/enso$ find . | grep graalvm-community | grep java$
./runtime/graalvm-community-openjdk-17.0.7+7.1/Contents/Home/bin/java
```

why the DMG contains GraalVM for JDK17 and not GraalVM for JDK21, @mwu-tow?

<blockquote><img src="https://opengraph.githubassets.com/990c497058e7047498aef9da1bff08830cae83dcd0b967f722f413885da1239a/enso-org/enso/releases/tag/2023.2.1-nightly.2023.9.21" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/enso-org/enso/releases/tag/2023.2.1-nightly.2023.9.21">Release Enso 2023.2.1-nightly.2023.9.21 · enso-org/enso</a></strong></div><div>Download
Enso IDE
Enso IDE is the main product of the Enso project. The packages are stand-alone,
they contain both GUI and the backend.
Download links:

Linux (AppImage);
macOS (DMG);
Windows (Ins...</div></blockquote>

**Comment by JaroslavTulach** [comment]
Trying once again with DMG from https://github.com/enso-org/enso/releases/tag/2023.2.1-nightly.2023.11.28 this is the log I get:

```
[DEBUG] [2023-11-29T11:42:37+01:00] [org.enso.projectmanager.requesthandler.ProjectCreateHandler] started (org.enso.projectmanager.requesthandler.ProjectCreateHandler@689ac226)
[DEBUG] [2023-11-29T11:42:37+01:00] [org.enso.distribution.config.GlobalConfigurationManager] Global config [/Users/seal/Library/Preferences/org.enso/global-config.yaml] not found, falling back to defaults.
[TRACE] [2023-11-29T11:42:37+01:00] [org.enso.projectmanager.requesthandler.ProjectCreateHandler] Creating project using engine 2023.2.1-nightly.2023.11.28
[DEBUG] [2023-11-29T11:42:37+01:00] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Creating project [New_Project_1, 7888213a-95a7-4f3e-8fef-7018d6c24c65, None].
[INFO] [2023-11-29T11:42:37+01:00] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Created project with actual name [New_Project_1].
[DEBUG] [2023-11-29T11:42:37+01:00] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Project name [New_Project_1] validated by [org.enso.projectmanager.service.validation.ProjectNameValidator@36fe0490].
[DEBUG] [2023-11-29T11:42:37+01:00] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Checked if the project name [New_Project_1] exists in [org.enso.projectmanager.infrastructure.repository.ProjectFileRepository@430d99d5].
[DEBUG] [2023-11-29T11:42:37+01:00] [org.enso.projectmanager.infrastructure.log.Slf4jLogging] Found a path [/Users/seal/enso/projects/New_Project_1] for a new project [New_Project_1, 7888213a-95a7-4f3e-8fef-7018d6c24c65].
[DEBUG] [2023-11-29T11:42:37+01:00] [org.enso.distribution.config.GlobalConfigurationManager] Global config [/Users/seal/Library/Preferences/org.enso/global-config.yaml] not found, falling back to defaults.
[INFO] [2023-11-29T11:42:37+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine [2023.2.1-nightly.2023.11.28] found.
[INFO] [2023-11-29T11:42:37+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] The engine [2023.2.1-nightly.2023.11.28] found.
[TRACE] [2023-11-29T11:42:37+01:00] [org.enso.projectmanager.service.ProjectCreationService] Running engine 2023.2.1-nightly.2023.11.28 to create project New_Project_1 at [***/New_Project_1].
[DEBUG] [2023-11-29T11:42:37+01:00] [org.enso.runtimeversionmanager.runner.Command] Executing ENSO_DATA_DIRECTORY="/Users/seal/Library/Application Support/org.enso" ENSO_AUXILIARY_LIBRARY_CACHES="/Applications/Enso.app/Contents/Resources/enso/dist/2023.2.1-nightly.2023.11.28/lib" ENSO_RUNTIME_DIRECTORY="/Users/seal/Library/Application Support/org.enso" ENSO_EDITION_PATH="/Users/seal/enso/editions" ENSO_CONFIG_DIRECTORY="/Users/seal/Library/Preferences/org.enso" ENSO_HOME="/Users/seal/enso" ENSO_LOG_DIRECTORY="/Users/seal/Library/Logs/org.enso" ENSO_LIBRARY_PATH="/Users/seal/enso/libraries" "java" "-Dpolyglot.compiler.IterativePartialEscape=true" "--module-path" "/Applications/Enso.app/Contents/Resources/enso/dist/2023.2.1-nightly.2023.11.28/component" "-m" "org.enso.runtime/org.enso.EngineRunnerBootLoader" "--new" "/Users/seal/enso/projects/New_Project_1" "--new-project-name" "New_Project_1"
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

[ERROR] [2023-11-29T11:42:37+01:00] [org.enso.projectmanager.requesthandler.ProjectCreateHandler] Request ProjectCreate with Number(1) failed due to ProjectCreateFailed(The runner used to create the project returned exit code 1.).
[DEBUG] [2023-11-29T11:42:37+01:00] [org.enso.projectmanager.requesthandler.ProjectCreateHandler] stopped
[TRACE] [2023-11-29T11:42:37+01:00] [org.enso.jsonrpc.JsonRpcServer] Sent text message {"jsonrpc":"2.0","id":1,"error":{"code":4012,"message":"The runner used to create the project returned exit code 1."}}.
```

There seems to be the right GraalVM for JDK21:
```
/Applications/Enso.app/Contents$ ./Resources/enso/runtime/graalvm-ce-java21.0.1-23.1.0/Contents/Home/bin/java -version
openjdk version "21.0.1" 2023-10-17
OpenJDK Runtime Environment GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)
```


<blockquote><img src="https://opengraph.githubassets.com/0a9d86ec11d3233210e09b7a4a55047e2a6dbc7305b6f3ebc6574dde33c86e72/enso-org/enso/releases/tag/2023.2.1-nightly.2023.11.28" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/enso-org/enso/releases/tag/2023.2.1-nightly.2023.11.28">Release Enso 2023.2.1-nightly.2023.11.28 · enso-org/enso</a></strong></div><div>Download
Enso IDE
Enso IDE is the main product of the Enso project. The packages are stand-alone,
they contain both GUI and the backend.
Download links:

Linux (AppImage);
macOS (DMG);
Windows (Ins...</div></blockquote>

**Comment by sylwiabr** [comment]
This is the package I was installing: https://github.com/enso-org/enso/actions/runs/7000033985

<blockquote><img src="https://opengraph.githubassets.com/b4a02e226d2ad8b3ff4c2a1de89fcd000c0a2b06e27102020f1fff96038c50a7/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Nightly Release · enso-org/enso@5aef122</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
