### ISSUE TITLE
New IDE Backend Crash Opening Project

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#8398]
Using newest develop build as of 2023-11-17:

```
new session with ws://127.0.0.1:58020
LS connection initialized.
file:///C:/Repos/Enso/ide/app/gui2/vite.config.ts.timestamp-1701085461541-09ccfa0650ed3.mjs:332
        throw new LsRpcError(new RemoteRpcError(remoteError.data), method, params);
              ^

LsRpcError: Language server request 'text/openFile' failed.
    at LanguageServer.request (file:///C:/Repos/Enso/ide/app/gui2/vite.config.ts.timestamp-1701085461541-09ccfa0650ed3.mjs:332:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  cause: RemoteRpcError {
    code: 1005,
    message: 'IO operation timeout',
    data: undefined
  },
  request: 'text/openFile',
  params: {
    path: {
      rootId: 'e5bb4720-184b-4025-9965-3b02556e5665
',
      segments: [ 'src', 'Main.enso' ]
    }
  }
}

Node.js v18.14.1
npm ERR! Lifecycle script `dev` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: enso-gui2@0.1.0
npm ERR!   at location: C:\Repos\Enso\ide\app\gui2
```

[Enso_Getting_Started_3.tar.gz](https://github.com/enso-org/enso/files/13473950/Enso_Getting_Started_3.tar.gz)

Crashes every time on mine.

**Comment by farmaazon** [comment]
Not reproducible on Linux - I can open both in built package and the dev server.

**Comment by somebody1234** [comment]
i do (inconsistently) get crashes due to `text/openFile` on linux though, but haven't tested with this specific project

**Comment by farmaazon** [comment]
Ok, so for this task, let's make sure our service do not crash on `text/openFile` error, but retries with some backoff, and create an issue for the engine if the problem with IO timeouts will be heavy (and perhaps with some reliable reproduction scenario).

**Comment by farmaazon** [comment]
I discovered a case where it often happens to me: pasting or deleting a snippet 1000 lines long.

**Comment by farmaazon** [comment]
Refinement notes: After several failed openings, we could try to reconnect with LS, but probably it won't help anyway.

**Comment by somebody1234** [comment]
Adding LS tag, as I don't think *timeouts* are fixable from the GUI side (nor should they happen under normal use)

**Comment by farmaazon** [comment]
For engine's issue, let's make a separate issue, as this one I plan to close once we make our service not crashing after text/open failure.
