### ISSUE TITLE
Inline execution does not detach visualization if the execution failed

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#8429]
Reported by @farmaazon that when submitting multiple `executionContext/executeExpression` that fail, it seems that it starts sending `visualizationFailed` updates from previous executions.

That can happen if the visualization attached during the `executionContext/executeExpression` is not properly detached after the execution.

**Comment by farmaazon** [comment]
When I test 12.7 nightly, I still see many responses for `executeExpression`:

![image](https://github.com/enso-org/enso/assets/3919101/a6937f8b-cba1-496d-9bff-e397d8233723)

**Comment by farmaazon** [comment]
Here is a broader record of message exchange, involving some adding/editing nodes (so I called executeExpression a lot of times)

[ide-engine.txt](https://github.com/enso-org/enso/files/13600535/ide-engine.txt)

**Comment by 4e6** [comment]
I was not able to reproduce this issue on the develop.

However I can reproduce the #8431

1. Start with the default template
```py
from Standard.Base import all
from Standard.Table import all
from Standard.Database import all
from Standard.AWS import all
import Standard.Visualization

main =
    operator1 = "Press ENTER key to create a new node"
```

2. create a node with an error
```py
from Standard.Base import all
from Standard.Table import all
from Standard.Database import all
from Standard.AWS import all
import Standard.Visualization

main =
    operator1 = "Press ENTER key to create a new node"
    operator10439 = operator1.foo
```
3. Now when you open the component browser, you'll get the error responses to `executeExpression` requests:
```json
{
   "jsonrpc":"2.0",
   "method":"executionContext/visualizationEvaluationFailed",
   "params":{
      "contextId":"9477ba7c-69ce-4a69-953e-a0feabec8ab7",
      "visualizationId":"4ee38432-f045-4e4d-a236-aa2517fd4b1a",
      "expressionId":"50a7dcb9-4f53-4ea5-8e22-accafbfbad49",
      "message":"Compiler Internal Error: ID 3 defined in multiple scopes.",
      "diagnostic":null
   }
```

**Comment by 4e6** [comment]
I have a fix for `Compiler Internal Error: ID 3 defined in multiple scopes.`
```diff
--- a/engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
+++ b/engine/runtime-compiler/src/main/scala/org/enso/compiler/pass/analyse/AliasAnalysis.scala
@@ -996,7 +996,7 @@ case object AliasAnalysis extends IRPass {
       *
       * @return a unique identifier for this graph
       */
-    def nextId(): Graph.Id = {
+    def nextId(): Graph.Id = this.synchronized {
       val nextId = nextIdCounter
       nextIdCounter += 1
       nextId
```
But this means that the inline execution started by `EvalNode`  can run in parallel with some other compilation process. https://github.com/enso-org/enso/blob/b89d1b692a80afecf8981a17e0c3428df5f16771/engine/runtime/src/main/java/org/enso/interpreter/node/expression/debug/EvalNode.java#L76

This can potentially cause other issues because the compiler is not designed for concurrent access.

The proper fix would be to ensure the sequential access to the compiler.
