### ISSUE TITLE
Run GUI2 E2E tests (they do not include backend) as job on CI

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8433]
More or less, as in the title. They should be run in the "test" step only.

Scope includes fixing them if they do not pass.

**Comment by somebody1234** [comment]
it's possible to add them to the existing gui2 CI runs, but we might prefer it being in its own CI run as it can then be run in parallel - and it doesn't need to be run on all three platforms that way.

possibly in scope, if this requires changes to GH workflows and/or the build script - the dashboard would ideally get its E2E tests run as well
