### ISSUE TITLE
Node icon does not ignore overridden output context

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#8442]
Context not overridden:
![image](https://github.com/enso-org/enso/assets/4046547/7dae3b07-b25b-4640-b555-b8481ca71b97)

Context overridden:
![image](https://github.com/enso-org/enso/assets/4046547/247ec169-6acd-4360-a57e-8bf8ca7277a0)

The logo changes back to the default (fallback) logo.

**Comment by farmaazon** [comment]
I don't understand this issue. I see both nodes has same node icon, and everything seems right.

**Comment by somebody1234** [comment]
sorry, my bad - something messed up... i'll re-upload a correct screenshot

**Comment by somebody1234** [comment]
@farmaazon screenshot updated.

**Comment by somebody1234** [comment]
note that the PR on which this is an issue isn't merged yet, so it's not yet actionable

**Comment by somebody1234** [comment]
uh oh... this is still an issue

**Comment by somebody1234** [comment]
the node color seems to also not ignore an overridden output context.

**Comment by farmaazon** [comment]
Fixed by #9188
