### ISSUE TITLE
Output type displays below other nodes

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#8460]
![image](https://github.com/enso-org/enso/assets/4046547/bc831975-047e-4a5f-a009-84e36cf4ef70)

I've tried a few things, but this may be quite difficult to fix without putting *all* output types after the DOM tree.

**Comment by farmaazon** [comment]
Are we sure we want it? The output type displayed over another node would look bad anyway (especially over a node from the same group).

Calling in @jdunkerley and/or @wdanilo for consultation.

**Comment by somebody1234** [comment]
ah, true. we can consider displaying it *above* nodes though - it should be less likely for it to be hidden under the node above (although selecting the node above would change this)

plus, it means we would get around the issue of the type overlapping the visualization container too, for free

**Comment by farmaazon** [comment]
> ah, true. we can consider displaying it above nodes though - it should be less likely for it to be hidden under the node above (although selecting the node above would change this)

I would rather go with extending the default gap between nodes. Having type under node is logical, as there are output ports.

Or, we should consider the area under port a part of node's rect when looking for a free place for a new node.

**Comment by farmaazon** [comment]
Refinement notes:
1. The gap is already wide enough; we should just add additional magnet axes, so the nodes will snap to standard gap position.
