### ISSUE TITLE
Use Enso Font in new GUI

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8485]
As in title. The fonts are defined in https://github.com/enso-org/font repository. They should be downloaded during `npm install` and ready to use in new GUI codebase. For details, see https://github.com/enso-org/enso/issues/7197.

**Comment by somebody1234** [comment]
Ideally we should also remember to also use this font in:
- the Code Editor (I think it is currently using the system default monospace font so it looks pretty bad on Windows)
- certain visualizations (probably JSON, potentially SQL if it is supposed to be monospace)
