### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8487]
Automatic tests of GUI with the real backend connection. They could be playwright tests which assume there is a running project manager instance.

OPTIONAL, as it would be replaced with Bazel scripts soon: The build script should have working command `./run integration-tests` which spawns PM and run those tests. The Project Manager should be configured in such a way, that it creates projects in temporary directory (to not clutter user project list) - the old integration tests had a similar mechanism.

If the above will be nontrivial (or in case of lack of time), having pnpm script for running tests (assuming there is an already built electron package) is enough for this task.

As output of this task, there should be one test scenario of "typical new project flow" where we create new project, add some nodes there, browse visualizations, collapse node, enter it, check visualizations there and leave it.

**Comment by somebody1234** [comment]
ideally the PM would remove any temporary directories after it's done as well

**Comment by farmaazon** [comment]
Updated the description, loosening somewhat the requirements: as we expect to remove rust build script soon, the new command is optional.

Also, after a brief research I discovered https://playwright.dev/docs/api/class-electron - as playwright for electron testing just gets the path to executable, we should test the actually build package (without running PM ourselves)

<blockquote><img src="https://repository-images.githubusercontent.com/221981891/8c5c6942-c91f-4df1-825f-4cf474056bd7" width="48" align="right"><div><strong><a href="https://playwright.dev/docs/api/class-electron">Electron | Playwright</a></strong></div><div>Playwright has experimental support for Electron automation. You can access electron namespace via:</div></blockquote>
