### ISSUE TITLE
if then else and chained block syntax

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#8489]
Assuming that
```ruby
    main =
        pairs = (if t then a else b) . to_vector . sort
```
and 
```ruby
    main =
        pairs = if t then a else b
            . to_vector
            . sort
```
shall be the same. They are not [right now](https://github.com/enso-org/enso/commit/c5a6859654abb1d94fa1fd698684eb62387bd633) on `2023.2.1-nightly.2023.12.7`

**Comment by somebody1234** [comment]
@JaroslavTulach i think you messed up the link?

**Comment by JaroslavTulach** [comment]
@kazcw what do you think? As far as I can see in debugger the chained code is equivalent to `b . to_vector . sort` - e.g. the chain is only applied to the `b` and not to the result of the whole `if_then_else`.

**Comment by JaroslavTulach** [comment]
There are [three tests](https://github.com/enso-org/enso/compare/develop...JaroslavTulach:enso:wip/jtulach/IfChained_8489). Two work, but `testIfAndBlockSyntax` fails. Is that correct or wrong, @kazcw?

**Comment by kazcw** [comment]
I'm looking for a consistent rule that would make this work. Here's a candidate:

The body of an `else` segment is *either*:
- The rest of the line (if non-empty)
- A following child block (if there is no expression following the `else` on the same line)

This is a change from current behavior, in which if the `else` has in-line content, any following child block belongs to the `else` branch.

This would also affect other block types, e.g. this:
```ruby
    main =
        value = if t then f1 else f2
            y
```
Would be equivalent to this:
```ruby
    main =
        value = (if t then f1 else f2)
            y
```

IMO it minimizes confusion to treat all block types the same way in this regard.

What do you think, @JaroslavTulach? If we shall do it, I can use the AST-comparison script to check for any existing code relying on the old behavior.

**Comment by JaroslavTulach** [comment]
>    The rest of the line (if non-empty)
>    A following child block (if there is no expression following the else on the same line)

+1
