### ISSUE TITLE
Code editor breaks after some time

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8491]
https://github.com/enso-org/enso/assets/3919101/ab6c4855-06a0-4305-90ca-c07e7eecfa8b

Logs from another run: 
[localhost-1701952176893.log](https://github.com/enso-org/enso/files/13599959/localhost-1701952176893.log)

**Comment by Frizi** [comment]
That looks like a problem with AST range mapping again. Might be related to what I'm seeing with duplicated AST IDs on widgets.

**Comment by farmaazon** [comment]
So it is just reverting changes because of problems with engine sync, nothing to do with code editor itself?

**Comment by farmaazon** [comment]
It seems fixed by AST changes, but still is a bit laggy. Also found another issues, report them soon.
