### ISSUE TITLE
Reorder nodes after connecting.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8494]
After #8367 

After connecting node, we must sure that for each connection, the target node will be after the source node in the code (unless there is a cycle)

**Comment by somebody1234** [comment]
i think this would benefit from waiting for AST edits first

**Comment by vitvakatu** [comment]
Also keep in mind that the cycle can involve arbitrary number of nodes:
```
a = … c …
b = … a …
c = … b …
```
