### ISSUE TITLE
Custom Comparator sometimes not detected in the GUI

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#8505]
I have tried using the GUI with a custom comparator and it behaves... weird.

Let's use the following code for my repro:
```
from Standard.Base import all
from Standard.Table import all

type My_Type
    Value x

    score self = -self.x

    to_display_text self = self.to_text

type My_Comparator
    hash x = Nothing
    compare x y = Ordering.compare x.score y.score

Comparable.from (_ : My_Type) = My_Comparator

main =
    v = [My_Type.Value 1, My_Type.Value 3, My_Type.Value 2]
    vs = v.sort
    
    t = Table.new [["X", v]]
    

    c = Comparable.from v.first

    IO.println v
    IO.println vs
    IO.println c
    t.print
```

When run in CLI, all runs fine - the vector and Table get sorted fine.

When opened in GUI, at first it also seems OK.

https://github.com/enso-org/enso/assets/1436948/a591c5ed-3d40-4ed9-969b-aac5e889bbf1

However, once I delete the original `order_by` node and add it again. After some attempts - it starts failing with `Incomparable_Values`. 
It is as if `Table.order_by` seems to be no longer resolving the `Comparable.from` I defined for `My_Type`, and so it is falling back to `Default_Comparator` and yielding the `Incomparable_Values` because of that.

Curiously, after running into this error, I tried computing `Comparable.from v.first` _again_ and the second computation indeed shows the `Default_Comparator` instead of `My_Comparator` like the old one.

![image](https://github.com/enso-org/enso/assets/1436948/f938bcf1-627c-42d6-ad2e-8d82813611ce)

**Comment by JaroslavTulach** [comment]
@radeusgd, can you please check whether the behavior still present in recent releases? I am not aware of any fixes related to this problem, but there have been hundreds of small changes that may change the behavior somehow. Thank you. Reopen if the faulty behavior persists.

**Comment by radeusgd** [comment]
OK.

I tried updating the example to the new changes (e.g. the fix that enforces the type of value returned from `Comparable.from` conversion). I can no longer reproduce the problem.

![image](https://github.com/user-attachments/assets/fa40b1ea-4a34-4d4f-98be-67bc83e1779a)

**Comment by JaroslavTulach** [comment]
Thank you Radek for taking the burden of reproducing the issue away from my shoulder. I am glad to hear it works now.
