### ISSUE TITLE
Report errors to the user

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8524]
Currently, not all errors in our application are clearly reported to the user, what could make our bug reports harder to investigate.

Known missing messages:
* Lost connection with the engine or y-docs server
* Execution failures
* ~~Attaching visualization failures~~ - to be designed and done in a separate task.
* ~~Edits applying errors~~ - also separate task.

**Comment by farmaazon** [comment]
Refinement notes:
* Make sure it works in demo scenes and tests (where tostify may be not set up).

**Comment by somebody1234** [comment]
XD... porting the dashboard to Vue is an option, but i figured that's a super low priority right now given that we're currently looking for more React developers for the cloud frontend

**Comment by MichaelMauderer** [comment]
> XD... porting the dashboard to Vue is an option, but i figured that's a super low priority right now given that we're currently looking for more React developers for the cloud frontend

Yeah it's what we talked about yesterday. Still, it is a “possible solution” to avoid compatibility issues.
