### ISSUE TITLE
Don't swallow exceptions in `RuntimeVisualizationsTest`

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#8529]
with 630bf2d2d66cf960f0b136e2563a7458c4f4fb80 the following fails:

sbt:runtime-with-polyglot> testOnly *RuntimeVisualizationsTest -- -z preprocessor
[info] - should [1] run visualization error preprocessor *** FAILED ***
[info]   scala.MatchError: None (of class scala.None$)
[info]   at org.enso.interpreter.test.instrument.RuntimeVisualizationsTest.$anonfun$new$18(RuntimeVisualizationsTest.scala:2455)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:22)
[info]   at org.scalatest.Transformer.apply(Transformer.scala:20)
[info]   at org.scalatest.flatspec.AnyFlatSpecLike$$anon$5.apply(AnyFlatSpecLike.scala:1832)
[info]   at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
[info]   at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
[info]   at org.scalatest.flatspec.AnyFlatSpec.withFixture(AnyFlatSpec.scala:1686)

that's not really helpful.
Why cannot the original exception from the engine be logged in the output?

**Comment by JaroslavTulach** [comment]
This would be my fix:
```diff
enso$ git diff
diff --git engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
index e9e658a6a7..86e9f1406f 100644
--- engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
+++ engine/runtime-instrument-common/src/main/scala/org/enso/interpreter/instrument/job/ProgramExecutionSupport.scala
@@ -500,13 +500,19 @@ object ProgramExecutionSupport {
               .getOrElse(expressionValue.getClass)
           )
         )
-        ctx.executionService.callFunctionWithInstrument(
-          ctx.contextManager.getVisualizationHolder(contextId),
-          visualization.cache,
-          visualization.module,
-          visualization.callback,
-          expressionValue +: visualization.arguments: _*
-        )
+        try {
+          ctx.executionService.callFunctionWithInstrument(
+            ctx.contextManager.getVisualizationHolder(contextId),
+            visualization.cache,
+            visualization.module,
+            visualization.callback,
+            expressionValue +: visualization.arguments: _*
+          )
+        } catch {
+          case t: Throwable =>
+            logger.log(Level.SEVERE, null, t)
+            throw t
+        }
       }
 
   /** Compute the visualization of the expression value and send an update.
```

**Comment by JaroslavTulach** [comment]
I can integrate my fix myself, if it seems like the correct one.

**Comment by jdunkerley** [comment]
Closing as believe fixed.
