### ISSUE TITLE
Changing column name in `aggregate` does not update error.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8534]
![image](https://github.com/enso-org/enso/assets/3919101/ea260702-431a-4b61-b6ed-5d8e1cacc9a3)

Occurring spontaneously (quite often for me). In above screenshot, I just edited the `aggregate` node changing column name from `Data` to `Value` (which is valid) but the error did not disappear. Clicking "play" button cleared the error.

**Comment by farmaazon** [comment]
As I discovered, the error is not updated if right before accepting change in CB its preview showed "Compiler Internal Error: ID 2 defined in multiple scopes." So perhaps it's worth waiting for [#8431](https://github.com/enso-org/enso/issues/8431)

**Comment by somebody1234** [comment]
yeah.
note that on the GUI2 side, the error displays  just use the computed value registry, so if it *is* a problem on the GUI2 side, it would be a bug in the computed value registry, i think

**Comment by farmaazon** [comment]
No longer reproducible, closing.
