### ISSUE TITLE
Marketing Analytics use case - query from and update Google Ads

### ISSUE THREAD

**Issue by Cassandra-Clark** [enso-org/enso#8537]
As a user, I want to be able to connect to my Marketing Analytics data from Google to evaluate the success of my ad campaigns. I also want to be able to update Google Ads with data from another source so that it can be used to accurately report on non-google campaigns.

- Authenticate with Google Ads
- Connect to Google Ads
- Read from Google Ads
- Join to secondary datasource
- Write updates to Google Ads via API
- Create Google Ads connector to support most common APIs (list TBD, might become its own issue)

**Comment by jdunkerley** [comment]
Can you put a skeleton in a google doc of what it will be and aim to review on 2024-01-03
