### ISSUE TITLE
Holding down a shortcut invokes it repeatedly

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#8538]
e.g. Holding down Ctrl+V to paste a node.

This is not an issue in `shortcuts.ts` as it provides no event handling itself.

The issue is with using `useEvent(window, 'keydown'`. This task will involve adding a custom composable to `events.ts` which avoids re-triggering the callback until *after* the next `keyup` event. Care should be taken to ensure that the keyup event wasn't of the Ctrl being released (if that is possible).

**Comment by somebody1234** [comment]
On second thought it's possible to just check `event.repeat`: https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat

So it *may* be possible to check for this in `shortcuts.ts`

<blockquote><img src="https://developer.mozilla.org/mdn-social-share.cd6c4a5a.png" width="48" align="right"><div><img src="/favicon-48x48.cbbd161b.png" height="14"> MDN Web Docs</div><div><strong><a href="https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/repeat">KeyboardEvent: repeat property - Web APIs | MDN</a></strong></div><div>The repeat read-only property of the
  KeyboardEvent interface returns a boolean value that is
  true if the given key is being held down such that it is automatically
  repeating.</div></blockquote>

**Comment by farmaazon** [comment]
Cannot we just check `repeat` flag of keydown event?
