### ISSUE TITLE
Unify handling of file format detection

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#8555]
Recently #8403 introduced `File_Format_Metadata` that is a bit similar (but different) to `File_For_Read`.

We want to unify these types - ensuring that most fields are optional and ensuring that our file format detectors can work with that.

Along these lines, we may want to unify `for_web` and `for_file_read` as well - essentially currently `for_file_read` relies on `File_For_Read`, whereas `for_web` relies on a subset of `File_Format_Metadata` - once we merge these types, we could have `for_file_read` handle also the content-type case from `for_web` - as I'm not sure if we really need distinction if the thing is coming from web (do we? cc: @jdunkerley) - we mostly just want to be able to detect the format based on available information - whether this is file name extension, `Content-Type` (or other mime-type info), or possibility to read first bytes from the file.

---

We may want to add `File_Format_Metadata` to the `read` function as well, similarly as it is added to `read_stream`. The presence of additional metadata may be useful to further enhance the file format information that may be used for decoding the file.

The current instance of that use case is - when the user specifies the `Excel` type explicitly (which defaults `xls_format=Infer`, once we actually `read` or `read_stream` it - we want to change the `Infer` to actually be a proper `True|False` value and the metadata allow us to do so.

Currently, we default `Plain_Text`'s `encoding` to `utf_8`. We could similarly default it to `Infer` for reading and when the user requests to decode a request as `Plain_Text`, we could rely on the metadata to further enhance the format with the encoding based on the headers (still defaulting to UTF-8 if data is not available, of course).

**Comment by jdunkerley** [comment]
One method `for_read` which does both file or web.
- Use content-type if present and known.
- Use extension next.
- Special handling of reading first few bytes (SQLite at moment) but only if available.
