### ISSUE TITLE
Easier way to run a single Table test file against a different backend

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#8580]
## Context

Currently, we are able to run a specific test file from the `Common_Table_Operations`, e.g.
```
> enso run .\test\Table_Tests\src\Common_Table_Operations\Filter_Spec.enso
```

This suite is normally run across all our enabled backends - when running the whole test sutie `enso run .\test\Table_Tests`. When running a single file it is run with the _default_ backend which is in-memory.

When implementing features for a different backend, e.g. Postgres, it is useful to be able to run a particular file across that backend.

Currently, it is not straightforward. The only solution is to set `TEST_ONLY_GROUP` accordingly and run e.g. `test/Table_Tests/src/Database/Postgres_Spec.enso`. But a single file may contain multiple groups, so this is not as simple + it still runs some initialization of the whole test suite, taking more time than needed.

## Solution

Let's allow setting `ENSO_TEST_DEFAULT_BACKEND` environment variable that will drive what default backend is used.

Then, the above scenario will be just matter of setting the env var and running a selected file:
```
ENSO_TEST_DEFAULT_BACKEND=postgres enso run .\test\Table_Tests\src\Common_Table_Operations\Filter_Spec.enso
```
which will be much more convenient, especially when adding support for new backends.

To do so, we probably need to slightly refactor how our backends are initialized and the common tests are run.

**Comment by jdunkerley** [comment]
Can also allow filtering by `Test.specify` as well

**Comment by jdunkerley** [comment]
Using filtering of test name to achieve this so not doing.
