### ISSUE TITLE
Suppress logs in unit tests

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#8603]
The outputs of our unit tests are too verbose. Even if they succeed, we can see a lot of `[ERROR]` or `[WARN]` messages from various components that are just garbage. We should either suppress all the logs if the test succeeds, or print verbose logs if a test fails.

May be related to follow-ups of #7566

Might need tweaking our [TestLogProvider](https://github.com/enso-org/enso/blob/352ad06d2ff927b67938a2d2c35acdafcf6acba8/lib/scala/logging-service-logback/src/test/java/org/enso/logger/TestLogProvider.java)

**Comment by JaroslavTulach** [comment]
There is a [prior work in NetBeans](https://github.com/apache/netbeans/blob/master/harness/nbjunit/src/org/netbeans/junit/NbTestCase.java#L251) which works for JUnit3. Each `NbTestCase` has method `logLevel` (and also `logRoot`) and collects all logs of such severity into memory buffer. If the test succeeds the buffer is cleared. If it fails, it is _appended_ to the error message.
