### ISSUE TITLE
Full Wheel Component Menu. Replace Component Menu documentation icon with an edit icon

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#8612]
Add Ellipses on the small Component menu to open the full wheel Component Menu.
Full wheel Component Menu also opens on right click on component

![image](https://github.com/enso-org/enso/assets/1720119/75335007-eaa0-44c3-86c7-d2080fe2e3a9)

Replace Component Menu documentation icon with an edit icon. Clicking the edit icon puts the node into edit mode. (Equivalent to CTRL-Click today)

![image](https://github.com/enso-org/enso/assets/1720119/078dc042-3dc3-4ab2-a7b1-7ae9038e152f)

![image](https://github.com/enso-org/enso/assets/1720119/dc959a3d-d126-4ae2-a1dc-6fbe315fa4ca)

Documentation icon moves to the Full Component Menu Wheel

**Comment by farmaazon** [comment]
Refinement notes:
* The icon for editing may be (temporarily) picked from icons available in figma ("text input" maybe?)
