### ISSUE TITLE
New ... menu in the top bar with zoom controls

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#8614]
New ... menu in the top bar with zoom controls

... Goes top right

![image](https://github.com/enso-org/enso/assets/1720119/c1759a64-308c-4d22-afbf-6224ae573b82)

Currently only one menu item with zoom controls. Similar to Chrome, but instead of full screen button want restore to 100% button

![image](https://github.com/enso-org/enso/assets/1720119/12d3cbfa-c866-4a85-9c5a-9d756b3d79fb)

**Comment by somebody1234** [comment]
note that the user menu (the chat button and the user icon) are rendered by the dashboard, so i'm not 100% sure how this should work

**Comment by AdRiley** [comment]
Would it be easier if it wasn't connected to the user menu?

![image](https://github.com/enso-org/enso/assets/1720119/483df457-19f5-4478-a891-535473e9e707)

**Comment by somebody1234** [comment]
it would. there *is* still a minor issue because the dashboard would need to know how much space to leave for that button, but worst case that can simply be hardcoded

**Comment by farmaazon** [comment]
Refinement log:
* The menu under three dots should have now a single entry. The "fullscreen button" should be replaced with "fit to all" existing action.
![Image](https://github.com/enso-org/enso/assets/3919101/1551be41-fde9-4d9b-a2ca-e7d9d0c2dab2)
