### ISSUE TITLE
Add scroll bars to graph editor background

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#8617]
These will be a temporary addition until we come up with a better navigation solution.

Need to think about how the limits work. But I think initial assumption is the size of the graph editor background for the scroll bars is the size of the current workflow.

**Comment by farmaazon** [comment]
Refinement notes:
* Let's try to make scrollbars not too eye-catching, like in the google docs
* We could make scrollbar extend their range when "overscrolling" (so user could navigate an infinite canvas). But do not invest too much on it.

**Comment by AdRiley** [comment]
https://www.lucidchart.com/ seems to work reasonably well for the "overscrolling" problem.

<blockquote><img src="https://cdn-cashy-static-assets.lucidchart.com/marketing/images/Lucidchart_favicon_full_96x96.png" width="48" align="right"><div>Lucidchart</div><div><strong><a href="https://www.lucidchart.com">Intelligent Diagramming | Lucidchart</a></strong></div><div>Lucidchart is your solution for visual communication and cross-platform collaboration.</div></blockquote>
