### ISSUE TITLE
Cannot enable `org.enso.persist` logger via a property

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#8644]
[PR 8635](https://github.com/enso-org/enso/pull/8635/files#r1437722872) introduced a `Histogram` to log the _"top ten"_ of objects that occupy the most space in `.ir` cache files. Originally the code was using `System.err`. However that's not production ready. As such the system switched to usage of `Logger` in https://github.com/enso-org/enso/pull/8635/commits/015f4bb09b462c275ce895aa418370500fbc3b84 - the logging is disabled by default.

However there doesn't seem to be any way to enable the logging!

According to [logging doc](https://github.com/enso-org/enso/blob/ec51127635df3421c55be39a3bd26e39872cea9f/docs/infrastructure/logging.md#custom-log-levels) one should be able to specify:
```
-Dorg.enso.persist.Logger.level=debug
```
but that doesn't seem to work. Using `slf4j` doesn't compile as `org.enso.persist` package doesn't have a dependency on that 3rd party library and adding it would make it more [heavyweight](http://wiki.apidesign.org/wiki/HeavyWeight). [Regular loggers](https://docs.oracle.com/en/java/javase/21/docs/api/java.logging/module-summary.html) aren't configured properly. There is [System.Logger](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/System.Logger.html) which would be the _lightest_, but isn't configured either.

What's the recommended rewrite to enable logging via a property?

**Comment by hubertp** [comment]
Looks like the change that fixed truffle loggers in https://github.com/enso-org/enso/pull/8162 regressed along the way. Fixing the latter will probably also fix this issue.

**Comment by JaroslavTulach** [comment]
> Looks like the change that fixed truffle loggers in #8162 regressed along the way. 
> Fixing the latter will probably also fix this issue.

Setting [levels via builder.option](https://github.com/enso-org/enso/pull/8162/files#diff-0024a96ec0db8aac19bdc515cf0c8c108b0ac1f2beee916ad7da5e6737993805R109) cannot have any impact on `Logger` created by [Logger.getLogger](https://github.com/enso-org/enso/pull/8635/files#diff-9d27b6bd14cc82cf4c3817f34013a7b88be171835fc553b522bf61d255bf0680R16).

**Comment by hubertp** [comment]
> Setting [levels via builder.option](https://github.com/enso-org/enso/pull/8162/files#diff-0024a96ec0db8aac19bdc515cf0c8c108b0ac1f2beee916ad7da5e6737993805R109) cannot have any impact on `Logger` created by [Logger.getLogger](https://github.com/enso-org/enso/pull/8635/files#diff-9d27b6bd14cc82cf4c3817f34013a7b88be171835fc553b522bf61d255bf0680R16).

I don't really understand the comment. I meant that previous work in that area, #8162, enabled custom log levels via `JAVA_OPTS="-Dorg.enso.compiler.SerializationManager.Logger.level=debug"`. But even that doesn't work right now, so it regressed. The same way one should be able to enable `org.enso.persist`, requested in this ticket.

**Comment by hubertp** [comment]
After more careful inspection I retract my statement. The above example with SerializationManager a) works (user error) b) it is not related to this problem. The latter is simply because Logger is not managed by TruffleContext and thus does not load all custom application levels.

**Comment by hubertp** [comment]
> The latter is simply because Logger is not managed by TruffleContext 

And because of that one way of _fixing_ it is... using slf4j logger:
```diff
diff --git a/lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java b/lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java
index 0be8db574f..89cd07e030 100644
--- a/lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java
+++ b/lib/java/persistance/src/main/java/org/enso/persist/PerGenerator.java
@@ -9,11 +9,14 @@ import java.util.HashMap;
 import java.util.IdentityHashMap;
 import java.util.Map;
 import java.util.function.Function;
-import java.util.logging.Level;
-import java.util.logging.Logger;
+import org.slf4j.Logger;
+import org.slf4j.LoggerFactory;
 
 final class PerGenerator {
-  private static final Logger LOG = Logger.getLogger(Persistance.class.getPackageName());
+  private static final Logger LOG = LoggerFactory.getLogger(Persistance.class.getPackageName());
 
   static final byte[] HEADER = new byte[] {0x0a, 0x0d, 0x03, 0x0f};
   private final OutputStream main;
@@ -33,7 +36,7 @@ final class PerGenerator {
   }
 
   static byte[] writeObject(Object obj, Function<Object, Object> writeReplace) throws IOException {
-    var histogram = LOG.isLoggable(Level.FINE) ? new Histogram() : null;
+    var histogram = LOG.isDebugEnabled() ? new Histogram() : null;
 
     var out = new ByteArrayOutputStream();
     var data = new DataOutputStream(out);
@@ -142,14 +145,13 @@ final class PerGenerator {
             return a.getValue()[0] - b.getValue()[0];
           });
 
-      log.fine("==== Top Bytes & Counts of Classes =====");
+      log.debug("==== Top Bytes & Counts of Classes =====");
       for (var i = 0; i < list.size(); i++) {
         if (i == 30) {
           break;
         }
```

**Comment by hubertp** [comment]
So, I'm afraid this is a won't fix the way it is defined i.e. via JUL. If you pick slf4j, it will correctly pick up the config and apply the properties.

**Comment by hubertp** [comment]
Another thing to consider is `System.Logger`. Will need another look. 
But `Logger.isLoggable` just won't work.
