### ISSUE TITLE
Enable Ag-Grid Enterprise Features in GUI2

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#8660]
The current set up of the Table Viz in GUI2 imports a minimal set of Ag Grid packages but this is disabling some of the enterprise functionality (such as copy and paste).

This ticket is to re-enable all of these features by importing the full package.

Initial testing of re-enabling these packages showed issues with the focus management. Once you select into a grid it was very hard to get the selection back onto the graph rather than the grid. This meant Copy and Paste shortcuts was working inside the grid not in the graph.

**Comment by somebody1234** [comment]
there is a `useAutoBlur` utility to automatically blur (unfocus) an element when focus moves outside of its root element:
https://github.com/enso-org/enso/blob/ffa06c9476866bbfb69b46b01e5d3599c69f8f6e/app/gui2/src/components/CodeEditor.vue#L37-L38

not 100% sure it's the correct solution in this case, but it's probably worth a try
