### ISSUE TITLE
Add an icon for Error and Panic when shown on a Component

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#8677]
When an error or panic is shown on a component, we should also display an icon to allow for easier distinguishing between the 2.

The icon should be shown in the same place as the warning icon. The error message should be always visible only on the node causing it.

e.g. this situation:
<img width="452" alt="image" src="https://github.com/enso-org/enso/assets/919491/2156d967-f1db-43dc-a7de-283564d9153c">

**Comment by farmaazon** [comment]
* We need new icon for panic @AdRiley. The icon for error will be already there.
* We probably need more info about stacktraces from the engine (for Dataflow errors) to implement it properly. We can apply some heuristic (like: check if my error is exactly the same as some input's one). Then create a task/discussion with engine.

**Comment by AdRiley** [comment]
Added panic icon to Figma.
