### ISSUE TITLE
Display warnings on components

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#8678]
- If a component has warnings display the first warning in a similar way to errors but with orange background and a warning icon. 
- Only show when node is selected and when hovering over it. 
- Ideally with a link to open the full warning list.

**Comment by farmaazon** [comment]
the third point should be done in a separate task.

**Comment by somebody1234** [comment]
if the warning should only be shown when hovering over it, then we'd need a warning indicator, right? would that be just the orange border like in GUI1?

**Comment by AdRiley** [comment]
@somebody1234 Yes good call out. We should have the orange border like in GUI1.

@MichaelMauderer @farmaazon Can we do that as part of this story?
