### ISSUE TITLE
Broken workflow in GUI2

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#8684]
When I open the attached workflow in GUI2 it doesn't open correctly

GUI1:
![image](https://github.com/enso-org/enso/assets/1720119/b15de3f0-9459-4b38-b6a2-abc9ce5a7cdf)

GUI2:
![image](https://github.com/enso-org/enso/assets/1720119/9b12960e-72ee-4413-9bf6-79c3132b5ca7)

[Ayx_407_Single_Biggest_Lottery_Winner.zip](https://github.com/enso-org/enso/files/13840088/Ayx_407_Single_Biggest_Lottery_Winner.zip)

**Comment by farmaazon** [comment]
@AdRiley I don't reproduce it. Do you still reproduce it on your end?

**Comment by AdRiley** [comment]
Yes still reproduces in ide2-enso-win-2024.1.1-nightly.2024.1.19. But I do now get an error message

![image](https://github.com/enso-org/enso/assets/1720119/752f208d-8c61-4d0a-a991-0992d6c403d9)

**Comment by farmaazon** [comment]
I still see no broken layout nor execution error. @Frizi may it be related somehow to OS? Maybe line endings are confusing our parser? Could you check it on your side?

**Comment by vitvakatu** [comment]
Can’t reproduce on Mac either: 
<img width="1071" alt="image" src="https://github.com/enso-org/enso/assets/6566674/2747c0e9-32d0-409d-a2f2-b9a5a8f803f3">

**Comment by vitvakatu** [comment]
Can’t reproduce on Windows as per [Enso 2024.1.1-nightly.2024.1.25.1](https://github.com/enso-org/enso/releases/tag/untagged-860748266b31a8b3821d)

**Comment by vitvakatu** [comment]
Can’t reproduce on Windows as per [Enso 2024.1.1-nightly.2024.1.30](https://github.com/enso-org/enso/releases/tag/2024.1.1-nightly.2024.1.30)

**Comment by AdRiley** [comment]
Agreed it is fixed in 2024.1.30. We must have got it with another fix. Nice!
