### ISSUE TITLE
EditionManager slows empty startup down by 10%

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#8692]
Calling `EditionManager.resolveEdition` takes 161ms e.g. more than 9% of startup time on my computer.

![obrazek](https://github.com/enso-org/enso/assets/26887752/d2ab98ad-6f0a-4aaa-a853-a3d88a7faff8)

Why? Do we _"resolve any editions"_ at all? Isn't each engine currently associated with its own edition and that's it. If so, such an edition shall be instantly ready and require hundreds of milliseconds to resolve.

Can we avoid using needlessly complex Scala libraries? I am particularly horrified seeing 51ms (of 161ms!) spent in classloading some useless library with _bunch of implicits_ we probably don't need at all:
```
cats.implicits$.<clinit> ()	51.4 ms (2.9%)	51.4 ms (3%)	1
```
Overall I'd prefer if `org.enso.editions` was rewritten to Java.

**Comment by hubertp** [comment]
By resolving here we mean that a correct edition is found in the FS, which is unavoidable. But it's not that which is causing the slowdown.
The biggest penalty is paid in a) parsing YAML file b) parsing `SemVer` version. `circe` has some startup cost but the latter is definitely not efficient as it uses parser combinators.
