### ISSUE TITLE
[GUI2] Argument placeholders for type constructor expressions are not visible

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#8788]
Now that the engine provides method pointers for constructor expressions, GUI should be able to properly use them. Currently the suggestion database method lookup fails for unknown reason, causing the placeholders to not show up.

**Comment by hubertp** [comment]
@Frizi 
```
suggestion database method lookup fails for unknown reason
```
can you elaborate on the failure? Any message? 
Is this likely on our end or maybe on the GUI part?

**Comment by Frizi** [comment]
@hubertp 

This is the local database lookup on GUI side, not to the engine. Everything looks fine in the network responses.
