### ISSUE TITLE
Project name with camel case name and digits fails to initialize

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8793]
A project called `AoC01` fails to perform the first execution with a
```
Module local.Ao_C_01.Main not found.
```
error and obviously looks broken in GUI:
![Screenshot from 2024-01-17 21-42-03](https://github.com/enso-org/enso/assets/292128/cac74413-2697-4016-9c98-63e4389f8fb8)

Seems like #8649 has not completely addressed all normalization issues.

The only workaround is currently to provide an explicit config property:
```
normalized-name: AoC01
```

**Comment by 4e6** [comment]
Cannot reproduce it on the current develop. @hubertp if you were using the dev build, did you rebuild the project manager?

**Comment by hubertp** [comment]
hmm, couldn't reproduce either anymore. I will reopen if I encounter this again.
