### ISSUE TITLE
This visualization seems to be reloaded when changing zoom

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#8799]
In the attached project, the central visualization seemed to be reloaded every time I changed zoom.

[Bookclub_17_01.zip](https://github.com/enso-org/enso/files/13975479/Bookclub_17_01.zip)

**Comment by farmaazon** [comment]
Strangely, when trying to make a screencast, it reproduced no more. Let this task leave for a while to see if we will have similar effects, if not, then I'll close it.

**Comment by hubertp** [comment]
Seems to be happening to me with no interaction on my side (2x on the video). Sometimes more frequently, sometimes less.
There is no interaction between GUI and LS AFAIK.

[Kazam_screencast_00030.webm](https://github.com/enso-org/enso/assets/292128/8d9ef2bf-1a5c-4059-a31b-c26d4fb06371)

**Comment by hubertp** [comment]
I think a fix for #8801 might have fixed that one as well. At least I was no longer able to reproduce the flickering

**Comment by farmaazon** [comment]
#8853 seems to fix the issue. I still see that the visualizations are reloaded unnecessarily, but will file another one for it.
