### ISSUE TITLE
Only allow the correct type to be used for `self` in the static method call syntax

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#8805]
A discussion during today's standup led me to try discussing this suggestion.

## Expectations

When I'm declaring member methods on a type, I **definitely** expect `self` within those methods to have that type:

```
type My_Type
    Ctor_A x
    Ctor_B x y

    sum self = case self of
        My_Type.Ctor_A x -> x
        My_Type.Ctor_B x y -> x + y

    my_method self z =
        self.sum + z
```

Within `sum`, I definitely expect that `self` has type `My_Type`, so that I know that my `case-of` statement covering the 2 constructors of it is definitely exhaustive.

Within `my_method`, I definitely expect that `self` has type `My_Type`, so that I know I can safely call the other method `sum` on it.

## Unexpected reality

We have static syntax for calling member methods, which allows us to replace `x.my_method 200` with `My_Type.my_method x 200`.

This syntax allows us to kind-of 'manually' specify the `self` parameter to the method, by referring to it statically.

However, it does not enforce that such-specified `self` has the correct type. Thus the following program:
```
from Standard.Base import all

type My_Type
    Ctor_A x
    Ctor_B x y

    sum self = case self of
        My_Type.Ctor_A x -> x
        My_Type.Ctor_B x y -> x + y

    my_method self z =
        self.sum + z

    simple_method self = self.x+1000

type Other_Type
    Value x

main =
    o = Other_Type.Value 23

    IO.println <| My_Type.simple_method o
    IO.println <| Panic.recover Any <| My_Type.my_method o 200
    IO.println <| Panic.recover Any <| My_Type.sum o
```
will yield
```
1023
(Error: (No_Such_Method.Error (Other_Type.Value 23) UnresolvedSymbol<sum>))
(Error: (Inexhaustive_Pattern_Match.Error (Other_Type.Value 23)))
```

The `simple_method` will _just work_, because `Other_Type` provides all it needs - a getter `x`. The other 2 methods however, will break in wonderful (read: harder to debug) ways somewhere within the internals of the implementation.

As @JaroslavTulach pointed out, this basically rules out the ability to infer `self : My_Type` inside of any of these methods, because as shown in this example, the `self` may be whatever type we put there. 

This defeats almost all of our type checking on member methods (which constitute most of Enso libraries). If I don't know the type of `self`, I cannot statically infer the type of any methods called on `self` as well. Thus if a member method relies on other member methods/fields, I cannot really perform type inference within it. And lots of methods _do_ refer to others in such a way.

I don't think this is good, so I'd suggest to change that.

## Proposal

Let's enforce the type of `self` by **checking** it during the static-syntax dispatch.

To keep sanity of our code, I think we need to ensure that `self` is what the developer expects it to be. The proposal is to add a check that will only allow the correct type within the static dispatch.

That is `My_Type.sum (My_Type.Ctor_A 2)` will happily work, however `My_Type.sum (Other_Type.Value 3)` will raise a `Type_Error`.

Then the behaviour of the program I pasted above would be following:
```
(Error: (Type_Error.Error My_Type (Other_Type.Value 23) 'self'))
(Error: (Type_Error.Error My_Type (Other_Type.Value 23) 'self'))
(Error: (Type_Error.Error My_Type (Other_Type.Value 23) 'self'))
```

All these invocations would fail, because we cannot call a `My_Type` member method on a non-`My_Type` instance, even (ab)using the static call syntax.

I think this is the right thing to do, because then, within those member methods, we can safely assume that `self` is of the expected type. This is sane both for the developer and for the type system.

## Consequences of the change

I'm not aware of any _problematic_ consequences of this change. However, I may be missing something regarding the expected semantics of the static-syntax for member methods. If so, let's discuss.

The only usage of this pattern that I know of currently is within `Array.enso` where we dispatch statically the methods defined on `Vector` with the `Array` as their `self` parameter, to re-use the `Vector`'s implementation of these methods. This is a neat trick, but I don't think it's a thing that we really need at all, so I'd suggest to refactor it ([an alternative has already been suggested](https://github.com/orgs/enso-org/discussions/6216#discussioncomment-5579906)). We can move the common methods to be static methods on `Array_Like_Helpers` that take a `array_like` parameter (what used to be `self`). Then we can change the invocations to be:
```diff
-Array.insert self at=self.length item=Nothing = Vector.insert self at item
+Array.insert self at=self.length item=Nothing = Array_Like_Helpers.insert self at item
```

```[tasklist]
### Tasks
- [ ] Fix [staticWithRFirstAndZSecondNoConversionHappens](https://github.com/enso-org/enso/pull/8779/files#r1463856968) test
- [ ] Implement conversions for `self` to fix [staticWithRFirstArgumentIsConverted](https://github.com/enso-org/enso/pull/8779/files#r1463859288) test
```

**Comment by radeusgd** [comment]
@JaroslavTulach has mentioned that @wdanilo was heavily involved in the design of the 'static syntax for calling member methods' (I'm not sure what is the official name of this construct). @wdanilo could you have a look at this proposal and let me know if you think it is OK to implement it?

**Comment by wdanilo** [comment]
Given

```
type My_Type
    Ctor_A x
    Ctor_B x y

    sum self = case self of
        My_Type.Ctor_A x -> x
        My_Type.Ctor_B x y -> x + y
```

`My_Type.sum : My_Type -> Number`, always. Passing any other type to `My_Type.sum` should throw type error. If we are not throwing type error here, this should be considered a bug in the current implementation, because, as you pointed out, it can easily cause hard to find bugs throwing errors from their internal implementation. Of course, such things can be (should be?) caught by type inferencer, as checking that at runtime might slow things down. 

Anyway, yes, `self` is always typed as `Self`.

**Comment by JaroslavTulach** [comment]
> Let's enforce the type of `self` by **checking** it during the static-syntax dispatch.

Should the policy have any real effect, it has to be _enforced during runtime_. E.g. we have to use `ReadArgumentCheckNode` to verify `self` in the _static version of each method_ (invocable via the static `Type.method` syntax). Using `ReadArgumentCheckNode`  will give us automatic conversions of the `self` argument, however that seems desirable and consistent with behavior of other static methods.
