### ISSUE TITLE
Language Server `LibrariesTest` & co. tests fail due to timeouts in CI

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#8806]
The Engine tests fail from time to time due to timeouts.

[Example](https://github.com/enso-org/enso/actions/runs/7558161910/job/20579030654?pr=8790#step:10:14579):
```
- should create a library project and include it on the list of local projects *** FAILED *** (5 seconds, 503 milliseconds)
  java.lang.AssertionError: assertion failed: timeout (5 seconds) during expectMsgClass waiting for class java.lang.String
  at scala.Predef$.assert(Predef.scala:279)
  at akka.testkit.TestKitBase.expectMsgClass_internal(TestKit.scala:571)
  at akka.testkit.TestKitBase.expectMsgClass(TestKit.scala:567)
  at akka.testkit.TestKitBase.expectMsgClass$(TestKit.scala:567)
  at akka.testkit.TestKit.expectMsgClass(TestKit.scala:973)
  at org.enso.jsonrpc.test.JsonRpcServerTestKit$WsTestClient.expectMessage(JsonRpcServerTestKit.scala:120)
  at org.enso.jsonrpc.test.JsonRpcServerTestKit$WsTestClient.expectSomeJson(JsonRpcServerTestKit.scala:158)
  at org.enso.languageserver.websocket.json.LibrariesTest.$anonfun$new$2(LibrariesTest.scala:137)
  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
  ...
```

Eventually followed by:
```
Tests: succeeded 300, failed 1, canceled 0, ignored 4, pending 6
*** 1 TEST FAILED ***
 Failed tests:
 	org.enso.languageserver.websocket.json.LibrariesTest
```

([full log archive, in case they are no longer accessible through GH Actions](https://github.com/enso-org/enso/files/13988112/logs_110338.zip))

The tests should not have timeouts that can so easily be hit if the machine is under load or the tests are run on a slow machine.

We had previously increased the timeouts, however, the issues still occur.

https://github.com/enso-org/enso/pull/8785 added printing thread dumps when a timeout failure occurs, which may potentially help with debugging. (The dumps are present in the linked example.)

[See also the last Discord discussion](https://discord.com/channels/401396655599124480/1196890831207018597) on the subject.

**Comment by radeusgd** [comment]
@JaroslavTulach [commented](https://github.com/enso-org/enso/pull/8785#issuecomment-1898672558) that there are lots of ZIO threads running during the tests and this may be one of the causes why the tests are 'jamming'

**Comment by mwu-tow** [comment]
Another case, though on macOS: https://github.com/enso-org/enso/actions/runs/7639249532/job/20811863330?pr=8844

<blockquote><img src="https://opengraph.githubassets.com/912ebb7780a9ba244a2b281288499b39e5f3c1e85b90e789b8debe2d1d48e3b7/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Align collapsed node to the leftmost selected one · enso-org/enso@2b9d798</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by JaroslavTulach** [comment]
[LibrariesTest failed](https://github.com/enso-org/enso/actions/runs/7672566748/job/20924452121?pr=8779#step:10:12413) - the last thread dump seems to contain 15 searcher.db-1 threads. That's 14 more than I'd expect.

The [LibrariesTest.log.gz](https://github.com/enso-org/enso/files/14071342/LibrariesTest.log.gz) file contains the last thread dump extracted from the raw output of the CI run.

**Comment by hubertp** [comment]
I have a pending fix for fixing Actor System threads but ZIO stuff is proving difficult. I also noticed that the way we [currently](https://github.com/enso-org/enso/blob/develop/engine/language-server/src/main/scala/org/enso/languageserver/effect/Runtime.scala#L27) configure Runtime, seems to ignore the assigned executor despite the explicit setting. Instead, zio stuff appears to default to a regular ZScheduler which uses all cores.

**Comment by JaroslavTulach** [comment]
> ... the way we [currently](https://github.com/enso-org/enso/blob/develop/engine/language-server/src/main/scala/org/enso/languageserver/effect/Runtime.scala#L27) configure Runtime, seems to ignore the assigned executor...

That's a good finding! It promises _things may get better_.

**Comment by mwu-tow** [comment]
@hubertp 
It seems that #8892 is not enough yet, as its merge-commit failed due to this very issue: https://github.com/enso-org/enso/actions/runs/7724599547/job/21057063189#step:10:4031

<blockquote><img src="https://opengraph.githubassets.com/a09e2296b9363b26ca87e14155fa6c7d2626bfab0827cdd73d5765efa4bb2b53/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Reduced resources for various Akka dispatchers (#8892) · enso-org/enso@68ce4ae</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by hubertp** [comment]
Created a follow up ticket. I haven't seen the timeout since this change.

**Comment by Akirathan** [comment]
Just bumped into another instance of LibrariesTests failure due to timeout in https://github.com/enso-org/enso/actions/runs/7738790398/job/21100330354?pr=8918#step:10:4033

<blockquote><img src="https://opengraph.githubassets.com/4a536c44d1c1417327e58be67ca84baef214b6c6137414ba8ca4bd49cf29b535/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Fix teardown in SQLite File spec · enso-org/enso@f4163b7</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by mwu-tow** [comment]
> Created a follow up ticket. I haven't seen the timeout since this change.

I've linked one two messages above.
