### ISSUE TITLE
doubly nested dropdown options are not propagating to widgets

### ISSUE THREAD

**Issue by Frizi** [enso-org/enso#8822]
Table.filter should have a dropdown available for "Equals" inside filter parameter. When filling in the "Equals" parameter, brackets must be inserted.

Aggregate needs to have a "columns" dropdown for vector entries as well.

**Comment by vitvakatu** [comment]
The project to reproduce:
[GUI_Dropdowns.enso-project.zip](https://github.com/enso-org/enso/files/14009716/GUI_Dropdowns.enso-project.zip)
