### ISSUE TITLE
Native aarch64 macOS builds.

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#8848]
Our releases should include native aarch64 builds for macOS.

**Comment by kgantchev** [comment]
@mwu-tow 
I apologize if I'm intruding here, but if you need MacOS ARM64 runners, may I suggest giving [FlyCI](https://flyci.net) a try? We offer MacOS M1 and M2 runners that tend to be faster and cheaper than GitHub's. For public repos, we offer 500 mins/month of free M1 usage (4 vCPUs, 7 GB RAM, 28 GB storage).

The setup is super easy: 

1. Install the [FlyCI GitHub app](https://github.com/apps/flyci-prod).
2. Give the FlyCI app permissions to this repo.
3. Change your runs-on flag whenever you implement the ARM64 MacOS workflow:

```diff
jobs:
ci:
-    runs-on: macos-latest
+    runs-on: flyci-macos-large-latest-m1
      steps:
      - name: 👀 Checkout repo
         uses: actions/checkout@v4
```

Do you think this might be a good option for enso? 

Web: [flyci.net](https://flyci.net/) | Twitter: [flyciapp](https://twitter.com/flyciapp) | LinkedIn: [FlyCI](https://linkedin.com/company/flyci) | Discord: [FlyCI](https://discord.gg/JyCjh439da)
