### ISSUE TITLE
Workflow gets turned into _ components

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#8854]
In the attached workflow if I connect the right most read query into the tables of the union my entire workflow gets turned into _ components

![image](https://github.com/enso-org/enso/assets/1720119/d6c59e80-b7d6-4110-a2fb-469fc8f0624f)

like so

![image](https://github.com/enso-org/enso/assets/1720119/86403a7d-168c-4bd1-90bf-e4241d065369)

Undo does not work.

Have attached workflow, input data and my console logs

[PreppingData_2024_Week4.zip](https://github.com/enso-org/enso/files/14049863/PreppingData_2024_Week4.zip)
[PD 2024 Wk 4 Input.xlsx](https://github.com/enso-org/enso/files/14049868/PD.2024.Wk.4.Input.xlsx)
[localhost-1706175716470.log](https://github.com/enso-org/enso/files/14049876/localhost-1706175716470.log)

Found in: ide2-enso-win-2024.1.1-nightly.2024.1.25.exe

Not reproducible in ide2-enso-win-2024.1.1-nightly.2024.1.24.exe

**Comment by farmaazon** [comment]
Fixed by #8851
