### ISSUE TITLE
(1.0 . to BigDecimal) != 1.0 - e.g. equality isn't working correctly

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#8855]
The support for non-builtin number types (as introduced by #8779) **doesn't work well with `==`**. As result of that certain [tests had to be disabled](https://github.com/enso-org/enso/pull/8779/commits/6b9bdca0c7854ecd5ded86b4f3501805ce54efe0). This is a follow up issue that tracks further work on the reimplementation of `EqualsNode`.

The initial idea:
- when comparing two objects of different type, check possible conversions first
- only then use comparators

Catch:
- warn when there is not a consistency of `hash` code!

**Comment by Akirathan** [comment]
After #7883, the consistency of `hash` code can be checked within `Runtime.assert`. That way, we ensure that the hash consistency is checked only in tests and not in production.
