### ISSUE TITLE
Hovering some parts of a node reloads visualisation

### ISSUE THREAD

**Issue by MichaelMauderer** [enso-org/enso#8875]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When hovering a node with an open visualisation, the visualisation gets reloaded unnecessarily. 

### Expected behaviour

Visualisation should only change when the node value changes.

### Screenshots or screencasts

[Peek 2024-01-26 14-32.webm](https://github.com/enso-org/enso/assets/1428930/430a9031-ea68-4a5a-91bd-8cb24fcf4895)

### Enso Version

[03dbb1b](https://github.com/enso-org/enso/pull/8859/commits/03dbb1b98d0e718890eb6dd8f418c9e6827a8a3a)

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

Chromium Version 117.0.5938.88 (Official Build) Arch Linux (64-bit)

### Operating System

Linux

**Comment by jdunkerley** [comment]
Closing as no longer occuring.
