### ISSUE TITLE
Warnings are not wrapped with Map_Error

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#8910]
During the migration of `Base_Tests` to the new builder Test API in #8890, the following test fails https://github.com/enso-org/enso/blob/dc8f562b6228f36134742e2c06e7414c965a1014/test/Base_Tests/src/Semantic/Warnings_Spec.enso#L319

The failure is in https://github.com/enso-org/enso/actions/runs/7710597347/job/21014244070?pr=8890#step:10:25728.

In https://github.com/enso-org/enso/pull/8890/commits/4b5417447133c1ff9b87d23c3a4282b8d42345ba, I have marked the test as pending.

```[tasklist]
### Tasks
- [ ] Revert https://github.com/enso-org/enso/pull/8890/commits/4b5417447133c1ff9b87d23c3a4282b8d42345ba
```

**Comment by radeusgd** [comment]
I reverted the pending status in #8955.

I was able to reproduce the problem locally. It occurs only under some circumstances (I suspect it may be some Truffle specialization issue, which only triggers if some other steps fall randomly into right places).

My repro seems to be deterministic.
It seems that the problem only occurs if very specific conditions are met. If any one of these conditions is _not_ satisfied, it does not occur:
- enable assertions with `-ea`,
- enable writing JUnit XML report with `ENSO_TEST_JUNIT_DIR`,
- enable HTTP tests by setting `ENSO_HTTP_TEST_HTTPBIN_URL` and running the helper server.

All of these conditions _are_ set on CI so that's why it is so consistently failing there.

`REPORT_ONLY_FAILED` seems to be optional but I use it to keep the logs shorter and easier to browse.

The repro that worked multiple times for me is:
```
> $env:ENSO_JVM_OPTS='-ea'
> $env:REPORT_ONLY_FAILED=1
> $env:ENSO_TEST_JUNIT_DIR="target/"
> $env:ENSO_HTTP_TEST_HTTPBIN_URL="http://localhost:8080/"
> enso run .\test\Base_Tests\
[WARN] [2024-02-03T10:21:52+01:00] [org.enso.runtimeversionmanager.components.RuntimeVersionManager] Ignoring the minimum required engine version check [2023.2.1-nightly.2023.11.2] for the development version [0.0.0-dev].
[INFO] [2024-02-03T10:21:54+01:00] [org.enso.interpreter.runtime.DefaultPackageRepository] Found library Standard.Base @ 0.0.0-dev at [***\0.0.0-dev].
[INFO] [2024-02-03T10:21:54+01:00] [org.enso.interpreter.runtime.DefaultPackageRepository] Found library Standard.Test_New @ 0.0.0-dev at [***\0.0.0-dev].
[INFO] [2024-02-03T10:21:54+01:00] [org.enso.interpreter.runtime.DefaultPackageRepository] Found library Standard.Test @ 0.0.0-dev at [***\0.0.0-dev].
[FAILED] Instrument fibonacci: [0/3, 135ms]
    - [FAILED] collect and filter on return updates [87ms]
        Reason: 0 did not equal 1 (at X:\NBO\enso\test\Base_Tests\src\Semantic\Instrumentor_Spec.enso:34:17-41).
    - [FAILED] access local variables  [24ms]
        Reason: 0 did not equal 3 (at X:\NBO\enso\test\Base_Tests\src\Semantic\Instrumentor_Spec.enso:66:17-41).
    - [FAILED] replay with caches and specify different result [23ms]
        Reason: 89 did not equal 42 (at X:\NBO\enso\test\Base_Tests\src\Semantic\Instrumentor_Spec.enso:89:17-40).
[FAILED] Instrument @Tail_Call fibonacci: [2/6, 105ms]
    - [FAILED] call and collect on return updates [26ms]
        Reason: [] did not equal [[1, 1], [1, 2], [2, 3], [3, 5], [5, 8], [8, 13], [13, 21], [21, 34], [34, 55], [55, 89]]; lengths differ (0 != 10)  (at X:\NBO\enso\test\Base_Tests\src\Semantic\Instrumentor_Spec.enso:128:17-122).
    - [FAILED] * instead of + on return updates [19ms]
        Reason: 89 did not equal 17179869184 (at X:\NBO\enso\test\Base_Tests\src\Semantic\Instrumentor_Spec.enso:157:17-50).
    - [FAILED] Caching in on_enter prevents on_call [17ms]
        Reason: 89 did not equal 90 (at X:\NBO\enso\test\Base_Tests\src\Semantic\Instrumentor_Spec.enso:182:17-41).
    - [FAILED] Access (even default) arguments of calls [21ms]
        Reason: 89 did not equal 155 (at X:\NBO\enso\test\Base_Tests\src\Semantic\Instrumentor_Spec.enso:214:17-42).
[FAILED] Dataflow Warnings: [31/32, 1070ms]
    - [FAILED] should be preserved after operations on multi-dimensional Vector [15ms]
        Reason: [(Map_Error.Error 3 3), (Map_Error.Error 3 2), (Map_Error.Error 3 1), (Map_Error.Error 3 0), (Map_Error.Error 2 2), (Map_Error.Error 2 1), (Map_Error.Error 2 0), (Map_Error.Error 1 1), (Map_Error.Error 1 0), (Map_Error.Error 0 0)] did not equal [(Map_Error.Error 3 (Map_Error.Error 3 3)), (Map_Error.Error 3 (Map_Error.Error 2 2)), (Map_Error.Error 3 (Map_Error.Error 1 1)), (Map_Error.Error 3 (Map_Error.Error 0 0)), (Map_Error.Error 2 (Map_Error.Error 2 2)), (Map_Error.Error 2 (Map_Error.Error 1 1)), (Map_Error.Error 2 (Map_Error.Error 0 0)), (Map_Error.Error 1 (Map_Error.Error 1 1)), (Map_Error.Error 1 (Map_Error.Error 0 0)), (Map_Error.Error 0 (Map_Error.Error 0 0))]; first difference at index 0  (at X:\NBO\enso\test\Base_Tests\src\Semantic\Warnings_Spec.enso:319:9-503).
2384 tests succeeded.
8 tests failed.
29 tests skipped.
2 groups skipped.
```

This repro seems deterministic to me - it failed each time on several retries, but only if all conditions were met. If I forgot about just one thing (be it `-ea`, http tests, or JUnit), it would _not_ reproduce.

Weirdly the instrumentation tests also are failing locally for me, but that is not related to this issue. cc: @JaroslavTulach any hints what may be happening with the instrumentation tests?

@GregoryTravis can you check if you can also reproduce the problem with the steps above? You could then pick up debugging it, or I can give it a go as well.

**Comment by radeusgd** [comment]
Sorry I first posted the comment above with wrong repro (I was trying to find a minimal repro and did a mistake). I have updated the comment with a correct repro now.

**Comment by Akirathan** [comment]
@radeusgd I am able to reproduce the problem very simply with:
```diff
diff --git a/test/Base_Tests/src/Semantic/Warnings_Spec.enso b/test/Base_Tests/src/Semantic/Warnings_Spec.enso
index 129a0152d..d24fa5728 100644
--- a/test/Base_Tests/src/Semantic/Warnings_Spec.enso
+++ b/test/Base_Tests/src/Semantic/Warnings_Spec.enso
@@ -308,7 +308,7 @@ add_specs suite_builder = suite_builder.group "Dataflow Warnings" group_builder-
         r.should_equal [0, 1, 20, 3, 40, 5, 60, 7, 80, 9]
         Warning.get_all r wrap_errors=True . map .value . should_contain_the_same_elements_as [Map_Error.Error 1 100, Map_Error.Error 3 300, Map_Error.Error 5 500, Map_Error.Error 7 700, Map_Error.Error 9 900]
 
-    group_builder.specify "should be preserved after operations on multi-dimensional Vector" pending="https://github.com/enso-org/enso/issues/8910" <|
+    group_builder.specify "should be preserved after operations on multi-dimensional Vector" <|
         even x = (Warning.attach x x) % 2
         nested_range_even x =
             (0.up_to x).to_vector.map even
@@ -466,5 +466,5 @@ add_specs suite_builder = suite_builder.group "Dataflow Warnings" group_builder-
 main =
     suite = Test.build suite_builder->
         add_specs suite_builder
-    suite.run_with_filter
+    suite.run_with_filter spec_filter="should be preserved after operations on multi-dimensional Vector"
```

And running directly `env JAVA_OPTS=-ea enso --run test/Base_Tests/src/Semantic/Warnings_Spec.enso`

No need for running all the `Base_Tests` at all, just the failing one.

**Comment by GregoryTravis** [comment]
I will try to follow these steps to reproduce it; if I can, then I think I know what needs to be done.

**Comment by radeusgd** [comment]
> @radeusgd I am able to reproduce the problem very simply with:
> 
> ```diff
> diff --git a/test/Base_Tests/src/Semantic/Warnings_Spec.enso b/test/Base_Tests/src/Semantic/Warnings_Spec.enso
> index 129a0152d..d24fa5728 100644
> --- a/test/Base_Tests/src/Semantic/Warnings_Spec.enso
> +++ b/test/Base_Tests/src/Semantic/Warnings_Spec.enso
> @@ -308,7 +308,7 @@ add_specs suite_builder = suite_builder.group "Dataflow Warnings" group_builder-
>          r.should_equal [0, 1, 20, 3, 40, 5, 60, 7, 80, 9]
>          Warning.get_all r wrap_errors=True . map .value . should_contain_the_same_elements_as [Map_Error.Error 1 100, Map_Error.Error 3 300, Map_Error.Error 5 500, Map_Error.Error 7 700, Map_Error.Error 9 900]
>  
> -    group_builder.specify "should be preserved after operations on multi-dimensional Vector" pending="https://github.com/enso-org/enso/issues/8910" <|
> +    group_builder.specify "should be preserved after operations on multi-dimensional Vector" <|
>          even x = (Warning.attach x x) % 2
>          nested_range_even x =
>              (0.up_to x).to_vector.map even
> @@ -466,5 +466,5 @@ add_specs suite_builder = suite_builder.group "Dataflow Warnings" group_builder-
>  main =
>      suite = Test.build suite_builder->
>          add_specs suite_builder
> -    suite.run_with_filter
> +    suite.run_with_filter spec_filter="should be preserved after operations on multi-dimensional Vector"
> ```
> 
> And running directly `env JAVA_OPTS=-ea enso --run test/Base_Tests/src/Semantic/Warnings_Spec.enso`
> 
> No need for running all the `Base_Tests` at all, just the failing one.

For me, that does _not_ reproduce the issue. It only occurs if I do all the steps enumerated above.
