### ISSUE TITLE
Add E2E tests for dashboard to CI

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#8911]
The command to run the tests is `npm run test:e2e` in `app/ide-desktop/lib/dashboard/`.

**Comment by somebody1234** [comment]
Tests typically take 2.2 min to 2.5 min on my machine, if anyone's curious

**Comment by somebody1234** [comment]
@mwu-tow Should these E2E tests just be added to the existing GUI2 CI runs, rather than creating a new CI job?

**Comment by mwu-tow** [comment]
@somebody1234 Unless there are any significant reasons to do otherwise, I'd just put them together with other GUI tests. Essentially make this step "test all JS/TS code".
If need arises, we can always split the job in the future.
