### ISSUE TITLE
Replace Akka Http back to Apache HttpClient

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8934]
Back in https://github.com/enso-org/enso/pull/1169 we replaced Apache HttpClient with Akka Http:
1. Central logging was the main motivation
2. We were already using Akka, so one less dependency

We are coming full circle because it seems we should get back to it.
Re 1: that's no longer valid given our implementation that is based on slf4j.
Re 2: eventually Akka will go

Using Akka Http is not wrong on its own but the current implementation is problematic since we are not terminating the system.
This leads to resource usage (#8806) in tests:
![Screenshot from 2024-02-01 17-04-25](https://github.com/enso-org/enso/assets/292128/7e224389-40d4-4fec-b816-a5459321c346)

**Comment by Akirathan** [comment]
Since JDK provides `HttpClient` capable of handling HTTP requests, I would restrain from using the Apache's httpclient. No need to add yet another dependency. In #8222, I am already migrating the `downloader` project to JDK's httpclient.
