### ISSUE TITLE
Use builtin edition when project's edition cannot be found

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8948]
When we create a new Enso project, `package.yaml` includes the current engine version with which it was created.
This is problematic when sharing projects and after upgrades.

When one upgrades Enso and tries to use an old project with an engine that is now missing it will fail completely to boot the project.
Instead, we could send a warning to GUI of an automatic upgrade and still attempt to use the builtin version of the engine.

**Comment by 4e6** [comment]
The current logic is to ignore the `edition` field and start the project using the packaged language server. It was implemented in #7868

**Comment by hubertp** [comment]
Tried with different subprojects. I can't reproduce anymore. Will reopen if it occurs again.
