### ISSUE TITLE
After stopping the project GUI still attempts to the connect to the language server

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#8966]
To reproduce:
1. Open any project 
2. Once loaded switch to project manager
3. Click stop the project
4. Console starts to spit up errors about not being able to connect to the websocket

![Screenshot from 2024-02-05 13-03-14](https://github.com/enso-org/enso/assets/292128/67d0590e-1fac-4007-bb69-db89557613a4)

**Comment by farmaazon** [comment]
Duplicate of [#8964](https://github.com/enso-org/enso/issues/8964)
