### ISSUE TITLE
Improve diagnostics for failed Standard Library Tests

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#8969]
Currently, when standard library test fails it is mentioned in a summary but with no specific information.

This leads to [output like](https://github.com/enso-org/enso/actions/runs/7782532912/job/21219149952#step:8:7172):
```
[SQLite File] Schemas and Databases: [3/3, 7ms]
    - should be able to get current database and list databases [1ms]
    - should be able to get current schema and list schemas [1ms]
    - does not allow changing schema or database [4ms]
[FAILED] [SQLite File] Tables and Table Types: [3/4, 211ms]
    - should be able to list table types [39ms]
    - should be able to list tables [121ms]
    - [FAILED] should be able to filter tables by name [40ms]
        Reason: 2 did not equal 1 (at C:\runner\_work\enso\enso\test\Table_Tests\src\Database\SQLite_Spec.enso:139:13-76).
    - should be able to filter tables by type [9ms]
[SQLite File] Error Handling: [2/2, 54ms]
    - should wrap errors [18ms]
    - is capable of handling weird tables [36ms]

(…almost 3k lines of logs here…)

Value_Type: [2/2, 11ms]
    - should have a nice display text representation [3ms]
    - should use correct in-memory logic to reconcile pairs of types for operations like union/iif [8ms]
4312 tests succeeded.
1 tests failed.
121 tests skipped.
25 groups skipped.
```

This is difficult to read and understand — at the end of failing command there is just information that 1 test failed, but no information about which test it was. The only way to find out is to scroll through the endless stream of logs and look for the failure. (Well, one could search for `[failed]` but this is not obvious.)

I suggest that:
* the summary should contain information about which test failed;
* this information should contain some string that can be used to search for the failure details in the logs.

**Comment by radeusgd** [comment]
I think the idea is indeed worth considering.

For now, we have an environment variable `REPORT_ONLY_FAILED` which if set, makes only failed tests printed in the report.
The downside of that is that we can't track progress of which tests _are being executed_ on the CI - the process would go silent for a long time, and if all tests succeed not print anything. IMO that is not a good default for CI.

Also please note that the generated HTML test report based on the `JUnit.xml` files ([example](https://github.com/enso-org/enso/runs/21226116835?pr=8921)) does contain a summary of failed tests at the bottom - I usually use that and it's been working quite well for me.

![image](https://github.com/enso-org/enso/assets/1436948/d8be4cb8-3a50-4521-bd12-ed24ccff90b5)

Not trying to discourage improvements to the test lib, I think they could be valuable.

**Comment by jdunkerley** [comment]
Test stability much better these days!

**Comment by radeusgd** [comment]
It feels like this was actually handled by #9986
