### ISSUE TITLE
Avoid `Unable to create a system terminal, creating a dumb terminal`

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#8977]
Enso doesn't work well from CLI when its output is redirected to a file. The `jline` intergration prints a nasty warning:
```
Feb 05, 2024 5:41:42 PM org.jline.utils.Log logr
WARNING: Unable to create a system terminal, creating a dumb terminal (enable debug logging for more information)
```

**Goal 1**: Avoid printing this warning. Redirecting output to a file is a common operation. It is (going to be) used by Enso users. Printing such a warning _seems unprofessional_.

There are however other problems associated with terminal. For example @Akirathan has designed nice ANSI coloring as part of his work on 
- #8622

However, the _nice colorings_ are **off by default** and one needs to use special environment variable [ENSO_TEST_ANSI_COLORS](https://github.com/search?q=repo%3Aenso-org%2Fenso%20ENSO_TEST_ANSI_COLORS&type=code) to enable them. Such a behavior is _nasty towards Enso users_ - they don't want to read our documentation to get the best of Enso!

**Goal 2**: Enable _nice colorings_ by default and only **disable them** when not running in a terminal. JLine is able to detect such situation and use its _dump terminal_. We shall be able to detect such situation as well and act appropriately.

The `ENSO_TEST_ANSI_COLORS` environment variable may still exist. However the _default value_ should be more _appropriate_. Of course, the value of `ENSO_TEST_ANSI_COLORS` takes precedence over the default, but when the default is sane, many usages of the variable 

- see https://github.com/search?q=repo%3Aenso-org%2Fenso%20ENSO_TEST_ANSI_COLORS&type=code

can be removed in favor of the sane default value.

**Comment by Akirathan** [comment]
Closing as not relevant anymore. Both goals are already achieved nowadays.
