### ISSUE TITLE
Drop-down widget filtering

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#9058]
* The drop-down should be shown on any click on the widget, not just the arrow.
* When the internal widget of the drop-down is something editable (text or numeric input), _once user will start typing_, the options list should be filtered by the current content.

**Comment by somebody1234** [comment]
i wonder if autosizing the widget should be part of this task? or maybe the previous one?

**Comment by Frizi** [comment]
Refinement notes:
Q: When there is no widget for a value (e.g. argument placeholder with just a name), how are we supposed to filter the dropdown?
A: Potentially transform the argument name into an text input with the name as a placeholder.

Q: How to handle nested dropdowns, and where we should type when we already have a complex expression (e.g. a list expression) in place?
A: Needs more design. For now we can ignore the problem and not allow filtering for such cases.

- Filtering should only start once you type anything (after first keyboard event). The initial value should NOT filter the list.

Potential implementation: Use Vue contexts to provide a "dropdown widget" API to child widgets.
