### ISSUE TITLE
Render self argument connections as arrows

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9064]
Update the self argument connections as per the figma design.

So instead of seeing operator12345

![image](https://github.com/enso-org/enso/assets/1720119/561af45b-55e7-4dbb-aba5-89a876d7e2fa)

we get an arrow

![image](https://github.com/enso-org/enso/assets/1720119/86793d6f-5807-47b4-bb7e-0a8e1795da2a)

```[tasklist]
### Tasks
- [ ] https://github.com/enso-org/enso/pull/9099
- [ ] https://github.com/enso-org/enso/pull/9116
```

**Comment by Frizi** [comment]
Refinement notes:
- The arrow should appear only in the most obvious case: method call with a "self" argument placed the access chain
- The icon should become a port to which you can connect a different "self" value
- The icon should still behave as a drag handler for the node when we are not dragging any connections
