### ISSUE TITLE
Opening and closing component browser without creating a node breaks the metadata

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9103]
Create a simple workflow (or any workflow) like so

![image](https://github.com/enso-org/enso/assets/1720119/8e73c175-a6f4-43ba-a328-9c697bf9b23d)

Open the component browser by pressing enter or the plus button.

![image](https://github.com/enso-org/enso/assets/1720119/4b74cbd2-9e06-44d5-bcc1-36d2bb572ad5)

Imagine user has now changed their mind and wants to close the component browser.

Click on the graph editor background.

**Expected behaviour:**

Component browser is closed and no new component is added.

**Actual behaviour:**

Metadata gets broken, so layout is lost.
A = component gets created

![image](https://github.com/enso-org/enso/assets/1720119/24f9fe53-5c5e-48f6-9f46-f918a03ceb80)

**Comment by farmaazon** [comment]
Clicking-off the opened component browser always accepted the input - this was by design, to keep it consistent with other fields (like numeric/text widget)

The lost metadata are indeed an issue

**Comment by AdRiley** [comment]
But in this case I didn't input anything in the component browser.

**Comment by AdRiley** [comment]
This is much better in the ide2-enso-win-x64-2024.1.1-nightly.2024.2.21 build. Everything reported is fixed :).

But in testing I found one more. If you drag from an existing component and then click off without typing anything it produces a strange rhs component

![image](https://github.com/enso-org/enso/assets/1720119/827921a6-2256-4de0-ba18-4742de0d983b)

Again in this case I think it shouldn't create a component.

**Comment by Frizi** [comment]
@AdRiley What you see is an argument placeholder for the dot operator right-hand side, since the default node expression (`operator1.`) includes the trailing dot. This isn't really a bug, more like a missing feature to remove that dot. An implementation of that is already in progress by @farmaazon.

**Comment by AdRiley** [comment]
OK. I'll test it again after that feature is done and see if it then feels better as an end user.

**Comment by farmaazon** [comment]
The PR: https://github.com/enso-org/enso/pull/9127
