### ISSUE TITLE
Unexpected warning when running a standalone script

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#9109]
Repro:
1. create a file `test.enso` with contents `main = 42`
2. run it

## Actual behaviour

```
> .\built-distribution\enso-engine-0.0.0-dev-windows-amd64\enso-0.0.0-dev\bin\enso --run .\test.enso
[WARN] [2024-02-20T12:04:21+01:00] [enso.org.enso.interpreter.runtime.SerializationPool] Serialization of module `test` failed: Unable to write cache data for test.`
42
```

A warning about inability to write cache data for the script's module is printed.

## Expected behaviour

The warning shouldn't be there. I don't think we should expect cache for standalone scripts.

**Comment by hubertp** [comment]
The default log level is warning, I think. So we should reduce the log level of that particular message to trace or debug.

**Comment by radeusgd** [comment]
> The default log level is warning, I think. So we should reduce the log level of that particular message to trace or debug.

On the other hand, if writing the cache for some proper module fails (which would not be expected), it may make sense to keep such an information at the Warning level.

So maybe instead we could not attempt to write a cache for the standalone script at all? I think it will just always fail, so logging it at whatever level feels unnecessary here, and I don't think that should influence the log level for the cases when this _is_ unexpected.

**Comment by 4e6** [comment]
I assume that the runner's log level was lowered to `WARN` in [#7825](https://github.com/enso-org/enso/pull/7825/files#diff-7111bba91c7d387c5ae7e93bc67c9e0b513b31f99e3a10a86d1a1cff82baff0b) to make the logging work in case of the language server. 

I'd leave the `WARN` default level for the language server, and change it back to `ERROR` for other commands.
