### ISSUE TITLE
Add indicator on nodes with warnings

### ISSUE THREAD

**Issue by somebody1234** [enso-org/enso#9125]
- Split out of #8678 as the corresponding PR was merged without support for this specific feature.

The UI should (?) match with the existing orange border present on GUI1.

**Comment by somebody1234** [comment]
pinging @AdRiley as a heads up.
(@ anyone - feel free to edit the description to be clearer, and/or include screenshots.)

**Comment by farmaazon** [comment]
I'm not sure if we need strictly orange border - maybe just warn sign next to node? We plan making icons for errors too: https://github.com/enso-org/enso/issues/8677

**Comment by AdRiley** [comment]
Do we need a design? I guess the user requirement is to be able to see a component has warnings even when the component is not hovered or selected. And then hover/select shows you the warning.

**Comment by somebody1234** [comment]
yeah...
... just tried adding a border around the node. while it *technically* works, it seems to be very difficult to get it to render below the edges.

**Comment by farmaazon** [comment]
We will go with the icon, as it's easier than making a working border.

Soon new icons will be merged. We should display them with the following colors (ignore the trash bin)

![Image](https://github.com/enso-org/enso/assets/3919101/15af1fb3-3ada-4503-aa9a-b4df019a9d74)

**Comment by farmaazon** [comment]
Also info from @jdunkerley:
> it should appear to the left of the node, to the left of the menu if shown
