### ISSUE TITLE
Chained operator syntax does not work if there is no space after dot on a new line

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#9138]
```
from Standard.Base import all
main =
    Vector.new_builder
        . append 1
        . to_vector
```
Works, but
```
from Standard.Base import all
main =
    Vector.new_builder
        .append 1
        .to_vector
```
fails with:
```
Execution finished with an error: Method `append` of type Integer could not be found.
        at <enso> tmp.main<arg-1>(tmp.enso:21:9-17)
        at <enso> tmp.main(tmp.enso:20-22)
```

**Comment by kazcw** [comment]
This is per spec: https://github.com/enso-org/design/blob/wip/wd/enso-spec/epics/enso-spec-1.0/03.%20Code%20format%20and%20layout.md#chained-operator-code-blocks

Without the spaces it is the syntax for passing operator sections as arguments in an argument-list block.

<blockquote><img src="https://github.githubassets.com/assets/github-logo-55c5b9a1fe52.png" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com">Build software better, together</a></strong></div><div>GitHub is where people build software. More than 100 million people use GitHub to discover, fork, and contribute to over 420 million projects.</div></blockquote>

**Comment by JaroslavTulach** [comment]
Yeah, I thought this is the specified behavior. But people do these mistakes as your fix to my https://github.com/enso-org/enso/pull/8671/commits/bc05faa86b22db3a60f789454d9d74db16aaa6a9 test shows, @kazcw ;-)
