### ISSUE TITLE
Add comments to components

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9162]
This story adds the ability to display one line comments for components in the GUI.

That is comments that are stored in the enso file like so:

```
## add a row number so I can use it for my transpose
operator20253 = operator95608.add_row_number
```

It should appear in the GUI the same as the error dialog, but positioned above the component

![image](https://github.com/enso-org/enso/assets/1720119/94074903-9f7e-406b-9f5a-efcd06a5b57a)

As always please don't take my poor artwork as anything more than an indicator of the idea. Fonts, sizing, spacing etc. should match existing standards.

- New comments can be added using a new menu item on the full wheel
- New menu item should be top right (North-East) on the wheel (so next to where the comment appears)
- Comment should be spaced to not overlap with the full wheel
- If a comment already exists the menu item button will put the comment in edit mode
- Comment can also enter edit mode by Ctrl-clicking on the comment
- If a user deletes all the text in a comment and then exits edit mode the comment should be removed

```[tasklist]
### Tasks
- [ ] #9218
- [ ] Removing empty comments from node
- [ ] Icon for editing comments
- [ ] #9230
```

**Comment by somebody1234** [comment]
i assume Ctrl+Click should also put the comment into edit mode, for consistency with nodes?

**Comment by AdRiley** [comment]
> i assume Ctrl+Click should also put the comment into edit mode, for consistency with nodes?

Yes good call. In fact I think it should probably only be Ctrl+Click for consistency with nodes. Will update story.

**Comment by farmaazon** [comment]
Refinement notes:
* To simplify, let's keep comments on the same layer as the node.
* Display entire content as plain HTML. When editing, let's use codemirror to allow multiline edits. 
* For now, just display documentation code as-is, and parse the edit result.
