### ISSUE TITLE
API for changing root directory of local project manager

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#9174]
Part of local project manager's improvements epic.

We are missing API for changing the root directory of Enso's projects. Right now that is hardcoded at `~/enso/projects` (or the equivalent on non-Linux based OS) and cannot be changed.
- [ ] Ability to specify a default location for Enso projects that is different from the hardcoded one
- [ ] Ability to switch between roots (can be treated as workspaces)

**Comment by 4e6** [comment]
Implemented in #8650
