### ISSUE TITLE
Verify downloading Enso project locally works

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#9176]
Part of local project manager's improvements epic.

Apparently the feature has been supported on the backend for a while but needs to be verified. Problems have been reported.

**Comment by 4e6** [comment]
Project manager exposes the [`projects/{project-id}/enso-project`](https://github.com/enso-org/enso/blob/fecdd534b1f4256955a2c9c80da5ac80f7e4a630/docs/language-server/project-manager-http-endpoints.md#projectsproject_idenso-project) HTTP endpoint for downloading projects.

The `Download` menu entry of the projects list redirects to the `/api/project-manager/projects/${asset.id}/enso-project` https://github.com/enso-org/enso/blob/fecdd534b1f4256955a2c9c80da5ac80f7e4a630/app/ide-desktop/lib/dashboard/src/components/dashboard/AssetRow.tsx#L365-L368

Which is being rewritten by the Electron server to the appropriate project manager URL
https://github.com/enso-org/enso/blob/fecdd534b1f4256955a2c9c80da5ac80f7e4a630/app/ide-desktop/lib/client/src/bin/server.ts#L137-L142

URL rewriting is not implemented in the dev server (when GUI started with `npm run dev`, and therefore the `Download` menu entry only works in the desktop app.

**Comment by hubertp** [comment]
So the verification bit is done. I create a follow up ticket for you @somebody1234 https://github.com/enso-org/enso/issues/9482
