### ISSUE TITLE
`executeExpression` not working for all builtin visualizations

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#9194]
`executionContext/executeExpression` only seems to be working for the default preprocessor.

Working:
- executeExpression: `Standard.Visualization.Preprocessor.default_preprocessor _ <| operator3.column_count`

Not working:
- executeExpression: `Standard.Visualization.Warnings.process_to_json_text _ <| operator3.column_count`
    > Method `Warnings` of type Main could not be found.
- executeExpression: `Standard.Visualization.Table.Visualization.prepare_visualization _ 1000 <| operator3.info`
    > Method `Table` of type Main could not be found.

It looks like only the default preprocessor is exported from `Standard.Visualization`?

**Comment by GregoryTravis** [comment]
@kazcw Can you tell me how to reproduce this bug?

**Comment by farmaazon** [comment]
> @kazcw Can you tell me how to reproduce this bug?

We use `executeExpression` in component browser's visualization preview; so you may open Component Browser, switch to code edit mode with Tab, and pick `Warning` or `Table` visualization.
