### ISSUE TITLE
Attached workflow breaks in GUI2

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9198]
Reported by @jdunkerley 

The attached workflow does not work correctly in GUI2.

[ESG_Employee_Figures.zip](https://github.com/enso-org/enso/files/14417387/ESG_Employee_Figures.zip)

@jdunkerley will be able to provide the data files.

**Comment by jdunkerley** [comment]
Here is the rough summary:

There is an error in one of the grouped functions (`build_energy_source`).

When trying to repair this, the GUI won't evaluate (possibly due to the order of nodes being incorrect).
If you try and fix with the code editor (e.g. sorting the imports at the top of the file or manually fixing the function) then the file is not correctly saved.

In the end, once we deleted the metadata from the file we were able to repair it (though was still painful).

Editing any collapsed function also appears to cause a complete recalculation which likewise makes the process very painful.

With the metadata deleted, the main function was laid out correctly but grouped functions were laid out going upwards not downwards.

**Comment by farmaazon** [comment]
Without data, I cannot follow those steps: I have Unauthorized error.

There is, however, another bug: When opening this project and showing code editor, it seems to be constantly re-evaluated without my action (the errors flicker).

**Comment by jdunkerley** [comment]
Data files used are:
[gridData_summary.csv](https://github.com/enso-org/enso/files/14418952/gridData_summary.csv)
[Commuting.xlsx](https://github.com/enso-org/enso/files/14418953/Commuting.xlsx)
[BuildingUsage.csv](https://github.com/enso-org/enso/files/14418959/BuildingUsage.csv)
[buildingEnergyStats.zip](https://github.com/enso-org/enso/files/14418964/buildingEnergyStats.zip)

For the postgres access I will message you separately

**Comment by farmaazon** [comment]
Thanks, @jdunkerley. Yes, the project is very unstable. Actually, single entering node + trying to fix paths actually _freezes_ IDE.

Investigation in progress.

**Comment by farmaazon** [comment]
I know what is the problem: its combination of several factors:
1. this project's 100 lines of code produced 240KB of idmap
2. After a single edit, the idmap seems completely shuffled. The expected diff is large
3. We try to [apply O(ND) algorithm](https://neil.fraser.name/writing/diff/myers.pdf) and are choked.

Not sure if there is a workaround. We could use the stupid O(1) algorithm from the old GUI... but in that case we likely send 240KB of edit to the engine on every edit, what is far from ideal.

The better solution would be to reduce size of idmap, (already reported as an issue) - however, we must be _very_ efficient. Currently, a single entry takes 82-86 bytes; even if we reduce it to 12 bytes (two words for span boundary -  may not suffice, and 8 bytes for UUID) we quickly get back to ~250KB when the modules will grow - and even a module of 1000 lines should be considered reasonable.

There is also an idea of getting rid of IdMap from file entirely, and make separate API for sharing Ids of AST nodes. In this API we could make a smarter diffing.

**Comment by farmaazon** [comment]
@jdunkerley you may check package with fixes: https://github.com/enso-org/enso/actions/runs/8079248374?pr=9207 I didn't check yet the problem of nodes ordering after removing metadata.

Also, I saw many duplicated imports - were they added by GUI?

<blockquote><img src="https://opengraph.githubassets.com/f8ebdfd0d920471af450bd2f1e7c9ad4925fec8bbdf174e2c946b7139c851111/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">Add workaround for huge idmap diffs · enso-org/enso@f45963a</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by jdunkerley** [comment]
Definitely seems a lot better, thanks @farmaazon

**Comment by jdunkerley** [comment]
> Also, I saw many duplicated imports - were they added by GUI?

Yes still an issue.

**Comment by farmaazon** [comment]
Made follow-up issues: #9255 and #9257.

I cannot reproduce the problem with imports. Let's see if it will happen in future projects.
