### ISSUE TITLE
Opening one of my old projects makes new GUI freeze for ~20 seconds.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#9199]
The project [Unnamed_10.zip](https://github.com/enso-org/enso/files/11122369/Unnamed_10.zip)

Doing any change in it makes it "safe" - reopening afterward, I don't see any freezes.

**Comment by hubertp** [comment]
Logs?

**Comment by farmaazon** [comment]
Well, I haven't recored any, as I was unable to read in frozen GUI, and I think this is not a bug of project manager.

**Comment by farmaazon** [comment]
No longer reproducible.
