### ISSUE TITLE
Arguments without value set should be hidden on components.

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9208]
Components with arguments without value set should generally have those arguments hidden.

![image](https://github.com/enso-org/enso/assets/1720119/45a60adf-d0d5-4970-b685-798e1a622630)

Unless:
- Only one component is selected. Then all values/widgets are shown.
![image](https://github.com/enso-org/enso/assets/1720119/d293fa8d-35b6-4ba9-94fa-09c7e05a07ec)

- Some values are marked by libs team as always show. This needs to be respected.

**Comment by farmaazon** [comment]
If I guess correctly, "default values" are in fact "arguments without value set, which have a default"?

Or should we hide also arguments which have been set to a value equal to the default value of given parameter?

**Comment by AdRiley** [comment]
Yes thank you. Arguments without value set. I don't think actually if they have a default or not makes a difference.

I think that what you see in the code editor should be the same as you see on the graph. So for the above example 

![image](https://github.com/enso-org/enso/assets/1720119/45b21c22-aab6-49f6-a0c5-51110f8976a9)

**Comment by farmaazon** [comment]
> Yes thank you. Arguments without value set. I don't think actually if they have a default or not makes a difference.

I think it makes. We will display all ports which have to be connected by the user to make component functioning properly.

**Comment by farmaazon** [comment]
Refinement notes:
* We hide every placeholder (widget without value set) which is an argument with default value
* `Display` parameter of widget configuration should override above.
* A node should be extended only when it's the only node selected.
* When during box selecting, no node should be extended (or shrunk) before finishing drag.
* We keep displaying unset arguments which have no default value (to inform user about arguments they have to provide).
* Extending it tied to showing circular menu (show both or none). 
* Add extending animation if it will be easy.
