### ISSUE TITLE
Component Browser should not be prepopulated with text and should be connected

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9210]
When adding a new component that is connected to an existing component the component browser should: 
- be connected
- not be pre-populated with operator123456.

From: 

![image](https://github.com/enso-org/enso/assets/1720119/3b4e4898-8e32-4ec4-93e9-906b1841cf29)

To:

![image](https://github.com/enso-org/enso/assets/1720119/6981f719-c158-4afc-830a-9bc5aac9906c)

**Comment by farmaazon** [comment]
1. What if use won't pick any component from list but instead type `foo`? Should we apply `operator123456.` before?
2. What if user instead type some code like `+ 2` or `2 + 2` or `(foo)`?

**Comment by AdRiley** [comment]
Yes I think we apply `operator123456.` before all of those. The `operator123456.` is implicit because the user created a connected component.

If the user wants a unconnected component they can use the bottom left + icon.

**Comment by farmaazon** [comment]
Refinement notes:
* We should replace CB input with codemirror, where the `operator12345.` will be replaced with WidgetPort (or something, to which we could display a connection). This will be a codemirror decoration.

**Comment by farmaazon** [comment]
Update: Let's use Lexical here, not CodeMirror. We don't need the understanding of Enso language immediately (e.g. coloring).

**Comment by kazcw** [comment]
Update: We decided during standup that we *will* support the equivalent of removing the dot after typing space.
