### ISSUE TITLE
New "add component" menu item on component

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9219]
We want a new + menu item on the small menu that sits underneath the menu like so

![image](https://github.com/enso-org/enso/assets/1720119/2b36cca9-5e8e-477f-9ba8-4ff5e896e0d5)

Pressing it opens the component browser connecting a new component to the existing one.

If the visualisation is open the + button needs to move down under the visualisation

![image](https://github.com/enso-org/enso/assets/1720119/4b50e565-8e5a-4ef8-b578-21e1fa1da221)

When the new component is added it should be positioned 
 - vertically in line with where the + button is when it is pressed
 - horizontally left aligned with component it is being added from

I **think** the + should be grey to match the other wheel icons. Not blue like in the screenshots and the existing + button.

**Comment by farmaazon** [comment]
> When the new component is added it should be positioned
> 
> vertically in line with where the + button is when it is pressed
> horizontally left aligned with component it is being added from

What if the place is already occupied? Also, I think the node appearing in place of + button will be very close to the node above - much closer than it is today, when you press enter with node selected.

**Comment by AdRiley** [comment]
This is the enter button spacing today

![Image](https://github.com/enso-org/enso/assets/1720119/664c8481-2933-4ee8-b0ef-24536333d430)

Not sure we will be far out. Can always move the + button down a bit.

In terms of collisions. I think we just put it on top for first pass. The user can see where it is going to go so it is their choice.
