### ISSUE TITLE
After uploading cloud project, it's no longer executed succesfully

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#9224]
I think it's because the project has different name than assumed "local.Project_root"

![image](https://github.com/enso-org/enso/assets/3919101/e944584c-bd21-457f-9d4a-476b70a42c13)

**Comment by farmaazon** [comment]
@somebody1234 I haven't checked yet, but does dashboard set `Project_root` as project name for cloud projects?

**Comment by somebody1234** [comment]
@farmaazon i don't think so - i think it's the cloud backend that does. @PabloBuchu any ideas?

**Comment by PabloBuchu** [comment]
Closing as it was fixed on cloud backend side. All uploaded projects should open without issues
