### ISSUE TITLE
Add ability for a visualisation to add a component

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9226]
There needs to be a way for visualisations to be able to add components to the graph connected to the component that the visualisation is on.

For example you create a filter in the table view and then want to add a filter component.

**Comment by farmaazon** [comment]
Proposition for testing (except the one in description)
* Click at object in JSON visualization to create node fetching it
* Button at the warning visualization's top bar adds a node removing warnings.

The node content could be a pattern, where then the node ID is inserted.

Adding imports is not in scope of this task.
