### ISSUE TITLE
Problems catching a Panic thrown within a TCO loop

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#9251]
The following program demonstrates the issue:

```ruby
from Standard.Base import all
import Standard.Base.Errors.Illegal_State.Illegal_State

# Function with TCO
foo1 x =
    if x > 10 then Panic.throw (Illegal_State.Error "foo1") else
        @Tail_Call foo1 x+1

# Same loop but without TCO
foo2 x =
    if x > 10 then Panic.throw (Illegal_State.Error "foo2") else
        foo2 x+1

main =
    handle caught =
         IO.println "Caught "+caught.payload.to_text

    IO.println "without TCO:"
    Panic.catch Any handler=handle <| foo2 0
    IO.println "now, with TCO:"
    Panic.catch Any handler=handle <| foo1 0
    IO.println "done (will not be printed 🙁)"
```

### Actual behaviour

```
without TCO:
Caught (Illegal_State.Error 'foo2' Nothing)
now, with TCO:
Execution finished with an error: Illegal State: foo1
        at <enso> Panic.throw(Internal)
        at <enso> catching.foo1<arg-1>(catching.enso:6:20-59)
        at <enso> catching.foo1(catching.enso:6-7)
        at <enso> catching.main(catching.enso:21:5-44)
```

We can see that the Panic thrown from `foo1` is not caught in main and instead fails the whole function.

The only difference between `foo1` and `foo2` is that `foo1` relies on `@Tail_Call`.

### Expected behaviour

Both functions should behave the same and it should be possible to catch the panic in both cases.

```
without TCO:
Caught (Illegal_State.Error 'foo2' Nothing)
now, with TCO:
Caught (Illegal_State.Error 'foo1' Nothing)
done (will not be printed 🙁)
```

**Comment by radeusgd** [comment]
We've been observing panics falling through the test suite and crashing the suite from time to time. I suspect that this might also have been an instance of this issue.

**Comment by hubertp** [comment]
Anyone who is looking into it should check if there is no duplicate for it already. I believe this was a known issue.

**Comment by Akirathan** [comment]
> Anyone who is looking into it should check if there is no duplicate for it already. I believe this was a known issue.

@hubertp I was not able to find any potential duplicates.
