### ISSUE TITLE
Integrate Oracle GraalVM into Enso CI

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#9266]
Oracle GraalVM (formerly GraalVM EE) is said to offer performance benefits as well as additional functionality (for example **isolates** as needed by #9171). Enso shall not ignore Oracle GraalVM, but continuously work towards using the best of both:
- GraalVM Community
- Oracle GraalVM

Oracle GraalVM comes with [extremely benevolent license](https://www.graalvm.org/faq/) (for a non-open source component) which allows

>  use by any user including commercial and production use. Redistribution is permitted as long as it is not for a fee

As such there is nothing stopping us to use and test against Oracle GraalVM in our CI pipelines. Thus, let's start with **using Oracle GraalVM in our CI**. Having such a CI pipeline set up we can move towards more intricate usages of Oracle GraalVM as outlined by 
- #9171

```[tasklist]
### Tasks
- [x] Set a CI pipeline up that builds and tests engine with Oracle GraalVM
- [x] Execute (engine) benchmarks against Oracle GraalVM
```

**Comment by mwu-tow** [comment]
@JaroslavTulach 
Is it enough to just replace the GraalVM package with the [non-community one](https://www.oracle.com/java/technologies/downloads/#graalvmjava21-linux) in `PATH`/`JAVA_HOME`/`GRAALVM_HOME` and then run everything "as usual" or is there something more that CI needs to do here? Do we need to somehow inform sbt/engine that it is provided a different Graal flavour?

**Comment by JaroslavTulach** [comment]
> @JaroslavTulach Is it enough to just replace the GraalVM package with the [non-community one](https://www.oracle.com/java/technologies/downloads/#graalvmjava21-linux) in `PATH`/`JAVA_HOME`/`GRAALVM_HOME` and then run everything "as usual" 

Yes, that should be enough. When working on #9171, that's exactly what I have done. Download _Oracle GraalVM_ start `sbt` with that JVM and then do everything normally. There appears a warning in the logs, but otherwise things seem to work fine.
