### ISSUE TITLE
Prefix autoscoped constructors with ..

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#9275]
As of #9190 the autoscoped constructors are prefixed by `~`. That's unfortunate as it is using the same symbol in _expression space_ as well as _type space_. Should Enso allow treating of _types as expressions_, it will not be possible to differentiate whether one wants to express suspended argument or autoscope a constructor.

Detailed [description by Wojciech](https://github.com/orgs/enso-org/discussions/8646#discussioncomment-8677685) is also available. As such a decision was made to replace `~` by `..`.

**Comment by wdanilo** [comment]
More info on the technical issue with the current design here: https://github.com/orgs/enso-org/discussions/8646#discussioncomment-8677685

<blockquote><img src="https://opengraph.githubassets.com/da18625b4bceae2c423c3053f8705725fd065dd737881ae1a33ace30ae9a19d6/orgs/enso-org/discussions/8646" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/orgs/enso-org/discussions/8646">Autoscoping of constructors · enso-org · Discussion #8646</a></strong></div><div>Do you remember how ugly it is to always prefix a constructor of a type with its type name? Always write something like: table.aggregate Aggregate_Column.Count Enso should do better! Let's discuss ...</div></blockquote>
