### ISSUE TITLE
Default view/zoom should show the workflow

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9316]
- Build a simple workflow
- Zoom out as far as you can and move the workflow into a corner

![image](https://github.com/enso-org/enso/assets/1720119/b278fb87-a3ac-43d4-978d-000623b1baf0)

- Close and re-open project

![image](https://github.com/enso-org/enso/assets/1720119/363164c4-6e33-44c0-8a92-ab2f8d1f2bbe)

Expected behaviour:

The workflow should be visible.

Actual behaviour:

We get an apparently empty screen.

**Comment by farmaazon** [comment]
There is also https://github.com/enso-org/enso/issues/6250 which one do we prefer @AdRiley ? They are of similar difficulty.

**Comment by AdRiley** [comment]
Let's do https://github.com/enso-org/enso/issues/6250 . Closing this one as a duplicate.
