### ISSUE TITLE
Allow project manager to write files

### ISSUE THREAD

**Issue by 4e6** [enso-org/enso#9360]
Implement a command that would allow the project manager to write files.

### API

- `--filesystem-write-path {path}` - the path to the file. Create if not exists
- `--filesystem-write-payload {data}` - the base64 encoded string with the file contents

**Comment by 4e6** [comment]
We can also use `stdin` for payload. Should be more suitable in case of big files

**Comment by somebody1234** [comment]
yeah, stdin is probably a better idea. i can't imagine commandline would handle even medium-sized files particuarly well...

**Comment by somebody1234** [comment]
i suppose more importantly - *theoretically* that'd allow for streaming uploads. *realistically* however, last i checked, `http:` didn't support streaming request bodies.
