### ISSUE TITLE
Test Randomly Failing: `componentBrowser.spec.ts:240:1 › Visualization preview: user visualization selection`

### ISSUE THREAD

**Issue by mwu-tow** [enso-org/enso#9369]
See the following failed test run:
https://github.com/enso-org/enso/actions/runs/8232620344/job/22520547106?pr=9342#step:8:707

```
 1) componentBrowser.spec.ts:240:1 › Visualization preview: user visualization selection ──────────

   Test timeout of 60000ms exceeded.

   Error: locator.click: Test timeout of 60000ms exceeded.
   Call log:
     - waiting for getByRole('button', { name: 'Table' })


     249 |   await expect(locate.jsonVisualization(page)).toExist()
     250 |   await locate.showVisualizationSelectorButton(page).click()
   > 251 |   await page.getByRole('button', { name: 'Table' }).click()
         |                                                     ^
     252 |   // The table visualization is not currently working with `executeExpression` (#9194), but we can test that the JSON
     253 |   // visualization is no longer selected.
     254 |   await expect(locate.jsonVisualization(page)).not.toBeVisible()

       at /runner/_work/enso/enso/app/gui2/e2e/componentBrowser.spec.ts:251:53
```

**Comment by mwu-tow** [comment]
Another occurrence: https://github.com/enso-org/enso/actions/runs/8232224820/job/22509187926?pr=9323#step:8:707

<blockquote><img src="https://opengraph.githubassets.com/0e16c9ad9fc614bf096e0a335a8650bd20dadc0e5439f9769d0856c7eeb8584f/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso">[CI] Upload the directory as an artifact, not just its content · enso-org/enso@ba888f5</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>

**Comment by farmaazon** [comment]
Not seen since quite a long time, I think it was fixed by one of the test-fixing PRs.
