### ISSUE TITLE
Reduce parser dependencies

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#9374]
Now that GUI1 has been removed, a lot of the Rust parser's dependencies could be eliminated, including most/all of the `prelude` dependencies; `visit_items` in particular is generated by a macro crate, but now only used for testing. If we do the test some other way we could eliminate the macro and its dependencies. This would improve build times and reduce source code to maintain.

**Comment by JaroslavTulach** [comment]
CCing @Frizi
