### ISSUE TITLE
Dropdown width is truncated.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#9379]

**Comment by jdunkerley** [comment]
Better screenshot of truncation issue:
![image](https://github.com/enso-org/enso/assets/4699705/3224da1b-2a24-4c37-b28b-58778dbdaa1c)

**Comment by farmaazon** [comment]
I just pasted the wrong link.

**Comment by jdunkerley** [comment]
Sorry this still seems to be an issue.

**Comment by kazcw** [comment]
Looked in to this: The type of animation we're using for hidden arguments is essentially incompatible with our current DOM structure. We could fix it by teleporting the dropdown to not be a descendant of the `WidgetArgument`; that is not trivial to do. For now we will have to disable the animation.
