### ISSUE TITLE
Support returning small `BigInteger` values from Java

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#9392]
Allow calls directly to Java libraries to return a small `java.math.BigInteger` and treat it as an Enso `Integer`. Probably requires adding `ToEnsoNumberNode` to `HostValueToEnsoNode` to convert small `java.math.BigInteger` into `long` rather than `EnsoBigInteger`.

See [discussion](https://github.com/enso-org/enso/pull/9272#discussion_r1514571164) in #9272.

**Comment by JaroslavTulach** [comment]
After playing with this for the whole morning and seeing the complexities we have in our `Equals*Node` and `HashCodeNode` specializations, I no longer think this is a _good first issue_.
