### ISSUE TITLE
It is impossible to catch Panics in the GUI

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#9402]
![image](https://github.com/enso-org/enso/assets/1436948/40b41e68-9428-44d7-bad4-276cc15b3a43)

I would like to be able to catch a panic for example in order to inspect its stack trace.

Ideally, the visualization should allow to show a stack trace for a panic by default, but that's probably another thing.

### Expected behaviour

The same operations in the REPL work and allow to catch a Panic:

#### Uncaught panic
```
> r = Panic.throw "foo"
null:: warning: Unused variable r.
Evaluation failed with: foo
java.lang.Exception: foo
        at <enso>.Panic.throw(Unknown Source)
        at <enso>.<eval>(Unknown Source)
        at <enso>.Debug.breakpoint(Unknown Source)
        at <enso>.Rrepl::Rrepl::main(Rrepl.enso:46)
        at <unknown>.org.graalvm.polyglot.Value<Function>.execute(Unknown Source)

> r
null:: error: The name `r` could not be found.
Evaluation failed with: Compilation aborted due to errors.
java.lang.Exception: Compilation aborted due to errors.
        at <enso>.Debug.breakpoint(Unknown Source)
        at <enso>.Rrepl::Rrepl::main(Rrepl.enso:46)
        at <unknown>.org.graalvm.polyglot.Value<Function>.execute(Unknown Source)
```

#### Panic recovered as dataflow error
```
> r = Panic.recover Any (Panic.throw "foo")
null:: warning: Unused variable r.
>>> Nothing
> r
>>> (Error: 'foo')
> r.catch
>>> foo
```

#### Caught panic
```
> r = Panic.catch Any (Panic.throw "foo") c->c.payload
null:: warning: Unused variable r.
>>> Nothing
> r
>>> foo
```

**Comment by radeusgd** [comment]
Added a triage label because while the issue is showing up in the GUI, it likely may be an issue in the runtime.

**Comment by 4e6** [comment]
I encountered this issue today. In the expression

```py
Panic.catch Any (Panic.throw 42) _.payload
```

- when the `Panic.throw 42` sub-expression is instrumented, the `Panic.catch` expression is ignored and the whole expression results in a panic
- when the `Panic.throw 42` sub-expression is not instrumented, the whole expression results in `42` correctly

I created a test reproducing this issue on the [`wip/db/9402-catch-panic-instrumented`](https://github.com/enso-org/enso/compare/develop...wip/db/9402-catch-panic-instrumented) branch

**Comment by 4e6** [comment]
The issue might be that we're unwinding too early

https://github.com/enso-org/enso/blob/f05997d58c39610f343f930b35162f654e68feb8/engine/runtime-instrument-id-execution/src/main/java/org/enso/interpreter/instrument/id/execution/IdExecutionInstrument.java#L254-L256

**Comment by JaroslavTulach** [comment]
The code runs fine from CLI. The project seems to work for me, when "booted". Only later it "diverges from regular run flow":

![works](https://github.com/user-attachments/assets/52649a3f-781e-4851-a76f-f989c052d2b3)

Yes, the problem is likely in the instrument.

**Comment by JaroslavTulach** [comment]
The instrument converts `PanicException` to a sentinel and the catch node then ignores it. The following seems to help:
```diff
index 53a716f4fb..6d29469fad 100644
--- engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CatchPanicNode.java
+++ engine/runtime/src/main/java/org/enso/interpreter/node/expression/builtin/error/CatchPanicNode.java
@@ -20,6 +20,7 @@ import org.enso.interpreter.runtime.EnsoContext;
 import org.enso.interpreter.runtime.callable.argument.CallArgumentInfo;
 import org.enso.interpreter.runtime.data.atom.AtomNewInstanceNode;
 import org.enso.interpreter.runtime.error.PanicException;
+import org.enso.interpreter.runtime.error.PanicSentinel;
 import org.enso.interpreter.runtime.state.State;
 
 @BuiltinMethod(
@@ -61,7 +62,11 @@ public abstract class CatchPanicNode extends Node {
       @CachedLibrary(limit = "3") InteropLibrary interop) {
     try {
       // Note [Tail call]
-      return thunkExecutorNode.executeThunk(frame, action, state, BaseNode.TailStatus.NOT_TAIL);
+      var ret = thunkExecutorNode.executeThunk(frame, action, state, BaseNode.TailStatus.NOT_TAIL);
+      if (ret instanceof PanicSentinel sentinel) {
+        throw sentinel.getPanic();
+      }
+      return ret;
     } catch (PanicException e) {
       panicBranchProfile.enter();
       Object payload = e.getPayload();
```
