### ISSUE TITLE
Add output port on the bottom of the visualisation

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9415]
If a component has an open visualisation there should be an output port on the bottom of the visualisation.
The output port on the bottom of the component should ALSO be present.

**Comment by farmaazon** [comment]
This makes some confusing things:
1. User could use both ports for connecting, right? Then, we could have two variants of visible connection representing the same thing in the code. And what if the user closes and opens the visualization; should the connection stay under component, or move back under the visualization.
2. If connection is connected to port under visualizations, and vis is opened/closed, the edges also change. This was considered undesirable, especially when #8533 is implemented.

**Comment by AdRiley** [comment]
duplicate of #9830
