### ISSUE TITLE
The type shown on the output port should not be fully qualified

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9416]
- The output type should move from the output port to the visualisation
-  When we show the type on the output port we should just show the last part of its name and a tooltip should show the full name

![image](https://github.com/enso-org/enso/assets/1720119/5bc0fd7b-7aaa-4054-951d-93b1b1220074)

So in this example just Table

![Image](https://github.com/enso-org/enso/assets/1720119/266bdd2e-2c0d-4a3c-b29d-b47274ddf6f2)

**Comment by farmaazon** [comment]
I remember in GUI2 the full name was shown after hovering ~2 seconds. Do we want to restore it? I think that sometimes the FQN may be helpful, if there is many types with same name.

**Comment by AdRiley** [comment]
Which types have the same name? Struggling to think when this would be useful.

**Comment by farmaazon** [comment]
Anyone can put `type Table` in his project.

**Comment by AdRiley** [comment]
But typical users of the product that we are building will not. I don't want to block features because of edge cases that will likely never happen.

**Comment by farmaazon** [comment]
But this "show on lag" feature should be fairly simple to implement. And I expect the name collisions will happen once user starts publishing their libraries. Let's discuss it during refinement.

**Comment by farmaazon** [comment]
Refinement note: Take care if the custom vis icons won't obscure the type label.
