### ISSUE TITLE
Component Browser appears to suggest non-existent methods on Integer

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#9429]
As demonstrated by the screenshots:
![Screenshot from 2024-03-14 15-19-38](https://github.com/enso-org/enso/assets/292128/16b266c2-ebb9-4c05-acbf-9fb5404271a1)
![Screenshot from 2024-03-14 14-50-41](https://github.com/enso-org/enso/assets/292128/5d6aa975-3b67-4e38-9be4-e471cb269b33)

**Comment by farmaazon** [comment]
This is what do we get from Suggestion Db:
```
      {
        "type": "Add",
        "id": 248,
        "suggestion": {
          "type": "method",
          "module": "Standard.Base.Data.Index_Sub_Range",
          "name": "count",
          "arguments": [
            {
              "name": "self",
              "reprType": "Standard.Base.Data.Index_Sub_Range.Index_Sub_Range",
              "isSuspended": false,
              "hasDefault": false,
              "defaultValue": null,
              "tagValues": null
            }
          ],
          "selfType": "Standard.Base.Data.Numbers.Integer",
          "returnType": "Standard.Base.Data.Numbers.Integer",
          "isStatic": false,
          "annotations": []
        }
      },
```
Mark the selfType: it's not `Standard.Base.Data.Index_Sub_Range.Index_Sub_Range` as one could expect, but `Standard.Base.Data.Numbers.Integer`. So the IDE thinks that this is an extension method of Integer defined in `Standard.Base.Data.Index_Sub_Range`

The same problem I found for 
* `Standard.Base.Internal.Time.Format.Tokenizer.Format_Token`
* `Standard.Base.Data.Statistics.Accumulator` 
* `Standard.Base.Errors.Common.Additional_Warnings`
* `Standard.Table.Errors.Additional_Invalid_Rows`
* `Standard.Database.Errors.Unmatched_Rows`
* `Standard.Database.Errors.Rows_Already_Present`

These `count` methods are free from this issue:
* `Standard.Base.System.File_By_Line.File_By_Line`
* `Standard.Table.Data.Column.Column`
* `Standard.Database.Data.DB_Column.DB_Column`
