### ISSUE TITLE
Scrolling Down in Cloud Drive View Causes Visual Glitch in Column Header Rendering

### ISSUE THREAD

**Issue by indiv0** [enso-org/enso#9432]
### Discord username

npekin

### What type of issue is this?

Intermittent – Occurring irregularly

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When scrolling down rapidly in the Cloud Drive view, the contents of the rows sometimes "spills over" onto the column headers. This usually occurs when scrolling up/down very rapidly.

> re: the visual glitch... yeah, i think the HTML renderer often struggles to update the clip path before paint. not sure whether it's solveable, but it's not a bad idea to open an issue for it

_Originally posted by @somebody1234 in https://github.com/enso-org/enso/issues/9378#issuecomment-1997830935_
            

### Expected behaviour

Row contents should never visually overlap with the column headers.

### How we can reproduce it?

1. Open Cloud Drive in Enso GUI
2. Try to scroll up/down rapidly

- Issue is more likely to occur on **the first scroll down**, so try to refresh and repeat if it doesn't occur at first
- Issue may be more likely to occur if you have more elements in your root directory, so try to fill it with files/folders first

### Screenshots or screencasts

https://github.com/enso-org/enso/assets/641547/ec96fedd-ca15-435a-bb6c-18f24d0d6081

### Enso Version

2024.1.1-dev (2024.1.1-dev) (`a2507abcdb2c375d094dc4d4ce4e7c731cba69f1`)

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Sonoma 14.1.1 (23B81)

### Hardware you are using

M2 Macbook Air 24GB

**Comment by somebody1234** [comment]
no longer relevant as the background is a solid color now.
