### ISSUE TITLE
`cmd` + `?` Keybind Does Not Show Enso Version

### ISSUE THREAD

**Issue by indiv0** [enso-org/enso#9433]
### Discord username

npekin

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [x] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

I tried to report a bug, and the bug report form asked me to provide the Enso version by using the `cmd` + `?` keybind.

![image](https://github.com/enso-org/enso/assets/641547/cd55a100-fe24-4468-bca7-9ac250afad89)

Using that keybind does not show the Enso version, instead it opens some kind of help search bar.

### Expected behaviour

Enso version should be displayed when the `cmd` + `?` keybind is pressed

### How we can reproduce it?

1. Open standalone Enso GUI
2. Press `cmd` + `?` (on macOS)
3. Observe the lack of version displayed

### Screenshots or screencasts

![image](https://github.com/enso-org/enso/assets/641547/f263c4bb-25ee-4e14-82b3-f468dc2882da)

### Enso Version

It's literally unknowable 😱😱😱 (just kidding it's `a2507abcdb2c375d094dc4d4ce4e7c731cba69f1`)

### Browser or standalone distribution

Standalone distribution (cloud project)

### Browser Version or standalone distribution

standalone

### Operating System

MacOS

### Operating System Version

Sonoma 14.1.1 (23B81)

### Hardware you are using

M2 Macbook Air 24GB

**Comment by AdRiley** [comment]
We should also add a menu option under the ... menu to get this

**Comment by farmaazon** [comment]
Refinement note:
1. Use the ref/branch/tag name on which it was built, from environment variable. Vite should put the value to some global.
2. Shortcut should work both in GUI and dashboard
3. Important: the version name should be copyable, or better: with "copy" button.
4. Also, we could put UserAgent there.
5. You should not have to press shift, so effectively it is cmd+/
6. Rather the dashboard task, as we want this shortcut to work globally.

**Comment by somebody1234** [comment]
note re:
> You should not have to press shift, so effectively it is cmd+/

in fact we *can't* use ctrl+shift+?, because (as mentioned in the original post) it is a dedicated shortcut on macos to bring up the search tool to search through the application menus.
