### ISSUE TITLE
Drop `executionContext/recompute` call on startup

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#9448]
On startup GUI sends
- `executionContext/push`
- `executionContext/recompute`

The latter is redundant if the former has just been sent and it would, unnecessarily, trigger execution interruption (once #9278 implements it). In the current setup it's not even better - it triggers a second execution once the first one (as triggered by `push`) finished.

**Comment by farmaazon** [comment]
We should remove https://github.com/enso-org/enso/blob/6c2b2383d34e29c5ce58634762172765ee1b30a7/app/gui2/src/stores/project/index.ts#L191 and see if something breaks.

**Comment by farmaazon** [comment]
I'm not sure when it was fixed, but there's no `recompute` call anymore.
