### ISSUE TITLE
`NaN` when default argument of a function uses `self`

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#9449]
Let's change the definition of `up_to` from
```
Integer.up_to self n:Integer include_end:Boolean=False step:Integer=1
...
```
to
```
Integer.up_to self n:Integer=self include_end:Boolean=False step:Integer=1
```
Engine happily accepts `54321.up_to` while GUI produces:
![Screenshot from 2024-03-15 12-43-02](https://github.com/enso-org/enso/assets/292128/9068c404-91b9-46e1-97e2-f07251c01acb)

**Comment by farmaazon** [comment]
A bit of "missing feature" - we should guard numeric input from non-numeric default values.

There is more general problem of making distinction between "non-set argument with some default" from "set argument" - still to be designed.

**Comment by farmaazon** [comment]
Refinement notes:
1. If the default value is non-numeric, the numeric input should be empty with a dimmed placeholder showing the default value "expression" (`self` in this case).

**Comment by farmaazon** [comment]
#10168 was merged with this task; make sure that we work properly also when there's no default.
