### ISSUE TITLE
Blank screen when opening IDE

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#9455]
### Discord username

farmaazon

### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

When opening IDE after closing with opened project, I see the blank screen instead of the project:

![image](https://github.com/enso-org/enso/assets/3919101/a1ccbf2f-5dc2-456e-85e2-2c499bd228f7)

I must go back to project list: and indeed no project is opened there:

![image](https://github.com/enso-org/enso/assets/3919101/e08ac910-d3b5-4636-bcd7-c02a8c543588)

### Expected behaviour

The project will be opened (as before), or at least I'll see the project list instead of a blank screen.

### Enso Version

e1893b65af1774bacd4b862cff11d28886bb81c2 - almost 2024.1.1-nightly.2024.3.18

### Browser or standalone distribution

Standalone distribution (local project)

### Browser Version or standalone distribution

standalone

### Operating System

Linux

### Operating System Version

Garuda

**Comment by farmaazon** [comment]
@somebody1234 It looks like dashboard regression, doesn't it?

**Comment by somebody1234** [comment]
seems like it... will investigate soonish
