### ISSUE TITLE
Report warning for an insufficient warmup in a benchmark

### ISSUE THREAD

**Issue by Akirathan** [enso-org/enso#9474]
In all of our benchmarks, we try to measure the *peak* performance. That is, the performance of a program once all the dynamic compilation is finished and stable. We assume that during the *warmup* phase of a benchmark, all the dynamic optimizations and compilations are finished and thus, during the *measurement* phase of a benchmark, no more dynamic compilation happens. All our benchmarks are *micro* benchmarks and so, we don't want to measure the performance of the dynamic compiler. If the warmup is not sufficient, and some dynamic compilation creeps into the measurement, it has negative impact on the stability of the results. The *standard deviation* for benchmarks with insufficient warmup tends to be high, and thus, the results of such benchmarks are less reliable.

We can ensure that no dynamic compilation happens during the measurement phase by dumping `--engine.CompilationDetails` logs and ensuring that no `opt` or `deopt` happens in measurement. So the idea is to start the benchmark with `env JAVA_OPTS=-Dpolyglot.engine.CompilationDetails=true`, gather these logs (along with their timestamps), and make sure that there are no logs during the measurement phase.

**Comment by JaroslavTulach** [comment]
Kind of implemented by #10574
