### ISSUE TITLE
Error when try to compile and run Language Server

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#949]
#### Summary
The command we used usually for testing integration with Language Server does not work

#### Expected Result

LS process runs as before

#### Actual Result

```
[error] Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: Provider org.enso.interpreter.dsl.MethodProcessor not found
[warn] There may be incompatibilities among your library dependencies; run 'evicted' to see detailed eviction warnings.
*** Flatbuffers code generation generated 14 files in project language-server
[info] Compiling 22 Scala sources to /home/adam-praca/dev/enso/engine/language-server/target/scala-2.13/classes ...
[info] Compiling 8 Scala sources to /home/adam-praca/dev/enso/engine/language-server/target/scala-2.13/classes ...
[info] Compiling 1 Scala source to /home/adam-praca/dev/enso/engine/runner/target/scala-2.13/classes ...
[error] (interpreter-dsl / Compile / compileIncremental) javac returned non-zero exit code
[error] Total time: 42 s, completed Jun 29, 2020 12:35:27 PM
```

#### Version

The current master `8ecc786be6975b09271231d692aacd53d19618f2`
The command works fine in the previous commit f0551f7693da69ac955f36b3d6f08c7fb2dc069f

**Comment by farmaazon** [comment]
Strangely, I don't reproduce it anymore on `c3a0d249b120f1e7d3cd1a750fd3c66e645e3518`, so if you also don't, this issue can be closed.

**Comment by kustosz** [comment]
@farmaazon you may still encounter it. In such a case, run `interpreter-dsl/clean` in sbt. It's an incremental compilation issue.

**Comment by 4e6** [comment]
Can not reproduce on current 728fe2e6ed26f5344e19a695bb8a63a47b96f5f3
