### ISSUE TITLE
Make execution multithreaded to allow for faster visualization responses

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#9529]
Follow up on https://github.com/enso-org/enso/issues/9237 which reached the limits of what is currently capable.
Blocked by #9473.

**Comment by hubertp** [comment]
Investigate [safepoints](https://github.com/oracle/graal/blob/master/truffle/docs/Safepoints.md) as a way to interrupt

**Comment by JaroslavTulach** [comment]
> Follow up on #9237 which reached the limits of what is currently capable. Blocked by #9473.

Both #9237 and #9473 are integrated. What are the next ideas to investigate and explore?

**Comment by hubertp** [comment]
Created #9736 as this ticket went a different direction than I initially intended.
