### ISSUE TITLE
Design the launcher

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#954]
### Summary

To start working on the launcher, we need to document its requirements and design and split the whole work into smaller tasks.

### Value

We have a reference of what the launcher is supposed to be like. We can plan the work on particular tasks needed to implement it.

### Specification

The launcher should satisfy the following requirements:
- Use enso version based on the current project or a default version outside of projects
  - It has to check if it is within a project and be able to read package.yaml
- Use the local per-project configuration and global user config.
- Automatically manage the GraalVM versions to make sure each version of enso is run under the correct JVM
  - *but* also allow an override to use the system JVM (but only if the system JVM is a GraalVM)
- Should be a (preferably small) native binary (using NativeImage), dependencies (enso distribution, GraalVM) should be downloaded on demand.
  - If possible, the binary should be statically linked.
- Should be distributed on the CI as a zip within an 'empty' enso distribution structure.
  - The native binary should be built on CI.
  - For now it should be distributed along enso on its CI (in the same repo).
  - The launcher binary will be placed inside the `bin` directory of enso distribution structure (conforming to the release document)
  - Other directories of enso distribution structure will be empty and will be populated when the launcher downloads the components.
  - The root of enso distribution structure should contain a README explaining the directory structure and usage.
- Cannot use symlinks (because of Windows support (on Windows symlinks by default require admin privileges))
- It will be used to launch the REPL, run project files or enso scripts outside of a project and to launch the language server.
  - It should pass the arguments further to the launched component.
  - It should be able to run the REPL in the default version or in a specific project (inheriting project's enso version).
  - But it should have some understanding of the passed arguments to determine which project it should look at to check its enso version and other config.
- It should automatically download enso versions required by project configuration if it is not specified.
  - New versions should be checked at GitHub releases and downloaded from there.
  - New versions of Graal releases may be downloaded for a custom repository controlled by enso, to make sure the launcher doesn't break if Graal moved their distribution to a different place.
  - It should show a progress bar when downloading the new version.
- It should allow to manually install and uninstall old versions of enso and automatically remove GraalVM versions that are not used by any version of enso anymore.
- It should provide utility commands for managing the global configuration, for example
  - `enso default 2.0`
  - `enso list`
- Project configuration should be able to specify version bounds. At first just `==` but at some point in the future also `>=` and `<`.
  - Unless specified by an exact version match, a release that is marked as broken must be ignored by the launcher and not downloaded.
- Project configuration should be able to specify the minimum version of the launcher. The launcher should use this to detect that it is out-of-date and print a message that it has to be updated.
  - Or later, the launcher should be able to update itself.
  - Updates of the launcher may be based on GitHub releases, but a fallback upgrade scheme based on enso.org domain should be implemented, so that the launcher can be upgraded safely even if the distribution scheme is changed.
- New enso releases may specify the minimum version of the launcher.
  - It should print a message that enso versions newer than X cannot be used without updating the launcher.
  - There should be a mechanism in versioning enso that allows the launcher to detect these circumstances.
- The launcher should be updated without breaking changes (old versions of the launcher should at least be able to update themselves or print information that a manual update is required (worst-case scenario)).

### Acceptance Criteria & Test Cases

- [ ] The launcher design satisfies the above requirements.
- [ ] The launcher design has been established and written down concretely.
- [ ] The epic should be updated with smaller tasks leading to the launcher implementation.

**Comment by radeusgd** [comment]
As the launcher has to be a native binary, the initial idea was to use Graal's Native Image to build the launcher which will allow us to write it using the same technologies as other components.

The native binary cannot be fully statically linked on Windows and Mac given system restrictons, but when asked on Slack, the Graal team response was that the dependencies of the Java code are automatically included in the binary.
This suggests that only the system libraries are dynamically linked, which if I understand correctly is not an issue on Windows and Mac as these are rather portable.

As for Linux, it is possible to link statically, but also a solution for `distroless` containers is prepared which should allow to create portable binaries (see: https://github.com/oracle/graal/issues/2589).

So I understand that this satisfies our requirements of portability and we can proceed with trying to use Native Image for this task, is that correct? @iamrecursion @kustosz

**Comment by iamrecursion** [comment]
We'd want fully statically-linked binaries on Linux. We can't guarantee existence of `glibc` on all platforms.
