### ISSUE TITLE
GeoMap capturing all mouse interactions.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#9542]
Once you start dragging a GeoMap in GUI2 it is impossible to stop!

https://github.com/enso-org/enso/assets/4699705/939c3f46-c584-473b-9bb7-50ca787b5f62

To reproduce:
- Open the Geospatial example
- Click on the first map, zoom out to find some points.
- It is then impossible to deactivate moving the map

**Comment by farmaazon** [comment]
Merging with [#9780](https://github.com/enso-org/enso/issues/9780)
