### ISSUE TITLE
Use `TypeOfNode` instead of `TypesLibrary` in `InvokeConversionNode`

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#9547]
This would enable this to succeed:

```
from Standard.Base import all

main =
    huge_a = Decimal.new "3.4E320"
    huge_a_int = Integer.from huge_a

    (huge_a == huge_a_int)
```

See [discussion](https://github.com/enso-org/enso/pull/9462#discussion_r1533268318) in #8982.

**Comment by JaroslavTulach** [comment]
@GregoryTravis I've just added my fix https://github.com/enso-org/enso/pull/9462/commits/850816bcb6b0f88f66d848a4bc15e7b29773cd36 to #9462. Should my fix cause any problems, feel free to remove the commit from your PR.

**Comment by JaroslavTulach** [comment]
#9462 has been integrated.
