### ISSUE TITLE
GUI project does not receive suggestion database.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#9558]
Very often, when I open a project, GUI does not receive suggestion database. Sometimes I see only local variables.

![image](https://github.com/enso-org/enso/assets/3919101/d353b0bb-d493-49cd-be6a-4d157988daa1)

The logs from today, right after opening a project which has not received any suggestion entry (above screenshot):

[enso-project-manager-2024-03-27.0.log](https://github.com/enso-org/enso/files/14771097/enso-project-manager-2024-03-27.0.log)

**Comment by JaroslavTulach** [comment]
I am facing these issues often. Even so often that I wasn't able to do a bookclub for last two weeks.

**Comment by hubertp** [comment]
I got it today as well. Looks like while `DeserializeLibrarySuggestionsCmd` is run, the `DeserializeLibrarySuggestionsJob` background job that it submits is never triggered. Will investigate.

**Comment by hubertp** [comment]
Potentially a regression introduced in #9142

**Comment by hubertp** [comment]
[enso-no-suggestions-db.log](https://github.com/enso-org/enso/files/14872147/enso-no-suggestions-db.log)
Logs from my execution. Clearing of suggestions DB is never triggered.

**Comment by hubertp** [comment]
As debugged with @4e6, `InvalidateModulesIndexCommand` takes too long to complete (requires write compilation lock) and its handler timeouts and never sends a message to clear suggestions' DB.
