### ISSUE TITLE
The project with its old name still exists after it's renamed

### ISSUE THREAD

**Issue by notdanilo** [enso-org/enso#959]
### General Summary
When renaming a project, another copy with the old project name still exists.

### Steps to Reproduce
1. Launch IDE without passing the `--project` argument, which will open a newly created `Untitled` project printing a "Hello, World" message.
2. Apply any change.
3. Rename the project to `NewProjectName`, for instance.
4. Save it (ctrl+s).
5. Close IDE.
6. Verify if the project was renamed to the new name by opening it by passing `--project NewProjectName` argument to IDE.
7. Close IDE agan.
7. Relaunch IDE without passing `--project` again, so it opens another newly created `Untitled` project printing a "Hell, World" message.
8. Here is the error: The `Untitled` project has the same content of the renamed project.

### Expected Result
The old "Untitled" project should be removed once it's renamed so IDE can verify that it doesn't exist and create a new one.
Please check the process defined in https://github.com/enso-org/ide/issues/584 for reference.

### Actual Result
![project-renaming](https://user-images.githubusercontent.com/1069140/86308062-ab5f9500-bbee-11ea-9bfa-ce20d482261c.gif)

### Enso Version
```
Enso Compiler and Runtime
Version:    0.0.1
Built with: scala-2.13.3 for GraalVM 20.1.0
Built from: main* @ c3a0d249b120f1e7d3cd1a750fd3c66e645e3518
Running on: OpenJDK 64-Bit Server VM, GraalVM Community, JDK 11.0.7+10-jvmci-20.1-b02
            Linux 5.4.0-39-generic (amd64)
```

**Comment by wdanilo** [comment]
nice wallpaper!
