### ISSUE TITLE
10s waiting for suggestions to be sent to the IDE

### ISSUE THREAD

**Issue by JaroslavTulach** [enso-org/enso#9650]
Here is a video of initialization of a simple project with two tables and one `join`:

[10sOfWaiting.mp4](https://github.com/enso-org/enso/assets/26887752/e7c49565-7382-4abd-b8dc-60a302c5816b)

The initialization & computation of visualizations is quick. It happens in the _first two seconds_ of the video. That's not the end of initializations (and the video, _wait and watch_!) - IDE also needs suggestions and it takes another **10s** to transfer the suggestions - only then the node arguments get proper widgets and the color of nodes changes to a final (brown) state.

![sampler output](https://github.com/enso-org/enso/assets/26887752/8ff20eb7-540c-455b-a877-8e8b38216628)

According to the sample from VisualVM those 10s are spend in `searcher.db-1` thread.

**Comment by JaroslavTulach** [comment]
The code of my `Main.enso` file is:
```ruby
from Standard.Base import all
from Standard.Table import all
from Standard.Database import all
from Standard.AWS import all
import Standard.Visualization

main =
    operator1 = Table.new [['a', [1, 2]], ["b", [11, 22]], ["e", [15, 25]]]
    operator72433 = Table.new [['c', [33, 32]], ["b", [11, 22]], ["e", [25, 35]]]
    operator88051 = operator1.join operator72433
```

**Comment by hubertp** [comment]
Just a side-note. Deserialization of suggestions is a non-issue here. It's almost instantaneous. It's the insertion to DB which is taking a while.
