### ISSUE TITLE
Make it easier to click the output port to add a new component

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9701]
- Update output port to look like latest Figma design:

![Image](https://github.com/enso-org/enso/assets/1720119/632e6302-2e9e-41e5-a6cc-171921ffd9b2)

- Make the output port appear with the drag halo.
- Make the click zone for the output port be the port itself and 16px below it (This probably means there is no drag zone below the component.

Question - Could we change the mouse cursor when we are in the output port click zone?

**Comment by farmaazon** [comment]
~~Refinement notes:~~
~~* For the beginning, let's add some "border highlight" on hover, indicating that you can click on it.~~

**Comment by farmaazon** [comment]
Refinement notes:
* The connections should start "under the node" and go under the port (if visible)
* There is a variable defining distance between node and output port. Just change it and see if anything looks bad.
