### ISSUE TITLE
Make it easier to resize the visualisation window

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9702]
Visualizations should have resize areas defined as presented below:

![Image](https://github.com/enso-org/enso/assets/1720119/98121085-be45-40ce-8c15-78c9cea328b7)

- With the 1:1 zoom level, these areas should be 16px wide inside of visualization and should span to 3px wide outside of the visualisation.
- Ideally there should be a debug-switch that allows for runtime changing of the 16px and 3px to allow for testing which feels more correct/natural.

**Comment by farmaazon** [comment]
Refinement notes:
* The configuration of area sizes could be done by editing top-level CSS variables.
* The different scaling of draggable edges will be in a separate ticket.
