### ISSUE TITLE
Standardise the logic for positioning a newly added connected component

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9703]
Currently using the + button on a component or pressing Enter with a component selected has different logic for where the newly added component is placed.

- They should both use the same code to position the new component.
- Components shouldn't be placed on top of each other. So the Enter key logic is the better one right now. (but not sure how this works with longer components)

**Comment by kazcw** [comment]
I'll fix this as part of a node-creation refactor I started while working on #9456
