### ISSUE TITLE
Switching focus between Text Input widgets by Tab key discards changes

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#9711]
As shown on the video:

https://github.com/enso-org/enso/assets/1436948/d499bf87-e0cc-4b67-b859-4f3df1ac065b

Whenever I use Tab (or Shift+Tab) to switch between text inputs, the edits I did on these inputs **are discarded**.

The edits are saved if I press Enter first and only afterwards use Tab.

### Expected behaviour

I think that the edits should be submitted after just pressing Tab.

**Comment by Frizi** [comment]
Currently tabbing away and clicking away is treated as the same interaction (defocus). We probably want to keep it that way. We could make defocus accept the changes, and pressing escape discarding changes.
