### ISSUE TITLE
Propagate dataflow errors that are added to a `Vector.Builder` using `.append`

### ISSUE THREAD

**Issue by GregoryTravis** [enso-org/enso#9733]
Currently, attempting to add an uncaught dataflow error to a `Vector.Builder` results in nothing being added, and the error is not propagated. It should be detected and propagated by `Builder.to_vector`.

The same logic should be applied to `.set` and `.append_vector_range`.

**Comment by JaroslavTulach** [comment]
With #9725 and while in `Vector.build builder->` callback one could throw a `Panic` on `Error` being `append`ed, catch it in the caller of the callback and turn it back to `Error` - e.g. we could interrupt the addition sequence immediately when we know the result is going to be an error.
