### ISSUE TITLE
Report Warning in the CLI Execution

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#9749]
Currently, if you run a script in the CLI any warnings produced will be swallowed silently.

It would be good if any warning that occurs in the `main` method variables are sent to the logging system so can be seen by the user and captured into Elastic.

**Comment by JaroslavTulach** [comment]
With #9773 I can do [GraalVM Insight](https://www.graalvm.org/jdk21/tools/graalvm-insight/) experiment...

#### Define Insight Script in JavaScript

Create a file `enso_insight.js` with following content:
```js
let mod = Polyglot.eval("enso", `
from Standard.Base import Warning, Meta

h o = Warning.has_warnings o
w o = Warning.get_all o . at 0 . to_text
t o = o.to_text
`);
let h = mod.eval_expression("h")
let w = mod.eval_expression("w")
let t = mod.eval_expression("t")

function detect_warnings_among_local_variables(ctx, frame) {
  print(`Detecting warnings at the end of ${ctx.name}`);
  for (let n in frame) {
    let o = frame[n];
    if (h(o)) {
      print(`value of ${n} is ${t(o)} has warning ${w(o)}`);
    }
  }
  insight.off('return', detect_warnings_among_local_variables)
}

insight.on('return', detect_warnings_among_local_variables, {
  roots: true,
  rootNameFilter : ".*main"
});
```
it contains a mixture of Enso and JavaScript code. The JavaScript part _"attaches itself"_ to end of execution of any method with a name that matches `.*main` regexp. It iterates over all _local variables_ in the `frame`, checks if they have a `Warning` attached and if so, it prints it out.

#### Run any Script with Insight

Create an Enso file with `main` method. Execute it as:
```bash
JAVA_OPTS=-Dpolyglot.insight=enso_insight.js ./built-distribution/enso-engine-*/enso-*/bin/enso  --run Main.enso
Detecting warnings at the end of local.Main::local.Main::main
value of operator32735 is /tmp/temp_file_ensodryrun6824262491422756151.xlsx has warning Warning Only a dry run has occurred, with data written to a temporary file.  Press the Record Once button ❙⬤❙ to write the actual file.
```
the `main` method is executed and then all its local variables are scanned to check if they contain a warning. If so, the warning is printed. Similar execution can be used in batch executions.

**Comment by JaroslavTulach** [comment]
One of the problems of the [GraalVM Insight](https://www.graalvm.org/jdk21/tools/graalvm-insight/) is the need to mix Enso and JavaScript. One way to avoid that is to make sure `Warning` can be recognized via a polyglot boundary - e.g. it exposes itself via the `InteropLibrary` in a _recognizable way_.

> ```js
> let mod = Polyglot.eval("enso", `
> from Standard.Base import Warning, Meta
> 
> h o = Warning.has_warnings o
> w o = Warning.get_all o . at 0 . to_text
> t o = o.to_text
> `);
> let h = mod.eval_expression("h")
> let w = mod.eval_expression("w")
> let t = mod.eval_expression("t")

That could be done if we pretended that `WithWarnings` is actually an `InteropLibrary.isException`...
- #9840 - the PR to verify what happens...

**Comment by JaroslavTulach** [comment]
The [AtTheEndOfFirstMethod code](https://github.com/enso-org/enso/pull/10767/files#diff-33b8b63d241be8f81b6c755a27c49a23d627b1e9845a93a296a75c45ae59e67dR283) gives us alternative way (other than GraalVM Insight) to stop at the end of main method execution.

There already is [:list command](https://github.com/enso-org/enso/blob/31e589e362ac690896b961be38f783219a3b68b5/engine/runner/src/main/scala/org/enso/runner/Repl.scala#L171) and it can be used to _dump local variables and their warnings_.

CCing @radeusgd

**Comment by jdunkerley** [comment]
Can we also return a non-zero exit code if errors occur in main.

**Comment by JaroslavTulach** [comment]
The current plan:

> The [AtTheEndOfFirstMethod code](https://github.com/enso-org/enso/pull/10767/files#diff-33b8b63d241be8f81b6c755a27c49a23d627b1e9845a93a296a75c45ae59e67dR283) gives us alternative way (other than GraalVM Insight) to stop at the end of main method execution.
> 
> There already is [:list command](https://github.com/enso-org/enso/blob/31e589e362ac690896b961be38f783219a3b68b5/engine/runner/src/main/scala/org/enso/runner/Repl.scala#L171) and it can be used to _dump local variables and their warnings_.

- expand the instrument to do [AtTheEndOfFirstMethod code](https://github.com/enso-org/enso/pull/10767/files#diff-33b8b63d241be8f81b6c755a27c49a23d627b1e9845a93a296a75c45ae59e67dR283)
- expand the [:list command](https://github.com/enso-org/enso/blob/31e589e362ac690896b961be38f783219a3b68b5/engine/runner/src/main/scala/org/enso/runner/Repl.scala#L171) to print warnings and errors
- by default on and perform `:list+warnings+errors-regular` (e.g. dump error like values) 
- non-zero when there is any error
- zero exit when only warnings present
