### ISSUE TITLE
Autoscoping should not escape `True` and `False`.

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#9765]
The tag values produced should not auto-scope `Boolean.True`  and `Boolean.False` they should be entered just as `True` and `False`.

Currently it results in an error:
![image](https://github.com/enso-org/enso/assets/4699705/7777652e-be88-456a-ad16-3e6cd123edef)

**Comment by JaroslavTulach** [comment]
This program seems to fail with similar `ClassCastException`:
```ruby
from Standard.Base import all


bool b:Boolean = b

main =
    m = bool ..False
    m.not
```

**Comment by JaroslavTulach** [comment]
- #9767 - fixes the `ClassCastException`

> The tag values produced should not auto-scope `Boolean.True` and `Boolean.False` they should be entered just as `True` and `False`.

I'd be great if `True` and `False` didn't have to be **treated especially**. Would following rule work?
- If the atoms are exported from library's `Main`, don't autoscope them
