### ISSUE TITLE
Z-Ordering of drop down menu and Viz menu is incorrect

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9783]
![image](https://github.com/enso-org/enso/assets/1720119/db3d8d19-994c-4dbe-ac7c-c5bcbf52ec31)

The drop down menu should display above the viz menu.

The Column separators should render below the drop down menu

**Comment by kazcw** [comment]
The solution in #9848 conflicts with #9842 until #9830 is implemented. Reverting it until then; details in #9830.
