### ISSUE TITLE
Add Documentation Pane

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9786]
- Add new documentation pane which appears on the right hand side of the graph editor.
- It will render the doc level comment from the main function in the .enso file
- ~~Rendering should be consistent with the doc rendering inside the Component Browser~~
- It should support markdown and have a WYSIWYG editor (lexical library).
- For now pane can be opened with an option on the ... menu and a keyboard shortcut.

![image](https://github.com/enso-org/enso/assets/1720119/a56ea630-bcb2-4532-bfc8-5a4fc5899014)

**Comment by farmaazon** [comment]
In the first version, just store Markdown to the doc comment of main function, and read this doc comment as Markdown - we don't do any translation from "Enso doc format" to markdown for now.

**Comment by farmaazon** [comment]
After brief research I think milkdown https://github.com/Milkdown/milkdown seems promising.
Another candidate is https://github.com/nhn/tui.editor

<blockquote><img src="https://repository-images.githubusercontent.com/345922282/584f87eb-2da3-4f23-ab74-0894f14c3bf8" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/Milkdown/milkdown">GitHub - Milkdown/milkdown: 🍼 Plugin driven WYSIWYG  markdown editor framework.</a></strong></div><div>🍼 Plugin driven WYSIWYG  markdown editor framework. - Milkdown/milkdown</div></blockquote>
<blockquote><img src="https://opengraph.githubassets.com/07dab1b9ed1226dbaf91a74867c2bdf619ce227619d7021fd94f6867f02c3df4/nhn/tui.editor" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/nhn/tui.editor">GitHub - nhn/tui.editor: 🍞📝 Markdown WYSIWYG Editor. GFM Standard + Chart & UML Extensible.</a></strong></div><div>🍞📝 Markdown WYSIWYG Editor. GFM Standard + Chart & UML Extensible. - nhn/tui.editor</div></blockquote>
