### ISSUE TITLE
Widget for renaming local functions: renaming group of components.

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9790]
The local function calls should have a special widget in place of their names, allowing renaming it.

After renaming, we call refactor engine. The name in the node should be updated immediately.

**Comment by farmaazon** [comment]
* The "local" function means: function/method defined in currently opened project. Let's assume engine `refactor` endpoint will manage it. If not, we will add exceptions later.
* Only the name itself should be editable (not `Main.`).
* The change in name should be immediate, but only on visual layer; it should be commited to code by engine (as a result of refactor endpoint).
