### ISSUE TITLE
Automate Release Process on CI

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#980]
### Summary

Add a workflow on the CI that is triggered by creating a tag which builds all components, creates a draft release and adds their artifacts to it.

### Value

We have an automated and reproducible workflow that creates releases in a format known by the launcher.
We can easily create a release and be assured that the launcher will be able to find and download it.

### Specification
This workflow should:

- [x] Trigger only on tags ~pushed to `release/*` branches~ that match `enso-*.*.*`.
- [x] Create a _draft_ release.

As part of this, the following should happen:

- [x] Enso components artifacts (runtime.jar, runner, project-manager) are added to the release.
- [x] Manifest containing metadata as described in the [release policy](https://github.com/enso-org/enso/blob/main/docs/distribution/release-policy.md) is added.
- [x] Launcher is built to a native binary and added for Linux, Mac and Windows.
- [x] Launcher binaries are packaged in such a way, that they can be executed on all platforms without additional actions (i.e. distributions for Unix preserve the executable bit).

### Acceptance Criteria & Test Cases

- [x] A CI workflow is added which satisfies the above specification.
- [ ] The workflow has been run to create a temporary test release to see that it works correctly.

**Comment by radeusgd** [comment]
Currently it seems quite infeasible to trigger on tags that are assigned to a `release/*` branch, because it is hard to check and anyway it seems that developers can create a tag on a commit in the `release/*` chain even without write permissions to `release/*`, because that commit can also exist in other branches.

**Comment by iamrecursion** [comment]
To be clear, it should match `enso-semverstring` not `v...`.
