### ISSUE TITLE
Minor Bugs in Dashboard

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#9817]
When running locally:
- Can't rename a local folder.
- Seeing .git folder (and other hidden things).
- Opening sample with another open project makes it appear both open.

**Comment by somebody1234** [comment]
> Seeing .git folder (and other hidden things).

i assume this will need the `hidden` attribute to be exposed: <https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#isHidden-java.nio.file.Path->

i assume this is something that will need to be implemented on the PM's side by @4e6?

<blockquote><div><strong><a href="https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#isHidden-java.nio.file.Path-">Files (Java Platform SE 8 )</a></strong></div></blockquote>
