### ISSUE TITLE
Cannot pass through "Set username" window.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#9818]
On the latest package, I cannot get through the initial "set username" window.

![image](https://github.com/enso-org/enso/assets/3919101/03dcba3d-de73-403b-b370-6fb24d774f37)

**Comment by farmaazon** [comment]
Adding `-authentication=false` does not help

**Comment by farmaazon** [comment]
Nor using older package (2024.4.15)

**Comment by farmaazon** [comment]
The only way I could work now is to clear cache (to logout) and continue without logging in. Once I log in, I'm stuck with above screen forever.

**Comment by jdunkerley** [comment]
Caused by IAM permission error knocking out the /users/me endpoint.
