### ISSUE TITLE
Wrong capability/acquire description in docs

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#982]
### General Summary
The parameters of capability.acquire does not work as described in https://dev.enso.org/docs/enso/language-server/protocol-language-server.html#capabilityacquire 

### Steps to Reproduce

send request:
```{"jsonrpc":"2.0","id":2,"method":"capability/acquire","params":{"registration":{"method":"search/receivesSuggestionsDatabaseUpdates","registerOptions":{}}}}```

### Expected Result
The request works.

### Actual Result
The request fails with "Invalid Params" response. However, the following message will work:
```{"jsonrpc":"2.0","id":2,"method":"capability/acquire","params":{"method":"search/receivesSuggestionsDatabaseUpdates","registerOptions":{}}}```
however it does not reflect the description in docs.

### Enso Version
built on commit 6ba038c800485910a925a9328119f7446000cf57

**Comment by iamrecursion** [comment]
@lolczak We need to decide what the appropriate behaviour for this is, and either unify the docs with the implementation, or the implementation with the docs.

**Comment by lolczak** [comment]
@iamrecursion It is the API designed and implemented by Dmitry @4e6

**Comment by iamrecursion** [comment]
@4e6 Please take a look then.
