### ISSUE TITLE
Make grouped components take the icon from the group's comment

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9831]
- Make grouped components take the icon from the group's comment
- Default new groups to ## ICON group

**Comment by farmaazon** [comment]
The first point should already work, but sometimes we miss the local entries in suggestion db (or they are not updated). Check the not working scenarios and file a bug to the engine as part of this task.

**Comment by kazcw** [comment]
>    Make grouped components take the icon from the group's comment

Seems to have been fixed with #9962. 

>    Default new groups to ## ICON group

Implemented in #10020
