### ISSUE TITLE
`npm run dev` not working

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#9847]
### What type of issue is this?

Permanent – Occurring repeatably

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [X] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

After #9528, `npm run dev` isn't working. The page is blank, and there is an error "504 (Outdated Optimize Dep)" in the console. The error occurs even in a clean build of the repo.

### Expected behaviour

The dev server should be usable

### Screenshots or screencasts

<img width="662" alt="Screenshot 2024-05-02 at 09 06 19" src="https://github.com/enso-org/enso/assets/1047859/8a50b3bf-b967-4a49-8ffc-9e7eaa5cea56">

### Enso Version

develop after 5995a009

### Browser or standalone distribution

Chromium

### Browser Version or standalone distribution

chromium

### Operating System

MacOS

**Comment by kazcw** [comment]
I have also tried the polyglot ydoc server mode (described in #9528), with the same result

**Comment by kazcw** [comment]
It works now. Since a clean build didn't help but the issue turned out to be transient anyway, I think it must have been caused by a zombie process.

**Comment by vitvakatu** [comment]
I’m facing the same issue now. Both clean build and reboot didn’t help.

**Comment by vitvakatu** [comment]
<img width="766" alt="image" src="https://github.com/enso-org/enso/assets/6566674/6ca4ef8f-d57e-4bc0-b9f8-390742770012">

**Comment by Frizi** [comment]
I faced this once, and running `npm run dev -- --force` once helped to clear up the issue. That causes vite to force recreate the optimized dependencies bundle instead of using one from cache.

**Comment by vitvakatu** [comment]
Emptying browser cache helped with the issue.

**Comment by kazcw** [comment]
I just encountered this on OS X while integration-testing. This worked:
```
rm -rf /System/Volumes/Data/Users/kaz/Library/Caches/ms-playwright/chromium-*
corepack pnpm i
```

**Comment by kazcw** [comment]
Still getting this a lot. More efficient workaround:
```
rm -rf /var/folders/*/*/*/playwright-*
```
