### ISSUE TITLE
Benchmark the Enso Lexer

### ISSUE THREAD

**Issue by iamrecursion** [enso-org/enso#985]
### Summary
Now that the new Enso lexer is feature-complete, we need to get some idea of its performance.

### Value
We will be able to determine the performance of the lexer and ensure that it is acceptable.

### Specification

- [x] Write a comprehensive set of benchmarks for the Rust implementation of the Enso lexer. This should include individual tests of the various primary types of token (e.g. literals, names, operators, blocks, comments), as well as comprehensive combined tests.
- [x] Write a simple benchmark comparing iteration time over characters of text in Rust.
- [x] Write the equivalent benchmarks in the scala lexer.
- [x] Work out a way to protect the lexer against performance regressions using these benchmarks.
- [x] The benchmarks must include absolute time statistics to ensure that the overall runtime is acceptable.
- [x] The benchmarks should include memory usage statistics if possible. If this is not possible, these statistics should be recorded manually and noted down.
- [x] If possible, the regression suite should perform performance-counter-based benchmarking as well. This would allow us to run the benchmarks on CI without timing issues impacting the results.
- [x] Use profiling tools on the running benchmarks to identify bottlenecks. If some are found:
  + Analyse why they occur.
  + Determine a fix if possible, and fix it in the codegen.
- [x] Document the benchmarking process, with a focus on what people need to do when changing the lexer.

### Acceptance Criteria & Test Cases

- We have a comprehensive picture of the performance of the new Enso lexer.

**Comment by wdanilo** [comment]
Regarding benchmarks, I would love to see a comparison of times of:
1. Your lexer.
2. Scala lexer (not the parser, just the generated lexer so we compare the same things).
3. Simple traversing of the string with a loop in Rust + simple comparison of each traversed letter. This, of course, will be faster than lexer but will give us picture of the most extreme case we can aim for regarding performance.
