### ISSUE TITLE
"NaN expected number" console errors

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#9860]
### What type of issue is this?

Transient – Occurring only once

### Is this issue blocking you from using Enso?

- [ ] Yes, I can't use Enso because of this issue.

### Is this a regression?

- [ ] Yes, previous version of Enso did not have this issue.

### What issue are you facing?

![Screenshot from 2024-05-03 18-12-00](https://github.com/enso-org/enso/assets/292128/9ea1afe8-db3f-4609-9229-1b360755dc87)

### Expected behaviour

No errors

### Enso Version

develop

### Browser or standalone distribution

Chrome

### Browser Version or standalone distribution

124.0.6367.91 

### Operating System

Linux

**Comment by farmaazon** [comment]
As I tested, it appears only after closing project.

**Comment by farmaazon** [comment]
Not reproducible anymore on `88eeacf78bc5461ac9d0440f21f0c531c48756cb`
