### ISSUE TITLE
Don't unnecessarily report bindings as unused variables (in IDE & REPL)

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#9883]
The repro is trivial - just declare a named binding in the REPL:
```
> abc = 123
[WARN] [2024-05-08T00:52:20+02:00] [enso.org.enso.compiler.Compiler] Internal_Repl_Module___:1:1: warning: Unused variable abc.
    1 | from Standard.Base import all
      | ^~~
>>> Nothing
```

### Expected behaviour

1. The warning should not be reported - it is expected in the REPL that the variable is not yet used.
2. Even if it is shown - the location of the error is wrong.

**Comment by JaroslavTulach** [comment]
I've heard similar complain by @jdunkerley for the IDE case. Warnings of unused `operatorXYZ` are reported and they quite useless as it is a common development practice to have unused values in the IDE.

Can we disable _unused bindings pass_ when `STRICT_ERRORS` are `false`? That would fix the IDE case. Is REPL running with strict or non-strict errors? If the latter, the change would fix also the repl mode.

**Comment by hubertp** [comment]
> That would fix the IDE case. Is REPL running with strict or non-strict errors? If the latter, the change would fix also the repl mode.

The former it seems. https://github.com/enso-org/enso/blob/develop/engine/runner/src/main/java/org/enso/runner/Main.java#L629

<blockquote><img src="https://opengraph.githubassets.com/562af4940cfa3fd180ccaa77c4a7d49fb5bf7ebc17a569e21eb5d6e8c6dd682c/enso-org/enso" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="https://github.com/enso-org/enso/blob/develop/engine/runner/src/main/java/org/enso/runner/Main.java">enso/engine/runner/src/main/java/org/enso/runner/Main.java at develop · enso-org/enso</a></strong></div><div>Hybrid visual and textual functional programming. Contribute to enso-org/enso development by creating an account on GitHub.</div></blockquote>
