### ISSUE TITLE
Update the Dashboard to Newest Design

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#9886]
- Remove the home tab icon
- Add a new `Start with a template` button to dashboard.
- Clicking this button should open the templates (old home tab) as a pop up over the asset list.
- Add a Drag and drop area to bottom to the asset list.
- **We will move to tabs at the top as a follow up ticket.**

![image](https://github.com/enso-org/enso/assets/4699705/5b674e97-0212-4f77-bf87-3c65f7fae357)

![image](https://github.com/enso-org/enso/assets/4699705/0bee2230-2387-4503-9c32-1e7f74cd0ad7)

**Comment by somebody1234** [comment]
link to design:
<https://www.figma.com/file/v8Sec6m03hz8ZExWkpIsPD/ide2-v122?type=design&node-id=15504-63814&mode=design&t=wSOOMnI983IppETn-0>
