### ISSUE TITLE
Move to the Tab layout for Dashboard

### ISSUE THREAD

**Issue by jdunkerley** [enso-org/enso#9898]
Following the work restructuring the home button, next step is to move to tab look at top

![image](https://github.com/enso-org/enso/assets/4699705/a53fa66a-68ba-4856-a674-eee482bdf285)

- The search box should be in the red area.
- The cog button should be removed and only shown within the right hand panel.

- A new button to open and close the right hand panel should be added
![image](https://github.com/enso-org/enso/assets/4699705/4bb1912d-2487-47eb-a212-96a1e3817977)

**Comment by somebody1234** [comment]
i guess the main question is, where should the chat button go?
- temporarily removed perhaps?
- in the top bar to the left of the invite button?
- somewhere else?

also minor questions about:
- what the gear icon in the right panel does
  - perhaps it's just an indicator of the current panel tab?
- what the versions control is supposed to do (specifically the arrows)
  - i assume the current "versions" UI is *fine*, but perhaps we may want to temporarily move that to a tab based layout too.
