### ISSUE TITLE
List of projects not synchronized

### ISSUE THREAD

**Issue by hubertp** [enso-org/enso#9901]
It appears that dashboard (cloud) does not synchronize the list of projects without a manual refresh.
![Screenshot from 2024-05-09 00-12-25](https://github.com/enso-org/enso/assets/292128/2837d48d-ac42-4aa5-b227-f55f1582133c)
The following screenshots illustrates:
- on the left - electron app 
- on the right - browser

Both use the same login. Enso in the browser has been started a while ago and in the meantime I've created a couple of new projects. The new ones are not reflected in the browser despite it making a number of calls to `cloud.enso.org`.

**Comment by somebody1234** [comment]
I think ideally directory update events should be sent by the server. @PabloBuchu thoughts?

**Comment by PabloBuchu** [comment]
We implemented polling to fetch updates for opened directories. Should be fixed by now
