### ISSUE TITLE
New project not centered

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9902]
When I create a new project the starting component should be centered in the window and zoomed 100%.

This is what it does today.
![image](https://github.com/enso-org/enso/assets/1720119/c31a4b35-3d3e-4321-8fe3-ff44ec1533bd)
Sometimes the starting component can be off screen

**Comment by hubertp** [comment]
I think I noticed a similar issue when debugging https://github.com/enso-org/enso/issues/9789. The page appeared blank but it wasn't really.

**Comment by farmaazon** [comment]
If there is no camera position in project, we should fit to all (after all sizes will be completed).
