### ISSUE TITLE
The multi-component menu should disappear after the group button is clicked

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9903]
The multi-component menu should disappear after the group button is clicked as once you have grouped there are no longer multiple components selected.

Actual:
![image](https://github.com/enso-org/enso/assets/1720119/e3365c2f-a939-4310-b97c-a14a99735f59)

Expected:
The multi-component menu should disappear

**Comment by farmaazon** [comment]
Interesting. Looks really like we still have those nodes selected, somehow.

**Comment by farmaazon** [comment]
There should another list of "actually selected" nodes (the current selection, with non-existing nodes filtered out) - a computed value.
There are some places in code where we already do that - unify them.
