### ISSUE TITLE
Hyperlinks in comments should be clickable

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9907]
![image](https://github.com/enso-org/enso/assets/1720119/abe65fc5-f4be-46d4-95fb-cba5bffb0627)

- Detect hyperlinks as text starting http:\\\\ or https:\\\\
- Underline the hyperlink to give user clue it is clickable
- I think copy VS code behaviour with a clickable tooltip or ctlr-click to follow

![image](https://github.com/enso-org/enso/assets/1720119/c974a4c9-739a-4b5c-b0b5-a65a06e53306)

**Comment by farmaazon** [comment]
* Use the editor we use for documentation panel to every comment box. It should handle links by itself - or we are just one plugin away.

**Comment by kazcw** [comment]
This is blocked on #9935.
