### ISSUE TITLE
Legal Review of Distribution Notices

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#992]
### Summary

Before creating official releases, we need to review that we distribute the engine and the launcher in a way that complies with licenses of dependencies that are included along the distribution.

[Licenses](https://dev.enso.org/docs/enso/distribution/licences.html) describes the current approach to gathering licences of dependencies (possibly) included in the launcher binary and creating the [`NOTICE`](https://github.com/enso-org/enso/blob/main/distribution/launcher/NOTICE) file that is attached with launcher distribution. This file should be reviewed to ensure that the way the NOTICEs and licence files are gathered does indeed comply with the used licences.

Moreover, it may be necessary to also analyse if a similar approach is required for distributions of the engine components. The difference here is that the engine is distributed as a JAR file, and some (but seemingly not all) of the libraries' licences are included inside this JAR. It should be verified if just having the licences inside a JAR is enough to satisfy the licences, or should the licences and NOTICEs be added along the distribution, just like in the case of the launcher.

### Value

We have a clear understanding of what has to be done to comply with licences of dependencies used in the engine and the launcher.
We can distribute the launcher and the engine in compliance with licences of the dependencies that are included in these distributions.

### Specification

- [ ] The `NOTICE` file should be reviewed to make sure its format is correct and satisfies the legal requirements.
- [ ] The process for gathering launcher dependnecy licensing requirements should be reviewed to make sure it satisfies the legal requirements.
- [ ] Licensing requirements for the engine components should be analysed and written down at [Engine Components](https://github.com/enso-org/enso/blob/main/docs/distribution/licences.md#engine-components).

### Acceptance Criteria & Test Cases

- We have a clear understanding of what files have to be included in the distribution to satisfy the license requirements of dependencies that are included within the distribution.
- We know how to ensure that these requirements are satisfied when adding a new dependency.

**Comment by iamrecursion** [comment]
@sylwiabr Is this something we can pass to Basia?

**Comment by iamrecursion** [comment]
Had a quick chat with the legal team. They will review and get back to us with a quote early week beginning 21st september 2020.
