### ISSUE TITLE
Documentation needs to be sanitized

### ISSUE THREAD

**Issue by vitvakatu** [enso-org/enso#9933]
Documentation of `Table.parse_to_columns` is currently rendered like this:

<img width="598" alt="Screenshot 2024-05-13 at 3 40 57 PM" src="https://github.com/enso-org/enso/assets/6566674/9b0c2e26-9bb4-4562-973b-2017f5ce787e">

The white rectangle is actually an `<input>` HTML element, because documentation includes the following sentence:

```
       If the marked groups are named, the names will be used otherwise the column
       will be named `<Input Column> <N>` where `N` is the number of the marked group.
```

All these angle brackets go to the parser output unsanitized.

**Comment by farmaazon** [comment]
We plan to switch the documentation format to Markdown. For now, let's replace `<` and `>` in the doc comments.

Or quckfix it on GUI.
