### ISSUE TITLE
Issues from today testing of product with Sylwia and Wojciech

### ISSUE THREAD

**Issue by wdanilo** [enso-org/enso#9949]
1. When opening Enso, it shows "loading to Enso", which blinks, it disappears, and then a log-in screen is shown:
https://github.com/enso-org/enso/assets/1623053/67dfec29-2c2f-4c21-9f96-c76d4227245d

2. When I remove `~/enso`, after opening Enso I see this: 
<img width="1376" alt="image" src="https://github.com/enso-org/enso/assets/1623053/8c7cb86d-fb8d-411b-97e5-3be916584d80">
and after messages disappear I see this:
<img width="1376" alt="image" src="https://github.com/enso-org/enso/assets/1623053/f3f7d955-4360-4fc1-a76f-da37f6e715f7">
And nothing more.

3. Then after switching to local drive and clicking "new project" I see this:
<img width="1376" alt="image" src="https://github.com/enso-org/enso/assets/1623053/0b1ebbfe-c9e2-45ad-8ce4-afd5f9bca175">

Then after re-opening Enso, I see this:

<img width="1376" alt="image" src="https://github.com/enso-org/enso/assets/1623053/51e8e009-34f7-4e96-920a-1ef717d197c8">

Logs:
[enso-project-manager-2024-05-14.0.log](https://github.com/enso-org/enso/files/15308756/enso-project-manager-2024-05-14.0.log)

In the end, I can't use Enso at all (no re-login or re-installation helped).

**Comment by wdanilo** [comment]
Note: this is new - I was removing these folders couple days ago (Thursday?) and it was working on older build

**Comment by 4e6** [comment]
I can reproduce it with the latest Nightly AppImage https://github.com/enso-org/enso/releases/tag/2024.1.1-nightly.2024.5.14

Even without removing the `~/enso` directory. If I open the GUI without login (`Continue without creating an account`), I see a blank screen when I open the project.

If I type `showLogs()` in the browser console, I can see a lot of errors related to the shader compilation:

![2024-05-14-151148_2560x1356_scrot](https://github.com/enso-org/enso/assets/357683/e1c2f987-b6c1-4511-bab9-795b6f8b6759)


<blockquote><img src="https://opengraph.githubassets.com/839a62d72623833a95877b954fdd6e0b75969853de4173f0650468dab81bcde1/enso-org/enso/releases/tag/2024.1.1-nightly.2024.5.14" width="48" align="right"><div><img src="https://github.githubassets.com/favicons/favicon.svg" height="14"> GitHub</div><div><strong><a href="/enso-org/enso/releases/tag/2024.1.1-nightly.2024.5.14">Release Enso 2024.1.1-nightly.2024.5.14 · enso-org/enso</a></strong></div><div>Download
Enso IDE
Enso IDE is the main product of the Enso project. The packages are stand-alone, they contain both GUI and the backend.
Download links:

Windows
Linux
macOS (Intel)
macOS (Apple si...</div></blockquote>

**Comment by kazcw** [comment]
That's a GUI1 log!

**Comment by JaroslavTulach** [comment]
Too old. Closing.
