### ISSUE TITLE
Launcher CLI Arguments Parsing

### ISSUE THREAD

**Issue by radeusgd** [enso-org/enso#995]
### Summary

At first no separate task for this was created, as it seemed like a simple thing that can be added along the way with each implemented commands. But with additional requirements it becomes a more complex problem.

### Value

We can parse the command line parameters and pass them on to the launched components in a way that is intuitive for the users.

### Specification

- The launcher should pass unknown arguments to the engine components that are launched (`run`, `repl`, `language-server`). The idea is that more arguments may be added in future versions and the launcher does not necessarily have to be aware of that. The arguments that the launcher is not aware of, have to be added after a `--` at the end of the command line.
- The path to run for the `run` subcommand should be positional arguments (i.e. `enso run some/path`).
- The parameters and flags may be placed before and after the positional arguments.
- The launcher should support plugins as described in the documentation. Running `enso plugin arguments-and-parameters` should launch `enso-plugin` (if it exists), passing `arguments-and-parameters`.
- The launcher should handle typos in a friendly way (find similarly named options and print them).
- The launcher should include plugins (the ones that it can find on the `PATH`) in the help text listing the subcommands.

### Acceptance Criteria & Test Cases

- [x] The specification above is updated to be non-contradictory.
- [ ] A CLI parser is implemented that satisfies the updated specification. The unimplemented subcommands should just print their settings and exit.

**Comment by radeusgd** [comment]
The specification, as originally defined, is contradictory.

The following points cannot be all satisfied at the same time.

> - The launcher should pass unknown arguments to the engine components that are launched (`run`, `repl`, `language-server`). The idea is that more arguments may be added in future versions and the launcher does not necessarily have to be aware of that.
> - The path to run for the `run` subcommand should be positional arguments (i.e. `enso run some/path`).
> - The parameters and flags may be placed before and after the positional arguments.

If `enso run` has to take a positional argument **and** it may be preceded by additional parameters **and** this additional parameters may be not known **and** the first positional argument (file location) has to be parsed by the launcher (it cannot be delegated to the ran component, as the path determines the version of the component to launch), we get a pattern that is impossible to parse unambiguously.

To reiterate, the launcher has to parse the first positional argument to determine the project path and thus the version of `runner` to launch.

Let's look at the command `enso run --foo bar baz`:
- should the launcher run a project located at `baz` and pass a parameter named `foo` with value `bar` to the runner
- or should it run a project located at `bar` and pass a flag `foo` and a positional argument `baz` to the runner?

This cannot be determined without further knowledge of wether `foo` is a flag or a parameter, but we can't know that if it is unknown.

Alternative solutions are:
- Enforce the positional argument for `run` to go first (and ensure other components don't need any positional arguments that have to be parsed, just parameters (for example by providing the path for the repl by a parameter `enso repl --path project/path`)).
- Turn the positional argument into a parameter, so using `enso run --path path/to/file`.
- Only allow parameters with a `=` sign, i.e. disallow `--param value` for `--param=value`.
- Allow additional unknown parameters for known components after a `--`.

**Comment by radeusgd** [comment]
After a discussion with @kustosz and @iamrecursion, we decided that we will support unknown arguments for the known components after a `--` separator.

So for now, additional arguments would go after a separator, like `enso run project/path -- additional-arguments`. When additional arguments are actually added to the runner, new launcher versions that are aware of them may support them, so users will be able to use `enso run --new-arg value project/path`, but if they use the old launcher that does not know the `new-arg`, they can still use the `enso run project/path -- --new-arg value` syntax.

**Comment by iamrecursion** [comment]
A few thoughts that I had last night. The global `enso --help` should display commands from plugins, such that if `enso ide` is available, it shows up in the list with a brief description. To this end, plugins should provide a `--describe` option that returns a short description of what the plugin does. If this option does not exist, or returns nonsense, you should default to "Please run `enso <plug> --help` for more information." or similar.
