### ISSUE TITLE
`refactor/renameSymbol` method does not update buffer of opened module.

### ISSUE THREAD

**Issue by farmaazon** [enso-org/enso#9960]
In [this branch](https://github.com/enso-org/enso/pull/9959) there is IDE with "rename local method" feature. It calls `refactor/rename` method of language server and - when `text/didChange` message arrives - it reloads file using `file/read` method.

But `file/read` method returns the old state of the file, despite the documentation which says:

> If the file is recorded as open by the language server, then the result will return the contents from the in-memory buffer rather than the file on disk.

To reproduce:

* Switch to `wip/farmaazon/rename-functions`
* Run project manager (I tested 5.15 nightly) and dev server `npm --workspace enso-gui2 run dev`
* Open project with collapsed nodes and try to edit `collapsed` name in calling node. **Note** - if you cannot edit the name, then probably the local methods haven't been loaded to suggestion db [due to some bug](https://github.com/enso-org/enso/issues/9962). Try restarting application (including PM).
* Observe the logs of dev server

First we receive "did change" message with proper diff, but then, from `file/read` we receive old file.

**Comment by farmaazon** [comment]
I've assigned `p-high` because it prevents me from finishing #9790

**Comment by 4e6** [comment]
> If the file is recorded as open by the language server, then the result will return the contents from the in-memory buffer rather than the file on disk.

Maybe it was supposed to be like that, but right now the `file/read` reads the contents from disk.

**Comment by 4e6** [comment]
There is another potential issue. The `refactor/renameSymbol` only returns changes related to the program and does not update the IdMap

**Comment by 4e6** [comment]
The fix for the `file/read` #9994 is merged. The remaining issue is with the IdMap

**Comment by farmaazon** [comment]
> The fix for the `file/read` #9994 is merged. The remaining issue is with the IdMap

Regarding IdMap; our ydocs server (after a few tweaks) handles the idmap changes if received a code-only update. Thus, the task #9790 is no longer blocked.

For me, this task may be closed - we want to remove idmaps from files anyway.

**Comment by 4e6** [comment]
Ok, closing this one
