### ISSUE TITLE
Add table display support to documentation editor

### ISSUE THREAD

**Issue by kazcw** [enso-org/enso#9970]
Initially just render tables that have been typed in the code editor in markdown. GUI style editing will be a follow on story.

The table plugin in `lexical-react` can be used as the primary reference; there is also a Vue port in `lexical-vue`, but it is out of date.

**Comment by farmaazon** [comment]
Refinement notes:
* this requires making our own markdown-table parser (we already use one for images).
* table editing is not part of this issue.

**Comment by farmaazon** [comment]
Refinement notes:
* In this task's scope, the widget is "read only", switching to just markdown on edit. Making cells editable and add/remove row/columns will be in another task.
* Worth considering using AGGrid, styled so it will look better in documentation.
