### ISSUE TITLE
Choose File doesn't work for write component

### ISSUE THREAD

**Issue by AdRiley** [enso-org/enso#9984]
Choose File doesn't work for write component if the file doesn't exist (which is common as I am about to write it)

![image](https://github.com/enso-org/enso/assets/1720119/a51cfea9-a4ec-479c-857e-a70fe0bd6c31)

**Comment by farmaazon** [comment]
Perhaps there should be some configuration from the engine, when we want to allow only existing files.

But now let's just always accept any file name.
